* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 8b377884-7d64-4fac-aec3-810546e840c2
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
d812959f-6844-4a85-83ec-0dcb5469de60.mp3
***** 转录
青少年的兴趣爱好若能及早得到培养，就能表现出某一方面的才能。老师根据学生的爱好，有意识地加以引导，就会使学生在自己爱好的活动中发展特长、增长聪明才智，进而具有发现问题、分析问题、解决问题的能力。
**** 选择
***** A
每个孩子都有自己的特长
***** B
好老师要能发现学生的问题
***** C
老师要善于帮学生解决问题
***** D
老师要根据学生的特长加以引导
**** 答案
D
*** 2
:PROPERTIES:
:ID: e3dce1f3-364b-49f1-9b10-1b4c57bdfbe2
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
76a692b0-8726-45fe-ae33-a1739647da74.mp3
***** 转录
7月份新疆出现异常高温天气，大部分地区最高气温在35摄氏度以上,一些地区的最高气温为40摄氏度以上。首府乌鲁木齐14日最高气温达到40.6摄氏度,突破近30年来最高气温历史极值,吐鲁番地区最高气温达到46.2摄氏度。
**** 选择
***** A
乌鲁木齐是新疆的首府
***** B
在新疆40人高温很普道
***** C
7月份新疆的天气反复无常
***** D
乌鲁木齐的气温高于吐鲁番
**** 答案
A
*** 3
:PROPERTIES:
:ID: 961df13e-762f-4400-96ae-edee33cefe61
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
d59fbbd3-47bf-4fa4-b855-02ea3a5958e8.mp3
***** 转录
随着社会的发展，新事物、新概念不断出现，这些都会向交际提出新的要求，我们翻阅解放前的书报杂志，就会感到有些词语很陌生，有些格式很不习惯。社会的发展变迁必然会在语言的词汇里留下印记。
**** 选择
***** A
每个人都向交际提出新要求
***** B
历史会记录社会的发展变化
***** C
语言会随着社会的变化而变化
***** D
书面语和口语有许多不同之处
**** 答案
C
*** 4
:PROPERTIES:
:ID: a2a7e2b7-35a5-4183-a656-54d7ddac5ebb
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fb8c1140-5db6-47e3-817e-a7c22b317c12.mp3
***** 转录
今年读到了新近出版的“经济新观察”丛书中的林行止系列和熊秉元系列。林行止读书甚广，读他的文章犹如进入阿里巴巴的山洞，美不胜收。熊秉元善于从一些日常小事中总结出经济学精神，读来有滋有味。
**** 选择
***** A
林行止、熊秉元都是小说作家
***** B
林行止的书介绍了很多旅游景点
***** C
熊秉元的书内容常涉及餐饮美显
***** D
“经济新观察“是一套经济学书籍
**** 答案
D
*** 5
:PROPERTIES:
:ID: 8b665d1c-651e-4ccb-9f37-a6a5e30f610d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
05fd0009-bc2b-4bcd-bb1d-606fa4d9ac68.mp3
***** 转录
从渔猎到农业，人类社会先是出现了半永久性的农牧业村舍，之后有了定居的村庄。但这种状况也未能持久，一旦地力衰竭或人口增长过快，整个村舍就要迁移，或分裂成较小的组团，寻找新的住地，以保证足够的耕地。
**** 选择
***** A
人类的定居促进了人口的增长
***** B
农业的发展也促进了渔猎文明
***** C
人口迁移是为了解决耕地问题
***** D
人类定居从渔猎时期就开始了
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: c507f1d0-23cf-4c3f-a52a-41d897d6cd44
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
164c19e3-8938-4f95-afcb-2afa9be0e641.mp3
***** 转录
女：听说你是个美食家？
男：美食家谈不上，只能说我是一个对美食没有抵抗力的人，我的优点就是不挑食。
女：你认为什么是美食？
男：美食是可以让你身心愉悦的妙药。
女：能说得具体点儿吗？
男：在心情好的时候、疲惫的时候或是悠闲的时候，享受一顿可口的饭菜，那一定是最幸福的时刻。
女：看来吃什么在其次，只要能让你有愉快的感受，什么都是美食？
男：可以这么说。可是也有例外，对于我来讲，新疆的饭菜都是美味佳肴，因为我是新疆人嘛。还有，南京算是我的第二故乡，我对南京美食也是爱得不得了呀。
女：对吃你有什么感悟？
男：俗话说“民以食为天”，吃对于每个人来讲都是生存本能。可是，众所周知，吃给予我们的远不止于此，我更在意的是与家人、友人在“吃”的那个时刻围坐在一起，暂时放下忙碌的工作，忘掉这样那样的烦恼，享受片刻难得的悠闲。
女：平常你下厨吗？
男：以前经常下厨，现在因为工作的关系，下厨少了。其实我很享受烹饪的过程，能亲手为家人准备一桌饭菜，是一件非常幸福的事情。虽然做不出用料复杂、精致无比的饭菜，色香味俱佳还是没有问题的。
女：讲个关于你的吃的故事吧？
男：要说就说与拍戏有关的吃，那是在拍摄《特种兵》的时候。这部戏主要讲的是女特种兵的故事，拍戏强度很高，体力消耗特别大。我们的阵容中女演员居多，女孩子嘛，本来就喜欢吃一些零食和水果之类的东西，可是在戏里我是教官，总操练她们，尤其不允许她们吃零食。每天女演员们顶着烈日做体能训练，还得忍受我的“训斥”。直到今天，我心里还对她们抱有歉意，觉得当时我丧失了一个男子汉对女士们应有的同情心。
**** 题目
***** 6
:PROPERTIES:
:ID: c6b28bc3-77d4-45a3-b224-5509183062c0
:END:
****** 问题
******* 音频
92fd1d7b-6361-41cf-b78f-939b4efbc197.mp3
******* 转录
在吃的问题上，男的是个什么样的人？
****** 选择
******* A
没有不爱吃的食物
******* B
对美食的要求很高
******* C
只吃自已喜爱的食物
******* D
对美食有奇特的标准
****** 答案
A
***** 7
:PROPERTIES:
:ID: 61ceecde-7843-40c2-8031-ed57b05b5d5f
:END:
****** 问题
******* 音频
233cbbef-7c2d-49cf-b326-fd7b8289e723.mp3
******* 转录
关于男的眼中的美食，下列哪项正确？
****** 选择
******* A
美食是可以治病的
******* B
口昧独特的是美食
******* C
家乡的食物是美食
******* D
饿了吃什么都是美食
****** 答案
C
***** 8
:PROPERTIES:
:ID: 793c381d-c08d-4fac-8ac5-9f9d86cb91e2
:END:
****** 问题
******* 音频
131963ff-b7ef-46b8-b6a0-2e59a697624d.mp3
******* 转录
对于吃，男有什么感悟？
****** 选择
******* A
吃是人生头等大事
******* B
吃能解决生存问题
******* C
吃能提供营养，保证健康
******* D
可以和亲友一起享受悠闲
****** 答案
D
***** 9
:PROPERTIES:
:ID: e4943dac-ba80-495b-818c-8af7c0ef851a
:END:
****** 问题
******* 音频
c3243686-8ffa-4a73-a7f8-4a1af6f7dd7c.mp3
******* 转录
在做饭的问题上，下列哪项正确？
****** 选择
******* A
男的历来就不愿意做饭
******* B
男的太忙，没学过做饭
******* C
男的做饭手艺相当不错
******* D
男的做饭非常讲究用料
****** 答案
C
***** 10
:PROPERTIES:
:ID: 513d59ff-812a-44ed-8eaf-3df2f33bdefd
:END:
****** 问题
******* 音频
5efbb6b2-9f15-4419-b827-fedbaf58970c.mp3
******* 转录
关于吃的故事，下列哪项正确？
****** 选择
******* A
男的拍戏时经常吃零食
******* B
女演员怕胖不敢吃零食
******* C
男的看不惯女演员老吃零食
******* D
戏中男的不让女演员吃零食
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: ea9cf9ff-8b1f-43db-bb0c-ccb9fad5c8c0
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
92f7cadd-9833-406a-b595-224f11720fe6.mp3
***** 转录
传统密码的缺陷是显而易见的，简单的密码依然是大多数人保护个人隐私的最常见方式。以人体生物特征作为密码，真的可以变为现实吗？回答是肯定的，距离我们越来越近的“眼泪密码”便是如此。由于眼泪作用于角膜的结果无法被复制，因此“眼泪密码”的安全性有了质的提升。
“眼泪密码”之所以保密性强，是因为每个人的角膜都有独特的图像，扫描仪可据此甄别不同的人。如果黑客偷取并使用某人上次使用过的数据，机器会认定其无效，因为它“懂得”每次扫描结果都应该有细微的变化。这是因为，角膜表面因有泪水而湿润，因此数据是实时改变的。
还有科学家在探索声音密码，也有银行推出指纹密码。不过，生物密码技术目前并不完全成熟，假如一个人的手指肿了，那么机器则无法识别出指纹密码。
**** 题目
***** 11
:PROPERTIES:
:ID: 2ecf0097-a01c-4abd-be8e-dc0d7bed3e10
:END:
****** 问题
******* 音频
25cdab92-1583-4e0c-80ee-56501030005e.mp3
******* 转录
关于传统密码，可以知道什么？
****** 选择
******* A
缺点非常明显
******* B
简单、可靠、易操作
******* C
被黑客偷取后无法使用
******* D
比人体生物密码更安全
****** 答案
A
***** 12
:PROPERTIES:
:ID: 943ee437-92e0-4109-a38b-ac4a5660e011
:END:
****** 问题
******* 音频
f8437bb8-fb62-4906-a23d-b6b42a92505d.mp3
******* 转录
关于眼泪密码，可以知道什么？
****** 选择
******* A
安全性有待提升
******* B
可复制性差一些
******* C
数据会实时改变
******* D
黑客破解很容易
****** 答案
C
***** 13
:PROPERTIES:
:ID: 810fccf1-7f61-42c5-bbfc-7dbb84a9b481
:END:
****** 问题
******* 音频
6ad21196-65a3-4596-9fbe-2a8d1667e545.mp3
******* 转录
目前已在银行使用的生物密码是哪一种？
****** 选择
******* A
声音密码
******* B
眼泪密码
******* C
传统密码
******* D
指纹密码
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: dbe5676c-a54e-49c2-8c65-53d14e48b840
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
0c735f12-ec42-4e5f-9b28-afb8f359495a.mp3
***** 转录
蛤蜊，身上长着像树木年轮一样的纹路，每成长一年，它就仔细地划上一道完美的圆圈。科学家们数了又数，身上有一百二十多圈的蛤蜊并不稀少，也就是说这些蛤蜊穿越了一个世纪，又健康快乐地生活了二十多年。目前发现的最高龄蛤蜊为 507 岁。
想知道蛤蜊长寿的秘诀吗？夏天对许多动物来说都是最享受的季节，它们大口大口地吃东西，以保持正常的新陈代谢；夏季的美食足够丰盛，它们不担心会没有东西可享用。对于蛤蜊来说，夏季是最幸福的季节，它们要繁殖后代，要承担起做父母的责任和义务，它们没有过多的时间去享用美食，它们的生活简单而快乐。冬天到了，宝宝们长大了，爸爸妈妈也自由了。但这时候草木枯萎、万物藏匿，蛤蜊吃不到多少可口的食物。好在它们习惯了节省而优雅的生活，只要有一些东西吃就足够满意和幸福了。
正是这些高贵的品质保证了蛤蜊的长寿。也许聪明的人类，这时你恍然大悟了吧，我们总能够从蛤蜊身上想到些什么吧！
**** 题目
***** 14
:PROPERTIES:
:ID: 995cd09e-13fe-4ee2-99b4-bdc0e3ffc1ec
:END:
****** 问题
******* 音频
27bd4703-bd84-4fde-806f-0b47af3e7b46.mp3
******* 转录
目前发现最长寿的蛤蜊多少岁？
****** 选择
******* A
二十几岁
******* B
一百多岁
******* C
五百多岁
******* D
一百二十岁左右
****** 答案
C
***** 15
:PROPERTIES:
:ID: 61faff5b-6412-421a-a891-23013ab2fd6f
:END:
****** 问题
******* 音频
da7905ad-2312-40e7-8f05-3400fe2d2ddb.mp3
******* 转录
对许多动物来说，夏天是个怎样的季节？
****** 选择
******* A
生儿育女的季节
******* B
尼情吃喝的季节
******* C
保养身体的季节
******* D
享受自由的季节
****** 答案
B
***** 16
:PROPERTIES:
:ID: 4b9dc091-a992-47f9-8000-57a53c48f76c
:END:
****** 问题
******* 音频
46b7a6b7-b2d6-4415-a8a5-fbc311e6b758.mp3
******* 转录
蛤蜊在什么时候繁育后代？
****** 选择
******* A
春天
******* B
夏天
******* C
秋天
******* D
冬天
****** 答案
B
***** 17
:PROPERTIES:
:ID: 9d29e872-b064-4053-b464-de70c33e77f7
:END:
****** 问题
******* 音频
b1bbff8a-e07e-4c32-9b5c-1270a11061ad.mp3
******* 转录
人类从蛤蜊身上能悟出什么道理？
****** 选择
******* A
一生都要追求优雅
******* B
父母必须对孩子负责
******* C
父母抚养孩子不容易
******* D
简约的生活是最健康的
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
钟大夫的卫生室是镇里最正规的之一。
***** B
在我的记忆里，几乎每一个冬天的晚上，奶奶都在灯下学习。
***** C
一个华丽的转身，她在近乎疯狂的掌声中完美地结束了花样滑冰表演。
***** D
河水在阳光的照耀下闪闪发光，但河比以前窄了很多，浪也没有以前大。
**** 答案
A
*** 19
**** 句子
***** A
他被《时代》杂志将其列人“20世纪最有影响的100个人”。
***** B
没有翻不过的高山，没有走不出的沙漠，更没有超越不了的自我。
***** C
蔚蓝的天空堆满造型奇异的云朵，有的像人，有的像动物，还有的像花。
***** D
含杏仁油的护理液更容易渗透到受损的发丝中，从内部对发丝进行修补。
**** 答案
A
*** 20
**** 句子
***** A
空气不仅有体积，而且它还有重量。
***** B
写论文不仅要驳错误的观点，而丁会借助先人的看法。
***** C
尽可能少犯错误，这是人的准则；不犯错误，那是天使的梦想。
***** D
大雪过后，空气仿佛被过滤得干干净净，一切都变得那么纯洁而美好。
**** 答案
B
** 第二部分
*** 21
**** 段话
板块一地体学说[[gap]]了地壳运动现象，证明地球是一个生机勃勃的星体，它有着非常[[gap]]的“新陈代谢”过程，有着[[gap]]的过去和灿烂的未来。
**** 选择
***** A
****** 1
解释
****** 2
活跃
****** 3
辉煌
***** B
****** 1
发现
****** 2
活泼
****** 3
惊人
***** C
****** 1
发明
****** 2
复杂
****** 3
广阗
***** D
****** 1
展现
****** 2
古怪
****** 3
光荒
**** 答案
A
*** 22
**** 段话
[[gap]]的采访时间已过大半，桌上的那杯茶未动。我[[gap]]着周先生。他全神贯注，谈话仍旧有条不紧地进行着，没有[[gap]]，没有停顿，谁也无法[[gap]]这仨科学家严谨的思维。
**** 选择
***** A
****** 1
打算
****** 2
注意
****** 3
迷惑
****** 4
停止
***** B
****** 1
计划
****** 2
凝视
****** 3
混乱
****** 4
断绝
***** C
****** 1
预测
****** 2
审视
****** 3
顾虑
****** 4
拒绝
***** D
****** 1
预定
****** 2
注视
****** 3
跳跃
****** 4
打断
**** 答案
D
*** 23
**** 段话
[[gap]]不要因为矿物质在人体内含量极小就[[gap]]它的价值，须知它们对维持人体中的一些决定性的新陈代谢是十分必要的。[[gap]]缺少了这些必需的微量元素，人体就会出现疾病，[[gap]]危及生命。
**** 选择
***** A
****** 1
总之
****** 2
小看
****** 3
与其
****** 4
以至
***** B
****** 1
据悉
****** 2
轻视
****** 3
果然
****** 4
乃至
***** C
****** 1
干万
****** 2
忽视
****** 3
一且
****** 4
甚至
***** D
****** 1
偏偏
****** 2
演视
****** 3
随着
****** 4
随后
**** 答案
C
** 第三部分
*** 段话
苍蝇是声名狼藉的“逐臭之夫”，凡是脏臭污秽的地方，都有它们的踪迹。
苍蝇的嗅觉特别灵数，[[gap:24]]日是苍蝇并没有“鼻子”，它靠什么来闻呢？原来苍蝇的嗅觉感受器分布在头部的亘〈1触角上，每个触角有一个“鼻孔”与外界相通，内含上百个嗅觉神经细胞。[[gap:25]]，这些神经会立即把气昧刺激转变成神经电脉冲，送往大脑，大脑根据不同气味物质所产生的神经电脉冲的不同，就可区别出不同气显的物质。因此，苍蝇的触角像是一台灵敏的气体分析仪。
仿生学家由此得到启发，[[gap:26]]，仿制出一种十分奇特的小型气体分析仪。这种仪器的“探头”不是金属，[[gap:27]]。就是把非常纤细的微电极插到苍蝇的噶觉神经上，将引导出来的神经电信号经电子线路放大后，传送给分析器；分析器一经发现气显物质的信号，便能发出警报。这种仪器已经被安装在宇宙飞船的座舱里，[[gap:28]]。这种小型气体分析仪，也可测量潜水艇和矿井里的有害气体。
*** 选择
**** A
根据苍蝇喱觉器官的结构和功能
**** B
远在儿干米外的气咖也能嗣到
**** C
用来检测舱内气体的成分
**** D
而是活的苍蝇
**** E
若有气昧进人“鼻孔“
*** 答案
**** 24
B
**** 25
E
**** 26
A
**** 27
D
**** 28
C
** 第四部分
*** 29-32
**** 段话
活化石指先发现化石再发现活体，或活体与确认的化石属同一种且同时存在。于是就有了一些延续了上千万年的古老生物，与其同时代的其他生物早已绝灭，只有它们独自保留下来，适应了现代的环境，生活在一个极其狭小的区域，被称为“活化石”。
1938年在非洲东南部海中发现的矛尾鱼，是世界闻名的一种活化石。中国的银杏树、水杉，哺乳动物大熊猪、中华鲟，均被世界公认为珍贵的活化石。
银杏树又名白果树，古又称鸭脚树或公孙树。远在二亿七十多万年前，银杏的祖先就开始出现了。到了一亿七千多万年前，
银杏已和当时称霸世界的恐龙一样道布世界各地，后来，绝大部分银杏像恐龙一样灭绝了，只在中国部分地区保存下来一点点，流传至今，成为稀世之宝。浙江天目山一带尚可见到野生银杏。故银杏有“活化石”植物中的熊猾“之称。
水杉树姿优美，枝叶繁茂，叶色多变而独具一格。它曾广泛分布于北半球。但经过第四纪冰期以后，它们儿乎全部绝灭。20世纪40年代，科学家在中国的四川、湖北和湖南均发现水杉尚有留存，其后，这个曾被认为早已在世界上绝迹的树种迅速传播于世。水杉不仅是珍贵的“活化石”，而且它有很强的生命力和广泛的适应性，它生长迅速，是优良的绿化树种，现在不但在中国各地广泛栽培，世界很多国家也争相引种，使这珍贵的树木得以在全球范围内生生不息。
**** 题目
***** 29
****** 问题
关于“活化石”，下列哥项正确？
****** 选择
******* A
先发现化石再发现活体
******* B
对生存空间没有特殊要求
******* C
化石与活体同时被发现
******* D
是活了上千万年的动植物
****** 答案
A
***** 30
****** 问题
银杏树古代又称为：
****** 选择
******* A
化石树
******* B
鸭脚树
******* C
公二树
******* D
熊猫树
****** 答案
B
***** 31
****** 问题
银杏树的繁盛时期在：
****** 选择
******* A
一干多万年前
******* B
恐龙灭绝的时候
******* C
二亿七干多万年前
******* D
一亿七千多万年前
****** 答案
D
***** 32
****** 问题
水杉的特点是：
****** 选择
******* A
适应环境的能力很强
******* B
在世界各地均有发现
******* C
生长速度慢于其他树
******* D
仅可栽种于中国南方
****** 答案
A
*** 33-36
**** 段话
5年前，一位老人在海边发现了一只津身覆盖着石油、饽得奄奄一息的企鹅。老人把企鹅带回丁家，给它取名Dindim。
Dindim是一只麦哲伦企鹅。之所以叫麦哲伦企鹅，是囚为著名航海家麦哲伦于1519年最早发现了它们，后来科学界就以麦哲伦命名该物种了。这种企鹅主要分布于南美洲南端海域的群岛中，是温带地区企鹅类中极具代表性的物种。
老人给Dindim清理黏附在羽毛上的油渍，使它身上不再有难闻的气昧；喂鱼给它吃，让它尽快强壮起来。有了老人的悉心照料，Dindim很快得以康复。老人把它带到海边，想让它回家，Dindim却没有走，它在老人身边整整待了11个月，直到它开始换毛才离开。
老人本以为这辈子不会再见到Dindim了，令他诧异的是，几个月后，Dindim又回来了，而东大模大样地跟着老人回了家。更为奇妙的是，此后，每年的6月，Dindim都会如期出现，次年的2月再回到阿根廷和智利的海岸。而它每年来看望老人要游行的距离超过3000公里。
老人说，Dindim与他越来越亲密，每年他们一相见，Dindim就会愉快地摇晃尾巴，发出欢快的叫声，老人也像爱自己的孩子一样爱着Dindim。他相信Dindim也爱他，因为Dindim喜欢待在老人的膈上等着老人给它喂食，还允许老人把它抱起来，除了老人之外，任何人想接近Dindim，都会被啄。
Dindim为什么会和老人这么亲近，还要每年不远万里来和老人囡聚，有生物学家认为，可能是企鹅把老人当成了家人，也可能是Dindim认为老人也是一只企鹅。至于真相，只有企鹅能够告诉你。
**** 题目
***** 33
****** 问题
5年前，老人发现企鹅时，那只企鹅：
****** 选择
******* A
饿得没有了呼吸
******* B
身上沾满了石油
******* C
身上已开始换毛
******* D
非常想有一个家
****** 答案
B
***** 34
****** 问题
关于“麦哲伦企鹅”名字的来源，下列睇项正确？
****** 选择
******* A
救了 Dindim 的老人给起的
******* B
发现这一物种的人给起的
******* C
以企鹅栖息地的地名而命名
******* D
以最早发现人的名字而命名
****** 答案
D
***** 35
****** 问题
老人认为最奇妙的事情是：
****** 选择
******* A
Dindim 康复之后一直没有离开他
******* B
Dindim 大大方方跟着老人回了家
******* C
每年 6 月，Dindim 都会准时来看他
******* D
Dindim 居然能够游 3000 公里的距离
****** 答案
C
***** 36
****** 问题
关于企鹅为什么会和老人这么亲近，下列睇项正确？
****** 选择
******* A
老人行事风格很像企鹅
******* B
老人把企鹅当成了孩子
******* C
这个答案只有企鹅知道
******* D
别人的亲近让企鹅不愉快
****** 答案
C
