* Expansion

** indication

词汇：熟悉下列词语的语素义

** notes

事物 / shi4 wu4 / object, thing ;

* 课文
** 转录
（一）优秀女警官
女警官李真是公认的“指纹破译专家”。
一次，某酒店一位正在化妆的女士被残忍地杀害在室内，现场没有烟头，没有纸屑，也没有抢劫等犯罪痕迹，侦破工作一时陷入停顿，一位曾在楼道内徘徊的男子有嫌疑，却苦于找不到证据。经过反复多次的现场勘查，窗台上一枚残缺的指绞成了唯一的线索，李真经过几个昼夜反复细致的比对，最终得出结论，抓住了歹徒。
另一次，某地发生多起入室抢劫案，附近居民恐惧感大增。其中两起案件提取到了犯罪嫌疑人的指纹，一枚是在玻璃上，而且指纹严重变形；另一枚是在铜制的框架上，指纹只残留有指尖部位。李真天天盯着指纹看，开始怎么也理不出头绪，两枚指纹都是残缺变形的，可以把两枚指纹结合起来分析吗？经过努力，李真发现因刑事犯罪被关押，一年前刑满放出监狱的王某的指纹与现场指纹具有共同特点，王某作案嫌疑很大。为了慎重起见，她又将其他现场遗留的指类部位指纹与王某的指纹反复比较，最终认定该系列抢劫案为王某所为。
李真说，指绞认定工作繁重、枯燥，不能有半点麻痹和失误，是一项考验耐心的工作。十余年间，李真全身心投入到痕迹检验和指绞管理工作中，查获了不少犯罪分子，使罪犯得到了应得的制裁。
（二）缉毒警察的故事
公安局接到情报，有人要在某地进行毒品交易，志强立刻带领手下实地走访调查，很快了解到：几天前，的确有一伙人运来大批毒品。因各处防守严密，毒贩把东西藏在了桃花乡附近的大山里，准备参与交易的人也住在附近。志强感到毒贩十分狡猾，为了做到万无一失，他确定了“化装行动、引蛇出洞、主动出击”的破案思路。志强假扮成购买毒品的毒贩，与对方接上了头。对方提出在山里进行交易，志强认为山里地形复杂，提出在山下交易。信息传过去，对方却保持了沉默。时间一天天过去，志强心中十分焦急，但他清楚，必须沉着冷静，他决定暂且拖一拖这帮毒贩。他放出风说，自己在外地还有事，没贷就算了。听到这话，对方急了，提出要不就在镇子附近交易。
大清早，志强和全队民警出发了。到了交货地点，志强开始部署兵力。他让一个同事在车里隐蔽好，一个随他下车，其他同事埋伏在附近。
刚刚布置妥当，一辆农用车和一辆摩托车朝自己缓缓驶来。面对毒贩，志强提出先验货后交钱，并告诉毒贩钱就放在车里。毒贩拿出毒品，奔向车门去取钱，车内民警扑上去，毒贩来不及反抗就被逮捕了。
这次，缉毒大队成功破获了当地有史以来最大的一起非法运输贩卖毒品案。
（三）特殊的“缉毒警察”
小罗是个兵，辉杰是只犬，这原本是一个平面上两条平行而非并列的线，却在缉毒战场上交叉，创造出感人的故事。
接手缉毒犬辉杰，小罗心里包袱很重。小罗怕狗，小时候被狗狂追的经历让他提起狗就胆怯。和辉杰初次见面，小罗努力和它搞好关系，可任你怎么哄，辉杰就是不理，弄得小罗很着急。没几天，辉杰生病了，小罗悉心照顾它。辉杰很快就好了，自此它对小罗非常的信赖和忠诚，每次见到小罗就会亲热地伸出舌头舔一舔。训练中，辉杰表现突出，无论毒品藏得多隐秘，辉杰一出手，不出一分钟，肯定能查出来。
小罗和辉杰可以正式执行任务了。这天辉杰按小罗的指令对一辆车实施搜嗅，很快就从车厢尾部空隙内查出了毒品。此后，辉杰累立战功。
那是 9 月的一天，辉杰在一辆车上发现了毒品，它扒开车厢底板上铺着的塑料垫，直接从下面叼出一个装有粉末状毒品的塑料袋，薄薄的塑料袋一咬即破，毒品直接渗入了辉杰的口腔。辉杰中毒了，它呼吸急促，无法站立，得赶快上医院。路上，辉杰眼看就不行了，小罗来不及多想便给辉杰做起了人工呼吸。14 公里路程，小罗一次次把辉杰从死亡线上拉回来。经过抢救，辉杰脱离了生命危险，半个月后它又出现在缉毒岗位上。
中毒事件让辉杰的身体每况愈下，几年后，辉杰离世。参加过无数次大大小小“战役”的辉杰走完了它光辉的一生，也给小罗的心中留下了无尽的思念。
