* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 8607e59e-da4c-4e05-add4-d474c702ab6b
:END:
**** 对话
***** 转录
男：听说你去爬华山了？够刺激吧？[[file:4f14f342-31e5-4673-bbe2-356dfb3d0b70.mp3][(audio)]]
女：没错，有些地方山路非常窄，吓得我腿直发抖。[[file:da3a9aa4-2ca4-4df3-9998-086447a99bb6.mp3][(audio)]]
***** 音频
87c0ae81-8fa5-4f9c-a4af-a3877bd1b222.mp3
**** 问题
***** 转录
女的爬山时感觉怎么样？
***** 音频
6a93c035-b043-4772-8fab-8e55bfa05bff.mp3
**** 选择
***** A
有些慌张
***** B
非常冷静
***** C
轻松愉快
***** D
格外激动
**** 答案
A
*** 2
:PROPERTIES:
:ID: 26c39b73-2cf2-46c9-95f0-8c19c97c6ef5
:END:
**** 对话
***** 转录
女：刘教授的讲座是明天下午几点？[[file:ef49a04c-fbea-4e1d-bdc2-03423def1f23.mp3][(audio)]]
男：本来定的是两点半，临时又通知说改在三点了。[[file:6119c139-1075-4bd0-9519-8ae7db17ff56.mp3][(audio)]]
***** 音频
f27a285a-00ac-4a01-bdaa-52d1905c83f2.mp3
**** 问题
***** 转录
关于那个讲座，下列哪项正确？
***** 音频
ebbfac1c-89db-4273-add2-1d87e59b2e44.mp3
**** 选择
***** A
提前了
***** B
信迟了
***** C
取消了
***** D
按时举行
**** 答案
B
*** 3
:PROPERTIES:
:ID: 9d17d410-0230-4a41-b34f-8649bebaf7dc
:END:
**** 对话
***** 转录
男：我们运气真好，海面风平浪静，风景多美啊！[[file:15211df7-ee0b-4c1a-b767-1a732414a70e.mp3][(audio)]]
女：是啊，临出门时，我还担心会晕船呢。[[file:3fa7daf6-00b3-4e80-9ea5-8985054acab5.mp3][(audio)]]
***** 音频
38935a7c-40c6-4b6c-b66e-94129756cb5d.mp3
**** 问题
***** 转录
关于女的，可以知道什么？
***** 音频
762c7b50-ea77-4eb2-9047-48a25cad0eec.mp3
**** 选择
***** A
首次出海
***** B
后悔上船
***** C
没有晕船
***** D
遇到风浪
**** 答案
C
*** 4
:PROPERTIES:
:ID: 30ba002f-1960-42a0-8440-41f1a30b2780
:END:
**** 对话
***** 转录
男：早上起来时，突然感觉脑子特别晕，身体一下子失去平衡就摔倒了。[[file:9ec813f4-ca8e-4eb2-b1fc-81cd58c47b37.mp3][(audio)]]
女：那后来怎么样了？您这个毛病可得好好查查了。[[file:089d7eb5-ef02-41be-9628-60b760054aee.mp3][(audio)]]
***** 音频
3ac8ecdf-8ff9-4cd4-8a1a-38b3eb2ab716.mp3
**** 问题
***** 转录
男的为什么摔倒了？
***** 音频
4cd960fc-103c-45a0-a476-7d4a0c856cad.mp3
**** 选择
***** A
头晕
***** B
肚子饿
***** C
被车撞了
***** D
地面湿滑
**** 答案
A
*** 5
:PROPERTIES:
:ID: 1baac7d6-04cd-408a-b9b3-cf1b76cb0c9f
:END:
**** 对话
***** 转录
女：老师让你把作文再检查一下，上面还有标点错误。[[file:d3df97b7-31f1-4fbc-a3bd-7b4a42f5b63b.mp3][(audio)]]
男：好的，我现在就看。[[file:31d0b705-6ff4-4066-9be9-39af252b88c8.mp3][(audio)]]
***** 音频
fe80f72c-254f-4ee4-a13f-4e2923b2595c.mp3
**** 问题
***** 转录
老师觉得作文还有什么问题？
***** 音频
12bcba08-8583-484f-984c-4f94f1d29a37.mp3
**** 选择
***** A
语句不通
***** B
字数不够
***** C
结构太乱
***** D
标点有误
**** 答案
D
*** 6
:PROPERTIES:
:ID: 441cd7d8-f920-42fb-a2a3-495d809ecfd5
:END:
**** 对话
***** 转录
女：听说你选刘宏老师做你的导师了？[[file:e6940023-7bab-4660-b13a-74ada1c33083.mp3][(audio)]]
男：是的，刘教授很有学问，分析问题也很透彻，就是有点儿严肃。[[file:39133c6b-172c-44ec-8be6-82ed3466a8c5.mp3][(audio)]]
***** 音频
089e719d-1c22-40a3-9af4-5ea5c8a7d49e.mp3
**** 问题
***** 转录
男的觉得刘教授怎么样？
***** 音频
2a547795-73d8-4a63-987e-e77f475c1b00.mp3
**** 选择
***** A
待人很亲切
***** B
看着很严肃
***** C
为人很谦虚
***** D
说话很幽默
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
男：您选的这两套房子户型很相似，只是面积相差了二十多平米。
女：房屋质量怎么样？
男：这个绝对有保证，我建议您买大一点儿的那套，住着更舒服。
女：大的是好，就是这个价格我有点儿承受不了。
***** 音频
fdb7f7d5-b0b7-4a08-ad55-3652ed848069.mp3
**** 问题
***** 转录
女的觉得男的推荐的房子怎么样？
***** 音频
bd20ed58-cd44-4bb2-8ed6-e4f2458db1ac.mp3
**** 选择
***** A
户型不够好
***** B
质量没保证
***** C
面积不够用
***** D
价钱有点儿贵
**** 答案
D
*** 8
**** 对话
***** 转录
男：昨晚的风实在太大了，顶着风都走不动路了。
女：我们家对面楼上的广告牌都让风给刮下来了。
男：太可怕了，没砸着人吧？
女：幸亏没有人，不过，警察、消防都来了。
***** 音频
e0fb0466-fa79-480a-8dc8-349488029fb2.mp3
**** 问题
***** 转录
关于昨晚的风，从对话中可以知道什么？
***** 音频
b0bcada3-2d6f-49d6-a916-6d57394ff45e.mp3
**** 选择
***** A
造成了堵车
***** B
风力不太大
***** C
刮坏了广告牌
***** D
整整刮了一夜
**** 答案
C
*** 9
**** 对话
***** 转录
男：擦地时在电视柜下面发现了你的口红。
女：我说哪儿去了，怎么滚到那里去了。
男：去问你的宝贝儿子吧，昨天幼儿园老师叫他们画一幅妈妈的画儿。
女：哦，我说呢，画上红嘴唇的颜色怎么那么像我口红的颜色。
***** 音频
5482856d-40ae-4ce8-a89b-5879cdae48e8.mp3
**** 问题
***** 转录
女的的口红是在哪儿找到的？
***** 音频
74d127b6-e070-4f6c-8cb4-75992b9c195a.mp3
**** 选择
***** A
幼儿园里
***** B
电视柜下
***** C
儿子书包里
***** D
老师书桌上
**** 答案
B
*** 10
**** 对话
***** 转录
女：这个瓶子每次你盖上后，谁都打不开。
男：我来帮你。
女：以后你盖上时，别太使劲儿了。
男：我没有使多大的劲儿，是瓶口沾上了蜂蜜。
***** 音频
0301cdb1-5546-4b66-b5f5-7ae17f59a2df.mp3
**** 问题
***** 转录
女的认为打不开瓶子的原因是什么？
***** 音频
2e0810c2-ce1e-4256-9140-5c3eadc0781a.mp3
**** 选择
***** A
自已手没劲儿
***** B
男的盖得太紧
***** C
瓶子设计有问题
***** D
瓶口沾上了蜂蜜
**** 答案
B
*** 11-12
**** 对话
***** 转录
古时候，有个士兵在一次战斗中腿部中了一箭，疼得要命。军官请了一位外科医生来给他治伤。医生看后说：“这个不难！”就拿出一把剪子，把露在外边的箭杆剪掉了，然后要了手术费就要走。士兵着急地说：“剪掉箭杆儿谁不会呀？我要你拔出射进肉里的箭头！”医生摇摇头说：“外科的事我已做完了，挖掉肉里的箭头，那是内科的事。”
***** 音频
745be9c2-4a78-4cf1-b029-5fbd8c1eb621.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于那个士兵，可以知道什么？
******* 音频
36cbfb96-dda8-4020-999f-422578ba6989.mp3
****** 选择
******* A
眼睛瞎了
******* B
腹受伤了
******* C
快要死了
******* D
胳膊断了
****** 答案
B
***** 12
****** 问题
******* 转录
关于那个医生，下列哪项正确？
******* 音频
ffaf2870-ea95-4088-bcf7-72aa7f29ed2e.mp3
****** 选择
******* A
责任心很强
******* B
没收手术费
******* C
没解决问题
******* D
医术很高明
****** 答案
C
*** 13-14
**** 段话
***** 转录
产品销售会上，销售情况极其令人失望，经理对负责销售的职员大声责备道：“我已经看够了你们恶劣的工作表现，听够了你们的那些理由。如果你们无法胜任这项工作，会有人代替你们，卖出这些有价值的产品。”然后，他转身朝一名新招聘来的职员——一个刚刚从足球队退下来的球员——说道：“如果一支球队赢不了球，会怎么样呢？队员们都得被换掉，对吗？”沉默了几秒钟后，这名前足球队员回答道：“实际上，先生，如果整个队伍都有麻烦的话，我们通常只是换个新教练。”
***** 音频
7d3a1a52-bc84-4184-8685-0899dbf365ad.mp3
**** 题目
***** 13
****** 问题
******* 转录
经理觉得销售人员的业绩怎么样？
******* 音频
8096b9d4-251f-4aa1-a767-553c24b6aa91.mp3
****** 选择
******* A
令人失望
******* B
十分理想
******* C
有待提高
******* D
下降明显
****** 答案
A
***** 14
****** 问题
******* 转录
经理问前足球队员的目的是什么？
******* 音频
10a79a7f-23b8-413b-b124-698a027617b2.mp3
****** 选择
******* A
想跟他开个玩笑
******* B
想当足球队的教练
******* C
想考察他的业务能力
******* D
想吓吓那些销售人员
****** 答案
D
* 阅读
** 第一部分
*** 段话
26岁的荷兰残疾姑娘莫妮克收到了最棒的圣诞礼物：从轮椅上站起来了。原来，莫妮克曾在一次[[gap][15]]的交通事故中瘫疸，但坚强的莫妮克并没有放弃生活，经过[[gap][16]]训练，她成为一名残疾运动员，并曾在2008年北京残奥会公路白行车项目中获得亚军。或许是莫妮克这种[[gap][17]]的精神感动了上天，奇迹发生了。在西班牙集训时，一辑全速行驶的自行车将莫妮克撞倒在地。她说，当时自己毫无知觉的双腿感觉像通了电一样，之后奇迹发生了。那[[gap][18]]事故仿佛打通了莫妮克双腹的“行走按钮”，酥麻感过去后，莫妮克惊奇地发现自己可以从轮椅上站起来了，她虽然走得很艰难，但这却预示着一个全新的未来。
*** 题目
**** 15
***** 选择
****** A
恐怕
****** B
可怕
****** C
害怕
****** D
厉害
***** 答案
B
**** 16
***** 选择
****** A
刻苦
****** B
彻底
****** C
猛烈
****** D
使劲儿
***** 答案
A
**** 17
***** 选择
****** A
严于律己
****** B
惜时如金
****** C
敢于冒风险
****** D
不向命运认输
***** 答案
D
**** 18
***** 选择
****** A
回
****** B
件
****** C
起
****** D
项
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: aad07951-88c2-4b15-8477-60464a6ee3c7
:END:
**** 段话
宋应星的《天工开物》是一部系统地记载中国古代农业和手工业成就的伟大著作。这本书受到了世界各国的重视，先后被翻译成日、法、德、俄等多种文字。狄德罗是因编写《百科全书》而具有世界影响的法国学者，编写《中国科技史》的英国学者李约瑟称宋应星为“中国的狄德罗""”。
**** 选择
***** A
宋应星编写了《中国科技史》
***** B
《天工开物》被翻译成四种文字
***** C
宋应星发明丁许多农业生产工具
***** D
宋应星的成就和影响与狄德罗相当
**** 答案
D
*** 20
:PROPERTIES:
:ID: 0afd9fa0-b98f-4777-8668-c5a40294abc4
:END:
**** 段话
冬季天气阴沉，容易让人感觉精神不愉快。如何赶走坏心情呢？一项最新研究表明，每天只要花上5分钟倾听清晨的鸟叫，就能有效地帮助人们击退负面情绪。如果无法听见真的鸟叫，听鸟叫的录音也能够达到相似的效果。
**** 选择
***** A
清晨的鸟叫声最动听
***** B
鸟叫的录音使人心烦
***** C
天气阴沉易影响心情
***** D
养鸟有助于叫人起床
**** 答案
C
*** 21
:PROPERTIES:
:ID: 9e0416c2-169a-4169-9a13-911139fe3e6e
:END:
**** 段话
在做一件事前，你是否常在心中对自己说“可能不行吧”“万一怎么样怎么样”，结果可能还没去做，你就没有信心了，事情十有八九就会朝着你设想的不利方向发展。所以，你要相信自己是最优秀的，有了信心，你的能力和智慧才能发挥到最好。
**** 选择
***** A
信心有助于人发挥才智
***** B
做事时要避免盲目自信
***** C
事前准备不足往往失败
***** D
对困难要有充分的估计
**** 答案
A
*** 22
:PROPERTIES:
:ID: 40d1e9b9-13d8-471a-a603-61b77727351e
:END:
**** 段话
运动后，可以花5～10分钟做一些放松性练习，如慢跑、柔软体操、放松按摩等，也可以做一些静态的伸展运动。这些运动被称作积极性休息，有助于促使疲劳的消除和机体的恢复，因此，运动结束阶段也是运动过程中不可忽视的重要阶段。
**** 选择
***** A
运动结束时一定要休息
***** B
运动结束阶段常被忽视
***** C
放松性练习可以帮助消除疲劳
***** D
柔软体操是最好的积极性休息
**** 答案
C
** 第三部分
*** 23-25
**** 段话
一对老夫妇住进了公寓，与我成了对门邻居。
两位老人都70多岁，入住后极少外出，一些食物和日用品，大都由住在附近的女儿、女婿送来。偶尔与老两口在楼道碰面，他们会对我微笑点头，但很少开口说话。
那天，我出门上班，刚好看到老头儿在取报纸。彼此点点头后，我无意中看见他家挂在楼道上的报箱并未用锁，而是用铜线弯成圆圈将箱门连接上。取报时，主人稍转动一下铜圈，箱门便打开了。我对他说：“您应买把锁把箱门锁上，以防报纸丢失。”老人听后，点头答应，可事后，我看到他的报箱依然如故。
在我又一次提示后，老头儿终于开口说话，他指着楼道墙上那成排的报箱说：“锁是用来防小偷的。现在楼里住户大都订了报刊，都有书报阅读，就不会出现家贼；小区里还有保安，丢报纸的可能性很小；再说，邻里之间相处是缘分，大家应该生活在真挚、友爱、信任的环境里。多信任、少戒心，尽量不要人为设置障碍。”
我听了老头儿一番话，也认真效仿起来。果然，半年多的时间过去了，不愉快的事情从未发生，而我也惊喜地发现，楼道里报箱不用锁的越来越多了。
**** 题目
***** 23
****** 问题
关于两位老人，从文中可知：
****** 选择
******* A
爱逛超市
******* B
是退休教师
******* C
搬来时间不久
******* D
和女儿一起住
****** 答案
C
***** 24
****** 问题
老人报箱不上锁是因为？
****** 选择
******* A
没有订报
******* B
信任邻居
******* C
觉得太麻烦
******* D
不愿花钱买锁
****** 答案
B
***** 25
****** 问题
上文主要告诉我们什么？
****** 选择
******* A
邻里要互相照顾
******* B
防人之心不可无
******* C
人与人应多些信任
******* D
全社会都要关心老人
****** 答案
C
*** 26-28
**** 段话
有一个博士到一家研究所应聘，成为该研究所学历最高的一个人。
有一天他到单位后面的小池塘去钓鱼，正好正副所长在他的一左一右，也在钓鱼。
他只是微微点了点头，这两个本科生，有喊好聊的呢？
不一会儿，正所长放下钓竿，伸伸懒腰，噌噌噌从水面上走到对面上厕所。
博士眼睛睁得都快掉出来了。水上漂？不会吧！这可是一个池塘啊。
正所长上完厕所回来的时候，同样也是噌噌噌地从水上“漂”回来的。
怎么回事？博士生又不好去问，自己是博士生啊！
过了一阵，副所长也站起来，走儿步，同样噌噌噌地漂过水面上厕所。这下子博士更是差点儿晕倒，心想：不会吧，到了一个江湖高手集中的地方？
博士生紧张得也想上厕所了。这个池塘两边有围墙，要到对面厕所非得绕十分钟的路，而回单位上又太远，怎么办？
博士生又不愿意去问两位所长，忍了半天后，也起身往水里跨，暗想：我就不信本科生能过的水面，我博士生不能过。
只听咚的一声，博士生栽到了水里。
两位所长将他拉了出来，问他为什么要下水，他问：“为什么你们可以走过去呢？”
两所长相视一笑：“这池塘里有两排木桩子，由于这两天下雨涨水正好没在水面下。我们都知道这木桩的位置，所以可以踩着桩子过去。你怎么不问一声呢？”
**** 题目
***** 26
****** 问题
关于那个博士，从文中可以知道：
****** 选择
******* A
瞧不起正副所长
******* B
在单位年纪最轻
******* C
对工作很有想法
******* D
受到同事的欢迎
****** 答案
A
***** 27
****** 问题
根据上文，博士差点儿晕倒是因为看到所长怎样？
****** 选择
******* A
从水中抓上鱼来
******* B
飞快地游到对面
******* C
从水面上走到对岸
******* D
钓的鱼多得装不下
****** 答案
C
***** 28
****** 问题
根据本文，博士往水里跨是想：
****** 选择
******* A
下水练习游泳
******* B
去对面上厕所
******* C
学习所长的功夫
******* D
找水下的木桩
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
