* 练习

** 1
:PROPERTIES:
:ID: bfdb0052-e8a4-4371-8307-a5b3f025d0a2
:END:
*** 选择
**** 1
逗
**** 2
合作
**** 3
推广
**** 4
业务
**** 5
召开
**** 6
注册
*** 题目
**** 1
***** 句子填空
为了[[gap]]这项新产品，公司做了很多宣传。
***** 答案
3
**** 2
***** 句子填空
原本定在周三上午[[gap]]的会议改时间了。
***** 答案
5
**** 3
***** 句子填空
你做这么多事，难道只是为了[[gap]]女朋友开心？
***** 答案
1
**** 4
***** 句子填空
要想在这个网站购物，你必须先[[gap]]一个它的邮箱。
***** 答案
6
**** 5
***** 句子填空
那个新来的销售员这个月做成了三笔大[[gap]]，真厉害！
***** 答案
4
**** 6
***** 句子填空
我们跟这家公司[[gap]]过两次，很愉快。
***** 答案
2
** 2
*** 1
:PROPERTIES:
:ID: 897fea96-49d9-4cab-bf14-21727c9b2f56
:END:
**** 句子填空
像这样能够给全社会信心与快东的事情，我们应该重点[[gap]]。
**** 选择
***** A
宣传
***** B
推广
**** 答案
A
*** 2
:PROPERTIES:
:ID: 3aa6558f-ea93-4a6c-8ad3-dde085f2518e
:END:
**** 句子填空
要吃中国菜，你首先要学会[[gap]]筷子。
**** 选择
***** A
应用
***** B
使用
**** 答案
B
*** 3
:PROPERTIES:
:ID: bb55e206-8d64-4681-b559-e9d9893bbe3c
:END:
**** 句子填空
过了这么多年，我的愿望终于[[gap]]了！
**** 选择
***** A
现实
***** B
实现
**** 答案
B
*** 4
:PROPERTIES:
:ID: 593b958d-42c3-4602-9b5e-b7e81dc8b0d5
:END:
**** 句子填空
这是我的[[gap]]爱好，跟我学什么专业没有关系。
**** 选择
***** A
个人
***** B
自己
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
这个问题[[A]]是在什么样的背景[[B]]提[[C]]出[[D]]来的？
**** 词语
下
**** 答案
B
*** 2
**** 句子
公司[[A]]新[[B]]开发[[C]]的产品很受[[D]]消费者欢迎。
**** 词语
出
**** 答案
C
*** 3
**** 句子
本店销售[[A]]电视、冰箱、[[B]]洗衣机[[C]]其他电器。
**** 词语
以及
**** 答案
C
*** 4
**** 句子
[[A]]这个问题，[[B]]我们[[C]]开会讨论了[[D]]好几次。
**** 词语
针对
**** 答案
A
* 扩展
** 词语
*** 话题
电脑网络
*** 词语
**** 1
键盘
**** 2
鼠标
**** 3
光盘
**** 4
信息
**** 5
硬件
**** 6
软件
**** 7
数码
**** 8
数据
**** 9
程序
**** 10
系统
**** 11
网络
**** 12
信号
**** 13
充电器
** 题目
*** 1
**** 句子
我忘带手机[[gap]]了，得节省着用，先关机吧。
**** 答案
13
*** 2
**** 句子
汉字是一个整体的[[gap]]，字与字之间是有联系的。
**** 答案
10
*** 3
**** 句子
调查[[gap]]显示，用户们对微信的服务很满意。
**** 答案
8
*** 4
**** 句子
喂，您说什么？我听不清。这里[[gap]]不太好。
**** 答案
12
* 注释
** （三）词语辨析
*** 发达——发展
**** 做一做
***** 1
****** 句子
四川是茶馆文化最[[gap]]的地区之一。
****** 答案
******* 1
******** 发达
1
******** 发展
0
***** 2
****** 句子
人们常说这种动物不聪明，其实它的大脑很[[gap]]。
****** 答案
******* 1
******** 发达
1
******** 发展
0
***** 3
****** 句子
方便的交通是[[gap]]经济的基础。
****** 答案
******* 1
******** 发达
0
******** 发展
1
***** 4
****** 句子
她的病情[[gap]]得比我们想象的还要快。
****** 答案
******* 1
******** 发达
0
******** 发展
1
* 课文
** 转录
举着手机，边颠着球边拍……国际足球明星梅西用微信直播自己的颠球技术，把手机另一头一个正在哭的小宝贝通笑。这条 30 秒的全新广告宣传片在全球 15 个国家和地区同步上线。
如此大手笔的推广，腾讯自有其底气所在。微信“在海外注册用户已经超过 7000 万，且在快速增长当中”。7 月 3 日，在北京召开的2013 腾讯合作伙伴大会上，腾讯总裁刘炽平言语间充满了骄傲。
2011 年 1 月，微信上线；同年 4月，以英文名 WeChat 正式进入国际市场；2011 年 12 月，实现支持全球100 个国家的短信注册；2012 年底，覆盖国家和地区超过 100 个。如今，微信已经覆盖了 200 多个国家和地区、支持 16 种外语，是全球使用人数最多的移动通信应用。
在美国互联网企业“称霸”全球的背景下，作为中国自己的移动互联网产品，微信的出现，自然吸引了更多的关注。
被称为“微信之父”的腾讯公司高级副总裁张小龙介绍了微信的发展过程：微信的研究开发工作开展得很早，2010 年底，移动互联网刚起步，腾讯广州产品研发中心就开始考虑相关业务。他们清楚地认识到了这样的现实——在个人计算机时代，由于中国互联网的用户数量以及市场成熟程度等都低于发达国家，在产品创新上难有领导地位，而移动互联网是一个重新开始的机会。
在经营销售上，微信针对不同的国家和地区，推出了不同的广告片，邀请当地明星和名人代言，收效相当不错。海外用户群中不仅有华裔和新移民，还出现了更多的外国人。
