:PROPERTIES:
:CREATED: [2022-03-14 05:15:10 -05]
:END:

* Listening
:PROPERTIES:
:CREATED: [2022-03-14 05:15:15 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-14 05:15:17 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-06-24 14:28:21 -05]
:ID: e977eb9d-b8b2-4011-807e-59bf1e0aead9
:END:

妈妈知道电话是谁打的。
pi: māma zhīdào diànhuà shì shéi dǎ de
en: Mom knows who the caller was.
es: Mamá sabe quién era la persona que llamaba.


Answer: ✅
Reasoning: The picture shows a woman answering the phone, so she knows who called.

*** 2
:PROPERTIES:
:CREATED: [2022-06-24 14:28:24 -05]
:ID: 989207c6-ed78-4be6-acb0-0954370d2693
:END:

看！这是我在和小王一起跑步。
pi: kàn, zhè shì wǒ zài hé xiǎo wáng yīqǐ pǎobù
en: Look! This is me running with Xiao Wang.
es: ¡Mira! Este soy yo corriendo con pequeño Wang.

Answer: ❌
Reasoning: The picture shows 两个人踢足球。

*** 3
:PROPERTIES:
:CREATED: [2022-06-24 14:28:26 -05]
:ID: c804c979-24a2-4dd0-a8cd-86547cfd6ccc
:END:

今天的晚饭是我和丈夫一起做的。
pi: jīntiān de wǎnfàn shì wǒ hé zhàngfu yīqǐ zuò de
en: Today's dinner was cooked by my husband and me.
es: La cena de hoy la hemos cocinado mi marido y yo.

Answer: ✅
Reasoning: The picture shows two humans cooking together and expressing love to each other

*** 4
:PROPERTIES:
:CREATED: [2022-06-24 14:28:28 -05]
:ID: cb1447bd-4138-48d5-ba66-0cbe7a44b41f
:END:

今天报纸是王小姐买的。
pi: jīntiān bàozhǐ shì wáng xiǎojiě mǎi de
en: Today's newspaper was bought by Ms. Wang.
es: El periódico de hoy fue comprado por la señorita Wong.

Answer: ❌
Reasoning: There's no woman buying a newspaper in the picture

*** 5
:PROPERTIES:
:CREATED: [2022-06-24 14:28:31 -05]
:ID: 91b1c5a2-4efb-47c2-a4d9-3bbc2c493f19
:END:

我非常喜欢这个工作，已经工作两年了。
pi: wǒ fēicháng xǐhuan zhège gōngzuò, yǐjīng gōngzuò liǎng nián le
en: I like this job very much, I have been working for two years.
es: Me gusta mucho este trabajo, ya llevo dos años trabajando.

Answer: ✅
Reasoning: The woman wearing a dress is smiling

** 2
:PROPERTIES:
:CREATED: [2022-03-14 05:37:57 -05]
:END:




I didn't know that sentences could start with 是.

I didn't know the character 接.

*** 6
:PROPERTIES:
:CREATED: [2022-03-15 22:52:28 -05]
:ID: a7ce8876-5cb6-4330-bad1-c3122c9ade95
:END:

男：你喜欢吃中国菜吗？
pi: nǐ xǐhuan chī zhōngguó cài ma
en: Do you like Chinese food?
es: ¿Te gusta la comida china?

女：我非常喜欢吃，我也会做。
pi: wǒ fēicháng xǐhuan chī, wǒ yě huì zuò
en: I like it very much, and I can cook it.
es: Me gusta mucho y sé cocinar.

Answer: B

Reasoning: The image shows 女在做饭。

*** 7
:PROPERTIES:
:CREATED: [2022-03-15 22:53:29 -05]
:ID: abc8859f-5f83-4c7e-a235-1a010b7cd89b
:END:

安娜 | ānnà | Anna (female given name) | Ana (nombre de mujer) ;

男：这个是谁买的？
pi: zhègè shì shéi mǎi de
en: Who bought this?
es: ¿Quién ha comprado esto?

女：这个是安娜买的，今天是大卫的生日。
pi: zhègè shì ānnà mǎi de, jīntiān shì dàwèi de shēngrì
en: Anna bought it, it's David's birthday.
es: Lo compró Anna, es el cumpleaños de David.

Answer: F

Reasoning: The image shows 男人和一个 gift.

*** 8
:PROPERTIES:
:CREATED: [2022-03-15 22:53:35 -05]
:ID: fc8b9758-6b26-4aae-9b15-f76f72016661
:END:

I wrote 去院 instead of 出院.

I wrote 是年 instead of 时间.

I couldn't recognize 李.

I couldn't recognize 吧.

女：李先生出院多长时间了？
pi: lǐ xiānsheng chū yuàn duō cháng shíjiān le
en: How long has Mr. Li been out of the hospital?
es: ¿Cuánto tiempo lleva el Sr. Li fuera del hospital?

女：我不知道，你问一下张医生吧。
pi: wǒ bù zhīdào, nǐ wèn yīxià zhāng yīsheng bā
en: I don't know, ask Dr. Zhang.
es: No lo sé, pregúntale al Dr. Zhang.

Answer: E

Reasoning: The image shows a woman speaking with a doctor.

*** 9
:PROPERTIES:
:CREATED: [2022-03-15 22:54:01 -05]
:ID: 4691e5b1-09d8-4d85-82c0-fe860488e87b
:END:

I wrote 饭饭 instead of 芳芳.

女：你怎么认识芳芳的？
pi: nǐ zěnme rènshi fāng fāng de
en: How do you know Fang Fang?
es: ¿Cómo conoces a Fang Fang?

男：是小明帮我介绍的。
pi: shì xiǎo míng bāng wǒ jièshào de
en: Xiaoming introduced me to her.
es: Fue Xiaoming quien me presentó.

Answer: A

Reasoning: The image shows a group of co-workers.

*** 10
:PROPERTIES:
:CREATED: [2022-03-15 22:54:15 -05]
:ID: 4326ea50-102f-41e4-94d8-6112e2c5d8be
:END:

男：女儿，你去接一下电话。
pi: nǚ'ér, nǐ qù jiē yīxià diànhuà
en: Daughter, please answer the phone.
es: Hija, ve a contestar el teléfono.

女：对不起，爸爸，我没时间接电话，我在做饭呢。
pi: duìbuqǐ, bàba, wǒ méi shíjiān jiē diànhuà, wǒ zài zuò fàn ne
en: Sorry, Dad, I don't have time to answer the phone, I'm cooking.
es: Lo siento, papá, no tengo tiempo de contestar al teléfono, estoy cocinando.

Answer: B

Reasoning: The image shows 一个女性在做饭。

** 3
:PROPERTIES:
:CREATED: [2022-03-15 23:04:10 -05]
:END:

*** 11
:PROPERTIES:
:CREATED: [2022-03-17 21:49:46 -05]
:ID: 218e8bb1-a972-47b3-874e-531444116b23
:END:

alternatives

a

张老师
pi: zhāng lǎoshī
en: Mr. Zhang
es: Sr. Zhang

b

小王
pi: xiǎo wáng
en: Xiao Wang
es: Xiao Wang

c

王老师
pi: wáng lǎoshī
en: Mr. Wang
es: Sr. Wang

dialogue

女：小王，今天是张老师的生日。
pi: xiǎo wáng, jīntiān shì zhāng lǎoshī de shēngrì
en: Xiao Wang, it's Mr. Zhang's birthday today.
es: Xiao Wang, hoy es el cumpleaños del Sr. Zhang

男：我知道，这本书是我买的，要送给张老师。
pi: wǒ zhīdào, zhè běn shū shì wǒ mǎi de, yào sòng gěi zhāng lǎoshī
en: I know, I bought this book, I have to give it to Mr. Zhang
es: Lo sé, compré este libro, tengo que darselo a Mr. Zhang

问：这本书是送给谁的？
pi: zhè běn shū shì sòng gěi shéi de
en: who is this book for?
es: ¿para quién es este libro?

answer

a

*** 12
:PROPERTIES:
:CREATED: [2022-03-17 21:50:16 -05]
:ID: 43b723c8-b444-479e-a544-52d44998230d
:END:

alternatives

a

大卫
pi: dàwèi
en: David
es: David

b

李先生
pi: lǐ xiānshēng
en: Mr. Lee
es: Sr. Lee

c

不知道
pi: bù zhī dào
en: don't know
es: no se sabe

dialogue

女：大卫，上午有你的一个电话。
pi: dàwèi, shàngwǔ yǒu nǐ de yī ge diànhuà
en: David, you had a call this morning
es: David, alguien te llamo en la mañana

男：我知道，是李先生打的。
pi: wǒ zhīdào, shì lǐ xiānshēng dǎ de
en: I know, Mr. Li called
es: Lo sé, fue el Sr. Lee

问：上午的电话是谁打的？
pi: shàng wǔ de diànhuà shì shéi dǎ de
en: Who called this morning?
es: ¿Quién llamo en la mañana?

answer

b

*** 13
:PROPERTIES:
:CREATED: [2022-03-17 21:53:38 -05]
:ID: fc2efb16-a559-4aa0-86c6-9d85987692aa
:END:

alternatives

一年前
pi: yì nián qián
en: one year ago
es: hace 1 año

一年多了
pi: yì nián duō le
en: more than a year
es: más de un año

两年前
pi: liǎng nián qián
en: 2 years ago
es: hace 2 años

dialogue

女：你的汉语真好，你是什么时候开始学汉语的？
pi: nǐ de hànyǔ zhēn hǎo, nǐ shì shénme shíhou kāishǐ xué hànyǔ de
en: your chinese is really good, when did you start studying chinese?
es: tu chino es muy bueno ¿cuándo empezaste a estudiar chino?

男：两年前开始的，我来中国已经一年多了。
pi: liǎng nián qián kāishǐ de, wǒ lái zhōngguó yǐjīng yī nián duō le
en: I started two years ago, I've been in China for over a year now
es: empecé hace 2 años, he estado en China por más de un año

问：男的是什么时候开始学汉语的？
pi: nán de shì shénme shíhou kāishǐ xué hànyǔ de
en: when did the man started studying chinese?
es: ¿cuando el hombre empezó a estudiar chino?

answer

c

*** 14
:PROPERTIES:
:CREATED: [2022-03-17 22:04:16 -05]
:ID: 7e3a8f92-5f09-4a37-99aa-0936a8ce1a23
:END:

alternatives

很不喜欢
pi: hěn bù xǐhuan
en: not like it much
es: no me gusta mucho

非常喜欢
pi: fēicháng xǐhuan
en: really like it
es: realmente me gusta

不太喜欢
pi: bú tài xǐhuan
en: really not like it
es: realmente no me gusta

dialogue

女：你喜欢现在的工作吗？
pi: nǐ xǐhuan xiànzài de gōnzuò ma
en: do you like your current job?
es: ¿te gusta tu trabajo actual?

男：非常喜欢，我已经做了三年多了。
pi: fēicháng xǐhuan, wǒ yǐjīng zuò le sān nián duō le
en: I really like it, I've been doing it for more than three years
es: realmente me gusta, lo he estado haciendo por más de 3 años

问：他喜欢现在的工作吗？
pi: tā xǐhuan xiànzài de gōngzuò ma
en: does he like his current job?
es: ¿le gusta su trabajo actual?

answer

b

note

e: I confused 做 with 作 (character that is used in 工作).

*** 15
:PROPERTIES:
:CREATED: [2022-03-17 22:08:14 -05]
:ID: b264dd94-c0b6-4cff-ab99-98567d031420
:END:

alternatives

十年
pi: shí nián
en: 10 years
es: 10 años

不到十年
pi: bú dào shí nián
en: less than ten years
es: menos de diez años

十几年
pi: shí jǐ nián
en: more than ten years
es: más de 10 años

dialogue

女：你什么时候认识谢先生的？
pi: nǐ shénme shíhou rènshi xiè xiānshēng de
en: when did you meet Mr. Xie?
es: ¿cuándo conociste a Sr. Xie?

男：我们十年前认识的，他是我的大学同学。
pi: wǒmen shí nián qián rénshi de, tā shì wǒ de dàxué tóngxué
en: we met 10 years ago, he was my classmate at the university
es: nos conocimos hace 10 años, era mi compañero en la universidad

问：男的和谢先生认识多长时间了？
pi: nán de hé xiè xiānshēng rènshi duō chán shíjiān le
en: how long have the man and Mr. Xiè known each other?
es: ¿desde cuándo se conocen el hombre y el Sr. Xie?

answer

a

* Reading
:PROPERTIES:
:CREATED: [2022-03-17 22:14:43 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-18 00:16:12 -05]
:END:
*** 16
:PROPERTIES:
:CREATED: [2022-03-18 00:14:27 -05]
:END:

汤姆先生介绍我们认识的。


Answer

e

Notes

汤 | tāng :

姆 | mǔ :

汤姆 | tāngmǔ  | Tom | male given name | nombre de hombre ;

*** 17
:PROPERTIES:
:CREATED: [2022-03-18 00:14:30 -05]
:END:

爸爸已经回来了，他在看电视呢。

Answer: C

*** 18
:PROPERTIES:
:CREATED: [2022-03-18 00:14:34 -05]
:END:

昨天是我的生日，这是我丈夫送给我的。

Answer: A

*** 19
:PROPERTIES:
:CREATED: [2022-03-18 00:14:37 -05]
:END:

晚饭是李小姐帮我做的。

Answer: F

*** 20
:PROPERTIES:
:CREATED: [2022-03-18 00:14:39 -05]
:END:

张先生非常忙，晚上不能回家。

Answer: B

** 2
:PROPERTIES:
:CREATED: [2022-03-18 00:15:54 -05]
:ID: 9109c81c-0bf2-4a80-b8b5-89152d116850
:END:

Alternatives

介绍 | jièshào | to introduce, to recommend | introducir, recomendar | verb ;

帮 | bāng | to help, to assist | ayudar | verb ;

给 | gěi | to, for (used after a verb) | a, para (usado luego de un verbo) | preposition ;

非常 | fēicháng | very, extremely |  muy, extremadamete | adverb ;

贵 | guì | expensive | caro | adjective ;

已经 | yǐjīng | already | ya | adverb ;

介绍
帮
给
非常
贵
已经

*** 21
:PROPERTIES:
:CREATED: [2022-03-18 00:20:19 -05]
:END:

我身体不好，不能去学校，你//我给王老师打个电话吧。
帮

*** 22
:PROPERTIES:
:CREATED: [2022-03-18 00:21:54 -05]
:END:

明天是丽丽的生日，你想送//她什么？
给

*** 23
:PROPERTIES:
:CREATED: [2022-03-18 00:22:58 -05]
:END:

这本书//好，我们都看了，你也看看吧。
非常

*** 24
:PROPERTIES:
:CREATED: [2022-03-18 00:24:16 -05]
:END:

医生说你的病//好了，明天开始不吃这个药了。
已经

*** 25
:PROPERTIES:
:CREATED: [2022-03-18 00:44:57 -05]
:END:

你认识李先生吗？能不能给我//一下。
介绍

** 3

*** 26

妈妈做晚饭了，晚上我们回家吃饭吧。

他们晚上不出去吃饭。

*** 27

下午我睡觉的时候有一个电话，我没接。

我不知道电话是谁打的。

*** 28

明天是你的生日，明天晚上我不工作。

他明天晚上没有时间。

*** 29

你问一下爸爸什么时候去踢足球。

爸爸要踢足球。

*** 30

山姆，我给你介绍一下，这是我的大学同学谢力。

我和谢力是大学的时候认识的。

** 4
:PROPERTIES:
:ID: 142da49d-b004-41be-8fe9-939d2921449b
:END:

这本书是你什么时候写的？
昨天晚上的电话是谁打的？
你的汉字非常漂亮！
今天我非常高兴，你们多吃点儿。
他在哪儿呢？你看见他了吗？
这几天我不想吃饭，觉得很累。

*** 31

王方打的，她说今天不能去学校了。

*** 32

谢谢！我是大学的时候开始学的。

*** 33

是不是病了？你问一下医生吧。

*** 34

2011年吧，已经两年了。

*** 35

我们也很高兴，生日快乐！

