:PROPERTIES:
:CREATED: [2022-03-24 05:58:16 -05]
:END:

* Listening
:PROPERTIES:
:CREATED: [2022-03-25 01:29:45 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-25 01:41:41 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-03-25 01:33:02 -05]
:ID: 13242139-2990-4a5f-a354-d3b6c768f13e
:END:

我第一次跳舞是在七岁的时候。
pi: wǒ dì yí cì tiào wǔ shì zài qī suì de shíhou
en: the first time I danced was when I was 7 years old
es: la primera ves que bailé fue cuando tenía 7 años



answer

1

note

I was in doubt whether "zài" was 在 or 再

*** 2
:PROPERTIES:
:CREATED: [2022-03-25 01:33:04 -05]
:ID: def0fe40-2cd3-43e2-9689-109ece407049
:END:

这是他的第一个工作，他非常喜欢。
pi: zhè shì tā de dì yì ge gōngzuò, tā fēicháng xǐhuan
en: this is his first job, he really likes it.
es: este es su primer trabajo, realmente le gusta

answer

0

*** 3
:PROPERTIES:
:CREATED: [2022-03-25 01:35:08 -05]
:ID: 85a1bf8f-f5d5-4383-8ad6-44971be0092a
:END:

今天的汉语课，我都听懂了。
pi: jīntiān de hànyǔ kè, wǒ dōu tīngdǒng le
en: I understood all the chinese lesson today
es: entendí todas las clases de chino hoy

answer

1

error

According to the solutionary, a comma was not necessary. The following

今天的汉语课我都听懂了。

instead of the following

今天的汉语课，我都听懂了。

*** 4
:PROPERTIES:
:CREATED: [2022-03-25 01:37:02 -05]
:ID: cacae529-bae9-4c2c-933c-8c0dcbb85af4
:END:

你看，衣服都洗完了。
pi: nǐ kàn, yīfu dōu xǐ wán le
en: look, the laundtry is done
es: mira, la ropa está lavada

answer

1

*** 5
:PROPERTIES:
:CREATED: [2022-03-25 01:38:29 -05]
:ID: 5bb85b2d-080c-49cc-83c2-d2bb130904e5
:END:

考试的题太多了，我没有做完。
pi: kǎoshì de tí tài duō le, wǒ méiyǒu zuò wán
en: the exam had many questions, I didn't finish it
es: el examen tenía muchas preguntas, no lo terminé

answer

0

** 2
:PROPERTIES:
:CREATED: [2022-03-25 01:41:44 -05]
:END:

*** 6
:PROPERTIES:
:CREATED: [2022-03-25 01:42:14 -05]
:ID: db669026-1bcf-4ba1-9b73-7936d7ac0e9e
:END:

男：你从几岁开始学跳舞？
pi: nǐ cóng jǐ suì kāishǐ xué tiàowǔ
en: at what age did you start practicing dancing?
es: ¿A qué edad empezaste a practicar baile?

女：我第一次跳舞是在七岁的时候。
pi: wǒ dì yí cì tiǎo wǔ shì zài qī suí de shíhou
en: la primera vez que empecé a bailar fue cuando tenía 7 años
es: the first time I started dancing was when I was 7 years old

answer

b

*** 7
:PROPERTIES:
:CREATED: [2022-03-25 01:45:41 -05]
:ID: 4c72441f-8cb2-48d3-a3cb-15c7a80f8840
:END:

女：今天的考试怎么样？
pi: jīntiān de kǎoshì zěnmeyàng
en: how was the exam today?
es: ¿cómo estuvo el examen hoy?

男：不太好，有几个题没有做完。
pi: bú tài hǎo, yǒu jǐ ge tí méi yǒu zuò wán
en: not so good, I didn't finish a few questions
es: no tan bien, no terminé algunas preguntas

answer

c

*** 8
:PROPERTIES:
:CREATED: [2022-03-25 01:49:04 -05]
:ID: 931773d0-c0d4-477b-aac9-d6448b35cc68
:END:

男：你看见我的手机了吗？
pi: nǐ kànjiàn wǒ de shǒujī le ma 
en: have you seen my phone?
es: ¿has visto mi teléfono?

女：就在桌子上面，你看见了没有？
pi: jiù zài zhuōzi shàngmian, nǐ kànjiàn le méiyǒu
en: it's right on top of the table, didn't you see it?
es: está encima de la mesa, no lo viste?

answer

a

note

e: I confused the pronunciatino of 就 (jiù) with 住 (zhù)

*** 9
:PROPERTIES:
:CREATED: [2022-03-25 01:52:43 -05]
:ID: 9a5102cc-5058-4d5e-b23f-9fb2a6888acf
:END:

女：这么多的衣服，你一个人能洗完吗？
pi: zhè me duō de yīfu, nǐ yī gè rén néng xǐ wán ma
en: all these clothes, can you wash all the clothes by yourself?
es: todas estas prendas ¿lo puedes lavar por tu cuenta?

男：你现在有时间吗？帮我一起洗吧。
pi: nǐ xiànzài yǒu shíjiān ma? bāng wǒ yīqǐ xǐ ba
en: do you have time now? help me wash the clothes
es: ¿tienes tiempo ahora? ayudame a lavar la ropa

answer

e

*** 10
:PROPERTIES:
:CREATED: [2022-03-25 01:58:48 -05]
:ID: 1c6278fd-e3fe-458b-9949-eb7b63a8f86b
:END:


Ａ：这是我第一次去大医院，医院里人真多啊。
pi: zhè shì wǒ dì yì cì qǔ dà yīyuàn, yīyuàn lǐ rén zhēn duō
en: this is my first time I go o a big hopsital, it is very crowded inside
es: está es la primera vez que voy a un hospital grande, hay mcuhas personas

Ｂ：是啊。
pi: shì a
en: good
es: bien

answer

f

note

e: I couldn't recognize 人真

** 3

*** 11
:PROPERTIES:
:ID: 5db2ff40-dbd7-49b2-a4ee-6900be2caa30
:END:


alternatives

a

想找女的。
pi: xiǎng zhǎo nǚ de
en: wants to find the woman
es: quiere encontrar a la mujer

b

想找张欢。
pi: xiǎng zhǎo zhāng huān
en: wants to find Zhang Huan
es: quiere encontrar a Zhang Huan

c

想去看看张欢。
pi: xiǎng qù kànkan zhāng huān
en: wants to go to see Zhang Huan
es: quiere ir a ver a Zhang Huan

dialogue

男：你好，请问，张欢在吗？
pi: nǐ hǎo, qǐngwèn, zhāng huān zài ma
en: hello, please, is Zhang Huan there?
es: hola, por favor ¿está Zhang Huan ahí?

女：对不起，我们这儿没有张欢，你打错电话了。
pi: duìbuqǐ, wǒmen zhèr méiyǒu zhāng huān, nǐ dǎ cuò diànhuà le
en: I'm sorry, we don't have someone called Zhang Huan here, you called the wrong number
es: Lo siento, no tenemos a nadie llamado Zhang Huan acá, te confundiste de número

问：男的为什么要打电话？
pi: nán de wèi shénme yào dǎ diànhuà
en: why did the man called?
es: ¿por qué el hombre llamó?

answer

b

*** 12
:PROPERTIES:
:ID: 10b741ff-cd45-41c4-bdf7-c2b17a172504
:END:

alternatives

昨天
pi: zuótiān
en: yesterday
es: ayer

今天
pi: jīntiān
en: today
es: hoy

明天
pi: míngtiān
en: tomorrow
es: mañana

dialogue

男：买到电影票了没有？今天晚上的。
pi: mǎi dào diànyǐng piào le méiyǒu? jīntiān wǎnshang de
en: have you bought movie tickets for tonight?
es: ¿has comprado entradas para la película en la noche?

女：买到了，是明天的，今天的都买完了。
pi: mǎi dào le, shì míngtiān de, jīntiān de dōu mǎi wán le
en: I bought, they are for tomorrow, today's tickets sold out
es: sí compré, son para mañana, las de hoy día se acabaron

问：他们什么时候去看电影？
pi: tāmen shénme shíhou qù kàn diànyǐng
en: when are they going to watch movies?
es: ¿cuándo irán a ver películas?

answer

c

*** 13
:PROPERTIES:
:ID: 4e8d2c07-f204-427f-9cdc-5df1e28e8809
:END:

alternatives

a

学校
pi: xuéxiào
en: school
es: colegio

b

医院
pi: yīyuàn
en: hospital
es: hospital

c

公司
pi: gōngsī
en: cmopany
es: empresa

dialogue

女：你真的认识去医院的路，是不是走错了？
pi: nǐ zhēn de rènshi qù yīyuàn lù, shì bú shì zǒu cuò le
en: do you really know the way to the hospital? is this the wrong way?
es: ¿realmente conoces el camino al hospital? ¿este es el camino incorrecto?

男：没错，就在那个公司的前面，学校的后面。
pi: méi cuò, jiù zài nǎ ge gōngsī de qiánmian, xuéxiào de hòumian
en: we are not wrong, it is right in front of that company, behind the school
es: no estamos mal, está justo al costado de la compañia, atrás del colegio

问：他们想去哪儿？
pi: tāmen xiǎng qù nǎr
en: where do they want to go?
es: ¿a dónde quieren ir?

answer

a

note

I confused 走 with 错. I wrote 走走 instead of 走错. I thought that the repetition of 走 twice made sense there.

I consued 走 with 错 in the sentence of the woman

I confused 就 with 住

*** 14
:PROPERTIES:
:ID: 4c3390ed-cadc-4f3d-9874-3de8b8ceb6ca
:END:

alternatives


没看见
pi: méi kànjiàn
en: she didn't see it
es: ella no lo vio

看见了
pi: kànjiàn le
en: she watched it
es: ella lo vio

没有报纸
pi: méi yǒu bàozhǐ
en: there was no newspaper
es: no había ningún periódico

dialogue

男：看见了没有？报纸就在电视的左边。
pi: kànjiàn le méiyǒu? bàozhǐ jiù zài diànshì de zuǒbian
en: you see? the newspaper is just to the left of the TV
es: ¿ves? el periódico está justo a la izquierda del televisor

女：等一下，你这儿的东西太多了。
pi: děng yí xià, ni zhèr de dōngxi tài duō le
en: wait a moment, you have lots of things here
es: espera un momento, tienes demasiadas cosas aquí

question

问：女的看见报纸了没有？
pi: nǚ de kànjiàn bàozhǐ le méi yǒu
en: did the woman see the newspaper?
es: ¿la mujer vio el periódico?

answer

a

note

I consued 住 with 就. I thought that 住 made sense there, but I didn't know the meaning of that word.

*** 15
:PROPERTIES:
:ID: ef9d0588-ffe2-4b70-b469-76b03707d386
:END:

alternatives

a

没听懂
pi: méi tīngdǒng
en: he didn't understand what he heard
es: no entendió lo que escuchó

b

不会做
pi: bú huì zuò
en: she couldn't do it
es: no lo pudo hacer

c

没做完
pi: méi zuòwán
en: didn't finish
es: no lo acabó

dialogue

男：昨天的考试怎么样？都做完了没有？
pi: zuótiān de kǎoshì zěnmeyàng? dōu zuò wán le méiyǒu
en: how was yesterday's exam? did you finish it all?
es: ¿cómo estuvo el examen de ayer? ¿acabaste todo?

女：题太多，我没做完。
pi: tí tài duō, wǒ méi zuò wán
en: there were so many questions, I didn't finish
es: habían muchas preguntas, no lo acabé

question

问：她作天的考试怎么样？
pi: tā zuótiān de kǎoshì zěnmeyàng
en: how did she find yesterday's exam?
es: ¿cómo le pareció el examen de ayer?

answer

c

note

I couldn't identify 都做完 (dōu zuò wán).

I wrote 蹄 instead of 题

* Reading
:PROPERTIES:
:CREATED: [2022-03-24 05:58:33 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-24 06:11:33 -05]
:END:

*** 16
:PROPERTIES:
:CREATED: [2022-03-24 05:58:36 -05]
:END:

非常欢迎你来我们公司上班。
pi: fēicháng huānyíng nǐ lái wǒmen gōngsī shàng bān
en: you are very welcome to work in our company
es: eres muy bienvenido a trabajar en nuestra empresa

answer

e

*** 17
:PROPERTIES:
:CREATED: [2022-03-24 06:03:08 -05]
:END:

吃完晚饭后，她还要慢跑一个小时。
pi: chīwán wǎnfàn hòu, tā hái yào màn pǎo yí ge xiǎoshí
en: after eating dinner, she has to jog for an hour
es: después de cenar, tiene que trotar por una hora

answer

a

notes

慢跑 | màn pǎo | jogging | trotar | verb

*** 18
:PROPERTIES:
:CREATED: [2022-03-24 06:03:10 -05]
:END:

考试不难，我都做对了。
pi: kǎoshì bù nán, wǒ doū zuò duì le
en: the exam wasn't difficult, I did everything right
es: el examen no estuvo difícil, hice todo bien

answer

f

note

难 | nán | difficult | difícil | adjective ;

難 | nán | difficult | difícil | adjective ;

*** 19
:PROPERTIES:
:CREATED: [2022-03-24 06:06:04 -05]
:END:

我希望能和朋友们一起过生日。
pi: wǒ xīwàng néng hé péngyoumen yìqǐ guò shēngrì
en: I wish I could spend my birthday with my friends
es: espero que pueda celebrar mi cumpleaños con mis amigos

answer

b


*** 20
:PROPERTIES:
:CREATED: [2022-03-24 06:08:24 -05]
:END:

从我家到学校要坐一个多小时的公共汽车。
pi: cóng wǒ jiā dào xuéxiào yào zuò yí ge duō xiǎoshí de gōnggòngqìchē
en: from my house to the school, it takes more than hour by bus
es: desde mi casa a la escuela, toma más de una hora ir en bus

answer

c

** 2
:PROPERTIES:
:CREATED: [2022-03-24 06:11:37 -05]
:ID: a2c4d61f-7c01-467e-a261-2ccdde278fad
:END:

上班
从
希望
问题
贵
懂

*** 21
:PROPERTIES:
:CREATED: [2022-03-24 06:11:48 -05]
:END:

我每天//八点到十二点都在公司工作。
从
pi: wǒ měitiān cóng bā diǎn dào shí'èr diǎn dōu zài gōngsī gōngzuò
en: I work every day in the office from 8 to 12
es: trabajo en la oficina todos los días de 8 a 12

*** 22
:PROPERTIES:
:CREATED: [2022-03-24 06:11:49 -05]
:END:

我家离公司不太远，所以每天走路去//。
上班
pi: wǒ jiā lí gōngsī bú tài yuǎn, suǒyǐ měitiān zǒu lù qù shàng bān
en: my house is not very far from the company, so I walk to work every day
es: mi casa no está lejos de la empresa, así que todos los días camino

*** 23
:PROPERTIES:
:CREATED: [2022-03-24 06:11:50 -05]
:END:

今天的课你都听//了没有？
懂
pi: jīntiān de kè nǐ dōu tīngdǒng le méiyǒu
en: did you understand everything from today's class?
es: ¿entendiste todo de la clase de hoy?

*** 24
:PROPERTIES:
:CREATED: [2022-03-24 06:11:51 -05]
:END:

你有什么//都可以问老师。
问题
pi: nǐ yǒu shénme wèntí dōu kěyǐ wèn lǎoshī
en: you can ask your teacher any questions you may have
es: puedes preguntar a tu profesor cualquier duda que tengas

*** 25
:PROPERTIES:
:CREATED: [2022-03-24 06:11:59 -05]
:END:

我//能找到一个好的工作。
希望
pi: wǒ xīwàng néng zhǎo dào yí ge hǎo de gōngzuò
en: I hope to find a good job
es: espero encontrar un buen trabajo


** 3

*** 26

我女儿已经六岁了，我希望她能跟您学唱歌。

她女儿唱歌非常好。

*** 27

这是他的第一个工作，从下个星期开始上班，希望他能喜欢这个工作。

他还没有上班呢。

*** 28

昨天的考试不太难，题很多，我有两个题没有做完。
pi: zuótiān de kǎoshì bú tài nán, tī hěn duō, wǒ yǒu liǎng ge tí méi yǒu zuò wán
en: yesterday's exam wasn't really difficult, there were many questions, I didn't answer two questions
es: el examen de ayer no estuvo muy difícil, habían muchas preguntas, no pude responder 2 preguntas

这次考试题很多，很难。
pi: zhè cì kǎoshì tí hěn duō, hěn nán
en: this exam had many questions and it was difficult
es: este examen tuvo muchas preguntas y estuvo difícil

answer

0

reasoning

这次考试题很多，但是它是不太难，所以它是不很难。
pi: zhè cì kǎoshì tí hěn duō, dànshì tā shì bú hěn nán, suǒyǐ tā shì bú hěn nán
en: this exam had a lot of qusetions but it is not too difficult, so it is not very difficult
es: este examen tuvo muchas preguntas, pero no estuvo difícil, así que no estuvo muy difícil

*** 29

今天是9月20号，再有三天就是爸爸的生日了。我想送他一个薪手机。
pi: jīntiān shì 9 yuè 20 hào, zài yǒu sān tiān jiù shì bàba de shēngrì le. wǒ xiǎng sòng tā yí ge xīn shǒujī
en: today is September 20th, three more days until dad's birthday. I want to give him a new phone
es: hoy es 20 de setiembre, tres días mas hasta el cumpleaños de papá. Quiero darle un nuevo celular

9月23号是我的生日。
pi: 9 yuè 23 hào shì wǒ de shēngrì
en: my birthday is on September 23th
es: mi cumpleaños es el 23 de setimebre

answer

0

*** 30

我的一个朋有正在找房子，希望离公司近一些，这样他每天七点起床就可以了。
pi: wǒ de yí ge péngyou zhèngzài zhǎo fángzi, xīwàng lí gōngsī jìn yìxiē, zhèyàng tā měitīan qī diǎn qǐ chuáng jiù kěyǐ le
en: uno de mis amigos está buscando un apartamento, quiere que esté más cerca de la oficina para poder levantarse a las 7 de la mañana todos los días
es: one of my friends is looking for a room, he wishes it is closer to the company so that every day he can wake up at 8 o'clock

他的朋有现在每天七点起床。
pi: tā de péngyǒu xiànzài měitiān qī diǎn qǐ chuáng
en: nowadays his friend wakes up every day at 7 o'clock
es: actualmente su amigo se levanta todos los días a las 7

answer

0

** 4
:PROPERTIES:
:ID: c13c1dfb-e2e2-4cc1-b0b1-41571374f1e5
:END:

就在前面，你还没看见吗？
非常好，我想明年再来一次。
还可以，都做完了。
这些衣服你一个人能洗完吗？
他在哪儿呢？你看见他了吗？
等等我，我也想去。

*** 31

昨天的考试怎么样？题都做完了吗？

*** 32

没关系，今天洗一些，明天再洗一些。

*** 33

你看见我哥哥了吗？

*** 34

羊肉吃完了，我再去商店买一些吧。

*** 35

第一次来北京吧？北京漂亮吗？

