* 听力

** 第二部分
:PROPERTIES:
:ID: 57a42d26-8960-4ff3-800c-54ee031f954e
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：今天来参加我们访谈节目的是年轻朋友非常崇拜的著名节目主持人刘可心。欢迎您！您知道年轻朋友私底下怎么称呼您吗？
男：“可心同学”？
女：对。
男：可以这么叫我。我喜欢这个称呼。
女：那好，咱们就这么叫了。可心同学，很多听众喜欢听您说话，认为您思维角度与众不同，听您说话不只是听听而已，关键是总能受到启发。
男：过奖了。我之所以能成为今天的我，无非是和读书，特别是和读名著有关。阅读经典，肯定会对我们的人生产生影响。比如，我小时候对“美”和“丑”的理解，就跟读法国作家雨果的《巴黎圣母院》有关，这本书让我意识到，不能光凭外表长得不好看就觉得这个人也不好。
女：名著这么好，有些孩子怎么就是不愿意读呢？
男：主要是因为老师家长把这事当任务布置给孩子，孩子就会觉得很累，甚至反感。读书不能勉强，其实读名著是件很好玩儿的事情，名著都是经受住了历史考验的。所以，家长要让孩子带着好奇心去读，他就有了动力。
女：您的孩子喜欢读书吗？这不是隐私吧？
男：当然不是。我的孩子非常喜欢读书。
女：他读的第一本书是什么，您还记得吗？
男：他认真读的第一本书是武侠小说。
女：哦？
男：在读书方面，我给他非常大的自由。我觉得最重要的是让他在年少时喜欢读书，而不是读哪本书。
女：听说您的孩子马上就要高考了，而且选择的是历史？
男：对，应该说他的选择跟他的阅读经历有关，他读金庸的武侠小说着迷，读完一遍还想读第二遍，书里涉及一些他不懂的内容，就到处查书查资料，这样他的阅读面就会不断向外延伸。
女：这么说，名著也不需要读全？您怎么看古人说过的“读万卷书行万里路”？
男：在我看来，不管行万里路还是读万卷书，关键得看走不走心，到哪儿赶紧拍照，奔下一个景点，万里路固然是走了，可一点儿用都没有。即使你没读万卷书，但把 10 本书给读明白了，要比囫囵吞枣读 100 本书好得多。

**** 音频

74a36d54-4368-47ab-b1b7-4e8b3337ba86.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1aead7c4-4e7e-4c12-bf50-1f08391698fc
:END:

***** 问题

关于刘可心，可以知道什么？

****** 音频

a2847335-119d-4770-9b75-c11b917e85ec.mp3

***** 选择

****** A

他很受年轻人欢迎

****** B

他还没工作，是个学生

****** C

他的话没有太大的价值

****** D

他总能从生活中受到启发

***** 答案

A

**** 7
:PROPERTIES:
:ID: 7c5c9da6-682b-4d75-bca5-0611a78f1eab
:END:

***** 问题

刘可心怎么评价自己？

****** 音频

fb29d2bd-5e35-4644-8a27-333ff87048c4.mp3

***** 选择

****** A

他在睇儿都会受表扬

****** B

他的成功和读书有关

****** C

他一直喜欢法国小说

****** D

人长相难看心眼儿才好

***** 答案

B

**** 8
:PROPERTIES:
:ID: e458609a-6cdf-4317-816c-deb14ff344b0
:END:

***** 问题

刘可心认为有的孩子不愿意读名著的原因是什么？

****** 音频

215fab1f-8b0b-428f-8ef2-c8d279d1e1e6.mp3

***** 选择

****** A

孩二们学习太紧张

****** B

家长自己就不读书

****** C

孩二们没找到好书

****** D

大人的方法有问题

***** 答案

D

**** 9
:PROPERTIES:
:ID: beb8f4f4-572a-497d-a00b-2a57f33b8896
:END:

***** 问题

关于刘可心的孩子，下列哪项正确？

****** 音频

64efc845-e40b-4304-ba90-40943096a700.mp3

***** 选择

****** A

读书使他喜欢上了历史

****** B

每本书他都会认真读完

****** C

每部小说他都会反复看

****** D

父亲喜欢武侠他也喜欢

***** 答案

A

**** 10
:PROPERTIES:
:ID: 7af910a9-fe70-4069-8cdb-481c00aca1ca
:END:

***** 问题

对“读万卷书行万里路”，刘可心怎么看？

****** 音频

f82caf6d-cf23-41f9-9b42-9e0221f35877.mp3

***** 选择

****** A

书当然是读得越多越好

****** B

行万里路一点儿用都没有

****** C

读书不在多少，关键是用心

****** D

天天忙着旅游就没法读书了

***** 答案

C

** 第一部分

*** 1

**** 选择

***** A

他每天都学习英语

***** B

他白天工作特别多

***** C

他每天很晚才睡觉

***** D

他晚上一直没睡着

**** 段话

活儿总算忙完了，他累得都要崩溃了，满脑子都是客户和协议。虽然困得要死，可躺在床上颠来倒去睡不着，心烦意乱之中，突然听到儿子的房间传来了朗读英语的声音，轻柔、平静，不知不觉中，他竟入睡了。

***** 音频

4d9de802-ce66-4dad-a4c6-791a7d3d25de.mp3

**** 答案

B

*** 2

**** 选择

***** A

头发是否变白和人的肤色有关

***** B

头发变白说明人各种机能变好

***** C

头发的颜色取决于黑色素的多少

***** D

黑色素的多少决定着头发的多少

**** 段话

人的头发中有一种叫作黑色素的物质，黑色素越多头发的颜色越黑，黑色素少了，头发便会发黄或变白。人进入老年，身体的各种机能会逐渐衰退，色素也会越来越少，所以头发就会渐渐变白。

***** 音频

18799a1f-b801-4732-952c-00006536ebad.mp3

**** 答案

C

*** 3

**** 选择

***** A

1915年中国有了清明节

***** B

1928年中国首创植树节

***** C

很多省市有自己的植树节

***** D

植树节在每年的3月12号

**** 段话

1915 年中国将清明节定为植树节，1928 年将植树节改为 3 月 12 日，这一设定一直沿用至今。此外，一些省市还根据当地的气候规律，规定了其他的植树日、植树周、植树月。

***** 音频

a8473ed7-d75d-4b7c-8f2b-387b8944f7fb.mp3

**** 答案

D

*** 4

**** 选择

***** A

盘文强从小生活在农村

***** B

意文强的作品取材海洋

***** C

盛文强很会讲民间故事

***** D

盛文强特别喜欢看小说

**** 段话

盛文强长期从事海洋民间故事的采集整理，并出版了多部海洋题材小说。作为传统的农业国家，中国文学中的农业元素太多了，所以盛文强的“海洋文学”出现在读者面前时，不免让人眼前一亮。

***** 音频

2c62cb1e-9f13-4b8c-b992-7bc7ccea521c.mp3

**** 答案

B

*** 5

**** 选择

***** A

狗追近丁，兖子才会躲开

***** B

免子看到狗就会拼命地跑

***** C

兖二看到狗就会心神不定

***** D

我专程去郊外看狗追免子

**** 段话

5. 我带着狗去郊游，狗发现了野兔就兴奋地前去追赶。野兔明明知道狗来了，却像没这事一样，照样坐在那儿吃草，直到狗跑近了，野兔才一跃而起，迅速跑开，当它跑到自认为安全的地方，便又马上安定下来。

***** 音频

d23170e5-df13-4e5b-ba35-4562cdea0466.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

我们常常会听到家长感叹，现在的孩子，能安安静静坐下来看书的实在太少。想想我们小的时候，一本书在同学之间传来传去，大家迫不及待地轮流传阅，兴致勃勃地捧着一本书，如痴如醉……那样的乐趣，我们的孩子为什么就完全没有感觉呢？

王先生常抱怨，儿子小的时候，自己每天晚上给他读故事，本以为他长大了，在读书方面，会成为自己的知音。现实却并非如此，儿子对老师推荐的书、家长给他买的书好像都没兴致，偶尔翻看一下，不过是应付老师和家长。

在浮躁的现代生活氛围中，借助互联网和各色电子产品，人们可以接触到最新娱乐资讯，可以在卡通动漫和电脑游戏中得到放松。人们将大量时间耗费在手机、电脑与电视机前。因此，如何让心灵回归沉静，已经成为摆在人们面前的难题。

**** 题目

***** 11

****** 选择

******* A

孩子们安静不下来

******* B

孩子们不喜欢看书

******* C

自己小时候没有书看

******* D

自己小时候没钱买书

****** 问题

家长常为什么事感叹？

****** 答案

B

***** 12

****** 选择

******* A

儿子对自己很反感

******* B

儿子长大了,不听话了

******* C

儿子长大后并不爱读书

******* D

现在的老师不为学生着想

****** 问题

王先生常抱怨什么？

****** 答案

C

***** 13

****** 选择

******* A

怎样远离电脑游戏

******* B

怎样让心灵安静下来

******* C

怎样克服互联网的弊端

******* D

如何让娱乐资讯有深度

****** 问题

如今摆在人们面前的难题是什么？

****** 答案

B

*** 14-17

**** 课文

有人说学好外语就得努力学、拼命学，得有大把的时间，我却说学外语就得“见缝插针”。所谓“见缝插针”，就是要把一般人看着不起眼的零碎时间都利用起来。可千万别看不起这几分钟十几分钟的时间，根据记忆心理学的原理，对于外语等以机械记忆为主的学习内容，及时地利用零碎时间进行复习，效果是很好的，学了就搁在一边，等于没学。

“见缝插针”的另一种方式就是把外语学习和日常生活联系起来，处处学，时时学，事事学。只要有了学习外语的强烈愿望和兴趣，日常生活的各个方面都可以成为外语学习的第二课堂，而且在日常生活中学到的外语记得快、记得牢，学习效果特别好。

“见缝插针”时间长了，就会感到外语学习已成为自己生活中不可缺少的内容，就会感到学习外语是一种乐趣和享受，一天不学就好像缺了点儿什么。

**** 题目

***** 14

****** 选择

******* A

工作给别人,自己学外语

******* B

有了充足的时间再学外语

******* C

别人看电视时自己学外语

******* D

多么短的时间都利用起来

****** 问题

怎样“见缝插针”学外语？

****** 答案

D

***** 15

****** 选择

******* A

有新鲜感

******* B

有成就感

******* C

有利于记忆

******* D

不浪费时间

****** 问题

“见缝插针”学外语的好处是什么？

****** 答案

C

***** 16

****** 选择

******* A

在日常生活中学习

******* B

培养学外语的兴趣

******* C

锻炼自己的记忆力

******* D

和外国人多多接触

****** 问题

“见缝插针”的另一种学习方式是什么？

****** 答案

A

***** 17

****** 选择

******* A

工作忙不是学不好外语的借口

******* B

学习外语的过程也是一种享受

******* C

只要有时间就不会学不好外语

******* D

会“见缝插针“的人都能成功

****** 问题

这段话告诉我们什么？

****** 答案

A

