* 听力

** 1

*** 1

**** transcript

活儿总算忙完了，他累得都要崩溃了，满脑子都是客户和协议。虽然困得要死，可躺在床上颠来倒去睡不着，心烦意乱之中，突然听到儿子的房间传来了朗读英语的声音，轻柔、平静，不知不觉中，他竟入睡了。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

人的头发中有一种叫作黑色素的物质，黑色素越多头发的颜色越黑，黑色素少了，头发便会发黄或变白。人进入老年，身体的各种机能会逐渐衰退，色素也会越来越少，所以头发就会渐渐变白。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

1915年中国将清明节定为植树节，1928年将植树节改为3月12日，这一设定一直沿用至今。此外，一些省市还根据当地的气候规律，规定了其他的植树日、植树周、植树月。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

盛文强长期从事海洋民间故事的采集整理，并出版了多部海洋题材小说。作为传统的农业国家，中国文学中的农业元素太多了，所以盛文强的“海洋文学”出现在读者面前时，不免让人眼前一亮。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

我带着狗去郊游，狗发现了野兔就兴奋地前去追赶。野兔明明知道狗来了，却像没这事一样，照样坐在那儿吃草，直到狗跑近了，野兔才一跃而起，迅速跑开，当它跑到自认为安全的地方，便又马上安定下来。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 57a42d26-8960-4ff3-800c-54ee031f954e
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：今天来参加我们访谈节目的是年轻朋友非常崇拜的著名节目主持人刘可心。欢迎您！您知道年轻朋友私底下怎么称呼您吗？
男：“可心同学”？
女：对。
男：可以这么叫我。我喜欢这个称呼。
女：那好，咱们就这么叫了。可心同学，很多听众喜欢听您说话，认为您思维角度与众不同，听您说话不只是听听而已，关键是总能受到启发。
男：过奖了。我之所以能成为今天的我，无非是和读书，特别是和读名著有关。阅读经典，肯定会对我们的人生产生影响。比如，我小时候对“美”和“丑”的理解，就跟读法国作家雨果的《巴黎圣母院》有关，这本书让我意识到，不能光凭外表长得不好看就觉得这个人也不好。
女：名著这么好，有些孩子怎么就是不愿意读呢？
男：主要是因为老师家长把这事当任务布置给孩子，孩子就会觉得很累，甚至反感。读书不能勉强，其实读名著是件很好玩儿的事情，名著都是经受住了历史考验的。所以，家长要让孩子带着好奇心去读，他就有了动力。
女：您的孩子喜欢读书吗？这不是隐私吧？
男：当然不是。我的孩子非常喜欢读书。
女：他读的第一本书是什么，您还记得吗？
男：他认真读的第一本书是武侠小说。
女：哦？
男：在读书方面，我给他非常大的自由。我觉得最重要的是让他在年少时喜欢读书，而不是读哪本书。
女：听说您的孩子马上就要高考了，而且选择的是历史？
男：对，应该说他的选择跟他的阅读经历有关，他读金庸的武侠小说着迷，读完一遍还想读第二遍，书里涉及一些他不懂的内容，就到处查书查资料，这样他的阅读面就会不断向外延伸。
女：这么说，名著也不需要读全？您怎么看古人说过的“读万卷书行万里路”？
男：在我看来，不管行万里路还是读万卷书，关键得看走不走心，到哪儿赶紧拍照，奔下一个景点，万里路固然是走了，可一点儿用都没有。即使你没读万卷书，但把 10 本书给读明白了，要比囫囵吞枣读 100 本书好得多。

*** 音频

74a36d54-4368-47ab-b1b7-4e8b3337ba86.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1aead7c4-4e7e-4c12-bf50-1f08391698fc
:END:

***** 问题

关于刘可心，可以知道什么？

***** 音频

a2847335-119d-4770-9b75-c11b917e85ec.mp3

***** 选择

****** A

他很受年轻人欢迎

****** B

他还没工作，是个学生

****** C

他的话没有太大的价值

****** D

他总能从生活中受到启发

***** 答案

A

**** 7
:PROPERTIES:
:ID: 7c5c9da6-682b-4d75-bca5-0611a78f1eab
:END:

***** 问题

刘可心怎么评价自己？

***** 音频

fb29d2bd-5e35-4644-8a27-333ff87048c4.mp3

***** 选择

****** A

他在睇儿都会受表扬

****** B

他的成功和读书有关

****** C

他一直喜欢法国小说

****** D

人长相难看心眼儿才好

***** 答案

B

**** 8
:PROPERTIES:
:ID: e458609a-6cdf-4317-816c-deb14ff344b0
:END:

***** 问题

刘可心认为有的孩子不愿意读名著的原因是什么？

***** 音频

215fab1f-8b0b-428f-8ef2-c8d279d1e1e6.mp3

***** 选择

****** A

孩二们学习太紧张

****** B

家长自己就不读书

****** C

孩二们没找到好书

****** D

大人的方法有问题

***** 答案

D

**** 9
:PROPERTIES:
:ID: beb8f4f4-572a-497d-a00b-2a57f33b8896
:END:

***** 问题

关于刘可心的孩子，下列哪项正确？

***** 音频

64efc845-e40b-4304-ba90-40943096a700.mp3

***** 选择

****** A

读书使他喜欢上了历史

****** B

每本书他都会认真读完

****** C

每部小说他都会反复看

****** D

父亲喜欢武侠他也喜欢

***** 答案

A

**** 10
:PROPERTIES:
:ID: 7af910a9-fe70-4069-8cdb-481c00aca1ca
:END:

***** 问题

对“读万卷书行万里路”，刘可心怎么看？

***** 音频

f82caf6d-cf23-41f9-9b42-9e0221f35877.mp3

***** 选择

****** A

书当然是读得越多越好

****** B

行万里路一点儿用都没有

****** C

读书不在多少，关键是用心

****** D

天天忙着旅游就没法读书了

***** 答案

C

