:PROPERTIES:
:CREATED: [2022-03-22 19:40:21 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-03-22 17:51:27 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-22 17:57:17 -05]
:END:

1. c

黑 | hēi | dark | oscuro | noun ;

2. d

天气 | tiānqì | weather | clima | noun ;

3. a

运动 | yùndòng | sport | deporte | noun ;

4. f

服务员 | fúwùyuán | waiter, waitress | mozo, moza, noun ;

5. b

等 | děng | to wait | esperar | verb ;

6. e

白 | bái | blank | blanco | noun ;

** 2
:PROPERTIES:
:CREATED: [2022-03-22 17:57:12 -05]
:END:

Try to say the antonyms of the following words

word

大 | dà | big | grande | adjective ;

小 | xiǎo | small, little | pequeño | adjective ;

word

多 | duō | more | más | noun ;

少 | shǎo | little, few | poco | adjective ;


word

快 | kuài | fast | rápido | adjective ;

慢 | màn | slow | lento | adjective ;

word

冷 | lěng | cold | frío | ;

热 | rè | hot | calor | ;

word

上 | shàng | above | arriba | ;

下 | xià | below | abajo | ;

word

黑 | hēi | dark | oscuro | noun ;

白 | bái | white | blanco | noun ;

* Text
:PROPERTIES:
:CREATED: [2022-03-22 18:05:01 -05]
:END:

** 1. 在学校 | In the classroom
:PROPERTIES:
:CREATED: [2022-03-22 18:06:33 -05]
:ID: 958d8e05-8089-4f19-945a-f5fe21253a63
:END:

dialogue

Ａ：我们下午去看电影，好吗？
pi: wǒmen xiàwǔ qù kàn diànyǐng, hǎo ma
en: we'll go to the movies this afternoon, okay?
es: vayamos en la tarde a ver una película ¿está bien?

Ｂ：今天下午我没有时间，明天下午再去吧。
pi: jīntiān xiàwǔ wǒ méiyǒu shíjiān, míngtiān xiàwǔ zài qù ba
en: this afternoon I don't have time, let's go tomorrow's afternoon
es: esta tarde no tengo tiempo, vayamos mañana por la tarde

Ａ：你想看什么电影？
pi: nǐ xiǎng kàn shénme diànyǐng
en: what do you want to watch?
es: ¿qué quieres ver?

Ｂ：让我想想再告诉你。
pi: ràng wǒ xiǎngxiang zài gàosu nǐ
en: let me think and I'll tell you later
es: dejame pensar y te diré luego

new words

再 | zài | again, once more | de nuevo, una vez más | adverb ;

让 | ràng | to let, to allow | dejar | verb ;

告诉 | gàosù | to tell | decir | verb ;

** 2. 在宿舍
:PROPERTIES:
:CREATED: [2022-03-22 18:06:35 -05]
:ID: 391bebc5-a139-40bf-9d4d-c28ffe1ba243
:END:

dialogue

Ａ：外边天气很好，我们出去运动运动吧！
pi: wàibian tiānqì hěn hǎo, wǒmen chūqu qù yùndòng yùndòng ba
en: it's a nice day outside, let's go out do some exercise
es: hace un buen clima, vayamos a hacer ejerrcicio

Ｂ：你等等我，好吗？王老师让我给大卫打个电话。
pi: nǐ děngdeng wǒ, hǎo ma? wáng lǎoshī ràng wǒ gěi dàwèi dǎ ge diànhuà
en: you wait for me, okay? Mr. Wang asked me to call David
es: me esperas, si? El Sr. Wang me pidió que llamara a David

Ａ：回来再打吧。找大卫有什么事情吗？
pi: huílai zài dǎ ba. zhǒu dàwèi yǒu shénme shíqing ma
en: call him after we come back. what's the matter?
es: llamalo despues que lleguemos ¿qué ocurrió con david?


Ｂ：听说大卫病了，我想找时间去看看他。
pi: tīngshuō dàwèi bìng le, wǒ xiǎng zhǎo shíjiān qù kànkan tā
en: i heard that David is sick. I want to find time to visit him
es: escuché que David está enfermo. Quiero tener tiempo para visitarlo.


new words

宿舍 | su4 she4 | dorm room ;
等 | děng | to await | esperar | verb ;
找 | zhǎo | to look for | buscar | verb ;
事情 | shìqing | thing, matter, afair | cosa, tema | noun ;

** 3. 在宾馆的前台
:PROPERTIES:
:CREATED: [2022-03-22 18:06:35 -05]
:ID: 73aa24ae-5183-42d4-b19c-11e484f6359f
:END:

dialogue

Ａ：服务员，我房间的门打不开了。
pi: fúwùyuán, wǒ fángjiān de mén dǎ bu kāi le
en: excuse me, I can't open my door
es: disculpe, no puedo abrir mi puerta

Ｂ：您住哪个房间？
pi: níng zhù nǎge fángjiān
en: which room do you stay in?
es: ¿cuál es tu habitación?

Ａ：317。
pi: sān yāo qī
en: 317
es: 317

Ｂ：好的，我叫人去看看。
pi: hǎode, wǒ jiào rén qù kànkan
en: ok, I'll send someone to see
es: ok, enviaré a alguien a que lo vea

new words

服务员 | fúwùyuán | waiter, waitress | mozo, moza, noun ;

notes

前台 | qian2 tai2 | front desk ;
住 | zhù | to live | vivir | verb ;

** 4. 在商店 | In a store
:PROPERTIES:
:CREATED: [2022-03-22 18:06:36 -05]
:ID: 75b8fb1f-4129-4855-b4ad-9c2bd067c071
:END:

dialogue

Ａ：你看看这几件衣服怎么样。
pi: nǐ kànkan zhè jǐ jiàn yīfu zěnmeyàng
en: look, what about these dresses?
es: mira ¿qué te parecen estos vestidos?

Ｂ：这件白的有点儿长，那件黑的有点儿贵。
pi: zhè jiàn bái de yǒudiǎnr cháng, nà jiàn hēi de yǒudiǎnr guì
en: this white one is a little bit too long, that black one is a bit expensive
es: el vestido blanco es largo, el vestido negro es caro

Ａ：这件红的呢？这是今天新来的。
pi: zhè jiàn hóng de ne? zhè shì jīntiān xīn lái de
en: what about this red one? this one has just got here today
es: ¿qué tal el rojo? este recién vino hoy

Ｂ：让我再看看。
pi: ràng wǒ zài kànkan
en: let me see it again
es: dejame verlo de nuevo

new words

白 | bái | white | blanco | adjective ;

黑 | hēi | black | negro | adjective ;

贵 | guì | expensive | caro | adjective ;


note

让我再说一次。
pi: ràng wǒ zài shuō yī cì
en: let me say it again
es: dejame decirlo de nuevo

* Notes
:PROPERTIES:
:CREATED: [2022-03-22 19:38:30 -05]
:END:

** 1. The interrogative sentence "…, 好吗"
:PROPERTIES:
:CREATED: [2022-03-22 19:38:40 -05]
:END:

It is used to ask about another person's idea or opinion. For example,

我们一起去吃饭，好吗？
pi: wǒmen yīqǐ qù chīfàn, hǎo ma?
en: let's go to dinner together, okay?
es: vayamos a comer juntos ¿está bien?

你明天下午给我打电话，好吗？
pi: nǐ míngtiān xiàwǔ gěi wǒ dǎ diànhuà, hǎo ma
en: you call me tomorrow afternoon, okay?
es: me llamas mañana por la tarde ¿está bien?

我们下午去看电影，好吗？
pi: wǒmen xiàwǔ qù kàn diànyǐng, hǎo ma
en: we'll go to the movies this afternoon, okay?
es: iremos a ver una película esta tarde ¿está bien?

** 2. The adverb "再"
:PROPERTIES:
:CREATED: [2022-03-22 19:44:26 -05]
:END:

It indicates the repetition or continuation of an action or state. It can also indicate that an action will happen under a certain circumstance. For example:

|---------+------------+----------------|
|         | Predicate  | Predicate      |
|---------+------------+----------------|
| Subject | 再         | V(+O)          |
|---------+------------+----------------|
| 你      | 再         | 看看这本书吧。 |
| 你      | 明天再     | 给我打电话吧。 |
| 你      | 让我想想再 | 告诉你。       |
|---------+------------+----------------|

你再看看这本书吧。
pi: nǐ zài kànkan zhè běn shū ba
en: look at the book again
es: vulve a mirar el libro

你明天再给我打电话吧。
pi: nǐ míngtiān zài gěi wǒ dǎ diànhuà ba
en: you call me back tomorrow
es: llamame mañana de nuevo

你让我想想再告诉你。
pi: ňǐ ràng wǒ xiǎngxiang zài gàosù nǐ
en: let me think.  then I'll tell you
es: dejame pensar, luego te diré

** 3. Pivotal sentences
:PROPERTIES:
:CREATED: [2022-03-22 19:51:31 -05]
:END:

The predicate of a pivotal sentence is made up of two verbal phrases, the object of the first verb being the subject of the second. The first verb is often a causative verb, such as "请" (to invite), "让" (to let) and "叫" (to ask). For exmaple:

|---------+----+-----+-----------|
| Subject | V  | O/S | Predicate |
|---------+----+-----+-----------|
| 我      | 请 | 你  | 吃饭。    |
| 你      | 让 | 我  | 再想想。  |
| 我      | 叫 | 人  | 去看看。  |
|---------+----+-----+-----------|

我请你吃饭。
pi: wǒ qǐng nǐ chī fàn
en: I ask you to eat
es: te invito a cenar

你让我再想想。
pi: wǒ ràng wǒ zài xiǎngxiang
en: let me think again
es: dejame pensarlo de nuevo

我叫人去看看。
pi: wǒ jiào rén qù kànkan
en: I'll ask someone to take a look
es: le diré a alguien que vaya a verlo

** 4. Reduplication of verbs
:PROPERTIES:
:CREATED: [2022-03-22 20:01:14 -05]
:ID: f67eea95-77bc-4ad0-b76b-dbf380728f7f
:END:

The reduplication form of a verb indicates a short time, a small quantity, a slight degree or an attempt, conveying a relaxed and casual mood. It is often used in spoken chinese.

Reduplication forms of monosyllabic verbs

|----+------+--------|
| A  | AA   | A-A    |
|----+------+--------|
| 说 | 说说 | 说一说 |
| 听 | 听听 | 听一听 |
| 看 | 看看 | 看一看 |
|----+------+--------|

Reduplication forms of disyllabic verbs

|------+----------|
| AB   | ABAB     |
|------+----------|
| 学习 | 学习学习 |
| 准备 | 准备准备 |t
| 运动 | 运动运动 |
|------+----------|

* Exercises
:PROPERTIES:
:CREATED: [2022-03-22 20:07:40 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-03-22 20:33:11 -05]
:END:

1

他们为什么今天下午不去看电影？
pi: tāmen wèi shénme jīntiān xiàwǔ bú qù kàn diànyǐng
en: why won't they go this afternoon to watch movies?
es: ¿por qué no iran esta tarde a ver películas?

因为今天下午女的没有时间。
pi: yīnwèi jīntiān xiàwǔ nǚ de méiyǒu shíjiān
en: because today afternoon the woman doesn't have time
es: porque la mujer no tiene tiempo hoy por la tarde

2

王老师为什么让他给大卫打电话？
pi: wáng lǎoshī shénme ràng tā gěi dàwèi dǎ diànhuà
en: why does Sr. Wang asked him to call David?
es: ¿por qué el señor Wang le pidió que llamara a David?

因为王老师听说大卫病了。
pi: yīnwèi wáng lǎoshī tīngshuō dàwèi bìng le
en: because Sr. Wang heard that David got sick
es: porque Sr. Wang escuchó que David se enfermó

3

大卫怎么了？
pi: dàwèi zěnme le
en: how is David?
es: ¿cómo está david?

大卫病了。
pi: dàwèi bìng le
en: David is sick
es: David está enfermo

他们还不知道，所以他想找时间去看看大卫。
pi: tāmen hái bù zhīdào, suǒyǐ tā xiǎng zhǒu shíjiān qù kànkan dàwèi
en: they don't know it yet, so he wants to have some time to visit David
es: aún no lo saben, por eso él quiere tener un tiempo para visitar a David

4

她为什么去找服务员？
pi: tā wèi shénme qù zhǒu fúwùyuán
en: why did she go to the waiter?
es: ¿por qué busca al mozo?

因为她的房间的门打不开。
pi: yīnwèi tā de fángjiān de mén dǎ bu kāi
en: because the door of his room doesn't open
es: porque la puerta de su habitación no abre

5

她为什么不喜欢那件黑的？
pi: tā wèi shénme bù xǐhuan nà jiàn hēi de
en: why doesn't she likes the black one?
es: ¿por qué no le gusta el vestido negro?

因为黑的衣服有点儿贵。
pi: yīnwèi hēi de yīfu yǒudiǎr guì
en: because the black dress is a bit expensive
es: porque el vestido negro es un poco caro

** 3
:PROPERTIES:
:CREATED: [2022-03-22 20:33:13 -05]
:END:


*** 1
:PROPERTIES:
:CREATED: [2022-03-23 20:19:55 -05]
:END:

妈妈，我们一起（看书），好吗？
pi: māma, wǒmen yīqǐ kàn shū, hǎo ma
en: mom, we read the book together, ok?
es: máma, leemos el libro juntos ¿está bien?

reasoning: they are looking at the book

妈妈，我们一起（看看书），好吗？
pi: māma, wǒmen yīqǐ kànkan shū, hǎo ma
en: mom, let's read a book together, ok?
es: máma, leamos un libro juntos ¿está bien?

reasoning: they will read the book for a short time because he's a kid

*** 2
:PROPERTIES:
:CREATED: [2022-03-23 20:20:00 -05]
:END:



再见，我明天再（来）。
pi: zàijiàn, wǒ míngtiān zài huílai
en: goodbye, tomorrow I'll be back
es: adiós, mañana estaré de vuelta

再见，我明天再（来看你）。
pi: zàijiàn, wǒ míngtiān zài lái kàn nǐ
en: goodbye, tomorrow I'll come to see you
es: adiós, mañana estaré de vuelta para verte

reasoning: the man said goodbye, and the action needs to be repeated.

According to Qi, the following is not correct because hospital is not a home, so we don't use 回来. We only use 回来 for referring to our home.

*** 3
:PROPERTIES:
:CREATED: [2022-03-23 20:20:02 -05]
:END:

According to Qi, the following is correct.

老师让我再（想想）。
pi: lǎoshī ràng wǒ zài kǎoshì
en: the teacher told me to think about it again
es: el profesor me dijo que lo pensara de nuevo

reasoning: the kid is thinking

Qi recommended me use the sentence shown above

老师让我再（考试）。
pi: lǎoshī ràng wǒ zài kǎoshì
en: the teacher let me take the test again
es: el profesor me dejó tomar el examen de nuevo.

reasoning: the kid is thinking, so he might be doing an exam

*** 4
:PROPERTIES:
:CREATED: [2022-03-23 20:20:04 -05]
:END:

老师叫同学们（看书）。
pi: lǎoshī jiào tòngxuémen kàn shū
en: the teacher told the students to read the book
es: el profesor le dijo a los estudiantes que lean el libro

老师叫同学们（学习）。
pi: lǎoshī jiào tòngxuémen xuéxí
en: the teacher told the students to study
es: el profesor le dijo a los estudiantes que estudien

老师叫同学们（做作业）。
pi: lǎoshī jiào tòngxuémen zuòyè
en: the teacher told the students to do the homework
es: el profesor le dijo a los estudiantes que hagan la tarea

i recommended me changing the following question to any of the options shown above. This because 看看 is for a short time and usually teacher want students to study hard instead of reading casually.

老师叫同学们（再看看书）。
pi: lǎoshī jiào tóngxué men zài kàn kàn shū
en: the teacher told the students to continue reading the book
es: el profesor dijo a los estudiantes que sigan leyendo el libro

reasoning: the students have to keep reading the book

* Pronunciation
:PROPERTIES:
:CREATED: [2022-03-22 20:51:38 -05]
:END:

** Intonation of declarative sentences
:PROPERTIES:
:CREATED: [2022-03-22 20:51:44 -05]
:END:

Declarative sentences in chinese usually have a falling intonation. For example:

1

我学习汉语。
pi: wǒ xuéxí hànyǔ
en: I study chinese
es: Yo estudio chino

2

他是我的老师。
pi: tā shì wǒ de lǎoshī
en: he is my teacher
es: él es mi profesor

3

外边天气很好。
pi: wàibian tiānqì hěn hǎo
en: it's a good day outside
es: hace un buen clima afuera

* Characters
:PROPERTIES:
:CREATED: [2022-03-22 20:54:11 -05]
:END:

** Chiense radicals
:PROPERTIES:
:CREATED: [2022-03-22 20:54:14 -05]
:END:

偏旁 | piān páng | chinese character component | componente de caracter chino | noun ;

The radical of "TODO" can have a variety of meanings.

欢 | huān | merry, happy, cheerful | feliz | ;

对 | duì | right, correct | correcto | ;

The radical of "TODO" is usually related to cotton or silk products or textiles.

帮 | bāng | to help, to aid  | ayudar | verb ;

帽 | mào | hat, cap | gorro | noun ;

* Application
:PROPERTIES:
:CREATED: [2022-03-22 20:58:13 -05]
:END:

** Pair Work
:PROPERTIES:
:CREATED: [2022-03-22 20:58:15 -05]
:END:

Think about the verb that you've learned. Find the ones that can be reduplicated and write them down.

读读
pi: dúdu

看看
pi: kànkan

我叫人去看看。
pi: wǒ jiào rén qù kànkan
en: I'll ask someone to take a look
es: le diré a alguien que vaya a verlo

听说大卫病了，我想找时间去看看他。
pi: tīngshuō dàwèi bìng le, wǒ xiǎng zhǎo shíjiān qù kànkan tā
en: I heard that David is sick. I want to find time to visit him
es: escuché que David está enfermo. Quiero tener tiempo para visitarlo.

看一看
pi: kàn yi kàn

Ｂ：医生说有要再住三天看一看。
pi: yīsheng shǔo, yào zài zhù sān tiān kàn yī kàn
en: The doctor said there is to stay for another three days to see.
es: El médico dijo que habría una estancia de tres días más para ver qué pasa.

运动运动
pi: yùndòng yùndòng

Ａ：外边天气很好，我们出去运动运动吧！
pi: wàibian tiānqì hěn hǎo, wǒmen chūqu yùndòng yùndòng ba
en: it's a nice day outside, let's go out do some exercise
es: hace un buen clima, vayamos a hacer ejerrcicio

** Group work
:PROPERTIES:
:CREATED: [2022-03-22 21:24:21 -05]
:END:

Work in group of 3-4. Practice the pivotal sentences you've learned in class. Each group chooses a member to take notes.

Using 让

老师让我写汉字。
pi: lǎoshī ràng wǒ xiě hànzì

我奶奶让我买水果。
pi: wǒ nǎinai ràng wǒ mǎi shuǐguǒ

Using 叫

我哥哥叫我看看我们的狗。
pi: wǒ gēge jiào wǒ kànkàn wǒmen de gǒu
en: my brother told me to look at our dog

医生叫我多喝水。
pi: yīshēng jiào wǒ duō he shuǐ
en: el médico dijo que debo tomar más agua

Using 请 (qǐng)

我已经请他买面包。
pi: wǒ yǐjīng qǐng tā mǎi miànbāo
en: I already asked him to buy bread

