* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: a2a53ab1-03c1-4437-8a16-e6b7a2765b17
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
6c3bca7b-4a53-4cb7-9660-ce1761bc4f7a.mp3
***** 转录
1997 年，不安分的李长风突发奇想，宣布要造汽车。从这一年起，中国家用轿车的拥有量连年翻番。众多专家纷纷预言，中国的家用轿车时代已经到来。
**** 选择
***** A
李长风常常感到不安
***** B
97年李长风有了汽车
***** C
97年起，中国轿车数量猛增
***** D
专家都觉得中国轿车发展太快了
**** 答案
C
*** 2
:PROPERTIES:
:ID: a2300d25-d4e4-4399-8857-b5aff50d4db2
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
7ffcb013-c482-49d6-ba75-41c5c314a700.mp3
***** 转录
在我们的现实生活中，“用脚投票”原理极其简单：你搞不好、不公平，我就走人。例如，当股东们发现经理没有把企业经营好，企业的资产有可能贬值时，他们就会抛售股票，从而与该企业脱离关系。
**** 选择
***** A
生活中，常有企业出现问题
***** B
企业的股东们不会轻易抬脚走人
***** C
世界这么大，什么事都可能发生
***** D
“用脚投票“的情况生活中时有发生
**** 答案
D
*** 3
:PROPERTIES:
:ID: b7354a7f-4eaa-494a-a27a-70eb6623db84
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
68e69f78-ada9-43d8-a6be-ecee7d928e54.mp3
***** 转录
在着手进行休闲、观光方面的具体投资时，他发现：孤立的某一个娱乐项目难以吸引很多人，只有当一个地方风景优美、交通便利、饭店高档舒适、娱乐项目众多时，才可能吸引更多的游客。
**** 选择
***** A
他有了空闲就去旅游
***** B
他正在进行旅游开发
***** C
风景好的地方就有人去
***** D
游客最在意吃住的质量
**** 答案
B
*** 4
:PROPERTIES:
:ID: 640d2733-f0e5-49c5-86b6-a7da442b6c89
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
cf7e15ba-dd1c-4b46-80d4-7e62ff819eff.mp3
***** 转录
在超市，如果顾客结账需要排队等候很长时间，他们就会失去耐心，一走了之，但如果开设很多收款台却少有人光顾，则又会导致成本提高。“排队模型”就试图为这个问题找到一个最好的解决方案。
**** 选择
***** A
排队是需要耐心的
***** B
买东西排队也是难免的
***** C
排队模型可以代替人排队
***** D
收款台闲置会造成成本上升
**** 答案
D
*** 5
:PROPERTIES:
:ID: 18e7ac1a-c22d-4850-8ef2-cf4bf4407be7
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
ddf2c5aa-3abc-4027-879a-a5b2559d0f68.mp3
***** 转录
上中学时，爱因斯坦很喜欢数学。一次，叔叔给他讲了勾股定理的来历后，问爱因斯坦能不能试着证明它。爱因斯坦决定试一试。眼看着运算的草稿纸越积越厚，找到正确的证明方案却并非易事，但他没有动摇，二十多天后，他终于拿出了正确方案。
**** 选择
***** A
爱因斯坦的叔叔是一位数学家
***** B
叔叔给爱因斯坦出了一道难题
***** C
任何人在困难面前都难免动摇
***** D
爱因斯坦最后也没能证明定理
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: cab7814a-fc4c-4f94-8f95-604e77f78054
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
78d9aacc-a3b2-42a0-9c73-d7803095b125.mp3
***** 转录
女：欢迎经济学者纪老师做客网络空间。纪老师，您好，我们常看到“分享经济”这个词，您能否详解一下分享经济的由来？
男：最早提出分享经济的是美国经济学家威茨曼撰写的《分享经济》一书。作者针对的是 20 世纪 70 年代出现的“经济滞胀”。作者认为产生经济滞胀的原因是工资结构不合理，提出以分享制度代替工资制度。在实践中，分享经济形成了两种不同的模式。一种是欧美的通过股权制度让工人参与企业收入分配的模式，另一种是日本的通过企业文化和管理制度让员工参与企业管理的模式。
女：在我们的生活中，分享经济有哪些呈现方式？
男：最典型的是有偿分享模式、对等分享模式、劳务分享模式、众筹分享模式。有偿分享是指把自己剩余或暂时不用的物品分享给别人使用，收取租金。
女：比如说我去旅游，不想住酒店，我就上网查找住宿信息，一旦和房主达成一致，就可以实地入住、网上结算了？
男：对，就是这样。
女：对等分享模式呢？
男：顾名思义，就是双方互相交换使用财产，不向对方支付报酬。
女：我们的“城乡儿童互换生活环境体验成长快乐”活动算不算？
男：当然算，最近几年这种活动已经成为许多学校教育的重要内容，它分享的不仅仅是双方对等交换的环境，还有双方情感和文化价值的体验。
女：劳务分享模式就是对大量没有充分利用的劳务资源的分享吧？
男：是啊，现代分享经济中，人们不仅可以出售自己多余的物品，还可以出售多余的时间。美国有一家创业公司，凭 1 小时送货上门服务取得了成功，它就是通过互联网，把分散在社区居民中的剩余时间利用起来，实现一小时送达的承诺。
女：众筹分享模式就是指大众筹资或群众筹资了吧？
男：对，当然现代众筹是指用互联网平台进行资金筹集。而且，现代众筹筹资目标也包含了分享投资对象，不纯粹是为了筹集资金。
**** 题目
***** 6
:PROPERTIES:
:ID: 3d586efd-b24e-4852-8f81-ec4b50f7f0ee
:END:
****** 问题
******* 音频
61946bc2-51aa-42a0-9add-b4de8f1bb187.mp3
******* 转录
“分享经济”是在什么背景下产生的？
****** 选择
******* A
《分享经济》一书问世以后
******* B
工人提出改良工资制度之后
******* C
欧美和日本经济模式创新的背景下
******* D
 20世纪70年代出现经济滞胀以后
****** 答案
D
***** 7
:PROPERTIES:
:ID: 5b79f96e-540b-48cb-8f0b-df90fc7444b4
:END:
****** 问题
******* 音频
38aae85b-6626-4be4-83d4-cd6b8407a4f3.mp3
******* 转录
“有偿分享模式”的主要特点是什么？
****** 选择
******* A
使用者需要付费
******* B
交卖掉不用的东西
******* C
用不了的东西就送人
******* D
能够租赁就不要购买
****** 答案
A
***** 8
:PROPERTIES:
:ID: bc7dba9d-cf28-4d21-bd6c-3f28be05c4c4
:END:
****** 问题
******* 音频
245222ec-6811-4c26-ae4a-19ad984f70c2.mp3
******* 转录
“对等分享模式”的主要特点是什么？
****** 选择
******* A
城乡儿童可互通有无
******* B
无偿为使用者提供服务
******* C
着重于情感的交流体验
******* D
双方交换使用分享内容
****** 答案
D
***** 9
:PROPERTIES:
:ID: a7e76b4a-d831-4691-9329-9fa596ed0b8a
:END:
****** 问题
******* 音频
33834bf3-635e-449d-b1ea-9a85cbc4da4a.mp3
******* 转录
“劳务分享模式”的主要特点是什么？
****** 选择
******* A
以最快速度送货上门
******* B
合理利用零星的人工
******* C
对快递行业进行革命
******* D
答应的事情就要兑现
****** 答案
B
***** 10
:PROPERTIES:
:ID: 6aad0d78-c10f-4a09-a620-9910a8172eea
:END:
****** 问题
******* 音频
545f6c97-e94e-4be0-beb2-2f6df8ecf947.mp3
******* 转录
“众筹分享模式”的主要特点是什么？
****** 选择
******* A
目的就是筹集资金
******* B
及时反馈投资情况
******* C
包括分享投资对象
******* D
注重互联网平台建设
****** 答案
C
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 6ea3d4c3-f27a-49f2-a68b-d81819b0b00f
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
3e2be162-73c1-4aff-a528-2ac6646d70cd.mp3
***** 转录
在相当长的一段时间内，人们总爱用“大鱼吃小鱼”来形容市场竞争的残酷性，并似乎形成了约定俗成的共识。眼下，这种说法却悄然发生了改变。因为，当今已步入知识经济年代，市场瞬息万变，信息日新月异，思维迟钝、行动缓慢的大鱼未必吃得了头脑睿智、动作迅速的小鱼，所以出现了“快鱼吃慢鱼”的现象。其寓意是在强调随时调整思路适应市场变化的重要性，同时给做事一成不变、疏于创新的人敲响了警钟。事实上，不变意味着落后，落后就要挨打，照此下去，终究会被市场所淘汰。
**** 题目
***** 11
:PROPERTIES:
:ID: c3915371-9b72-4981-aee8-98e87ff9c7f9
:END:
****** 问题
******* 音频
056f58f9-69b3-4ec5-b352-f352d5522fdc.mp3
******* 转录
“大鱼吃小鱼”用来说明什么？
****** 选择
******* A
一种市场行为
******* B
一条普道真理
******* C
大鱼比小鱼受欢迎
******* D
市场竞争是残酷的
****** 答案
D
***** 12
:PROPERTIES:
:ID: bb9f534a-dbfd-4df7-9d52-0c64f82e5e69
:END:
****** 问题
******* 音频
db7b2704-ea18-4429-aa18-c414cfb4e8b2.mp3
******* 转录
如今的市场竞争出现了怎样的新现象？
****** 选择
******* A
快鱼吃慢鱼
******* B
市场变化快
******* C
信息随时更新
******* D
知识胜过一切
****** 答案
A
***** 13
:PROPERTIES:
:ID: 14769115-fe1a-4e7e-b3fe-30984a33b3b4
:END:
****** 问题
******* 音频
4f312a95-cb70-4dec-829d-5609bb36901b.mp3
******* 转录
说话人认为市场竞争中的强者是什么样的？
****** 选择
******* A
财力雄厚
******* B
警惕性高
******* C
勇于创新
******* D
知识渊博
****** 答案
C
*** 14-17
:PROPERTIES:
:ID: 6bcaaaf9-2cba-4784-98ab-02d449f33f8c
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
a336100f-072c-481b-99a5-338d17e4b065.mp3
***** 转录
随着天气转暖，冰品、饮品市场又火了起来。冷柜里五颜六色的冰激凌款式繁多，有几年前风行起来的怀旧雪糕，也有好玩儿的新面孔，新款冰激凌包装纸上的猴子、兔子、小松鼠等动物形象保管能唤起你的无限童心，粽子雪糕外面再裹上一层巧克力的中外混搭口味，肯定能让男女老少个个胃口大开，商家对消费者的体贴从观感到口味，可谓无微不至。冰激凌产品正从原来较为单纯的降温、好吃，向健康和完美口感的市场需求转变。
论价格，也是高低档次都有，你要是嫌三四元的档次低，有 15 元的脆筒冰激凌，48 元的水果冰激凌，环保人士还可选择 60 元的环保盒装冰激凌。
中国已经成为全球最大的冰激凌市场。2015 年中国冰激凌销售总额为 393亿元，同比微增 0.66%，利润为 20.1 亿元，同比下跌超过 9%，这说明冷饮经营也绝非易事，虽然全年营收略有上升，但整个行业利润却有一定下滑。我们不禁会想到，在欣欣向荣背后，行业竞争正在加剧。
**** 题目
***** 14
:PROPERTIES:
:ID: e060d0d4-5719-4526-9fb1-9079efe26ba8
:END:
****** 问题
******* 音频
cf344939-9a66-403e-aca1-48f6e60cb907.mp3
******* 转录
前几年市场上流行什么样的雪糕？
****** 选择
******* A
怀旧雪糕
******* B
动物雪糕
******* C
粽子雪猩
******* D
巧克力雪糕
****** 答案
A
***** 15
:PROPERTIES:
:ID: e599bc33-bf33-42d6-a585-13ab3b4c7017
:END:
****** 问题
******* 音频
2faa3695-11cd-466c-be65-0daea11fb75b.mp3
******* 转录
如今消费者对冰激凌的需求是什么？
****** 选择
******* A
好吃
******* B
降温
******* C
便宜
******* D
健康
****** 答案
D
***** 16
:PROPERTIES:
:ID: f33535f9-e3ae-4490-90d3-c7b6027ecb1a
:END:
****** 问题
******* 音频
d6a362ce-5f3f-4e32-814c-8ec0fd341fe4.mp3
******* 转录
小学生最可能会选择哪种冰激凌？
****** 选择
******* A
脆筒冰激啧
******* B
水果冰激凌
******* C
有动物形象的冰激凄
******* D
环保盒装冰激凌
****** 答案
C
***** 17
:PROPERTIES:
:ID: c49f1379-21b2-47c2-ac92-3c69b89437b7
:END:
****** 问题
******* 音频
2bae3172-f3d1-44a1-a44a-dec9f4d52cb7.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
中国人不喜欢吃冰激凌
******* B
冰激凌行业利润在下滑
******* C
冰激凌价格越来越合理
******* D
冰激凌吃多了容易上火
****** 答案
B
* 阅读
** 第一部分
*** 18
**** 句子
***** A
看见漏水的水龙头一定要赶快关上它。
***** B
我的汽车不仅很旧，但仍然跑得很好。
***** C
刘大爷喜欢坐在门口闭着眼睛听收音机里传出的咿咿呀呀的京剧唱段。
***** D
随着服装出口量的增加，他们厂生产的纽扣也漂洋出海，走向了世界。
**** 答案
B
*** 19
**** 句子
***** A
老百姓心里有杆秤，只要我们说实话，他们就会相信我们。
***** B
他非常希望能够获得一次和来自不同地方的人面对面交流。
***** C
那是为个子高的人特别设计的公寓一一一高大的家具，很高的门把手。
***** D
使用这些仪器可以把不太直观的声波变成可见的图像，之后进行分析。
**** 答案
B
*** 20
**** 句子
***** A
阵阵鞭炮声使我的心兴奋起来，我跑到窗前，看美丽的炯花已铺满了天空。
***** B
从80年代中后期开始，羽绒服逐步取代棉毛制品，成为中国北方冬季主打户外服装。
***** C
夕阳下，一个穿旗袍的女孩从安静的街巷穿过。我觉得旁袍很好看，应该给女儿做一件。
***** D
在海洋动物中，鲅鱼的嘘觉极其灵敏，可以在几千米外闻到血腥昧并立即赶往有血的地方。
**** 答案
A
** 第二部分
*** 21
**** 段话
今后，凡属投稿和业务信函，均请[[gap]]上面地址投寄，[[gap]]发生囚错投耿误时间的事情；[[gap]]寄至原址的邹件，将由专人转送过来，请寄件人放心。
**** 选择
***** A
****** 1
照
****** 2
省得
****** 3
或者
***** B
****** 1
依
****** 2
切勿
****** 3
一经
***** C
****** 1
遮
****** 2
防止
****** 3
依然
***** D
****** 1
按
****** 2
以免
****** 3
已经
**** 答案
D
*** 22
**** 段话
如果母亲[[gap]]良好的教育，她的习惯自然也就良好，她的孩子[[gap]]就会受到良好的教育；[[gap]]，孩二就会受到不良影响。有道是“先人为主”根深蒂和“，母亲教育与儿童教育的关系[[gap]]。
**** 选择
***** A
****** 1
受过
****** 2
无形中
****** 3
反之
****** 4
可想而知
***** B
****** 1
进行
****** 2
预料中
****** 3
反面
****** 4
显而易见
***** C
****** 1
经历
****** 2
无意间
****** 3
相应
****** 4
不言自明
***** D
****** 1
坚持
****** 2
意味着
****** 3
相反
****** 4
不得而知
**** 答案
A
*** 23
**** 段话
雅各布斯的这本书思绪[[gap]]，当然也[[gap]]流露出一些理想主义的浪漫。总体来说，世界上没有一个大城市是[[gap]]理性模式建立起来的，各种利益、各种欲望在城市中交错角力，形成了城市的现实[[gap]]。
**** 选择
***** A
****** 1
起伏
****** 2
通常
****** 3
遮照
****** 4
主义
***** B
****** 1
混乱
****** 2
大多
****** 3
服从
****** 4
样子
***** C
****** 1
流畅
****** 2
不免
****** 3
按照
****** 4
形态
***** D
****** 1
万十
****** 2
未兖
****** 3
根据
****** 4
形状
**** 答案
C
** 第三部分
*** 段话
一战期间，[[gap:24]]：奔赴战场的士兵甚至要带上剃须刀、磨刀的皮条以及磨刀石。可更换刀片式剃须刀的发明者金。坎普。吉列敏锐地觉察到这其中隐藏着的巨大商机，于是他以极低的折扣同政府签订了合同，[[gap:25]]，然后将这种装卸方便的剃须刀发放给士兵。不次，士兵们就成了吉列剃须刀的忠实客户。这些士兵带着吉列剃须刀到欧洲作战时，[[gap:26]]。战争结束后，一些士兵把吉列剃须刀带回了家，他们就像人体广告，使吉列剃须刀很快便名扬四海。自此[[gap:27]]，购买者川流不息。
吉列创造了一种全新的商业模式，它靠卖刀片而不是刀架赚钱，[[gap:28]]。汽车4S店也不是靠卖汽车挣钱而是通过售后服务的延伸赚取更多的利润。
*** 选择
**** A
政府低价购买了350万副刀架和3600万枚刀片
**** B
如同惠普打印机的利涧来自墨盒而非打印机本身
**** C
欧洲人也喜欢上了这种安全、方便的剃须刀
**** D
胡子在生活中给男士带来了巨大的烦恼
**** E
吉列剃须刀生意兴隆
*** 答案
**** 24
D
**** 25
A
**** 26
C
**** 27
E
**** 28
B
** 第四部分
*** 29-32
**** 段话
在电子商务风行的今天，实体店还能多大程度地影响品牌在零售市场的地位7就在零售商都为实体店的未来捏把汗的时候，有人做了一项调查，令人惊讶的是，未来计划更多通过实体店购物的消费者比例从一年前的18％攀升至26％；表示实体店“方便购物”的客户达到93％，远高于网络和移动设备。
这似乎与许多零售商的认识相去其远。过去一年多里，传统零售商纷纷扎堆规划电子商务，由店商向电商转型。根据调查，63％的传统零售商已开展多渠道零售，但近三成零售商表示，其多渠道战略实施并不成功。
究其根本，是因为许多零售企业并未深人了解消费者的需求变化，其转型初衷只是为了数字化而数字化，认为仅仅通过技术的部署就能带来绩效的提升。事实上，在数字时代，虽然技术的变革重新定义了零售商与消费者的连接方式，但却并没有改变消费者需求的本质一一价格合理、产品种类丰富以及多年积累的信任感。因此，掌控零售商未来和运的，不是涌现的新兴技术，更不是“凶猛”的互联网电商，而是瞬息万变的消费者需求。
**** 题目
***** 29
****** 问题
第1段中，画线词语“捏把汛”的意思最可能是：
****** 选择
******* A
担心
******* B
着急
******* C
天气太热
******* D
心情不好
****** 答案
A
***** 30
****** 问题
根据第1段，调查结果令人惊许是因为：
****** 选择
******* A
电商的地盘急剧扩大
******* B
追求品牌的人越来越多
******* C
喜欢实体店的人在增加
******* D
准备网购的人数超出预期
****** 答案
C
***** 31
****** 问题
过去一年里，很多传统零售商：
****** 选择
******* A
反省自己的经营理念
******* B
努力开展多渠道经暑
******* C
纷纷向电子商务取经
******* D
转型过程中被迫降价
****** 答案
B
***** 32
****** 问题
根据最后一段，可以知道：
****** 选择
******* A
数字化未必就是潼流
******* B
新技术能够带来效益
******* C
消费者的需求是根本
******* D
传统零售商成本较高
****** 答案
C
*** 33-36
**** 段话
《后汉书》记载：东汉时有个人叫费长房。一天他在酒楼喝酒解闰，偶见街上有一卖药的老人，悬挂着一个药菁芦兜售丸散膏丹。卖了一阵，街上行人渐渐散去，老人就悄悄钻人了荔芦之中。据说这是中国最早最原始的广告行为。此后，在门口挂个壶或葫芦推销药品流行起来，而东成为古代药店、诊所的标志，行医也因此被叫作“悬壶济世”。为什么药店门前挂壶或葫芦，而非其他物品？因为在古代，壶是装中药的，葫芦是装丹散、丸药的，菁芦就相当于今天的药瓶。门前挂士或葫芦很直观地说明这里是卖药的。
作为一种古老的广告形式，酒旗在中国也有着悠久的历史。据说，唐代以后，酒旗作为酒店的招牌，应用已经十分普遍。人们在酒旗上标以“酒”字或署上店名，或悬于店铺之上，或挂在屋顶房前，或另立一根长杆挂上酒旋，任其随风招展，非常醒目，过往行人在很远处便能见到。除此之外，酒旗还有一个重要作用，即酒旗的升降是店家有酒或无酒、腊业或不营业的标志。早晨起来，开始营业，有酒可卖，便高悬酒旗；若无酒可售，就收下酒旗。
随着社会的发展，古代的酒旗已消失，大屏幕主导着广告市场，偶有仿古酒旗悬挂在林立的高楼之间，新颖别致，仍会给人带来惊喜。路人除了知道这里有酒，还会体味到一种无以言传的韵显。
**** 题目
***** 33
****** 问题
关于中国最早最原始的广告，下列说法正确的是：
****** 选择
******* A
是卖药的广告
******* B
见于西汉时期
******* C
出现在酒楼门口
******* D
写着“悬壶济世”
****** 答案
A
***** 34
****** 问题
关于酒旗，下列说法正确的是：
****** 选择
******* A
上面都写着酒的名字
******* B
酒旗都悬挂在旗杆上
******* C
酒店没酒就不挂酒旗了
******* D
现在酒店仍普遍挂酒旗
****** 答案
C
***** 35
****** 问题
文中提到的广告的共性是：
****** 选择
******* A
有魅力
******* B
很直观
******* C
说服力强
******* D
能打动人
****** 答案
B
***** 36
****** 问题
最适合做上文标题的是：
****** 选择
******* A
广告的起源
******* B
中国广告的发展
******* C
中国古代的广告
******* D
广告的功能及其艺术性
****** 答案
C
