* 听力

** 1

*** 1

**** transcript

猫行动敏捷，善跳跃。嗅觉灵敏，喜欢吃鱼、鼠、兔、鸟等。因为猫是夜行动物，为了在夜间能看清事物，需要大量的牛磺酸，而鱼和老鼠的体内就含较多牛磺酸，所以猫不仅仅是因为喜欢而吃鱼和老鼠，也是因为自己的需要才吃。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

我们常常看到猫趴在那儿睡觉。这并不是因为它们懒惰，而是为了补充精力。猫每天的睡眠时间比较长，在12～16小时之间，猫、老鼠、猪都喜欢睡懒觉。蝙蝠、沙鼠和狮子每天的睡眠时间更长，它们一生之中有多达三分之二的时间在梦乡中度过。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

看到主人，狗会快活地扑过来，与人交往是狗的天性，但程度常取决于3～7周龄时其与人接触的程度。假如狗出生的头两个月只跟狗类在一起，不是由人类饲养的，或者说没有真正接触过人类，那它一生都不会亲近人，并难以训练。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

天鹅体态优雅迷人，好像高贵的君子。白天鹅浑身雪白，声音像喇叭一样洪亮。小天鹅叫声清脆，好像哨子声，所以也叫“口哨天鹅”。黑天鹅浑身长着卷曲的黑褐色羽毛，嘴巴是红色的。

***** notes
:PROPERTIES:
:CREATED: [2022-08-22 11:33:07 -05]
:END:

嘴巴 / zui3 ba / mouth ;

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

鸽子的方向感极强，特别是信鸽，无论飞出去多远，都能准确无误地飞回家，好像身体里安装了一个遥控器一样。常生活在山区的原鸽有很强的飞翔能力，一天可以飞行十几个小时而不疲倦。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



