* 听力

** 第二部分
:PROPERTIES:
:ID: 06c92c77-eef9-4063-be77-0bd5da3176df
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：今天我们请到了小朋友都非常喜欢的明明老师来跟大家谈谈关于动物的话题。明明老师，很多小朋友都想知道动物是怎么分类的。您能跟我们说说吗？
男：动物的分类标准有很多，我先给小朋友们介绍一种超级简单的分类方法吧。跟你们一样，每种动物都有它们喜欢的食物。爱吃肉的动物叫作肉食动物，被它们吃的动物是猎物，它们会跟踪并捕捉猎物。你家里养的小猫和小狗都是肉食动物，老虎也是。注意啦，老虎会很高兴吃掉你的猫、吞下你的狗，所以不能把它们关在一起。
女：这么说，爱吃草的动物就是草食动物了？
男：没错，以植物为主要食物的动物统统归入草食动物，包括大象、马、牛、羊等等。
女：还有的动物既吃动物也吃植物，应该属于哪一类呢？
男：动植物都吃的动物，被称为杂食动物。比如小猪、熊等等。希望小朋友也是杂食动物啊，这样营养才会全面。还有吃昆虫的动物是食虫动物，这类动物包括食蚁兽等。
女：那这些动物之间有什么关系吗？
男：肉食动物吃草食动物，草食动物吃植物……科学家把动物彼此之间谁吃谁的关系，画成了一张特殊的关系图，称为食物链或食物网。如果草食动物灭绝了，肉食动物也会灭绝，因为它们没有东西可吃了。如果肉食动物灭绝了，草食动物的数目会大量增加，并吃光所有植物。接着，草食动物会因为没有东西可吃而灭绝。

**** 音频

9482629a-206f-4221-b7ef-dc739ae567f3.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 59d88310-c4c5-4eb2-ad80-9f188a8d8f0a
:END:

***** 问题

明明老师介绍了哪种动物分类方法？

****** 音频

3a5bc738-434e-4e1a-bb8b-737c2f465e9b.mp3

***** 选择

****** A

根据动物的体型分类

****** B

根据动物的食物分类

****** C

根据动物的栖息地分类

****** D

根据动物的身体结构分类

***** 答案

B

**** 7
:PROPERTIES:
:ID: d54513de-be1e-40e3-9665-2c681984e84c
:END:

***** 问题

文中没提到哪类动物？

****** 音频

3da9dff3-c9b6-45f9-b58f-bb5bf3a14921.mp3

***** 选择

****** A

肉食动物

****** B

草食动物

****** C

杂食动物

****** D

食鱼动物

***** 答案

D

**** 8
:PROPERTIES:
:ID: ce4fc365-dd59-4bb6-b712-a045ab55024d
:END:

***** 问题

明明老师为什么希望小朋友也是杂食动物？

****** 音频

892a7702-19a5-4a82-80a6-521071287370.mp3

***** 选择

****** A

营养更全面

****** B

吃得更安全

****** C

更节省资源

****** D

性格会更好

***** 答案

A

**** 9
:PROPERTIES:
:ID: 49d6f7b8-e120-4ffa-9180-f8bc257e7f77
:END:

***** 问题

下列哪种关系被称为食物链？

****** 音频

61339aa3-dd8d-45a9-98b7-83ccf5d03ed4.mp3

***** 选择

****** A

草食动物吃植物

****** B

肉食动物吃草食动物

****** C

肉食动物吃杂食动物

****** D

动物间谁吃谁的关系

***** 答案

D

**** 10
:PROPERTIES:
:ID: 1e6b9b44-d80a-4150-b275-f1cac3b18e28
:END:

***** 问题

如果草食动物灭绝了，会出现什么情况？

****** 音频

bdbd2d12-4f71-48ff-aeaa-49ba5096a3bb.mp3

***** 选择

****** A

肉食动物也灭绝

****** B

植物都会被吃光

****** C

杂食动物也灭绝

****** D

食虫动物也灭绝

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

猎能发现老鼠的踪迹

***** B

猎需要牛磴酸提高嗜克

***** C

猎的体内含有较多牛磺酸

***** D

猎因为自己的需要而吃鱼和老鼠

**** 段话

猫行动敏捷，善跳跃。嗅觉灵敏，喜欢吃鱼、鼠、兔、鸟等。因为猫是夜行动物，为了在夜间能看清事物，需要大量的牛磺酸，而鱼和老鼠的体内就含较多牛磺酸，所以猫不仅仅是因为喜欢而吃鱼和老鼠，也是因为自己的需要才吃。

***** 音频

0c68fbfc-1ad5-4e6a-9d37-e25c77e56dfe.mp3

**** 答案

D

*** 2

**** 选择

***** A

猎是睡眠时间最长的动物

***** B

老鼠和猪并不喜欢睡懒克

***** C

猎为了补充体力，睡眠时间比较长

***** D

狮子一生中三分之一的时间在睡克

**** 段话

我们常常看到猫趴在那儿睡觉。这并不是因为它们懒惰，而是为了补充精力。猫每天的睡眠时间比较长，在 12～16 小时之间，猫、老鼠、猪都喜欢睡懒觉。蝙蝠、沙鼠和狮子每天的睡眠时间更长，它们一生之中有多达三分之二的时间在梦乡中度过。

***** 音频

6427af15-d1b1-4ee2-83e4-3b15f292c3a3.mp3

**** 答案

C

*** 3

**** 选择

***** A

狗天生不喜欢与人交往

***** B

通过练习，所有的狗都能与人友善

***** C

狗与人的亲密关系要经过几年的时间才能建立起来

***** D

狗是否与人亲热，取决于出生后 3 ～ 7 周与人接触的程度

**** 段话

看到主人，狗会快活地扑过来，与人交往是狗的天性，但程度常取决于 3～7 周龄时其与人接触的程度。假如狗出生的头两个月只跟狗类在一起，不是由人类饲养的，或者说没有真正接触过人类，那它一生都不会亲近人，并难以训练。

***** 音频

c2ba5782-f2b9-488d-b593-721abfd56606.mp3

**** 答案

D

*** 4

**** 选择

***** A

天鹅是高贵的君子

***** B

白天鹅又称“口哨天鹅“

***** C

黑天鹅的嘴巴是红色的

***** D

小天鹅的叫声像喇叭一样

**** 段话

天鹅体态优雅迷人，好像高贵的君子。白天鹅浑身雪白，声音像喇叭一样洪亮。小天鹅叫声清脆，好像哨子声，所以也叫“口哨天鹅”。黑天鹅浑身长着卷曲的黑褐色羽毛，嘴巴是红色的。

***** 音频

dc8958c4-88f8-40a7-a338-0907d7655187.mp3

**** 答案

C

*** 5

**** 选择

***** A

鸽孔是方向感很强的鸟类

***** B

信鸽的身体里安装丁遥控器

***** C

所有鸟都能准确无误地飞回家

***** D

原鸽可以飞行几十个小时而不疲倦

**** 段话

鸽子的方向感极强，特别是信鸽，无论飞出去多远，都能准确无误地飞回家，好像身体里安装了一个遥控器一样。常生活在山区的原鸽有很强的飞翔能力，一天可以飞行十几个小时而不疲倦。

***** 音频

21e06450-37dd-4b00-ad9d-9207b6874ea8.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

每当夏天来到，我们就会在花园里、草坪上，看到轻轻飞过的蜻蜓。而在池塘边，我们还会看到蜻蜓用尾巴在水面上一点，然后飞走。这是怎么回事呢？这其实是蜻蜓产卵的动作。第二年春天到来时，小蜻蜓便会破卵而出，慢慢长出跟妈妈一样的翅膀。

蜻蜓常常一边飞行，一边寻找小昆虫，一碰上猎物，就会立刻进攻。它们用6 只脚把猎物钩住，然后送入口中。据科学家研究，蜻蜓靠“运动伪装”来追踪猎物。蜻蜓慢慢靠近猎物，在猎物的眼中，飞行的蜻蜓好像是个固定的点，因此完全不知危险已经来临。

蜻蜓的头顶有一对亮晶晶的大眼睛，这就是复眼。复眼给了它们非常敏锐和宽广的视觉。所以蜻蜓能在飞行时看清各个方向每个角落的动静。

**** 题目

***** 11

****** 选择

******* A

喝水

******* B

洗深

******* C

产卵

******* D

照顾小蜻蜍

****** 问题

蜻蜓用尾巴在水面上一点是在干什么？

***** 12

****** 选择

******* A

立刻进攻

******* B

运动伪装

******* C

快速飞行

******* D

固定不动

****** 问题

蜻蜓用什么方法追踪猎物？

***** 13

****** 选择

******* A

蜻蜓的眼睛很大

******* B

蜻蜓的眼睛很亮

******* C

蜻蜓的眼睛是复眼

******* D

蜻蜓的眼睛在头顶

****** 问题

蜻蜓为什么能看清各个方向的动静？

*** 14-17

**** 课文

在春天或夏天的雨后，我们常能看到慢慢爬行的蜗牛。小小的蜗牛背着重重的外壳，一副吃力的样子，但这个壳却是用来保护蜗牛的“房子”。一旦遇到危险，蜗牛就会缩进里面，躲过侵扰。蜗牛大多生活在温暖、潮湿的地方，喜欢在植物丛中躲避太阳直晒。

蜗牛以蔬菜、青草、瓜果为食，它是怎么吃东西的呢？蜗牛的舌头上有 135排整齐的角质牙齿，总共有 14000 多颗牙齿，称得上是世界上牙齿最多的动物。蜗牛就是利用这些牙齿，刮下蔬菜、青草和瓜果皮来进食。

蜗牛的头上有两对触角，一对长一对短。长触角上的两个黑点是眼睛，不过视力不太好，幸亏这对长触角能伸缩自如，摸索前进，帮助眼睛了解周围的情况。蜗牛的那对小触角具有嗅觉功能，如果受到损伤，它们就很难找到食物了。

**** 题目

***** 14

****** 选择

******* A

用来储存食物

******* B

用来保护蜗牛

******* C

用来给蜗牛保温

******* D

用来躲避太阳直晒

****** 问题

蜗牛的外壳有什么作用？

***** 15

****** 选择

******* A

安静的地方

******* B

凉爽的地方

******* C

温暖、潮湿的地方

******* D

有太阳直晒的地方

****** 问题

蜗牛喜欢在什么样的环境中生活？

***** 16

****** 选择

******* A

重重的外壳

******* B

灵活的舌头

******* C

舌头上的牙齿

******* D

长短两对触角

****** 问题

蜗牛利用什么来吃东西？

***** 17

****** 选择

******* A

视觉功能

******* B

嗜觉功能

******* C

帮助蜗牛消化食物

******* D

帮助蜗牛躲过侵扰

****** 问题

蜗牛的小触角具有什么功能？

