* 听力

** 1

*** 1

**** transcript

猫行动敏捷，善跳跃。嗅觉灵敏，喜欢吃鱼、鼠、兔、鸟等。因为猫是夜行动物，为了在夜间能看清事物，需要大量的牛磺酸，而鱼和老鼠的体内就含较多牛磺酸，所以猫不仅仅是因为喜欢而吃鱼和老鼠，也是因为自己的需要才吃。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

我们常常看到猫趴在那儿睡觉。这并不是因为它们懒惰，而是为了补充精力。猫每天的睡眠时间比较长，在12～16小时之间，猫、老鼠、猪都喜欢睡懒觉。蝙蝠、沙鼠和狮子每天的睡眠时间更长，它们一生之中有多达三分之二的时间在梦乡中度过。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

看到主人，狗会快活地扑过来，与人交往是狗的天性，但程度常取决于3～7周龄时其与人接触的程度。假如狗出生的头两个月只跟狗类在一起，不是由人类饲养的，或者说没有真正接触过人类，那它一生都不会亲近人，并难以训练。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

天鹅体态优雅迷人，好像高贵的君子。白天鹅浑身雪白，声音像喇叭一样洪亮。小天鹅叫声清脆，好像哨子声，所以也叫“口哨天鹅”。黑天鹅浑身长着卷曲的黑褐色羽毛，嘴巴是红色的。

***** notes
:PROPERTIES:
:CREATED: [2022-08-22 11:33:07 -05]
:END:

嘴巴 / zui3 ba / mouth ;

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

鸽子的方向感极强，特别是信鸽，无论飞出去多远，都能准确无误地飞回家，好像身体里安装了一个遥控器一样。常生活在山区的原鸽有很强的飞翔能力，一天可以飞行十几个小时而不疲倦。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 06c92c77-eef9-4063-be77-0bd5da3176df
:NOTETYPE: dialogue-with-5-questions
:END:

*** 对话

女：今天我们请到了小朋友都非常喜欢的明明老师来跟大家谈谈关于动物的话题。明明老师，很多小朋友都想知道动物是怎么分类的。您能跟我们说说吗？
男：动物的分类标准有很多，我先给小朋友们介绍一种超级简单的分类方法吧。跟你们一样，每种动物都有它们喜欢的食物。爱吃肉的动物叫作肉食动物，被它们吃的动物是猎物，它们会跟踪并捕捉猎物。你家里养的小猫和小狗都是肉食动物，老虎也是。注意啦，老虎会很高兴吃掉你的猫、吞下你的狗，所以不能把它们关在一起。
女：这么说，爱吃草的动物就是草食动物了？
男：没错，以植物为主要食物的动物统统归入草食动物，包括大象、马、牛、羊等等。
女：还有的动物既吃动物也吃植物，应该属于哪一类呢？
男：动植物都吃的动物，被称为杂食动物。比如小猪、熊等等。希望小朋友也是杂食动物啊，这样营养才会全面。还有吃昆虫的动物是食虫动物，这类动物包括食蚁兽等。
女：那这些动物之间有什么关系吗？
男：肉食动物吃草食动物，草食动物吃植物……科学家把动物彼此之间谁吃谁的关系，画成了一张特殊的关系图，称为食物链或食物网。如果草食动物灭绝了，肉食动物也会灭绝，因为它们没有东西可吃了。如果肉食动物灭绝了，草食动物的数目会大量增加，并吃光所有植物。接着，草食动物会因为没有东西可吃而灭绝。

*** 音频

9482629a-206f-4221-b7ef-dc739ae567f3.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 59d88310-c4c5-4eb2-ad80-9f188a8d8f0a
:END:

***** 问题

明明老师介绍了哪种动物分类方法？

***** 音频

3a5bc738-434e-4e1a-bb8b-737c2f465e9b.mp3

***** 选择

****** A

根据动物的体型分类

****** B

根据动物的食物分类

****** C

根据动物的栖息地分类

****** D

根据动物的身体结构分类

***** 答案

B

**** 7
:PROPERTIES:
:ID: d54513de-be1e-40e3-9665-2c681984e84c
:END:

***** 问题

文中没提到哪类动物？

***** 音频

3da9dff3-c9b6-45f9-b58f-bb5bf3a14921.mp3

***** 选择

****** A

肉食动物

****** B

草食动物

****** C

杂食动物

****** D

食鱼动物

***** 答案

D

**** 8
:PROPERTIES:
:ID: ce4fc365-dd59-4bb6-b712-a045ab55024d
:END:

***** 问题

明明老师为什么希望小朋友也是杂食动物？

***** 音频

892a7702-19a5-4a82-80a6-521071287370.mp3

***** 选择

****** A

营养更全面

****** B

吃得更安全

****** C

更节省资源

****** D

性格会更好

***** 答案

A

**** 9
:PROPERTIES:
:ID: 49d6f7b8-e120-4ffa-9180-f8bc257e7f77
:END:

***** 问题

下列哪种关系被称为食物链？

***** 音频

61339aa3-dd8d-45a9-98b7-83ccf5d03ed4.mp3

***** 选择

****** A

草食动物吃植物

****** B

肉食动物吃草食动物

****** C

肉食动物吃杂食动物

****** D

动物间谁吃谁的关系

***** 答案

D

**** 10
:PROPERTIES:
:ID: 1e6b9b44-d80a-4150-b275-f1cac3b18e28
:END:

***** 问题

如果草食动物灭绝了，会出现什么情况？

***** 音频

bdbd2d12-4f71-48ff-aeaa-49ba5096a3bb.mp3

***** 选择

****** A

肉食动物也灭绝

****** B

植物都会被吃光

****** C

杂食动物也灭绝

****** D

食虫动物也灭绝

***** 答案

A

