* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 534d1afe-eaed-42b5-b757-650b5cf96eb8
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
52a0b2f7-3255-4972-a1bc-0c631dbf0c4d.mp3
***** 转录
那次聚会我至今记忆犹新。一群富家子弟，山珍海味都已吃过，就是不曾见过西点西餐，在校长家里他们才算真正“大开洋荤”，吃的是西式糕点，喝的是咖啡、可乐。
**** 选择
***** A
有钱就能整天山珍海咖
***** B
餐桌上多数是大鱼大肉
***** C
大家喜欢在校长家里聚餐
***** D
在校长家吃的是西式餐点
**** 答案
D
*** 2
:PROPERTIES:
:ID: 3e2b0679-c826-470d-a78d-4a3f840bce23
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
7770ee84-3b17-4a0c-81d1-8deab7fa650e.mp3
***** 转录
捕杀野生动物、破坏生态平衡的行为之所以屡禁不止，皆因“利”之驱动。如果捕杀了野生动物卖不出去，且有严格的法律法规，犯法就兑现，捕杀就会被重判，干这个行当的人就会越来越少。
**** 选择
***** A
野生动物保护应继续加强
***** B
捕杀野生动物都会被严惩
***** C
有人竟然驱车捕杀野生动物
***** D
捕杀野生动物的现象已很少
**** 答案
A
*** 3
:PROPERTIES:
:ID: ae68e76f-1bf1-4b0a-88fb-51ffb203e487
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
ff06a7ac-aaf3-49d2-8063-ae11b1d2cf11.mp3
***** 转录
我碰了无数次壁，也没推出自己的歌，我绝望了，想重返地铁口，从此安心做我的地铁歌手，并发誓永远不再去那个所谓的歌坛折腾。这时候，一位真正有才有德的艺人出现了，是他彻底改变了我的命运！
**** 选择
***** A
说话人得到了别人的帮助
***** B
说话人的命运在别人手里
***** C
说话人坚持履行自己的诺言
***** D
说话人是一副失败者的姿态
**** 答案
A
*** 4
:PROPERTIES:
:ID: 94699cf7-1c7f-46de-9edb-4c7c57899166
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fc3aada2-14a1-49a2-a672-6f404b6f7fad.mp3
***** 转录
在访谈中，我的一些说法可能有失偏颇，请大家原谅。在一些文章中，我的观点不够成熟，请大家包涵。总之，在传媒行业，我有许多东西需要学习，真诚地希望通过本书结识更多的媒体同行，向大家请教学习。
**** 选择
***** A
说话人经常得罪人
***** B
说话人出版了一本书
***** C
说话人文章写得很漂亮
***** D
说话人是个刚人门的记者
**** 答案
B
*** 5
:PROPERTIES:
:ID: f11c8ebd-5d8d-4b0f-a035-08d22e200723
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
10ee7f76-6c8d-4d59-90e6-0cf4de618dc8.mp3
***** 转录
当代中学生“青春期”发育普遍提前，尤其是女中学生，由于身心发展普遍比男生快，加上独生女在家庭中的地位得到强化，她们往往敢于做一些引人注目、与众不同的事，爱说一些令人吃惊的话，比男生更敢于顶撞和冒犯父母。
**** 选择
***** A
当代独生女都很能干
***** B
独生子女都被宠坏了
***** C
青春期女孩更具叛逆性
***** D
现在的中国学生很不听话
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 4a226529-7735-4691-af9e-8979b513ac87
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
7a051a43-150e-48eb-9f02-7b3e098ddf2e.mp3
***** 转录
女：不少人认为《西游记》是儿童读物，请问您是怎样看待《西游记》的特点以及它在中国文学史上的地位的？
男：《西游记》是中国古代小说中最容易为儿童接受的作品，这本身就是极为可贵的。要知道，中国古代除了民间故事和童谣，儿童可读的作品几乎没有。不过，这并不意味着《西游记》是肤浅的。一方面，对童心童趣的向往，可能是人难以泯灭的本性。而《西游记》神奇瑰丽、自由天真的想象，或许有助于我们暂时回归这一本性。另一方面，《西游记》又不只是单纯的童话，其中蕴含了丰富的中国文化。
女：您能具体谈一谈吗？
男：具体来说，孙悟空的机智勇敢、诙谐幽默代表了英雄主义和乐观主义；唐僧的坚定虔诚、软弱无能反映出旧时代知识分子面对瞬息万变的现实时缺乏应对能力；猪八戒的贪图安逸、目光短浅体现了传统农民的保守心理；至于沙和尚的勤恳依顺，也折射着我国民众朴实善良的品性。
女：有道理。
男：能够以一部作品如此鲜活地概括民族性格的几个重要类型，在古代小说中是不多见的。
女：这么说，即使在今天，《西游记》也还是很有现实意义的。
男：对呀。我们常常可以在以上这些人物身上看到自己或者我们相识的人的影子。也许，你渴望摆脱一切束缚，那么，孙悟空一定是你心仪的榜样；也许，你有时不免为物色诱惑，做出些荒唐可笑的事，那么，不妨以猪八戒为自嘲的镜子；万一你不幸如唐僧处处逢灾，又无能为力，也不必自怨自艾，只要虔诚坚定，西天还是可以到达的；假如你普普通通，默默奉献如沙和尚，最终也会赢得人们的赞赏和尊敬。
**** 题目
***** 6
:PROPERTIES:
:ID: 1702f390-7b41-4d35-bae9-db5e50c8f43c
:END:
****** 问题
******* 音频
d0866e39-4d86-4f29-9da1-c27bad68a7be.mp3
******* 转录
关于《西游记》的可贵之处，下列哪项正确？
****** 选择
******* A
容易为儿童接受
******* B
书中有民间故事
******* C
书中有许多童诫
******* D
是为儿童创作的
****** 答案
A
***** 7
:PROPERTIES:
:ID: 14cdf506-26ca-4d01-8533-d544d174a8ef
:END:
****** 问题
******* 音频
ff714da0-cbb3-4b9e-a1ea-908708cdab13.mp3
******* 转录
为什么说《西游记》并不肤浅？
****** 选择
******* A
它是一部优秀的童话
******* B
它能启发人的想象力
******* C
它能帮助成年人回忆童年
******* D
它有丰富的中国文化内淼
****** 答案
D
***** 8
:PROPERTIES:
:ID: 40d70744-f420-4273-ab6a-7bef5b94ff43
:END:
****** 问题
******* 音频
fcefb446-2415-4f54-9f43-0079e71a0785.mp3
******* 转录
关于《西游记》反映的民族性格，可以知道什么？
****** 选择
******* A
孙悟空反映出中国人很重视集体观念
******* B
唐僧反映出古代知识分子对现实的不满
******* C
猪八戒反映出中国传统农民的乐观心理
******* D
沙和尚反映出中国人朴实而善良的品格
****** 答案
D
***** 9
:PROPERTIES:
:ID: 194d9181-f562-4d0a-baaf-49fc6d037598
:END:
****** 问题
******* 音频
1c0ce09e-68f9-4227-b540-ae1cc839d2d9.mp3
******* 转录
关于《西游记》的现实意义，下列哪项正确？
****** 选择
******* A
孙悟空仍是我们学习的榜样
******* B
性格懦羽也不是要命的缺点
******* C
从中可以看到现代人的影子
******* D
默默奉献的精神才会受尊敬
****** 答案
C
***** 10
:PROPERTIES:
:ID: 524a187d-1664-43a1-aa57-ceb482701aa9
:END:
****** 问题
******* 音频
2087bf80-c7e8-4b80-876e-9cd644e178a9.mp3
******* 转录
这段话主要谈的是什么？
****** 选择
******* A
《西游记》的故事情节
******* B
《西游记》与儿童文学
******* C
《西游记》中的人物性格
******* D
《西游记》的特点和历史地位
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 06eea3d2-5649-4b60-bd2f-b071c780ceca
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
f82993ff-0e08-48d5-ab44-8fe713287f75.mp3
***** 转录
塞万提斯出生在一个医生家庭，有过军旅生活的经历，并屡立战功，得到嘉奖，曾经被俘身负重伤。当他拿着元帅的保荐书，兴致勃勃归国时，途中再次被俘，做了 5 年苦工后才得以回国。没想到，回来后，他连工作都找不到，历尽艰辛，才勉强找了份工作，后又被诬陷入狱。出狱后，他干上了税收。一次他把税款交给一家银行保管，偏偏银行倒闭，他第二次入狱。
出狱后，他陷入贫困，妹妹、妻子、儿女，一大家子人都等着他抚养。他住的地方环境极其恶劣，楼下就是酒馆。一天，有人酒后斗殴，眼看就要发生命案，他不顾一切，把那人背到家里，谁知人没救活，他涉嫌谋杀再次入狱。
虽然恶运缠身，他却没有被打倒，相反思想却变得异常丰富。他凭着对生活的反思和斗牛士的精神，写出了震惊世界的巨著——《堂•吉诃德》。
**** 题目
***** 11
:PROPERTIES:
:ID: 05e4a349-e9b0-4c02-ac28-4566054d2af0
:END:
****** 问题
******* 音频
b6427548-a0b2-4914-823b-2ae75daec2c7.mp3
******* 转录
塞万提斯靠什么出的名？
****** 选择
******* A
医术
******* B
军功
******* C
经历
******* D
作品
****** 答案
D
***** 12
:PROPERTIES:
:ID: 733771f8-f00c-4118-a3c9-505e3d247dd1
:END:
****** 问题
******* 音频
139405ac-3148-4216-ae56-be91c5afc266.mp3
******* 转录
关于塞万提斯的经历，下列哪项正确？
****** 选择
******* A
他做过军医
******* B
他做过斗牛士
******* C
他曾三次人狱
******* D
他做过三次俘虏
****** 答案
C
***** 13
:PROPERTIES:
:ID: 2feb3820-6be5-41d3-8be5-d23843318567
:END:
****** 问题
******* 音频
3133d6c0-84c8-4103-9fdf-c58e652b370e.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
他的运气特别不好
******* B
他喜欢银行的工作
******* C
他天生是个思想家
******* D
他一直在为写作做准备
****** 答案
A
*** 14-17
:PROPERTIES:
:ID: ba7f366d-3593-4008-acaf-86893a9b4541
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
053bc7d0-0916-436f-8992-8c5841c1a234.mp3
***** 转录
“我的手还能活动；我的大脑还能思维；我有终生追求的理想；我有爱我和我爱着的亲人与朋友；对了，我还有一颗感恩的心……”。谁能想到这段豁达而美妙的文字，竟出自一位在轮椅上生活了三十余年的高位截瘫的残疾人——世界科学巨匠霍金。
在常人看来，命运真是亏待了霍金，可他仍感到自己很富有：一根能活动的手指，一个能思维的大脑……这些都让他感到满足，并对生活充满了感恩之心。因而，他的人生是充实而快乐的。
对生活、对世界、对身边熟悉和陌生的人、对我们的朋友和对手，怎么能不真诚感谢呢？是它们使我们的人生变得如此精彩。我们更要真诚地感恩生活中的逆境，它让我们得到锤炼；它是一个课堂，让我们学会了刻苦、忍耐、淡泊和宽容；它是一笔财富，经历了它，会让我们精神富有，终生享用不尽。
**** 题目
***** 14
:PROPERTIES:
:ID: 5d44df82-8c5a-41bf-b4e7-4368ffcccc7f
:END:
****** 问题
******* 音频
38e65e21-a553-4024-81a3-766e7344f934.mp3
******* 转录
根据这段话，世界科学巨匠霍金很珍惜什么？
****** 选择
******* A
工作的权利
******* B
灵活的大脑
******* C
祺高的理想
******* D
方便的轮椅
****** 答案
B
***** 15
:PROPERTIES:
:ID: 2f7b49d9-9e5d-4411-abcd-1e732ab825d1
:END:
****** 问题
******* 音频
43567925-7c3a-4e17-98c0-e7d2c34df6b8.mp3
******* 转录
关于常人眼中的霍金，下列哪项正确？
****** 选择
******* A
非常容易满跃
******* B
有雄厚的经济实力
******* C
命运对他极其苛刻
******* D
对物质生活要求不多
****** 答案
C
***** 16
:PROPERTIES:
:ID: ac1056d7-6e3f-48fd-bb71-c173e0c8d7fe
:END:
****** 问题
******* 音频
a1ee43ea-69cb-40b3-b541-27f5742b53cb.mp3
******* 转录
关于生活中的逆境，下列哪项正确？
****** 选择
******* A
它让我们的身体得到锻炼
******* B
它让我们得到更多的知识
******* C
它让我们嬴得了大量钱财
******* D
它让我们学会了如何感恩
****** 答案
D
***** 17
:PROPERTIES:
:ID: 808c528d-aee4-4b89-ba6d-0eb38d8795bb
:END:
****** 问题
******* 音频
106db23a-ac37-4c6d-a276-225f31428e08.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
有对手的生活才有味道
******* B
转变逆境需要好的对策
******* C
学生的生活也会有坎坷
******* D
挫折可以帮助我们成长
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
他拍拍胸脯，很把握地说：“剩下的事情我来去办。”
***** B
共同语是社会打破地域隔闽、走向统一时出现的语言形式。
***** C
记得，我们是学校的第一批毕业生，我们的毕业典礼隆重极了。
***** D
细加分析，大多数情况下，他打架还是出于义愤，而非无理取闸。
**** 答案
*** 19
**** 句子
***** A
他自以为动机正确，做事就可以理直气壮。
***** B
期未成绩好，因为不是运气好，而是平时努力学习的结果。
***** C
他幻想着自己躺在海滩上，沐浴在阳光里，耳边海浪拍岩之声不断。
***** D
民族素质指我国境内各民族全体成员个体和群体的素质，亦称国民素质。
**** 答案
*** 20
**** 句子
***** A
作业发下来了，他看到自己的作文里错字那么多，而且错得五花八门，到处都是。
***** B
夜深丁，他还在左思右意，绞尽脑汁地合计新型的配药处方、剂量的多少以及服用的方法等。
***** C
这些年，在礼尚往来中，有些礼品已变了昧，不再是友情的象征，而成为贿赂的手段与工具。
***** D
词在运用的范围方面，有些多用于书面表达，有些多用于口头语言；有些多用于庄严的场合，有些只用于日常的场合。
**** 答案
** 第二部分
*** 21
**** 段话
大院的邻里相处得[[gap]]融洽是久有[[gap]]的。但是这个大院的怪现象却令人费解一一许多户居民做饭时把门窗关得很[[gap]]，即使三伏天也不例外。难道是做好吃的怕人家讨要不成？
**** 选择
***** A
****** 1
和睦
****** 2
耳闻
****** 3
严
***** B
****** 1
和平
****** 2
传闻
****** 3
紧
***** C
****** 1
友善
****** 2
所知
****** 3
实
***** D
****** 1
亲善
****** 2
闻名
****** 3
快
**** 答案
*** 22
**** 段话
女儿为了从我这里获得[[gap]]的自由，不知道和我打了多少次架，吵过多少次嘴。事实上，在[[gap]]孩子的过程中，我是很[[gap]]的，而女儿也是很[[gap]]的，真可谓是棋逢对手。
**** 选择
***** A
****** 1
生长
****** 2
管理
****** 3
野蛮
****** 4
坚定
***** B
****** 1
成才
****** 2
辅导
****** 3
粗暴
****** 4
死板
***** C
****** 1
成长
****** 2
教育
****** 3
霸道
****** 4
固执
***** D
****** 1
发展
****** 2
培育
****** 3
无理
****** 4
刚强
**** 答案
*** 23
**** 段话
有时候你只是在某些事情上不愿[[gap]]对方，一个小小的谎言便脱口而出，即使不是恶意的，但这也可能造成大大的[[gap]]。因此，下一次当你想要[[gap]]时，还是再三思考一下，是否说出[[gap]]更好？
**** 选择
***** A
****** 1
得罗
****** 2
害处
****** 3
扯谧
****** 4
真相
***** B
****** 1
奉告
****** 2
损害
****** 3
造诫
****** 4
事实
***** C
****** 1
报告
****** 2
圈套
****** 3
骗人
****** 4
实话
***** D
****** 1
告知
****** 2
伤害
****** 3
撒谧
****** 4
实情
**** 答案
** 第三部分
*** 段话
人之所以会心累，就是常常徘徊在坚持和放弃之间。坚持与放弃，是每个人面对人生问题的一种态度。如果我们懂得取舍，该坚持的坚持，该放弃的放弃，[[gap:24]]。
人之所以会痛苦，就是追求太多。人生在世，不可l含l【邑事事顺心。不要总觉得自己不幸，其实世界上比我们痛苦的人多的是。明知道有些理愚永远无法实现，有些问题永远没有答案，有些故事永远没有结局，[[gap:25]]，无谓地等待和幻想。
人之所以不快乐，就是计较太多。[[gap:26]]，而是我们计较得太多。不要总是只看到别人的幸福，自己总是心存失落和压扼。其实你只看到了表面现象，或许他过得还不如你。[[gap:27]]，人人都想得到自己想要的东西，人人都在为了自己的目标整天忙碌着，奋斗着。得到了开心一时；得不到，痛苦一世。
世界上没有完美无缺的东西，[[gap:28]]，只有在不断争取、不断承受失败与挫折时，才能发现快乐。
*** 选择
**** A
就免去了举棋不定的烦恼
**** B
不是我们拥有得太少
**** C
人的欲望是无止境的
**** D
可还是要苦苦地追求
**** E
不完美其实才是一种美
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
心理学家对孤独是有不同认识的，尽管更多的人认为，亲密的人际关系是人类幸福和快乐最主要的源泉，但是《孤独》一书却认为：亲密关系是人生有价值的重要部分，但并非幸福的唯一源泉，而且孤独对于树些人是必霁的《孤独》一书列举了很多艺术家、哲学家、科学家在孤独中做出创造性贡献的例子，即使普通人，很多特别具有创造性的工作一样需要不和他人发生关系而独立完成。
《孤独》的作者说：人类一生被两种相反的驱动力操纵着，一种是对陷伴、爱以及其他所有能让我们亲近同类的关系的渴望，另一种则是对独立、孤单和自主的向往。大部分作家、音乐家、画家注定一芬子大多数时间都是孤独的。
需要孤独的人在揭示一些东西的过程中必须专注，因此，你想培养孩子的想象力，就要让他们拥有一些享受孤独的时间和机会，并在其中自得其乐。大家都知道《彼得免》的故事。《彼得兖》的作者波特小姐从来没有上过学，和父母关系也很淡薄，很少有机会和其他孩子一起均耍，大部分时间和宠物在一起，她把想象力和强烈的情感都投射在动物身上，创作出了不朽的儿童作品。
**** 题目
***** 29
****** 问题
《孤独》一书的观点是：
****** 选择
******* A
是人就会湖望亲近同类
******* B
孤独对某些人是不可或缺的
******* C
有亲密的人际关系才可能幸福
******* D
心理学界争端的实质是何为幸福
****** 答案
***** 30
****** 问题
《孤独》一书举了很多例子，其中人物的共同特点是：
****** 选择
******* A
他们都成名成家了
******* B
他们不会与人合作
******* C
他们做的事有创造性
******* D
他们都非常喜欢孤独
****** 答案
***** 31
****** 问题
如果想培养孩子的想象力，就要：
****** 选择
******* A
让他们树立远大志向
******* B
让他们天天自得其乐
******* C
从小训练他们全神贯注
******* D
让他们有些独处的时间
****** 答案
***** 32
****** 问题
关于《彼得兖》的作者，下列睇项正确？
****** 选择
******* A
父母对她疑于管理
******* B
宠物的事撂得她很忙
******* C
她的作品发行量一航
******* D
对宠物在情感上很慷慨
****** 答案
*** 33-36
**** 段话
晏子出使楚国，楚国人想嘲笑他身材矮小，特意在城门旁开了一个小门，请晏子从小门进去。晃子说：“出使狗国的人才从狗洞进去。今天我出使的是楚国，应该不从此门进吧！”楚国人只好请晏子进了大门。
晏子拜见楚王。楚王说：“齐国恐怕是没人了吧？怎么派你来呢。”晏子答复说：“齐国都城人口众多，人们一起张开袖子，天就暗下来；一起探洒汗水，就会汇成大一。怎么能说齐国没人呻？”楚王说：“那为什么派你这样一个人来做使臣呢？”晏子回答：“齐国派遣使臣，要看对象，贺能的人被派遣出使到规能的国王那里去，无能的人被派遣出使到无能的国王那里去，我晏婴是齐国最没有才能的人了，荣幸地出使到楚国。”
晏子来楚之前，楚王对身边的大臣说：“晏婴特别能说，我怎么羞辱他一下吱？”大臣提议：“他来的时候，我们绑一个人来。大王就问：”他是什么人？“我们就说：「齐国人。大王再问：”犯了什么罪？“我们就说：「他是小偷。。”“如此这般，君臣谋划完毕。
晏子到了楚国，楚王请晏子喝酒。喝得正高兴的时候，两个官吏绑着一个人来到楚王面前。楚王问：“绑的是什么人？”小吏回答：“是齐国人，犯了偷窃罪。”
楚王对晏子说：“齐国人都善于偷东西吗？”晏子从容答道：“我听说橡标生长在淮河以南就是橡树，生长在淮河以北就变为架子，树叶形状相似，果实的昧道却全变了，皆因水土不同。这个人在齐国不偷东西，到了楚国就偷起东西来，茧非是楚国的水土使然？”楚王听后苦笑着说：“真是不能和有实力的人开玩笑，我反而自取其辱了”
**** 题目
***** 33
****** 问题
面对楚国为自已开的小门，晏子：
****** 选择
******* A
很气愤
******* B
很兴奋
******* C
很机智
******* D
很无奈
****** 答案
***** 34
****** 问题
按晃子的意思，他被派遣出使楚国是因为：
****** 选择
******* A
齐国人个子都矮
******* B
齐国人多，不好选
******* C
楚国是个无赖国家
******* D
楚王是最无能的国君
****** 答案
***** 35
****** 问题
晏子来楚之前，楚王和大臣共同：
****** 选择
******* A
设计幽套
******* B
审理案件
******* C
妄想害人
******* D
碱商国事
****** 答案
***** 36
****** 问题
晏子讲栩树的故事，是要说明：
****** 选择
******* A
楚国的声誉并不好
******* B
楚国的小偷比齐国多
******* C
楚国使好人变为了坏人
******* D
楚王的阴谋已经得逞了
****** 答案
