* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: c2769224-a9bc-40c5-aeea-defa81ec91cf
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
098ec147-f9a6-444d-bd33-c1fbf6c381d5.mp3
***** 转录
女性杂志很受欢迎，实际上这类杂志并没有什么内涵和底蕴，读者不会从杂志中真正获得多少信息，得到的只是休息和放松。也就是说，“没什么实质性内容”反而成了女性杂志吸引人的地方。
**** 选择
***** A
女性杂志的格调普道不高
***** B
女性读者对杂志内容要求很高
***** C
女性读者希望杂志提供丰富信息
***** D
女性杂志因读起来轻松而受欢迎
**** 答案
D
*** 2
:PROPERTIES:
:ID: 94853412-5ff8-4b7c-9bb4-f485ba5f78d4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
6373d342-d0e0-4832-907b-42a7bedf7e15.mp3
***** 转录
远古的地球，除了海水就是绿色。森林不但是原始人类的栖息之地，也是他们生产和生活资料的来源。然而，随着经济的发展与人口的增长，人类正在以摧毁地球为代价，肆无忌惮地砍伐着森林。
**** 选择
***** A
没有森林就没有人类
***** B
远古人类靠海洋生存
***** C
远古人类生活在森林中
***** D
人类必须增强资源意识
**** 答案
C
*** 3
:PROPERTIES:
:ID: cd908bbc-85e7-4de7-9856-e1ba64f543d4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
ae57bec0-feca-4313-9f03-2ea90909eb85.mp3
***** 转录
他表演的相声在嬉笑怒骂间，用他自己的语言与判断陈述了相声界的现状及他本人曲折的经历。令他意外的是，这个段子赢得的竟然是台下相声爱好者的眼泪，然后是如雷般的掌声。
**** 选择
***** A
他表演相声时经常又哭又笑
***** B
他做相声演员本身是个意外
***** C
他的相声反映了相声的发展历程
***** D
他的相声收到了意外的表演效果
**** 答案
D
*** 4
:PROPERTIES:
:ID: 019b79fb-d827-4f47-ba44-4e88909c0f1f
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
ac9d5299-4daa-4360-b0de-b3b036645c0e.mp3
***** 转录
樱花是日本民族的骄傲，它同雄伟的富士山一样，是勤劳、勇敢、智慧的象征。每年的 3 月 15 日，是日本的樱花节。这一天,日本的男女老少都会到公园或野外赏樱花，东京的上野公园在这天还有花宴、花会、花舞等种种活动。
**** 选择
***** A
日本人很喜欢山
***** B
日本是个爱美的国家
***** C
日本把樱花视为骄傲
***** D
3月15日是日本的国庆节
**** 答案
C
*** 5
:PROPERTIES:
:ID: 0ef41aeb-4c80-4a2f-aaec-9c8098ad086e
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
f8079d05-e816-4939-9de6-e46c2f127a10.mp3
***** 转录
地毯怕湿，若不保持干燥，就会发霉，被虫蛀，缩短使用寿命。地毯每年最好在阳光下晾晒二三次。晒时要用木棍敲打，把地毯里的灰尘弹出。地毯如溅上酱油、菜汤和其他油脂，应立即用干净的干抹布轻轻擦去，切忌用湿抹布擦。
**** 选择
***** A
地毯使用寿命很短
***** B
地毯不能经常暴晒
***** C
地毯不可用涨布擦
***** D
地毯上不可撒汤类等东西
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 5507774e-33d2-42e3-a258-ec618e9a5322
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
859fd2f5-700c-4ac9-9176-ea3a115da230.mp3
***** 转录
女：感谢您应邀接受我们的采访。您对健康、农业、移动银行等领域做出了预测，我们就聊聊这些领域吧。
男：先说说埃博拉吧。希望我们可以消灭埃博拉，我们已经取得了很大进步，中国在其中付出了许多努力，投入了很多资源。事实证明应对这样的传染病爆发，需要广泛的国际合作。至于为什么健康会成为基金会的第一要务，是因为没有健康，贫困国家不仅会有很多孩子死亡，还会有很多孩子因为疾病或营养不良而丧失发展的机会，所以健康是最基本的保障。
女：在农业方面，您刚才提到，中国是稻米生产的行家，还有哪些方面中国可以贡献更多的力量呢？
男：首先中国在农业生产力方面实现了大幅度提升，而有的国家农业生产力大概是世界平均水平的五分之一，无论是政策扶持或是科技创新，中国都有很多经验。我们正在和中国合作，确保合适的技术被应用到非洲有需求的国家，并为当地带来实实在在的好处。
女：那么移动银行呢？您觉得什么技术是移动银行革新的关键？
男：如果我们在贫困地区推广传统银行，那么传统银行的收费结构对于贫困地区的居民来说成本过高，所以贫困地区的人会倾向于使用现金，同时传统银行的借贷利率也很高，所以它们不适用于这些地区。我们必须在这些地区推行新的银行，必须价格低廉而且高效，所以我们要推广电子银行。即便你只借一块或两块钱，服务成本也是非常低的。我们同时会对农民进行教育，教会他们如何借贷，如何更好地管理储蓄等。传统银行不能为穷人提供服务，但是这些新兴银行可以，我们需要做的是确保相关监管到位，推动普及教育，提高大家的信任度，并激励更多的创新者为电子银行开发新的产品和应用。
**** 题目
***** 6
:PROPERTIES:
:ID: 1196e4fe-0db0-406f-a188-649246c2cd98
:END:
****** 问题
******* 音频
728873c5-f294-419d-8dc2-377add321c4c.mp3
******* 转录
关于健康，男的首先谈到了什么？
****** 选择
******* A
如何控制埃博拉疫情
******* B
钦佩、赞叹中国的医疗水平
******* C
许多国家为防治疾病投人了资金
******* D
对付某些传染病暴发需要国际合作
****** 答案
D
***** 7
:PROPERTIES:
:ID: 2aca8bac-a5bd-46bb-9c27-5ae02ebd6bce
:END:
****** 问题
******* 音频
904e905a-6571-4375-96cc-6befcfe7672a.mp3
******* 转录
没有健康会怎样？
****** 选择
******* A
会重新陷人贫囱
******* B
会丧失发展机会
******* C
会导致人口危机
******* D
会减少投资收益
****** 答案
B
***** 8
:PROPERTIES:
:ID: 1f0e450a-de44-4347-9d00-66b7ae650e87
:END:
****** 问题
******* 音频
f0f6d372-ad09-4db3-8e14-2436619ee7bb.mp3
******* 转录
在农业方面，中国可以做出什么贡献？
****** 选择
******* A
成为稻米生产的行家
******* B
研究如何提高生产力水平
******* C
介绍中国政策扶持的好经验
******* D
根据当地的需求推广合适的技术
****** 答案
D
***** 9
:PROPERTIES:
:ID: 40711852-9b11-4582-b1d1-a4515dd111aa
:END:
****** 问题
******* 音频
585356c1-e783-4f96-9b3d-e7db3f96c04c.mp3
******* 转录
对于贫困地区，传统银行有什么问题？
****** 选择
******* A
现金不足
******* B
成本过高
******* C
利率不透明
******* D
服务不到仨
****** 答案
B
***** 10
:PROPERTIES:
:ID: eed5a7b4-ca20-400c-9360-20727d513c16
:END:
****** 问题
******* 音频
a302c930-8dd0-4643-9836-89460d1cea04.mp3
******* 转录
关于移动银行，下列哪项正确？
****** 选择
******* A
借一块钱不收费
******* B
价格低廉效率高
******* C
可替农民管理储花
******* D
监管到位信任度高
****** 答案
B
** 第三部分
*** 11-13
:PROPERTIES:
:ID: eb46ace2-8bc7-4fed-a275-292811000798
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
d50e2b8c-7101-4d49-b927-12d394bb221c.mp3
***** 转录
托尔斯泰年轻时和屠格涅夫是好朋友。遗憾的是，有一天他们发生了争执，从此断交，一断就是 17 年。这期间，托尔斯泰一直在忙碌，恋爱、结婚、办学校、写作等。他分别用 6 年和 3 年的时间创作了《战争与和平》与《安娜·卡列尼娜》，这两部鸿篇巨著的先后问世，把他推到了文学的巅峰。
步入 50 岁时，托尔斯泰开始对人生哲理进行新的探索。忆及屠格涅夫时，他惊奇地发觉，心中对屠格涅夫充满怀念，两人在一起喝酒、聊天、骑马、散步和讨论手稿的情景历历在目，屠格涅夫对他的鼓励、赞扬犹在耳边，他情不自禁地给屠格涅夫写了一封信。
屠格涅夫收到信，立刻从国外赶回来，直奔托尔斯泰的庄园。俩人见面紧紧相拥。屠格涅夫含着热泪说：“我是流着泪读完您那封信的，惭愧的是，首先写那封信的为什么不是我呢！”
世间再伟大的友谊也有受伤的时候，友谊需要包容，更需要真诚，唯有真诚能治愈受伤的心，唯有真诚能唤回友人远去的脚步。
**** 题目
***** 11
:PROPERTIES:
:ID: 8f1abddc-8b38-4292-9b97-7bb3eeb6ccf5
:END:
****** 问题
******* 音频
9f671d82-1042-4610-8070-421c737b3c8c.mp3
******* 转录
关于托尔斯泰，下列哪项正确？
****** 选择
******* A
他谈恋爱用了17年
******* B
他17年写了两部小说
******* C
他主动跟屠格涅夫和解
******* D
他的兴趣是喝酒、聊天
****** 答案
C
***** 12
:PROPERTIES:
:ID: d16fb461-b614-4a51-be5a-3897646cb52c
:END:
****** 问题
******* 音频
84a9db00-77c6-48f0-a58a-62a3603cbc83.mp3
******* 转录
关于屠格涅夫，下列哪项正确？
****** 选择
******* A
他很珍惜友情
******* B
他一直在养病
******* C
他缺少自省精神
******* D
他主动写信认错
****** 答案
A
***** 13
:PROPERTIES:
:ID: 8600e755-01cd-4a33-8d62-532212374cac
:END:
****** 问题
******* 音频
8f7460a2-6510-4c5f-bcd2-527e9d9d5c86.mp3
******* 转录
这段话主要想告诉我们什么？
****** 选择
******* A
友谊需要真诚对待
******* B
多好的朋友都会吵架
******* C
世界上没有牢固的友谊
******* D
放下架子也没什么大不了
****** 答案
A
*** 14-17
:PROPERTIES:
:ID: b7ba7a1a-3fed-459f-8315-929b96d27155
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
0808db1e-827f-4465-a873-894fb1475108.mp3
***** 转录
那是一个晴朗的早晨。公园里，一个得了绝症的男孩在轻声歌唱，他在歌唱生命，他认为没有一样东西是永远不变的，生命也一样。不远处，一个女孩在跳舞，舞姿如蝴蝶。
男孩看到了正在跳舞的女孩，坐在旁边，静静地看她把舞跳完，说了句“你跳得真好。”“谢谢！”女孩回答。男孩看着女孩清秀的面孔，惊异地发现，那是两只无神的眼睛——她是个盲女。男孩的心抽动了一下。
他们认识了。一有空，就会在公园相见，男孩唱歌，女孩伴舞。一天又一天，一种强烈的欲望渐渐从男孩心中升起……
这天，女孩兴奋地告诉男孩，有人愿意捐出眼角膜，那真是最宝贵的礼物，不久自己就能见到光明了。男孩笑了笑，对女孩说：“我曾经不相信世界上有永远不变的事物，但我现在明白世上存在永恒，那就是友情。我要走了，永远都不回来了，我将永远珍藏我们的友谊。”
女孩没想到，男孩的告辞竟是永别，而且给自己留下最宝贵礼物的就是他。
女孩的手术成功了，她看到了这个美丽的世界，虽然她一直没有机会亲眼看到男孩，但男孩在她的心里永远是清晰的。
**** 题目
***** 14
:PROPERTIES:
:ID: 66b88f92-fd76-4cf9-8443-e982bc396df8
:END:
****** 问题
******* 音频
efa478a4-5db3-417a-9ab3-7dccc150eac1.mp3
******* 转录
关于那个晴朗的早晨，下列哪项正确？
****** 选择
******* A
男孩在公园里歌唱
******* B
男孩想给女孩惊腺
******* C
女孩在给男孩跳舞
******* D
公园里有很多蝴蝶
****** 答案
A
***** 15
:PROPERTIES:
:ID: e3361e14-c4c2-4862-8008-7e57725e6026
:END:
****** 问题
******* 音频
698303c5-7d52-4601-aac1-39be47fe08f0.mp3
******* 转录
关于女孩，下列哪项正确？
****** 选择
******* A
她是个舞蹈演员
******* B
她的眼睛失明了
******* C
她早就认识男孩
******* D
她想帮男孩治病
****** 答案
B
***** 16
:PROPERTIES:
:ID: ecae25a1-6ceb-4eef-a940-8f1e879fca95
:END:
****** 问题
******* 音频
34a8a179-87d4-4a13-b6a5-fe34d1145be3.mp3
******* 转录
关于男孩，下列哪项正确？
****** 选择
******* A
他很欣赏会跳舞的女孩
******* B
他告别女孩远走他乡了
******* C
他生病后变得非常悲观
******* D
他逝世后捐出了眼角膜
****** 答案
D
***** 17
:PROPERTIES:
:ID: 84bd7474-102d-44c3-8065-c6ea90b02714
:END:
****** 问题
******* 音频
8255acf5-0997-44f5-a814-c13f14429de1.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
男孩善良而宽容
******* B
男孩死于心脏病
******* C
女孩重见了光明
******* D
医生的医术高明
****** 答案
C
* 阅读
** 第一部分
*** 18
**** 句子
***** A
学习成绩的提高，主要取决于是否学生努力。
***** B
老头儿一个巴掌打去，吴三差点儿被打趴下，嘲角顿时流出血来。
***** C
南海波涛汹涌，夜间行船更是危险，即将远行的李云望着海面出神。
***** D
和“十七年”电影相比，20世纪90年代以后的电影主旋律发生了明显的变化。
**** 答案
*** 19
**** 句子
***** A
中国古代诗歌很讲究节奏和押韵，音乐感很强。
***** B
他把自己构想中的车体形状画在一张乐谱的背面拿给我看。
***** C
随着秦兵马俑在沉寂24年后的再次发掘，引起了国内外媒体的关注。
***** D
黎明之前，客机在空中窝然粉碎性解体，141名机组人员和乘客全部遇难。
**** 答案
*** 20
**** 句子
***** A
睡前在脸上涂抹鸡蛋清，早上起来用清水洗，可使脸部肌肤润滢，保持青春的美丽。
***** B
萤火虫原本在野草从生的荒凉的地方出没，如今竟在宫院中飞来飞去，说明宫女生活的凄凉。
***** C
在他的遗体前，我们悲痛万分。他一直关心和照顾着我们一家，可我们还没来得及感谢他，他就走了。
***** D
经济泡沫与泡沫经济是两个不同的概念，前者反映的是“局部”的经济现象；后者反映的是“全局”的经济形象，不可混为一谈。
**** 答案
** 第二部分
*** 21
**** 段话
“民间艺术”，是艺术领域中的一[[gap]]分类，冠以“民间”字样，[[gap]]是要与所谓的“宫廷艺术”与“贵族艺术”等有所区分，而且“民间艺术”的领域也更[[gap]]。
**** 选择
***** A
****** 1
份
****** 2
不止
****** 3
壮观
***** B
****** 1
项
****** 2
显然
****** 3
宽广
***** C
****** 1
类
****** 2
明确
****** 3
美妙
***** D
****** 1
门
****** 2
向来
****** 3
平凡
**** 答案
*** 22
**** 段话
纽约是个艺术的大都会，[[gap]]那里的很多街头艺人[[gap]]，完全可以上卡耐基音乐厅进行[[gap]]。但为什么他们会在街头或地铁站里表演呢？说[[gap]]了这其实是一种生活方式。
**** 选择
***** A
****** 1
据说
****** 2
技艺超群
****** 3
演奏
****** 4
白
***** B
****** 1
传说
****** 2
难能可贵
****** 3
表演
****** 4
穿
***** C
****** 1
话说
****** 2
出类拔萃
****** 3
演出
****** 4
明
***** D
****** 1
虽说
****** 2
超群出众
****** 3
上演
****** 4
破
**** 答案
*** 23
**** 段话
坐在他对面，听他侃侃而谈，我有时会产生这样的[[gap]]：这个人怎么这么奇怪？中国传统文化中[[gap]]熏陶出博学儒雅的文士、忍辱负重的忠良、[[gap]]悲歌的英雄，但极少会有他那份泼辣、尖刻、诙谐的[[gap]]。
**** 选择
***** A
****** 1
怀疑
****** 2
不时
****** 3
豪迈
****** 4
气魄
***** B
****** 1
疑问
****** 2
不免
****** 3
豪壮
****** 4
真挚
***** C
****** 1
困扰
****** 2
时而
****** 3
正气
****** 4
气概
***** D
****** 1
疑惑
****** 2
间或
****** 3
慷慨
****** 4
气质
**** 答案
** 第三部分
*** 段话
家里穷得揭不开锅了，户F子只兰要〕乙石身曹亘着身吏皮至‖玉垩荃1r可侯家芝…丁翼F`予才釜l曼监河侯爽快地答应下来，说：“行，等我收到租税后，[[gap:24]]。”庄子听罡满脸沿丧，对监河侯说：“我昨天赶路，半路听到呼救声。珩帧周不见人影，再观察周围，[[gap:25]]，呼吸急促，气息奄奄。”庄子叹了口气说：“唉，它见到我，像遐见救星般向我水救据说，这条鱼原住东海，不幸沦落车辙，眼看就快要干死了，请求路人给点儿水，救救性命。”[[gap:26]]，问他是否救助了那条鱼。庄了冷冷地说：“我说可以，等我到南方，请人帮忙把清澈的江水引到你这儿来，你就可以游回东海老家去了！”
[[gap:27]]，说：“那怎么行呢7”是啊，鱼也说眼下断了水，没有安身之处，只需几桶水就能解阴，你那叫远水不解近渴呀，不等把水引来，我就成了干鱼啦！“
“远水解不了近渺”，[[gap:28]]，用以讽刺说大话、讲空话、不解决实际问题的做法。我们提倡少说空话，多办实事。
*** 选择
**** A
原来干涠的车辙里腐着一条鱼
**** B
马上借你300两银子
**** C
监河侯认为庄子的救助方法十分荒唐
**** D
这是人们的常识
**** E
监河侯听了庄子的话
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
