* Text

** title

高山流水遇知音

** content

俞伯牙从小酷爱音乐，他的琴声优关磁动听，犹如高山流水一般。虽然大家都赞美他琴弹得好，却从没有人能真正领会他琴声的内涵，他多想找到自己的知音啊！

一个中秋之夜，他乘船来到江边，偶偶风浪，船停在了一个类似港湾的地方。晚上，风浪渐渐平息，天气晴朗，江水清澈，景色十分迷人。

望着空中的明月，俞伯牙来了兴致拿出琴弹了起来，一会儿他就沉醉在了音乐之中。忽然他看到一个人雕塑一样站在岸边，似乎听得出了神。俞伯牙一个不留神，“啪”的一声，琴弦拨断了一根。这时，听琴的人大声说：“先生不必在意，我是个打柴的，回家晚了，走到这里听到您在弹琴，觉得琴声美妙，不由得站在这里听了起来。”

俞伯牙借着月光仔细打量，见那人身旁放着刚刚砍伐来的木柴，果然是个打柴的。俞伯牙心想：一个打柴的怎么能听懂我的琴呢？偏僻的山野还有这么不平凡的人？于是他问：“你既然懂琴，那就请说说，我弹的是什么曲子？”打柴人说：“先生刚才弹的乐谱是孔子为赞叹他的弟子而创作的，只可惜，您弹到第四句的时候琴弦断了。”俞伯牙不禁感叹，民间真有精通音乐之人，难能可贵！他迫不及待地想和打柴人好好聊聊。

打柴人应邀上了船，看到俞伯牙的琴，赞道：“真是好琴。”接着又说起瑶琴的来历，俞伯牙不禁心生钦佩。接着俞伯牙又为打柴人演奏了几曲，请他辨识其中之意。当他的琴声雄壮豪迈的时候，打柴人说：“这旋律表达了高山的雄伟壮观。有气势，有气魄！”当琴声曲激越、节奏短促时，打柴人说：“这旋律表达的是波涛汹涌，浪花飞溅，气概非凡！”当琴声变得清新流畅时，打柴人说：“这旋律表达的是无尽的流水。”俞伯牙惊喜万分，过支没人能听懂他琴声的含义，没想到在这荒凉之地，竟觅到自己久寻不遇的知音，不仅能领会其意，还能领悟其神打柴人叫钟子期，两人在月下侃侃而谈，越谈越投机。黎明将至，钟子期秸辞，并与俞伯牙约定，来年中秋还在这里相见。


第二年中秋这天，俞伯牙如约来到了老地方，从黄昏等到夜幕降临，一直不见钟子期到来，他有些沮丧，开始用琴声呼唤钟子期，可还是见不到钟子期的影子。该不是有了什么变故吧？俞伯牙焦急万分。

第二天，俞伯牙向一位老人打听他的好友，老人告诉他，仲子期染病，逝世己有段时间了。临走前，他留下遗言，把坟墓修在江边，到八月十五，好听俞伯牙弹琴。老人的话使俞伯牙泪流不止，他来到仲子期坟前，弹了一曲《高山流水》，曲终，他把心爱的琴摔了个粉碎，悲伤地说：“欲与向来是要弹给知音听的，如今我唯一的知音己不在人世，这琴还弹给谁听呢？”

故事有些凄凉，但两位知音的深情厚谊感动了后人，至今人们还用“知音”来形容朋友之间真挚而纯洁的情谊。

** footnotes

① 中秋：中国传统节日“中秋节”，为每年的农历八月十五。

** source



** new words



