* 听力

** 1

*** 1

**** transcript

不知不觉中，互联网已经进入了我们的生活。我们可以通过互联网得到海量信息，从天文到地理，从深水到太空，从远古到现代，从国内到国外；我们可以通过互联网学习，浏览新闻杂志，获知发生在世界各地的时事要闻。互联网给我们的生活带来了乐趣，使我们的生活变得更加充实。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 2

**** transcript

我们班一大半同学都有手机，虽然每次上课老师都要求我们关掉手机，但关不关就看自己了，很多人都把手机调到振动状态，在桌子下面偷偷玩。很多同学都对发短信上瘾，有同学喜欢自己编写各种短信，下课的时候还比较谁的短信新鲜好玩。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 3

**** transcript

作为年轻人，我们上网更多的是消遣和娱乐，有许多同龄人认为，网络这个完全虚拟的世界是我们放松自己的最佳场所。也许正因为这一点，我们的家长和老师才会对学生上网表现出不同程度的抵制，因为他们认为网上的娱乐分散了我们过多的精力，会对学业造成影响；更为重要的是，他们害怕网络上的不良信息对我们的身心不利。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 4

**** transcript

钱包不带没关系，手机千万不能忘，人们越来越深刻地感受到：在手机支付已成为重要的支付方式的今天，出门已不必非要手机、钱包、钥匙一样都不能少。互联网之所以能够进入金融业，不是因为互联网天生能做金融，而是因为传统的金融业忽略了网络支付功能。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

与传统的房地产开发模式相比，众筹建房的确大大缓解了房地产企业的销售压力。以往，在开发商的总成本中，融资成本和销售成本分别占比7％和3％左右，如今通过互联网设立的融资平台，房企绕过银行获得了新的融资渠道，从而将融资成本大大降低。另一方面，合伙众筹的成员也有机会从中受益，不但房价更合算，并且可以按照自己的需求定制房产，满足个性化需求。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

**  第二部分

*** 对话

女：您好！您能不能重点跟我们谈谈，社交网站给传统交往方式带来了哪些影响？
男：最近几年，社交网络非常流行。用户可以在网站创建一个公开或半公开的个人账号，展示和自己有联系的其他用户，查看和搜索与自己有联系的用户以及与朋友有联系的用户，还能交到新朋友，和更多的人建立起联系。
女：这是人们使用网站的主要目的吗？
男：还不是。
女：那人们使用社交网站的主要目的是什么呢？
男：应该说，社交网站主要体现的还是现实世界中的人际关系。社交网站使我们能够和平时不常见的人保持联系，但是要注意，介绍陌生人给你并不是社交网站的意图。
女：那现实中的友谊和互联网中的友谊有什么区别呢？
男：现实中的友谊和互联网上的友谊并不相同。在线联系并不意味着你们交换过电话号码，对于一些联系人，也许你觉得线上交流比线下交流舒服。网上的友谊一般是慢慢积累起来的，人们一般会在网上增加联系，而不会切断联系。而且，我们和朋友在网上的交流方式也不一样，比如在网上我们的交流更加简洁，而不是专注的、较长时间的对话。
女：在线上社交网络中，我们不仅维护着和所有朋友的珍贵友情，还能看到他们和其他人的交往和互动。这一点比在现实生活中要容易得多。
男：确实，有时候，你的线上好友传上一组照片，你会发现他们刚和你去了同一个国家……突然之间，你和好友的距离一下子就拉近了，对好友的日常生活一下就有了了解。也许你还会发现和你线上好友互动的人中，也有你的朋友，而你之前并不知道他们认识，这对于你，也许是一份惊喜。
