* 听力

** 1

*** 1

**** transcript

不知不觉中，互联网已经进入了我们的生活。我们可以通过互联网得到海量信息，从天文到地理，从深水到太空，从远古到现代，从国内到国外；我们可以通过互联网学习，浏览新闻杂志，获知发生在世界各地的时事要闻。互联网给我们的生活带来了乐趣，使我们的生活变得更加充实。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 2

**** transcript

我们班一大半同学都有手机，虽然每次上课老师都要求我们关掉手机，但关不关就看自己了，很多人都把手机调到振动状态，在桌子下面偷偷玩。很多同学都对发短信上瘾，有同学喜欢自己编写各种短信，下课的时候还比较谁的短信新鲜好玩。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 3

**** transcript

作为年轻人，我们上网更多的是消遣和娱乐，有许多同龄人认为，网络这个完全虚拟的世界是我们放松自己的最佳场所。也许正因为这一点，我们的家长和老师才会对学生上网表现出不同程度的抵制，因为他们认为网上的娱乐分散了我们过多的精力，会对学业造成影响；更为重要的是，他们害怕网络上的不良信息对我们的身心不利。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 4

**** transcript

钱包不带没关系，手机千万不能忘，人们越来越深刻地感受到：在手机支付已成为重要的支付方式的今天，出门已不必非要手机、钱包、钥匙一样都不能少。互联网之所以能够进入金融业，不是因为互联网天生能做金融，而是因为传统的金融业忽略了网络支付功能。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

与传统的房地产开发模式相比，众筹建房的确大大缓解了房地产企业的销售压力。以往，在开发商的总成本中，融资成本和销售成本分别占比7％和3％左右，如今通过互联网设立的融资平台，房企绕过银行获得了新的融资渠道，从而将融资成本大大降低。另一方面，合伙众筹的成员也有机会从中受益，不但房价更合算，并且可以按照自己的需求定制房产，满足个性化需求。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b
