* 听力

** 1

*** 1

**** transcript

不知不觉中，互联网已经进入了我们的生活。我们可以通过互联网得到海量信息，从天文到地理，从深水到太空，从远古到现代，从国内到国外；我们可以通过互联网学习，浏览新闻杂志，获知发生在世界各地的时事要闻。互联网给我们的生活带来了乐趣，使我们的生活变得更加充实。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 2

**** transcript

我们班一大半同学都有手机，虽然每次上课老师都要求我们关掉手机，但关不关就看自己了，很多人都把手机调到振动状态，在桌子下面偷偷玩。很多同学都对发短信上瘾，有同学喜欢自己编写各种短信，下课的时候还比较谁的短信新鲜好玩。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 3

**** transcript

作为年轻人，我们上网更多的是消遣和娱乐，有许多同龄人认为，网络这个完全虚拟的世界是我们放松自己的最佳场所。也许正因为这一点，我们的家长和老师才会对学生上网表现出不同程度的抵制，因为他们认为网上的娱乐分散了我们过多的精力，会对学业造成影响；更为重要的是，他们害怕网络上的不良信息对我们的身心不利。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 4

**** transcript

钱包不带没关系，手机千万不能忘，人们越来越深刻地感受到：在手机支付已成为重要的支付方式的今天，出门已不必非要手机、钱包、钥匙一样都不能少。互联网之所以能够进入金融业，不是因为互联网天生能做金融，而是因为传统的金融业忽略了网络支付功能。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

与传统的房地产开发模式相比，众筹建房的确大大缓解了房地产企业的销售压力。以往，在开发商的总成本中，融资成本和销售成本分别占比7％和3％左右，如今通过互联网设立的融资平台，房企绕过银行获得了新的融资渠道，从而将融资成本大大降低。另一方面，合伙众筹的成员也有机会从中受益，不但房价更合算，并且可以按照自己的需求定制房产，满足个性化需求。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

**  第二部分
:PROPERTIES:
:ID: e127423e-09c6-4643-b76c-3ea089fb9016
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：您好！您能不能重点跟我们谈谈，社交网站给传统交往方式带来了哪些影响？
男：最近几年，社交网络非常流行。用户可以在网站创建一个公开或半公开的个人账号，展示和自己有联系的其他用户，查看和搜索与自己有联系的用户以及与朋友有联系的用户，还能交到新朋友，和更多的人建立起联系。
女：这是人们使用网站的主要目的吗？
男：还不是。
女：那人们使用社交网站的主要目的是什么呢？
男：应该说，社交网站主要体现的还是现实世界中的人际关系。社交网站使我们能够和平时不常见的人保持联系，但是要注意，介绍陌生人给你并不是社交网站的意图。
女：那现实中的友谊和互联网中的友谊有什么区别呢？
男：现实中的友谊和互联网上的友谊并不相同。在线联系并不意味着你们交换过电话号码，对于一些联系人，也许你觉得线上交流比线下交流舒服。网上的友谊一般是慢慢积累起来的，人们一般会在网上增加联系，而不会切断联系。而且，我们和朋友在网上的交流方式也不一样，比如在网上我们的交流更加简洁，而不是专注的、较长时间的对话。
女：在线上社交网络中，我们不仅维护着和所有朋友的珍贵友情，还能看到他们和其他人的交往和互动。这一点比在现实生活中要容易得多。
男：确实，有时候，你的线上好友传上一组照片，你会发现他们刚和你去了同一个国家……突然之间，你和好友的距离一下子就拉近了，对好友的日常生活一下就有了了解。也许你还会发现和你线上好友互动的人中，也有你的朋友，而你之前并不知道他们认识，这对于你，也许是一份惊喜。

**** 音频

963c8350-cd24-43ab-ae10-18b10051053f.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 075b50bd-f6c1-491e-a362-a1b42dee258b
:END:

***** 问题

人们在社交网站上可以做什么？

****** 音频

ee062aa4-d4d6-4187-9872-46f3a79262ba.mp3

***** 选择

****** A

炫耀和自己有联系的朋友

****** B

查看其他网络用户的账号

****** C

通过朋友交到更多的朋友

****** D

建立自己公开或半公开的账号

***** 答案

D

**** 7
:PROPERTIES:
:ID: c7bad2b7-000a-44e6-b102-52aa3b7ec53e
:END:

***** 问题

人们使用线上社交网站的主要目的是什么？

****** 音频

cc78f6e3-cfc9-42a8-bcbc-66f510d2db5a.mp3

***** 选择

****** A

迅速扩大朋友的范围

****** B

和更多的陌生人成为朋友

****** C

和不易见面的朋友保持联系

****** D

与已失联的朋友重新建立联系

***** 答案

C

**** 8
:PROPERTIES:
:ID: df251837-0b4d-446f-838a-4b2145d53cb7
:END:

***** 问题

与网上交流方式相比，线下交流的特点是什么？

****** 音频

0024cf16-c1da-4916-b495-36a83ffa0146.mp3

***** 选择

****** A

交流更加简洁

****** B

联系更加频繁

****** C

对话更加专注

****** D

对话时间更短

***** 答案

C

**** 9
:PROPERTIES:
:ID: 1049cab8-ea88-4267-a60c-4c763943dec0
:END:

***** 问题

互联网中的友谊有什么特点？

****** 音频

0fc51a17-5e6e-4fe6-98bf-28ef58a3b9e6.mp3

***** 选择

****** A

交流起来更加任性

****** B

不想联系了就自然断交

****** C

都不要对方的电话号码

****** D

建立友谊尤其靠日积月累

***** 答案

D

**** 10
:PROPERTIES:
:ID: 73ced705-a59d-42fb-8a89-3f6c2721791e
:END:

***** 问题

根据对话，什么情况下，我们会有惊喜？

****** 音频

accc8168-a760-4e01-8c68-687f7925e964.mp3

***** 选择

****** A

看到朋友传上的照片

****** B

和朋友一块儿去旅游

****** C

发现和朋友住得很近

****** D

发现和朋友有共同的朋友

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

网络的信息资源很有限

***** B

互联网充实了我们的生活

***** C

我们可以通过互联网环游世界

***** D

互联网让我们进入别人的生活

**** 段话

不知不觉中，互联网已经进入了我们的生活。我们可以通过互联网得到海量信息，从天文到地理，从深水到太空，从远古到现代，从国内到国外；我们可以通过互联网学习，浏览新闻杂志，获知发生在世界各地的时事要闻。互联网给我们的生活带来了乐趣，使我们的生活变得更加充实。

***** 音频

4a359d1a-2051-4a23-9cab-e13ecc2f93a9.mp3

**** 答案

B

*** 2

**** 选择

***** A

很多同学玩儿游戏上瘾

***** B

下课后大家会比较谁的手机好

***** C

老师对手机的管理不那么严格

***** D

老师脾气好，学生不听话就算了

**** 段话

我们班一大半同学都有手机，虽然每次上课老师都要求我们关掉手机，但关不关就看自己了，很多人都把手机调到振动状态，在桌子下面偷偷玩。很多同学都对发短信上瘾，有同学喜欢自己编写各种短信，下课的时候还比较谁的短信新鲜好玩。

***** 音频

fb1902e2-caf7-43d7-b006-c19941c19443.mp3

**** 答案

C

*** 3

**** 选择

***** A

家长和老师担心互联网诈骗

***** B

家长和老师担心互联网让人变怪

***** C

家长和老师担心互联网让人急功近利

***** D

家长和老师担心互联网会分散学生的精力

**** 段话

作为年轻人，我们上网更多的是消遣和娱乐，有许多同龄人认为，网络这个完全虚拟的世界是我们放松自己的最佳场所。也许正因为这一点，我们的家长和老师才会对学生上网表现出不同程度的抵制，因为他们认为网上的娱乐分散了我们过多的精力，会对学业造成影响；更为重要的是，他们害怕网络上的不良信息对我们的身心不利。

***** 音频

b3220956-715f-473c-a39d-943ca8278768.mp3

**** 答案

D

*** 4

**** 选择

***** A

互联网天生适合做金融

***** B

出门丢什么都不能丢手机

***** C

如今手机支付已十分普遍

***** D

手机、钱包、钥匙必须随身带

**** 段话

钱包不带没关系，手机千万不能忘，人们越来越深刻地感受到：在手机支付已成为重要的支付方式的今天，出门已不必非要手机、钱包、钥匙一样都不能少。互联网之所以能够进入金融业，不是因为互联网天生能做金融，而是因为传统的金融业忽略了网络支付功能。

***** 音频

df34fbdd-10bf-410c-8f3a-78e4165956ba.mp3

**** 答案

C

*** 5

**** 选择

***** A

众筹建房会增加融资成本

***** B

众筹建房的成员可以定制房产

***** C

房地产企业在众筹建房中很尴尬

***** D

传统房地产开发模式销售压力更小

**** 段话

与传统的房地产开发模式相比，众筹建房的确大大缓解了房地产企业的销售压力。以往，在开发商的总成本中，融资成本和销售成本分别占比 7%和 3%左右，如今通过互联网设立的融资平台，房企绕过银行获得了新的融资渠道，从而将融资成本大大降低。另一方面，合伙众筹的成员也有机会从中受益，不但房价更合算，并且可以按照自己的需求定制房产，满足个性化需求。

***** 音频

8cf63feb-9995-41aa-b892-be3215b01a9f.mp3

**** 答案

B

