* Text

** title

互联网时代的生活

** content

互联网走进我们的生活没有多久，却让我们实实在在地感受到生活正生着日新月异的変化：它能让我们自如地通话、视频、传递消息，哪怕你在天涯海角口它使我们的生活不再单调沉闷，每一天都变得浪漫、丰富和充实口它将异地购物、交易变为了可能--我们足不出户就能任意挑选欧洲、美洲的商品；我们可以在网上找工作，简单又高效；我们能设立个人网站，既能扩不你的朋友圈，又能让你小小的虚荣心得到满足，如果愿意，还可以设立你亲友的网站，作为赠送给他们的珍贵礼物。最近又有人通过网络，和朋友、朋友的朋友合伙筹备资金买房，人们视这一创举为互联网金融下的新成员。

据集资买房项目发起人介绍，此次众筹买房，初步打算召集200人，筹备建立众篿家园小区。众筹购房的好处在于价格上拥有明显优势，比市场价至少便宜30％，无论是投资还是自隹，都很合算。项目沟通中，微信是主要渠道，申请人递交申請表、通过中，微信群，项目的设计、户型、价格等，全部由不家商议决定。

不家深知买房对每个家庭都不是小事，众筹买房也还处于摸索阶段，因此必须慎重。众筹的参与者，都是发起人的朋友，或者朋友的朋友。他们层次较高，都有一定的经济基础，对新生事物有强烈好奇之，基本属于同一阶。用发起人的话说，众筹不是在筹房子，而是在凝聚人心。房子怎么设计、对国家的政策怎么理解、失败了怎么办？不家每天在微信群你来我住，忙碌而欢东，除了产肃的房价，这种共商不事的感觉也很让人上瘾。

什么是“众筹”？说白了，就是不家筹钱干一件事，上文所说的“众筹”更像是“集资建房”，广义的“众筹”则是互联网金融的产物，指创业者通过网络，向众多素不相识的人争取资金支持。

世界上第一个让初创公司梦想成真的众筹网站是美国的Kickstarter。2011年5月，中国国内首家众筹网站--点名时间，将Kickstarter模式搬进了中国，之后众筹平台越来越多。如今，仈慈善到图书出版，仈电影制作到创业项目，众筹几乎跨越了所有的领域。

美微传媒CEO①朱江做梦也没想到他成了传说中的“中国众筹第一人”。那年，朱江开始在淘宝网出售美微会员卡，购实会员卡就是购实公司的原始股票票，每股1．2元，最低认购100股，也就是说，花120元就可以成为持有美微股份的股东。朱江回忆起当时钞票源源不断流进来的感觉，真的有种苦尽甘来的味道。时至令日，众筹项目有成功的，也有处境尴尬的，而国内第一家众筹网站“点名时间”三年以后却拋弃了“众筹”，改营其他。坦白地讲，国内用户与国外有很不区别，比如，Kickstarter上聚集着一群理想主义者，他们心中充满向往，购买时感性因素超越了理性。国内用户则希望尽快得到回报，甚至有些急功近利，而用户的心态很不程度上决定了项目成功的可能性。再比如，国内用户对收获时间和产品质量要求较高，如果认为产品不符合预期，或是项目进展比计划白白方慢，就会紁牢骚，有怨气。另外，不部分投资者对众筹还是持观望态度。因此，迄今为止众筹在国内还是一个看起来很美、做起来吃力的事情。

是啊，在互联网变得家喻户晓，给我们的生活带来许许多多的方便和乐趣的同时，也给我们增添了无穷无尽的烦恼，众筹平台上有，其他领域也有。据官方报道，尚未查明身份的罪犯盗窃了1800万个电子邮件账户及其密码口仅有两三个人的皮包公司①化然冒充国家部门开设了一家假网站，不肆进行詐骗，如今已被警方依法刑事拘留；还有时时活跃着的网络黑黫客①。 每次类似这些败坏互联网名誉的事件一经曝曝光，就会使我们有触目惊心之感。

这就是互联网时代，在们对它爱不释手的同时，也不免对它心存担忧。

** footnotes

① CEO: 首席执行官。［Chief Executive Officer 的缩写］
① 皮包公司：指沒有固定资产、没有固定经营地点及人员，只提着皮包，从事社会经济活动的人或集体，多挂有公司的名义。
① 年月通过互联网非法侵入他人的计算机系统，查改，窃取保密数据或干扰计算机程序的人。

** new words

日新月异 / ri4 xin1 yue4 yi4 / to change rapidly, to alter from day to day ;
沉闷 / chen2 men4 / depressing, dull ;
充实 / chong2 shi2 / substantial, rich ;
衫易 / jiao1 yi4 / to do business, to trade ;
任意 / ren4 yi4 / arbitrarily, willfully ;
乐趣 / le4 qu4 / delight, pleasure, joy ;
设立 / she4 li4 / to establish, to set up ;
虚荣 / xu1 rong2 / vanity ;
珍贵 / zhen1 gui4 / valuable, precious ;
合伙 / he1 huo2 / to form a partnership ;
筹备 / chou2 bei4 / to prepare ;
成员 / cheng2 yuan2 / member ;
初步 / chu1 bu4 / initial, preliminary ;
合算 / he2 suan4 / worthwhile ;
渠道 / qu2 dao4 / channel, medium of communication ;
审查 / shen3 cha2 / to examine, to check ;
缴纳 / jiao3 na4 / to pay ;
摸索 / mo1 suo3 / to grope, to fumble, to feel about ;
层次 / ceng2 ci4 / level, layer ;
阶层 / jie1 ceng2 / stratum, rank ;
政策 / zheng4 ce2 / policy ;
欢乐 / huan1 le4 / happy, joyous ;
上瘾 / shang4 yin3 / to be addicted (to sth.), to get into the habit (of doing sth.) ;
慈 / ci2 shan4 / charitable ;
股份 / gu3 fen4 / share, stock ;
股东 / gu3 dong1 / shareholder, stakeholder ;
钞票 / chao1 piao4 / banknote, paper money ;
苦尽甘来 / ku3 jin4 - gan1 lai2 / all sufferings have their reward, after suffering comes happiness ;
尴尬 / gan1 ga4 / awkward ;
拋弃 / pao1 qi4 / to abandon, to cast aside ;
坦白 / tan3 bai2 / honest, frank ;
急功近利 / ji2 gong1 jin4 li4 / to be anxious to achieve quick success and get instant benefits ;
进展 / jin4 zhan3 / to make progress ;
牢骚 / lao2 sao1 / to grumble, to complain ;
迄今为止 / qi4 jin1 wei2 zhi3 / so far, up to now ;
吃力 / chi1 li4 / strenuou, laborious ;
家喻户晓 / jia1 yu4 hu4 xiao3 / to be known to every household ;
无穷无尽 / wu2 qiong2 wu2 jin4 / inexhaustible, boundless, endless, from everlasting to everlasting ;
罪犯 / zui4 fan4 / criminal, offender ;
盗窃 / dao4 qie4 / to steal ;
公然 / gong1 ran2 / openly, undisguisedly ;
冒充 / mao4 chong1 / to pretend to be ;
不肆 / da4 si4 / without restraint, recklessly ;
诈骗 / zha4 pian4 / to defraud ;
拘留 / ju1 liu2 / to detain ;
败坏 / bai4 huai4 / to ruin, to corrupt ;
名誉 / ming2 yu4 / fame, reputation ;
曝光 / bao4 guang1 / to expose ;



