* 练习

** 1
:PROPERTIES:
:ID: 510138bc-b941-44f7-a5ce-a32303454a65
:END:
*** 选择
**** 1
鼓舞
**** 2
公布
**** 3
消失
**** 4
幻想
**** 5
不安
**** 6
幸运
*** 题目
**** 1
***** 句子填空
小时候，他常[[gap]]着自己有一天了能成为一名导演。
***** 答案
4
**** 2
***** 句子填空
船翻了，他很[[gap]]地抱住一根木头，游到一个小岛上。
***** 答案
6
**** 3
***** 句子填空
大赛的作品将被放在网上，由网友打分，比赛结果于四月十五日[[gap]]。
***** 答案
2
**** 4
***** 句子填空
谈判的成功给了他极大的[[gap]]。
***** 答案
1
**** 5
***** 句子填空
接到电话，她感到有些[[gap]]，急忙连夜赶回家中。
***** 答案
5
**** 6
***** 句子填空
记录、保存将要[[gap]]的事物是摄影非常重要的作用。
***** 答案
3
** 2
*** 1
:PROPERTIES:
:ID: 1d3cd584-db74-4317-86e6-9e9c2f3b3e54
:END:
**** 句子填空
虽然我不同意你的看法，沄，但我还是[[gap]]你的选择。
**** 选择
***** A
酋敬
***** B
尊重
**** 答案
B
*** 2
:PROPERTIES:
:ID: dccddb5d-30f1-4976-b17d-6f55f3713c06
:END:
**** 句子填空
作品充分地表达了作者内心[[gap]]的情感。
**** 选择
***** A
真实
***** B
确实
**** 答案
A
*** 3
:PROPERTIES:
:ID: 674ff64a-ec4b-42b0-bee9-90293ce95bc8
:END:
**** 句子填空
那个城市的基础[[gap]]还不够完善。
**** 选择
***** A
设施
***** B
没备
**** 答案
A
*** 4
:PROPERTIES:
:ID: b4d57bdf-8d74-4c83-9e6f-6c83dbd3bc1e
:END:
**** 句子填空
这次考试能否通过，我实在没什么[[gap]]。
**** 选择
***** A
把握
***** B
掌握
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
贡献
***** 答案
力量
**** 2
***** 词语
放弃
***** 答案
幻想
**** 3
***** 词语
改变
***** 答案
命运
**** 4
***** 词语
鼓舞
***** 答案
人心
*** 2
**** 1
***** 词语
态度
***** 答案
消极
**** 2
***** 词语
话题
***** 答案
敏感
**** 3
***** 词语
联系
***** 答案
密切
**** 4
***** 词语
心神
***** 答案
不安
* 扩展
** 词语
*** 话题
资源
*** 词语
**** 1
金属
**** 2
黄金
**** 3
银
**** 4
钢铁
**** 5
煤炭
**** 6
能源
**** 7
原料
**** 8
资源
** 题目
*** 1
**** 句子
这种管子是[[gap]]管，只是从表面上看像塑料。
**** 答案
1
*** 2
**** 句子
“中国大妈”一词的产生充分证明中国是[[gap]]消费的大国。
**** 答案
2
*** 3
**** 句子
豆腐深受中国人的喜爱，制作它的主要[[gap]]就是黄豆。
**** 答案
7
*** 4
**** 句子
从目前中国能源消费结构来看，[[gap]]依然占主导地位。
**** 答案
5
* 注释
** （三）词语辨析
*** 鼓励——鼓舞
**** 做一做
***** 1
****** 句子
父母平时应[[gap]]孩子多参加体育活动。
****** 答案
******* 1
******** 鼓励
1
******** 鼓舞
0
***** 2
****** 句子
在工作中，管理者多[[gap]]员工，会提高员工的工作积极性。
****** 答案
******* 1
******** 鼓励
1
******** 鼓舞
0
***** 3
****** 句子
听了他们的发言，我挺受[[gap]]的，对他们很有信心。
****** 答案
******* 1
******** 鼓励
0
******** 鼓舞
1
***** 4
****** 句子
感谢大家对我的肯定与[[gap]]。
****** 答案
******* 1
******** 鼓励
1
******** 鼓舞
0
* 课文
** 转录
如果你觉得地球上的一点儿小污染没什么关系，那你可就大错特错了！环境污染会危害动物、植物以及人类自身。
有些生活在过去的动物，你今天再也看不到了，植物也面临着同样的危险。动植物的消失，部分原因是由于自然界的变化，比如洪水、地震等改变了它们生活的环境，但更大的原因则是人类对自然的破坏      有些地区的森林已经几乎被人砍光了，很多河流被污染，不再适合鱼类生存，有的地区原本是草原，如今已变为沙漠……从国际环保组织公布的数据可知，地球上一半以上的动植物正在消失，这是真实的情况，一点儿也不夸张。
人类自身也饱受污染的危害。有些地区地表水已污染，地下水又被过量使用，水资源短缺问题就连科学家们也不知道该如何解决，目前世界上有17％的人无法享用干净的饮用水，而每年死于与空气污染有关的疾病的人比死于车祸的还要多。这些数据确实令人不安。
一部分环境污染是由工业农业生产活动造成的，例如，大型工厂生产过程中，有的会产生大量废水；有的要大量燃烧煤炭，从而产生大量废气和废物。还有一部分污染和我们的日常生活密切相关，汽车尾气就是其中之一。此外，垃圾也会对环境造成严重的损害。
幸运的是，越来越多的人敏感地认识到了环境问题的严重，并自觉地投入到了保护地球的行动中。生产中，增加环保设施，减少污染物排放，调整能源消费结构，逐步向可再生能源转变；而在日常生活中，改变生活习惯，尽量减少生活垃圾，做到垃圾分类。同时，尽量多骑自行车，多选择公共交通，少使用私家车。这些为此付出努力的人们令人尊敬，取得的成绩也令人鼓舞。
地球是人类共同的家园，我们应该把它看作一个属于自己的大房间。房间脏了，消极的逃避和不符合实际的幻想都不能解决问题，为保持它的卫生每一个人都应付出行动，做出贡献。人类的命运由我们自己掌握，改变要靠我们自己。
