* 听力

** 第二部分
:PROPERTIES:
:ID: b1337463-fce6-4294-b1ac-97e5f8c9bbd8
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

*** 对话

女：大家好，今天我们请到了儿童文学作家赵老师，跟大家谈谈寓言。
男：我先从“寓言”这两个字谈起。“寓”的意思是“寄托”，“寓言”就是把作者的思想藏在一个故事里。
女：那“寓言”故事可不能听完就完了，必须弄明白其中的道理。
男：对。寓言很有特点。有位作家做过这样的描述：“寓言是一个怪物，当它朝你走过来的时候，它是一个故事，生动活泼；当它转身要走开的时候，却突然变成了一个哲理，严肃认真。”“寓言是一把钥匙，这把钥匙可以打开心灵之门，启发智慧，让思想活跃。”
女：嗯，这段话非常生动。赵老师，世界最早的寓言集是什么时候出现的？
男：大约成书在公元前 6 世纪，就是《伊索寓言》。
女：中国的寓言创作情况又是如何？
男：中国寓言创作的历史也很长，春秋战国时期，也就是大约 2000 多年前，寓言就已经广泛流传。当时中国思想界很活跃，一些政治家、思想家提出各自不同的主张，并且争论不休。他们喜欢借寓言表明自已的观点，因为在简单的故事中包含着大道理。
女：我发现那个时候流传下来的很多寓言我们都很熟悉，比如“揠苗助长”“自相矛盾”。
男：你说的不错。
女：汉语很多成语也是寓言，我们上面说的“揠苗助长”“自相矛盾”就是。那么，成语和寓言是什么关系呀？
男：成语是人们长期以来惯用的、简洁深刻的定型词组或短句，大多数是四个字。一般成语都有来源，有些成语从字面上就能理解，比如“后来居上”，这个成语最开始用在《史记》当中，意思是“后来者超过前辈”。而有些成语必须知道来源或典故才能懂得意思，如“朝三暮四”“画蛇添足”。
女：所以很多成语故事本身就是一个寓言故事，但不是所有的寓言故事都会形成成语。
男：对。

**** 音频

f70c00f8-249e-4637-bf46-1e19dcabc1a1.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 6568e163-8904-4023-ab86-73e2dcfb88d4
:END:

***** 问题

男的是干什么的？

****** 音频

34c25567-c6bb-4f4d-a34a-483c5f7b089c.mp3

***** 选择

****** A

 老师

****** B

作家

****** C

思想家

****** D

语言学家

***** 答案

B

**** 7
:PROPERTIES:
:ID: 0ce6e9a9-9471-43f6-bacf-e10ec0214a82
:END:

***** 问题

那位作家对寓言的描述表达的是什么意思？

****** 音频

bdb1d6f0-0708-4e55-b8f6-cbd586ef6820.mp3

***** 选择

****** A

寓言故事都有些奇怪

****** B

寓言作家都是聪明人

****** C

寓言故事常包含哲理

****** D

思想活跃才能写寓言

***** 答案

C

**** 8
:PROPERTIES:
:ID: 676aa094-3b06-4cbe-a23c-459f074237b9
:END:

***** 问题

以下哪一项符合 2000 多年前中国的情况？

****** 音频

81f86f78-243e-4acd-9fd5-b59383c87363.mp3

***** 选择

****** A

各种思想非常活跃

****** B

对寓言有很多争论

****** C

当时的人都喜欢寓言

****** D

创作了《伊索寓言》

***** 答案

A

**** 9
:PROPERTIES:
:ID: cd5ea622-b506-4cc4-9da1-fc614392363f
:END:

***** 问题

以下哪一项是成语的特点？

****** 音频

82792e31-fc54-4607-bab5-1a504ea1886c.mp3

***** 选择

****** A

都是四个字组成的

****** B

包含着深刻的道理

****** C

从字面就知道意思

****** D

是定型的词组或短句

***** 答案

D

**** 10
:PROPERTIES:
:ID: b9becc68-c53d-4691-9247-9ae6ad77e316
:END:

***** 问题

成语和寓言是什么关系？

****** 音频

e40f846d-6885-45a0-aa4b-f8d6877fb3d2.mp3

***** 选择

****** A

二者没有任何关系

****** B

成语都来源于寓言故事

****** C

寓言故事都可以形成成语

****** D

有的成语故事就是寓言故事

***** 答案

D

** 第一部分

*** 1
:PROPERTIES:
:ID: 73af10a6-27af-4128-af58-288861e3c4fb
:END:

**** 选择

***** A

白藤生长在温带地区

***** B

白藤的长度参差不齐

***** C

有的树上会生长长鞭

***** D

大树想摆脱白藤的缠绕

**** 段话

在热带、亚热带森林中，许多大树上都缠绕着一根根又细又长的“长鞭”，这就是白藤。一般的白藤长二三百米，最长的可达 400 多米,是植物中的长度冠军。白藤浑身长满小钩刺，当细长的白藤随风摇摆的时候，一旦碰上大树，倒生的小钩刺就会紧紧钩住大树不放。

***** 音频

207e8e73-a513-4641-a831-0230782524f5.mp3

**** 答案

B

*** 2
:PROPERTIES:
:ID: 6f3c4507-faf4-4fee-83fb-c8e3bfbdc7bc
:END:

**** 选择

***** A

经常抱怨有损健康

***** B

抱怨是一种心理疾病

***** C

爱抱怨的人不受欢迎

***** D

喜欢抱怨的人很愚蠢

**** 段话

你很可能从未注意过自己抱怨的习惯，但在别人的眼中，你已经是一个喜欢抱怨的人了。没有人愿意总是听你抱怨，因为抱怨会传播负面情绪，而负面情绪会使人们长时间地心情不好。

***** 音频

bc8dc9ae-e11b-4fc5-90f2-cad0158a8f76.mp3

**** 答案

C

*** 3
:PROPERTIES:
:ID: 27b42ca8-383a-4740-8c2b-df30b5331355
:END:

**** 选择

***** A

带着宠物去旅行的人不少

***** B

不喜欢坐飞机的人才开车

***** C

眼下假期开车远行很时髯

***** D

假期有人会带着狗去打猎

**** 段话

很多人选择假期开车出行，不是不想坐飞机，而是想带着自己的宠物，尽管主人会耗费更多的精力和体力。因此我们在高速公路上常会看到这样一幕：奔跑着的汽车的车窗中，一闪而过的是一张幸福的狗脸。

***** 音频

2fe3becf-dc69-484c-bb9d-7acfe654c453.mp3

**** 答案

A

*** 4
:PROPERTIES:
:ID: 85131b79-e6be-48ea-904e-bf7ca5d9045f
:END:

**** 选择

***** A

只要读书就会感到快乐

***** B

读书就是为了得到知识

***** C

要趁情绪好的时候读书

***** D

心灵与书相通就会快乐

**** 段话

读书最快乐的，并不一定是你学到了什么。知识不会给你带来最快乐的东西，而是你本来就有的一些想法和感受，在书中被唤醒了，“啊，我也是这么想的！”这时候你会很快乐。

***** 音频

8a06815b-e3e4-44fb-b623-503a9d47b10e.mp3

**** 答案

D

*** 5
:PROPERTIES:
:ID: b2d53b9c-7daf-47a0-8ea8-778c0d55bbbd
:END:

**** 选择

***** A

恶人就是恶人

***** B

那条蛇中毒而死

***** C

蛇的牙齿很锋利

***** D

做事之前应认真思考

**** 段话

农夫发现一条快冻死的蛇，觉得它很可怜，就把它放在怀里，用体温温暖着它。蛇暖和过来以后，咬了农夫一口，农夫中毒而死。农夫死前十分悔恨，说：“我可怜这家伙，得到这样的结果是应该的。”这故事说明，恶人的本性是不会改变的。

***** 音频

e5650e9f-3233-4f2d-83bf-852a954b38ce.mp3

**** 答案

A

** 第三部分

*** 11-13
:PROPERTIES:
:ID: 4e257fa8-ffa1-41fe-9ff1-3265d1c70027
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

**** 课文

大象因记忆力强而著称，但一份新的研究报告显示，大象还有预测天气的本领。大象的耳朵很大，对声音极其敏感，它们能听到远处很小的雷声和较大的雨声，由此可预测雨水何时会到来。

科学家们是在研究纳米比亚象群突然搬迁这一现象后得出上述结论的。研究小组记录了 9 头来自不同象群的大象的活动情况，经过历时七年的观察，研究人员发现，这些大象在纳米比亚的雨季经常改变行进路线，它们能对 200 多公里以外的天气“有感觉”，并凭这种感觉预测暴风雨，进而向有暴风雨的方向前行。大象需要雨，经过漫长的旱季，大象一旦知道哪里有雨，就会朝下雨的方向行进，这样它们可以更快地获得水源。

研究者认为，这项研究除了能够了解大象追逐暴风雨行进的状况、原因，更积极的意义在于，它有助于动物保护者预测大象的活动，从而使它们免遭偷猎者毒手。

***** 音频

9db5d575-ae67-43d3-9b91-ce04a240b729.mp3

**** 题目

***** 11
:PROPERTIES:
:ID: 82fd8bed-248f-4374-8c37-96b91a380fb9
:END:

****** 选择

******* A

耳朵特别大

******* B

对气候敏感

******* C

记忆力特别好

******* D

能对抗暴风雨

****** 问题

大象广为称道的特点是什么？

******* 音频

378a68eb-a2f8-4209-9046-7a2f67cdb65c.mp3

****** 答案

C

***** 12
:PROPERTIES:
:ID: da37364e-ca14-4299-aad8-843a63fe7812
:END:

****** 选择

******* A

大象总是追寻暴风雨

******* B

大象凭视觉选择路线

******* C

纳米比亚象群经常搬家

******* D

大象每天能走200公里

****** 问题

经过跟踪，研究者发现了什么？

******* 音频

34967a15-84b8-4ec3-ab20-21b7c7d33bb5.mp3

****** 答案

A

***** 13
:PROPERTIES:
:ID: 5675e676-11a4-4ae3-9f2e-4526c77117fc
:END:

****** 选择

******* A

有利于保护大象

******* B

有助于保护水源

******* C

使天气预报更为准确

******* D

可更好地预防自然灾害

****** 问题

这一研究成果的积极意义是什么？

******* 音频

a5b0d853-505a-447c-a66b-854e404bf7eb.mp3

****** 答案

A

*** 14-17
:PROPERTIES:
:ID: 003a1a8f-9d53-45e3-8dba-0fb2e4e7809a
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

**** 课文

有一种动物叫麋鹿。麋鹿的尾巴有些像驴尾，蹄子有些像牛蹄，面部有些像马面，角有些像鹿角，但整体看上去却似鹿非鹿，似马非马，似牛非牛，似驴非驴，因此又叫“四不像”。麋鹿性情温和，十分可爱。

有个人出去打猎，得到一头小麋鹿，决定把它带回家养起来。刚进家门，家里的几只狗就流着口水，摇着尾巴聚拢过来，主人气愤地吓跑了狗。此后主人每天抱着小麋鹿与狗接近，希望狗慢慢习惯，不再伤害小麋鹿。后来又逐渐让狗和小麋鹿一起玩耍，一段时间以后，狗能按主人的意愿做了。

小麋鹿稍微长大后，以为狗就是自己的好伙伴，不但对狗毫无防备之心，还整日和狗翻滚打闹，亲热极了。狗害怕主人，也就天天老老实实地和麋鹿玩耍，但还是会时常忍不住流出口水。

三年过去了，一次麋鹿独自出门，看见外面有很多不相识的狗，就跑过去想和它们一起玩儿。结果狗见了麋鹿，一起冲上去把麋鹿吃了。可怜的麋鹿到死也不明白这是怎么回事。

这则寓言告诉我们，认敌为友，必然会招致灭亡。

***** 音频

aeeeb593-cc67-4f85-aff5-42f2337fbbba.mp3

**** 题目

***** 14
:PROPERTIES:
:ID: 4081602d-1eb3-467a-98b7-d7ff89f7377a
:END:

****** 选择

******* A

十分胆小

******* B

样子最像鹿

******* C

是马的一种

******* D

性情温和顺从

****** 问题

麋鹿有什么特点？

******* 音频

009b441f-7f2e-43b9-adba-6028d3591748.mp3

****** 答案

D

***** 15
:PROPERTIES:
:ID: 3431523f-1ad9-4392-ae16-0f83c94d5663
:END:

****** 选择

******* A

狗被廉鹿吓跑了

******* B

主人天天抱着狗

******* C

主人看见狗就生气

******* D

主人让狗和糖鹿玩儿

****** 问题

主人把麋鹿带回家以后，家里发生了什么事？

******* 音频

555d7c47-d7ff-4618-a58b-c1857a49decc.mp3

****** 答案

D

***** 16
:PROPERTIES:
:ID: 296ba67c-14fa-4049-bee0-c26d30ba7d68
:END:

****** 选择

******* A

廖鹿和狗成了真正的朋友

******* B

家里的狗终于把廉鹿吃了

******* C

糠鹿独自出门遇到了危险

******* D

外面的狗也爱和糖鹿玩耍

****** 问题

三年后发生了什么事？

******* 音频

9c2f539c-0d09-4625-bc17-4b19e69e2ea8.mp3

****** 答案

C

***** 17
:PROPERTIES:
:ID: 0f3f9a4d-b30c-4c7c-8a2d-3de4c2786136
:END:

****** 选择

******* A

主人救了糖鹿

******* B

不能敌我不分

******* C

狗活得很委屈

******* D

狗都害怕主人

****** 问题

这则寓言告诉我们什么？

******* 音频

8e39162a-371e-4d79-82e0-d6e688218a77.mp3

****** 答案

B

