* 听力

** 1

*** 1

**** transcript

在热带、亚热带森林中，许多大树上都缠绕着一根根又细又长的“长鞭”，这就是白藤。一般的白藤长二三百米，最长的可达400多米，是植物中的长度冠军。白藤浑身长满小钩刺，当细长的白藤随风摇摆的时候，一旦碰上大树，倒生的小钩刺就会紧紧钩住大树不放。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

你很可能从未注意过自己抱怨的习惯，但在别人的眼中，你已经是一个喜欢抱怨的人了。没有人愿意总是听你抱怨，因为抱怨会传播负面情绪，而负面情绪会使人们长时间地心情不好。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

很多人选择假期开车出行，不是不想坐飞机，而是想带着自己的宠物，尽管主人会耗费更多的精力和体力。因此我们在高速公路上常会看到这样一幕：奔跑着的汽车的车窗中，一闪而过的是一张幸福的狗脸。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

读书最快乐的，并不一定是你学到了什么。知识不会给你带来最快乐的东西，而是你本来就有的一些想法和感受，在书中被唤醒了，“啊，我也是这么想的！”这时候你会很快乐。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

农夫发现一条快冻死的蛇，觉得它很可怜，就把它放在怀里，用体温温暖着它。蛇暖和过来以后，咬了农夫一；，农夫中毒而死。农夫死前十分悔恨，说：“我可怜这家伙，得到这样的结果是应该的。“这故事说明，恶人的本性是不会改变的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：大家好，今天我们请到了儿童文学作家赵老师，跟大家谈谈寓言。
男：我先从“寓言”这两个字谈起。“寓”的意思是“寄托”，“寓言”就是把作者的思想藏在一个故事里。
女：那“寓言”故事可不能听完就完了，必须弄明白其中的道理。
男：对。寓言很有特点。有位作家做过这样的描述：“寓言是一个怪物，当它朝你走过来的时候，它是一个故事，生动活泼；当它转身要走开的时候，却突然变成了一个哲理，严肃认真。”“寓言是一把钥匙，这把钥匙可以打开心灵之门，启发智慧，让思想活跃。”
女：嗯，这段话非常生动。赵老师，世界最早的寓言集是什么时候出现的？
男：大约成书在公元前 6 世纪，就是《伊索寓言》。
女：中国的寓言创作情况又是如何？
男：中国寓言创作的历史也很长，春秋战国时期，也就是大约 2000 多年前，寓言就已经广泛流传。当时中国思想界很活跃，一些政治家、思想家提出各自不同的主张，并且争论不休。他们喜欢借寓言表明自已的观点，因为在简单的故事中包含着大道理。
女：我发现那个时候流传下来的很多寓言我们都很熟悉，比如“揠苗助长”“自相矛盾”。
男：你说的不错。
女：汉语很多成语也是寓言，我们上面说的“揠苗助长”“自相矛盾”就是。那么，成语和寓言是什么关系呀？
男：成语是人们长期以来惯用的、简洁深刻的定型词组或短句，大多数是四个字。一般成语都有来源，有些成语从字面上就能理解，比如“后来居上”，这个成语最开始用在《史记》当中，意思是“后来者超过前辈”。而有些成语必须知道来源或典故才能懂得意思，如“朝三暮四”“画蛇添足”。
女：所以很多成语故事本身就是一个寓言故事，但不是所有的寓言故事都会形成成语。
男：对。
