:PROPERTIES:
:CREATED: [2022-03-28 22:27:49 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-03-28 22:27:52 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-28 22:27:54 -05]
:END:

Match the pictures with the words/phrases.

1. f

跳舞 | tiào wǔ | dance | bailar | verb ;

2. c

说话 | shuō huà | talk | hablar | verb ;

3. b

女 | nǚ | woman | mujer | noun ;

4. d

孩子 | hái zi | kid | niño | noun ;

5. a

唱歌 | chàng gē | sing | cantar | verb ;

6.

男 | nán | man | hombre | noun ;

** 2
:PROPERTIES:
:CREATED: [2022-03-28 22:27:58 -05]
:END:

Try to say the antonyms of the following words.

Word

贵 | guì | expernsive | caro | adjective ;

贱 | jiàn | inexpensive | barato | adjective ;

Word

对 | duì | right | correcto | noun ;

错 | cuò | wrong | incorrecto | noun ;

Word

左 | zuǒ | left | izquierda | ;

右 | yòu | right | derecha | ;

Word

里 | lǐ | inside | dentro | ;

外 | wài | outside | afuera | ;

Word

来 | lái | come | volver | verb ;

去 | qù | go | ir | verb ;

Note

反义词 | fǎn yì cí | antonym | antónimo | noun ;

* Text
:PROPERTIES:
:CREATED: [2022-03-28 22:51:05 -05]
:END:

** 1. 在歌厅
:PROPERTIES:
:CREATED: [2022-03-28 22:51:07 -05]
:ID: 85c60339-9720-4de2-b2b9-e90cc3bfa178
:END:

dialogue

Ａ：王方，昨天和你一起唱歌的人是谁？
pi: wáng fāng, zuótiān hé nǐ yìqǐ chànggē de rén shì shéi
en: Wang Fang, who was the person you sang with yesterday?
es: Wang Fang ¿quién era la persona con la que cantaste ayer?

Ｂ：一个朋友。
pi: yí ge péngyou
en: a friend
es: un amigo.

Ａ：什么朋友？是不是男朋友？
pi: shénme péngyou? shì bu shì nán péngyou
en: what friend? is it a boyfriend?
es: ¿qué clase de amigo? ¿era un novio?

Ｂ：不是不是，我同学介绍的，昨天第一次见。
pi: bú shì bú shì, wǒ tóngxué jièshào de, zuótiān dì yī cì jiàn
en: no, no, my classmate introduced me, I saw him for the first time yesterday
es: no, no, me lo presentó mi compañero de clase, lo conocí ayer por primera vez.


new words

歌厅 | ge1 ting1 | karaoke bar ;
唱歌 | chàng gē | to sing | cantar | verb ;
男 | nán | man, male | hombre | adjective ;

** 2. 在宿舍
:PROPERTIES:
:CREATED: [2022-03-28 22:51:14 -05]
:ID: 43918a00-5c3d-4050-bf2e-c396f15d654a
:END:

Ａ：左边这个看报纸的女孩子是你姐姐吗？
pi: zuǒbian zhège kàn bàozhǐ de nǚ háizi shì nǐ jiějie ma?
en: is the girl on the left reading the newspaper your sister?
es: ¿la chica de la izquierda leyendo el periódico es tu hermana?

Ｂ：是，右边写字的那个人是我哥哥。
pi: shì, yòubian xiě zì de nàge rén shì wǒ gēge
en: yes, the one writing on the right is my brother.
es: sí, el hombre que escribe a la derecha es mi hermano.

Ａ：你哥哥多大？
pi: nǐ gēge duō dà?
en: how old is your brother?
es: ¿qué edad tiene tu hermano?

Ｂ：25岁，他比我大三岁。
pi: 25 suì, tā bǐ wǒ dà sān suì
en: 25 years old, he isthree years older than me.
es: 25 años, es tres años mayor que yo.

new words

女 | nǚ | woman, female | noun ;

孩子 | child, kid | niño | noun ;

右边 | yòubian | right, right side | noun ;

比 | bǐ | than, (superior or inferior) to | que (superior o inferior) ... | preposition ;

** 3. 在商店
:PROPERTIES:
:CREATED: [2022-03-28 22:51:15 -05]
:ID: 10e28739-7ff4-4543-8a1d-e329eb961bf8
:END:

Ａ：今天的西瓜怎么卖？
pi: jīntiān de xīguā zěnme mài?
en: what's the price of watermelons today?
es: ¿cómo están las sandías a la venta hoy?

Ｂ：三块五一斤。
pi: sān kuài wǔ yì jīn
en: three yuan and a half per 500 grams
es: tres yuanes y medio por medio kilo.

Ａ：比昨天便宜。
pi: bǐ zuótiān piányi
en: it's cheaper than the price yesterday
es: es más barato que ayer

Ｂ：是，苹果也比昨天便宜一些。您来点儿吧。
pi: shì, píngguǒ yě bǐ zuótiān piányi yī xiē. nín lái diǎnr ba
en: yes. the apples are also cheaper. why not take some?
es: sí, las manzanas también son más baratas que ayer ¿por qué no te llevas un poco?

New words

便宜 | piányi | cheap, inexpensive | caro | adjective ;

** 4. 在学校
:PROPERTIES:
:CREATED: [2022-03-28 22:51:15 -05]
:ID: 59810866-5ae0-4690-9453-d5f44a458b82
:END:

Ａ： 前边说话的那个人就是我的汉语老师。你可能不认识她。
pi: qiánbian shuōhuà de nǎge rén jiù shì wǒ de hànyǔ lǎoshī. nǐ kěnéng bù rènshi ta
en: the woman speaking in front of us is my chinese teacher. You may not know her.
es: la persona que habla delante de mí es el profesor chino. Probablemente no la conozcas.

Ｂ：是新来的汉语老师吗？
pi: shi xīn lái de hànyǔ lǎoshī ma?
en: Is she the new chinese teachepr?
es: ¿es la nueva profesora de chino?

Ａ：是去年来的，她姓王，28岁。
pi: shì qù nián lái de, ta xìng wáng, èrshíbā suì
en: she came here last year. Her family name is Wang, 28 uears old.
es: llegó el año pasado, se apellida Wang y tiene 28 años.

Ｂ：她比我们老师小两岁。
pi: tā bǐ wǒmen lǎoshī xiǎo liǎng suì
en: she is two years younger than our teacher
es: es dos años más joven que nuestra profesora.


new word

说话 | to speak, to say, to talk | conversar | verb ;

可能 | kěnéng | maybe, perhaps, probably  ;

去年 | qùnián |  last year | año pasado, anterior año | noun ;

姓 | xìng | fmaily name, surname | apellido | noun ;

* Note
:PROPERTIES:
:CREATED: [2022-03-29 06:23:17 -05]
:END:

** A Verb (Phrase) Used as an Attributive Modifier
:PROPERTIES:
:CREATED: [2022-03-29 06:23:19 -05]
:END:

When a verb or verb phrase is used as an attributive modifier, "的" should be put between the modifier and the word modified. For example,

新买的自行车。
pi: xīn mǎi de zìxíngchē
en: newly purchased bicycle
es: bicicleta recién comprada

我妈妈做的饭。
pi: wǒ māma zuò de fàn
en: food cooked by my mother
es: comida cocinada por mi madre

和你一起唱歌的人。
pi: hé nǐ yīqǐ chàng gē de rén
en: person that sing with you
es: la persona con la que cantabas

** The "比" Sentence
:PROPERTIES:
:CREATED: [2022-03-30 08:34:45 -05]
:END:


A 比 sentence is a sentence using "比" to make a comparison. The predicate of the sentence can be an adjective. For example:

哥哥比姐姐高。
pi: gēge bǐ jiějie gāo
en: brother is taller than sister
es: hermano mayor es más alto que hermana mayor

今天比昨天热。
pi: jīntiān bǐ zuótiān rè
en: today is hotter than yesterday
es: hoy hace más calor que ayer

今天的西瓜比昨天便宜。
pi: jīntiān de xīguā bǐ zuótiān piányi
en: watermelon is cheaper today than it was yesterday.
es: las sandías son más baratas hoy que ayer


"A 没有 B" is the negative form of a "比" sentence. For example:

哥哥没有姐姐高。
pi: gēge méiyǒu jiějie gāo
en: brother is not as tall as sister
es: mi hermano no es tan alto como mi hermana

今天没有昨天热。
pi: jīntiān méiyǒu zuótiān rè
en: today is not as hot as yesterday
es: hoy no hace tanto calor como ayer

西瓜没有苹果便宜。
pi: xīguā méiyǒu píngguǒ piányi
en: watermelons are not as cheap as apples.
es: las sandías no son tan baratas como las manzanas

When describing the difference between things, a specific number is used to specify the difference, "一点儿" or "一些" indicates the difference is slight, and "多" or "很多" indicates the difference is significant. For example

西瓜比苹果贵两块钱。
pi: xīguā bǐ píngguǒ guì liǎng kuài qián
en: watermelon is two dollars more expensive than apples
es: las sandías son dos dólares más caras que las manzanas.

我的学习比他好一点儿。
pi: wǒ de xuéxií bǐ tā hǎo yīdiǎr
en: I studied a little better than he did
es: he estudiado un poco mejor que él

今天比昨天热很多
pi: jīntiān bǐ zuótiān rè hěn duō
en: today is hotter than yesterday
es: hoy hace mucho más calor que ayer

她比我们老师小两岁。
pi: tā bǐ wǒmen lǎoshī xiǎo liǎng suì
pi: she is two years younger than our teacher
es: ella es dos años más joven que nuestra profesora.
** The auxiliary verb "可能"
:PROPERTIES:
:CREATED: [2022-03-30 09:05:16 -05]
:END:

It means "maybe" indicating an estimation. It can be used before the verb or subject of a sentence. For example:

他可能早就知道这件事情了。
pi: tā kě néng zǎo jiù zhī dào zhè jiàn shìqíng le
en: he probably already knew about it

可能我明天不来上课了。
pi: kěnéng wǒ míngtiān bù lái shàng kè le
en: maybe I won't come to class tomorrow

你可能不认识她。
pi: nǐ kěnéng bú rènshi tā
en: you probably don't know her

*** Note
:PROPERTIES:
:CREATED: [2022-03-30 09:20:01 -05]
:END:

早就 | zǎo jiù | already at an earlier time | ya en tiempo pasado | noun ;

* Exercises
:PROPERTIES:
:CREATED: [2022-03-30 09:22:20 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-04-12 00:01:36 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-12 00:08:15 -05]
:END:

昨天和王方一起唱歌的人是谁？
pi: zuótiān hé wáng fāng yiqǐ chàng gē de rén shì shéi?
en: who was the person who sang with Wang Fang yesterday?
es: ¿quién era el hombre que cantó ayer con Wang Fang?

他是她昨天认识的一个朋友。
pi: tā shì tā zuótiān rènshi de yí ge péngyou
en: he's a friend that she met yesterday.
es: él es un amigo que ella había conocido ayer

*** 2
:PROPERTIES:
:CREATED: [2022-04-12 00:08:18 -05]
:END:

左边看报纸的女孩子是谁？
pi: zuǒbiān kàn bàozhǐ de nǚ háizi shì shéi?
en: who is the girl on the left reading the newspaper?
es: ¿quién es la chica de la izquierda que lee el periódico?

她是她姐姐。
pi: tā shì tā jiějie
en: she is her sister
es: es su hermna

*** 3
:PROPERTIES:
:CREATED: [2022-04-12 00:08:20 -05]
:END:

她的哥哥二十五岁了，她多大了？
pi: tā de gēge èrshíwǔ suì le, tā duō dà le?
en: her brother is twenty-five years old, how old is she?
es: su hermano tiene veinticinco años ¿cuántos tiene ella?

她二十二岁了。
pi: tā èrshíèr suì le
en: she's 22 years old
es: ella tiene 22 años

*** 4
:PROPERTIES:
:CREATED: [2022-04-12 00:08:22 -05]
:END:

昨天的西瓜可能卖多少钱？
pi: zuótiān de xīguā kěnéng mài duō shǎo qián?
en: how much might yesterday's watermelon sell for?
es: ¿cuánto podría haber costado la sandía ayer?

三块一斤。
pi: sān kuài yī jīn
en: tres yuanes half the kilogram
es: tres yuanes el medio kilo

*** 5
:PROPERTIES:
:CREATED: [2022-04-12 00:08:24 -05]
:END:

王老师是新老师吗？
pi: wáng lǎoshī xīn lǎoshī ma?
en: Is Mr. Wang a new teacher?
es: ¿es el Sr. Wang un nuevo profesor?

是的，她是去年来的。
pi: shì de, tā shì qù nián lái de
en: yes, she came last year.
es: sí, ella vino el año pasado

** 3
:PROPERTIES:
:CREATED: [2022-04-12 00:01:38 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-12 00:26:17 -05]
:END:

绿苹果比红苹果（多）。
绿苹果比红苹果多。
pi: lǜ píngguǒ bǐ hóng píngguǒ duō
en: there are more green apples than red apples
es: hay más manzanas verdes que manzanas rojas

*** 2
:PROPERTIES:
:CREATED: [2022-04-12 00:26:20 -05]
:END:

姐姐比我（大很多）。
姐姐比我大很多。
pi: jiějie bǐ wǒ dà hěn duō
en: my sister is much older than me
es: mi hermana es mucho mayor que yo

*** 3
:PROPERTIES:
:CREATED: [2022-04-12 00:26:21 -05]
:END:

昨天35°，今天没有（昨天热）。
昨天35°，今天没有昨天热。
pi: zuótiān sānshíwǔ dù, jīntiān méiyǒu zuótiān rè
en: yesterday it was 35 degrees, today it is not as hot as yesterday
es: ayer estabamos en 35 grafos, hoy no hace tanto color como ayer

*** 4
:PROPERTIES:
:CREATED: [2022-04-12 00:26:23 -05]
:END:

哥哥学习很好，我没有（他好）。
哥哥学习很好，我没有他好。
pi: gēge xuéxí hěn hǎo, wǒ méiyǒu tā hǎo
en: my brother is a good student, I'm not as good as him
es: mi hermano es un buen estudiante, no soy tan bueno como él

* Application
:PROPERTIES:
:CREATED: [2022-04-12 00:33:05 -05]
:END:

** Pair Work
:PROPERTIES:
:CREATED: [2022-04-12 00:33:13 -05]
:END:

Example

西瓜比苹果大。
pi: xīguā bǐ píngguǒ dà
en: watermelons are bigger than apples
es: las sandías son más grandes que las manzanas

苹果没有西瓜大。
pi: píngguǒ méiyǒu xīguā dà
en: watermelons are not as big as apples
es: las manzanas no son tan grandes como las sandías

Example

我们学校比公园大很多。
pi: wǒmen xuéxiào bǐ gōngyuán dà hěn duō
en: our school is much bigger than the park
es: nuestar escuela es mucho más grande que el parque

我们学校没有公园大。
pi: wǒmen xuéxiào méiyǒu gōngyuán dà
en: our school is not as big as the park
es: nuestra escuela no es tan grande como el parque

Example

飞机比公共汽车快很多。
pi: fēijī bǐ gōnggòngqìchē kuài hěn duō
en: airplanes are much faster than buses
es: los aviones son mucho más rápidos que los autobuses

飞机没有公共汽车快。
pi: fēijī méiyǒu gōnggòngqìchē kuài
en: airplanes are not as fast as buses
es: los aviones no son ran rápidos como los buses

Example

飞机票比公共汽车票贵很多。
pi: fēijī piào bǐ gōnggòngqìchē piào guì hěn duō
en: airplane tickets are much more expensive than bus tickets
es: los boletos de avión son mucho más caros que los boletos de bus

飞机票没有公共汽车票贵很多。
pi: fēijī piào méi yǒu gōnggòngqìchē piào guì hěn duō
en: airplane tickets are not as expensive as bus tickets
es: los boletos de avión no son tan caros como los boletos de bus

Example

我的手机比飞机便宜很多。
pi: wǒ de shǒujī bǐ fēijī piányi hěn duō
en: my phone is much cheaper than the plane
es: mi celular es mucho más barato que el avión

我的手机没有飞机便宜。
pi: wǒ de shǒujī méi yǒu fēijī piányi
en: my phone is not as cheap as the plane
es: mi celular no es tan barato como el avión

** Group Work
:PROPERTIES:
:CREATED: [2022-04-12 00:47:18 -05]
:END:

Group A

我的眼睛比安妮组学生大。
pi: wǒ de yǎnjing bǐ ānni zǔ xuésheng dà
en: my eyes are bigger than those of the Annie group of students
es: mis ojos son más grandes que los del grupo de estudiantes de Annie

王方的车比我的车大很多。
pi: wáng fāng de chē bǐ wǒ de chē dà hěn duō
en: Wang Fang's car is much bigger than my car
es: el coche de Wang Fang es mucho más grande que el mío

大卫的书包比方的大一些。
pi: dàwèi de shūbāo bǐ fāng de dà yi xiē
en: David's bag is a little bigger than Fang.
es: la mochila de David es un poco más grande que la de Fang

Group B

我的手机比大卫的贵三百块钱。
pi: wǒ de shǒujī bǐ dàwèi de guì sān bǎi kuài qián
en: my phone is three hundred dollars more expensive than David's
es: mi teléfono cuesta trescientos dólares más que el de David

小刘的自行车比我的贵一千钱。
pi: xiǎo liú de zìxíngchē bǐ wǒ de guì yī qiān qián
en: Xiao Liu's bike is a thousand yuans more expensive than mine.
es: la bicicleta de Xiao Liu cuesta mil dólares más que la mía

