* 听力

** 1

*** 1

**** transcript

对于劳资纠纷，最好的解决方案是在劳资之间建立和谐的关系，最大程度上避免或减少劳资纠纷的发生，或者至少把劳资之间的矛盾化解在萌芽状态，使其不致发展成为“纠纷”，这才是企业管理的上策。

***** translation

For labor-management disputes, the best solution is to establish a harmonious relationship between labor and management to avoid or reduce the occurrence of labor-management disputes to the greatest extent possible, or at least to nip the conflicts between labor and management in the bud so that they do not develop into "disputes", which is the best policy for enterprise management.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

普通牙膏中含有冰片、丁香油、薄荷脑等，具有防治口腔疾病的功效。而有些药物牙膏有较强的刺激性，对口腔粘膜有损害；有的药物牙膏含有活性较强的染色素， 用久了会污染牙面，因此使用药物牙膏要慎重。

***** translation

Common toothpaste contains ice chips, clove oil, menthol, etc., which has the effect of preventing oral diseases. While some drug toothpaste has strong irritation, damage to oral mucosa; some drug toothpaste contains strong stain, with a long time will contaminate the tooth surface, so the use of drug toothpaste should be careful.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

导演40多岁，黑黑的脸，像所有的导演一样，下巴留着胡子，脸上很少有笑容。他匆匆向我交代了几句就说：“开始吧！”顿时，房屋里的灯光全都打开，我被照得有点儿晕，接着看到这么多人看着自己，我顿时紧张了起来。

***** translation

The director was in his 40s, with a dark face and, like all directors, a beard on his chin and very little smile on his face. He hurriedly explained a few words to me and said, "Let's begin!" At once, all the lights in the house turned on, I was illuminated a little dizzy, and then saw the allegiance of so many people watching themselves, I was suddenly nervous.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

先前发生的事件与后来发生的事件之间往往有着千丝万缕的联系，甚至是后来发生事件的根源或条件。但是由于历史记录不全、事件之间的关系错综复杂，往往使得因果分析变得困难而复杂。

***** translation

Previous events are often inextricably linked to later events, and are even the root cause or condition of later events. But the incomplete historical record and the intricate relationships between events often make causal analysis difficult and complex.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

她两眼茫然地盯着前方，为自己如此草率的远行而担忧，不知道刘大明会不会来接她。忽然，她的眼前一亮，她被一大捧鲜艳的红玫瑰吸引住了，她以万分艳羡的目光盯着那些红玫瑰，她没想到，红玫瑰的后面竟然是刘大明的一张微笑的脸！

***** translation

She stared blankly ahead with two eyes, worried about her own so rashly away, wondering if Liu Daming would come to pick her up. Suddenly, her eyes lit up, she was attracted by a large handful of bright red roses, she stared at those red roses with a million envious eyes, she chances are, behind the red roses was a smiling face of Liu Daming!

**** alternatives

***** a



***** b



***** c



***** d



**** answer



