* 听力

** 1

*** 1

**** transcript

对于劳资纠纷，最好的解决方案是在劳资之间建立和谐的关系，最大程度上避免或减少劳资纠纷的发生，或者至少把劳资之间的矛盾化解在萌芽状态，使其不致发展成为“纠纷”，这才是企业管理的上策。

***** translation

For labor-management disputes, the best solution is to establish a harmonious relationship between labor and management to avoid or reduce the occurrence of labor-management disputes to the greatest extent possible, or at least to nip the conflicts between labor and management in the bud so that they do not develop into "disputes", which is the best policy for enterprise management.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

普通牙膏中含有冰片、丁香油、薄荷脑等，具有防治口腔疾病的功效。而有些药物牙膏有较强的刺激性，对口腔粘膜有损害；有的药物牙膏含有活性较强的染色素， 用久了会污染牙面，因此使用药物牙膏要慎重。

***** translation

Common toothpaste contains ice chips, clove oil, menthol, etc., which has the effect of preventing oral diseases. While some drug toothpaste has strong irritation, damage to oral mucosa; some drug toothpaste contains strong stain, with a long time will contaminate the tooth surface, so the use of drug toothpaste should be careful.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

导演40多岁，黑黑的脸，像所有的导演一样，下巴留着胡子，脸上很少有笑容。他匆匆向我交代了几句就说：“开始吧！”顿时，房屋里的灯光全都打开，我被照得有点儿晕，接着看到这么多人看着自己，我顿时紧张了起来。

***** translation

The director was in his 40s, with a dark face and, like all directors, a beard on his chin and very little smile on his face. He hurriedly explained a few words to me and said, "Let's begin!" At once, all the lights in the house turned on, I was illuminated a little dizzy, and then saw the allegiance of so many people watching themselves, I was suddenly nervous.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

先前发生的事件与后来发生的事件之间往往有着千丝万缕的联系，甚至是后来发生事件的根源或条件。但是由于历史记录不全、事件之间的关系错综复杂，往往使得因果分析变得困难而复杂。

***** translation

Previous events are often inextricably linked to later events, and are even the root cause or condition of later events. But the incomplete historical record and the intricate relationships between events often make causal analysis difficult and complex.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

她两眼茫然地盯着前方，为自己如此草率的远行而担忧，不知道刘大明会不会来接她。忽然，她的眼前一亮，她被一大捧鲜艳的红玫瑰吸引住了，她以万分艳羡的目光盯着那些红玫瑰，她没想到，红玫瑰的后面竟然是刘大明的一张微笑的脸！

***** translation

She stared blankly ahead with two eyes, worried about her own so rashly away, wondering if Liu Daming would come to pick her up. Suddenly, her eyes lit up, she was attracted by a large handful of bright red roses, she stared at those red roses with a million envious eyes, she chances are, behind the red roses was a smiling face of Liu Daming!

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

男：“社交离线日，出来分享才开心”主题活动至今已经举办多次了，作为心理专家，您对这个活动有什么看法？
女：飞速发展的社交网络，简化了人们的沟通，却解决不了人与人之间内心的情感需要。今年的活动进一步号召人们行动起来，希望更多的人能够暂别网络，关注面对面交流，分享真实沟通带来的幸福体验，绝对是一件好事。
男：其实线上交流也是交流，难道二者有什么差别吗？
女：社交网络打破了时间和空间的壁垒，但也为社会带来了不小的影响。这样的社交模式，催生了“新型社交人类”。例如，亲朋聚会，“新型社交人类”手机不离手，一道美食上桌，他们先要拍照并通过社交媒体分享，然后期盼着别人点赞和评论，反倒冷落和忽视了身边的人。这一情景折射出的是“新型社交人类”过于在乎创造未来的幸福感，而缺乏聚焦当下、感受当下幸福感的能力。
男：嗯，过分依赖线上交流，可能导致这类人群无法应对现实生活中的人际问题。
女：不仅如此，大家公认的是，面对面交流是复杂、高层次的，更能考验一个人的人际交往能力。面对面的交流要求人身心投入地对待彼此，线上交流的隐患就是不需要这种对人内心情感的体察与维护。
男：嗯，有道理。
女：适度离线，不要过度依赖网络，在真实的世界里进行互动分享、情感经营，是克制网络迷恋的切实可行的理性选择，也是长远幸福的重要源泉。
男：您说的是“情感经营”？难道情感还要“经营”？
女：是啊，人与人之间的情感是需要经营的，这种说法并不荒谬。这在面对面交往中体现尤为真切。比如，与人交往要真诚，要用心，要懂得彼此珍重。但人与人之间总会有磕磕碰碰，这就需要磨合。相处久了，彼此熟悉了，也就有了相处之道。在这个过程中，人要不断自省，要提高自己的修养和涵养，如果一个人能使对方因为拥有你而感到自豪，就是你人生最大的成功。

*** 音频

e193318e-ede7-4d31-99fc-181373dfc2cf.mp3

*** 题目

**** 6

***** 问题

女的对这项主题活动的看法，下列哪项正确？

***** 音频

8a3c1bc2-36a0-46e5-9582-def528c8fc85.mp3

***** 选择

****** A

认为真实沟通绝对是一件好事

****** B

鼓励人们通过活动彻底告别网络

****** C

网络走进生活是社会发展的必然

****** D

网络应重视人的沟通与情感交流

***** 答案

A

**** 7

***** 问题

线上交流和面对面交流的差别是什么？

***** 音频

dbde101a-5345-4b56-b5d1-8bdda4221fb0.mp3

***** 选择

****** A

 二者对时空要求不一样

****** B

 二者适应的人群不一样

****** C

 线上交流更能满足虚荣心

****** D

 面对面交流让人更有幸福感

***** 答案

A

**** 8

***** 问题

过分依赖线上交流，可能导致什么问题？

***** 音频

1c7d5282-3ca6-4920-ba67-4a4dd093c386.mp3

***** 选择

****** A

 身在福中不知福

****** B

 做事不能集中精力

****** C

 对生活期望值过高

****** D

 高层次交往能力退化

***** 答案

D

**** 9

***** 问题

关于“经营情感”，下列哪项正确？

***** 音频

bd677149-5912-4524-a342-a608c0b15824.mp3

***** 选择

****** A

是一种陈旧的理论

****** B

人为色彩过于浓重

****** C

“经营“二字内含丰富

****** D

通俗易懒，但可行性差

***** 答案

C

**** 10

***** 问题

这次主题活动希望人们做什么？

***** 音频

5b1bf30c-0c5d-4ec4-93fe-d792df1ec5fe.mp3

***** 选择

****** A

增强对未来幸福的感知力

****** B

暂别网络，关注面对面交流

****** C

完善自己，让朋友为自己而自豪

****** D

有自省精神，提高自己的修养和源养

***** 答案

B

