* 听力

** 第二部分
:PROPERTIES:
:ID: 555ea437-e390-40ba-9120-7be0b4de4282
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：“社交离线日，出来分享才开心”主题活动至今已经举办多次了，作为心理专家，您对这个活动有什么看法？
女：飞速发展的社交网络，简化了人们的沟通，却解决不了人与人之间内心的情感需要。今年的活动进一步号召人们行动起来，希望更多的人能够暂别网络，关注面对面交流，分享真实沟通带来的幸福体验，绝对是一件好事。
男：其实线上交流也是交流，难道二者有什么差别吗？
女：社交网络打破了时间和空间的壁垒，但也为社会带来了不小的影响。这样的社交模式，催生了“新型社交人类”。例如，亲朋聚会，“新型社交人类”手机不离手，一道美食上桌，他们先要拍照并通过社交媒体分享，然后期盼着别人点赞和评论，反倒冷落和忽视了身边的人。这一情景折射出的是“新型社交人类”过于在乎创造未来的幸福感，而缺乏聚焦当下、感受当下幸福感的能力。
男：嗯，过分依赖线上交流，可能导致这类人群无法应对现实生活中的人际问题。
女：不仅如此，大家公认的是，面对面交流是复杂、高层次的，更能考验一个人的人际交往能力。面对面的交流要求人身心投入地对待彼此，线上交流的隐患就是不需要这种对人内心情感的体察与维护。
男：嗯，有道理。
女：适度离线，不要过度依赖网络，在真实的世界里进行互动分享、情感经营，是克制网络迷恋的切实可行的理性选择，也是长远幸福的重要源泉。
男：您说的是“情感经营”？难道情感还要“经营”？
女：是啊，人与人之间的情感是需要经营的，这种说法并不荒谬。这在面对面交往中体现尤为真切。比如，与人交往要真诚，要用心，要懂得彼此珍重。但人与人之间总会有磕磕碰碰，这就需要磨合。相处久了，彼此熟悉了，也就有了相处之道。在这个过程中，人要不断自省，要提高自己的修养和涵养，如果一个人能使对方因为拥有你而感到自豪，就是你人生最大的成功。

**** 音频

e193318e-ede7-4d31-99fc-181373dfc2cf.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 06c628ca-8748-43fe-96bc-8b91b9cb1b04
:END:

***** 问题

女的对这项主题活动的看法，下列哪项正确？

****** 音频

8a3c1bc2-36a0-46e5-9582-def528c8fc85.mp3

***** 选择

****** A

认为真实沟通绝对是一件好事

****** B

鼓励人们通过活动彻底告别网络

****** C

网络走进生活是社会发展的必然

****** D

网络应重视人的沟通与情感交流

***** 答案

A

**** 7
:PROPERTIES:
:ID: cc945b94-ace2-491b-98c1-2dfbd0400657
:END:

***** 问题

线上交流和面对面交流的差别是什么？

****** 音频

dbde101a-5345-4b56-b5d1-8bdda4221fb0.mp3

***** 选择

****** A

 二者对时空要求不一样

****** B

 二者适应的人群不一样

****** C

 线上交流更能满足虚荣心

****** D

 面对面交流让人更有幸福感

***** 答案

A

**** 8
:PROPERTIES:
:ID: beec3e00-ac80-4564-baba-e9d8de5c548b
:END:

***** 问题

过分依赖线上交流，可能导致什么问题？

****** 音频

1c7d5282-3ca6-4920-ba67-4a4dd093c386.mp3

***** 选择

****** A

 身在福中不知福

****** B

 做事不能集中精力

****** C

 对生活期望值过高

****** D

 高层次交往能力退化

***** 答案

D

**** 9
:PROPERTIES:
:ID: 502db061-4da1-4653-9e67-a2a60dcbf8f1
:END:

***** 问题

关于“经营情感”，下列哪项正确？

****** 音频

bd677149-5912-4524-a342-a608c0b15824.mp3

***** 选择

****** A

是一种陈旧的理论

****** B

人为色彩过于浓重

****** C

“经营“二字内含丰富

****** D

通俗易懒，但可行性差

***** 答案

C

**** 10
:PROPERTIES:
:ID: 2f473168-4f8e-4c02-8824-87ad7d1ed6e6
:END:

***** 问题

这次主题活动希望人们做什么？

****** 音频

5b1bf30c-0c5d-4ec4-93fe-d792df1ec5fe.mp3

***** 选择

****** A

增强对未来幸福的感知力

****** B

暂别网络，关注面对面交流

****** C

完善自己，让朋友为自己而自豪

****** D

有自省精神，提高自己的修养和源养

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

企业应主动给工人涨工资

***** B

企业与员工之间总会有矛盾

***** C

高明的企业会避免与员工冲突

***** D

员工应该为企业发展献计献策

**** 段话

对于劳资纠纷，最好的解决方案是在劳资之间建立和谐的关系，最大程度上避免或减少劳资纠纷的发生，或者至少把劳资之间的矛盾化解在萌芽状态，使其不致发展成为“纠纷”，这才是企业管理的上策。

***** 音频

9cc286af-a826-4198-b37d-a04eb9049959.mp3

**** 答案

C

*** 2

**** 选择

***** A

应禅止生产药物牙膏

***** B

不要随意使用药物牙膏

***** C

药物牙膏对人有害而无益

***** D

药物牙膏的生产缺乏科学性

**** 段话

普通牙膏中含有冰片、丁香油、薄荷脑等，具有防治口腔疾病的功效。而有些药物牙膏有较强的刺激性，对口腔粘膜有损害；有的药物牙膏含有活性较强的染色素，用久了会污染牙面，因此使用药物牙膏要慎重。

***** 音频

317aca6e-c9af-48b1-9dc8-c38f779ad624.mp3

**** 答案

B

*** 3

**** 选择

***** A

导演对我非常严厉

***** B

围观的观众不太多

***** C

我担心导演拍不好

***** D

导演是个严肃的人

**** 段话

导演40多岁，黑黑的脸，像所有的导演一样，下巴留着胡子，脸上很少有笑容。他匆匆向我交代了几句就说：“开始吧！”顿时，房屋里的灯光全都打开，我被照得有点儿晕，接着看到这么多人看着自己，我顿时紧张了起来。

***** 音频

2af44d3c-04f0-4121-bb99-a774f772379a.mp3

**** 答案

D

*** 4

**** 选择

***** A

任何事件的发生都有其必然性

***** B

前后事件之间常常是有联系的

***** C

要重视对历史事件的记录工作

***** D

因果分析再难也必须努力去做

**** 段话

先前发生的事件与后来发生的事件之间往往有着千丝万缕的联系，甚至是后来发生事件的根源或条件。但是由于历史记录不全、事件之间的关系错综复杂，往往使得因果分析变得困难而复杂。

***** 音频

25469e35-17d3-4907-b6c2-876ce43ace83.mp3

**** 答案

B

*** 5

**** 选择

***** A

她心中忐忑不安

***** B

刘大明是卖花的

***** C

刘大明对她非常失望

***** D

她和刘大明都喜欢花

**** 段话

她两眼茫然地盯着前方，为自己如此草率的远行而担忧，不知道刘大明会不会来接她。忽然，她的眼前一亮，她被一大捧鲜艳的红玫瑰吸引住了，她以万分艳羡的目光盯着那些红玫瑰，她没想到，红玫瑰的后面竟然是刘大明的一张微笑的脸！

***** 音频

9544d4cc-6498-48d2-8edf-3a2a64bc42f4.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

时至今日，《大数据时代：生活、工作与思维的大变革》仍是全世界最好的一本大数据专著。其作者之一是维克托•迈尔——舍恩伯格，大数据时代的预言家，《科学》《自然》等著名学术期刊最推崇的互联网研究者之一，有在哈佛大学、牛津大学、耶鲁大学和新加坡国立大学等多个互联网研究重镇任教的经历。

《大数据时代：生活、工作与思维的大变革》一书的两位译者中，有一位是我国最年轻有为的大数据专家，年仅 27 岁的周涛教授，数年来他一直带领我国学术界在大数据研究上向国际一流水平看齐。

**** 题目

***** 11

****** 选择

******* A

生活用书

******* B

学术著作

******* C

刚出版的书

******* D

倡导改革的书

****** 问题

《大数据时代:生活、工作与思维的大变革》是一本什么样的书？

****** 答案

B

***** 12

****** 选择

******* A

原本是学外语的

******* B

不但年轻而且学术水平高

******* C

是我国研究大数据的第一人

******* D

是《大数据时代:生活、工作与思维的大变革》一书的作者

****** 问题

关于周涛，下列哪项正确？

****** 答案

B

***** 13

****** 选择

******* A

维克托.迈尔一舍恩伯格常为《自然》写稿

******* B

《大数据时代:生活、工作与思维的大变革》是一本好书

******* C

杂志对《大数据时代:生活、工作与思维的大变革》评价很高

******* D

哈佛大学、牛津大学、耶鲁大学和新加坡国立大学都是好学校

****** 问题

这段话主要谈什么？

****** 答案

B

*** 14-17

**** 课文

判断一个东西是不是脏，不仅要看其表面上的细菌数量，还要看上面的致病菌数量，因为致病菌的毒性要远远高于普通细菌。

电脑键盘和没有清洗的鞋子，哪个更容易滋生细菌呢？为了找到答案，有人对一双穿了半年左右的运动鞋和一个用了半年多的电脑键盘上面的细菌数量进行检测对比，结果发现，两件样本都有大量的细菌存在，而键盘上的菌落数量是运动鞋的 65 倍，需要注意的是，键盘上还发现了真菌。为验证键盘和运动鞋中是否存在致病性极高的金黄色葡萄球菌，实验员用试纸进行了测试，幸运的是，测试结果均为阴性，运动鞋和键盘上并没有发现这种细菌。

实验结果显示，运动鞋前脚掌处的细菌数量远不如键盘上的细菌数量多。电脑键盘因为数字键不常使用，其菌落数远远低于字母键盘。

专家建议，电脑键盘每两周用酒精擦拭一次，可有效消灭细菌；清洗运动鞋时一定要注意鞋子内部的清洁，清洗之后，可在阳光下进行暴晒消毒。

**** 题目

***** 14

****** 选择

******* A

有细菌的东西

******* B

沾上泥土的东西

******* C

布满灰小的东西

******* D

致病菌多的东西

****** 问题

根据这段话，下列东西哪个最脏？

****** 答案

D

***** 15

****** 选择

******* A

运动鞋更容易滋生真菌

******* B

电脑键盘更容易滋生细菌

******* C

键盘上发现了金黄色葡萄球菌

******* D

键盘上的菌落数量比运动鞋高65俘

****** 问题

关于运动鞋和电脑键盘细菌检测的对比结果，下列哪项正确？

****** 答案

B

***** 16

****** 选择

******* A

运动鞋表面

******* B

运动鞋前脚掌处

******* C

电脑键盘的孙母键盘

******* D

电脑键盘的数字键盘

****** 问题

实验结果显示，最脏的是什么部位？

****** 答案

C

***** 17

****** 选择

******* A

键盘最好用酒精擦洗

******* B

电脑内部更要常清理

******* C

鞋在阳光下暴晒即可

******* D

电脑每次用后应消毒

****** 问题

关于专家建议，下列哪项正确？

****** 答案

A

