* 热身

** 1
:PROPERTIES:
:ID: 5d632220-8c7c-4837-998e-cdf267beb99e
:END:

*** 1

**** 词语

热闹

**** 答案

f

*** 2

**** 词语

森林

**** 答案

c

*** 3

**** 词语

云

**** 答案

b

*** 4

**** 词语

活泼

**** 答案

a

*** 5

**** 词语

老虎

**** 答案

d

*** 6

**** 词语

海洋

**** 答案

e

* 注释

** 3

*** 比一比

**** 做一做

***** 词语

****** 1

趟

****** 2
:PROPERTIES:
:ID: b602e06c-0615-465d-a3f7-483a69e474f1
:END:

次

***** 题

****** 1
:PROPERTIES:
:ID: 72305ad0-f631-4318-9660-1411e35b999e
:END:

******* 课文

去年放暑假的时候，我去了一🟦北京动物园。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: 5fd1528e-39ed-4450-99fd-fa3decbf5b1f
:END:

******* 课文

我们去🟦超市叱，明天出去玩儿得买点儿饼干和面包。

******* 答案

******** 1

1

******** 2

0

****** 3
:PROPERTIES:
:ID: 63dc0ea3-4d41-47e6-a359-e42097b7143a
:END:

******* 课文

中午我给你打了好几🟦电话，你怎么都不接呢？

******* 答案

******** 1

0

******** 2

1

****** 4
:PROPERTIES:
:ID: 4b7a6edc-c0a1-4f5e-b392-8e0d69054642
:END:

******* 课文

他没赶上最后一🟦公共汽车，只好坐出租车回家了。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: 3a973efd-2828-47ac-8f40-a862b47d9fc7
:END:

******* 课文

古红柿鸡蛋汤的做法很简单，我保证你一🟦就能学会。

******* 答案

******** 1

0

******** 2

1

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: a5a0fa16-9d7a-4790-970d-68b5300891c0
:END:

**** 选择

***** 1

广播

***** 2

酋重

***** 3

剩

***** 4

照

***** 5

底

**** 题

***** 1

****** 段话填空

这本小说就🟦十几页了，我想看看最后到底怎么样了。

****** 答案

剩

***** 2

****** 段话填空

刚才听🟦说明天可能会下大雨，足球比赛恐怕要推迟了。

****** 答案

广播

***** 3

****** 段话填空

您看这个挲发怎么样？我们年🟦有活动，正在打折，比平时便宜了一千块。

****** 答案

底

***** 4

****** 段话填空

不管男人还是女人，只要能在自己的工作中取得好的成绩，都应该赢得🟦。

****** 答案

尊重

***** 5

****** 段话填空

很多自行车后面都有一个灯，虽然小，但用处却很大。每当后面汽车的灯光🟦到它时，它就会反光，这样就能提醒司机前方有人。

****** 答案

照

*** 6-10
:PROPERTIES:
:ID: 51856e6c-0961-42c3-a4f5-212de2e29398
:END:

**** 选择

***** 1

难受

***** 2

暖和

***** 3

活泼

***** 4

凉快

***** 5

热闹

**** 题

***** 6

****** 对话填空

Ａ：下了雨，🟦多了，前几天实在是太热了。
Ｂ：是啊，前两天晚上热得都睡不着，今天终于能睡个好觉了。

****** 答案

谅快

***** 7

****** 对话填空

Ａ：你经常参加学校举办的舞会吗？
Ｂ：不，我从来没参加过，我不太喜欢🟦。

****** 答案

热闹

***** 8

****** 对话填空

Ａ：工作半天了，起来活动活动。
Ｂ：好，坐久了确实有些🟦。

****** 答案

难受

***** 9

****** 对话填空

Ａ：小李，我给你个绍个女朋友吧，说说你有什么条件。
Ｂ：我，我喜欢🟦可爱的女孩子。

****** 答案

活泼

***** 10

****** 对话填空

Ａ：今天很🟦，外面一点儿也不冷，你不用穿这么多衣服。
Ｂ：好的，那我脱掉一件。

****** 答案

暖和

* 扩展

** 做一做
:PROPERTIES:
:ID: 42933f11-edb9-45aa-956b-bb4f913d5c92
:END:

*** 选择

**** 1

既然

**** 2

竟然

**** 3

仍然

**** 4

突然

*** 题

**** 1

***** 内容填空

真是没想到，四年的大学生活🟦这么快就结束了！

***** 答案

****** 1

竟然

**** 2

***** 内容填空

Ａ：刚才太危险了，那辆车怎么回事？
Ｂ：不知道，🟦加速，估计是新手，刚学会开车。

***** 答案

****** 1

突然

**** 3

***** 内容填空

只要你不放弃努力，就🟦有希望。你总会找到一条合适的路，通往成功的目的地。

***** 答案

****** 1

仍然

**** 4

***** 内容填空

世界上有一种药是肯定买不到的，那就是“后悔药”。有些事情过去了就是过去了，再也不能回头。🟦不能重新来过，那么就把那些过去的事情放在心里，当成一种回忆然后勇孜地抬起头向前看，走好以后的路。

***** 答案

****** 1

既然


* 课文
** 1
*** 转录
小夏：最近天气趋来越凉快了，风一制，草地上就会有一层厚厚的黄叶，看来秋天已经到了。
安娜：这几天香山特别热闹，随着气温的降低，那里许多植物的叶子都由绿变黄或者变红，吸引了很多游客参观，咱们今天也去看看吧。
小夏：你看天上的云，今天肯定有大雨。再说，香山上看红叶的人太多了。咱们改天去长城吧，广播里说那里也有不少专门看红叶的好地方。
安娜：真可惜，我还想多照点儿香山的照片呢。去长城倒是一个好主意，那我们明天去吧。
小夏：明天恐怕也不行，明天是我爸的生日。
安娜：没关系，那我们再约时间。
** 2
*** 转录
小林：你的这只大黑狗毛真漂亮，而且这么聪明，每次见了都想抱一抱它。
小李：狗是很聪明的动物，只要稍微花点儿时间教教它，它就能学会很多东西。
小林：听你这么一说，我现在也想养一只狗了。每欠你让它干什么，它就像能听懂你的话一样去做。你教它是不是用了什么特别的方法？
小李：要让它完成一些任务，只教一次是不够的，应该耐心地一遍一遍地教给它，使它熟悉，然后它就会严格按照你的要求做了。
小林：看来没有想的那么容易。
小李：狗是我们的好朋友，它能听懂人的话，明白人的心情。在你心里难受的时候，它会一直陪着你。
** 3
*** 转录
马克：上个月我去了趟北京动物园，那里约有500种动物，听导游说北京动物园是亚洲最大的动物园之一。
小夏：去年放暑假的时候，我也去过一次，我在那儿看了马、熊猫、老虎等动物。我特别喜欢熊猫，可惜它们当时大多在睡觉。
马克：我去的那天正赶上六一儿童节，许多父母带着孩子去动物园。入口处排队的人很多，动物园里热闹极了。熊猫们也变得特别活泼，我还给它们照了不少照片呢。
小夏：大熊猫身子胖胖的，样子可爱极了。
马克：不过，它们数量不多，现在全世界一共才有一千多只吧。
小夏：以前只有中国有大熊猫，为了表示友好，从1957年开始，中国把大熊猫作为礼物送给其他一些国家。现在，很多国家的人们在本国都能看到大熊猫了。
** 4
*** 转录
不仅社会上的人与人之间有竞争，森林里的各种植物之间也有竞争，这一点儿也不奇怪。植物会为了阳光、空气和水而竞争。一些高大的植物往往能获得更多的阳光、空气和水，而剩下的一些比较低矮的植物就只能长在这些高大植物的下面。由于气候条件不同，世界各地植物叶子的样子也很不相同。在暖和、水分比较多的地方，叶子往往长得又大又厚；在阳光特别厉害、水分少的地方，叶子就会长得又细又长。
** 5
*** 转录
地球上大约71%的地方是蓝色的海洋，在美丽的海底世界里，生活着各种各样的植物和动物。我们小时候都听过美人鱼的故事，其实真正的海底世界比故事里写的更美。科学研究发现，海洋底部看上去非常安静，然而却不是一点儿声音也没有，海底的动物们一直在“说话”，只不过人的耳朵是听不到的。另外，就算在几公里深的海底也仍然能看到东西，许多鱼会发出各种颜色的亮光，像一个个排列起来的灯，美极了，就像在梦里一样。
