* 听力

** 1

*** 1

**** transcript

1768年7月下旬，酷热笼罩着大地。紫禁城里，人们开始为皇家一年一度前往承德避暑山庄的转移做准备。在那里，有一片按照江南风格与神韵巧妙设计而成的园林，坐落着富有南方情调的豪华宫殿以及令人赏心悦目的亭台楼阁。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

雏燕放飞的时候终于到了。为了这一天的到来，女儿的老师、朋友，以及我先生、我和女儿本人，都付出了许多的心血。这些心血已经变成女儿起飞的动力，使她能够展开翅膀，飞翔在全球资本市场的上空。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

喜欢旅游是因为她想放眼世界，在旅游中体验“行千里路胜读万卷书”的乐趣。喜欢烹饪，是因为她想用美味佳肴奖励辛勤工作之后的自己，同时也为亲朋好友献上在餐厅里吃不到的“美女私房菜”。


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

李小龙是一个神话。他以原本并不优秀的天赋自创截拳道，并成为影响世界的一代功夫巨星。他可在拍出多部影响世界的功夫电影的同时著书立说。他惊人的毅力和坚韧的品格，都已成为后人无法复制的神话。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

很显然，一些学科所以能够产生、存在和发展是因为它对于社会、人类有着自己的功能和价值。这种功能、价值一旦消失，这门学科便会失掉存在的意义，便会或迟或早地枯萎，直至被取消。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: f38491a6-81e0-4e88-9a2e-9d17baba7303
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：大家好，现在坐在我身边的是旅行家郑先生。郑先生，您好！ww
男：您好！我不是什么旅行家，只是喜欢旅行。
女：或者说是喜欢旅行在路上的感觉？
男：对，这个贴切。旅行在路上不仅能让你陶醉于风景，更重要的是体验人与人的沟通。忘却自己的身份去和来自不同地方的人面对面交流，这是我最喜欢的。
女：听说您尤其喜欢搭车旅行？
男：是，因为异样的旅行方式会带你感受不一样的风景。
女：搭车旅行是最近才兴起的吗？
男：不，国外早就有。中国是前几年，美籍华裔小伙谷岳和纪录片导演刘畅两个人历经三个月，从北京出发到柏林，一路上只依靠陌生人的帮助，共搭车88 次，走了 16000 多公里，穿越 13 个国家。这件事在中国传开之后，很多人开始搭车旅行。
女：碰上的都是未知的，我们不禁会对未知产生憧憬和向往！
男：也会充满惶恐，因为不知道自己该如何踏出勇敢的第一步。
女：能跟我们分享一下您记忆最深刻的搭车旅行吗？
男：那就是去西藏了。
女：冒险加神秘感？
男：不是，是西藏的壮美让我震撼。我那次运气特别好，搭的是一位藏族同胞的车，他是做生意的，我搭他的车几乎跑遍了我计划中所有想去的地方。
女：成专车了！
男：嗯，他说一个人开车也闷得慌，有我一路聊天儿，他还能跟我练练普通话。我们第一天是从拉萨去林芝，一路上抬头是蔚蓝的天空、漂浮的白云，远望是牧民、草场和牛、羊等牲畜，天上偶尔有老鹰盘旋。翻过米拉山，汽车开始在山谷间行驶，山上有泉水、瀑布，在峡谷间汇集成小溪，随着水量的增加，小溪汇聚成了江河，最后成了汪洋一片。那天的行程是我最有感悟的一天。
女：感悟什么呢？
男：“不积小流，无以成江海。”
女：是啊，就像滴水穿石一样，积累的作用不能小看。

*** 音频

69df9ca7-9dc7-4ef3-a039-99cb2e147387.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 6caae373-6837-4ee6-b7eb-5053be7d2045
:END:

***** 问题

男的为什么喜欢“旅行在路上”的感觉？

***** 音频

6fdf33db-1c7e-4e07-aab2-c2f5694ca2d5.mp3

***** 选择

****** A

因为能够认识更多有身份的人

****** B

因为别人能告诉你晨里风景好

****** C

因为能与不同的人面对面交流

****** D

因为能够了解各地的风土人情

***** 答案

C

**** 7
:PROPERTIES:
:ID: d3ae1ebf-2f39-45a4-830b-3908d887721d
:END:

***** 问题

关于搭车旅行，下列哪项正确？

***** 音频

23f86c5e-edf5-41ec-b25b-5ac9ccf4ff12.mp3

***** 选择

****** A

美国人在中国经常搭车旅行

****** B

很早以前中国人就搭车旅行

****** C

三个月以前有人尝试搭车旅行

****** D

谷岳、刘畅的搭车旅行影响了中国人

***** 答案

D

**** 8
:PROPERTIES:
:ID: a73c43b9-3a70-45f1-a68f-56804b166873
:END:

***** 问题

搭车旅行的魅力是什么？

***** 音频

f704608f-cc0b-4136-bed5-fcd3dfbf1127.mp3

***** 选择

****** A

对未知的神往

****** B

对已知的期待

****** C

对艰辛的恐惧

****** D

对能力的提升

***** 答案

A

**** 9
:PROPERTIES:
:ID: 75c9bf1f-dd49-44c7-b904-977d478ca68d
:END:

***** 问题

关于男的在西藏搭车的经历，下列哪项正确？

***** 音频

79d42dca-394d-42eb-b394-b09876005496.mp3

***** 选择

****** A

车主是个汉族人

****** B

车主也喜欢旅游

****** C

车主喜欢有人聊天儿

****** D

车主对西藏不太熟悉

***** 答案

C

**** 10
:PROPERTIES:
:ID: f92271b3-b28c-4f99-9915-61d00acff9ba
:END:

***** 问题

男的在西藏有什么感悟？

***** 音频

09e8a9df-7d3c-4301-8962-7512408ecd80.mp3

***** 选择

****** A

西藏的生态环境很好

****** B

西藏的江河湖海很美

****** C

一路的景色自然纯朴

****** D

积累的作用不能小看

***** 答案

D

