* 听力

** 1

*** 1

**** transcript

十七八年前，他最后一次会见他的母校康奈尔大学的史学大师布尔先生。布尔先生有一句话他至今没有忘记。先生说，年纪越大，越感觉到容忍比自由更重要。

***** tramscript
:PROPERTIES:
:CREATED: [2022-08-20 17:39:40 -05]
:END:

Seventeen or eighteen years ago, he met for the last time with Mr. Bull, the historian of his alma mater, Cornell University. Mr. Boer had a remark that he has not forgotten to this day. He said that the older he got, the more he felt that tolerance was more important than freedom.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

随着科学技术的普及，人们将更愿意接受电脑采访。有调查显示，与纸张问卷的调查形式相比，越来越多的人更愿意接受借助于电脑的采访，特别是那些对技术感兴趣或熟悉电脑的人，明显持肯定态度。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 17:43:39 -05]
:END:

With the spread of science and technology, people will be more willing to be interviewed by computers. Some surveys show that more and more people are more willing to be interviewed with the help of a computer than in the form of a paper questionnaire, especially those who are interested in technology or familiar with computers, with a clearly positive attitude.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

他想借贵报一角呼吁：读书应该成为人们的追求和良好的风尚。因为读书是将人类浓缩几千年的科技、文化快速习得的最佳方式，读书能够让你在极短的时间内，掌握大量的科学文化知识，摆脱愚昧和迷信。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 17:47:55 -05]
:END:

He would like to take a corner of your newspaper to appeal that reading should become a pursuit and a good fashion for people. Reading is the best way to quickly acquire thousands of years of technology and culture, and it allows you to master a large amount of scientific and cultural knowledge in a very short period of time, and get rid of ignorance and superstition.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

他是一名出色的军官，总是能精确地完成任务。他有个14岁的儿子，正值叛逆期，而且像他的父亲一样顽固。不过他很骄傲，孩子有自己的主见，不会人云亦云，他对自己的孩子有着许多期待。

***** trnascript
:PROPERTIES:
:CREATED: [2022-08-20 17:53:41 -05]
:END:

He is an outstanding officer who always gets the job done with precision. He has a 14-year-old son who is in the midst of a rebellious phase and is as stubborn as his father. He is proud, however, that the child has his own opinions and does not follow the crowd, and he has many expectations of his child.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

一次，我问他：“忙些什么？”他说：“练画儿，每天糟蹋好多纸！”他的画儿很像他的文章，是些小画儿，雅气，很有品位，是典型的文人画儿。他的画儿和他的文章颇有共同之处，观其画儿能咂摸出他写文章的特点。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 17:58:33 -05]
:END:

Once, I asked him, "What are you doing?" He said, "I'm practicing painting, and I waste a lot of paper every day! "His paintings are very much like his writings, they are small paintings, elegant, very tasteful, typical of a literati. His paintings have something in common with his writings, and by looking at his paintings, I can smack the characteristics of his writings.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



