* 听力

** 第二部分
:PROPERTIES:
:ID: 03002995-b3dc-48ca-b3e5-96dddf470fab
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：孙老师是搞生命科学的，今天打算跟大家谈谈我们非常熟悉的睡眠。
男：对于睡眠的机制和功效，前沿的探索尽管还很粗浅，但科学家基本上得出了一些结论。
女：我们进入休息状态的时候，大脑是否在休息？
男：不会。我们从能耗的角度来考虑。我们思考、工作时，大脑对血氧的消耗可达全身的 40％以上，而在睡眠状态下，大脑能耗仍达 20％～30％。这和人的肌体大不相同，静卧时肌体的能耗可降低到运动时的十分之一。可见，人在睡眠时大脑仍在紧张地工作。
女：我们能不能随意调整睡眠时间、长度或时段？
男：也不能，至少是极为困难的。成年人每天需要 7 至 9 小时睡眠，平均 7 个半小时。睡眠效果最佳的时段，是午夜之前到第二天早上六点，所以越洋飞行后倒时差是挺痛苦的事，调整过来后，你还得按当地的这个时段来睡眠。这也说明，人们几乎不能适应“大夜班”，可能的话，应该尽量避免。偶尔为之，或许还凑合，长期如此，就是对身体的摧残。
女：人越老需要的睡眠时间越少，有道理吗？
男：不是。上了年岁，不容易长睡，但白天会打盹儿。好办法是分数次睡眠，就是人们常说的“猫打盹儿”，对老龄人蛮实用的。《马年睡个好觉》这本书提到年近七旬的丘吉尔，在第二次世界大战中，是如何挺过公务繁忙的那五个年头的，他靠的就是每天数次的“猫睡”。每次少至 20 分钟，长不超出一小时，一次不够，两次足矣，这样老人精力不济、记性变差的疲态就可以改善了。
女：睡不着时闭眼静卧能代替睡眠吗？
男：不能。也许这能保持一些精力，减低一点儿能耗，但大脑休整的充分实现，要靠真正的睡眠来完成。睡眠恶化固然有压力、紧张、心理问题的因素，但还有其他原因，往往要靠诊治，不然不会轻易消失。同时，坚持运动也会有很大帮助。

**** 音频

a07b13e0-03b6-466f-a16d-e636dcf99187.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: ac496bd0-09c1-4b20-853a-abddd8c4f921
:END:

***** 问题

对于睡眠的研究，现在处于什么阶段？

****** 音频

5a413a2b-fb01-4f14-9eb3-f29d7a2e1222.mp3

***** 选择

****** A

有了定论

****** B

十分浅显

****** C

深人探索阶段

****** D

已达最高水平

***** 答案

B

**** 7
:PROPERTIES:
:ID: c7085420-10e5-4f57-acfa-691580a1c73a
:END:

***** 问题

为什么说人在睡眠状态中，大脑没有休息？

****** 音频

0474138d-825c-487b-b385-05def3da7e76.mp3

***** 选择

****** A

大脑能耗减少有限

****** B

大脑仍在紧张思考

****** C

肌体能耗大幅减少

****** D

肌体仍需紧张工作

***** 答案

A

**** 8
:PROPERTIES:
:ID: c24c9063-5c54-4d1c-b78c-4c733f2494cc
:END:

***** 问题

关于睡眠时间、睡眠长度和时段，下列哪项正确？

****** 音频

a023ee4f-fba6-475a-8dd7-af72b63b7b44.mp3

***** 选择

****** A

睡眠长度可长可短

****** B

睡眠时间应在午夜之后

****** C

上夜班后必须要补充睡眠

****** D

人体不堪忍受睡眠时段混乱

***** 答案

D

**** 9
:PROPERTIES:
:ID: 2c12f7d9-2a23-473a-97b3-399a9f113738
:END:

***** 问题

关于猫睡，下列哪项正确？

****** 音频

913df9e7-6ef0-4a0a-ab65-a3d98685775c.mp3

***** 选择

****** A

猫睡是呆老的表现

****** B

猎睡是丘吉尔发明的

****** C

应大大普及猎睡方式

****** D

精力不足可用猫睡缓解

***** 答案

D

**** 10
:PROPERTIES:
:ID: 9614e0b9-68f7-46f2-9e58-6c3b5e14514d
:END:

***** 问题

闭眼静卧的作用是什么？

****** 音频

da9e8c67-d74e-4178-a309-ae96507053d4.mp3

***** 选择

****** A

湘少消耗

****** B

改善睡眠

****** C

缓解紧张的心情

****** D

使大脑得到休整

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

他毕业于康奈尔大学

***** B

布尔先生认为自由最重要

***** C

十儿年前他就想见布尔先生

***** D

布尔先生只和他说了一句话

**** 段话

十七八年前，他最后一次会见他的母校康奈尔大学的史学大师布尔先生。布尔先生有一句话他至今没有忘记。先生说，年纪越大，越感觉到容忍比自由更重要。

***** 音频

d7729493-10f7-4cc4-9b43-90741f4f6256.mp3

**** 答案

A

*** 2

**** 选择

***** A

纸张问卷调查更受欢迎

***** B

多数人都渴望学习新技术

***** C

电脑采访将被更多的人肯定

***** D

电脑采访只适合熟悉电脑的人

**** 段话

随着科学技术的普及，人们将更愿意接受电脑采访。有调查显示，与纸张问卷的调查形式相比，越来越多的人更愿意接受借助于电脑的采访,特别是那些对技术感兴趣或熟悉电脑的人，明显持肯定态度。

***** 音频

c91f448a-5998-4a68-855f-cab490f547b9.mp3

**** 答案

C

*** 3

**** 选择

***** A

读书可搓脱愚昧

***** B

不读书就会迷信

***** C

他借了一张报纸看

***** D

书也传授学习方法

**** 段话

他想借贵报一角呼吁：读书应该成为人们的追求和良好的风尚。因为读书是将人类浓缩几千年的科技、文化快速习得的最佳方式，读书能够让你在极短的时间内，掌握大量的科学文化知识，摆脱愚昧和迷信。

***** 音频

e58957c5-b308-416f-8db3-9ab8970b1be8.mp3

**** 答案

A

*** 4

**** 选择

***** A

儿子不喜欢坏天气

***** B

儿子从小做事认真

***** C

儿子将来也愚当军官

***** D

儿子是个有主意的人

**** 段话

他是一名出色的军官，总是能精确地完成任务。他有个 14 岁的儿子，正值叛逆期，而且像他的父亲一样顽固。不过他很骄傲，孩子有自己的主见，不会人云亦云，他对自己的孩子有着许多期待。

***** 音频

393497ef-8750-4045-93ad-3e020f8617a0.mp3

**** 答案

D

*** 5

**** 选择

***** A

其画儿如其文

***** B

他学画儿非常用心

***** C

他只写些短小的文章

***** D

他给自己的文章画插图

**** 段话

一次，我问他：“忙些什么？”他说：“练画儿，每天糟蹋好多纸！”他的画儿很像他的文章，是些小画儿，雅气，很有品位，是典型的文人画儿。他的画儿和他的文章颇有共同之处，观其画儿能咂摸出他写文章的特点。

***** 音频

eaa0b0fb-67f8-4e78-a291-b4ff552bd5b4.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

早睡早起，有益身心健康，但它并不适合每一个人，尤其是 IT 族、文字工作者。在一些拥有伟大头脑和卓越功勋的人中，盛行夜猫子习惯。

几个月前，王鹏曾尝试早起。他比以往提前 1～1.5 个小时起床，但他无法适应早早地躺在床上。不管白天多么疲惫，晚上 10:00 以后他的头脑都变得活跃兴奋，直到 12:00 以后。早早地在床上躺着，他会心烦意乱、辗转反侧，恨不得用拳头捶打自己，就是一点儿也不困。不得已，他又重拾惯例。

当然晚睡晚起也不是完全有利。如果不加控制和计划，将会导致过度睡眠，进而浪费掉一整天的大好时光。因此，晚起不等于不起，晚睡不等于不睡，最好设置合理的作息时间，制订适合自己生物钟的时间表，充分利用自由的夜晚时间，这就是我给夜猫子的一些建议，希望对提高我们的工作效率有所帮助。

*** 14-17

**** 课文

自然界的花儿不仅形态各异，颜色更是五彩缤纷，那么，花儿为什么会有各种颜色呢？原来，花瓣中含有各种色素，正是这些色素，形成了花儿的五颜六色。

造就花儿色泽最主要的色素叫作“花青素”，它分布在细胞的液泡内，控制花儿的颜色变化。花青素很调皮，在不同的环境下，会形成不同的颜色。在酸性溶液中，它呈现红色，酸性越强，颜色越红；在碱性溶液中，它呈现蓝色。碱性较强时，会成为蓝黑色，当它处于中性环境的时候，则是紫色。

花青素虽然神通广大，但花的颜色并不全由它来控制，广泛存在于花瓣中的另一类色素，是类胡萝卜素，这种色素“色如其名”。目前已发现的类胡萝卜素有 600 种以上，不同种类的类胡萝卜素能使花显出黄色、橙黄色、橙红色等。

此外，影响花朵颜色的色素还有类黄酮、甜菜色素等。至于白花，是因为细胞液里不含色素，而绿色花，则是含有叶绿素的缘故。

