* 听力

** 1

*** 1

**** transcript

十七八年前，他最后一次会见他的母校康奈尔大学的史学大师布尔先生。布尔先生有一句话他至今没有忘记。先生说，年纪越大，越感觉到容忍比自由更重要。

***** tramscript
:PROPERTIES:
:CREATED: [2022-08-20 17:39:40 -05]
:END:

Seventeen or eighteen years ago, he met for the last time with Mr. Bull, the historian of his alma mater, Cornell University. Mr. Boer had a remark that he has not forgotten to this day. He said that the older he got, the more he felt that tolerance was more important than freedom.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

随着科学技术的普及，人们将更愿意接受电脑采访。有调查显示，与纸张问卷的调查形式相比，越来越多的人更愿意接受借助于电脑的采访，特别是那些对技术感兴趣或熟悉电脑的人，明显持肯定态度。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 17:43:39 -05]
:END:

With the spread of science and technology, people will be more willing to be interviewed by computers. Some surveys show that more and more people are more willing to be interviewed with the help of a computer than in the form of a paper questionnaire, especially those who are interested in technology or familiar with computers, with a clearly positive attitude.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

他想借贵报一角呼吁：读书应该成为人们的追求和良好的风尚。因为读书是将人类浓缩几千年的科技、文化快速习得的最佳方式，读书能够让你在极短的时间内，掌握大量的科学文化知识，摆脱愚昧和迷信。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 17:47:55 -05]
:END:

He would like to take a corner of your newspaper to appeal that reading should become a pursuit and a good fashion for people. Reading is the best way to quickly acquire thousands of years of technology and culture, and it allows you to master a large amount of scientific and cultural knowledge in a very short period of time, and get rid of ignorance and superstition.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

他是一名出色的军官，总是能精确地完成任务。他有个14岁的儿子，正值叛逆期，而且像他的父亲一样顽固。不过他很骄傲，孩子有自己的主见，不会人云亦云，他对自己的孩子有着许多期待。

***** trnascript
:PROPERTIES:
:CREATED: [2022-08-20 17:53:41 -05]
:END:

He is an outstanding officer who always gets the job done with precision. He has a 14-year-old son who is in the midst of a rebellious phase and is as stubborn as his father. He is proud, however, that the child has his own opinions and does not follow the crowd, and he has many expectations of his child.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

一次，我问他：“忙些什么？”他说：“练画儿，每天糟蹋好多纸！”他的画儿很像他的文章，是些小画儿，雅气，很有品位，是典型的文人画儿。他的画儿和他的文章颇有共同之处，观其画儿能咂摸出他写文章的特点。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 17:58:33 -05]
:END:

Once, I asked him, "What are you doing?" He said, "I'm practicing painting, and I waste a lot of paper every day! "His paintings are very much like his writings, they are small paintings, elegant, very tasteful, typical of a literati. His paintings have something in common with his writings, and by looking at his paintings, I can smack the characteristics of his writings.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：孙老师是搞生命科学的，今天打算跟大家谈谈我们非常熟悉的睡眠。
男：对于睡眠的机制和功效，前沿的探索尽管还很粗浅，但科学家基本上得出了一些结论。
女：我们进入休息状态的时候，大脑是否在休息？
男：不会。我们从能耗的角度来考虑。我们思考、工作时，大脑对血氧的消耗可达全身的 40％以上，而在睡眠状态下，大脑能耗仍达 20％～30％。这和人的肌体大不相同，静卧时肌体的能耗可降低到运动时的十分之一。可见，人在睡眠时大脑仍在紧张地工作。
女：我们能不能随意调整睡眠时间、长度或时段？
男：也不能，至少是极为困难的。成年人每天需要 7 至 9 小时睡眠，平均 7 个半小时。睡眠效果最佳的时段，是午夜之前到第二天早上六点，所以越洋飞行后倒时差是挺痛苦的事，调整过来后，你还得按当地的这个时段来睡眠。这也说明，人们几乎不能适应“大夜班”，可能的话，应该尽量避免。偶尔为之，或许还凑合，长期如此，就是对身体的摧残。
女：人越老需要的睡眠时间越少，有道理吗？
男：不是。上了年岁，不容易长睡，但白天会打盹儿。好办法是分数次睡眠，就是人们常说的“猫打盹儿”，对老龄人蛮实用的。《马年睡个好觉》这本书提到年近七旬的丘吉尔，在第二次世界大战中，是如何挺过公务繁忙的那五个年头的，他靠的就是每天数次的“猫睡”。每次少至 20 分钟，长不超出一小时，一次不够，两次足矣，这样老人精力不济、记性变差的疲态就可以改善了。
女：睡不着时闭眼静卧能代替睡眠吗？
男：不能。也许这能保持一些精力，减低一点儿能耗，但大脑休整的充分实现，要靠真正的睡眠来完成。睡眠恶化固然有压力、紧张、心理问题的因素，但还有其他原因，往往要靠诊治，不然不会轻易消失。同时，坚持运动也会有很大帮助。

*** 音频

a07b13e0-03b6-466f-a16d-e636dcf99187.mp3

*** 题目

**** 6

***** 问题

对于睡眠的研究，现在处于什么阶段？

***** 音频

5a413a2b-fb01-4f14-9eb3-f29d7a2e1222.mp3

***** 选择

****** A

有了定论

****** B

十分浅显

****** C

深人探索阶段

****** D

已达最高水平

***** 答案

B

**** 7

***** 问题

为什么说人在睡眠状态中，大脑没有休息？

***** 音频

0474138d-825c-487b-b385-05def3da7e76.mp3

***** 选择

****** A

大脑能耗减少有限

****** B

大脑仍在紧张思考

****** C

肌体能耗大幅减少

****** D

肌体仍需紧张工作

***** 答案

A

**** 8

***** 问题

关于睡眠时间、睡眠长度和时段，下列哪项正确？

***** 音频

a023ee4f-fba6-475a-8dd7-af72b63b7b44.mp3

***** 选择

****** A

睡眠长度可长可短

****** B

睡眠时间应在午夜之后

****** C

上夜班后必须要补充睡眠

****** D

人体不堪忍受睡眠时段混乱

***** 答案

D

**** 9

***** 问题

关于猫睡，下列哪项正确？

***** 音频

913df9e7-6ef0-4a0a-ab65-a3d98685775c.mp3

***** 选择

****** A

猫睡是呆老的表现

****** B

猎睡是丘吉尔发明的

****** C

应大大普及猎睡方式

****** D

精力不足可用猫睡缓解

***** 答案

D

**** 10

***** 问题

闭眼静卧的作用是什么？

***** 音频

da9e8c67-d74e-4178-a309-ae96507053d4.mp3

***** 选择

****** A

湘少消耗

****** B

改善睡眠

****** C

缓解紧张的心情

****** D

使大脑得到休整

***** 答案

A

