* Text

** title

你睡好了吗

** content
:PROPERTIES:
:CREATED: [2022-12-03 23:31:12 -05]
:END:

对普通人来说，睡觉只是贯可是对于患有顽固失眠症的人来说，睡觉却成了难得的奢侈。

近日，中国发布的睡眠指数总得分66.5分，超过36.2％的居民得分低于及格线60分。统计数字显示，睡眠指数的得分随着城市层级的升高而下降，一线城市的平均睡眠指数为60.3分，三线城市为61.4分，而农村和小城镇得分均在70分以上。可见，当前失眠症正扰乱着人们的情绪，摧残着城市人群的健康。

调查发现，该睡时不睡，是影响成人健康睡眠的重要因素。手机和平板电脑的普及，使睡前上网的习惯日渐盛行，不少人临睡前再过过网瘾成了常态。而电子产品严重的光污染不仅影响了人体褪黑素的正常分泌，还会使人体生物钟后移，结果就是晚上睡不着，早上睡不醒。

褪黑素是什么？据研究，褪黑素是保证人体健康的重要物质之一，它的职能包括增强人体免疫力、抗衰老、调剂睡眠等。当人体内褪黑素分泌不正常时，人体细胞组织和器官的作用和活动能力都会受到影响，各种疾病，包括恶性肿瘤，也就是我们常说的癌症，就会随之而来。

除了睡不着，还有人睡不好。中国有睡眠障碍的人约为38.2％，因此，在中国专治睡眠障碍的医生总是供不应求。

睡眠障碍表现为入睡困难，头在枕头上，就是睡不着，翻来覆支瞎折腾，心烦意乱得无法容忍白天又老是犯困。此外，入睡后噩梦连连，一会儿蹬腿，一会儿挥拳头，不时大声叫喊，也是睡眠障碍的典型症状。

睡眠不足会使人气色不好，行为能力偏离正常轨道，据愁，一个17～19个小时没睡觉的人，其行为能力与一个血液中酒精浓度为0.05％的人不相上下。即便一周内每天少睡两个小时，疲劳也会累积在一起，并在不适宜的场合引发事故，我们曾见过这样一个不可思议的案例，一位技术熟练的老司机把车开上了逆行道，而这就是疲劳驾驶造成的。

此外，长期睡眠不足还会使人注意力下降、表情落户然、丢三长程四、情绪起伏不定，动不动就发呆，继而记性越差，到了更严重的地步，会思维混乱，健康状况逐步恶化，进而诱发惭紧性疾病。总而言之，睡眠好坏对人体健康举足轻重，因此，医生呼吁，不要对失眠症状无动于衷，要弄清病因，并根据不同情况竭尽全力进行治疗。

不可否认的是，很多人原本睡眠是没有问题的，导致致问题的根源多多少少与不健康的生活方式有关，因此，对付失眠症的方法就是纠正不好的生活习惯，不要糟蹋自己的身体，不要自己迫害自己，不要让坏习惯毁。

** source

改编自北京卫视《北京你早》节目“2014年中国睡眠措数发布”

** footnotes

① 一线城市：中国一线城市、二线城市、三线城市的主要指标包括经济地位、城市规模、城市级别、影响力、辐射力、知名度等。一线城市指对本国的经济、政治具有重要作用的在都市，在城市规模、基酝建设、财政收入、消费、对人才的吸引等方面均领先于其他城市，二线城市、三线城市以上指标相对降低。例如北京、上海是一线城市，杭州、南京、苏州、青岛等为二线城市，海口、邯郸、洛阳等为三线城市。
① 褪黑素：melatonin，是存在于从藻类到人类等众多生物中的一种荷尔蒙，它在生物中的含量随每天的时间变化而变化。
