* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 185a27d2-e169-449d-9089-245996adb772
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fb4dfd45-9022-47a2-b788-c699a141c5fc.mp3
***** 转录
《康熙字典》是清代康熙年间出版的图书，作者是张玉书、陈廷敬等，它是在明朝《字汇》《正字通》两书的基础上加以增订的。该书的编撰工作始于康熙四十九年，成书于康熙五十五年，历时六年，因此书名叫《康熙字典》。
**** 选择
***** A
《康熙字典》是康熙编的
***** B
《康熙字典》的编纂者共有2人
***** C
《康熙字典》的名字是康熙起的
***** D
编写《康熙字典》共用了6年时间
**** 答案
D
*** 2
:PROPERTIES:
:ID: 9e98a5b5-115c-4114-ab1c-c5a2e8716d33
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
f3855770-a3d1-4f04-847a-7b146292f059.mp3
***** 转录
有些人很爱凑热闹，不管街头发生什么事情，他们都要驻足引颈，看个究竟。有的还免不了要放开喉咙，起哄喝倒彩，从中寻找乐趣，寻求刺激，这其实反映出一种病态心理。
**** 选择
***** A
爱起哄的心态不健康
***** B
有好奇心是人的本性
***** C
在街上唱歌是一种快乐
***** D
喜欢凑热闸的人不在少数
**** 答案
A
*** 3
:PROPERTIES:
:ID: f79a65d5-e6c4-416b-999a-13c18e257879
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
da250eb8-1a64-4559-9a63-c714aa4ffb9b.mp3
***** 转录
婴儿在 1 周岁左右，开始学会独立行走，能更自由地接近和探索周围事物。当他看到桌子上放着一个他喜爱的玩具而无法拿到手时，会推大人的手去拿，表现出初步的有意向的行动。
**** 选择
***** A
婴儿喜欢拥有自己的玩具
***** B
大人总会帮婴儿实现目标
***** C
大人应该想办法了解婴儿的理想
***** D
1岁的婴儿会表现出自己的意向
**** 答案
D
*** 4
:PROPERTIES:
:ID: 2f5aa9a8-a144-46c7-bbbb-2716e1a1139e
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
0374b7c3-d047-4afe-b889-11373b1c51b0.mp3
***** 转录
读者获取信息也是有成本与收益的。他们花钱买报，花时间看报就是成本，从报纸中得到对自己有用的信息就是收益。报纸扩版后，读者的成本增加了，尤其是要花更多宝贵的时间去读，忙碌的现代人承受不起这么高的成本。
**** 选择
***** A
读者的时间也是成本
***** B
报纸的成本越来越高
***** C
扩版后报纸信息变少
***** D
现在的人不愿意读报
**** 答案
A
*** 5
:PROPERTIES:
:ID: 7102547e-55a0-4925-a167-e4c00eff6a5a
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
567d3b78-264b-4d00-acbe-428609f48f5f.mp3
***** 转录
这个剧本的可读性很强，尤其是剧本的语言，让人看后久久难忘。它的语言虽然都是生活中的口语，但经过了作者的提炼熔铸后，显得既鲜活又不失文雅，而且富有情趣。可以想象，这样朗朗上口的语言，一定很适合舞台演出。
**** 选择
***** A
这个剜本只适合阅读
***** B
这个剧本演出效果很好
***** C
这个剧本写得极其成功
***** D
生活中的口语是最文雅的
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 76d96a6b-5838-420a-8fa4-ccfaaf4c439e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
5fabd694-e537-4695-bc7d-cda5a51faa1f.mp3
***** 转录
女：能不能告诉我们，您最初怎么选中了厨师这个行业？
男：我最初选择学厨师，想法很简单，人走到哪里都得吃饭，干这一行肯定饿不着。
女：后来怎么就做到了五星级酒店的京菜主厨呢？
男：进了饭店从做小工、刷盘子开始，我越干越觉得，厨师这一行实在是个让人痴迷又魅力无穷的行业。
女：我们都知道掂大勺、刀功，都是厨师的看家本领，您学艺过程中，最头疼的是什么呢？
男：记得刚学会做菜那会儿，我是吃到哪儿挑到哪儿，每吃一道菜，都要评头论足，“油放少了”“盐放多了”。后来，我想明白了，同样的调料，不同的人会炒出不同的味儿，就是中餐的精髓。我学做饭那时候，最伤脑筋的就是菜谱上“少许”这俩字，老是分寸把握不好。把这两个字琢磨透了，就可以出师了。
女：自从您学厨师之后，过年过节，您家的聚餐就成了您露一手的机会了吧？
男：说到这儿，我就会想起奶油菜花，这道菜给我的教训太深了。
女：能讲给我们听听吗？
男：2003 年春节，我在学校练了一年的基本功，急于给大伙儿露一手，自告奋勇要给大家来个奶油菜花。这道菜我没做过，听老师在课堂上提过，觉得没什么难的。结果我进了厨房，一看那一堆菜花和黄油就傻眼了，最后愣是做出一锅大乱炖。菜端上桌，我觉得太丢人了，简直无地自容。亲戚朋友倒是非常捧场，把那道菜吃了个精光。
女：大伙儿肯定能原谅您，那时候您还是个刚入学一年的学生嘛。
男：8 年以后，我把家里的亲戚朋友召集到一块儿，来了场“雪耻之战”。我当时放下豪言，让大家随便点，想吃什么点什么，他们能想得出的，我都能做。几个小时倒腾出来的十几道菜，当然也得到了大伙儿的一致称赞。
女：您心里特别美吧？
男：那就不用说了。
**** 题目
***** 6
:PROPERTIES:
:ID: 8dc4a7d0-9a8f-4f3c-9c3d-f5bb4608c8c9
:END:
****** 问题
******* 音频
61fe386e-2fda-4389-823d-f35e7bec51b3.mp3
******* 转录
男的为什么选择做厨师？
****** 选择
******* A
厨师省脑子
******* B
厨师挣钱多
******* C
厨师不会失业
******* D
厨师不会挨俄
****** 答案
C
***** 7
:PROPERTIES:
:ID: 6df67efc-10cb-4ff7-81d0-ebc39526b69d
:END:
****** 问题
******* 音频
b3d00605-f093-444c-9ba2-dca657ddf48f.mp3
******* 转录
为什么男的能做到五星级酒店的京菜主厨？
****** 选择
******* A
因为做小工、刷盘子太累
******* B
因为他从小喜欢吃北京菜
******* C
因为他迷恋上了厨师这个行业
******* D
田为他的师傅是个很有魅力的人
****** 答案
C
***** 8
:PROPERTIES:
:ID: 965cbce1-b96f-4853-9f13-cce3a5c24275
:END:
****** 问题
******* 音频
26c6ccb8-4040-468e-a9b3-f8e83d1b49a5.mp3
******* 转录
关于中餐，下列哪项正确？
****** 选择
******* A
要多放油
******* B
做菜讲究标准化
******* C
各种调料要按顺序放
******* D
各种调料的量要恰到好处
****** 答案
D
***** 9
:PROPERTIES:
:ID: 48642522-0064-4a35-958f-36ae206fd321
:END:
****** 问题
******* 音频
2fac5c9e-7af6-4efd-8680-811d6234f097.mp3
******* 转录
关于奶油菜花，下列哪项正确？
****** 选择
******* A
是男的学会的第一道菜
******* B
最后男的根本没做出来
******* C
是大家强烈要求男的做的菜
******* D
是大家公认最好吃的一道菜
****** 答案
B
***** 10
:PROPERTIES:
:ID: 4360a1c8-9e92-4638-9984-30d2587184be
:END:
****** 问题
******* 音频
52d0e397-83a1-4a9d-a8c3-ed66a61d5735.mp3
******* 转录
8 年以后，男的做了件什么事？
****** 选择
******* A
请大家吃了顿最贵的饭
******* B
一顿饭吃了好几个小时
******* C
做的都是大家没吃过的菜
******* D
为8年前的事找回了面子
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 29f9a243-8d26-42b9-896d-d0316f1220dd
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
0345cfe7-3172-4bc2-a7ed-3bae64ad2f42.mp3
***** 转录
音乐是一种有效的止痛剂。有研究报告称，手术前、手术后甚至手术过程中播放音乐，都有助于缓解疼痛。
本项研究共涉及近 7000 名患者的 70 多次临床试验的数据，试验证明，音乐确实是一剂有效的止痛药。实验者把术后疼痛分为 0－10 级，０代表丝毫不疼，10 代表疼到极点，听音乐能够使疼痛等级下降２级。
研究人员发现，音乐的镇痛作用与音乐类别无关，具体曲目由医生还是由患者选择也无所谓。研究涉及多种手术，但不含大脑或中枢神经系统手术。令人意外的是，患者即便接受全身麻醉，听音乐也有助于缓解术后疼痛，但效果不如接受手术时意识清醒的患者。
虽然目前尚未将播放音乐作为帮助患者术后康复的常规项目，但这项研究毫无疑问在帮助人们进一步了解音乐的积极影响方面做了有益的探索。
**** 题目
***** 11
:PROPERTIES:
:ID: 42472d7a-bcbd-4a4c-b955-dc90ce3a317a
:END:
****** 问题
******* 音频
c68952da-8e9c-4c9f-aa65-0fcccfc4722f.mp3
******* 转录
关于试验，下列哪项正确？
****** 选择
******* A
“0“表示最轻度的疹痛
******* B
“10“表示最世重的疼痛
******* C
研究者做了70多次手术
******* D
研究对象涉及7000多人
****** 答案
B
***** 12
:PROPERTIES:
:ID: 1b8c66b4-d1ce-4fd7-8736-71b6bdef8aa7
:END:
****** 问题
******* 音频
ae742a7b-844d-41df-9b4f-23916f2b1161.mp3
******* 转录
关于试验结果，下列哪项正确？
****** 选择
******* A
音乐减痛更适用于术后康复
******* B
音乐减痛不适用于脑部手术
******* C
音乐减痛对全身麻醉者无效
******* D
任何类型的音乐都可减轻疣痛
****** 答案
D
***** 13
:PROPERTIES:
:ID: 4581b555-978a-41ba-83f6-465a44c84763
:END:
****** 问题
******* 音频
04b3c6ee-01fe-467a-ba79-20208609cd6a.mp3
******* 转录
这项研究的意义是什么？
****** 选择
******* A
改善医院的氛围
******* B
增加临床的应用
******* C
减少麻醉药的使用
******* D
认识音乐的积极作用
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: 1e495ffc-4d50-4ead-bc92-131ae42ae61c
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
d60f29b3-0579-4f24-97a7-5227e8d10294.mp3
***** 转录
据世界卫生组织统计，全球一半患者不会正确用药。在中国，用药安全同样是个不可回避的问题，一项涉及 45 万份的网络调查显示，九成人存在用药误区。
比如止痛药，不少人觉得，不管哪里疼痛，吃点儿止痛药，病就好了，这是再简单不过的事了。殊不知，乱用止痛药也会有严重后果，如损伤内脏、延误病情、产生心理依赖，甚至可能致死。再比如创可贴，人人都觉得自己会用，完全不存在专业的问题，可是有多少人知道，它的基本作用只是止血，并不能完全做到抗菌消毒。创可贴吸水性和透气性较差，使用不当可能造成伤口感染。出血较多的伤口、小而深的伤口、动物咬伤、污染较重的伤口、烧伤或者烫伤的创面，都不宜使用创可贴，它只适用于皮肤表面、出血不多而又不需要缝合的小伤口。
**** 题目
***** 14
:PROPERTIES:
:ID: 6468ee36-a0ad-44ea-87be-f7129d606083
:END:
****** 问题
******* 音频
4332b5d1-0ce1-41d2-a1b5-234b01b05d7f.mp3
******* 转录
关于用药误区，下列哪项正确？
****** 选择
******* A
全球一半人不能正确用药
******* B
九成患者安全用药知识匮乏
******* C
45万中国人缺乏正确的用药知识
******* D
大部分被调查者有用药不当的问题
****** 答案
D
***** 15
:PROPERTIES:
:ID: 2276f815-cdc8-4167-9487-7e634b04d160
:END:
****** 问题
******* 音频
4327d147-cce1-4484-842d-3bb37dddc58a.mp3
******* 转录
关于止痛药，下列哪项正确？
****** 选择
******* A
止痛药很难标本兼治
******* B
止痛药的作用不用探讨
******* C
一痛药管用只是虚假现象
******* D
一痛药用法简单无副作用
****** 答案
A
***** 16
:PROPERTIES:
:ID: 864ac7f4-da61-4cba-93e1-04e04bf883a0
:END:
****** 问题
******* 音频
cf9912af-bddc-42c2-b835-790fa020fc4c.mp3
******* 转录
关于创可贴，下列哪项正确？
****** 选择
******* A
抗菌消毒作用很强
******* B
用后伤口不能沾水
******* C
应在医生指导下使用
******* D
使用不当会造成感染
****** 答案
D
***** 17
:PROPERTIES:
:ID: 49ed5259-1cc1-4ede-b628-e3bca09601db
:END:
****** 问题
******* 音频
6240749b-1bba-4da0-a013-7243c2bd6ccd.mp3
******* 转录
创可贴适用哪种情况？
****** 选择
******* A
烧伤患者
******* B
烫伤患者
******* C
出血少的伤口
******* D
小而深的伤口
****** 答案
C
* 阅读
** 第一部分
*** 18
**** 句子
***** A
那所学校的校舍，不是正规的学校。
***** B
他厌恶公文，也不喜欢动笔，当然也没有备忘录。
***** C
他对武术的见解成为了年轻人的座右铭，成为了励志的经典话语。
***** D
它时时提醒我们，不要为歪门邪道所惑，走到无法回头的岔路上去。
**** 答案
A
*** 19
**** 句子
***** A
你们说一套做一套，言行不一，表里相违，真是岂有此理。
***** B
父亲很生气，说我们跟他说话没有礼貌，一点儿都把他不放在眼里。
***** C
大灾之年，洪水泛滥，它的肆无忌惮给人们带来了无穷的灾害和忧患。
***** D
脸谱以红色代表忠勇，黑色代表粗直，白色代表奸邪，使人物性格一目了然。
**** 答案
B
*** 20
**** 句子
***** A
最好多做工作，他每天清晨5点多钟就起床，深夜才就富。他对工作一丝不苟，非常讨厌懒散拖拉的作风。
***** B
现在有些音乐电视越来越吸引不了观众。有的音乐作品还是不错的，可一配上电视就显得画蛇添足、不伦不类了。
***** C
搜索引擎能够帮助我们更快更容易地找到信息，你只需输人一个或几个关键词，搜索引擎就会找到所有符合要求的网页。
***** D
儿乎每台文艺晚会都少不了相声节目，演员们幽默的语言、诙谐的表情，逗得观众捧腹大笑。相声已成为流传最广、最为群众喜闻乐见的曲艺形式。
**** 答案
A
** 第二部分
*** 21
**** 段话
在生活世界中，人不是一个[[gap]]完成的概念，而是一个可选择的概念。人存在[[gap]]生活，人选择生活就是选择存在方式。选择存在方式就是[[gap]]自身。
**** 选择
***** A
****** 1
预先
****** 2
即
****** 3
创作
***** B
****** 1
父母
****** 2
和
****** 3
完善
***** C
****** 1
事先
****** 2
将
****** 3
改变
***** D
****** 1
社会
****** 2
亦
****** 3
激励
**** 答案
A
*** 22
**** 段话
幸福是什么？幸福就是看着粮食心里[[gap]]，不再有饿肚子的恐惧。我知道在农村的很多地方，农民家里都[[gap]]着很多粮食，看到满仓的粮食，农民的心里就踏实多了。这是很[[gap]]的想法，但[[gap]]不是被我们抛弃的真理。
**** 选择
***** A
****** 1
平静
****** 2
储蓄
****** 3
庸俗
****** 4
毕竟
***** B
****** 1
踏实
****** 2
偷存
****** 3
朴实
****** 4
未必
***** C
****** 1
平稳
****** 2
积聚
****** 3
机灵
****** 4
历来
***** D
****** 1
沉着
****** 2
常备
****** 3
难堪
****** 4
明明
**** 答案
B
*** 23
**** 段话
用本族语也好，用外族语也好，一个人在思维的时候总得运用一种语言。学习外语耍养成用外语[[gap]]的习惯。如果没有这种习惯，用外语说话时就得先用本族语把意思想好，[[gap]]再译成外语说出来。[[gap]]，说出来的外语就不会流畅、[[gap]]。
**** 选择
***** A
****** 1
思想
****** 2
接着
****** 3
如此
****** 4
正宗
***** B
****** 1
翻译
****** 2
后来
****** 3
当然
****** 4
专业
***** C
****** 1
表达
****** 2
以后
****** 3
那样
****** 4
周密
***** D
****** 1
思维
****** 2
然后
****** 3
这样
****** 4
纯正
**** 答案
D
** 第三部分
*** 段话
-户人家要盖房，各种材料堆放在空地上。一根杨木、一根松木并排放在一个角落里，粗大、光滑，仔细看，杨木仿佛更加粗壮一些。
夜深人静，杨木对松木说起话来。“真高兴，[[gap:24]]1看我这粗大的体型一定是主梁！你呢，蚀然瘦小一些，也可以做根柱子！”松木说：“付出总有回报，[[gap:25]]！”
第二天，工匠来选木料，师傅敲敲松木说：“这根做主梁！”又看看那根粗大的杨木说：“这根做个拴马桩子吧！”
夜深人静，杨木又开始说话了：“[[gap:26]]，就你那体格，要去做主梁？而我，去做拴马桩孔？这世道，还有说理的地方吗！”
松木说：“孩子！你是比我粗大，[[gap:27]]，你却只生长了十几年。我生活的地方风大、缺水，环境恶劣，我们每年只能生长那么一点点，但木质紧密、结实。你生活在水源充足、营养丰富的河湾里，十几年就长得比我粗大了。但是孩孔，你的身体是虚的啊！承担不起主梁的责任。”
听了松木的话，[[gap:28]]，下决心要做好一根拴马桩子！
*** 选择
**** A
努力和汗水都不会白费
**** B
我们终于成材了
**** C
杨木惭愧得无话可说
**** D
那个匠人真是老糊涂了
**** E
可我已经有上百年的树龄了
*** 答案
**** 24
B
**** 25
A
**** 26
D
**** 27
E
**** 28
C
** 第四部分
*** 29-32
**** 段话
在床上吃比萨饼和冰激凌不行，边看电视边吃东西也不行，专家提醒人们：尽管很多人喜欢上述就餐习惯，但它对人体健康一点儿好处也没有。就餐的地点和方式与食物一样重要，因为有些环境会诱惑人多吃，有些就餐方式不利于消化。
有人对办公室、学校、餐馆、路边摊等地方做过比较，结果是餐馆、黑暗的环境以及狼孜虎咽为最差就餐地点和习惯。其理由是餐馆的美显佳育意味着更多的卡路里，因为餐馆中许多菜品的烹任手段是过油之后再炒，而且在餐馆进餐往往比在家里吃得更多。
至于黑暗的环境，主要是在昏暗的光线下，人们更容易无所顾忌地吃，吃得更加没有节制。
狼吞虎咽就更不可取了，细嚼慢咽有助于消化，可以防止喳着、打嗝和心脏病发作。食物的块头越大越难消化，把食物咀嚼成近似液体状才是标准的进餐方式，因此诸位不管多把时间当回事，也千万不要节省吃饭的那点儿时间。
专家特别提示，良好的就餐环境可以调动神经、内分泌和新陈代谢等多个系统，会让人感觉到满足从而停止吃东西。
**** 题目
***** 29
****** 问题
下列哥个是最差就餐地点？
****** 选择
******* A
学校
******* B
餐馆
******* C
办公室
******* D
路边掌
****** 答案
B
***** 30
****** 问题
狼吞虎咽的结果可能是：
****** 选择
******* A
饭量与日俱增
******* B
食物消化得更快
******* C
体味不出食物之美
******* D
丘重时可引发心脏病
****** 答案
D
***** 31
****** 问题
画线词语“把时间当回事”的意思最可能是：
****** 选择
******* A
在意时间
******* B
浪费时间
******* C
算计时间
******* D
消磨时间
****** 答案
A
***** 32
****** 问题
关于就餐，专家特别提示：
****** 选择
******* A
食品质量是最重要的
******* B
应高度重视就餐环境
******* C
吃饭时应该专心致志
******* D
吃饭不要吃撑再停止
****** 答案
B
*** 33-36
**** 段话
初见刘岩，舞者的气质自然流淌，纵使多年前的那次意外让她不能再用灵巧的足尖走近你，你却仍然第一眼就会认定这是一位顶尖的舞者。笑容妞媚却豁达，声音温柔而坚定，郧怕是坐在轮椅上，你也要赞叹她长歌善舞的风采。
刘岩表示《手之彗之》是一本学术著作，英文版的推出更是意义非凡，可以让全世界更加了解中国舞蹈文化。在世界范围内，中国的手舞研究学术性强，传承多样，在丰厚的古典文化滋润中，手舞作为微身体语言舞蹈，可以通过整体与局部来实现情感的沟通与表达。
刘岱既是一名舞者，也是一名教育者，还是一名理论研究者，而她最在意的是教师身份，坚持一线教学，培养青年人才，是她的快乐所在。
2010年，她以自己的名字命名成立了“刘岩文艺专项基金”，一直投身社会公益，关注贫囱、孤残儿童的艺术教育。她告诉我们：“专项基金成立以后，每周末都会资助老师走到儿童福利机构去给那些孤儿或联哑孩子上课，虽然困难很多，但当你去帮助了那些需要帮助的人时，快乐和温暖会充满每个人的内心，最重要的是孩子们从中收获了欢乐。”
**** 题目
***** 33
****** 问题
根据上文，刘宝：
****** 选择
******* A
善于倾听
******* B
憎恶虚伪
******* C
豁达乐观
******* D
为人严肃
****** 答案
C
***** 34
****** 问题
《手之舞之》英文版的意义在于：
****** 选择
******* A
是第一本英文舞蹈学术专著
******* B
着眼于中国古典文化的传播
******* C
创造了中国微身体语言舞蹈
******* D
帮助世界了解中国舞蹈文化
****** 答案
D
***** 35
****** 问题
根据上文，可以知道：
****** 选择
******* A
刘岩在福利机构工作
******* B
刘岩很重视培养年轻人
******* C
刘岩每天生活在快乐之中
******* D
刘岩的基金更倾向于资助老师
****** 答案
B
***** 36
****** 问题
最适合做上文标题的是：
****** 选择
******* A
舞者刘岩
******* B
著名作家刘岩
******* C
孤残儿童的好老师
******* D
她在探测生命的意义
****** 答案
A
