* 课文
** 转录
（一）大脑能“听”出笑声的真假
真是岂有此理，难道我们听到庸俗、不上档次的笑话假笑两声、敷衍一下也不可以吗？可是，好像确实不行。诸位，如果你不想难堪，不想让别人发现你发出的是虚伪、违背心意的笑声，你可以回道，可以不表态，可以把话题岔开，可以装聋装哑，但不要画蛇添足，违心地笑。因为只要你笑，不管你多机灵，不管你掩饰得多么周密，别人都能看出你的笑是真心实意，还是虚情假意、装模作样。有人不禁要问，人是通过什么途径识别“笑”背后的真实情感呢？研究者发现，我们在听到发自内心的笑声和虚假的笑声时，大脑会呈现出完全不同的反应。
假笑声会激活大脑中用于破译情感信息的特定区域，同时大脑会自动分析假笑的缘故，假笑者想隐瞒什么，以及假笑者的意向；诚挚的笑声则会激活大脑中与快乐和积极情绪相关的区域。为了证实这一理论，一丝不苟的研究者让志愿者倾听网站视频中的笑声，同时记录他们大脑的反应，并将志愿者听到真笑与假笑时大脑的反应做对比。测试结果一目了然，志愿者在预先未被告知测试目的的情况下，仅凭直觉就能准确地分辨出假笑声。天呀，人的大脑中竟然深藏着一双能够探测他人喜悦之情真伪的眼睛 1
研究者指出：“人类大脑对于笑声中所隐含的社会和情感信息非常敏感，这不完全是智商问题。当志愿者听到笑声时，会开启大脑中与心智相关的区域，从而获知他人的情感或精神状态，有些志愿者还动用了大脑中控制运动和感知的部分，进而更精准地提炼出真假笑声背后的信息。”
（二）笑未必是最佳良药
中国人喜欢听相声，因为它逗笑。
“笑有益于健康”几乎得到了全世界的认可，“笑一笑十年少”“一笑解千愁”不仅被大家认可，甚至被一些人当作生活的座右铭。中国人深信开怀大笑也好，哈哈傻笑也罢，哪怕是私下里偷偷地笑，都会是生活中最通用，而且管用的治病良方。
有研究证实，笑可以调节情绪，可以促进血液循环和腹肌收缩，100次捧腹大笑所吸收的氧气相当于用桨划船 10 分钟的吸氧量。有人做过这样的试验，开怀大笑一整天，可以燃烧掉 2000 卡路里，从而帮助消耗脂肪，减轻体重，同时，笑有助于缓解动脉硬化，有助于消除紧张感，这就是笑有利于健康的实质性的证据。
然而，笑，真的是人生旅途中的最佳良药吗？答案似乎不是那么肯定。有研究人员表示，笑也不是有百益而无一害的，有时它还会产生副作用。有医生就碰到过这样的案例：有人在肆无忌惮地笑过后因心跳加速而昏迷，而大笑到“几乎笑破肚皮”可能会导致岔气，心脏不舒服，甚至损坏人体健康。新的研究结果对笑“有百益而无一害”的观点提出了挑战，似乎更倾向于笑不是坏事，但分寸要掌握得恰到好处。可是多数人还是深信，笑的是非无须探讨，任何形式的幽黯，伤害风险都不高，其收益则是显而易见的，况且，真是好朋友在一起，高兴了，起起哄，或是遇到了开心事，哪里还顾得上斟酌分寸掌握得恰当不恰当呢？
