* 课文
** 转录
年画的起源
年画是中国画的一种，始于古代的门神画。
有文献记载：传说很久以前，有一对兄弟，专门监督百鬼，发现凶恶的鬼就捆绑起来，无须揭露恶行，直接去喂老虎。于是有人在门上画上他们兄弟二人的像，用以防鬼，这就是最早的门神画。
随着唐宋？两朝经济的发展，文化的昌盛以及民间绘画水平的提高，门神画的内容得以拓展，反映世俗生活题材的作品进入了这一领域。之后，有清朝“学者在论述这类画作时正式使用了”年画“一词，自此，以驱逐祸凶、祝福新年吉祥喜庆为内容的画儿就叫年画了。
木版年画
造纸技术的发明是人类文化发展史上一个重要的里程碑。
有了纸，书写就需要墨水儿，于是有人发明了墨；字画、书信上需要盖章，于是印章开始流行；碑刻、拓印技术被广泛运用，于是有人联想到：这些技术结合起来，不就能印出书来吗 ！ 人们尝试把印章扩大成一张纸那么大，叫作“版”，然后把书的内容刻在版上，在版上涂抹上墨，把纸铺到上面，用刷子均匀地刷印，最后将纸揭起，印品就出来了，这就是最早的雕版印刷。虽然雕版印刷中雕刻版面需要大量的人工和材料，但雕版完成后一经开印，就显示出空前的高效率和印刷量大的优越性。
单色印品终究不能满足人们的审美需求，之后就有了彩色套印技术。人们把这种技术运用到年画制作上，木版彩色套印年画就此诞生。
宋明两代，木版年画从问世走向成熟，之后走进了百姓生活，以至过年贴年画成为了一种风尚，仿佛没有年画，没有烟花爆竹，没有春联就不叫过年，而寄托着百姓美好愿望的年画，也为春节增添了浓浓的年味。当时的另一盛况是，家族式的年画印制场所遍及全国各地。这期间，年画的内容也从威武的门神，扩展到期盼丰收、恭喜发财、连年有余的吉庆画，再到历史故事、戏曲人物、民间笑话、寓言和神话，内容无所不包。年画成了文化交流、道德教育、信仰传承的载体与工具，是老百姓喜闻乐见的文化艺术形式。
年画传人张光宁
第一次见到张光宁的木版年画，是在春节庙会上。在众多摊位中，他的两只木版彩色套印技术做成的布老虎神气极了。那虎翘着尾巴，神态逼真，身上装饰着彩绘花纹和盛开的花朵，全身散发着喜气。我问多少钱，他耸耸肩，对我说：“这是魏州虎。”言外之意是在告诉我这个外行，这虎可是系出名门。我心想：“魏州是哪儿？我不知道别人也未必知道，这算什么推销术！”这是他给我留下的第一印象。
“这个卖年画的不像个商人”，这是他给我留下的第二印象。当你和他讨价还价的时候，他立刻就变得不好意思起来，说话吞吞吐吐。什么“这是纯手工的”“残次品不可避免”这些现成的“谢绝”还价的理由他一条也说不出来，相反却唠唠叨叨地总想和你讨论木版年画中深厚的文化底蕴。
相识久了才知道，他在年画的故乡出生、长大，从小就画年画，基本功扎实，后来又对年画的构图创作、人物塑造、雕版手法、颜料加工等进行了广泛的研究。当他的作品逐步被市场认可后，他又不满足了，中国年画虽不分派别，但不同地区的年画各有所长，都值得学习借鉴。于是，他再接再厉，数年间走遍了全国各大年画产地，与同行进行广泛的交流。不仅如此，参加民俗文化巡展，走进大学和师生就相关主题进行研讨，交流艺术心得，他从不缺席。
张光宁一年到头真够忙的，可他总是干劲十足。他曾真诚地说：“年画占据了我生命的全部，我喜欢它，热爱它，靠它生活，也在努力探索它、发展它。”是啊，愈是经营年画久了，他对年画就愈是热爱。他已确立了自己的目标——传播他喜爱的这一民俗文化。他的信念就是拓展年画的内容，使其雅俗共赏，为更多民众所喜爱，虽然任重道远，也不会一帆风顺，但他一定会坚持下去。
