* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 12a7b391-6fbb-4c9e-9e65-7369a7e2d07c
:END:
**** 对话
***** 转录
女：何必这么费劲儿呢？我来帮你做不就行了？[[file:b1cd5730-30cb-450b-8e4f-b29b6cf5dd94.mp3][(audio)]]
男：那太麻烦你了，我还是自己来吧。[[file:0c2da6cb-946b-49d6-8783-cd6e76530ebe.mp3][(audio)]]
***** 音频
3be9f35c-d349-486c-b3e2-c30ea3b71e3e.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
2dd58f43-765d-4409-8b3d-3cc70ec069e8.mp3
**** 选择
***** A
他不觉得费劲
***** B
他觉得不麻烦
***** C
他可以自己做
***** D
感谢女的帮助他
**** 答案
C
*** 2
:PROPERTIES:
:ID: d6449a3a-f7b9-4265-811f-f7dcc695fff4
:END:
**** 对话
***** 转录
男：你给王老师发个短信告诉他一声吧。[[file:54c9f633-d4c2-4da2-b986-ea5109afd5e4.mp3][(audio)]]
女：他现在应该在上课，看不了短信；[[file:fbeb0008-d6fb-4169-956c-a36e96ab33fb.mp3][(audio)]]何况现在我们都用微信联系，谁还发短信啊？[[file:af29b748-28ba-4da3-8494-4e1786b6bb42.mp3][(audio)]]
***** 音频
3d3ad0ef-7938-44f9-a61a-d50f9812aa42.mp3
**** 问题
***** 转录
对男的的要求，女的是什么态度？
***** 音频
4709b147-8af5-4208-9a77-9f2a6954b9ef.mp3
**** 选择
***** A
反对
***** B
接受
***** C
同意
***** D
好奇
**** 答案
A
*** 3
:PROPERTIES:
:ID: 59aee6a7-f58f-4642-8543-f50406b8a053
:END:
**** 对话
***** 转录
女：你的腿怎么了？摔伤了吗？[[file:64084901-228f-4daf-8e94-004ff7a4c64c.mp3][(audio)]]
男：昨天在健身房锻炼的时候用力过大，把肌肉拉伤了。[[file:44f352ae-594f-44dc-b88b-aabedafccf55.mp3][(audio)]]
***** 音频
f87e5219-7955-4083-83bd-30ce19168f50.mp3
**** 问题
***** 转录
男的是怎么受的伤？
***** 音频
628cd333-6e5d-402c-bd54-55d1c17e51b5.mp3
**** 选择
***** A
摔了跤
***** B
用力不当
***** C
锻炼太多
***** D
被车撞了
**** 答案
B
*** 4
:PROPERTIES:
:ID: 381557a7-e36b-4127-b39b-4f17a803b74d
:END:
**** 对话
***** 转录
男：张教练，您能分析一下本次比赛失利的原因吗？[[file:15023971-9c2c-4594-aa56-479081bd9d87.mp3][(audio)]]
女：主要是队员们参赛前缺乏训练。[[file:1d7b244a-9bce-48ed-a3f6-38267b2bf6b0.mp3][(audio)]]
***** 音频
bcb1d9d3-6a2f-4a52-bfaf-5a09dba9449a.mp3
**** 问题
***** 转录
张教练他们队最后的比赛结果怎么样？
***** 音频
76e58cfc-3748-46ca-8d0f-0ab821d69566.mp3
**** 选择
***** A
赢了
***** B
输了
***** C
平了
***** D
不清楚
**** 答案
B
*** 5
:PROPERTIES:
:ID: ff13f014-3dbc-40e2-8d5c-afdd37461ccc
:END:
**** 对话
***** 转录
女：我觉得你太不重视我的事了。[[file:53ee3bc8-f78e-4565-bce7-b96d1c3c17e9.mp3][(audio)]]
男：一接到你的电话，我就连忙打车过来了，还不重视啊？[[file:7fa40a71-edb3-43ff-a236-712a2c39593b.mp3][(audio)]]
***** 音频
237e8c9f-e4d0-456f-b57f-62e6d641a9c5.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
fa11acbc-33f9-4c58-b44c-176d3cff647d.mp3
**** 选择
***** A
女的的事不严重
***** B
他没有接到电话
***** C
他很重视这件事
***** D
因为他打不到车
**** 答案
C
*** 6
:PROPERTIES:
:ID: 2b345715-d34d-49a6-bac5-b6b65a4b4c1c
:END:
**** 对话
***** 转录
男：高秘书，刘总还在跟小李谈话吗？[[file:53bc729e-e618-4597-9927-50a27849c2ed.mp3][(audio)]]
女：对，气氛好像有点儿紧张，……[[file:39e6acd1-d91a-4b1c-8400-93b820f28290.mp3][(audio)]]
***** 音频
716a831e-6b83-4a55-a1bb-c4e7c9e71414.mp3
**** 问题
***** 转录
女的接下来最可能说什么？
***** 音频
09e996f4-894f-4d8a-a091-d44a5a626a3e.mp3
**** 选择
***** A
你去把他叫出来
***** B
你最好先别进去
***** C
看来他们倓得很愉快
***** D
我可以给他打个电话
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
女：没想到最后是一个小孩子想出了办法。
男：是啊，去掉篮筐的底，这么简单的事，我们怎么都没想到呢？
女：有时候，我们把一些事情想得太复杂了。
男：说白了，我们的思维，都像篮球一样被篮筐的底挡在了半空中。
***** 音频
9ed10bde-c5b0-467e-a026-13310c57681d.mp3
**** 问题
***** 转录
他们在讨论什么话题？
***** 音频
8b87fbbe-fd11-4095-ba99-981d20c31cc9.mp3
**** 选择
***** A
等球
***** B
篮筐
***** C
小孩
***** D
思维
**** 答案
D
*** 8
**** 对话
***** 转录
男：昨天的球赛你看了吗？
女：看了，平安队又赢了。别看他们水平一般，还老赢。
男：是啊，论技术他们真不比对手强，就是运气好。
女：也不完全是运气，队员们的情绪很稳定。
***** 音频
34773823-a36a-445b-9f1b-f519e5cbe529.mp3
**** 问题
***** 转录
男的认为平安队为什么能赢？
***** 音频
40c1f221-ffb4-4511-9c4b-78cfb3f596ae.mp3
**** 选择
***** A
水平高
***** B
运气好
***** C
技术强
***** D
情绪稳定
**** 答案
B
*** 9
**** 对话
***** 转录
女：你怎么精神这么差？
男：这几天总是失眠。
女：是不是工作有压力？情绪紧张容易造成失眠。
男：可能吧，最近太忙了。
***** 音频
3f8b592a-5606-41e1-87ce-c92076ba7044.mp3
**** 问题
***** 转录
男的为什么失眠？
***** 音频
8ce09aad-49ff-4b2b-baed-c9a66fb9fb6a.mp3
**** 选择
***** A
压力大
***** B
失恋丁
***** C
精神差
***** D
有情绪
**** 答案
A
*** 10
**** 对话
***** 转录
男：刘大夫，谢谢您给我开的药，擦了之后很管用。
女：现在好点儿了吗？疼得不那么厉害了吧？
男：好多了。
女：最好还是再休息几天，别急着恢复训练，容易重复拉伤。
***** 音频
1d98bf9d-3662-491d-af8b-33ecef4acf96.mp3
**** 问题
***** 转录
女的建议男的什么？
***** 音频
ee2e7e82-9ead-4752-9138-e6db8c3be3c1.mp3
**** 选择
***** A
绣续吃药
***** B
恢复训练
***** C
回来住院
***** D
继续休息
**** 答案
D
*** 11-12
**** 对话
***** 转录
女：您好，请问参加潜水活动需要满足什么条件？
男：首要条件就是身心健康，否则无法在水中安全活动，因为水压可能会加重某些疾病；心理上也需要克服一些紧张情绪。另外，最好有一定的游泳基础，然后在我们这儿接受潜水训练。
女：对年龄有限制吗？
男：一般没有限制。但我们不建议 8 岁以下的小朋友潜水；高龄者的话，要提供体检证明。
女：好的，谢谢您！
***** 音频
ec963d9e-62b0-418b-b54d-28f25314870e.mp3
**** 题目
***** 11
****** 问题
******* 转录
下列哪项不是参加潜水活动必须满足的条件？
******* 音频
96cf3705-449f-493c-ae6c-53ef64aa55cf.mp3
****** 选择
******* A
身体健康
******* B
心理放松
******* C
游泳技术很好
******* D
接受潜水训练
****** 答案
C
***** 12
****** 问题
******* 转录
关于年龄有什么规定？
******* 音频
0aedb046-fc59-4ab9-b21e-5d11966493f6.mp3
****** 选择
******* A
没有规定
******* B
必须是青少年
******* C
10岁以下不可以潜水
******* D
老年人要提供体检证明
****** 答案
D
*** 13-14
**** 段话
***** 转录
网球起源于法国，现在在欧美已经成为仅次于足球的最受欢迎的体育项目。目前，国际上著名的网球比赛有男子团体戴维斯杯、女子团体联合会杯以及四大单项赛，分别是澳大利亚、温布尔登、法国和美国网球公开赛。网球运动的职业化程度相当高，每年都会举行数十次公开赛或大奖赛，有奖金、有积分，一些网球高手的年收入可达几千万美元。
***** 音频
2413128c-c142-42da-9752-84d9334e36de.mp3
**** 题目
***** 13
****** 问题
******* 转录
根据上文，现在在欧美最受欢迎的体育项目是什么？
******* 音频
4f4fd25b-ed08-49ae-99d3-d0eb0ff9243f.mp3
****** 选择
******* A
足球
******* B
网球
******* C
篮球
******* D
排球
****** 答案
A
***** 14
****** 问题
******* 转录
关于网球，下列哪项不正确？
******* 音频
6219e386-20fb-4d4d-b57d-bf39b2ef0951.mp3
****** 选择
******* A
起源于法国
******* B
在欧美很流行
******* C
有团体赛和单项赛
******* D
选手多数是业余的
****** 答案
D
* 阅读
** 第一部分
*** 课文
*** 题目
**** 15
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 16
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 17
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 18
***** 选择
****** A
****** B
****** C
****** D
***** 答案
** 第二部分
*** 19
:PROPERTIES:
:ID: d4ff9e4d-3d0c-4582-97cf-182be417fe80
:END:
**** 段话
篮球运动是1891年由美国马萨诸塞州的体育教师詹姆士・奈史密斯博士发明的。最初的篮筐下面有底，每当投进球时，就得有一个人踩着梯子上去把球取出来。因此，比赛断断续续，缺少了激烈紧张的气氛。后来，在一个上幼儿园的小男孩的提醒下，人们才想到锯掉篮筐的底部，成为我们今天看到的样子。
**** 选择
***** A
篮球的发明者是英国人
***** B
开始篮球运动水平不高
***** C
上梯子的人是为了站高一点儿
***** D
问题的解决是受小朋友的启发
**** 答案
D
*** 20
:PROPERTIES:
:ID: 7b376f2d-9907-41a9-8a07-a98e912d5f40
:END:
**** 段话
说到乒乓球，很多人马上会想到中国。的确，长期以来，中国的乒乓球水平一直是世界领先。因此，人们常会误以为乒乓球运动最早是从中国开始的。而事实上，这项运动在中国只有70多年的历史，它真正的发源地在英国。19世纪末，英国人吃完饭后想用适当的运动来帮助消化，便发明了一种在饭桌上进行的和网球相似的运动。直到今天，兵乓球的英文名仍然叫作“桌上网球“。
**** 选择
***** A
中国人的乒乓球水平都很高
***** B
五乓球运动是从中国开始的
***** C
最早的乒乓球运动是在饭后进行
***** D
上乓球运动最早是在网球场进行的
**** 答案
C
*** 21
:PROPERTIES:
:ID: b5db3dcc-0824-4a3b-aeaf-144ea34173cb
:END:
**** 段话
作为球迷，莫言十分关注中国足球的发展，他认为，中国球队打进世界杯需要一个漫长的过程，因为中国足球的起步比较晚，目前还不够普及“为什么乒乓球能够出现这么多高手，就在于它有强大的群众基础，有些偏远山区的孩子可能一辈子都踢不上足球“莫言提议，首先要让中国的孩子们都踢上足球，参加的人多了，高手自然会出现。
**** 选择
***** A
莫言是一个足球迷
***** B
莫言认为中国很快能打进世界杯
***** C
偏远山区有较好的足球运动环境
***** D
是否有运动高手与群众基础无关
**** 答案
A
*** 22
:PROPERTIES:
:ID: 5f65d55e-a5c7-44d7-9163-6a527eab4dda
:END:
**** 段话
避免运动过量的办法很简单，就是要控制时间。对于所有运动，一般持续时间最好不要超过一小时。在进行重复性的激烈运动时，应千万小心，例如蹲起等，一定要保持正确的姿势，避免受伤。在运动时最好能够向老师或教练求教，请他们告诉你如何调整动作。
**** 选择
***** A
运动时间不应少于一个小时
***** B
不能进行重复性的激烈运动
***** C
运动姿势不正确时容易受伤
***** D
运动时应注意不断调整动作
**** 答案
C
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
