* 练习

** 1
:PROPERTIES:
:ID: 8c5f471f-6272-4c49-b806-2d8d5e46fbb2
:END:
*** 选择
**** 1
重复
**** 2
造成
**** 3
气氛
**** 4
缺乏
**** 5
仿佛
**** 6
连忙
*** 题目
**** 1
***** 句子填空
今天的晚会你们组织得相当好，[[gap]]搞得轻松愉快。
***** 答案
3
**** 2
***** 句子填空
一觉醒来发现已经8点多了，李阳[[gap]]穿好衣服往公司赶。
***** 答案
6
**** 3
***** 句子填空
他一边听，一边在本子上记着什么，[[gap]]对我的发言挺感兴趣似的。
***** 答案
5
**** 4
***** 句子填空
心理学家指出，一个人的动作或想法，如果[[gap]]二十一天就会形成习惯。
***** 答案
1
**** 5
***** 句子填空
每天大量饮酒确实给我的身体健康[[gap]]了很大的伤害。
***** 答案
2
**** 6
***** 句子填空
在食物[[gap]]的季节，动物为了活下去就只能多睡觉。
***** 答案
4
** 2
*** 1
:PROPERTIES:
:ID: db63548b-c151-4e1b-aca1-2762a42b403d
:END:
**** 句子填空
要整理的东西太多了，你看，这个箱子根本[[gap]]不下。
**** 选择
***** A
装
***** B
安装
**** 答案
A
*** 2
:PROPERTIES:
:ID: e55c7153-f2b8-46a6-a1ee-d0d8ae1c7962
:END:
**** 句子填空
昨晚我失眠了，睡不着就躺着[[gap]]书，结果不知不觉天就亮了。
**** 选择
***** A
瞧
***** B
看
**** 答案
B
*** 3
:PROPERTIES:
:ID: 84198779-439b-4397-b609-7672dc6cea3e
:END:
**** 句子填空
即使在现代社会里，故事仍然是人们生活中不可[[gap]]的一部分。
**** 选择
***** A
缺少
***** B
缺之
**** 答案
A
*** 4
:PROPERTIES:
:ID: e5f229a1-1dad-48f6-8337-b6dfe482b41a
:END:
**** 句子填空
你们知道中国人除夕夜守岁，放鞭炮的风俗是怎么[[gap]]的吗？
**** 选择
***** A
形成
***** B
造成
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
您[[A]]多画点儿画儿多好，[[B]]把时间[[C]]浪费在这些人的身上[[D]]？
**** 词语
何必
**** 答案
B
*** 2
**** 句子
[[A]]年轻人[[B]]恐怕都受不了，[[C]]一个[[D]]有病的老人呢？
**** 词语
何况
**** 答案
C
*** 3
**** 句子
[[A]]你提醒，[[B]]要不[[C]]我肯定忘了[[D]]下午还要开会。
**** 词语
多亏
**** 答案
A
*** 4
**** 句子
[[A]]经历了那件事后，[[B]]我[[C]]一夜之间长大[[D]]成人了。
**** 词语
仿佛
**** 答案
C
* 扩展
** 词语
*** 话题
体育
*** 词语
**** 1
太极拳
**** 2
球迷
**** 3
武术
**** 4
纪录
**** 5
象棋
**** 6
教练
**** 7
对手
**** 8
冠军
**** 9
决赛
** 题目
*** 1
**** 句子
[[gap]]是中国传统的体育项目，[[gap]]是其中重要的组成部分。
**** 答案
***** 1
3
***** 2
1
*** 2
**** 句子
我认识一位大学的体育老师，他[[gap]]下得可棒了。
**** 答案
5
*** 3
**** 句子
打羽毛球你可不是我的[[gap]]，不管打多少场你也赢不了。
**** 答案
7
*** 4
**** 句子
他决心苦练一年，好在下次比赛时打败对方，拿回[[gap]]的奖杯。
**** 答案
8
* 注释
** （三）词语辨析
*** 激烈——强烈
**** 做一做
***** 1
****** 句子
这种蔬菜有[[gap]]的香味，它既可以生吃，又可熟食。
****** 答案
******* 1
******** 激烈
0
******** 强烈
1
***** 2
****** 句子
明天我去一家公司面试，听说竞争很[[gap]]。
****** 答案
******* 1
******** 激烈
1
******** 强烈
0
***** 3
****** 句子
当晚的比赛紧张、[[gap]]，两队都打出了很高的水平。
****** 答案
******* 1
******** 激烈
1
******** 强烈
0
***** 4
****** 句子
学生们[[gap]]要求重新安排考试。
****** 答案
******* 1
******** 激烈
0
******** 强烈
1
* 课文
** 转录
篮球运动是 1891 年由美国马萨诸塞州的体育教师詹姆士·奈史密斯博士发明的。那年的冬天特别冷，奈史密斯所在的训练学校缺乏在室内进行的球类比赛项目，他从当地人把球扔进桃子筐（当地产桃子，各家各户都备有装桃子的专用篮筐）的游戏中得到启发，将两只篮筐分别安装在体育馆两边看台的栏杆上，学生分为甲乙两队，以足球为比赛工具向篮内投，按得分多少决定输赢。
这项运动很快流行起来。不过，由于栏杆上固定的是真正的筐，每当球投进时，就得有一个人踩着梯子上去把球取出来。这样的行为必须一再地重复，为此，比赛不得不断断续续地进行，缺少了激烈紧张的气氛，连运动员都不满意，更何况看比赛的球迷呢？为了解决这个问题，大家纷纷出主意，想出了很多取球的办法。有一位工程师甚至专门制造出一种机器，在下面一拉篮筐就能把球弹出来。可是，这些办法都没能让比赛顺畅起来。
几年后的一天，一个上幼儿园的小男孩跟着父亲从一群正在进行篮球比赛的人旁边经过。看到大人们一次次辛苦地取球，小男孩好奇地问父亲：“何处这么麻烦呢？把篮筐的底去掉不就行了吗 9”多亏了他这句话，人们如梦初醒，一位球员连忙找来一把锯子把篮筐的底锯掉。你瞧，困扰人们很长时间的取球问题就这样被一个小孩子解决了。
去掉篮筐的底，本是一件简单的事，可为什么那么多人都没有想到呢？说白了，因为我们的思维像篮球一样被篮筐的底挡在了半空中。于是，我们呆呆地去搬梯子、造机器……其实，世界上本来就没有太复杂的事，复杂都是我们自己造成的。生活仿佛篮筐，许多时候，我们需要的只不过是一把锯子，来锯掉那些阻碍我们的“筐底”。
