* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: c3ecb3cd-60b3-4253-afd7-9a74582f0ce4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
359af44a-6f5a-4473-a88f-78ae00b9b82e.mp3
***** 转录
游泳是非常有益于健康的体育运动，因为它可以使人体肌肉都得到锻炼。一旦学会了游泳，你将终生不会忘记。它不仅能够在危急的时候挽救你的生命，还是完成许多其他水上运动的前提。
**** 选择
***** A
游泳可以帮助你减肥
***** B
学会游泳后很容易忘
***** C
游泳在危急时能救命
***** D
游泳前应做其他运动
**** 答案
C
*** 2
:PROPERTIES:
:ID: f707cf6d-27ae-45e6-9a83-c78bb55523f3
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
9e7b4601-2bc8-465e-8968-1ca5bc17bfb0.mp3
***** 转录
你在某种运动项目上有着特别的天赋吗？检验一下你最喜欢什么吧。你是喜欢和别人一起运动，还是更愿意独自运动呢？其实哪种方式都没错，你只要记住，胆小鬼可以通过运动变得勇敢，而好动的孩子则可以通过运动发泄精力。
**** 选择
***** A
每人在运动上都有特别的天赋
***** B
和别人一起运动比独自运动好
***** C
胆子小的人通过运动会变得勇敢
***** D
娆动的孩子通过运动能获得精力
**** 答案
C
*** 3
:PROPERTIES:
:ID: 19455c56-746c-4f0c-8314-645450a11efa
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
82f03f23-26d2-424d-9c34-09f24a9c6d69.mp3
***** 转录
田径运动包括下列人类最原始的运动：走、跑、跳、投和推。十项全能运动员是田径运动员中的“王者”，他们要按顺序参加十个指定田径项目的比赛。在两天的竞技中，他们要分别在赛跑、跳跃和投掷项目中赛出自己的最佳成绩。
**** 选择
***** A
田径运动是人类发展最快的运动
***** B
十项全能比赛的项目主要是赛跑
***** C
十项全能运动员自选十个项目比赛
***** D
十项全能运动员要参加两天的比赛
**** 答案
D
*** 4
:PROPERTIES:
:ID: c1ef0486-0d7f-43b1-ac9e-08c192e32820
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
2ae751cc-f387-4b50-9fad-c04913b620f9.mp3
***** 转录
所有的运动员，无论是大人还是小孩，在运动中有了诸如进球或者跑了第一名这样的精彩表现后，都会非常兴奋。但是他们如果没能实现自己的目标，就会感到失望。那么，运动带给人们的究竟是愉悦还是痛苦呢？可能只有身在其中的人才会有发言权吧。
**** 选择
***** A
运动员有了精彩表现后会很兴奋
***** B
运动员一般都是为了娱乐而运动
***** C
每个人都应选择自己喜欢的运动
***** D
运动的目的是在竞争中嬴得比赛
**** 答案
A
*** 5
:PROPERTIES:
:ID: 4e75f4bf-87f1-4e20-8bfe-e5464f5ce61d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
11477f10-496f-4627-8891-a362c1190c94.mp3
***** 转录
体操运动员特别敏捷，他们所完成的动作需要巨大的力量。有时他们在蹦床上练习，蹦床的弹性特别强，运动员会被弹到空中非常高的地方。顶级的体操运动员在学习复杂的动作时，都会训练几千遍。只有这样，他们才能在难度极高的动作中保持最完美的姿态。
**** 选择
***** A
体操运动员的身体弹性特别强
***** B
体操运动员需要很大力量完成动作
***** C
体操运动员比赛时常被弹到非常高的地方
***** D
体操运动员的动作在比赛中要保持很长时间
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: ce5e337d-50a6-46f9-a754-f1f1760d0480
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
d6c80d7a-2aa4-4c4b-80dd-539599ef67cb.mp3
***** 转录
女：观众朋友，今天来到现场的是著名跨栏王子——刘翔，他在雅典奥运会上顽强拼搏，最后夺得了 110 米栏冠军。今天请刘翔跟我们聊聊他在运动场之外的生活。
男：大家好，很高兴跟大家分享我生活中的点点滴滴。
女：刘翔，大家都知道你的成功来之不易，在你成功的背后，在塑胶跑道之外，你的业余生活怎么样？
男：我爱好上网，每次结束上午的训练课，回到宿舍，随便把跑鞋一扔，直接冲到电脑前，有时甚至门钥匙都忘了拔。
女：那你上网主要干什么呢？
男：主要看体育新闻，因为必须掌握更多对手的战术等信息才能百战不殆。除了体育，我也关心一些国内、国际上新发生的大事，我喜欢接触各种事物。
女：除了上网，你还有别的爱好吗？
男：我喜欢唱歌，而且唱的还不错，什么陶喆、阿杜，我都会模仿，大家都说模仿的还挺像。
女：那晚上你一般做什么？
男：晚上 7 点以后，我一般会到医务室按摩。大家都知道，好成绩与科学正规的训练和恢复是相辅相成的。
女：听说只有你有优先按摩权，只要你去了，别的队友必须马上让开，因为大赛在即，必须保证你的身体不出意外，是这样吗？
男：这可是舆论冤枉我了，事实不是这样的，竞赛是残酷的，可大家的友谊却是温暖的。大家练得都很苦，我从来没享受过这种特权。不能因为我有点成绩就骄傲，我会选择在赛场上去征服每一个对手和观众。
**** 题目
***** 6
:PROPERTIES:
:ID: 35143aca-0584-40dd-9244-d1d8cf55b90c
:END:
****** 问题
******* 音频
cef3c530-c898-48e5-b3df-cdebc660c4aa.mp3
******* 转录
刘翔是什么项目的冠军？
****** 选择
******* A
 400米接力比赛
******* B
 100米短跑比赛
******* C
 110米跨栏比赛
******* D
 10000米长跑比赛
****** 答案
C
***** 7
:PROPERTIES:
:ID: 0296d72d-0246-4e99-8637-7b6a41e56720
:END:
****** 问题
******* 音频
e6024a4b-8af6-4f11-847d-2ae9dbf902ca.mp3
******* 转录
刘翔为什么有时候门钥匙都不拔？
****** 选择
******* A
刘翔的宿舍很安全
******* B
刘翔生活中很马虎
******* C
刘翔特别喜欢上网
******* D
刘翔非常喜欢听歌
****** 答案
C
***** 8
:PROPERTIES:
:ID: fb00012e-ee3f-4627-bd47-d12d95b8d833
:END:
****** 问题
******* 音频
b16caddc-c432-4102-a01e-dbc172711744.mp3
******* 转录
刘翔为什么喜欢看体育新闻？
****** 选择
******* A
掌握对手信息
******* B
了解社会新闻
******* C
了解经济情况
******* D
关注国内外大事
****** 答案
A
***** 9
:PROPERTIES:
:ID: 4d9a4908-e1c8-4f08-9c58-5acf1e6ce661
:END:
****** 问题
******* 音频
a229d238-af40-4a15-9ac6-ae6f7577b5cd.mp3
******* 转录
主持人说刘翔享有的特权是什么？
****** 选择
******* A
队友必须为他服务
******* B
他能优先接受按摩
******* C
他能优先使用训练场
******* D
他能任意挑选按摩师
****** 答案
B
***** 10
:PROPERTIES:
:ID: 3b43b890-9553-4c81-aff0-8cf764be8fcf
:END:
****** 问题
******* 音频
07b4ee8f-59e2-4fbb-942e-f51451c4b8fc.mp3
******* 转录
根据本文，刘翔和队友的关系怎么样？
****** 选择
******* A
有矛盾
******* B
挺友善
******* C
很冷淡
******* D
比较一般
****** 答案
B
** 第三部分
*** 11-13
:PROPERTIES:
:ID: f11c08e4-600f-4881-a00b-804821bd44a9
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
026ab3e7-f301-42c5-9389-473333448903.mp3
***** 转录
跑步、跳跃和投掷是人类最古老的运动。我们如今刻苦训练的这些技能，其实都是原始人生存的必备能力。原始人只有利用他们的技巧、力量、速度和耐力，才能找到食物或抵御危险，才能在冷酷的环境中生存下去。
你能站在一艘狭窄又摇晃的小船里，用弓箭射鱼吗？如今，在非洲和南美洲的原始森林中，还有一些人保留着几千年前的生活方式。他们从小就在不知不觉中学会了以“运动的方式”应对周围环境的变化。
可是现在的我们，大多数时间几乎都静坐不动：在学校里、在电视机前、在电脑前、在汽车里或是工作中……长此以往，我们不生病才怪呢！因此，为了保证健康，我们必须注重体育锻炼。
你知道吗？当你感觉无聊，或是又困又乏，对什么都没兴趣的时候，出去大玩儿一场或者近似疯狂地运动一通，就可以摆脱这种状态。当然，最重要的是你要接触新鲜空气：不管是和朋友在一起，还是在社团或者在学校里。
**** 题目
***** 11
:PROPERTIES:
:ID: 60824ff9-03c5-4497-88e1-b7392bf967ec
:END:
****** 问题
******* 音频
84d395cf-f989-4234-9c9b-89fee6616c24.mp3
******* 转录
我们现在刻苦训练的运动技能，对原始人来说是什么？
****** 选择
******* A
保持健康的方式
******* B
结交朋友的途径
******* C
生存的基本能力
******* D
自娱自乐的方式
****** 答案
C
***** 12
:PROPERTIES:
:ID: ff3dedaf-eae6-4164-8058-05f8ed9c1f22
:END:
****** 问题
******* 音频
9fe81823-2437-4ce9-a664-d4d2ac87c871.mp3
******* 转录
关于非洲和南美洲的原始森林，下列哪项正确？
****** 选择
******* A
那里的人驾船的本领很高
******* B
那里的人喜欢用弓箭捕鱼
******* C
那里的人个个都是运动高手
******* D
那里还存在着古老的生活方式
****** 答案
D
***** 13
:PROPERTIES:
:ID: a260efbc-7ae6-45e8-9e13-2b9a0acbc866
:END:
****** 问题
******* 音频
c440243c-a1d2-41cc-8c3d-e8f847a42a25.mp3
******* 转录
根据本文，要摆脱无聊状态，最重要的是什么？
****** 选择
******* A
出门去旅行
******* B
疯狂地工作
******* C
坚持体育锻炼
******* D
去呼吸新鲜空气
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: eda8a87b-82ad-4025-bc72-d2a2b9578130
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
f93f42e4-1e76-4495-94de-076ecee0c29b.mp3
***** 转录
每隔四年，来自全世界的运动员都会在奥运赛场上相会，而各个国家的体育迷们都会守在电视机前关注直播的赛事，为自己的同胞们加油，奥运会的胜利者也将成为顶级明星。古代奥运会的冠军会得到橄榄枝花环，而如今获得比赛冠军、亚军、季军的选手则会分别得到金、银、铜牌。
奥运五环代表了五大洲之间的友谊。比赛期间，奥运圣火将一直在奥运主赛场上熊熊燃烧。
古希腊的选手们很早之前就已经在为夺取胜利而竞争了。在奥林匹亚，赛跑和摔跤成为最古老的比赛项目。那个时候，古希腊城邦之间经常会爆发战争，但在奥运会期间，战争必须停止。
这项盛大的赛事是古希腊最受欢迎的活动，每次比赛都会引来无数观众观看。
**** 题目
***** 14
:PROPERTIES:
:ID: e9dc0b7a-5dd8-4c5d-9fb7-957f061a1781
:END:
****** 问题
******* 音频
feb11134-3c32-4d0d-8157-6b0d59161b6c.mp3
******* 转录
奥运会期间，体育迷们会做什么？
****** 选择
******* A
参加比赛
******* B
关注赛事
******* C
出门旅行
******* D
成为明星
****** 答案
B
***** 15
:PROPERTIES:
:ID: 6b9887f0-c4d2-4d54-9b02-4394cb931c0d
:END:
****** 问题
******* 音频
df079ca5-0f95-469b-94b5-1e67b28e9ba2.mp3
******* 转录
现代奥运会的季军会收获什么？
****** 选择
******* A
花环
******* B
金牌
******* C
银牌
******* D
铜牌
****** 答案
D
***** 16
:PROPERTIES:
:ID: 0e7fab59-6eab-4063-9e04-9a0a7f633579
:END:
****** 问题
******* 音频
e0ad34eb-49f2-4773-9d63-93e7119faccf.mp3
******* 转录
奥运五环代表了什么？
****** 选择
******* A
五个古老的项目
******* B
五位奥运会冠军
******* C
熊熊燃烧的圣火
******* D
五大洲之间的友谊
****** 答案
C
***** 17
:PROPERTIES:
:ID: 97c7a511-a348-484b-a64d-edb3c3ff40c7
:END:
****** 问题
******* 音频
f96b795d-2412-42d9-9cac-5157dfca2354.mp3
******* 转录
在古希腊，奥运会期间，城邦之间会怎么样？
****** 选择
******* A
爆发战争
******* B
停止战争
******* C
转流举办奠运会
******* D
举行盛大的欢迎活动
****** 答案
B

* 阅读
** 第一部分
*** 18
**** 句子
***** A
后来她不知不觉睡着了，不知多长时间睡觉。
***** B
她聪明而任性，常常为一点点小事和同学争执、赌气。
***** C
经济学家往往迷信数字，什么利润率多少、GDP多少等。
***** D
学生的心理发展还远没有达到极限，还可能有更大的发展。
**** 答案
*** 19
**** 句子
***** A
作文比赛的报名时间下周末下午截至。
***** B
我们应该把整个任务分解成若干小项目。
***** C
《史记》最后一篇中引用了司马谈的文章。
***** D
这项社会工程需要动员各方面的力量参与。
**** 答案
*** 20
**** 句子
***** A
这篇文章论点鲜明、论述详尽，从人口的角度给出了地方政府的最优管辖范围。
***** B
我们不能把引人竞争机制当作一句空话，领导干部的公开选拔也是引人竞争机制的做法。
***** C
上个星期跟朋友慕名参观了郊外的一处景点，那儿小巧精致，范围不大，我三个小时才看完。
***** D
我们应尽量避免因电脑出现故障而丢失未能保存的内容，所以在用电脑工作时应及时保存文件。
**** 答案
** 第二部分
*** 21
**** 段话
[[gap]]你没有梦想过成为足球明星或职业网球选手，体育运动对你来说也仍然十分重要。如果能有[[gap]]地活动你的运动器官一一骨骼、肌肉、韧带、肌腱和所有大大小小的关节的话，你就会变得灵巧而敏捷。体育运动可以强健你的心脏和血液循环系统，还可以[[gap]]大脑的氧气供应。
**** 选择
***** A
****** 1
不管
****** 2
规定
****** 3
改变
***** B
****** 1
即使
****** 2
规律
****** 3
改善
***** C
****** 1
因为
****** 2
规则
****** 3
改革
***** D
****** 1
一且
****** 2
规范
****** 3
改掉
**** 答案
*** 22
**** 段话
在网球、乒乓球和羽毛球比赛中，选手要[[gap]]通过技巧将球打过网，打在对方的界内，并使对方[[gap]]不到球或在回击时出现失误。哪一方将球打到网上或是打到界外，就[[gap]]对方得分。网球选手发球时，球的速度能达到赛车的速度！而对方选手必须快速地[[gap]]脚步，做出如闪电般迅速的回应。
**** 选择
***** A
****** 1
尽管
****** 2
抓
****** 3
为
****** 4
转移
***** B
****** 1
随意
****** 2
拿
****** 3
认
****** 4
转换
***** C
****** 1
尽量
****** 2
接
****** 3
算
****** 4
移动
***** D
****** 1
尽快
****** 2
扔
****** 3
给
****** 4
运动
**** 答案
*** 23
**** 段话
F1赛车手一般都是体魄[[gap]]的运动员，因为F1赛车的驾驶[[gap]]和车手所必须经受的强大离心力，跟驾驶一般车辆相差悬殊。赛车手不仅体能状态要[[gap]]常人，更要有沉着、冷静的[[gap]]。而东身体的耐热性对F1车手也是很重要的。
**** 选择
***** A
****** 1
强健
****** 2
方式
****** 3
优于
****** 4
头脑
***** B
****** 1
强大
****** 2
方法
****** 3
高于
****** 4
脑力
***** C
****** 1
坚强
****** 2
办法
****** 3
长于
****** 4
精力
***** D
****** 1
顽强
****** 2
形式
****** 3
大于
****** 4
脑袋

**** 答案
** 第三部分
*** 段话
来到新西兰后，学校希望每一个学生都能够在课余按照自己的喜好选择一两项运动。这不属于必修的课程，完全属于课后的休闲娱乐，许多同学都放弈了选择的机会，我倒是觉得既然能有多达17种运动项目供我选择，[[gap:24]]？于是我选择了击剑。
周二下午，老师通知我到休育馆参加首次训练，不需要任何装备，也不需要任何准备。教练是一位和蔼可亲的女士，叫戴安。[[gap:25]]，并说当年中国选手获得过奥运会冠军，相信我也可以荻得好成绩。与国内直接进行技术和体能训练的教育不同，她首先让我了解击剑的发展史。熟悉了基本规则之后，[[gap:26]]。让我吃惊的是，刚刚参加了两次训练，戴安就安排我参加了一次演习赛，[[gap:27]]。大概是初生牛犊不怕虎吧，我只用了15分钟就以5：1拿下了比赛。[[gap:28]]，也指出了我进攻时暴露的问题。首次比赛的成功对我以后的练习是个很大的动力。
*** 选择
**** A
赛后戴安对我大大代奖了一番
**** B
她首先对我表示欢迎
**** C
对手是一个已经学习击剑两年但年龄比我小3岁的男孩儿
**** D
何不尝试一下呱
**** E
我便开始在她的指导下循序渐进地进行步伐、动作训练

*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
训练场上有人哭着骂他是“魔鬼”；生活中，大家说他像父亲般慈爱。他就是女子曲棍球队的“金牌教练”一一金教练。
刚指导这支球队时，金教练很快就准确地抓住了制约球队进步的主要问题一一体能。为此，他制定了一套严格的训练计划。他在训练中十分严厉。每天训练结柬后，女队员们的两条腹都累得迈不上楼梯。这种超极限的“魔鬼式”训练，强度起码超出以往3倍，于是有的队员哭过、骂过，但姑娘们都是好样的，她们依托良好的身体素质，很快就适应了，同时还锻炼了自己不向囱难届服的意志品质和力争上游的拼搏精神。姑娘们发现，要求队员做到的，金教练自己一定先做到。每次训练，他都提前10分钟到达场地，他也严禁其他教练和工作人员迟到。金教练的腰有旧伤，一犯起来就会全身疹得起不了床，但当腰疹时他硬是让人把他扶到训练场坚持训练。
空洞的说教是打动不了队员的，金教练用自己的行动赢得了姑娘们的信任。即使是哭着骂过金教练是“魔鬼”的姑娘，也觉得训练场外的教练慈祥如父。队员有伤、有病，教练胡起来就往医院送。比赛奖励给教练的奖金，他都拿出来给队员买营养品。他把每个队员的生日都抄下来贴在宿舍的塌上，到时就亲自为队员过生日。
在一次重大赛事中，球队取得了盼望已久的胜利。姑娘们欢呼着奔向金教练，自发地把手中的鲜花举到教练胸前。金教练沉默了许久，望着这一个个熟悉的身影，他的双眼模糊了。
**** 题目
***** 29
****** 问题
关于多年前的那场NBA决赛，下列睑项正确？
****** 选择
******* A
当时皮蓬还是个新手
******* B
乔丹一个人得丁36分
******* C
之前乔丹一直得分最高
******* D
这场比赛对公牛队很重耍
****** 答案
***** 30
****** 问题
第3段画线词语“明知故问”的意思是什么？
****** 选择
******* A
有不明白的，就要问人
******* B
明明知道，还故意问人
******* C
因为不明白，所以要问
******* D
问了，就什么都明白了
****** 答案
***** 31
****** 问题
乔丹认为皮蓬三分球比自己投得好的理由是什么？
****** 选择
******* A
皮造在气势上占优势
******* B
皮莹技术好，还很谦虚
******* C
自己命中率高纯属偶然
******* D
皮莹有得天独厚的天赋
****** 答案
***** 32
****** 问题
根据上文，下列睇个词形容乔丹最适合？
****** 选择
******* A
胸怀坩荡
******* B
目光如炬
******* C
化敌为友
******* D
心直口快
****** 答案
*** 33-36
**** 段话
在多年前的一场NBA决赛中，新秀皮蓬独得33分，超过乔丹3分，成为公牛队中比赛得分首次超过乔丹的球员。比赛结束后，乔丹与皮蓬紧紧拥抱，两人汨光闪闪。
这里有一个乔丹和皮蓬之间鲜为人知的故事。当年公牛队涌现出的众多新秀中，皮蓬是最有希望超越队友乔丹的，他时常流露出一种对乔丹不屑一顾的神情，还经常说乔丹某方面不如自己，自己一定会把乔丹推倒之类的话。但乔丹并没有把皮蓬当作潜在的威胁而排挤他，反而对他处处加以鼓励。
有一次，乔丹对皮蓬说：“我俩的三分球谁投得好7”皮蓬有点儿心不在焕地回答：“你明知故问，当然是你。”因为那时乔丹的三分球命中率是28.6％，而皮蓬是26.4％。但乔丹微笑着纠正：“不，是你！你投三分球的动作很规范、自然，有得天独厚的天赋，以后一定会投得更好，而我还有很多弱点。”他说：“我扣篮多用右手，习惯用左手帮一下，而你，左右都行。”这一细节连皮莹都不知道，他深深地为乔丹所感动。
这件事成了两人关系的转折点，从那以后，皮蓬和乔丹成了最好的朋友，皮莹也成了公牛队17场比赛得分首次超过乔丹的球员。而乔丹的这种品质则为公牛队注人了难以击破的谎聚力，从而使公牛队创造了一个又一个神话。乔丹不仅以球艺，更以他那坦荡无私的广阑胸襟赡得了所有人的拥护和尊重，包括他的对手。
**** 题目
***** 33
****** 问题
有人骂金教练是“魔鬼”，是因为：
****** 选择
******* A
他的品质有问题
******* B
他的要求太严格
******* C
他的长相太可怕
******* D
他的态度太凶恶
****** 答案
***** 34
****** 问题
制约那支球队进步的主要问题是什么？
****** 选择
******* A
体能
******* B
意志
******* C
精神
******* D
战术
****** 答案
***** 35
****** 问题
训练场外的金教练是个什么样的人？
****** 选择
******* A
很认真
******* B
很慈祥
******* C
十分严厉
******* D
也像魔鬼
****** 答案
***** 36
****** 问题
文中“......这一个个熟悉的身影”指的是：
****** 选择
******* A
其他教练
******* B
工作人员
******* C
球队队员
******* D
教练的家人
****** 答案
* 书写
** 文章
有一个叫菲尔德的商人，一次偶然的机会，在农夫巴敼勒斯家里吃到了一种番茄酱，那鲜美的味道，令他赞美不已。出于商人的本能，菲尔德决定向巴勒斯讨要制作番茄酱秘方。巴勒斯几乎未加任何考虑，便将番茄酱的制作方法告诉了他。临走时，菲尔德给了巴勒斯100美元，作为购买番茄酱秘方的费用。巴勒斯一再拒绝，可菲尔德还是将钱塞给了巴勒斯。
就这样，菲尔德开始了番茄酱的生产，不出所料，番茄酱的销量果然很好，菲尔德很快便成了百万富翁。就在菲尔德准备扩不生产的时候，突然在街头看到了一张小广告。菲尔德大吃了一惊，原来那是农夫巴勒斯寻找自己的广告，广告上说，如果菲尔德看到了这张广告，希望立即跟自己联系。
菲尔德想，巴勒斯肯定是来要钱的！当初自己用100美元购买的番茄酱秘方，转眼让自己变成了百万富翁，巴勒斯一定是后悔了。那么，他究竟想要多少钱？弄不好，巴勒斯还会要求自己停止生产，或者跟自己打官司。
为了躲避巴勒斯，菲尔德忍痛将茄酱厂一再搬迀，销售范围也一缩再缩。可是巴勒斯寻找他的小广告，仍然随时出现，菲尔德终于经不住折腾而破产了。
气急败坏的菲尔德决定去找巴勒斯算账，他想知道，巴勒斯究竟想要干什么！当菲尔德出现在巴勒斯面前的时候，巴勒斯就像遇到了久违的亲人一样，高兴地说：“我终于找到您了！”菲尔德气急败坏地说：“你找到我了，可我没有钱给你。”巴勒斯愣了一下，钱还给您。“菲尔德不解地问：”这不是我购买番茄酱的秘方的费用吗？“巴勒斯说：”是的但我不收您的钱，如果我因为这么点儿小事就收您的钱，邻居们会耻笑我的！“
菲尔德苦笑着问：”如果我一直不出现呢？“巴勒斯坚定地说：“那我就继继继续找下去，直到将钱还给您为止，这可是我们乡下人做人的原则！”
