* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 464c94f9-5a80-4813-b4b0-1ffd112a27f7
:END:
**** 对话
***** 转录
女：你家院子里种了些什么？[[file:7dfeb82e-91dd-4bbe-b3a8-6e5c7a5c3c6b.mp3][(audio)]]
男：有花，有竹子，而且我们还养了几条金鱼。[[file:68ae12c8-878c-4178-ad2a-cba723942f05.mp3][(audio)]]
***** 音频
a4115479-2f71-4f07-913c-0eb4857eaca4.mp3
**** 问题
***** 转录
他家院子里没有什么？
***** 音频
eb6ffb42-1d2d-43c6-afc4-f542ca76477a.mp3
**** 选择
***** A
花
***** B
草
***** C
竹
***** D
鱼
**** 答案
B
*** 2
:PROPERTIES:
:ID: f9905260-4030-4ada-9fd7-e695aa7c3920
:END:
**** 对话
***** 转录
男：这就是我们家乡的标志性建筑。[[file:2f47977c-2bb3-4ad4-a389-0c8d1cc4a1b2.mp3][(audio)]]
女：那咱们在这儿合张影留作纪念吧，毕竟我来旅游了一趟。[[file:3bd484fe-7dbb-493b-887d-787a8978694b.mp3][(audio)]]
***** 音频
a7211382-cb5c-4751-aa34-97ccc0b2dc74.mp3
**** 问题
***** 转录
他们现在在哪儿？
***** 音频
aad89eb7-5ac6-4254-bfc9-7cb037a16a5b.mp3
**** 选择
***** A
男的的家乡
***** B
女的的家乡
***** C
旅游目的地
***** D
男的的家
**** 答案
A
*** 3
:PROPERTIES:
:ID: bc719cb6-71ef-453a-8288-02bc048b120c
:END:
**** 对话
***** 转录
女：关于新产品，你有什么看法？[[file:b96d696b-cc59-4f46-9630-866facc48383.mp3][(audio)]]
男：相对而言，如果定价不能太高的话，我觉得功能比形式重要。[[file:ac9b604e-439f-4f8b-9e04-13ca041177cb.mp3][(audio)]]
***** 音频
629b6103-61be-4103-a372-fff9fae410f4.mp3
**** 问题
***** 转录
男的更重视什么？
***** 音频
7179350a-c10d-49a0-9ebb-925a8102234e.mp3
**** 选择
***** A
看法
***** B
价格
***** C
形式
***** D
功能
**** 答案
D
*** 4
:PROPERTIES:
:ID: 26ae0dfb-433c-445c-9680-49385a80a287
:END:
**** 对话
***** 转录
男：这些建筑已经有三百多年历史了。[[file:4101b1d8-9ed7-462f-9f9d-44b1b9e4e141.mp3][(audio)]]
女：历史这么长，规模这么大，还能保存完好，真是太不容易了。[[file:4b553e93-68f8-4764-9676-6dec7185ee35.mp3][(audio)]]
***** 音频
aa459e66-afec-40e1-ba28-5cd555108beb.mp3
**** 问题
***** 转录
女的觉得这些建筑怎么样？
***** 音频
044ff66e-9835-4279-99c3-b5e08b332086.mp3
**** 选择
***** A
历史不长
***** B
风格多样
***** C
规模很大
***** D
被破坏了
**** 答案
C
*** 5
:PROPERTIES:
:ID: e2e94ee5-20ec-4729-adae-3df9afc7c0d3
:END:
**** 对话
***** 转录
女：这就是你所谓的营销方案——出去发发小广告？[[file:c120c657-c5c7-408b-b6bb-f48bde536c73.mp3][(audio)]]
男：别小看小广告，它作用大着呢。[[file:bb57f1b4-e8e6-4d40-acd7-49dc4f03e9bc.mp3][(audio)]]
***** 音频
0cfb5793-6757-4f35-ba9a-4e406576eb09.mp3
**** 问题
***** 转录
听了男的的话，女的是什么反应？
***** 音频
6c07abc0-fb25-4d9e-a022-3d2844c62cb4.mp3
**** 选择
***** A
看不起
***** B
受不了
***** C
舍不得
***** D
忍不住
**** 答案
A
*** 6
:PROPERTIES:
:ID: 5179f447-6236-49a9-a6ac-d853dd2c74d7
:END:
**** 对话
***** 转录
男：这是我第一次负责接待这么大的一个代表团，有点儿紧张。[[file:b17a3fb4-e09d-476a-ae31-2d92f2ab88eb.mp3][(audio)]]
女：没事，大家都是这么过来的。[[file:4c578dcf-e77d-41dc-b94b-02dc87e51a8c.mp3][(audio)]]
***** 音频
93247f56-705b-4637-b97e-8b105bd00f12.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
abd799df-0662-4618-a8c7-26ce6ced1527.mp3
**** 选择
***** A
我可以帮你
***** B
都有第一次
***** C
这个团不重要
***** D
他们明天才过来
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
女：您太客气了，出去旅行还想着给我们带礼物。
男：这是当地最有名的小吃，大家都尝尝。
女：您对济南印象怎么样？
男：历史悠久，风景优美，是个好地方。
***** 音频
7b061f60-0d54-4183-8d6c-618cc2d4c557.mp3
**** 问题
***** 转录
男的为什么要带礼物？
***** 音频
ac368363-3c65-4154-b014-b70ce59d5d4e.mp3
**** 选择
***** A
他出差丁
***** B
他去旅行了
***** C
这些小吃很贵
***** D
他对济南印象很好
**** 答案
B
*** 8
**** 对话
***** 转录
男：你觉得这台空调怎么样？
女：功能倒是挺强大，价钱也便宜。
男：那就买这个吧？
女：但是这个样式，好像不太适合我们家的装修风格。
***** 音频
58e3a35f-1214-496f-a355-3dc036e411d4.mp3
**** 问题
***** 转录
女的对什么不满意？
***** 音频
18288f55-68a6-4a1d-b1c1-3eb35494fcfe.mp3
**** 选择
***** A
功能
***** B
价格
***** C
样式
***** D
装修
**** 答案
C
*** 9
**** 对话
***** 转录
女：终于搬进新家了！
男：从平房到楼房，条件是好了，但邻里关系没有以前那么密切了。
女：这有什么关系？再说跟以前的邻居也不是没矛盾。
男：我还是挺喜欢院子里的那种气氛。
***** 音频
00bcbf92-b38a-47f9-9a76-eac5b845befa.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
98a2528e-3c9a-4f5c-819c-e471b6cdb4b0.mp3
**** 选择
***** A
住平房更方便
***** B
新房条件不好
***** C
跟邻居间有矛盾
***** D
希望邻里关系好
**** 答案
D
*** 10
**** 对话
***** 转录
男：他三年就打下这么大一片市场，真是没想到。
女：是啊，听说他还没有任何背景，都靠自己。
男：对，完全是白手起家。
女：真是创造了一个奇迹。
***** 音频
e0e498de-3bda-46de-b5cf-400266e8429f.mp3
**** 问题
***** 转录
“白手起家”的意思可能是什么？
***** 音频
08d6268c-04a0-4caa-a440-4df853e886ea.mp3
**** 选择
***** A
用手制作产品
***** B
打下很大市场
***** C
没有经济支持
***** D
创造一个奇迹
**** 答案
C
*** 11-12
**** 对话
***** 转录
女：什么是四合院？
男：四合院是中国华北地区民居中的一种建筑形式。
女：我的意思是问为什么叫“四合”院。
男：“四”指东、西、南、北四面，“合”就是四面房屋围在一起，中间形成一个方形的院子。
女：哦，谢谢你，我明白了。
***** 音频
03da5cb8-dca2-4c85-9182-3b138b3c1bc8.mp3
**** 题目
***** 11
****** 问题
******* 转录
四合院主要分布在中国什么地方？
******* 音频
cc535589-96a2-4434-bcf8-6269c7e9cadc.mp3
****** 选择
******* A
西北
******* B
华南
******* C
华北
******* D
东南
****** 答案
C
***** 12
****** 问题
******* 转录
“四合院”中的“合”是什么意思？
******* 音频
a0023984-d2dd-477a-a2de-8fd6a5fabe7a.mp3
****** 选择
******* A
房屋围在一起
******* B
四面都有房屋
******* C
只有一个院子
******* D
是一种建筑群
****** 答案
A
*** 13-14
**** 段话
***** 转录
为什么明清时期描写北京历史风貌的文章，作者多数是外地人，特别是江南人呢？因为那时北京已成为全国的首都，有识之士纷纷从外地来到北京，这里的宏伟建筑、优美风光深深地吸引着他们，使他们耳目一新。这些人心有所感，自然要用笔记录下来。至于为什么北京人自己写得少，这恐怕与他们自小生活在这里，对各种事物都习以为常有关，并不等于北京本地缺少才子。
***** 音频
0d029a52-0846-4202-9506-53147b64980d.mp3
**** 题目
***** 13
****** 问题
******* 转录
为什么描写北京的文章，多数是外地人写的？
******* 音频
9884daf6-8652-4d47-b76e-eb61486282e4.mp3
****** 选择
******* A
北京缺少才子
******* B
北京没什么风景
******* C
北京人不爱写文章
******* D
外地人容易发现新奇的东西
****** 答案
D
***** 14
****** 问题
******* 转录
根据这段话，下列哪项正确？
******* 音频
ccf237e6-957d-4764-ab9e-6595bd5c1744.mp3
****** 选择
******* A
以前北京的建筑物很少
******* B
在北京的外地人都是江南人
******* C
北京人一辈子都不愿意离开家乡
******* D
北京在明清时期已经是中国的首都
****** 答案
D
* 阅读
** 第一部分
*** 段话
钱钟书先生初到清华时在外文系授课，有时在家批阅学生的试卷，让女儿钱瑗帮助记成绩。一次，钱瑗没头没脑地对爸爸说：“英若诚跟吴世良要好，他们是朋友。“钱先生说：“你怎么知道？“钱瑗指指课卷：“是墨水[[gap][15]]出来的：你看，全班学生的课卷都是用蓝墨水写的，只有他俩用的紫墨水。
“[[gap][16]]，英若诚和吴世良同是戏剧爱好者，同是清华骆驼剧团的演员，共同主演过俄罗斯拉夫列尼约夫的小说改编的戏剧《第四十一》英若试演被俘的白俄军官，吴世良[[gap][17]]“演押送他的红军女战士。两人从清华升业后，一起去了北京人民艺术剧院，结为夫妻，相潘以沫、风雨同舟地过了[[gap][18]]
*** 题目
**** 15
***** 选择
****** A
告诉
****** B
说明
****** C
显示
****** D
显得
***** 答案
C
**** 16
***** 选择
****** A
她猜得没错
****** B
他们都知道
****** C
事情并不是这样
****** D
没有想到的是
***** 答案
A
**** 17
***** 选择
****** A
而
****** B
却
****** C
倒
****** D
则
***** 答案
D
**** 18
***** 选择
****** A
一会儿
****** B
一辈子
****** C
一下子
****** D
一阵子
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 35c6ca27-33e9-48ea-aaa9-fbb1bead38cb
:END:
**** 段话
四合院的大门一般开在东南角或西北角，院中的北房是正房，比其他房屋的规模大，一般包括长辈的卧室和具备日常起居、接待客人等功能的客厅。院子的两边是东西厢房，是晚辈们生活的地方。在正房和厢房之间建有走廊，可以供人行走和休息。
**** 选择
***** A
四合院的大门一般在南面
***** B
正房和厢房之间是不相通的
***** C
东西厢房一般包括卧室和客厅
***** D
通常长辈住北房，晚辈住东西厢房
**** 答案
D
*** 20
:PROPERTIES:
:ID: 8172e754-7d23-42d0-9cbf-87a07651b266
:END:
**** 段话
中国正在步人老龄化国家的行列，因此，“银发住宅“的设计成为市场关注的新热点。为了适应目前和未来中国家庭“421“的基本结构，银发住宅应设计得既便于老人与子女孙辈团聚，居住空间又相对独立。
**** 选择
***** A
“421“家庭包括祖孙三代
***** B
“银发住宅“必须让老人和孩子住在一起
***** C
“银发住宅“主要是为中年人设计的住宅
***** D
“银发住宅“出现的主要原因是中国社会的年轻化
**** 答案
A
*** 21
:PROPERTIES:
:ID: 67181845-d3d7-47d5-bbdb-6ba19d34efc5
:END:
**** 段话
人们常用“诗情画意“四个字来形容中国的传统园林。这个评价有两层意思：一是说园林中的风景自然如画，二是说园林的设计体现了诗歌一般的情感。这确实说明了古代园林与山水诗、山水画的共同之处，它们都以表现自然美为主题，与西方几何规则式园林有明显的区别。
**** 选择
***** A
中国古代园林的设计者都是诗人
***** B
中国很多园林是根据山水画设计的
***** C
中国古代园林非常注重表现自然美
***** D
中国园林比西方园林更讲究规则有序
**** 答案
C
*** 22
:PROPERTIES:
:ID: 71ae66b5-a7c2-4f63-888d-27e60e3df886
:END:
**** 段话
钟鼓楼是坐落在北京市南北中轴线上的一组古代建筑，位于东城区地安门外大街北端。作为元、明、清代都城的报时中心，它是全国重点文物保护单位。两楼前后纵置，气势雄伟，巍峨壮观，是古代劳动人民智慧与力量的结晶。钟鼓楼与周边形成的许多胡同、四合院居住区成为古都风貌的重要组成部分，具有独特的人文价值。
**** 选择
***** A
钟鼓楼是一座古代建筑
***** B
钟鼓楼周边有很多胡同
***** C
钟鼓楼位于北京市西城区
***** D
钟鼓楼的功能是安放乐器
**** 答案
B
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
