:PROPERTIES:
:CREATED: [2022-08-20 08:39:01 -05]
:END:

* 听力

** 1

*** 1

**** transcript

教师必须把教学活动组织得生动、有趣，除了教师讲授外，要多给学生参与的机会。小学生中出现的课堂纪律问题，往往不是学生故意捣乱，而是学生对教师的课不感兴趣，因而不能坚持听课。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:45:33 -05]
:END:
 
Teachers must organize teaching activities in a lively and interesting way, giving students more opportunities to participate in addition to the teacher's lecture. Classroom discipline problems among elementary school students are often not a result of students' intentional disruptions, but rather of students' disinterest in the teacher's lessons and thus their inability to persist in listening to them.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 2

**** transcript

考古发掘中，能够直接参加考古工作的人终究是少数，且一旦发掘工作完毕，现场往往很难原样不动地保存下来，要想让更多的人了解某一地下发掘的现场、情景以及出土文物，只有依靠考古报告。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:48:18 -05]
:END:

Archaeological excavations, can directly participate in the work of archaeology is ultimately a minority, and an excavation is completed, the site is often difficult to preserve intact, in order to allow more people to understand the site of a certain place not excavated scenes and excavated artifacts, only rely on archaeological products.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 3

**** transcript

传统的化学工业给环境带来的污染已十分严重，并威胁着人类的生存。化学工业能否生产出对环境无害的化学品？甚至开发出不产生废物的工艺？有识之士提出了绿色化学的号召，并立确得到了全世界的积极响应。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:57:51 -05]
:END:

The pollution caused by the traditional chemical industry to the environment has been heavy and threatens the survival of human beings. Can the chemical industry produce chemicals that are environmentally friendly? Or even develop waste-free processes? The call for green chemistry has been raised by people with insight, and it has been positively received worldwide.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 4

**** transcript

农历正月初一是古时的新年，又称“新正”，今天我们称之为“春节”。它作为古代官方法定岁首，乃汉武帝时编定的太初历所规定。千百年来，这个法定岁首逐步汇聚了许多其他节日的习俗，成为一个送旧迎新的节日。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:57:36 -05]
:END:

The first day of the first month of the lunar calendar is the ancient New Year, also known as "New Year's Day", which today we call "Spring Festival". It was the official top of the year in ancient times, and was established by the Taichu calendar, which was compiled during the reign of Emperor Wu of the Han Dynasty. Over the centuries, this legal first day of the year has gradually converged with many other festive customs, becoming a festival to send off the old and welcome the new.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 5

**** transcript

小篆，是秦始皇统一六国之后，秦代通用的标准字体。相传是秦国丞相李斯所创。与大篆相比，小篆书写起来更加简便，字体长方，每个字大小一样，排列方正，横竖成行，给人一种整齐之美，这样也就形成了方圆兼备的小篆体。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 09:02:45 -05]
:END:

Small Seal Script is the standard script used in the Qin Dynasty after the unification of the six states by Qin Shi Huang. It is said to have been written by Li Si, the prime minister of Qin. It is easier to write than the non-seal script, with a rectangular font, each character is the same, and it is arranged squarely in horizontal and vertical lines, giving it a neat appearance.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

**  第二部分
:PROPERTIES:
:ID: b3972204-d280-499d-a2d3-443c835d9c41
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

男：离开美国后，你决定写这部非虚构题材的小说，有什么原因和契机吗？
女：这本书是我自己的一段人生历程，其中也包含了大量人们需要的信息。之前我只写形象更为复杂、主题相对悲观的虚构作品。说到非虚构题材的写作，原因和契机其实很偶然。去年，我和一位出版社编辑聊起我在美国陪孩子读书时的一些见闻，提到这样一个场景：一对华人夫妇星期天去购物，那是个冬天，下着鹅毛大雪，他们开车经过市中心，看到有个女孩儿高举标语牌，孤零零地站在教堂门口，标语牌上写着：“抗议反对人工流产”“抗议歧视同性恋”，华人夫妇议论道，这么冷的天，一个女孩子站在雪地里，也不知道她父母知道不知道，车到近前才骇然发现，这女孩儿竟是他们还在读高中的独生女儿。编辑朋友激动地打断我，提议我写下来。她认为，我这几年陪读生活中遇到的点点滴滴都值得记录下来，现在这么多中国家庭把孩子送出去留学，家长非常需要了解我经历过的这些事，中国教育是有问题，但异国生涯无论对小留学生还是对家长都未必不是挑战。
男：你是一个擅长写虚构小说和戏剧的作家，是什么让你决定从虚构的掩体中跃出，开始非虚构的写作？
女：关于非虚构写作，虽然我是第一次尝试，不过我很早就关注了。那是 2000年我在美国期间，逛书店的时候，我发现书店每周张贴出的畅销书前十名排行榜都分为两大类：虚构和非虚构，我吃惊地意识到，在美国，非虚构作品的数量和质量竟然可以和虚构作品不分伯仲。而那时，中国的文学刊物还没有“非虚构”栏目，虽然有报告文学，但报告文学只是非虚构里的一种形式。写这本书，我的初衷是希望和其他家长分享我所了解的美国高中校园，希望读者能够通过我和孩子的一些经历获得他们需要的信息，也希望通过我的视角让读者了解这个媒体上谈论最多的国家，因此比较有说服力的应该是非虚构这个写作形式。

*** 音频

da25817e-346b-44be-9900-caf84a639022.mp3

*** 题目

**** 6

***** 问题

女的这本非虚构题材小说的写作契机是什么？

***** 音频

6099cb26-7825-4003-ab85-f318b929e5f6.mp3

***** 选择

****** A

自己留学的经历

****** B

编辑朋友的建议

****** C

外国朋友的问题

****** D

女儿学校的要求

***** 答案

B

**** 7

***** 问题

关于编辑朋友，下列哪项正确？

***** 音频

df7e1cc0-0cef-4d1d-8b61-30f9b9eb50b0.mp3

***** 选择

****** A

被华人夫妇的女儿征服了

****** B

认为小留学生也面临挑战

****** C

认为中国家长有时很幼稚

****** D

庆幸自己认识一位好作者

***** 答案

B

**** 8

***** 问题

是什么原因促使女的愿意尝试非虚构写作？

***** 音频

ce385b2d-281e-497b-acf6-7b11deb00895.mp3

***** 选择

****** A

非虚构文学在中国是空白

****** B

 2000年非虚构文学才出现

****** C

在美国非虚构作品很畅销

****** D

她接受了非虚构刊物的约稿

***** 答案

C

**** 9

***** 问题

关于女的的非虚构小说，下列哪项正确？

***** 音频

b9cbe20c-5ec1-475c-98fb-d1163a032113.mp3

***** 选择

****** A

读者喜欢什么她就写什么

****** B

进人本周畅销书排行前十

****** C

写的是美国高中校园生活

****** D

媒体评价其内容很有说服力

***** 答案

C

**** 10

***** 问题

关于女的，下列哪项正确？

***** 音频

6b2677e2-0918-4eeb-adda-baa5dd8fa796.mp3

***** 选择

****** A

她的书都写自己的亲身经历

****** B

她的非虚构小说信息量很大

****** C

她的作品内容丰富体裁齐全

****** D

她是一位正义感极强的作家

***** 答案

B

