:PROPERTIES:
:CREATED: [2022-08-20 08:39:01 -05]
:END:

* 听力

** 第二部分
:PROPERTIES:
:ID: b3972204-d280-499d-a2d3-443c835d9c41
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：离开美国后，你决定写这部非虚构题材的小说，有什么原因和契机吗？
女：这本书是我自己的一段人生历程，其中也包含了大量人们需要的信息。之前我只写形象更为复杂、主题相对悲观的虚构作品。说到非虚构题材的写作，原因和契机其实很偶然。去年，我和一位出版社编辑聊起我在美国陪孩子读书时的一些见闻，提到这样一个场景：一对华人夫妇星期天去购物，那是个冬天，下着鹅毛大雪，他们开车经过市中心，看到有个女孩儿高举标语牌，孤零零地站在教堂门口，标语牌上写着：“抗议反对人工流产”“抗议歧视同性恋”，华人夫妇议论道，这么冷的天，一个女孩子站在雪地里，也不知道她父母知道不知道，车到近前才骇然发现，这女孩儿竟是他们还在读高中的独生女儿。编辑朋友激动地打断我，提议我写下来。她认为，我这几年陪读生活中遇到的点点滴滴都值得记录下来，现在这么多中国家庭把孩子送出去留学，家长非常需要了解我经历过的这些事，中国教育是有问题，但异国生涯无论对小留学生还是对家长都未必不是挑战。
男：你是一个擅长写虚构小说和戏剧的作家，是什么让你决定从虚构的掩体中跃出，开始非虚构的写作？
女：关于非虚构写作，虽然我是第一次尝试，不过我很早就关注了。那是 2000年我在美国期间，逛书店的时候，我发现书店每周张贴出的畅销书前十名排行榜都分为两大类：虚构和非虚构，我吃惊地意识到，在美国，非虚构作品的数量和质量竟然可以和虚构作品不分伯仲。而那时，中国的文学刊物还没有“非虚构”栏目，虽然有报告文学，但报告文学只是非虚构里的一种形式。写这本书，我的初衷是希望和其他家长分享我所了解的美国高中校园，希望读者能够通过我和孩子的一些经历获得他们需要的信息，也希望通过我的视角让读者了解这个媒体上谈论最多的国家，因此比较有说服力的应该是非虚构这个写作形式。

**** 音频

da25817e-346b-44be-9900-caf84a639022.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: d0428248-c813-4416-96f4-17342f0c0214
:END:

***** 问题

女的这本非虚构题材小说的写作契机是什么？

****** 音频

6099cb26-7825-4003-ab85-f318b929e5f6.mp3

***** 选择

****** A

自己留学的经历

****** B

编辑朋友的建议

****** C

外国朋友的问题

****** D

女儿学校的要求

***** 答案

B

**** 7
:PROPERTIES:
:ID: 02ba94fa-e9cc-4a21-9f57-a50bd99ca1e4
:END:

***** 问题

关于编辑朋友，下列哪项正确？

****** 音频

df7e1cc0-0cef-4d1d-8b61-30f9b9eb50b0.mp3

***** 选择

****** A

被华人夫妇的女儿征服了

****** B

认为小留学生也面临挑战

****** C

认为中国家长有时很幼稚

****** D

庆幸自己认识一位好作者

***** 答案

B

**** 8
:PROPERTIES:
:ID: a2867def-71e3-41a9-a781-6edbd47180d6
:END:

***** 问题

是什么原因促使女的愿意尝试非虚构写作？

****** 音频

ce385b2d-281e-497b-acf6-7b11deb00895.mp3

***** 选择

****** A

非虚构文学在中国是空白

****** B

 2000年非虚构文学才出现

****** C

在美国非虚构作品很畅销

****** D

她接受了非虚构刊物的约稿

***** 答案

C

**** 9
:PROPERTIES:
:ID: 7ab8ae37-7610-4899-b7aa-b942537f9538
:END:

***** 问题

关于女的的非虚构小说，下列哪项正确？

****** 音频

b9cbe20c-5ec1-475c-98fb-d1163a032113.mp3

***** 选择

****** A

读者喜欢什么她就写什么

****** B

进人本周畅销书排行前十

****** C

写的是美国高中校园生活

****** D

媒体评价其内容很有说服力

***** 答案

C

**** 10
:PROPERTIES:
:ID: 48762a3b-4476-4ad8-92d7-10d821634920
:END:

***** 问题

关于女的，下列哪项正确？

****** 音频

6b2677e2-0918-4eeb-adda-baa5dd8fa796.mp3

***** 选择

****** A

她的书都写自己的亲身经历

****** B

她的非虚构小说信息量很大

****** C

她的作品内容丰富体裁齐全

****** D

她是一位正义感极强的作家

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

小学生的注意力不能持仁

***** B

没有经验的老师上不好课

***** C

课有吸引力学生就会认真听

***** D

学生违反纪律是应该原谅的

**** 段话

教师必须把教学活动组织得生动、有趣，除了教师讲授外，要多给学生参与的机会。小学生中出现的课堂纪律问题，往往不是学生故意捣乱，而是学生对教师的课不感兴趣，因而不能坚持听课。

***** 音频

88e9d56a-b67a-4504-93a9-a83f46b63def.mp3

**** 答案

C

*** 2

**** 选择

***** A

考古工作者的数量一直不跃

***** B

考古工作完毕，现场就破坏了

***** C

考古工作者都应该学习考古报告

***** D

考古报告能反映当时的考古发掘情况

**** 段话

考古发掘中，能够直接参加考古工作的人终究是少数，且一旦发掘工作完毕，现场往往很难原样不动地保存下来，要想让更多的人了解某一地下发掘的现场、情景以及出土文物，只有依靠考古报告。

***** 音频

b709f83e-bc23-4fd0-a0e3-918c2462be6e.mp3

**** 答案

D

*** 3

**** 选择

***** A

化学工业正在进行一场革命

***** B

人们怀疑无害化学品的真实性

***** C

传统化学工业的生存受到了挑战

***** D

降低化学污染的号召得到了响应

**** 段话

传统的化学工业给环境带来的污染已十分严重，并威胁着人类的生存。化学工业能否生产出对环境无害的化学品？甚至开发出不产生废物的工艺？有识之士提出了绿色化学的号召，并立即得到了全世界的积极响应。

***** 音频

b0e2e70d-8698-4307-96be-a0ee74690fee.mp3

**** 答案

D

*** 4

**** 选择

***** A

春节是一年的最后一天

***** B

“春节“古时称为“新正“

***** C

汉武帝规定春节为法定节日

***** D

从一开始春节就有很多习俗

**** 段话

农历正月初一是古时的新年，又称“新正”，今天我们称之为“春节”。它作为古代官方法定岁首，乃汉武帝时编定的太初历所规定。千百年来，这个法定岁首逐步汇聚了许多其他节日的习俗，成为一个送旧迎新的节日。

***** 音频

e6faa4ae-1310-44a0-8121-759590a2fd51.mp3

**** 答案

B

*** 5

**** 选择

***** A

小篆曾经风行六国

***** B

相传李斯创造了小篆

***** C

小篆可以写成方的或圆的

***** D

就书写简便而言，大篆更优

**** 段话

小篆，是秦始皇统一六国之后，秦代通用的标准字体。相传是秦国丞相李斯所创。与大篆相比，小篆书写起来更加简便，字体长方，每个字大小一样，排列方正，横竖成行，给人一种整齐之美，这样也就形成了方圆兼备的小篆体。

***** 音频

7764c7a3-e05f-4a0d-ba8c-117123f90c1b.mp3

**** 答案

B

** 第三部分

*** 11-13

**** 课文

“年”是中国人最重要、最综合的一个节日。年，对我们究竟意味着什么？华服？美食？休闲？放松？不尽然，应该说贴对联、穿新衣，只是一种仪式，是对辞旧迎新的尊重，对美好生活的憧憬；拜年、聚餐、拉家常，则是对亲情的眷恋。

很多人感慨现在的“年味”越来越淡了。其实所谓“浓”或“淡”，恐怕只是成年人的感受，年复一年，循环往复，再加上现在生活水平提高了，平时吃、穿水平就不低，过年也变不出什么新花样，新鲜感自然就少了！但是孩子过年总是欢乐的，仿佛天天都被浓浓的年味包裹着，光是过年的气氛，就足以让他们欢快了，和儿时的我们一样。

**** 题目

***** 11

****** 选择

******* A

努力工作

******* B

全家团聚

******* C

举行仪式

******* D

外出旅行

****** 问题

根据这段话，中国人过年要做什么？

****** 答案

B

***** 12

****** 选择

******* A

为丁漂亮

******* B

以示重视

******* C

因为有钱

******* D

因为高兴

****** 问题

过年为什么要穿新衣服？

****** 答案

B

***** 13

****** 选择

******* A

以前的喧哗不见了

******* B

新鲜的东西都没有了

******* C

现在天天都穿新衣服

******* D

平时生活水平提高了

****** 问题

为什么很多人觉得现在年味不浓？

****** 答案

D

*** 14-17

**** 课文

我理解“慢生活”就是一种生活态度，把工作、吃饭、休息、劳动都看成一种享受。老实说，生活中的每件小事都能给我们带来快乐，比如，拿起剪刀慢慢做点儿小手工；亲手织一件色泽淡雅、款式绝无仅有的毛衣穿在身上；在花瓶中插上一束沁人心脾的鲜花；每顿都用心做一碗健康美味的汤品。而做这些事的过程并非都是痛苦的劳动，其本身就充满了乐趣。

于是，我开始改变自己。原本我不写日记，现在开始徜徉在文字之间，寻觅那一份“慢”的惬意；每天开车上班，我改变了按点出门的习惯，这样就不会为堵车而心急火燎，而是慢慢开，把驾驶当成一种乐趣；出去买菜或办事需要走路时，我的脚步慢了下来，看看身边的城市、身边的人，发现竟然会有不一样的心情！

慢下来其实很简单，只要去除那些外力强加给你的价值观，只需听从自己内心的声音，找到自己喜欢的事情，按照自己的节奏，慢慢地享受那份美好，你的心中就会少些抱怨，感觉生活其实很精彩！

**** 题目

***** 14

****** 选择

******* A

“慢生活“讲究事必躬亲

******* B

“慢生活“讲究行为优雅

******* C

“慢生活“讲究品咖和质量

******* D

“慢生活“讲究体咖做事的过程

****** 问题

说话人认为应该怎样理解“慢生活”？

****** 答案

D

***** 15

****** 选择

******* A

开始读书写作

******* B

开始调整自己

******* C

学着买菜做饭

******* D

在街上东张西望

****** 问题

说话人有哪些改变？

****** 答案

B

***** 16

****** 选择

******* A

不要去管别人想什么

******* B

不要惧怕外界的压力

******* C

按自己的想法享受美好

******* D

慢与不慢都能活得精彩

****** 问题

说话人对“慢生活”的切身感受是什么？

****** 答案

C

***** 17

****** 选择

******* A

慢生活是大势所趋

******* B

慢点开车才能欣赏到风景

******* C

想提高工作效率要先慢下来

******* D

慢下来可以感受到不一样的生活

****** 问题

说话人告诉我们什么？

****** 答案

D

