* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: aa08f8d8-4580-4049-a6a4-9397097eb858
:END:
**** 对话
***** 转录
女：小刘，你今年就要毕业了，对找工作有什么想法？[[file:967eaeae-e0c5-4271-b292-dbfded0f9db0.mp3][(audio)]]
男：说实话，我觉得从专业看，自己实在没有什么优势。[[file:7fcb99b6-bafe-4407-97a3-fdbc8feb6130.mp3][(audio)]]
***** 音频
0fb32b87-a85f-41a1-9e18-2cfae6ab18ba.mp3
**** 问题
***** 转录
男的觉得自己怎么样？
***** 音频
e2fd8d03-86c1-41e5-b858-064a9ecce1bc.mp3
**** 选择
***** A
毕不了业
***** B
专业很好
***** C
能找到好工作
***** D
就业形势不乐观
**** 答案
D
*** 2
:PROPERTIES:
:ID: b8a81178-79c9-453d-9a3f-fdd7fbfbf18d
:END:
**** 对话
***** 转录
男：请问，我想去鼓楼大街，应该怎么坐车？[[file:6a768870-476c-4251-869f-0ae2acb598c2.mp3][(audio)]]
女：在前面坐 1 路，到天安门东，然后换乘 3 路。[[file:14bf98ff-1ef6-4051-853e-67008a4899bf.mp3][(audio)]]
***** 音频
03fe05d2-f3f3-48f1-954e-a196d0796adf.mp3
**** 问题
***** 转录
从这里到鼓楼大街要换乘几次车？
***** 音频
fc4a9bda-95c4-489e-9f32-41dc83fab3a7.mp3
**** 选择
***** A
1次
***** B
2次
***** C
3次
***** D
4次
**** 答案
A
*** 3
:PROPERTIES:
:ID: 33e329f7-3cf9-411b-bff1-00a97f13ae20
:END:
**** 对话
***** 转录
女：来应聘我们网站的编辑职位，你觉得自己有什么优势？[[file:98ba8cec-828e-422b-902e-2e287363d05b.mp3][(audio)]]
男：我的专业是计算机，电脑软件用得很熟练；另外，我也很爱好文学。[[file:0b11039d-0e1e-4cdc-b060-0b5839ae9f67.mp3][(audio)]]
***** 音频
bdef3c61-4dc1-483d-a657-c21edfc0396d.mp3
**** 问题
***** 转录
男的觉得自己哪方面最强？
***** 音频
eb8eff79-60fc-49e0-a527-e1b2cfe2931d.mp3
**** 选择
***** A
上网
***** B
编辑
***** C
电脑
***** D
文学
**** 答案
C
*** 4
:PROPERTIES:
:ID: b29bd10f-97d5-4e1a-adbe-d846f2b01e61
:END:
**** 对话
***** 转录
男：昨天我才听说，你跟王林是同学。你们熟吗？[[file:1f516612-535a-4b2c-abcb-eeba308acad9.mp3][(audio)]]
女：不算熟，同届不同班，就是在楼里见面打个招呼的交情。[[file:8065a027-7135-48f2-8379-676b0fc345c0.mp3][(audio)]]
***** 音频
0eacc36d-1a8e-46b4-a3db-ce6f6676873c.mp3
**** 问题
***** 转录
女的跟王林是什么关系？
***** 音频
c0d79288-ca15-4357-b161-5aad5b405811.mp3
**** 选择
***** A
同班同学
***** B
同年级同学
***** C
师兄妹
***** D
恋人
**** 答案
B
*** 5
:PROPERTIES:
:ID: 13f84e8e-c3b3-4f1e-a462-1f6ba7feaefe
:END:
**** 对话
***** 转录
女：这次比赛让小李去参加怎么样？他反应比较快。[[file:b4fb3e8e-268c-498a-830a-65a0f3c791de.mp3][(audio)]]
男：小李反应虽然快，但基本功没有小张好。[[file:0a03070f-5dfb-4d30-8350-8dcfcfbd1bed.mp3][(audio)]]
***** 音频
fa1afb02-85b4-4566-9976-3e86124a2b77.mp3
**** 问题
***** 转录
男的希望派谁去参加比赛？
***** 音频
296a8e44-7fc7-461f-a8c7-fc9e0e17e9b5.mp3
**** 选择
***** A
小张
***** B
小李
***** C
两个都可以
***** D
两个都不行
**** 答案
A
*** 6
:PROPERTIES:
:ID: e17f6ef4-e385-46b7-8c9f-d87631e10c69
:END:
**** 对话
***** 转录
男：你们给的工资是不是太高了？[[file:9a4d68e0-ef79-40af-9af8-d4a4dcaba184.mp3][(audio)]]
女：专业的、执着的、优秀的人才是无价的。[[file:cfb28060-debe-42d0-8e7a-ea2ce99337f2.mp3][(audio)]]
***** 音频
f42f68d7-b4cb-4cbd-8590-be8dc65184ae.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
9870f742-4818-40ae-a312-35b4eb207447.mp3
**** 选择
***** A
给的工资太高了
***** B
学这个专业的人少
***** C
为人才付钱是值得的
***** D
她可以为公司挣回来
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：明天就要开项目会了，你真的打算这次让小刘负责？
男：我们不是都说好了吗？小刘有什么不好？
女：她可还是个新人。
男：你总是对别人缺乏信心。
***** 音频
aca52311-775d-4b14-919b-3d1808ccdada.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
b331c1ae-c7b9-470d-92b4-fb35bc3b5ebd.mp3
**** 选择
***** A
女的是新人
***** B
要相信小刘
***** C
换人来不及
***** D
再考虑一下
**** 答案
B
*** 8
**** 对话
***** 转录
男：今年来找工作的毕业生里，有适合干办公室的人吗？
女：怎么了？小高不是挺好的吗？
男：她下个月就要辞职了，说是跟别人一起去开公司。
女：我帮你看看。
***** 音频
6e152341-4ea8-45fd-a43f-2d53e235a8f3.mp3
**** 问题
***** 转录
关于小高，下列哪项正确？
***** 音频
105b596f-b84b-47cc-a5bb-5954ecfc54a8.mp3
**** 选择
***** A
要找工作
***** B
准备辞职
***** C
不适合干办公室
***** D
今年刚大学毕业
**** 答案
B
*** 9
**** 对话
***** 转录
女：老师，我的论文怎么样？
男：你论文里这个结论是怎么来的？我完全看不出科学性。
女：您不是说要大胆假设吗？
男：“大胆假设”后面还有一句是“小心求证”呢！
***** 音频
f77a6809-e839-4853-80b7-0d1878a10959.mp3
**** 问题
***** 转录
老师认为这篇论文怎么样？
***** 音频
cc8d9684-bb74-4f98-bfc5-3c0ecbb13bcc.mp3
**** 选择
***** A
写得很好
***** B
有科学性
***** C
没有证据
***** D
假设大胆
**** 答案
C
*** 10
**** 对话
***** 转录
男：你们今天怎么回事？8：30 上课，只来了十几个人，现在 9：00 了，还有三个没来。
女：老师，他们三个病了，去了医院，马上就到。
男：马上马上，已经迟到半小时了！
女：您看，已经来了！
***** 音频
08d9cd6e-109d-4b60-a832-3a885be8d7c1.mp3
**** 问题
***** 转录
今天学生来上课的情况怎么样？
***** 音频
9612895d-0512-4082-9560-22e9101de6d8.mp3
**** 选择
***** A
都是一起来的
***** B
一直没有到齐
***** C
是陆陆续续来的
***** D
所有人都迟到了
**** 答案
C
*** 11-12
**** 对话
***** 转录
女：之前公司并没有录用你，你为什么还要写感谢信给我们呢？
男：虽然公司没有录用我，但认真看过我的简历，也使我收获了面试经验，我觉得也应该表示感谢。
女：你做得好！正是因为你写来的感谢信，让我们觉得你是个很有礼貌的人，对我们公司也很有诚意，所以这次招聘时我们就优先考虑了你。
男：非常感谢您和公司给我这个机会。
女：这个机会是你自己创造的。
***** 音频
9859a42b-51ce-40d0-8729-569d616457b4.mp3
**** 题目
***** 11
****** 问题
******* 转录
说话的两个人是什么关系？
******* 音频
cc6459ba-dd5d-48ae-a3c0-1b5ad9ed9bb2.mp3
****** 选择
******* A
同学或朋友
******* B
老板和顾客
******* C
两个求职者
******* D
面试官和求职者
****** 答案
D
***** 12
****** 问题
******* 转录
这次公司招聘为什么优先考虑这个男的？
******* 音频
1f5adbd1-9f8a-44c0-820d-853ab85caa19.mp3
****** 选择
******* A
他写过感谢信
******* B
他有工作经验
******* C
他对面试官很礼貌
******* D
他是公司的老职员
****** 答案
A
*** 13-14
**** 段话
***** 转录
希望国际大酒店，是本市唯一一家五星级酒店，占地面积 5.5 万平方米，共有客房 288 套。现酒店财务部需要招聘财务经理一名，成本主管一名，IT 主管一名。以上职位都要求相关专业研究生毕业，需有两年以上酒店工作经验。酒店可提供住宿，薪酬面议。我们将为你提供一个和谐的工作环境和良好的学习氛围，传授五星级酒店管理的技能，助你快速成长。
***** 音频
364f8151-1345-49b5-a887-5720336bd210.mp3
**** 题目
***** 13
****** 问题
******* 转录
酒店对应聘者有什么要求？
******* 音频
a8e5e205-3cff-4f30-a7bd-a31069217a59.mp3
****** 选择
******* A
学酒店专业
******* B
研究生学历
******* C
有管理经验
******* D
签两年合同
****** 答案
B
***** 14
****** 问题
******* 转录
关于酒店，下列哪项正确？
******* 音频
1bec79c7-0417-4f8c-b1e5-c955c3828088.mp3
****** 选择
******* A
要招聘五人
******* B
工资非常高
******* C
有员工宿舍
******* D
有管理培训班
****** 答案
C
* 阅读
** 第一部分
*** 段话
生活就像一面镜子。你对它哭，[[gap][15]]。如果你想要它对你微笑，那么只有一种办法，就是也对它微笑。微笑，是最美好、最迷人的一种表情。人生有成功也有失败，谁都不可能一帆风顺。真正大的智意，往往源于失败的教训。古今中外，大多数成功者都经历过失败，可贵的是他们的勇气，他们能微笑着[[gap][16]]失败。就像马克。吐温经商失意，便弃商从文，结果一举成名。我们不能单单停留在失败中，要从失败中吸取经验教训，把这些经验教训作为以后行动的[[gap][17]]，这样，我们才会变得成熟，最终[[gap][18]]成功的彼岸。正如拿破仑所说的：“避免失败的最好方法，就是决心获得下一次成功“
*** 题目
**** 15
***** 选择
****** A
它看不见
****** B
它就碎了
****** C
它也对你哭
****** D
它就对你笑
***** 答案
C
**** 16
***** 选择
****** A
面对
****** B
对面
****** C
面临
****** D
方面
***** 答案
A
**** 17
***** 选择
****** A
参加
****** B
参观
****** C
参考
****** D
参与
***** 答案
C
**** 18
***** 选择
****** A
发达
****** B
到达
****** C
达到
****** D
表达
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 8949b955-18b2-4ca6-bb28-5c6368f3fd91
:END:
**** 段话
他对公交的这种专注显然为他求职打开了大门。老总们向他发出了热情的邀请，给他非常好的职位和待遇，甚至要专门为他成立有关的部门，只为留住这个人才。最终，他选择了一家他最感兴趣的单位。
**** 选择
***** A
他要去公交公司任职
***** B
想要录用他的公司不止一家
***** C
有人愿意为他专门成立公司
***** D
他选择了待遇最好的公司
**** 答案
B
*** 20
:PROPERTIES:
:ID: c9d5582c-82f6-43bb-8e0c-2ce8cd9a67e5
:END:
**** 段话
任何一家公司在招聘时，都会注意一个人的综合能力。然而在短暂的面试时间里，无论准备得如何充分，都无法让个人才能全方位地展示出来。作为求职者，应该做的是，针对所应聘岗位强调个人的能力和专长，针对这项工作详细阐述自己的优点与长处。
**** 选择
***** A
招聘时都要经过面试
***** B
面试前要做充分的准备
***** C
求职者要表现自己的优势
***** D
求职者应该全面展示自己
**** 答案
C
*** 21
:PROPERTIES:
:ID: 3af49e67-c086-4d4f-a563-2d294eda33cd
:END:
**** 段话
“名片效应”是指两个人在交往时，如果首先表明自己与对方的态度和价值观相同，就会使对方感到你与他有很多的相似性，从而很快地缩小与你的心理距离，更愿意同你接近，结成良好的人际关系。在这里，有意识、有目的地向对方表明态度和观点，就如同名片一样，可以把自己介绍给对方。
**** 选择
***** A
“名片效应”是指见面时给对方名片
***** B
“名片效应”要求双方态度完全一样
***** C
“名片效应”可以缩小人之间的距离
***** D
“名片效应”是有意识有目的地骗人
**** 答案
C
*** 22
:PROPERTIES:
:ID: 049bd38d-a032-4135-8535-6a30f565cf37
:END:
**** 段话
本职位任职要求：一、从事电视编导、新闻采编工作3年以上，有丰富的外拍经验；二、集体荣誉感强，能很好地与团队其他工作人员进行工作对接；三、能适应出差的工作节奏；四、有超强的抗压能力和工作主动性。
**** 选择
***** A
这个职位工作不太紧张
***** B
这是招聘报社记者的广告
***** C
这个职位要求个人独立工作
***** D
这个职位可能常常需要出差
**** 答案
D
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
