* 听力

** 1

*** 1

**** transcript

《康熙字典》是清代康熙年间出版的图书，作者是张玉书、陈廷敬等，它是在明朝《字汇》《正字通》两书的基础上加以增订的。该书的编撰工作始于康熙四十九年，成书于康熙五十五年，历时六年，因此书名叫《康熙字典》。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:02:52 -05]
:END:

The Kangxi Dictionary is a book published during the Kangxi period of the Qing Dynasty by Zhang Yushu and Chen Tingjing, which was updated on the basis of the two books of the Ming Dynasty, namely, "Word Hui" and "Zheng Zi Tong". The compilation of the book began in the 19th year of the Kangxi B and was completed in the 55th year of the Kangxi era, which took six years, hence the name of the book "Kangxi Dictionary".

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

有些人很爱凑热闹，不管街头发生什么事情，他们都要驻足引颈，看个究竟。有的还免不了要放开喉咙，起哄喝倒彩，从中寻找乐趣，寻求刺激，这其实反映出一种病态心理。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:06:46 -05]
:END:

Some people love to get together, no matter what is happening in the streets, they have to stop and neck, to see what is going on. Some also inevitably have to let go of the throat, the coaxing drink backwards, from which to find the East interesting, seeking stimulation, which in fact reflects a pathological psychology.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

婴儿在1周岁左右，开始学会独立行走，能更自由地接近和探索周围事物。当他看到桌子上放着一个他喜爱的玩具而无法拿到手时，会推大人的手去拿，表现出初步的有意向的行动。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:10:40 -05]
:END:

At around 1 week of age, infants begin to learn to walk independently and are able to approach and explore things around them more freely When he sees a favorite toy sitting on the table and cannot get his hands on it, he will push an adult's hand to get it, showing initial intentional action.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

读者获取信息也是有成本与收益的。他们花钱买报，花时间看报就是成本，从报纸中得到对自己有用的信息就是收益。报纸扩版后，读者的成本增加了，尤其是要花更多宝贵的时间去读，忙碌的现代人承受不起这么高的成本。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:13:58 -05]
:END:

Readers also have costs and benefits of getting information. They pay for the newspaper, spend time to read the newspaper is the cost, from the newspaper to get useful information for themselves is the benefit. After the expansion of the newspaper, the cost to the reader has increased, especially because it takes more precious time to read, and the busy modern people cannot afford such high costs.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

这个剧本的可读性很强，尤其是剧本的语言，让人看后久久难忘。它的语言虽然都是生活中的口语，但经过了作者的提炼熔铸后，显得既鲜活又不失文雅，而且富有情趣。可以想象，这样朗朗上口的语言，一定很适合舞台演出。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:17:36 -05]
:END:

The play is very readable, especially the language of the play, which makes it unforgettable after reading. Although the language is all spoken in life, after the author's refinement and melting, it seems to be both vivid and elegant, and is rich in emotion. It is imaginable that such language, which is spoken on the shoulders, must be suitable for stage performance.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 76d96a6b-5838-420a-8fa4-ccfaaf4c439e
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：能不能告诉我们，您最初怎么选中了厨师这个行业？
男：我最初选择学厨师，想法很简单，人走到哪里都得吃饭，干这一行肯定饿不着。
女：后来怎么就做到了五星级酒店的京菜主厨呢？
男：进了饭店从做小工、刷盘子开始，我越干越觉得，厨师这一行实在是个让人痴迷又魅力无穷的行业。
女：我们都知道掂大勺、刀功，都是厨师的看家本领，您学艺过程中，最头疼的是什么呢？
男：记得刚学会做菜那会儿，我是吃到哪儿挑到哪儿，每吃一道菜，都要评头论足，“油放少了”“盐放多了”。后来，我想明白了，同样的调料，不同的人会炒出不同的味儿，就是中餐的精髓。我学做饭那时候，最伤脑筋的就是菜谱上“少许”这俩字，老是分寸把握不好。把这两个字琢磨透了，就可以出师了。
女：自从您学厨师之后，过年过节，您家的聚餐就成了您露一手的机会了吧？
男：说到这儿，我就会想起奶油菜花，这道菜给我的教训太深了。
女：能讲给我们听听吗？
男：2003 年春节，我在学校练了一年的基本功，急于给大伙儿露一手，自告奋勇要给大家来个奶油菜花。这道菜我没做过，听老师在课堂上提过，觉得没什么难的。结果我进了厨房，一看那一堆菜花和黄油就傻眼了，最后愣是做出一锅大乱炖。菜端上桌，我觉得太丢人了，简直无地自容。亲戚朋友倒是非常捧场，把那道菜吃了个精光。
女：大伙儿肯定能原谅您，那时候您还是个刚入学一年的学生嘛。
男：8 年以后，我把家里的亲戚朋友召集到一块儿，来了场“雪耻之战”。我当时放下豪言，让大家随便点，想吃什么点什么，他们能想得出的，我都能做。几个小时倒腾出来的十几道菜，当然也得到了大伙儿的一致称赞。
女：您心里特别美吧？
男：那就不用说了。

**** 音频

5fabd694-e537-4695-bc7d-cda5a51faa1f.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 8dc4a7d0-9a8f-4f3c-9c3d-f5bb4608c8c9
:END:

***** 问题

男的为什么选择做厨师？

****** 音频

61fe386e-2fda-4389-823d-f35e7bec51b3.mp3

***** 选择

****** A

厨师省脑子

****** B

厨师挣钱多

****** C

厨师不会失业

****** D

厨师不会挨俄

***** 答案

C

**** 7
:PROPERTIES:
:ID: 6df67efc-10cb-4ff7-81d0-ebc39526b69d
:END:

***** 问题

为什么男的能做到五星级酒店的京菜主厨？

****** 音频

b3d00605-f093-444c-9ba2-dca657ddf48f.mp3

***** 选择

****** A

因为做小工、刷盘子太累

****** B

因为他从小喜欢吃北京菜

****** C

因为他迷恋上了厨师这个行业

****** D

田为他的师傅是个很有魅力的人

***** 答案

C

**** 8
:PROPERTIES:
:ID: 965cbce1-b96f-4853-9f13-cce3a5c24275
:END:

***** 问题

关于中餐，下列哪项正确？

****** 音频

26c6ccb8-4040-468e-a9b3-f8e83d1b49a5.mp3

***** 选择

****** A

要多放油

****** B

做菜讲究标准化

****** C

各种调料要按顺序放

****** D

各种调料的量要恰到好处

***** 答案

D

**** 9
:PROPERTIES:
:ID: 48642522-0064-4a35-958f-36ae206fd321
:END:

***** 问题

关于奶油菜花，下列哪项正确？

****** 音频

2fac5c9e-7af6-4efd-8680-811d6234f097.mp3

***** 选择

****** A

是男的学会的第一道菜

****** B

最后男的根本没做出来

****** C

是大家强烈要求男的做的菜

****** D

是大家公认最好吃的一道菜

***** 答案

B

**** 10
:PROPERTIES:
:ID: 4360a1c8-9e92-4638-9984-30d2587184be
:END:

***** 问题

8 年以后，男的做了件什么事？

****** 音频

52d0e397-83a1-4a9d-a8c3-ed66a61d5735.mp3

***** 选择

****** A

请大家吃了顿最贵的饭

****** B

一顿饭吃了好几个小时

****** C

做的都是大家没吃过的菜

****** D

为8年前的事找回了面子

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

《康熙字典》是康熙编的

***** B

《康熙字典》的编纂者共有2人

***** C

《康熙字典》的名字是康熙起的

***** D

编写《康熙字典》共用了6年时间

*** 2

**** 选择

***** A

爱起哄的心态不健康

***** B

有好奇心是人的本性

***** C

在街上唱歌是一种快乐

***** D

喜欢凑热闸的人不在少数

*** 3

**** 选择

***** A

婴儿喜欢拥有自己的玩具

***** B

大人总会帮婴儿实现目标

***** C

大人应该想办法了解婴儿的理想

***** D

1岁的婴儿会表现出自己的意向

*** 4

**** 选择

***** A

读者的时间也是成本

***** B

报纸的成本越来越高

***** C

扩版后报纸信息变少

***** D

现在的人不愿意读报

*** 5

**** 选择

***** A

这个剜本只适合阅读

***** B

这个剧本演出效果很好

***** C

这个剧本写得极其成功

***** D

生活中的口语是最文雅的

