* Listening

** 1

*** 1

**** transcript

《康熙字典》是清代康熙年间出版的图书，作者是张玉书、陈廷敬等，它是在明朝《字汇》《正字通》两书的基础上加以增订的。该书的编撰工作始于康熙四十九年，成书于康熙五十五年，历时六年，因此书名叫《康熙字典》。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:02:52 -05]
:END:

The Kangxi Dictionary is a book published during the Kangxi period of the Qing Dynasty by Zhang Yushu and Chen Tingjing, which was updated on the basis of the two books of the Ming Dynasty, namely, "Word Hui" and "Zheng Zi Tong". The compilation of the book began in the 19th year of the Kangxi B and was completed in the 55th year of the Kangxi era, which took six years, hence the name of the book "Kangxi Dictionary".

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

有些人很爱凑热闹，不管街头发生什么事情，他们都要驻足引颈，看个究竟。有的还免不了要放开喉咙，起哄喝倒彩，从中寻找乐趣，寻求刺激，这其实反映出一种病态心理。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:06:46 -05]
:END:

Some people love to get together, no matter what is happening in the streets, they have to stop and neck, to see what is going on. Some also inevitably have to let go of the throat, the coaxing drink backwards, from which to find the East interesting, seeking stimulation, which in fact reflects a pathological psychology.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

婴儿在1周岁左右，开始学会独立行走，能更自由地接近和探索周围事物。当他看到桌子上放着一个他喜爱的玩具而无法拿到手时，会推大人的手去拿，表现出初步的有意向的行动。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:10:40 -05]
:END:

At around 1 week of age, infants begin to learn to walk independently and are able to approach and explore things around them more freely When he sees a favorite toy sitting on the table and cannot get his hands on it, he will push an adult's hand to get it, showing initial intentional action.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

读者获取信息也是有成本与收益的。他们花钱买报，花时间看报就是成本，从报纸中得到对自己有用的信息就是收益。报纸扩版后，读者的成本增加了，尤其是要花更多宝贵的时间去读，忙碌的现代人承受不起这么高的成本。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:13:58 -05]
:END:

Readers also have costs and benefits of getting information. They pay for the newspaper, spend time to read the newspaper is the cost, from the newspaper to get useful information for themselves is the benefit. After the expansion of the newspaper, the cost to the reader has increased, especially because it takes more precious time to read, and the busy modern people cannot afford such high costs.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

这个剧本的可读性很强，尤其是剧本的语言，让人看后久久难忘。它的语言虽然都是生活中的口语，但经过了作者的提炼熔铸后，显得既鲜活又不失文雅，而且富有情趣。可以想象，这样朗朗上口的语言，一定很适合舞台演出。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:17:36 -05]
:END:

The play is very readable, especially the language of the play, which makes it unforgettable after reading. Although the language is all spoken in life, after the author's refinement and melting, it seems to be both vivid and elegant, and is rich in emotion. It is imaginable that such language, which is spoken on the shoulders, must be suitable for stage performance.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



