* 听力

** 1

*** 1

**** transcript

表面看，它是一个普通得不能再普通的包裹，里面装的是家乡的土特产，但在我的眼里，它珍贵着呢。它经过了母亲的双手，又途经千里，来到了我的面前。它沾染着故乡的气息，满载着母亲无声的爱意。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

清晨，梦中的我被父亲叫醒，“走，晨练去！”我和父亲并排跑着，一抬头发现父亲竟然有了一丝白发。我有些心酸。他总是那么勤奋，那么忙碌，为家庭、为单位操劳。作为女儿，我懂得父亲的付出、父亲的期望。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

家是什么？家是一个可以放松的地方，说话做事都不必小心；家是一个可以疗伤的地方，伤了痛了都可以在家中得以缓解。回到家，可以听几首音乐，可以饮一杯清茶，让心情重归舒畅。3

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

“诚”指诚实诚恳，“信”即信用信任。“诚”主要指“内诚于心”，“信”主要指“外信于人”。“诚”“信”组合在一起，就形成了一个内外兼备，具有丰富内容的词汇，即诚实无欺，讲求信用。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

老张做月饼的手艺是一流的，那是他父亲的父亲传下来的。老张做月饼不喜欢别人看，可他也不特别防范，一来是人来人往地不好防；二来是老张不好意思跟人急，真翻脸。邻居们也很自觉，老张养活着一大家人，不容易。

***** translation
:PROPERTIES:
:CREATED: [2022-08-22 22:05:00 -05]
:END:

Old Zhang's craft of making moon cakes is first-class, that is his father's father handed down. Old Zhang does not like people to see the moon cakes, but he is not particularly guarded, for one thing, it is not good to prevent people coming and going; secondly, the old Zhang is embarrassed to be anxious with people, really turn the other cheek. Neighbors are also very conscious, the old Zhang feed a large family, not easy.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



