* 听力

** 1

*** 1

**** transcript

表面看，它是一个普通得不能再普通的包裹，里面装的是家乡的土特产，但在我的眼里，它珍贵着呢。它经过了母亲的双手，又途经千里，来到了我的面前。它沾染着故乡的气息，满载着母亲无声的爱意。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

清晨，梦中的我被父亲叫醒，“走，晨练去！”我和父亲并排跑着，一抬头发现父亲竟然有了一丝白发。我有些心酸。他总是那么勤奋，那么忙碌，为家庭、为单位操劳。作为女儿，我懂得父亲的付出、父亲的期望。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

家是什么？家是一个可以放松的地方，说话做事都不必小心；家是一个可以疗伤的地方，伤了痛了都可以在家中得以缓解。回到家，可以听几首音乐，可以饮一杯清茶，让心情重归舒畅。3

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

“诚”指诚实诚恳，“信”即信用信任。“诚”主要指“内诚于心”，“信”主要指“外信于人”。“诚”“信”组合在一起，就形成了一个内外兼备，具有丰富内容的词汇，即诚实无欺，讲求信用。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

老张做月饼的手艺是一流的，那是他父亲的父亲传下来的。老张做月饼不喜欢别人看，可他也不特别防范，一来是人来人往地不好防；二来是老张不好意思跟人急，真翻脸。邻居们也很自觉，老张养活着一大家人，不容易。

***** translation
:PROPERTIES:
:CREATED: [2022-08-22 22:05:00 -05]
:END:

Old Zhang's craft of making moon cakes is first-class, that is his father's father handed down. Old Zhang does not like people to see the moon cakes, but he is not particularly guarded, for one thing, it is not good to prevent people coming and going; secondly, the old Zhang is embarrassed to be anxious with people, really turn the other cheek. Neighbors are also very conscious, the old Zhang feed a large family, not easy.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: cc675f57-f5d6-4289-8c49-a6ee93534d06
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：赵老师，今天跟您探讨一下“面子”问题。您能不能确切点儿说说，到底什么是面子？
男：按词典的解释，就是“表面上的形象；虚荣”。
女：这个解释挺负面的哈。中国人常说“死要面子活受罪”，可大家还是觉得面子不能不要。
男：也有人说，面子是每一个社会成员想为自己挣得的一种在公众中的个人形象。
女：这个解释我觉得更好。
男：仔细想想，其实咱们都挺顾面子的，比如说，在公众场合要干净、整洁、文明，给别人留下个好印象，不能丢人。
女：没错。
男：咱们中国人还认为有面子就有尊严，没面子就被人看不起，这是积极的一面。面子会使我们约束自己，规范自己，注意维护自己的形象。但因为要面子而使自己受委屈，甚至骗别人，就不好了。
女：您举个例子？
男：有这样一个故事。从前，有一个人，每次出去，都是酒足饭饱以后回来。妻子问他和什么人一起吃的饭？他说是朋友，大官，有钱人。妻子奇怪，家里从来没来过这样的客人呀。妻子想把这件事搞清楚。第二天丈夫出门后，她就跟上了。丈夫走遍全城也没有一个人和他说话，最后丈夫来到城东边安葬死人的地方，走到祭祀的人跟前，跟人家要剩下的食物。妻子看了很生气，心想：“丈夫是自己终身依靠的人，现在竟然这样。”一会儿，丈夫又高高兴兴地回来了，仍旧对妻子摆出一脸的高傲。这个故事没有讲结局，但我们可以想象，不管在什么时代，这个丈夫一定没有好前途。
女：这个故事像一幅画，给我们画出了一类人，他们不想劳动，只想过安闲舒适的生活，这种人还有个更大的问题，就是他们还想要面子。
男：对。
女：我觉得我们说的面子有时候还指公共面子，比如，我们都希望中国队在国际比赛中得到冠军，为国家争光。
男：没错。

**** 音频

fc5d5d4a-1434-46de-9145-99c1fe936ea6.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 5c22b646-d69e-48c7-a82d-f5975fbed9bf
:END:

***** 问题

女的认为哪种“面子”的解释更好？

****** 音频

47c6c99c-ba4c-4974-8863-68efbe6dcfa5.mp3

***** 选择

****** A

一个人天生的模样

****** B

实际不存在的光荣

****** C

努力取得的个人的公众形象

****** D

即使倒霆也得保持的好形象

***** 答案

C

**** 7
:PROPERTIES:
:ID: ee661273-4912-4d90-b5ad-f9bddcb1b1ee
:END:

***** 问题

面子的积极意义是什么？

****** 音频

b5814d68-d6aa-464f-8133-f30ea1aebc37.mp3

***** 选择

****** A

希望别人留下好印象

****** B

看不起不爱面子的人

****** C

在公共场合不能受委屈

****** D

为面子规范自己的行为

***** 答案

D

**** 8
:PROPERTIES:
:ID: ad3b5552-3421-4b5b-9a24-ed80c3b2870c
:END:

***** 问题

以下哪一项符合故事的情节？

****** 音频

47d1acf2-8228-4c7b-8032-ce5dc3564876.mp3

***** 选择

****** A

夫妻二人从来不和人来往

****** B

这个故事没有讲事情的结果

****** C

丈夫每天和达官贵人一起吃饭

****** D

丈夫自己在外吃饭妻孔很生气

***** 答案

B

**** 9
:PROPERTIES:
:ID: 55bcd8e5-2bd8-4a5f-90eb-90b897a43886
:END:

***** 问题

这个故事表现了一类人的什么特点？

****** 音频

779fbaf7-ef4f-4922-bf0f-13c86cce3c68.mp3

***** 选择

****** A

他们的生活像一张画儿

****** B

他们过着安闲舒适的生活

****** C

他们有比较大的心理问题

****** D

他们不想付出还想要面子

***** 答案

D

**** 10
:PROPERTIES:
:ID: 72584d97-c2ab-4ac5-983c-37f58de6047c
:END:

***** 问题

人们常说的面子还包括什么？

****** 音频

25985c08-d8db-4c82-a7cf-aa7c3637344f.mp3

***** 选择

****** A

集体、公众的面子

****** B

每个人的言行举止

****** C

不能让别人看不起

****** D

有自尊心不做丢脸事

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

猎能发现老鼠的踪迹

***** B

猎需要牛磴酸提高嗜克

***** C

猎的体内含有较多牛磺酸

***** D

猎因为自己的需要而吃鱼和老鼠

**** 段话

表面看，它是一个普通得不能再普通的包裹，里面装的是家乡的土特产，但在我的眼里，它珍贵着呢。它经过了母亲的双手，又途经千里，来到了我的面前。它沾染着故乡的气息，满载着母亲无声的爱意。

**** 答案

C

*** 2

**** 选择

***** A

母亲常常给我寄包衣

***** B

包啧里的东西很值钱

***** C

包商是母亲亲手打理的

***** D

母亲亲自给我带了包啧

**** 段话

清晨，梦中的我被父亲叫醒，“走，晨练去！”我和父亲并排跑着，一抬头发现父亲竟然有了一丝白发。我有些心酸。他总是那么勤奋，那么忙碌，为家庭、为单位操劳。作为女儿，我懂得父亲的付出、父亲的期望。

**** 答案

D

*** 3

**** 选择

***** A

我特别不喜欢晨练

***** B

我胃有点儿不舒服

***** C

父亲的胡须都白丁

***** D

我理解勤奋的父亲

**** 段话

家是什么？家是一个可以放松的地方，说话做事都不必小心；家是一个可以疗伤的地方，伤了痛了都可以在家中得以缓解。回到家，可以听几首音乐，可以饮一杯清茶，让心情重归舒畅。

**** 答案

D

*** 4

**** 选择

***** A

出门在外都应该惦记家

***** B

回家时心中会充满喜悦

***** C

受了伤还是回家休息好

***** D

在家中可以改变坏心情

**** 段话

“诚”指诚实诚恳，“信”即信用信任。“诚”主要指“内诚于心”，“信”主要指“外信于人”。“诚”“信”组合在一起，就形成了一个内外兼备，具有丰富内容的词汇，即诚实无欺，讲求信用。

**** 答案

D

*** 5

**** 选择

***** A

“信“主要指对人要诚悟

***** B

“诚“主要指对人要守信

***** C

“诚“和“信“是同义词

***** D

“诚信“指不欺骗，守信誉

**** 段话

老张做月饼的手艺是一流的，那是他父亲的父亲传下来的。老张做月饼不喜欢别人看，可他也不特别防范，一来是人来人往地不好防；二来是老张不好意思跟人急，真翻脸。邻居们也很自觉，老张养活着一大家人，不容易。

**** 答案

B

