* 听力

** 1

*** 1

**** transcript

1997年，不安分的李长风突发奇想，宣布要造汽车。从这一年起，中国家用轿车的拥有量连年翻番。众多专家纷纷预言，中国的家用轿车时代已经到来。

***** translation

In 1997, the restless Li Changfeng had a sudden idea and announced that he wanted to build a car. From this year's small self, the ownership of China's domestic coupe has doubled year after year. Many experts have predicted that the era of China's household coupe has come.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

在我们的现实生活中，“用脚投票”原理极其简单：你搞不好、不公平，我就走人。例如，当股东们发现经理没有把企业经营好，企业的资产有可能贬值时，他们就会抛售股票，从而与该企业脱离关系。

***** translation

In our reality, the principle of "voting with one's feet" is extremely simple: if you don't do a good job, if it's not fair, I'll leave. For example, when shareholders find out that the manager is not running the business well and that the business's assets are likely to fall in value, they will sell their shares and disassociate themselves from the business.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

在着手进行休闲、观光方面的具体投资时，他发现：孤立的某一个娱乐项目难以吸引很多人，只有当一个地方风景优美、交通便利、饭店高档舒适、娱乐项目众多时，才可能吸引更多的游客。

***** translation

In embarking on leisure and sightseeing to the point of specific investment, he found: isolated a particular entertainment project is difficult to attract many people, only when a place with beautiful scenery, convenient transportation, high-grade hotel comfort, entertainment projects are numerous, it is possible to attract more tourists.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

在超市，如果顾客结账需要排队等候很长时间，他们就会失去耐心，一走了之，但如果开设很多收款台却少有人光顾，则又会导致成本提高。“排队模型”就试图为这个问题找到一个最好的解决方案。

***** translation

In supermarkets, if customers have to wait for a long time in the checkout line, they will lose patience and leave, but if there are many checkout counters but few people visit them, it will lead to higher costs. "The Queuing Model is an attempt to find the best solution to this problem.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

上中学时，爱因斯坦很喜欢数学。一次，叔叔给他讲了勾股定理的来历后，问爱因斯坦能不能试着证明它。爱因斯坦决定试一试。眼看着运算的草稿纸越积越厚，找到正确的证明方案却并非易事，但他没有动摇，二十多天后，他终于拿出了正确方案。

***** translation

When he was in high school, Einstein loved mathematics. Once, his uncle told him about the origin of the tethered strand theorem and asked Einstein if he could try to prove it. Einstein secondly decided to give it a try. Seeing the thickening of the draft paper of arithmetic, finding the correct proof scheme was not an easy task, but he did not waver, and after more than twenty days, he finally came up with the correct scheme.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: cab7814a-fc4c-4f94-8f95-604e77f78054
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：欢迎经济学者纪老师做客网络空间。纪老师，您好，我们常看到“分享经济”这个词，您能否详解一下分享经济的由来？
男：最早提出分享经济的是美国经济学家威茨曼撰写的《分享经济》一书。作者针对的是 20 世纪 70 年代出现的“经济滞胀”。作者认为产生经济滞胀的原因是工资结构不合理，提出以分享制度代替工资制度。在实践中，分享经济形成了两种不同的模式。一种是欧美的通过股权制度让工人参与企业收入分配的模式，另一种是日本的通过企业文化和管理制度让员工参与企业管理的模式。
女：在我们的生活中，分享经济有哪些呈现方式？
男：最典型的是有偿分享模式、对等分享模式、劳务分享模式、众筹分享模式。有偿分享是指把自己剩余或暂时不用的物品分享给别人使用，收取租金。
女：比如说我去旅游，不想住酒店，我就上网查找住宿信息，一旦和房主达成一致，就可以实地入住、网上结算了？
男：对，就是这样。
女：对等分享模式呢？
男：顾名思义，就是双方互相交换使用财产，不向对方支付报酬。
女：我们的“城乡儿童互换生活环境体验成长快乐”活动算不算？
男：当然算，最近几年这种活动已经成为许多学校教育的重要内容，它分享的不仅仅是双方对等交换的环境，还有双方情感和文化价值的体验。
女：劳务分享模式就是对大量没有充分利用的劳务资源的分享吧？
男：是啊，现代分享经济中，人们不仅可以出售自己多余的物品，还可以出售多余的时间。美国有一家创业公司，凭 1 小时送货上门服务取得了成功，它就是通过互联网，把分散在社区居民中的剩余时间利用起来，实现一小时送达的承诺。
女：众筹分享模式就是指大众筹资或群众筹资了吧？
男：对，当然现代众筹是指用互联网平台进行资金筹集。而且，现代众筹筹资目标也包含了分享投资对象，不纯粹是为了筹集资金。

*** 音频

78d9aacc-a3b2-42a0-9c73-d7803095b125.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 3d586efd-b24e-4852-8f81-ec4b50f7f0ee
:END:

***** 问题

“分享经济”是在什么背景下产生的？

***** 音频

61946bc2-51aa-42a0-9add-b4de8f1bb187.mp3

***** 选择

****** A

《分享经济》一书问世以后

****** B

工人提出改良工资制度之后

****** C

欧美和日本经济模式创新的背景下

****** D

 20世纪70年代出现经济滞胀以后

***** 答案

D

**** 7
:PROPERTIES:
:ID: 5b79f96e-540b-48cb-8f0b-df90fc7444b4
:END:

***** 问题

“有偿分享模式”的主要特点是什么？

***** 音频

38aae85b-6626-4be4-83d4-cd6b8407a4f3.mp3

***** 选择

****** A

使用者需要付费

****** B

交卖掉不用的东西

****** C

用不了的东西就送人

****** D

能够租赁就不要购买

***** 答案

A

**** 8
:PROPERTIES:
:ID: bc7dba9d-cf28-4d21-bd6c-3f28be05c4c4
:END:

***** 问题

“对等分享模式”的主要特点是什么？

***** 音频

245222ec-6811-4c26-ae4a-19ad984f70c2.mp3

***** 选择

****** A

城乡儿童可互通有无

****** B

无偿为使用者提供服务

****** C

着重于情感的交流体验

****** D

双方交换使用分享内容

***** 答案

D

**** 9
:PROPERTIES:
:ID: a7e76b4a-d831-4691-9329-9fa596ed0b8a
:END:

***** 问题

“劳务分享模式”的主要特点是什么？

***** 音频

33834bf3-635e-449d-b1ea-9a85cbc4da4a.mp3

***** 选择

****** A

以最快速度送货上门

****** B

合理利用零星的人工

****** C

对快递行业进行革命

****** D

答应的事情就要兑现

***** 答案

B

**** 10
:PROPERTIES:
:ID: 6aad0d78-c10f-4a09-a620-9910a8172eea
:END:

***** 问题

“众筹分享模式”的主要特点是什么？

***** 音频

545f6c97-e94e-4be0-beb2-2f6df8ecf947.mp3

***** 选择

****** A

目的就是筹集资金

****** B

及时反馈投资情况

****** C

包括分享投资对象

****** D

注重互联网平台建设

***** 答案

C

