* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 92d7dc4f-c4cc-4223-aded-aee49979f58a
:END:
**** 对话
***** 转录
女：学校里有好几家小超市，你们怎么都喜欢去那家？[[file:80a18e85-df0c-4e32-a79e-63cc628ef89a.mp3][(audio)]]
男：那家服务好，品种齐全，价格合理。[[file:7256a525-30f7-4eea-97b6-3c545dcb92ff.mp3][(audio)]]
***** 音频
0a72b082-19a7-470d-9024-f4a9cfd3f07a.mp3
**** 问题
***** 转录
下列哪项是那家超市的优点？
***** 音频
a3626209-6422-48fa-bb1d-24dede87a5c5.mp3
**** 选择
***** A
环境好
***** B
品种多
***** C
价格最低
***** D
老板很帅
**** 答案
B
*** 2
:PROPERTIES:
:ID: 16ed51a2-69a6-469b-b68b-68789c22ab5d
:END:
**** 对话
***** 转录
男：那两家店生意都那么差，你干吗不挤垮他们算了？[[file:d255e174-62dc-4afd-b70e-848e8c68998c.mp3][(audio)]]
女：我把其他两家都挤垮了，不见得是件好事，因为别人一看这么大的地方只有我一家，新店就可能会出现。[[file:2ea76270-1e10-40ec-9a72-c3b7ef91b53a.mp3][(audio)]]
***** 音频
426c4fed-f72e-46cb-aaea-70c8f8133fac.mp3
**** 问题
***** 转录
女的为什么不挤垮对手？
***** 音频
4150e1b6-fd3c-4c9d-85de-be7c4cfaa4b3.mp3
**** 选择
***** A
大家关系很好
***** B
对手力量很强
***** C
不愿出现新对手
***** D
她没有经营能力
**** 答案
C
*** 3
:PROPERTIES:
:ID: f9de0fc7-f4a5-43f5-a4dd-4b31cd7d2f21
:END:
**** 对话
***** 转录
女：真不知道怎么才能把这些孩子教好！[[file:f9d8f6d6-d873-411f-b196-6c41611114d9.mp3][(audio)]]
男：你要先跟他们培养感情，然后再培养他们对钢琴的兴趣。[[file:92338885-e493-423f-9b2a-978843690835.mp3][(audio)]]
***** 音频
6d4738f4-bbe9-4a70-bfd5-c1316d7ede23.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
1c1ee613-5e29-4241-9ef3-d2dadd052656.mp3
**** 选择
***** A
小孩子确实很难教
***** B
要先跟孩子相处好
***** C
要让孩子不断练习
***** D
女的不适合做老师
**** 答案
B
*** 4
:PROPERTIES:
:ID: 389d864d-018b-45c7-809a-f4181fbff057
:END:
**** 对话
***** 转录
男：我觉得这套公寓不错，大小合适，价钱便宜，下面还有个小商店，买东西很方便。[[file:19c2b763-1917-4e6f-9660-984dc2a22bf2.mp3][(audio)]]
女：嗯，房东看起来也很热心。[[file:9ab435ca-0c78-4015-9178-c06972aae1a1.mp3][(audio)]]
***** 音频
2caeb95d-5ecd-42c0-9946-c54b2b242a56.mp3
**** 问题
***** 转录
他们在谈论什么？
***** 音频
e7daa055-9269-4ec7-8a1d-262ad1a93308.mp3
**** 选择
***** A
房东
***** B
买房
***** C
开店
***** D
租房
**** 答案
D
*** 5
:PROPERTIES:
:ID: 20c24c97-4231-4394-b177-d63a0587de27
:END:
**** 对话
***** 转录
女：这产品挺好的，就是价格高了点儿。[[file:3e84039a-f761-490f-912a-87a5f63d5905.mp3][(audio)]]
男：我们的质量肯定没话说。您要多少？如果量大的话，可以打八折。[[file:c9906cc1-c983-43f1-85e6-0b262bfaab00.mp3][(audio)]]
***** 音频
6f04ee15-ef75-4779-8718-921fd88038ab.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
19af80df-c309-456f-bdd9-3a8bea1113de.mp3
**** 选择
***** A
产品质量不好
***** B
产品价格不高
***** C
价格可以[[wikidata:L1144566-S1][商量]]
***** D
不能买得太少
**** 答案
C
*** 6
:PROPERTIES:
:ID: 2d6ad704-98f3-43f6-8f98-88b894911e47
:END:
**** 对话
***** 转录
男：合同里对付款方式是怎么约定的？[[file:00842122-10c8-45fb-acdd-a72af3e0ff14.mp3][(audio)]]
女：货到后银行转账付款，对方三天内开具发票。[[file:fd14d14d-2436-42d6-bbf1-c55b1d0079f4.mp3][(audio)]]
***** 音频
cef4a386-aa74-42e3-818f-e19e8aec3f43.mp3
**** 问题
***** 转录
双方约定如何付款？
***** 音频
c0a5445b-6157-4e15-8edd-83d95c0c2f71.mp3
**** 选择
***** A
银行代付款
***** B
货到后付款
***** C
签合同时付款
***** D
开发票后付款
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
女：今天来上班，真是累死我了！
男：太阳从西边出来了，你不是从不锻炼身体吗？
女：没办法，路上太堵，地铁又挤。
男：你也该动动了。
***** 音频
20cd739d-3e31-40d2-8e5f-5b99a81aae19.mp3
**** 问题
***** 转录
女的今天最可能是怎么来的？
***** 音频
2a10b687-134c-41a6-95d7-348160c010c5.mp3
**** 选择
***** A
打的
***** B
走路
***** C
坐地银
***** D
坐公共汽车
**** 答案
B
*** 8
**** 对话
***** 转录
男：妈，我出去买块电池。
女：拿把伞吧。
男：天气这么好，要什么伞啊？
女：万一下雨呢？天气预报是说今天有雨的。
***** 音频
5026331e-683d-49de-b97c-45fce484e6fa.mp3
**** 问题
***** 转录
女的让男的干什么？
***** 音频
adf08ba7-6345-4326-8369-bb900d68fa8b.mp3
**** 选择
***** A
带伞
***** B
买伞
***** C
买电池
***** D
看天气预报
**** 答案
A
*** 9
**** 对话
***** 转录
女：这孩子真乐观。
男：乐观多好啊！
女：我就是觉得他乐观得有点儿过分了，整天笑得跟傻子似的。
男：再怎么说，开心也比发愁好。
***** 音频
01788df7-477c-438d-aed0-52612aee1abd.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
9dc08a4f-493a-4028-aeba-6ab4353a87ee.mp3
**** 选择
***** A
乐观是优点
***** B
这孩子很傻
***** C
孩子应该发愁
***** D
孩子没有烦恭
**** 答案
A
*** 10
**** 对话
***** 转录
男：小青，这次项目你做得非常好，给你半个月假期休息休息吧。
女：老板，能换一个奖励吗？
男：怎么，你不想休假？你不是一直说想跟男朋友去旅行吗？
女：对，我是想去旅行，但我觉得现在时间不合适。
***** 音频
c6fd9a1f-8a21-4b05-a842-f0bfdf7154b8.mp3
**** 问题
***** 转录
老板为什么要给小青放假？
***** 音频
343d7b77-6a0c-48b8-89f8-5e3c4e4aa612.mp3
**** 选择
***** A
小青生病了
***** B
小青想去旅行
***** C
小青工作完成得好
***** D
全公司现在都放假
**** 答案
C
*** 11-12
**** 对话
***** 转录
女：建伟，好久不见了！
男：是啊，有大半年了吧？
女：听说现在你那家书店开得挺红火的，最近都有媒体来采访你了。
男：嗯，还不错。除了书，我还顺便卖点儿文具、电池、小日用品。虽然每件商品的利润都并不高，但诚信经营、薄利多销，现在生意越做越好了。
女：大学里原来还有三家书店吧？
男：对，那三家的经营空间越来越小了，三家的营业额加起来还不如我一家高。
***** 音频
c0f23e03-cc42-4251-8597-0194a8621fe4.mp3
**** 题目
***** 11
****** 问题
******* 转录
建伟现在主要做什么？
******* 音频
f3ca8aa1-a6e3-4071-a8b7-e64bd74c879c.mp3
****** 选择
******* A
卖书
******* B
卖电器
******* C
做媒体
******* D
做记者
****** 答案
A
***** 12
****** 问题
******* 转录
关于另外三家书店，下列哪项正确？
******* 音频
35822a66-7acf-4ede-9022-db4fe86002de.mp3
****** 选择
******* A
生意越来越好
******* B
常被媒体采访
******* C
占地面积很小
******* D
卖出的书不多
****** 答案
D
*** 13-14
**** 段话
***** 转录
体育运动对性格发展有什么影响？是促进还是妨碍？这是一个学术问题，也是一个让很多人困惑的现实问题。本文以针对 300 人进行的调查为基础，采用文献分析的方法，梳理了体育运动对性格发展促进和妨碍的两方面证据。然后,从三个角度分析了产生分歧的原因。最后,在此基础上对未来研究做出几点展望。
***** 音频
0b034252-c841-4816-8f9c-b748aabc603d.mp3
**** 题目
***** 13
****** 问题
******* 转录
这段话可能来自于什么？
******* 音频
bc1aab2e-35aa-4c04-ba52-690635c75bed.mp3
****** 选择
******* A
小说
******* B
新闻
******* C
论文
******* D
神话
****** 答案
C
***** 14
****** 问题
******* 转录
这段话主要谈论什么？
******* 音频
0f40dc18-9287-4506-bf09-fcc1d3158342.mp3
****** 选择
******* A
体育运动妨碍性格发展
******* B
体育运动促进性格发展
******* C
体育运动与性格发展无关
******* D
体育运动对性格发展的影响
****** 答案
D
* 阅读
** 第一部分
*** 段话
心理学上有一种问题叫“自我妨碍”，意思是人的意识与行为不一致。比如一个人明明很喜欢自己的工作，但却忍不住要破坏工作环境或者工作[[gap][15]]，最后造成无法正常工作的结果。[[gap][16]]这一问题的原因可能在于，以往的成功和别人的关注为这个人设置了很高的标准，而他害怕无法继续保持这样的成绩，就[[gap][17]]不再好好工作。有这种问题的人，以往越是表现好，就越遢自己，越害怕下次不能做到这个程度，形成一个恶性循环。如果发现自已有这样的问题，那就[[gap][18]]。
*** 题目
**** 15
***** 选择
****** A
对手
****** B
对方
****** C
对象
****** D
对待
***** 答案
C
**** 16
***** 选择
****** A
促进
****** B
促使
****** C
改进
****** D
导致
***** 答案
D
**** 17
***** 选择
****** A
干脆
****** B
必然
****** C
全面
****** D
未必
***** 答案
A
**** 18
***** 选择
****** A
应该赶快辞职
****** B
尽快去看心理医生吧
****** C
别耽误工作了
****** D
注意锻炼身体吧
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: d02a1027-b9f3-4d84-8894-cd7541c4d717
:END:
**** 段话
商业领域其实和自然界一样，自然界中的生物，适当有一些“敌人”，会促使它们生长得更好；同样，对手并不会妨碍我的发展，反而会促进经营，让我获得更多利益。所以，我不但不想挤垮对手，在需要的时候反而还会帮助他们。
**** 选择
***** A
商界是自然界的一部分
***** B
敌人中也有乐于助人的人
***** C
对手之间可能会相互促进
***** D
对手不一定能被挤垮
**** 答案
C
*** 20
:PROPERTIES:
:ID: eaca383e-4589-4893-8807-93f2337e711c
:END:
**** 段话
梅瑞是美国一家著名的大型百货公司。该公司的购物大厅里有一个咨询服务台，其主要职责是，如果消费者在梅瑞公司没买到自己想要的商品，咨询台的工作人员会介绍他到另一家有这种商品的商店。梅瑞公司这一违反常规的做法，不仅获得了顾客的好感，也赢得了对手的信任与尊重。
**** 选择
***** A
梅瑞是美国最大的一家百货公司
***** B
梅瑞公司会把顾客介绍给竞争对手
***** C
梅瑞公司与对手之间的竞争非常激烈
***** D
梅瑞公司的这种营销手段让人难以接受
**** 答案
B
*** 21
:PROPERTIES:
:ID: f5dfd45c-5849-4fbe-bf6a-3f1a3f8fdeae
:END:
**** 段话
女人逛超市从来不怕累，为了找到喜欢的商品，跑断腿都不怕；找到之后，还会根据价格反复比较，精挑细选。有时候，就算没有找到自己喜欢的商品，女人也会大包小包，买很多其他东西回来。而男人去超市时普遍都目标明确，他们清楚自己到底要买什么，直接把购物车推到该商品的货架前，不管贵不贵，拿起来就往购物车里装。他们不愿意比较价格，也不会去寻找打折商品。
**** 选择
***** A
女人逛超市常常会跑断腿
***** B
女人不愿意寻找打折商品
***** C
在超市男人负责推购物车
***** D
男人买东西一般比较干脆
**** 答案
D
*** 22
:PROPERTIES:
:ID: 05cf3258-8396-45bb-b293-37d93e7bd17f
:END:
**** 段话
有句话叫风险与收益并存。你想追求高收益高利润，就一定会有相对较大的风险，没有什么投资是稳赚不赔的。要投资，首先要做好承担亏损的思想准备。尤其是初期投资，最高目标就是保值不亏，当然，这个“不亏”的意思是说，不管外面的市场怎久变化，我们用来投资的钱，还值原来的那么多。
**** 选择
***** A
投资多少，就能得到多少
***** B
所有的投资都可能有风险
***** C
投资的钱不值原来那么多
***** D
初期投资一定会有亏损
**** 答案
B
** 第三部分
*** 23-25
**** 段话
因为工作需要，我利用业余时间报了个口译班。班里有一位老师，大约30岁，口译功夫了得。后来才知道，她大学学的是历史，本职工作是一家公司的公关部经理，跟英语没什么关系，儿子已经5岁，她每天要上班、做家务、带孩子。
打开她的博客，已经更新了500多页，全部都是每天她自己做口译练习的文章，平均每天两篇长的一篇短的，她坚持做这件事已经快10年了，非专业出身的她因为爱好英语而一直努力。我对她表示钦佩，她说，10年前，她曾经看到一份调查报告，一个人如果要掌握一项技能并成为专家，需要不间断地练习1万个小时。当时她算了一笔账，如果每天练习5个小时，每年300天的话，那么需要近7年的时间。
拨头士乐队在成名前已举办过1200场音乐会，比尔·盖茨在发家前已做了7年的程序员。
为什么你工作了10年还只是一名小职员？为什么你在家做了7年的饭，也没变成特级大厨？那是因为，你没有投入精力和热情来练习一项技能。每天上班只是看报纸、上网、应付琐碎的任务，每天做饭只是为了让家庭正常运转，并没用专业的眼光看待这件事。
生命中的下一个7年，下一个1万个小时，你打算怎样度过？
**** 题目
***** 23
****** 问题
关于口译老师，下列哪项正确？
****** 选择
******* A
她本来是个历史老师
******* B
她做口译老师是兼职
******* C
她学英语是工作需要
******* D
儿子经常帮她做家务
****** 答案
B
***** 24
****** 问题
上文提到披头士乐队、比尔·盖茨是为了证明：
****** 选择
******* A
掌握技能需要坚持练习
******* B
7年之后才可能取得成功
******* C
名人都了解7年规则
******* D
办1200场音乐会需要7年
****** 答案
A
***** 25
****** 问题
上文主要想告诉我们：
****** 选择
******* A
应该发展自己的爱好
******* B
要利用业余时间学习
******* C
怎样才可以成为专家
******* D
怎么提升自己的职位
****** 答案
C
*** 26-28
**** 段话
春节将至，京城各大商场又开始忙着发广告，准备打折促销、送积分送礼品、延长营业时间等，希望在春节“黄金周”里大赚一笔。这就是人们常说的“假日经济”。
其实，所谓的“假日经济”并不存在。
去年12月31日至今年1月2日的元旦假期中，各大商场的确人山人海，营业额创纪录。元旦假期一过，商场客流就下降，营业额甚至不到元旦期间的四分之一。此情此景给人们一种错觉：“假日经济”就像强心针，可以给现在不景气的商场带来繁荣，促进销售。
但大部分人没有注意到，在商场假日销售额保持增长的同时，利润并没有明显增加，因为商场的热闹基本都是由各种促销活动带来的。另外，顾客通常有固定的消费预算，在一定时期内，用于消费的金额实际上是有一定限度的，假期买得多了，其他时间自然就会减少购物行为。所以说，假期打折等促成了人们特定消费心理的形成，但更多的只是影响了顾客购物的时间调整，而并不能从根本上改变商业销售的旺淡规律。从某种意义上说，一年两三次的“假日经济”对商家长期稳定的发展并不利。商家应该多想想，节日之后该怎么办。
**** 题目
***** 26
****** 问题
上文没有提到下列哪种类型的促销活动？
****** 选择
******* A
全场六折
******* B
买二送一
******* C
购物返现
******* D
通宵营业
****** 答案
C
***** 27
****** 问题
关于“假日经济”，下列哪项正确？
****** 选择
******* A
是一种针的牌子
******* B
给商场带来表面的繁润
******* C
会使商家利润明显增加
******* D
有利于商家的长期发展
****** 答案
B
***** 28
****** 问题
作者对“假日经济”的态度是：
****** 选择
******* A
高兴的
******* B
赞同的
******* C
反对的
******* D
后悔的
****** 答案
C
* 书写
** 第一部分
*** 29
**** 词语
***** 1
对
***** 2
你不应该
***** 3
她的
***** 4
拒绝
***** 5
合理要求
**** 答案
***** 1
对她的合理要求你不应该拒绝。
*** 30
**** 词语
***** 1
我们的
***** 2
对手
***** 3
不见得
***** 4
会妨碍
***** 5
发展
**** 答案
***** 1
对手不见得会妨碍我们的发展。
***** 2
我们的发展不见得会妨碍对手。
*** 31
**** 词语
***** 1
商业领域
***** 2
已经
***** 3
被
***** 4
应用到
***** 5
这个理论
**** 答案
***** 1
这个理论已经被应用到商业领域。
