* Text

** title

培养对手

** content

建伟在大学的一座么寓楼里开了一家书店，顺便荬点儿文具、电池、小日用品等。一年多来，虽然每件商品的利润都并不高，但他诚信经营，薄利多销，使书店生意越来越红火，甚至成为了媒休的采访对象。这个大学里另外还有家书店，由于受到了建伟书店的影响，这三家书店的经营空间越来越小，三家的营业额加起来还不如他一家高。建伟成了这里的“书店老大”。

这时，许多亲朋好友便建议他干脆把另三家书店挤垮，垄断这个市场。可建伟大但没有去挤垮对手，反而还经常帮助三家书店搞一些营销活动，对于一家快要倒闭的书店，他还主动热心地借给其资金，想办法让他继续经营下去。

有人问他：“你怎么这么傻？就让他们倒霉，不好吗？！”

建伟说，我是在保持这一地区图书市场的“生态平衡”。商业领域其实和自然界一样，自然界中的生物，适当有一些“敌人”，会促使它们生长得更好；同样的，对手并不会妨碍我的发展，反而会促进经营，𧮪我获得更多利益。一个原因是这样能创造让客户有所比较和优中选优的购物环境，通过比较，学生们才知道我的书店服反好、品种优、价格合理。如果只有我一家书店了，学生们没有了比较，价格定得再低也会认为我的书价高，万一他们自己跑到其他图书市场去“货比三家”，那我的生意就完了。还有一个很重要的原因，就是维持这种书店饱和的“生态”，避免更多、更强的对手来“插足”。是把其他三家都挤垮了，不见得是件好事，因为别人一看这么不的地方只有我一家书店，新的书店可能就会出现，弄不好来一个比我更强的对手。所以，为了保持目前这种经营的“生态平衡”，我要继续把对手培养好。

** 生词

培养 / pei2 yang3 / to foster, to train ;
对手 / dui4 shou3 / opponent rival ;
翁寓 / gong1 yu4 / aparment, flat ;
文具 / wen2 ju4 / stationery ;
电池 / dian4 chi2 / battery, cell ;
日用品 / ri4 yong4 pin3 / articles of everyday use, daily necessities ;
利润 / li4 run4 / profit ;
诚信 / cheng2 xin4 / honest, in good faith ;
媒体 / mei2 ti3 / media, mass media ;
对象 / dui4 xiang4 / target, object ;
营业 / ying2 ye4 / to do business, to operate ;
额 / e2 / specified number, sum, volume or amount ;
不如 / bu4 ru2 / to be not as good as, to be inferior to ;
干脆 / gan1 cui4 / simply, just ;
挤 / ji3 / to squeeze out, to push out ;
垮 / kua3 / to collapse, to break down ;
垄断 / long3 duan4 / to monopolize ;
倒闭 / doa3 bi4 / to close down, to go bankrupt ;
热心 / re4 xin1 / enthusiastic, earnest ;
资金 / zi1 jin1 / capital, fund ;
傻 / sha3 / stupid, foolish ;
倒霉 / dao3 mei2 / having bad luck, unlucky ;
生态 / sheng1 tai4 / ecology ;
商业 / shang1 ye4 / business, commercee ;
领域 / ling3 yu4 / field, domain, realm ;
适当 / shi4 dang4 / proper, adequate ;
促使 / cu4 shi3 / to urge, to spur, to prompt ;
生长 / sheng1 zhang3 / to grow ;
妨碍 / fang2 ai4 / to hinder, to impede ;
促进 / cu4 jin4 / to promote, to accelerate ;
利益 / li4 yi4 / benefit, interest ;
合理 / he2 li3 / reasonable ;
万一 / wan1 yi1 / in case, if by any chance ;
维持 / wei2 chi2 / to keep, to mantain ;
饱和 / bao2 he2 / to be saturated, to be filled to capacity ;
不见得 / bu2 jian4 de2 / not necessariliy, may not ;

** 专有名词

建伟 / jian4 wei3 / Jianwei, name of a person ;

** source


改编自《小故事不道理》，作者：宗先哲
* 练习

** 1
:PROPERTIES:
:ID: 5c59dbab-1d1a-45ff-a840-29d6644845b1
:END:
*** 选择
**** 1
电池
**** 2
妨碍
**** 3
利润
**** 4
培养
**** 5
资金
**** 6
不见得
*** 题目
**** 1
***** 句子填空
太晚了，我先走了，不[[gap]]您休息。
***** 答案
****** 1
妨碍
**** 2
***** 句子填空
我的手机[[gap]]不行了，得去换一块。
***** 答案
****** 1
电池
**** 3
***** 句子填空
让他们俩在一起多待一会儿吧，[[gap]]一下感情。
***** 答案
****** 1
培养
**** 4
***** 句子填空
我们这个是蒲利多销，本来就没有多少[[gap]]。
***** 答案
****** 1
利润
**** 5
***** 句子填空
你们上次赢了，这次就肯定也能赢吗？我看[[gap]]。
***** 答案
****** 1
不见得
**** 6
***** 句子填空
这次活动，学校为我们提供了[[gap]]支持。
***** 答案
****** 1
资金
** 2
*** 1
:PROPERTIES:
:ID: f26ad7f1-bc5e-45d3-93aa-4843ac07ee3f
:END:
**** 句子填空
她的汉语说得很好，我的发音[[gap]]她。
**** 选择
***** A
不如
***** B
没有
**** 答案
A
*** 2
:PROPERTIES:
:ID: 3f858f93-3a1a-43df-b65f-146318b4feda
:END:
**** 句子填空
我建议你别去看那个演出，我已经看过了，很[[gap]]！
**** 选择
***** A
倒霉
***** B
糟糕
**** 答案
B
*** 3
:PROPERTIES:
:ID: 69b56f63-4aa3-421c-86f1-9a38a0440c01
:END:
**** 句子填空
最后老师的话[[gap]]他改变了主意。
**** 选择
***** A
促进
***** B
促使
**** 答案
B
*** 4
:PROPERTIES:
:ID: 869b2e59-3ae6-4f4e-b031-6033eaf54078
:END:
**** 句子填空
阳台，卧室的整体感觉都不错。但是桌子摆这儿，明显不[[gap]]。
**** 选择
***** A
合理
***** B
有理
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:

*** 1

**** 词语

不如

**** 句子

听说展览馆最近🟦有个🟦小人书展，🟦我们周末去🟦看看吧。

**** 答案



*** 2

**** 词语

干脆

**** 句子

他🟦上周🟦迟到，🟦这周🟦不来了？！

**** 答案



*** 3

**** 词语

万一

**** 句子

🟦你🟦小心一点儿，🟦受伤就🟦麻烦了。

**** 答案



*** 4

**** 词语

不见得

**** 句子

大家🟦都选的🟦就🟦是🟦最好的。

**** 答案



* 扩展

** 词语

*** 1

**** 话题

经济

**** 词语

发票
收据
支票
欠
税
市场
执照
柜台
商品
优惠
付价还价
兑换
投资
分配

** 题

*** 1

**** 句子

这是找您的钱，这是🟨，请拿好。

**** 答案



*** 2

**** 句子

交🟨是每个人的义务。

**** 答案



*** 3

**** 句子

我不喜欢在小商品市场买东西，因为我不会🟨。

**** 答案



*** 4

**** 句子

将军把自己的食品🟨给了身边的每一个士兵。

**** 答案


* 注释
** （三）词语辨析
*** 挤——拥挤
**** 做一做
***** 1
****** 句子
所有的事都[[gap]]在这一个星期了。
****** 答案
******* 1
******** 挤
1
******** 拥挤
0
***** 2
****** 句子
由于人群[[gap]]，有人受了伤。
****** 答案
******* 1
******** 挤
0
******** 拥挤
1
***** 3
****** 句子
他假装伤心[[gap]]，出了两滴眼泪。
****** 答案
******* 1
******** 挤
1
******** 拥挤
0
***** 4
****** 句子
周末这家商场里虽然人很多，但并不[[gap]]。
****** 答案
******* 1
******** 挤
1
******** 拥挤
1
