* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 584258e3-a670-468a-8062-8fc66f4ddcf6
:END:
**** 对话
***** 转录
女：鸟儿最重要的特征是什么？是有翅膀会飞？还是吃昆虫？[[file:a058d806-3f07-4eb4-ae5b-17bc54bfc427.mp3][(audio)]]
男：区分鸟儿和其他动物的唯一特征就是羽毛。[[file:4e50d0f4-ebb2-484a-8e19-d5073dfb1a48.mp3][(audio)]]
***** 音频
d7177f9c-d6cc-48c0-a665-51b71aa5f669.mp3
**** 问题
***** 转录
鸟儿最重要的特征是什么？
***** 音频
d3f5397b-c864-4d18-9270-21f0734e8b37.mp3
**** 选择
***** A
会飞
***** B
有翅膀
***** C
有羽毛
***** D
吃昆虫
**** 答案
C
*** 2
:PROPERTIES:
:ID: b2d5b7a6-ee11-452e-bf24-c0036c84f481
:END:
**** 对话
***** 转录
男：妈，我今天晚上又得加班，估计 11 点以后才能到家。[[file:f4c3240a-86d9-41d5-96f7-f9946c5c7075.mp3][(audio)]]
女：哎呀，老这样下去怎么行啊……你得爱惜身体！[[file:fc5de7d6-86e2-47e8-aff5-47eb5c6108d2.mp3][(audio)]]
***** 音频
ab76ba17-3d1c-42ff-8b5c-d68073f71280.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
0c1625b4-2d9a-4010-be06-c2c34c38b750.mp3
**** 选择
***** A
高兴
***** B
担心
***** C
后悔
***** D
生气
**** 答案
B
*** 3
:PROPERTIES:
:ID: 0c6b48d4-a44c-4b06-b866-f10ecbf82946
:END:
**** 对话
***** 转录
女：年纪轻轻的，总这么把自己关在家里，不接触社会，怎么行？[[file:7ad862a2-153c-4369-9921-79a14dc1d7b6.mp3][(audio)]]
男：可我就是不愿意出去工作，家里又不是没钱养我？[[file:25c0ecd9-f92f-4374-a396-4590f19d9a6d.mp3][(audio)]]
***** 音频
4f4a22d2-bbfb-4a68-b3c5-2d4ae387454e.mp3
**** 问题
***** 转录
关于男的，下列哪项正确？
***** 音频
ddf3005b-62dd-4db8-aee3-a3fdeb99a4ca.mp3
**** 选择
***** A
没钱了
***** B
退休了
***** C
生病了
***** D
不想工作
**** 答案
D
*** 4
:PROPERTIES:
:ID: ee06bc01-fb64-4caf-b4dc-e4a22f6e49c8
:END:
**** 对话
***** 转录
男：我觉得他挺好的，你怎么就不喜欢他呢？[[file:2e423b37-6175-4d10-97d3-3a6546801eb9.mp3][(audio)]]
女：一个大男人，天天随身带着把梳子，碰到镜子就梳来梳去的，我看不惯。[[file:afa5e61a-8a80-42d9-97c3-92ad29dc792b.mp3][(audio)]]
***** 音频
9ec11b51-e22e-41fb-85a7-a573d7641fd3.mp3
**** 问题
***** 转录
女的为什么不喜欢那个人？
***** 音频
047ef942-6421-4d5f-a604-2e13a02f8639.mp3
**** 选择
***** A
性格不好
***** B
特别小气
***** C
太女性化
***** D
从不梳头
**** 答案
C
*** 5
:PROPERTIES:
:ID: 15c4ed50-ae92-47a8-bc1d-d0c22b474c4e
:END:
**** 对话
***** 转录
女：电视电影里常常看到鲨鱼，都说它们是“海洋杀手”，是真的吗？[[file:8a6662b4-dbc9-455e-bb6f-20ca0b124894.mp3][(audio)]]
男：没那么可怕，地球上大约有 370 多种鲨鱼，大部分鲨鱼对人类无害，只有少数种类才会伤害人类。[[file:8015cd41-53d7-4e8a-8e29-b04c7ae63538.mp3][(audio)]]
***** 音频
0dccaf6f-9c33-4454-9cfc-ceb009a1f707.mp3
**** 问题
***** 转录
关于鲨鱼，下列哪项正确？
***** 音频
8b5d9530-65c6-4ccc-863d-1609d476857e.mp3
**** 选择
***** A
是海样杀手
***** B
有 700 多种
***** C
大部分很可怕
***** D
大部分不伤害人类
**** 答案
D
*** 6
:PROPERTIES:
:ID: 4dcca406-129e-4593-92bc-c19c5ca03786
:END:
**** 对话
***** 转录
男：这个杯子真不错，是石头的还是金属的？[[file:e0eb4146-7476-4e9f-a57a-14ec60f4f87d.mp3][(audio)]]
女：你看走眼了，这是木头的。[[file:2505c7e2-bba8-4a7f-b32e-a2603b90fb28.mp3][(audio)]]
***** 音频
58f35e35-7cfa-4eee-99a6-fe4e9e8b5fb2.mp3
**** 问题
***** 转录
这个杯子是什么材料做的？
***** 音频
270f2ef8-4c70-4deb-9dc7-aa3759d99cd5.mp3
**** 选择
***** A
木头
***** B
石头
***** C
塑料
***** D
金属
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
女：爸爸，鸟儿是不是不用睡觉？
男：睡啊！大多数鸟 1 天大约睡 8 小时，有些鸟差不多要睡 20 个小时，当然，也有一些鸟几乎一点儿觉也不用睡。
女：那为什么我们很少看到睡眠中的鸟呢？
男：因为它们通常会寻找一处秘密的地方休息。
***** 音频
331a6728-b604-411d-b3a8-6a181998e874.mp3
**** 问题
***** 转录
关于鸟儿的睡眠，下列哪项正确？
***** 音频
1aea9150-36ae-4a7f-9f35-282c5cc9628d.mp3
**** 选择
***** A
都不用睡觉
***** B
必须睡一天
***** C
每天都要睡
***** D
经常躲起来
**** 答案
D
*** 8
**** 对话
***** 转录
男：今天学的鸟儿沙浴，就是鸟儿用沙子洗澡，很有意思。
女：真是很难想象，用沙子怎么能洗澡呢？
男：因为它们生活在沙漠等干燥的环境里。
女：我倒是听说过，在一些沙漠地区，有人用沙疗的办法来健身治病。
***** 音频
9bcb2661-591f-4d67-be88-bb4368f9f9fb.mp3
**** 问题
***** 转录
沙疗有什么作用？
***** 音频
ef82ea84-77f7-4d9c-880d-449568699dd3.mp3
**** 选择
***** A
强身健体
***** B
保持卫生
***** C
保护鸟类
***** D
避免干燥
**** 答案
A
*** 9
**** 对话
***** 转录
女：你相信吗，鲸以前是生活在陆地上的。
男：怎么可能呢？它不是海洋中最大的动物之一吗？
女：科学家们曾经在高山上发现过五十万年前古代鲸的骨头。研究后发现，鲸以前生活在海边，后来因为陆地上的食物越来越少，而海里鱼类丰富，所以它们慢慢地离开了陆地。
***** 音频
82d7f79e-07c3-4f41-942a-50ad352a55d2.mp3
**** 问题
***** 转录
鲸为什么离开了陆地？
***** 音频
ffc3777b-b392-4c19-ac87-dc79c80d7659.mp3
**** 选择
***** A
气候变化
***** B
地理变化
***** C
寻找食物
***** D
身体太大
**** 答案
C
*** 10
**** 对话
***** 转录
男：你们宿舍新来的那个小王，办事真是太不痛快了！
女：怎么了？
男：她昨天说去超市，我请她帮我带块肥皂回来，她问了半天，又问要多少钱的，又问要洗衣服的还是洗澡的，又问要什么颜色的……有这工夫我自己都买回来了。
女：那是人家态度认真。
***** 音频
3c376560-a307-41b8-a65c-92902d1cebaf.mp3
**** 问题
***** 转录
对于小王，男的怎么看？
***** 音频
bb7d6913-744b-4ba7-bb00-53ebd98f9197.mp3
**** 选择
***** A
很认真
***** B
很负责
***** C
不干脆
***** D
不热心
**** 答案
C
*** 11-12
**** 对话
***** 转录
一只老鼠向狮子挑战，想要同它一决高低，被狮子拒绝了。老鼠问：“你害怕了吗？”“非常害怕，但我害怕的不是你。”狮子说，“如果我答应你，你就能得到曾与狮子比武的荣誉；而我呢，则会被所有动物嘲笑，说我竟然和老鼠打架。”毫无疑问，这只狮子是非常聪明的。因为它清楚与老鼠比赛的麻烦在于：即使赢了，对手也只是一只老鼠而已。一般情况下，大人物是没兴趣与低层次的人竞争的，他们更乐于面对与自己旗鼓相当甚至远高于自己的对手。
***** 音频
30e47159-c206-4159-9c2e-bd375fec6fd2.mp3
**** 题目
***** 11
****** 问题
******* 转录
狮子为什么拒绝老鼠？
******* 音频
62feb859-a4d9-404a-a77f-fa2727b305a8.mp3
****** 选择
******* A
害怕老鼠
******* B
同情老鼠
******* C
怕输掉比赛
******* D
对手不够资格
****** 答案
D
***** 12
****** 问题
******* 转录
作者对狮子的做法持什么态度？
******* 音频
61c887bc-ebd3-49b8-9fb7-78a61ce47ec4.mp3
****** 选择
******* A
赞成
******* B
鼓励
******* C
轻视
******* D
讽刺
****** 答案
A
*** 13-14
**** 段话
***** 转录
通过长期的观察和研究，动物学家为我们展现了动物睡眠方面千姿百态的特点：兔子是个胆小鬼，一天只打三次盹，每次只有几秒钟，全天一共只睡大约两分钟。牛不停地吃草和反刍，一天最多睡半小时。大象是站着睡觉的，为了避免小虫子和老鼠钻进鼻子里，它在睡觉时要把长鼻子弯起来，卷进嘴里轻轻含着。狮子只要吃饱喝足了，可以一直睡上 16 个小时。
***** 音频
e3bf312d-687a-459c-8cdf-3bf3b509d7dd.mp3
**** 题目
***** 13
****** 问题
******* 转录
睡觉时间最短的是哪种动物？
******* 音频
ae0ef105-6922-4bb8-b73c-ab6e1f02e17f.mp3
****** 选择
******* A
牛
******* B
免子
******* C
大象
******* D
狮子
****** 答案
B
***** 14
****** 问题
******* 转录
大象睡觉时为什么要把鼻子弯起来？
******* 音频
411f52e6-a08a-49b8-8206-a40a0bbe665b.mp3
****** 选择
******* A
它胆二很小
******* B
它鼻子太长
******* C
它已经吃饱了
******* D
预防虫子、老鼠进人
****** 答案
D
* 阅读
** 第一部分
*** 课文
*** 题目
**** 15
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 16
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 17
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 18
***** 选择
****** A
****** B
****** C
****** D
***** 答案
** 第二部分
*** 19
:PROPERTIES:
:ID: af5f7b26-a436-48a3-a4b7-bbe909e44e33
:END:
**** 段话
鸟儿飞行时，主要起作用的是飞羽和尾羽。飞羽是长在翅膀上的，依靠扇动气流产生向上的力量。尾羽是长在尾巴上的，主要用来控制方向，起到“舵”的作用。而它们身上其他的羽毛，在飞行过程中主要是起到减小空气阻力的作用。
**** 选择
***** A
鸟儿身上一共只有两种羽毛
***** B
鸟儿扇动翅膀产生向上的力量
***** C
飞羽可以控制鸟儿飞行的方向
***** D
其他羽毛可以使空气压力变小
**** 答案
B
*** 20
:PROPERTIES:
:ID: 9016f49d-a8db-43e6-8a5f-91e6b838804b
:END:
**** 段话
赵老板运了一船鲜蚌在海上航行，阻于风浪，误了归期，满船的蚌肉都腐烂了。赵老板见血本无归，急得要跳海自杀。船长劝他：“等一等，也许你还剩下什么东西。“他率领水手清理船舱，从满船烂肉中找到一粒明珠，它的价值足以弥补货价运费而有余。“失败”同样会给我们留下一些宝贵的东西，比如说经验，它比珍珠还可贵。
**** 选择
***** A
赵老板是一条船的船长
***** B
船长在风浪中跳海自杀了
***** C
赵老板不小心丢掉了珍珠
***** D
即使失败也可能会有收获
**** 答案
D
*** 21
:PROPERTIES:
:ID: 2182be40-23fc-46d5-9e17-ecfcf0e6e0eb
:END:
**** 段话
一只小鸡看到一只老鹰在高高的蓝天上飞过，十分羡慕。于是它问母鸡：“妈妈，我们也有一对翅膀，为什么不能像鹰那样高高地在蓝天上飞呢？”母鸡回答说：“飞得高对我们来说没什么用。蓝天上没有谷粒，也没有虫子。”每个人都有自己的生存技能和与之相适应的环境，我们在不断追求更高目标的同时，也要知道什么才是最适合自己的。
**** 选择
***** A
小鸡羡慕老鹰有翅膀
***** B
小鸡想飞上天吃虫子
***** C
每个物种都有不一样的特点
***** D
应该不断地追求更高的目标
**** 答案
C
*** 22
:PROPERTIES:
:ID: 948d27a7-72a6-445f-875f-1e9ad995b507
:END:
**** 段话
百余年来，全世界所有的中学教材都告诉孩子们：鸟类最早的祖先是始祖鸟。始祖鸟生活在晚侏罗纪时期，形象与现在的鸟儿不完全相同，它们虽然有羽毛，但前面两只翅膀上长着爪子，嘴里有尖尖的牙齿，尾巴很长。但是，历史，尤其是远古时期的历史，往往是在后人对前人的否定中日渐接近真实的。
**** 选择
***** A
鸟类最早的祖先就是始祖鸟
***** B
始祖鸟长得跟现代的鸟一样
***** C
始祖鸟有羽毛但没有翅膀
***** D
教材里写的内容是错误的
**** 答案
D
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
