* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 584258e3-a670-468a-8062-8fc66f4ddcf6
:END:
**** 对话
***** 转录
女：鸟儿最重要的特征是什么？是有翅膀会飞？还是吃昆虫？[[file:a058d806-3f07-4eb4-ae5b-17bc54bfc427.mp3][(audio)]]
男：区分鸟儿和其他动物的唯一特征就是羽毛。[[file:4e50d0f4-ebb2-484a-8e19-d5073dfb1a48.mp3][(audio)]]
***** 音频
d7177f9c-d6cc-48c0-a665-51b71aa5f669.mp3
**** 问题
***** 转录
鸟儿最重要的特征是什么？
***** 音频
d3f5397b-c864-4d18-9270-21f0734e8b37.mp3
**** 选择
***** A
会飞
***** B
有翅膀
***** C
有羽毛
***** D
吃昆虫
**** 答案
C
*** 2
:PROPERTIES:
:ID: b2d5b7a6-ee11-452e-bf24-c0036c84f481
:END:
**** 对话
***** 转录
男：妈，我今天晚上又得加班，估计 11 点以后才能到家。[[file:f4c3240a-86d9-41d5-96f7-f9946c5c7075.mp3][(audio)]]
女：哎呀，老这样下去怎么行啊……你得爱惜身体！[[file:fc5de7d6-86e2-47e8-aff5-47eb5c6108d2.mp3][(audio)]]
***** 音频
ab76ba17-3d1c-42ff-8b5c-d68073f71280.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
0c1625b4-2d9a-4010-be06-c2c34c38b750.mp3
**** 选择
***** A
高兴
***** B
担心
***** C
后悔
***** D
生气
**** 答案
B
*** 3
:PROPERTIES:
:ID: 0c6b48d4-a44c-4b06-b866-f10ecbf82946
:END:
**** 对话
***** 转录
女：年纪轻轻的，总这么把自己关在家里，不接触社会，怎么行？[[file:7ad862a2-153c-4369-9921-79a14dc1d7b6.mp3][(audio)]]
男：可我就是不愿意出去工作，家里又不是没钱养我？[[file:25c0ecd9-f92f-4374-a396-4590f19d9a6d.mp3][(audio)]]
***** 音频
4f4a22d2-bbfb-4a68-b3c5-2d4ae387454e.mp3
**** 问题
***** 转录
关于男的，下列哪项正确？
***** 音频
ddf3005b-62dd-4db8-aee3-a3fdeb99a4ca.mp3
**** 选择
***** A
没钱了
***** B
退休了
***** C
生病了
***** D
不想工作
**** 答案
D
*** 4
:PROPERTIES:
:ID: ee06bc01-fb64-4caf-b4dc-e4a22f6e49c8
:END:
**** 对话
***** 转录
男：我觉得他挺好的，你怎么就不喜欢他呢？[[file:2e423b37-6175-4d10-97d3-3a6546801eb9.mp3][(audio)]]
女：一个大男人，天天随身带着把梳子，碰到镜子就梳来梳去的，我看不惯。[[file:afa5e61a-8a80-42d9-97c3-92ad29dc792b.mp3][(audio)]]
***** 音频
9ec11b51-e22e-41fb-85a7-a573d7641fd3.mp3
**** 问题
***** 转录
女的为什么不喜欢那个人？
***** 音频
047ef942-6421-4d5f-a604-2e13a02f8639.mp3
**** 选择
***** A
性格不好
***** B
特别小气
***** C
太女性化
***** D
从不梳头
**** 答案
C
*** 5
:PROPERTIES:
:ID: 15c4ed50-ae92-47a8-bc1d-d0c22b474c4e
:END:
**** 对话
***** 转录
女：电视电影里常常看到鲨鱼，都说它们是“海洋杀手”，是真的吗？[[file:8a6662b4-dbc9-455e-bb6f-20ca0b124894.mp3][(audio)]]
男：没那么可怕，地球上大约有 370 多种鲨鱼，大部分鲨鱼对人类无害，只有少数种类才会伤害人类。[[file:8015cd41-53d7-4e8a-8e29-b04c7ae63538.mp3][(audio)]]
***** 音频
0dccaf6f-9c33-4454-9cfc-ceb009a1f707.mp3
**** 问题
***** 转录
关于鲨鱼，下列哪项正确？
***** 音频
8b5d9530-65c6-4ccc-863d-1609d476857e.mp3
**** 选择
***** A
是海样杀手
***** B
有 700 多种
***** C
大部分很可怕
***** D
大部分不伤害人类
**** 答案
D
*** 6
:PROPERTIES:
:ID: 4dcca406-129e-4593-92bc-c19c5ca03786
:END:
**** 对话
***** 转录
男：这个杯子真不错，是石头的还是金属的？[[file:e0eb4146-7476-4e9f-a57a-14ec60f4f87d.mp3][(audio)]]
女：你看走眼了，这是木头的。[[file:2505c7e2-bba8-4a7f-b32e-a2603b90fb28.mp3][(audio)]]
***** 音频
58f35e35-7cfa-4eee-99a6-fe4e9e8b5fb2.mp3
**** 问题
***** 转录
这个杯子是什么材料做的？
***** 音频
270f2ef8-4c70-4deb-9dc7-aa3759d99cd5.mp3
**** 选择
***** A
木头
***** B
石头
***** C
塑料
***** D
金属
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
女：爸爸，鸟儿是不是不用睡觉？
男：睡啊！大多数鸟 1 天大约睡 8 小时，有些鸟差不多要睡 20 个小时，当然，也有一些鸟几乎一点儿觉也不用睡。
女：那为什么我们很少看到睡眠中的鸟呢？
男：因为它们通常会寻找一处秘密的地方休息。
***** 音频
331a6728-b604-411d-b3a8-6a181998e874.mp3
**** 问题
***** 转录
关于鸟儿的睡眠，下列哪项正确？
***** 音频
1aea9150-36ae-4a7f-9f35-282c5cc9628d.mp3
**** 选择
***** A
都不用睡觉
***** B
必须睡一天
***** C
每天都要睡
***** D
经常躲起来
**** 答案
D
*** 8
**** 对话
***** 转录
男：今天学的鸟儿沙浴，就是鸟儿用沙子洗澡，很有意思。
女：真是很难想象，用沙子怎么能洗澡呢？
男：因为它们生活在沙漠等干燥的环境里。
女：我倒是听说过，在一些沙漠地区，有人用沙疗的办法来健身治病。
***** 音频
9bcb2661-591f-4d67-be88-bb4368f9f9fb.mp3
**** 问题
***** 转录
沙疗有什么作用？
***** 音频
ef82ea84-77f7-4d9c-880d-449568699dd3.mp3
**** 选择
***** A
强身健体
***** B
保持卫生
***** C
保护鸟类
***** D
避免干燥
**** 答案
A
*** 9
**** 对话
***** 转录
女：你相信吗，鲸以前是生活在陆地上的。
男：怎么可能呢？它不是海洋中最大的动物之一吗？
女：科学家们曾经在高山上发现过五十万年前古代鲸的骨头。研究后发现，鲸以前生活在海边，后来因为陆地上的食物越来越少，而海里鱼类丰富，所以它们慢慢地离开了陆地。
***** 音频
82d7f79e-07c3-4f41-942a-50ad352a55d2.mp3
**** 问题
***** 转录
鲸为什么离开了陆地？
***** 音频
ffc3777b-b392-4c19-ac87-dc79c80d7659.mp3
**** 选择
***** A
气候变化
***** B
地理变化
***** C
寻找食物
***** D
身体太大
**** 答案
C
*** 10
**** 对话
***** 转录
男：你们宿舍新来的那个小王，办事真是太不痛快了！
女：怎么了？
男：她昨天说去超市，我请她帮我带块肥皂回来，她问了半天，又问要多少钱的，又问要洗衣服的还是洗澡的，又问要什么颜色的……有这工夫我自己都买回来了。
女：那是人家态度认真。
***** 音频
3c376560-a307-41b8-a65c-92902d1cebaf.mp3
**** 问题
***** 转录
对于小王，男的怎么看？
***** 音频
bb7d6913-744b-4ba7-bb00-53ebd98f9197.mp3
**** 选择
***** A
很认真
***** B
很负责
***** C
不干脆
***** D
不热心
**** 答案
C
*** 11-12
**** 对话
***** 转录
一只老鼠向狮子挑战，想要同它一决高低，被狮子拒绝了。老鼠问：“你害怕了吗？”“非常害怕，但我害怕的不是你。”狮子说，“如果我答应你，你就能得到曾与狮子比武的荣誉；而我呢，则会被所有动物嘲笑，说我竟然和老鼠打架。”毫无疑问，这只狮子是非常聪明的。因为它清楚与老鼠比赛的麻烦在于：即使赢了，对手也只是一只老鼠而已。一般情况下，大人物是没兴趣与低层次的人竞争的，他们更乐于面对与自己旗鼓相当甚至远高于自己的对手。
***** 音频
30e47159-c206-4159-9c2e-bd375fec6fd2.mp3
**** 题目
***** 11
****** 问题
******* 转录
狮子为什么拒绝老鼠？
******* 音频
62feb859-a4d9-404a-a77f-fa2727b305a8.mp3
****** 选择
******* A
害怕老鼠
******* B
同情老鼠
******* C
怕输掉比赛
******* D
对手不够资格
****** 答案
D
***** 12
****** 问题
******* 转录
作者对狮子的做法持什么态度？
******* 音频
61c887bc-ebd3-49b8-9fb7-78a61ce47ec4.mp3
****** 选择
******* A
赞成
******* B
鼓励
******* C
轻视
******* D
讽刺
****** 答案
A
*** 13-14
**** 段话
***** 转录
通过长期的观察和研究，动物学家为我们展现了动物睡眠方面千姿百态的特点：兔子是个胆小鬼，一天只打三次盹，每次只有几秒钟，全天一共只睡大约两分钟。牛不停地吃草和反刍，一天最多睡半小时。大象是站着睡觉的，为了避免小虫子和老鼠钻进鼻子里，它在睡觉时要把长鼻子弯起来，卷进嘴里轻轻含着。狮子只要吃饱喝足了，可以一直睡上 16 个小时。
***** 音频
e3bf312d-687a-459c-8cdf-3bf3b509d7dd.mp3
**** 题目
***** 13
****** 问题
******* 转录
睡觉时间最短的是哪种动物？
******* 音频
ae0ef105-6922-4bb8-b73c-ab6e1f02e17f.mp3
****** 选择
******* A
牛
******* B
免子
******* C
大象
******* D
狮子
****** 答案
B
***** 14
****** 问题
******* 转录
大象睡觉时为什么要把鼻子弯起来？
******* 音频
411f52e6-a08a-49b8-8206-a40a0bbe665b.mp3
****** 选择
******* A
它胆二很小
******* B
它鼻子太长
******* C
它已经吃饱了
******* D
预防虫子、老鼠进人
****** 答案
D
* 阅读
** 第一部分
*** 段话
有一天，老虎抓住一只狐狸，心想，今天可以美美地享受一颍午餐了。可是，狐狸很[[gap][15]]，它骗老虎说：“我是天帝派到山林中来做百曾之王的，你要是吃了我，天帝是不会[[gap][16]]你的。”老虎不相信。狐狸[[gap][17]]说：“你如果不相信我的话，可以跟我到山林中去走一走，我让你亲眼看看百兽害怕我的样子。”老虎想这倒也是个办法，于是就让狐狸在前面带路，自己尾随其后，一起向山林深处走去。森林中的动物们远远地看见老虎来了，都纷纷逃命。老虎不知道动物们是害怕自己而逃跑的，还以为[[gap][18]]。
*** 题目
**** 15
***** 选择
****** A
狡猾
****** B
巧妙
****** C
担率
****** D
时髦
***** 答案
A
**** 16
***** 选择
****** A
阻止
****** B
接触
****** C
爱惜
****** D
原谅
***** 答案
D
**** 17
***** 选择
****** A
匆忙
****** B
连忙
****** C
痛快
****** D
尽快
***** 答案
B
**** 18
***** 选择
****** A
狐狸害怕自己
****** B
它们是害怕狐狸才逃走的
****** C
它们要去见天帝
****** D
是不帝派狐狸来的
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: af5f7b26-a436-48a3-a4b7-bbe909e44e33
:END:
**** 段话
鸟儿飞行时，主要起作用的是飞羽和尾羽。飞羽是长在翅膀上的，依靠扇动气流产生向上的力量。尾羽是长在尾巴上的，主要用来控制方向，起到“舵”的作用。而它们身上其他的羽毛，在飞行过程中主要是起到减小空气阻力的作用。
**** 选择
***** A
鸟儿身上一共只有两种羽毛
***** B
鸟儿扇动翅膀产生向上的力量
***** C
飞羽可以控制鸟儿飞行的方向
***** D
其他羽毛可以使空气压力变小
**** 答案
B
*** 20
:PROPERTIES:
:ID: 9016f49d-a8db-43e6-8a5f-91e6b838804b
:END:
**** 段话
赵老板运了一船鲜蚌在海上航行，阻于风浪，误了归期，满船的蚌肉都腐烂了。赵老板见血本无归，急得要跳海自杀。船长劝他：“等一等，也许你还剩下什么东西。”他率领水手清理船舱，从满船烂肉中找到一粒明珠，它的价值足以弥补货价运费而有余。“失败”同样会给我们留下一些宝贵的东西，比如说经验，它比珍珠还可贵。
**** 选择
***** A
赵老板是一条船的船长
***** B
船长在风浪中跳海自杀了
***** C
赵老板不小心丢掉了珍珠
***** D
即使失败也可能会有收获
**** 答案
D
*** 21
:PROPERTIES:
:ID: 2182be40-23fc-46d5-9e17-ecfcf0e6e0eb
:END:
**** 段话
一只小鸡看到一只老鹰在高高的蓝天上飞过，十分羡慕。于是它问母鸡：“妈妈，我们也有一对翅膀，为什么不能像鹰那样高高地在蓝天上飞呢？”母鸡回答说：“飞得高对我们来说没什么用。蓝天上没有谷粒，也没有虫子。”每个人都有自己的生存技能和与之相适应的环境，我们在不断追求更高目标的同时，也要知道什么才是最适合自己的。
**** 选择
***** A
小鸡羡慕老鹰有翅膀
***** B
小鸡想飞上天吃虫子
***** C
每个物种都有不一样的特点
***** D
应该不断地追求更高的目标
**** 答案
C
*** 22
:PROPERTIES:
:ID: 948d27a7-72a6-445f-875f-1e9ad995b507
:END:
**** 段话
百余年来，全世界所有的中学教材都告诉孩子们：鸟类最早的祖先是始祖鸟。始祖鸟生活在晚侏罗纪时期，形象与现在的鸟儿不完全相同，它们虽然有羽毛，但前面两只翅膀上长着爪子，嘴里有尖尖的牙齿，尾巴很长。但是，历史，尤其是远古时期的历史，往往是在后人对前人的否定中日渐接近真实的。
**** 选择
***** A
鸟类最早的祖先就是始祖鸟
***** B
始祖鸟长得跟现代的鸟一样
***** C
始祖鸟有羽毛但没有翅膀
***** D
教材里写的内容是错误的
**** 答案
D
** 第三部分
*** 23-25
**** 段话
长颈鹿母亲刚生下小长颈鹿后，会做出一件很不合常理的事——她抬起长长的脚，踢向她的孩子，使它翻了一个跟斗后，四肢摊开。
如果小长颈鹿不能站起身来，这个粗暴的动作就会被长颈鹿妈妈不断地重复。小长颈鹿为站起来，必须拼命努力。疲倦时，小长颈鹿有时会停止努力，母亲看到，就会再次踢向它，迫使它继续奋斗，直到小长颈鹿终于第一次用它颤动的双脚站起身来。
这时，长颈鹿母亲会做出更不合常理的举动。她会再次把小长颈鹿踢倒。为什么？她想让小长颈鹿记住自己是怎么站起来的，在头脑中形成长久的记忆。因为荒野里的狮子、土狼等野兽都喜欢猎食小长颈鹿，如果长颈鹿母亲不教会她的孩子尽快站起来，与大部队保持一致，那么它就会成为这些野兽口中的食物。
已故著名作家欧文·斯通毕生研究伟人，为许多人写过传记。斯通曾经被问及是否发现了贯穿这些杰出人物生命的线索。他说：“我写的这些人，都曾遭遇当头一击，一度被彻底打倒，然后在接下来的许多年里，他们走投无路。但是每次被击倒后，他们总会站起来。你不能摧毁这些人。”
**** 题目
***** 23
****** 问题
长颈鹿妈妈为什么要踢小长颈鹿？
****** 选择
******* A
她不喜欢自己的孩子
******* B
那不是她自己的孩子
******* C
她让孩子练习站起来
******* D
她在跟孩子闹着玩儿
****** 答案
C
***** 24
****** 问题
关于长颈鹿，下列哪项正确？
****** 选择
******* A
可能是群居动物
******* B
出生后马上就能站起来
******* C
野兽不会吃它们
******* D
一辈子只生一个孩子
****** 答案
A
***** 25
****** 问题
上文主要想告诉我们什么？
****** 选择
******* A
母亲要对孩子厉害些
******* B
写传记要先研究伟人
******* C
每个人都会遇到失败
******* D
要学会摔倒后爬起来
****** 答案
D
*** 26-28
**** 段话
台湾宽屏凤蝶，为昆虫纲、鳞翅目、凤蝶科、宽尾凤蝶属物种，是台湾特有的一种大型蝴蝶。
它的翅膀展开可达90～120mm。前翅底色黑而略带褐色，后翅在中室附近有白色大纹，在外沿则有一排红色弦月型纹。雌蝶较雄蝶略大，翅面更宽圆。台湾尾凤蝶具有特别宽大的尾状突起，同时二支翅脉贯穿其间，这是其他凤蝶所没有的特征，因此举世闻名。成虫栖息时常平放翅膀，飞行缓慢，常作滑翔，喜欢在向阳的崩塌地活动，幼虫寄生在檫树上。该种在乌来和台东都有采集记录。在学术上有很高的价值。
它的首次发现是在1932年的宜兰乌帽子河滩。过去中国台湾没有发现宽尾凤蝶的记载时，学术界普遍认为宽尾凤蝶属可能仅分布于中国大陆，然而在1932年7月，宜兰农林学校的日本籍教师铃木利一采集到了宽尾凤蝶标本。这引起了当时台北大学教授素木得一的兴趣，当他初次见到铃木利一采集的标本时，表示难以置信。1933年5月，素木得一带着他的助手中条道夫前往该地点，历经数天辛苦等候，终于采集到第二只台湾宽尾凤蝶。
台湾宽尾凤蝶喜欢出没于海拔1000到2000米的山区，早期这些地点都是交通不便、人迹罕至的地方，加上其发生期仅限于每年5到8月间，因此当时的采集记录非常稀少，而被称为“梦幻之蝶”。但却也因为声名大噪，一对宽尾凤蝶往往可以卖到上万元。在金钱的驱使下，宽尾凤蝶开始面临前所未有的生存压力。
**** 题目
***** 26
****** 问题
台湾宽凤尾蝶属于：
****** 选择
******* A
鸟类
******* B
鱼类
******* C
坏虫
******* D
蜜蜂
****** 答案
C
***** 27
****** 问题
关于台湾宽凤尾蝶，下列哪项正确？
****** 选择
******* A
有很高的药用价值
******* B
是台湾老师发现的
******* C
尾部比其他蝶类窄
******* D
一般雄蝶比雌蝶小
****** 答案
D
***** 28
****** 问题
从上文最后一句话可以知道：
****** 选择
******* A
台湾宽凤尾蝶的价值不高
******* B
人们为赚钱大量捕捉宽凤尾蝶
******* C
台湾宽凤尾蝶的生存环境很好
******* D
台湾宽凤尾蝶不容易被采集到
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
没接触过
***** 2
的
***** 3
业务
***** 4
我从来
***** 5
这方面
**** 答案
***** 1
我从来没接触过这方面的业务。
*** 30
**** 词语
***** 1
戏剧
***** 2
今天学的
***** 3
的种类
***** 4
概括一下
***** 5
请你
**** 答案
***** 1
请你概括一下今天学的戏剧的种类。
*** 31
**** 词语
***** 1
老板
***** 2
很多次
***** 3
强调过
***** 4
了
***** 5
反复
**** 答案
***** 1
老板反复强调过很多次了。
