* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 38dcb82c-147a-4e2b-9226-79cf2d963930
:END:
**** 对话
***** 转录
女：难道鲁迅这样的大文学家还会做饭？[[file:9955004b-ae03-448c-a6b6-a89f57aeda79.mp3][(audio)]]
男：他不但会做，还对美食很有见解，是个地道的行家。[[file:11b7ee14-40a6-4856-8186-679575003da5.mp3][(audio)]]
***** 音频
8ef58248-13ba-4734-8582-532ea850bfff.mp3
**** 问题
***** 转录
关于鲁迅，下列哪项正确？
***** 音频
8073c079-c854-42f1-a42e-aa2d87fcbd8e.mp3
**** 选择
***** A
他只吃不做
***** B
他不会做饭
***** C
他很会种粮食
***** D
他很了解美食
**** 答案
D
*** 2
:PROPERTIES:
:ID: a4e85e16-2f28-4254-a6a2-25ce3120cd32
:END:
**** 对话
***** 转录
男：作为这方面的[[wikidata:L1144568-S1][专家]]，您对这个问题怎么看？[[file:093426cb-b3b8-4741-ba6d-5d174df3b210.mp3][(audio)]]
女：我已经就这个问题专门写了一篇文章。[[file:27b923b8-eaae-46b5-a57a-4a4c126f28b3.mp3][(audio)]]
***** 音频
47560b14-6f1c-4b9a-9501-1d5d0560375e.mp3
**** 问题
***** 转录
男的为什么要问女的的意见？
***** 音频
e9020a30-4478-4b40-8308-cb399d72513b.mp3
**** 选择
***** A
女的是专家
***** B
女的是记者
***** C
女的很有想法
***** D
女的写了一篇文章
**** 答案
A
*** 3
:PROPERTIES:
:ID: 918ce89e-1f85-4e85-ae94-ca0eeb6b17a2
:END:
**** 对话
***** 转录
女：听说那家铺子的点心不错，咱们哪天去尝尝吧？[[file:755cd207-14cd-4feb-a49b-af12ac6fdb4b.mp3][(audio)]]
男：我最近胃不太好，吃什么都没胃口。[[file:545820db-c7c4-491e-9969-f6f8a0b5eaca.mp3][(audio)]]
***** 音频
eebe6ad4-4bb7-4b44-9491-b61bb80bbdf5.mp3
**** 问题
***** 转录
对于女的的建议，男的是什么态度？
***** 音频
79a0a256-0298-4cd4-a6a1-16f2c3a15059.mp3
**** 选择
***** A
同意
***** B
拒绝
***** C
担心
***** D
委屈
**** 答案
B
*** 4
:PROPERTIES:
:ID: 7f01be15-6bd4-4613-ba69-a54d65a11a43
:END:
**** 对话
***** 转录
男：真没想到这些年老刘的生意做得这么大！[[file:ecf17bc1-56dd-40c8-9a11-c648b7e02388.mp3][(audio)]]
女：是啊，不声不响地，他们公司都位居行业之首了。[[file:d93ac4af-1f60-4cac-8d43-37d237c62cb6.mp3][(audio)]]
***** 音频
f0f30150-c948-4752-b4b5-d3d889c2d216.mp3
**** 问题
***** 转录
老刘的公司在本行业中地位如何？
***** 音频
0692cb81-c407-43c5-895a-de55652e63eb.mp3
**** 选择
***** A
不清楚
***** B
排名第一
***** C
排名最后
***** D
不方便说
**** 答案
B
*** 5
:PROPERTIES:
:ID: ca0916a5-60d4-4ea8-bdac-d7e981add5d3
:END:
**** 对话
***** 转录
女：这些都是宝贵的资料，应该好好儿保存下来。[[file:d7d0e8f0-0eef-41f1-b1e7-c17af284104c.mp3][(audio)]]
男：我那儿还有一大堆呢。[[file:d83784f2-f08c-4c3e-93bc-b609d99d3807.mp3][(audio)]]
***** 音频
770e16aa-99b9-451e-a2ba-01e1aec7d3a1.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
579eeb23-958a-4fa9-b3e9-86daab6785ff.mp3
**** 选择
***** A
资料并不宝贵
***** B
资料很难保存
***** C
已经保存好了
***** D
可以送给女的
**** 答案
A
*** 6
:PROPERTIES:
:ID: 1f0b1c1c-10d3-4a5f-a6cf-37cdd61fadeb
:END:
**** 对话
***** 转录
男：你读过鲁迅先生的《彷徨》吗？[[file:0a781ac4-cf8c-40f9-acfd-bb8843341e52.mp3][(audio)]]
女：当然读过，那是鲁迅的小说作品集，共收录他 1924 年到 1925 年所作的 11 篇小说。[[file:c8f7eac9-c407-46d6-9fc9-728ce9c29654.mp3][(audio)]]
***** 音频
059ad4af-70ad-4192-afa7-e07525d11c57.mp3
**** 问题
***** 转录
关于《彷徨》，下列哪项不正确？
***** 音频
ac1ba884-3b47-4963-838d-1f7a382ca32a.mp3
**** 选择
***** A
作者是鲁迅
***** B
写于1924～1925年
***** C
是一部长篇小说
***** D
共收录 11 篇小说
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：咱们老同事好久不见了，周末聚聚吧？
男：好啊！去太和居怎么样？
女：我没去过。你觉得好吗？
男：算不上豪华，但很适合朋友聚会。
***** 音频
c4d49858-130b-444d-ade9-836992b14736.mp3
**** 问题
***** 转录
男的觉得太和居怎么样？
***** 音频
ecc9e7b4-5a3c-4d35-884a-c6ff21daf50b.mp3
**** 选择
***** A
很豪华
***** B
他没有去过
***** C
适合朋友聚会
***** D
周未可能没座仨
**** 答案
C
*** 8
**** 对话
***** 转录
男：要是经济上有困难，你尽管跟我说。
女：你已经帮我出了不少力了，不能让你再出钱。
男：就算是我借给你的好了，等你赚回来了再还我。
女：我会有办法的。
***** 音频
50c95c76-dd84-40c3-bc51-6bb6ff069d26.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
c3031189-f723-47d7-8cc3-b194a86940b0.mp3
**** 选择
***** A
她需要借钱
***** B
她已经借到钱
***** C
她没有办法赚钱
***** D
她不想跟男的借钱
**** 答案
D
*** 9
**** 对话
***** 转录
女：你不是戒烟了吗？怎么又抽上了？
男：哎呀，跟朋友和同事在一起，免不了要抽一点儿。
女：整天就知道呼朋唤友，家里的事你根本不管！
男：你看你，又来了……
***** 音频
8b4843eb-87b7-451b-ace0-9af8b2c276d7.mp3
**** 问题
***** 转录
他们最可能是什么关系？
***** 音频
b904781a-1227-42f2-9933-e0240da47227.mp3
**** 选择
***** A
夫妻
***** B
朋友
***** C
同事
***** D
师生
**** 答案
A
*** 10
**** 对话
***** 转录
男：你怎么不吃啊？
女：这个碗有点儿脏，我叫服务员换一个。
男：你以为这是高档酒店啊，别穷讲究了。
女：什么叫穷讲究？路边小馆儿也得干净啊！
***** 音频
0cdd7eb8-97f1-48b8-a4fb-a834fec8e46d.mp3
**** 问题
***** 转录
他们在哪儿吃饭？
***** 音频
feb99cda-e0e5-4b2f-8773-a33ce2ce342a.mp3
**** 选择
***** A
自已家
***** B
小饭馆儿
***** C
学校食堂
***** D
高档酒店
**** 答案
B
*** 11-12
**** 对话
***** 转录
男：你听说过孔子吗？
女：当然。他是中国古代著名的思想家、教育家，儒家学派的创始人。
男：那我再考考你，孔子是春秋末期哪国人？
女：鲁国人。不过他曾经带着弟子周游列国 14 年，因为当时没有得到很多人的欣赏。我想他自己也没想到，他的思想和学说对后世产生了这么深远的影响。
男：还真难不倒你！那最后一个问题，“七十二贤人”是什么意思？
女：相传孔子有弟子 3000 人，其中有 72 个特别优秀，被后人称为“七十二贤人”。
***** 音频
720a31bf-24ca-44c6-b31f-e55bd949166d.mp3
**** 题目
***** 11
****** 问题
******* 转录
孔子是春秋末期哪国人？
******* 音频
31c4a7e8-9eba-46f9-b354-d22823fbfea2.mp3
****** 选择
******* A
齐国
******* B
鲁国
******* C
楚国
******* D
赵国
****** 答案
B
***** 12
****** 问题
******* 转录
关于孔子，下列哪项正确？
******* 音频
87c291c8-241a-4736-b6c7-4d6236c1d000.mp3
****** 选择
******* A
他创立了道家学派
******* B
他共有72个学生
******* C
他一直在家乡教学
******* D
他对后世影响很大
****** 答案
D
*** 13-14
**** 段话
***** 转录
文彦博是北宋杰出的政治家，他自小聪明过人。有一次，他和几个小朋友在草地上玩儿球，一不小心，球掉进一棵大树的树洞里去了。小朋友尝试伸手进树洞取球，可是树洞太深，怎么办呢？小朋友们你一言我一语的，都想不出办法来。文彦博看着那黑乎乎的树洞想了一会，说：“我有个办法，可以试试！”他们叫人帮忙提来几桶水，把水一桶一桶往树洞里倒，不一会儿，水就把树洞给填满了，皮球也浮了上来。
***** 音频
a4487bef-473a-4b0f-82d0-dfac3a7fb339.mp3
**** 题目
***** 13
****** 问题
******* 转录
文彦博是什么人？
******* 音频
4253ade3-603e-46a4-927a-8b6f718a691e.mp3
****** 选择
******* A
现代人
******* B
文学家
******* C
政治家
******* D
运动员
****** 答案
C
***** 14
****** 问题
******* 转录
文彦博想了什么办法把球取出来？
******* 音频
65b1ba5b-5581-4e5c-a363-675b15aa5a3b.mp3
****** 选择
******* A
利用桶的重量
******* B
利用水的浮力
******* C
伸手进树洞去取
******* D
请大人们来帮忙
****** 答案
D
* 阅读
** 第一部分
*** 段话
新员工培训的时候，为了在群体中比别人更早地[[gap][15]]出自己的领导能力，很多人会[[gap][16]]着做事，希望占据主动地位。其实，[[gap][17]]。你应该把更多的心思花在如何完成任务上，想办法提出比别人更有价值的操作方式；另外，领导力并不等于事事都要[[gap][18]]去做，而是要懂得如何信任和尊重自己的团队成员，计每个人发挥自己的作用。
*** 题目
**** 15
***** 选择
****** A
表演
****** B
显得
****** C
表现
****** D
表达
***** 答案
C
**** 16
***** 选择
****** A
挣
****** B
抢
****** C
挡
****** D
摸
***** 答案
B
**** 17
***** 选择
****** A
这种做法是对的
****** B
没有人会这样做
****** C
培训以后才应该这佯
****** D
这种做法并不正确
***** 答案
D
**** 18
***** 选择
****** A
亲自
****** B
亲口
****** C
各自
****** D
个人
***** 答案
A
** 第二部分
*** 19
:PROPERTIES:
:ID: 9da272ac-619b-4a73-8773-25a8e6e578bd
:END:
**** 段话
鲁迅大方好客且喜欢美食，常与朋友三五个人一起边吃边聊。有时甚至会直接让广和居送外卖到家里，在家招待朋友。当然最重要的还是因为广和居有鲁迅喜欢的菜。那里的菜既有高档的，也有适合普通百姓的，样样都让人有胃口。
**** 选择
***** A
鲁迅喜欢独自享受美食
***** B
鲁迅喜欢广和居的环境
***** C
广和居有外卖服务
***** D
广和居的菜价较贵
**** 答案
C
*** 20
:PROPERTIES:
:ID: ab4f9fd0-f196-4517-b268-c92f5475e2ed
:END:
**** 段话
徐霞客是明未地理学家，经34年旅行，写有名山游记17篇和《浙游日记》等多部著作，除佚散者外，剩有60余万字游记资料，死后由他人整理成《徐霞客游记》。世传本有10卷、12卷、20卷等数种，主要按日记述作者1613一1639年间旅行观察所得，对地理、水文、地质、植物等现象，均做了详细记录，在地理学和文学上都有重要的价值。
**** 选择
***** A
徐霞客是清朝人
***** B
《徐霞客游记》是一部著名小说
***** C
《徐霞客游记》是他晚年的著作
***** D
《徐霞客游记》记录了他旅行观察所得
**** 答案
D
*** 21
:PROPERTIES:
:ID: 0fa2df5a-a7f9-4944-8b20-f2c7827cc27d
:END:
**** 段话
1970年，威廉威廉・威廉。莎士比亚登上了英镑纸币。此后，纸币上相继迎来了大批文化名人。目前，英国人使用的20英镑纸币上印着的是英国著名经济学家亚当・斯密，这一点儿也不令人感到意外。不过，在未来的三到五年里，我们将看到市面流通的20英镑上出现某位艺术家的肖像。至于是谁，我们还不知道，但可以肯定的是，这位艺术家一定是非常受人受迎的，因为他（她）将从公众提名中产生。
**** 选择
***** A
沙士比亚是第一位肖像被印在英镑上的文化名人
***** B
亚当・斯密是英国一位著名的艺术家
***** C
出现在新英镑上的艺术家人选已确定
***** D
出现在新英磅上的艺术家由政府选出
**** 答案
A
*** 22
:PROPERTIES:
:ID: 50761379-9d46-48fa-9858-092c7559f669
:END:
**** 段话
本书共选人郁达夫诗歌180余首、散文47篇。郁达夫的诗歌，绝大多数是旧体诗词，其中不乏优秀之作。这些旧体诗歌，雄浑瑰丽，佳句迭出，既闪烁着中国古典诗歌的神韵，又流动着新鲜浓烈的现代生活气息，为这位现代作家赢得了令人艳羡的显赫诗名。这在20世纪中国文学史上也是稀有的现象。
**** 选择
***** A
本书是郁达夫的诗歌集
***** B
郁达夫写的主要是现代诗
***** C
郁达夫的诗在文学史上地位不高
***** D
郁达夫的诗有传统的形式、现代的内容
**** 答案
D
** 第三部分
*** 23-25
**** 段话
海伦。凯勒相信大家都知道吧？她是美国著名的女作家。她小时候生过一场大病，结果双目失明，耳朵也失去了听觉。你可以想象，海伦作为一个又聋又瞎的孩子，她要克服怎样的困难啊，但她以惊人的毅力学习、生活，终于成了一位举世闻名的作家。海伦能够走出黑暗，达到那么高的学术成就，除了靠她自己的努力之外，与她的老师莎莉文的教导是分不开的。她说：“我的老师安妮。曼斯菲尔德。莎莉文来到我家的这一天，是我一生中最重要的一天。”海伦七岁时，她的父母为她请来了一位教师，她就是莎莉文。可是，海伦看不见，也听不见，怎么学呢？莎莉文想到了一个办法：先拿一个洋娃娃给海伦玩，然后在她的手心上，写上洋娃娃这个词，这样海伦就知道了什么叫洋娃娃了。因此，海伦很快就喜欢上这种学习的方法。她一个一个地记，日积月累，学会了不少的词。莎莉文从此成了她的良师益友，她们相处达50年。海伦大学期间写了《我生命的故事》讲述了她战胜病残的过程，给成千上万的残疾人和正常人带来了鼓舞。这本书被译成50种文字，在世界各国流传。后来她又写了许多文字和几部自传性小说。
**** 题目
***** 23
****** 问题
“聋”的意思是：
****** 选择
******* A
生病了
******* B
没耳朵
******* C
听不见
******* D
看不见
****** 答案
C
***** 24
****** 问题
关于莎莉文，下列哪项正确？
****** 选择
******* A
她是一位作家
******* B
她很讲究教育方法
******* C
她是大学老师
******* D
她七岁时到海伦家
****** 答案
B
***** 25
****** 问题
关于海伦，下列哪项正确？
****** 选择
******* A
她是一个聋哑孩子
******* B
她特别喜欢洋娃娃
******* C
她会说50种外语
******* D
她跟莎莉文关系很好
****** 答案
D
*** 26-28
**** 段话
1926年在厦门大学教书时，鲁迅先生曾到一家理发店理发。理发师不认识鲁迅，见他衣着简朴，就穿着一件旧长袍和一双旧布鞋，心想他肯定没几个钱。于是，理发师冷冰冰地叫鲁迅坐下，马马虎虎地给理了个发。对此，鲁迅不仅没有生气，反而在理完后极随意地掬出一大把钱给他，数也没数就出门离开了。理发师一点钱数，远远超出了应付的数额，不禁喜形于色。
过了一段日子，鲁迅又来到这家理发店。理发师一眼就认出了他，立即迎上去献殷勤。虽然鲁迅仍是上次那身打扮，但理发师拿出了全部看家本领，满脸写着谦恭，慢工细活地做，足足用了一个多小时，还不时敬烟递茶。不料理毕，鲁迅并没有再显豪爽，而是照价付款，一个子也没多给。
理发师觉得很奇怪：“先生，您上回那样给，今天怎么这样给？”鲁迅笑笑：“您上回给我乱剪，所以我也就乱给；这回您认认真真地理，我就规规矩矩地给了”理发师听了大窘。
**** 题目
***** 26
****** 问题
第一次理发师态度为什么不好？
****** 选择
******* A
他心情不好
******* B
他急着出门
******* C
鲁迅穿得不像有钱人
******* D
鲁迅没给够钱
****** 答案
C
***** 27
****** 问题
第二次鲁迅先生为什么没有多给钱？
****** 选择
******* A
他带的钱不够
******* B
他觉得理得不好
******* C
他没有抽烟喝茶
******* D
他要教训理发师
****** 答案
D
***** 28
****** 问题
第二次鲁迅付款以后，理发师非常：
****** 选择
******* A
高兴
******* B
不解
******* C
生气
******* D
平静
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
因为
***** 2
而
***** 3
他
***** 4
戒丁酒
***** 5
胃病
**** 答案
***** 1
他因为胃病而戒了酒。
*** 30
**** 词语
***** 1
地道的
***** 2
你
***** 3
这
***** 4
快尝尝
***** 5
传统点心
**** 答案
***** 1
你快尝尝这地道的传统点心。
*** 31
**** 词语
***** 1
他
***** 2
平均
***** 3
要
***** 4
招待一次客人
***** 5
每两个星期
**** 答案
***** 1
他平均每两个星期要招待一次客人。
