* 练习

** 1
:PROPERTIES:
:ID: e5b75987-0116-45d7-824a-1f9fceafa1a6
:END:
*** 选择
**** 1
戒
**** 2
首
**** 3
保存
**** 4
地道
**** 5
讲究
**** 6
形象
*** 题目
**** 1
***** 句子填空
著名的文学家、语言学家刘半农1920年写了一[[gap]]题为《教我如何不想她》的小诗，流传至今。
***** 答案
2
**** 2
***** 句子填空
筷子是中餐最主要的进餐用具，在使用上也有很多[[gap]]。
***** 答案
5
**** 3
***** 句子填空
你咳嗽得这么厉害，真得[[gap]]烟了！
***** 答案
1
**** 4
***** 句子填空
作为一家北京的川菜馆，能做出如此[[gap]]的麻婆豆腐真是不容易。
***** 答案
4
**** 5
***** 句子填空
新鲜的葡萄不易[[gap]]，因此其价格也比较㙜。
***** 答案
3
**** 6
***** 句子填空
公司这次要求招聘[[gap]]好的职员。
***** 答案
6
** 2
*** 1
:PROPERTIES:
:ID: fb62a4b7-c2dd-40e9-abd8-61f00d1ed2c4
:END:
**** 句子填空
他平的成绩一般，但在今晚的比赛中[[gap]]得很突出。
**** 选择
***** A
表达
***** B
表现
**** 答案
B
*** 2
:PROPERTIES:
:ID: 2a276ca3-af6b-49ef-b573-76a5ea046fdc
:END:
**** 句子填空
我对从1840年到1919年的中国[[gap]]历史很感兴趣。
**** 选择
***** A
近代
***** B
现代
**** 答案
A
*** 3
:PROPERTIES:
:ID: cdf75714-c66b-45aa-8cbe-7cf3b539e18f
:END:
**** 句子填空
我今天[[gap]]不太舒服，所以没什么[[gap]]。
**** 选择
***** A
胃
***** B
胃口
**** 答案
***** 1
A
***** 2
B
*** 4
:PROPERTIES:
:ID: 8757015c-538c-4da8-b774-b07f2bb95862
:END:
**** 句子填空
人们[[gap]]把西红柿当做有害的果子。
**** 选择
***** A
曾经
***** B
已经
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
这事你找我[[A]]商量[[B]]找对人[[C]]了，这方面我可懂得[[D]]不少。
**** 词语
算
**** 答案
B
*** 2
**** 句子
我[[A]]听说总理[[B]]将[[C]]参加这次活动[[D]]。
**** 词语
亲自
**** 答案
C
*** 3
**** 句子
请写下与你[[A]]关系最[[B]]亲近的六个朋友，记下他们每个人的月收入，然后[[C]]算出他们月收入的[[D]]数。
**** 词语
平均
**** 答案
D
*** 4
**** 句子
[[A]]这[[B]]怎么[[C]]是个缺点呢？[[D]]是个优点呀！
**** 词语
明明
**** 答案
D
* 扩展
** 词语
*** 话题
社会
*** 词语
**** 1
道德
**** 2
传统
**** 3
风俗
**** 4
制度
**** 5
秩序
**** 6
权力
**** 7
权利
**** 8
义务
**** 9
文明
**** 10
人口
**** 11
集体
** 题目
*** 1
**** 句子
公司有产格的管理[[gap]]，保证了各项工作的正常进行。
**** 答案
4
*** 2
**** 句子
每一个学龄儿童都有受教育的[[gap]]。
**** 答案
7
*** 3
**** 句子
西安，古称“长安”，是世界四大[[gap]]古都之一。
**** 答案
9
*** 4
**** 句子
乘车，购物要排队，好的公共[[gap]]需要我们每个人的努力。
**** 答案
5
* 注释
** （三）词语辨析
*** 亲自——自己
**** 做一做
***** 1
****** 句子
这是你[[gap]]的事，应该[[gap]]做。
****** 答案
******* 1
******** 亲自
0
******** 自己
1
******* 2
******** 亲自
0
******** 自己
1
***** 2
****** 句子
今年我的业绩全公司第一，新年晚会上，总裁[[gap]]给我发了奖金。
****** 答案
******* 1
******** 亲自
1
******** 自己
0
***** 3
****** 句子
希望您能[[gap]]来参加这欠活动。
****** 答案
******* 1
******** 亲自
1
******** 自己
0
***** 4
****** 句子
每个学生都有[[gap]]的性格特点和兴趣爱好，因此老师在教育学生时应该注意选择合适的方法。
****** 答案
******* 1
******** 亲自
0
******** 自己
1
* 课文
** 转录
美食很大一部分是靠名人推动的，这一点在民国时期表现得尤其突出。例如著名的文学家鲁迅，在吃喝这件事上，就算是个地道的行家，不但会吃，还会亲自动手做，对许多美食都有独特的见解。这是近代新时尚。
北京是鲁迅长期生活过的城市，仅从这一时期鲁迅写作的日记中，我们发现他去过的知名餐馆就有65 家，另外，他还很爱吃稻香村的点心。作为大作家、大学问家，鲁迅对吃很讲究，吃的内容在他的日记里占了很大一部分。在众多餐馆里，鲁迅去得最多、最喜欢的是广和居，平均每周都要去一次。
鲁迅经常到这家店的一个重要原因是距离近，广和居的大门就在他当时住的胡同的斜对面。位于菜市口附近的广和居是北京“八大居”之首，在民国时期非常出名。广和居算不上豪华，但却很适合朋友在这里聚会、热闹。这里特别欢迎文人的光临，为他们的聚会创造了很好的条件。广和居院里分成大小不同的各种房间，有一个人的，有三五人小聚的，也有十多个人大聚会的。这大大满足了鲁迅爱和朋友吃饭的要求。他爱好交际，大方好客，常呼朋唤友，多数是三五个人一起吃，有时甚至会直接让广和居送外卖到家里，在家招待朋友。当然最重要的还是因为广和居有鲁迅喜欢的菜。那里的菜既有高档的，也有适合普通百姓的，样样都让人有胃口。
鲁迅也爱喝酒，虽然明明知道自己有胃病，不应该喝酒，但却很难戒掉。他是每顿饭必喝酒的人。现在保存的历史资料记载，他和郁达夫一起喝酒的次数最多。鲁迅酒量不大，经常喝醉，而且在喝酒的过程中烟不离手。郁达夫在 1933 年曾经作诗形容他：“醉眼蒙眬上酒楼，彷徨呐喊两悠悠”，描写得十分形象。
