* 听力

** 第一部分

*** 1
:PROPERTIES:
:ID: faea0f7f-577e-4280-806d-e303ff3a3a2c
:END:

**** 字稿

好的开始是成功的一半，很多事情开头做好了，以后就容易多了；开头没做好，后面会更困难。

***** 笔记

开头 🟦 kai1 tou2 🟦 beginning ;

***** QUESTION “的一半”什么意思？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 08:44]
:END:

***** QUESTION ”以后“和”后面“有什么 区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 08:45]
:END:

**** 星星

好的开始很重要。

**** 答案

1

*** 2
:PROPERTIES:
:ID: e2bff0b8-208c-4753-83cf-34ac71633388
:END:

**** 字稿

其实，只要我们真正努力过了，就不需要太关心结果。因为无论最后是成功还是失败，在努力的过程中，我们已经学到了很多东西。

***** 笔记

只要 🟦 zhi3 yao4 🟦 if only, so long as ;
真正 🟦 zhen1 zheng4 🟦 true ;
关心 🟦 guan1 xin1 🟦 to care about ;
结果 🟦 jie2 guo3 🟦 result ;
无论 🟦 wu2 lun4 🟦 regardless of whether ;
失败 🟦 shi1 bai4 🟦 to fail ;
过程 🟦 guo4 cheng2 🟦 process ;

****** QUESTION “无论”和“不管”有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 08:47]
:END:

**** 星星

结果比过程更重要。

***** 笔记

结果 🟦 jie2 guo3 🟦 result ;
过程 🟦 guo4 cheng2 🟦 process ;

**** 答案

0

*** 3
:PROPERTIES:
:ID: 3b080ceb-c335-42dc-ac3c-2e8f26ceb822
:END:

**** 字稿

为什么说没有失败就没有成功？因为我们可以从失败中发现自己的缺点总结出很多经验，有了这些经验的积累，才有可能获得成功。

***** 笔记

失败 🟦 shi1 bai4 🟦 to fail ;
缺点 🟦 que1 dian3 🟦 disadvantage, weak point ;
经验 🟦 jing3 yan4 🟦 experience ;
积累 🟦 ji1 lei3 🟦 to accumulate ;
获得 🟦 huo4 de2 🟦 to obtain ;

**** 星星

没有失败就没有成功。

***** 笔记

失败 🟦 shi1 bai4 🟦 to fail ;
成功 🟦 cheng2 gong1 🟦 success ;

**** 答案

1

*** 4
:PROPERTIES:
:ID: 5628278b-4d4e-4ab8-903b-cab0a46f75d2
:END:

**** 字稿

我认为态度决定一切。如果一个人做事情积极、努力、那么他就更容易成功。如果一个人不积极、不努力、不认真，他再聪明也很难成功。

***** 笔记

一切 🟦 yi1 qie4 🟦 everything ;
积极 🟦 ji1 ji2 🟦 positive ;

**** 星星

聪明最重要。

**** 答案

0

*** 5
:PROPERTIES:
:ID: 9fed90fd-9546-438d-a5f3-d904fe030267
:END:

**** 字稿

如果你想做什么事情，那就勇敢地去做吧。只有试过才知道能不能成功。实际上，即使最后不成功也没有关系，因为至少你努力过。

***** 笔记

勇敢 🟦 yong3 gan3 🟦 courageous ;
实际上 🟦 shi2 ji4 shang4 🟦 in reality ;
即使 🟦 ji2 shi3 🟦 even if ;
至少 🟦 zhi4 shao3 🟦 at least ;

**** 星星

不要担心失败。

***** 笔记

失败 🟦 shi1 bai4 🟦 to fail ;

**** 答案

1

** 第二部分

*** 6
:PROPERTIES:
:ID: 7cd41f3e-a343-465a-8317-b036525c1e70
:END:

**** 对话稿

男：饿了吧？来巧克力怎么样？
女：不，我最近在减肥，我吃个西红柿吧。

**** 问题稿

女的是什么意思？

**** 选择

***** a

不饿

***** b

想吃巧克力

***** c

不能吃东西

***** d

正在减肥

**** 答案

d

*** 7
:PROPERTIES:
:ID: f7fe4a8a-5d11-4de5-8403-a0a403cd7758
:END:

**** 对话稿

男：怎么又买这么多吃的？难道你不减肥了？
女：我减了一个月，结果一点儿也没瘦，我实在没有信心了。

***** 笔记

难道 🟦 nan2 dao4 🟦 (used to reinforce a rhetorical question) could it be said that...? ;
结果 🟦 jie2 guo3 🟦 result ;
实 🟦 shi2 🟦 honest ;
信心 🟦 xin4 xin1 🟦 confidence ;

**** 问题稿

女的是什么意思？

**** 选择

***** a

不想吃饭

***** b

放弃减肥

****** 笔记

放弃 🟦 fang4 qi4 🟦 to give up ;

***** c

坚持运动

****** 笔记

坚持 🟦 jian1 chi2 🟦 to persist ;

***** d

瘦了很多

**** 答案

b

*** 8
:PROPERTIES:
:ID: bef75855-10ec-4e17-9e20-1bf1bd41d118
:END:

**** 对话稿

男：你哥不是说三点到吗？都过去半个小时了，怎么还没出来？
女：他还得去取行李箱，您别担心，我打个电话问问。

***** 笔记

得 🟦 dei3 🟦 to have to ;
取 🟦 qu3 🟦 to get ;

**** 问题稿

男的怎么了？

**** 选择

***** a

有些着急

***** b

刚下火车

***** c

行李箱去了

***** d

提前回来了

****** 笔记

提前 🟦 ti2 qian2 🟦 to do in advance or ahead of time ;

**** 答案

a

*** 9
:PROPERTIES:
:ID: 8c74c98a-20ad-4f92-9988-bd5701206a4f
:END:

**** 对话稿

女：我实在跑不动了，你让我休息一会儿吧。
男：你才跑了十分钟，要坚持，至少再跑十分钟。

***** 笔记

坚持 🟦 jian1 chi2 🟦 to persist ;
至少 🟦 zhi4 shao3 🟦 at least ;

**** 问题稿

男的是什么意思？

**** 选择

***** a

走一会儿

***** b

别迟到

***** c

休息一下

***** d

再跑一会儿

**** 答案

d

*** 10
:PROPERTIES:
:ID: e285812b-1e31-4f36-a124-9bf2ba6733aa
:END:

**** 对话稿

女：走，咱们一起去打网球，锻炼锻炼身体。
男：好主意，我很久没去运动了。你等我几分钟，我去换双运动鞋。

***** 笔记

网球 🟦 wang3 qiu2 🟦 tennis ;
主意 🟦 zhu3 yi 🟦 idea ;
鞋（子） | xie2 (zi) | shoes ;

**** 问题稿

他们要去做什么？

**** 选择

***** a

加班

***** b

爬山

***** c

打网球

***** d

打篮球

**** 答案

c

*** 11
:PROPERTIES:
:ID: 16051975-3972-4c37-a27d-b4ab20cecfc0
:END:

**** 对话稿

女：我本来以为任务能顺利完成，没想到事情会变成这样。
男：别着急，会慢慢好起来的。

***** 笔记

本来 | ben3 lai2 | originally, at first ;
任务 🟦 ren4 wu 🟦 task ;
顺利 🟦 shun4 li4 🟦 smoothly ;

**** 问题稿

任务怎么样了？

**** 选择

***** a

提前完成了

****** 笔记

提前 🟦 ti2 qian2 🟦 to do in advance or ahead of time ;

***** b

遇到困难了

***** c

通过检查了

****** 笔记

通过 🟦 tong2 guo4 🟦 through ;
检查 🟦 jian3 cha2 🟦 to check, to examine ;


***** d

交给别人了

**** 答案

b

*** 12
:PROPERTIES:
:ID: ea3860ee-c5ae-4cf6-8145-182675444f61
:END:

**** 对话稿

男：发生这么大的事，你怎么没告诉校长呢？
女：当时他不在办公室，打他的电话又一直没人接。

***** 笔记

校长 🟦 xiao4 zhang3 🟦 headmaster ;
办公室 | ban4 gong1 shi4 | office ;

**** 问题稿

女的为什么没把这事告诉校长？

**** 选择

***** a

没找到他

***** b

没调查清楚

****** 笔记

调查 🟦 diao4 cha2 🟦 to investigate ;


***** c

不取告诉他
****** 笔记

取 🟦 qu3 🟦 to get ;

***** d

不想告诉他

**** 答案

a

** 第三部分

*** 13
:PROPERTIES:
:ID: d18f9946-9133-47d3-9847-a541e45cddcb
:END:

**** 对话稿

男：您能给我们介绍一些您的成功经验吗？
女：我觉得平时的积累是最重要的，要多向周围的人学习。
男：那您觉得您最大的优点十什么呢？
女：是诚实。

***** 笔记

经验 🟦 jing3 yan4 🟦 experience ;
积累 🟦 ji1 lei3 🟦 to accumulate ;
周围 🟦 zhou1 wei2 🟦 surroundings ;
优点 🟦 you1 dian3 🟦 strong point ;
诚实 🟦 cheng2 shi2 🟦 honest ;

**** 问题稿

女的觉得自己怎么样？

**** 选择

***** a

很勇敢

****** 笔记

勇敢 🟦 yong3 gan3 🟦 courageous ;

***** b

很可爱

***** c

很诚实

***** d

很有礼貌

**** 答案

c

*** 14
:PROPERTIES:
:ID: bdffecd0-f2d7-413d-861e-88a219890372
:END:

**** 对话稿

女：你今天怎么这么安静呀？
男：刚刚经理让我写篇总结，我正考虑怎么写呢。
女：总结？哪方面的？
男：招聘方面的。

***** 笔记

安静 | an1 jing4 | quiet ;
篇 🟦 pian1 🟦 (classifier used for writings, papers or articles) ;
总结 🟦 zong3 jie2 🟦 summary (written material that reviews and analyzes the work of a certain stage or the completion of a certain work) ;
招聘 🟦 zhao1 pin4 🟦 to recruit ;

***** QUESTION Why would his manager ask him to write a resume?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 23:17]
:END:

A resume is for finding a job, but why would the boss wanted that man to find a job?

**** 问题稿

经理让男的做什么？

**** 选择

***** a

翻译

****** 笔记

翻译 🟦 fan1 yi4 🟦 translator, interpreter ;

***** b

做调查

****** 笔记

调查 🟦 diao4 cha2 🟦 to investigate ;

***** c

招聘

****** 笔记

招聘 🟦 zhao1 pin4 🟦 to recruit ;

***** d

写总结

**** 答案

d

*** 15
:PROPERTIES:
:ID: d1bdbcca-424e-425d-b74d-18170f3ee092
:END:

**** 对话稿

女：黄教授，我们想邀请您七月份也去我们那儿讲一次课，您看您有时间吗？
男：七月二十号以后应该都可以。
女：那我们暂时定七月十五号可以吗？正好是星期五。
男：好的，如果有什么变化我们提前和你联系的。


***** 笔记

教授 🟦 jiao4 shou4 🟦 professor ;
邀请 🟦 yao1 qing3 🟦 to invite ;
暂时 🟦 zan4 shi2 🟦 temporary, for the time being ;
正好 🟦 zheng4 hao3 🟦 by chance ;
提前 🟦 ti2 qian2 🟦 to do in advance or ahead of time ;

***** QUESTION Why is 份 used here?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 23:27]
:END:

**** 问题稿

关于男的，可以知道什么？

**** 选择

***** a

接受邀请了

***** 笔记

接受 🟦 jie1 shou4 🟦 to accept ;
邀请 🟦 yao1 qing3 🟦 to invite ;

***** b

在讲课

***** c

在邀请客人

****** 笔记

邀请 🟦 yao1 qing3 🟦 to invite ;

***** d

没时间

**** 答案

a

*** 16
:PROPERTIES:
:ID: 5eec795a-fa01-4430-9d47-4491336a2fa9
:END:

**** 对话稿

男：您穿这条裙子有点儿大。
女：那太好了，我就买这条。
男：还是给您换小一号的吧。
女：不用，我穿上它，朋友见了肯定会说我减肥成功了。

***** 笔记

肯定 🟦 ken3 ding4 🟦 definitely ;

***** QUESTION “肯定”和“一定”有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 23:31]
:END:

iirc they both mean "definitely".

**** 问题稿

关于女的，可以知道什么？

**** 选择

***** a

要去约会

****** 笔记

约会 🟦 yue1 hui4 🟦 appointment ;

***** b

正在减肥

***** c

不打算买裙子

***** d

想换小一号的

**** 答案

b

*** 17
:PROPERTIES:
:ID: 32422048-fd84-43c0-b33f-2e7c01aa3449
:END:

**** 对话稿

男：上海话和普通话的区别很大，上次去上海，我竟然一句也听不懂。
女：别说你听不懂，就连很多中国人听起来也很困难。
男：你的这个同学是上海人吗？
女：对，他虽然讲普通话，可是仔细听，还是有上海味儿。

***** 笔记

竟然 | jing4 ran2 | (indicating unexpectedness) ;
连 🟦 lian2 🟦 even ;
仔细 🟦 zi4 xi3 🟦 careful ;
味儿 🟦 wei4 r 🟦 taste ;

**** 问题稿

男的的同学说话有什么特点？

***** 笔记

特点 🟦 te4 dian3 🟦 charasteristic (feature) ;

**** 选择

***** a

声音非常小

****** 笔记

声音 | sheng1 yin1 | sound, voice ;

***** b

有上海味儿

****** 笔记

味儿 🟦 wei4 r 🟦 taste ;

***** c

别人听不懂

***** d

记下经历

****** 笔记

经历 🟦 jing1 li4 🟦 experience ;

**** 答案

b

*** 18
:PROPERTIES:
:ID: ff052a31-6387-4f71-9280-04198bf33fdf
:END:

**** 对话稿

女：您为什么会写这本书呢？
男：这些年我经历了许多难忘的事情，我想把它们都写下来。
女：您想通过这本书告诉读者什么呢？
男：我主要想告诉大家，友谊是我们生命中不可缺少的。

***** 笔记

经历 🟦 jing1 li4 🟦 experience ;
通过 🟦 tong2 guo4 🟦 through ;
读者 🟦 du2 zhe3 🟦 reader ;
生命 🟦 sheng1 ming4 🟦 life ;
缺少 🟦 que1 shao3 🟦 to lack ;

**** 问题稿

男的为什么要写这本书？

**** 选择

***** a

能够赚钱

****** 笔记

赚钱 🟦 zhuan4 qian2 🟦 make money ;

***** b

能够出名

****** 笔记

出名 🟦 chu1 ming2 🟦 to become well known ;

***** c

送给爱人

***** d

记下经历

****** 笔记

记下 🟦 ji4 xia4 🟦 to write down ;

**** 答案

d

*** 19-20
:PROPERTIES:
:ID: 6799e00a-49c6-4646-aec1-622a550b13cb
:END:

**** 段话稿

许多人都有过后悔的经历，其实，只要我们按照自己的想法去做了，就没什么后悔的，因为我们不可能把所有的事情都做对，另外，让我们走向成功的，往往是我们从过去做错的事情中得到的经验。

***** 笔记

许多 🟦 xu3 duo1 🟦 a lot of ;
后悔 🟦 hou4 hui3 🟦 to regret ;
只要 🟦 zhi3 yao4 🟦 if only, so long as ;
按照 🟦 an4 zhao4 🟦 according to ;

**** 题
:PROPERTIES:
:CREATED: [2023-01-11 11:48:24 -05]
:END:

***** 19

****** 问题稿

许多人都有过怎样的经历？

****** 选择

******* a

后悔

******* b

紧张

******* c

高兴

******* d

难过

****** 答案

a

***** 20

****** 问题稿

什么能帮助我们走向成功？

****** 选择

******* a

理想

******** 笔记

理想 🟦 li3 xiang3 🟦 dream ;

******** QUESTION “理想”和“梦”有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-07 Sun 23:46]
:END:

According to the dictionary, the meaning of 理想 is "dream", and 梦 also has that meaning.

******* b

努力工作

******* c

正确的方法

******* d

失败的经验

******** 笔记

失败 🟦 shi1 bai4 🟦 to fail ;

****** 答案

d

*** 21-22
:PROPERTIES:
:ID: 5661b0d5-1f8c-4be6-8bd7-ae57007e224f
:END:

**** 段话稿

有三个人 参加长跑比赛，他们都很努力，却都没有得第一。这是不是聪明三个都失败了？肯定不是，因为他们的目的不同。第一个人是想通过跑步锻炼身体，第二个人以前参加过长跑，这次是想得到一个更好的成绩；第三个人是第一次参加，只要能跑完，他就很高兴。这样看来，三个人都成功了。

***** 笔记

目的 🟦 mu4 di4 🟦 aim, purpose ;
长跑 | chang2 pao3 | long-distance running ;
成绩 🟦 cheng2 ji4 🟦 grade ;
只要 🟦 zhi3 yao4 🟦 as long as, provided ;

**** 题
:PROPERTIES:
:CREATED: [2023-01-11 11:48:31 -05]
:END:

***** 21

****** 问题稿

地一个人为什么参加比赛？

****** 选择

******* a

减肥

******* b

支持朋友

******** 笔记

支持 🟦 zhi1 chi2 🟦 support ;

******* c

得奖金

******** 笔记

得 🟦 de2 🟦 to obtain ;
奖金 🟦 jiang3 jin1 🟦 award money ;

******* d

锻炼身体

****** 答案

d

***** 22

****** 问题稿

说话人认为这三个人怎么样？

****** 选择

******* a

都想得第一

******* b

没有努力

******* c

都成功了

******* d

很有耐心

******** 笔记

耐心 🟦 nai4 xin1 🟦 patience ;

****** 答案

c

* 阅读

** 第一部分

*** 23-26
:PROPERTIES:
:ID: 92ec4697-adcf-4f70-a6a2-cbe986541653
:END:

**** 选择

***** a

经历

****** 笔记

经历 🟦 jing1 li4 🟦 experience ;

***** b

篇

***** c

轻松

****** 笔记

轻松 🟦 qing1 song1 🟦 to relax ;

****** QUESTION “放松”和“轻松 ”有什么区别 ？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-08 Mon 09:24]
:END:

***** d

坚持

****** 笔记

坚持 🟦 jian1 chi2 🟦 to persist ;

***** e

暂时

****** 笔记

暂时 🟦 zan4 shi2 🟦 temporary, for the time being ;

**** 题
:PROPERTIES:
:CREATED: [2022-12-21 18:38:28 -05]
:END:

***** 23

****** 段话填空

昨天的网球比赛他赢得非常🟦。

******* 笔记

赢 🟦 ying2 🟦 to win ;

****** 答案

c

***** 24

****** 段话填空

这🟦小说就是他写的，他现在已经写了上百万字了。

******* 笔记

百万 🟦 bai3 wan2 🟦 million ;

****** 答案

b

***** 25

****** 段话填空

虽然🟦了很多困难，但这也让他积累了许多经验。

******* 笔记

积累 🟦 ji1 lei3 🟦 to accumulate ;
许多 🟦 xu3 duo1 🟦 a lot of ;
经验 🟦 jing3 yan4 🟦 experience ;

****** 答案

a

***** 26

****** 段话填空

相信我，困难知识🟦的，只要不放弃，就一定会成功。

******* 笔记

放弃 🟦 fang4 qi4 🟦 to give up ;

****** 答案

e

*** 27-30
:PROPERTIES:
:ID: fd2ff88a-08f1-46f1-a54d-5551990cd5b2
:END:

**** 选择

***** a

正确

***** b

主意

****** 笔记

主意 🟦 zhu3 yi 🟦 idea ;

***** c

温度

***** d

国际

****** 笔记

国际 🟦 guo2 ji4 🟦 international ;

***** e

随便

**** 题
:PROPERTIES:
:CREATED: [2022-12-21 18:38:36 -05]
:END:

***** 27

****** 对话填空

Ａ：这个🟦是谁想出来的呀？
Ｂ：好想是三班的一个学生。

****** 答案

b

***** 28

****** 对话填空

Ａ：明天晚上的活动很正式，不要穿太🟦。
Ｂ：好，我已经准备好西服了。

******* 笔记

随便 | sui2 bian4 | casually ;
西服 🟦 xi1 fu2 🟦 western-style clothes, suit ;

****** 答案

e

***** 29

****** 对话填空

Ａ：马经理，这次的🟦会议安排在下午两点，北京饭店7号会议室。
Ｂ：好，你准备一下材料，下午带上笔记本电脑和我一起去。

******* 笔记

材料 🟦 cai2 liao4 🟦 material ;

******* QUESTION What does 材料 exactly mean?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-08 Mon 12:37]
:END:

Something like slides, a summary of the progress on the work?

****** 答案

d

***** 30

****** 对话填空

Ａ：这件事我应该先跟您谈一谈，听听您的看法再决定的。
Ｂ：没关系，你的决定是🟦的，我支持你。

******* 笔记

支持 🟦 zhi1 chi2 🟦 support ;

****** 答案

a

** 第二部分

*** 31

**** 句子

***** a

所以今天早上才告诉你

***** b

可是又怕打扰你休息

***** c

我本来想昨天晚上就通知你的

****** 笔记

通知 🟦 tong1 zhi1 🟦 to inform ;

**** 答案

cba

*** 32

**** 句子

***** a

但过程比结果更重要

***** b

而且你还年轻，一切都可以重新开始

****** 笔记

一切 🟦 yi1 qie4 🟦 everything ;
重新 🟦 chong2 xin1 🟦 again ;

***** c

尽管这个计划失败了

****** 笔记

尽管 🟦 jin3 guan3 🟦 although ;
计划 🟦 ji4 hua4 🟦 plan ;
失败 🟦 shi1 bai4 🟦 to fail ;

**** 答案

cab

*** 33

**** 句子

***** a

至少我们努力过

****** 笔记

至少 🟦 zhi4 shao3 🟦 at least ;

***** b

即使失败了也没关系

****** 笔记

即使 🟦 ji2 shi3 🟦 even if ;

***** c

机会来了，就该试一试

****** 笔记

该 🟦 gai1 🟦 should ;

**** 答案

cba

*** 34

**** 句子

***** a

后来他见我做的很好，才慢慢改变了自己的看法

***** b

我爱人当时反对我选择这个工作

****** 笔记

反对 🟦 fan3 dui4 🟦 to oppose ;

***** c

他觉得这个工作太辛苦了

****** 笔记

辛苦 🟦 xin1 ku3 🟦 hard ;

**** 答案

bca

** 第三部分

*** 35

**** 段话

成功是跟年龄没有关系的。只要你不放弃希望，不怕辛苦，能够一直坚持努力学习，提高自己的水平和能力，就一定会成功。

***** 笔记

年龄 🟦 nian2 ling2 🟦 (a person's age) ;
放弃 🟦 fang4 qi4 🟦 to give up ;
坚持 🟦 jian1 chi2 🟦 to persist ;

**** 星星

什么样的人能获得成功？

***** 笔记

获得 🟦 huo4 de2 🟦 to obtain ;

**** 选择

***** a

聪明的

***** b

一直努力的

***** c

放弃希望的

***** d

年龄大的

**** 答案

b

*** 36

**** 段话

人们往往只羡慕别人成功是获得的鲜花和奖金，却很少去注意别人在取得成功之前流下的汗水。

***** 笔记

羡慕 🟦 xian4 mu4 🟦 to admire ;
获得 🟦 huo4 de2 🟦 to get ;
奖金 🟦 jiang3 jin1 🟦 award money ;
注意 🟦 zhu4 yi4 🟦 to pay attention to ;
取 🟦 qu3 🟦 to obtain ;
之前 🟦 zhi1 qian2 🟦 previously ;
汗水 🟦 han4 shui3 🟦 sweat ;
流下 🟦 liu2 xia4 🟦 shed 🟦 derramar ;

**** 星星

人们很少注意到：

**** 选择

***** a

别人的努力

***** b

别人的判断

***** c

自己的优点

***** d

自己的缺点

**** 答案

a

*** 37

**** 段话

我们对失败应该有真却的认识。失败其实可以让我们清楚自己还有什么地方需要提高，它可以版主我们走向最后的成功。

**** 星星

这段话中的“它”指的是：

***** 笔记

指 🟦 zhi3 🟦 refer to ;

**** 选择

***** a

仔细

****** 笔记

仔细 🟦 zi4 xi3 🟦 careful ;

***** b

认真

***** c

失败

***** d

努力

**** 答案

c

*** 38

**** 段话

人们最爱听的，是成功的故事；最爱说的，是成功的经历。对成功的人，很多人知识道羡慕，却不知道他们成功的原因是：别人休息的时候他们还在工作。

***** 笔记

经历 🟦 jing1 li4 🟦 experience ;
知识 🟦 zhi3 shi 🟦 knowledge ;
羡慕 🟦 xian4 mu4 🟦 to admire ;

**** 星星

根据这段话，为什么有些人能成功？

**** 选择

***** a

经验丰富

****** 笔记

丰富 🟦 feng1 fu4 🟦 to enrich ;

***** b

更有耐心

****** 笔记

耐心 🟦 nai4 xin1 🟦 patience ;

***** c

工作更努力

***** d

更注意休息

****** 笔记

注意 | zhu4 yi4 | to pay attention to ;

**** 答案

c

*** 39

**** 段话

每个人都想成功，但是成功并不是一件简单的事情。成功者在做事情以前会做好计划，遇到困难，他们从来不放弃，而是想办法去解决。即使遇到暂时的失败，他们也会勇敢地接受并总结经验。

***** 笔记

计划 🟦 ji4 hua4 🟦 plan ;
放弃 🟦 fang4 qi4 🟦 to give up ;
勇敢 🟦 yong3 gan3 🟦 courageous ;
接受 🟦 jie1 shou4 🟦 to accept ;

**** 星星

成功的人：

**** 选择

***** a

想法简单

***** b

害怕困难

***** c

没有计划

***** d

不怕失败

**** 答案

d

*** 40-41

**** 段话

“冬天到了，春天还会远吗？”这句话很浪漫，也是一种积极、勇敢的精神。它告诉我们，任何失败都只是暂时的。只要我们不放弃希望，相信自己的能力，那么困难将被解决，烦恼将会离去，我们将迎来一个新的季节。

***** 笔记

积极 🟦 ji1 ji2 🟦 positive ;
勇敢 🟦 yong3 gan3 🟦 courageous ;
精神 🟦 jing3 shen2 🟦 mental ;
任何 🟦 ren4 he2 🟦 any, whatever ;
放弃 🟦 fang4 qi4 🟦 to give up ;
烦恼 🟦 fan2 nao3 🟦 worries ;

***** QUESTION Why is 将 used here twice? What expresses its usage?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-08 Mon 13:07]
:END:

**** 题
:PROPERTIES:
:CREATED: [2023-01-06 16:58:20 -05]
:END:

***** 40

****** 星星

根据这段话可以知道，失败：

****** 选择

******* a

很浪漫

******* b

很危险

******** 笔记

危险 🟦 wei1 xian3 🟦 dangerous ;

******* c

离我们很近

******* d

只是暂时的

****** 答案

d

***** 41

****** 星星

这段话告诉我们要：

****** 选择

******* a

相信自己

******* b

相信别人

******* c

适应环境变化

******* d

学会安排时间

******** 笔记

学会 🟦 xue2 hui4 🟦 to learn ;

****** 答案

a

*** 42-43

**** 段话

有的人害怕失败，无法接受失败。他们认为，做每件事都必须成功，只有成功才是他们想要的结果。这不仅是因为他们不够勇敢，还因为他们对自己要求太高。不要因为失败而不再努力，通过失败你能获得别人没有 的经验。

***** 笔记

无法 🟦 wu2 fa3 🟦 uncapable ;
接受 🟦 jie1 shou4 🟦 to accept ;
不仅 🟦 bu4 jin3 🟦 not only ;
勇敢 🟦 yong3 gan3 🟦 courageous ;

**** 题
:PROPERTIES:
:CREATED: [2023-01-06 17:00:25 -05]
:END:

***** 42

****** 星星

有的人害怕失败，是因为他们：

****** 选择

******* a

有责任

******** 笔记

责任 🟦 ze2 ren4 🟦 responsibility ;

******* b

没经验

******* c

容易紧张

******* d

不够勇敢

******** 笔记

勇敢 🟦 yong3 gan3 🟦 courageous ;

****** 答案

d

***** 43

****** 星星

这段话想告诉我们：

****** 选择

******* a

不能失败

******* b

结果更重要

******* c

不要害怕失败

******* d

要对自己高要求

******** QUESTION Does 高 also work as a verb?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-08 Mon 13:19]
:END:

****** 答案

c

* 书写

** 第一部分

*** 44

**** 词语

***** 1

这场

***** 2

赢

***** 3

比赛

***** 4

非常漂亮

***** 5

得

**** 答案

***** 1

这场比赛赢得非常漂亮。

*** 45

**** 词语

***** 1

弟弟紧张

***** 2

一身汗

***** 3

的

***** 4

出了

**** 答案

***** 1

弟弟紧张得出了一身汗。

*** 46

**** 词语

***** 1

先

***** 2

调查

***** 3

难道

***** 4

一下

***** 5

你没有

***** 笔记

调查 🟦 diao4 cha2 🟦 to investigate ;

**** 答案

***** 1

难道你没有先调查一下？

***** 2

你难道没有先调查一下？

*** 47

**** 词语

***** 1

效果

***** 2

他的办法

***** 3

很好

***** 4

取得了

***** 5

的

***** 笔记

效果 🟦 xiao4 guo3 🟦 result ;
取得 🟦 qu3 de2 🟦 to acquire, to get, to obtain ;

**** 答案

***** 1

他的办法取得了很好的效果。

*** 48

**** 词语

***** 1

生活的压力

***** 2

并没有

***** 3

放弃

***** 4

理想

***** 5

使他

***** 笔记

压力 🟦 ya1 li4 🟦 pressure ;

**** 答案

***** 1

生活的压力并没有使他放弃理想。

** 第二部分

*** 49

**** 词语

汗

**** 答案

我每天都会跑步锻炼身体，虽然会出很多汗，但是觉得很舒服。

*** 50

**** 词语

主意

***** 笔记

主意 🟦 zhu3 yi 🟦 idea ;

**** 答案

这真是个不错的主意，值得一试。

