* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 24f0f3a4-9604-41f0-81ab-f2ebef03c574
:END:
**** 对话
***** 转录
女：爸爸，阳阳可爱看您的那些旧小人书了，特别是那套《西游记》。[[file:810f788e-0187-4fda-86cd-8d159d67803a.mp3][(audio)]]
男：你可得保留好，别弄坏了，现在那都是收藏品了。[[file:62027aa9-3d47-4552-abc1-d3ec476c475f.mp3][(audio)]]
***** 音频
82990752-76f5-4f34-aeb8-a922ec1c94ae.mp3
**** 问题
***** 转录
男的认为那些小人书怎么样？
***** 音频
c30a0508-9ec1-4c82-89a1-d9c40ee389c8.mp3
**** 选择
***** A
很有收藏价值
***** B
内容过时陈旧
***** C
不值得再保留
***** D
《西游记》最好看
**** 答案
A
*** 2
:PROPERTIES:
:ID: 1f651b22-19b7-4c13-9a5b-70b69090e38b
:END:
**** 对话
***** 转录
女：这次没能进决赛，是我太骄傲了，对对手估计不足，准备不够充分。[[file:6a36f7cb-d70e-4570-83f1-71fda02dd7a0.mp3][(audio)]]
男：不要紧，回去好好总结经验，明年再来。[[file:82c54947-3ecc-4aa8-99e3-32db400bb57c.mp3][(audio)]]
***** 音频
82f4b5ed-0275-42b1-97b7-dc1849cca98f.mp3
**** 问题
***** 转录
男的最可能是谁？
***** 音频
3eaf30e3-e4e3-43b9-9365-ed3803d70180.mp3
**** 选择
***** A
教练
***** B
医生
***** C
对手
***** D
经理
**** 答案
A
*** 3
:PROPERTIES:
:ID: b6d27203-be14-4fb6-bc52-74f423d567f6
:END:
**** 对话
***** 转录
女：刘芳岁数不小了，也没个对象，你们学校有合适的吗？给她介绍一个。[[file:9077d9c0-a935-4041-86bc-2c6fa79e6e7f.mp3][(audio)]]
男：教体育的行吗？我们那儿的赵老师曾经得过武术冠军呢。[[file:fd2490c1-c1c4-48dd-a48b-56a1da6c83bb.mp3][(audio)]]
***** 音频
a2b661a6-0d07-4ad7-9c8b-a796fbc1222d.mp3
**** 问题
***** 转录
关于刘芳，下列哪项正确？
***** 音频
f491eb37-c57c-4acd-b60a-033980046180.mp3
**** 选择
***** A
是武术冠军
***** B
在学校工作
***** C
很想当老师
***** D
还没男朋友
**** 答案
D
*** 4
:PROPERTIES:
:ID: 28b97539-a4cb-4c04-82c5-39b8c524dfc7
:END:
**** 对话
***** 转录
女：你怎么了？一直打喷嚏、流鼻涕的，感冒了吧？[[file:22a79b16-ced2-4498-a7b4-10c5db11f0d4.mp3][(audio)]]
男：一到春天，我这花粉过敏的老毛病就又来了。[[file:6a2eca7d-d587-44df-b0f2-057595902306.mp3][(audio)]]
***** 音频
82c50454-bfa3-4bdc-b8f3-da95fd95a344.mp3
**** 问题
***** 转录
男的怎么了？
***** 音频
30808f7a-b51d-429c-be8f-8dceb4bcb06b.mp3
**** 选择
***** A
感冒了
***** B
失眠了
***** C
嗓子疼
***** D
过敏了
**** 答案
D
*** 5
:PROPERTIES:
:ID: d4dadeb5-eed4-43e1-b43e-c5844df7d5ca
:END:
**** 对话
***** 转录
男：你们单位新来的小李怎么样？[[file:d9e2d96e-25aa-4d24-be0d-a11515c05d48.mp3][(audio)]]
女：他平时话不多，干起活儿来却很卖力，多累都不抱怨。[[file:058666ea-9091-4edd-8be8-4aef396f38bc.mp3][(audio)]]
***** 音频
b65b5b5c-eda4-49ac-a238-127e3ecfbd50.mp3
**** 问题
***** 转录
关于小李的工作表现，可以知道什么？
***** 音频
1c8f0165-9aea-46d2-886b-63d612118787.mp3
**** 选择
***** A
很善于思考
***** B
做事爱抱怨
***** C
工作很勤奋
***** D
干活儿怕吃苦
**** 答案
C
*** 6
:PROPERTIES:
:ID: 63b6e562-7f7f-415c-af2b-bd3f68c0f274
:END:
**** 对话
***** 转录
男：你怎么这么快就回来了？借书证办好了吗？[[file:da0f9d3d-b1ea-4b74-9b0a-4aeccabc608f.mp3][(audio)]]
女：没有，手续倒是挺简单，登记时才知道要交押金，我没带那么多钱。[[file:b488b38d-93df-49a7-9b3a-181fc05d0a30.mp3][(audio)]]
***** 音频
d06bd373-de80-4e8a-b813-2eb1748b510c.mp3
**** 问题
***** 转录
女的为什么没办成借书证？
***** 音频
b488b38d-93df-49a7-9b3a-181fc05d0a30.mp3
**** 选择
***** A
没带够押金
***** B
办理的人多
***** C
图书馆闭馆
***** D
手续太复杂
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
男：最近找不到我的学生证了。
女：那你赶快补一个吧，马上就要毕业了，没有学生证到时候怎么办手续呀？
男：这个有什么关系吗？
女：按规定，办理离校手续时，如果交不出学生证，押金就不退还了。
***** 音频
1d1c7f7e-2ef6-40bb-8d1c-0b2ef8a118b7.mp3
**** 问题
***** 转录
关于学生证，女的希望男的做什么？
***** 音频
62ee95d5-4a84-4510-8bbc-964a9c990336.mp3
**** 选择
***** A
早点儿补办
***** B
再好好找找
***** C
别要押金了
***** D
留下做纪念
**** 答案
A
*** 8
**** 对话
***** 转录
男：你帮我拿个主意，这两部手机你觉得买哪个好？
女：我不太喜欢大屏的，大的这部显得有点儿笨，而且处理速度也没小的快。
男：大小我倒不在乎，但这部机身做工比较粗糙。
女：那还是买这部小的吧。
***** 音频
489a293a-8707-4304-a5dd-33c2b40cafa0.mp3
**** 问题
***** 转录
男的为什么不买大屏的那部手机？
***** 音频
256ed96d-5439-4629-b2ef-6d15282c8bd0.mp3
**** 选择
***** A
显得有点儿筐
***** B
价格有点儿贵
***** C
牌子不太喜欢
***** D
机身做工粗糙
**** 答案
D
*** 9
**** 对话
***** 转录
女：你身材保持这么好，天天去健身房吧？
男：那倒也不是，反正每周都去游两回泳。游泳馆离家比较近，还挺方便的。
女：真羡慕你，我们家那儿想找个跑步的公园都得到五六公里以外。
男：那就赶紧搬家吧。
女：你说得倒容易。
***** 音频
c2f03c44-f02f-4bfd-99da-734f52bb88b3.mp3
**** 问题
***** 转录
女的羡慕男的什么？
***** 音频
ca4c2d92-e2f8-4e03-8165-abb948efdea7.mp3
**** 选择
***** A
身材保持得好
***** B
游泳馆离家近
***** C
每天吃得很少
***** D
天天去健身房
**** 答案
B
*** 10
**** 对话
***** 转录
男：我记得以前在你家看见过一套《三国演义》的小人书，是不是？
女：没错，那是我小时候爷爷给我买的。
男：现在还有吗？听说那套书很有收藏价值，价钱都涨疯了。
女：多贵我也不会卖的，那套书有纪念意义。
***** 音频
ebc9b3d6-c9e1-41b3-aeb1-212174e7c19a.mp3
**** 问题
***** 转录
关于《三国演义》的小人书，女的是什么意思？
***** 音频
6aaa0d1b-66e2-4876-b7dc-7e8f41929574.mp3
**** 选择
***** A
等着升值
***** B
留作纪念
***** C
送给爷爷了
***** D
想卖给男的
**** 答案
B
*** 11-12
**** 对话
***** 转录
我家附近的医院有位老中医把脉特别准，不用病人自己介绍，他经过把脉之后，就能知道病人得的是什么病。那天，我感觉胃有些不舒服，打算去找老中医看看。正在做作业的儿子说：“爸爸，我刚好做完作业，我要和您一起去，您几天前就答应给我买玩具的，今天一定要买。”到了医院，我一字没说，老中医为我把脉后说：“你这病在胃上。”我点点头，然后说：“医生，请您也给我儿子看看吧。”儿子一听，急忙往后退，说：“算了，我还是回去把作业做完吧。”原来没做完作业的儿子担心老中医把脉看出他说了假话。
***** 音频
9f828e00-1a8d-4946-9214-4134339a2e4c.mp3
**** 题目
***** 11
****** 问题
******* 转录
这位老中医看病怎么样？
******* 音频
7a994d49-4a53-43ad-8af8-daca0fc51a48.mp3
****** 选择
******* A
把脉不是特别准
******* B
判断病情很准确
******* C
开的药方很特别
******* D
询问病情很仔细
****** 答案
B
***** 12
****** 问题
******* 转录
儿子为什么要跟着一起去医院？
******* 音频
dfd5563c-5878-418c-9ff3-41f0a6054e19.mp3
****** 选择
******* A
觉得胃有些不舒服
******* B
想跟老中医学看病
******* C
顺便让爸爸买玩具
******* D
做完作业后散散心
****** 答案
C
*** 13-14
**** 段话
***** 转录
有个精力旺盛的老婆婆去乘公交车。上了车，一个彬彬有礼的小男孩儿起身给老婆婆让座，老婆婆说：“你坐好，我还很年轻，不需要你给我让座的！”过了一会儿小男孩儿又站了起来，老婆婆拍拍他的肩膀，说：“没有关系的啦，你不用给我让座，我没那么老，我还年轻！”就这样经过三四次后，小男孩儿哭了！他哭着说：“老奶奶，我家已经过了好几站了，你为什么不让我下车？”
***** 音频
57a85b25-2b86-4070-a40d-7f95523b0c94.mp3
**** 题目
***** 13
****** 问题
******* 转录
公交车上，老婆婆不坐下的原因是什么？
******* 音频
de9d95e4-6b3a-47ab-83ce-cff9122c2bb5.mp3
****** 选择
******* A
没人给她让座
******* B
马上就要下车
******* C
克得自己不需要坐
******* D
想把座留给男孩儿
****** 答案
C
***** 14
****** 问题
******* 转录
关于小男孩儿，可以知道什么？
******* 音频
aabdb478-8e68-42a3-ba52-1f15faabc5b5.mp3
****** 选择
******* A
和老奶奶认识
******* B
没让座很惭愧
******* C
不知道睇站下车
******* D
下不了车急哭了
****** 答案
D
* 阅读
** 第一部分
*** 段话
世界球王贝利在20多年的足球生涯里，[[gap][15]]过1364场比赛，共踢进1282个球，并创造了一个队员在一场比赛中射进8个球的[[gap][16]]。他高超的球技不仅令万千观众心醉，就连球场上的对手[[gap][17]]。不仅如此，他的谈吐也非同一般。当他个人进球达到1000个时，有人问他：“您睇个球踏得最好？”
贝利的回答含薄幽默，意昧深长，如同他的球技一样精彩。他笑着说：“下一个。”
在迈向成功的道路上，每当实现了一个近期[[gap][18]]时，我们不应自满，而应像贝利那样，把原来的成功当成是新的成功的起点，要有一种归零的心态，这样我们才能获得更多成功的乐趣。
*** 题目
**** 15
***** 选择
****** A
参加
****** B
参与
****** C
投入
****** D
举办
***** 答案
A
**** 16
***** 选择
****** A
记录
****** B
纪录
****** C
成果
****** D
机会
***** 答案
B
**** 17
***** 选择
****** A
也想向他虚心学习
****** B
也都对他无可奈何
****** C
也没有人看得起他
****** D
也都为他鼓掌喝彩
***** 答案
D
**** 18
***** 选择
****** A
方案
****** B
理想
****** C
目标
****** D
转变
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: 77edf326-08c9-46cc-87b5-add1c3399a12
:END:
**** 段话
科技的广泛传播逐渐打破了语言的障碍。电脑、因特网和各种电子通信设备使用的是一种没有国界的通用语言。令这里的孩子们着迷的电子游戏，也许在地球的另一端也同样受到其他孩子们的喜爱。
**** 选择
***** A
电脑使我们的语言交流减少
***** B
电脑网络改变了语言的使用
***** C
科技的传播不受语言的影响
***** D
孩子们更喜欢通过游戏交流
**** 答案
C
*** 20
:PROPERTIES:
:ID: 6ecee194-c746-4d3a-873d-be2d2187e109
:END:
**** 段话
夏天的衣服，面料以外表面光滑、内表面粗糙的最好。因为平滑的面料对光的反射率高，吸收的热能较少，而粗糙的内表面能够增加衣服与皮肤之间的空气流通，有利于散热。同时，敞开的衣领及宽大的袖子和裤脚，在人走动时有明显的鼓风作用，能促进空气流动，而比较紧的衣服会阻碍空气流动，影响散热。
**** 选择
***** A
夏装的衣领会帮助散热
***** B
外表面平滑有利于散热
***** C
粗糙的内表面吸收热能少
***** D
裤脚宽大有利于空气流动
**** 答案
D
*** 21
:PROPERTIES:
:ID: 7e8af77d-15e6-49e8-a3dc-067239e4d377
:END:
**** 段话
提起“宫廷建筑”，一般人都不陌生。尤其是北京人，就生活在这宫廷建筑云集的城市之中。这里有中国现存最大、最完整的古建筑群——  紫禁城（故宫），以及众多的皇家宫苑和园林，让人感到满眼皆风景，到处是古迹。它们述说着历史，凝聚着智慧，是中华民族建筑史上的瑰宝。
**** 选择
***** A
北京人很爱惜身边的古迹
***** B
北京保存着很多皇家建筑
***** C
故客是历史最悠久的建筑
***** D
北京是古建筑最多的城市
**** 答案
B
*** 22
:PROPERTIES:
:ID: 4cb4e56d-d82c-4cb0-8050-511b605600a3
:END:
**** 段话
培养孩子的责任感，就要让孩子学会关心别人、热爱生活。孩子是家庭的一分子，家里有事应该及时告知，让其承担自己的一份责任。要教育孩子关心亲人，要求孩子主动关心家里的老人、病人和兄弟姐妹。要让孩子做一些力所能及的家务劳动，使其在家庭生活的磨炼中形成责任感，进而上升为对父母、对家庭、对社会负责。
**** 选择
***** A
家长有事要多和孩子商量
***** B
家务劳动对孩子是种负担
***** C
关心家人的孩子更有责任感
***** D
尊重孩子可以培养他的责任感
**** 答案
C
** 第三部分
*** 23-25
**** 段话
一只蜜蜂无法度过严寒的冬天，一群蜜蜂则不同。据说蜂箱中的蜜蜂在过冬的时候，往往要抱成一团。最外面的一层是工蜂，它们拼命地扇动翅膀，像厚厚的衣服一样阻挡外面的寒冷。在这样严严实实的“包裹”之下，里边的温度恒定在13℃左右，舒适如春。
被工蜂“包裹”在里边的不仅有蜂王和雄蜂，还有其他的工蜂。饿了，它们依靠夏天采集来的蜜获得足够的能量。但里面的工蜂并不总在里面待着，一段时间后，它们需要到外面来“换岗”。就这样，蜜蜂的家族可以顺利度过寒冬。
事实上，这个世界上没有人能孤立地活下来。有了别人的帮助，我们才容易度过人生的某个冬天，或者走出一段刻骨铭心的苦难，或者摆脱一场意外的困境。然而，我们如果能像蜜蜂过冬那样，反过来去“换岗”般地回报别人，或许，人生留给我们的所有最“冷”的路，我们都能从容走过。
**** 题目
***** 23
****** 问题
根据上文可知，外层工蜂舞动翅膀是为了：
****** 选择
******* A
给蜂箱降温
******* B
保护里面的蜂王
******* C
相互传递信息
******* D
阻止冷空气进人
****** 答案
D
***** 24
****** 问题
根据上下文，“换岗”的意思是里面的工蜂：
****** 选择
******* A
外出采蜜
******* B
给外层工蜂送食物
******* C
接替外层工蜂的工作
******* D
打扫蜂箱保持卫生
****** 答案
C
***** 25
****** 问题
这篇短文主要想说，人们应该：
****** 选择
******* A
懂得互帮互助
******* B
学习蜜蜂的勤劳
******* C
勇于面对生活的艰苦
******* D
不要忘记帮助过你的人
****** 答案
A
*** 26-28
**** 段话
你肯定听过卖橘子、卖房子，但是你相信世界上有人能“卖日子”吗？日子也可以当作商品，进行买卖吗？还真有这么一位先生，居然靠“卖日子”发了财呢。他就是法国的贝利。
贝利是一个集报迷，家里收集了许多旧报纸。有一天，一个朋友来访，在他的报纸堆里随便翻着。突然，朋友满脸惊喜地叫出声来。原来，朋友手上拿的报纸正好是他女儿出生那天出版的。朋友最后要走了那份报纸，临出门还忙不停地说：“贝利，谢谢你，我把这份和我女儿同一天诞生的报纸送给女儿做生日礼物，她一定会非常高兴的。”
通过这件事，贝利突然来了灵感：何不卖日子赚钱？也就是说，把家里的旧报纸当作商品，卖给跟报纸出版日期同一天出生的人。说干就干，贝利把家里的旧报纸一一整理好，成立了历史报纸档案公司，专营生日礼品报纸。
每个人都有探源的心理，对自己生日那一天出版的报纸有一种微妙的关切之情。因此，贝利的奇特礼品一推出，就受到了顾客的欢迎，不出几日，贝利的报纸就销售一空了。于是，他遍访各地的图书馆，请求他们把准备丢弃的旧报纸卖给他。不久，法国国家图书馆等报纸馆藏单位与贝利签约，答应一旦图书馆把旧报纸制成显微胶片后，贝利可优先拥有购买权。
有了丰富的报源之后，贝利就花大力气做推广。他在报纸、杂志、广播里大做广告，塑造新型“生日礼品”的形象，并且在礼品店、文具店建立销售点。他凭借自己的经验训练店员，教他们如何向顾客推荐这种“礼品”以提高销量。
功夫不负有心人。如今，贝利历史报纸档案公司每年可卖出25万份旧报纸，平均每天能销出近700份。历史上一个个泛黄的“日子”，在他的经营之下都变成了白花花的银子。
**** 题目
***** 26
****** 问题
关于贝利，从文中可以知道什么？
****** 选择
******* A
很喜欢冒险
******* B
曾在报社工作
******* C
很会制作礼品
******* D
卖光了家里的旧报纸
****** 答案
D
***** 27
****** 问题
贝利是怎么想到创办历史报纸档案公司的？
****** 选择
******* A
女儿给他出的主意
******* B
受国家图书馆的委托
******* C
读报时偶然想到的
******* D
朋友的想法启发了他
****** 答案
D
***** 28
****** 问题
这个故事说明，成功的机会：
****** 选择
******* A
需要及时把握
******* B
要靠自己创造
******* C
要耐心地等待
******* D
必须花钱购买
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
了
***** 2
史学家
***** 3
提出
***** 4
不少疑问
***** 5
对这个问题
**** 答案
***** 1
史学家对这个问题提出了不少疑问。
***** 2
对这个问题史学家提出了不少疑问。
*** 30
**** 词语
***** 1
的
***** 2
粗糙
***** 3
这本书
***** 4
比较
***** 5
印刷质量
**** 答案
***** 1
这本书的印刷质量比较粗糙。
*** 31
**** 词语
***** 1
了
***** 2
从事
***** 3
周先生
***** 4
文艺创作
***** 5
已经很多年
**** 答案
***** 1
周先生从事文艺创作已经很多年了。
