* 热身

** 1
:PROPERTIES:
:ID: a414ba61-1ae6-4a76-8ad1-be568548c450
:END:

*** 1

**** 词语

复印

**** 答案

a

*** 2

**** 词语

厨房

**** 答案

d

*** 3

**** 词语

禁止

**** 答案

f

*** 4

**** 词语

戴眼镜

**** 答案

e

*** 5

**** 词语

理发

**** 答案

c

*** 6

**** 词语

道歉

**** 答案

b

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: c13c2a08-1de1-476b-8ce6-9a91d1966509
:END:

**** 选择

***** 1

打招呼

***** 2

场

***** 3

性别

***** 4

吵

***** 5

禁止

**** 题

***** 1

****** 段话填空

请在表格上填好姓名、🟦、年龄、职业等，然后再给我们传真过来。

****** 答案

性别

***** 2

****** 段话填空

我觉得咋们还是换个地方信吧。这个小区太🟦了，我怕影响孩子学习和休息。

****** 答案

吵

***** 3

****** 段话填空

抽烟不但污染空气，影响身体健康，而且在加油站这样的地方抽烟非常危险，因此，很多地方都🟦抽烟。

****** 答案

禁止

***** 4

****** 段话填空

要想更快适应新环境，其实有很多办法。比如，多和周围的人🟦，在别人遇到麻烦的时候去帮一把，等等。

****** 答案

打招呼

***** 5

****** 段话填空

这个京剧我一直想看，下星期六是他们在这儿的最后一🟦演出。中午你记得提醒我去买票，否则我就没有机会看了。

******* 笔记
:PROPERTIES:
:CREATED: [2022-12-21 14:42:15 -05]
:END:

京剧 / Jing1 ju4 / n. Beijiing opera ;

****** 答案

场

*** 6-10
:PROPERTIES:
:ID: fb119746-c1f9-4f37-a882-9d76f9dd1987
:END:

**** 选择

***** 1

占线

***** 2

道歉

***** 3

座位

***** 4

打印

***** 5

零钱

**** 题

***** 6

****** 对话填空

Ａ：先生，一共二百三十九快七。您付现金还是刷卡？
Ｂ：现金。我带的🟦应该够了。

****** 答案

零钱

***** 7

****** 对话填空

Ａ：请问，您一共几位？
Ｂ：我们一共四个人，麻烦你给我们找个安静点儿的🟦。

****** 答案

座位

***** 8

****** 对话填空

Ａ：明天几点到？八点来得及来不及？
Ｂ：提前点儿吧，咱们还得负责🟦会议材料呢。

****** 答案

打印

***** 9

****** 对话填空

Ａ：我是专门来向您🟦的，我真的觉得很对不起您。
Ｂ：没关系，过去的事情就让它过去吧，您也别太放在心上。

****** 答案

道歉

***** 10

****** 对话填空

Ａ：李经理的电话一直🟦，去办公室找他，敲了半天门，也没人开。
Ｂ：他刚出去开会了，可能下午才能回来。

****** 答案

占线

* 注释

** 3

*** 比一比

**** 做一做

***** 词语

****** 1

出来

****** 2
:PROPERTIES:
:ID: f0ae23e9-e524-4036-a98b-5404c68ae65d
:END:

起来

***** 题

****** 1
:PROPERTIES:
:ID: 079abd04-4937-4bce-bdda-f5aad0eb2779
:END:

******* 课文

久坐办公室的人有时间一定要站🟦活动活动。

******* 答案

******** 1

0

******** 2

1

****** 2
:PROPERTIES:
:ID: 178607a1-a501-4fba-aefa-86b4654e3100
:END:

******* 课文

这个主意好像是三班的一个学生想🟦的。

******* 答案

******** 1

1

******** 2

0

****** 3
:PROPERTIES:
:ID: 0739432d-42fc-46d4-9a8d-970fcfd4526f
:END:

******* 课文

声音听着挺熟悉的，不过我一趟子想不🟦了。

******* 答案

******** 1

0

******** 2

1

****** 4
:PROPERTIES:
:ID: ca8ee223-58da-4852-a4a0-a4bbf2c5575a
:END:

******* 课文

遇到烦恼事时，你应该想一些办法让自己从不高兴的心情中走🟦。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: fe4a467c-1770-4c5e-9d7f-027a57abec5b
:END:

******* 课文

你回去后把今天大家在会上提的意见都整理🟦。

******* 答案

******** 1

1

******** 2

0 

* 扩展

** 做一做
:PROPERTIES:
:ID: 6ede0cfa-b509-4bbc-9da4-49433952f79d
:END:

*** 选择

**** 1

发展

**** 2

理发

**** 3

沙发

**** 4

发生

*** 题

**** 1

***** 内容填空

注意速度，我们又不赶时间，太快了容易🟦危险。

***** 答案

****** 1

发生

**** 2

***** 内容填空

商场年底有活动，正在打折，这个黑色的🟦比平时便宜了一千块。

***** 答案

****** 1

沙发

**** 3

***** 内容填空

帮助别人可以积累人际关系，为自己的职业🟦打下基础。

****** 笔记
:PROPERTIES:
:CREATED: [2022-12-24 23:02:29 -05]
:END:

积累 🟦 ji1lei3 🟦 v. to accumulate ;
人际关系 🟦 ren2ji4 guan1xi4 🟦 n. interpersonal relationship ;
职业 🟦 zhi2ye4 🟦 n. occupation/profession/vocation ;

***** 答案

****** 1

发展

**** 4

***** 内容填空

出了南门向左走大约五百米，就能看到一个黄色的二层小搂，🟦店就在一层。

***** 答案

****** 1

理发

* 课文
** 1
*** 转录
马克：老师，您好！我希望下个学期在这里继续学习，请问还需要重新申请吗？
高老师：是的。给你表格，出生年月、性别、护照号码都要填，还有联系地址、联系电话。
马克：真抱歉，我不小心把护照号码填错了，您能再给我一份新的申请表吗？
高老师：没关系，不用道歉，谁都有粗心填错的时候。申请表都被别人拿走了，我给你重新打印一份，你等一下。
（高老师打印，马克填表。）
马克：这次我按照要求都填写完了，请问还需要做别的事情吗？
高老师：请把你的护照给我，我们要把护照复印一下。
** 2
*** 转录
李进：呀，你的手怎么流血了？等一下，我给你包起来。
王静：没关系，我想给你做点儿羊肉饺子，刚才用刀切肉的时侯把手弄破了。
李进：你也太不小心了，不过好像不太严重，过几天就好了。衣服上也有一点儿血，你把衣服脱下来，我给你洗洗。
王静：看来今天吃不上羊肉饺子了。
李进：那我们就吃点儿别的。我常去的那家理发店附近有个餐厅，那里的包子很好吃，我一会儿去买一点儿。
王静：好吧，我衣服口袋里有十几块零钱，买包子应该够。
** 3
*** 转录
马克：我早上跟你打招呼，你没看见。想不到又在这儿碰见你了。
安娜：真是对不起，我不是故意的，今天早上我忘戴眼镜了，看不清楚。
马克：刚才我在旁边看到你跳中国舞了，没看出来你跳得这么好！难道你以前在你们国家就学过中国舞蹈吗？
安娜：我小时侯妈妈教我跳过两年的舞，所以稍微有点儿基础。再说，舞蹈不仅是一门艺术，也是一种“语言”，这种语言与国籍无关，无论哪个国家的人都能看懂。
马克：太好了！我刚学习跳这种舞没多久，你帮我看看，我的这个动作对不对。
安娜：你这个动作做得还是不太标准，我给你跳一遍。你仔细看着，应该像我这样：先抬胳膊，然后抬腿，最后头再向右转一下。
** 4
*** 转录
马克去年租的房子离马路很近，对面有大大小小的商店，周围环境非常吵。所以，房子还没到期，马克就开始着急换房子了。有一天，他在小区门口看到一个租房子的广告。广告上说房子交通方便，周围很安静，厨房很大。总的来说，这套房子他很满意，于是他就记下了房东的手机号码。可回家后打电话，电话总是占线。第二天，他路过小区门口时，又仔细看了一下广告，原来在记号码的时侯写错了一个数字。
** 5
*** 转录
很多外国人认为所有中国人都会功夫和乒乓球，其实只是喜爱这两种运动的中国人比较多。中国人特别喜欢打乒乓球，在中国你会发现到处都有乒乓球桌。像乒乓球、羽毛球、跑步等运动对条件要求不高，所以它们都成为人们运动不错的选择。人们常说“生命在于运动”，所以很多人一到周末就会到体育馆打几场球。“乒乓球”这个名字也很有意思，“乒”和“乓”就是打球时发出的声音。在看乒乓球比赛时，尤其是在运动员发球的时候，观众要安静，禁止大声讲话或者离开座位随便走动。
