* 听力

** 1

*** 1

**** transcript

我们的旅游一向是靠老祖宗留下的宫殿庙宇和老天爷造化的奇山秀水吃饭，许多“原装”景点尚且门庭冷落，经过微缩之后的“小玩意”到底有多少吸引力，前景实难预料。

***** translation

Our tourism has always relied on the old ancestors left the palaces and temples and God's creation of the strange mountain show small dinner many "original" original "attractions are still cold, after the micro "gadgets" in the end how much attraction, the future is hard to predict. It is difficult to predict the future.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

戏开拍前，他不惜血本，花费了数千万人民币搭建了一座影视城。为了再现当年明军与清军鏖战的场面，他不惜重金累计动用了数万人来担任群众演员，场面之宏大令人叹为观止。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:14:26 -05]
:END:

Before the shooting, he spared no expense, spending tens of millions of yuan to build a film city. In order to recreate the scene of the fierce battle between the Ming army and the Qing army, he spared no expense and used tens of thousands of people to serve as mass actors, the magnitude of the scene is breathtaking.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

转让无形资产，是指转让无形资产的所有权或使用权的行为；销售不动产，是指有偿转让不动产的所有权，转让不动产的有限产权或永久使用权。单位将不动产无偿赠送给他人等视同销售不动产的行为。

***** trnaslation

The transfer of intangible assets refers to the transfer of ownership or use of intangible assets. The sale of real estate refers to the transfer of ownership of real estate for a fee and the transfer of limited ownership or perpetual use of real estate. The unit will give away the real estate to others for free, etc. is regarded as the act of selling real estate.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

a

*** 4

**** transcript

企业在选拔班组成员时，应注意各种气质类型人员的适当搭配。这样，在工作中各种气质可以得到适当的互补。把不同气质的人搭配在一起，就可以发挥各种气质的积极因素，弥补其中消极的成分。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:13:37 -05]
:END:

When selecting team members, enterprises should pay attention to the appropriate mix of various temperament types of personnel. In this way, various temperaments can be appropriately complemented in the workplace. By matching people with different temperaments together, the positive factors of each temperament can be brought into play to compensate for the negative components.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

与其对社会公益事业的慷慨资助相比，他对自己的要求显得过于苛刻了，他生活十分俭朴，从不乱花一分钱，每天作画裁下的纸条儿都舍不得丢掉；到外边吃饭要打包，甚至连家里每月的开销也要精打细算，力求节俭。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:18:29 -05]
:END:

Compared with his generous support for social causes, he was too demanding on himself. He lived a very frugal life, never spending a penny indiscriminately, and could not throw away the strips of paper he cut out for his daily painting; he had to pack his meals away from home, and even his monthly expenses at home had to be finely calculated and frugal.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 0ec2133c-615d-45aa-a322-a711d0b629a3
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：您和中国的一线作家都有交情，海岩的第一件收藏品还是您帮他挑选的。您写过爱情小说，之后就去写文物了。
男：我和这些作家关系都非常好，50 岁以上、60 岁以下的都认识，他们这些人本身都文学素养很高。他们年轻的时候，工作都是分配的，不能辞职。后来，慢慢地，很多人退出了文学圈。我曾经还是有些文学理想的，但后来觉得文学界不争气，就从那里面走出来了。后来，我写的关于艺术品的小说比他们的文学小说还畅销。
女：您怎么评价文学界和文物界？
男：我觉得文物比文学好的一点在于：它比较深，而文学比较浅。好比，你原来是个吸烟者，那是文学；而搞文物的就是雪茄。等你吸了雪茄，你会发现香烟比较淡。文学的评价标准也是个问题，写诗可以有好坏，反正都能写，谁好谁坏也没有一个终极标准。但文物是一个很窄的领域，而且文物是有终极判断的。我发现，文物界很多人说起话来前言不搭后语，文物界的人都特别死板，眼界特窄，而我眼界比较宽。
女：您介入公共事务极为频繁，前不久还在博客上写关于贪官什么的文章，这样做是要保持影响力，还是纯粹出于表达的欲望？
男：博客我一年要写 137 篇，最近四年都是这个速度。对我而言，收藏只是生活中的一个调剂，我因为在《百家讲坛》说收藏而“红”了。但我觉得，这反而是我最不看重的事儿。如果说我是“收藏家”的话，那可能是因为我著书立说了。
女：商人、作家、学者、收藏家，在这几种身份之间，您如何评价自己？
男：我是一个学者，不是一个商人。我曾经和我儿子说“我能够做一个学者，是这个时代的不幸，是我自己的大幸。”我们不能和王国维、陈寅恪相比，我实际上没读过什么书，我们算什么？我们这个时代缺少文化，所以稍微读了一点儿书的人就显得有文化。

*** 音频

41c77856-530c-4391-b153-f70ae460b4d1.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1807677b-0785-4270-99b7-d4f9dc103fb7
:END:

***** 问题

关于对话中所说的一线作家，下列哪项正确？

***** 音频

34f4812b-4b19-4f69-be1c-59b21ebab7f1.mp3

***** 选择

****** A

和说话人关系都很好

****** B

其文学素养有高有低

****** C

并不真心愿意撂写作

****** D

很多人改行搞收藏了

***** 答案

A

**** 7
:PROPERTIES:
:ID: ff9ed111-b0c0-49ca-877e-42d1e2d32f6e
:END:

***** 问题

男的怎样评价文物界？

***** 音频

c1b200c1-773b-475b-b2e2-0bccfebf2912.mp3

***** 选择

****** A

搞文物的人喜欢雪茄

****** B

文物界的人眼界不宽

****** C

和文学的评价标准一致

****** D

文物涉及的领域比较广

***** 答案

B

**** 8
:PROPERTIES:
:ID: 7ad58726-3c2c-4305-9fc4-0008b330e8da
:END:

***** 问题

关于男的，下列哪项正确？

***** 音频

1c908ac8-f66a-4c3c-a187-9299a1c97b83.mp3

***** 选择

****** A

他是个做事死板的人

****** B

他著有关于收藏的著作

****** C

他很喜欢《百家讲坛》

****** D

他一直在寻找表达机会

***** 答案

B

**** 9
:PROPERTIES:
:ID: f0e64b98-145e-43ea-989c-821ebb3e4524
:END:

***** 问题

男的怎样看自己和自己所生活的时代？

***** 音频

34a223cd-e487-44f0-a669-ccf64cb5b09c.mp3

***** 选择

****** A

他认为自己是个幸运儿

****** B

他是个具有公益心的人

****** C

他喜欢学者，不喜欢商人

****** D

他认为这个时代学者众多

***** 答案

A

**** 10
:PROPERTIES:
:ID: 54bcc8b8-f41d-45cc-831c-c0778f1f52c0
:END:

***** 问题

根据对话，下列哪项正确？

***** 音频

99f3b0b9-7146-4362-b1db-1dfca3e63e6b.mp3

***** 选择

****** A

收藏能够让人眼界开阀

****** B

王国维、陈寅恪很有威望

****** C

男的的主要收人来源是写作

****** D

男的认可的身份是学者和商人

***** 答案

B

