* 听力

** 第二部分
:PROPERTIES:
:ID: 0ec2133c-615d-45aa-a322-a711d0b629a3
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：您和中国的一线作家都有交情，海岩的第一件收藏品还是您帮他挑选的。您写过爱情小说，之后就去写文物了。
男：我和这些作家关系都非常好，50 岁以上、60 岁以下的都认识，他们这些人本身都文学素养很高。他们年轻的时候，工作都是分配的，不能辞职。后来，慢慢地，很多人退出了文学圈。我曾经还是有些文学理想的，但后来觉得文学界不争气，就从那里面走出来了。后来，我写的关于艺术品的小说比他们的文学小说还畅销。
女：您怎么评价文学界和文物界？
男：我觉得文物比文学好的一点在于：它比较深，而文学比较浅。好比，你原来是个吸烟者，那是文学；而搞文物的就是雪茄。等你吸了雪茄，你会发现香烟比较淡。文学的评价标准也是个问题，写诗可以有好坏，反正都能写，谁好谁坏也没有一个终极标准。但文物是一个很窄的领域，而且文物是有终极判断的。我发现，文物界很多人说起话来前言不搭后语，文物界的人都特别死板，眼界特窄，而我眼界比较宽。
女：您介入公共事务极为频繁，前不久还在博客上写关于贪官什么的文章，这样做是要保持影响力，还是纯粹出于表达的欲望？
男：博客我一年要写 137 篇，最近四年都是这个速度。对我而言，收藏只是生活中的一个调剂，我因为在《百家讲坛》说收藏而“红”了。但我觉得，这反而是我最不看重的事儿。如果说我是“收藏家”的话，那可能是因为我著书立说了。
女：商人、作家、学者、收藏家，在这几种身份之间，您如何评价自己？
男：我是一个学者，不是一个商人。我曾经和我儿子说“我能够做一个学者，是这个时代的不幸，是我自己的大幸。”我们不能和王国维、陈寅恪相比，我实际上没读过什么书，我们算什么？我们这个时代缺少文化，所以稍微读了一点儿书的人就显得有文化。

**** 音频

41c77856-530c-4391-b153-f70ae460b4d1.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1807677b-0785-4270-99b7-d4f9dc103fb7
:END:

***** 问题

关于对话中所说的一线作家，下列哪项正确？

****** 音频

34f4812b-4b19-4f69-be1c-59b21ebab7f1.mp3

***** 选择

****** A

和说话人关系都很好

****** B

其文学素养有高有低

****** C

并不真心愿意撂写作

****** D

很多人改行搞收藏了

***** 答案

A

**** 7
:PROPERTIES:
:ID: ff9ed111-b0c0-49ca-877e-42d1e2d32f6e
:END:

***** 问题

男的怎样评价文物界？

****** 音频

c1b200c1-773b-475b-b2e2-0bccfebf2912.mp3

***** 选择

****** A

搞文物的人喜欢雪茄

****** B

文物界的人眼界不宽

****** C

和文学的评价标准一致

****** D

文物涉及的领域比较广

***** 答案

B

**** 8
:PROPERTIES:
:ID: 7ad58726-3c2c-4305-9fc4-0008b330e8da
:END:

***** 问题

关于男的，下列哪项正确？

****** 音频

1c908ac8-f66a-4c3c-a187-9299a1c97b83.mp3

***** 选择

****** A

他是个做事死板的人

****** B

他著有关于收藏的著作

****** C

他很喜欢《百家讲坛》

****** D

他一直在寻找表达机会

***** 答案

B

**** 9
:PROPERTIES:
:ID: f0e64b98-145e-43ea-989c-821ebb3e4524
:END:

***** 问题

男的怎样看自己和自己所生活的时代？

****** 音频

34a223cd-e487-44f0-a669-ccf64cb5b09c.mp3

***** 选择

****** A

他认为自己是个幸运儿

****** B

他是个具有公益心的人

****** C

他喜欢学者，不喜欢商人

****** D

他认为这个时代学者众多

***** 答案

A

**** 10
:PROPERTIES:
:ID: 54bcc8b8-f41d-45cc-831c-c0778f1f52c0
:END:

***** 问题

根据对话，下列哪项正确？

****** 音频

99f3b0b9-7146-4362-b1db-1dfca3e63e6b.mp3

***** 选择

****** A

收藏能够让人眼界开阀

****** B

王国维、陈寅恪很有威望

****** C

男的的主要收人来源是写作

****** D

男的认可的身份是学者和商人

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

旅游是中国的支柱产业

***** B

中国有很多人造风景区

***** C

不漂亮的地方鲜有人去

***** D

说话人不看好微缩景观

**** 段话

我们的旅游一向是靠老祖宗留下的宫殿庙宇和老天爷造化的奇山秀水吃饭，许多“原装”景点尚且门庭冷落，经过微缩之后的“小玩意”到底有多少吸引力，前景实难预料。

***** 音频

be3b7ce4-00c6-4866-ad91-a7b4571a7f2b.mp3

**** 答案

D

*** 2

**** 选择

***** A

很多人在拍戏前受了重伤

***** B

他舍不得花钱搭建影视城

***** C

戏中的战争场面极其宏大

***** D

影片中的群众演员很出色

**** 段话

戏开拍前，他不惜血本，花费了数千万人民币搭建了一座影视城。为了再现当年明军与清军鏖战的场面，他不惜重金累计动用了数万人来担任群众演员，场面之宏大令人叹为观止。

***** 音频

a8ca4e9b-c9c2-4d00-b3fa-78cbc8461e50.mp3

**** 答案

C

*** 3

**** 选择

***** A

所谓销售就是有偿转让

***** B

转让无形资产是有条件的

***** C

单位不动产不可随意赠送

***** D

无偿赠予和销售无本质区别

**** 段话

转让无形资产，是指转让无形资产的所有权或使用权的行为；销售不动产，是指有偿转让不动产的所有权，转让不动产的有限产权或永久使用权。单位将不动产无偿赠送给他人等视同销售不动产的行为。

***** 音频

bf407fbe-acb5-4f66-8f8d-06ee359fce54.mp3

**** 答案

A

*** 4

**** 选择

***** A

不同气质的人可以互相影响

***** B

各种气质的人混搭方便互相学习

***** C

企业用人时应考虑不同气质的混搭

***** D

不同气质的人混搭的消极影响极大

**** 段话

企业在选拔班组成员时,应注意各种气质类型人员的适当搭配。这样,在工作中各种气质可以得到适当的互补。把不同气质的人搭配在一起,就可以发挥各种气质的积极因素,弥补其中消极的成分。

***** 音频

61bb2be0-59cd-40a5-88e7-baa4c103ce2d.mp3

**** 答案

C

*** 5

**** 选择

***** A

他常在外面吃饭

***** B

他是个画画儿的

***** C

他历来花钱要算计

***** D

做公益不如画画儿

**** 段话

与其对社会公益事业的慷慨资助相比，他对自己的要求显得过于苛刻了，他生活十分俭朴，从不乱花一分钱，每天作画裁下的纸条儿都舍不得丢掉；到外边吃饭要打包，甚至连家里每月的开销也要精打细算，力求节俭。

***** 音频

eb6f67a5-e28a-4559-9bf1-5f2ba1ebd0ad.mp3

**** 答案

B

** 第三部分

*** 11-13

**** 课文

齐白石 1864 年出生，籍贯湖南，是近现代中国绘画大师，世界文化名人。他早年曾做过木工，后以卖画为生，五十七岁后定居北京。齐白石书法、篆刻、诗文、绘画样样精通，并著有《白石诗草》及《白石老人自述》等。

居住在北京的齐白石，内心装着的却是家乡的山水、家乡的草木。无奈他不可能将家乡草木带到北京，于是这种情思便化作艺术信息传达出来。他刻了许多寄托着怀乡之情的印章，写了许多怀乡诗，那些诗句无一不是齐白石“夜不安眠”时的肺腑之言。

齐白石的作品《我最知鱼》，画的是小鱼追逐钓钩和鱼饵的情景，而那正是齐白石少年时常做的事情，他怎会不“知鱼”？齐白石画中的黑蜻蜓、红甲虫，家乡人叫作“黑婆子”“红娘子”，这正是农民的审美情趣；齐白石画鲇鱼题“年年有余”，画石榴象征多子，画桃子象征多寿，也都是民间艺术的喻意象征。这些作品，无一不是齐白石的恋乡情结和童真情趣的自然流露。

**** 题目

***** 11

****** 选择

******* A

他的家乡是湖南

******* B

他是个成功的商人

******* C

他是自学成才的木工

******* D

他从事美术教育工作

****** 问题

关于齐白石，下列哪项正确？

****** 答案

A

***** 12

****** 选择

******* A

夜里总是睡不好觉

******* B

院里种了许多花草

******* C

心中充满思乡之情

******* D

学会了写诗、刻印章

****** 问题

齐白石定居在北京后，有什么变化？

****** 答案

C

***** 13

****** 选择

******* A

专门为孩子创作

******* B

充满了童真童趣

******* C

内容深受城市人的喜爱

******* D

借鉴了民间艺术的手法

****** 问题

齐白石的作品有什么特点？

****** 答案

B

*** 14-17

**** 课文

一走进汪先生的家，我就看到他收藏的“宝贝”，有明代的漆器，清代的银碗和各种古典家具，不过数量最多的还是玉器。

汪先生家原本有些祖传物件，如今均已失传，只剩下一个玉笔筒。听着汪先生的介绍，我注意到他家书桌上那个插着几支笔的青玉笔筒，虽貌不惊人，却别有情趣。

汪先生说，这个玉笔筒是他父亲年轻时买的，当时花了一块大洋。那时一块大洋可值不少钱，所以笔筒价格不算便宜。他的父亲是一名中医，他买这笔筒是为了自己用，并不为收藏。

汪先生从小看着这个笔筒长大，慢慢对老物件有了兴趣。后来，他随父母迁移到新疆伊犁，有机会接触到和田美玉。那时候和田玉的价格不像现在这么疯狂。当地居民都能接触到和田玉，少数民族居民身上都佩戴有玉器。汪先生觉得它们很漂亮，他喜欢玉的内在美感，从此汪先生成了玉器收藏者。

**** 题目

***** 14

****** 选择

******* A

是祖父收购来的

******* B

看起来平平常常

******* C

买时价格很便宜

******* D

如今已经是孤品

****** 问题

关于玉笔筒，下列哪项正确？

****** 答案

B

***** 15

****** 选择

******* A

他是一名中医

******* B

玉器是他的最爱

******* C

小时候就居住在新疆

******* D

把祖传玉器都处理了

****** 问题

关于汪先生的父亲，下列哪项正确？

****** 答案

A

***** 16

****** 选择

******* A

当地居民大多收藏玉器

******* B

和田玉的价格历来很贵

******* C

当地居民都能接触玉器

******* D

当地居民对玉都很在行

****** 问题

关于和田玉，下列哪项正确？

****** 答案

C

***** 17

****** 选择

******* A

祖上就有收藏的传统

******* B

感受到收藏能赚大钱

******* C

天天看笔筒就喜欢上玉了

******* D

他领略到了玉的内在之美

****** 问题

汪先生对玉的爱好是怎样形成的？

****** 答案

D

