* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: afa55b10-fa35-4240-aa44-c917a46b2dc2
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
9cc286af-a826-4198-b37d-a04eb9049959.mp3
***** 转录
对于劳资纠纷，最好的解决方案是在劳资之间建立和谐的关系，最大程度上避免或减少劳资纠纷的发生，或者至少把劳资之间的矛盾化解在萌芽状态，使其不致发展成为“纠纷”，这才是企业管理的上策。
**** 选择
***** A
企业应主动给工人涨工资
***** B
企业与员工之间总会有矛盾
***** C
高明的企业会避免与员工冲突
***** D
员工应该为企业发展献计献策
**** 答案
C
*** 2
:PROPERTIES:
:ID: e6b1efee-6b45-4e19-8205-dc01a9f47a15
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
317aca6e-c9af-48b1-9dc8-c38f779ad624.mp3
***** 转录
普通牙膏中含有冰片、丁香油、薄荷脑等，具有防治口腔疾病的功效。而有些药物牙膏有较强的刺激性，对口腔粘膜有损害；有的药物牙膏含有活性较强的染色素，用久了会污染牙面，因此使用药物牙膏要慎重。
**** 选择
***** A
应禅止生产药物牙膏
***** B
不要随意使用药物牙膏
***** C
药物牙膏对人有害而无益
***** D
药物牙膏的生产缺乏科学性
**** 答案
B
*** 3
:PROPERTIES:
:ID: fba377d9-b47f-45da-be2e-90d6d8921f63
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
2af44d3c-04f0-4121-bb99-a774f772379a.mp3
***** 转录
导演40多岁，黑黑的脸，像所有的导演一样，下巴留着胡子，脸上很少有笑容。他匆匆向我交代了几句就说：“开始吧！”顿时，房屋里的灯光全都打开，我被照得有点儿晕，接着看到这么多人看着自己，我顿时紧张了起来。
**** 选择
***** A
导演对我非常严厉
***** B
围观的观众不太多
***** C
我担心导演拍不好
***** D
导演是个严肃的人
**** 答案
D
*** 4
:PROPERTIES:
:ID: 16835e0c-2bf5-4ec3-84ac-cf4cb8e09364
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
25469e35-17d3-4907-b6c2-876ce43ace83.mp3
***** 转录
先前发生的事件与后来发生的事件之间往往有着千丝万缕的联系，甚至是后来发生事件的根源或条件。但是由于历史记录不全、事件之间的关系错综复杂，往往使得因果分析变得困难而复杂。
**** 选择
***** A
任何事件的发生都有其必然性
***** B
前后事件之间常常是有联系的
***** C
要重视对历史事件的记录工作
***** D
因果分析再难也必须努力去做
**** 答案
B
*** 5
:PROPERTIES:
:ID: 25ba4481-4660-4d34-bc60-3d7fddefac00
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
9544d4cc-6498-48d2-8edf-3a2a64bc42f4.mp3
***** 转录
她两眼茫然地盯着前方，为自己如此草率的远行而担忧，不知道刘大明会不会来接她。忽然，她的眼前一亮，她被一大捧鲜艳的红玫瑰吸引住了，她以万分艳羡的目光盯着那些红玫瑰，她没想到，红玫瑰的后面竟然是刘大明的一张微笑的脸！
**** 选择
***** A
她心中忐忑不安
***** B
刘大明是卖花的
***** C
刘大明对她非常失望
***** D
她和刘大明都喜欢花
**** 答案
A
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 555ea437-e390-40ba-9120-7be0b4de4282
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
e193318e-ede7-4d31-99fc-181373dfc2cf.mp3
***** 转录
男：“社交离线日，出来分享才开心”主题活动至今已经举办多次了，作为心理专家，您对这个活动有什么看法？
女：飞速发展的社交网络，简化了人们的沟通，却解决不了人与人之间内心的情感需要。今年的活动进一步号召人们行动起来，希望更多的人能够暂别网络，关注面对面交流，分享真实沟通带来的幸福体验，绝对是一件好事。
男：其实线上交流也是交流，难道二者有什么差别吗？
女：社交网络打破了时间和空间的壁垒，但也为社会带来了不小的影响。这样的社交模式，催生了“新型社交人类”。例如，亲朋聚会，“新型社交人类”手机不离手，一道美食上桌，他们先要拍照并通过社交媒体分享，然后期盼着别人点赞和评论，反倒冷落和忽视了身边的人。这一情景折射出的是“新型社交人类”过于在乎创造未来的幸福感，而缺乏聚焦当下、感受当下幸福感的能力。
男：嗯，过分依赖线上交流，可能导致这类人群无法应对现实生活中的人际问题。
女：不仅如此，大家公认的是，面对面交流是复杂、高层次的，更能考验一个人的人际交往能力。面对面的交流要求人身心投入地对待彼此，线上交流的隐患就是不需要这种对人内心情感的体察与维护。
男：嗯，有道理。
女：适度离线，不要过度依赖网络，在真实的世界里进行互动分享、情感经营，是克制网络迷恋的切实可行的理性选择，也是长远幸福的重要源泉。
男：您说的是“情感经营”？难道情感还要“经营”？
女：是啊，人与人之间的情感是需要经营的，这种说法并不荒谬。这在面对面交往中体现尤为真切。比如，与人交往要真诚，要用心，要懂得彼此珍重。但人与人之间总会有磕磕碰碰，这就需要磨合。相处久了，彼此熟悉了，也就有了相处之道。在这个过程中，人要不断自省，要提高自己的修养和涵养，如果一个人能使对方因为拥有你而感到自豪，就是你人生最大的成功。
**** 题目
***** 6
:PROPERTIES:
:ID: 06c628ca-8748-43fe-96bc-8b91b9cb1b04
:END:
****** 问题
******* 音频
8a3c1bc2-36a0-46e5-9582-def528c8fc85.mp3
******* 转录
女的对这项主题活动的看法，下列哪项正确？
****** 选择
******* A
认为真实沟通绝对是一件好事
******* B
鼓励人们通过活动彻底告别网络
******* C
网络走进生活是社会发展的必然
******* D
网络应重视人的沟通与情感交流
****** 答案
A
***** 7
:PROPERTIES:
:ID: cc945b94-ace2-491b-98c1-2dfbd0400657
:END:
****** 问题
******* 音频
dbde101a-5345-4b56-b5d1-8bdda4221fb0.mp3
******* 转录
线上交流和面对面交流的差别是什么？
****** 选择
******* A
 二者对时空要求不一样
******* B
 二者适应的人群不一样
******* C
 线上交流更能满足虚荣心
******* D
 面对面交流让人更有幸福感
****** 答案
A
***** 8
:PROPERTIES:
:ID: beec3e00-ac80-4564-baba-e9d8de5c548b
:END:
****** 问题
******* 音频
1c7d5282-3ca6-4920-ba67-4a4dd093c386.mp3
******* 转录
过分依赖线上交流，可能导致什么问题？
****** 选择
******* A
 身在福中不知福
******* B
 做事不能集中精力
******* C
 对生活期望值过高
******* D
 高层次交往能力退化
****** 答案
D
***** 9
:PROPERTIES:
:ID: 502db061-4da1-4653-9e67-a2a60dcbf8f1
:END:
****** 问题
******* 音频
bd677149-5912-4524-a342-a608c0b15824.mp3
******* 转录
关于“经营情感”，下列哪项正确？
****** 选择
******* A
是一种陈旧的理论
******* B
人为色彩过于浓重
******* C
“经营“二字内含丰富
******* D
通俗易懒，但可行性差
****** 答案
C
***** 10
:PROPERTIES:
:ID: 2f473168-4f8e-4c02-8824-87ad7d1ed6e6
:END:
****** 问题
******* 音频
5b1bf30c-0c5d-4ec4-93fe-d792df1ec5fe.mp3
******* 转录
这次主题活动希望人们做什么？
****** 选择
******* A
增强对未来幸福的感知力
******* B
暂别网络，关注面对面交流
******* C
完善自己，让朋友为自己而自豪
******* D
有自省精神，提高自己的修养和源养
****** 答案
B
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 5a8c4010-e765-4559-9a6d-9b048db92241
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
70226305-05f6-41fc-ba77-0724cc43ab52.mp3
***** 转录
时至今日，《大数据时代：生活、工作与思维的大变革》仍是全世界最好的一本大数据专著。其作者之一是维克托•迈尔——舍恩伯格，大数据时代的预言家，《科学》《自然》等著名学术期刊最推崇的互联网研究者之一，有在哈佛大学、牛津大学、耶鲁大学和新加坡国立大学等多个互联网研究重镇任教的经历。
《大数据时代：生活、工作与思维的大变革》一书的两位译者中，有一位是我国最年轻有为的大数据专家，年仅 27 岁的周涛教授，数年来他一直带领我国学术界在大数据研究上向国际一流水平看齐。
**** 题目
***** 11
:PROPERTIES:
:ID: 63433a8c-96a6-4eed-8796-edfab7b330f3
:END:
****** 问题
******* 音频
c39e0ac5-0170-42e0-968e-56251d8bc9b1.mp3
******* 转录
《大数据时代:生活、工作与思维的大变革》是一本什么样的书？
****** 选择
******* A
生活用书
******* B
学术著作
******* C
刚出版的书
******* D
倡导改革的书
****** 答案
B
***** 12
:PROPERTIES:
:ID: 98be0dd8-c4a7-4540-b693-1a0a045066c5
:END:
****** 问题
******* 音频
8269331d-6235-4bf9-a454-02a328d85e3b.mp3
******* 转录
关于周涛，下列哪项正确？
****** 选择
******* A
原本是学外语的
******* B
不但年轻而且学术水平高
******* C
是我国研究大数据的第一人
******* D
是《大数据时代:生活、工作与思维的大变革》一书的作者
****** 答案
B
***** 13
:PROPERTIES:
:ID: 17b4d3ee-640a-477e-9476-cca3558d85b5
:END:
****** 问题
******* 音频
9fa74397-df10-4bd1-978a-6d0a3ac8fde9.mp3
******* 转录
这段话主要谈什么？
****** 选择
******* A
维克托.迈尔一舍恩伯格常为《自然》写稿
******* B
《大数据时代:生活、工作与思维的大变革》是一本好书
******* C
杂志对《大数据时代:生活、工作与思维的大变革》评价很高
******* D
哈佛大学、牛津大学、耶鲁大学和新加坡国立大学都是好学校
****** 答案
B
*** 14-17
:PROPERTIES:
:ID: 12e4924e-e304-4905-aa1a-4c9ba6276399
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
d63abfb5-64e6-4500-aa48-f387a217d607.mp3
***** 转录
判断一个东西是不是脏，不仅要看其表面上的细菌数量，还要看上面的致病菌数量，因为致病菌的毒性要远远高于普通细菌。
电脑键盘和没有清洗的鞋子，哪个更容易滋生细菌呢？为了找到答案，有人对一双穿了半年左右的运动鞋和一个用了半年多的电脑键盘上面的细菌数量进行检测对比，结果发现，两件样本都有大量的细菌存在，而键盘上的菌落数量是运动鞋的 65 倍，需要注意的是，键盘上还发现了真菌。为验证键盘和运动鞋中是否存在致病性极高的金黄色葡萄球菌，实验员用试纸进行了测试，幸运的是，测试结果均为阴性，运动鞋和键盘上并没有发现这种细菌。
实验结果显示，运动鞋前脚掌处的细菌数量远不如键盘上的细菌数量多。电脑键盘因为数字键不常使用，其菌落数远远低于字母键盘。
专家建议，电脑键盘每两周用酒精擦拭一次，可有效消灭细菌；清洗运动鞋时一定要注意鞋子内部的清洁，清洗之后，可在阳光下进行暴晒消毒。
**** 题目
***** 14
:PROPERTIES:
:ID: 73104762-39c9-4901-b3b5-5a5d259658e2
:END:
****** 问题
******* 音频
c04a5df0-acae-438a-a9b4-8944380b5651.mp3
******* 转录
根据这段话，下列东西哪个最脏？
****** 选择
******* A
有细菌的东西
******* B
沾上泥土的东西
******* C
布满灰小的东西
******* D
致病菌多的东西
****** 答案
D
***** 15
:PROPERTIES:
:ID: a6b6eec6-9620-4218-92bf-83d04871cb4d
:END:
****** 问题
******* 音频
a5fcee08-6705-4a18-a111-0dc5bfbd5b7f.mp3
******* 转录
关于运动鞋和电脑键盘细菌检测的对比结果，下列哪项正确？
****** 选择
******* A
运动鞋更容易滋生真菌
******* B
电脑键盘更容易滋生细菌
******* C
键盘上发现了金黄色葡萄球菌
******* D
键盘上的菌落数量比运动鞋高65俘
****** 答案
B
***** 16
:PROPERTIES:
:ID: 212c2678-5d5d-4a24-a2c1-f9dace5cde53
:END:
****** 问题
******* 音频
bb3ae393-952e-4490-a035-64b42895a190.mp3
******* 转录
实验结果显示，最脏的是什么部位？
****** 选择
******* A
运动鞋表面
******* B
运动鞋前脚掌处
******* C
电脑键盘的孙母键盘
******* D
电脑键盘的数字键盘
****** 答案
C
***** 17
:PROPERTIES:
:ID: 90a6e875-28b4-49e5-a000-d30848c89133
:END:
****** 问题
******* 音频
a159d0a2-0a41-439d-ba43-c7f6f53803fa.mp3
******* 转录
关于专家建议，下列哪项正确？
****** 选择
******* A
键盘最好用酒精擦洗
******* B
电脑内部更要常清理
******* C
鞋在阳光下暴晒即可
******* D
电脑每次用后应消毒
****** 答案
A
* 阅读
** 第一部分
*** 18
**** 句子
***** A
人们对自己生活的最早零星回忆，一般是四五岁时。
***** B
11月，南方还是秋高气爽，北国早已“草木皆冰”了。
***** C
我们的父辈只知道辛辛苦苦积描财富，不懂得享受人生。
***** D
火车出发以后，一直走在辽阔无边的戈壁滩上，满眼荒凉。
**** 答案
D
*** 19
**** 句子
***** A
他相信，经过协商协商，大家还是可能达成共识的。
***** B
那时，体制、技术等问题堆积如山，纺织业陷人困境。
***** C
很多学者支持这种模型，认为该模型可以取代有效市场假说。
***** D
由于本研究取自非临床样本，所以尚不能作为临床诊断的依据。
**** 答案
A
*** 20
**** 句子
***** A
文字的发展可以从两方面加以考察：造字方法、文字记录语言的完备程度。
***** B
据研究，影响人身心发展的主要因素有遗传、环境和教育，其中教育是主导因素。
***** C
车站上有很多等车的人，但公共汽车毕竟不顾他们，人们只好眼巴巴地看着公共汽车开过去。
***** D
以前，偏远山区的教学条件不好，但近年来，教学仪器、图书资料、文体器材、校舍等，均与一般城市相差无几。
**** 答案
C
** 第二部分
*** 21
**** 段话
英国、日本、菲律宾等岛国，受气候[[gap]]的影响不言而喻，因而[[gap]]气候变化的态度最积极；韩国虽然不是岛国，却三面环海，气候变化对韩国的影响也不能[[gap]]。
**** 选择
***** A
****** 1
条件
****** 2
对付
****** 3
忽略
***** B
****** 1
变化
****** 2
应对
****** 3
小视
***** C
****** 1
环境
****** 2
解决
****** 3
忘记
***** D
****** 1
预报
****** 2
面对
****** 3
被动
**** 答案
B
*** 22
**** 段话
骄傲和自卑从两[[gap]]个背离实事求是的精神。骄傲使人盲目[[gap]]，以致脱离群众，远离进步与成功的道路。自卑是不切实际地过低估计自己，觉得自己[[gap]]不如别人，对[[gap]]、对一切灰心丧气，这往往导致无所作为。
**** 选择
***** A
****** 1
极端
****** 2
自满
****** 3
处处
****** 4
事业
***** B
****** 1
方面
****** 2
优越
****** 3
大大
****** 4
事情
***** C
****** 1
方向
****** 2
透顶
****** 3
远远
****** 4
前景
***** D
****** 1
领域
****** 2
振奇
****** 3
睇哪
****** 4
世界
**** 答案
A
*** 23
**** 段话
新年价始，几位“大牌”记者[[gap]]撰文，从不同角度回眸历史，[[gap]]“地球村”的明天。乐观者有之，悲观者也[[gap]]其人。大家见仁见智，热门话题不少，只是没有人谈及，在经济全球化进程不断[[gap]]的今天，媒体该如何表现。
**** 选择
***** A
****** 1
依次
****** 2
期待
****** 3
时有
****** 4
促进
***** B
****** 1
先后
****** 2
预料
****** 3
增加
****** 4
前进
***** C
****** 1
纷纷
****** 2
聊聊
****** 3
确有
****** 4
迈进
***** D
****** 1
分别
****** 2
展望
****** 3
不乏
****** 4
加快
**** 答案
D
** 第三部分
*** 段话
你身边一定有人手机被偷过，且多数是女性。为什么？细细追究起来，我认为女人丢手机应该是服装设计师的“功劳”。
[[gap:24]]，就是少了功能性。如今出门必带手机，可在女人的衣服上，完全没有合适的地方搁，不是拿在手里就是随便放在很浅的口袋里。那些口袋基本属于为了美观而设置的，放手机完全不靠谱，[[gap:25]]，别说“老偷”了。
其实小偷偷东西不按性别来，只按隼易程度。那些穿户外衣服的人很少被偷，当然是因为衣服口袋多，多到共计多少个口袋都数不过来，[[gap:26]]，小偷到哪儿去找？更重要的是户外服装的口袋有把门的，不是拉链就是魔术贴，[[gap:27]]。可惜这种功能性很强的衣服，女性通常不喜欢，她们认为这种服装会模糊性别概念。
我想说的是，当代设计师也须扭转观念与时俱进，为女人们想得周到一点儿，[[gap:28]]，也要功能性、美观性同时具备。我敢说，这样的设计肯定大受欢迎。
*** 选择
**** A
小偷也就知难而退丁
**** B
女人的衣服大多好看时尚
**** C
即使是女人的服装
**** D
受过初级培训的小偷就能轻易得手
**** E
自己都找不着东西了
*** 答案
**** 24
B
**** 25
D
**** 26
E
**** 27
A
**** 28
C
** 第四部分
*** 29-32
**** 段话
“黑天鹅事件”是当下流行的词语。其实“黑天鹅事件”并不是什么新词。据说，17世纪，欧洲人认为所有的天鹅都是白色的，因为他们从来没见过其他颜色的天鹅。18世纪初，欧洲人漂洋过海来到澳洲，一上岸就惊松了，天鹅居然有黑色的！他们奔走相告，把这消息传回家乡，史称“黑天鹅事件”。
“黑天鹅”的出现告诉人们，世界上永远存在不可预测的事情，尼管人类总是相信自己的经验，希望自己的判断、决定和计划准确无误，无论是第二次世界大战，还是互联网浪潮，发生之前不是没有预兆，但它们的发生还是使人们措手不及、惊愕不已。
普通人日常生活中的选择，也存在黑天鹅现象。我有两个朋友，一个工作党兢业业，对公司不离不弃，十儿年后他成长为技术副总裁，但一个突如其来的财务丑闻使公司倒闭了；另一个总是在选择中跳槽，在跳槽中选择，最后在一家公司工作了两年后，公司上市了，这家伙还去纳斯达克敲了钟！
如果说，以上案例说明，在自然界的物种领域，当今的科技以及信息传播的进步，已经使当年“黑天鹅事件”的出现成为了不可能，但并不能就此说明“黑天鹅事件”全部可以预测，因为第二次世界大战的发生、互联网浪潮的出现以及我朋友的故事都说明，预计未来不是件容易的事情，这，你是否同意？
**** 题目
***** 29
****** 问题
关于“黑天鹅事件”，下列睇项正确？
****** 选择
******* A
已经成为历史
******* B
今天仍有可能发生
******* C
是科技水平低造成的
******* D
日常生活中比比皆是
****** 答案
B
***** 30
****** 问题
“我”的两个朋友的故事说明：
****** 选择
******* A
人无法预计生活中的全部
******* B
社会对丑闻的容忍度很低
******* C
只钻研技术不能换救公司
******* D
不断跳槽有利于人生发展
****** 答案
A
***** 31
****** 问题
文中第3段画线词语“上市”的意思是：
****** 选择
******* A
被卖掉丁
******* B
实行了股份制
******* C
产品得到市场认可
******* D
在证券交易所挂牌交易
****** 答案
D
***** 32
****** 问题
根据上文，下列睇项正确？
****** 选择
******* A
人类还不能准确预测未来
******* B
各个时期的流行词语不一样
******* C
互联网浪潮的出现没有任何先兆
******* D
世界上也许还有其他颜色的天鹅
****** 答案
A
*** 33-36
**** 段话
在低头族盛行的现代社会。很多人已将智能手机视为必不可少的“伴侣”，不少上班族甚至将不眩眼地看手机作为消除疲劳的休闲活动。殊不知，智能手机屏幕发出的“蓝光”在晓间会对人造成多种危害。
蓝光为什么会对人体造成危害告？弄明白这一点的前提是先了解人的生理特点以及作息规律。人脑部的“松果体”生产褪黑素，调整人体的屉夜节律。夜幕降临后，光刺激减弱，褪黑素开始产生，人们有了睡意。日出后，眼普视网膜的感测器感受到蓝光的存在，抑制褪黑素的产生，新的一天开始。由此可以理解，夜闰过多接触蓝光，容易干扰人体县夜节律，带来种种危害。
危害之一就是发胖。夜间面对发出蓝光的手机和电脑超过3小时，人体就会饥馈，部分原因是视网膜接受的蓝光信号传到大脑，大脑认为白天已开始，人体需补充消耗掉的能量。即便当晚吃过晚餐，饥饿感还是会令人产生进食的欲望，当然，过量进食的结果就是发胖。其二，研究发现，经常使用电脑的女性夜间工作者患乳癌的几率比其他女性高17％，护士患癌的风险也可能增加。青少年受光线的影响比成年人要大，有研究显示，469％的成年人在夜间接触蓝光后褪黑素减少，但儿童的数字是88％。人们如果在睡前4小时处于强光环境下，患2型糖尿病的几率增加50％4，并且灯光越强患病概率越大。研究人员推测，人体生物钟可能在控制人体血糖方面发挥树种作用。一位研究员曾让一组成年男子在睡前接触2小时蓝光，另一组不接触光线，两组人睡眠时间相同。结果显示，第一组第二天多人表现困倦，这显示蓝光对生物钟造成影响，导致启动新一天活动的能力降低。
**** 题目
***** 33
****** 问题
什么可以产生褪黑素？
****** 选择
******* A
蓝光
******* B
松果体
******* C
视网膜
******* D
生物钟
****** 答案
B
***** 34
****** 问题
蓝光通过什么对人佛造成危害？
****** 选择
******* A
让人不胚眼普
******* B
控制人体血压
******* C
干扰人体居夜节律
******* D
刺激松果体产生褪黑素
****** 答案
C
***** 35
****** 问题
蓝光为什么会导致人发胖？
****** 选择
******* A
蓝光能促迹食欲
******* B
蓝光会让人感觉麻木
******* C
蛇光会消耗人体能量
******* D
蓝光会让人产生饥偏感
****** 答案
D
***** 36
****** 问题
根据上文，下列晨项正确？
****** 选择
******* A
蓝光会减少患癌几率
******* B
蓝光会让人饭量变大
******* C
蓝光对孩子的影响更大
******* D
视网膜无法感受到蓝光的存在
****** 答案
C
