* 听力

** 1

*** 1

**** transcript

走出学校七年，张越住过地下室，被人炒过鱿鱼，为事业押上过全部财产，也曾经山穷水尽。如今，他从一个冒冒失失的青年成长为颇具头脑的公司高管，全力以赴地干着他最喜欢的工作。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

知名医学杂志《柳叶刀》几年前就发表了一系列综述文章，指出身体活动水平低下是当今人类健康的第四大杀手。世界卫生组织的数据显示，全球每年死亡的人群中，有10％直接源自身体活动水平低下。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

菊花经过人工栽培，由野生变为家菊。据北宋《宣和画谱》记载，菊花作为绘画的表现对象是从唐朝末年开始的，可惜作品无传。中国最早的菊花邮票，是1958年发行的，也是我国第一套花卉邮票。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

每次与朋友说起非洲的撒哈拉沙漠，大家都会想起《撒哈拉的故事》，自然又都会讲起书的作者三毛。当我也来到三毛随丈夫荷西居住的西属撒哈拉那座城市时，我对40年前三毛选择在这里生活有点儿肃然起敬。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

现今不少人喜欢用简练、时尚的网络语言进行交流，无论是在虚拟世界还是现实世界。我们不能说这不是社会发展的正常现象，但我们仍需思考语言如何变化才能更适应社会的发展，而不是向原始时代的简单符号倒退。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: c3fe53b0-6f0e-4a29-914b-d29e009e1212
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：大家好。今天我们请李总跟我们说说他的创业故事。李总，我们很想知道，当初您怎么就选择了美容行业？
男：我选择了一个自己从未涉足过的行业作为事业的起点。当时就想：爱美，是人的天性，只要人类存在，这个行业就会存在；其次，美容业也存在薄弱环节，超过别人的成绩很难，而超越别人的弱点就比较容易了；另外呢，我以前没有接触过这个行业，所以就不会有什么约束，就更有可能超越别人。
女：您就是抱着这样的想法开始在美容行业施展才能的？
男：对。我认为干哪行要研究透哪行。比如，我们的公司创立不久，我就跑遍了全国各地的美容院，一方面取经，学习别人的优点，另一方面就是发现别人的弱点，并且想方设法克服这些弱点，结果我的企业就得到了飞越式的发展。
女：您觉得目前中国的美容业存在哪些问题？
男：从业人员钻研能力不强，文化素养不是很高，缺乏工作激情，人员流动性又很大，这是美容业面临的共同问题。有些店铺装潢前卫，收费也高，顾客的需求却得不到很好的满足。还有，整个行业的店铺使用的产品大多雷同，技术也缺乏特色。
女：所有这些问题不在您身上发生，您就成功了。
男：当然。
女：听说您店里的员工个个都有才干，做事兢兢业业，从不敷衍凑合。
男：用我的话说，我重视的是“态度”。我把“态度”看成是人的第一能力，这种能力比职业技能本身更重要。我注重员工们的心态培养，我坚信人有好的心态，才能把事情做好，美容技术是其次的事情。我觉得自己的成就之一就是改造了我的员工的思想和观念，从我手下走出去的年轻人，回到家乡后，他们的彬彬有礼，常让家人惊叹，他们做事的干练有素也令人折服。这种从精神层面改变人的管理风格，也许就是我成功的原因之一吧。

*** 音频

dcfb9470-9022-4af9-a7a4-2c7e0cf6add4.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 093a71b8-307c-4403-96ad-00585a4229d2
:END:

***** 问题

李总为什么选择了美容业？

***** 音频

314646df-81a1-4150-86a2-9fa14912bdc0.mp3

***** 选择

****** A

他以前做过美容

****** B

美容业比较落后

****** C

美容行业很开放

****** D

人类天生就爱美

***** 答案

D

**** 7
:PROPERTIES:
:ID: f7a136cd-8e20-44ad-90c0-d8cd0824e6ca
:END:

***** 问题

李总创立公司后做了什么事？

***** 音频

a754f978-c0a3-46a7-a257-1bb45de2e8fc.mp3

***** 选择

****** A

努力学习美容技术

****** B

到全国各地去旅行

****** C

克服自己公司的弱点

****** D

吸取其他公司的优点

***** 答案

D

**** 8
:PROPERTIES:
:ID: d4f54004-b6f9-4969-84a1-541ba523a6a4
:END:

***** 问题

以下哪一项是美容业存在的问题？

***** 音频

57037dc0-976f-4f35-b304-067fcaa45cf4.mp3

***** 选择

****** A

从业人员不稳定

****** B

从业人员收人低

****** C

从业人员不爱读书

****** D

美容业收费不公道

***** 答案

A

**** 9
:PROPERTIES:
:ID: c19fa3e4-b778-4518-be0f-0f3635d69b24
:END:

***** 问题

李总企业的管理特点是什么？

***** 音频

f6636fd6-cac4-4233-8a18-88f5689e7eb7.mp3

***** 选择

****** A

注重员工技能的考核

****** B

注重员工心态的培养

****** C

注重员工的工作效率

****** D

培养员工的做事能力

***** 答案

B

**** 10
:PROPERTIES:
:ID: 2b146c7e-71ef-46b6-895b-19dab081c22a
:END:

***** 问题

关于李总，下列哪项正确？

***** 音频

a396e169-2107-48b3-8fec-322e3f4d3fe0.mp3

***** 选择

****** A

虚心做人，认真做事

****** B

对自己的缺点零容忍

****** C

有自己独特的经营之道

****** D

对美容业改革情有独钟

***** 答案

C

