* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 6318e7dd-59a9-4825-8e92-c3a9cdcb8994
:END:
**** 对话
***** 转录
女：我们得快一点儿了，要不然赶不上 2 号线的末班车了。[[file:0fc1301a-cafb-488f-9e91-1752a85eebd6.mp3][(audio)]]
男：别着急，拐过前边的路口就到地铁进站口了。[[file:3ed1da15-62b3-485e-b2a0-2e72c80e731e.mp3][(audio)]]
***** 音频
16185578-9994-4670-9d37-de40f08893ca.mp3
**** 问题
***** 转录
女的为什么着急？
***** 音频
ed6ab4dc-25d8-4885-8ab3-c27f8c8322fb.mp3
**** 选择
***** A
坐错了绕路
***** B
打不到出租车
***** C
怕错过末班车
***** D
找不到地铁入口
**** 答案
C
*** 2
:PROPERTIES:
:ID: e0aee472-a78d-4752-b8ec-1d74fc872ad7
:END:
**** 对话
***** 转录
男：我觉得他们配合得还不太熟练，歌词记得也不过关。[[file:66fadec7-ae1f-4e73-b6d8-766888aa760d.mp3][(audio)]]
女：他们这一组是上个月刚组成的，时间比较短。[[file:bef9aadd-4f1d-4430-9427-90d6095e7af5.mp3][(audio)]]
***** 音频
1e146731-8fbe-4556-9d94-b2884c4d1246.mp3
**** 问题
***** 转录
男的认为他们怎么样？
***** 音频
99594da4-79ca-4946-9866-fe70d2cb3100.mp3
**** 选择
***** A
配合不理想
***** B
动作不优美
***** C
歌词很熟练
***** D
表演很精彩
**** 答案
A
*** 3
:PROPERTIES:
:ID: cfb66247-2f64-48c9-a9bd-d51ecf1e0c72
:END:
**** 对话
***** 转录
女：先生，对不起！飞机马上就要降落了，现在卫生间暂停使用了。[[file:e9266cc1-1473-4fe4-88f4-58cacf3ca630.mp3][(audio)]]
男：好吧，谢谢。[[file:b70c4a60-fb82-4a19-8c1d-40ce4078d599.mp3][(audio)]]
***** 音频
b42cdcf5-3149-456c-b1be-e9b44317aed0.mp3
**** 问题
***** 转录
女的提醒男的什么事？
***** 音频
cad88a84-a37a-4ea6-ba59-bd57c53ad2fd.mp3
**** 选择
***** A
系好安全带
***** B
不能上厕所
***** C
出示登机牌
***** D
调整好座椅
**** 答案
B
*** 4
:PROPERTIES:
:ID: 69fac686-5283-4e8b-9168-2fa12ecdaac8
:END:
**** 对话
***** 转录
女：师傅，我好像记错路了，刚才那个路口应该向左拐。[[file:2d0b2190-1f40-4df8-a6f3-b96d4d277873.mp3][(audio)]]
男：好的，我到下一个路口再调头回来。[[file:661d0c79-91a9-4864-9ac9-de71e0d6e960.mp3][(audio)]]
***** 音频
3f5414f5-1fce-4470-978b-44e4c4dcc15e.mp3
**** 问题
***** 转录
男的接下来打算做什么？
***** 音频
b155291d-b11c-4560-b8af-b4dace826e76.mp3
**** 选择
***** A
下车问路
***** B
调头回去
***** C
靠边停车
***** D
在路口左拐
**** 答案
B
*** 5
:PROPERTIES:
:ID: 04f23339-713a-4776-834c-20c692bf5175
:END:
**** 对话
***** 转录
男：你好，请问南航在哪儿办理登机牌？[[file:27d201be-3fb5-404a-8b07-7c40aac570fc.mp3][(audio)]]
女：您走过了，南航的服务台在 H 区，您往回走。[[file:efc528d7-09d7-4ce6-b700-d6ada48de20e.mp3][(audio)]]
***** 音频
4bb20e5c-8247-46a0-b3b7-74ce51a30aae.mp3
**** 问题
***** 转录
说话人现在最可能在哪儿？
***** 音频
0f4dafea-954a-43ca-81e9-e29ac6ff983f.mp3
**** 选择
***** A
银行
***** B
商店
***** C
机场
***** D
火车站
**** 答案
C
*** 6
:PROPERTIES:
:ID: 0c123c5c-f51f-4ae5-bec5-35bae2ab177f
:END:
**** 对话
***** 转录
女：糟糕，行李箱的钥匙怎么没了？我记得就放口袋里了呀。[[file:09fa9ec6-b156-4dde-84a9-f242c31e1990.mp3][(audio)]]
男：别着急，好好想想，你一般不是都放在随身的小背包里吗？[[file:88b233a1-7eb1-4dc5-9bd4-fee924817117.mp3][(audio)]]
***** 音频
a9f7c26e-1130-447f-a065-b5396d2033ba.mp3
**** 问题
***** 转录
女的怎么了？
***** 音频
ac360198-dea0-4498-9025-36d4aa3c713f.mp3
**** 选择
***** A
忘了箱子密码
***** B
行李箱超重了
***** C
钥匙找不到了
***** D
出来忘锁门了
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：你跟卖电视的售货员咨询了吗？
男：问过了，不过现在的新技术、新名词我也听不太懂。
女：那你打算怎么办？
男：依我看，功能越简单越好，没必要赶时髦。
***** 音频
1e093390-4b1d-4189-b8a1-f01cb553bd2f.mp3
**** 问题
***** 转录
关于买电视，男的想怎么办？
***** 音频
5a3ef36e-2fcd-4390-af9d-d9b4a3b0758f.mp3
**** 选择
***** A
买功能简单的
***** B
买最新的产品
***** C
买技术最先进的
***** D
暂时不考虑买了
**** 答案
A
*** 8
**** 对话
***** 转录
男：你坐地铁到丰联广场，在十字路口西北角有个蓝天商务大厦。
女：然后呢？
男：你从行人的地下通道过来，大厦楼下有个咖啡馆，我在那儿等你。
女：好，我马上过来。
***** 音频
43d4cfe4-7ca9-4932-a4fa-1637decab94a.mp3
**** 问题
***** 转录
女的接下来应该做什么？
***** 音频
309c6760-06d2-476e-a345-a56708b286aa.mp3
**** 选择
***** A
去乘地铁
***** B
参加面试
***** C
去买咖啡
***** D
进地下通道
**** 答案
A
*** 9
**** 对话
***** 转录
女：这两天怎么没开车？
男：之前路上和人碰了一下，不严重，对方负全部责任。
女：保险公司的赔偿手续都办好了吗？
男：处理好了，车也修得差不多了。
***** 音频
bc2b42b5-54e7-4515-84c6-0c1b89313d82.mp3
**** 问题
***** 转录
关于男的，可以知道什么？
***** 音频
e2390bd4-e935-44c8-bc58-f4310e186031.mp3
**** 选择
***** A
负全部责任
***** B
受伤不严重
***** C
车被借走了
***** D
保险已赔偿
**** 答案
D
*** 10
**** 对话
***** 转录
男：刘老师，下周晚上的文化选修课有变动吗？
女：怎么想起问我这个问题？
男：下周不是要期中考试了嘛，晚上的课还上吗？
女：这个没有影响，文化课照常。
***** 音频
0b9a4d4f-76f0-4ce4-b8a1-02cfc344b0e9.mp3
**** 问题
***** 转录
关于文化课，可以知道什么？
***** 音频
eeddc3e3-1577-4dc7-8af9-88fd97dc6cdd.mp3
**** 选择
***** A
下周暂停
***** B
绣续上课
***** C
时间变了
***** D
老师换丁
**** 答案
B
*** 11-12
**** 对话
***** 转录
男：老奶奶，检票了，把您的车票给我看一下。
女：列车员同志，请问到西安要几个小时啊？
男：老奶奶，我们这趟车是沈阳到上海的，不到西安。
女：不对，你看我的车票是北京到西安的啊。
男：您的票是到西安的，这没错，可您上错车了。
女：那怎么办，难道就连司机也没发现他开的方向不对吗？
***** 音频
477a9692-2fdc-4319-8311-6f5a79a18c02.mp3
**** 题目
***** 11
****** 问题
******* 转录
从对话中可以知道这趟列车是去哪儿的？
******* 音频
26a8f0ad-766a-4d73-b116-6148b6bdc35e.mp3
****** 选择
******* A
沈阳
******* B
北京
******* C
西安
******* D
上海
****** 答案
D
***** 12
****** 问题
******* 转录
关于那位老奶奶，可以知道什么？
******* 音频
166e0316-1577-4951-a966-022ab613ef0e.mp3
****** 选择
******* A
买错了车票
******* B
坐错了列车
******* C
头脑很清醒
******* D
想找列车司机
****** 答案
B
*** 13-14
**** 段话
***** 转录
国外一家旅游公司的调查数据显示，赴欧洲的中国游客，46%的人仅尝过一次欧洲食物，10%的人从未吃过一次。而那唯一一次欧洲食物还是旅行社提供的，比如在法国巴黎吃海鲜、在德国吃火腿、在意大利吃意大利面，其余餐饮都是“中国式”，很多人干脆留在酒店房间吃自带的方便面。不过，他们分析说，这不是中国人不吃欧洲食物，只是不习惯而已，何况是在舟车劳顿的旅程中；另一方面，了解欧洲饮食文化并不是中国游客计划的出游项目，不能让他们兴奋，他们更关心游览著名景点。
***** 音频
cdddca44-3466-4ea3-a386-0a1eeaf517dd.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于去欧洲旅游的中国游客，从调查数据中可以知道什么？
******* 音频
7991b613-328f-4faf-ac60-6d58827c4b42.mp3
****** 选择
******* A
喜欢吃海鲜
******* B
常吃方便面
******* C
大多是吃中餐
******* D
不爱吃意大利面
****** 答案
C
***** 14
****** 问题
******* 转录
根据这段话，中国游客去欧洲最喜欢做的是下面哪项？
******* 音频
83b2be38-6839-4e6d-ae19-f4496127d31a.mp3
****** 选择
******* A
游览景点
******* B
观看演出
******* C
品尝美食
******* D
拜访当地人
****** 答案
A
* 阅读
** 第一部分
*** 段话
父子俩住山上，每天都要赶牛车下山卖柴。老父亲比较有经验，负责驾车，山路不宽，弯道很多，儿子眼神比给好，总是在要转弯时提醒道：“爹，拐弯啦！”
有一次父亲受伤了，儿子独自一人[[gap][15]]赶车下山。到了弯道，牛怎么也不肯转弯，[[gap][16]]“，下车又推又拉，用青草引它，牛就是一动不动。
到底是怎么回事？儿子百思不得其解。最后只有一招儿了，他前后看看路上没有行人，就[[gap][17]]牛的耳朵大声叫道；“爹，拐弯啦！”
牛应声而动。
牛用条件反射的方式活着，而人往往依靠习惯生活。一个成功的人懂得如何[[gap][18]]好的习慢，用它们代替坏习惯，当好的习惯积累多了，自然会有一个好的人生。记住，人和人之间的差别并不是很大，优秀不过是一种习惯。
*** 题目
**** 15
***** 选择
****** A
经常
****** B
取消
****** C
轮流
****** D
照常
***** 答案
D
**** 16
***** 选择
****** A
低着头只顾吃草
****** B
站在那里摇着尾巴
****** C
儿子用尽各种方法
****** D
儿子真想回去叫父亲
***** 答案
C
**** 17
***** 选择
****** A
接近
****** B
靠近
****** C
附近
****** D
堵住
***** 答案
B
**** 18
***** 选择
****** A
培养
****** B
休现
****** C
克服
****** D
适应
***** 答案
A
** 第二部分
*** 19
:PROPERTIES:
:ID: e05b1958-1c4d-47bc-8acd-bb6ba3bf164b
:END:
**** 段话
研究学问、学习技能，应该是为充实自己，千万不能为了投他人所好，迎合别人的意愿，或随时代潮流而盲目地进行，否则达不成目的事小，白白浪费了宝贵的时光才最可惜。
**** 选择
***** A
学习是为了自已
***** B
正确的就要坚持
***** C
不要盲目跟随潮流
***** D
要珍惜宝贵的时光
**** 答案
A
*** 20
:PROPERTIES:
:ID: 355a0461-15b5-442a-9d6e-812f16125931
:END:
**** 段话
科研人员对300多名孤独症患儿及约260名没有患孤独症的儿童进行了一项调查，结果发现，环境因素或许是孤独症的一个致病原因，那些居住地离交通主干道大约300米的儿童患孤独症的风险较大。而离交通主干道近意味着受到噪音、尾气污染的风险较大，因此研究人员认为，交通污染可能会导致孤独症。
**** 选择
***** A
靠近交通主干道容易出事故
***** B
孤独症与交通污染可能有关
***** C
住房离交通主干道越远越好
***** D
儿童易受到噪音、尾气的伤害
**** 答案
B
*** 21
:PROPERTIES:
:ID: eec996ee-5c52-468d-8071-a6aefba18ef8
:END:
**** 段话
语言真是奇妙的东西，人和人之间之所以能够沟通、交流和表达，就是因为人是能够使用语言的动物，但是，人和人之间的误解、误会和欺骗也是由语言所导致的。因此，人与人之间语言的表达、沟通和理解也就成了一门学问，特别是现在人际交往的频繁和密切已到了空前的地步。
**** 选择
***** A
语言交流是有技巧的
***** B
人比动物更善于沟通
***** C
少说话才能减少误解
***** D
语言是人际交往的最好方式
**** 答案
A
*** 22
:PROPERTIES:
:ID: c40d306f-579e-4b03-ab68-3ee212e8f1e2
:END:
**** 段话
两千多年前，许多旅行者记载下了他们旅途中的所见所闻。随着时间的推移，其中的七个建筑成为了众所周知的“古代世界七大奇迹”，之所以定为七种，是因为这份名录是希腊人制作的，而他们认为“7”是个有魔力的数字。
**** 选择
***** A
这份名录为世人熟知
***** B
这份名录记录了旅途见闻
***** C
这份名录是旅行者编制的
***** D
希腊人认为这份名录有魔力
**** 答案
A
** 第三部分
*** 23-25
**** 段话
有一个人经常出差，经常买不到对号入座的车票。可是无论长途短途，无论车上多挤，他总能找到座位。
他的办法其实很简单，就是耐心地一节车厢一节车厢找过去。这个办法听上去似乎并不高明，但却很管用。每次，他都做好了从第一节车厢走到最后一节车厢的准备，可是每次他都用不着走到最后就会发现空位。他说，这是因为像他这样锲而不舍找座位的乘客实在不多。经常是在他落座的车厢里尚余若干座位，而其他车厢的过道和车厢接头处居然人满为患。他说，大多数乘客轻易就被一两节车厢拥挤的表面现象欺骗了，不大细想在数十次停靠之中，从火车十几个车门上上下下的流动中藏着不少出现座位的机遇；即使想到了，他们也没有那一份寻找的耐心。眼前一方小小立足之地很容易让大多数人满足，为了一两个座位背负着行李挤来挤去有些人也觉得不值。他们还担心万一找不到座位，回头连个好好站着的地方也没有了。与生活中一些安于现状、不思进取、害怕失败的人永远只能滞留在没有成功的起点上一样，这些不愿主动找座位的乘客大多只能在上车时最初的落脚之处一直站到下车。
自信、执着、富有远见、勤于实践，会让你握有一张人生之旅永远的坐票。
**** 题目
***** 23
****** 问题
上文中的“他”总能找到座位的方法是：
****** 选择
******* A
找列车员帮忙
******* B
装病骗人给他让座
******* C
找准备下车的乘客
******* D
耐心地一直找过去
****** 答案
D
***** 24
****** 问题
大多数不愿主动找座位的乘客一般会怎样？
****** 选择
******* A
挤在车厢门口处
******* B
站在最初上车的地方
******* C
等不了提前下车
******* D
很快就有人给他让座
****** 答案
B
***** 25
****** 问题
上文主要想说的是：
****** 选择
******* A
出行要当心被骗
******* B
失败是成功之母
******* C
坚持才能把握住机会
******* D
不要被眼前的假象欺骗
****** 答案
C
*** 26-28
**** 段话
一天，机场的工作人员迎来了一位很特别的女乘客——一位身体巨胖的女乘客。
当这位女乘客出现在他们面前的时候，他们几乎全被惊呆了。对他们之中的大多数人来说，这或许是他们有生以来见过的最胖的女子——这位女乘客胖得几乎连走路都困难了，她是被亲人用轮椅推进候机大厅的。
于是，问题迎面而来了。因为当大家为她办理海关、安检等手续时，猛然发现所有的门对她来说都显得实在太窄了，她根本就无法通过这一扇扇门，顺利地办好手续登机。
工作人员不得不将这个难题交给了领导，向上级报告和请示。你一定会想，遇到这种事情，换作任何一个领导也无可奈何，他们能做的或许就是道歉、退票了。但是令大家吃惊的是，领导居然做了一个令人惊讶的决定——拆门！
领导当即决定迅速抽调工程人员组织一个“拆门小队”，他们一定要为这名乘客拆开一扇大门，让她顺利登机。因为他们不能滞留任何一名乘客，让乘客抱憾而归。就这样，这位肥胖的女乘客一路经过拆开的大门，来到了飞机跟前。
但是此时问题又出现了，她无法一步步顺着扶梯登机。于是机场的领导再次做出决定——用机场行李升降机把她送到舱门口。还好，这位女乘客的身体刚好能进入舱门。最后机组人员全部出动，将她安顿在了整整三个位置上。
最终，他们把这位满怀感动的女乘客送到了她的目的地。
无论是对那些身体有缺陷的人，还是健康的人，我们都要有一颗尊重之心。尊重别人，可能会牺牲自己眼前的一点儿私利，但却能换来长远的利益。每给予一份尊重，自我价值也会随之提升。
**** 题目
***** 26
****** 问题
关于那位女乘客，从文中可以知道：
****** 选择
******* A
身材苗条
******* B
很有礼貌
******* C
无法行走
******* D
深受感动
****** 答案
D
***** 27
****** 问题
为让她顺利登机，机场方面都做了什么努力？
****** 选择
******* A
飞机延迟起飞
******* B
拆开了机舱门
******* C
用升降机登机
******* D
坐轮椅过安检
****** 答案
C
***** 28
****** 问题
上文主要想告诉我们什么？
****** 选择
******* A
健康非常重要
******* B
安全是第一位的
******* C
办法总会有的
******* D
每个人都应受尊重
****** 答案
D
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
