* 练习

** 1
:PROPERTIES:
:ID: e1b8f5ae-b026-46ae-b086-2313873bbbe8
:END:
*** 选择
**** 1
保险
**** 2
缓解
**** 3
赔偿
**** 4
拥挤
**** 5
咨询
**** 6
展开
*** 题目
**** 1
***** 句子填空
每当体育馆有比赛举行，周围的交通就会出现[[gap]]情况。
***** 答案
4
**** 2
***** 句子填空
手术有风险，小明父母[[gap]]了许多专家后，还是决定做。
***** 答案
5
**** 3
***** 句子填空
为了赢得顾客，双方一定会在服务方面[[gap]]兑争。
***** 答案
6
**** 4
***** 句子填空
小李办事太马虎，你派他去可不太[[gap]]。
***** 答案
1
**** 5
***** 句子填空
车的问题已经处理好了，保险公司正在办理[[gap]]手续。
***** 答案
3
**** 6
***** 句子填空
道路修通后，灾民饮水困难的问题得到了[[gap]]。
***** 答案
2
** 2
*** 1
:PROPERTIES:
:ID: d48e9d38-5948-480e-81b7-7227ea2f54f2
:END:
**** 句子填空
学校规定，旷课达到60节以上的学生[[gap]]其考试的资格。
**** 选择
***** A
取消
***** B
消失
**** 答案
A
*** 2
:PROPERTIES:
:ID: 9be44937-e79d-4ab8-a188-7daf418ad099
:END:
**** 句子填空
汽油明天要涨价了，[[gap]]加油站又有车在排队加油呢。
**** 选择
***** A
难怪
***** B
难道
**** 答案
A
*** 3
:PROPERTIES:
:ID: ea467d2e-c9d1-4a71-9778-f6a1a1519f18
:END:
**** 句子填空
一个好的领了地导能[[gap]]听取不同的意见。
**** 选择
***** A
廉虚
***** B
虚心
**** 答案
B
*** 4
:PROPERTIES:
:ID: 578013a4-bbac-4ea4-bbd5-bb92e2e71eb7
:END:
**** 句子填空
调查发现，有60％的人[[gap]]表示愿意选择公交出行。
**** 选择
***** A
明确
***** B
清楚
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
展开
***** 答案
辩论
**** 2
***** 词语
扩大
***** 答案
影响
**** 3
***** 词语
归纳
***** 答案
观点
**** 4
***** 词语
批准
***** 答案
方案
*** 2
**** 1
***** 词语
缓解
***** 答案
矛盾
**** 2
***** 词语
取消
***** 答案
限制
**** 3
***** 词语
赔偿
***** 答案
损失
**** 4
***** 词语
期待
***** 答案
胜利
* 扩展
** 词语
*** 话题
交通
*** 词语
**** 1
卡车
**** 2
列车
**** 3
摩托车
**** 4
行人
**** 5
车厢
**** 6
车库
**** 7
拐弯
**** 8
绕
**** 9
长途
**** 10
运输
**** 11
汽油
**** 12
罚款
** 题目
*** 1
**** 句子
列车长办公室在9号[[gap]]，请到那儿办理补票手续。
**** 答案
5
*** 2
**** 句子
刚考下驾照时，他陪我到郊外练车，[[gap]]、倒车、停车，没一个月我就敢自己上路了。
**** 答案
7
*** 3
**** 句子
月亮[[gap]]了球一圈的真实时间是27日7小时43分11秒。
**** 答案
8
*** 4
**** 句子
这个交通标志表示禁止停车，在这儿停车是要被[[gap]]的。
**** 答案
12
* 注释
** （三）词语辨析
*** 表现——体现
**** 做一做
***** 1
****** 句子
用表格来说明问题是一种有条理的思考方法的[[gap]]。
****** 答案
******* 1
******** 表现
0
******** 体现
1
***** 2
****** 句子
人们一直认为，哭是胆小、软弱的[[gap]]。
****** 答案
******* 1
******** 表现
1
******** 体现
0
***** 3
****** 句子
丽丽是不会错过这个在大家面前[[gap]]自已的机会的。
****** 答案
******* 1
******** 表现
1
******** 体现
0
***** 4
****** 句子
人生的价值不[[gap]]在你口袋里有多少钱，而在于你为社会做出了多少贡献。
****** 答案
******* 1
******** 表现
0
******** 体现
1
* 课文
** 转录
城市汽车的数量迅速增长，最初还被视为是社会发展、经济繁荣的体现。但很快人们就发现了问题。随着车流量的增加，道路变得格外拥挤，堵车在大城市中已经成了家常便饭。
解决交通拥堵的问题就要减少单位面积道路内的汽车数量，新建或加宽道路被公认为最基本的方法。但事实证明这只是我们美好的主观愿望，道路扩建的速度远远跟不上车流量增加的速度，面积的增加并未使道路空出空间来，甚至还会无形之中鼓励更多的司机开车上路，使得市中心的道路更加拥挤。
那么，如何根治交通拥堵呢？这里我们不妨听听佩·詹森的故事。
詹森一到欧洲环境保护署交通部工作，就接到了研究如何解决城市拥堵问题的任务。于是，他开始展开调查，研究收集上来的数据，归纳问题特点，并虚心咨询了有关专家。
九月中旬的一天早晨，詹森照常提前出门赶在早高峰之前去交通部。他看到一个健身的人慢跑通过一个有过街天桥的路口时，为图省事没上天桥，而是横穿马路。结果，他被一辆车撞倒在地，虽然最后他只是受了点轻伤，而且有保险可以赔偿，但司机还是被吓得不轻。
不过这件事倒是给了詹森启发：开车出行是为了省时省力，但如果情况相反呢？他决定要改变市民出行的观念，反其道而行之        让城市先堵起来，给司机制造麻烦，以堵治堵。
经过多次努力，政府批准了他提出的改革措施，比如，增设红绿灯，让车辆不得不走走停停；在主要十字路口取消地下通道，让行人从地下重返地面；在购物广场、商务大厦的附近不建停车场等。同时，大力发展公共交通。
半年过去了，虽然市民们有些抱怨，但效果非常明显，自愿放弃开私家车出门的人越来越多。这也难怪，与其堵在路上浪费时间和汽油，污染环境，倒不如改乘公交出行。这样一来，道路拥堵大为缓解。
城市本是为人而建，如今却被汽车占有，詹森的目标很明确，就是期待能够解放城市，使之更适合人类生活。
