* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 547ab524-713b-4614-b6a1-16beddd95ff4
:END:
**** 对话
***** 转录
女：在汉语当中，语音、汉字、词汇、语法，你对哪个最感兴趣？[[file:a64a33f7-3e24-4491-95bc-5423b55af3c1.mp3][(audio)]]
男：古今词义的变化，我觉得最有意思。[[file:94abd1af-17ec-44cf-9980-b42b94672857.mp3][(audio)]]
***** 音频
e824f2a5-e81c-4319-a63d-6331c142092a.mp3
**** 问题
***** 转录
男的对什么最感兴趣？
***** 音频
0287a095-3c8c-4b28-ae80-3821c5657987.mp3
**** 选择
***** A
语音
***** B
汉字
***** C
词汇
***** D
语法
**** 答案
C
*** 2
:PROPERTIES:
:ID: 9685c527-e066-409a-997c-f4d1c096e044
:END:
**** 对话
***** 转录
男：怎么这么半天才来？[[file:5538420b-50d0-4fda-9f8e-d4ea3f99c89b.mp3][(audio)]]
女：别提了，门口很多人抢着买票，半天才进来。[[file:3d36cb81-b6f2-483b-ad9b-d44985f205af.mp3][(audio)]]
***** 音频
80372e48-8ba5-4f86-886e-2616a984dec3.mp3
**** 问题
***** 转录
女的为什么来得晚？
***** 音频
24b49579-d066-441e-a49d-12cfb50ba5ff.mp3
**** 选择
***** A
堵车了
***** B
门口人多
***** C
没抢到票
***** D
被人拦住了
**** 答案
B
*** 3
:PROPERTIES:
:ID: 17028452-1164-42cd-b3fc-7d640da8869a
:END:
**** 对话
***** 转录
女：李教授，请您谈谈最近几年，汉语新词语有哪些特点？[[file:257959ec-db8f-47d4-83f0-c2e83a56e4de.mp3][(audio)]]
男：首先，在当前产生的新词语中，多音节词明显增多，打破了以前双音节占主要地位的局面。[[file:9e306a55-e29a-4571-ae43-2ebbdb72df7d.mp3][(audio)]]
***** 音频
503d8d5c-0a1c-47ea-ae1d-75f2ba9a8b4d.mp3
**** 问题
***** 转录
李教授提到汉语新词语有什么变化？
***** 音频
9a47b702-0fc3-4049-aabb-822dd23be3c6.mp3
**** 选择
***** A
双音节词增加了
***** B
双音节词减少了
***** C
多音节词增加了
***** D
多音节词减少了
**** 答案
C
*** 4
:PROPERTIES:
:ID: 9f7b5585-3b2c-4c32-b140-aca6561e9d6c
:END:
**** 对话
***** 转录
男：试了这么多次都不行，我真的想放弃了。[[file:c5432ef9-c042-4d0b-9e5f-f53f2731c473.mp3][(audio)]]
女：别着急，机会总是给有准备的人，你一定能成功。[[file:97648e5d-e89c-4a41-aeda-d30ffbc0b4fa.mp3][(audio)]]
***** 音频
a9818aa5-124b-445a-861a-5c0857d16b26.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
81b11052-c13b-428b-b8ad-3029e7b6ca6f.mp3
**** 选择
***** A
抱怨的
***** B
惭愧的
***** C
鼓励的
***** D
无奈的
**** 答案
C
*** 5
:PROPERTIES:
:ID: bac5de9b-db10-4e6d-99f8-917193a36072
:END:
**** 对话
***** 转录
女：老王，今天你穿这件 T 恤显得格外年轻。[[file:6100b419-fc5f-4f8b-8ccd-6ac36de0e7d8.mp3][(audio)]]
男：老婆昨天刚给我买的，挺贵的。[[file:bb52d72c-2008-490a-ae44-1e87be86585c.mp3][(audio)]]
***** 音频
6f86cfd5-e53d-4dab-a4a4-c284071cae38.mp3
**** 问题
***** 转录
女的觉得男的这件衣服怎么样？
***** 音频
b7f7fe12-5530-4df4-827c-8f238c0cc578.mp3
**** 选择
***** A
太小
***** B
很好
***** C
很特别
***** D
太贵了
**** 答案
B
*** 6
:PROPERTIES:
:ID: 4bfe8aae-cef6-42a0-8256-869cb4b715af
:END:
**** 对话
***** 转录
女：好久不见，你可胖了不少。[[file:377c11dc-93f6-4514-82aa-34c091ef8bc3.mp3][(audio)]]
男：看来我得限制一下自己的食量了。[[file:77c19eda-6e13-4a40-a0db-569ac282ed56.mp3][(audio)]]
***** 音频
a864718a-fa05-402c-a9b2-0071bf9ea560.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
d4f7020c-0a63-4710-874c-ae9a6e552b79.mp3
**** 选择
***** A
别限制他
***** B
他要减肥
***** C
女的在胡说
***** D
他吃得不多
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：我儿子真是太调皮了！我都快受不了了。
男：小孩子嘛，多少都有点儿淘气。
女：有点儿？你是没见过他，不知道。
男：那你下次把他带到办公室来玩儿玩儿。
***** 音频
5f2df029-25c6-46b6-9f80-6e74c72f614c.mp3
**** 问题
***** 转录
他们最可能是什么关系？
***** 音频
b5a976f6-61cb-4525-966b-9c4f2b988f0c.mp3
**** 选择
***** A
夫妻
***** B
母子
***** C
同事
***** D
师生
**** 答案
C
*** 8
**** 对话
***** 转录
男：给你盛点儿饭吧？
女：不用，我减肥呢，不吃主食。
男：你每天光吃蔬菜，连肉都不吃，会营养不足。
女：我觉得没问题，我身体挺好的。
***** 音频
3577bf0f-2ef6-4ca4-86d1-d41fd662e02c.mp3
**** 问题
***** 转录
女的只吃什么？
***** 音频
4c7d2fc1-cc4b-4cc7-8203-82dfd8bf5d85.mp3
**** 选择
***** A
主食
***** B
茶菜
***** C
肉类
***** D
水果
**** 答案
B
*** 9
**** 对话
***** 转录
女：新来的小姑娘真是太不会干活儿了！
男：你多教教她，慢慢就好了。
女：我除了干自己的还得帮她？那我多吃亏啊，挣一份钱打两份工！
男：哎呀，不是说吃亏就是福吗？
***** 音频
9fb792bb-79d1-438c-b7e7-d96c765ad06c.mp3
**** 问题
***** 转录
男的在表达什么意思？
***** 音频
39452124-1df3-4f90-8197-f443b752e021.mp3
**** 选择
***** A
抱怨
***** B
委屈
***** C
询问
***** D
安慰
**** 答案
D
*** 10
**** 对话
***** 转录
男：这个办法似乎行不通。
女：我们还没试过，你怎么知道不行？
男：以前有另一个团队用过这个办法，就没成功。
女：那要不你再宽限我两天？我再想想别的法子。
***** 音频
5f51719b-9e69-49a8-98d1-587594267765.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
745d9560-1188-4ec0-a96b-d3544e6045bf.mp3
**** 选择
***** A
已经想丁很多办法
***** B
已经试过这个办法
***** C
这是最好的方式
***** D
还需要更多时间
**** 答案
D
*** 11-12
**** 对话
***** 转录
男：老师，“朝三暮四”是一个成语，对吧？
女：是的。成语是汉语中特有的一种语言现象。
男：成语有什么特点呢？
女：它们有固定的结构，不能随便更改。
男：听说很多成语背后都有故事？
女：对，成语的意义并不一定是每个字意思的简单相加，而是一个整体。
***** 音频
8d938961-8212-40ca-abfa-06c65f6ad701.mp3
**** 题目
***** 11
****** 问题
******* 转录
对话中提到了哪个成语？
******* 音频
7b283754-1cd1-47a3-99d6-0a6937da6214.mp3
****** 选择
******* A
育人摸象
******* B
朝三暨四
******* C
全神贯注
******* D
相敬如宾
****** 答案
B
***** 12
****** 问题
******* 转录
“成语不能随便更改”说的是它哪方面的特点？
******* 音频
1ad60c55-f5c6-4056-ac70-8559f59fdc99.mp3
****** 选择
******* A
结构特点
******* B
意义特点
******* C
使用特点
******* D
历史特点
****** 答案
A
*** 13-14
**** 段话
***** 转录
有一天,兔子兄弟得到一块大饼，可是他们碰到了一个大难题：一个大饼要怎么分才公平呢？这时候跑来一只狐狸。狐狸说：“我来帮你们呀。”说着狐狸就把饼掰作了两半。他故意把左边一块大一点儿递给兔哥哥，把小的一块儿递给兔弟弟。兔弟弟哭了，说：“我不干，哥哥的比我的大。”狐狸说：“没事没事，我是最公平的。”说着狐狸便咬了一口兔哥哥的饼，兔弟弟笑了，兔哥哥又哭了，狐狸又咬了一口兔弟弟的饼……就这样，一块饼被狐狸左一口、右一口地咬光了。
***** 音频
c94d43cb-3fe8-49ca-927d-bc9462d4d616.mp3
**** 题目
***** 13
****** 问题
******* 转录
狐狸说自己来干什么？
******* 音频
ac1233ea-1405-49be-8433-fc220714ab92.mp3
****** 选择
******* A
来尝克子兄弟的饼
******* B
来看兖子兄弟的饼
******* C
来帮兔子兄弟分饼
******* D
来送给兔子兄弟饼
****** 答案
C
***** 14
****** 问题
******* 转录
最后谁吃到了饼？
******* 音频
e29f583b-fcf9-4583-994c-419642ec1a8a.mp3
****** 选择
******* A
狐狸
******* B
兖哥哥
******* C
兔弟弟
******* D
都没吃到
****** 答案
A
* 阅读
** 第一部分
*** 段话
如果你常常在手机或电脑上跟人聊天儿的话，相信你除了输人文字，一定也用过[[gap][15]]。有了它，互联网时代的我们变得越来越懒。以前我们想要表达一种意思，比如[[gap][16]]，可能需要花时间打出一句[[gap][17]]的话；而现在，只要轻松地点一个笑脸就好了。不过，也有专业人士怀疑它的发展前景，他们[[gap][18]]并不认为这种方式能够一直被大范闵应用下去。
*** 题目
**** 15
***** 选择
****** A
表演
****** B
表情
****** C
表面
****** D
表达
***** 答案
B
**** 16
***** 选择
****** A
我很生气
****** B
我很吃惊
****** C
我很高兴
****** D
我很伤心
***** 答案
C
**** 17
***** 选择
****** A
完整
****** B
整齐
****** C
整个
****** D
整体
***** 答案
A
**** 18
***** 选择
****** A
相信
****** B
相以
****** C
似的
****** D
似乎
***** 答案
D
** 第二部分
*** 19
:PROPERTIES:
:ID: fa871cab-a6a1-4f89-a0e0-51d0f365daa3
:END:
**** 段话
从前有位老人，他很喜欢动物，便喂养了一群猴子当宠物。相处久了，他们的关系越来越好，彼此居然可以从表情、声音和行为举止中丁解对方的意思。所以，虽然猴子不会说话，他们仍然可以很好地交流。
**** 选择
***** A
老人把猴子当朋友
***** B
他们通过语言互相交流
***** C
他们之间的关系不太好
***** D
他们能理解对方的意思
**** 答案
D
*** 20
:PROPERTIES:
:ID: 1df1dc68-65fb-481b-805b-9573747540de
:END:
**** 段话
你永远是别人嘴里的故事，而别人的故事又永远在你的嘴里。结果故事从你的嘴到别人的耳朵，然后再从别人的嘴到另一个人的耳朵，就这样一路流传下去。最后你会听到你的故事，是一个热心的人好意过来告诉你的。你听完了，却不知道那是你的故事，因为在你的身上，从来没有发生过如他嘴里所叙述的那样的故事。到底那是谁的故事？哟，原来是集体创作。
**** 选择
***** A
每个人都喜欢给别人讲故事
***** B
大家希望别人知道自己的故事
***** C
故事在流传的过程中会有变化
***** D
大家一起商量写了一个故事
**** 答案
C
*** 21
:PROPERTIES:
:ID: 463bab04-bacb-44fc-8130-d9f7e655a01e
:END:
**** 段话
恋人们之间彼此常有亲昵的称呼。有的国家，恋人用小动物相称，如维也纳人称自己的心上人为“我的小蜗牛”；有的国家以植物相称，如日本人称其恋人为“美丽的山花”；还有的国家用食物称呼自己的情人，如美国人叫“蜜糖”，波兰人称“饼干”。
**** 选择
***** A
每对恋人之间都有昵称
***** B
蜗牛是一种植物的名称
***** C
“美丽的山花”是日本人用的
***** D
“蜜糖、饼干”都是人的名字
**** 答案
C
*** 22
:PROPERTIES:
:ID: 2f0ddad9-c123-4797-b1f8-b255734546e2
:END:
**** 段话
强烈的需要会成为某一时期消费行为的决定性力量。但是，某一需要最终转换为消费行为还取决于消费者个人的习惯、个性和家庭的收人总水平与财产额的高低，以及家庭规模与结构的特点。
**** 选择
***** A
消费行为与需要无关
***** B
消费行为与财产有关
***** C
消费行为与性别有关
***** D
消费行为与收人无关
**** 答案
B
** 第三部分
*** 23-25
**** 段话
就讲单一语言的人口而言，汉语是世界上最大的语种，以汉语为母语的人有十几亿。
我们平时说的汉语，其实更多时候指的是普通话。普通话是中国不同民族间进行沟通交流的通用语言，以北京语音为标准音，以北方话为基础方言，以典范的现代白话文著作为语法规范。而汉语中还包括很多方言，如北方方言、吴方言、粤方言、闽方言、赣方言、湘方言和客家话。
汉语缺少严格意义的形态变化，这是汉语和印欧语言的根本区别，并由此产生了一系列其他特点：第一，同样的词，语序不同，组成的短语或句子就不一样。第二，汉语词类和句法成分的关系复杂，并不对应，如名词，既可以做主语、宾语，也可以做定语、状语，在一定的条件下甚至还可以做谓语。第三，音节的多少会影响语法形式，例如，有些双音节词就要求跟其他的双音节或多音节词一起使用，而不能用同样意义的单音节词，比如我们可以说“显得高兴、显得格外美丽”，但不能说“显得高”，必须说“显得很高”。
随着社会的发展，汉语也处于不断的变化完善中。所以，要学好汉语，我们也必须关注汉语的新发展。
**** 题目
***** 23
****** 问题
“七大方言”不包括：
****** 选择
******* A
北方方言
******* B
湘方言
******* C
普通话
******* D
客家话
****** 答案
C
***** 24
****** 问题
下列哪项反映了汉语的语序特点？
****** 选择
******* A
汉语不说“三个学生们”
******* B
“固定座位”和“座位固定”不同
******* C
可以说“今天星期一”
******* D
不能说“互相帮”
****** 答案
B
***** 25
****** 问题
关于汉语的描述，下列哪项正确？
****** 选择
******* A
普通话以北京语音为标准音
******* B
汉语属于印欧语言
******* C
汉语词类与句法成分一一对应
******* D
汉语是固定不变的
****** 答案
A
*** 26-28
**** 段话
“不得要领”这个成语来源于《史记》成语中的“要”，即“腰”，指衣腰；“领”指衣领。古人上衣下裳，提上衣时拿着衣领，提下裳时拿着腰的部分。所以“要领”比喻人的主要意思或态度。“不得要领”现在一般用来形容说话、写文章抓不住要点或关键。
《史记》中记载了汉武帝初即位的时候，听说北方的月氏人对匈奴人怀着强烈的仇恨，他们想攻打匈奴，但得不到别国的帮助。当时，武帝正想消灭匈奴。听了这话，就招募了张骞作为使者，出使月氏。
要到月氏去，必须经过匈奴，很不幸，张骞经过匈奴的时候被抓住了。匈奴的王把张骞扣留下来，并且对他说：“月氏在我们的西北，你们汉人怎么能穿过我们的地方，出使到那里去？如果我们要出使到越国去，你们能让我们去吗？”就这样，张骞被匈奴扣留了十多年，还在那里成了家，生了儿子。
后来，匈奴放松了对张骞的监视，他就与随从们一起逃走了。在其他国家的帮助下，终于找到了月氏人西迁以后建立的大月氏。但是，现在月氏国人已经立了被杀国王的太子为新国王，在新土地上定居了下来。那里物产丰富，没有战争，他们只想过太平的日子，不再有向匈奴报复的心愿了。张骞谈的夹击匈奴的事月氏人并不感兴趣，他在那里停留了一年多，劝说一直抓不住要点，不得要领，始终不能得到月氏对与汉共击匈奴之事的明确表态，最后只得起程回国。
**** 题目
***** 26
****** 问题
“不得要领”中的“领”是指：
****** 选择
******* A
领带
******* B
领导
******* C
本领
******* D
衣领
****** 答案
D
***** 27
****** 问题
“不得要领”的故事发生在什么时候？
****** 选择
******* A
汉武帝在位的时候
******* B
汉武帝攻打匈奴的时候
******* C
建立大月氏的时候
******* D
写《史记》的时候
****** 答案
A
***** 28
****** 问题
为什么说张骞“不得要领”？
****** 选择
******* A
他被抓住了
******* B
他在匈奴成了家
******* C
他没有找对地方
******* D
他没有把握劝说的要点
****** 答案
D
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
