* 练习

** 1
:PROPERTIES:
:ID: b084726b-098a-444e-aece-7d435f00e7aa
:END:
*** 选择
**** 1
颗
**** 2
群
**** 3
安慰
**** 4
似乎
**** 5
限制
**** 6
相处
*** 题目
**** 1
***** 句子填空
希望我们能够友好[[gap]]，共同发展。
***** 答案
6
**** 2
***** 句子填空
他最近心情不太好，事情[[gap]]办得不太顺利。
***** 答案
4
**** 3
***** 句子填空
聚在电台门口的那[[gap]]人是干什么的？
***** 答案
2
**** 4
***** 句子填空
她跟丈夫离婚后非常伤心朋友们轮流来[[gap]]她。
***** 答案
3
**** 5
***** 句子填空
小明昨天掉了一[[gap]]牙齿，这是他第一次换牙。
***** 答案
1
**** 6
***** 句子填空
这次的作文不[[gap]]字数，你可以想写多少就写多少。
***** 答案
5
** 2
*** 1
:PROPERTIES:
:ID: cc634ffa-2365-415b-8e9a-60da6e9082eb
:END:
**** 句子填空
我建议这几天我们应该把下周会议讨论话题的顺序[[gap]]下来。
**** 选择
***** A
固定
***** B
一定
**** 答案
A
*** 2
:PROPERTIES:
:ID: 09af7b35-70b8-4cdf-bcd7-56241389a8a4
:END:
**** 句子填空
汉语的[[gap]]非常丰富，你得特别注意近义[[gap]]之间的区别。
**** 选择
***** A
词
***** B
词汇
**** 答案
***** 1
B
***** 2
A
*** 3
:PROPERTIES:
:ID: 5df96bc3-7f5e-4b32-a537-6061600d2e2c
:END:
**** 句子填空
这篇文章[[gap]]上写得不错，有些小地方还要再改改。
**** 选择
***** A
整体
***** B
完整
**** 答案
A
*** 4
:PROPERTIES:
:ID: afebd08a-0329-4338-9d87-77731b4398bc
:END:
**** 句子填空
这两个女孩儿关系非常好，[[gap]]亲姐妹一样。
**** 选择
***** A
似乎
***** B
好像
**** 答案
B
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
从成为[[A]]学同学以来，[[B]]他们就[[C]]相爱[[D]]了。
**** 词语
彼此
**** 答案
C
*** 2
**** 句子
他输了这场比赛不是因为能力[[A]]不够[[B]]，而是因为[[C]]准备[[D]]。
**** 词语
不足
**** 答案
D
*** 3
**** 句子
[[A]]我[[B]]根想辞职，但是[[C]]我妻子[[D]]不支持我的想法。
**** 词语
倒是
**** 答案
B
*** 4
**** 句子
你已经[[A]]不错了，别老觉得自己好像[[B]]仡了[[C]]亏[[D]]似的！
**** 词语
大
**** 答案
C
* 扩展
** 词语
*** 话题
饮食1
*** 词语
**** 1
食物
**** 2
粮食
**** 3
蔬菜
**** 4
豆腐
**** 5
辣椒
**** 6
花生
**** 7
土豆
**** 8
玉米
**** 9
馒头
**** 10
海鲜
**** 11
香肠
** 题目
*** 1
**** 句子
[[gap]]主要是指可以做主食的东西，比如大米，土豆，玉米等。
**** 答案
2
*** 2
**** 句子
你不能每顿饭光吃肉，还得多吃[[gap]]。
**** 答案
3
*** 3
**** 句子
我不太能吃辣，麻烦你做菜时少放点儿[[gap]]。
**** 答案
5
*** 4
**** 句子
我老家靠海，所以我从小就喜欢吃[[gap]]。
**** 答案
10
* 注释
** （三）词语辨析
*** 彼此——互相
**** 做一做
***** 1
****** 句子
你们是姐妹，应该[[gap]]照顾。
****** 答案
******* 1
******** 彼此
1
******** 互相
1
***** 2
****** 句子
对同一个问题，[[gap]]的认只不同，是很正常的事情。
****** 答案
******* 1
******** 彼此
1
******** 互相
0
***** 3
****** 句子
我们是夫妻，各自除了孝顺自己的父母，也应该孝顺[[gap]]的父母。
****** 答案
******* 1
******** 彼此
1
******** 互相
0
***** 4
****** 句子
现在是我们公司最困难的时候，大家应该[[gap]]支持，[[gap]]帮助。
****** 答案
******* 1
******** 彼此
0
******** 互相
1
******* 2
******** 彼此
0
******** 互相
1
* 课文
** 转录
成语是汉语中非常有特点的一部分词汇。成语有固定的结构，不能随便更改；意义是整体性的，不是每个字意思的简单相加，而是综合起来表达一个完整的意思。
一般来说，成语的意义也是稳定的，很少发生变化，比如我们学过的“盲人摸象”和“精诚所至，全石为开”。但也有古今不同的，像我们今天要学习的“朝三暮四”。
中国古代有一位哲学家，在他的书中讲了这样一个寓言故事：
从前有位老人，喂养了一群猴子当宠物。相处久了，彼此居然可以从表情、声音和行为举止中了解对方的意思。
猴子太多，每天要吃大量的瓜果、蔬菜和粮食。然而，一个普通的家庭，财产不多，哪有那么大的财力满足一群猴子对食物的长期需要呢？老人甚至必须减少家人的消费，好节省些食物拿去喂养猴子。他注意到该限制猴子的食量了。
问题是，猴子不像猪、狗，吃不饱时仅仅只是叫叫，它们如果得不到好的待遇，就会像一群调皮的孩子，经常跟人淘气。
老人的朋友送给他很多橡子，这是一种猴子爱吃的果实。在其他粮食不足的情况下，用橡子喂猴子倒是个办法。于是老人对猴子们说：“今后你们除了吃馒头，还可以再吃一些橡子。我早上给你们三颗，晚上给四颗。”
猴子们似乎只弄懂了主人前面说的一个“三”，觉得自己吃了亏，一个个立起身子跳来跳去，对着老人大喊大叫地发脾气。
老人见猴子们不接受，就换了一种方式，安慰它们说道：“要不这样吧，既然你们觉得少，那就改成每天早上四颗，晚上三颗，这样总够了吧？”
猴子把主人前面说的一个“四”当成全天多得了的橡子，所以马上安静下来，显得格外开心。老人看着这情景，哈哈地笑了。
哲学家用这个故事告诉人们，不要太关心生死、得失，因为到最后我们会发现没有失去什么，也没有得到什么。不过，发展到今天，“朝三暮四”这个成语的意义已经完全改变了。你知道它现在是什么意思吗？
