* 听力

** 1

*** 1

**** transcript

教师上课精神焕发、情绪饱满，学生也会注意力集中。在这种状态下进行体育教学，学生就会思想敏捷、动作反应快；反之，则动作迟缓、接受能力差。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

书有精装，有平装。我喜欢平装的那种，一是经济实惠，二是便于阅读。硬皮的精装版不适于携带，阅读时需要正襟危坐，本来看书是一种赏心悦目的享受，这样严阵以待弄得就有些累了。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

仿生学是生物学的一个分支，研究生物体系统的结构、功能等，用来改进工程技术系统。如模拟人脑的结构和功能原理，改善计算机的性能。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

别看小青长得不起眼，她的工作可是一级棒。想当初她应聘，没有一个部门要她。看她笔试成绩第一，我决定姑且一试。结果不到一星期，她就把部门所有的烂账搞得一清二楚，现在大家都想来抢她。嘿嘿，这可是门儿都没有的事。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

对于我这个小球迷，姥姥可是操心不少，她总是担心我看足球比赛影响学习。我向她保证，只会学习球员勇争第一的精神，一定不会影响学习。可是，独自看球多没劲呀，一个人喝彩、一个人焦急！我真想看球的时候有个伴儿。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：您新书上市以后，引起了不少读者的共鸣，您是怎么决定写这本书的？
男：我爱人给我讲了一个真实的故事。一个弱女子为了爱远嫁他乡，但换来的既有短暂的幸福又有暴力相加的婚姻生活。她想过逃，可一想到还有甜蜜的爱，又不想逃了，就这样，她已年近 40。我想知道现在人的爱情观，他们的爱与被爱，他们的幸福与不幸福。我开始有了写书的念头，我希望写一本书，能给爱或即将爱的人一些思考抑或参考。
女：素材来自哪里呢？
男：既然要真实，那就采访吧。我采访了各行各业的数十个男男女女，听他们讲述各自的情感故事。
女：难怪这本书是由一系列并无关联的小故事构成的。
男：是。我打心眼里相信，有的人的人生是故事，也有可能是事故，而在人生的爱情部分，有太多的存在方式。譬如自爱、他爱、离爱、被爱、弃爱。我的愿望是写出真实、可感、可悟的作品，客观地呈现当代人的情感状态。
女：为了搜集这些情感故事，您一定付出了很多。
男：是啊，一边采访一边写。我每天观察身边的人，不想漏掉任何一个好故事，再筛选其中最有价值的。我每天带着纸和笔，我拒绝用录音、录像那些高科技手段做记录，因为原始的方法给我一种“融入”或“参与”其中的感觉，我怕其中掺杂了太多想像的成分。
女：能给我们讲一个您印象最深的故事吗？
男：书里面有一个电脑先生的故事。电脑先生一直单身。一次他去一个客户家维修电脑，他娴熟的技术和温文尔雅的态度给客户小姐留下了深刻的印象。从此，客户小姐电脑一出问题立刻就找他，再后来，家里所有的东西出了问题都会请他来。结局你当然猜得到，文雅、漂亮、收入好的客户小姐相中了电脑先生。这个故事呈现出爱情的千万种可能，所以我把它写进了书里。
