* 听力

**  第二部分
:PROPERTIES:
:ID: 25a0dbac-64eb-4a3f-b8e7-33c658a83969
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：您新书上市以后，引起了不少读者的共鸣，您是怎么决定写这本书的？
男：我爱人给我讲了一个真实的故事。一个弱女子为了爱远嫁他乡，但换来的既有短暂的幸福又有暴力相加的婚姻生活。她想过逃，可一想到还有甜蜜的爱，又不想逃了，就这样，她已年近 40。我想知道现在人的爱情观，他们的爱与被爱，他们的幸福与不幸福。我开始有了写书的念头，我希望写一本书，能给爱或即将爱的人一些思考抑或参考。
女：素材来自哪里呢？
男：既然要真实，那就采访吧。我采访了各行各业的数十个男男女女，听他们讲述各自的情感故事。
女：难怪这本书是由一系列并无关联的小故事构成的。
男：是。我打心眼里相信，有的人的人生是故事，也有可能是事故，而在人生的爱情部分，有太多的存在方式。譬如自爱、他爱、离爱、被爱、弃爱。我的愿望是写出真实、可感、可悟的作品，客观地呈现当代人的情感状态。
女：为了搜集这些情感故事，您一定付出了很多。
男：是啊，一边采访一边写。我每天观察身边的人，不想漏掉任何一个好故事，再筛选其中最有价值的。我每天带着纸和笔，我拒绝用录音、录像那些高科技手段做记录，因为原始的方法给我一种“融入”或“参与”其中的感觉，我怕其中掺杂了太多想像的成分。
女：能给我们讲一个您印象最深的故事吗？
男：书里面有一个电脑先生的故事。电脑先生一直单身。一次他去一个客户家维修电脑，他娴熟的技术和温文尔雅的态度给客户小姐留下了深刻的印象。从此，客户小姐电脑一出问题立刻就找他，再后来，家里所有的东西出了问题都会请他来。结局你当然猜得到，文雅、漂亮、收入好的客户小姐相中了电脑先生。这个故事呈现出爱情的千万种可能，所以我把它写进了书里。

**** 音频

82f478a9-0f33-411f-9ab9-43422540749e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: dc0a7f9b-f119-4dec-93dc-6a73bfd7b23f
:END:

***** 问题

关于男的的爱人讲的故事，下列哪项正确？

****** 音频

54b2d396-d930-4a64-81af-bb122370a1c2.mp3

***** 选择

****** A

女的身体一直不好

****** B

女的婚后有时挨打

****** C

女的婚后非常幸福

****** D

女的四十岁去世了

***** 答案

B

**** 7
:PROPERTIES:
:ID: a6cb4f08-98c1-4e01-952f-b15b5fb1705a
:END:

***** 问题

男的写这本书的目的是什么？

****** 音频

3b8b987c-7d49-48f3-8771-a78ae4de6889.mp3

***** 选择

****** A

给人们提供一些思考

****** B

避免人生事故的出现

****** C

告诉人们要相信爱情

****** D

写出一本最畅销的书

***** 答案

A

**** 8
:PROPERTIES:
:ID: 04bc85f2-39fa-4652-b89c-730b1d921630
:END:

***** 问题

关于素材，下列哪项正确？

****** 音频

92cce102-352e-4ee2-b652-62fe67112e72.mp3

***** 选择

****** A

故事必须是自己的

****** B

当事人要写下故事

****** C

故事必须有录音录像

****** D

作者追求融人的感觉

***** 答案

D

**** 9
:PROPERTIES:
:ID: 3c37e899-41a3-4f88-a54c-25ca52c571a1
:END:

***** 问题

关于电脑先生的故事，下列哪项正确？

****** 音频

4a13f8d8-372a-40e9-8361-eb1b5c222790.mp3

***** 选择

****** A

电脑先生非常会讨好女士

****** B

电脑先生修电脑的技术差

****** C

客户小姐看上了电脑先生

****** D

客户小姐独立生活能力差

***** 答案

C

**** 10
:PROPERTIES:
:ID: 05f2ba23-6031-440d-83d6-c17e68bc57f0
:END:

***** 问题

关于小说创作，男的看重什么？

****** 音频

e4214290-db9e-4785-bd00-a5ccc91dd91d.mp3

***** 选择

****** A

书的真实性

****** B

书的发行量

****** C

书的知名度

****** D

书的影响力

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

身体不好就不适合教书

***** B

老师的情绪会影响学生

***** C

好老师未必能教出好学生

***** D

老师上课都会集中注意力

**** 段话

教师上课精神焕发、情绪饱满，学生也会注意力集中。在这种状态下进行体育教学，学生就会思想敏捷、动作反应快；反之，则动作迟缓、接受能力差。

***** 音频

291bff1d-81b1-42e2-9cc0-85da1a1565c6.mp3

**** 答案

B

*** 2

**** 选择

***** A

精装书便于阅读

***** B

平装书价格便宜

***** C

收藏精装书是享受

***** D

说话人喜欢欣赏书

**** 段话

书有精装，有平装。我喜欢平装的那种，一是经济实惠，二是便于阅读。硬皮的精装版不适于携带，阅读时需要正襟危坐，本来看书是一种赏心悦目的享受，这样严阵以待弄得就有些累了。

***** 音频

05eafdd8-c1df-4102-a62e-8a26c633e472.mp3

**** 答案

B

*** 3

**** 选择

***** A

仿生学等同于生物学

***** B

仿生学可仿制人脑的结构

***** C

计算机中就有仿生学的研究成果

***** D

生物体系统的结构、功能有待改进

**** 段话

仿生学是生物学的一个分支，研究生物体系统的结构、功能等，用来改进工程技术系统。如模拟人脑的结构和功能原理，改善计算机的性能。

***** 音频

d5875aac-fff8-49fb-8e7f-153e461c3d19.mp3

**** 答案

C

*** 4

**** 选择

***** A

小青样孔很漂亮

***** B

小青面试不合格

***** C

小青数学成绩好

***** D

谁都要不走小青

**** 段话

别看小青长得不起眼，她的工作可是一级棒。想当初她应聘，没有一个部门要她。看她笔试成绩第一，我决定姑且一试。结果不到一星期，她就把部门所有的烂账搞得一清二楚，现在大家都想来抢她。嘿嘿，这可是门儿都没有的事。

***** 音频

06f8dc8b-9932-493f-91bf-00673e98b529.mp3

**** 答案

D

*** 5

**** 选择

***** A

姥姥不爱看足球比赛。

***** B

姥姥喜欢球员的勇敢

***** C

一个人看球很没意思

***** D

“我“有个朋友也爱看球

**** 段话

对于我这个小球迷，姥姥可是操心不少，她总是担心我看足球比赛影响学习。我向她保证，只会学习球员勇争第一的精神，一定不会影响学习。可是，独自看球多没劲呀，一个人喝彩、一个人焦急！我真想看球的时候有个伴儿。

***** 音频

ad6512b7-78e4-48ee-8e26-cd3081f0a234.mp3

**** 答案

C

