* 听力

** 1

*** 1

**** transcript

水是地球上最丰富的物质，它覆盖了70％以上的地球表面。不仅江河、大海里有水，空气、云层里有水，我们吃的蔬菜、水果里有水，连人体内也含有大量的水。水对我们真是太重要了。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

我们每个人都有属于自己的名字，电话也有名字，这就是电话号码。电话号码是由电话局统一编制的号码。固定电话号码一般为7～9位数 ，手机号码通常是11位数。一个城市的电话号码一般是不会重复的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

光照亮了我们的世界，让我们可以看清万物。然而，我们平时看见的只是光的一部分——可见光，它还有很大部分是我们肉眼看不见的，如微波、红外线、紫外线等。

***** QUESTION Are "--" the correct character or there are full-width characters?
:PROPERTIES:
:CREATED: [2022-08-22 14:26:36 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-22 Mon 14:26]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

侦探指负责调查案件的职业，也指负责调查的调查员。侦探一般是通过秘密调查来获取信息的。要成为一个好侦探，高度的注意力和敏锐的观察力是必不可少的。同时要有丰富的知识和良好的记忆力，这样才能在复杂的情况下，排除干扰，找到答案。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

假如你家里只有一台电视机，爸爸想看足球，而你想看动画片，怎么办呢？双画面电视机就可以解决这个问题。这种电视机有一大一小两个画面，可以同时收看两个节目。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：观众朋友们，大家好，今天我们来谈一谈与我们生活息息相关的电话。我们请到了电信专家王老师，让他跟我们说说电话。
男：大家好，很高兴能与大家分享关于电话的故事和知识。
女：王老师，我们都知道，只要在电话键盘上拨下一组数字，就可以和世界各地的人互相通话了。电话是人类一个了不起的发明，它将人与人之间的距离拉得很近很近。可是，王老师，您能给我们介绍一下电话是怎样工作的吗？
男：电话是通过电话网来工作的。这个网由电话机、电话线和交换机组成。当我们对着话筒说话时，电话机会将声音转换为电子信号，并传达到电话局的交换机上。交换机再将这些信号输送到和我们通话的电话机上，由那部电话机把电子信号还原成声音。
女：那拨打电话为什么有时会占线呢？
男：因为每个有线电话机都需要一对电话线传送声音。可是，电话线可以通过的信号是有限的，当通过电话线的信号太多时，就会产生电话占线现象。
女：当今科技发展很快，已经出现了可视电话，这又是什么原理呢？
男：可视电话非常神奇，使用它时不但可以听到对方的声音，还能够看到对方的模样。可视电话也是用电话线进行信息传递的，只不过它将声音信号与图像信号合并在一起传输出去，并通过电话两端的摄像管扫描、还原，这样，我们就能看到对方了。

*** 音频

f9cd19f1-fccd-4d31-95c4-55f34d7f156d.mp3

*** 题目

**** 6

***** 问题

关于电话，下列哪项正确？

***** 音频

240984d0-8270-4498-8f5b-ead6b63e90cc.mp3

**** 7

***** 问题

电话是通过什么来工作的？

***** 音频

d3eba2a8-56a6-4abe-b038-e2226cf356c3.mp3

**** 8

***** 问题

电话机会把声音转换成什么？

***** 音频

ef0eb459-03d6-486e-bd10-01490f6a04be.mp3

**** 9

***** 问题

拨打电话为什么会占线？

***** 音频

6253f1e0-d6f1-4a9f-95dc-ba3f74ef6789.mp3

**** 10

***** 问题

为什么说可视电话非常神奇？

***** 音频

69909ae9-8d8a-4e4a-909d-0213fe096217.mp3

