* 听力

** 第二部分
:PROPERTIES:
:ID: 93ef5660-fb16-4beb-b22b-a74f2d30ae43
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：观众朋友们，大家好，今天我们来谈一谈与我们生活息息相关的电话。我们请到了电信专家王老师，让他跟我们说说电话。
男：大家好，很高兴能与大家分享关于电话的故事和知识。
女：王老师，我们都知道，只要在电话键盘上拨下一组数字，就可以和世界各地的人互相通话了。电话是人类一个了不起的发明，它将人与人之间的距离拉得很近很近。可是，王老师，您能给我们介绍一下电话是怎样工作的吗？
男：电话是通过电话网来工作的。这个网由电话机、电话线和交换机组成。当我们对着话筒说话时，电话机会将声音转换为电子信号，并传达到电话局的交换机上。交换机再将这些信号输送到和我们通话的电话机上，由那部电话机把电子信号还原成声音。
女：那拨打电话为什么有时会占线呢？
男：因为每个有线电话机都需要一对电话线传送声音。可是，电话线可以通过的信号是有限的，当通过电话线的信号太多时，就会产生电话占线现象。
女：当今科技发展很快，已经出现了可视电话，这又是什么原理呢？
男：可视电话非常神奇，使用它时不但可以听到对方的声音，还能够看到对方的模样。可视电话也是用电话线进行信息传递的，只不过它将声音信号与图像信号合并在一起传输出去，并通过电话两端的摄像管扫描、还原，这样，我们就能看到对方了。

**** 音频

f9cd19f1-fccd-4d31-95c4-55f34d7f156d.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 22f8e024-31ae-4160-94a7-ac5cf2b876db
:END:

***** 问题

关于电话，下列哪项正确？

****** 音频

240984d0-8270-4498-8f5b-ead6b63e90cc.mp3

***** 选择

****** A

可以拉近人与人的距离

****** B

是历史上最伟大的发明

****** C

与人们的健康息息相关

****** D

能让世界各地的人见面

***** 答案

A

**** 7
:PROPERTIES:
:ID: 7f04a046-cf24-43a8-801a-6b8d9b6172b0
:END:

***** 问题

电话是通过什么来工作的？

****** 音频

d3eba2a8-56a6-4abe-b038-e2226cf356c3.mp3

***** 选择

****** A

电话线

****** B

电话机

****** C

电话网

****** D

交换机

***** 答案

C

**** 8
:PROPERTIES:
:ID: d69637ce-d545-4d01-8e34-24e4f525770a
:END:

***** 问题

电话机会把声音转换成什么？

****** 音频

ef0eb459-03d6-486e-bd10-01490f6a04be.mp3

***** 选择

****** A

电子信号

****** B

声音信号

****** C

图像信号

****** D

交换信号

***** 答案

A

**** 9
:PROPERTIES:
:ID: bebc69e5-2586-4ff8-88f9-05ab7a8ffcb0
:END:

***** 问题

拨打电话为什么会占线？

****** 音频

6253f1e0-d6f1-4a9f-95dc-ba3f74ef6789.mp3

***** 选择

****** A

电话线的长度不够

****** B

电话线的宽度不够

****** C

通过电话线的信号太多了

****** D

电话机或电话线出现故障

***** 答案

C

**** 10
:PROPERTIES:
:ID: 0da76d95-acad-41f3-8018-4fad0b229027
:END:

***** 问题

为什么说可视电话非常神奇？

****** 音频

69909ae9-8d8a-4e4a-909d-0213fe096217.mp3

***** 选择

****** A

利用电话线进行信息传递

****** B

先传递声音，再传递图像

****** C

利用交换机扫描、还原图像

****** D

不但可以听到，还能看到对方

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

地球内70％都是水

***** B

大部分水在空气、云层里

***** C

水果是含水最多的物质

***** D

水对我们非常重要

**** 段话

水是地球上最丰富的物质，它覆盖了 70%以上的地球表面。不仅江河、大海里有水，空气、云层里有水，我们吃的蔬菜、水果里有水，连人体内也含有大量的水。水对我们真是太重要了。

***** 音频

cd1c1266-3a2c-4cb9-8c9c-77749954fcba.mp3

**** 答案

D

*** 2

**** 选择

***** A

电话号码就好像是电话的名字

***** B

电话号码是由用户自己编制的

***** C

固定电话导码一般为7一11位数

***** D

一个城市的电话号码往往会重复

**** 段话

我们每个人都有属于自己的名字，电话也有名字，这就是电话号码。电话号码是由电话局统一编制的号码。固定电话号码一般为 7～9 位数，手机号码通常是 11 位数。一个城市的电话号码一般是不会重复的。

***** 音频

52c4bd3c-0525-453a-b1ce-cfb9e9f2a690.mp3

**** 答案

A

*** 3

**** 选择

***** A

我们能看见大部分光

***** B

我们平时看见的是可见光

***** C

微波是肉眼能看见的

***** D

红外线、紫外线不属于光

**** 段话

光照亮了我们的世界，让我们可以看清万物。然而，我们平时看见的只是光的一部分——可见光，它还有很大部分是我们肉眼看不见的，如微波、红外线、紫外线等。

***** 音频

c4ba2880-73d3-4875-b6aa-04941ed0e87b.mp3

**** 答案

B

*** 4

**** 选择

***** A

侦探通过公开调查来获取信息

***** B

侦探是负责审判案件的职业

***** C

侦探需要有丰富的知识

***** D

侦探要有良好的体力

**** 段话

侦探指负责调查案件的职业，也指负责调查的调查员。侦探一般是通过秘密调查来获取信息的。要成为一个好侦探，高度的注意力和敏锐的观察力是必不可少的。同时要有丰富的知识和良好的记忆力，这样才能在复杂的情况下，排除干扰，找到答案。

***** 音频

94805239-e5bb-4566-9963-f6cb3ddbdd08.mp3

**** 答案

C

*** 5

**** 选择

***** A

双画面电视机需要两台电视机

***** B

双画面电视机可以收看动画片

***** C

双画面电视机有两个相同大小的画面

***** D

双画面电视机可以同时收看两个节目

**** 段话

假如你家里只有一台电视机，爸爸想看足球，而你想看动画片，怎么办呢？双画面电视机就可以解决这个问题。这种电视机有一大一小两个画面，可以同时收看两个节目。

***** 音频

0de1f605-cff6-4228-a1d5-81bfd0c19b97.mp3

**** 答案

D

** 第三部分

*** 11-13

**** 课文

对于喜欢四处游玩的旅行者来说，自拍杆是个好东西，它可以让“手臂”变长，获得更好的拍摄角度。不过自拍杆有个弊病，不知道你发现没有。那就是如果自拍期间突然想拍点儿别的景色，比如正划过天空的流星，那又该怎么办呢？把自拍杆缩短，然后把相机或手机取下来，放好自拍杆，再用相机或手机来拍摄，等你弄好这些，估计流星雨早就过去了。

怎么办呢？试试这款可以改变拍摄方向的自拍杆吧，让你 360 度无死角。和普通自拍杆一样，机身上有一个按键。不过这不是拍照按键，而是控制电动云台的。每按一下，云台就会旋转 180 度，自拍还是拍他人一眨眼就能搞定。再也不用担心错过转瞬即逝的流星了。

**** 题目

***** 11

****** 选择

******* A

增加了人们的身高

******* B

帮助人们四处游玩

******* C

让人们360度无死角

******* D

让人获得更好的拍探角度

***** 12

****** 选择

******* A

不能缝短

******* B

不方便携带

******* C

不能改变拍摄的方向

******* D

不容易把相机取下来

***** 13

****** 选择

******* A

方便大家进行自拍

******* B

机身上有拍照按键

******* C

一眩眼就能结束拍摄

******* D

能快速改变拍摄角度

*** 14-17

**** 课文

机器人是人类发明的最复杂的自动化机器之一，它能够帮助人们做很多事情。机器人干起活来又快又准，而且它不怕脏不怕累，因此应用很广泛。

一说到机器人，你可能会想到电视中那种跟人一样有鼻子、眼睛的机器。其实，现代机器人大多还没有达到这种逼真的程度，它们不仅没有鼻子、眼睛，甚至也没有胳膊和腿。它们有的像机器，有的像怪物，有的脑袋又尖又长，有的三头六臂。真是千奇百怪。

机器人刚造出来的时候，只有一只手臂，称为“机器手”。机器手是个相当复杂的装置。大多数机器人的手臂都像人的手臂一样，能够进行弯曲和翻转，还能够夹住东西。

现在已经有可以用来处置炸弹的机器人。这种机器人体内安置了一个摄相机，当机器人用专门的开启装置打开包裹时，工作人员可以通过摄相机进行观察，然后通过遥控来指挥拆除炸弹。这种机器人可以帮助人类有效打击恐怖袭击，保卫我们安宁的生活。

**** 题目

***** 14

****** 选择

******* A

干活又快又准

******* B

不怕脏不怕累

******* C

应用非常广泛

******* D

结构最为复杂

***** 15

****** 选择

******* A

有鼻孔、眼普

******* B

有胳膊有腹

******* C

十奇百怪

******* D

跟人一样

***** 16

****** 选择

******* A

能够拍照、摄像

******* B

能够鸣曲、翻转

******* C

能够读书、写字

******* D

能够踩球、游泳

***** 17

****** 选择

******* A

通过电子眼处置炸弹

******* B

用三头六臂打开包裹

******* C

通过摄像机观察后遥控拆弹

******* D

用手臂弯曲翻转,夹住炸弹

