* 听力

** 1

*** 1

**** transcript

水是地球上最丰富的物质，它覆盖了70％以上的地球表面。不仅江河、大海里有水，空气、云层里有水，我们吃的蔬菜、水果里有水，连人体内也含有大量的水。水对我们真是太重要了。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

我们每个人都有属于自己的名字，电话也有名字，这就是电话号码。电话号码是由电话局统一编制的号码。固定电话号码一般为7～9位数 ，手机号码通常是11位数。一个城市的电话号码一般是不会重复的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

光照亮了我们的世界，让我们可以看清万物。然而，我们平时看见的只是光的一部分——可见光，它还有很大部分是我们肉眼看不见的，如微波、红外线、紫外线等。

***** QUESTION Are "--" the correct character or there are full-width characters?
:PROPERTIES:
:CREATED: [2022-08-22 14:26:36 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-22 Mon 14:26]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

侦探指负责调查案件的职业，也指负责调查的调查员。侦探一般是通过秘密调查来获取信息的。要成为一个好侦探，高度的注意力和敏锐的观察力是必不可少的。同时要有丰富的知识和良好的记忆力，这样才能在复杂的情况下，排除干扰，找到答案。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

假如你家里只有一台电视机，爸爸想看足球，而你想看动画片，怎么办呢？双画面电视机就可以解决这个问题。这种电视机有一大一小两个画面，可以同时收看两个节目。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



