* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 6f2c66fa-5a61-4754-a728-3ff2a3d73d95
:END:
**** 对话
***** 转录
男：您好！我在网上查询话费，它要我输入密码，可我没设置过密码呀！[[file:a7ed4910-7ce7-4a2b-989a-88bac3b9a97b.mp3][(audio)]]
女：您可以输入手机号码，选择获取随机密码就可以登录了。[[file:f5e2d8fe-37ba-461e-875d-2db44fe46801.mp3][(audio)]]
***** 音频
cead303c-2ab7-402f-b972-ac57a1234841.mp3
**** 问题
***** 转录
男的想要做什么？
***** 音频
2fe4aab0-111f-44e4-997d-43d980fd1e35.mp3
**** 选择
***** A
修改套餐
***** B
设置密码
***** C
查询话费
***** D
下载文件
**** 答案
C
*** 2
:PROPERTIES:
:ID: 872ea00b-8ea0-49df-952a-0e55907c2938
:END:
**** 对话
***** 转录
男：你最近怎么不跟李阳打羽毛球了？[[file:1ffa3a72-2c58-4135-861f-b13ea16755b5.mp3][(audio)]]
女：他参加了学校的演讲比赛，已经进了复赛，这段时间都在忙着准备呢。[[file:3cfe1b3c-1285-45b3-bf6b-3fcb9cd78639.mp3][(audio)]]
***** 音频
8eb11329-cc90-480e-89f7-d4d7763dff93.mp3
**** 问题
***** 转录
李阳最近在忙什么？
***** 音频
1784bbea-df2e-4c40-b504-20dad5567c8b.mp3
**** 选择
***** A
参加期末考试
***** B
准备演讲比赛
***** C
查找论文资料
***** D
组织球赛活动
**** 答案
B
*** 3
:PROPERTIES:
:ID: 7bd3c311-f4ac-47f6-9093-7e386f666051
:END:
**** 对话
***** 转录
男：这次修改后的论文您觉得怎么样？[[file:e962b869-2e53-4bf0-b7a3-80e536a9828d.mp3][(audio)]]
女：结论部分我认为有必要再完善一下，别留遗憾，你抓紧点儿时间吧。[[file:a9b68086-9069-4c1e-ab30-6ca2523ff781.mp3][(audio)]]
***** 音频
f3141d56-4509-4f0c-899a-aae4a9f4e5e4.mp3
**** 问题
***** 转录
女的觉得这篇论文怎么样？
***** 音频
c614f30d-0af1-4b42-a26d-fe34a7784842.mp3
**** 选择
***** A
需要再完善
***** B
应尽快发表
***** C
质量符合要求
***** D
内容令她遗憾
**** 答案
A
*** 4
:PROPERTIES:
:ID: 232e383e-24de-4ea0-86e6-b1a175c08242
:END:
**** 对话
***** 转录
男：这么晚了，你怎么还在加班？[[file:8d4d27b2-0496-415a-82de-3caede0945b5.mp3][(audio)]]
女：马主任说名单又有调整，确定后就给我发邮件，我再等会儿。[[file:567f9738-1c20-41ca-af70-4970f091f4c6.mp3][(audio)]]
***** 音频
8c21b96a-19af-448b-9404-9fd0ad5133c2.mp3
**** 问题
***** 转录
女的现在在做什么？
***** 音频
d8a99414-50c8-4a84-a685-4be45f23f0ef.mp3
**** 选择
***** A
写邮件
***** B
调整名单
***** C
在单位加班
***** D
和主任谈事
**** 答案
C
*** 5
:PROPERTIES:
:ID: d9f66a54-530b-442a-9a94-a1eab5a477b8
:END:
**** 对话
***** 转录
女：我爸爸抽了二十多年的烟，现在说戒就戒了。[[file:6772b722-8ea5-4c80-a17c-cdb033a73ecc.mp3][(audio)]]
男：真让人佩服。要想戒烟关键就看有没有决心。[[file:f42292a2-79a5-4593-aa72-42eddb91d872.mp3][(audio)]]
***** 音频
1c0a59dd-0d5c-464b-8b81-16642b10aa8e.mp3
**** 问题
***** 转录
男的认为戒烟怎么样？
***** 音频
f8decd50-1c28-4ef4-b9d4-6ed059c9be48.mp3
**** 选择
***** A
很难成功
***** B
要有决心
***** C
贵在坚持
***** D
要讲究方法
**** 答案
B
*** 6
:PROPERTIES:
:ID: 049e3cb4-d2de-4ab7-9a1d-d387e87d76a8
:END:
**** 对话
***** 转录
女：这几天的日程怎么安排得这么满？你要注意身体。[[file:5b330bac-d516-458a-b04c-e4227e52cb07.mp3][(audio)]]
男：放心吧，等我把这个合同谈下来，咱们就去海边玩儿几天。[[file:5f77c89f-dfef-4bf1-8464-16182e568cd7.mp3][(audio)]]
***** 音频
f9b5bdfd-316e-4209-a1e9-95b390f55e3f.mp3
**** 问题
***** 转录
男的最近怎么样？
***** 音频
16b55a74-6fb9-4633-8253-5f9caf4ad9bf.mp3
**** 选择
***** A
工作很顺利
***** B
身体不太好
***** C
日程很紧张
***** D
玩儿得很开心
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
男：你怎么一大早就打哈欠，昨晚没睡好？
女：我最好的朋友回国来看我，就住在我家了。
男：多年没见了，这下可有的聊了。
女：可不是，我们俩硬是聊了一夜都没睡。
***** 音频
022ec2eb-ed93-4b11-9307-2be046de47dd.mp3
**** 问题
***** 转录
关于女的，从对话中可以知道什么？
***** 音频
53e892c5-6a82-4970-94f7-b93955bce3c8.mp3
**** 选择
***** A
昨晚失眠了
***** B
正准备应试
***** C
和朋友聊了一夜
***** D
和男朋友分手了
**** 答案
C
*** 8
**** 对话
***** 转录
男：你这么快就把论文写好了？真是佩服啊！
女：我这还不是最快的，刘京都准备答辩了。
男：我的调查问卷还没收齐呢，看着你们，真让人着急。
女：大可不必，早晚没关系，通过最重要。
***** 音频
14777610-7916-4dc8-9942-355dd0e15090.mp3
**** 问题
***** 转录
关于男的的论文，从对话中可以知道什么？
***** 音频
9d660066-262a-446f-8f6f-6a65068662e9.mp3
**** 选择
***** A
在收集资料
***** B
已经写好了
***** C
正准备答辩
***** D
已顺利通过
**** 答案
A
*** 9
**** 对话
***** 转录
女：这段时间怎么一直没见到你？去实习啦？
男：最近跑了好几家单位，递了很多简历。
女：面试通过了吗？有单位录取吗？
男：有是有，不过，我还没有想好要不要去。
***** 音频
366f34c2-8b36-473b-bcda-6475d3b5a22c.mp3
**** 问题
***** 转录
关于男的，从对话中可以知道什么？
***** 音频
40f8be97-c764-4da6-9585-e958a617f87d.mp3
**** 选择
***** A
正准备简历
***** B
在单位实习
***** C
已接到录用
***** D
已报到上班
**** 答案
C
*** 10
**** 对话
***** 转录
男：出访的日程表我看过了，安排得很满，有些地方不够合理。
女：是的，我正和有关部门商量，一些细节要再完善。
男：好的，一有消息及时通知我。
女：您放心，估计周末就能给您。
***** 音频
b5608681-7131-4f64-9e84-3181276a1026.mp3
**** 问题
***** 转录
关于出访的日程，男的觉得怎么样？
***** 音频
b5526a62-3449-4ad9-9ce1-eba580afbac2.mp3
**** 选择
***** A
需要开会讨论
***** B
内容不够详细
***** C
设计非常合理
***** D
还要调整完善
**** 答案
D
*** 11-12
**** 对话
***** 转录
有个笑话是这样的。两个工人安装灯泡，一个踩在另一个人的肩膀上。过了老半天，下面的人也不见上面有什么动静，就问上面的人：“喂，装好了吗？”上面的人说：“你不知道这是螺丝口的灯泡吗？你不转，我怎么装得上啊？”10在工作中，你不得不承认，个人的知识和能力总是有限的，依靠和利用朋友的知识、经验和能力共同完成项目是明智的选择。但是，你却不能因此完全放弃了自己的努力。
***** 音频
12bfb54a-b161-4a01-8637-c0c06c2942a3.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于那两个工人，可以知道什么？
******* 音频
7318089d-fad7-497b-ac3f-ea855189e1b0.mp3
****** 选择
******* A
都不会装灯泡
******* B
上面的人很懒
******* C
两个人配合很好
******* D
下面的人很努力
****** 答案
B
***** 12
****** 问题
******* 转录
这段话主要想告诉我们什么？
******* 音频
9b38ed42-fbb4-4047-a42c-ecbba0b5f285.mp3
****** 选择
******* A
朋友的帮助是无私的
******* B
要善于利用有利条件
******* C
个人的知识是有限的
******* D
合作需要双方共同努力
****** 答案
D
*** 13-14
**** 段话
***** 转录
从前有个人非常自私，对别人的事从不关心，还常说：“别人的事，天大的也不要管。”因此别人送了他一个外号叫“天不管”。一天，“天不管”买了一袋大米背回家。路上，袋子破了，米不断漏出来。同伴看见了，问他：“别人的事要不要管？”他不加思考地说：“天大的事也不管。”一会儿，米漏掉了不少。同伴又问：“对人家有好处的事难道也不管吗？”他还说：“只要对自己没有好处，一百个也不管！”快到家时，“天不管”觉得肩上轻多了，这才发现一袋米已漏掉了半袋。他又气又急，责备他的同伴说：“你为什么不早点儿跟我说？”同伴学着他的腔调说：“不管，不管，一百个不管！”
***** 音频
fbdb2c7a-2ab2-4406-b25f-82ddf2595498.mp3
**** 题目
***** 13
****** 问题
******* 转录
根据这段话，别人为什么叫那个人“天不管”？
******* 音频
65f1343f-2b45-40b9-a42a-3beac936309c.mp3
****** 选择
******* A
他做人很自私
******* B
他天天闲待着
******* C
他总爱管闲事
******* D
他喜欢抱怨人
****** 答案
A
***** 14
****** 问题
******* 转录
关于“天不管”，下列哪项正确？
******* 音频
358d698f-afa5-4deb-a2c0-3f538d9382e1.mp3
****** 选择
******* A
没发现米漏了
******* B
育着大米回家
******* C
买的大米很轻
******* D
送给同伴一袋米
****** 答案
B
* 阅读
** 第一部分
*** 段话
不可否认，传统纸质出版有着不可避免的局限。随着技术的发展和电子书自身的[[gap][15]]，从长远来看，很难说人们两十多年的阅读习惯不会改变。正如许多作家从最初不愿放弃稿纸到现在习惯了在电脑上[[gap][16]]“文字一样，阅读的习惯在数字化浪潮下也在默默改变。多年以后，纸质书或许将会作为一种有限范围内的阅读方式，被小众化地予以保留。就像现在我们中的一小部分人，仍然对经典的线装书十分着迷一样。我个人认为，如果书本真的远离了我们的生活，那将是一件十分[[gap][17]]的事情。
在科技高速发展、人们生活的各方面都受到极大冲击的时代，传统的阅读方式是否会被颠覆？电子书能为我们的文化产业带来什么？对“无纸化阅读”该保持怎样的态度？传统的图书出版业又该何去何从？这都是我们需要深人[[gap][18]]的问题。
*** 题目
**** 15
***** 选择
****** A
先进
****** B
完善
****** C
深入
****** D
开放
***** 答案
B
**** 16
***** 选择
****** A
搜索
****** B
下载
****** C
输入
****** D
识别
***** 答案
C
**** 17
***** 选择
****** A
遗憾
****** B
后悔
****** C
佩服
****** D
偶然
***** 答案
A
**** 18
***** 选择
****** A
称赞
****** B
追求
****** C
克服
****** D
思考
***** 答案
D
** 第二部分
*** 19
:PROPERTIES:
:ID: 1b6cd772-257d-4f2a-a765-ab3a94b2150f
:END:
**** 段话
两个搬运工人在门道里搬运一个大木箱。他们又推又拉，用尽了力气，却始终无法将箱子搬动。最后那个在门外的人说：“算了吧，这么大的箱子，我们怎么也搬不进去。谁说要把它搬进来？”里面的那个人说，“我还以为是要把它搬出去呢。”
**** 选择
***** A
做事情苦干不如巧干
***** B
想成功就要付出努力
***** C
目的一致是合作的基础
***** D
做任何事都要讲究方法
**** 答案
C
*** 20
:PROPERTIES:
:ID: dbe2779c-3373-4501-8f21-3d3e81a82c55
:END:
**** 段话
绘画是一种语言，是一种不规范的表达手段，它反映一个人的心态，儿童也如此。儿童绘画的寓意很丰富，它是儿童同外部世界联系、向他人诉说和表明他的存在的一种方式。不管画中有无色彩，不管画的是圆还是方，不管画得夸张还是细腻，儿童的每一幅画都有其内在的含义。
**** 选择
***** A
儿童绘画通常比较夸张
***** B
儿童绘画能反映其心态
***** C
孤独的儿童常常画画儿
***** D
儿童绘画的含义很难理解
**** 答案
B
*** 21
:PROPERTIES:
:ID: b5137489-f766-4fbf-859a-e301a0a4dcc5
:END:
**** 段话
全球15岁以上的人中，大约有84％具备识字能力。识字率因国家和地区而异。一个人是否具备识字能力受到许多因素的影响，比如财富、性别、受教育机会和所在的地区等。全球目前还有7亿7400万不具备读写能力的人，其中三分之二为女性。这主要是因为在一些欠发达国家，女性往往缺少接受教育的机会。
**** 选择
***** A
全球84％的学龄儿童都识字
***** B
不发达国家女性识字率较低
***** C
各国的识字率是基本相近的
***** D
经济因素对识字率没有影响
**** 答案
B
*** 22
:PROPERTIES:
:ID: 098332a3-016b-49e0-846a-ebecb2b6653a
:END:
**** 段话
目前地球上共有70多亿人，190多个独立的国家，但人类所说的语言却超过5000种。有些国家只有一种官方语言，比如日本，而有些则不然。在印度，现在除了全国性的法定官方语言英语和印地语外，还有20种地方性的联邦官方语言。专家们认为，人类的语言种类最多时曾达到10000种，目前数量已经减少了近一半，并且仍在不断减少中。
**** 选择
***** A
各国的官方语言数量不等
***** B
人类的语言种类在逐渐增加
***** C
语言种类最终会超过一万种
***** D
人口越多的国家语言种类越多
**** 答案
A
** 第三部分
*** 23-25
**** 段话
1993年，一个14岁的孩子在上海青年篮球队里打球。当时，球队里的队员都穿着帆布面的篮球鞋。有一次，他在观看一场国外球队的比赛时发现，那些国外的球员竟然都穿着皮制的篮球鞋。这种球鞋不但美观，而且穿着舒适。于是，这个孩子就梦想能穿上一双皮制的篮球鞋。
一天，当他把这个梦想告诉教练后，教练笑着说：“努力吧，孩子。如果你能进入国家青年队，你就能穿这样的鞋”
从这一刻起，这个孩子就把进入国家青年队作为自己奋斗的目标。终于在17岁那年，他凭借自己超凡的球技，被选入国家青年队。穿上了向往已久的皮制篮球鞋，他倍加珍惜。一位队友发现此事后告诉他：“不用在意一双球鞋。如果你能进入国家队，这样的篮球鞋你想有多少就有多少！”这句极具诱惑力的话深深触动了他。于是，他又有了新的奋斗目标——中国国家篮球队。
功夫不负有心人，经过一年的苦练，他真的穿上了国家队的队服。
2001年，亚洲篮球锦标赛上，他为中国国家队夺得冠军做出了突出贡献。2002年6月26日，美国NBA的选秀大会上，休斯敦火箭队选择了他。几年后，他成为中国篮球运动的标志性人物。他叫姚明。
**** 题目
***** 23
****** 问题
姚明为什么想进入国家青年队？
****** 选择
******* A
想成为一名世界冠军
******* B
不想辜负父母的希望
******* C
想得到一双皮制球鞋
******* D
完成教练给他的任务
****** 答案
C
***** 24
****** 问题
关于姚明，下列哪种说法是正确的？
****** 选择
******* A
教练送了他一双球鞋
******* B
对中国篮球贡献很大
******* C
收藏了很多名牌球鞋
******* D
队友的鼓励给他很大力量
****** 答案
B
***** 25
****** 问题
上文说明了什么道理？
****** 选择
******* A
求人不如求已
******* B
有压力才有动力
******* C
目标未必要很远大
******* D
不能这山望着那山高
****** 答案
C
*** 26-28
**** 段话
减肥是令许多人望而却步的难事，是许多胖子的大难题。但有一家减肥健美俱乐部却效果显著，久负盛名。
一天，一位胖男子慕名而来，他已有过多次失败的经历了。他抱着最后一试的态度问教练他该怎么办。教练记下了他的地址，然后告诉他：“回家等候通知。明天会有人告诉你怎么做”
第二天一早，门铃响了，一位漂亮性感的女郎站在门口，对胖子说：“教练吩咐，你要是能追上我，我就做你的女朋友。”
胖子大喜，从此每天早晨都在女郎后边狂追。如此数月下来，胖子已逐渐身手矫健起来，他早就忘了这是减肥，只是想一定要把那位姑娘追到手。
直到有一天，胖子心想：今天我一定能追到她了。他早早起来在门口等着，那位姑娘没来，来的是一位同他以前一样胖的女士。
胖女士对他说：“教练吩咐，我要能追到你，你就做我的男朋友。”
这只是一个笑话，但它却告诉我们，不妨“偷换概念目标”，把一些艰苦的过程变得轻松有趣起来，这样你就能更好地坚持下去。
**** 题目
***** 26
****** 问题
从文中可知，这家减肥健美俱乐部，
****** 选择
******* A
顾客不多
******* B
名气很大
******* C
管理混乱
******* D
欺骗消费者
****** 答案
B
***** 27
****** 问题
文中的胖男子参加了这家减肥俱乐部后：
****** 选择
******* A
晨跑坚持了几个月
******* B
很佩服这里的教练
******* C
给很多朋友做了推荐
******* D
追到了那位漂亮女郎
****** 答案
A
***** 28
****** 问题
当我们追求一个困难的目标时，作者建议要怎样？
****** 选择
******* A
多动动脑筋
******* B
善于发现乐趣
******* C
不达目的不罢休
******* D
学会有舍才有得
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
都需要
***** 2
任何
***** 3
行动之前
***** 4
有完善的计划
***** 5
采取
**** 答案
***** 1
采取任何行动之前都需要有完善的计划。
*** 30
**** 词语
***** 1
值得
***** 2
成就
***** 3
称赞
***** 4
刘校长
***** 5
在教改方面的
**** 答案
***** 1
刘校长在教改方面的成就值得称赞。
*** 31
**** 词语
***** 1
勇气
***** 2
是为了
***** 3
培养学生
***** 4
活动的目的
***** 5
克服困难的
**** 答案
***** 1
活动的目的是为了培养学生克服困难的勇气。
