* 听力

** 第二部分
:PROPERTIES:
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:ID: c5d60bd6-8a01-49fe-aa57-4739d046b523
:END:

*** 对话

女：今天我们很荣幸请到了教育方面的专家李老师和大家一起聊聊“啃老族”的问题。李老师，近来我们常听人说起“啃老族”，“啃老族”指的是些什么样的人呢？
男：指那些不升学、不就业、不进修，终日无所事事，有谋生能力，却还靠父母供养的年轻人。
女：这样一个族群是怎么产生的呢？
男：“啃老族”产生的原因是多方面的。比如，经济不景气，社会对就业的吸纳能力不足，年轻人找不到理想的工作，也有的是年轻人对工作的要求比较高，自身的学历、知识水平却不怎么过硬，又怕吃苦，不愿出去工作养活自己，于是选择了啃老。
女：“啃老族”的出现，是不是也和家庭教育有关系呢？
男：那当然，父母的责任也是不可逃脱的，对孩子溺爱的家庭才会出“啃老族”，在孩子成长过程中，父母没有教会他们做人要有独立精神，没有教会孩子怎样规划人生。当然，社会原因也是有的，如前边提到的经济不够景气，年轻人就业压力大，他们找不到工作，只能选择“啃老”。
女：“啃老族”的出现，对家庭、对社会的影响是很负面的哈。
男：是，“啃老族”会使很多家庭出现矛盾，也会使原本能够生活得很幸福的家庭失去幸福的根基，“啃老族”的问题将成为未来影响家庭生活的“第一杀手”。特别是在中国已进入老年社会的今天，“啃老族”必将带来更多的社会问题。
女：那“啃老族”的问题应该怎么解决呢？
男：年轻人要独立自主，这种精神的树立除了要有正确的人生观、价值观，社会也应该为他们创造适合的工作机会。与其让父母养活“啃老族”，不如给他们工作岗位，让他们成为有能力养活父母的“养老族”。

**** 音频

7d96405a-d8ce-44b3-a1f5-0e20cf9e4b11.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1a818bb8-51aa-4652-bf8d-3a7b1ffe3590
:END:

***** 问题

“啃老族”的特点是什么？

****** 音频

6f8a6655-7a1c-48fb-9ca9-038946194d02.mp3

***** 选择

****** A

整天闲着不干事

****** B

失去了学习机会

****** C

家里经济条件好

****** D

没有能力养活自己

***** 答案

A

**** 7
:PROPERTIES:
:ID: 55e29a28-12fa-4775-a58a-0a25d3086b28
:END:

***** 问题

以下哪一项是“啃老族”产生的原因？

****** 音频

0c830f86-4af8-4a77-8e9f-de107e8a61f4.mp3

***** 选择

****** A

年轻人缺少工作能力

****** B

年轻人学的知识太少

****** C

父母愿意掏钱养活他们

****** D

社会提供的工作机会不足

***** 答案

D

**** 8
:PROPERTIES:
:ID: 4ba50e64-2d71-4ce3-83b1-dcd21f523af9
:END:

***** 问题

“啃老族”的出现和家庭教育哪方面的问题有关？

****** 音频

ea618099-45e9-42b6-a98a-1aefc2b5e4c6.mp3

***** 选择

****** A

父母过分宠爱孩子

****** B

父母做事不负责任

****** C

父母缺少独立精神

****** D

父母不替孩子规划

***** 答案

A

**** 9
:PROPERTIES:
:ID: 8ac0b113-448d-4864-9a69-82c0cddbe00b
:END:

***** 问题

“啃老族”的负面影响是什么？

****** 音频

ef79b862-1dba-45b9-a947-90dbb7cb3c5c.mp3

***** 选择

****** A

经济不景气

****** B

家庭不和谐

****** C

社会不安定

****** D

老人不健康

***** 答案

B

**** 10
:PROPERTIES:
:ID: 19f532d6-f6ab-4648-ba70-c53be4db24ff
:END:

***** 问题

怎样解决“啃老族”的问题？

****** 音频

3970d36b-4552-43b3-bea6-aebce6941377.mp3

***** 选择

****** A

提高年轻人的能力，让他们学习

****** B

让有能力的人给年轻人工作机会

****** C

让年轻人树立正确的人生观、价值观

****** D

父母要给“啃老族“存下足够的钱

***** 答案

C

** 第一部分

*** 1

**** 选择

***** A

爸爸为人很和气

***** B

爹爸也腺欢夜读

***** C

爹爸非常关心我

***** D

睡前应该喝牛奶

**** 段话

夜深了，我还在熬夜，为了准备考试，没有片刻的休息。一阵轻轻的脚步声，爸爸来到了我的身旁，轻声对我说：“渴了吧？”我回头，看到爸爸慈祥的目光，“爸爸，您还没睡？”他点点头。我喝了一口温热的牛奶，顿时，幸福传遍了我的全身。

***** 音频

d127d4b9-1b11-4d7f-a513-0f174ac721e1.mp3

**** 答案

C

*** 2

**** 选择

***** A

王先生是撂家庭教育研究的

***** B

王先生喜欢看家庭教育杂志

***** C

王先生创办了家庭教育专业

***** D

《中国家庭教育》办得不错

**** 段话

王先生是师范大学教育学院的教授，兼任《中国家庭教育》杂志的主编，还是中国教育学会家庭教育专业委员会理事长。作为中国当代家庭教育研究的开拓者，他在家庭教育理论与实践的研究上做出过很多贡献。

***** 音频

87d84b62-5a64-4d83-aa20-eddd5bd48702.mp3

**** 答案

A

*** 3

**** 选择

***** A

中国70％的家长不重视教育

***** B

中国不少家庭教育存在问题

***** C

多数家长教育观念十分先进

***** D

学校教育是家庭教育的基础

**** 段话

家庭教育是学校教育与社会教育的基础，在人的一生中起着重要的作用。据研究，目前我国将近 70%的家庭教育方式不够好，因此，转变家庭教育观念，提高家庭教育水平是家长必须认真面对的问题。

***** 音频

f425da7a-9384-40f2-bdf3-1cb9238a6462.mp3

**** 答案

B

*** 4

**** 选择

***** A

同学们的父母都愚团圆

***** B

有人想隐睿自己的事情

***** C

想投稿的同学都很孤独

***** D

假期有同学打算去旅游

**** 段话

漫长的暑假就要开始了。怎样度过这个假期，在同学们的心中酝酿了很久。有人想脱离父母的视线，找个寂静之处，享受一下孤独；有人想寻找打工的机会；有人想尝试给报刊、杂志投投稿，检验一下自己的本事；也有人禁不住旅游的诱惑，恨不得立刻投入大自然的怀抱。

***** 音频

d7f8a87f-4ae2-4a86-9ee1-c84e2019c386.mp3

**** 答案

D

*** 5

**** 选择

***** A

父母教育“我“好好读书

***** B

“我“的父母念书不太多

***** C

父母改变了“我“的一切

***** D

父母认为“我“没有缺点

**** 段话

我敬重我的父母，他们虽然学历不高，但是和蔼可亲，心地善良，更难得的是，他们总是告诉我要宽容，不要总想着别人的缺点，总想改变别人，要站在对方的立场上为别人着想，多体谅他人。

***** 音频

ec639d31-fd9a-4e6a-bc73-fda4286c9e7d.mp3

**** 答案

B

** 第三部分

*** 11-13

**** 课文

读大三的小孙每年都会利用寒暑假做不同类型的打工工作。“我想锻炼一下自己，学点儿与人交流的技巧，顺便赚点儿生活费。”小孙笑着说。

这个充满活力的女生告诉记者，这并不是她的第一份打工工作，之前在快餐店做过收银，在外语培训机构做过电话咨询。通过一次次不同的工作经历，小孙渐渐学会了如何与不同的人交流，特别是面对挑剔的消费者，如何让对方消火，化解危机，小孙有了自己的心得。“一味地谦让是不行的，要在与对方的交流中让他们认识到自己的不足，同时还要给对方台阶下，这样才能化解矛盾。这些都是在学校学不到的东西，我感觉自己在工作中成长了很多。”小孙跟记者谈到打工的收获时，脸上不由得满是兴奋。

**** 题目

***** 11

****** 选择

******* A

不愿意在快餐店工作

******* B

最喜欢做商店收银员

******* C

做过很多不同的工作

******* D

在外语培训机构上过课

***** 12

****** 选择

******* A

有的消费者很难交流

******* B

吵架的时候没必要谦让

******* C

对不讲理的人就不用客气

******* D

解决矛盾时要给对方留面子

***** 13

****** 选择

******* A

能够自己赚生活费了

******* B

每天能顺便锻炼身体

******* C

每个假期都过得开心

******* D

能学到课本外的东西

*** 14-17

**** 课文

随着旅游旺季的到来，小岛上的餐厅变得异常忙碌。与往年不同的是，这里大大小小餐厅的打工者除了中老年人，就是 18 岁以下的年轻人，往年忙里忙外的大学生不见了踪影。啤酒屋老板分析说：“以前确实有不少大学生会来店里找工作，现在是越来越少了，可能是大家生活好了，家长舍不得吧。”对这种现象，大学生却另有解释：现在打工的大学生比以前多多了，只是大家不干饭店服务员了。服务员、促销员等工作太简单，对自身能力提升有限，难以吸引大学生。即使挣钱也不值得浪费时间。

王新在一家咖啡吧打工，性格开朗的她说自己喜欢这里的工作环境，可以和来自全国，甚至全世界的游客聊天儿，还可以学习冲泡咖啡的手艺。王新计划毕业后也开一家创意咖啡馆。

与王新的悠闲相比，张海涛则忙碌了许多。他和同伴和开了一家特色纪念品小店，他们的小店一共就 5 个人，所以他们每人都身兼数职。不过张海涛认为这份忙碌是值得的，他就是想通过辛苦的工作取得一份创业的“真经”。

**** 题目

***** 14

****** 选择

******* A

旅游者老年人居多

******* B

餐厅的生意特别好

******* C

小岛上餐厅特别多

******* D

大学生都在餐厅打工

***** 15

****** 选择

******* A

不缺钱就不用打工

******* B

不如抓紧时间读书

******* C

打工纯属浪费时间

******* D

希望能够提升自己

***** 16

****** 选择

******* A

大学生打工更追求金钱之外的收获

******* B

年轻人不怕累,只希望工作有钱赚

******* C

悠闲、简单的工作最受大学生欢迎

******* D

年轻人觉得和朋友一起创业太辛苦

***** 17

****** 选择

******* A

在中国,喜欢喝咖啡的人多了

******* B

假期打工的大学生越来越少了

******* C

大学生打工的目的发生丁变化

******* D

大学生打工只能做简单的工作

