* 听力

** 1

*** 1

**** transcript

夜深了，我还在熬夜，为了准备考试，没有片刻的休息。一阵轻轻的脚步声，爸爸来到了我的身旁，轻声对我说：“渴了吧？”我回头，看到爸爸慈祥的目光，“爸爸，您还没睡？“他点点头。我喝了一口温热的牛奶，顿时，幸福传遍了我的全身 。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

王先生是师范大学教育学院的教授，兼任《中国家庭教育》杂志的主编，还是中国教育学会家庭教育专业委员会理事长。作为中国当代家庭教育研究的开拓者，他在家庭教育理论与实践的研究上做出过很多贡献。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

家庭教育是学校教育与社会教育的基础，在人的一生中起着重要的作用。据研究，目前我国将近70％的家庭教育方式不够好，因此，转变家庭教育观念，提高家庭教育水平是家长必须认真面对的问题。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

漫长的暑假就要开始了。怎样度过这个假期，在同学们的心中酝酿了很久。有人想脱离父母的视线，找个寂静之处，享受一下孤独；有人想寻找打工的机会；有人想尝试给报刊、杂志投投稿，检验一下自己的本事；也有人禁不住旅游的诱惑，恨不得立刻投入大自然的怀抱。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

我敬重我的父母，他们虽然学历不高，但是和蔼可亲，心地善良，更难得的是，他们总是告诉我要宽容，不要总想着别人的缺点，总想改变别人，要站在对方的立场上为别人着想，多体谅他人。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:ID: c5d60bd6-8a01-49fe-aa57-4739d046b523
:END:

*** 对话

女：今天我们很荣幸请到了教育方面的专家李老师和大家一起聊聊“啃老族”的问题。李老师，近来我们常听人说起“啃老族”，“啃老族”指的是些什么样的人呢？
男：指那些不升学、不就业、不进修，终日无所事事，有谋生能力，却还靠父母供养的年轻人。
女：这样一个族群是怎么产生的呢？
男：“啃老族”产生的原因是多方面的。比如，经济不景气，社会对就业的吸纳能力不足，年轻人找不到理想的工作，也有的是年轻人对工作的要求比较高，自身的学历、知识水平却不怎么过硬，又怕吃苦，不愿出去工作养活自己，于是选择了啃老。
女：“啃老族”的出现，是不是也和家庭教育有关系呢？
男：那当然，父母的责任也是不可逃脱的，对孩子溺爱的家庭才会出“啃老族”，在孩子成长过程中，父母没有教会他们做人要有独立精神，没有教会孩子怎样规划人生。当然，社会原因也是有的，如前边提到的经济不够景气，年轻人就业压力大，他们找不到工作，只能选择“啃老”。
女：“啃老族”的出现，对家庭、对社会的影响是很负面的哈。
男：是，“啃老族”会使很多家庭出现矛盾，也会使原本能够生活得很幸福的家庭失去幸福的根基，“啃老族”的问题将成为未来影响家庭生活的“第一杀手”。特别是在中国已进入老年社会的今天，“啃老族”必将带来更多的社会问题。
女：那“啃老族”的问题应该怎么解决呢？
男：年轻人要独立自主，这种精神的树立除了要有正确的人生观、价值观，社会也应该为他们创造适合的工作机会。与其让父母养活“啃老族”，不如给他们工作岗位，让他们成为有能力养活父母的“养老族”。

**** 音频

7d96405a-d8ce-44b3-a1f5-0e20cf9e4b11.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1a818bb8-51aa-4652-bf8d-3a7b1ffe3590
:END:

***** 问题

“啃老族”的特点是什么？

****** 音频

6f8a6655-7a1c-48fb-9ca9-038946194d02.mp3

***** 选择

****** A

整天闲着不干事

****** B

失去了学习机会

****** C

家里经济条件好

****** D

没有能力养活自己

***** 答案

A

**** 7
:PROPERTIES:
:ID: 55e29a28-12fa-4775-a58a-0a25d3086b28
:END:

***** 问题

以下哪一项是“啃老族”产生的原因？

****** 音频

0c830f86-4af8-4a77-8e9f-de107e8a61f4.mp3

***** 选择

****** A

年轻人缺少工作能力

****** B

年轻人学的知识太少

****** C

父母愿意掏钱养活他们

****** D

社会提供的工作机会不足

***** 答案

D

**** 8
:PROPERTIES:
:ID: 4ba50e64-2d71-4ce3-83b1-dcd21f523af9
:END:

***** 问题

“啃老族”的出现和家庭教育哪方面的问题有关？

****** 音频

ea618099-45e9-42b6-a98a-1aefc2b5e4c6.mp3

***** 选择

****** A

父母过分宠爱孩子

****** B

父母做事不负责任

****** C

父母缺少独立精神

****** D

父母不替孩子规划

***** 答案

A

**** 9
:PROPERTIES:
:ID: 8ac0b113-448d-4864-9a69-82c0cddbe00b
:END:

***** 问题

“啃老族”的负面影响是什么？

****** 音频

ef79b862-1dba-45b9-a947-90dbb7cb3c5c.mp3

***** 选择

****** A

经济不景气

****** B

家庭不和谐

****** C

社会不安定

****** D

老人不健康

***** 答案

B

**** 10
:PROPERTIES:
:ID: 19f532d6-f6ab-4648-ba70-c53be4db24ff
:END:

***** 问题

怎样解决“啃老族”的问题？

****** 音频

3970d36b-4552-43b3-bea6-aebce6941377.mp3

***** 选择

****** A

提高年轻人的能力，让他们学习

****** B

让有能力的人给年轻人工作机会

****** C

让年轻人树立正确的人生观、价值观

****** D

父母要给“啃老族“存下足够的钱

***** 答案

C

