* Listening

** 1

*** 1

**** transcript

人，还是要接地气。想归想，生活是另外一回事，要是始终追求感觉和完美会很累。有些事偶尔想想挺好，可做事还是要踏实些，该是啥样人就过啥样的日子，这样最舒服。

***** notes

接地气 / jie1 di4 qi4 / down-to-earth, in touch with the common people ;

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

在众多的连锁药店当中，有企业自身创建的，也有许多加盟的。由于数量增长过快，出现鱼目混珠的现象也在所难免，这就要求我们做好企业管理，防备出现轰轰烈烈开张，随即偃旗息鼓的局面。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

学术界可以断定，孔子是中国历史上第一个以私人身份教了大量学生的人。照传统说法，他有几千个学生，其中有几十人成为著名的思想家和学者。前一个数目无疑有夸大成分，但毫无问题的是，他是个很有影响的教师。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

近年来世界经济形势变化多端，公司面临的各种风险与日俱增，因此，适时地评估内部控制指引的适当性，并及时地予以修订尤其必要，这既可以及时引导公司关注各种新的风险，也可以防止因指引过时而形同虚设。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

海兴的苹果很有名，他们曾把该县产的“红富士”与中国最有名的“红富士”混到一起，请专家品尝，愣是弄得许多专家分不清伯仲。海兴昼夜温差大，降水适中，气候条件与“红富士”的故乡日本富士岛非常相近，这就难怪海兴“富士”难住了专家。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



