* 听力

** 第二部分
:PROPERTIES:
:ID: 6da1fc5d-8695-49f6-9151-eebe99f3d092
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：各位听众朋友晚上好，今天我们非常荣幸地请到亿利资源集团董事长王文彪先生做客本台。您能不能先简单介绍一下您的经历。
男：我生于沙漠，长于沙漠，每日所见都是漫漫黄沙，这是我 29 岁前的生活。挑战沙漠，改造沙漠，把死亡之海变成沙漠绿洲，这是我现在和以后的目标。
女：您开始从事治沙这项工作以来，最困难的是什么时候？
男：1988 年，我作为沙漠盐厂厂长走马上任，盐厂生产蒸蒸日上，却因为黄沙堵路，盐产品经常运不出去，我们的盐厂不得不先修公路。沙漠公路不比咱们一般的公路，要解决流沙覆盖公路的问题。65 公里的沙漠公路一修就是 3年，我们经历了一次又一次的失败，被流沙搞得焦头烂额。
女：你们是在失败和奋斗中趟出了一条科学治沙之路？
男：是啊，我们走了很多弯路，深深地感到要想治沙，前提是科学、是技术。比如，我们通过飞播技术，在打好的格子上种草，等生长出来的草控制住沙丘，再大面积种植沙柳和杨树，这些改善沙漠生态的办法，都是从实践中探索出来的，否则你一棵树也种不出来。
女：听说您还获得了联合国环境与发展大奖，您所在的库布齐沙漠已经变得生机勃勃，沙漠经济也搞得有声有色。
男：库布齐沙漠是中国第七大沙漠，总面积 1.86 万平方公里。我们通过 28 年的坚守，创造了 6000 多平方公里沙漠绿洲，如今我们要向沙漠要效益，发展沙漠经济，把生态当生意做，把保护生态变成一项可持续发展的事业。
女：28 年是一个漫长的过程。现在您已经被业内看作是我国生态产业的领军人物了，您感受如何？
男：沙漠治理、保护生态不是一个人的事业，也不是一朝一夕的事情，它需要成千上万的人共同奋斗，需要更多的人把最美好、最青春的年华献给沙漠。

**** 音频

cd8fb4dc-976d-4bc7-91a3-4413e717ea08.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 87f551c7-50d8-4954-a98a-1e9fa5702eb0
:END:

***** 问题

男的 29 岁前的生活，下列哪项正确？

****** 音频

8a154032-db30-44e4-a15e-4afcfef5ad34.mp3

***** 选择

****** A

制定治沙目标

****** B

在沙漠中修路

****** C

开始挑战沙演

****** D

生长在沙演中

***** 答案

D

**** 7
:PROPERTIES:
:ID: 5d2fc1a6-7f5f-49be-888c-453813265501
:END:

***** 问题

1988 年发生了什么事情？

****** 音频

94a1404e-636c-45e1-b1d0-4177e20124a0.mp3

***** 选择

****** A

男的当了盐厂的厂长

****** B

沙演公路终于通车了

****** C

发现了沙漠中的盐矿

****** D

土地沙漠化更严重了

***** 答案

A

**** 8
:PROPERTIES:
:ID: ffb6fe7f-e3b2-43bb-ada7-2c116c9417f1
:END:

***** 问题

为了在沙漠中种树，人们做了哪些努力？

****** 音频

a789dc13-eeca-4a05-af0d-260796a0c247.mp3

***** 选择

****** A

不怕失败，努力探索

****** B

大量种树，少量种草

****** C

去国外学习科学技术

****** D

尝试种植不同的树种

***** 答案

A

**** 9
:PROPERTIES:
:ID: 289d20fe-8111-4fd5-b357-522085d62dc1
:END:

***** 问题

关于库布齐沙漠，下列哪项正确？

****** 音频

648d77f6-0cc4-479e-a468-de7be6cf89af.mp3

***** 选择

****** A

是世界有名的沙漠

****** B

正计划搞沙漠经济

****** C

沙漠改造很见成效

****** D

得到联合国的支持

***** 答案

C

**** 10
:PROPERTIES:
:ID: fef7b04f-9f11-40cb-8e2e-ee740ddc9b8a
:END:

***** 问题

男的有什么感受？

****** 音频

8b0e1078-a501-4f5b-8fcc-f5094be3110a.mp3

***** 选择

****** A

 28年一晃就过去了

****** B

保护生态是长期任务

****** C

生态产业缺少领头人

****** D

年轻人应该献身沙漠

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

做人不要脱离实际

***** B

生活不需要愚象力

***** C

要精心安排好生活

***** D

完美的东西追求不到

**** 段话

人，还是要接地气。想归想，生活是另外一回事，要是始终追求感觉和完美会很累。有些事偶尔想想挺好，可做事还是要踏实些，该是啥样人就过啥样的日子，这样最舒服。

***** 音频

f6c0698f-3de8-4587-b928-263ff7bd0f15.mp3

**** 答案

A

*** 2

**** 选择

***** A

连锁企业很受欢迎

***** B

鱼店的生意都很好

***** C

商店开张搞得很热闹

***** D

连锁药店应加强管理

**** 段话

在众多的连锁药店当中，有企业自身创建的，也有许多加盟的。由于数量增长过快，出现鱼目混珠的现象也在所难免，这就要求我们做好企业管理，防备出现轰轰烈烈开张，随即偃旗息鼓的局面。

***** 音频

4f7fd414-5f2e-4505-8fe4-e7dd8ed34a90.mp3

**** 答案

D

*** 3

**** 选择

***** A

孔子的学生成千上万

***** B

孔子说话常用夸张的方法

***** C

孔子的学生都很有影响力

***** D

孔子是中国的第一位私学教师

**** 段话

学术界可以断定，孔子是中国历史上第一个以私人身份教了大量学生的人。照传统说法，他有几千个学生，其中有几十人成为著名的思想家和学者。前一个数目无疑有夸大成分，但毫无问题的是，他是个很有影响的教师。

***** 音频

da5f43dc-d395-4447-9e6f-8f6087db36f7.mp3

**** 答案

D

*** 4

**** 选择

***** A

公司必须重新编写内部规刑

***** B

公司面临的风险每天都在增加

***** C

所有公司都能及时关注各种风险

***** D

出版公司要不断修订过时的出版物

**** 段话

近年来世界经济形势变化多端，公司面临的各种风险与日俱增，因此，适时地评估内部控制指引的适当性，并及时地予以修订尤其必要，这既可以及时引导公司关注各种新的风险，也可以防止因指引过时而形同虚设。

***** 音频

cb42998c-1729-459e-9d2a-8588c2aa67a1.mp3

**** 答案

B

*** 5

**** 选择

***** A

海兴是红富士的故乡

***** B

海兴很适合栽种苹果

***** C

专家看着苹果一直发愣

***** D

专家弄不清海兴的位置

**** 段话

海兴的苹果很有名，他们曾把该县产的“红富士”与中国最有名的“红富士”混到一起，请专家品尝，愣是弄得许多专家分不清伯仲。海兴昼夜温差大，降水适中，气候条件与“红富士”的故乡日本富士岛非常相近，这就难怪海兴“富士”难住了专家。

***** 音频

01356a83-4386-48ef-a412-b4d8ddf068a2.mp3

**** 答案

B

** 第三部分

*** 11-13

**** 课文

中药主要由植物药、动物药和矿物药组成，植物药指植物的根、茎、叶、果，动物药包括动物的内脏、皮、骨、器官等。因植物药占中药的大多数，所以中药也称中草药。

中国是中草药的发源地，目前中国大约有 12000 种药用植物。中药应用理论比较独特，讲究四气五味。四气又称四性，是指药性的寒、热、温、凉。五味指药物的辛、酸、甘、苦、咸。中草药的气、味不同，针对的病症也各异。

中草药的应用形式多种多样，有用药物加水煎熟后去渣留汁而成的汤剂，还有制成了成药的丸剂、膏剂、片剂、冲剂、注射剂等等。很多患者偏爱中成药，认为服用方便，不像汤药，煎制过程太过麻烦。但是从治疗的角度来讲，汤剂却是更好的，因为中医强调个体化治疗，并随时根据病情的变化调整药物的搭配，因此，汤剂更易取得最佳疗效。

**** 题目

***** 11

****** 选择

******* A

中药是中国生长的植物

******* B

中药是中医才用的草药

******* C

中药中大部分为植物药

******* D

中国可人药的植物最多

****** 问题

为什么中药又叫中草药？

***** 12

****** 选择

******* A

四气与四季的气候有关

******* B

中药咖道好疗效也会好

******* C

中草药也讲究烹饪技术

******* D

气、味不同的药治不同的病

****** 问题

关于四气五味，可以知道什么？

***** 13

****** 选择

******* A

多数患者更喜欢汤剂

******* B

中成药比汤药的疗效好

******* C

中成药更强调个体化治疗

******* D

汤剂可随时针对病人情况调整

****** 问题

根据这段话，可以知道什么？

*** 14-17

**** 课文

1999 年中国就有了“太空蔬菜”的报道，那时所谓的“太空蔬菜”是指将植物种子搭载飞船飞越太空，重返地球后，再经过农业专家培育种植出的蔬菜。严格来讲，它们仍然是地球上生长的蔬菜。实验的目的是检测种子经过太空失重、缺氧等特殊环境变化后，内部结构是否会发生激变。实验证明，这种种子种出的“太空蔬菜”的维生素含量高于普通蔬菜，对人体有益的微量元素含量也有所提高。

2015 年“太空蔬菜”又一次成为新闻报道的热点。这次所说的“太空蔬菜”与前次提到的不同，是将种子带到太空中，由生活在国际空间站的宇航员在太空微重力环境下种植而成的。它标志着该空间站蔬菜培育试验取得了阶段性的成功，也可看作是载人飞船在前往火星的行程中又迈出了重要一步。

太空种植食材，长期而言，将能很好地解决长途太空旅行无法供给新鲜食物的难题；短期而言，能起到降低成本的作用，因为当前每运送 1 公斤食物到国际空间站，要花费近 14 万元人民币。所以通常运送的都是些高热量并能长期存放的食品，新鲜食物尤其是蔬菜水果非常有限。

**** 题目

***** 14

****** 选择

******* A

种子曾到太空一游

******* B

农业专家去过太空

******* C

从太空带回的茶菜

******* D

在太空生长的蔬菜

****** 问题

1999 年“太空蔬菜”的概念是什么？

***** 15

****** 选择

******* A

增加蔬菜维生素含量

******* B

改变蔬菜的营养成分

******* C

促使种子内部结构发生变化

******* D

观察特殊环境对种孔的影响

****** 问题

把种子带上太空的目的是什么？

***** 16

****** 选择

******* A

种子是在太空培育的

******* B

宇航员在太空种植的

******* C

在模拟太空环境下种的

******* D

飞船前往火星途中种的

****** 问题

2015 年“太空蔬菜”的概念是什么？

***** 17

****** 选择

******* A

每株太空蔬菜都很贵

******* B

飞船带食物成本很高

******* C

-飞船食品供应品种很丰富

******* D

带种子会增加飞船的负担

****** 问题

根据这段话，可以知道什么？

