* 听力

** 1

*** 1

**** transcript

企业虽是老板一手创立的，但并不意味着老板就永远正确。很多老板在企业做到一定规模后，自信心膨胀，独断专行，功劳都归自己，失败都是下属的。久而久之，缺少了员工们的齐心协力，企业就会逐渐衰败。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 2

**** transcript

一般的主管是这样训练员工的：先告诉他们一些“成功之道”，再告诉他们，按照“成功之道”一一实践后，自然就可以成功了！这个主管和别人不一样，他先让员工相信自己可以成功。当这个信念已经深深烙在员工心里之后，他们就会开始认真讨论：现在该怎么成功？

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 3

**** transcript

很多企业老板热衷“短平快”，看到什么赚钱就干什么，一哄而上，缺乏企业长远战略布局。很少有人真正致力于企业创新，无论是研发、管理还是商业模式。这对企业的长期可持续发展是极为不利的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 4

**** transcript

其实，一般员工对管理者的要求并不高，你只要做到了公平公正地对待每一位员工，准确、客观地评价员工的工作表现，他就很愿意服从你的管理。“一碗水端平”是老百姓常念叨的一句俗话，而这也正是管理者应该常念的管理要决。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 5

**** transcript

网购时我的省钱妙招是保持理性，在网上选中商品后不直接掏钱购买，先在购物车里放一两周，也许过了新鲜劲儿就不会花钱买了。对于已经签单的快递，如果不合适或者用不着，就算花运费也要退掉，这样能够管理自己的过度消费行为，久而久之就养成了理性消费的习惯。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

** 2

*** 6-10

**** transcript

女：
男：
女：
男：
女：
男：
女：
男：
女：
男：
女：
男：

**** 6

***** transcript



***** alternatives

****** a



****** b



****** c



****** d


***** answer



**** 7

***** transcript



***** alternatives

****** a



****** b



****** c



****** d


***** answer



**** 8

***** transcript



***** alternatives

****** a



****** b



****** c



****** d


***** answer



**** 9

***** transcript



***** alternatives

****** a



****** b



****** c



****** d


***** answer



**** 10

***** transcript



***** alternatives

****** a



****** b



****** c



****** d


***** answer

**  第二部分
:PROPERTIES:
:ID: a86b5452-fe5c-4a41-b6dd-a3fcc7d707fc
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：经营食堂应该是最简单的小生意，假设你是食堂的小老板，怎样才能有效防范食堂采购环节的贪污问题？这可是一道考验管理者的综合题。今天我们请来一位食堂的管理者跟大家谈谈怎么处理食堂采购的管理难题。
男：大家好，食堂采购管理确实是个难题，因为任何商品的标准都不如粮食青菜油盐酱醋复杂，不信你试试看，你能管好一个食堂吗？
女：如果老板自己或让老板的亲信去买是不是能可靠一些呢？
男：这样一来你不就成了个体户了吗？你的食堂还能做大吗？如果再有第二个、第三个食堂你怎么管？
女：那我就派两个人去买， 一个买，一个监督。
男：管过企业的都知道，在现金交易，无发票，并且质量和价钱每天随着淡季、旺季变化的菜市场中，采购者抵御诱惑的能力很差，靠人监督人是不可靠的，两个人很快就能结成同盟。
女：那我就采取轮班制，每次去买的两个人都不同。
男：一看你就不懂食堂生意。千万别小看油盐酱醋青菜土豆这些人人都知道的东西，它们的采购可是很专业的活儿，不信你问你妈妈。一个不懂菜市行情的人往往会被小贩欺骗。
女：那就采购的人固定，监督的人轮换。
男：可是一个不懂行的人怎么可能有效监督一个天天采购的人？
女：看似简单的食堂生意，管理竟然如此复杂！那到底怎么办好呢？
男：我是这样做的，依据所购物品来拟定购买方案。需要每天买的青菜副食由大师傅负责，不需要天天买的粮油酱味招标采购，清洁用品等杂项由食堂经理买，炉灶器具锅碗瓢盆等固定资产由我亲自负责。
女：那不怕大师傅贪污吗？
男：不怕。这个食堂每人每天只有 7 元钱的伙食定额，扣掉主食和其他费用，每人每天副食只有 4 元钱。大师傅要用 4 元钱，买回能做出可口饭菜的材料已很不容易了，哪里还有贪污的余地？另外，我自己偶尔也就近逛菜市场，对市价比较清楚。

**** 音频

eabc229c-7de3-4f7c-aa37-30c1780f8953.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 6c71da73-dec6-489c-912e-07a90aefef00
:END:

***** 问题

本文主要讲了食堂管理哪个环节的问题？

****** 音频

45172871-7a54-4f6c-8ca0-6765a93337b4.mp3

***** 选择

****** A

 采购

****** B

 监督

****** C

 财务

****** D

 烹饪

***** 答案

A

**** 7
:PROPERTIES:
:ID: 716a9765-50ba-4b0f-9b62-6a47515b8eaf
:END:

***** 问题

老板或亲信负责采购会出现什么问题？

****** 音频

21aa54aa-18aa-4c74-ad6e-7b6555ca86dd.mp3

***** 选择

****** A

会出现缺乏经营本钱的问题

****** B

会出现采购不够专业的问题

****** C

会出现食堂不能做大的问题

****** D

会出现隼以防范的贪污问题

***** 答案

C

**** 8
:PROPERTIES:
:ID: 775f4f6e-bb3b-44f8-b316-79471f5e7ee9
:END:

***** 问题

为什么采购者抵御诱惑的能力很差？

****** 音频

93931f20-63c0-4d0c-834c-516398e79b4d.mp3

***** 选择

****** A

食堂采购员缺乏专业训练

****** B

食堂采购员不是老板亲信

****** C

粮食青荷油盐醋的采购标准十分复杂

****** D

菜市场现金交易、无发票、价格变化大

***** 答案

D

**** 9
:PROPERTIES:
:ID: 5f63db18-2fdd-4fe8-aca3-a9f96ec7d748
:END:

***** 问题

采取轮班制采购会有什么后果？

****** 音频

984a902b-5301-4ad0-a6f5-7d3cf0ae7121.mp3

***** 选择

****** A

大家不能互相关照

****** B

人和人会结成同盟

****** C

不专业的采购者会被小贩欺骗

****** D

不懂行的人不能有效监督采购者

***** 答案

C

**** 10
:PROPERTIES:
:ID: 195415f0-409c-40b7-8b6c-740142da23f8
:END:

***** 问题

文中老板采取了什么采购策略？

****** 音频

a4035bfb-4dfd-48a0-b12d-ba1bfda263e2.mp3

***** 选择

****** A

不同的人轮流采购

****** B

一人采购，一人监督

****** C

对所有东西都招标采购

****** D

不同物品由不同的人采购

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

老板的创业历程很艰辛

***** B

要有自信企业才能成功

***** C

老板应该掌握企业的一切

***** D

成功后也要听取不同声音

**** 段话

企业虽是老板一手创立的，但并不意味着老板就永远正确。很多老板在企业做到一定规模后，自信心膨胀，独断专行，功劳都归自己，失败都是下属的。久而久之，缺少了员工们的齐心协力，企业就会逐渐衰败。

***** 音频

10173add-13b7-41f1-a5b4-d50e8a3f55cb.mp3

**** 答案

D

*** 2

**** 选择

***** A

这个主管教育员工空想没有用

***** B

这个主管先告诉员工“成功之道“

***** C

这个主管先让员工相信自己能成功

***** D

这个主管认为怎样成功不是大问题

**** 段话

一般的主管是这样训练员工的：先告诉他们一些“成功之道”，再告诉他们，按照“成功之道”一一实践后，自然就可以成功了！这个主管和别人不一样，他先让员工相信自己可以成功。当这个信念已经深深烙在员工心里之后，他们就会开始认真讨论：现在该怎么成功？

***** 音频

58a62890-73fb-46d2-853f-3aeaba38a77a.mp3

**** 答案

C

*** 3

**** 选择

***** A

企业发展并没有什么规律

***** B

“短平快“有利于企业发展

***** C

缺乏长远布局对企业发展不利

***** D

很多老板热衷于商业模式创新

**** 段话

很多企业老板热衷“短平快”，看到什么赚钱就干什么，一哄而上，缺乏企业长远战略布局。很少有人真正致力于企业创新，无论是研发、管理还是商业模式。这对企业的长期可持续发展是极为不利的。

***** 音频

23592c90-6bd3-4803-aed5-13305493291f.mp3

**** 答案

C

*** 4

**** 选择

***** A

管理者要尼量满足员工的要求

***** B

管理者要公平地对待每位员工

***** C

管理者要让员工绝对服从自已

***** D

管理者要让员工提出自己的看法

**** 段话

其实，一般员工对管理者的要求并不高，你只要做到了公平公正地对待每一位员工，准确、客观地评价员工的工作表现，他就很愿意服从你的管理。“一碗水端平”是老百姓常念叨的一句俗话，而这也正是管理者应该常念的管理要决。

***** 音频

097735b5-07f9-4889-9150-99ef2bd1a117.mp3

**** 答案

B

*** 5

**** 选择

***** A

网购时要注意物品是否新鲜

***** B

网购时要选择物美价廉的商品

***** C

网购时要养成理性消费的习惯

***** D

网购时每次消费金额都不要太大

**** 段话

网购时我的省钱妙招是保持理性，在网上选中商品后不直接掏钱购买，先在购物车里放一两周，也许过了新鲜劲儿就不会花钱买了。对于已经签单的快递，如果不合适或者用不着，就算花运费也要退掉，这样能够管理自己的过度消费行为，久而久之就养成了理性消费的习惯。

***** 音频

73d5b63d-86ef-44f0-bda8-e360fb2b276b.mp3

**** 答案

C

