:PROPERTIES:
:CREATED: [2022-04-12 16:01:50 -05]
:END:

* Listening
:PROPERTIES:
:CREATED: [2022-04-12 12:31:05 Hora est. Pacífico, Sudamérica]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-12 16:04:33 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-12 12:32:40 Hora est. Pacífico, Sudamérica]
:ID: e900e856-bced-44ce-86b1-8ff7be16a028
:END:


昨天我和朋友们一起去唱歌了。
pi: zuótiān wǒ hé péngyou men yiqǐ qù chànggē le
en: yesterday I went with my friends to sing
es: ayer fui con mis amigos a cantar

*** 2
:PROPERTIES:
:CREATED: [2022-04-12 12:57:16 Hora est. Pacífico, Sudamérica]
:ID: c30a5d6d-eb11-4bc6-bd57-05f1667d2d21
:END:

右边看报纸的那个女孩子是我姐姐。
pi: yòubian kàn bàozhǐ de nǎ ge nǚ háizi shì wǒ jiějie
en: the girl on the right reading the newspaper is my sister
es: la niña a la derecha leyendo el periódico es mi hermana

*** 3
:PROPERTIES:
:CREATED: [2022-04-12 12:57:19 Hora est. Pacífico, Sudamérica]
:ID: 409dd14e-8d67-411f-8feb-42c444cfe675
:END:

她是新来的汉语老师。
pi: tā shì xīn lái de hànyǔ lǎoshī
en: she is the new chinese teacher
es: ella es la nueva profesora de chino

*** 4
:PROPERTIES:
:CREATED: [2022-04-12 13:04:30 Hora est. Pacífico, Sudamérica]
:ID: e327f0c3-de6f-4207-975e-4d6b01586e48
:END:

北京10°C（十摄氏度），我们那儿的天气比北京的冷。
pi: běijing shí shè shì dù, wǒmen nǎer de tiānqì bǐ běijīng de lěng
en: Beijing is ten degrees Celius and our weather there is colder than Beijing's
es: En Pekín hay 10 grados centígrados, y allí hace más frió que en Pekín

*** 5
:PROPERTIES:
:CREATED: [2022-04-12 13:25:25 Hora est. Pacífico, Sudamérica]
:ID: 9cd1d76c-caaa-43b5-91cf-a20688713df6
:END:

她生病了，明天可能不去上课了。
pi: tā shēng bìng le, míngtiān kěnéng bù qù shàng kè le
en: she got sick, she will probably not go to class tomorrow
es: ella se enfermó, probablemente no irá a clase mañana

** 2
:PROPERTIES:
:CREATED: [2022-04-12 16:04:30 -05]
:END:

*** 6
:PROPERTIES:
:CREATED: [2022-04-12 13:28:01 Hora est. Pacífico, Sudamérica]
:ID: 2ff4559a-739e-4689-be7e-297b88e3382e
:END:

女：昨天和你一起唱歌的人是谁？
pi: zóutiān hé nǐ yiqǐ chànggē de rén shì shéi?
en: who was the person you were singing with?
es: ¿quién era la persona con la que estabas cantando?

男：是我女朋友。
pi: shì wǒ nǚ péngyou
en: it was my girlfriend
es: era mi novia

*** 7
:PROPERTIES:
:CREATED: [2022-04-12 13:34:26 Hora est. Pacífico, Sudamérica]
:ID: db52ba9b-0ada-4c97-bc01-c3cc9f4caa80
:END:

女：右边看报纸的那个是你哥哥吗？
pi: yòubian kàn bàozhǐ de nǎ ge shì nǐ gēge ma?
en: is the person reading the newspaper on the right is your brother?
es: ¿la persona que está leyendo el periódico a la derecha es tu hermano?

男：对，他是我哥哥。
pi: duì, tā shì wǒ gēge
en: yes, he is my brother
es: sí, es mi hermano

*** 8
:PROPERTIES:
:CREATED: [2022-04-12 13:38:12 Hora est. Pacífico, Sudamérica]
:ID: f04a1e9b-2eeb-4c38-862c-3ffa6019188e
:END:

女：她是你们新来的老师吗？
pi: tā shì nǐmen xīn llái de lǎoshī ma?
en: is she a new teacher for you?
es: ¿es una profesora nueva para ti?

男：她不是新来的老师，她去年就来了。
pi: tā bú shì xīn lái de lǎoshī, tā qù nián jiù lái le
en: she's not a new teacher, she came last year
es: no es una profesora nueva, vino el año pasado

*** 9
:PROPERTIES:
:CREATED: [2022-04-12 13:41:44 Hora est. Pacífico, Sudamérica]
:ID: 10280cc2-b212-4285-b90e-76883588c2b7
:END:

女：今天的苹果比昨天的便宜一些，你来点儿吗？
pi: jīntiān de píngguǒ bǐ zuótiān de piányi yī xiē, nǐ lái diǎnr ma?
en: today's apples are cheaper than yesterday's, would you like some?
es: las manzanas de ayer son más baratas que las de ayer, ¿quieres algunas?

男：我再看看吧。
pi: wǒ zài kàn kàn ba
en: I'll take another look
es: voy a echar otro vistazo

*** 10
:PROPERTIES:
:CREATED: [2022-04-12 14:19:48 Hora est. Pacífico, Sudamérica]
:ID: 7a662e20-46fb-4973-ac76-e94d43f22228
:END:


女：前边说话的那几个人是谁？
pi: qiánbian shuōhuà de nǎ jǐ ge rén shì shéi
en: who are those people talking in front?
es: ¿quiénes son esas personas que hablan al frente?

男：不认识，可能是新来的学生吧。
pi: bù rènshi, kěnéng shì xīn lái de xuésheng ba
en: I don't know, probably the new students
es: no los conozco, probablemente los nuevos estudiantes

** 3
:PROPERTIES:
:CREATED: [2022-04-12 16:04:15 -05]
:END:

*** 11
:PROPERTIES:
:CREATED: [2022-04-12 14:24:18 Hora est. Pacífico, Sudamérica]
:ID: 8d57dfe4-7c72-46c4-8587-25d184bf6e8c
:END:

男：昨天和你一起唱歌的人是谁？
pi: zuótiān hé nǐ yiqǐ chànggē de rén shì shéi?
en: who was the person you sang with yesterday?
es: ¿quién era la persona con la que cantaste ayer?

女：是一个朋友，我同学介绍的，昨天第一次见。
pi: shì yī ge péngyou, wǒ tóngxué jièshào de, zuótian dì yī cì jiàn
en: it was a friend, introduced by my classmate, who I met for the first time yesterday
es: fue un amigo presentado por mi compañero de clase, al que conocí ayer por primera vez.

问：昨天和女的一起唱歌的人是谁？
pi: zuótiān hé nǚ de yiqǐ chànggē de rén shì shéi?
en: who was the person who sang with the woman yesterday?
es: ¿quién era el hombre que cantó ayer con la mujer?

*** 12
:PROPERTIES:
:CREATED: [2022-04-12 16:05:01 -05]
:ID: b1043036-7d9e-467a-9a6f-5f91d654efc6
:END:


男：你哥哥多大？
pi: nǐ gēge duō dà?
en: how old is your brother?
es: ¿cuántos años tiene tu hermano?

女：他25岁，比我大三岁。
pi: tā èrshíwǔ suì, bǐ wǒ dà sān suì
en: he's 25 years old, he's 3 years older than me
es: él tiene 25 años, es 3 años mayor que yo

问：女的多大了？
pi: nǚ de duō dà?
en: how old is the woman?
es: ¿cuántos años tiene la mujer?

*** 13
:PROPERTIES:
:CREATED: [2022-04-12 16:10:15 -05]
:ID: 9dd7d84d-ebea-4da4-9ad0-ed30fda72fa7
:END:

女：西瓜三块钱一斤，苹果一块五一斤。
pi: xīgua sān kuài qián yī jīn, píngguǒ yī kuài wǔ yī jīn
en: watermelon is three dollars half a kilo, apples are one dollar and a half half a kilo
es: las sandías cuestan tres yuanes el medio kilo y las manzanas un dolar y medio el medio kilo

男：苹果比西瓜便宜多了。我还是买苹果吧。
pi: píngguǒ bǐ xīgua piányi duō le, wǒ hái shì mǎi píngguǒ ba
en: apples are much cheaper than watermelons. I'd better buy apples
es: las mazanas son mucho mas baratas que las sandías, será mejor que compre manzanas

问：男的为什么买苹果？
pi: nán de wèi shénme mǎi píngguǒ?
en: why does the man buy apples?
es: ¿por qué el hombre compra manzanas?

*** 14
:PROPERTIES:
:CREATED: [2022-04-12 17:05:44 -05]
:ID: ceb8f5d9-ef3e-4bf1-9760-66242d2c13f7
:END:

男：你的生日是4月28号？
pi: nǐ de shēngrì shì 4 yuè 28 hào?
en: is your birthday on April 28th?
es: ¿tu cumpleaños es el 28 de abril?

女：是，你的生日是哪天？
pi: shì, nǐ de shēngrì shì nǎtiān?
en: yes, when is your birthday?
es: sí ¿cuándo es tu cumpleaños?

男：我也是那天的生日，我是八七年的，你呢？
pi: wǒ yě shì nǎtiān de shēngrì, wǒ shì bā qī nián de, nǐ ne?
en: my birthday is also on that day. I'm from 1987, how about you?
es: mi cumpleaños también es ese día, estoy en 1987 ¿y tú?

女：那我比你大一岁。
pi: nǎ wǒ bǐ nǐ dà yī suì
en: then I'm one year older than you
es: entonces soy un año mayor que tú.

问：他们两个人谁大？
pi: tāmen liǎng ge rén shéi dà?
en: who is older of the two of them?
es: ¿quién es mayor de los dos?

*** 15
:PROPERTIES:
:CREATED: [2022-04-12 17:15:44 -05]
:ID: 36525697-27d4-4763-ab98-736134907ce3
:END:

男：你的眼睛怎么红了？
pi: nǐ de yǎnjīng zěnme hóng le?
en: why are your eyes red?
es: ¿por qué tienes los ojos rojos?

女：是吗？可能是没休息好。
pi: shì ma? kěnéng shì méi xiūxi hǎo
en: are they? maybe it is because I didn't rest well
es: ¿lo están? probablemente sea porque no he descansado bien

男：那今天晚上早点儿睡觉吧。
pi: nǎ jīntiān wǎnshàng zǎo diǎnr shuìjiào ba
en: then go to bed early tonight
es: entonces vete a la cama temprano esta noche

女：好的，谢谢。
pi: hǎo de, xièxie
en: okay, thanks
es: sí, gracias

问：女的怎么了？
pi: nǚ de zěn me le?
en: what's wrong with the woman?
es: ¿qué le pasa a la mujer?

* Reading
:PROPERTIES:
:CREATED: [2022-04-12 17:21:30 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-12 17:22:27 -05]
:END:

*** 16
:PROPERTIES:
:CREATED: [2022-04-12 17:21:33 -05]
:END:

昨天我和朋友们一起去喝咖啡了。
pi: zuótiān wǒ hé péngyoumen yìqǐ qù hē kāfēi le
en: yesterday I went out for coffee with my friends
es: ayer fui a tomar un café con mis amigos

answer

e

*** 17
:PROPERTIES:
:CREATED: [2022-04-12 17:21:44 -05]
:END:

左边那个女孩子比右边的那个大两岁。
pi: zuǒbian nàge nǚháizi bǐ yòubian de nàge dà liǎng suì
en: the girl on the left is two years older than the one on the right
es: la chica de la izquierda es dos años mayor que la de la derecha

answer

b

*** 18
:PROPERTIES:
:CREATED: [2022-04-12 17:21:58 -05]
:END:

正在打电话的那个人可能是新来的王老师。
pi: zhèngzài dǎ diànhuà de nàge rén kěnéng shì xīn lái de wáng lǎoshī
en: the one who is on the phone is probably the new teacher, Mr. Wang
es: el que está al teléfono es probablemente el nuevo profesor, el Sr. Wang

answer

a

*** 19
:PROPERTIES:
:CREATED: [2022-04-12 17:22:08 -05]
:END:

多吃水果对身体好，你也来一个吧。
pi: duō chī shuǐguǒ duì shēntǐ hǎo, nǐ yě lái yí ge ba
en: eat more fruit is good for your body, you should bring one
es: comer mas fruta es bueno para la salud, tú deberías llevar una

answer

f

*** 20
:PROPERTIES:
:CREATED: [2022-04-12 17:22:17 -05]
:END:

这件衣服300块，比那件便宜50块。
pi: zhè jiàn yīfu sān bǎi kuài, bǐ nà jiàn piányi wǔ shí kuài
en: this dress is 300 yuanes, which is 50 cheaper than that one
es: este vestido cuesta 300 yuanes, que es 50 dólares más barato que ese.

answer

c

** 2
:PROPERTIES:
:CREATED: [2022-04-12 17:22:29 -05]
:ID: bbedb6a6-31d0-4938-bbe6-d720647c455b
:END:

唱歌
便宜
说话
可能
贵
比

*** 21
:PROPERTIES:
:CREATED: [2022-04-12 17:22:45 -05]
:END:

昨天25度，今天//昨天热一点儿。
比
pi: zuótiān èrshíwǔ dù, jīntiān bǐ zuótiān rè yìdiǎnr
en: yesterday it was 25 degrees, today it's a little hotter than yesterday
es: ayer había 25 grados, hoy hace un poco más de calor quer ayer

answer

f

*** 22
:PROPERTIES:
:CREATED: [2022-04-12 17:22:48 -05]
:END:

每个周末，我都喜欢和朋友们一起去//。
唱歌
pi: měi ge zhōumò, wǒ dōu xǐhuan hé péngyoumen yìqǐ qù chànggē
en: every weekend, I like to go singing with my friends
es: cada fin de semana, me gusta ir a cantar con mis amigos

answer

a

*** 23
:PROPERTIES:
:CREATED: [2022-04-12 17:22:50 -05]
:END:

你认识前边//的那两个人吗？
说话
pi: nǐ rènshi qiánbian shuōhuà de nà liǎng ge rén ma?
en: do you know the two people talking in the fron?
es: ¿conoces a las dos personas que están hablando delante?

answer

c

*** 24
:PROPERTIES:
:CREATED: [2022-04-12 17:22:50 -05]
:END:

天气不太好，我觉得//要下雨了。
可能
pi: tiānqì bú tài hǎo, wǒ juéde kěnéng yào xià yǔ le
en: the weather is not very good, I think it might rain
es: el clima no está bueno, creo que podría llover

answer

d

*** 25
:PROPERTIES:
:CREATED: [2022-04-12 17:22:52 -05]
:END:

苹果比西瓜//，我想多买点儿苹果。
便宜
pi: píngguǒ bǐ xīguā piányi, wǒ xiǎng duō mǎi diǎnr píngguǒ
en: apples are cheapter than watermelons, I want to buy more apples
es: las manzanas son más baratas que las sandías, quiero comprar más manzanas

answer

b

** 3
:PROPERTIES:
:CREATED: [2022-04-12 17:24:30 -05]
:END:

*** 26
:PROPERTIES:
:CREATED: [2022-04-12 17:24:55 -05]
:END:

左边看报纸得这个人是我姐姐，右边写字得那个人是我哥哥。
pi: zuǒbian kàn bàozhǐ de zhège rén shì wǒ jiějie, yòubian xiězì de nàge rén shì wǒ gēge
en: the person reading the newspaper on the lefti s my sister, the person writing on the right is my brother
es: la persona que lee el periódico a la izquierda es mi hermana y la que escribe a la derecha es mi hermano

他们家可能有三个孩子。
pi: tāmen jiā kěnéng yǒu sān ge háizi
en: there may be three children in their family
es: puede haber tres hijos en su familia

answer

1

*** 27
:PROPERTIES:
:CREATED: [2022-04-12 17:24:55 -05]
:END:

女儿让我告诉你，她今天晚上和朋友们一起唱歌，不回来吃晚饭了。
pi: nǚ'ér ràng wǒ gàosu nǐ, tā jīntiān wǎnshang hé péngyoumen yìqǐ qù chànggē, bù huílai chī wǎnfàn le
en: my daughter asked me to tell you that she is singing with her friends tonight and will not come back for dinner.
es: mi hija me ha pedido que le diga que esta nocha va a cantar con sus amigos y no estará en casa para la cena

女儿今天在家吃晚饭。
pi: nǚ'ér jīntiān zài jiā chī wǎnfàn
en: the daughter is home for dinner today
es: la hija está en casa para cenar hoy

answer

0

*** 28
:PROPERTIES:
:CREATED: [2022-04-12 17:24:55 -05]
:END:

这是儿子送给我的手表，因为明天是我的生日。
pi: zhè shì érzi gěi wǒ de shǒubiǎo, yīnwèi míngtiān shì wǒ de shēngrì
en: this is the watch my son gave me because it's my birthday tomorrow
es: este es el reloj que me regaló mi hijo porque mañana es mi cumpleaños

她送给儿子一块手表。
pi: tā sòng gěi érzi yí kuài shǒubiǎo
en: she gave her son a watch
es: le dio a su hijo un reloj

answer

0

*** 29
:PROPERTIES:
:CREATED: [2022-04-12 17:24:55 -05]
:END:

你问的这个问题很好，我要想一想，明天再告诉你，可以吗？
pi: nǐ wèn de zhège wèntí hěn hǎo, wǒ yào xiǎng yi xiǎng, míngtiān zài gàosu nǐ, kěyǐ ma?
en: that's a good question you asked, I'll have to think about it and tell you tomorrow, is that okay?
es: es una buena pregunta la que has hcho, tendré que pensarlo y te lo diré mañana ¿está bien?

他现在没有回答这个问题。
pi: tā xiànzài méiyǒu huídá zhège wèntí
en: he didn't answer the question now
es: ahora no responde la pregunta

answer

1

*** 30
:PROPERTIES:
:CREATED: [2022-04-12 17:24:55 -05]
:END:

哥哥的汉语比我好，姐姐的汉语也比我好。
pi: gēge de hànyǔ bǐ wǒ hǎo, jiějie de hànyǔ yě bǐ wǒ hǎo
en: my brother's chinese is better than mine, and my sister's chinese is better than mine
es: el chino de mi hermano es mejor que el mío, y el de mi hermana es mejor que el mío

我的汉语没有哥哥和姐姐那么好。
pi: wǒ de hànyǔ méiyǒu gēge hé jiějie nàme hǎo
en: my chinese is not as good as my brother's and sister's
es: mi chino no es tan bueno como el de mi hermano y mi hermana

answer

1

** 4
:PROPERTIES:
:CREATED: [2022-04-12 17:26:35 -05]
:ID: f3f59ddb-8f74-4131-8e1f-d00e4fa6a88c
:END:

这两天怎么没看见王老师？
pi: zhè liǎng tiān zěnme méi kànjiàn wáng lǎoshī?
en: how come I haven't seen Ms. Wang recently?
es: ¿cómo es que no he visto a la Sra. Wang recientemente?

我哥哥比我姐姐大三岁。
pi: wǒ gēge bǐ wǒ jiějie dà sān suì
en: my brother is three years older than my sister
es: mi hermano es tres años mayor que mi hermana

家里还有呢，来点儿水果吧。
pi: jiāli hái yǒu ne, lái diǎnr shuǐguǒ ba
en: we still have some at home, let's have some fruit
es: todavía tenemos algo en casa, llevemos algo de fruta

这是我爸爸送给我的，昨天是我的生日。
pi: zhè shì wǒ bàba sòng gěi wǒ de, zuòtiān shì wǒ de shēngrì
en: my dad gave it to me. yesterday was my birthday
es: me lo regalo mi padre, ayer fui mi cumpleaños

他在哪儿呢？你看见他了吗？

我觉得公共汽车没有自行车快。因为路上车太多了。
pi: wǒ juéde gōnggòngqìchē méiyǒu zìxíngchē kuài. yīnwèi lùshang chē tài duō le
en: I don't think the bus is as fast as the bicycle, because there are too many cars on the road
es: no creo que el autobus es tan rápido como la bicicleta, porque hay demasiados coches en la carretera.

*** 31
:PROPERTIES:
:CREATED: [2022-04-12 17:26:37 -05]
:END:

今天的鸡蛋比昨天的便宜一些，您来点儿吧。
pi: jīntiān de jīdàn bǐ zuótiān de piányi yìxiē, nín lái diǎnr ba
en: today's eggs are cheaper than yesterday. have some.
es: los huevos de hoy son más baratos que los de ayer. Toma algunos.

answer

c

*** 32
:PROPERTIES:
:CREATED: [2022-04-12 17:26:38 -05]
:END:

你哥哥大还是你姐姐大？
pi: nǐ gēge dà hái yǒu nǐ jiějie dà?
en: is your brother older or your sister older?
es: ¿es mayor tu hermano o tu hermana?

answer

b

*** 33
:PROPERTIES:
:CREATED: [2022-04-12 17:26:38 -05]
:END:

这是你的自行车吗？真漂亮。
pi: zhè shì nǐ de zìxíngchē ma? zhēn piàoliang
en: is this your bike? it's beautiful
es: ¿esta es tu bicicleta? es muy bonita

answer

d

*** 34
:PROPERTIES:
:CREATED: [2022-04-12 17:26:39 -05]
:END:

你每天坐公共汽车去学校吗？
pi: nǐ měi tiān zuò gōnggòngqìchē qù xuéxiào ma?
en: do you take the bus to school every day?
es: ¿tomas el autobus para ir al colegio todos los días?

answer

f

*** 35
:PROPERTIES:
:CREATED: [2022-04-12 17:26:40 -05]
:END:

她可能去旅游了。
pi: tā kěnéng qù lǚyóu le
en: she may have gone on a trip
es: puede que se haya ido de viaje

answer

a

