* Listening

** 1

*** 1

**** transcript

乐观的人会有些主观，有些“傻”。他们习惯于“歪曲”现实世界，当现实世界不利于他们发展或有些危险时，他们倾向于人为地忽视危险，不把危险放在心上，乐观地认为，天塌不下来，睡醒再说。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 09:07:04 -05]
:END:

Optimistic people will be somewhat subjective, some "silly". They are accustomed to "distort" the real world, when the real world is not conducive to their development or some danger, they tend to artificially ignore the danger, do not put the central what danger on top, optimistic that the sky is not falling, wake up and say.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

日记是孩子成长过程中的心得体会，未经许可，家长是不应该看的。文具店里装潢漂亮、挂着小锁的日记本往往特别受欢迎，就是因为买主写完后可以将日记锁起来，以防被人偷看。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 09:55:21 -05]
:END:

A diary is a child's experience of growing up and should not be read by parents without permission. The beautifully decorated diaries with small locks in stationery stores are often particularly popular because the buyer can lock them up after writing to prevent peeking.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

服饰文化在人类文明史中占有很重要的地位。事实上，在各种服饰文化表象的背后，不论这种服饰是光彩四溢、如诗如画，还是朴实无华、素净淡雅，都存在着各种与之对应的服饰观念。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 09:58:46 -05]
:END:

The culture of dress occupies a very important place in the history of human civilization. In fact. Behind the various cultural appearances of costume, whether the costume is glamorous, or simple, plain and elegant, there are various corresponding costume concepts.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

不要让对方认为你抹杀了他的一切，一点儿也不承认他的好处，这样很难使谈话融洽地进行下去。无论你的意见和对方的意见相差多远，冲突多厉害，都要表现出一切都可以商量的诚意。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 10:02:55 -05]
:END:

Do not let the other person think that you erase everything he has to offer and do not acknowledge his benefits at all, so it is difficult to make the conversation go on harmoniously. No matter how far your opinion differs from the other person's and how strong the conflict is, show the sincerity that everything is negotiable.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

万圣节也叫“鬼节”，起源于公元前5世纪，欢度万圣节的习俗由爱尔兰移民带到北美。万圣节前后，在儿童商场能买到各种魔鬼图案的化装衣服、帽子和脸谱，年龄大一些的孩子们还会自行设计魔鬼套装。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 10:06:19 -05]
:END:

Halloween, also called "Ghost Day", started in the 5th century B.C. The custom of celebrating Halloween was brought to North America by Irish immigrants. Before and after Halloween, you can buy a variety of devil costumes, hats and faces in children's malls, and children of all ages will design their own devil suits.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



