* Listening

** 1

*** 1

**** transcript

我们的旅游一向是靠老祖宗留下的宫殿庙宇和老天爷造化的奇山秀水吃饭，许多“原装”景点尚且门庭冷落，经过微缩之后的“小玩意”到底有多少吸引力，前景实难预料。

***** translation

Our tourism has always relied on the old ancestors left the palaces and temples and God's creation of the strange mountain show small dinner many "original" original "attractions are still cold, after the micro "gadgets" in the end how much attraction, the future is hard to predict. It is difficult to predict the future.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

戏开拍前，他不惜血本，花费了数千万人民币搭建了一座影视城。为了再现当年明军与清军鏖战的场面，他不惜重金累计动用了数万人来担任群众演员，场面之宏大令人叹为观止。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:14:26 -05]
:END:

Before the shooting, he spared no expense, spending tens of millions of yuan to build a film city. In order to recreate the scene of the fierce battle between the Ming army and the Qing army, he spared no expense and used tens of thousands of people to serve as mass actors, the magnitude of the scene is breathtaking.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

转让无形资产，是指转让无形资产的所有权或使用权的行为；销售不动产，是指有偿转让不动产的所有权，转让不动产的有限产权或永久使用权。单位将不动产无偿赠送给他人等视同销售不动产的行为。

***** trnaslation

The transfer of intangible assets refers to the transfer of ownership or use of intangible assets. The sale of real estate refers to the transfer of ownership of real estate for a fee and the transfer of limited ownership or perpetual use of real estate. The unit will give away the real estate to others for free, etc. is regarded as the act of selling real estate.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

a

*** 4

**** transcript

企业在选拔班组成员时，应注意各种气质类型人员的适当搭配。这样，在工作中各种气质可以得到适当的互补。把不同气质的人搭配在一起，就可以发挥各种气质的积极因素，弥补其中消极的成分。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:13:37 -05]
:END:

When selecting team members, enterprises should pay attention to the appropriate mix of various temperament types of personnel. In this way, various temperaments can be appropriately complemented in the workplace. By matching people with different temperaments together, the positive factors of each temperament can be brought into play to compensate for the negative components.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

与其对社会公益事业的慷慨资助相比，他对自己的要求显得过于苛刻了，他生活十分俭朴，从不乱花一分钱，每天作画裁下的纸条儿都舍不得丢掉；到外边吃饭要打包，甚至连家里每月的开销也要精打细算，力求节俭。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 08:18:29 -05]
:END:

Compared with his generous support for social causes, he was too demanding on himself. He lived a very frugal life, never spending a penny indiscriminately, and could not throw away the strips of paper he cut out for his daily painting; he had to pack his meals away from home, and even his monthly expenses at home had to be finely calculated and frugal.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



