* Listening

** 1

*** 1

**** transcript

1997年，不安分的李长风突发奇想，宣布要造汽车。从这一年起，中国家用轿车的拥有量连年翻番。众多专家纷纷预言，中国的家用轿车时代已经到来。

***** translation

In 1997, the restless Li Changfeng had a sudden idea and announced that he wanted to build a car. From this year's small self, the ownership of China's domestic coupe has doubled year after year. Many experts have predicted that the era of China's household coupe has come.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

在我们的现实生活中，“用脚投票”原理极其简单：你搞不好、不公平，我就走人。例如，当股东们发现经理没有把企业经营好，企业的资产有可能贬值时，他们就会抛售股票，从而与该企业脱离关系。

***** translation

In our reality, the principle of "voting with one's feet" is extremely simple: if you don't do a good job, if it's not fair, I'll leave. For example, when shareholders find out that the manager is not running the business well and that the business's assets are likely to fall in value, they will sell their shares and disassociate themselves from the business.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

在着手进行休闲、观光方面的具体投资时，他发现：孤立的某一个娱乐项目难以吸引很多人，只有当一个地方风景优美、交通便利、饭店高档舒适、娱乐项目众多时，才可能吸引更多的游客。

***** translation

In embarking on leisure and sightseeing to the point of specific investment, he found: isolated a particular entertainment project is difficult to attract many people, only when a place with beautiful scenery, convenient transportation, high-grade hotel comfort, entertainment projects are numerous, it is possible to attract more tourists.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

在超市，如果顾客结账需要排队等候很长时间，他们就会失去耐心，一走了之，但如果开设很多收款台却少有人光顾，则又会导致成本提高。“排队模型”就试图为这个问题找到一个最好的解决方案。

***** translation

In supermarkets, if customers have to wait for a long time in the checkout line, they will lose patience and leave, but if there are many checkout counters but few people visit them, it will lead to higher costs. "The Queuing Model is an attempt to find the best solution to this problem.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

上中学时，爱因斯坦很喜欢数学。一次，叔叔给他讲了勾股定理的来历后，问爱因斯坦能不能试着证明它。爱因斯坦决定试一试。眼看着运算的草稿纸越积越厚，找到正确的证明方案却并非易事，但他没有动摇，二十多天后，他终于拿出了正确方案。

***** translation

When he was in high school, Einstein loved mathematics. Once, his uncle told him about the origin of the tethered strand theorem and asked Einstein if he could try to prove it. Einstein secondly decided to give it a try. Seeing the thickening of the draft paper of arithmetic, finding the correct proof scheme was not an easy task, but he did not waver, and after more than twenty days, he finally came up with the correct scheme.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



