* Text

** title

奇异的灯灯光

** content

传说古代有个爱如命的读书人，每当他捧捧起书本就像是走进了知识的海洋，天文地理、儒家经典、传记散文、历代诗词，都会便他着迷。历史文化的长期熏陶，使他思维敏捷，胸怀宽广。冬季使人不堪忍受的严寒以及炎热夏天蚊子的骚扰都没肝影响他读书的热情，唯独让他发愁的是家境贫乏，日子过得艰难，晚上看书别说蜡烛了，就是灯油也要节省着用。

又是一个闷热的夏夜，窗外阵阵热浪袭来，汗珠顺着脸往下流，脸上痒痒的，像有蚂蚁在爬，他用手擦了擦汗，依然沉醉在书本里由于坐得太久，他的颈椎有些麻木，屁股酸痛，他晃了晃头，用手揉了揉麻木的脖子，挪了挪屁股换个姿势，顿时麻木的部位恢复了知觉，他依旧沉浸在读书的快乐中。是啊，只要有书读，挨锇受冻他都不怕；只要有书陪伴，他就感觉幸福、美满，像是生活在天堂。

忽然，油灯无力地跳了两下，无声地熄灭了，眼前顿时陷入了黑暗。糟了，一定是灯油没有了，他有些泄气。黑暗中他眯起双眼，极力使自己尽快适应眼前的时料暗。他拿起油灯在耳边摇，灯油瓶空了。他放下灯，绝望地凝视着眼前的茫茫黑暗，不知道怎样打发这个漫漫长夜。

屋子里闷热的空气像是凝固了，烦躁在他身体中蔓延开来，他努力克制着自己的民且一绪，默默地背诵着刚刚读过的古诗，在头脑中编织着诗中描绘的动人画面，可这种强制的办法没有效果，于是，他打开房门走入了沉沉夜色。

夏日的夜十分美丽，一闪一闪的星星镶嵌在夜空中，偶尔还会吹来一阵凉风。他渐紧步在田野中，欣赏着美丽的夜景，忽然他社皮眼前的情形吸引住了，只见一大群萤火虫在低空盘旋飞舞，来来回回地飞。萤火虫的尾巴都有亮光在闪烁，成为黑暗中唯一耀眼的光芒。

他跟在萤火虫后面。忽然一只萤火虫飞到了眼前，他呻手一捞，把它握在了手心，摊开手掌，哇，萤火虫还老老实实地待在那里，尾部依旧闪着亮光，也许那亮光只能用毫米计算，可却还算明亮。瞬间，他头脑中迸发出一个想法：”如果将许多萤火虫集中在一起，不就成灯了吗？“他决定试一试。他找了个薄布做的布兜，抓了一些萤火虫放在里面，然后将袋口扎住，把口袋吊起来，一个“灯笼”就做成啦，虽然没有油灯亮，看书还是勉强可以的，从此，萤火虫做成的“灯”就夜夜陪伴着他。

他虽然不是天才，没有过人的天赋，但是日复一日的努力，使他的学识与日俱增，最后终于成为知名学者。

生活贫困并不可怕，可怕的是思想贫困、精神贫困、智慧贫困。贫困的经历在有些人那儿可以成为财富，成为奋斗拼搏的动力和源泉。

** source

改编自《学圣人悟做人》文章《囊萤照读》“编著：欧阳敏敏

** new words



