* 听力

** 1

*** 1

**** transcript

在查找资料的过程中，我发现外国人对于经典老车的区分很明确。1919年之前生产的汽车被叫作老爷车，之后生产的汽车叫古董车。单从这一点也可以看出，他们对于这些经典老车常常是怀着一份敬慕之情去看待的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

消费者不应该只把眼睛盯在哪种商品价格升了或是降了，支出多了还是少了，而应用心研究“钱”的购买力、“钱”的潜在价值还有哪些，只有这样，才能真正做到精打细算，花多少钱办多少事。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

对包装，人们提出了“绿色”的要求，希望它在保护环境和资源利用两方面都符合可持续发展的特征。即该种包装源于自然，能与自然融为一体，对生态环境和人类健康无害，能重复使用和再生。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

春节后是员工跳槽的高峰期，也是中国企业招聘的高峰期，一是会有员工离职，二是有些部门对人员有新的需求。作为部门经理，这时就应该对人员变动提前做好预期和准备，以免临时抓瞎。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

我见过许多成就颇高的华人文化艺术家，这些人往往是一袭中式对襟衣裳，神情淡定，举止儒雅。那种气质和风度，令人倾倒。我深信，文化就是蕴含在举手投足之间的秘密，这些生命与文化的密码，是任何形式的全球化都无法改变的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：大家好，在热闹的娱乐圈里，陈老师算是位特立独行的人物，演戏之余，往往深居简出，即使不得不参加一些公开的宣传活动，也是惜字如金。于是，一些人说他是典型的“孤芳自赏”“冷漠清高”，不过陈老师本人却觉得自己很委屈，也许是为了证明自己并不那么各色，他同意接受我的访问。您是不是一直有意识地使自己和这个圈子保持一定的距离？
男：我不是有意识的，在圈子里也有不少谈得来的朋友，但是我不喜欢动不动就上酒桌，我一上这个酒桌就觉得是一种煎熬。
女：没话说？
男：没话说，因为我本人不喝酒。尤其有这么一两次，当一个人喝醉酒，一个主题、一句话跟你说五遍的时候，我就感到窝火，头脑就会冲动，心里充满难以抑制的愤怒。
女：平常的潇洒劲儿也没了，觉得是别人强加给您的？
男：对。你还得客客气气地对他，好好听着。他跟你说五遍，一个名片递你八张。这时候我就觉得特别烦。
女：那跟什么样的人说话越来越多呢？
男：可能跟我自己对话多一些，我经常反问自己一些问题。
女：问自己什么问题呢？
男：其实仔细想一想，包括现在社会一天到晚在强调竞争，往往就忽略和忘记了独处的美好。
女：美好在什么地方？
男：我觉得是自我净化，自我调教，自我教化，在独处当中我才能够真正安安静静地去思考。我喜欢自己支配自己的时间。
女：那您靠什么来排解自己的压力和情绪呢？
男：我有第二支点，就是弹钢琴。我把弹钢琴当作自己情绪的抒发口。
女：不同情绪的时候弹不同的曲子？
男：对，我弹钢琴时面对一扇窗，从那扇窗可以望见天空，我经常会坐在钢琴前面，一边弹琴，一边使目光穿越窗口，用心跟一片片白云对话。
