* 听力

** 第二部分
:PROPERTIES:
:ID: 20b7b77a-ed15-491c-97c6-1d1ac47d4c03
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：大家好，在热闹的娱乐圈里，陈老师算是位特立独行的人物，演戏之余，往往深居简出，即使不得不参加一些公开的宣传活动，也是惜字如金。于是，一些人说他是典型的“孤芳自赏”“冷漠清高”，不过陈老师本人却觉得自己很委屈，也许是为了证明自己并不那么各色，他同意接受我的访问。您是不是一直有意识地使自己和这个圈子保持一定的距离？
男：我不是有意识的，在圈子里也有不少谈得来的朋友，但是我不喜欢动不动就上酒桌，我一上这个酒桌就觉得是一种煎熬。
女：没话说？
男：没话说，因为我本人不喝酒。尤其有这么一两次，当一个人喝醉酒，一个主题、一句话跟你说五遍的时候，我就感到窝火，头脑就会冲动，心里充满难以抑制的愤怒。
女：平常的潇洒劲儿也没了，觉得是别人强加给您的？
男：对。你还得客客气气地对他，好好听着。他跟你说五遍，一个名片递你八张。这时候我就觉得特别烦。
女：那跟什么样的人说话越来越多呢？
男：可能跟我自己对话多一些，我经常反问自己一些问题。
女：问自己什么问题呢？
男：其实仔细想一想，包括现在社会一天到晚在强调竞争，往往就忽略和忘记了独处的美好。
女：美好在什么地方？
男：我觉得是自我净化，自我调教，自我教化，在独处当中我才能够真正安安静静地去思考。我喜欢自己支配自己的时间。
女：那您靠什么来排解自己的压力和情绪呢？
男：我有第二支点，就是弹钢琴。我把弹钢琴当作自己情绪的抒发口。
女：不同情绪的时候弹不同的曲子？
男：对，我弹钢琴时面对一扇窗，从那扇窗可以望见天空，我经常会坐在钢琴前面，一边弹琴，一边使目光穿越窗口，用心跟一片片白云对话。

**** 音频

5deea55f-92c4-4ad6-af82-233b16e46e5d.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 5f856b35-21ee-4cd6-bd75-2c7d5c5c2f43
:END:

***** 问题

男的为什么接受这次采访？

****** 音频

98aef0a0-84f4-466e-beaa-ba9df13b0ce9.mp3

***** 选择

****** A

他非常欣赏这位记者

****** B

他不愚再冷漠下去了

****** C

他觉得别人误解他了

****** D

他演完戏后有时间了

***** 答案

C

**** 7
:PROPERTIES:
:ID: eb766336-c3be-4eab-8c8f-4eb0193ae15c
:END:

***** 问题

女的所说的“这个圈子”指什么？

****** 音频

76237e77-a79e-458d-be51-6a0e965835f0.mp3

***** 选择

****** A

娱乐圈

****** B

谈话圈

****** C

记者圈

****** D

百姓圈

***** 答案

A

**** 8
:PROPERTIES:
:ID: 93a54d20-60cc-4508-9ae0-5b7ef97b94f2
:END:

***** 问题

为什么男的一上酒桌就觉得煎熬？

****** 音频

a6d228a3-1b29-402a-b299-d274ca107e95.mp3

***** 选择

****** A

他对喝酒没兴趣

****** B

他本来话就不多

****** C

他痛恨别人唷唆

****** D

他怕自己喝醉了

***** 答案

A

**** 9
:PROPERTIES:
:ID: c42ee668-2434-4539-858c-a8c4eff9dca5
:END:

***** 问题

男的为什么喜欢独处？

****** 音频

869aeeaa-a439-4558-9c44-aacac0191dea.mp3

***** 选择

****** A

可以赢得竞争

****** B

可以静心思考

****** C

可以排解压力

****** D

可以听钢琴曲

***** 答案

B

**** 10
:PROPERTIES:
:ID: 5d4c771a-2656-4976-84d4-e861d4fe9102
:END:

***** 问题

关于男的，下列哪项正确？

****** 音频

6284eb64-cf1b-4fc2-b6e7-8cdecb0ad824.mp3

***** 选择

****** A

他只懂得自我欣赏

****** B

他的性格非常冲动

****** C

他很冷漠看不起人

****** D

他喜欢安静和思考

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

古董车的历史比老爷车长

***** B

外国人对车的评价十分经典

***** C

外国人对车怀有尊敬、仰慕之情

***** D

老爷车和古董车的区别在资料中有记载

**** 段话

在查找资料的过程中，我发现外国人对于经典老车的区分很明确。1919 年之前生产的汽车被叫作老爷车，之后生产的汽车叫古董车。单从这一点也可以看出，他们对于这些经典老车常常是怀着一份敬慕之情去看待的。

***** 音频

60e8e9f4-f85a-44d6-b042-effa6c2caf20.mp3

**** 答案

D

*** 2

**** 选择

***** A

消费者应该处处精打细算

***** B

东西涨价，就会增加支出

***** C

钱的潜在价值比商品价格更重要

***** D

精明的消费者能够少花钱多办事

**** 段话

消费者不应该只把眼睛盯在哪种商品价格升了或是降了，支出多了还是少了，而应用心研究“钱”的购买力、“钱”的潜在价值还有哪些，只有这样，才能真正做到精打细算，花多少钱办多少事。

***** 音频

a0347b39-9217-4366-b98b-65f9171f3315.mp3

**** 答案

C

*** 3

**** 选择

***** A

绿色包装对人体健康无害

***** B

绿色包装的颜色都很自然

***** C

绿色包装不支持重复使用

***** D

绿色包装都使用再生资源

**** 段话

对包装，人们提出了“绿色”的要求，希望它在保护环境和资源利用两方面都符合可持续发展的特征。即该种包装源于自然，能与自然融为一体，对生态环境和人类健康无害，能重复使用和再生。

***** 音频

13e4aa8d-6584-4a8b-aafd-b31d04758bae.mp3

**** 答案

A

*** 4

**** 选择

***** A

春节后是公司生产的旺季

***** B

春节后单位人员流动很大

***** C

很多部门经理工作抓得不够紧

***** D

公司应事先掌握人员变动情况

**** 段话

春节后是员工跳槽的高峰期，也是中国企业招聘的高峰期，一是会有员工离职，二是有些部门对人员有新的需求。作为部门经理，这时就应该对人员变动提前做好预期和准备，以免临时抓瞎。

***** 音频

e082c0c1-99be-484a-b045-3dbc37b48e60.mp3

**** 答案

B

*** 5

**** 选择

***** A

我访问过许多艺术家

***** B

全球化包括文化交流

***** C

艺术家的一举一动都有文化烙印

***** D

艺术家的气质、风度很令人信任

**** 段话

我见过许多成就颇高的华人文化艺术家，这些人往往是一袭中式对襟衣裳，神情淡定，举止儒雅。那种气质和风度，令人倾倒。我深信，文化就是蕴含在举手投足之间的秘密，这些生命与文化的密码，是任何形式的全球化都无法改变的。

***** 音频

fa47ca5c-7305-43b3-b793-1c304c31c3af.mp3

**** 答案

C

** 第三部分

*** 11-13

**** 课文

无论是摄影还是旅行圈子，火车迷都为数不少。王嵬对于火车、对于铁路的喜爱，源于小时候家住火车站附近，铁路就从他家楼下经过，趴在阳台上观察来往的火车是小王嵬最喜欢的游戏，后来，他变成了十足的“火车迷”。他观察火车、画火车、研究火车的车型和运动原理、关注铁路的历史和建设，他设想过自己当上了火车司机，也觉得造火车的工作很不错，没想到的是，如今他举办了铁路题材的个人摄影作品展。

这张拍摄于卓资山的照片是王嵬最喜欢的作品之一。他还记得这里的地形特点是多山、多丘陵、少平川，景色富于变化，非常美丽，火车蜿蜒穿行其间，又给这份景色平添了一份硬朗的动感。

为了拍出火车经过那里所呈现的大曲线的美感，王嵬多次前往，仔细研究卓资山大曲线的拍摄角度，最终在大曲线北端的高山上将曲线的“S”形整个收入到画面中。后来，随着穿山隧道的投入使用，卓资山大曲线完成了它的历史使命，不再有列车通行。他的这张照片承载的也就不光是一份美，还有着一段沉甸甸的历史了。

*** 14-17

**** 课文

从前，森林里生活着一群熊，它们食物充足，无忧无虑。突然有一天，森林着火了，它们的家园被烧光，食物没有了来源。这时，一部分熊说：“我们去北极吧，说不定那里有我们的天地。”另一部分则反对说：“不行，那里气候严寒，说不定我们会冻饿而死。还是找个近点儿的地方吧。”熊们争论到疲惫至极也没有结果。最后，一部分熊去了北极，一部分熊去了四季温暖、草木葱郁的盆地。

到了北极的熊学会了在冰冷的海水中捕鱼捉虾，甚至和比自己大的海豹搏斗，结果它们进化成高大凶猛的北极熊。到了盆地的熊发现，这里的食肉动物太多了，它们根本抢不到食物，于是它们改吃草；可是，更加意外的是，这里食草动物也多，它们连草也抢不到，于是它们改吃别的动物不吃的食物——竹子，这才勉强生存下来，成了人们天天念叨的濒危动物——熊猫。

竞争每天都在发生，如果一味地逃避，唯一的结果就是被淘汰出局。因此要勇敢地走在风暴的前面，敢于主动超越自己，只有这样，才能不被别人淘汰，让自己成为那个走在最前面的乘风破浪的勇士。

