* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 9db4beac-7e6c-49eb-a72c-97ddec9c9efe
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
cc4260b1-c3e8-4c0a-b0b5-2507fe545fef.mp3
***** 转录
1768年7月下旬，酷热笼罩着大地。紫禁城里，人们开始为皇家一年一度前往承德避暑山庄的转移做准备。在那里，有一片按照江南风格与神韵巧妙设计而成的园林，坐落着富有南方情调的豪华宫殿以及令人赏心悦目的亭台楼阁。
**** 选择
***** A
皇帝要去承德避暑了
***** B
7月的北方气候舒适
***** C
避暑山庄的宫殿十分简朴
***** D
紫禁城里有一片美丽的园林
**** 答案
A
*** 2
:PROPERTIES:
:ID: 2c46e670-e5a4-4742-a8d5-d1f9ee9b11ce
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
e32e1384-35d7-473d-957d-fcc6f13bc275.mp3
***** 转录
雏燕放飞的时候终于到了。为了这一天的到来，女儿的老师、朋友，以及我先生、我和女儿本人，都付出了许多的心血。这些心血已经变成女儿起飞的动力，使她能够展开翅膀，飞翔在全球资本市场的上空。
**** 选择
***** A
女儿是个科学家
***** B
女儿是个飞行员
***** C
很多人付出了心血
***** D
很多人来祝贺女儿
**** 答案
C
*** 3
:PROPERTIES:
:ID: 265132f0-0813-4a48-91dc-ff9cb13dc4c6
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
e9e291d2-607c-47b5-ba88-2c881281fcd2.mp3
***** 转录
喜欢旅游是因为她想放眼世界，在旅游中体验“行千里路胜读万卷书”的乐趣。喜欢烹饪，是因为她想用美味佳肴奖励辛勤工作之后的自己，同时也为亲朋好友献上在餐厅里吃不到的“美女私房菜”。
**** 选择
***** A
她喜欢旅游途中读书
***** B
她有一家自己的餐厅
***** C
她喜欢读与旅游相关的书
***** D
她喜欢做出美昧与朋友共享
**** 答案
D
*** 4
:PROPERTIES:
:ID: 652761af-5981-472a-91be-956ff2cb89ee
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
12747a27-89d1-4828-84e3-5813d4a5ac23.mp3
***** 转录
李小龙是一个神话。他以原本并不优秀的天赋自创截拳道，并成为影响世界的一代功夫巨星。他可在拍出多部影响世界的功夫电影的同时著书立说。他惊人的毅力和坚韧的品格，都已成为后人无法复制的神话。
**** 选择
***** A
李小龙有书出版
***** B
李小龙口才很好
***** C
李小龙十分有天赋
***** D
没人想复制李小龙
**** 答案
A
*** 5
:PROPERTIES:
:ID: b7e9bf03-bb1d-43c9-b82e-4c3671f73b4a
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
97e22bb8-f320-4e57-82e1-ff82b30be6b3.mp3
***** 转录
很显然，一些学科所以能够产生、存在和发展是因为它对于社会、人类有着自己的功能和价值。这种功能、价值一旦消失，这门学科便会失掉存在的意义，便会或迟或早地枯萎，直至被取消。
**** 选择
***** A
学科产生是社会发展的必然
***** B
学科存在的前提是对社会有用
***** C
学科的功能、价值迟早会消失
***** D
随着社会的发展将不再区分学科
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: f38491a6-81e0-4e88-9a2e-9d17baba7303
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
69df9ca7-9dc7-4ef3-a039-99cb2e147387.mp3
***** 转录
女：大家好，现在坐在我身边的是旅行家郑先生。郑先生，您好！ww
男：您好！我不是什么旅行家，只是喜欢旅行。
女：或者说是喜欢旅行在路上的感觉？
男：对，这个贴切。旅行在路上不仅能让你陶醉于风景，更重要的是体验人与人的沟通。忘却自己的身份去和来自不同地方的人面对面交流，这是我最喜欢的。
女：听说您尤其喜欢搭车旅行？
男：是，因为异样的旅行方式会带你感受不一样的风景。
女：搭车旅行是最近才兴起的吗？
男：不，国外早就有。中国是前几年，美籍华裔小伙谷岳和纪录片导演刘畅两个人历经三个月，从北京出发到柏林，一路上只依靠陌生人的帮助，共搭车88 次，走了 16000 多公里，穿越 13 个国家。这件事在中国传开之后，很多人开始搭车旅行。
女：碰上的都是未知的，我们不禁会对未知产生憧憬和向往！
男：也会充满惶恐，因为不知道自己该如何踏出勇敢的第一步。
女：能跟我们分享一下您记忆最深刻的搭车旅行吗？
男：那就是去西藏了。
女：冒险加神秘感？
男：不是，是西藏的壮美让我震撼。我那次运气特别好，搭的是一位藏族同胞的车，他是做生意的，我搭他的车几乎跑遍了我计划中所有想去的地方。
女：成专车了！
男：嗯，他说一个人开车也闷得慌，有我一路聊天儿，他还能跟我练练普通话。我们第一天是从拉萨去林芝，一路上抬头是蔚蓝的天空、漂浮的白云，远望是牧民、草场和牛、羊等牲畜，天上偶尔有老鹰盘旋。翻过米拉山，汽车开始在山谷间行驶，山上有泉水、瀑布，在峡谷间汇集成小溪，随着水量的增加，小溪汇聚成了江河，最后成了汪洋一片。那天的行程是我最有感悟的一天。
女：感悟什么呢？
男：“不积小流，无以成江海。”
女：是啊，就像滴水穿石一样，积累的作用不能小看。
**** 题目
***** 6
:PROPERTIES:
:ID: 6caae373-6837-4ee6-b7eb-5053be7d2045
:END:
****** 问题
******* 音频
6fdf33db-1c7e-4e07-aab2-c2f5694ca2d5.mp3
******* 转录
男的为什么喜欢“旅行在路上”的感觉？
****** 选择
******* A
因为能够认识更多有身份的人
******* B
因为别人能告诉你晨里风景好
******* C
因为能与不同的人面对面交流
******* D
因为能够了解各地的风土人情
****** 答案
C
***** 7
:PROPERTIES:
:ID: d3ae1ebf-2f39-45a4-830b-3908d887721d
:END:
****** 问题
******* 音频
23f86c5e-edf5-41ec-b25b-5ac9ccf4ff12.mp3
******* 转录
关于搭车旅行，下列哪项正确？
****** 选择
******* A
美国人在中国经常搭车旅行
******* B
很早以前中国人就搭车旅行
******* C
三个月以前有人尝试搭车旅行
******* D
谷岳、刘畅的搭车旅行影响了中国人
****** 答案
D
***** 8
:PROPERTIES:
:ID: a73c43b9-3a70-45f1-a68f-56804b166873
:END:
****** 问题
******* 音频
f704608f-cc0b-4136-bed5-fcd3dfbf1127.mp3
******* 转录
搭车旅行的魅力是什么？
****** 选择
******* A
对未知的神往
******* B
对已知的期待
******* C
对艰辛的恐惧
******* D
对能力的提升
****** 答案
A
***** 9
:PROPERTIES:
:ID: 75c9bf1f-dd49-44c7-b904-977d478ca68d
:END:
****** 问题
******* 音频
79d42dca-394d-42eb-b394-b09876005496.mp3
******* 转录
关于男的在西藏搭车的经历，下列哪项正确？
****** 选择
******* A
车主是个汉族人
******* B
车主也喜欢旅游
******* C
车主喜欢有人聊天儿
******* D
车主对西藏不太熟悉
****** 答案
C
***** 10
:PROPERTIES:
:ID: f92271b3-b28c-4f99-9915-61d00acff9ba
:END:
****** 问题
******* 音频
09e8a9df-7d3c-4301-8962-7512408ecd80.mp3
******* 转录
男的在西藏有什么感悟？
****** 选择
******* A
西藏的生态环境很好
******* B
西藏的江河湖海很美
******* C
一路的景色自然纯朴
******* D
积累的作用不能小看
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: f17ea1b2-7949-47a6-a326-72513caa57fc
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
4434d5d9-3188-46fd-94f8-7855987f3ecf.mp3
***** 转录
“地球生态超载日”又称“生态越界日”或“生态负债日”。“地球生态超载日”指的是，根据估计，地球当天进入了本年度生态赤字状态，即地球上全部人类活动的总消费量已超出了地球本年度产生的可再生自然资源的总量。
我们的地球就像失去了尾巴的壁虎，本来是可以恢复原貌的。它可以让植物再生长，可以恢复鱼类资源，重新吸收空气中的碳，让干净的水重回湖泊、河流和地下蓄水层。但这些过程需要时间。
自文明发祥以来的很长一段时间，地球补充资源的速度快于人类消耗资源的速度。然而，我们最终还是跨过了那条看不见的界线。从 1970 年起，我们每年从地球获取的资源开始超过其可以恢复的资源，自那以后，“地球生态超载日”就一路狂奔，不可阻挡，2015 年的 8 月 13 日它就已经来了。
**** 题目
***** 11
:PROPERTIES:
:ID: 38a3c1db-0066-4f94-976d-83698c159c92
:END:
****** 问题
******* 音频
cb2d6188-afe6-4229-aede-04cd65c3fabc.mp3
******* 转录
“地球生态超载日”意味着什么？
****** 选择
******* A
生态已经人不敷出
******* B
地球资源已近枯竭
******* C
地球已无法再制造资源
******* D
人类对再生资源利用不够
****** 答案
A
***** 12
:PROPERTIES:
:ID: 2d5de591-e4dc-4081-b3d2-b6beb9b6dc86
:END:
****** 问题
******* 音频
fdadbaea-cf8d-4144-8ba9-2fcc55a849b4.mp3
******* 转录
说话人举壁虎的例子主要想说明什么？
****** 选择
******* A
壁虎的自愈能力非常强
******* B
地球资源是取之不尸的
******* C
地球修复是需要时间的
******* D
污染的水无法自行净化
****** 答案
C
***** 13
:PROPERTIES:
:ID: b4c77f22-60be-4e7c-a2ab-d10e1d2e259d
:END:
****** 问题
******* 音频
02bcfc5c-94b5-4d5e-b0bb-f9bf9b5d9d9a.mp3
******* 转录
人类活动造成了怎样的后果？
****** 选择
******* A
地球补充资源的速度变慢了
******* B
地球的修复时间越来趁快了
******* C
“地球生态超载日“不好计算了
******* D
“地球生态超载日“越来越提前了
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: 5dacfcbd-d263-42d3-a202-18a6bbb8844e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
39e1a589-521c-4a98-bf35-ae5fc43328d0.mp3
***** 转录
丝绸之路，简称丝路。是指西汉时，张骞出使西域开辟的以长安（今天的西安）为起点，经甘肃、新疆，到中亚、西亚，并联结地中海各国，通往欧、非大陆的陆路通道。
中国是丝绸的故乡，在经由这条路线进行的贸易中，中国输出的商品以丝绸最具代表性，而输入的商品有玉石、珠宝、皮毛、香料、汗血马以及葡萄、黄瓜等农产品。19 世纪下半期，德国地理学家李希霍芬在 1877 年出版的《中国》一书中将这条陆上交通路线称为“丝绸之路”，此后中外史学家都赞成此说，沿用至今。
除了上述的路线之外，还有一条在南北朝时期形成，在明末发挥巨大作用的海上丝绸之路以及另一条在元末取代西北丝绸之路成为路上交流通道的南方丝绸之路。
**** 题目
***** 14
:PROPERTIES:
:ID: 9141090c-8584-4f6f-8884-273493d36eda
:END:
****** 问题
******* 音频
32554ae4-276a-4ed3-9caf-e50270ec5368.mp3
******* 转录
这段话中的“丝路”指的是什么？
****** 选择
******* A
陆上丝绸之路
******* B
海上丝绸之路
******* C
南方丝绸之路
******* D
运送丝绸的路
****** 答案
A
***** 15
:PROPERTIES:
:ID: e228b3f3-60af-4416-bd4c-6e914dd26004
:END:
****** 问题
******* 音频
c5798980-e3fc-439d-8af7-c2193c236216.mp3
******* 转录
说话人提到德国地理学家李希霍芬主要想说明什么？
****** 选择
******* A
他是一位地理学家
******* B
他是很有影响力的学者
******* C
他写过一本书叫《中国》
******* D
“丝绸之路“名孙的由来
****** 答案
D
***** 16
:PROPERTIES:
:ID: 0a8f15f9-ee7a-4bb9-b0e4-fccbbd78ffcb
:END:
****** 问题
******* 音频
e266f277-097e-4bbe-8a60-817ee560a174.mp3
******* 转录
丝绸之路的起点是今天的哪里？
****** 选择
******* A
新疆
******* B
西安
******* C
甘肃
******* D
中亚
****** 答案
B
***** 17
:PROPERTIES:
:ID: a8d44c9e-23b6-425e-a888-f19cf6796378
:END:
****** 问题
******* 音频
92703779-7144-47ef-9a9b-1d2a2f94b6cb.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
有了丝绸之路中国才有了马匹
******* B
中国出口商品中丝绸影响最大
******* C
陆路贸易通道在当时更受欢迎
******* D
丝绸之路是贸易往来的唯一通道
****** 答案
B
* 阅读
** 第一部分
*** 18
**** 句子
***** A
皮格马利翁是古代塞浦路斯的一位善于雕刻的国王。
***** B
这天，邻居家办喜事，请我去写对联，回来时已近中午。
***** C
他的豌豆杂交试验历时7年，他逐个地分析了数以万计的种子和植株。
***** D
制作糖瓜很难勾起年轻人的积极性，天天起早贪黑不算，还挣不了多少钱。
**** 答案
*** 19
**** 句子
***** A
每到开花季节，勤劳的蜜蜂到处采集花蜜，然后酿成蜜糖。
***** B
他是我们班学习最努力的学生，我断定他大概会考上大学。
***** C
这里环境优美，迷人的峡谷装饰着四时各异的色彩，令人流连忘返。
***** D
鸵鸾既吃小鱼小虾和昆虫一类动物性食物，也吃稻谷、草籽等植物性食物。
**** 答案
*** 20
**** 句子
***** A
他家过年的餐桌上曾经必备的一道菜，还有蛋侩。
***** B
具有镐而不舍追求真理的精神是一个人走向成功的必要因素。
***** C
计划工作是为实现组织未来目标铺平道路的，其本身就具有前眯性。
***** D
21世纪，经济全球化的浪潮汹涌滩涛，金融一体化则是经济全球化的关键。
**** 答案
** 第二部分
*** 21
**** 段话
“温室[[gap]]”使全球气候变得，许多地方发生干旱或洪浦，还会使冰山融化，海平面[[gap]]，海拔低的国家或岛屿有可能被淆没。
**** 选择
***** A
****** 1
效果
****** 2
反常
****** 3
拙高
***** B
****** 1
效应
****** 2
异常
****** 3
升高
***** C
****** 1
现状
****** 2
失常
****** 3
提升
***** D
****** 1
现象
****** 2
特别
****** 3
提高
**** 答案
*** 22
**** 段话
石林是世界[[gap]]的风景名胜，是大自然的[[gap]]之作。在广达400平方公里的区域内，[[gap]]着上百个黑色大森林一般的巨石群。有的独立成景，有的[[gap]]交错，这成一片。
**** 选择
***** A
****** 1
珍稀
****** 2
出色
****** 3
充满
****** 4
时而
***** B
****** 1
拥有
****** 2
鬼斧
****** 3
漫布
****** 4
大牙
***** C
****** 1
目睹
****** 2
经典
****** 3
遍及
****** 4
重叟
***** D
****** 1
罕见
****** 2
杰出
****** 3
遍布
****** 4
纵横
**** 答案
*** 23
**** 段话
随着人口的增加和耕地面积的减少，对农业生产的要求也越来越高，科学家必须[[gap]][[gap]]更多高产、优质、抗病虫的动植物[[gap]]，提供效率更高的高产优质生产[[gap]][[gap]]和更好保护地球环境的[[gap]]发展策略。
**** 选择
***** A
****** 1
培育
****** 2
品种
****** 3
技术
****** 4
可持续
***** B
****** 1
培养
****** 2
种类
****** 3
技能
****** 4
可利用
***** C
****** 1
养育
****** 2
产品
****** 3
能力
****** 4
可行性
***** D
****** 1
耕种
****** 2
商品
****** 3
本领
****** 4
可靠性
**** 答案
** 第三部分
*** 段话
世界文化遗产，是一项由联合国发起、联合国教育科学文化组织负责执行的国际公约建制，以保存对全世界人类都具有杰出普遍性价值的自然或文化处所为目的。[[gap:24]]，世界文化遗产属于世界遗产范畴。
世界遗产分为自然遗产、文化遗产、自然遗产与文化遗产混合体（即双重遗产）、文匕景又见〕皇′4类。国际文化纪念物与历史场所委员会等非政府组织作为联合国教科文组织的协力组织，[[gap:25]]。
1972 年，联合国教科文组织在世界文化遗产总部巴黎通过了《保护世界文化和自然遗产公约》[[gap:26]]，其宗叶在于促进各国和各国人民之间的合作，[[gap:27]]。
自中华人民共和国在1985年12月12日加人《保护世界文化与自然遗产公约》的缔约国行列至今，世界文化遗产、世界文化景观遗产、世界文化与自然双重遗产、世界自然遗产，[[gap:28]]。
*** 选择
**** A
成立联合国教科文组织世界遗产委员会
**** B
参与世界遗产的甄选、管理与保护工作
**** C
均有经联合国教科文组织审核被批准列人《世界遗产名录》的项目
**** D
为合理保护和恢复全人类共同的遗产做出积极的贡献
**** E
世界文化遗产是文化的保护与传承的最高等级
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
三江并流自然保护区是世界上蕴藏最丰富的地质地貌博物馆。4000万年前，印度次大陆板块与欧亚大陆板块大碰撞，引发了横断山脉的急剧挤压、隆升、切割，高山与大江交替展布，形成世界上独有的三江并行奔流170千米的自然奇观。
三江并流是一个很大的区域。准确地讲，是指长江上游的金沙江、湄公河上游的澜沧江以及怒江三条大江的并流区域，三江并行奔流，穿越于神山峻岭之间，形成世界上罕见的“江水并流而不交汇”的奇特自然地理景观。
三江并流地处东亚、南亚和青藏高原三大地理区域的交汇处，是世界上罕见的高山士也茗乒壹丕乏其扛一'子丁七口'J《弋丛<士也区，也是世界上生物物种最丰富的地区之一。万自然保护区总面积3500多平方公里。景观主要包括万江并流、高山雪峰、峡谷险海雪原、冰蚀湖泊，广阑美丽的雪山花和、丰富的珍稀动植物、独特的民族风情等。同时，该地区还是16个民族的聚居地，是世界上罕见的多民族、多语言、多种宗教信仰和风俗习惯并存的地区，是一块令人神往的处女景区。
**** 题目
***** 29
****** 问题
关于三江并流的形成，下列睇项正确？
****** 选择
******* A
是横断山脉断裂的结果
******* B
是江水奔流冲刷的结果
******* C
是大陆板块碰撞的结果
******* D
是人为改造自然的结果
****** 答案
***** 30
****** 问题
三江并流的奇特之处在于：
****** 选择
******* A
三条大江都很长
******* B
三条大江都很有名
******* C
三条大江都发源于长江
******* D
三条大江并行而不交叉
****** 答案
***** 31
****** 问题
关于三江并流，下列哪项正确？
****** 选择
******* A
那里的景观丰富壮丽
******* B
那里的生态保护做得不好
******* C
那里的动物种类为世界之最
******* D
那里的百姝聚居在16个区域
****** 答案
***** 32
****** 问题
第3段画线词语“处女景区”的意怡是：
****** 选择
******* A
尚未开发的景区
******* B
神仙都想去的景区
******* C
女人比男人多的景区
******* D
母系民族文化尚存的景区
****** 答案
*** 33-36
**** 段话
1981年，法国创设“最美乡村”品牌，至今已有157个古镇被列人法国文化遗产保护范围。有着1000多年历史的古镇贝弗龙，就是“最美乡村”之一。为保持原生态，贝弗龙严格控制商业用房的开发数量，至今依旧只有一家面包店、一家小超市和为数不多的儿家咖啡馆与餐馆。虽然生活不太方便，但保护与开发的平衡发展为贝弗龙赡得了生机，也给村民带来了实实在在的好处。
英国古城镇的保护与19世纪兴起的历史文化遗产立法运动息息相关《古迹保护法令》《城市规划法令兆古建筑及古迹法令兆地方政府古建筑法令》等多部专门的法律法规相继出台。根据这些法律规定，凡是1840年前的建筑物，都要加以保护，不得更改外观。
在德国，保护、修复甚至重建古城和古代建筑很少引发德国公众大讨论。二战后，德国人努力按照原样修复或重建历史建筑，由此形成的“老建筑”无不以假乱真。为保护和修复古建筑以及古镇，德国政府积极采取措施吸引投资者参与，同时通过立法约束确保古建筑保护到位。
中国古镇的开发、保护热潮早已席卷全国，除了乌镇、丽江、几凰这些游客早已耳熟能详的古镇外，四川的丹巴藏寨，几百幢民居依山就势，融于自然之中，体现了天人合一的理念；新疆的图瓦村环境优美，四周山清水秀，充满着古朴的原始色彩；云南的哈尼村落坐落在美丽的田园之中，与梯田、庄稼相依相谐，如同们境一般；腾冲的和顺古镇有清代民居100多座，风光如诗如画，被誉为中国古代建筑的活化石。
**** 题目
***** 33
****** 问题
法国贝弗龙古镇：
****** 选择
******* A
开发中避免了过度商业化
******* B
只为村民想，不为游客想
******* C
生活不方便阻碍了它的发展
******* D
在保护与开发之间经常摇揭
****** 答案
***** 34
****** 问题
在英国：
****** 选择
******* A
开展了古镇保护的讨论
******* B
就城市建设有一系列法令
******* C
曾兴起历史文化遗产立法运动
******* D
1840年前的建筑物可以更改外观
****** 答案
***** 35
****** 问题
德国的“老建筑”：
****** 选择
******* A
都是假的
******* B
修复后一点儿痕迹不露
******* C
全部由投资者参与修复
******* D
通过立法决定是否进行保护
****** 答案
***** 36
****** 问题
和第4段画线词语“耳熟能详”意思最相近的是：
****** 选择
******* A
熟能生巧
******* B
轻而易举
******* C
耳闻目睹
******* D
家喻户晓
****** 答案
