* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 2224caad-9ef2-4123-a1d5-f7c6747c5fcb
:END:
**** 对话
***** 转录
女：班里有哪些同学特别需要注意吗？[[file:d6b4efa3-57a1-467f-84cf-37846f8b5095.mp3][(audio)]]
男：你多留意赵福根。他上课从不发言，很多课不及格，平时也几乎不和同学交往。[[file:8e9022f8-4518-4cc6-93ef-3534aae1649d.mp3][(audio)]]
***** 音频
958347e5-51d6-4107-9a53-2d0009ce47a9.mp3
**** 问题
***** 转录
下列哪项是赵福根的问题？
***** 音频
4f8ed015-6a28-4183-8247-8cbe169eda82.mp3
**** 选择
***** A
成绩很好
***** B
不爱发言
***** C
喜欢逃课
***** D
交坏朋友
**** 答案
B
*** 2
:PROPERTIES:
:ID: 5f7deb98-fcb5-443d-ab48-cd25aed6bef8
:END:
**** 对话
***** 转录
男：听说你在读一个网络课程，感觉怎么样？[[file:f3f732b6-4e35-494f-b401-5c32cf44cc60.mp3][(audio)]]
女：还不错。你要不要也考虑考虑？可以免费试听两周，我就是试听了以后觉得好，才正式报的名。到现在已经听了两个月了。[[file:b9003024-96e0-4ad5-a6db-03321baa5951.mp3][(audio)]]
***** 音频
e00839ad-e4c7-40ef-ae1e-9dffabe8acee.mp3
**** 问题
***** 转录
女的这段时间在干什么？
***** 音频
aa907ceb-ef2c-4bb2-a953-91c9b2539564.mp3
**** 选择
***** A
考虑上网课
***** B
报名上网课
***** C
在试听网课
***** D
正在上网课
**** 答案
D
*** 3
:PROPERTIES:
:ID: c6aa7c40-0f73-4b7e-b032-1ceec6c9302c
:END:
**** 对话
***** 转录
女：他这次比赛的成绩怎么样？[[file:6ccf629d-16fe-4d43-a7b6-11fed7773e51.mp3][(audio)]]
男：很可惜，银牌，差一点儿就能拿冠军了。[[file:0e07bc29-c268-4bc1-a594-9e806b52bd68.mp3][(audio)]]
***** 音频
837e97f4-eca7-4aef-983c-086a2ccc0efc.mp3
**** 问题
***** 转录
他这次比赛得了第几名？
***** 音频
aae77936-d843-48d5-a0c2-842bc0cb1575.mp3
**** 选择
***** A
第一名
***** B
第二名
***** C
第三名
***** D
不知道
**** 答案
B
*** 4
:PROPERTIES:
:ID: c2642799-210e-4376-a1e9-92d0169689d5
:END:
**** 对话
***** 转录
男：真没想到，计划得这么好，还会出这样的事！[[file:921c1d47-96b7-4298-a974-27665be2ef14.mp3][(audio)]]
女：出事不怕，现在的问题是我们要主动承担责任，迅速采取行动。[[file:c9c1f5c5-013b-4239-90ba-8465ef85a7a6.mp3][(audio)]]
***** 音频
7e3fcf5f-221f-4f4a-8234-36484fbaae14.mp3
**** 问题
***** 转录
女的认为应该怎么做？
***** 音频
7d16c086-57d8-44a9-be33-14cb543c6c67.mp3
**** 选择
***** A
做好计划
***** B
避免出事
***** C
主动负责
***** D
提前行动
**** 答案
C
*** 5
:PROPERTIES:
:ID: 76903b99-0757-4809-9d57-017527dfe875
:END:
**** 对话
***** 转录
女：你到底想找个什么样的女朋友？[[file:7896090b-0750-4c8c-b996-1c7ba682d696.mp3][(audio)]]
男：漂不漂亮、工作好不好、有没有钱都不要紧，我就想要个温柔体贴的。[[file:09e25b14-3808-4b6d-9ae5-a33b02f9101b.mp3][(audio)]]
***** 音频
511f5ad0-5c66-4638-83d8-0ab87c7fafb2.mp3
**** 问题
***** 转录
男的找女朋友最重视什么？
***** 音频
435e52b7-e97a-4333-84a8-63ce3da48673.mp3
**** 选择
***** A
性格
***** B
收人
***** C
工作
***** D
长相
**** 答案
A
*** 6
:PROPERTIES:
:ID: 13284d41-c6b2-45cf-bb46-cc21a7ecbad6
:END:
**** 对话
***** 转录
男：他们俩不是挺好的吗，怎么突然就离婚了？[[file:926ce95d-c746-41fb-830d-764266066e04.mp3][(audio)]]
女：家家有本难念的经，你就别替人家操心了。[[file:a80a6863-bd9b-488d-9795-da5b410a48d4.mp3][(audio)]]
***** 音频
a80d4f86-5c34-4197-94cd-e36e8add5408.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
c908ac6e-05ca-498c-876b-529f8b48fb85.mp3
**** 选择
***** A
他们关系不好
***** B
他们没有离婚
***** C
大家都很关心这个问题
***** D
别人的情况我们不了解
**** 答案
D
** 第二部分
*** 7
**** 对话
***** 转录
女：爸爸，老师明天要来我们家做家访。
男：明天我有事，跟你妈妈说吧。
女：老师特意说了，每次家访都是见的妈妈，家长会也是妈妈去参加，希望这次能跟您见见面。
男：好吧，我明天先去公司安排一下。
***** 音频
509cf8d9-97c0-41cd-8260-530d99a990dd.mp3
**** 问题
***** 转录
明天老师和爸爸会在什么地方见面？
***** 音频
33259a0d-9901-4a35-ba53-1af8ac0ac9a6.mp3
**** 选择
***** A
家里
***** B
学校
***** C
公司
***** D
还没定
**** 答案
A
*** 8
**** 对话
***** 转录
男：刘老师，能不能请您利用空闲时间给我做一下辅导？
女：对不起，恐怕不行。
男：我可以另付费用的。
女：我们学校有规定，不允许老师给自己的学生做收费的辅导。
***** 音频
5be9535a-a032-40df-9b41-e3b52482a3ae.mp3
**** 问题
***** 转录
女的为什么不辅导男的？
***** 音频
d0deb6ee-9d01-49cc-988c-7e4f22c8f9b8.mp3
**** 选择
***** A
她没有时间
***** B
学校不同意
***** C
她觉得钱太少
***** D
男的不是自己的学生
**** 答案
B
*** 9
**** 对话
***** 转录
女：真不明白，儿子怎么老想出去闯世界，咱们家又不缺钱花！
男：男孩子，出去闯闯也好。
女：哪儿那么容易？
男：你不让他试试，怎么知道他不行呢？
***** 音频
b30eacee-5434-42df-b634-31c7725c3813.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
e4ee79be-143c-40a1-9f7a-171d629e4e9f.mp3
**** 选择
***** A
孩子没有这个能力
***** B
家里经济条件不好
***** C
应该让孩子去试试
***** D
闯世界没什么难的
**** 答案
C
*** 10
**** 对话
***** 转录
男：这么晚了，你怎么还不睡啊？
女：明天轮到我发言，我还要再练两遍。
男：差不多就行了，不必这么认真吧。
女：要是我自己的事就算了，但这是要算小组成绩的。
***** 音频
70d31202-28cb-4340-aa8b-01cdfd9c974d.mp3
**** 问题
***** 转录
女的为什么还不睡？
***** 音频
ef5980fb-a3d7-4826-ae00-2f00b560d6b7.mp3
**** 选择
***** A
现在还不晚
***** B
她没写完作业
***** C
她要代表小组发言
***** D
她太紧张了睡不着
**** 答案
C
*** 11-12
**** 对话
***** 转录
男：郝老师，你来支教一年多，觉得辛苦吗？
女：辛苦是辛苦，但我来这里，本来就不是为了来享受的。
男：这里条件这么差，刚来时是不是很不习惯？
女：条件虽然艰苦，但我觉得我的收获远远大于付出。
男：以后你还会做志愿者吗？
女：不管以后在哪儿，我都会继续用我的力量帮助山里的孩子们，因为孩子是我们国家的未来与希望。
***** 音频
c66efd18-7b84-46f4-90fe-468ea7c913a8.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于支教，郝老师有什么看法？
******* 音频
da543e47-1a0c-4ff8-a554-0d3faf9940a9.mp3
****** 选择
******* A
条件不差
******* B
是种享受
******* C
大辛苦丁
******* D
很有收获
****** 答案
D
***** 12
****** 问题
******* 转录
郝老师将来有什么打算？
******* 音频
658a027a-db08-4934-b345-58ace4e03171.mp3
****** 选择
******* A
她会留在山里
******* B
她会继续学习
******* C
她要帮助孩子们
******* D
她要回自己的国家
****** 答案
C
*** 13-14
**** 段话
***** 转录
今天，我们这个大学校园里迎来了众多中学生朋友。来自全国各地的 2500多名高中生齐聚清华园，共同参加 2016 年青少年高校科学营全国开营式。首先，我代表清华大学，向各位同学和老师的到来表示热烈的欢迎！2012 年青少年高校科学营开办，4 年来共吸引了 37000 多名营员参加，承办高校由也最初的 41所增加到 51 所，科学营已成为传播科学知识、科学思想、科学方法和提高青少年科学素质的重要平台。清华大学是科学营的最初参与者和积极的承办者，2013年全国开营式就在清华园举行，我们非常愿意再次承办科学营活动，为所有有科学梦想的同学搭建更加宽广的舞台。
***** 音频
c027619f-2eaf-47df-b9ae-5f501ab9b2ab.mp3
**** 题目
***** 13
****** 问题
******* 转录
这是什么活动上的讲话？
******* 音频
1e195f3d-d5f8-42ad-baef-5e9cea7a8380.mp3
****** 选择
******* A
大学运动会
******* B
科学营开营
******* C
高中开学
******* D
小学开学
****** 答案
B
***** 14
****** 问题
******* 转录
关于这次活动，下列哪项正确？
******* 音频
a7bb41b1-5bc9-4337-8dee-322fb2e8b28b.mp3
****** 选择
******* A
在大学举行
******* B
中小学生参加
******* C
已举办了三年
******* D
清华大学第一次举办
****** 答案
A
* 阅读
** 第一部分
*** 段话
各位老师，我院五年前曾经公开征集听力考试试题，进行试题库[[gap][15]]，当时工作取得了很好的效果。本学期，学院计划开展新题库的有关工作。具体包括：一、进一步扩大题库规模。原题库包括单句题、对话题和短文题各200道。现计划增加[[gap][16]]的数量，将三种题型各增加100道。二、因时代发展，社会发生变化，原题库中部分试题内容过时，不再符合当前的社会情况，需要进行[[gap][17]]或昼换。这项工作需要大家的力量，[[gap][18]]1
*** 题目
**** 15
***** 选择
****** A
建立
****** B
建筑
****** C
建设
****** D
建议
***** 答案
C
**** 16
***** 选择
****** A
题目
****** B
主题
****** C
问题
****** D
话题
***** 答案
A
**** 17
***** 选择
****** A
改正
****** B
改变
****** C
修改
****** D
进步
***** 答案
C
**** 18
***** 选择
****** A
你们都来看看
****** B
原来的不能用了
****** C
一个人是干不了的
****** D
欢迎各位老师积极参与
***** 答案
D
** 第二部分
*** 19
:PROPERTIES:
:ID: 56dc47d3-6eb8-4aee-80ab-89650b6a1bb4
:END:
**** 段话
这次，老师组织了一项8周的研究型学习活动，主题是“让家乡的明天更美好”。学生们参加以后说：“以前，我们总认为建设家乡是大人的事，用不着我们操心。不过，现在我们明白了，建设家乡，人人有责，我们也要承担这个义务。这个任务很艰巨，我们要尽自己最大的力量去完成。”
**** 选择
***** A
建设家乡是大人的事
***** B
这次活动可以自选主题
***** C
每个人都应该承担建设家乡的责任
***** D
小学生们承担不了这么艰巨的任务
**** 答案
C
*** 20
:PROPERTIES:
:ID: d90c8d56-8f06-4763-bff1-c5b3187d670d
:END:
**** 段话
为了能够保证活动顺利进行，请务必确保以下所有条件与您的实际情况相符，年满二十二周岁；大专或以上学历；有充足的时间，必须能完成最短一个学期的教学任务；取得家人对支教的理解和支持；有一定的经济能力，能承担支教期间所产生的相关费用，包括交通及日常生活用品和其他私人支出。
**** 选择
***** A
三十岁以上的人不能报名
***** B
研究生可以参加支教活动
***** C
这个活动至少要参加一年
***** D
这个活动需要参加人捐款
**** 答案
B
*** 21
:PROPERTIES:
:ID: fa0d9376-2e25-41ad-9e24-353ee01c0795
:END:
**** 段话
21。按照自己的特点制定作息时间表固然有道理，但有时却与考试要求的作息时间不一致。而人体的生物钟具有惯性，很难一下子完全调整过来。所以，在重大考试之前，必须提前行动，使自己各方面的情况，在考前调节到最理想的状态。
**** 选择
***** A
作息时间表必须按照自己的特点制定
***** B
人体的生物钟可以随时随地调整过来
***** C
考试要求的作息时间会影响人体生物钟
***** D
为取得好的成绩，应提前调整作息时间
**** 答案
D
*** 22
:PROPERTIES:
:ID: bc368cc5-da70-40e3-8cc9-a12191c0d845
:END:
**** 段话
中国从80年代开始开展普及义务教育的工作，但至今仍未完成。因此，“素质教育”的改革不能只是一句简单的口号，它在各个地区所面临的情况和需完成的任务是不一样的。北京、上海这样的大城市，可以侧重培养学生的创造性等，但对贫困地区来说，首先需要的还是完全普及义务教育。
**** 选择
***** A
普及义务教育的工作80年才能完成
***** B
“素质教育”是未来教育改革的方向
***** C
各个地区义务教育的普及程度一致
***** D
实施“素质教育”应该因地而异
**** 答案
D
** 第三部分
*** 23-25
**** 段话
每周三是女儿畅畅班里的图书馆日。这一天，他们要把上周借的书还回去，再把新的书借回来。这周二晚上，我帮畅畅收拾书包，发现她从学校图书馆借的书不见了，在家里找遍了也没找到。一想到把学校图书馆的书弄丢了不知道有什么后果，也不知道这一周畅畅还能不能借书，我就很着急。
我慢慢回想，我们放书的地方基本是固定的，出门也不会带书出去，那么只有一个可能，就是我把书还错了——上周畅畅从学校图书馆借了一本书，我在附近的公共图书馆也给她借了一本同样的。大概是去公共图书馆还书的时候我没注意，两本放在一起还了。
第二天，我忐忑不安地去公共图书馆咨询。当我说明了情况，工作人员告诉我，不用担心，凡是错还到这里的书，他们都会送回去的。“这种事经常发生。”工作人员这样说。放学的时候到学校接畅畅，我跟老师说了这件事。她的第一句话也是：“没关系，这种事经常发生。”原来，不止公共图书馆会收到学校图书馆的书，学校图书馆也会收到不属于自己的书。同样的，他们也会送回去。这是通行的规则。当我问及我是否需要跟学校图书馆说明，她说她会去跟图书馆核对，假如这本书他们没有收到，她再告诉我。所以，我什么也不用做。
至此，我一颗悬着的心才放了下来。我以为是多么严重的问题，他们却都显得很轻松。我想，这就是信任。
**** 题目
***** 23
****** 问题
作者为什么很着急？
****** 选择
******* A
她忘了给女儿收拾书包
******* B
她把图书馆的书弄丢了
******* C
图书馆的书被女儿弄坏了
******* D
她没有时间去接女儿放学
****** 答案
B
***** 24
****** 问题
根据上文，下列哪项是正确的？
****** 选择
******* A
学生们每周三去公共图书馆
******* B
两本书都还到学校图书馆了
******* C
图书馆和老师都没有批评妈妈
******* D
妈妈要亲自去向图书馆说明
****** 答案
C
***** 25
****** 问题
最适合做上文标题的是：
****** 选择
******* A
我的女儿畅畅
******* B
两家图书馆
******* C
书丢了怎么办
******* D
信任
****** 答案
D
*** 26-28
**** 段话
在中国贫困山区，师资非常紧缺，很多学校都是一个老师负责上多种文化课，所以每年都会招募大量的支教志愿者前往山区进行支教，改良山区的教学水平。支教志愿者招募条件有哪些呢？我们一起来看看吧！
首先呢，一定要有爱心。作为一名支教志愿者，每天相处最多的就是孩子，所以一定要有爱心，热爱这份事业！有很多人可能是为了体验一下山村生活而选择前往，这是不负责任的行为！
其次呢，一定要有充足的时间。给自己多留一点儿时间，多陪陪这些孩子，多让他们体会一下你看到的外面的世界。这对于他们来说是难能可贵的。不要刚刚前往就选择离开，这对于山区孩子来说是一种伤害。
然后呢，还要有一定的学识。当然，需要支教的山区孩子大多数都是小学生，支教老师不需要有多么高的学历，但是学识还是一定要有的。不只是
最后，承受能力、吃苦能力要强。山区生活条件艰苦，前来支教的志愿者要有有较好的承受能力，而不能因为生活条件差就匆匆离开。
如果大致符合以上条件的话，爱心人士基本就可以选择前往山区支教了，当然，不同的组织在招募不同地区的支教老师时，条件可能会有所不同，这是根据当地的实际情况来考量的。
**** 题目
***** 26
****** 问题
下列哪项不是担任支教志愿者的必要条件？
****** 选择
******* A
喜欢和孩子相处
******* B
有很高的学历
******* C
有一定的知识
******* D
能吃苦
****** 答案
B
***** 27
****** 问题
为什么说支教需要充足的时间？
****** 选择
******* A
孩子们需要陪伴
******* B
山区的老师很少
******* C
山区的交通不方便
******* D
在山区生活容易受伤
****** 答案
A
***** 28
****** 问题
关于支教，下列哪项正确？
****** 选择
******* A
老师一般教自己的专业
******* B
大家都应该去体验山区的生活
******* C
最好具备一些医学常识
******* D
各地招募志愿者的要求都一样
****** 答案
C
* 书写
** 第一部分
*** 29
**** 词语
***** 1
是
***** 2
每个人的
***** 3
促进
***** 4
义务
***** 5
社会进步
**** 答案
***** 1
促进社会进步是每个人的义务。
*** 30
**** 词语
***** 1
经常利用
***** 2
我们
***** 3
刘老师
***** 4
来指导
***** 5
空闲时间
**** 答案
***** 1
刘老师经常利用空闲时间来指导我们。
*** 31
**** 词语
***** 1
既温柔
***** 2
的人
***** 3
又体贴
***** 4
是个
***** 5
她丈夫
**** 答案
***** 1
她丈夫是个既温柔又体贴的人。
