* 练习

** 1
:PROPERTIES:
:ID: e59d9873-2ad2-4667-a2bc-3cf63323d1ff
:END:
*** 选择
**** 1
闯
**** 2
操心
**** 3
承担
**** 4
勇气
**** 5
建设
**** 6
温柔
*** 题目
**** 1
***** 句子填空
别怕因难，鼓起[[gap]]，你一定能成功！
***** 答案
4
**** 2
***** 句子填空
大家都很羡慕他有个[[gap]]体贴的妻子。
***** 答案
6
**** 3
***** 句子填空
昨天开车时精力不集中，[[gap]]子红灯。
***** 答案
1
**** 4
***** 句子填空
父母为我们[[gap]]了一辈子[[gap]]，现在该享福（xiǎngfú，to enjoy a happy life）了。
***** 答案
****** 1
操
****** 2
心
**** 5
***** 句子填空
毕业后的希望回去[[gap]]我的国家。
***** 答案
5
**** 6
***** 句子填空
这次活动的费用将由学校统一（tǒngyī，uniform, unified）[[gap]]。
***** 答案
3
** 2
*** 1
:PROPERTIES:
:ID: 75a039ed-f7eb-4a41-a5e8-ddced1649fc3
:END:
**** 句子填空
该准备的我们都已经准备了，你这么做完全是[[gap]]的。
**** 选择
***** A
多余
***** B
过分
**** 答案
A
*** 2
:PROPERTIES:
:ID: 5a5c7866-ba54-40cf-8861-d4f286cc342d
:END:
**** 句子填空
表面上弱小的人，很可能拥有你想象不到的巨大[[gap]]。
**** 选择
***** A
精力
***** B
力量
**** 答案
B
*** 3
:PROPERTIES:
:ID: fe206519-70c6-414d-b412-34d0d849aaf8
:END:
**** 句子填空
心理学家发现，性格[[gap]]的人的生活比其他人更丰富。
**** 选择
***** A
热烈
***** B
热情
**** 答案
B
*** 4
:PROPERTIES:
:ID: eef6e84d-ba1f-4ae9-98f9-66703220e5f4
:END:
**** 句子填空
我觉得他这并不是对你好，只是[[gap]]你。
**** 选择
***** A
用
***** B
利用
**** 答案
B
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
我都已经[[A]]安排[[B]]好了，你别[[C]]瞎[[D]]了！
**** 词语
操心
**** 答案
D
*** 2
**** 句子
看了她的舞蹈，大家都[[A]]鼓[[B]]起[[C]]来[[D]]。
**** 词语
掌
**** 答案
C
*** 3
**** 句子
[[A]]他[[B]]下班后的[[C]]时间参加[[D]]专业培训。
**** 词语
利用
**** 答案
B
*** 4
**** 句子
我会[[A]]最大的[[B]]力量[[C]]来[[D]]帮助你。
**** 词语
尽
**** 答案
A
* 扩展
** 词语
*** 话题
教学2
*** 词语
**** 1
测验
**** 2
实验
**** 3
抄
**** 4
试卷
**** 5
夏令营
**** 6
操场
**** 7
用功
**** 8
辅导
**** 9
收获
**** 10
铃
**** 11
退步
**** 12
改正
** 题目
*** 1
**** 句子
暑假时很多中小学生去外地或外国参加[[gap]]，又可以旅游又可以交朋友。
**** 答案
5
*** 2
**** 句子
这是上次考试的[[gap]]，请大家认真看一看错在哪儿。
**** 答案
4
*** 3
**** 句子
我想请一个家教，下课后[[gap]]我学习汉语。
**** 答案
8
*** 4
**** 句子
预习生词时，我会把不认识的字[[gap]]三遍。
**** 答案
3
* 注释
** （三）词语辨析
*** 发言——发表
**** 做一做
***** 1
****** 句子
我准备公开[[gap]]我的意见。
****** 答案
******* 1
******** 发言
0
******** 发表
1
***** 2
****** 句子
明天上课该轮到我[[gap]]了。
****** 答案
******* 1
******** 发言
1
******** 发表
0
***** 3
****** 句子
总裁，这是明天会议的[[gap]]，请您过目。
****** 答案
******* 1
******** 发言
1
******** 发表
0
***** 4
****** 句子
她年纪虽小，已经在杂志上[[gap]]过几首诗了。
****** 答案
******* 1
******** 发言
0
******** 发表
1
* 课文
** 转录
来云南支教一年多，郝琳硕老师自己也记不清有多少次家访了。刚到时，一位叫赵福根的男生引起了她的注意。他上课从不发言，很多课不及格，平时也几乎不和同学交往。
郝老师家访后得知，赵福根的父亲去世了，姐姐在外打工，他家里很穷，还得帮着妈妈做家务，是个体贴孝顺的孩子。“和他妈妈聊天才知道他很喜欢跳舞，”郝老师说，“我觉得这是个机会！”她鼓励福根在学校艺术节上表演，每周二带着他一起去找音乐老师排练。表演时，福根的蝴蝶舞得了舞蹈组的冠军，台下的同学们鼓起掌来，齐声地喊着“福根”的名字……
之后，赵福根学习用功了，成绩也逐渐进步。他写了一篇题目为《那天的舞蹈和掌声》的作文，得了全班最高分，他朗读了自己的作文：“郝老师来到我家，那是第一次有老师来。她非常温柔……我永远都忘不了那热烈的掌声和同学们送我的糖，甜甜的。我感觉在学校也有人爱我了我开始有勇气……”
郝老师发现，山里的青壮年都出去闯世界，只有老人、孩子留守，“他们出去了还回来吗？大山以后谁来负责”？于是，郝老师组织了一个8周的研究型学习活动，主题是“让家乡的明天更美好”。她鼓励学生寻找村子的问题，通过了解历史地理情况、采访村里的老人、小组讨论等，最终提出解决方案。她和其他志愿者利用午休、周末等空闲时间给学生们指导和培训。
学生们说：“以前，我们总认为建设家乡是大人的事，用不着我们操心。不过，现在我们明白了，建设家乡，人人有责，我们也要承担这个义务。这个任务很艰巨，我们要尽自己最大的力量。”
郝琳硕觉得自己的收获远多于给孩子们的。“不管以后在哪儿，我都会继续用我的力量影响山里的孩子们，因为他们是国家的未来与希望。”
