* 听力

** 1

*** 1

**** transcript

乐观的人会有些主观，有些“傻”。他们习惯于“歪曲”现实世界，当现实世界不利于他们发展或有些危险时，他们倾向于人为地忽视危险，不把危险放在心上，乐观地认为，天塌不下来，睡醒再说。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 09:07:04 -05]
:END:

Optimistic people will be somewhat subjective, some "silly". They are accustomed to "distort" the real world, when the real world is not conducive to their development or some danger, they tend to artificially ignore the danger, do not put the central what danger on top, optimistic that the sky is not falling, wake up and say.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

日记是孩子成长过程中的心得体会，未经许可，家长是不应该看的。文具店里装潢漂亮、挂着小锁的日记本往往特别受欢迎，就是因为买主写完后可以将日记锁起来，以防被人偷看。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 09:55:21 -05]
:END:

A diary is a child's experience of growing up and should not be read by parents without permission. The beautifully decorated diaries with small locks in stationery stores are often particularly popular because the buyer can lock them up after writing to prevent peeking.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

服饰文化在人类文明史中占有很重要的地位。事实上，在各种服饰文化表象的背后，不论这种服饰是光彩四溢、如诗如画，还是朴实无华、素净淡雅，都存在着各种与之对应的服饰观念。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 09:58:46 -05]
:END:

The culture of dress occupies a very important place in the history of human civilization. In fact. Behind the various cultural appearances of costume, whether the costume is glamorous, or simple, plain and elegant, there are various corresponding costume concepts.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

不要让对方认为你抹杀了他的一切，一点儿也不承认他的好处，这样很难使谈话融洽地进行下去。无论你的意见和对方的意见相差多远，冲突多厉害，都要表现出一切都可以商量的诚意。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 10:02:55 -05]
:END:

Do not let the other person think that you erase everything he has to offer and do not acknowledge his benefits at all, so it is difficult to make the conversation go on harmoniously. No matter how far your opinion differs from the other person's and how strong the conflict is, show the sincerity that everything is negotiable.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

万圣节也叫“鬼节”，起源于公元前5世纪，欢度万圣节的习俗由爱尔兰移民带到北美。万圣节前后，在儿童商场能买到各种魔鬼图案的化装衣服、帽子和脸谱，年龄大一些的孩子们还会自行设计魔鬼套装。

***** transcript
:PROPERTIES:
:CREATED: [2022-08-20 10:06:19 -05]
:END:

Halloween, also called "Ghost Day", started in the 5th century B.C. The custom of celebrating Halloween was brought to North America by Irish immigrants. Before and after Halloween, you can buy a variety of devil costumes, hats and faces in children's malls, and children of all ages will design their own devil suits.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: af86092e-9661-4a5f-b9dc-c47648e98a67
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：参加“我是歌手”，对你来说有挑战吗？
男：我不太会唱别人的歌，因为我以前都是唱自己写的歌。唱别人的歌是有挑战的，我的很多压力也来自于此。
女：人有的时候还是需要一点儿压力的吧？
男：对啊，就像有时候必须去考试一样。
女：说实话，以后你还会参加这样的节目吗？
男：不会了，这样的经历，一生有这么一次足矣，没必要总是做这样的事情。
女：这些年你还是有了点儿改变……
男：如果说成长和成熟是改变，那就是改变。
女：其实更多地在坚持？
男：坚持是不自觉的，我只想过做个歌手。也许我只适合做这类事，可以说这是坚持吧。别人看来是坚持，自己看来就是做喜欢的事。
女：好多人都是在就要忘了你之前，又被你的突然出现感动。你是怎么做到的？
男：在很多时候，你喜欢的未必别人喜欢，更未必被市场喜欢。但是，你喜欢的东西如果坚持做到底，把它做到极致，别人或者市场是有可能接受的。假如你做的东西既不是你喜欢的，又不是别人接受的，那么我觉得这样的事情做下去，是不可能有好结果的。
女：你对音乐市场有什么看法？
男：在我看来，做这行的没有什么人真正懂市场。每个人也就几首歌曲可以算是真正成功的……既然这样，为什么不做点儿自己真正喜欢的呢？做自己不喜欢的东西是很痛苦的，只有一种情况除外，那就是你本身根本不爱音乐，就是想成名，名利足够让你获得快感。
女：这算是你在 40 岁时候的感悟吗？
男：我的人生是相反的：30 多岁的时候我是不惑的，40 岁反而又困惑了。30 岁不惑源于自己对世界的未知；可到了 40 岁，真正了解一点儿社会之后，发现很多问题其实是无解的。世界无时无刻不在变化，哪来的什么答案？

**** 音频

c8aebc65-d3de-4ec9-be7a-feee08b46801.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: bb4d06a3-b311-4200-8904-520c06afa4f1
:END:

***** 问题

对参加“我是歌手”，男的是什么态度？

****** 音频

9e0b569d-0475-440a-b3b5-bf1ef37b9b31.mp3

***** 选择

****** A

兴奋

****** B

向往已久

****** C

不甚积极

****** D

像参加考试一样紧张

***** 答案

C

**** 7
:PROPERTIES:
:ID: 2a5e37d1-b7c1-427e-85f3-8d1f4898243a
:END:

***** 问题

关于男的，下列哪项正确？

****** 音频

a9564a6d-a1c2-4f42-99d9-a36e04e82ad3.mp3

***** 选择

****** A

越来越成熟

****** B

趁来越乐观

****** C

尝试过很多职业

****** D

受到鼓励才坚持下来

***** 答案

A

**** 8
:PROPERTIES:
:ID: c7187349-0924-4ee7-ab4c-ca5e48593798
:END:

***** 问题

男的认为，自己沉寂之后又能感动别人的原因是什么？

****** 音频

8c9debe0-4e1c-4618-b105-492851f19676.mp3

***** 选择

****** A

他学会丁顺应市场

****** B

社会从不缺少关怀

****** C

岁月不可能淹没美好的记忆

****** D

他坚持做好自己喜欢的东西

***** 答案

D

**** 9
:PROPERTIES:
:ID: f7fad761-ccca-4eb9-93d4-8e1a2765aac6
:END:

***** 问题

对音乐市场，男的怎么看？

****** 音频

75db9525-ccfb-40a0-b79a-953a079fe28b.mp3

***** 选择

****** A

成功的歌手每一首歌都很成功

****** B

只有不断学习才能了解音乐市场

****** C

真正娆音乐的人会做自己喜欢的东西

****** D

歌手在音乐市场中扮演着痛苦的角色

***** 答案

C

**** 10
:PROPERTIES:
:ID: a61392f8-fa0b-4b6d-abcf-70b45559c8b8
:END:

***** 问题

男的 40 岁时有什么感悟？

****** 音频

5e1debbd-7ecf-4d76-86df-6eb46f167212.mp3

***** 选择

****** A

年轻时思想更开阑

****** B

 40岁的人更趋于保守

****** C

 30岁犯错误也在情理之中

****** D

世界在变化，很多事没有答案

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

乐观的人有时会忽视危险

***** B

乐观的人经常会做些傻事

***** C

有人认为睡觉比什么都重要

***** D

天塌下来表示危险即将来临

*** 2

**** 选择

***** A

有思想的孩子才记日记

***** B

家长都喜欢看孩子的日记

***** C

孩子的日记是写给自己的

***** D

家长喜欢漂亮的有锁的日记本

*** 3

**** 选择

***** A

服饰文化的历史不长

***** B

素净淡雅的服饰如诗如画

***** C

美丽的服饰能制造出非凡的效果

***** D

每种服饰文化都体现着相应的观念

*** 4

**** 选择

***** A

要善于发现别人的优点

***** B

人与人存在分歧很正常

***** C

与人发生冲突时要冷静

***** D

与人谈话态度诚恳很重要

*** 5

**** 选择

***** A

爱尔兰先于北美过万圣节

***** B

大家喜欢自制万圣节服装

***** C

一般商场都会卖魔鬼服装

***** D

万圣节始于大约1500年前

