* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 9f781689-6327-4555-bd6c-af6c2bfd95f7
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
eb517b97-7100-44eb-80d2-98049e4531c7.mp3
***** 转录
宋末政治家、文学家、爱国诗人文天祥被关在牢房里，恶劣的环境只能折磨他的身体，却不能摧毁他的意志。就是在这间牢房中，文天祥写下了千古传诵的《正气歌》。
**** 选择
***** A
文天祥身体不好
***** B
文天祥神拜英雄
***** C
《正气歌》流传久远
***** D
文天祥生活的地方气候恶劣
**** 答案
C
*** 2
:PROPERTIES:
:ID: b71a0f76-9da0-4b1a-ab9b-9b47577f7f17
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fc299850-1ec2-49fa-9122-c7dadaa29aab.mp3
***** 转录
博客从某个方面来说，已经不是一个私人圈子，而更像是一个言论堂，一个发表观点的地方。一般来说，博客谈论的是社会热门话题。其实，是先有论坛，后来因为用户想有自己的小天地，所以才产生了博客。
**** 选择
***** A
博客和论坛没有区别
***** B
博客只给小圈子的人看
***** C
博客是用户自己的小天地
***** D
博客之后，论坛也随之兴起
**** 答案
C
*** 3
:PROPERTIES:
:ID: fdb81a3f-c3f8-4b0c-abb5-bf1c4fa4149b
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
81ae41a4-e5ae-45fc-96fb-0bb4a421bfae.mp3
***** 转录
汽车司机在封闭的高速公路上驾驶汽车时，基于合理信赖相信行人不会横穿公路，如果行人违反交通规则横穿公路而被正常行驶的汽车撞死，该汽车司机不承担过失犯罪的刑事责任。
**** 选择
***** A
行人横穿公路被撞，司机没有责任
***** B
司机在封闭的高速公路上驾车是受保护的
***** C
司机撞人至死都要承担过失犯罪的刑事责任
***** D
司机相信行人不会横穿封闭高速公路的想法合理
**** 答案
D
*** 4
:PROPERTIES:
:ID: 7aae6043-3ff7-4316-b832-f858ce612a9b
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
3b696423-77e5-446c-b92d-d124ea4f1b90.mp3
***** 转录
谈起李敖，无论是他的敌人还是朋友都不得不承认他是一位奇人，他几十年来口诛笔伐、特立独行，坐过六年牢，打过几十场官司，一共有九十六本书被禁，创下了历史记录，但同时他又是千万人心中的偶像。
**** 选择
***** A
李敖是一位律师
***** B
李敖的心中也有偶像
***** C
李敖是一位公认的奇人
***** D
李敖一生都在努力创纪录
**** 答案
C
*** 5
:PROPERTIES:
:ID: 58099c90-62af-4c77-94a4-c2fb8909d308
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
10148391-5faf-48f9-a8c9-708b122077e3.mp3
***** 转录
在超市打工期间，她边打工，边读书，穿梭于校园和工作单位之间。她逐渐学会了如何最大限度地利用一天 24 小时的有限时间，如何面对工作考核和学校考试的双重压力，如何从容完成一个接一个的作业和论文。
**** 选择
***** A
她平常不在学校就在超市
***** B
她打工也并没有耿误学业
***** C
她在超市也会抽时间看书
***** D
她感到一天24小时不够用
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: cf24e400-3fb5-4000-9d47-dc0766f86685
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
6f6c7ea6-914b-4df4-8539-0af885e1fff5.mp3
***** 转录
女：您的网上书店开业以来，销量和好评率一直很稳定，您还开有实体书店。我们想知道，您是怎么与书结缘的？
男：与书结缘，是从少年时代开始的。那时家境贫寒，新书买不起，就打旧书的主意。80 年代初，小镇上有租连环画的摊子，一分钱，两分钱，就可以租看一本，我整天坐在小板凳上，慢慢品味，这种美妙的享受让我对书十分有感情。上学以后，我周末去的最多的地方就是书店。
女：那您最开始开书店和这份书缘有关？
男：是啊，那也算是我人生一个小小的转折点。那时我在南方打工，一个老乡知道我喜欢看书，告诉我去废品收购站可以买到非常便宜的旧书。我由此得到启发，决心开二手书摊。
女：您后来开了实体书店，卖的也是二手书吗？
男：对，我的书店不卖新书，只卖各种门类的二手书，这样一来，在售价上就比较有优势。当然，也不仅仅是价格优势，许多早年出版的书，在图书城是很难买到的，而在旧书店却有可能淘到。
女：您对深圳的状况很熟悉，能不能给我们说说那里古旧书的情况？
男：大家都知道，深圳是一座年轻的城市，是中国改革开放建立的第一个经济特区。深圳的古旧书市场并不是很理想，这大概与这座城市的年龄有关。但深圳二手书货源却相当充足，这也给我开设实体书店提供了帮助。如果我们把古旧书仅仅定义为多少年多少年以前的老书，那深圳的“货源”的确是个大问题，但如果把二手书都当作旧书来经营，深圳的货源充足到一听到有人打电话让我去收书，我就头痛，因为收回来没地方放，店租实在涨得太快，这也是我经营中最大的难题。
女：感谢您给我们讲了这么多有趣的事情，衷心祝愿您的书店越办越好！
**** 题目
***** 6
:PROPERTIES:
:ID: d631cd9e-b7a0-45da-a3b8-4ccbaeead129
:END:
****** 问题
******* 音频
048556f2-2bf8-4268-977d-fce862557b12.mp3
******* 转录
男的是怎样与书结缘的？
****** 选择
******* A
从小对书就有感情
******* B
家里开了连环画摊
******* C
小时候买书很便宜
******* D
上学时在书店打工
****** 答案
A
***** 7
:PROPERTIES:
:ID: ae920c93-605e-4615-9786-5579c03b237f
:END:
****** 问题
******* 音频
c203e5d9-0f7a-450a-b010-dd5545399e69.mp3
******* 转录
男的在南方打工时发生了什么事情？
****** 选择
******* A
遇到了开书摊的老乡
******* B
在老乡的启发下开了书摊
******* C
老乡给他介绍了书店的工作
******* D
收废品时发现旧书可以敞开收
****** 答案
B
***** 8
:PROPERTIES:
:ID: 0b7d11f0-27ea-489d-94b5-53431074dd52
:END:
****** 问题
******* 音频
9f804417-9bf5-424a-a625-045134c88529.mp3
******* 转录
男的开的实体书店有什么特色？
****** 选择
******* A
书的进价很贵
******* B
书店制度完备
******* C
销售人员态度好
******* D
全部经营二手书
****** 答案
D
***** 9
:PROPERTIES:
:ID: b0d9d4ab-8aac-47ae-873a-88f858fa8b33
:END:
****** 问题
******* 音频
9fa5efc5-b180-4c23-8f89-890bbb5ab500.mp3
******* 转录
深圳是个什么样的城市？
****** 选择
******* A
深圳是个厚重的城市
******* B
深圳的历史不够久远
******* C
深圳能激发读书的激情
******* D
深圳的二手书货源不多
****** 答案
B
***** 10
:PROPERTIES:
:ID: 55641d59-5cc1-4975-8aa9-8f2830d6b896
:END:
****** 问题
******* 音频
00866bc5-2b69-4ef2-997a-50702c43b5b7.mp3
******* 转录
关于男的，下列哪项正确？
****** 选择
******* A
男的很受读者的爱戴
******* B
男的打工时收过废品
******* C
男的卖的书价格便宜
******* D
男的专卖古旧连环画
****** 答案
C
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 0bd043ce-2f49-4ec0-a17a-b361d2bb789b
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
f8442d1a-abc6-483f-909a-7dff75183b87.mp3
***** 转录
未来学校在时空上肯定会发生变化，无时不可学，无处不可学；未来学校的办学理念会进一步更新，学校对儿童会有全新的认识，儿童和成年是否依然二元对立就很值得怀疑，儿童是积极的社会行动者，童年是一种文化的、社会的、历史的建构，更是自然、文化、技术等异质因素的复杂产物；未来学校的技术变革将是几何级数的，“互联网+课堂” “互联网+教学”“互联网+德育”等，已经不可回避。未来学校的结构也将发生很大的变化，这也是毫无异议的，所以，学校必须选择结构变革。
**** 题目
***** 11
:PROPERTIES:
:ID: d07a5c90-1ca7-41b0-8ed0-ce0bf90441d6
:END:
****** 问题
******* 音频
ee89fbc3-c198-444a-b1a5-7c6707ea0827.mp3
******* 转录
未来学校在时空上会发生怎样的变革？
****** 选择
******* A
学校不再有围墙
******* B
学校可容纳更多学生
******* C
学校可以随时招收学生
******* D
学生想学习随时就能学习
****** 答案
D
***** 12
:PROPERTIES:
:ID: f044d92e-ce66-4336-90e8-f385b294294d
:END:
****** 问题
******* 音频
c140773e-6a01-45ee-84ee-b9a875afc717.mp3
******* 转录
未来学校在办学方面将会发生怎样的变化？
****** 选择
******* A
教学方法将更加规范化
******* B
教学目的是重建学生的童年
******* C
儿童和成年人可以一起学习
******* D
现在对儿童的认识或许会被颠覆
****** 答案
D
***** 13
:PROPERTIES:
:ID: 25be913b-9059-41ec-8e60-f70004c711ca
:END:
****** 问题
******* 音频
fc33e1b0-85e2-48f5-9039-05d8f785188b.mp3
******* 转录
关于未来学校的技术革命，下列哪项正确？
****** 选择
******* A
计算机课会更受重视
******* B
彻底抛弃实体课堂教学
******* C
完全利用互联网治理学校
******* D
技术方面的变化会是最大的
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: 6948fc3c-7889-4bb9-a25e-03de38a4f309
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
70f635f5-ea04-496f-bc37-0f279d6bdae8.mp3
***** 转录
如今，一年 365 天中随便哪个日子，你在吃、穿、住、用，不管哪个方面，都能随心所欲地挑选自己喜欢的颜色。在古人看来，这是不可想象的。
周朝典籍中有“衣正色，裳闲色”的记载，古时“衣”指上衣，“裳”指下裙；所谓“正色”，指青、赤、黄、白、黑五色，“闲色”与“正色”相对，指绿、红、碧、紫、褐黄五色。由此可知，周朝，人们对上衣、下衣颜色的选定是有要求的。
之后，秦始皇成了黑色服饰、建筑等的代言人，汉武帝是选定了黄色的第一人。秦始皇、汉武帝虽然喜欢黑色、黄色，却并没有独霸，到了唐朝，情况有了改变。《新唐书》记载：唐朝开国皇帝李渊多穿用黄色的袍衫，并逐渐禁止臣民穿用。到了公元 668 年，唐高宗颁布圣旨：官民一律不许穿黄衣服、住黄房子。截止到清朝灭亡的 1000 多年里，黄色一直是帝王家专用之色。
**** 题目
***** 14
:PROPERTIES:
:ID: cdb3c7a0-697d-4df1-9b7f-4c7d2d218305
:END:
****** 问题
******* 音频
3ba15577-ff8d-4a70-980d-4367c958a376.mp3
******* 转录
关于今人选用颜色，下列哪项正确？
****** 选择
******* A
没有任何限制
******* B
不需要任何标准
******* C
人的想象力较差
******* D
不像古人那么保守
****** 答案
A
***** 15
:PROPERTIES:
:ID: 664d56ca-fc44-4494-80a1-13ede5761d68
:END:
****** 问题
******* 音频
fd46d28d-c838-4a61-82f0-c9814548d0f8.mp3
******* 转录
关于周朝，下列哪项正确？
****** 选择
******* A
休闲装有休闲装的颜色
******* B
“衣“与“裁“是同义的
******* C
“衣“裁“颜色有讲究
******* D
人们不太遵守当时的礼节
****** 答案
C
***** 16
:PROPERTIES:
:ID: d0d21806-2285-4fd0-9ecc-29501334fbe2
:END:
****** 问题
******* 音频
1ba30052-fc5d-4328-96f8-7b9890c268f0.mp3
******* 转录
关于秦始皇，下列哪项正确？
****** 选择
******* A
给黑色做广告
******* B
喜欢黑色建筑
******* C
是第一个选定黄色的皇帝
******* D
禅止百姓使用黑色、黄色
****** 答案
B
***** 17
:PROPERTIES:
:ID: 75738165-6f04-40c0-b99a-71918aa10ee0
:END:
****** 问题
******* 音频
ce360748-2aac-4a46-85dd-18527ae1c0fd.mp3
******* 转录
关于唐朝，可以知道什么？
****** 选择
******* A
哥朝第一位皇帝是李溶
******* B
唐朝百姓的房子黄色居多
******* C
唐朝允许官员穿黄色衣服
******* D
唐朝一开始就只有皇帝能用黄色
****** 答案
A
* 阅读
** 第一部分
*** 18
**** 句子
***** A
他的行为遭到众人的唾弃。
***** B
无论我题没做完，但是我做完的全对，我还是全班第一名。
***** C
卑鄙小人总是忘恩负义的，忘恩负义原本就是卑鄙的一部分。
***** D
原以为这仅仅是一段异国就职经历，不料却陷人了一场海外生存的较量之中。
**** 答案
*** 19
**** 句子
***** A
如今，家长不能再以门当户对为由粗暴地干涉儿女的婚姻自由。
***** B
受过高等教育的他，常混迹于不三不四的人之中，真是自甘晰落！
***** C
这些彩绘玉器既有商周图案，汉唐纹饰，体现了华夏民族的艺术风格。
***** D
那位同学演奏小提琴所达到的完美境界，是很多艺术家都不能达到的。
**** 答案
*** 20
**** 句子
***** A
谁能知道，隐藏在战火纷飞的前线和厚颜无耻的面具后面的敌人，究竟脆骏到什么程度？
***** B
每次开始攀登珠峰之前，都要举行一项仪式，在仪式中夏尔巴人会表达他们对山神的神敬之情。
***** C
时间如风，轻柔地驶过不留一丝痕迹；时间如光，明媚地照下，却无处追寻；时间如水，永无终止地流渊，不分星夜。
***** D
NHS去年发表在官网上的忠告称，“趁来越多的证据”把久坐与肥胖、2型糖尿病、桅些种类的癌症以及早逝关联起来。
**** 答案
** 第二部分
*** 21
**** 段话
她[[gap]]出现，便叫人难以忘怀。她似乎比一般女人更懂得理性思维，而日更聪明[[gap]]，遇事不张扬，[[gap]]刚柔相济，有着知性的魅力。
**** 选择
***** A
****** 1
刚刚
****** 2
可爱
****** 3
且
***** B
****** 1
突然
****** 2
崇高
****** 3
还
***** C
****** 1
按时
****** 2
完美
****** 3
并
***** D
****** 1
当众
****** 2
美丽
****** 3
故
**** 答案
*** 22
**** 段话
墨家的创始人墨子，在春秋战国时期处于显学的[[gap]]。墨子[[gap]]强烈的救世匡时的[[gap]]，从实用主义的立场出发，考虑社会问题，提出一系列政治和伦理[[gap]]。
**** 选择
***** A
****** 1
位置
****** 2
立足
****** 3
心愿
****** 4
主意
***** B
****** 1
身份
****** 2
倡议
****** 3
理想
****** 4
观点
***** C
****** 1
地位
****** 2
本着
****** 3
愿望
****** 4
主张
***** D
****** 1
职位
****** 2
发扬
****** 3
志向
****** 4
看法
**** 答案
*** 23
**** 段话
随着全球科技、经济的[[gap]]发展，在物质财富极大提高的同时，人们的生活质量与精神追求却[[gap]]落后，负面心理[[gap]]，而传统心理学许多理论[[gap]]只把人当作动物或机器，而忽略了人内在的潜力和主动性。
**** 选择
***** A
****** 1
火速
****** 2
往往
****** 3
司空见惯
****** 4
大概
***** B
****** 1
健康
****** 2
显然
****** 3
不足为奇
****** 4
恐怕
***** C
****** 1
全面
****** 2
分外
****** 3
比比皆是
****** 4
一概
***** D
****** 1
迅速
****** 2
相对
****** 3
层出不穷
****** 4
似乎
**** 答案
** 第三部分
*** 段话
西方学校的第一次变革始于17世纪。这时，欧洲正处于从封建制度向资本主义过渡时期。随着手工业生产的发展和生产技术的革新，[[gap:24]]，近代自然科学体系开始形成，各种新的思想和方法不断涌现。17世纪40年代，英国爆发了资产阶级革命，[[gap:25]]，宣告了欧洲新社会政治制度的诞生。与此同时，关心生产力提高的新兴资产阶级也需要科学的帮助，促进自然科学的发展。因此，17世纪欧洲的时代精神、社会生产力的发展以及平民群众对文化教育的普及需求，[[gap:26]]。
但是，无论在学校管埋制度上，[[gap:27]]，当时欧洲的学校都无法漾足时代和社会的需要。学校不是为整个社会设立的，而是为富人设立的；学校的教学不是有序的，而是混乱的。本来应当清晰的和条理分明的讲授却被混乱的和复杂的讲授所取代，[[gap:28]]，而东体罚、殴打学生的现象也十分普遍，所有这些，都成为教育变革的催化剂。
*** 选择
**** A
近代自然科学知识得到了更为迅速的发展
**** B
使学生好像是走人了知识迷客
**** C
都使得已具有几干年历史的西方学校面临着变革
**** D
揭开了欧洲资产阶级革命的序幕
**** E
还是在学校课程内容和教学方法上
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
家庭教育一般指家庭中父母及其他成年人对未成年孩子进行教育的过程。其教育目标是：在孩子进人社会接受集体教育之前保证孩子身心健康地发展，为理解幼儿园、学校的教育打好基础。家庭教育具有以下两大特点：
第一是家庭教育的早期性。家庭是人出生后接受教育的第一个场所；家长是儿童的第一任教师，因此家长对儿童进行的教育具有早期性。一般来说，孩子1一3岁为幼儿时期，3一6岁为学龄前期，也就是人们常说的早期教育阶段，这是人身心发展的重要时期，人的许多基本潜质是这个年龄阶段构成的，如语言表达、性格形成等。有心理学家认为，一个人的智力发展，如果把17岁到达的水平算作100％，那么4岁时就到达了50％，4一8岁又增加了30％，8一17岁又获得了20％6。可见幼儿在5岁之前是智力发展最迅速的时期，家长能吞在这个时期给孩子良好的家庭教育，将是孩子早期智力发展的关键。
第二是家庭教育的连续性。挂子从小到大，几乎2/3的时间生活在家庭之中，朝朝暮暮，都在理解着家长的教育。这种教育是在有意和无意、计划和无计划、自觉和不自觉之中进行的。家长的生活习惯、道德品行、谈吐举止等在不停地给孩子以影响和示范，其潜移默化的作用相当大。这种教育往往反映为一个家庭的家风，家风的好坏往往要延续儿代人，甚至十儿代人、儿十代人。
基于以上两点，侗家庭教育成为教育人的起点与基点，具有其他教育所不及的优势。
**** 题目
***** 29
****** 问题
家庭教育指：
****** 选择
******* A
成年人教育未成年人
******* B
父母等教育未成年子女
******* C
孩子上学之前的教育
******* D
对幼儿开展的集体教育
****** 答案
***** 30
****** 问题
关于“家庭教育的早期性”，下列睇项正确？
****** 选择
******* A
人的智力发展越来越快
******* B
3一6岁的孩子最有潜力
******* C
家长越早给挂子请老师越好
******* D
5岁前最适合孩子的智力开发
****** 答案
***** 31
****** 问题
关于“家庭教育的连续性”，下列睑项正确？
****** 选择
******* A
家庭教育的2／3是连续完成的
******* B
家庭教育是自然的，无需计划
******* C
家长的所作所为很容易影响子女
******* D
家风的形成需要好几代人的努力
****** 答案
***** 32
****** 问题
最后一段画线词语“不及”的意思是：
****** 选择
******* A
来不及
******* B
不合格
******* C
比不上
******* D
不及时
****** 答案
*** 33-36
**** 段话
司马迁的家乡在黄河边上，那里山峦起伏，河流奔腾，风景十分壮美，这条中华民族的母亲河滋养了幼年的司马迁。司马迁从小就帮家里干活，种田、放牧牛羊，十分勤劳。在父亲的严格管教下，司马迁10岁就能阅读古代史书，他边读边做摘记，不懂的地方就请教父亲。小小年纪的他，读道了有影响的史籍，并立志要做一名史学家。
父亲虽然忙，对司马迁读书却是有要求的。一天，父亲把司马迂叫到跟前，指着一本书说：“这几个月，我公务缠身，抽不出空来教你。你自己读这本书吧。”司马迂看了看那本书，说：“这本书我读过了”说着就把书从头至尾一字不差地背了一道。父亲很奇怪，难道世界上真有神童！第二天，父亲偷偷跟在出门放羊的司马迁后面。翻过小山，过了河，来到一片水草丰美的洼地，司马迁把羊群赶到草地中央，羊开始吃草后，他从怀中捧出一本书认真读起来，父亲恍然大悟。
20岁起，司马迂开始到各地游历，考察历史和风土人情，这为他日后编写史书提供了充足的史料。做太史令后，他常跟随皇帝到处巡游，又搜集了大量的历史资料，还了解到统治集团的许多内幕。为官期间，他如饥似渴地阅读宫廷收藏的大量书籍，收集了不少珍贵史料。
就在他撰写《史记》的时候，因为替李陵说情，触怒了皇帝，被关人监狱，判处了重刑。司马迁出狱后继续写作，经过前后10年的艰苦努力，终于写成了《史记％这部巨著，对后世史学与文学都产生了极为深远的影响。
**** 题目
***** 33
****** 问题
根据第1段可以知道，司马迁：
****** 选择
******* A
在劳动中锻炼了坚强的意志
******* B
从小深受黄河文化的影响
******* C
家里穷得只能跟父亲学习
******* D
从小就熟悉历史热爱历史
****** 答案
***** 34
****** 问题
关于司马迁读书，下列睇项正确？
****** 选择
******* A
父亲对司马迁要求很高
******* B
司马迁读书只限于胡诵
******* C
父亲忙得没时间过问司马迁
******* D
司马迁的读书方法与父亲有分歧
****** 答案
***** 35
****** 问题
司马迁20岁以后：
****** 选择
******* A
边旅游边撰写史书
******* B
在皇帝身边做官了
******* C
了解了为官的不易
******* D
得到了官方的资助
****** 答案
***** 36
****** 问题
根据第4段可以知道：
****** 选择
******* A
李陵也是太史令
******* B
《史记》的内容让皇帝非常生气
******* C
司马迁在皇帝面前替李陵说话
******* D
司马迁出狱后又写了10年《史记》
****** 答案
