* 课文
** 转录
中国藏书的历史很长，有 2000 多年了，有官方藏书，也有私人藏书。唐代有人把藏书的地方称作书院，之后各种书院层出不穷，甚至有人把自己的书屋也命名为书院。
时光流转，书院渐渐发展成了藏书、教学和研究相结合的教育机构。比如，东佳书院就是中国书院史上最早拥有学田、订有规章制度、收有学生的私办书院。它前后存在了千余年，名字更换了三四次，截止到清朝末年，书院制度终止，东佳书院改成了学校。可以这样说，萌芽于唐，完备于宋，废止于清的东佳书院是中国书院制度的一个缩影。
历史上的书院立足于人才培养。它把灵魂塑造看得和学问同等重要；提倡刻苦、严谨的治学精神；努力实践自由活泼的办学宗旨。书院的历史是中国古代教育史上的一份珍贵遗产。
德业并重是书院自始至终的追求目标。翻开各时代书院颁布的《学规》就能发现，书院重视学问，更重视品德修养。比如，丽泽书院《学规》第一条大意是：凡是本书院的学子，都要孝顺长辈，敬爱兄长，为人忠诚，守信用。不顺从长辈，和兄弟不友善，与人不和睦，对朋友不忠诚，言行不一，擅以虚伪的言辞掩饰过失的无耻之徒，一经发现，本书院定不容纳。短短一段文字透露出这样的信息：书院在人文环境的治理上是有标准的，那就是树立正气，唾弃卑鄙、堕落的腐败行为。因此，有学问、有道德、有崇高的境界，就成为了古代知识分子立志终生攀登的道德高峰。
提倡刻苦、严谨的治学精神是古代书院的共同特点。古代书院学术思想各有不同，但治学态度却极为相似，认为读书没有窍门，没有捷径，唯有发扬勤奋好学的精神，扎扎实实，一步一个脚印，才能做好学问。在学习方法上，提倡读书成诵，因为“书读百遍，其义自见”“；提倡温故知新”；提倡博学求精“；提倡读书须有疑”。
书院在办学方法上，努力实践自由活泼的办学思想。首先，书院本着贫富平等的原则，敞开大门，招收平民子弟入学，这在当时碧实是令人震撼的开明之举。其二，书院重视自修和研究，在读书的过程中倡议自行思考，杜绝外来因素的干涉，也不会过多过问，以便开发学生的自主学习能力，激发学生的主动性和创造性。其三，鉴于一个人的知识是有限的，大家的知识是无限的，个人解决不了的问题，在众人的智慧面前就不是问题，书院倡导互相切磋、互相学习。其四，鼓励师生之间相互质疑，形成探讨争辩、求真求实的学习风气。另外，重视观点的多元化，开展不同观点的论辩、交流，也是书院提倡的。观点对立、有分歧不要紧，开放、保守也无关紧要，书院主张不同学派、不同主张之间的争辩与较量，为此书院设立了讲演辩论制度，类似今天的“论坛”。这种学术活动很受欢迎，学子们学习热情高涨，相互激励，取长补短，共同进步。
书院讲究长幼，注重礼节，但不拘泥；主张刻苦自励，自主学习，却又鼓励相互质疑、辩论。书院内师生关系融洽，感情深厚，学生衷心爱戴名师，因为他们学识广博，品德过人，给学生做出了最好的示范，是学生崇敬的偶像。
书院对中国封建社会教育、学术的发展，产生过重要影响。
