* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: f7da913f-9b05-4232-ba64-9b73dfe5872a
:END:
**** 对话
***** 转录
男：上海的那批货准备得怎么样了？时间可别耽误了。[[file:1136eec7-8e0d-443c-805f-0aee7a97d031.mp3][(audio)]]
女：您放心，小李他们这两天都在加班，保证按合同要求的日期发货。[[file:c91c6d15-6270-433f-a122-d0eeca2d47e9.mp3][(audio)]]
***** 音频
e40aa979-7205-49d3-ba23-d30804f73ce5.mp3
**** 问题
***** 转录
关于那批货，可以知道什么？
***** 音频
6e1e1dde-b505-4ef5-85aa-d535f339c511.mp3
**** 选择
***** A
合同的问题
***** B
已经到上海
***** C
能按时发货
***** D
路上耽误了
**** 答案
C
*** 2
:PROPERTIES:
:ID: 659ffbef-857c-452c-8513-2e1c76bc24d9
:END:
**** 对话
***** 转录
男：喂，你现在在宿舍吗？[[file:5e8cc1ae-3095-4d95-9dc5-9befc0e266ac.mp3][(audio)]]
女：我刚下课，正要去图书馆查一份资料，有什么事儿吗？[[file:8d825106-795d-458a-bc6d-5332f02a93da.mp3][(audio)]]
***** 音频
61c50f19-8ae1-4b19-8751-051d43273e79.mp3
**** 问题
***** 转录
女的现在准备做什么？
***** 音频
27936122-a1ae-4762-844a-a37d17afbaf8.mp3
**** 选择
***** A
去查找资料
***** B
去超市购物
***** C
去教室自习
***** D
回宿舍休息
**** 答案
A
*** 3
:PROPERTIES:
:ID: 1b8618b2-cf7a-4f68-b4c9-624c123af654
:END:
**** 对话
***** 转录
女：平时你要是能多关心一下孩子，他肯定也不至于考不及格吧？[[file:e23c2dcc-9251-42b0-9003-dfc0cdad9de1.mp3][(audio)]]
男：这怎么能都怪我呢？你这当妈的也有责任啊。[[file:c93a3d5d-e4f1-4dc1-96c6-45fa93e9297f.mp3][(audio)]]
***** 音频
d698f82e-582b-4764-8a0e-5220d873f709.mp3
**** 问题
***** 转录
从他们的谈话中，可以知道什么？
***** 音频
1fbc6139-5a32-4e9c-8131-527998ac9357.mp3
**** 选择
***** A
男的工作很忙
***** B
女的非常惭愧
***** C
孩子成绩不好
***** D
两人经常吵架
**** 答案
C
*** 4
:PROPERTIES:
:ID: 4e91da50-47a1-4988-96f5-f89c6bab6ff7
:END:
**** 对话
***** 转录
男：总算弄好了，真把我累坏了。[[file:c8094bb8-86da-4903-8671-d8f937978586.mp3][(audio)]]
女：快休息休息，没想到这么个小桌子安装起来还挺麻烦。[[file:58ac283f-dd64-4a54-9601-cd605bdbb5c1.mp3][(audio)]]
***** 音频
0998805d-b536-4a03-8885-835e6f7fe720.mp3
**** 问题
***** 转录
关于男的，可以知道什么？
***** 音频
1b30388f-f7bc-4cf1-8dd0-c1f89c43c171.mp3
**** 选择
***** A
不想休息
***** B
病快好了
***** C
很怕麻烦
***** D
干活儿累了
**** 答案
D
*** 5
:PROPERTIES:
:ID: 70ecb9dc-54b4-4cb8-889b-329349c24038
:END:
**** 对话
***** 转录
女：欢迎光临，本店五周年店庆，所有商品一律 5 折销售。[[file:7faa536e-5544-4372-80cc-4faffe6779b6.mp3][(audio)]]
男：我想给孩子买双网球鞋，这种有 42 号的吗？[[file:a12d6e89-a1f4-44d4-9b9c-2d5a29a323fd.mp3][(audio)]]
***** 音频
35544a27-fe98-496d-bcae-6220c23e5034.mp3
**** 问题
***** 转录
从对话中可以知道什么？
***** 音频
033c2a51-d63f-46a0-9883-7a9b0612106c.mp3
**** 选择
***** A
网球鞋半价优惠
***** B
女的有一个孩子
***** C
男的要的鞋没货
***** D
男的穿 42 号鞋
**** 答案
A
*** 6
:PROPERTIES:
:ID: 68fa18b6-e237-4eb2-9cc0-bbf2ec1a8f60
:END:
**** 对话
***** 转录
女：王总，这是您的机票，是往返的。[[file:a9a2a8ca-937f-4dcf-a82b-2ccc5a28e74d.mp3][(audio)]]
男：好的，谢谢。这两份合同我签过字了，你给销售部的刘经理送去吧。[[file:8ff8eeb1-4cb8-4820-b62f-10b17a7a91e4.mp3][(audio)]]
***** 音频
49b7ead9-99e7-4361-9a26-76ce0a5fdeeb.mp3
**** 问题
***** 转录
从对话中可以知道什么？
***** 音频
01e1159e-5630-4467-a39b-238e2a200bb0.mp3
**** 选择
***** A
刘经理订了机票
***** B
王总批准了合同
***** C
女的是销售部的
***** D
女的要出门旅行
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
男：这个书架我怎么装不上呀？
女：你是按说明书上的步骤安装的吗？
男：是啊，有个零件我看不懂它装在哪儿，说明书上说得不清楚。
女：那你给卖家打个电话问问。
***** 音频
11c8876f-f7a1-467b-86b8-760bf631e01d.mp3
**** 问题
***** 转录
男的为什么装不上书架？
***** 音频
b0951622-1fdf-4298-99ec-d3f3b0c45607.mp3
**** 选择
***** A
安装步骤错了
***** B
少了一个零件
***** C
说明书不详细
***** D
卖家发错了货
**** 答案
C
*** 8
**** 对话
***** 转录
男：你们家小雪的作业要做到几点？
女：吃晚饭前就完成了呀。现在学校不让留太多作业。
男：我们家小明每天都要做到十点钟。
女：那可不对，你要注意培养他的专注力，要提高效率。
***** 音频
8670b8c1-6c60-4ce9-9fe6-f6b5b1687250.mp3
**** 问题
***** 转录
小明作业做到很晚，女的觉得是什么原因？
***** 音频
dfe0c424-a843-4d2a-b7c4-1ba402bd9e7b.mp3
**** 选择
***** A
没有家人辅导
***** B
作业留得太多
***** C
脑子不够聪明
***** D
做作业不专心
**** 答案
D
*** 9
**** 对话
***** 转录
女：真不好意思，耽误了您这么长时间。
男：别这么说，亮亮的学习也离不开家长的关心和督促。
女：非常感谢！让您费心了。
男：您太客气了，感谢您对我们学校工作的支持和配合。
***** 音频
8d7879c7-f958-4f9d-adeb-ee7ec58ee70e.mp3
**** 问题
***** 转录
男的最可能是亮亮的什么人？
***** 音频
3d9adbbc-3f10-4a89-86e9-469575e43775.mp3
**** 选择
***** A
家长
***** B
老师
***** C
医生
***** D
朋友
**** 答案
B
*** 10
**** 对话
***** 转录
男：最近眼睛看东西总感觉模模糊糊的，是不是老花眼了？
女：你才多大就老花眼？
男：我们同事刚 45，眼睛就花了。
女：我觉得你最近写东西弄得太晚了，少看会儿电脑就好了。
***** 音频
efdaec5f-75c6-4f83-8546-d80c5552218a.mp3
**** 问题
***** 转录
女的觉得男的的眼睛是什么问题？
***** 音频
45856c01-dfbf-4ebd-a215-336418934163.mp3
**** 选择
***** A
疲劳了
***** B
老花丁
***** C
发炎丁
***** D
眼镜不合适
**** 答案
A
*** 11-12
**** 对话
***** 转录
有一位酿酒师，经过长期的努力，酿制出了一种口感独特的葡萄酒，起名叫“赤玉”。但他做不起广告，酒的销路非常不好。情急之下，他想了一个办法，就是每天晚上到各个卖酒的商店去买赤玉葡萄酒。得到的回答当然是“没有”，这时，他热情地说：“没关系，等你们进了货，我再来买。”随着询问次数的增多，许多店家开始关心这种酒，并打听哪里能进到货。赤玉葡萄酒由此打开了销路。这则故事告诉我们一个道理：当你无法解决一个问题时，积极变换思路，从其他角度去想，眼前就会豁然开朗。
***** 音频
7fc2ee1b-c4e9-489c-b31c-2a5c2135283d.mp3
**** 题目
***** 11
****** 问题
******* 转录
赤玉这种酒为什么卖得不好？
******* 音频
43acd7ec-92c3-4a9e-8c18-596f11f01b0a.mp3
****** 选择
******* A
质量不好
******* B
宣传不够
******* C
产量太小
******* D
口昧不被接受
****** 答案
B
***** 12
****** 问题
******* 转录
酿酒师想出了一个什么办法？
******* 音频
2c8a54fe-38a6-49e2-b729-5dfb6fcf00da.mp3
****** 选择
******* A
改进口感
******* B
降价促销
******* C
借钱做广告
******* D
反复询问店家
****** 答案
D
*** 13-14
**** 段话
***** 转录
只有自己经历过创业之苦，才懂得节省的道理，才懂得创造的艰辛和财富的来之不易。约翰就是这样的人。他虽然非常富有，可在日常开支方面却很节省。一天，他在纽约一家宾馆办理入住，要求住一间最便宜的房间。宾馆的服务生说：“先生，你为什么要住便宜的小房间？你儿子来住宿时，总是挑最豪华的房间呀！”“没错，”约翰说，“我儿子有个百万富翁的父亲，可我没有呀！”
***** 音频
c99b5cd3-1a0d-44ec-867b-ff3b7902a93b.mp3
**** 题目
***** 13
****** 问题
******* 转录
对话中的两个人是什么关系？
******* 音频
abc523e6-3b19-4ad9-9f9f-bdc94060cbc6.mp3
****** 选择
******* A
父亲和儿子
******* B
客人和店员
******* C
房东和租客
******* D
老板和职员
****** 答案
B
***** 14
****** 问题
******* 转录
关于约翰，可以知道什么？
******* 音频
ccd2a60a-d37b-47a8-aa58-5af6f1436516.mp3
****** 选择
******* A
非常小气
******* B
十分贫穷
******* C
从不浪费
******* D
很爱孩子
****** 答案
C
* 阅读
** 第一部分
*** 课文
*** 题目
**** 15
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 16
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 17
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 18
***** 选择
****** A
****** B
****** C
****** D
***** 答案
** 第二部分
*** 19
:PROPERTIES:
:ID: 2322254e-ae8a-400d-a4bd-9461a7e983c4
:END:
**** 段话
请求别人帮忙，这是一种获得别人信任和支持的非常有效的方法。因为你使自己处于一种弱势的地位，这样就等于尊重了别人，使别人感到某种心理上的满足和自豪，从而对你心存善意。
**** 选择
***** A
万事不求人
***** B
求人不如求已
***** C
求助时要信任对方
***** D
帮助别人会得到满足感
**** 答案
D
*** 20
:PROPERTIES:
:ID: 727cc2ed-66b1-4ffd-8143-f9224216da37
:END:
**** 段话
一个小男孩儿问上帝：“一万年对你来说有多长？”上帝回答说：“像一分钟。”小男孩儿又问上帝：“100万元对你来说有多少？”上帝回答说：“像一元”小男孩儿再问上帝：“那你能给我100万元吗？”上帝回答说：“当然可以，只要你给我一分钟。”天下没有免费的午餐，创造财富要凭自己的毅力、耐心。
**** 选择
***** A
小男孩儿希望长寿
***** B
小男孩儿没有耐心
***** C
小男孩儿想得到财富
***** D
小男孩儿很羡慕上帝
**** 答案
C
*** 21
:PROPERTIES:
:ID: e7ade6ce-b35a-426f-ba9d-955f3936de88
:END:
**** 段话
在这个竞争的社会里，什么人都不能忽视。的确，在一个大集体里，干好一项工作，占主导地位的往往不是一个人的能力，关键是各成员间的团结合作。团结大家就是提升自己，因为别人会心甘情愿地教会你很多有用的东西。
**** 选择
***** A
不要看不起别人
***** B
要虚心向别人学习
***** C
不用在乎和别人的关系
***** D
干工作，团队合作很关键
**** 答案
D
*** 22
:PROPERTIES:
:ID: 4d69c04c-1aa6-4697-9d95-9c77e1dcc942
:END:
**** 段话
人有五只手指，长度各有不同。但是，你有没有注意到，其他手指都有三节，而唯独大拇指只有两节，这是为什么呢？原来，它的节数正好配合其他四指。要是三节的话，大拇指会显得没有力气，不能提起较重的物品；要是只有一节，它便不能灵活自如地与其他四指配合抓紧东西。
**** 选择
***** A
三节的手指才更有力气
***** B
大拇指主要负责提重物
***** C
大拇指是慢慢退化成两节的
***** D
两节的大拇指和四指配合最好
**** 答案
D
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
