* Text

** 标题

你属亟哪一种“忙”

** content

工作中的忙碌大概可概可以分为三种：第一种忙，忙得很被动，总是被事情追着、赶着，人几乎成了工作的奴隶口第二种忙，忙得很主动，忙而不乱，人是工作的主人口第三种忙，忙得有些虚伪，因为在他们的思想中，已经把忙与成功、闲与失败联系到一起，所以，这样的人褣是想办法让自己忙。

你属于那种忙呢？

我有一个体会：现实中，我们不一定知道正确的道路是什么，但时时反省、总结，却可以使我们不会在错误的道路上走得太远。

据说，曾经有一位很有个性、极爱冒险的大导演到南美丛林拍有关古代印加文明的纪隶片。他雇了20来个当地人为他带路和搬运行李。这批当地人个个都表现出色，尽管他们背着重重的行李，但他们的脚力过人，健步如飞。一连三天，他们都很顺利地实现了原定的计划。到了第四天，大导演一由醒来就催着大家上路。然而，当地人却拒绝行动。大导演非常着急，一来，耽误了时间，日程就得重新安排；二来，会因为费用增加而让段资人不高兴，至于这部影片的投资人，可是一位大人物，他可不敢得罪。经过沟通，大导演总算搞明白了，当地人自古就有一种习俗：在赶路时，用尽全力地向前仲，但每走上三天，便要休息一天。当大导演进一步询问原因时，当地人的回荅令他受益终生。

“那是为了让我们的灵魂，能够追得上我们赶了三天路的疲劳的身体。”

多么富有哲理的话！在这个提倡和鼓励竞争的时代，我们常常只顾低头拉车，却少了抬头看路，少了思考、总结这一重要的步骤。

从20世纪80年代起，比尔・盖茨每年都要进行两次为期一周的“闭关”。在这一周的时间里，他会把自己关在一所房子里，包括家人在内的任何人他都一律不见，使自己完全不受日常工作的打扰。盖茨的这种令人寂寞难耐的“闭关”不只是一种休息方式，更是一种高效率的工作方式。

忙碌的人们，请多给自己一点思考的时间吧。

** 生词

忙碌 / mang2lu4 / bussy, fully occupied ;
被动 / bei4dong4 / passive ;
奴隶 / nu2li4 / slave ;
虚伪 / xu1wei3 / hypocritical ;
思想 / si1xiang3 / thought, thinking ;
反省 / fan3xing3 / to reflect on oneself, to self-examine ;
据说 / ju4shuo1 / it is said, reputedly ;
个性 / ge4xing4 / individual character, personality ;
冒险 / mao4xian3 / to venture, to have an adventuree ;
丛林 / cong2lin2 / jungle, forest ;
文明 / wen2ming2 / civilization ;
纪隶 / ji4lu4 / record, note; to record, to note down ;
雇 / gu4 / to employ, to hire ;
来 / lai2 / part used after round numbers to indicate approximation ;
批 / pi1 / group, batch ;
出色 / chu1se4 / remarkable, outstanding ;
健步如飞 / jian4bu4-ru2fei1 / to walk as if on wings ;
一连 / yi4lian2 / in a row, in succession ;
耽俣 / dan1wu4 / to delay, to spoil through delay ;
至于 / zhi4yu2 / as for, as to ;
投资 / tou2zi1 / to invest, to fund ;
人物 / ren2wu4 / figure, personage ;
得罪 / de2zui4 / to offend, to displease ;
总算 / zong3suan4 / at last, finally ;
搞 / gao3 / (followed by a complement) to produce a certain effect or result ;
习俗 / xi2su2 / custom, convention ;
灵魂 / ling2hun2 / soul, spirit ;
疲劳 / pi2lao2 / tired, fatigued ;
哲理 / zhe2li3 / philosophy ;
提倡 / ti2chang4 / to advocate, to encourage  ;
步骤 / bu4zhou4 / step, procedure ;
闭关 / bi4guan1 / to stay secluded (a Taoist practice) ;
一律 / yi2lv4 / all, without exception ;
寂寞 / ji4mo4 / lonely ;
效率 / xiao4lv4 / efficiency ;

** QUESTION “个性”和“性个”有什区别？
:PROPERTIES:
:CREATED: [2022-08-27 18:29:20 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-27 Sat 18:29]
:END:

去世
** 专有名词

印加 / yin4jia1 / Inca Empire, the largest empire in pre-Columbian America ;
比尔・盖茨 / bi3'er3 gai4ci2 / Bill Gates ;

* 练习

** 1
:PROPERTIES:
:ID: c92065d7-f315-478f-a17b-20b974081853
:END:
*** 选择
**** 1
寂寞
**** 2
至于
**** 3
耽误
**** 4
提倡
**** 5
一律
**** 6
出色
*** 题目
**** 1
***** 句子填空
现在饭馆都[[gap]]节约，不浪费食物，“光盘”的意思就是把点的菜吃光。
***** 答案
****** 1
提倡
**** 2
***** 句子填空
上次约刘经理见面，路上堵车，[[gap]]了很长时间，这次可别再出问题了。
***** 答案
****** 1
耽误
**** 3
***** 句子填空
按规定，小动物[[gap]]小准带上飞机。
***** 答案
****** 1
一律
**** 4
***** 句子填空
她有些[[gap]]，想让我到她那儿陪她聊聊天。
***** 答案
****** 1
寂寞
**** 5
***** 句子填空
他顶住了压力，[[gap]]地发挥了自己的水平，打败了强敌。
***** 答案
****** 1
出色
**** 6
***** 句子填空
你们两口子吵架归吵架，不[[gap]]要闹离婚吧？
***** 答案
****** 1
至于
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:

*** 1

**** 词语

看到房间满是灰尘，他发起🟦了悉，刚🟦坐了十🟦个🟦小时火车，实在没力气收拾了。

**** 句子

来

**** 答案



*** 2

**** 词语

昌险

**** 句子

我🟦找刘明天来🟦当导演，其实是🟦有点儿🟦的。

**** 答案



*** 3

**** 词语

一律

**** 句子

🟦按学校🟦规定，缺课60节以上的学生🟦不允许🟦参加考试。

**** 答案



*** 4

**** 词语

出色

**** 句子

小丽🟦地完成了🟦比赛的各项动作，🟦取得了第一名🟦的好成绩。

**** 答案



** 2
*** 1
:PROPERTIES:
:ID: 735ed449-0f68-469e-a581-95f30a588e4b
:END:
**** 句子填空
为了保证病人的休息，午饭后[[gap]]不准探视（tànshì，to visit）。
**** 选择
***** A
一律
***** B
都
**** 答案
A
*** 2
:PROPERTIES:
:ID: bddd1be5-d5f6-40fb-9dca-b733a42c7b52
:END:
**** 句子填空
你怎么[[gap]]的？不是说好了周末和小丽见面的吗？怎么又不去了？
**** 选择
***** A
搞
***** B
做
**** 答案
A
*** 3
:PROPERTIES:
:ID: d4da2a06-fcbd-4da9-8a67-3e2b9d1fda5a
:END:
**** 句子填空
因为有大雾，飞机不能起飞。[[gap]]了您的宝贵时间，非常抱歉！
**** 选择
***** A
耽误
***** B
影响
**** 答案
A
*** 4
:PROPERTIES:
:ID: 74eabfff-c585-4649-bb03-98853d8eed9a
:END:
**** 句子填空
马向阳在那儿当县长时，[[gap]]地完成了任务。
**** 选择
***** A
出色
***** B
优秀
**** 答案
A
* 扩展

** 词语

*** 1

**** 话题

社会关系

**** 词语

演讲
发言
宴会
嘉宾
证件
名片

*** 2

**** 话题

婚恋

**** 词语

嫁
娶
分手
怀孕
吻

** 题

*** 1

**** 句子

这是我的🟨，我们保持联系，希望将来有机会一起合作。

**** 答案



*** 2

**** 句子

明天，希望公司的总裁刘明先生来学校🟨，你想去听听吗？

**** 答案



*** 3

**** 句子

老师，请问我报名时，都需要带什么🟨啊？

**** 答案



*** 4

**** 句子

出席开幕式的🟨都联系好了。

**** 答案


* 注释
** （三）词语辨析
*** 总算——终于
**** 做一做
***** 1
****** 句子
他多次想告诉她，但[[gap]]没说出口。
****** 答案
******* 1
******** 总算
0
******** 终于
1
***** 2
****** 句子
可让我担心的事[[gap]]还是发生了。
****** 答案
******* 1
******** 总算
0
******** 终于
1
***** 3
****** 句子
整整一个星期没出门，我[[gap]]把这几本厚厚的书读完了。
****** 答案
******* 1
******** 总算
1
******** 终于
1
***** 4
****** 句子
听了李阳这些话后，妈妈[[gap]]有点放心了。
****** 答案
******* 1
******** 总算
1
******** 终于
0
