* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 0b510c39-6741-4d0c-8084-960395f33411
:END:
**** 对话
***** 转录
女：老板派咱儿子去完成这次的任务不是好事吗？[[file:25f8f52b-1b9f-45fd-b309-acbea5fd342d.mp3][(audio)]]你为什么这么不高兴？[[file:37713ebe-6e46-453e-8a64-5960a4a56a99.mp3][(audio)]]
男：儿子的毛病是只会讲大道理，缺乏实际锻炼。[[file:5f8a5e8e-3686-4b20-a915-2291c48861b0.mp3][(audio)]]如果让他去，八成儿会把事情弄糟。[[file:df9c6cfa-2d9e-46fe-828d-612edb69f2c5.mp3][(audio)]]
***** 音频
ebf3dc29-cf0e-4ae5-936f-bef0ec8572fa.mp3
**** 问题
***** 转录
对于儿子去完成这次任务，父亲的态度是什么？
***** 音频
088733de-fc18-4280-95c9-01ce72716ebb.mp3
**** 选择
***** A
去挂
***** B
反对
***** C
高兴
***** D
惭愧
**** 答案
B
*** 2
:PROPERTIES:
:ID: 0a988a10-22aa-48cf-a7fa-35d1fdb03895
:END:
**** 对话
***** 转录
男：你为什么不想去幼儿园呢？[[file:838ae1ba-953a-474e-a3bf-575fd144fa6f.mp3][(audio)]]
女：小朋友们骂我是胆小鬼，不跟我玩儿。[[file:bba5f5c5-00a0-438b-83b7-234206480f3b.mp3][(audio)]]
***** 音频
2ed4644e-f013-4084-9722-d6fe50f43ead.mp3
**** 问题
***** 转录
女孩儿为什么不愿意去幼儿园？
***** 音频
f04cd93e-f310-45b8-a65c-b375fcce8f0b.mp3
**** 选择
***** A
不愿意起床
***** B
不喜欢老师
***** C
觉得幼儿园没意思
***** D
跟小朋友们关系不好
**** 答案
D
*** 3
:PROPERTIES:
:ID: 55cb825f-bab8-425e-bfc9-a9d8d3d5f340
:END:
**** 对话
***** 转录
女：这次夏令营是一个挑战，看看你是不是真的可以独立了。[[file:92828981-f276-4758-bd53-17ac122b8a5e.mp3][(audio)]]
男：您放心吧，我一定没问题。[[file:ce31631c-61ad-4396-8d1d-55c6425d677d.mp3][(audio)]]
***** 音频
cba16848-61f5-4c45-9fc8-4ecdbfb29fc6.mp3
**** 问题
***** 转录
他们最可能是什么关系？
***** 音频
d28ce1a3-635a-43d1-be4b-56697874570a.mp3
**** 选择
***** A
母子
***** B
父女
***** C
夫妻
***** D
同学
**** 答案
A
*** 4
:PROPERTIES:
:ID: 27782edd-2ae8-4a2c-aa9a-58f6baf4ba51
:END:
**** 对话
***** 转录
男：今天的会议有什么重要内容？[[file:f851d88d-2100-4a3b-ba94-9d4e69aedd21.mp3][(audio)]]
女：我跟你一样，没有参加会议的资格。[[file:854b2afd-e500-4180-9a77-294869618584.mp3][(audio)]]
***** 音频
908366d0-d950-439b-817e-a4d623a8fc75.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
e154a910-03e6-4381-9fb3-4cde538a7d7e.mp3
**** 选择
***** A
会议不重要
***** B
你应该知道
***** C
我也不知道
***** D
我没空参加
**** 答案
C
*** 5
:PROPERTIES:
:ID: 7a3ebb47-7b27-47c7-a49e-7b025b13c7e2
:END:
**** 对话
***** 转录
女：这孩子整天这么没脑子，以后可怎么办哪？[[file:72369b30-5086-4c78-8ac8-8a7f0f990cc4.mp3][(audio)]]
男：没关系，长大了慢慢就会懂事了。[[file:e17e153d-877a-475f-aa9c-47ed13984b10.mp3][(audio)]]
***** 音频
925f2fc5-0f08-4d72-a56f-4aec237a116c.mp3
**** 问题
***** 转录
女的觉得孩子怎么样？
***** 音频
85c99877-3bb5-4500-848a-b5092ba1e35c.mp3
**** 选择
***** A
懂事
***** B
糊涂
***** C
周到
***** D
孝顺
**** 答案
B
*** 6
:PROPERTIES:
:ID: ec1ba368-79bb-41aa-83c9-dd05f0fbe249
:END:
**** 对话
***** 转录
男：战国时期，各个国家之间的竞争非常激烈。[[file:76be35c9-e792-4f04-80fc-968f365d512a.mp3][(audio)]]
女：其实哪个时代都一样，那时候人才也是关键。[[file:20e9529d-101d-4991-9b8b-f00b86355c95.mp3][(audio)]]
***** 音频
7149cddd-6197-472d-8fc4-6b0f5e36dae6.mp3
**** 问题
***** 转录
女的想说明什么？
***** 音频
628242c6-a18a-4a15-8d74-fa69cecf8cb3.mp3
**** 选择
***** A
想取胜要靠人才
***** B
要积极参与竞争
***** C
战国时期人才重要
***** D
时代已经发生变化
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：老王不在你们公司工作了吗？
男：他被派到上海分公司去任总经理了。
女：原来是升官了啊！
男：是啊，干了这么多年，也该轮到他了。
***** 音频
d22e24e8-a295-4c6d-a3dd-a5254167dff7.mp3
**** 问题
***** 转录
关于老王，可以知道什么？
***** 音频
418c6a43-5f10-4554-be22-d391a33792b8.mp3
**** 选择
***** A
他辞职丁
***** B
他出国了
***** C
他一直在上海工作
***** D
他是这家公司的老员工
**** 答案
D
*** 8
**** 对话
***** 转录
男：太倒霉了！这次真是上了个大当！
女：之前我就再三地阻止你，你不听我的，能怪谁呢？
男：是啊，早知道听你的就好了。
女：现在后悔也晚了。
***** 音频
c235753a-e5ff-4b13-b802-dbf5081a3b17.mp3
**** 问题
***** 转录
男的怎么了？
***** 音频
136264e6-3eae-402a-bb3f-4b78efd23c28.mp3
**** 选择
***** A
来晚了
***** B
受骗了
***** C
怪女的没有阻止他
***** D
后悔听了女的的话
**** 答案
B
*** 9
**** 对话
***** 转录
女：我们为什么不主动去跟他们竞争呢？
男：现在的形势是敌强我弱，我们要做的就是坚守阵地。
女：我觉得你太小心谨慎了。
男：谨慎总比冒险好。
***** 音频
d908bea1-3ff2-4253-b9eb-e13b9546a7a7.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
c3942ce1-3092-411f-8878-b0f86c7143f7.mp3
**** 选择
***** A
应该去竞争
***** B
应该去胍险
***** C
小心没坏处
***** D
对方会吃亏
**** 答案
C
*** 10
**** 对话
***** 转录
男：为什么每次老张骂你，你都不出声？
女：我懒得跟他吵。
男：什么懒得跟他吵，我看你明明是吵不过他。
女：他年纪比我大，资历比我老，我当然只能让着他了。
***** 音频
716a9ea4-2ef8-4837-95d2-b31692151df0.mp3
**** 问题
***** 转录
关于女的，可以知道什么？
***** 音频
2f581a15-1730-4f5f-b499-a0f373e37673.mp3
**** 选择
***** A
她比老张大
***** B
她常常骂老张
***** C
她比老张厉害
***** D
她不愿意跟老张吵架
**** 答案
D
*** 11-12
**** 对话
***** 转录
女：昨天你不是说先等等，看看对方的反应怎么样吗？
男：我又想了想，觉得这件事迟早是要解决的，还不如先拿出一个有利于我们自己的方案。
女：你这主意改得可真快。
男：别说这么多了，还是快想办法吧。
女：知己知彼才能百战百胜呢，现在我们完全不了解对方的情况，怎么拿方案啊？这不是纸上谈兵嘛！
***** 音频
955c7714-11c3-45e6-9de6-91cc29ad1bd3.mp3
**** 题目
***** 11
****** 问题
******* 转录
男的原来的想法是什么？
******* 音频
6082b56b-b00d-4d42-8b5f-2310cbf60d72.mp3
****** 选择
******* A
改主意
******* B
纸上谈兵
******* C
先看对方的反应
******* D
拿出有利的方案
****** 答案
C
***** 12
****** 问题
******* 转录
女的是什么意思？
******* 音频
49336b9c-5e4b-4729-b754-314a98475210.mp3
****** 选择
******* A
应该改主意
******* B
应该跟对方联系
******* C
应该马上拿出新方案
******* D
应该先了解对方的情况
****** 答案
D
*** 13-14
**** 段话
***** 转录
有些中国人言必称汉唐，因为汉朝和唐朝确实是中国古代历史上最值得骄傲的两个朝代，经济条件好，军事力量强。不过仔细想一想，其实这两代也并不是从头到尾都繁荣富强。汉朝最值得称赞的主要是汉高祖以后的一百多年，代表人物是汉文帝和汉武帝；唐朝也一样，总共约三百年江山，最令后人怀念的大概也只有唐太宗的“贞观之治”和唐玄宗的“开元之治”两段时间。
***** 音频
3b6ccf96-f52c-400e-a7bc-4a3ebf3cb5f4.mp3
**** 题目
***** 13
****** 问题
******* 转录
说话人认为汉朝和唐朝怎么样？
******* 音频
e27ba3e5-1c2e-42ba-8e1f-ebd497513ced.mp3
****** 选择
******* A
英雄众多
******* B
繁荣富强
******* C
经济落后
******* D
环境艰苦
****** 答案
B
***** 14
****** 问题
******* 转录
根据这段话，下列哪项正确？
******* 音频
7b694127-d5bf-4dc4-98e0-217d89159f0f.mp3
****** 选择
******* A
汉朝有三个皈帝
******* B
唐朝一共一百多年时间
******* C
中国人为汉唐两朝而骄傲
******* D
汉唐两朝一直都很繁荣富强
****** 答案
C
* 阅读
** 第一部分
*** 段话
随着比赛结束的哨声吹响，天津男篮的主教练高举双臂，冲到了球场中，并激动地高啧：“我们赢了！我们赡了！“
“这是梦幻的时刻，我们竟然真的干掉了上届冠军！“他看着大屏幕上显示的比分，[[gap][15]]，“是的，我们做到了！每个人都是好样的！”
临近记者发布会，他的心情才平静下来，并向大家解释了为什么会如此激动，“这场[[gap][16]]来得太不容易，赛前几乎没人看好我们，我们被[[gap][17]]“了。但结果，我们用[[gap][18]]的优势回击了所有人的质疑。我们做到了，我为球员们骄傲“
*** 题目
**** 15
***** 选择
****** A
等待比赛的最后结果
****** B
仿佛伋然不敢相信这个结果
****** C
看起来非常生气
****** D
似乎在期待另外一种结果
***** 答案
B
**** 16
***** 选择
****** A
赢
****** B
比赛
****** C
胜利
****** D
成功
***** 答案
C
**** 17
***** 选择
****** A
轻视
****** B
重视
****** C
模糊
****** D
委屈
***** 答案
A
**** 18
***** 选择
****** A
完全
****** B
肯定
****** C
特别
****** D
绝对
***** 答案
D
** 第二部分
*** 19
:PROPERTIES:
:ID: 5427d7cf-5bad-4de0-a97d-2506f28ca7e6
:END:
**** 段话
公元前260年，赵括带兵出战。一直盲目自信、轻视秦军的他完全改变了廉颇的作战方案，死搬兵书上的理论，主动进攻秦军，结果数十万赵军全部被杀，丢掠了宝贵的生命。
**** 选择
***** A
赵括非常谦虚
***** B
赵括询问了廉颇的意见
***** C
赵军主动发起了这次进攻
***** D
这场战争的结果是赵国胜利
**** 答案
C
*** 20
:PROPERTIES:
:ID: a53add5f-dfa1-4153-92c8-55fbf61aca27
:END:
**** 段话
秦国和晋国之间发生战争时，晋惠公要使用郑国赠送的马来驾车。大臣庆郑劝告惠公说：“自古以来，打仗时都要用本国的好马，因为它土生土长，熟悉道路，听从命令。用外国的马，不好控制；而东郑国马外表看起来好像很强壮，实际上并没有什么本领，怎么能作战呢？“但是惠公没有听从庆郑的劝说。战斗打响后，晋国的车马便乱跑一气，结果被秦军打得大败。
**** 选择
***** A
晋国打败了秦国
***** B
打仗应该选用本地的马
***** C
惠公听取了大臣的意见
***** D
输掉这场战争的原因是马生病了
**** 答案
B
*** 21
:PROPERTIES:
:ID: 9daa6094-6a6a-4ace-b8c5-965145ec1b8a
:END:
**** 段话
湖南省博物馆保存有三幅世界上最早的地图，它们1973年12月出土于长沙马王堆一号汉墓。这三幅汉代的彩色帛绘地图距今已有两十多年的历史。图上绘有山脉、河流、居民点，着重标出了9支军队。从地图的精确度看，与今天当地的地理状况基本相同，说明当时的地图绘制技术已经达到了很高的水平。
**** 选择
***** A
这些地图现在保存在国家博物馆
***** B
汉代距今已有三千年的历史
***** C
这些地图可能用于军事
***** D
当地的地理状况发生丁很大的变化
**** 答案
C
*** 22
:PROPERTIES:
:ID: e0ed3d11-3770-45aa-a8f7-a89ba0572785
:END:
**** 段话
杜预（222年一285年），字元凯，京兆杜陵（今陕西西安东南）人，西晋时期著名的政治家、军事家和学者，灭吴统一战争的统帅之一。他是一位儒将，博学多才，被称为“杜武库“，意思是他什么都懂，就好像武器库里面藏有各种各样的武器一样。
**** 选择
***** A
杜预是山西人
***** B
杜预没能参加灭吴统一战争
***** C
杜预是一个学识很丰富的人
***** D
杜预会使用各种各样的武器
**** 答案
C
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
