* 练习

** 1
:PROPERTIES:
:ID: 47dea1e2-2d47-4d97-89aa-0b6156fcac47
:END:
*** 选择
**** 1
宝贵
**** 2
阻止
**** 3
善于
**** 4
独立
**** 5
挑战
**** 6
糊涂
*** 题目
**** 1
***** 句子填空
我见朋友的小孩怎么也打不开房门，就想帮他，却被朋友[[gap]]了。
***** 答案
2
**** 2
***** 句子填空
任何经验都是[[gap]]的，但并不是任何时候都是有效的。
***** 答案
1
**** 3
***** 句子填空
社会上的成功人士，有不少都[[gap]]记住别人的名字。
***** 答案
3
**** 4
***** 句子填空
你这脑子可真[[gap]]，银行卡的密码怎么能忘了呢？
***** 答案
6
**** 5
***** 句子填空
跳伞运动以自身的惊险和[[gap]]性，被世人称为“勇敢者的运动”。
***** 答案
5
**** 6
***** 句子填空
家长应尽量创造一个能让孩子[[gap]]生活和学习的环境。
***** 答案
4
** 2
*** 1
:PROPERTIES:
:ID: 1e0f583b-b679-4ed4-85e5-88b37d083638
:END:
**** 句子填空
我[[gap]]以为这一生我只能做一个普普通通的工人了。
**** 选择
***** A
曾经
***** B
已经
**** 答案
A
*** 2
:PROPERTIES:
:ID: cca283f6-ffec-4be5-9976-e6544ba84244
:END:
**** 句子填空
师傅，最近我这车出了点儿[[gap]]，空高总是不太凉。
**** 选择
***** A
缺点
***** B
毛病
**** 答案
B
*** 3
:PROPERTIES:
:ID: bc5bf986-b40d-4bac-9fec-281fb305eef3
:END:
**** 句子填空
父母给我讲了许多做人的[[gap]]，对我的影响很大。
**** 选择
***** A
理论
***** B
道理
**** 答案
B
*** 4
:PROPERTIES:
:ID: e555ff5e-4904-4583-9c53-129a2f44f465
:END:
**** 句子填空
我相信这样的安排他是[[gap]]不会同意的。
**** 选择
***** A
绝对
***** B
完全
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
克服
***** 答案
毛病
**** 2
***** 词语
下
***** 答案
命令
**** 3
***** 词语
具备
***** 答案
资格
**** 4
***** 词语
阻止
***** 答案
战争
*** 2
**** 1
***** 词语
危急的
***** 答案
形势
**** 2
***** 词语
糊涂的
***** 答案
经理
**** 3
***** 词语
宝贵的
***** 答案
时间
**** 4
***** 词语
抽象的
***** 答案
道理
* 扩展
** 词语
*** 话题
军事
*** 词语
**** 1
枪
**** 2
射
**** 3
射击
**** 4
英雄
**** 5
士兵
**** 6
敌人
**** 7
战争
**** 8
胜利
** 题目
*** 1
**** 句子
猎人被眼前的情景吓傻了，慌乱地连开了几[[gap]]。
**** 答案
1
*** 2
**** 句子
我们已经走完一大半了，坚持就是[[gap]]。
**** 答案
8
*** 3
**** 句子
花木兰是中国古代的女[[gap]]，她替父参军并打败敌人，从而闻名天下。
**** 答案
4
*** 4
**** 句子
在1896的年奥运会上，[[gap]]就被列为了正式比赛项目。
**** 答案
3
* 注释
** （三）词语辨析
*** 胜利——成功
**** 做一做
***** 1
****** 句子
这项实验如果研究[[gap]]，将给成千上万的病人带来希望。
****** 答案
******* 1
******** 胜利
0
******** 成功
1
***** 2
****** 句子
得民心者才会赢得这场战争的[[gap]]。
****** 答案
******* 1
******** 胜利
1
******** 成功
0
***** 3
****** 句子
她[[gap]]地说服了丈夫放弃了搬家的打算。
****** 答案
******* 1
******** 胜利
0
******** 成功
1
***** 4
****** 句子
座谈会开得很[[gap]]，大家交换了意见，增进了理解。
****** 答案
******* 1
******** 胜利
0
******** 成功
1
* 课文
** 转录
两千七百多年前的战国末期，赵国名将赵奢有个儿子叫赵括，他从小读了不少兵书，跟别人谈论起军事来，没有人说得过他，就是父亲赵奢也难不住他。赵括因此很骄傲，自以为天下无敌，连父亲也不放在眼里。
但是赵奢心里明白，自己的儿子虽然对军事理论都很了解，但是没有实际作战的经验，想法很不符合实际。他曾经偷偷对妻子说：“儿子的毛病是只会讲大道理，缺乏实际锻炼，不能当大将。如果让他当了大将，迟早会害了赵国。”几年后，赵奢去世了。这一年正好秦国军队来打赵国，赵国派老将廉颇带 20 万大军迎战。廉颇根据敌强我弱的形势，命令士兵们坚守阵地，绝对不可主动出战。秦军多次挑战，骂他是胆小鬼，他还是不出兵。这个办法果然非常有效，成功地把秦军拦在了国门之外。渐渐地，秦军无法快速取得胜利，粮食也快没了，有些坚持不住了。
秦人深知廉颇善于用兵，如果想在短期内打败赵国，必须想办法叫赵国把廉颇调回去。于是，他们在赵国四处散布谣言，说秦军最怕赵括，别的人都不放在眼里。
这时，赵王正因廉颇闭门不战而生气呢，听到外面的那些谣言，果然上当了，他派赵括去换回廉颇。赵括的母亲再三阻止赵王任命儿子为大将，说他还没有独立带兵作战的资格。可是，糊涂的赵王哪里听得进去！
公元前 260 年，赵括带兵出战。一直盲目自信、轻视秦军的他完全改变了廉颇的作战方案，死搬兵书上的理论，主动进攻秦军，结果数十万赵军全部被杀，丢掉了宝贵的生命。
这就是成语“纸上谈兵”的故事。现在常用这个成语讽刺那些只会空谈理论的人，提醒大家做事一定要灵活，要注意理论联系实际。
