* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 4d30a073-3aa3-41e6-9430-de114d69567e
:END:
**** 对话
***** 转录
女：这件事情，我建议你先回去征求一下父母的意见。[[file:47f9e916-fb2b-49d1-9d9d-72dd2ef97136.mp3][(audio)]]
男：老师，我相信父母会支持我的。[[file:97963fbe-6829-4275-8341-b6a15c05c634.mp3][(audio)]]
***** 音频
0a156499-38a2-42bb-8619-134409441ad0.mp3
**** 问题
***** 转录
对这件事情，老师的看法是什么？
***** 音频
8dc0ae2d-bcdb-491b-b7b7-6d67db39b6d2.mp3
**** 选择
***** A
同意他的做法
***** B
反对他的做法
***** C
相信父母会支持他
***** D
应该问父母的意见
**** 答案
D
*** 2
:PROPERTIES:
:ID: e11ca1a9-8b67-4b14-b897-27791ade8f2c
:END:
**** 对话
***** 转录
男：能被牛津大学这样的世界名校录取多好啊！你怎么能放弃呢？[[file:77650e75-424b-4be8-bd64-b0105a129dc0.mp3][(audio)]]
女：牛津大学当然很好，但是我想去美国。[[file:db9a56c6-1da1-4e55-aa0a-c0ee5f779f78.mp3][(audio)]]
***** 音频
52ebd5c0-341d-4069-b1c5-2639d34473cf.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
a897d64f-45fa-4856-b764-44812557a6c6.mp3
**** 选择
***** A
牛津大学不太好
***** B
牛津大学是名校
***** C
她不想去牛津大学
***** D
她没被牛津大学录取
**** 答案
C
*** 3
:PROPERTIES:
:ID: f44db7e3-8278-4b40-838a-a35fdf3a5cb7
:END:
**** 对话
***** 转录
女：我们终于取得一致了，真是太不容易了。[[file:9d5c9ee1-8f86-498d-9aea-5ea4b157a1ef.mp3][(audio)]]
男：大家的目标从来都是一致的，都是为了公司好。[[file:3248ee64-793c-426b-846d-cc9dba10931e.mp3][(audio)]]
***** 音频
5d6e4a0f-5795-411d-96dc-a7905ea088d9.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
5a7671cc-cfe9-499b-acc6-4728dfd76593.mp3
**** 选择
***** A
大家的意见一直一样
***** B
他不同意妇的的意见
***** C
大家的目的是一样的
***** D
现在的意见也不一样
**** 答案
C
*** 4
:PROPERTIES:
:ID: 9028391d-8cad-4d13-8d4e-22e569b91fef
:END:
**** 对话
***** 转录
男：小王，你怎么不说说你的看法？[[file:ff7d4ac2-d270-4bc9-b079-035c017c4e4c.mp3][(audio)]]
女：你不允许我们说不同意，我只好沉默。[[file:c4af089a-a5f2-45ac-835d-c4b52e4905b8.mp3][(audio)]]
***** 音频
7a8294cb-7321-4b47-b830-9a81948156c4.mp3
**** 问题
***** 转录
女的是什么态度？
***** 音频
82e6a685-aee0-47bb-931c-6bb258215391.mp3
**** 选择
***** A
支持
***** B
担心
***** C
不满
***** D
无所谓
**** 答案
C
*** 5
:PROPERTIES:
:ID: 618c718c-a72f-45c7-be0c-1f8a615c8186
:END:
**** 对话
***** 转录
女：你跟文文现在发展到什么程度了？[[file:0b0f6a5e-7737-41dd-a9e7-978b70f6221d.mp3][(audio)]]
男：昨天我第一次吻了她。[[file:3f4c1088-cd43-4bc9-a8b8-f4fd1f70ee57.mp3][(audio)]]
***** 音频
d401058e-c83e-49a9-bccf-191b477a6ace.mp3
**** 问题
***** 转录
男的跟文文最可能是什么关系？
***** 音频
83de3f9a-2d8f-4867-91cf-a737722629b0.mp3
**** 选择
***** A
朋友
***** B
恋人
***** C
同学
***** D
母子
**** 答案
B
*** 6
:PROPERTIES:
:ID: b07d0cd0-b55f-4af5-9c44-f77e2af25aac
:END:
**** 对话
***** 转录
男：你听说了吗，昨天 34 路车出事了！[[file:535df0da-fee5-428e-a610-2451f3fd425a.mp3][(audio)]]
女：是啊，我回家经常坐那趟车呢！幸亏昨天加班走得晚，打车回去的。[[file:8cdab871-06a4-4faf-a3b1-f2f1e9d6e57c.mp3][(audio)]]
***** 音频
ea062bd8-4c43-4786-a1d4-b923671ed754.mp3
**** 问题
***** 转录
女的昨天为什么没坐 34 路车？
***** 音频
8615f550-c22f-439e-ab76-2a802b2a4a72.mp3
**** 选择
***** A
那趟车出事了
***** B
她昨晚没回家
***** C
那趟车不顺路
***** D
她昨天加班了
**** 答案
D
** 第二部分
*** 7
**** 对话
***** 转录
男：他要是靠得住，我早就交给他了。
女：儿子有什么不好？你总是不信任他！
男：你还说，都是你把他惯坏了！我说往东，他就偏要往西！
***** 音频
af139f51-b0d0-4cdb-a215-351d54f1fc7c.mp3
**** 问题
***** 转录
说话人最可能是什么关系？
***** 音频
f89cf90b-f23f-44e6-9255-15df206ec83a.mp3
**** 选择
***** A
父子
***** B
师生
***** C
夫妻
***** D
同事
**** 答案
C
*** 8
**** 对话
***** 转录
男：妈妈，我去上班的时候，您自己也可以出去走走，别整天关在家里。
女：我一句外语也不会说，怎么出门啊？
男：放心吧，您先去附近的超市看看。我给您准备好地图，写上我们家的地址，如果找不到您就拿给别人看。
女：那我明天试试吧。
***** 音频
d2b6f0b5-a71f-400c-9b39-27d6d376f171.mp3
**** 问题
***** 转录
女的为什么不愿意出门？
***** 音频
3c62b2b0-761a-440c-a9ae-579079c07163.mp3
**** 选择
***** A
没有地图
***** B
语言不通
***** C
不知道地址
***** D
儿子要去上班
**** 答案
B
*** 9
**** 对话
***** 转录
女：这次能够获奖，您有什么想说的吗？
男：能够得到这个奖，全靠大家的肯定与帮助，还有领导的关心，甚至还有善意的批评。
女：那您最想感谢的是谁？
男：最想感谢的是我的家人。如果没有他们的鼓励与支持，我是不可能坚持下来的。
***** 音频
c2935b47-ad75-43a4-accd-da934c19db82.mp3
**** 问题
***** 转录
男的最想感谢什么？
***** 音频
9cbfabdb-ee97-485a-831b-7521ae9a4415.mp3
**** 选择
***** A
领导的关心
***** B
大家的帮助
***** C
家人的支持
***** D
家人的批评
**** 答案
C
*** 10
**** 对话
***** 转录
男：上课了，小明怎么站在教室外面？
女：一定是他又淘气，被李老师罚站了。
男：就算孩子违反了纪律，也不能体罚！
女：嗯，下课后我跟李老师谈谈。
***** 音频
2a7c35cc-6fb5-4737-aa68-4f68904fac7f.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
98d376ee-95a2-4931-8120-151b4570ccd0.mp3
**** 选择
***** A
小明应该被罚
***** B
小明太淘气了
***** C
老师不该体罚小明
***** D
小明没有违反纪律
**** 答案
C
*** 11-12
**** 对话
***** 转录
孩子的教育是全社会特别关心的一个问题。很多家长在教育孩子的问题上，都学了很多理论，有自己的主张，听起来都很有道理。但是在实际生活中，父母们往往又不按照这些理论去做。他们说：道理很简单，我工作太忙了，实在没有那么多时间按照那些理论去教育孩子，我希望学校、老师能去完成这些事情。
***** 音频
11840834-bfdb-4e48-bc2b-179dd2570b44.mp3
**** 题目
***** 11
****** 问题
******* 转录
全社会都特别关心什么问题？
******* 音频
7bb70e88-0a35-4bd4-af3a-4ecd2aaad4c3.mp3
****** 选择
******* A
孩二的教育问题
******* B
家长的工作问题
******* C
学校的问题
******* D
心师的问题
****** 答案
A
***** 12
****** 问题
******* 转录
家长们为什么不按照教育理论去做？
******* 音频
6b78ef34-c410-4d86-bf86-4666f7447458.mp3
****** 选择
******* A
他们不同意这些理论
******* B
他们不关心这些理论
******* C
他们没学过这些理论
******* D
他们没有时间这么做
****** 答案
D
*** 13-14
**** 段话
***** 转录
我自己是个数学老师，但我女儿小时候特别不喜欢数学，成绩很差。有一天，我给女儿出了 10 道题，女儿竟然做错了 9 道。我并没有生气，相反，对她大加称赞：“这么难的题目，你竟然也能做对！我小时候可是一道都做不出啊！”第二天晚上，我又准备了 10 道难度降低了的题目，再让女儿做，结果这次做对了 5道。我鼓励女儿说：“天哪，你真是太了不起了！一天之内，你可以进步这么大！”第三天，女儿自己主动要求：“爸爸，今晚我们还做数学题吧！”半年之后，女儿成了班里的数学课代表。
***** 音频
c99a40ef-fea0-457f-abe0-3d9a1be88f39.mp3
**** 题目
***** 13
****** 问题
******* 转录
女儿第二天做题时为什么对得比较多？
******* 音频
edd5cbbf-f35a-4697-a2c1-10d67a24fa92.mp3
****** 选择
******* A
题目减少了
******* B
题目增多了
******* C
题目容易了
******* D
女儿进步了
****** 答案
C
***** 14
****** 问题
******* 转录
这段话主要谈什么？
******* 音频
e5e57d52-74a1-418b-a396-8b2c9a84618b.mp3
****** 选择
******* A
怎么提高成绩
******* B
孩子需要鼓励
******* C
老师要懂教育
******* D
学习需要兴趣
****** 答案
B
* 阅读
** 第一部分
*** 段话
有人哭，是因为伤心；有人哭，是因为激动。而我[[gap][15]]，是因为同学们带给我的感动。
那天我要代表我们[[gap][16]]去参加全校的书法比赛，没想到，就在比赛的那天早上，我突然发起了高烧。宿舍的同屋都劝我不要勉强，不过我还是坚持走进了赛场。但是，身佛的不适的确影响了我的状态，最后写出来的字，完全不像练了十儿年书法的人写的。我知道，这次我输了。可是同学们都没有笑我批评我，反而安慰我说：“没关系，以后还有机会，我们都相信你的[[gap][17]]。”听了大家的话，我[[gap][18]]哭了。
*** 题目
**** 15
***** 选择
****** A
每次哭
****** B
最难忘的那一次哭
****** C
从来不哭
****** D
最伤心的那一次哭
***** 答案
B
**** 16
***** 选择
****** A
系
****** B
某
****** C
念
****** D
暗
***** 答案
A
**** 17
***** 选择
****** A
能干
****** B
本领
****** C
能力
****** D
功能
***** 答案
C
**** 18
***** 选择
****** A
说不定
****** B
受不了
****** C
来不及
****** D
忍不住
***** 答案
D
** 第二部分
*** 19
:PROPERTIES:
:ID: fda42af9-bfe0-44b9-9000-ec05065c5f20
:END:
**** 段话
到了大学阶段，亲爱的女儿竟然违反了“乖乖女”的各种规矩，越来越有自己的主见，越来越能干、独立了。尽管她的成绩仍然是第一名，但她不再甘于当“好学生”：她逃课去听讲座，参加欧盟商会的鸡尾酒会，做志愿者，拍电影，学摄影，泡酒吧，竞选并担任了学生会主席，组织各种社会活动。
**** 选择
***** A
女儿一直是一个乖乖女
***** B
女儿积极参加社会活动
***** C
女儿的成绩越来越差了
***** D
女儿从小就很喜欢逃课
**** 答案
B
*** 20
:PROPERTIES:
:ID: 4189bc47-3fc4-4da3-9760-3c26dac531ac
:END:
**** 段话
谈到单亲家庭的教育问题，专家说，有些离了婚的妈妈一个人带孩子很辛苦，于是她们就把对孩子爸爸的不满灌输给孩子，让孩子觉得爸爸很坏，这样会严重地影响孩子的心理健康。因此，母亲自身的文化修养很重要。
**** 选择
***** A
单亲妈妈不应该让孩子觉得爸爸很坏
***** B
单亲家庭都是离婚后妈妈独自带孩子
***** C
单亲家庭的孩子有心理健康问题
***** D
母亲的文化修养对孩子没有影响
**** 答案
A
*** 21
:PROPERTIES:
:ID: 71f70025-49df-4db2-aa37-6c110d5d4ba6
:END:
**** 段话
今晚我们的《父与子》栏目，让四对父子面对面说出了自己的心里话。希望所有的父子都能够像他们一样，多交流，多沟通，加强双方的理解。父母可以不同意孩子的观点，但要给他们说出来的机会，让双方取得共识，而不应强迫孩子顺从自己的意愿。
**** 选择
***** A
所有的父子之间都有足够的沟通机会
***** B
今晚有四个人参加了《父与子》节目
***** C
父母应该努力让孩子理解自己的要求
***** D
父母在自己孩子面前可以说了算
**** 答案
C
*** 22
:PROPERTIES:
:ID: cd9001c5-f2ef-4c47-aa52-1c336dd896f0
:END:
**** 段话
未来社会将是一个更加重视知识的“学习化社会”，人人都需要受教育，因此，教育将成为最大的行业之一。其中，师范教育又尤为重要，因为师范教育的质量关系到教师的质量，教师的质量又影响着学生的质量。从这个意义上说，办好师范教育，对提高一个国家整体的国民素质，进而促进国家经济的发展、推动政治文化的建设，都起着举足轻重的作用。
**** 选择
***** A
未来社会，人人都是学生
***** B
师范教育是教育行业中人数最多的
***** C
教师水平高，学生的质量就一定会好
***** D
师范教育的水平会影响国家的经济文化建设
**** 答案
D
** 第三部分
*** 23-25
**** 段话
大三下学期，就读于西安交通大学的徐达士得到了去芬兰交换学习一年的机会。
芬兰有无边无际的森林、星罗棋布的湖泊。徐达士说：“在芬兰，感受到更多的是平静以及人与自然的相互依赖，我很喜欢那种与自然亲近的生活状态。”
由于是交换生，选课相对自由。基于自己的兴趣爱好，他学习了文化人类学、跨文化交流、芬兰语等课程。开朗的性格使他很快融入了当地人的生活，暑假他还和朋友们一起去了俄罗斯、德国、荷兰等地。
“那一年的交换生经历让我结识到了很多来自世界各地的学生、学者，算是第一次体验到了跨文化交流，交到了几个好朋友。他们来自荷兰、希腊、匈牙利，当然还有芬兰。”
当谈到选择到美国读研究生时，徐达士说：“美国机会更多，研究生教育在世界范围内更知名，而且美国文化更加多样化。在芬兰的学生食堂，可能95％都是芬兰人，而在美国的食堂，你可以看到更多不同国家、不同文化背景的人。”
然而，“交换生和研究生是两个完全不同的角色，交换时过得很潇洒，压力小，到处旅行。去美国读研要忙很多，过得更紧凑。”去年暑假，徐达士在国际救援委员会做了三个月的志愿实习。在平时，他也会去做些其他工作，如给老师做助研、教汉语、组织汉语角、帮图书馆录数据等。
现在就读于美国约翰·霍普金斯大学公共政策专业的他，对未来充满了希望，期望自已能够领略不同的风景，体验不一样的人生。
**** 题目
***** 23
****** 问题
徐达士现在是：
****** 选择
******* A
大三学生
******* B
交换生
******* C
研究生
******* D
志愿者
****** 答案
C
***** 24
****** 问题
关于徐达士在芬兰的生活，下列哪项正确？
****** 选择
******* A
芬兰有很多湖可以游泳
******* B
在芬兰学习压力比较小
******* C
他不能去别的国家旅行
******* D
他业余教芬兰人学汉语
****** 答案
B
***** 25
****** 问题
徐达士选择去美国读研究生最主要的原因是：
****** 选择
******* A
他在芬兰没有多少朋友
******* B
约翰·霍普金斯大学很有名
******* C
他喜欢与自然亲近的生活状态
******* D
他想经历不一样的生活
****** 答案
D
*** 26-28
**** 段话
有三个孩子在树林里玩儿，都不小心被树枝划破了裤子。面对裤腿上的破洞和孩子不安的脸，三位母亲用不同的态度处理了这件事情。
第一位母亲大声教训了孩子之后，用一根线绳像系麻袋一样把那个破洞扎紧，整条裤腿因此显得皱皱巴巴。破洞是没有了，取而代之的那个结却像孩子撅起的小嘴。孩子也因此受到严厉的警告：“今后再也不准到树林里去玩儿！”
第二位母亲不打也不骂，默默地把那个破洞一针一线缝补好，裤子上留下了针线的痕迹。
第三位母亲面对孩子裤腿上的破洞，安慰孩子：“不要紧，哪个小孩子不贪玩儿，你奶奶说你爸爸小时候比你还调皮呢。”她把孩子的裤子脱下来，用彩线在破洞上绣了朵漂亮的小花，好像原本那里就有一朵花。孩子笑得好开心。
同样的问题，因为用了三种不同的解决办法，就导致了不同的结果：第一位母亲让孩子感到恐惧和失望，那皱巴巴的裤腿就如同母亲脸上写满的愤怒，孩子不得不活在母亲强制的意愿中；第二位母亲平平常常，孩子得到的是一个顺其自然的生活环境；第三位母亲是最优秀的教育家，她用裤子上的花朵启发了孩子美好的想象，她脸上灿若朝阳的微笑给了孩子更多的宽容，让孩子在成长的路上充满自信并富有创造力。
**** 题目
***** 26
****** 问题
作者最欣赏哪位母亲？
****** 选择
******* A
第一位
******* B
第二位
******* C
第三位
******* D
都不欣赏
****** 答案
C
***** 27
****** 问题
关于第一位母亲，下列哪项正确？
****** 选择
******* A
乐于称赞孩子
******* B
要求孩子遵守纪律
******* C
批评警告了孩子
******* D
补好了划破的裤子
****** 答案
C
***** 28
****** 问题
第三位母亲培养了孩子的：
****** 选择
******* A
纪律性
******* B
自信心
******* C
行动力
******* D
环保观念
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
