* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: a9f19701-d85a-4fc1-a963-f2e0c66ada18
:END:
**** 对话
***** 转录
女：怎么你今天吃得这么少？是不是这些菜不合你的口味？[[file:78d90f9e-82d5-405d-83f3-09fd5eb8176f.mp3][(audio)]]
男：这两天有点儿不舒服，没什么胃口。[[file:330c8f68-a6f7-4958-8bd7-09e5a8af7b2d.mp3][(audio)]]
***** 音频
8ef3614a-6832-48ff-b894-ee20301f3909.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
72806869-79ab-4051-bf94-bb7e1dc4262b.mp3
**** 选择
***** A
菜不太好吃
***** B
心里不舒服
***** C
不想吃东西
***** D
胃有点儿疼
**** 答案
C
*** 2
:PROPERTIES:
:ID: 3c156f44-d282-43d5-aa31-80744e7c6973
:END:
**** 对话
***** 转录
女：这香肠的颜色怎么这样？是不是有点儿问题？[[file:c8b54440-9f8a-443c-960a-1f90d3488ff0.mp3][(audio)]]
男：放在冰箱里就忘了，你赶紧看看生产日期吧。[[file:ef28b633-9dd5-4389-8aa1-0c0b10122451.mp3][(audio)]]
***** 音频
5cbb25b0-a543-408e-a564-51a1305f5116.mp3
**** 问题
***** 转录
男的觉得香肠怎么了？
***** 音频
58783480-29ba-4cf0-80e4-e89336eccd5b.mp3
**** 选择
***** A
颜色有问题
***** B
可能过期了
***** C
质量不太好
***** D
味道有些怪
**** 答案
B
*** 3
:PROPERTIES:
:ID: 02f305cf-0af2-48e3-a579-f530bc016724
:END:
**** 对话
***** 转录
女：欢迎光临！对不起，现在没位子了，您在这儿坐下等一会儿可以吗？这儿准备了点心和茶水，您先用一点儿。[[file:ca1fc40c-c84f-45ca-90d2-d807029520b8.mp3][(audio)]]
男：哦，谢谢！我下午跟你们订过一个包间，你查一下李先生的预订有没有？[[file:21e4083b-e5cd-4628-b4e0-43a8f42153fa.mp3][(audio)]]
***** 音频
87415fa8-246c-4e72-ab7d-1793da017030.mp3
**** 问题
***** 转录
男的现在最可能在哪儿？
***** 音频
d3a5755a-f0fa-439f-b444-639881415f4e.mp3
**** 选择
***** A
商店
***** B
宾馆
***** C
剧院
***** D
饭馆
**** 答案
D
*** 4
:PROPERTIES:
:ID: d8563cdf-a0e0-4ed1-a346-28cf1a820ac8
:END:
**** 对话
***** 转录
女：这萝卜饼的饼皮薄得跟纸似的，萝卜颜色红红绿绿的，真好看。[[file:17ec0d81-316b-4bd0-802e-4354db12801f.mp3][(audio)]]
男：怎么样，好吃吧？这饼可是我们家乡的特色美食。[[file:f027e288-a090-4e8a-bf1c-0695229125fe.mp3][(audio)]]
***** 音频
c94685b3-2351-4a00-8d8b-3283971c6f76.mp3
**** 问题
***** 转录
关于萝卜饼，可以知道什么？
***** 音频
252fa939-02dc-465a-9f4e-bbea6888365c.mp3
**** 选择
***** A
饼皮颜色很好看
***** B
饼薄得像纸一样
***** C
男的对它很熟愁
***** D
女的做得很拿手
**** 答案
C
*** 5
:PROPERTIES:
:ID: b03b2ff9-0c96-48b8-b117-7d0767c139d3
:END:
**** 对话
***** 转录
男：半年不见，你比以前苗条多了。怎么，最近减肥呢？[[file:837f3613-60cb-48fc-b273-a9cdffd1401b.mp3][(audio)]]
女：我比以前瘦了吗？我这几个月一直在健身，看来真有效果。[[file:6bfbbbc8-e9ed-45a9-940f-8acb3dedfc6e.mp3][(audio)]]
***** 音频
66abddde-45f7-4fa9-81d2-ae194024ee56.mp3
**** 问题
***** 转录
关于女的，下列哪项正确？
***** 音频
99d5f77c-dd6f-4f39-86f7-59270b52309b.mp3
**** 选择
***** A
身体不好
***** B
经常健身
***** C
不想减肥
***** D
正在节食
**** 答案
B
*** 6
:PROPERTIES:
:ID: a0175b2e-12c0-4549-a927-08fed77de446
:END:
**** 对话
***** 转录
女：星期六下午有个聚会，给丽丽过生日，你一定要去啊。[[file:f1fc8a8d-dee0-4eb2-91d6-721f67d62a26.mp3][(audio)]]
男：我晚点儿过去，行吗？下午正好有培训课。你们几点开始？[[file:9aeb6d16-5355-4e6d-930a-a59652a6c28c.mp3][(audio)]]
***** 音频
15f8ee28-937c-4ad3-86e6-273d814f8c19.mp3
**** 问题
***** 转录
星期六女的希望男的做什么？
***** 音频
b732c17c-b0ef-4b3c-a793-fa4dfc3805dd.mp3
**** 选择
***** A
去上培训课
***** B
去参加聚会
***** C
陪她去看电影
***** D
给她床祝生日
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
女：我看见林林又在吃零食了，你少给他买点儿这些东西吧。
男：我不是答应他考试成绩好可以满足他一个要求吗？
女：这算什么要求？你也不能不讲原则啊。
男：油炸食品不健康，这个我懂，少吃一点儿就行了。
***** 音频
b0c59d1b-150c-4684-b1ac-9ed4d71778cd.mp3
**** 问题
***** 转录
他们主要在谈什么问题？
***** 音频
4d7ff4e6-7d02-4c2c-8e80-050562376407.mp3
**** 选择
***** A
如何提高考试成绩
***** B
孩子该不该吃零食
***** C
油炸食物有什么危害
***** D
怎么给孩子提出要求
**** 答案
B
*** 8
**** 对话
***** 转录
男：服务员，给我们推荐几个你们这儿的特色菜吧。
女：我们这儿是川菜馆，麻婆豆腐来的客人基本上都会点。
男：好，来一个。
女：您喜欢海鲜吗？今天的干烧黄鱼是特价。
***** 音频
20b9a057-4fea-459a-b579-263441751489.mp3
**** 问题
***** 转录
根据对话，下列哪项正确？
***** 音频
b90473ef-1816-4601-9df0-008e829d4f73.mp3
**** 选择
***** A
男的喜欢海鲜
***** B
男的没点豆腐
***** C
女的是饭馆老板
***** D
女的推荐干烧黄鱼
**** 答案
D
*** 9
**** 对话
***** 转录
男：奶奶，超市里的有机蔬菜是无污染的绿色食品，卖得可好了。
女：就是价钱比肉还贵。
男：现在人们都追求健康，不是每天大鱼大肉才是吃得好了。
女：那倒是，现在很多人得了富贵病，还不是吃得太好了？
***** 音频
27d4baf5-ce8c-47e6-88c2-b84925b250b0.mp3
**** 问题
***** 转录
根据对话，女的同意哪种看法？
***** 音频
5b556fb6-0ca0-4b1d-9404-3ee79533673b.mp3
**** 选择
***** A
应该买绿色食品
***** B
超市的菜更安全
***** C
大鱼大肉不健康
***** D
少吃粮食多吃菜
**** 答案
C
*** 10
**** 对话
***** 转录
女：我做了些点心，你尝尝看。
男：味道真不错，很好吃。跟谁学的？
女：这是我们家乡的特产，过年回家时奶奶教我做的。
男：怪不得我从来都没吃过呢。
***** 音频
57c32b2e-8aa4-4c32-925a-134524a817a5.mp3
**** 问题
***** 转录
关于这种点心，可以知道什么？
***** 音频
7f637deb-580e-4d3c-9507-3fe35b0ed613.mp3
**** 选择
***** A
过年时才会吃
***** B
女的自己做的
***** C
昧道有点儿怪
***** D
男的以前吃过
**** 答案
B
*** 11-12
**** 对话
***** 转录
男：我教你啊，把肉切丝，辣椒、土豆也都一样，炒的时候，少放酱油。
女：是想清淡点儿吗？
男：咸淡自己根据口味，主要是做出来颜色漂亮。
女：那加点儿胡萝卜丝不就更好看了？
男：那是当然。不过，有人不喜欢那味道。
女：我没问题，营养丰富更重要。
***** 音频
d6040752-56c4-497e-8beb-a2cc577cf4f2.mp3
**** 题目
***** 11
****** 问题
******* 转录
男的让女的怎么做这个菜？
******* 音频
c184ca09-cc32-4063-b599-e31b3051ac8f.mp3
****** 选择
******* A
肉和菜切成丝
******* B
多放点儿酱油
******* C
显道清淡一点儿
******* D
加一点儿胡莪卜
****** 答案
A
***** 12
****** 问题
******* 转录
做菜时，女的更看重什么？
******* 音频
8ee068a1-1d65-4612-bdd4-1df35dbfffc0.mp3
****** 选择
******* A
颜色
******* B
显道
******* C
材料
******* D
营养
****** 答案
D
*** 13-14
**** 段话
***** 转录
提起新疆的吐鲁番，就不得不说葡萄。这里为什么会生长出这么好吃的葡萄呢？原来这与当地的气候有很大的关系。这里气候干燥，晴天多，阴天少，再加上纬度比较高，夏季日照时间长，日照强度大，可以让葡萄进行长时间的光合作用，以制造出大量的有机物质和糖分；而到了晚上，气温降得很低，植物的呼吸作用减弱，这样就减少了养分的损失。所以果实中能够积累大量的营养物质，不但个儿长得大，而且十分甜美。
***** 音频
f77af476-7650-4a96-a4a1-47a9e78d5c94.mp3
**** 题目
***** 13
****** 问题
******* 转录
根据这段话，吐鲁番的葡萄好吃跟什么有很大关系？
******* 音频
cf6644e3-d32b-4865-b1a0-24f1a877aa5f.mp3
****** 选择
******* A
气候
******* B
温度
******* C
品种
******* D
一水
****** 答案
A
***** 14
****** 问题
******* 转录
根据这段话，晚上气温低可以使葡萄怎么样？
******* 音频
a425b053-8246-4099-94c2-b6c3b6e550bf.mp3
****** 选择
******* A
停止呼吸
******* B
个儿长得大
******* C
减少养分损失
******* D
制造大量精分
****** 答案
C
* 阅读
** 第一部分
*** 段话
白荷是十字花科的蔬菜，原产于中国北方，后引种南方，直到19世纪才传人日本和欧美。
白菜在中国的栽种历史非常[[gap][15]]，早在三国时期的《吴录》中，就有“陆逊催人种豆、萝”这样的内容，“菪”指的就是白菜。不过，到了隋唐以后，白菜的种植才得到大面积[[gap][16]]。
白菜耐保存，中国人特别是北方人对白菜有特殊的感情。在经济囱难时期，白菜是他们整个冬季的主要蔬菜，一个家庭往往需要购买数百斤白荷[[gap][17]]，因此白菜在中国就有了炖、炒、腌、拌等各种做法。冬季，最低气温[[gap][18]]零下5左有时，白荷仍然可以在室外存放过冬，外部叶子干燥后可以为内部保湿。
白菜不仅叹有丰富的维生素、蛋白质等营养成分，还具有一定的药用价值，俗话说：“鱼生火，肉生疾，白菜豆腐保平安”
*** 题目
**** 15
***** 选择
****** A
情楚
****** B
简单
****** C
悠久
****** D
复杂
***** 答案
C
**** 16
***** 选择
****** A
上升
****** B
接受
****** C
利用
****** D
推广
***** 答案
D
**** 17
***** 选择
****** A
来减少出门的次数
****** B
好节省家庭的花费
****** C
以度过温长的冬季
****** D
以补充粮食的不足
***** 答案
C
**** 18
***** 选择
****** A
有
****** B
为
****** C
变
****** D
降
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 6036b030-0dcf-49a1-88b5-0442ed4ecd73
:END:
**** 段话
蔬菜中的维生素C和维生素B都怕热、怕煮，在炒蔬菜的时候，如果用小火炒，维生素会损失很多，如果用大火快炒，维生素损失只有1／15。所以，炒蔬菜一定要用旺火。
**** 选择
***** A
炒菜比煮菜更健康
***** B
火的大小要视蔬菜种类而定
***** C
小火炒菜破坏维生素C最多
***** D
大火快炒能保留蔬菜更多营养
**** 答案
D
*** 20
:PROPERTIES:
:ID: 1ece11d8-638a-4eaf-83d2-406c15f301be
:END:
**** 段话
水煮牛肉是中国传统的菜品，通过大火焖煮的方式，让牛肉中那些人体难以消化的粗纤维更好地分解，让牛肉更香浓。但是，炖煮的过程中，一些营养成分会流入汤料中，造成极大的浪费，人体也无法完全吸收。
**** 选择
***** A
水煮牛肉不容易消化
***** B
水煮牛肉制作很复杂
***** C
水煮牛肉要文火慢炖
***** D
水煮牛肉的味道香浓
**** 答案
D
*** 21
:PROPERTIES:
:ID: a87ef922-b0a4-45f9-9254-586936ae03ec
:END:
**** 段话
无论是蔬菜还是海鲜，或是肉类，在烹饪前都需要用水清洗。很多人为了节约用水，往往用盆把水接住，然后反复洗不同的食材，这种做法不仅不能将食材洗干净，反而会造成二次污染，危害我们的健康。因此，清洗食材的时候，用流动的清水是最好的。
**** 选择
***** A
海鲜或肉类更需要清洗
***** B
有些食材反复洗才干净
***** C
用盆接水洗菜有害健康
***** D
用流动的水洗菜浪费水
**** 答案
C
*** 22
:PROPERTIES:
:ID: 65d9e8c8-5c90-40b8-a2d1-55646491d217
:END:
**** 段话
孩子是西式快餐厅的主角，有的家长为了不让孩子吃垃圾食品，可谓想尽办法。其实，西式快餐中并不都是垃圾食品，也有一些有益食品，如土豆泥、蔬菜沙拉等。而且，偶尔吃一两次并不会给健康带来多么大的影响。我们应该理性和冷静地看待西式快餐，在味道和营养中获得平衡。
**** 选择
***** A
西式快餐也有健康的食物
***** B
快餐厅是孩子们表演的舞台
***** C
土豆泥和蔬菜沙拉是垃圾食品
***** D
家长希望滋味和营养能够平衡
**** 答案
A
** 第三部分
*** 23-25
**** 段话
臭豆腐是经过发酵后有特殊气味的小块豆腐，闻着臭，吃着香。
说起臭豆腐的由来，还有这么一段传说。据说清朝康熙八年，安徽有个名叫王致和的读书人来京考试，不幸没有考中。身上带的钱已花完无法返乡，王家原以做豆腐为生，王致和也会这门手艺，于是，为挣够回家路费，他就在北京住了下来，做起了卖豆腐的小买卖。他每天早早就起来制作豆腐，然后挑着豆腐走街串巷叫卖，但生意总是很清淡，仅仅能够吃饱肚子。
有一次，他做的豆腐剩了不少，他舍不得倒掉，又怕豆腐放久了会变坏，就在豆腐上撒了一些盐，放在罐子里存放起来。过了一段时间，他取出一看，大吃一惊。原来豆腐变成了灰绿色，而且发出一股奇特的味道。他大胆地尝了尝，味道鲜美而可口，这可真使他意想不到。于是，他按照这种方法制作豆腐，并给这种豆腐起名为“臭豆腐”。这一新产品一进人市场就深受顾客欢迎，供不应求。王致和的臭豆腐生意越做越好。从此，臭豆腐的“臭名”便传开了。
**** 题目
***** 23
****** 问题
根据上文可以知道，王致和来京是想：
****** 选择
******* A
读书求学
******* B
参加考试
******* C
学做豆腐
******* D
独立生活
****** 答案
B
***** 24
****** 问题
王致和为什么做起了卖豆腐的生意？
****** 选择
******* A
讨厌学习
******* B
想留在北京
******* C
喜欢吃豆腐
******* D
要赚钱回家
****** 答案
D
***** 25
****** 问题
王致和是怎么发明“臭豆腐”的？
****** 选择
******* A
不断研究
******* B
意外发明
******* C
朋友指点
******* D
长辈所教
****** 答案
B
*** 26-28
**** 段话
中国饮食重视“味”，而西方是一种理性饮食观念，不论食物的色、香、味、形如何，营养一定要得到保证。西方人更关心自己一天要获取多少热量、维生素、蛋白质等问题，即使口味千篇一律，也一定要吃下去——因为有营养。在宴席上，可以讲究餐具，讲究用料，讲究服务，讲究食材形、色方面的搭配，可不管怎么豪华高档，从洛杉矶到纽约，牛排都只有一种味道。作为菜肴，鸡就是鸡，牛排就是牛排，就是有搭配，也是在盘中进行的。一盘“法式羊排”，一边放土豆泥，旁边摆块羊排，另一边配煮青豆，加几片西红柿就可以了。色彩上对比鲜明，但在味道上各种原料互不相干、互不调和，各是各的味，简单明了。
中国是很重视“吃”的民族，“民以食为天”，从这句俗语就可以看出中国人对吃的重视程度。如果一种文化把吃看成第一位的事，那么就会出现两种现象：一方面会把这种吃的功能发挥到顶峰，不仅维持生存，还利用它保持健康；另一方面，对吃的过分重视，会促使人不断地追求美味。中国人对美味的追求达到了极高的程度，就连中国人到国外做生意，也常有人以开餐馆为业。但我们的很多传统食品都要经过油炸或长时间的文火炖煮，菜肴的营养成分受到了破坏。当我们对美味过分追求，把它作为第一要求时，我们往往会忽视对食物最根本的营养要求。
**** 题目
***** 26
****** 问题
作者认为，中国的饮食文化更追求什么？
****** 选择
******* A
营养
******* B
形状
******* C
色彩
******* D
味道
****** 答案
D
***** 27
****** 问题
根据上文，西方人吃饭时更重视什么？
****** 选择
******* A
用餐的环境
******* B
食物的营养
******* C
食材的质量
******* D
使用的餐具
****** 答案
B
***** 28
****** 问题
上文主要讲的是：
****** 选择
******* A
中国人重视饮食
******* B
中外食材的对比
******* C
中外不同的饮食观念
******* D
食物色、形、味的搭配
****** 答案
C
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
