:PROPERTIES:
:CREATED: [2022-04-23 12:38:21 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-04-23 12:38:23 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-23 12:41:09 -05]
:END:

1. d

电影院 | diànyǐngyuàn | cinema | cine ;

2. a

等 | děng | wait | esperar ;

3. e

晴 | qíng | clear, fine (weather) | claro ;

4. f

一百 | yì bǎi | one hundred | cien ;

5. c

打电话 | dǎ diànhuà | call | llamar ;

6. b

玩儿 | wánr | play | jugar ;

** 2
:PROPERTIES:
:CREATED: [2022-04-23 12:41:03 -05]
:END:

1.

电视 | diànshì | TV | televisor ;

2.

电影 | diànyǐng | moie | película ;

3.

电话 | diànhuà | computer | computadora ;

4.

电脑 | diànnǎo | computer | computadora ;

* Text
:PROPERTIES:
:CREATED: [2022-04-23 12:42:32 -05]
:END:

** 1. 在教室
:PROPERTIES:
:CREATED: [2022-04-23 12:43:19 -05]
:ID: f6d060b8-da4d-4b4e-8eab-29a9c09a9d32
:END:

Ａ：你看过那个电影没有？
Ｂ：没看过，听说很有意思。
Ａ：那我们下个星期一起去看吧？
Ｂ：可以，但是我女朋友也想去。

new words

有意思 | yǒu yìsi | interesting, fun | interesante, divertido ;

但是 | dànshì | but, still, yet ;

** 2. 在办公室
:PROPERTIES:
:CREATED: [2022-04-23 12:55:45 -05]
:ID: 9eb14dfd-4517-449a-8509-2fa008647541
:END:

Ａ：听说你去过中国，还想去吗？
Ｂ：我虽然去过好几次，但是还想再去玩儿玩儿。
Ａ：那我们一起去吧。
Ｂ：好啊，到时候我给你打电话。

new words

虽然 | suīrán | although, though | aunque ;

次 | cì | time | tiempo ;

玩儿 | wánr | to play, to have fun | jugar, divertirse ;

** 3. 在房间
:PROPERTIES:
:CREATED: [2022-04-23 12:57:28 -05]
:ID: 46014daa-6be4-4444-8f1e-2bdf2362cf73
:END:

Ａ：明天天气怎么样？
Ｂ：虽然是晴天，但是很冷。
Ａ：那还能去跑步吗？
Ｂ：可以，但是你自己去吧，我还有很多事情要做。

new words

晴 | qíng | sunny, fine, clear | soleado, bien, despejado ;

** 4. 在商店
:PROPERTIES:
:CREATED: [2022-04-23 12:59:11 -05]
:ID: 631910b6-f4b1-46d2-a47c-eca0ff7fe4b6
:END:

Ａ：你在这个商店买过东西没有？
Ｂ：买过一次，这儿的东西还可以，就是不便宜。
Ａ：我喜欢这件衣服，但是觉得有点儿贵。
Ｂ：两百块还可以，喜欢就买吧。

new words

百 | bǎi | hundred | cien ;

* Notes
:PROPERTIES:
:CREATED: [2022-04-23 13:04:20 -05]
:END:

** 1. The structural particle "过"
:PROPERTIES:
:CREATED: [2022-04-23 13:25:04 -05]
:END:

A verb followed by the structural particle "过" usually indicates a past experience action which hasn't lasted to the present. For example:

他们来过我家。
pi: tāmen láiguo wǒ jiā
en: they came to my house
es: vinieron a mi casa

我看过那个电影。
pi: wǒ kànguo nà ge diànyǐng
en: I've seen that movie
es: he visto esa película

我去过中国。
pi: wǒ qùguo zhōngguó
en: I've been to China
es: he estado en China

In the negative form, "没（有）" is added before the verb. For example:

他们没（有）来过我家。
pi: tāmen méi yǒu láiguo wǒ jiā
en: they didn't come to my house
es: no han venido a mi casa

我没（有）看过那个电影。
pi: wǒ méi (yǒu) kànguo nà ge diànyǐng
en: I have not seen that movie
es: no he visto esa película

我没（有）去过中国。
pi: wǒ méiyǒu qùguo zhōngguó
en: I have never been to China
es: nunca he estado en china

In the interrogative form, "没有" is added at the end of the sentence. For example:

他们来过你家没有？
pi: tāmen láiguo nǐ jiā méiyǒu?
en: have they ever come to your house?
es: ¿fueron a tu casa?

你看过那个电影没有？
pi: nǐ kànguo nà ge diànyǐng méiyǒu?
en: have you seen that movie?
es: ¿has visto ya esa película?

你去过中国没有？
pi: nǐ qùguo zhōngguó méiyǒu?
en: have you ever been to China?
es: ¿has estado alguna vez en China?

** 2. "虽然……, 但是……"
:PROPERTIES:
:CREATED: [2022-04-23 13:25:12 -05]
:END:

The conjunctions "虽然……, 但是……" connect two clauses, forming a complex sentence indicating an adversative relation. For example:

虽然外面很冷，但是房间里很热。
pi: suīrán wàimiàn hěn lěng, dànshì fángjiān lǐ hěn rè
en: althought it was cold outside, it was hot in the room
es: aunque hace frío afuera, la habitación esta caliente

虽然汉字很难，但是我很喜欢写汉字。
pi: suīrán hànzì hěn nàn, dànshì wǒ hěn xǐhuan xiě hànzì
en: although it is hard write kanji, I enjoy writing the characters
es: aunque los caracteres chinos son dificiles, disfruto escribirlos

虽然是晴天，但是很冷。
pi: suīrán shì qīngtiān, dànshì hěn lěng
en: although it is sunny, it is cold
es: aunque es un dia soleado, hace frío

** 3. The complement of frequency "次"
:PROPERTIES:
:CREATED: [2022-04-23 13:30:57 -05]
:END:

The complement of frequency "次" is usllya used after the predicate verb, indicating the number of times that an action has taken place. For example:

我们看过三次电影。
en: we've seen the movie three times
es: hemos visto la película tres veces

他们坐过一次飞机。
en: they have been on a plane once
es: ellos han estado en avión una vez

我（在这个商店）买过一次（东西）。
en: I have bought something from this store once
es: una vez compré algo en esta tienda

When the object of a verb is a place, the complement of frequency can be put either before or after the object. For example

我们去过三次（北京）。
我们去过（北京）三次。


他们来过一次（中国）。
他们来过（中国）一次。


我上星期去过一次（医院）。
我上星期去过（医院）一次。

When the object is a personal pronoun, the complement of frequency should be put after the object. For example

我们找过（他）三次。
他们看过（我）一次。
老师叫过（我）两次。

* Exercises
:PROPERTIES:
:CREATED: [2022-04-23 13:40:02 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-04-23 13:40:06 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-23 13:43:38 -05]
:END:

他们看过那个电影吗？

没看过，但是他们下个星期可能去看那个电影。

*** 2
:PROPERTIES:
:CREATED: [2022-04-23 13:43:35 -05]
:END:

他们想几个人去看电影？

三个人，两个朋友和女朋友。

*** 3
:PROPERTIES:
:CREATED: [2022-04-23 13:43:39 -05]
:END:

他们想来中国做什么？

他们想去中国玩儿玩儿。

*** 4
:PROPERTIES:
:CREATED: [2022-04-23 13:45:29 -05]
:END:

为什么她明天不能去跑步？

因为她还有很多事情要做。

*** 5
:PROPERTIES:
:CREATED: [2022-04-23 13:50:07 -05]
:END:

女的觉的这个商店的东西怎么样？

她喜欢一个衣服，但是她觉的那件有点儿贵。

** 3
:PROPERTIES:
:CREATED: [2022-04-23 13:53:25 -05]
:END:

你以前（吃过）这种水果吗？
pi: nǐ yǐqián chīguo zhè zhǒng shuǐguǒ ma?
en: have you ever eaten this fruit before?
es: ¿has comido alguna vez esta fruta?

我去年（看过）你姐姐一次。
pi: wǒ qù nián kànguo nǐ jiějie yī cì
en: I saw your sister once last year
es: vi a tu hermana una vez el año pasado

虽然天气很冷，但是他（游泳）。
pi: suīrán tiānqì hěn lěng, dànshì tā yóuyǒng
en: although the weeather was cold, he swam
es: aunque hace frío, el nada

虽然英语很难，但是她（学习）。
pi: suīrán yīngyǔ hěn nán, dànshì tā xuéxí
en: although English is difficult, she studies
es: aunque el inglés es difícil, ella estudia

* Application
:PROPERTIES:
:CREATED: [2022-04-23 14:15:43 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-23 14:15:49 -05]
:END:

虽然这本书有意思，但是我没钱买。

虽然我比我哥哥跑的快，但是他比我骑的快。

** 2
:PROPERTIES:
:CREATED: [2022-04-23 14:15:50 -05]
:END:

我没有去过中国。
pi: wǒ méiyǒu qùguo zhōngguó
en: I have never been to China
es: nunca he estado en China

我去过纽约一次。
pi: wǒ qùguo niǔyuē yi cì
en: I have been to New York once
es: he estado en Nueva York una vez

我在美国买过一个耳机。
pi: wǒ zài měiguó mǎi guo yī ge ěrjī
en: I have bought a headset in the United States
es: he comprado unos auriculares en Estados Unidos

