:PROPERTIES:
:CREATED: [2022-03-15 20:04:35 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-03-08 09:35:31 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-08 09:35:41 -05]
:END:

起床 | qǐ chuáng | wake up | despertarse ;

跑步 | pǎo bù | to run | correr ;

吃药
pi: chī yào
en: to take medicine
es: tomar medicina

生病 | shēng bìng | to fall ill, to be sick | enfermarse | verb ;

休息 | xiūxi | to have a rest | descansar | verb ;

出院 | chū yuàn | leave hospital | abandonar el hospital ;

马丁 | mǎdīng | Martin (male given name) | Martin (female given name) ;

1. A
2. D
3. B
4. E
5. F
6. C

** 2
:PROPERTIES:
:CREATED: [2022-03-08 09:35:35 -05]
:END:


Picture 1

马丁每天早上吃早饭。
pi: mǎdīng měitiān zǎoshang chī zǎofàn

Picture 2

马丁每天下午做运动。
pi: mǎdīng měitiān xiàwǔ zuò yùndòng

马丁每天下午去健身房做运动。
pi: mǎdīng měitiān xiàwǔ qù jiànshēnfáng zuò yùndòng

Picture 3

马丁每天晚上看电视。
pi: mǎdīng měitiān wǎnshang kàn diànshì

马丁每天晚上看电影。
pi: mǎdīng měitiān wǎnshang kàn diànyǐng

马丁和他的女朋友每天晚上看电视。
pi: mǎdīng hé tā de nǚpéngyǒu měitiān wǎnshang kàn diànshì

马丁和他的女朋友每天晚上看电影。
pi: mǎdīng hé tā de nǚpéngyǒu měitiān wǎnshang kàn diànyǐng

Picture 4
马丁星期六和星期天旅游。
pi: mǎdīng xīngqī liù hé xīngqī tiān lǚyóu

* Text
:PROPERTIES:
:CREATED: [2022-03-08 10:14:19 -05]
:END:

** 1. 在运动场 | On the playground
:PROPERTIES:
:CREATED: [2022-03-08 10:14:24 -05]
:ID: 584f1350-ade0-400f-9abf-c8652108c534
:END:

Ａ：你很少生病，是不是喜欢运动？
pi: nǐ hěn shǎo shēng bìng, shì bu shì xǐhuan yùndòng
en: You rarely get sick, do you like to exercise?
es: Rara vez te pones enfermo, ¿te gusta hacer ejercicio?

Ｂ：是啊，我每天早上都要出去跑步。
pi: shì a, wǒ měitiān zǎoshang dōu yào chūqu pǎo bù
en: Yes, I go out for a run every morning.
es: Sí, salgo a correr todas las mañanas.

Ａ：你每天几点起床？
pi: nǐ měitiān jǐ diǎn qǐ chuáng
en: What time do you get up every day?
es: ¿A qué hora se levanta cada día?

Ｂ：我每天六点起床。
pi: wǒ měitiān liù diǎn qǐ chuáng
en: I get up at six every day.
es: Me levanto a las seis todos los días.

New words

生病 | shēng bìng | to fall ill, to be sick | enfermarse | verb ;

每 | měi | every, each | todos | pronoun ;

早上 | zǎoshang | morning | mañana ;

跑步 | pǎobù | to run | correr ;

起床 | qǐ chuáng | to get up, to get out of bed | wake up ;

Notes

每天 | měitiān | every day | todos los días | pronoun ;

** 2. 在医院 | In the hospital
:PROPERTIES:
:CREATED: [2022-03-08 10:25:11 -05]
:ID: 599914e9-acd9-4a29-ad0a-1f1d5da6b809
:END:

Ａ：吃药了吗？现在身体怎么样？
pi: chī yào le ma? xiànzài shēntǐ zěnmeyàng?
en: Did you take your medication? How is your health now?
es: ¿Te has tomado la medicación? ¿Cómo está su salud ahora?

Ｂ：吃了。现在好多了。
pi: chī le. xiànzài hǎo duō le
en: Yes, I did. I am much better now.
es: Sí, lo hice. Ahora estoy mucho mejor.

Ａ：什么时候能出院？
pi: shénme shíhou néng chū yuàn
en: When will you be discharged from the hospital?
es: ¿Cuándo le darán el alta?

Ｂ：医生说下个星期。
pi: yīshēng shuō xià ge xīngqī
en: The doctor said next week.
es: El médico dijo que la próxima semana.

New words

药 | yào | medicine, drug | medicina | noun ;

身体 | shēntǐ | body | salud, cuerpo | verb ;

出院 | chū yuàn | to leave hospital, to be discharged from hospital | dar de alta | verb ;

出 | chū | to come, go out | salir | verb ;

** 3. 在操场  | On the playground
:PROPERTIES:
:CREATED: [2022-03-08 10:31:36 -05]
:ID: 345dfcb9-ef30-4aa8-86ff-4cd1578b6207
:END:

Ａ：大卫今年多大？
pi: dàwèi jīnnián duō dà
en: How old is David this year?
es: ¿Qué edad tiene David este año?

Ｂ：二十多岁。
pi: ershí duō suì
en: In his twenties.
es: En sus veinte años.

Ａ：他多高？
pi: tā duō gāo
en: How tall is he?
es: ¿Qué altura tiene?

Ｂ：一米八几。
pi: yì mǐ bā jǐ
en: One meter eight or so.
es: Un metro ocho más o menos.

Ａ：你怎么知道这么多啊？
pi: nǐ zěnme zhīdào zhème duō a
en: How do you know so much?
es: ¿Cómo sabes tanto?

Ｂ：他是我同学。
pi: tā shì wǒ tóngxué
en: He is my classmate.
es: Es mi compañero de clase.


New words

知
pi: zhī

道
pi: dào

高 | gāo | tall, high | alto ;

米 | mǐ | meter | metro ;

知道 | zhīdào | to know | saber ;

** 4. 在房间 In the room
:PROPERTIES:
:CREATED: [2022-03-08 10:59:54 -05]
:ID: c1d93b2d-87fe-476c-9402-9d5dd0e48f7c
:END:

Ａ：张老师星期六也不休息啊？
pi: zhāng lǎoshī xīngqī liù yě bù xiūxi a
en: Mr. Zhang doesn't have Saturday off either?
es: ¿El Sr. Zhang tampoco se toma los sábados libres?

Ｂ：是啊，他这几天很忙，没有时间休息。
pi: shì a, tā zhè jǐ tiān hěn máng, méiyǒu shíjiān xiūxi
en: Yes, he is very busy these days, so he has no time to rest.
es: Sí, estos días está muy ocupado y no tiene tiempo para descansar.

Ａ：那会很累吧？
pi: nà huì hěn lèi ba
en: That's very tiring, isn't it?
es: Eso es muy cansado, ¿no?

Ｂ：他每天回来都很累。
pi: tā měi tiān huílai dōu hěn lèi
en: He comes back tired every day.
es: Vuelve cansado todos los días.

New words

休息
pi: xiūxi
en: to have or take a rest
es: descansar

忙
pi: máng
en: busy
es: ocupado

时间
pi: shíjiān
en: time
es: tiempo

* Notes
:PROPERTIES:
:CREATED: [2022-03-08 22:41:29 -05]
:END:
** Questions using 是不是
:PROPERTIES:
:CREATED: [2022-03-08 22:33:43 -05]
:END:

If one raises a question and is somehow certain about a fact or situation, they can use this kind of question to confirm their guess. "是不是" (literally, "yes or no") is usually used before the predicate or at the beginning or end of a sentence. For example,

你很少生病，是不是喜欢运动？
pi: nǐ hěn shǎo shēng bìng, shí bú shì xǐhuan yùndòng
en: You rarely get sick, do you like sports?
es: Rara vez te enfermas, ¿te gusta el deporte?

是不是明天爸爸休息？
pi: shì bú shì míngtiān bàba xiūxi
en: Isn't tomorrow Dad's day off?
es: ¿No es cierto que mañana es el día libre de papá?

我们星期一去北京，是不是？
pi: wǒmen xīngqī yì qù běijīng, shì bú shì
en: We're going to Beijing on Monday, aren't we?
es: Nos vamos a Pekín el lunes, ¿no?

** The pronoun "每"
:PROPERTIES:
:CREATED: [2022-03-08 22:49:10 -05]
:END:

"每" is used before a measure word, indicating each or every individual or group in the whole, for example, "每天" (every day), "每年" (every year), "每个月" (every month) and "每个星期" (every week).

山姆每年都去中国旅游。
pi: shān mǔ měinián dōu qù zhōngguó lǚyóu
en: Sam travels to China every year.
es: Sam viaja a China todos los años.

你每个星期六都工作吗？
pi: nǐ měi gè xīngqī liù dōu gōngzuó ma
en: Do you work every Saturday?
es: ¿Trabajas todos los sábados?

我每天六点起床。
pi: wǒ měitiān liù diǎn qǐchuáng
en: I get up at six every day.
es: Me levanto a las seis todos los días.

** The interrogative pronoun "多"
:PROPERTIES:
:CREATED: [2022-03-08 22:56:41 -05]
:END:

The interrogative pronoun "多" is used before an adjective, asking about  the degree of something. A specific quantity should be given to anser the question. For example

形容词
pi: xíngróngcí
en: adjective
es: adjetivo

|---------+----+--------|
| Subject | 多 | 形容词 |
|---------+----+--------|
| 你      | 多 | 大？   |
| 大卫    | 多 | 高？   |
| 他      | 多 | 高？   |
|---------+----+--------|

你多大？
pi: nǐ duō dà
en: how old are you?
es: ¿cuántos años tienes?

大卫多高？
pi: dàweì duō gāo
en: how tall is David?
es: ¿cuántos mide David?

他多高？
pi: tā duō gāo
en: how tall is he?
es: ¿cuánto mide él?

Example

Ａ：你多大？
pi: nǐ duō dà
en: how old are you?
es: ¿cuántos años tienes?

Ｂ：我16岁
pi: wǒ shíliù suì
en: I'm 16 years old
es: Tengo 16 años

Example

王医生的儿子多jj高？
pi: wáng yīshēng de èrzi duō gāo
en: how tall is Dr. Wang's son?
es: ¿Cuánto mide el hijo de Dr. Wang?

他儿子一米七。
pi: tā èrzi yī mǐ qī
en: His son is one meter seven
es: Su hijo mide 1.70

Example

他多高？
pi: tā duō gāo
en: how tall is he?
es: ¿cuánto mide él?

一米八几。
pi: yī mǐ bā jǐ
en: one meter eight or so.
es: 1 metro 80 por ahí.

* Exercises
:PROPERTIES:
:CREATED: [2022-03-08 23:13:50 -05]
:END:


** Role play the dialogues
:PROPERTIES:
:CREATED: [2022-03-08 23:26:37 -05]
:END:
** Answer the question based on the dialogues
:PROPERTIES:
:CREATED: [2022-03-09 05:32:04 -05]
:END:

他为什么很少生病？
因为他喜欢运动。他每天都要出去跑步。

他每天几点起床？
他每天六点起床。

她现在身体怎么样？
她现在身体好多了。

大卫今年多高？多大？
他有一米八几。他二十多岁。

张老师星期六休息吗？
没有，他这几天很忙。
pi: méiyǒu, tā zhè jǐ tiān hěn máng.
** Describe the pictures using the newwly-learned language points and words
:PROPERTIES:
:CREATED: [2022-03-09 05:32:18 -05]
:END:

安妮  | ān nī | Annie (female given name) | Annie (nombre de mujer) ;

小丽（这几）天都很忙，也很累。
小丽这几天都很忙，也很累。
pi: xiǎolì zhèjǐ tiān dōu hěn máng, yě hěn lèi.
en: Xiao Li is very busy and tired these days.
es: Xiao Li ha estado muy ocupado y cansado estos días.

他每天早上出去（跑步），身体很好。
他每天早上出去跑步，身体很好。
pi: tā měitiān zǎoshang chūqu pǎobù, shēntǐ hěn hǎo
en: He goes out for a run every morning and is in great shape.
es: Sale a correr todas las mañanas y está en forma

王医生的儿子多（高）？
王医生的儿子多高？
pi: wáng yīshēng de érzi duō gāo
en: How tall is Dr. Wang's son?
es: ¿Cuánto mide el hijo del Dr. Wong?

我听说安妮（生病）了，我想去看看她。
我听说安妮生病了，我想去看看她。
pi: wǒ tīngshuō Ānni shēngbìng le, wǒ xiǎng qù kànkàn tā
en: I heard that Annie is sick, I want to go see her.
es: Escuché que Annie está enferma y quiero ir a verla.

* Pronunciation
:PROPERTIES:
:CREATED: [2022-03-12 21:00:02 -05]
:END:

** Medium-stressed + Light + Stressed
:PROPERTIES:
:CREATED: [2022-03-12 21:01:23 -05]
:END:

收音机
pi: shōuyīnjī
en: radio
es: radio

新加坡
pi: xīnjiāpō
en: Singapore
es: Singapur

好莱坞
pi: hǎoláiwù
en: Hollywood
es: Hollywood

电视剧
pi: diànshìjù
en: TV series
es: serie de televisión

** Medium-stressed + Stressed + Light
:PROPERTIES:
:CREATED: [2022-03-12 21:06:13 -05]
:END:

胡萝卜 | húluóbo | carrot | zanahoria | ;

没关系 | méi guānxi | nevermind, that's ok, it doesn't matter | no hay problema, no te preocupes ;

老狐狸 | lǎohúli | old fox | viejo zorro | ;

毛孩子 | máo háizi | little child | pequeño niño | ;

** Stressed + Light + Light
:PROPERTIES:
:CREATED: [2022-03-12 21:12:09 -05]
:END:

什么的
pi: shénmede
en: and so on
es: y así sucesivamente

怪不得
pi; guàibude
en: no wonder
es: no es de extrañar

姑娘家
pi: gūniangjia
en: girl's family
es: familia de una niña

好者呢
pi: hǎozhene
en: And the good guys?
es: ¿Dónde están los buenos?

