* 听力

** 1

*** 1

**** transcript

在原始社会，生产力水平低下，人们为了获取食物、防御自然界的危险和侵袭，必须集体行动、共同协作才能生存下去。对集体的依赖性强化了人们的群体意识以及与集体同生共死的观念。

***** translation

In primitive societies, with low productivity, people had to act collectively and work together to survive in order to obtain food and defend themselves from the dangers and invasions of nature. The dependence on the collective strengthened people's sense of community and the concept of living and dying together with the collective.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

老话说得好，当一个人变为两个人，两个人守护着一个共同的家，就必须各尽其责，关心对方、体贴对方、照顾对方、 理解对方。美满的婚姻应该是两颗心的相守相依，两个人情感的互相给予。

***** translation

As the old saying goes, when a person becomes two people, two people guarding a common home, they must each do their part, care for each other, considerate of each other, care for each other, understand each other. A happy marriage should be the two hearts to keep each other, two people give each other emotions.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

暴发户文化最大的特征就是附庸风雅。暴发户的文化水平没有到，可是经济水平超过了，因此他会花很多冤枉钱，做很多冤大头的事情。比如说到哪儿都摆阔，房间里弄得金玉满堂，十分俗气。

***** translation

The most important feature of the culture of the rich is that it is attached to the elegant. The level of culture of the rich is not to, but the economic level exceeded, so he will spend a lot of money, do a lot of things that are unjust. For example, everywhere you go, the room is full of gold and jade, very vulgar.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

那些学贯古今的大学者，何不编写一册通俗的传统文化读本。不要长篇巨制，那是成心不让人读；不要东拼西凑，那样不值得读。只要以成熟的态度，把古人的生存方式、智慧、经验、得失告诉我们，就像一册新时代的《三字经》，岂不是好事！

***** translation

Why don't the great scholars, who have learned from the past and the present, write a popular book on traditional culture? Don't make a long book, that is intentionally not allowed to read: don't piece together, that is not worth reading. Just tell us the way of the ancients, their wisdom, experience, gains and losses in a mature manner, just like a book of "Three Character Classic" in the new era, wouldn't it be good!

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

她能说善辩，适合当律师。在课堂上，她们做过模拟律师辩护项目，她的表现极其出色。可她读过许多美国名律师写的小说，她知道律师们要想赚大钱就要为有钱有势的人打官司，她不想被钱、权、势所左右，所以她不想当律师。

***** translation

She is articulate and well suited to be a lawyer. In the classroom, they did a mock defense program, and she did extremely well. But she had read many novels written by famous American lawyers, and she knew that lawyers had to fight for rich and powerful people in order to make a lot of money, and she didn't want to be swayed by money, power and influence, so she didn't want to be a lawyer.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



