* 听力

** 1

*** 1

**** transcript

在原始社会，生产力水平低下，人们为了获取食物、防御自然界的危险和侵袭，必须集体行动、共同协作才能生存下去。对集体的依赖性强化了人们的群体意识以及与集体同生共死的观念。

***** translation

In primitive societies, with low productivity, people had to act collectively and work together to survive in order to obtain food and defend themselves from the dangers and invasions of nature. The dependence on the collective strengthened people's sense of community and the concept of living and dying together with the collective.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

老话说得好，当一个人变为两个人，两个人守护着一个共同的家，就必须各尽其责，关心对方、体贴对方、照顾对方、 理解对方。美满的婚姻应该是两颗心的相守相依，两个人情感的互相给予。

***** translation

As the old saying goes, when a person becomes two people, two people guarding a common home, they must each do their part, care for each other, considerate of each other, care for each other, understand each other. A happy marriage should be the two hearts to keep each other, two people give each other emotions.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

暴发户文化最大的特征就是附庸风雅。暴发户的文化水平没有到，可是经济水平超过了，因此他会花很多冤枉钱，做很多冤大头的事情。比如说到哪儿都摆阔，房间里弄得金玉满堂，十分俗气。

***** translation

The most important feature of the culture of the rich is that it is attached to the elegant. The level of culture of the rich is not to, but the economic level exceeded, so he will spend a lot of money, do a lot of things that are unjust. For example, everywhere you go, the room is full of gold and jade, very vulgar.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

那些学贯古今的大学者，何不编写一册通俗的传统文化读本。不要长篇巨制，那是成心不让人读；不要东拼西凑，那样不值得读。只要以成熟的态度，把古人的生存方式、智慧、经验、得失告诉我们，就像一册新时代的《三字经》，岂不是好事！

***** translation

Why don't the great scholars, who have learned from the past and the present, write a popular book on traditional culture? Don't make a long book, that is intentionally not allowed to read: don't piece together, that is not worth reading. Just tell us the way of the ancients, their wisdom, experience, gains and losses in a mature manner, just like a book of "Three Character Classic" in the new era, wouldn't it be good!

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

她能说善辩，适合当律师。在课堂上，她们做过模拟律师辩护项目，她的表现极其出色。可她读过许多美国名律师写的小说，她知道律师们要想赚大钱就要为有钱有势的人打官司，她不想被钱、权、势所左右，所以她不想当律师。

***** translation

She is articulate and well suited to be a lawyer. In the classroom, they did a mock defense program, and she did extremely well. But she had read many novels written by famous American lawyers, and she knew that lawyers had to fight for rich and powerful people in order to make a lot of money, and she didn't want to be swayed by money, power and influence, so she didn't want to be a lawyer.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：您今天能不能就马拉松这个话题和我们聊聊。
男：马拉松运动起源于一个古老的故事。公元前 490 年，波斯军队入侵希腊，在雅典城东北的马拉松平原登陆，准备攻打雅典。当时雅典将军手下只有一万多人，面对的是 10 万装备精良的敌人。雅典士兵拼死奋战，结果他们赢了。雅典统帅大声喊道：“我们应该立刻把消息传送给雅典人民，从这儿到雅典有很长的一段路，谁能去？”刚从战场上回来的菲迪皮德思说：“我能，我跑得比谁都快！”接着他就奔赴雅典城。当到达雅典的时候，菲迪皮德思已经筋疲力尽，他高喊出“高兴吧，我们胜利了”，就永远地倒下了。
女：很感人的一个故事，那这个故事怎么就变成了一项运动呢？
男：1896 年，第一届奥运会于雅典召开前，法国人米歇尔·布雷尔向现代奥林匹克运动的奠基人顾拜旦建议，增设一项以马拉松命名的长跑赛，以纪念马拉松战役和菲迪皮德思。希腊奥组委接受了这一建议，马拉松这个名词第一次出现在国际体坛。
女：那马拉松长跑跑的是什么路线呢？
男：就是昔日菲迪皮德思跑过的从马拉松到雅典的路线。
女：那之后呢？
男：之后几届奥运会的起点和终点都是组织者根据当地情况决定，长度也各不相同。直到 1908 年英国主办奥运会时，马拉松长跑总长度定为 42.195 公里，以后马拉松比赛的正式距离就以此为准了。
女：这项比耐力、比速度、比技能、比拼搏精神的运动一定有很多有趣的故事吧？
男：是啊。我最喜欢的是首届奥运会马拉松冠军的故事。比赛那天酷热难耐，路上灰尘满天，比赛的艰苦无法形容。希腊人路易斯第一个冲入运动场，全场欢声雷动，此时冠军已无悬念，担任总裁判的希腊王储情不自禁地陪着路易斯冲击终点。一束束鲜花，一件件礼物，投向人们崇拜的英雄，甚至有人高呼：让他当部长。
女：后来呢？
男：后来，他获得了希腊民族英雄的称号，仍然回到了偏僻的家乡，继续当他的乡村邮递员，和妻儿一起过着清贫的生活。

*** 音频

8800fd44-3924-4cbc-8c44-b844eeb6b278.mp3

*** 题目

**** 6

***** 问题

马拉松作为一项体育运动，是哪一年开始的？

***** 音频

55bf3720-3040-44f9-b23d-ed2e3d419466.mp3

**** 7

***** 问题

关于马拉松运动的起源，下列哪项正确？

***** 音频

9cc6cb66-4d88-429c-b043-84e2222124f3.mp3

**** 8

***** 问题

在奥运会上设立马拉松长跑项目是谁提出的？

***** 音频

2cffee10-4629-4670-8363-7f93f7badc79.mp3

**** 9

***** 问题

关于今天奥运会马拉松长跑总长度，下列哪项正确？

***** 音频

ba17d356-6185-4fc4-a53f-8e367104c820.mp3

**** 10

***** 问题

根据这段采访可以知道什么？

***** 音频

dcfd5101-863e-48d9-9a6d-b040d3f439e8.mp3

