* 听力

** 第二部分
:PROPERTIES:
:ID: e6245534-b395-4a47-a5cb-c7bef68a6f67
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：您今天能不能就马拉松这个话题和我们聊聊。
男：马拉松运动起源于一个古老的故事。公元前 490 年，波斯军队入侵希腊，在雅典城东北的马拉松平原登陆，准备攻打雅典。当时雅典将军手下只有一万多人，面对的是 10 万装备精良的敌人。雅典士兵拼死奋战，结果他们赢了。雅典统帅大声喊道：“我们应该立刻把消息传送给雅典人民，从这儿到雅典有很长的一段路，谁能去？”刚从战场上回来的菲迪皮德思说：“我能，我跑得比谁都快！”接着他就奔赴雅典城。当到达雅典的时候，菲迪皮德思已经筋疲力尽，他高喊出“高兴吧，我们胜利了”，就永远地倒下了。
女：很感人的一个故事，那这个故事怎么就变成了一项运动呢？
男：1896 年，第一届奥运会于雅典召开前，法国人米歇尔·布雷尔向现代奥林匹克运动的奠基人顾拜旦建议，增设一项以马拉松命名的长跑赛，以纪念马拉松战役和菲迪皮德思。希腊奥组委接受了这一建议，马拉松这个名词第一次出现在国际体坛。
女：那马拉松长跑跑的是什么路线呢？
男：就是昔日菲迪皮德思跑过的从马拉松到雅典的路线。
女：那之后呢？
男：之后几届奥运会的起点和终点都是组织者根据当地情况决定，长度也各不相同。直到 1908 年英国主办奥运会时，马拉松长跑总长度定为 42.195 公里，以后马拉松比赛的正式距离就以此为准了。
女：这项比耐力、比速度、比技能、比拼搏精神的运动一定有很多有趣的故事吧？
男：是啊。我最喜欢的是首届奥运会马拉松冠军的故事。比赛那天酷热难耐，路上灰尘满天，比赛的艰苦无法形容。希腊人路易斯第一个冲入运动场，全场欢声雷动，此时冠军已无悬念，担任总裁判的希腊王储情不自禁地陪着路易斯冲击终点。一束束鲜花，一件件礼物，投向人们崇拜的英雄，甚至有人高呼：让他当部长。
女：后来呢？
男：后来，他获得了希腊民族英雄的称号，仍然回到了偏僻的家乡，继续当他的乡村邮递员，和妻儿一起过着清贫的生活。

**** 音频

8800fd44-3924-4cbc-8c44-b844eeb6b278.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: c120bd85-da93-440a-acb5-1fbb98a3b68f
:END:

***** 问题

马拉松作为一项体育运动，是哪一年开始的？

****** 音频

55bf3720-3040-44f9-b23d-ed2e3d419466.mp3

***** 选择

****** A

 490年

****** B

 1896年

****** C

 1908年

****** D

 2000多年前

***** 答案

B

**** 7
:PROPERTIES:
:ID: 44eef77f-188b-4225-a055-437c60c141e7
:END:

***** 问题

关于马拉松运动的起源，下列哪项正确？

****** 音频

9cc6cb66-4d88-429c-b043-84e2222124f3.mp3

***** 选择

****** A

那只是一个传闻

****** B

参加马拉松的人都很能跑

****** C

这项运动与马拉松战役有关

****** D

为丁表彰喜爱运动的希腊人

***** 答案

C

**** 8
:PROPERTIES:
:ID: e9530352-40d5-4eb4-82f9-f9ef55fc2790
:END:

***** 问题

在奥运会上设立马拉松长跑项目是谁提出的？

****** 音频

2cffee10-4629-4670-8363-7f93f7badc79.mp3

***** 选择

****** A

顾拜丁

****** B

菲迪皮德思

****** C

希腊奠组委

****** D

米歇尔・布雷尔

***** 答案

D

**** 9
:PROPERTIES:
:ID: 23e1129e-9d65-4d70-ab77-4861adcd0de4
:END:

***** 问题

关于今天奥运会马拉松长跑总长度，下列哪项正确？

****** 音频

ba17d356-6185-4fc4-a53f-8e367104c820.mp3

***** 选择

****** A

各国奥组委可自行决定

****** B

以马拉松到雅典的距离为准

****** C

奥组委根据当地情况临时决定

****** D

以1908年英国奥运会距离为准

***** 答案

D

**** 10
:PROPERTIES:
:ID: 084ed17c-28ab-4809-bcbd-ccf5f3e29939
:END:

***** 问题

根据这段采访可以知道什么？

****** 音频

dcfd5101-863e-48d9-9a6d-b040d3f439e8.mp3

***** 选择

****** A

路易斯原本是个乡村邮递员

****** B

全世界都视马拉松冠军为英雄

****** C

长跑是希腊全民热爱的体育运动

****** D

路易斯拿到马拉松冠军后当了部长

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

自然界的危险时刻会危害人类

***** B

共同协作能够培养人的群体意识

***** C

原始社会，人要生存就离不开集体

***** D

生产力水平取决于人们的思想观念

**** 段话

在原始社会，生产力水平低下，人们为了获取食物、防御自然界的危险和侵袭，必须集体行动、共同协作才能生存下去。对集体的依赖性强化了人们的群体意识以及与集体同生共死的观念。

***** 音频

e210c269-8fa7-4602-949a-681c6d615f27.mp3

**** 答案

C

*** 2

**** 选择

***** A

结婚后要改变过去的生活方式

***** B

老人的话都是宝贵的生活经验

***** C

美满婚姻有赖于两个人的经营

***** D

给予了才能得到，家庭也如此

**** 段话

老话说得好，当一个人变为两个人，两个人守护着一个共同的家，就必须各尽其责，关心对方、体贴对方、照顾对方、理解对方。美满的婚姻应该是两颗心的相守相依，两个人情感的互相给予。

***** 音频

fd3aec14-652e-449e-af81-68370a426dbc.mp3

**** 答案

C

*** 3

**** 选择

***** A

暴发户都没有文化

***** B

有钱不会花，就是暴发户

***** C

暴发户会花很多不该花的钱

***** D

说话人对房间俗气的摆设很恭火

**** 段话

暴发户文化最大的特征就是附庸风雅。暴发户的文化水平没有到，可是经济水平超过了，因此他会花很多冤枉钱，做很多冤大头的事情。比如说到哪儿都摆阔，房间里弄得金玉满堂，十分俗气。

***** 音频

7cfa2593-3624-4d8e-ad23-54030157c8ed.mp3

**** 答案

C

*** 4

**** 选择

***** A

说话人讨厌拼凑而成的书

***** B

说话人特别喜欢长篇小说

***** C

《通俗文化读本》是一本好书

***** D

真正有学问的人都能谈古论今

**** 段话

那些学贯古今的大学者，何不编写一册通俗的传统文化读本。不要长篇巨制，那是成心不让人读；不要东拼西凑，那样不值得读。只要以成熟的态度，把古人的生存方式、智慧、经验、得失告诉我们，就像一册新时代的《三字经》，岂不是好事！

***** 音频

6fe8974b-6acd-4981-848d-c69c4a43a4cd.mp3

**** 答案

A

*** 5

**** 选择

***** A

她有当律师的天分

***** B

她一直被钱所困扰

***** C

她不愿看律师写的小说

***** D

她认为为钱打官司很容易

**** 段话

她能说善辩，适合当律师。在课堂上，她们做过模拟律师辩护项目，她的表现极其出色。可她读过许多美国名律师写的小说，她知道律师们要想赚大钱就要为有钱有势的人打官司，她不想被钱、权、势所左右，所以她不想当律师。

***** 音频

563331b9-8f75-4a71-9e77-b998b5ce8847.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

趣味体育是近年新兴的体育活动，其运动方式没有传统运动那么正式，它以趣味为主，注重娱乐性与大众性；没有传统运动那么严格，它以体验为主；更不需要那么严格的选拔，它属于有兴趣参加的每一个人。它可以在乡间，也可以在高楼之间，甚至在小区的小院里都能举办，比赛的内容也不需要你具备什么天分，更不必提前多少年去接受专门训练。

趣味体育同样可以强身健体，使大家形成终身体育的意识；趣味体育可以娱乐大众，使没有体育专长的人也能体验到体育带来的快乐；由于趣味体育以集体项目居多，可以锻炼参赛者的团结协作意识和竞争拼搏精神。

**** 题目

***** 11

****** 选择

******* A

刺激

******* B

正规

******* C

传统

******* D

好玩儿

****** 问题

趣味体育比赛项目的设计有什么特点？

***** 12

****** 选择

******* A

产生更多冠军

******* B

增强团队观念

******* C

普及体育常识

******* D

给观众带来竞争

****** 问题

趣味体育的作用是什么？

***** 13

****** 选择

******* A

近年来趣昧体育逐渐衰落

******* B

没有人不喜欢趣显体育

******* C

趣味体育对场所要求不高

******* D

趣显体育的参与者都没有天分

****** 问题

根据这段话，可以知道什么？

*** 14-17

**** 课文

世界杯刚一落幕，老球迷就在微博上怀念起旧时足球解说员。

1978 年之前，中国还是收音机时代，那时候不是“看足球”，而是“听足球”。因为足球比赛信息量大且有规定时间，加上比赛情况瞬息万变，所以当时解说的语速都很快，像足球在场上的速度那么快。

电视时代到来后，足球解说也悄然变化。第一代解说以宋世雄、韩乔生为代表，语言上已相对活泼一些了，而且开始引入解说嘉宾这一概念，并尝试在解说中提供更多背景信息。

黄健翔是第二代解说的代表。他把重心放在掌握更多资讯上，同时注重给观众一种现场感，由于是现场解说，解说员自然也会更有激情。

近年被称为文艺青年解说员的贺炜给人们留下了深刻的印象。他语言充满艺术性，被球迷称为“诗人”。解说时这位新生代解说员声情并茂，遣词用句常在观众意料之外，有人评价他的解说专业客观，又使人得到一种艺术的享受。

**** 题目

***** 14

****** 选择

******* A

信息量大

******* B

解说速度快

******* C

解说员都是球员

******* D

没人看电视转播

****** 问题

31978 年之前，中国足球解说有什么特点？

***** 15

****** 选择

******* A

风格变化很突然

******* B

解说员都很活泼

******* C

有时嘉宾代替解说

******* D

解说中增加了背景信息

****** 问题

第一代电视足球解说有什么特点？

***** 16

****** 选择

******* A

他们选出了自己的代表

******* B

现场解说的比例增加了

******* C

解说员解说时更有激情

******* D

解说员对任何资讯都不疏忽

****** 问题

第二代电视足球解说有什么特点？

***** 17

****** 选择

******* A

他会写诗

******* B

他是业余诗人

******* C

他对艺术情有独钟

******* D

他的语言充满艺术性

****** 问题

贺炜为什么被称为文艺青年解说员？

