:PROPERTIES:
:CREATED: [2022-03-14 05:15:06 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-03-08 14:08:46 -05]
:END:

** 1w
:PROPERTIES:
:CREATED: [2022-03-08 14:11:38 -05]
:END:

生日 | shēngrì | birthday | cumpleaños | noun ;

晚上 | wǎnshang | night | noche ;

两个儿子
pi: liǎng ge érzi
en: 2 sons
es: 2 hijos

电话 | diànhuà | phone | teléfono ;

看书
pi: kàn shū
en: read book
es: leer libro

工作 | gōngzuò | work | trabajo ;

1. C
2. F
3. E
4. D
5. A
6. B

** 2
:PROPERTIES:
:CREATED: [2022-03-08 14:11:46 -05]
:END:

（帮忙）妈妈
pi: bāngmáng māma
en: help mom
es: ayudar a mama

（问）医生
pi: wèn yīshēng
en: ask to the doctor
es: preguntar al doctor

（介绍）朋有
pi: jièshào péngyǒu
en: introduce friend
es: introducir amigo

（打）电话
pi: dǎ diànhuà
en: call
es: llamar

* Text
:PROPERTIES:
:CREATED: [2022-03-08 14:17:08 -05]
:END:

** 1. 在教室 In the classroom
:PROPERTIES:
:CREATED: [2022-03-08 14:17:10 -05]
:ID: 48cbc776-83e3-4434-b82d-05c015828f99
:END:

Ａ：生日快乐！这是送给你的！
pi: shēngrì kuàilè! zhè shì sòng gěi nǐ de
en: Happy birthday! This is for you!
es: ¡Feliz cumpleaños! ¡Esto es para ti!

Ｂ：是什么？是一本书吗？
pi: shì shénme? shì yì běn shū ma
en: What is it? Is it a book?
es: ¿Qué es? ¿Es un libro?

Ａ：对，这本书是我写的。
pi: duì, zhè běn shū shì wǒ xiě de
en: Yes, I wrote this book.
es: Sí, yo escribí este libro.

Ｂ：太谢谢你了！
pi: tài xièxie nǐ le
en: Thank you so much!
es: ¡Muchas gracias!

New words

生日 | shēngrì | birthday | cumpleaños  | noun ;

快乐 | kuàilè | feliz, agradecido | noun ;

给 | gěi | to, for (used after a verb) | a, para (usado luego de un verbo) | preposition ;

** 2. 在家里 At home
:PROPERTIES:
:CREATED: [2022-03-08 14:17:13 -05]
:ID: 0a261289-6666-4ed6-b691-475198ce52c5
:END:

Ａ：早上有你一个电话。
pi: zǎoshang yǒu nǐ yí ge diànhuà
en: You had a phone call this morning.
es: Alguien te llamó esta mañana.

Ｂ：电话是谁打的？
pi: diànhuà shì shéi dǎ de
en: Who was on the phone?
es: ¿Quién estaba en el teléfono?

Ａ：不知道，是儿子接的。
pi: bù zhīdǎo, shì érzi jiē de
en: I don't know, our son picked it up.
es: No lo sé, nuestro hijo respondió.

Ｂ：好，晚上我问一下儿子。
pi: hǎo, wǎnshang wǒ wèn yíxià érzi
en: Okay, I'll ask him about it tonight.
es: De acuerdo, le preguntaré esta noche.

New words

接
pi: jiē
en: to receive, to take, to accept
es: recibir, tomar, aceptar
lexical category: verb

晚上
pi: wǎnshang
en: evening
es: noche 
lexical category: noun

问
pi: wèn
en: to ask
es: preguntar
lexical category: verb

** 3. 在运动场 On the playground
:PROPERTIES:
:CREATED: [2022-03-08 14:17:16 -05]
:ID: e03038fe-fe09-4ddc-83c4-cefc2925c213
:END:

Ａ：你喜欢踢足球吗？
pi: nǐ xǐhuan tī zúqiú ma
en: Do you like to play soccer?
es: ¿Te gusta jugar al fútbol?

Ｂ：非常喜欢。
pi: fēicháng xǐhuan
en: I like it a lot.
es: Me gusta mucho.

Ａ：你是什么时候开始踢足球的？
pi: nǐ shì shénme shíhou kāishǐ tī zúqiú de
en: When did you start playing soccer?
es: ¿Cuándo empezó a jugar al fútbol?

Ｂ：我十一岁的时候开始踢足球，已经踢了十年了。
pi: wǒ shíyī suì de shíhou kāishǐ tī zúqiú, yǐjīng tī le shí nián le
en: I started playing soccer when I was eleven years old, and I've been playing for ten years.
es: Empecé a jugar al fútbol a los once años y ya llevo diez.

New words

非常 | fēicháng | very, extremely |  muy, extremadamete | adverb ;

开始 | kāishǐ | to begin, to start |  empear | verb ;

已经 | yǐjīng | already | ya | adverb ;

** 4. 在公司 In the company
:PROPERTIES:
:CREATED: [2022-03-08 14:17:22 -05]
:ID: e4c3ccd6-aaf4-4b61-8524-5d4c1ee23dcd
:END:

Ａ：你在这儿工作多长时间了？
pi: nǐ zài zhèr gōngzuò duō cháng shíjiān le
en: How long have you been working here?
es: ¿Cuánto tiempo lleva trabajando aquí?

Ｂ：已经两年多了，我是2011年来的。
pi: yǐjīng liǎng nián duō le, wǒ shì èr líng yī yī nián lái de
en: It's been more than two years, I came here in 2011.
es: Han pasado más de dos años, llegué aquí en 2011.

Ａ：你认识谢先生吗？
pi: nǐ rènshi xiè xiāngsheng ma
en: Do you know Mr. Xie?
es: ¿Conoce al Sr. Xie?

Ｂ：认识，我们是大学同学，这个工作是他帮我介绍的。
pi: rènshi, wǒmen shì dàxué tóngxué, zhège gōngzuò shì tā bāng wǒ jièshào de
en: Yes, we went to college together and he introduced me to this job.
es: Sí, fuimos juntos a la universidad y él me presentó este trabajo.

New  words

长 | cháng | long | largo | adjective;

两 | liáng | two | dos | number;

帮 | bāng | to help, to assist | ayudar | verb ;

介绍 | jièshào | to introduce, to recommend | introducir, recomendar | verb ;

* Notes
:PROPERTIES:
:CREATED: [2022-03-13 19:20:55 -05]
:END:

** 1. "是...的" 
:PROPERTIES:
:CREATED: [2022-03-13 19:38:43 -05]
:END:

When the ocurrence of an action is known, "是...的" can be used to emphasize the agent of an action. For exmaple:


动作
pi: dòngzuò
en: action
es: acción

晚饭
pi: wǎnfàn
en: dinner
es: cena

电话
pi: diànhuà
en: phone
es: teléfono

|--------+--------+----------+---------+------|
| Object | 是 (V) | 谁 (who) | 动作(V) | 的   |
|--------+--------+----------+---------+------|
| 这本书 | 是     | 我       | 买      | 的。 |
| 晚饭   | 是     | 妈妈     | 做      | 的。 |
| 电话   | 是     | 谁       | 打      | 锝？ |
|--------+--------+----------+---------+------|

这本书是我买的。
pi: zhè běn shū shì wǒ mǎi de
en: Who made the phone call?
es: ¿Quién hizo la llamada?

晚饭是妈妈做的。
pi: wǎnfàn shì māma zuò de
en: Mom made the dinner.
es: Mamá hizo la cena.

电话是谁打的？
pi: diànhuà shì shéi dá de
en: I bought this book.
es: He comprado este libro.

In the negative form, "不" is added before "是". For example

汉字 | hànzì | chinese character | caracter chino ;

苹果 | píngguǒ | apple | manzana ;

王方 | wáng fāng | Wang Fang | Wang Fang ;

这个汉字不是大卫写的。
pi: zhè gè hàizì bù shì dàwèi xiě de
en: The Chinese character was not written by David.
es: Este carácter chino no fue escrito por David.

苹果不是王方买的。
pi: píngguǒ bù shì wáng fāng mǎi de
en: Wang Fang didn't buy the apple.
es: Wang Fang no compró la manzana.

电话不是我接的。
pi: dìanhuà bù shì wǒ jiē de
en: I didn't answer the phone.
es: No he contestado al teléfono.

** 2. Indicating time
:PROPERTIES:
:CREATED: [2022-03-13 19:38:54 -05]
:ID: 5d26ac0b-3f47-4f6a-a19a-d1f52c1eb25a
:END:


开始 | kāishǐ | begin | start ;

"Num-M + 的时候" indicates time. For example:

今天早上八点的时候我没在家。
pi: jīntiān zǎoshang bā diǎn de shíhòu wǒ méi zài jiā
en: I wasn't home at eight o'clock this morning.
es: No estaba en casa a las ocho de la mañana.

我十八岁的时候一个人来到北京。
pi: wǒ shíbā suì de shíhòu yī gè rén lái dào běijīng
en: I came to Beijing by myself when I was eighteen.
es: Llegué a Pekín sola cuando tenía dieciocho años.

我十一岁的时候开始踢足球。
pi: wǒ shīyī suì de shíhòu kāishǐ tī zúqiú
en: I started playing soccer when I was eleven.
es: Empecé a jugar al fútbol a los once años.

"V + 的时候" also indicates time. For example:

我睡觉的时候，我妈妈在做饭。
pi: wǒ shuìjiào de shíhòu, wǒ māma zài zuò fàn
en: While I was sleeping, my mom was cooking.
es: Mientras yo dormía, mi madre cocinaba.

麦克到学校的时候下雨了。
pi: màikè dào xuéxiào de shíhòu xiàyǔ le
en: It was raining when Mike arrived at school.
es: Estaba lloviendo cuando Mike llegó a la escuela.

王老师工作的时候，她丈夫开车去医院了。
pi: wáng lǎoshī gōngzuò de shíhòu, tā zhàngfu kāichē qù yīyuàn le
en: While Ms. Wang was working, her husband drove off to the hospital
es: Mientras la Sra. Wang estaba en el trabajo, su marido se dirigió al hospital.

** 3. The adverb of time "已经"
:PROPERTIES:
:CREATED: [2022-03-13 20:06:02 -05]
:END:

已
pi: yǐ

经
pi: jīng

王老师已经回家了。
pi: wáng lǎoshī yǐjīng huí jiā le
en: Mr. Wang has already gone home.
es: El Sr. Wang ya se ha ido a casa.

我的身体已经好了。
pi: wǒ de shēntǐ yǐjng hǎo le
en: My body has gotten better.
es: Estoy bastante bien.

足球我已经踢了十年了。
pi: zúqiú wǒ yǐjīng tī le shí nián le
en: I've been playing soccer for ten years now.
es: Llevo diez años jugando al fútbol.

* Exercises
:PROPERTIES:
:CREATED: [2022-03-13 20:12:35 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-03-13 23:03:20 -05]
:END:

这本书是谁写的？
pi: zhè běn shū shì shéi xiě de
en: Who wrote this book?
es: ¿Quién escribió este libro?

这本书是她写的。
pi: zhè běn shū shì tā xiě de
en: She wrote this book.
es: Ella escribió este libro.

早上的电话是谁接的？
pi: zǎoshàng de diānhuà shì shéi jiē de
en: Who answered the phone in the morning?
es: ¿Quién ha contestado al teléfono por la mañana?

早上的电话是他的儿子接的。
pi: zǎoshang de diānhuà shì de érzi jiē de
en: The phone call in the morning was answered by his son.
es: El teléfono de la mañana lo contestó su hijo.

他是什么时候开始踢足球的？
pi: tā shì shénme shíhòu kāishǐ tī zúqiú de
en: When did he start playing soccer?
es: ¿Cuándo empezó a jugar al fútbol?

他十一岁的时候开始踢足球。
pi: tā shíyī suì de shíhòu kāishǐ tī zúqiú
en: He started playing soccer when he was eleven years old.
es: Empezó a jugar al fútbol a los once años.

他在那儿工作多长时间了？
pi: tā zài nǎr gōngzuó duō cháng shíjiān le
en: How long has he been working there?
es: ¿Cuánto tiempo lleva trabajando allí?

他在那儿工作已经两年多了。
pi: tā zài nǎr gōngzuó yǐjīng liǎng nián duō le
en: He has been working there for more than two years.
es: Lleva más de dos años trabajando allí.

工作是谁帮他介绍的？
pi: gōngzuó shì shéi bāng tā jièshào de
en: Who introduced him to the job?
es: ¿Quién le introdujo en el trabajo?

工作是谢先生帮他介绍的。
pi: gōngzuó shì xiè xiānsheng bāng tā jièshào de
en: Mr. Xie introduced him to the job.
es: El trabajo le fue presentado por el Sr. Tse.

** 3
:PROPERTIES:
:CREATED: [2022-03-13 23:03:23 -05]
:END:

篮球 | lánqiú | basketball | baloncesto | noun ;
打篮球 | dǎlánqiú | play basketball | jugar baloncesto | verb ;

我在做饭呢，是马丁（接）的电话。
我在做饭呢，是马丁接的电话。
pi: wǒ zài zuò fàn ne, shì mǎdīng (jiē) de diànhuà
en: I was cooking, it was Martin who answered the phone.
es: Estaba cocinando, fue Martin quien contestó al teléfono.

这个工作是王方帮我（介绍）的，我想请她吃饭。
这个工作是王方帮我介绍的，我想请她吃饭。
pi: zhège gōngzuó shì wáng fāng bāng wǒ jièshào de, wǒ xiǎng qíng tā chī fàn
en: This job was introduced to me by Wang Fang, I want to invite her to dinner.
es: Este trabajo me lo presentó Wang Fang, quiero invitarla a cenar.

这本书是我写的，我是二十岁的（时候）开始写书的。
这本书是我写的，我是二十岁的时候开始写书的。
pi: zhè běn shū shì wǒ xié de, wǒ shì èrshí suì de shíhòu kāishǐ xiě shū de
en: I wrote this book. I started writing books when I was twenty years old.
es: Escribí este libro, empecé a escribir libros cuando tenía veinte años.

我是六岁开始打篮球的，我（最）喜欢打篮球。
我是六岁开始打篮球的，我最喜欢打篮球。
pi: wǒ shì liù suì kāishǐ dǎlánqiú de, wǒ zuì xǐhuan dǎlánqiú
en: I started playing basketball when I was six years old. I love playing basketball the most.
es: Empecé a jugar al baloncesto a los seis años. Era mi juego favorito.

