* 听力

** 第二部分
:PROPERTIES:
:ID: b156799f-90a8-4157-9306-71f7c6e43552
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：请问，为什么要编写《口述“非遗”》这么一本书呢？
男：大家都知道，每一个苏州人都为自己的城市骄傲。我们骄傲的基础有三点：第一是水，苏州因水而昌盛，水是苏州人的骄傲；第二是人，苏州出人才，古的不说了，当今院士就有 130 多位；第三就是艺，历史上，苏州有各种各样的工艺。去年联合国给予我们“手工艺与民间艺术之都”的称号，这是实至名归。而工艺，大部分属于非物质文化遗产，但是一些“非遗”项目的现状不容乐观，所以我们组织专家、学者，对非物质文化遗产的传承人、见证人进行采访，目的是留下历史的记录，同时希望有更多的人了解、关注、保护“非遗”。
女：为什么要采用口述的方式呢？
男：因为非物质文化遗产的传承人年龄都很大了，80 岁以上的有 15 位，年龄最大的 101 岁。有两位老人在接受采访不久、成书之前就去世了。应该说，这份历史文献是对“非遗”抢救式的保护，我们心里充满了紧迫感。
女：苏州“非遗”项目保护的具体办法是什么？
男：我们采取了区别性的保护办法。对于生存状态好的，进行生产性保护，比如核雕、刺绣；不好的，那些渐行渐远的、濒危的项目，需要去关怀；还有的年代太过久远，由于历史原因已经抢救不活的，进行记忆性保护。
女：为什么会造成“非遗”今天的困境，大家有过思考吗？
男：所谓“遗”，就是前人留下来的，不是我们这个时代的东西。所谓“非遗”，是文化的东西，是古人曾经的生活方式。“非遗”建立的基础是农耕文化，可我们今天生活已经发生了巨大的变化。从中国发展的历程来看，我们几乎没有经历一个现代的工业时代，直接进入了信息时代。在社会跳跃式发展的过程中，必然会抛弃一些东西。抛弃什么呢？很显然，就是那些曾经的生活方式，这就形成了中国“非遗”今天所面对的困境。

**** 音频

105bf0ef-b70a-424b-a422-38b72c2dd18e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: b6c156cf-703f-4da0-9537-076889c0fac0
:END:

***** 问题

苏州人最可能会为什么而骄傲？

****** 音频

dd8738ea-9181-46d5-8e90-f486a057b333.mp3

***** 选择

****** A

为苏州的水而骄傲

****** B

为苏州艺人多而骄傲

****** C

为苏州是人间天堂而骄傲

****** D

为苏州曾做过都城而骄傲

***** 答案

A

**** 7
:PROPERTIES:
:ID: 526cd5cd-b47f-4db8-89c8-70eb7e2c27c8
:END:

***** 问题

关于非物质文化遗产，下列哪项正确？

****** 音频

8212ad8e-981a-4d88-919f-7f921f68ee89.mp3

***** 选择

****** A

非物质文化遗产的文字记录丰富

****** B

非物质文化遗产的研究已很深人

****** C

越来越多的人在关注非物质文化遗产

****** D

中国非物质文化遗产保护的现状堪忧

***** 答案

D

**** 8
:PROPERTIES:
:ID: 464a8022-cc8b-4669-a0ca-310944296d5e
:END:

***** 问题

对苏州“非遗”的保护措施是什么？

****** 音频

89020edf-4cd9-45bc-b1d7-0a5f2751a21a.mp3

***** 选择

****** A

优先记忆性保护

****** B

首先保护年代久远的

****** C

尽力救活每一个项目

****** D

根据具体情况区别对待

***** 答案

D

**** 9
:PROPERTIES:
:ID: 93efd94b-ec2d-4114-a527-e0b9316ec529
:END:

***** 问题

“非遗”今天困境产生的原因是什么？

****** 音频

70d9b5c1-5379-48f1-8bd6-5bc504c5e5d3.mp3

***** 选择

****** A

它看不见摸不着

****** B

当下农民都在城里

****** C

我们的生活方式改变了

****** D

信息时代的吸引力太大

***** 答案

C

**** 10
:PROPERTIES:
:ID: a54d997b-918b-4ca1-89bc-9dc91747df7c
:END:

***** 问题

这段话主要谈的是什么？

****** 音频

c5e39a34-bf93-4edd-a7af-ba854d02b690.mp3

***** 选择

****** A

苏州的历史很悠久

****** B

苏州自古至今人才济济

****** C

“口述“的方式在今天很时坤

****** D

苏州非物质文化遗产保护迫在眉睫

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

螳螂的身体细长

***** B

螳螂的头脑灵活

***** C

螳螂喜欢东张西望

***** D

螳螂骨子里很温柔

**** 段话

从外表看，螳螂并不可怕。身躯修长，前胸纤长；长颈上，顶着一个扁三角形的小脑袋；它的颈部是柔软的，能使头向任何方向窥视。它的神态温柔，被人称作“会祈祷的螳螂”。

***** 音频

b2f89817-fa24-4307-9f33-bd2dc143a67b.mp3

**** 答案

A

*** 2

**** 选择

***** A

先生最为擅长编写历史故事

***** B

先生的文章有许多绝妙之处

***** C

先生文章中的人物都很神奇

***** D

先生读起文章来总是神情感人

**** 段话

先生文章的妙处实在难以尽述，就如那文章里涉及的当时的许多人和事，如今读来，又都成了饶有趣味的历史小掌故。先生的文章，针砭时弊，泼辣犀利，绝无时文的吞吞吐吐，读来令人神旺气盛。

***** 音频

b43b7a50-278a-4e36-b0e0-d1f900efbf35.mp3

**** 答案

B

*** 3

**** 选择

***** A

长安在黄河流域

***** B

再冷井水也不会结冰

***** C

黄河流域气候一直较温暖

***** D

公元七、人世纪天气冷到极点

**** 段话

东汉末年，中华大地气候又表现出向寒冷转变的迹象，东海、东莱等郡出现水井冰冻厚尺余的现象，渤海湾也有冰封记载。公元七、八世纪，黄河流域气候一度转暖，长安地区的梅花花期又有变长的迹象。

***** 音频

008c60e7-3df1-4cbd-a211-bdc8eaa1ac03.mp3

**** 答案

A

*** 4

**** 选择

***** A

女人个个都懂得爱护皮肤

***** B

女人从电影中学习美容方法

***** C

精油都是从水果中提炼出来的

***** D

精油出现前人们会用水果美容

**** 段话

记得看过的一部电影，女主角将柠檬从中间切开，然后拿起半只直接涂抹颈部，这种利用水果的美容法应该算是精油疗法的雏形了。在提炼精油的高科技还未出现时，女人已经知道如何呵护自己的皮肤了，这让我当时为之一震。

***** 音频

40e9e460-d2bc-482c-b211-358eb88749dd.mp3

**** 答案

D

*** 5

**** 选择

***** A

语言中，基本词汇部分十分稳定

***** B

语言中的词汇只能反映基本概念

***** C

语言中构造新词的材料十分有限

***** D

语言中不断出现构成新词的格式

**** 段话

语言中词汇的变化很灵敏，但其基础非常稳固。这表现在两方面：第一，词汇中的基本词汇部分反映交际中最常用的基本概念，它是很不容易变化的。第二，构造新词的材料几乎都是语言中古已有之的，构成新词的格式也是语言中现成的。

***** 音频

7cef550f-dbb2-451d-b61a-32e1da5cd84d.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

变脸，这是川剧表演艺术的特殊技巧之一，看过的观众，无不惊叹其神。它是揭示剧中人物内心思想感情的一种浪漫主义手法，把不可见、不可感的抽象的东西变得可见、可感。

剧作家柳倩认为，“变脸”是感情的象征，许多脸谱已经有它显著的典型特质，说明人物的忠奸邪正，而且有助于强调人物个性，表现感情变化的发展过程，这是四川戏的优点。加之演员能于观众不注意间改变他的脸像，也是一种惊人的技术。

如今，“变脸”的特技已被其他剧种所采用，而且，已经传到了国外。值得注意的是，为卖弄技艺、讨好观众而滥用变脸的现象也时有发生。

*** 14-17

**** 课文

对于苹果的商标最初是怎样来的，有很多谣言。其中最盛行的说法是，那被咬掉一口的彩色苹果，是已故伟人阿兰·图灵的杰作。图灵因同性恋遭到排斥后自杀了，可能是食用了带有氰化物的苹果。相信这一说法的人认为苹果公司选择苹果商标是为了纪念“计算机科学之父”。

其实，这仅仅是一个听起来意义深远的故事，事实上，全是瞎扯。对公司而言，取名叫“苹果”，仅仅是因为斯蒂夫·乔布斯认为这个词听起来不错。乔布斯想出这个名字时，没有任何象征或者暗示牛顿或图灵的意思，如果要问为什么在浩如烟海的词汇中，他偏偏选中了“苹果”，那是因为当时他正处于水果减肥计划当中，觉得这个词听起来“有趣”。而就商标本身而言，商标的设计者罗伯·吉道夫已经多次澄清不是许多人以为的那样，不是为了向图灵或者牛顿或者“水果学问”致敬而设计的。它只是一个苹果。至于为什么被咬了一口，只是为了不让人们把它当成樱桃而已。

