* 听力

** 1

*** 1

**** transcript

从外表看，螳螂并不可怕。身躯修长，前胸纤长；长颈上，顶着一个扁三角形的小脑袋；它的颈部是柔软的，能使头向任何方向窥视。它的神态温柔，被人称作“会祈祷的螳螂”。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

a

*** 2

**** transcript

先生文章的妙处实在难以尽述，就如那文章里涉及的当时的许多人和事，如今读来，又都成了饶有趣味的历史小掌故。先生的文章，针砭时弊，泼辣犀利，绝无时文的吞吞吐吐，读来令人神旺气盛。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

*** 3

**** transcript

东汉末年，中华大地气候又表现出向寒冷转变的迹象，东海、东莱等郡出现水井冰冻厚尺余的现象，渤海湾也有冰封记载。公元七、八世纪，黄河流域气候一度转暖，长安地区的梅花花期又有变长的迹象。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

记得看过的一部电影，女主角将柠檬从中间切开，然后拿起半只直接涂抹颈部，这种利用水果的美容法应该算是精油疗法的雏形了。在提炼精油的高科技还未出现时，女人已经知道如何呵护自己的皮肤了，这让我当时为之一震。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

语言中词汇的变化很灵敏，但其基础非常稳固。这表现在两方面：第一，词汇中的基本词汇部分反映交际中最常用的基本概念，它是很不容易变化的。第二，构造新词的材料几乎都是语言中古已有之的，构成新词的格式也是语言中现成的。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

a

**  第二部分
:PROPERTIES:
:ID: b156799f-90a8-4157-9306-71f7c6e43552
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：请问，为什么要编写《口述“非遗”》这么一本书呢？
男：大家都知道，每一个苏州人都为自己的城市骄傲。我们骄傲的基础有三点：第一是水，苏州因水而昌盛，水是苏州人的骄傲；第二是人，苏州出人才，古的不说了，当今院士就有 130 多位；第三就是艺，历史上，苏州有各种各样的工艺。去年联合国给予我们“手工艺与民间艺术之都”的称号，这是实至名归。而工艺，大部分属于非物质文化遗产，但是一些“非遗”项目的现状不容乐观，所以我们组织专家、学者，对非物质文化遗产的传承人、见证人进行采访，目的是留下历史的记录，同时希望有更多的人了解、关注、保护“非遗”。
女：为什么要采用口述的方式呢？
男：因为非物质文化遗产的传承人年龄都很大了，80 岁以上的有 15 位，年龄最大的 101 岁。有两位老人在接受采访不久、成书之前就去世了。应该说，这份历史文献是对“非遗”抢救式的保护，我们心里充满了紧迫感。
女：苏州“非遗”项目保护的具体办法是什么？
男：我们采取了区别性的保护办法。对于生存状态好的，进行生产性保护，比如核雕、刺绣；不好的，那些渐行渐远的、濒危的项目，需要去关怀；还有的年代太过久远，由于历史原因已经抢救不活的，进行记忆性保护。
女：为什么会造成“非遗”今天的困境，大家有过思考吗？
男：所谓“遗”，就是前人留下来的，不是我们这个时代的东西。所谓“非遗”，是文化的东西，是古人曾经的生活方式。“非遗”建立的基础是农耕文化，可我们今天生活已经发生了巨大的变化。从中国发展的历程来看，我们几乎没有经历一个现代的工业时代，直接进入了信息时代。在社会跳跃式发展的过程中，必然会抛弃一些东西。抛弃什么呢？很显然，就是那些曾经的生活方式，这就形成了中国“非遗”今天所面对的困境。

*** 音频

105bf0ef-b70a-424b-a422-38b72c2dd18e.mp3

*** 题目

**** 6

***** 问题

苏州人最可能会为什么而骄傲？

***** 音频

dd8738ea-9181-46d5-8e90-f486a057b333.mp3

***** 选择

****** A

为苏州的水而骄傲

****** B

为苏州艺人多而骄傲

****** C

为苏州是人间天堂而骄傲

****** D

为苏州曾做过都城而骄傲

***** 答案

A

**** 7

***** 问题

关于非物质文化遗产，下列哪项正确？

***** 音频

8212ad8e-981a-4d88-919f-7f921f68ee89.mp3

***** 选择

****** A

非物质文化遗产的文字记录丰富

****** B

非物质文化遗产的研究已很深人

****** C

越来越多的人在关注非物质文化遗产

****** D

中国非物质文化遗产保护的现状堪忧

***** 答案

D

**** 8

***** 问题

对苏州“非遗”的保护措施是什么？

***** 音频

89020edf-4cd9-45bc-b1d7-0a5f2751a21a.mp3

***** 选择

****** A

优先记忆性保护

****** B

首先保护年代久远的

****** C

尽力救活每一个项目

****** D

根据具体情况区别对待

***** 答案

D

**** 9

***** 问题

“非遗”今天困境产生的原因是什么？

***** 音频

70d9b5c1-5379-48f1-8bd6-5bc504c5e5d3.mp3

***** 选择

****** A

它看不见摸不着

****** B

当下农民都在城里

****** C

我们的生活方式改变了

****** D

信息时代的吸引力太大

***** 答案

C

**** 10

***** 问题

这段话主要谈的是什么？

***** 音频

c5e39a34-bf93-4edd-a7af-ba854d02b690.mp3

***** 选择

****** A

苏州的历史很悠久

****** B

苏州自古至今人才济济

****** C

“口述“的方式在今天很时坤

****** D

苏州非物质文化遗产保护迫在眉睫

***** 答案

D

