* Text

** title

走近木版年画

** content

年画是中国画的一种，始于古代的门神画。

有文献记载：传说很久以前，有一对兄弟，专门监督百鬼，发现凶恶的鬼就捆绑起来，无须揭露恶行，直接去喂老虎。于是有人在门上画上他们兄弟二人的像，用以防鬼，这就是最由的门神画。

随着唐宋①两朝经济的紁展，文化的昌盛以及民间绘画水平的提高，门神画的内容得以拓展，反映世俗生活题材的作品进入了这一领域。之后有清朝①学者在论述这类画作时正式使用了“年画”一词，自此，以驱逐祸凶、祝福新年吉祥喜庆为内容的画儿就叫年画了。

木版年画

造纸技术的紁明是人类文化发展史上一个重要的里程碑。

有了纸，书之与就需要墨水儿，于是有人发明了墨；字画、书信上需要盖章，于是印章开始流行口碑刻、拓印枝术被广泛运用，于是有人联想到：这些技术结合起来，不就能印出书来吗！人们尝试把印章扩不成一张纸那么大，叫作“版”，然后把书的内容刻在版上，在版上涂抹上墨，把纸铺到上面，用刷子均习地刷印，最后将纸揭起，印品就出来了，这就是最早的雕版印刷。虽然雕版印刷中雕刻版面需要不量的人工和材料，但雕版完成后一经开印，就显示芔空前的高效率和印刷量不的优越性。

单色印品终究不能满足人们的审美需求，之后就有了彩色套印年画就此诞生。

宋明①两代，木版年画从问世走向成熟，之后走进了百姓生活，以至过年贴年画成为了一种风尚，仿佛没有年画，没有烟花爆竹，没有春联就不叫过年，而寄托着百姓美好愿望的年画，也为春节增添了浓的年味。当时的另一盛况是，家族式的年画印制场所遍及全国各地。这期间，年画的内容也从威武的门神，扩展到期盼丰收、恭喜紁财、连年有余的吉庆画，再到历史故事、戏曲人物、民间笑话、寓言和神话，内容无所不包。年画成了文化交流、道德教育、信仰传承的载体与工具，是老百姓喜闻乐见的文化艺术形式。

年画传人张光宁

第一次见到张光宁的木版年画，是在春节庙会上。在众多摊位中，他的两只木版彩色套印技术做成的布老虎神气手极了。那虎印技术做成的布老虎神气极了。那虎翘着尾巴，神态逼真，身上装饰着彩绘花紋和盛开的花朵，全身散发着喜气。我问多少钱，他耸耸肩，对我说：“这是魏州①虎。“言外之意是在告诉我这个外行，这虎可是系出名门。我心想：”魏州是哪儿？我不知道别人也未必知道，这算什么推销术？“这是他給我留下的第一印象。

”这个卖年画的不像个商人“，这是他给我留下的第二印象。当你和他讨价的时候，他立刻就变得不好意思起来，说话吞吞吐吐。什么”这是纯手工的“”残次品不可避免“这些现成的”谢谢绝“还价的理由他一条也说不出来相反却唠唠叨叨地总想和你讨论木版年画中深厚的文化底蕴。


相识久了才知道，他在年画的故乡出生、长不，从小就画年画，基本功扎实，后来又对年画的构图创作、人物塑造雕版手法、颜料加工等进行了广泛的研究。当他的作品逐步被市场认可后，他又不满足了，中国年町虽不分派别，但不同地区的年画各有所长，都值得学习倩鉴。于是，他再接再厉，数年间走遍了全国各不年画产地，与同行进行广泛的交流。不仅如此，参加民俗文化巡展，走进不学和师生就相关主题进行研討，訟流艺术心得，他从不缺席。

张光宁一年至头真够忙的，可他总是干劲十足。他曾真诚地说：“年画占据了我生命的全部，我喜欢它，热爱它、发展它。”是啊，愈是经营年画久了，他对年画就愈是热爱。他已确立了自己的目标--传播他喜爱的这一民俗文化。他的信念就是拓展年画的内容，使其雅俗其赏，为更多民众所喜爱，虽然任重道远，也不会一帆风顺，但他一定会坚持下去。

** footnotes

① 唐宋：朝代名。唐：公元618年～公元907年。宋：公元960年～公元1279年。
① 清朝：朝代名。公元1616年～公元1911年。
② 明：朝代名。公元1368年～公元1644年。
① 魏州：地名：在今河北此省邯郸市魏县。其传统花布染织技艺至今仍然风格独具。

** new words

起源 / qi3 yuan2 / origin, beginning ;
文献 / wen2 xian4 / document, literature ;
凶恶 / xiong1 ' e4 / fierce, vicious ;
揭露 / jie1 lu4 / to expose, to uncover ;
昌盛 / chang1 sheng4 / properous, flourishing ;
题材 / ti2 cai2 / subject, theme ;
驱逐 / qu1 zhu2 / to drive out, to expel ;
古祥 / ji2 xiang2 / lucky, propitious ;
里程碑 / li3 cheng2 bei1 / milestone ;
墨水儿 / mo4 shui3 r / ink ;
盖章 / gai4 zhang1 / to seal, to stamp ;
联想 / to lian2 xiang3 / to associate, to connect in the mind ;
涂抹 / tu2 mo3 / to paint, to daub ;
终究 / zhong1 jiu1 / eventually, in the end, after all ;
烟花爆竹 / yan1 hua1 / bao4 zhu2 / fireworks, firecrackers ;
寄托 / ji4 tuo1 / to place (hope, etc.) on ;
增添 / zeng1 tian1 / to add ;
丰收 / feng1 shou1 / to have a bumper harvest ;
犮财 / fa1 cai2 / to make a  fortune ;
连年 / lian nian2 / in successive years, in consecutive years ;
寓言 / yu2 yan2 / fable, allegory, parable ;
信仰 / xin4 yang3 / faith, belief ;
喜闻乐见 / xi3 wen2-le4 jian4 / to love to see and hear, to be delightd to hear and see ;
神气 / shen2 qi4 / impressive, vigorous ;
翘 / qiao4 / to raise (one's head, tail, etc.) ;
神态 / shen2 tai4 / expression, manner, miem ;
盛开 / sheng4 kai1 / to be in full bloom ;
散发 / san4 fa1 / to send forth, to give off ;
耸 / song3 / to shrug ;
州 / zhou1 / prefecture ;
外行 / wai4 hang2 / layman, outsider ;
推销 / tuii xiao1 / to promote sales ;
吞吞吐吐 / tun1 tun1 tu3 tu3 / to mutter and mumble, to falter out a few words ;
残次品 / can2 ci4 pin3 / damaged or defective product ;
次品 / ci4 pin3 / defective product ;
现成 / xian4 cheng2 / ready-made ;
谢绝 / xie4 jue2 / to refuse, to decline ;
故乡 / gu4 xiang1 / hometown ;
扎实 / zha1 shi / solid, sound ;
塑造 / su4 zao4 / to portray ;
手法 / shou3 fa3 / skill, technique ;
派别 / pai4 bie2 / faction, school ;
借鉴 / jie4 jian4 / to use for reference, to draw lessons from ;
再接再厉 / zai4 jie1 - zai4 li4 / to make persistent efforts ;
心得 / xin1 de2 / what one has learned from work, study, etc. ;
缺席 / que1 xi2 / to be absent (from a meeting, etc.) ;
干劲 / gan4 jin4 / passion, energy ;
占据 / zhan4 ju4 / to occupy, to take over ;
确立 / que4 li4 / to establish ;
言念 / xin4 nian4 / faith, belief ;
任重道远 / ren4 zhong4 - dao4 yuan3 / it is an arduous task and the road is long, to take a heavy burden and embark on a long road ;
一帆风顺 / yi4 fan1 - feng1 shun4 / everything is going smoothly; to go off smoothly, to have a favorable wind all the way ;
** QUESTION Is 增添 used in mathematical contexts?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-17 Wed 14:53]
:END:

