* 课文
** 转录
到今天为止，我们的社会对好男人的标准从没有改变过：男人要有责任心，为人正直、宽容、刚毅，不背叛朋友；男人要上进，有抱负，有魄力；男人要谦虚，诚实，大方；男人要有修养，心胸开阔，处境艰难而不退缩，面对打出而不脆弱；男人是生活中的榜样，家庭的靠山，社会的支柱。总之，男人要顶天立地，光彩照人，要有男人的气概。
不仅如此，男人们从小受到的教育就是“男儿有泪不轻弹”，意思是说，理智的男子汉再悲伤也不轻易哭泣，爱哭的男人走到哪儿都会被一票否决，因为男人流泪就意味着软弱、没出息，而这种教育是从娃娃时代就潜移默化地在起作用了，他们天天被这样的古训鞭策着。我们的文化赋予了男人高大、坚强的形象，他们在生活中必须扮演强者。
男人们为了不被鄙视，不被讥笑，为了远离那些恶心、不体面的词汇，千百次暗暗叮嘱自己：伤心是软弱的表现，哪怕遭受打击、面对失败、受尽委屈，也一定要坚强，这是什么时候都不能含糊的。
实际情况是，“男儿有泪不轻弹”是社会文化赋予男人的一种束缢。男人不是魔鬼，也不是神仙，他们也是有血有肉、有健全情感的人。男人也有喜怒哀乐，也需要关怀，也需要温柔的抚慰，否则，再有力的肩膀也有被压塌的时俞。事实表明，长期的压抑、隐忍对健康只有坏处，没有好处，反之，以适当的方式将情绪释放一下，人的心绪才会变得平和。
其实，眼泪是情绪释放的一种形式，人在情绪抑郁时会分泌一种被称为痛苦激素的物质，它会让人情绪低落、无精打采，眼泪恰恰可以将它排出体外。通常人们哭泣后，在情绪强度上会降低 40％，如果不能利用眼泪把情绪压力转移掉，则会影响身体健康。
中医认为，忧伤肺。当人难过、想哭的时候，喉咙里会觉得不舒服。喉呈咙接通肺，喉咙不舒服，就是肺部受刺激了；人哭起来常常会一把鼻涕一把泪，之所以会流鼻涕，也是肺受了刺激。一旦悲伤难过没有了，也就不再流鼻涕了，喉咙也会舒适起来。这说明，悲伤难过对肺会有影响。伤心难过之际，不妨痛哭。哭完了，一切都得到了修复。因此，不发给男人宣泄情绪的许可证不是正道，男人也有流泪的权利。我们倡导要给男人释放情绪的空间，男人流泪本在情理之中。
不过，宣泄归宣泄，宣泄时忌讳哭泣时间过长，一般不要超过 15分钟，压抑的心情得到发泄、缓解后就不要再哭，否则对身体反而有害。因为人的胃肠机能对情绪极为敏感，忧愁悲伤或哭注时间过长，胃的运动会减慢，会影响食欲，甚至引起其他胃部疾病。
释放情绪除了哭泣，还应在想法上做调整：扔掉外界对男人流泪的鄙视，因为这种鄙视只是一种狭隘的偏见。不要阻挠男人流泪，男人流泪不等于软弱无用，也并不丧失尊严。男人本身也不必理睬别人说三道四，谁都不能长久地淹没在忧伤、难过的情绪中。偶尔具有负面情绪不是什么坏事，它能让我们更了解自己，让我们成长，让我们更深刻地体悟到什么是快乐。
须知，真正的个人成长往往来自于痛苦、磨难，而非快乐，不要抹杀掉痛苦在我们成长中的功劳。既然悲伤无可避免，就应该好好面对悲仿，不要妄想生命中从不出现这样的过程和阶段。毕章，快乐往往是短暂的，人生岁月中更多地伴随着的是灰暗的情绪，而它却可以沉淀出智慧。
