* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 464211dd-1fe6-4a35-ac80-7ae4013a7a7b
:END:
**** 对话
***** 转录
女：这么多家卖沙丁鱼的店，怎么只有那家特别贵？[[file:4e193828-2650-48ff-8ceb-9d8572b33e35.mp3][(audio)]]
男：只有他们知道怎么延长沙丁鱼的存活期。[[file:e4e8ad49-bf27-448a-a1b1-4cb5ba4fcf02.mp3][(audio)]]
***** 音频
d5a6e711-f6e3-4846-a5fe-e51a7c887b1f.mp3
**** 问题
***** 转录
从对话中可以知道什么？
***** 音频
ecf9c092-db08-4a2b-938b-cb124c3b8c79.mp3
**** 选择
***** A
只有一家店卖沙丁鱼
***** B
活鱼和死鱼价格相同
***** C
那家店的老板很自私
***** D
让沙丁鱼存活很困难
**** 答案
D
*** 2
:PROPERTIES:
:ID: 453d8679-b97d-4e3a-ad34-52cd7e6e666f
:END:
**** 对话
***** 转录
男：你昨天的飞机几点到的？[[file:e8d54353-0a06-414c-b71b-019ce4a63eba.mp3][(audio)]]
女：别提了，快 12 点才到，晚点了 4 个小时。[[file:446e41af-ed88-4b3d-adde-c8b760b72e70.mp3][(audio)]]
***** 音频
358ad66d-b3cc-415a-95b8-00cddbddf513.mp3
**** 问题
***** 转录
飞机本来应该几点到？
***** 音频
3a3addb6-f641-45fa-af93-8d5dd2306350.mp3
**** 选择
***** A
8 点多
***** B
快 8 点
***** C
12 点
***** D
4 点
**** 答案
B
*** 3
:PROPERTIES:
:ID: 6469f4fd-2f33-4255-94d5-0e0602a1383f
:END:
**** 对话
***** 转录
女：听说对方有个队员非常强，你有把握吗？[[file:e8277fe0-3371-40f3-8f72-949844248a3c.mp3][(audio)]]
男：我不觉得他可以对我构成威胁。[[file:c486cee2-143b-4460-8438-075a179da6ae.mp3][(audio)]]
***** 音频
edfdb490-30d1-43c9-8224-4b1ccaa8f993.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
7db3a209-3423-4cfd-b81d-18f7d2d20873.mp3
**** 选择
***** A
对手水平很高
***** B
他不了解对手
***** C
他们没比过
***** D
对手不如他
**** 答案
D
*** 4
:PROPERTIES:
:ID: 0e71c105-2236-447a-b9f6-1a6a42897fd3
:END:
**** 对话
***** 转录
男：你们今年不招聘男老师吗？[[file:5de6806f-3599-44c3-83f1-4e243ee709f4.mp3][(audio)]]
女：我们是理工科学校，男老师占的比例太大了。[[file:d0c5f71b-fef6-41e9-b7c1-544e378a9955.mp3][(audio)]]
***** 音频
7c7f56a1-b072-47eb-8730-dec2a78019b1.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
9a744006-a7f2-44ff-aa3a-f38cd09226b2.mp3
**** 选择
***** A
他们要招聘男老师
***** B
优秀的男老师也可以
***** C
他们希望男女比例平衡
***** D
今年招聘对性别没有要求
**** 答案
C
*** 5
:PROPERTIES:
:ID: 9fabcaa6-733e-4c75-b70b-fd3310aa7d41
:END:
**** 对话
***** 转录
女：你觉得小张能办好这件事吗？[[file:a25c62c4-7d07-4311-9188-fbbfaccc62c5.mp3][(audio)]]
男：我听他说了他的想法，我觉得的确很巧妙。[[file:4414092f-eac4-4a18-8c57-c2e17566b763.mp3][(audio)]]
***** 音频
f04e8f5d-bab8-4c07-981c-391b81cf81c1.mp3
**** 问题
***** 转录
男的是什么态度？
***** 音频
1017b274-799e-4595-bd87-89096d36bcc3.mp3
**** 选择
***** A
信任
***** B
鼓励
***** C
怀疑
***** D
反对
**** 答案
A
*** 6
:PROPERTIES:
:ID: 296e4e84-bb2c-44d1-8293-edfe0080c8e0
:END:
**** 对话
***** 转录
男：那里是山区，条件那么差，你怎么会想到要去支教呢？[[file:416b0f14-1478-4414-b566-4a01701a119a.mp3][(audio)]]
女：正因为那里是落后地区，才需要大家去建设。[[file:9f215570-aa40-464f-854a-198b989f7507.mp3][(audio)]]
***** 音频
b1521e05-c6dd-47c2-aecb-65e35b8e581d.mp3
**** 问题
***** 转录
关于山区，下列哪项正确？
***** 音频
b83c5caf-2183-4848-8644-01a892538487.mp3
**** 选择
***** A
条件很好
***** B
正在建设
***** C
非常落后
***** D
发展很快
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：我已经两个月没有跟他见面了，也不接他的电话。
男：你总这么逃避也不是办法。
女：可是我不知道该怎么跟他说……
男：不知道怎么说也得说啊，时间越久越麻烦。
***** 音频
d10722bf-0185-4af3-8ac5-0933be2d81b0.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
c079bc8c-7e4f-45e9-8ace-cfba7a642cef.mp3
**** 选择
***** A
应该多打电话
***** B
没有必要见面
***** C
要面对这个问题
***** D
过一段时间就好了
**** 答案
C
*** 8
**** 对话
***** 转录
男：来中国一年多了，你有什么感想？
女：我最大的体会就是中国太大了，要学的、要看的、要吃的太多了，只待两年远远不够。
男：那你打算延长留学时间吗？
女：我正在考虑这个问题。
***** 音频
5abeb84c-91a0-44cd-87df-41ed47deb3fc.mp3
**** 问题
***** 转录
关于女的，下列哪项正确？
***** 音频
a2856077-90e0-4662-9d8d-90359bf33d61.mp3
**** 选择
***** A
她想来中国留学
***** B
她正在中国学习
***** C
她延长了留学时间
***** D
她推迟了人学时间
**** 答案
B
*** 9
**** 对话
***** 转录
女：这批来应聘的人，你对谁比较满意？
男：我觉得那位刘先生不错，很会做商业谈判。
女：但他原来是做进出口贸易的，跟我们离得有点儿远，年龄也大了些。
男：专业知识不是问题，可以学嘛。
***** 音频
76486ef6-63a9-4784-9b4f-1ed6c8d7a610.mp3
**** 问题
***** 转录
刘先生的优势是什么？
***** 音频
422bb322-ee2e-4e65-ac6b-fdadd27d0706.mp3
**** 选择
***** A
年龄大
***** B
做进出口贸易
***** C
善于商业谈判
***** D
专业知识丰富
**** 答案
C
*** 10
**** 对话
***** 转录
男：最近股票市场很火，你不打算试试吗？
女：股市风险太大了。
男：现在形势好，我们楼里的大爷大妈都赚钱了。
女：正因为连大爷大妈都开始炒股了，我才害怕呢。
***** 音频
806f4810-4947-4920-93a6-72c523387d85.mp3
**** 问题
***** 转录
女的对炒股是什么态度？
***** 音频
46ecf5e1-3b8a-4cde-a80e-f4588f914cbc.mp3
**** 选择
***** A
赞成
***** B
反对
***** C
想试试
***** D
无所谓
**** 答案
B
*** 11-12
**** 对话
***** 转录
女：爸爸，今天生物课上，老师教了我们达尔文的“自然选择学说”。
男：是吗？那你说说是什么意思。
女：简单地说，“自然选择”就是生物之间存在着竞争，适应者才能够生存下来，不适应的则会被淘汰。
男：说得真清楚！
女：我们人类也是通过这样的竞争，躲开了很多天敌的威胁，才生存到今天的。
男：是的。不过，自然选择的范围也没有当年达尔文所说的那么广泛。以后这些你也会慢慢学到的。
***** 音频
3226f8d7-0c4e-441b-a9b9-10e797ccbdf9.mp3
**** 题目
***** 11
****** 问题
******* 转录
“自然选择学说”是谁提出来的？
******* 音频
1ba9e8e5-ac7f-4919-a8db-9ad2d51f4f84.mp3
****** 选择
******* A
爸爸
******* B
女儿
******* C
达尔文
******* D
生物老师
****** 答案
C
***** 12
****** 问题
******* 转录
根据这段对话，下列哪项正确？
******* 音频
fe662708-1d7f-4c7a-9e95-6da6025b8513.mp3
****** 选择
******* A
女儿没听懂今天的课
******* B
老师教的内容是错的
******* C
不参加比赛会被淘汰
******* D
动物之间存在着竞争
****** 答案
D
*** 13-14
**** 段话
***** 转录
一只兔子被猎人打伤了，但它竟然带着枪伤成功地逃过了猎狗的追捕，回到了家里。同伴们都围过来惊讶地问它：“那只猎狗很凶呀，你又带着伤，是怎么甩掉它的呢？”兔子说：“它是跑得快，但我用尽了全力呀！它没追上我，最多挨一顿骂，而我如果不用尽全力地跑，就没命了！”每个人都有很大的潜能。正如心理学家所指出的，一般人的潜能只开发了 2%-8%左右。这就是说，我们还有90%多的潜能处于沉睡状态。谁要想成功，必须用尽全力才行。
***** 音频
b732e7a0-e2e6-499f-b4c6-d8d0efba0551.mp3
**** 题目
***** 13
****** 问题
******* 转录
谁被打伤了？
******* 音频
be6752a0-f9d0-4bdc-8195-43225e368ad9.mp3
****** 选择
******* A
猎人
******* B
猎狗
******* C
兖子
******* D
心理学家
****** 答案
C
***** 14
****** 问题
******* 转录
兔子为什么可以逃跑？
******* 音频
86e4f04a-82b9-42d5-b096-e96c826fb698.mp3
****** 选择
******* A
猎狗受伤了
******* B
同伴来救它了
******* C
猎人对它没兴趣
******* D
它用尽全力地跑
****** 答案
D
* 阅读
** 第一部分
*** 课文
*** 题目
**** 15
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 16
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 17
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 18
***** 选择
****** A
****** B
****** C
****** D
***** 答案
** 第二部分
*** 19
:PROPERTIES:
:ID: cb9c6a6a-1def-491f-ade9-b4446822e87e
:END:
**** 段话
很多研究发现，适度的压力有利于我们保持良好的状态，更加有助于挖掘我们的潜力，从而提高个人的工作效率。比如运动员每到参加比赛，尤其是决赛时，一定要将自己调整到接近最佳状态，感到适度的压力，让自己兴奋，如果他不紧张、没压力感，则不利于出成绩。适度的压力对挖掘自身的潜力，是有正面意义的。
**** 选择
***** A
压力和状态成正比
***** B
给人的压力应适度
***** C
运动员要特别紧张才有好成绩
***** D
潜力只有在压力大时才能发挥出来
**** 答案
B
*** 20
:PROPERTIES:
:ID: e4e86288-38a5-47c7-9386-8a02bf782dfa
:END:
**** 段话
美国有个43岁的妇女，为她姨妈向政府申请到了一个免费的轮椅。她所做的不过是准备了一些必要的文件，并填写了一些表格。为此，她写了一篇如何向政府申请免费轮椅的报告。然后，她在网上卖她的报告，售价仅仅2美元，后来她每月可赚3万！简直难以置信，这么简单的事会有市场，会有如此的潜在利益！
**** 选择
***** A
这个妇女为母亲买了一个轮椅
***** B
申请免费轮椅的手续非常简单
***** C
妇女申请免费轮椅是为了卖钱
***** D
作者认为她赚到钱是很合理的
**** 答案
B
*** 21
:PROPERTIES:
:ID: a296f5b8-7eb5-4c92-8810-abadd4c8f778
:END:
**** 段话
一家森林公园曾养了几百只梅花鹿。尽管环境幽静，水草丰美，又没有天敌，但几年以后，鹿群非但没有发展，反而病的病，死的死，竟然出现了负增长。后来公园买回儿只狼放置在园内。在狼的追赶捕食下，鹿群只得紧张地奔跑逃命。这样一来，除了那些老弱病残者被狼捕食外，其他鹿的体质日益增强，数量也迅速地增长起来。
**** 选择
***** A
梅花鹿没有天敌
***** B
森林公园的环境不好
***** C
狼和梅花鹿相处得很好
***** D
狼的追赶使梅花鹿体质增强
**** 答案
D
*** 22
:PROPERTIES:
:ID: 15989f29-3028-4375-a95a-038cd1e2fb30
:END:
**** 段话
市场竞争是指商品生产者或者商品经营者为争夺有利的生产或流通条件、地位而进行的斗争。竞争是商品经济的一般规律，它是商品本身内在矛盾的产物，只要存在商品生产和商品交换，竞争规律就起作用。商品经济还有一个重要的价值规律。价值规律存在，必然产生竞争；同时，价值规律的作用，也只有在竞争中才能实现。
**** 选择
***** A
竞争规律和价值规律是同一个理论
***** B
市场竞争是商品生产者之间的问题
***** C
只要有商品生产和交换，就有竞争
***** D
即使没有竞争也可以体现价值规律
**** 答案
C
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
