* 课文

** 标题

竞争让巿场更高效

** 转录
西班牙人特别喜欢吃沙丁鱼。但沙丁鱼对离开大海后的环境极不适应，运输就成了问题。鱼上岸后，过不了多久就会死去。而死掉的沙丁鱼口感很差，作为商品销售，价格就会便宜很多。如果上岸时沙丁鱼还活着，鱼的卖价可以涨很多倍。
为了延长沙丁鱼的存活期，减少经济损失，渔民们想了很多办法，但情况仍然没有得到太大的改善。后来一位渔民无意中发现了一种巧妙而实用的方法：把几条沙丁鱼的天敌鲇鱼放进装鱼的设备中。因为鲇鱼是食肉鱼，无法和沙丁鱼和平共处，它会四处游动寻找小鱼吃，对沙丁鱼构成威胁。为了逃避天敌，沙丁鱼自然会不断地加速游动，从而保持了旺盛的生命力，存活的比例大大提高。
看到这里，你有什么感想和体会呢？其实，这在经济学上被称为“鲇鱼效应”。“鲇鱼效应”对于市场经济以及现代企业管理都有着重要的启发作用。这个概念的核心是：一个市场如果能采取一种措施，刺激企业活跃起来，就能使企业获得足够的活力，在市场中积极参与竞争而不至于落后，同时这样反过来又能促使市场更为高效。
从本质上说，“鲇鱼效应”使得企业和员工产生一种危机感，其实就是一种压力效应。很多研究发现，适度的压力有利于我们保持良好的状态，更加有助于挖掘我们的潜力，从而提高个人的工作效率。比如运动员每到参加比赛，尤其是决赛时，一定要将自己调整到接近最佳状态，让自己感到适度的压力，如果他不紧张、没压力感，则不利于出成绩。因此，“鲇鱼效应”的确对挖掘员工潜力、提高企业活力具有积极的意义。
** source

改编自《每天学一点经济学》

** 生词

培养 / pei2 yang3 / to foster, to train ;
对手 / dui4 shou3 / opponent, rival ;
公寓 / gong1 yu4 / appartment, flat ;
文具 / wen2 ju4 / stationery ;
电池 / dian4 chi2 / battery, cell ;
日用品 / ri4 yong4 pin3 / articles of everyday use, daily necessities ;
利润 / li4 run4 / profit ;
诚信 / cheng2 xin4 / honest, in good faith ;
媒体 / mei2 ti3 / media, mass media ;
对象 / dui4 xiang4 / target, object ;
营业 / ying2 ye4 / to do business, to operate ;
额 / e2 / specified number, sum, volume or amount ;
不如 / bu4 ru2 / to be not as good as, to be inferior to ;
干脆 / gan1 cui4 / simply, just ;
挤 / ji3 / to squeeze out, to push out ;
垮 / kua3 / to collapse, to break down ;
垄断 / long3 duan4 / to monopolize ;
倒闭 / dao3 bi4 / to close down, to bankrupt ;
热心 / re4 xin1 / enthusiastic, earnest ;
资金 / zi1 jin1 / capital, fund ;
傻 / sha3 / stupid, foolish ;
倒霉 / dao3 mei2 / having bad luck, unlucky ;
生态 / sheng1 tai4 / ecology ;
商业 / ling3 yu4 / field, domain, realm ;
领域 / shi4 dang4 / proper, adequate ;
适当 / shi4 dang4 / proper, adequate ;
促使 / cu4 shi3 / to urge, to spur, to prompt ;
生长 / sheng1 zhang3 / to grow ;
妨碍 / fang2'ai4 / to hinder, to impede ;
促进 / cu4 jin4 / to promote, to accelerate ;
利益 / li4 yi4 / benefit, interest ;
合理 / he2 li3 / reasonable ;
万一 / wan4 yi1 / in case, if by any chance ;
维持 / wei2 chi2 / to keep, to mantain ;
饱和 / bao3 he2 / to be saturated, to be filled to capacity ;
不见得 / bu2 jian4 de2 / not necessarily, may not ;

** 专有名词

建伟 / jian4 wei3 / Jianwei, name of a person ;
* 练习

** 1
:PROPERTIES:
:ID: e92182fb-1684-425e-aa72-eb9440f99b8a
:END:
*** 选择
**** 1
实用
**** 2
接近
**** 3
落后
**** 4
逃避
**** 5
构成
**** 6
延长
*** 题目
**** 1
***** 句子填空
中国的发展和强大不会对任何人[[gap]]威胁。
***** 答案
5
**** 2
***** 句子填空
遇到因难不应该[[gap]]，应该积极地面对。
***** 答案
4
**** 3
***** 句子填空
由于报名的考生太多，学校决定适当[[gap]]报名时间。
***** 答案
6
**** 4
***** 句子填空
公司在产品包装、宣传推广和销售等方面积累了当丰富、[[gap]]的经验。
***** 答案
1
**** 5
***** 句子填空
中国各地区经济发展水平不平衡，中西部[[gap]]于东南沿海地区。
***** 答案
3
**** 6
***** 句子填空
参加本届运动会的运动员人数[[gap]]一万人。
***** 答案
2
** 2
*** 1
:PROPERTIES:
:ID: 6dee5848-8877-4f29-ac8b-5ea41b20f05e
:END:
**** 句子填空
你听谁说刘方要结婚了？消息[[gap]]吗？
**** 选择
***** A
有确
***** B
确实
**** 答案
B
*** 2
:PROPERTIES:
:ID: a8d9094c-e7c9-495b-902d-35a0c0ad20b5
:END:
**** 句子填空
主任临时有点儿事，下午的会[[gap]]到明天了。
**** 选择
***** A
延长
***** B
推迟
**** 答案
B
*** 3
:PROPERTIES:
:ID: 57d79e3d-3431-45e4-bedb-69e8d5fe6601
:END:
**** 句子填空
让孩子[[gap]]到自己的意见受到尊重，这一点很重要。
**** 选择
***** A
体会
***** B
感想
**** 答案
A
*** 4
:PROPERTIES:
:ID: 19bd36ec-1e5f-41b0-b4ca-2d12e3e7282c
:END:
**** 句子填空
他[[gap]]就看不见这些美丽的花呀。
**** 选择
***** A
本质
***** B
根本
**** 答案
B
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
没备
***** 答案
笨重
**** 2
***** 词语
体会
***** 答案
深刻
**** 3
***** 词语
概念
***** 答案
抽象
**** 4
***** 词语
效率
***** 答案
惊人
*** 2
**** 1
***** 词语
说话
***** 答案
巧妙
**** 2
***** 词语
经济
***** 答案
落后
**** 3
***** 词语
方法
***** 答案
实用
**** 4
***** 词语
世界
***** 答案
和平
* 扩展
** 词语
*** 话题
经济2
*** 词语
**** 1
出口
**** 2
进口
**** 3
贸易
**** 4
谈判
**** 5
合同
**** 6
中介
**** 7
破产
**** 8
资金
**** 9
利润
**** 10
股票
**** 11
账户
**** 12
利息
**** 13
贷款
**** 14
汇率
**** 15
押金
** 题目
*** 1
**** 句子
他从事对外[[gap]]工作多年，积累了丰富的经验。
**** 答案
3
*** 2
**** 句子
[[gap]]进行得还算顺利，是快下周就可以签合同了。
**** 答案
4
*** 3
**** 句子
公司的项目挺不错，但资金出了问题，目前面临[[gap]]危险。
**** 答案
7
*** 4
**** 句子
买房的[[gap]]还有三四年就可以还清了。
**** 答案
13
* 注释
** （三）词语辨析
*** 接近——靠近
**** 做一做
***** 1
****** 句子
做这个动作时，大腿要尽量[[gap]]胸部。
****** 答案
******* 1
******** 接近
0
******** 靠近
1
***** 2
****** 句子
直到天快亮的时候，他的体温才[[gap]]正常。
****** 答案
******* 1
******** 接近
1
******** 靠近
0
***** 3
****** 句子
这项技术已[[gap]]世界先进水平。
****** 答案
******* 1
******** 接近
1
******** 靠近
0
***** 4
****** 句子
对于这个问题，几国的意见很[[gap]]。
****** 答案
******* 1
******** 接近
1
******** 靠近
0
