:PROPERTIES:
:CREATED: [2022-03-19 07:06:38 -05]
:END:

* Text
:PROPERTIES:
:CREATED: [2022-03-20 00:26:24 -05]
:END:

** 1. 在学校 In the school
:PROPERTIES:
:CREATED: [2022-03-20 00:26:37 -05]
:ID: adc9cda3-bbd1-481a-b5e8-2b4ae7aed162
:END:

Dialogue

Ａ：你知道小王今天什么时候来学校吗？
pi: nǐ zhīdào xiǎo wáng jīntiān shénme shíhou lái xuéxiào ma
en: do you know when Xiao Wang will come to school today?
es: ¿sabes cuándo viene Xiao Wang a la escuela hoy?

Ｂ：她已经来了。
pi: 
en: 
es: 

Ａ：你怎么知道他来了？
pi: 
en: 
es: 

Ｂ：我在门外看见他的自行车。
pi: 
en: 
es: 


New words

门 | mén | door, gate | puerta | noun ;

外 | wài | outer, outside | noun ;

自行车 | zìxíngchē | bike, bicycle | bicicleta | noun ;



** 2. 在饭馆 In a restaurant
:PROPERTIES:
:CREATED: [2022-03-20 00:29:47 -05]
:ID: 1a7e70bb-3648-4b70-b4ce-f32c46f871a8
:END:

Dialogue

Ａ：今天的样肉很好吃，你怎么不吃了？
Ｂ：这个星期天天都吃样肉，不想吃了。
Ａ：那你还想吃什么？
Ｂ：来一点儿面条吧。

New words

羊肉 | mutton | yángròu | mutton | noun ;

好吃 | hǎochī | delicious | yummy | adjective ;

面条 | miàntiáo | noodles | fideos | noun ;

** 3. 在健身房 | In the gym
:PROPERTIES:
:CREATED: [2022-03-20 00:35:10 -05]
:ID: f7c5878f-c395-41a4-a2bf-23b66819d801
:END:

Dialogue

Ａ：昨天你们怎么都没去打篮球？
Ｂ：因为昨天下雨，所以我们都没去。我去游泳了。
Ａ：你经常游泳吗？
Ｂ：这个月我天天游泳，我现在七十公斤了。

Note

打篮球
pi: dǎ lánqiú
en: to play basketball
es: jugar baloncesto

因为 | yin1 wei4 | because, since | porque | conjugation ;

所以 | suo3 yi3 | so, therefore | entonecs, por lo tanto | conjugation ;

游泳 | you2 yong3 | to swim | nadar | verb ;

经常 | jing1 chang2 | often, frequently | adverb ;

公斤 | gong1 jin1 | kilogram | kilogramo | modal ;

** 4. 在办公室 In the office
:PROPERTIES:
:CREATED: [2022-03-20 00:41:54 -05]
:ID: 0e3766b3-cd5e-49f4-9961-9ab0352f0005
:END:

Dialogue

Ａ：这两天怎么没看见小张？
Ｂ：他去北京了。
Ａ：去北京了？是旅游吗？
Ｂ：不是，听说是去看他姐姐。

New words

姐姐 | jiějie | elder sister | hermana mayor | noun ;

* Notes
:PROPERTIES:
:CREATED: [2022-03-20 00:47:48 -05]
:END:

** Redeplication of measure words
:PROPERTIES:
:CREATED: [2022-03-20 00:47:53 -05]
:END:

When a measure word is reduplicated, it means "every/each", emphasizing that a specific feature is shared by every member in a certain group, usually followed by "都". For example:

|----------------+------+----------|
| Subject        | AA   | 都...    |
|----------------+------+----------|
| 同学们         | 个个 | 都很高兴 |
| 这个商店的衣服 | 件件 | 都很漂亮 |
| 这个星期（我） | 天天 | 都吃样肉 |
|----------------+------+----------|

同学们个个都很高兴。
pi: tóngxué men gègè dōu hěn gāoxìng
en: The students were all very happy.
es: Los estudiantes estaban muy contentos.

这个商店的衣服件件都很漂亮。
pi: zhègè shāngdiàn de yīfu jiànjiàn dōu hěn piàoliang
en: All the clothes in this store are beautiful.
es: Toda la ropa de esta tienda es preciosa.

这个星期（我）天天都吃羊肉。
pi: zhègè xīngqī wǒ tiān tiān dōu chī yángròu
en: I ate lamb every day this week.
es: Esta semana he comido cordero todos los días.

* Exercises
:PROPERTIES:
:CREATED: [2022-03-19 07:05:23 -05]
:END:

** 3
:PROPERTIES:
:CREATED: [2022-03-19 07:05:25 -05]
:ID: a66bf97f-2b52-42b9-b1ab-a0cf88fd797b
:END:

这儿的衣服（件件都很漂亮）。

女孩儿们（个个都很高兴）。

因为天气很冷，所以我（生病了）。

因为（外面下雨），所以我们在家吃晚饭。

