* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 2467db57-405e-486f-a4b3-fe633ac7efce
:END:
**** 对话
***** 转录
女：一到周一，我就发现这体重又上去不少，真没办法。[[file:54f4b0b4-f173-414e-9c46-9a631783218c.mp3][(audio)]]
男：还说呢，周末又在家做什么好吃的了吧？[[file:f1415899-d2fe-4e8e-b4a2-b787f10424ec.mp3][(audio)]]
***** 音频
0a4f565d-6598-4b24-8b0f-a5a227f5cf7e.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
5b9b3687-5ae0-4b53-9518-e28f1f501ba9.mp3
**** 选择
***** A
没觉得女的胖了
***** B
周末不该吃太多
***** C
女的做饭越来越好
***** D
让女的给他做点儿好吃的
**** 答案
B
*** 2
:PROPERTIES:
:ID: 96d7e558-9386-451c-942d-e41e1dd21931
:END:
**** 对话
***** 转录
男：小明吃坏肚子了，又吐又拉。[[file:9e12697f-3e63-4905-ac9d-abccbebc26d2.mp3][(audio)]]
女：那你赶紧带他去看急诊吧。[[file:a6b97c76-111e-4744-af6a-ba50cc3b5575.mp3][(audio)]]
***** 音频
c96cc1e7-7274-4399-9578-487894b1cb95.mp3
**** 问题
***** 转录
小明怎么了？
***** 音频
a8c520da-f5a6-4968-a347-0fd75f290cce.mp3
**** 选择
***** A
胃疼
***** B
拉肚子
***** C
受伤了
***** D
过敏了
**** 答案
B
*** 3
:PROPERTIES:
:ID: a9c5301f-a3ee-4f4b-99cc-628ffc9eebe1
:END:
**** 对话
***** 转录
男：昨天散步碰到你舅舅了。[[file:c20dcc42-c586-4786-b6c5-e39bcb815b82.mp3][(audio)]]他气色不错，走起路来挺有精神的。[[file:0947b79b-ab93-4427-bbf7-816ad137bd4b.mp3][(audio)]]
女：得谢谢您介绍了那位专家，吃了他开的汤药，我舅舅现在好多了。[[file:e2b46d46-4b4b-4bc3-ae4d-de213ff02e26.mp3][(audio)]]
***** 音频
a7a73f4c-d5f6-4cf6-8e3f-3ef1c6d5ff34.mp3
**** 问题
***** 转录
关于舅舅，可以知道什么？
***** 音频
01c4f384-e6d6-441d-abd1-30b277bdfbef.mp3
**** 选择
***** A
身体恢复很好
***** B
是位医学专家
***** C
每天都去散步
***** D
走路没有精神
**** 答案
A
*** 4
:PROPERTIES:
:ID: 848a9514-671f-44f5-b90f-69c7824e2aef
:END:
**** 对话
***** 转录
男：最近，胃总不舒服，想去人民医院看看，又怕排队人多，挂不上号。[[file:5d7cc3a7-27d0-41f5-b3f8-0cf4b16fcf6b.mp3][(audio)]]
女：你可以预约呀，打个电话或上网都很方便。[[file:4cf22d7c-6fa7-45a8-8a96-b25bc58c2a1c.mp3][(audio)]]
***** 音频
09bd93f3-ec9c-40f9-8ab5-d69f716eb5ed.mp3
**** 问题
***** 转录
关于挂号，女的建议怎么办？
***** 音频
a0b75aee-a397-4887-8d7f-8d1af89a3b3c.mp3
**** 选择
***** A
找医生挂号
***** B
早点儿排队
***** C
打电话预约
***** D
换别的医院
**** 答案
C
*** 5
:PROPERTIES:
:ID: 1d87f1d6-10de-456b-8674-0267f5cc889f
:END:
**** 对话
***** 转录
男：刘大夫，手术做完都一个星期了，我什么时候可以出院？[[file:21fda2b9-29bc-4b41-a84c-b9ab99829975.mp3][(audio)]]
女：昨天检查报告出来了，没问题。明天拆线，后天就可以办手续了。[[file:279508b9-e8e2-4d0a-8015-0d03b605b2f0.mp3][(audio)]]
***** 音频
0483035e-82ad-4881-ae7b-3f6aadae5c80.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
a3e2e6ae-e437-4192-805f-d758d56369de.mp3
**** 选择
***** A
再观察一周
***** B
等报告结果
***** C
拆线后出院
***** D
手术不理想
**** 答案
C
*** 6
:PROPERTIES:
:ID: 6130df1b-a40a-4807-a0e5-f508cbc78ab4
:END:
**** 对话
***** 转录
女：小李，你腿上的伤是怎么弄的？还在流血呢。[[file:e5f6b744-6062-40e6-b248-31e6f8932646.mp3][(audio)]]
男：不要紧，打网球时不小心摔倒了，过几天就好了。[[file:3320612e-0cad-4c0f-ad10-c9d1ec12c4ed.mp3][(audio)]]
***** 音频
195c9b1d-5320-46f8-8b8c-a8f7e07cfd84.mp3
**** 问题
***** 转录
小李的腿是怎么受伤的？
***** 音频
4783346b-b05e-4b79-8543-4e1d759b7ceb.mp3
**** 选择
***** A
打网球摔的
***** B
雪天滑倒了
***** C
和人打架了
***** D
不小心碰的
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
男：今天有客户来谈合同，恐怕我接不了孩子了。
女：不行，我下午有课，要 4 点才能完。
男：今天不是周三吗？他有篮球课，4 点 50 才下课呢。
女：我怎么给忘了，那没问题了，我去吧。
***** 音频
0cb3db8f-14e5-4be2-9116-3a8d77ddb1f4.mp3
**** 问题
***** 转录
他们在商量什么事？
***** 音频
8b2abb00-86b2-465e-9da3-d3310ca03067.mp3
**** 选择
***** A
谁能接孩子
***** B
谁去见客户
***** C
要不要请假
***** D
上不上篮球课
**** 答案
A
*** 8
**** 对话
***** 转录
女：明明，你每天早上刷牙太快了，刷不干净。
男：我赶时间嘛，不然，上课要迟到了。
女：医生说，必须持续三分钟，三个面都刷到，才能保证所有牙齿都刷干净。
男：好吧，下次我注意。
***** 音频
20437861-383f-43fb-ac75-33ed90f784bd.mp3
**** 问题
***** 转录
女的建议男的怎么刷牙？
***** 音频
4081aeb8-560d-43b4-8a9e-988eb5b66c88.mp3
**** 选择
***** A
快点儿刷
***** B
一颖颗地刷
***** C
刷够三分钟
***** D
从外往里刷
**** 答案
C
*** 9
**** 对话
***** 转录
男：大妈，请问您要办理什么业务？
女：我要查一笔钱是不是到账了。
男：柜台排队的人比较多，如果是卡的话，您在那边的自助机上也可以。
女：我不太会操作，还是麻烦你帮我取个号吧。
***** 音频
25c69df6-f5f9-445d-b111-eba029c7daaf.mp3
**** 问题
***** 转录
男的是做什么工作的？
***** 音频
337acdae-7bbb-4aed-ac82-b913eb0a03f2.mp3
**** 选择
***** A
医生
***** B
收银员
***** C
邹递员
***** D
银行职员
**** 答案
D
*** 10
**** 对话
***** 转录
女：大夫，我脸上又红又痒，眼睛也痒得不行。
男：多长时间了？这两天吃了什么？
女：昨天去海边玩儿，吃了海鲜，晚上就发现不对了。
男：我怀疑你是过敏了，先去做个检查吧。
***** 音频
40b02fdb-632f-4e73-b446-3db50d4b71e1.mp3
**** 问题
***** 转录
医生怀疑女的怎么了？
***** 音频
5f8cab8d-52b4-4ffe-a07f-877758449217.mp3
**** 选择
***** A
感冒了
***** B
过敏了
***** C
眼腑发炎
***** D
消化不艮
**** 答案
B
*** 11-12
**** 对话
***** 转录
男：从你的片子上看，骨头没问题，腰疼是肌肉劳损的原因。
女：那您说，我该怎么治疗呢？
男：卧床休息，可以擦点儿缓解疼痛的药膏，好了以后加强腰背部的肌肉训练。
女：大夫，能开点儿止疼药吗？
男：可以是可以，但我们一般不建议吃，除非疼得受不了。
女：那我还是忍一忍吧。
***** 音频
b82d4ffc-06e0-443a-b75d-432516c4a90a.mp3
**** 题目
***** 11
****** 问题
******* 转录
女的怎么了？
******* 音频
9bf63ec1-e127-4cf6-b989-3c3fe11f023a.mp3
****** 选择
******* A
腰肌劳损
******* B
骨头断了
******* C
肌肉拉伤
******* D
头疼失眠
****** 答案
A
***** 12
****** 问题
******* 转录
医生让她做什么治疗？
******* 音频
ce3a880b-75f2-48d2-8f4a-cd9d22ce6b1d.mp3
****** 选择
******* A
尸快手术
******* B
擦些药膏
******* C
吃止疹药
******* D
加强肌肉训练
****** 答案
B
*** 13-14
**** 段话
***** 转录
上世纪四十年代，国外有研究机构发表的报告称，我们每吃 1 卡路里的食物就需要补充 1 毫升的水。这种说法迅速传播开来，到了我们耳朵里，它就成了“每天应该喝 8 杯水”。一位运动学家称：“每天 8 杯水的量，相当于我们每天要补充 2.5 升液体。”但他表示，“液体并不一定非水不可。其中大约 750 毫升液体来自我们每天所吃的食物”。这个量其实很容易就达到了。所以我们常说的所谓“8 杯水”，只是在提醒我们应该多喝水，而且最好在口渴之前主动喝水。事实上，过量饮水反而容易引起身体水肿。在体育界，人们并不鼓励运动员在训练时过多补水，至今，也从未有过体育运动中由于脱水致死的报道。所以，在饮水问题上，适量就好。每个人身体的承受能力并不同，如果“8杯水”对你来说实在很难接受，那么可能“8 杯水”就会导致你饮水过量。
***** 音频
3c012334-6501-4061-8079-c903ea411584.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于补水，我们可以知道什么？
******* 音频
b6ef835c-369b-46a2-8381-445bf936feff.mp3
****** 选择
******* A
训练时应多补
******* B
食物不能补水
******* C
个人承受能力不同
******* D
不舒服就要多补水
****** 答案
C
***** 14
****** 问题
******* 转录
这段短文主要想告诉我们什么？
******* 音频
153fe84d-9fb5-4c03-b96e-703b18af2a68.mp3
****** 选择
******* A
每天要喝8杯水
******* B
口渴之后再喝水
******* C
饮水报告不科学
******* D
每天喝水要适量
****** 答案
D
* 阅读
** 第一部分
*** 段话
古时候，会稽爆发了一场很严重的传染病，儿天之内，就死了一万多人。面对这种情况，县官钟离意吃不下睡不安，他不住地[[gap][15]]“自己：”百姓受苦，我无法解救，还算什么父母官昵？“钟离意[[gap][16]]着被传染的危险，一家又一家地看望病人，安慰他们的家人，并命令亏下人聘请医生研制新药。
几天之后，新药制作出来了，就是不敢马上给病人喝，因为其中有几种有毒的草药。这时，钟离意说：“[[gap][17]]，让我来试就是了”手下人纷纷摆手阻止，可他不顾大家的反对，伸手[[gap][18]]J立荃君三豉〔丨喝了F去。
很快，传染病被控制住厂，钟离意紧皱的眉头也舒展了。
*** 题目
**** 15
***** 选择
****** A
提醒
****** B
表扬
****** C
责备
****** D
启发
***** 答案
C
**** 16
***** 选择
****** A
随
****** B
冒
****** C
顶
****** D
靠
***** 答案
B
**** 17
***** 选择
****** A
这可不得了
****** B
这可怎么办呢
****** C
这不很简单吗
****** D
这得好好考虑
***** 答案
C
**** 18
***** 选择
****** A
抢
****** B
递
****** C
举
****** D
捡
***** 答案
A
** 第二部分
*** 19
:PROPERTIES:
:ID: 53b61b3d-7cb9-4087-8526-f3e7de24a668
:END:
**** 段话
俗话说：病从口人，祸从口出。我们每天都需要摄人足量的食物，保证我们能够维持生命。但是，这些食物是否卫生，清洁工作是否做到位，这需要我们时刻跟进，时刻注意，把好人口第一关，否则，疾病就会找上门来了。
**** 选择
***** A
人每天要吃东西，所以难免会得病
***** B
要想不得病，就要注意食物的卫生
***** C
要想不得病，就要注意口腔的卫生
***** D
“不干不净，吃了没病”很有道理
**** 答案
B
*** 20
:PROPERTIES:
:ID: a48566da-10d1-46e4-877d-4223cd857f6d
:END:
**** 段话
肚子馈了便会咕噜咕噜地叫，这是因为之前吃进的食物消化完，胃里变空了，但胃中的胃液仍会继续分泌。这时候胃的收缩便会逐渐扩大，胃里的液体和气体便会翻揽起来，发出咕噜咕噜的声音。下次不要再为肚子咕咕叫而感到难为情了，因为这是人身体的正常反应。
**** 选择
***** A
肚子咕噜叫说明没吃饱
***** B
饭前喝水会造成肚子叫
***** C
消化食物时肚子都会叫
***** D
肚子叫常让人不好意思
**** 答案
D
*** 21
:PROPERTIES:
:ID: e992788d-e682-4a19-9dc3-5b029c94823e
:END:
**** 段话
综合全球已发表的实验报告，有31个长期临床研究证明，节食是没法让人长期保持苗条身材的。在五年内，三分之二的节食者眼睁睁看着甩掉的肥肉又回到身上，甚至还带了更多“亲戚”回来。而在青少年身上，这种体重反弹的后果更严重，年轻时就开始习惯性节食的人，五年后，他们普遍比没节食过的同龄人更重。
**** 选择
***** A
青少年节食对身体危害严重
***** B
有三分之二节食者获得成功
***** C
节食者大多要面对反弹的后果
***** D
节食可以使苗条体形保持五年
**** 答案
C
*** 22
:PROPERTIES:
:ID: 90a13b38-3ee2-4cb6-9eb3-8418a66df7b6
:END:
**** 段话
这项联合多所医学院校所做的研究发现，除了个别人以外，多数人体重的增加会从周六开始，而体重的减轻会从周二开始。它表明人们的体重变化在一周内会显示出一种明显的规律，工作日和周末体重的临时变化应该被视为正常现象。
**** 选择
***** A
多数人的体重周六达到最高
***** B
个别人的体重可以保持不变
***** C
体重变化的规律还无人展开研究
***** D
体重在一周内会发生临时的改变
**** 答案
D
** 第三部分
*** 23-25
**** 段话
人们伤心的时候会哭泣，高兴的时候也会流眼泪。但是不管你流不流眼泪，你的眼睛一直在产生着泪液。你知道吗？眼泪对眼睛有保护作用呢，它能够使你的眼睛不干涩。眼睛的某个特殊区域直不停地产生泪液，正是它使眼睛保持湿润。
如果你对着镜子仔细看，你就会在眼角处看到很小的孔，每个小孔都连接着一个细管，这些细管通向鼻子，正是这些细管不分屈夜地把泪液慢慢排出。如果它们不这样做的话，那么看上去，你就会一直是眼泪汪汪的。
当你开始哭的时候，就会产生更多的眼泪，而这些小孔不能及时地把眼泪排出去，于是多余的眼泪就会流到脸上。
眼泪有助于眼睛的安全。如果空气中存在有害物质的话，你的眼睛就会产生泪液，这些泪液会覆盖你的眼球，阻止有害物质进人眼睛。
戴隐形眼镜会让眼睛发干。有些人不得不往眼睛里滴人眼药水来保持眼睛湿润。
**** 题目
***** 23
****** 问题
根据本文，下列哪项正确？
****** 选择
******* A
眼睛一直在产生眼汨
******* B
高兴时眼泪不会流出来
******* C
眼泪有助于表达感情
******* D
戴隐形眼镜要滴眼药水
****** 答案
A
***** 24
****** 问题
文中谈到的“眼角处的小孔”有什么用处？
****** 选择
******* A
产生泪液
******* B
排出眼泪
******* C
保持眼睛湿润
******* D
阻止有害物质
****** 答案
B
***** 25
****** 问题
这篇短文最可能出自下列哪种杂志？
****** 选择
******* A
《大众健康》
******* B
《社会百科》
******* C
《动物世界》
******* D
《人与自然》
****** 答案
A
*** 26-28
**** 段话
感冒算得上是老百姓最熟悉的小病了。一旦症状出现，几乎不需要医生，多数人都能凭经验自己做出“感冒”的诊断。有人会翻箱倒柜地找中药、西药吃；还有人咬牙挺着，直到恢复健康或挺不住为止；更会有人迫不及待地去找医生开抗生素或干脆挂吊瓶…。。。那么感冒到底能不能挺？
当感觉嗓子干、咽东西不舒服，同时出现流清鼻涕、打喷嚏、鼻塞等症状时，这就是医学上所说的普通感冒，即由病毒引起的急性鼻炎或咽炎。普通感冒病程5一7天，一般不发烧，除了鼻子和咽部的不舒服外，其他症状都较轻。所以，注意多休息、多饮水，如有必要可吃一些缓解症状的非处方药，而不需要服用抗生素。
当呕部症状较重，疼痛和烧灼感剧烈，甚至吃饭喝水都变得困难时，要当心急性咽炎和急性扁桃体炎。对着镜子张开嘴，压下舌头根部，如果看到呕部发红，那么就应寻求医生的帮助，借助抗生素的治疗，而非继续咬牙硬挺。
因此，一旦症状出现，搞清是哪种感染最重要。如果不能肯定，则应求助于医生，勿将普通感冒的治疗原则简单地套在上呼吸道感染头上，避免耽误病情。
**** 题目
***** 26
****** 问题
根据上下文，文中画线的“挺不住”是什么意思？
****** 选择
******* A
累得爬不起来
******* B
身体感觉挺不错
******* C
牙疼到吃不了东西
******* D
病情严重受不了了
****** 答案
D
***** 27
****** 问题
关于普通感冒，从文中可以知道什么？
****** 选择
******* A
可以不用吃药
******* B
吃饭喝水困难
******* C
只是鼻子不舒服
******* D
都从打喷嚏开始
****** 答案
A
***** 28
****** 问题
本文主要谈的是感冒哪方面的事？
****** 选择
******* A
主要症状
******* B
发病原因
******* C
用药知识
******* D
治疗原则
****** 答案
D
* 书写
** 第一部分
*** 29
**** 词语
***** 1
有
***** 2
来报名
***** 3
总共
***** 4
这次
***** 5
两百多人
**** 答案
***** 1
这次总共有两百多人来报名。
*** 30
**** 词语
***** 1
采取
***** 2
治疗方法
***** 3
医生
***** 4
中医的
***** 5
决定
**** 答案
***** 1
医生决定采取中医的治疗方法。
*** 31
**** 词语
***** 1
小刘
***** 2
可靠
***** 3
不太
***** 4
办事
***** 5
经理觉得
**** 答案
***** 1
经理觉得小刘办事不太可靠。
