* 听力

** 第二部分
:PROPERTIES:
:ID: d3baa158-abdb-428a-ad14-8f91b80b0c93
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：您好！我们都知道您 25 岁考古系毕业就一头扎进了敦煌，在敦煌一待就是几十年，被誉为“敦煌女儿”。今天您就跟我们谈谈敦煌吧。
女：刚去的时候，虽说对大西北恶劣的自然环境早有心理准备，可是没想到反差那么大。那时候整个研究所只有一部电话，晚上只能用手电照明，上厕所要跑好远的路。和北京相比，简直就不是一个世界。可是每当我走过石窟的时候，都会赞叹：敦煌太好了，太美了！
男：敦煌莫高窟从发现到现在 100 多年了，把毕生精力都献给敦煌的人不少吧？
女：是的，它 1900 年一被发现便轰动了世界。1944 年中国第一批有志之士奔赴敦煌，在那儿设立了敦煌艺术研究所，至今已有三代学人在遍布黄沙的偏僻荒漠撰写了敦煌传奇。
男：我注意到您在那儿的研究不纯粹局限于考古，您的研究成果包括敦煌石窟考古美术方面的书籍、有关石窟考古与艺术的论文，还有大量探索古遗址科学保护及管理的论文。另外，“数字敦煌”也是在您的提倡下实现的，当时这在国内文物保护领域还是创举吧？
女：对。敦煌壁画是画在岩洞里的，自然侵蚀会使壁画慢慢消亡。莫高窟犹如人体，也会一天天变老，100 年前人们看到的莫高窟和现在看到的是不一样的。可是什么东西一旦数字化了就不变了，我们想利用计算机技术实现敦煌壁画、彩塑艺术永久保存的构想。
男：具体来讲，什么是“数字敦煌”？
女：这还要从游客说起。我们发现很多游客来之前没有做功课，不了解莫高窟。来了直接进入洞窟，看半天也看不出所以然。“数字敦煌”就是数字电影，把敦煌的历史、洞窟的相关内容以及分散在世界各地的相关资料、研究成果汇集到了一起。这样便于游客通过“数字敦煌”先了解敦煌，再进洞窟参观，效果会更好。实践证明“数字敦煌”很成功，它一问世就受到游客的欢迎。

**** 音频

ffaa7209-85b2-457e-be3b-5d75ed487207.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 8e47f99f-df92-4f0a-a491-4518729949f5
:END:

***** 问题

女的为什么被誉为“敦煌女儿”？

****** 音频

f2ec9372-dac5-4911-9570-377838750128.mp3

***** 选择

****** A

她对考古研究情有独钟

****** B

她多次去敦煌参观游览

****** C

她把毕生精力献给了敦煌

****** D

她自愿放弃了北京的生活

***** 答案

C

**** 7
:PROPERTIES:
:ID: a9e1c48a-6145-48af-955d-91e5862cc1cc
:END:

***** 问题

关于敦煌莫高窟，下列哪项正确？

****** 音频

d3700c56-318a-42f1-b392-5a2bf8efd4f4.mp3

***** 选择

****** A

莫高窟的历史长达百年

****** B

只有一批爱国人士去过敦煌

****** C

全世界都知道敦煌艺术研究所

****** D

三代学者为敦煌研究艰苦奉献

***** 答案

D

**** 8
:PROPERTIES:
:ID: a90a9c92-a371-410c-8112-d9cfa21b3ce0
:END:

***** 问题

女的做的哪件事在当时属于创新之举？

****** 音频

0ee48f1f-cccc-4d22-9554-00172d69067a.mp3

***** 选择

****** A

她写了敦煌石窟考古美术方面的书

****** B

她写了石窟考古与艺术方面的论文

****** C

关于古遗址科学保护及管理方面探索

****** D

利用计算机技术实现对文物的永久保存

***** 答案

D

**** 9
:PROPERTIES:
:ID: 5044b917-db1d-43a0-941f-6f92c90712bc
:END:

***** 问题

实现“数字敦煌”的好处是什么？

****** 音频

1980632c-aa5d-43d8-871c-4743805a0cc1.mp3

***** 选择

****** A

可实现敦煜艺术的永久保存

****** B

可代替人们去实地参观敦煌

****** C

可回看百年之前的敦煌莫高窟

****** D

可缓解自然对敦煌壁画的侵代

***** 答案

A

**** 10
:PROPERTIES:
:ID: 1c72bd0d-bd51-4f41-918b-154f66a0f114
:END:

***** 问题

游客为什么欢迎“数字敦煌”？

****** 音频

42f16bd8-4cf2-44d3-8803-e449e033af64.mp3

***** 选择

****** A

“数字敦煌”价格便宜

****** B

“数字敦煌”更为环保

****** C

游客直接看洞窟看不懂

****** D

游客喜欢电影这种形式

***** 答案

C

** 第一部分

*** 1

**** 选择

***** A

珍奇动物灭绝得更快

***** B

老鼠不喜欢单独行动

***** C

人类想尽办法消灭老鼠

***** D

人类保护动物效果很好

**** 段话

世界上有些珍奇动物，尽管人们千方百计去保护，仍然处于即将灭绝的境地。可是有些动物，比如老鼠，虽然人们在用各种方法消灭它们，但却总是消灭不了，成群的老鼠依然到处作祟。

***** 音频

65062dd7-f67d-41f2-a22c-4b8b1497852d.mp3

**** 答案

C

*** 2

**** 选择

***** A

原地跑步减肥成功概率高

***** B

手脚并用原地跑趣味性强

***** C

原地跑枯燥，但容易坚持

***** D

跑步需要互动，需要鼓励

**** 段话

手脚并用原地跑减肥方案的最大特点是在原地跑的基础上将上肢运动很好地融进来，通过每2～3分钟变速和花样变化跑，加之现场的互动气氛，增加了原地跑的趣味性，减少了原地跑的枯燥、乏味，使原地跑更易坚持。

***** 音频

31b548ef-d9c6-4882-bd0e-8b7fd67a67a2.mp3

**** 答案

B

*** 3

**** 选择

***** A

腌制食品的包装非常独特

***** B

高血压病人不能吃腋制食品

***** C

上班族经常在家制作腋制食品

***** D

腌制食品含盐多，常吃不利于健康

**** 段话

腌制食品口味独特，包装简单，便于携带，成为上班族的家常便饭。可是你知道吗，这些食品在腌制过程中需要大量放盐，这会导致此类食物盐含量超标，经常食用会加重肾脏的负担，增加发生高血压的风险。

***** 音频

a54e8f48-b4b0-47d2-a745-aa6411e1dc7c.mp3

**** 答案

D

*** 4

**** 选择

***** A

谈话要简单、抓住重点

***** B

会谈前应做好时间计划

***** C

每个人都应有自由时间

***** D

节省下时间能发现问题

**** 段话

与人会谈时，若言不及义、唠唠叨叨，再多的时间也浪费了，如能把握谈话要领，言谈简要切题，就可以节省很多时间。节省下时间，就可以解决更多的问题，并且为自己赢得更多的自由时间。

***** 音频

07aa6dfb-3c74-4615-abde-a2c24b4df7e0.mp3

**** 答案

A

*** 5

**** 选择

***** A

余老师热爱每一个学生

***** B

余老师的孩子没钱交学费

***** C

邻居家的闲事余老师都管

***** D

大伙把余老师看成最亲近的人

**** 段话

余老师是个热心人，她多次从自己微薄的收入中拿出钱来给家庭困难的学生交学费。前不久，又从自己多年的积蓄中拿出钱资助村里修路。邻居们谁家有事也总爱找她参谋，她是周围十里八乡大伙儿的贴心人。

***** 音频

b1f4e64b-9afa-45b0-9da6-16709dccf499.mp3

**** 答案

D

