* 听力

** 1

*** 1

**** transcript

世界上有些珍奇动物，尽管人们千方百计去保护，仍然处于即将灭绝的境地。可是有些动物，比如老鼠，虽然人们在用各种方法消灭它们，但却总是消灭不了，成群的老鼠依然到处作祟。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

手脚并用原地跑减肥方案的最大特点是在原地跑的基础上将上肢运动很好地融进来，通过每2～3分钟变速和花样变化跑，加之现场的互动气氛，增加了原地跑的趣味性，减少了原地跑的枯燥、乏味，使原地跑更易坚持。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

腌制食品口味独特，包装简单，便于携带，成为上班族的家常便饭。可是你知道吗，这些食品在腌制过程中需要大量放盐，这会导致此类食物盐含量超标，经常食用会加重肾脏的负担，增加发生高血压的风险。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

与人会谈时，若言不及义、唠唠叨叨，再多的时间也浪费了，如能把握谈话要领，言谈简要切题，就可以节省很多时间。节省下时间，就可以解决更多的问题，并且为自己赢得更多的自由时间。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

余老师是个热心人，她多次从自己微薄的收入中拿出钱来给家庭困难的学生交学费。前不久，又从自己多年的积蓄中拿出钱资助村里修路。邻居们谁家有事也总爱找她参谋，她是周围十里八乡大伙儿的贴心人。

***** notes
:PROPERTIES:
:CREATED: [2022-08-22 10:15:13 -05]
:END:

热心 / re4 xin1 / warmhearted, enthusiastic ;

***** translation
:PROPERTIES:
:CREATED: [2022-08-22 10:14:18 -05]
:END:

Ms. Yu is a warm-hearted person, and she takes out money from her own meager income to pay tuition for students whose families are in difficulty. Not long ago, she also took out money from her own savings for many years to finance road construction in the village. Neighbors always seek her advice on family matters, and she is a caring person for the people in the surrounding ten miles.

***** QUESTION Why doesn't the first sentence use "的人"?
:PROPERTIES:
:CREATED: [2022-08-22 10:14:35 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-22 Mon 10:14]
:END:

余老师是个热心人
余老师是个热心的人

**** alternatives

***** a



***** b



***** c



***** d



**** answer



 
