* 听力

** 1

*** 1

**** transcript

世界上有些珍奇动物，尽管人们千方百计去保护，仍然处于即将灭绝的境地。可是有些动物，比如老鼠，虽然人们在用各种方法消灭它们，但却总是消灭不了，成群的老鼠依然到处作祟。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

手脚并用原地跑减肥方案的最大特点是在原地跑的基础上将上肢运动很好地融进来，通过每2～3分钟变速和花样变化跑，加之现场的互动气氛，增加了原地跑的趣味性，减少了原地跑的枯燥、乏味，使原地跑更易坚持。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

腌制食品口味独特，包装简单，便于携带，成为上班族的家常便饭。可是你知道吗，这些食品在腌制过程中需要大量放盐，这会导致此类食物盐含量超标，经常食用会加重肾脏的负担，增加发生高血压的风险。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

与人会谈时，若言不及义、唠唠叨叨，再多的时间也浪费了，如能把握谈话要领，言谈简要切题，就可以节省很多时间。节省下时间，就可以解决更多的问题，并且为自己赢得更多的自由时间。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

余老师是个热心人，她多次从自己微薄的收入中拿出钱来给家庭困难的学生交学费。前不久，又从自己多年的积蓄中拿出钱资助村里修路。邻居们谁家有事也总爱找她参谋，她是周围十里八乡大伙儿的贴心人。

***** notes
:PROPERTIES:
:CREATED: [2022-08-22 10:15:13 -05]
:END:

热心 / re4 xin1 / warmhearted, enthusiastic ;

***** translation
:PROPERTIES:
:CREATED: [2022-08-22 10:14:18 -05]
:END:

Ms. Yu is a warm-hearted person, and she takes out money from her own meager income to pay tuition for students whose families are in difficulty. Not long ago, she also took out money from her own savings for many years to finance road construction in the village. Neighbors always seek her advice on family matters, and she is a caring person for the people in the surrounding ten miles.

***** QUESTION Why doesn't the first sentence use "的人"?
:PROPERTIES:
:CREATED: [2022-08-22 10:14:35 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-22 Mon 10:14]
:END:

余老师是个热心人
余老师是个热心的人

**** alternatives

***** a



***** b



***** c



***** d



**** answer



 
**  第二部分

*** 对话

男：您好！我们都知道您 25 岁考古系毕业就一头扎进了敦煌，在敦煌一待就是几十年，被誉为“敦煌女儿”。今天您就跟我们谈谈敦煌吧。
女：刚去的时候，虽说对大西北恶劣的自然环境早有心理准备，可是没想到反差那么大。那时候整个研究所只有一部电话，晚上只能用手电照明，上厕所要跑好远的路。和北京相比，简直就不是一个世界。可是每当我走过石窟的时候，都会赞叹：敦煌太好了，太美了！
男：敦煌莫高窟从发现到现在 100 多年了，把毕生精力都献给敦煌的人不少吧？
女：是的，它 1900 年一被发现便轰动了世界。1944 年中国第一批有志之士奔赴敦煌，在那儿设立了敦煌艺术研究所，至今已有三代学人在遍布黄沙的偏僻荒漠撰写了敦煌传奇。
男：我注意到您在那儿的研究不纯粹局限于考古，您的研究成果包括敦煌石窟考古美术方面的书籍、有关石窟考古与艺术的论文，还有大量探索古遗址科学保护及管理的论文。另外，“数字敦煌”也是在您的提倡下实现的，当时这在国内文物保护领域还是创举吧？
女：对。敦煌壁画是画在岩洞里的，自然侵蚀会使壁画慢慢消亡。莫高窟犹如人体，也会一天天变老，100 年前人们看到的莫高窟和现在看到的是不一样的。可是什么东西一旦数字化了就不变了，我们想利用计算机技术实现敦煌壁画、彩塑艺术永久保存的构想。
男：具体来讲，什么是“数字敦煌”？
女：这还要从游客说起。我们发现很多游客来之前没有做功课，不了解莫高窟。来了直接进入洞窟，看半天也看不出所以然。“数字敦煌”就是数字电影，把敦煌的历史、洞窟的相关内容以及分散在世界各地的相关资料、研究成果汇集到了一起。这样便于游客通过“数字敦煌”先了解敦煌，再进洞窟参观，效果会更好。实践证明“数字敦煌”很成功，它一问世就受到游客的欢迎。
