* 听力

** 第二部分
:PROPERTIES:
:ID: 27613dbe-0478-44e2-b649-666c82aaab0b
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：您是一位从事野外生态研究的科学家，今天现场的观众都渴望和您聊聊大熊猫。
女：大家都知道，大熊猫是国家一级保护动物，是中国的国宝。
男：世界上动物那么多，为什么大熊猫得到了这么特殊的待遇呢？就是因为它长得憨态可掬吗？
女：不是，主要是因为它稀少，已经濒临灭绝，换句话说，大熊猫这个物种正面临着从地球上消失的危险。
男：真是挺严峻的！大熊猫濒临灭绝和我们人类的活动有关吗？
女：关系很大。比如，人类不断扩大自己的生存空间，使大熊猫栖息地面积缩减；再比如，由于生态环境的破坏，使熊猫唯一的食物来源——竹林减少，这些都会直接威胁到熊猫的生存。
男：那大熊猫濒临灭绝有它自身的原因吗？
女：当然也有。
男：您不妨先说说，在大自然里，什么样的动物才能生存下去吧。
女：一般说来动物要生存下去，至少要具备以下七点中的某几点：一、有强健的肌肉，有锐利的爪子或锋利的牙齿；二、有快速奔跑的能力；三、有挖洞穴居的习性；四、有爬树的本事，或者能在树上生存，躲避敌害，储藏食物；五、有很强的繁殖能力；六、有很杂的食性；七、有很好的消化吸收能力。
男：大熊猫呢？
女：可以说，以上七点中，大熊猫哪一点都不具备。大熊猫的祖先是凶猛的食肉动物，可今天的大熊猫既没有利爪，也没有利牙，整天一副懒洋洋、温顺可人的样子；虽然它还保留着爬树的本领，可是那速度，也就是饭后遛食了；至于食谱，它只以新鲜的竹叶做主食，在它每天都吃掉的竹叶里，也只能消化掉一小部分，大多数营养都白白地浪费了；还有，它的繁殖能力也很差。这就是大熊猫濒临灭绝的内在因素。
男：是啊，这一切足以证实，大熊猫的保护工作确实是迫在眉睫。

**** 音频

069c27de-a5f7-4550-98aa-d248776d1f92.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 35bcc902-8188-41a8-b4de-808bf879a16a
:END:

***** 问题

大熊猫为什么成为国家一级保护动物？

****** 音频

96f07e52-c78e-4020-aa3d-34a019b700f6.mp3

***** 选择

****** A

因为它天真可爱

****** B

因为它身处险境

****** C

因为它是一种濒危动物

****** D

这是人们给它的特殊待遇

***** 答案

C

**** 7
:PROPERTIES:
:ID: a0453a3d-d774-460f-924d-84be1a36869a
:END:

***** 问题

人类怎样威胁到了大熊猫的生存？

****** 音频

0425675a-fc24-4058-83a7-8c8d090b85a8.mp3

***** 选择

****** A

人类不再给熊猎种植竹子

****** B

人类活动不利于竹林生长

****** C

人类改变了大熊猎的习性

****** D

人类活动导致了气候变化

***** 答案

B

**** 8
:PROPERTIES:
:ID: af919a01-5f93-47ea-a36f-fec69d14d53a
:END:

***** 问题

有利于动物生存的内在因素不包括什么？

****** 音频

e2fa6d7a-7c1b-49c2-abf0-412a1e3047a2.mp3

***** 选择

****** A

爱吃肉

****** B

速度快

****** C

穴居

****** D

杂食

***** 答案

A

**** 9
:PROPERTIES:
:ID: 6cfb89b3-fd6f-4715-88ac-4718391b2934
:END:

***** 问题

大熊猫濒临灭绝的内在因素有什么？

****** 音频

3d1a3be3-9fd0-47e1-b860-48fb65408db3.mp3

***** 选择

****** A

大熊猎太懒

****** B

大熊猎太可爱

****** C

大熊猎不会爬树

****** D

大熊猎消化能力差

***** 答案

D

**** 10
:PROPERTIES:
:ID: 0ca68c3a-e961-4632-a71a-f5aeba3f5c70
:END:

***** 问题

这段话主要谈的是什么？

****** 音频

32fafa7a-2599-41c7-9d16-bfda62d26df0.mp3

***** 选择

****** A

动物生存的条件

****** B

怎样保护大熊猫

****** C

大熊猎濒危的原因

****** D

人类为什么喜欢大熊猎

***** 答案

C

** 第一部分

*** 1

**** 选择

***** A

北京人不喜欢私立学校

***** B

北京人对交赞助费习以为常

***** C

京华私立学校成立于解放前

***** D

私立学校的所作所为让人吃惊

**** 段话

这不是一所普通小学，它是中华人民共和国成立后北京出现的第一所私立小学——京华私立学校。家长在给孩子办理报名手续的同时，还要交３万元的入学赞助费。这一切令当时的北京人目瞪口呆。

***** 音频

d25de085-4058-49b1-86c9-072f8418be54.mp3

**** 答案

D

*** 2

**** 选择

***** A

运动不当会产生错觉

***** B

过河时必须注意安全

***** C

过桥时注视哪里很重要

***** D

流动的河水突然静止了

**** 段话

过桥时，如果对脚下湍急的河水过多地注视，则会觉得桥逆水流而动，河水却不动，这就是运动错觉。产生这种运动错觉的原因是人们把流动的河水参照系当成了静止的参照系。

***** 音频

6e8e3a2b-f1e3-45db-b427-3cf6b304767b.mp3

**** 答案

C

*** 3

**** 选择

***** A

状态不积极就不可能有好机遇

***** B

好的经济地位是因为遇到积极的人

***** C

积极状态指好成绩、好地位这些指标

***** D

积极状态与心理素质、人生态度有关

**** 段话

一个处于积极状态的人可以拥有好成绩、高分数、好的经济地位和社会地位，但积极状态并不是指这些外在的指标，这些只是一个人奋斗和机遇的结果。积极状态指一个人具有的出色的综合心理素质、积极的人生态度。

***** 音频

82ef147d-f37a-4184-a317-19db087c2c17.mp3

**** 答案

D

*** 4

**** 选择

***** A

舍弃快节奏才是正确的做法

***** B

世界上近半数人患有焦虑疳

***** C

没有兴趣爱好的人生活很轻松

***** D

“大工业“是“快文化“的产物

**** 段话

大工业时代延续至今的“快文化”，使全世界 40%的人患上“时间疾病”。他们整日为工作忙碌，精神焦虑，忘记了自己的兴趣和爱好。因此丢掉快节奏，号召人们让自己的生活节奏慢下来，让生活更加人性化才是正道。

***** 音频

35af40bf-4c4e-49d2-a4d8-dc9436a0e510.mp3

**** 答案

A

*** 5

**** 选择

***** A

偷猎藏羚羊的事件在减少

***** B

偷猎藏羚羊的人枪法很准

***** C

偷猎藏羚羊的人都很紧张

***** D

藏羚羊遭受到很大的打击

**** 段话

过去，西藏可可西里偷捕藏羚羊的现象十分严重，偷猎分子洋枪快车，甚为嚣张。由于这些年加大了打击力度，捕杀藏羚羊的事件不断减少。这说明只要重视，野生动物一定可以得到更大限度的保护。

***** 音频

15891a3a-1b7e-4ccd-b43e-e7d4d61eb3ab.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

如果你的工作，让你心中充满的是苦涩，一想到上班就难受，一到班上就压抑，每天熬到快下班就心花怒放，你就不要再硬撑。但反过来说，如果你对这份工作还没有厌恶到每天觉得不痛快，那我建议你试久一点儿。因为成就感很多时候是在我们驾轻就熟、独当一面并能产生某种价值后才有的。所以如果某份工作自己没有很讨厌，那就让自己累积实力，提升熟练度。很可能当你哪天成为资深员工时，就会发现自己已经喜欢上这个工作，到你当上那个领域的大师，一群人对你投来佩服的眼光时，你会觉得这个工作非常棒。

若只是随便试那么一两个月，觉得不好不坏就溜走，那就永远不要指望你能够成为那一领域的大师。

*** 14-17

**** 课文

随着科学的进步，人类对自然的了解越来越深入，但是人类对自然的研究目的似乎只是为了让自然更好地为人类服务，因为人类滥用资源的行为对大自然造成了极大的破坏，这种状况一天也没有停止。

全球化使我们的世界不断变小，我们共同生活在地球村里。每个人都不能把自己的行为看成是个人行为，每个人的一举一动都与其他人、与我们的生存环境息息相关。因此，我们必须换一种方式对待自然，应该保护有限的自然资源，而非毫无节制地开发、剥夺自然资源。我们要学会和自然和谐相处，因为自然是我们的朋友。我们不能持续地为了人类的利益而去伤害它，但现实情况是，我们离共生这种状态已经非常遥远。

与自然相处，是一个道德问题，而不仅仅与知识相关。我们想要更好地立足于这个世界，必须跳出自我，处理好人与人、人与自然的关系，处理好不同文明、不同文化之间的关系。只有这样，地球人才能和谐相处，我们的生活才能更加美好。

