* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: d515f371-8bec-4163-a8ed-ba58ccb1f500
:END:
**** 对话
***** 转录
女：你拍的这些人物照片，构图、光线都很专业，真让人佩服！[[file:9c84bab5-1887-4ea3-8792-d0f09f2e79a0.mp3][(audio)]]
男：还差得远呢，摄影只不过是我的业余爱好。[[file:99b1fae2-b120-48aa-ab2c-57212e3b88fa.mp3][(audio)]]
***** 音频
952b9e2c-0dc7-4fdf-ad81-06f9de90e635.mp3
**** 问题
***** 转录
男的说话时，态度怎么样？
***** 音频
5f1402f0-5b45-4b32-9b4d-1d4aef5e9915.mp3
**** 选择
***** A
自信
***** B
骄傲
***** C
惭愧
***** D
廉虚
**** 答案
D
*** 2
:PROPERTIES:
:ID: b2d6a646-083f-4f1b-9f1f-5eeeed4dcbe2
:END:
**** 对话
***** 转录
男：小李会好多种乐器，弹钢琴、拉二胡，真是多才多艺啊！[[file:218f5d0e-b196-45f4-b757-baa33c4bf9a1.mp3][(audio)]]
女：她还是我们合唱团的领唱呢。[[file:79516a91-06b4-4a04-a271-ad2f0ffa5080.mp3][(audio)]]
***** 音频
40a14ddc-c0d7-45ee-ad21-c3baa3135bb4.mp3
**** 问题
***** 转录
关于小李，下列哪项正确？
***** 音频
d7809730-783e-4e46-84d1-a200d8f71757.mp3
**** 选择
***** A
爱好广泛
***** B
当过指挥
***** C
会修乐器
***** D
演过电影
**** 答案
A
*** 3
:PROPERTIES:
:ID: fb553a50-6980-4cf2-a518-2641bb883747
:END:
**** 对话
***** 转录
女：刘主任，这次的展览我们准备的作品很丰富。[[file:532b6c30-ca65-48b8-83de-d8e700e99359.mp3][(audio)]]
男：你们的设计方案我很满意。看得出是下了很大功夫的，辛苦啦！[[file:02aeec4e-7981-472a-b869-3807575f578b.mp3][(audio)]]
***** 音频
5206cb00-6c91-4a7e-bea9-3f74c12eb490.mp3
**** 问题
***** 转录
他们谈论的是什么事？
***** 音频
0fe7e943-7ad7-401a-9e4e-62f109267c5f.mp3
**** 选择
***** A
武术比赛
***** B
作品展览
***** C
市场调查
***** D
广告设计
**** 答案
B
*** 4
:PROPERTIES:
:ID: 6f4850c2-e59e-4618-8ae6-487fa5e7c8a1
:END:
**** 对话
***** 转录
男：你怎么还去电视台，你唱的那首歌昨天不是录完了吗？[[file:9df0ac95-b1e9-4b1f-8455-f6102151f9fe.mp3][(audio)]]
女：导演来电话，说昨天漏了一段，让我再去补录一下。[[file:852bd379-8aa9-4d91-ad5e-c7c71c05abc8.mp3][(audio)]]
***** 音频
cfee7b8f-c7f8-4cab-a603-5525d18d53fe.mp3
**** 问题
***** 转录
女的为什么要去电视台？
***** 音频
96cfb44a-3aca-4eb9-b022-f3b5afe2e1dc.mp3
**** 选择
***** A
主持节目
***** B
录制歌曲
***** C
拍电视剧
***** D
和导演见面
**** 答案
B
*** 5
:PROPERTIES:
:ID: cabe815a-0592-4577-9e40-a17e22d0fec0
:END:
**** 对话
***** 转录
女：听说这次来复试的考生，有一大半专业基础课考试都没通过。[[file:8755c400-075f-470b-aa16-b9d23d0171e2.mp3][(audio)]]
男：你别在这儿制造紧张气氛，我对咱们儿子很有信心。[[file:a84c929a-4dd2-42c9-9a20-b0b901c8e252.mp3][(audio)]]
***** 音频
0525d7a9-2883-42fb-8592-7820c7899722.mp3
**** 问题
***** 转录
说话的人是什么关系？
***** 音频
6e3faefa-8fee-451c-90a2-6dea40f9d454.mp3
**** 选择
***** A
夫妻
***** B
父女
***** C
师生
***** D
朋友
**** 答案
A
*** 6
:PROPERTIES:
:ID: 95f912c0-136c-4d89-b6ef-2e56dc86b3e8
:END:
**** 对话
***** 转录
男：这是什么画展啊？说实话，我一幅也看不懂。[[file:bc4f82d6-cc0d-48b9-bbdc-e0bb72d27f07.mp3][(audio)]]
女：你不懂就别乱说，这可都是抽象派大师的作品。[[file:cc4121a5-c113-43e7-aa5f-bbcc3d1a4c3f.mp3][(audio)]]
***** 音频
1abc829a-d509-4b34-8b78-bea818349b08.mp3
**** 问题
***** 转录
女的认为男的怎么样？
***** 音频
20dde8ea-24ae-4fc8-a935-48ce2f863cc3.mp3
**** 选择
***** A
不知道尊重画家
***** B
具有独特的眼光
***** C
不懂得欣赏艺术
***** D
不可能成为名家
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
男：妈，您要喝点儿什么？冰箱里有冷饮。
女：不着急，结婚证呢？快让我看看！
男：瞧把您急的，好像去登记结婚的是您不是我。
女：我这不是不放心吗？你快点儿！
***** 音频
9681992e-3166-42b6-b16e-d4f18463ee92.mp3
**** 问题
***** 转录
妈妈着急要做什么？
***** 音频
c4089256-2582-4e13-ac0d-4cf3006d45c8.mp3
**** 选择
***** A
暗冷饮
***** B
看结婚证
***** C
给儿子发短信
***** D
让儿子去登记
**** 答案
B
*** 8
**** 对话
***** 转录
男：现在很多影院都有网站，上网就可以订票，还可以挑选座位。
女：那我怎么付钱呢？
男：你可以通过网银付，也可以到影院取票时付。
女：这还真方便，我也来试试。
***** 音频
a70dd5af-5417-4619-a738-640de458c1d8.mp3
**** 问题
***** 转录
女的接下来想要做什么？
***** 音频
99335da0-00ee-4c5d-a2d3-bab7a9fa49de.mp3
**** 选择
***** A
去银行取钱
***** B
上网订电影票
***** C
在网上买东西
***** D
去影院看电影
**** 答案
B
*** 9
**** 对话
***** 转录
女：最近有个纪录片正在热播。
男：是什么方面的？好看吗？
女：片名叫《风味》，不但介绍美食，还介绍了各地的风俗文化以及相关厨师的个人成长经历，值得一看。
***** 音频
8d4b1fed-eb73-41d7-aced-f26cf93c1c70.mp3
**** 问题
***** 转录
这是一部关于什么内容的纪录片？
***** 音频
657210b4-f1b3-405d-a2ef-c08110bc6804.mp3
**** 选择
***** A
风景名胜
***** B
科学常识
***** C
各地美食
***** D
历史人物
**** 答案
C
*** 10
**** 对话
***** 转录
男：影视频道今晚播出一个新的连续剧，是李京主演的。
女：这个李京是挺会演戏的，上次演的那个医生也很好。
男：他可是现在最红的男演员，片约不断。
女：这次他演个什么角色？
男：好像是个工厂的车间主任。
***** 音频
0971bade-78f5-4158-96d7-0ed876d431b1.mp3
**** 问题
***** 转录
关于李京，可以知道什么？
***** 音频
4a9e9d29-847b-48ac-8f9c-ccd67f00a3be.mp3
**** 选择
***** A
深受观众喜爱
***** B
曾是眼科大夫
***** C
最近很少拍戏
***** D
想当电影导演
**** 答案
A
*** 11-12
**** 对话
***** 转录
男：你刚吹的乐器是叫笛子吗？
女：对，这是中国传统的民族乐器，是用竹子制作的。
男：你吹的曲子真好听，叫什么名字？
女：《小放牛》，这是一首经典的笛子独奏曲。
男：我学过钢琴，不知道笛子难不难学？
女：你有音乐基础，手指也灵活，学起来会很快，我教你。
***** 音频
689eb2c4-f7fb-48c7-8583-51ee2cf8871c.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于笛子，可以知道什么？
******* 音频
c5b26041-2f3a-4f1f-a5ad-47a8ceddfd7b.mp3
****** 选择
******* A
由竹子制作
******* B
非常难掌握
******* C
用手指弹奏
******* D
不适合独奏
****** 答案
A
***** 12
****** 问题
******* 转录
女的为什么认为男的会学得很快？
******* 音频
e5a37a12-74a3-416d-953f-63cf5127a899.mp3
****** 选择
******* A
自己教得好
******* B
钢琴弹得好
******* C
音乐基础好
******* D
学过民族乐器
****** 答案
C
*** 13-14
**** 段话
***** 转录
一位学画画儿的年轻人带着自己花了整整一年时间才画成的一幅瀑布画儿去求见书画大师，想请他指导。大师看了那幅画儿后，摇摇头说：“还好，只是没能画出瀑布的声音！”一年后，年轻人又来求见大师，将一幅自以为更好的瀑布画儿交给大师。大师看了，还是摇摇头说：“很遗憾，问题还是一样。”又过了一年，这位年轻人很有信心地再次求见大师，将一幅自以为完美无缺的瀑布画儿捧给大师。大师看后，又一次摇摇头说：“年轻人，你还是没能画出瀑布的声音！”年轻人糊涂了，他诚恳地问：“大师，晚辈确实不能明白其中的道理，请您指教！”大师提起画笔，在年轻人的画儿上画了起来，他在瀑布下的水潭边画了两个相对而立的人，其中一个人双手拢音大声喊，另一个人伸着耳朵仔细听。就这样，年轻人明白了怎样才能画出瀑布的声音，也终于理解了书画的真谛。
***** 音频
5103c4ae-f886-445a-80ad-ad99e391ce3e.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于年轻人第一次带去的画儿，可以知道什么？
******* 音频
a141e4cf-77dd-46ba-966a-273c91e1198c.mp3
****** 选择
******* A
整整画了一年
******* B
自以为很完美
******* C
是幅人物画儿
******* D
大师极不满意
****** 答案
A
***** 14
****** 问题
******* 转录
关于这位年轻人，下列哪项正确？
******* 音频
c4ae512a-ff35-412b-ade2-4259cbf55f07.mp3
****** 选择
******* A
学画时间不长
******* B
水平进步明显
******* C
脑子容易糊涂
******* D
求学态度诚恳
****** 答案
D
* 阅读
** 第一部分
*** 段话
侯宝林对相声艺术的[[gap][15]]是多方面的。他不仅带头浑化相声的语言，还提高了相声的审美趣显。他改编了许多传统节目，坚持以诙谐幽默的文明相声求生存、求发展。新中国成立后，他积极推动“相声[[gap][16]]运动”，在相声中注人了更加健康的内容，侗之面貌焕然一新。
有人说：“当初没有相声就没有侯宝林；后来没有侯宝林就没有如今的相声。”这话很有[[gap][17]]，侯宝林一直在说相声，一生都在钻研相声，直到有一天在大多数人的心中，他就是相声。
我国著名物理学家钱学森特别喜欢听侯宝林的相声。钱老说，侯宝林的相声内容健康，格调高雅，极富教育意义，又十分幽默，[[gap][18]]。那真是一种语言艺术，是俞宝林智惹的闪光，很了不起，并称侯宝林是“伟大的人民艺术家”。
*** 题目
**** 15
***** 选择
****** A
发展
****** B
成就
****** C
作用
****** D
影响
***** 答案
D
**** 16
***** 选择
****** A
改善
****** B
改进
****** C
调整
****** D
修改
***** 答案
B
**** 17
***** 选择
****** A
道理
****** B
原则
****** C
启发
****** D
意义
***** 答案
A
**** 18
***** 选择
****** A
怪不得让我感到费解
****** B
常常出奇地令人捧腹大笑
****** C
不得不使我们深感惭愧
****** D
连他本人帮忍不住会笑
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 0bd50cf5-3ade-45ea-a02b-443c32fe8257
:END:
**** 段话
有三分之一的画作作者没有签名，而其余的则标明了身份。令人头疼的是，一些签名被故意弄错了，志愿者无法确认作者到底是谁，所以有可能志愿者认为自己看到的是黑猩猩的随手涂鸦，实际则是著名抽象艺术家的大作。
**** 选择
***** A
许多画家不愿在作品上签名
***** B
画作都出自著名艺术家之手
***** C
黑猩猩的随手涂鸦也很出色
***** D
故意弄错的签名令志愿者头疼
**** 答案
D
*** 20
:PROPERTIES:
:ID: dfe11339-1ec8-43ba-a34e-83ac62810342
:END:
**** 段话
徐悲鸿早年曾到日本、法国留学，学习油画、素描，他把中外绘画技法很好地结合在一起，创造了新颖而独特的风格。回国后他长期从事美术教育工作，对中国美术队伍的建设和中国美术事业的发展做出了突出贡献，影响深远。
**** 选择
***** A
徐悲鸿画的中国画好于油画
***** B
徐悲鸿回国后学习了中国画
***** C
徐悲鸿是优秀的美术教育家
***** D
徐悲鸿早年主要从事素描创作
**** 答案
C
*** 21
:PROPERTIES:
:ID: 513d9eaf-01e8-49ef-b224-d8e491286012
:END:
**** 段话
梅兰芳是中国京剧史承上启下的代表性人物。他对京剧进行了艺术创新，通过吸收上海文明戏的改良成分，综合青衣、花旦、刀马旦的表演方式，塑造出了形态各异的不同历史时期的中国女性艺术形象，形成了独具特色的艺术流派——梅派，位居京剧四大名旦之首。
**** 选择
***** A
梅兰芳创作了一部中国京剧史
***** B
梅兰芳创造了青衣等表演方式
***** C
梅兰芳原从事上海文明戏的表演
***** D
梅兰芳塑造了许多女性艺术形象
**** 答案
D
*** 22
:PROPERTIES:
:ID: 987469af-a7a0-4fac-b9b7-48ecbc85d72f
:END:
**** 段话
壁画就是在天然石壁或人工墙面上制作的图画，它是人类历史上最早的绘画形式之一，起到了装饰和美化的作用。中国古代的壁画主要分布在神庙、宫殿、寺院、庭苑、石窟、陵墓等建筑物中。
**** 选择
***** A
壁画主要是在天然石壁上的创作
***** B
壁画对建筑起到装饰美化的作用
***** C
中国古代的壁画主要集中在寺庙
***** D
人类历史上最早的壁画画在地上
**** 答案
B
** 第三部分
*** 23-25
**** 段话
齐白石是中国著名的书画大师。一天，诗人艾青前来看望已经88岁高龄的齐白石，还带来一幅画儿，请他鉴别真伪。齐白石拿出放大镜，仔细看了看，对艾青说：“我用刚创作的两幅画儿跟你换这幅，行吗？”
艾青听后，赶紧收起画儿，笑着说：“您就是拿20幅，我也不跟您换。”齐白石见他不答应，忍不住叹了一口气说：“我年轻时画画儿多认真听，现在退步了。”原来，艾青带来的这幅画儿正是齐白石几十年前的作品。
艾青走后，齐白石一直愁眉不展。一天夜里，他儿子起来上厕所，看到书房的灯还亮着，走进一看，发现齐白石正坐在书桌前，一笔一画地描红。儿子不解地问道：“您都这么大年纪了，早就盛名于世，怎么突然想起描红了，而且描的还是这么初级的东西？”
齐白石摇丁摇头，不紧不慢地答道：“现在我的名气大，很多人都说我画得好，觉得我随便画一笔都是好的，我也被这些赞美弄得有些飘飘然了，无形中就放松了对自己的要求。直到前几天，我看见自已年轻时画的一幅画儿，才忽然惊醒，我不能再被外界的那些夸奖之词冲昏了头了，以后还得认真练习，自己管住自己啊。”
从此以后，尽管年龄越来越大，齐白石还是坚持每天练习，从不敢偷懒。有时为了一幅画儿，他甚至会花上几个月的时间。
不满足于过往的成就，不放松对自己的要求，这正是齐白石这位书画大师令人佩服的地方。
**** 题目
***** 23
****** 问题
齐白石想跟诗人艾青换的画儿：
****** 选择
******* A
是一幅古画儿
******* B
是一幅假画儿
******* C
是自己的画儿
******* D
值20幅画儿
****** 答案
C
***** 24
****** 问题
艾青走后，齐白石为什么愁眉不展？
****** 选择
******* A
没换成画儿
******* B
受到了批评
******* C
发现自己老了
******* D
觉得自己退步了
****** 答案
D
***** 25
****** 问题
本文认为，齐白石令人佩服的地方是：
****** 选择
******* A
不去和别人比较
******* B
始终严格要求自己
******* C
活到老学到老的精神
******* D
冷静地对待别人的赞美
****** 答案
B
*** 26-28
**** 段话
灯彩，又叫“花灯”，是起源于中国的一种汉族传统民间手工艺品，它与正月十五元宵赏灯的习俗关系密切。中国各地的灯彩种类众多，做工优美，各有特点，有代表性的如：鱼灯，鱼是中国民间美术最常见的造型主题之一，象征“年年有余”。陕西的鱼形灯彩，制作手法简括、构思精巧，用竹篾做骨、外糊彩纸，造型生动活泼。白菜灯，发音近似“百财”，民间取其吉祥的寓意。模仿白菜之形，朴素中流露着百姓热爱乡土的乐观精神。莲花灯，莲花具有圣洁清香之美，被誉为“花中君子”。民间又以莲藕并生、花开并蒂表示佳偶天成，用以祝贺新婚，又有“连年有余”等吉祥祝福之意。龙凤灯，属浙江仙居的针刺无骨花灯。传统观念中，龙和凤都是吉祥的动物，表达幸福美满的愿望，并相传点亮龙凤灯，能驱妖避邪除百病。花蝶灯，是广东佛山民间灯彩，以富丽的牡丹花和七彩斑斓的蝌蝶为主体结构，配置金色如意飘饰，寓意春天来临、百花齐放、彩蝶纷飞，表达人们对未来美好生活的期盼。
**** 题目
***** 26
****** 问题
根据本文，下面哪种说法是正确的？
****** 选择
******* A
鱼灯是陕西特有的民间灯彩
******* B
白菜灯具有朴素的乡土气息
******* C
结婚喜庆时一般挂龙凤灯
******* D
花蝶灯主体造型为莹花和蝴蝶
****** 答案
B
***** 27
****** 问题
民间传说哪种灯可以消除各种疾病？
****** 选择
******* A
鱼灯
******* B
白菜灯
******* C
龙凤灯
******* D
花蝶灯
****** 答案
C
***** 28
****** 问题
可以做这篇文章标题的是：
****** 选择
******* A
灯彩的起源
******* B
各地民间灯彩
******* C
灯彩的制作手法
******* D
正月十五看花灯
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
印象
***** 2
给我
***** 3
上海
***** 4
留下了
***** 5
极其深刻的
**** 答案
***** 1
上海给我留下了极其深刻的印象。
*** 30
**** 词语
***** 1
他也
***** 2
再等了
***** 3
一分钟
***** 4
哪怕是
***** 5
不愿意
**** 答案
***** 1
哪怕是一分钟他也不愿意再等了。
*** 31
**** 词语
***** 1
便
***** 2
成语
***** 3
出自
***** 4
“画龙点睛”
***** 5
关于他的传说
**** 答案
***** 1
成语“画龙点睛”便出自关于他的传说。
