* 热身

** 1
:PROPERTIES:
:ID: b59ea8c8-9c84-480d-81c3-701aa8300bff
:END:

*** 1

**** 词语

盐

**** 答案

a

*** 2

**** 词语

友好

**** 答案

c

*** 3

**** 词语

相反

**** 答案

d

*** 4

**** 词语

叶子

**** 答案

b

*** 5

**** 词语

教育

**** 答案

f

*** 6

**** 词语

商量

**** 答案

e

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: 1541c855-01a1-4c31-bed3-87df9e3dd8ec
:END:

**** 选择

***** 1

引起

***** 2

也许

***** 3

仔细

***** 4

作用

***** 5

可惜

**** 题

***** 1

****** 段话填空

她表示要放弃这个去国外留学的机会，同学们都觉得很🟦。

****** 答案

可惜

***** 2

****** 段话填空

如果你觉得心烦，可以吃点儿蛋糕或者巧克力，这些甜的东西🟦会给你带来好好心情。

****** 答案

也许

***** 3

****** 段话填空

现在网上银行的🟦，越来越大。有了它，网上购物就方便多了，还可以在网上交水费、电费等。

****** 答案

作用

***** 4

****** 段话填空

你现在做出的每一个决定都有可能影响到你的将来。所以，做决定之前前最好🟦考虑一下。

****** 答案

仔细

***** 5

****** 段话填空

事情的原因和结果往往是互相联系的。一定的原因会🟦一定的结果，有时候一件事情的结果可能又是另外一件事情的原因。

****** 答案

引起

*** 6-10
:PROPERTIES:
:ID: ed8c3ee2-0e3c-49c0-9e74-2da713163176
:END:

**** 选择

***** 1

详细

***** 2

解释

***** 3

商量

***** 4

力气

***** 5

直接

**** 题

***** 6

****** 对话填空

Ａ：咱们在这儿休息一会儿吧，我没🟦爬了。
Ｂ：一看就知道你不经常锻炼。

****** 答案

力气

***** 7

****** 对话填空

Ａ：刚才手机没电了，听说你打电话找我了，有什么事吗？
Ｂ：大家在教室🟦晚会节目的事情呢，就差你了。

****** 答案

商量

***** 8

****** 对话填空

Ａ：经理，新的计划发您信箱了，您看了吗？
Ｂ：内容太简单，不够🟦，明天我们得再开会商量商量。

****** 答案

详细

***** 9

****** 对话填空

Ａ：你有没有李律师的电话号码？我想问他几个法律方面的问题。
Ｂ：有，我发到你手机上，你🟦跟他联系就行。

****** 答案

直接

***** 10

****** 对话填空

Ａ：怎么样？事情解决了吧？
Ｂ：对，我向那位顾客🟦了这次不能及时送贷的原因，她表示可以理解。

****** 答案

解释

* 注释

** 3

*** 比一比

**** 做一做

***** 词语

****** 1

对于

****** 2

关于

***** 题

****** 1
:PROPERTIES:
:ID: 762e5d48-4d89-4652-bd5b-ec9e1e33b3ff
:END:

******* 课文

🟦这个问题，你应该再认真地考虑一下。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: 1d42f593-ebfe-47f7-9e4a-6d263144521b
:END:

******* 课文

🟦这方面的情况，大家最好上网去查一查。

******* 答案

******** 1

0

******** 2

1

****** 3
:PROPERTIES:
:ID: 9c632f2d-7373-40dd-97b2-09ff9fd011ae
:END:

******* 课文

🟦怎样提高中文阅读能经力，这一学习方法实践证明是有效的。

******* 答案

******** 1

0

******** 2

1

****** 4
:PROPERTIES:
:ID: 09e756da-2933-4910-9e95-4b3e8fdf577f
:END:

******* 课文

现在人们🟦自然环境越来越注意保护了。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: 3562b2be-2bea-4529-b15f-48143c64ddf4
:END:

******* 课文

昨天在报纸上看到一篇🟦这位明星的新闻，才知道她竟然还只是一位在校大学生。

******** ANSWERED 
:PROPERTIES:
:CREATED: [2022-12-26 12:00:15 -05]
:END:
:LOGBOOK:
- State "ANSWERED"   from "UNANSWERED" [2022-12-26 Mon 18:49]
- State "UNANSWERED" from              [2022-12-26 Mon 12:00]
:END:

********* Question
:PROPERTIES:
:CREATED: [2022-12-26 12:00:18 -05]
:END:

在这个句子里，“校”什么意思？

昨天在报纸上看到一篇关于这位明星的新闻，才知道她竟然还只是一位在➡️校⬅️大学生。

********* Answer
:PROPERTIES:
:CREATED: [2022-12-26 18:47:21 -05]
:END:

They are still learning in the university.

Those students that are doing internships can't be used with 校.

******** 笔记
:PROPERTIES:
:CREATED: [2022-12-26 11:53:16 -05]
:END:

明星 🟦 ming2​xing1​ 🟦 n. star, celebrity ;
竟然 🟦 jing4ran2 🟦 unexpectedly ;

******* 答案

******** 1

0

******** 2

1

* 扩展

** 做一做
:PROPERTIES:
:ID: 342f9b9d-4f4f-49b5-8761-d90df65ee61e
:END:

*** 选择

**** 1

信用卡

**** 2

作用

**** 3

使用

*** 题

**** 1

***** 内容填空

很多葡萄酒的瓶子都是深色的，这是因为太阳光会让酒的味道发生改变，而深色酒瓶能起到保护🟦。

***** 答案

****** 1

作用

**** 2

***** 内容填空

Ａ：我的钱包怎么不见了？钱和🟦都在里面呢。
Ｂ：你先别着急，仔细回忆一下，你最后在哪儿用过它。

***** 答案

****** 1

信用卡

**** 3

***** 内容填空

新闻往往🟦数字来说明问题，所以这些数字必须是准确的，只有这样，才能证明新闻的“真”，才是对读者负责。

***** 答案

****** 1

使用

* 课文
** 1
*** 转录
王经理：听说这次生意你到现在还没谈成。
马经理：按我以前的经验，早应该谈成了，这次我也不知道哪儿出了问题。
王经理：有句话叫“规定和经验是死的，人是活的”。当“规定”和“经验”不能解决问题时，建议你改变一下自己的态度和想法。
马经理：很多时候，我都习惯根据过去的经验做事，可惜，经验不是全部都是对的。
王经理：遇到不能解决的问题时，我们应该试着走走以前从来没走过的路，也许这样就能找到解决问题的方法了。
马经理：好，我再跟同事商量商量，希望能及时发现问题，并且准确地找到解决问题的方法。
** 2
*** 转录
女儿：妈，您看我刚买的裤子，洗完以后颜色怎么变得这么难看呢？
高老师：看来是掉颜色了，你洗的时候在水里加点儿盐就不会这样了。
女儿：放盐？！盐不是用来做饭的吗？难道它还能让衣服不掉颜色？
高老师：当然。有些衣服第一次洗的时候会掉颜色，其实，有很多方法可以解决这个问题。在水里加勺盐再洗是最简单的方法。用盐水来洗新衣服，这样穿得再久、洗的次数再多，衣服也不容易掉颜色。
女儿：我第一次听说盐有保护衣服颜色的作用，生活中还真有不少课本上无法学到的知识。
高老师：实际上，很多问题的答案都可以从生活中找到。但这需要你用眼睛去发现，用心去总结。
** 3
*** 转录
高老师：王教授，今天听完您的这节课，我终于明白为什么您的课那么受学生欢远了。
王教授：谢谢！您能详细谈谈对我的课的看法吗？
高老师：我发现您对学生特别了解，而且总是能用最筒单的方法把复杂的问题解释清楚，让每个学生都能听懂，这一点真是值得我们好好儿学习。
王教授：哪里哪里，这只是因为我对每个学生的能力水平比较了解。
高老师：那您认为对于老师来说，什么是最难做到的？
王教授：世界上没有完全相同的叶子，同样地，世界上也没有完全一样的人。所以，在教育学生时，要根据学生的特点选择不同的方法，我想这应该是最不容易做到的。
** 4
*** 转录
人人都会使用语言，但是怎么用语言把话说好却是一门艺术。看一个人怎么说话，往往可以比较准确地判断出他是一个什么样的人。有的人心里怎么想，嘴上就怎么说，即使是别人的缺点，他也会直接说出来，这样的人虽然很诚实，但是可能会引起别人的误会；有的人虽然也看到了别人的缺点，但却不会直接指出来，而是通过别的方法来提醒，让他认识到自已的缺点，这样的人会让人觉得更友好。
** 5
*** 转录
无论做什么事情，都要注意方法，学习尤其是这样。使用正确的方法，我们做起事来能“事半功倍”，也就是说，能节约时间，用较少的力气，职得更好的效果。相反，如果方法不对，可能花五倍甚至十借的时间都不能完成任务，结果变成了“事倍功半”。有一点需要提醒大家，别人的方法也许很有效，但是并不一定造合自已。因此，我们应该在听取别人意见的同时，仔细考虑一下，再根据不同的情况选择不同的方法，这样才能达到最好的效果。
