* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: c2309164-662d-4172-9312-5948b70d6e42
:END:
**** 对话
***** 转录
女：刘先生说周三来换饮水机，问你想要哪个牌子的？[[file:be26acdf-3ac1-497b-a6be-c9e44a97317c.mp3][(audio)]]
男：没关系，好用就成。[[file:b575f429-47e1-4d39-8daf-5ccfa355a6d7.mp3][(audio)]]
***** 音频
76f4b375-1ae5-44ee-b478-364cd8721b84.mp3
**** 问题
***** 转录
男的对这件事的态度怎么样？
***** 音频
cd8863bb-4272-40f3-a1e8-cc9f273bc333.mp3
**** 选择
***** A
很关心
***** B
无所谓
***** C
坚决反对
***** D
有点儿犹豫
**** 答案
B
*** 2
:PROPERTIES:
:ID: e5d13526-dd8b-4734-8fb8-466d3b8ae952
:END:
**** 对话
***** 转录
男：中午碰见林教授了，他说找你有事。[[file:c7adc852-8ce1-4f50-b0d8-aee8cf6cea2c.mp3][(audio)]]
女：本来说好了，上午给他送实验报告，结果他临时外出，就没送成。[[file:a3fc53e9-9c70-4cc3-af8c-4db40438069e.mp3][(audio)]]
***** 音频
b441fc81-23b7-4c83-88b8-8e1e3820ccaf.mp3
**** 问题
***** 转录
女的为什么没送成报告？
***** 音频
f7a026b1-277b-4745-8217-16ef1d3c6ae2.mp3
**** 选择
***** A
林教授不在
***** B
她临时有事
***** C
报告还没写完
***** D
说好了改天送
**** 答案
A
*** 3
:PROPERTIES:
:ID: 61db1be4-9783-46d7-93a1-36fa3463522c
:END:
**** 对话
***** 转录
男：小李，宣传册是在哪儿印的？有些地方印得比较模糊。[[file:101ed6f6-5660-421b-a538-f69ee35688cd.mp3][(audio)]]
女：那我马上跟对方联系一下，让他们重新印。[[file:212847cb-8d99-4a74-a05a-78448a45a876.mp3][(audio)]]
***** 音频
14751037-3070-4fb3-9908-4b7b6beead92.mp3
**** 问题
***** 转录
女的打算让对方怎么做？
***** 音频
c314241f-f1e1-4f83-b07c-4d420b1e88ff.mp3
**** 选择
***** A
修打印机
***** B
退还押金
***** C
重新印刷
***** D
开张发票
**** 答案
C
*** 4
:PROPERTIES:
:ID: 7e9539f3-58ea-41b9-a2a3-d523c43764ae
:END:
**** 对话
***** 转录
女：别犹豫了，既然房东同意续租，你又没别的合适的，就再住半年吧。[[file:5beb29ae-9515-48e1-8c45-ce7ededbe042.mp3][(audio)]]
男：也是啊，房租涨得还能接受，也省得再搬了。[[file:d82a69c0-b210-4b3f-9fb9-ae6bdd4cafbe.mp3][(audio)]]
***** 音频
b1df84c4-9bf3-4c24-907c-bcfbb978ccab.mp3
**** 问题
***** 转录
在租房问题上，男的是怎么想的？
***** 音频
a28365ef-f07d-4e2b-810c-fd78fe3e47b3.mp3
**** 选择
***** A
觉得房租贵
***** B
不想再搬家
***** C
房东人挺好
***** D
另找合适的
**** 答案
B
*** 5
:PROPERTIES:
:ID: 8a793f15-af06-4031-94b0-b79c60dea228
:END:
**** 对话
***** 转录
男：昨晚你电话一直占线，你在给谁打电话呢？[[file:5cff54e6-6a9c-4f82-9c98-f0e341e880c8.mp3][(audio)]]
女：我朋友小梅，两口子吵着要离，我在电话里一直在劝她要冷静。[[file:a168407f-09c9-4735-a903-ff437b819d50.mp3][(audio)]]
***** 音频
fd1850f6-5320-4273-b3a8-699d63a69856.mp3
**** 问题
***** 转录
小梅怎么了？
***** 音频
5ddd9501-9a20-4c70-8dba-14a4d7e0327f.mp3
**** 选择
***** A
想辞职
***** B
失恋了
***** C
爱伤了
***** D
要离婚
**** 答案
D
*** 6
:PROPERTIES:
:ID: aab393b4-dc63-4b38-aa6e-a2f50537216e
:END:
**** 对话
***** 转录
男：你做的方案会上通过了吗？[[file:4eea4265-b827-4092-b5b1-9e9be3e65d09.mp3][(audio)]]
女：我把计划跟他们一说，结果，没一个人赞成。[[file:b283e3cb-aa9e-4701-bb42-adc6e5e89499.mp3][(audio)]]
***** 音频
0cf978c2-3103-4024-9275-68883496e0b2.mp3
**** 问题
***** 转录
大家认为这个计划怎么样？
***** 音频
476dada6-091d-40c7-ae9f-e3fb9b723b9b.mp3
**** 选择
***** A
行不通
***** B
令人满意
***** C
的待完善
***** D
非常完美
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
男：是小丽来的电话？怎么打这么久？
女：是你妹妹，又失恋了。你这当哥哥的也不管。
男：这事我怎么管？你是她嫂子，替我多安慰安慰她。
女：就知道你会这么说。
***** 音频
ac47d8d1-2cbf-4e12-9c3f-a903d4f530f7.mp3
**** 问题
***** 转录
说话的两个人是什么关系？
***** 音频
b6a5aa82-5047-4826-bb24-aaf702bc6469.mp3
**** 选择
***** A
兄妹
***** B
夫妻
***** C
朋友
***** D
姐弟
**** 答案
B
*** 8
**** 对话
***** 转录
女：上次拜访的那家公司有结果了吗？
男：联系好几次了，每次约他们刘经理，对我都特冷淡。
女：开始时都这样，光看资料了解还是不够的。
男：是的，我争取能再去给他演示一下。
***** 音频
93c82918-10f1-41d9-a70f-5f717f396b2f.mp3
**** 问题
***** 转录
男的接下来想要做什么？
***** 音频
5e40c380-a92a-48b2-8d73-61a2f97706f4.mp3
**** 选择
***** A
耐心等结果
***** B
另找新客户
***** C
请经理吃饭
***** D
去演示产品
**** 答案
D
*** 9
**** 对话
***** 转录
女：谢谢你送我回家，你对这里不太熟吧？
男：你是奇怪这么近的路我怎么开了这么久吗？
女：是啊，你好像不太认识路似的。
男：如果我对这儿不熟悉，我怎么能开一个多小时的车，而一次也没经过你家的门口呢？
***** 音频
74b8f571-de48-431c-877c-dd4b3a96dcaa.mp3
**** 问题
***** 转录
从对话中可以知道什么？
***** 音频
a883a3e1-ed9d-415f-bdc3-bdadde11e1cc.mp3
**** 选择
***** A
女的想坐车兜风
***** B
男的故意多绕路
***** C
女的想赶快回家
***** D
男的对这里不熟
**** 答案
B
*** 10
**** 对话
***** 转录
男：你也认识刘京？
女：是啊，我们是高中同学，他学文科，我在理科班。
男：他武术特别棒。
女：没错，上学的时候，他就是武术队的，还得过太极拳比赛的冠军呢。
***** 音频
38dab8c5-f7ba-4a68-a443-c3a2990f5d8d.mp3
**** 问题
***** 转录
关于刘京，可以知道什么？
***** 音频
95b5c7bd-4ee2-4577-9492-a82d50b6b163.mp3
**** 选择
***** A
是个体育老师
***** B
教过女的武术
***** C
比赛得过冠军
***** D
和男的是同学
**** 答案
C
*** 11-12
**** 对话
***** 转录
女：先生，您的车票呢？
男：车票？我没有。
女：没有？那您要去哪儿？
男：我哪儿也不去。
女：那您为什么上这列火车？
男：我在车站遇到这列火车，听到车上的广播大声叫喊：“请大家赶快上车坐好！于是我不得不走进车厢。”
***** 音频
58744508-67fb-4bc6-b937-961eb2412831.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于那位先生，可以知道什么？
******* 音频
7ca3c824-7d2b-40f1-8ba0-6f26bfcfd7bc.mp3
****** 选择
******* A
坂过了站
******* B
丢了车票
******* C
上错了列车
******* D
有点儿糊涂
****** 答案
D
***** 12
****** 问题
******* 转录
说话时他们最可能在哪儿？
******* 音频
1a8bc341-a204-447b-854b-2c343e259b13.mp3
****** 选择
******* A
车厢里面
******* B
列车站司
******* C
候车大厅
******* D
售票窗口
****** 答案
A
*** 13-14
**** 段话
***** 转录
我已经暗恋她两年了，可是始终没有勇气向她表白。在朋友的鼓励下，我终于写了一份充满爱意的字条。可是，几次见到她，那只紧握字条的手总是无法从口袋里拿出来。就这样，浪费了好几次机会，字条已变得皱皱巴巴。终于有一天，不知是哪儿来的勇气，我一见到她，便把那张皱巴巴的字条塞进她手里，然后慌忙逃走了。第二天，她打来电话，说要跟我见面。我的心情是既兴奋又紧张，昏暗的路灯下我们见面了。她看着紧张不安的我，迫切地问道：“昨天你塞给我一百块钱干吗？”
***** 音频
2f888d36-39d7-4852-a362-870677afa936.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于这段话中的“我”，下列哪项正确？
******* 音频
65529d7d-c063-4aa7-8122-8ea81ecd5fbd.mp3
****** 选择
******* A
借给女孩儿一百块钱
******* B
打电话约女挂儿见面
******* C
给女孩儿写了求爱孙条
******* D
“我”的求爱被拒绝了
****** 答案
C
***** 14
****** 问题
******* 转录
从这段话中可以知道什么？
******* 音频
b0e8a3dc-600a-4015-92f2-176b08e656c9.mp3
****** 选择
******* A
“我”和她恋爱两年了
******* B
“我”总是没勇气表白
******* C
“我”对她态度很冷淡
******* D
“我”犹豫是否追求她
****** 答案
B
* 阅读
** 第一部分
*** 段话
好多人都会犯这样的[[gap][15]]，心里很想要成功，但是又缺乏勇气而迟迟不敢采取行动。
小黄性格内向胆小，因此年近39岁仍然单身一人。上个月公司新来了一位女职员，小黄常常找[[gap][16]]接近这个姑娘，但每次都面红耳赤，结结巴巴地聊上几句便走开了。他也曾经想过约这个姑娘看电影或迹街，但是每次都因为没有勇气开口，使约会遥遥无期。
这一天是“情人节“，小黄在妹妹的再三鼓励下，终于害羞地关上房门，然后战战兢兢地给这位女同事打电话，希望能约她共度佳节。
妹妹在房外等了好一阵。不久小黄兴奋地从房里冲了出来又跳又叫，妹妹[[gap][17]]地问道：“怎么样7[[gap][18]]7“小黄如释重负地说：“哇，我好并运，幸好她不在家。“
*** 题目
**** 15
***** 选择
****** A
缺点
****** B
态度
****** C
毛病
****** D
脾气
***** 答案
C
**** 16
***** 选择
****** A
借口
****** B
原因
****** C
对象
****** D
废话
***** 答案
A
**** 17
***** 选择
****** A
廉虚
****** B
迫切
****** C
冷淡
****** D
无所谓
***** 答案
B
**** 18
***** 选择
****** A
她拒钯你啦
****** B
她答应啦
****** C
你向她求婚啦
****** D
你改变主意啦
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 3d1eb3bc-7850-4371-af31-c60dbe53d7cf
:END:
**** 段话
人际交往，是一个古老而年轻的概念。说它古老，是因为自人类产生之日起，人们就开始感知它的存在。一个古代的阿拉伯哲人就曾经形象地描述过交往的重要性，他说一个不会交往的人，犹如陆地上的船，永远不会漂流到人生的大海中去。
**** 选择
***** A
人类的产生源于交往
***** B
交往对人类非常重要
***** C
阿拉伯哲人喜欢交往
***** D
不会交往的人无法生存
**** 答案
B
*** 20
:PROPERTIES:
:ID: f2c97790-25ca-4f9b-978c-def7fae71cfb
:END:
**** 段话
成就感，不是生命中“额外”的享受，而是保持生命力的“根本”因素。管理者只有在工作上充分满足员工的成就感，才能真正激发并延续员工的工作干劲儿，从而将个体生命力与公司竞争力紧密结合，提高工作效率。
**** 选择
***** A
有成就感生命才有意义
***** B
获得成就感是一种享受
***** C
要增强管理者的成就感
***** D
成就感可提升工作干劲儿
**** 答案
D
*** 21
:PROPERTIES:
:ID: fa1c019b-a53e-4710-a0ff-fc13afec4bf1
:END:
**** 段话
荷兰猪其实是老鼠的亲戚。也许是因为它们的身体矮矮胖胖、圆圆滚滚的，所以，当欧洲人第一次看见这种南美“小毛球”时，就用他们熟悉的农场动物——猪来为其命名。不管荷兰猪的名孙究竟因何而来，人们对这种小巧可爱的宠物的喜爱并没有因为它奇怪的名字而受到任何影响。
**** 选择
***** A
荷兰猪原产于南美
***** B
荷兰猪是猪的一种
***** C
荷兰猪是一种农场动物
***** D
荷兰猪是欧洲人的宠物
**** 答案
A
*** 22
:PROPERTIES:
:ID: 4ad096de-a22e-418a-b291-e5bdd7d7cae6
:END:
**** 段话
大街小巷和人一样，各有各的名字。每条胡同一形成，人们自然会给它起个名。这个名称一旦被大多数人所接受，叫开了，就成为人们交往、通信等活动中不可缺少的标志。在中国从胡同开始形成起，它的名称一直都是靠人们口头相传，至于用文字写在标牌上挂在胡同口上，是二十世纪初才开始有的。
**** 选择
***** A
胡同名都是请人专门起的
***** B
胡同名都是经大众认可的
***** C
二十世纪后胡同才有了名字
***** D
胡同产生之初是没有名字的
**** 答案
B
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
