* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: f198910e-fb9b-4556-8eb0-f3a2f9a91b55
:END:
**** 对话
***** 转录
女：这个胃药你晨起和入睡前各一次，一次两片。记住了吗？[[file:359c6b46-e50d-44d5-88af-48f87455716b.mp3][(audio)]]
男：好的，我明白了，谢谢大夫。[[file:a1a1fb82-fc4d-476b-9840-2897465092fc.mp3][(audio)]]
***** 音频
c54e3062-1731-4a9d-8ed7-0087e68e915d.mp3
**** 问题
***** 转录
胃药应该怎么吃？
***** 音频
7caf535b-e0bf-4f8c-9be3-926c8d6a2252.mp3
**** 选择
***** A
餐前吃
***** B
饭后吃
***** C
一日三次
***** D
早晚各两片
**** 答案
D
*** 2
:PROPERTIES:
:ID: 7d80489b-6ea5-46f8-a6c4-4b226def5d6c
:END:
**** 对话
***** 转录
男：亮亮是不是感冒了？一直打喷嚏。[[file:353a8002-4f49-48eb-9426-e88e09a562c7.mp3][(audio)]]
女：是，幼儿园这段时间感冒的小朋友特别多，肯定被传染上了。[[file:b8648953-2697-4810-960b-b7f877a0e292.mp3][(audio)]]
***** 音频
af0c2305-029a-4112-9a17-c372cd7d3729.mp3
**** 问题
***** 转录
亮亮是怎么感冒的？
***** 音频
f71bf41c-c676-4e72-af12-58070b0c0925.mp3
**** 选择
***** A
穿得太少了
***** B
睡觉着凉了
***** C
玩儿得太累了
***** D
小朋友传染的
**** 答案
D
*** 3
:PROPERTIES:
:ID: 5878f03e-946e-482a-9221-f6edd846c2af
:END:
**** 对话
***** 转录
男：老婆，我的腰带用最里面的洞眼也有点儿松了，你得帮我再打个洞了。[[file:e2d8f71f-5c13-4e4d-a372-1cafb7514de5.mp3][(audio)]]
女：好的。看来，你这段时间减肥很有效果嘛。[[file:0a2f81b0-5c20-4c97-b532-1941215309b5.mp3][(audio)]]
***** 音频
3c300f58-5d49-4bb2-9fe6-1267776c6b35.mp3
**** 问题
***** 转录
从对话中，可以知道男的什么？
***** 音频
fdadf516-de3a-4404-bdcd-17f1b3b9d056.mp3
**** 选择
***** A
减肥很成功
***** B
节食很痛苦
***** C
体重增加了
***** D
腰带太短了
**** 答案
A
*** 4
:PROPERTIES:
:ID: 58cb6135-b2ba-4900-909e-0bc147b72ffe
:END:
**** 对话
***** 转录
男：看你今天还是不怎么动筷子，是拔的那颗牙还疼吗？要不要给你做碗面条儿？[[file:7c523b1e-a760-4ed6-a11f-a4cf24ac9aa6.mp3][(audio)]]
女：是还有点儿疼。看着什么都没胃口。[[file:ad01927c-ca2a-4331-85b3-66a2aa74bafa.mp3][(audio)]]
***** 音频
9ddb34b2-d215-4628-be0b-370416cf4099.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
fe2e4790-0f23-4462-8023-a3f0479de44a.mp3
**** 选择
***** A
菜不合胃口
***** B
已经吃饭了
***** C
牙疼不想吃
***** D
想吃面条儿
**** 答案
C
*** 5
:PROPERTIES:
:ID: ec5f16fa-f8de-4836-adaa-cbaff12a2c4c
:END:
**** 对话
***** 转录
女：小刘怎么辞职了？[[file:eaa41b9d-9d48-4497-844a-d479deac4ede.mp3][(audio)]]
男：干我们这行业的，生活不规律，她孩子小，离不开人。[[file:8f7dab67-1dfb-42c4-9df7-f7c26ed893b4.mp3][(audio)]]
***** 音频
2f4fcec5-ec74-43a8-be27-63ba052cb748.mp3
**** 问题
***** 转录
关于小刘，可以知道什么？
***** 音频
df06c6f3-aa36-44e5-8070-64328bc3454d.mp3
**** 选择
***** A
换了新工作
***** B
身体不太好
***** C
要照顾孩子
***** D
刚刚怀孕了
**** 答案
C
*** 6
:PROPERTIES:
:ID: a1dbc7f0-683d-41c3-89aa-30af344c0eb8
:END:
**** 对话
***** 转录
男：昨天的电影你觉得怎么样？[[file:1e124bb9-88e3-4848-9e88-2d1c64bcf037.mp3][(audio)]]
女：开头部分还挺精彩，但结尾部分太平常了，有点儿乏味。[[file:b090ef64-874e-4016-807f-be287fa48e29.mp3][(audio)]]
***** 音频
5a5acd5b-5008-4226-b8f7-ae9074daa5f1.mp3
**** 问题
***** 转录
女的觉得电影怎么样？
***** 音频
b172260f-982f-4b43-a18f-8d92013731c1.mp3
**** 选择
***** A
开头没看懂
***** B
演员很漂亮
***** C
结尾出人意料
***** D
剧情令她望失
**** 答案
D
** 第二部分
*** 7
**** 对话
***** 转录
男：准备什么时候登记呀？
女：就我生日那天吧，以后生日和结婚纪念日一块儿过，好记。
男：哟，那马上就要到了，要你妈过去陪陪你吗？
女：不用，等婚礼的时候您跟妈再过来吧。
***** 音频
a4bc5ac9-2bd2-4ed6-813e-97c12ec625fe.mp3
**** 问题
***** 转录
女的马上就要做什么了？
***** 音频
ff0faebb-c01d-4b8d-8637-9ccbfb5417ce.mp3
**** 选择
***** A
结婚登记
***** B
外出旅行
***** C
举办婚礼
***** D
庆祝生日
**** 答案
A
*** 8
**** 对话
***** 转录
女：行李都准备好了吗？要我给你叫个车吗？
男：不用，一会儿公司刘秘书开车来接我。
女：你换好登机牌了吗？
男：换好了，昨晚就打印出来了。放心吧。
女：到了给我来个短信。
***** 音频
6268dcfc-7cc9-43a3-93f8-3c15bc337e68.mp3
**** 问题
***** 转录
他们现在最可能在哪儿？
***** 音频
a25eb805-4937-404d-8776-9cd7b3dd04f3.mp3
**** 选择
***** A
车站
***** B
公司
***** C
家里
***** D
机场
**** 答案
C
*** 9
**** 对话
***** 转录
女：彤彤高考填报志愿的事，我怎么都觉得她那么报不太好。
男：女儿大了，这事我们还是应该尊重她的愿望。
女：家里还有安眠药吗？这两天总睡不着。
男：我看你是心事太重了，你少操点儿心比吃什么药都强。
***** 音频
30274843-c33b-4e80-8974-f25e60cecd24.mp3
**** 问题
***** 转录
女的这两天为什么睡不好？
***** 音频
8a96e0b1-aa63-4902-a8e7-0d523c580610.mp3
**** 选择
***** A
忘丁吃安眠药
***** B
担心孩子的事
***** C
和丈夫吵架了
***** D
身体不太舒服
**** 答案
B
*** 10
**** 对话
***** 转录
男：小李精神状态不太好，抽空儿你找他聊聊，安慰一下。
女：他怎么了？
男：最近，公司业务不太顺利，心理压力比较大。
女：我看最好的办法是放他几天假，出去玩儿玩儿。
***** 音频
b34a36e7-af11-4a8c-8f9b-354a12a7074e.mp3
**** 问题
***** 转录
女的觉得小李现在需要做什么？
***** 音频
430c2866-a067-4af6-ba82-46c755d76322.mp3
**** 选择
***** A
放松休假
***** B
努力工作
***** C
看心理医生
***** D
找朋友聊天
**** 答案
A
*** 11-12
**** 对话
***** 转录
女：夏天冰箱里保存的东西一多，就特别容易有异味。
男：我听说拿几块新鲜的桔子皮放在冰箱里，可以去掉异味。
女：这季节哪儿来的桔子啊？据说，茶叶也能吸收异味。
男：你别打我那龙井茶的主意，我都舍不得喝，能给你这么浪费？
女：看你小气的。
男：我们同事说，拿一小块生面放冰箱里，效果也不错，你试试。
女：这倒是从没听说过，那晚上做馒头时，我留一块。
***** 音频
e8a72644-14a8-4727-a0f0-d94bba066b14.mp3
**** 题目
***** 11
****** 问题
******* 转录
这两个人主要在讨论什么事？
******* 音频
c81bd2d2-772d-4ada-bdd4-8f8d9cdf3465.mp3
****** 选择
******* A
晚饭吃什之
******* B
如何保存水果
******* C
怎么去除冰箱异显
******* D
什么时候去超市购物
****** 答案
C
***** 12
****** 问题
******* 转录
关于男的，从对话中可以知道什么？
******* 音频
02afd0ee-8084-4b53-8fcf-32f0f394a11d.mp3
****** 选择
******* A
会做饭
******* B
娆喝茶
******* C
想买橘二
******* D
要买茶叶
****** 答案
B
*** 13-14
**** 段话
***** 转录
我们的皮肤就像一个袋子把我们包裹在里面。我们的身体里大部分都是水分，同海水一样，我们身体里的水也是咸的，也会蒸发。风和阳光都会带走体内的水分，而皮肤能阻止身体里的水分流失。太强的阳光会伤害我们，皮肤则可以保护我们避免受到日晒。同样，皮肤也可以让我们远离那些脏东西，这是非常重要的，因为有些脏东西会让我们生病。皮肤还可以感受外界事物，它能感知冷暖，感受到疼痛。例如：篝火让我们觉得温暖，而砸在脸上的雪球则会让我们觉得冰冷和疼痛。
***** 音频
bbe80853-ba66-4cca-be7d-910624979757.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于皮肤，下列哪项正确？
******* 音频
6cabdebe-3b17-4ebf-8a10-3212dbee41e5.mp3
****** 选择
******* A
可以减轻人体的疣痛
******* B
影响我们感受外界事物
******* C
能阻止体内水分的流失
******* D
使我们避免接触他人而生病
****** 答案
C
***** 14
****** 问题
******* 转录
这段短文主要介绍的是皮肤的什么？
******* 音频
894d593b-641e-44e9-83ae-353d439ad957.mp3
****** 选择
******* A
作用
******* B
结构
******* C
保护
******* D
卫生
****** 答案
A
* 阅读
** 第一部分
*** 段话
北京人送客有很多[[gap][15]]，不常来的客人或是老年客人，一定将其送到或[[gap][16]]到大门以外，道别后目送来客远去再往家走。大人会告诉孩子：十万不可刚和客人告别就转身而回，更不许客人前脚刚走不远，后边就立即关大门，关门声响很大，如果被客人听见，就失礼了。
北京人很[[gap][17]]送别时“全家出动”（除病人外），以示热情，对待宾客一定要有始有终。特别是教育孩子，客人走时一定要停下自已手中的“活儿”，[[gap][18]]，切不可只顾自已玩耍。
*** 题目
**** 15
***** 选择
****** A
规律
****** B
理由
****** C
现象
****** D
规矩
***** 答案
D
**** 16
***** 选择
****** A
扶
****** B
拉
****** C
退
****** D
推
***** 答案
A
**** 17
***** 选择
****** A
强调
****** B
讲究
****** C
提倡
****** D
推荐
***** 答案
B
**** 18
***** 选择
****** A
帮父母关好大门
****** B
马上躲进自己的房间
****** C
起身和大人一起送客
****** D
收拾客人用过的茶杯
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: f5bfdfca-a8a9-4cd4-925b-ea4633fc370f
:END:
**** 段话
交谈是社交活动中必不可少的内容，更是一门艺术。俗话说：“一句话说得人笑，一句话说得人跳。”关键就看你能不能把话说得巧妙。
**** 选择
***** A
交谈需要对方的理解
***** B
交谈是为了使人开心
***** C
交谈要注意说话得体
***** D
交谈是一门舞蹈艺术
**** 答案
C
*** 20
:PROPERTIES:
:ID: 1de46f2c-63c9-4e8c-a0fe-c9b0d7436dfc
:END:
**** 段话
春季是由冬人夏的过渡季节。虽然气温回升，天气逐渐暖和，但北方冷空气还比较强烈，它每隔几天就要分成一小股一小股地南侵。冷空气南下减弱后，暖空气又趁机北上。冷睡空气活动频繁，于是，天气乍暖还寒，冷热多变，一天之内气温变化较大，如果人们过早地脱下冬衣，就容易感冒。因此，还是“春捂”一点儿好。
**** 选择
***** A
春季气温回升一般较快
***** B
春季冷暖空气常交替活动
***** C
春季是最容易感冒的季节
***** D
过早地脱下冬衣叫“春捂”
**** 答案
B
*** 21
:PROPERTIES:
:ID: 92cefb2d-6797-43d4-86f1-78472cf8a607
:END:
**** 段话
早餐在一日三餐中最重要，它不但能及时补充我们晚上消耗的营养，还能使我们一上午都精力充沛地学习或工作。有调查表明，习惯吃早餐的孩子比不吃早餐的孩子身体更好，长得更结实，更不容易得病，学习时注意力更集中，反应更快，理解力更强，成绩更好。
**** 选择
***** A
早餐的营养是三餐中最丰富的
***** B
人体从早餐中吸收的营养最多
***** C
吃早餐的孩子更容易提高成绩
***** D
相比成人，早餐对孩子更重要
**** 答案
C
*** 22
:PROPERTIES:
:ID: 3cd1d8fe-0b03-47a6-b51f-2a13aaeeae98
:END:
**** 段话
作为电视节目主持人，我在工作中常会运用“峰终定律”。例如，做节目时，与开幕式相比，我们宁可把更多的精力集中在闭幕式上，这样可以加强观众对节目的印象。虽然很多人并不了解“峰终定律”，但是，他们能从经验中体会这种做法的重要性。
**** 选择
***** A
观众通常对闭幕式更关注
***** B
许多人不认同“峰终定律”
***** C
“峰终定律”是节目制作的理论
***** D
“峰终定律”对“我”的工作有帮助
**** 答案
D
** 第三部分
*** 23-25
**** 段话
在我们的健康观念中，人们都接受一种说法：“多吃蔬果。”英国一场始于1994年的“每天五份果蔬”的运动，曾经得到大多数人的支持。英国牛津大学的专家迈克说：“‘每天五份果蔬’的口号当然比简单地告诉人们要‘均衡膳食’有用多了，毕竟有几个普通人能知道所谓‘均衡膳食’的真正含义呢？”
世界卫生组织曾建议人们每天吃的果蔬最好不低于400克。但有多少国家能达到这个水平呢？英国人当时每人平均果蔬食用量只有这个数量的一半左右，不过丹麦人能达到600克；希腊也远远“超标”人均“六份蔬菜外加三份水果”，国水以平均每份80克来算，便能达到720克。
研究发现，那些由于饮食导致的心脏病和癌症发病率低的国家，人均果蔬食用量都很高——最高能达到每天十份。所以说，“每天吃五份果蔬”的确有助身体健康，也许多吃一些效果会更好。
然而，关于哪些加工食品可以用来补充我们的果蔬食用量，很多国家都没有相关的严格规定。当我们自以为吃着那些经过加工的水果和蔬菜，达到了“健康生活新标准”，实际上我们却有可能正吃下更多的盐、糖和脂肪。
**** 题目
***** 23
****** 问题
关于“均衡膳食”，专家迈克认为：
****** 选择
******* A
很难统一标准
******* B
实际很难做到
******* C
一般人搞不清
******* D
需要更多宣传
****** 答案
C
***** 24
****** 问题
关于世界卫生组织对果蔬食用量的建议，从文中可知：
****** 选择
******* A
丹麦人不愿接受
******* B
很多国家都做不到
******* C
英国人均食用量最少
******* D
希腊人能达到每天十份
****** 答案
B
***** 25
****** 问题
本文最可能出自下列哪种杂志？
****** 选择
******* A
《科技前沿》
******* B
《农业天地》
******* C
《家庭医生》
******* D
《环球影视》
****** 答案
C
*** 26-28
**** 段话
天气突然转凉，温度的降低会直接刺激人体，使得胃肠功能变得紊乱，从而影响正常的消化和吸收。因此在寒冷的冬季，我们一定要时刻注意自己的胃肠变化，做好保护工作，打一场胜利的“保胃战”。
现代人工作压力越来越大，经常是忙得忘了吃饭，或者是即使很饿也无法抽空去吃饭。长此以往，对胃部的刺激很大。尤其在冬季，胃部本身就容易发病，如果饮食再没有规律的话，就更容易引起胃酸分泌异常，加重胃部的负担。因此，每天有规律地按时吃饭才是最佳的保胃措施。如果不能一天三顿正点进食的话，可以改为一天5至6次，分次进食，一次少量，只要是每天有规律的即可。这样不仅可以保护肠胃，还不会耽误到其他的事情。
有胃病的朋友都知道，胃部敏感的时候，如果吃了一些“硬菜”，比如大鱼大肉等就会觉得很不舒服。正因如此，对于肠胃的保护，我们应该采取软化政策。粥、面条儿、热牛奶等等都是不错的选择。当然，除此之外，在饮食制作过程中，也应该尽量选择蒸、煮、烩、炖等烹任方法，以减少对胃的刺激。
身体的健康离不开经常性的运动，一个好的身体才能够抵御疾病的侵袭。让你的肠胃在冬季不会过于受到伤害，胃部保暖很重要，温度过低会使腹部受凉，导致胃肠不适。因此，在这个季节就不要再选择过短的衣服了。
当然，以上说的都是一些基本的保养方法，最重要的还是要坚持，因为胃肠的调养和保护不是一天成就的。同时，胃病的发生与发展，与人的情绪、心态密切相关。因此，在养胃护胃的同时，大家还应注意劳逸结合，保持愉快和稳定的情绪。
**** 题目
***** 26
****** 问题
本文建议每天不能规律进食的人，可以：
****** 选择
******* A
早餐尼量多吃
******* B
每次尽量吃好
******* C
增加进食次数
******* D
吃些养胃的药
****** 答案
C
***** 27
****** 问题
本文中说的“硬菜”指的是：
****** 选择
******* A
油炸食品
******* B
粥或面条儿
******* C
温度太烫的食物
******* D
不易消化的食物
****** 答案
D
***** 28
****** 问题
下列哪项最适合做本文标题：
****** 选择
******* A
冬季“保胃战”
******* B
饮食要规律
******* C
养胃从保暖做起
******* D
浅谈健胃食品
****** 答案
A
* 书写
** 第一部分
*** 29
**** 词语
***** 1
他要给
***** 2
时间
***** 3
更多的
***** 4
争取
***** 5
自已
**** 答案
***** 1
他要给自己争取更多的时间。
*** 30
**** 词语
***** 1
刚
***** 2
给我
***** 3
推荐了
***** 4
老刘
***** 5
一份工作
**** 答案
***** 1
老刘刚给我推荐了一份工作。
***** 2
老刘给我刚推荐了一份工作。
*** 31
**** 词语
***** 1
被人
***** 2
这是
***** 3
细节
***** 4
忽视的
***** 5
最容易
**** 答案
***** 1
这是最容易被人忽视的细节。
