* 练习

** 1
:PROPERTIES:
:ID: e35d2ab3-03e6-4b4d-b41f-4cc83c99f051
:END:
*** 选择
**** 1
度过
**** 2
集中
**** 3
体会
**** 4
推荐
**** 5
运用
**** 6
争取
*** 题目
**** 1
***** 句子填空
我刚开始学滑雪的时候，最大的[[gap]]就是要放松，越紧张越容易摔（shuāidǎo，to fall down）。
***** 答案
3
**** 2
***** 句子填空
学知识不能死记硬背，要懂得灵活地[[gap]]。
***** 答案
5
**** 3
***** 句子填空
你复习时要[[gap]]注意力，效果才会好。
***** 答案
2
**** 4
***** 句子填空
一些现代营养学专家常常向大家[[gap]]“餐餐有蔬菜，每天有水果”。
***** 答案
4
**** 5
***** 句子填空
我在外么外婆身边[[gap]]了美好的童年。
***** 答案
1
**** 6
***** 句子填空
机会要靠自己去[[gap]]。
***** 答案
6
** 2
*** 1
:PROPERTIES:
:ID: 74bce003-69df-453a-8ad2-78e14acf0efa
:END:
**** 句子填空
大家要迅速地熟悉新产品，[[gap]]更好地向顾客推广。
**** 选择
***** A
用
***** B
以
**** 答案
B
*** 2
:PROPERTIES:
:ID: 9a9fb1c6-7c08-4ee6-9992-196a8cf6df4f
:END:
**** 句子填空
这次旅行给我留下了[[gap]]的印象。
**** 选择
***** A
深
***** B
深刻
**** 答案
B
*** 3
:PROPERTIES:
:ID: 4db6354b-2813-4919-a583-e00cdd50e7d3
:END:
**** 句子填空
这部电影很[[gap]]，我觉得没必要去看。
**** 选择
***** A
平常
***** B
平时
**** 答案
A
*** 4
:PROPERTIES:
:ID: 89dd212a-60a5-4f00-abf2-2f502d8c2ddd
:END:
**** 句子填空
他被[[gap]]为本校今年的十大“优秀毕业生”之一。
**** 选择
***** A
评价
***** B
评
**** 答案
B
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
事情[[A]]发生后，领导[[B]]采取了[[C]]措施，[[D]]积极应对。
**** 词语
迅速
**** 答案
B
*** 2
**** 句子
[[A]]三加五[[B]]是[[C]]八[[D]]吗？
**** 词语
等于
**** 答案
C
*** 3
**** 句子
十几年[[A]]过去了，[[B]]她[[C]]那么[[D]]美丽。
**** 词语
依然
**** 答案
C
*** 4
**** 句子
[[A]]我[[B]]多[[C]]花点儿钱，[[D]]也要买一个质量好点儿的。
**** 词语
宁可
**** 答案
B
* 扩展
** 词语
*** 话题
医务2
*** 词语
**** 1
诊断
**** 2
手术
**** 3
血
**** 4
肌肉
**** 5
骨头
**** 6
胃
**** 7
心
**** 8
脏
**** 9
病毒
**** 10
传染
**** 11
寿命
** 题目
*** 1
**** 句子
医生还这为他[[gap]]病情，请耐心地等待。
**** 答案
1
*** 2
**** 句子
我的电脑速度越来越慢了，是不是中了[[gap]]？
**** 答案
9
*** 3
**** 句子
这是一种新型的[[gap]]病，可能会在人和动物之间传播（chuánbō，to spread）。
**** 答案
10
*** 4
**** 句子
海龟（hǎiguī，sea turtle）的[[gap]]最长可达150多年，是动物中当之无愧的老寿星。
**** 答案
11
* 注释
** （三）词语辨析
*** 忽视——轻视
**** 做一做
***** 1
****** 句子
以前我们[[gap]]了教育问题，现在要赶上去。
****** 答案
******* 1
******** 忽视
1
******** 轻视
0
***** 2
****** 句子
我们过多地看电视、玩手机，[[gap]]了家人之间的交流。
****** 答案
******* 1
******** 忽视
1
******** 轻视
0
***** 3
****** 句子
虽然这是一份平常的工作，你也不能[[gap]]，要认真做好。
****** 答案
******* 1
******** 忽视
0
******** 轻视
1
***** 4
****** 句子
你不要因为他是小孩子就[[gap]]他。
****** 答案
******* 1
******** 忽视
0
******** 轻视
1
* 课文
** 转录
我奶奶说过：“人们应该在最美好的时候离开。”因为这个认知而获得诺贝尔奖的，不是我奶奶，而是心理学家丹尼尔。卡内曼。他将这一现象命名为“峰终定律”：我们对事物的记忆仅在高峰和结尾，而事情的经过对记忆几乎没有影响。高峰之后，终点出现得越迅速，这件事留给我们的印象就越深刻。
大部分人不理解这一定律。比如说为了一场戏剧演出，我们会投入很多时间，准备服装、化妆、道具、舞台美术，以创造良好的效果，争取给观众留下一个好的印象，却常常忽视结束退场时的准备。演出开始时人们认为很有魅力，但是糟糕的结局会给人留下难以忘记的坏印象。
有一次，我去参加一个婚礼，前三个小时感觉都很好，只在最后一个小时感到无聊。三个小时快乐减一个小时无聊等于两个小时快乐，也就是说，我愉快地度过了两个小时。但是，我的记忆并不是这样计算的。如果我参加另外一次活动，只在那里待一个小时，早早地告别，我却享受了满满 60 分钟的快乐。与第一次相比，第二次的聚会留给我的印象更为美好。
看电影也是如此。一部电影，开始虽然剧情平平常常，如果最后半个小时能使我们感动，我们依然会向别人推荐它。相反，如果在前半个小时就把剧情的创造力表现得淋漓尽致，结尾却非常普通，那么，观众对这部电影的评价就肯定不好，甚至会说这是一部“烂片”。
作为电视节目主持人，我在工作中常常会运用“峰终定律”。例如，做节目时，与开幕式相比，我们宁可把更多的精力集中在闭幕式上，这样可以加强观众对节目的印象。虽然很多人并不了解“峰终定律”，但是，他们能从经验中体会这种做法的重要性。
