* 课文
** 转录
屡次创业，却屡次惨遭失败的人总想知道，创业有窍门吗？当然有，窍门就是创业不可盲目，要依据市场规则捕捉商业机会。1903 年吉列先生发明的可替换刮胡刀、1958 年安藤百福发明的方便面、1992 年戚石川兄弟发明的罐装八宝粥，都受到了市场热捧，并给创业者带来了数额可观的财富，成功的案例告诉我们：创业必须依据市场需求，这是一条永恒的真理，只要遵循这条规则，就没有不成功的道理。
独具慧眼，寻找机遇
市场需求无处不在，却往往易被忽视，别人没发现，或是不屑做的生意，往往孕育着机会。譬如，在新产品博览会上，王先生看到了一台叫作“电池分析修复仪”的小机器，它是用来修复手机电池的。手机电池的正常寿命是 5 至 6 年，事实上大家的电池却没有那么耐用，往往用一年就坏了，换新电池又很贵。而所谓坏了，只是化学物质沉淀到了绝缘层，美国人发现在一定条件下，能够将其还原成初始状态，于是发明了这种机器。王先生花 4 万元买下了这台能够像变魔术一样修好电池的机器。之后，在商场租了柜台，修一块电池收费50～70 元，扣掉场地租金和税金，月收入上万，不到两个季度就轻松收回了本钱。类似这样的生意，即使碰上通责膨胀，也不会对他产生丝毫影响。可是，如果你没有眼光，就看不到商机；如果你思维平庸，就发现不了商机；只要你勤劳，市场就捏在你的手里。
从竞争对手的产品缺陷中捕捉商机
研究竞争对手，从中找出其产品的弱点及营销的薄弱环节，是捕捉商机的有效方法之一。
当年，日渐兴旺的日本泡泡糖市场大部分被劳特垫断，江崎公司想扩充这方面的业务，于是专门成立了团队，研究劳特的产品，以寻找市场缝隙。研究结果发现劳特产品有四个不足：一，成年人的泡泡糖市场正在扩大，劳特的眼光仍停留在儿童身上；二，劳特的产品口味单一，而消费者的需求正在日益多样化；三，劳特泡泡糖外观老旧，缺乏新式样；四，劳特产品售价 110 日元，买时得掏 10 日元硬币，不方便购买者。于是江崎公司大胆布局，以成年人的消费需求为依据设计产品，叉拟定了相应的市场营销策略，不久，推出四种功能型泡泡糖：
1. 司机用泡泡糖，以强烈的刺激消除司机的困倦。
2. 交际用泡泡糖，咀嚼后，可清洁口腔，消除口腔异味。
3. 体育用泡泡糖，内含多种维生素，有利于消除疲劳。
4. 轻松型泡泡糖，通过添加叶绿素，改变人的不良情绪。
在产品可口的同时，精心设计包装和造型，定价分 50 和 100 日元两种。江崎的产品物美价廉，风味独特。不靠广告吹捧，品尝后，消费者购买踊跃，市场需求呈井喷式爆发，财务收入也呈井喷式增长。这就是市场，只要你细心研究市场，细心研究消费者的需求，细心研究市场产品的优劣，对产品的不足做些局部改进，就有可能得到消费者的认可；你愈是为消费者考虑得周全，消费者愈是会慷慨地关照你。
从市场的潜在需求中寻找商机
在台湾某游览观光区，一台流动彩印车吸引了大家的目光，游客可以在这儿就近冲印照片，可以把喜欢的图案、肖像印在纪念品和纺织品上，作为独一无二的旅游留念。
流动彩印车的发明者是周家两兄弟，哥哥是汽车维修工，弟弟是摄影发烧友。台湾经济转型，旅游业成了台湾经济的支柱产业。兄弟俪发现，对照观光客的需求，传统彩色冲印做法太过陈旧，哪个游客能为冲洗照片等好几天？于是兄弟俩齐心协力，发挥各自的专长，以 50 万台币做资本，发明了这辆相当于一个小型专业冲印部的流动彩印车。
流动彩印车一出现就大受欢迎，每逢周末、节假日以及人多的场合简直就忙不过来，它最大的优势就是方便快捷，不像以往，要等上好几天。旅游淡季，彩印车还可以为学生的制服、不同规格的运动服印制高品质的图案。彩印车很快就有了知名度，收益也呈递增趋势，很短的周期就收回了成本。
可见，创业不是赌博，创业不能靠空想，能够准确预测市场的湛在需求，具有超前意识，是经营者必备的素质。
