* Text

** title

慧眼捕捉商机

** content

屡次创业，却屡次惨遭失败的人总想知道，创业有窍门吗？当然有，窍门就是创业不可盲目，要依据市场规则捕捉商业机会。1903年吉列先生发明的可替换刮胡刀、1958年安藤百福紁明的方便面、1992年戚右川兄弟发明的罐装人宝粥，都受到了市场热捧，并给创业者带来了数额可观的财富，成功的案例告诉我们：创业必须依据市场需求，这是一条永恒的真理，只要遵循这条规则就没有不成功的道理。

独具慧眼，寻我机遇

市场需求无处不在，却往往旸被忽视，别人没发现，或是不屑做的生意，往往孕育券机会。譬如，在新产品博览会上，王兒生看到了一台叫作“电池分析修复仪”的小机器，它是用来修复手机电池的。手机电池的正常寿命是5至6年，事实上不家的电池却没有那么耐用，往往用一年就坏了，換新电池又很贵。而所谓坏了，只是化学扬质沉淀到了绝缘层，美国不发现在一定条件下，能够将其还原成初始状态，于是紁明了这种机器。王先生花4万元买下了这台能够像变魔术一样修好电池的机器。之后，在商场租了柜台，修一块电池收费50～70元，折扣掉场地租金和税金，月收入上万，不到两个季度就轻松收回了本钱。类似这样的生意，即使碰上通货膨胀，也不会对他产生丝影响。可是，如果你没有眼光，就看不到商机如果你思维平庸，就发现不了商机只要你勤劳，市场就捏在你的手里。

从竞争对手的产品缺陷中捕捉商机

研究竞争对手，从口找出其产品的弱点及营销的薄弱环节，是捕捉商机的有效方法之一。

当年，日渐兴旺的日本泡泡糖市场不部分被劳特垄断，江崎公司想扩充这方面的业务，于是小专门成立了团队，研究劳特的产品，以寻找市场缝隙。研究结果发现劳特产品有四个不足：一，成年人的泡泡糖市场正在扩不，劳特的眼光仍人亭留在儿童身上呩，劳特的产品口味单一，而消费者的需求正在日益多样化口；三，劳特泡泡糖外观老旧，缺乏新式样；四，劳特产品售价110日元，买时得掏10日元硬币，不方便购买者。于是江崎公司不胆布局，以成年人的消费需求为依据设计产品，又拟定了相应的市场营销箱略，不久，推出四种功能型泡泡糖：

1．司机用泡泡糖，以强烈的刺激消除司机的困倦。
2．交际用泡泡糖，咀嚼后，可清洁口腔，消除口腔异味。
3．体育用泡泡糖，内含多种维生素，有利于消除疲劳。
4．轻松型泡泡糖，通过添加叶绿素，改变人的不良情绪。

在产品可口的同时，精之设计包装和造型，定价分50和100日元两种。江崎的产品场需求呈井喷式爆发，财务收入也呈井喷式增长。这就是市场，只要你细之研究市场，细心研究消费者的需求，细心研究市场产品的优劣，对产品的不足做些局部改进，就有可能得到消费者的认可口你愈是为消费者考虑得周全，消费者愈是会慷慨地关照你。

从巿场的潜在需求中寻找商机

在台湾某览枧光区，一台流动彩印轉吸引了大家的目光，游客可以在这儿就近冲印照片，可以把喜欢的图案、肖像印在纪念品和纺织品上，作为独一无二的旅游留念。

流动彩印车的发明者是周家两兄弟，哥哥是汽轉维修工，弟弟是摄影发烧友。台济的支柱产业。兄弟俩犮现，对照观光客的需求，传统彩色冲印做法太过陈旧，哪个游客能为冲洗照片等好几天？于是兄弟俩齐心协力，发挥各自的专长，以50万台币做资本，发明了这辆相当于一个小型专下半仲印部的流动彩印车。

流动彩印车一出现就不受欢迎，每逢周未、节假日以及人多的场合简直就忙不过来，它最大的优势就是方便快捷，不像以往，要等上好几天。旅游淡季，彩印车还可以为学生的制服、不同规格的运动服印制高品质的图案。彩印车很快就有了知名度，收益也呈递增趋势，很短的周期就收回了成本。

可见，创业不是赌博，创业不能靠空想，能够准确预测市场的潜在需求，具有超前意识，是经营者必备的素质。

** source

改编自《经商就这几道》，编著：王咏星

** new words

屡次 / lv3 ci4 / time and again, repeatedly ;
依据 / yi1 ju4 / according to ;
罐 / guan4 / can, tin ;
数额 / shu4'e2 / number, amount ;
永恒 / yong3 heng2 / eternal, perpetual ;
遵循 / zun1 xun2 / to follow, to adhere to ;
 不屑 / bu2 xie4 / to think sth. not worth doing ;
孕育 / yun4 yu4 / to be pregnant with, to breed ;
博览会 / bo2 lan3 hui4 / exposition, expo ;
耐用 / nai4 yong4 / durable ;
魔术 / mo2 shu4 / magic ;
扣 / kou4 / to deduct, to discount, to take... off... ;
季度 / ji4 du4 / quarter (of a year) ;
本钱 / ben3 qian2 / capital, seed money ;
通货膨胀 / tong1 huo4 peng2 zhang4 / inflation ;
平庸 / ping2 yong1 / mediocre, ordinary ;
捏 / nie1 / to hold between the fingers, to pinch ;
环节 / huan2 jie2 / link, segment ;
兴旺 / xing1 wang4 / prosperous, flourishing, thriving ;
垄断 / long3 duan4 / to monopolize ;
扩充 / kuo4 chong1 / to expand ;
掏 / tao1 / to take out, to draw out ;
布局 / bu4 ju2 / to arrange, to lay out ;
拟定 / ni3 ding4 / to draw up, to work out ;
箱略 / ce4 lve4 / tactic, strategy ;
咀嚼 / ju3 jue2 / to chew ;
可口 / ke3 kou3 / yummy, delicious ;
物美价廉 / wu4 mei3 jia4 lian2 / cheap and fine ;
风味 / feng1 wei4 / flavor ;
吹捧 / chui1 peng3 / to flatter, to tout ;
品尝 / ping3 chang2 / to taste ;
踊跃 / yong3 yue4 / eagter, active ;
井 / jing3 / well ;
财务 / cai2 wu4 / finance ;
局部 / jue2 bu4 / part ;
关照 / guan1 zhao4 / to look after, to keep an eye on ;
观光 / guan1 guang1 / to go sightseeing ;
就近 / jiu4 jin4 / (to do or get something) nearby, in the neighborhood ;
肖像 / xiao4 xiang4 / portrait ;
纺织 / fang3 zhi1 / to spin and weave ;
留念 / liu2 nian4 / to accept, keep as a souvenir ;
对照 /  dui4 zhao4 / to refer to, to compare ;
齐心协力 / qi2 xin1 - xie2 li4 / to make concerted efforts, to be all of one mind, to bend their efforts in a single direction ;
专长 / zhuan1 chang2 / speciality ;
资本 / zi1 ben3 / capital ;
以往 / yi3 wang3 / before, previously ;
淡季 / dan4 ji4 / slack season, off season ;
制服 / zhi4 fu2 / uniform ;
规格 / gui1 ge2 / standard, norm ;
递增 / di4 zeng1 / to increase progressively;
周期 / zhou1 qi1 / period, cycle ;
赌博 / du3 bo2 / to gamble ;
空想 / kong1 xiang3 / to daydream ;





*** QUESTION "可口"和“好吃"有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-17 Wed 01:08]
:END:

*** QUESTION 关照“和”照顾“有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-17 Wed 01:19]
:END:

