* 热身

** 1
:PROPERTIES:
:ID: f6ce8b3a-d212-4876-be0e-656be2768d86
:END:

*** 1

**** 词语

轻松

**** 答案

b

*** 2

**** 词语

网球

**** 答案

d

*** 3

**** 词语

作家

**** 答案

f

*** 4

**** 词语

勇敢

**** 答案

c

*** 5

**** 词语

饼干

**** 答案

a

*** 6

**** 词语

爱迪生

**** 答案

e

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: ca4eb0d5-8c86-49e0-bc49-bf775dbb7840
:END:

**** 选择

***** 1

过程

***** 2

至少

***** 3

区别

***** 4

正确

***** 5

暂时

**** 题

***** 1

****** 段话填空

我住的地方离地铁站有点儿远，走路🟦要三十分钟。

****** 答案

至少

***** 2

****** 段话填空

所有的困难都是🟦的，要有信心，我相信你一定会成功。

****** 答案

暂时

***** 3

****** 段话填空

“爱”和“喜欢”有什么🟦？我认为“爱”比“喜欢”的感情更深。

****** 答案

区别

***** 4

****** 段话填空

其实，只要我们真正努力过了，就不需要太关心结果。因为不管最后是成功还是失败，在努力的🟦中，我们已经学到了很多乐西。

****** 答案

过程

***** 5

****** 段话填空

减肥不只是为了瘦，更是为了健康。🟦的减肥方法是按时吃饭，多吃水果，多运动，而不是锇肚子。

****** 答案

正确


*** 6-10
:PROPERTIES:
:ID: 4c654cf8-9d00-4416-8e96-0826825f1594
:END:

**** 选择

***** 1

汗

***** 2

得

***** 3

取

***** 4

理想

***** 5

放弃

**** 题

***** 6

****** 对话填空

Ａ：师傅，麻烦您快点儿行吗？我🟦在九点之前到大使馆。
Ｂ：不用担心，保证按时把您送到。

****** 答案

得

***** 7

****** 对话填空

Ａ：你哥不是说三点到吗？都过去半个小时了，怎么还没出来？
Ｂ：他还得去🟦行季箱，您别担心，我打个电话问问。

****** 答案

取

***** 8

****** 对话填空

Ａ：外面热吗？你怎么满头大🟦？
Ｂ：电梯坏了，我爬楼梯上来的。

****** 答案

汗

***** 9

****** 对话填空

Ａ：你考虑清楚了？真的要🟦这次机会？
Ｂ：是的，我妈妈身体不太好，我决定留下来照顾她。

****** 答案

放弃
***** 10

****** 对话填空

Ａ：你研究生考试考得怎么样？
Ｂ：数学可能考得不太🟦。

****** 答案

理想

* 注释

** 2

*** 比一比

**** 做一做

***** 词语

****** 1

通过

****** 2
:PROPERTIES:
:ID: d806c376-7e9c-468f-ade7-c16db7254264
:END:

经过

***** 题

****** 1
:PROPERTIES:
:ID: 2161716d-e3c4-465b-b790-7138946a12a0
:END:

******* 课文

🟦调查我们发现，客人住宾馆最关心的是干净不干净。

******** 笔记
:PROPERTIES:
:CREATED: [2022-12-24 15:51:00 -05]
:END:

调查 🟦 diao4cha2 🟦 v. to investigate, to survey ;
宾馆 🟦 bin1guan3 🟦 n. hotel ;
干净 🟦 gan1jing4 🟦 adj. clean ;
客人 🟦 ke4ren2 🟦 n. customer, client ;


******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: ab0b2d02-aae1-4317-9ad1-e1209f3c10ca
:END:

******* 课文

这是保修卡，遇到什么问题，您可以🟦上面的电话联系我们。

******* 答案

******** 1

1

******** 2

0

****** 3
:PROPERTIES:
:ID: da15110e-fdfe-47e8-92e7-8f305bf4944e
:END:

******* 课文

我不了解这件事情的🟦，你问问其他人吧。

******* 答案

******** 1

0

******** 2

1

****** 4
:PROPERTIES:
:ID: dc1bde4d-7d52-48c8-ac2f-1e620d1762f8
:END:

******* 课文

🟦这段时间的学习，他的汉语水平提高了不少。

******* 答案

******** 1

1

******** 2

1

****** 5
:PROPERTIES:
:ID: 22e7fbcb-4117-410e-bbe4-e23ceeb4d41e
:END:

******* 课文

有些人🟦节食的方法来减肥，虽然有效，但是时间长了对身体没有好处。

******* 答案

******** 1

1

******** 2

0

* 扩展

** 做一做
:PROPERTIES:
:ID: 90a2956a-e1c1-4236-b65e-be92e5a8fb38
:END:

*** 选择

**** 1

如果

**** 2

结果

**** 3

效果

*** 题

**** 1

***** 内容填空

做事情，不要一开始就考虑过多：会不会很难，🟦会怎么样……这些其实都不重要，关键是要勇孜地去做，只有去做，一切才有可能。

***** 答案

****** 1

结果

**** 2

***** 内容填空

春天天气时冷时热，容易感冒，医生提醒人们要注意室内空气质量，早上起床后应该打开窗户换换空气。🟦感冒了，要及时去医院。

***** 答案

****** 1

如果

**** 3

***** 内容填空

水果减肥法是措通过每天只吃水果而不再吃别的东西来减肥的一种方法。这样减肥虽然有一定的🟦，却很不健康。

***** 答案

****** 1

效果

* 课文
** 1
*** 转录
王静：怎么又买了这么多饼干和巧克力？难道你不减肥了？
孙月：减了一个月都没瘦下来，我实在没有信心了。
王静：如果你想减肥，就得少吃东西，而且要多运动。
孙月：我就是这么做的，但这一个月下来，我只轻了一公斤。
王静：一个月太短了。要想减肥成功，只能坚持，才会慢慢有效果。
孙月：我本来已经打算放弃了，但是你刚才的话让我改变了主意。这些饼干和巧克力送给你了。
** 2
*** 转录
李进：你网球打得真好，还得过那么多国际大奖！每次看你比赛，感觉你轻轻松松就赢了。
张远：哪里啊！那是你没看到我辛苦练习的一面，没有人随随便便就能成功的。
李进：我从小也对网球感兴趣，但是到现在还是打得不怎么样。
张远：你知道吗？不管春夏秋冬，我练球从来没有休息过一天。
李进：真是不容易响！看来我只看到了你成功时获得的鲜花，却没注意到你成功前流下的汗水。
张远：任何成功都要通过努力才能得到。只要你坚持练习，我相信你也会越打越好的。
** 3
*** 转录
小林：你还记得王红吗？我在报纸上看到一篇关于她的新闻，她现在已经是一个有名的作家了。
小李：听说她毕业后放弃了律师的工作，开始专门写小说，没想到她竟然成功了。
小林：当时她的父母和亲都都不支持她，可是她坚持自己的选择，现在终于向所有人证明了她的选择是正确的。
小李：看来为了自已的理想，放弃一些东西也是值得的。
小林：一个人只有两只手，不可能得到所有想要的东西，所以有时候放弃是一种聪明的选择。
小李：是啊，只有学会放弃，才能把自己的能力用到最该做的事情上，最后获得成功。
** 4
*** 转录
如果你想做什么事情，那就勇敢地去做，不要担心结果，不要考虑会不会失败。要是太看重结果，失败就会给人们带来很多烦恼。我们应该把注意力放在做事情的过程上，这样你会在做的过程中发现解决问题的快乐，这是其他任何东西都给不了的。即使最后失败了也没有关系，因为至少你已经努力过，而且我们还可以从失败中总结出有用的经验，有了这些积累，成功自然离我们越来越近。
** 5
*** 转录
每一个人都希望成功，可是很多时侯，在成功之前会遇到很多困难。有些人遇到困难就放弃，而有些人遇到困难却想办法解决它。对困难的态度不同，结果也是不一样的。爱迪生就是在找了上千种材料后才找到了能点亮电灯的材料。取得成功的人往往都经历过许多失败，他们和普通人的区别就是他们都坚持了下来。所以就算只有1％的希望，我们也要做出100％的努力。困难只是暂时的，“阳光总在风雨后”，只有我们勇敢地面对困难，才能有希望取得成功。
