* 听力

** 1

*** 1

**** transcript

《梦溪笔谈》是中国北宋大科学家沈括的传世著作。沈括在晚年用笔记文学体裁写成《梦溪笔谈》，内容涉及天文、数学、物理、化学、地学、生物以及冶金、机械、造纸技术等各个方面，是中国科学史上的重要著作。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 14:09:34 -05]
:END:

The Mengxi Pensio is a biographical work by Shen Kuo, a scientist of the Northern Song Dynasty. In his later years, Shen Kuo wrote the book in the genre of notebook literature, which covers various aspects of astronomy, mathematics, physics and chemistry, geology, biology, as well as metallurgy, machinery, paper-making technology, etc. It is an important work in the history of Chinese science.

***** TODO Read this book
:PROPERTIES:
:CREATED: [2022-08-24 10:04:04 -05]
:END:
:LOGBOOK:
- State "TODO"       from              [2022-08-24 Wed 10:04]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

“家庭暴力”有广义、狭义之分。有人认为，广义的家庭暴力是指对家庭成员进行肉体上以及精神上的折磨、伤害和虐待的行为；狭义的家庭暴力指丈夫对妻子进行肉体上的摧残、虐待和伤害。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 14:15:23 -05]
:END:

"Domestic violence" has a broad sense and a lean sense. Some people believe that domestic violence in the broad sense refers to the physical as well as mental torture, injury and abuse of family members: domestic violence in the narrow sense refers to the physical destruction, abuse and injury of the wife by the husband.

****** QUESTION Isn't this dialogue narrowed to the fact thawt only male do domestic violence?
:PROPERTIES:
:CREATED: [2022-08-20 14:19:15 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-20 Sat 14:19]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

朋友认为自己病了，而且病得很重。医生说没什么大碍，家人也说心情舒畅就会好的。可他不信，认为医生和家人联合起来骗他。他的疑心越来越重，面容越来越憔悴，直到有一天真的生了一场大病。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 17:27:33 -05]
:END:

My friend thought she was sick and very sick. The doctor said there was nothing wrong with it, and his family said he would be fine if he was in a good mood. But he didn't believe it, thinking that the doctor and his family had joined forces to lie to him. His suspicion grew, and his face became more and more haggard, until one day he really had a not-so-sickness.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

张衡断定地球是圆的，月亮是借太阳的照射才反射出光来。他还认为天好像鸡蛋壳，包在地的外面，地好像鸡蛋黄，在天的中间。这种学说虽然不完全精确，但在1800多年前，能有这种见解，也够令人钦佩的了。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 17:32:00 -05]
:END:

Zhang Heng concluded that the earth was round and that the moon reflected light only by the light of Tai Chen. He also believed that the sky was like a marble egg wrapped around the outside of the earth, and the earth was like an egg yolk in the middle of the sky. Although this theory is not entirely accurate, it is admirable that it was made more than 1800 years ago.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

“饥饿营销”始终贯穿着“品牌”这个因素。其运作必须依靠产品强势的品牌号召力，也正由于有“品牌”这个因素，饥饿营销是一把双刃剑。用好了，可以使原来就强势的品牌产生更大的附加值；用不好，则会对其品牌造成伤害。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 17:36:11 -05]
:END:

"Hunger marketing" has always been throughout the "brand" factor. Its operation must rely on the strong brand appeal of the product, but also because of the "brand" factor, hunger marketing is a double-edged sword. With a good, can make the original strong brand to produce greater added value; with a bad, it will cause harm to its brand.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



