* 听力

** 第二部分
:PROPERTIES:
:ID: 56f0b0e0-0101-42a7-86a8-e7476f436c27
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：您认为作为裁判，最重要的是什么？
男：对一切都要公平公正。要公平地看待每一个运动员，一切都要以比赛成绩为准，这是体育赛事成功举办的基石。只有在公平的基础上竞争才有意义。
女：您认为体育比赛中最激动人心的时刻是什么时候？
男：对运动员来说，冲过终点线的那一刻，跳过横杆的那一刻，发现自己长久以来的努力得到回报，都是最激动人心的时刻；对观众来说，看到运动员奋力拼搏，感受到了运动之美和生命的活力，就是最激动人心的时刻；对裁判员来说，认真负责地做好本职工作，确保赛事有秩序地进行，让每个运动员能得到应有的肯定，直到运动会完美结束，就是他们最激动的时刻。
女：您认为一个优秀的运动员应该具有哪些品质？
男：首要的是敢于拼搏，要不断挑战自我，突破自我，向“更高，更快，更强”努力。第二要懂得尊重，要尊重每一位运动员、每一位工作人员、每一位观众，这样才能通过体育活动促进人与人、国与国的互信互爱。第三要吃苦耐劳，百折不挠。一个缺少坚韧品格的人是不可能取得好成绩的，在体育上是这样，其他领域也是这样。第四要乐于奉献，懂得感恩，体育从来不是一个个人的世界，对于他人的帮助要心存感激，还要学会无私地为他人奉献，这才是真正的体育精神。
女：哦，有道理。还有一个问题，您认为每年举行运动会，意义何在？
男：运动会的举办是为了给热爱运动的同学们一个展示自我的机会，更是为了带动全校师生强身健体，通过参与赛事使体育成为生活中的一环，养成终身健身的好习惯。

**** 音频

c0cadc41-b867-40a9-82fc-433aed533330.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: ef027ffd-34d9-4f09-9374-fcb1386d7e9c
:END:

***** 问题

男的认为作为裁判，最重要的是什么？

****** 音频

6339fadd-4786-4f87-9b2c-f689579a2298.mp3

***** 选择

****** A

要有丰富的体育知识

****** B

要努力宣传公平竞争

****** C

要平等地对待每一个人

****** D

要公允地对待赛场纠纷

***** 答案

C

**** 7
:PROPERTIES:
:ID: bcc812a0-d1de-4a71-a127-964875767c59
:END:

***** 问题

关于最激动人心的时刻，下列哪项正确？

****** 音频

1abe0165-319f-4e21-87a8-57f74c7ee918.mp3

***** 选择

****** A

运动员开始比赛的时刻

****** B

漂亮运动员出场的时刻

****** C

裁判受到大家肯定的时刻

****** D

观众看到精彩赛事的时刻

***** 答案

D

**** 8
:PROPERTIES:
:ID: 8c6cdd47-c151-4360-81d3-60dfd55f5240
:END:

***** 问题

关于优秀运动员应有的品格，下列哪项正确？

****** 音频

dc272b18-ffb1-4608-9d34-82b8ba6da759.mp3

***** 选择

****** A

要舍得拼和

****** B

要克服自身弱点

****** C

要不断地超趁自己

****** D

要端正对他人的态度

***** 答案

C

**** 9
:PROPERTIES:
:ID: b529eebf-6b33-40a7-9021-0478e9ab333d
:END:

***** 问题

关于每年举行运动会，男的有什么看法？

****** 音频

78c9702f-16b2-4e66-a208-5d88747efb0d.mp3

***** 选择

****** A

运动会可以进人大家的生活

****** B

希望带动师生重视日常锻炼

****** C

可以强化师生保重身体的意识

****** D

给身体好的人一个炫耀的机会

***** 答案

B

**** 10
:PROPERTIES:
:ID: d9e3bb50-2750-4724-bb01-6a81a7b1bcab
:END:

***** 问题

根据对话，可以知道什么？

****** 音频

31795c9f-b8df-4409-a530-d64ec3ee66a5.mp3

***** 选择

****** A

女的采访的是学校的运动会

****** B

运动会每次都邀请专业运动员

****** C

男的在运动会中取得了好成绩

****** D

运动会让女的养成终身健身的习惯

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

沈括是第一位笔记文学作者

***** B

沈括是《梦溪笔谈》的出版商

***** C

《梦溪笔谈》的学术价值非常高

***** D

北宋是中国科学技术发展的黄金时期

**** 段话

《梦溪笔谈》是中国北宋大科学家沈括的传世著作。沈括在晚年用笔记文学体裁写成《梦溪笔谈》，内容涉及天文、数学、物理、化学、地学、生物以及冶金、机械、造纸技术等各个方面，是中国科学史上的重要著作。

***** 音频

e6ae67a5-b9d7-4c3d-a0bd-fe4299d2aeac.mp3

**** 答案

C

*** 2

**** 选择

***** A

“广义“狭义“基本没区别

***** B

广义的家庭暴力包括精神伤害

***** C

家庭中丈夫虐待妻子现象广泛存在

***** D

家庭暴力只发生在丈夫与妻子之间

**** 段话

“家庭暴力”有广义、狭义之分。有人认为，广义的家庭暴力是指对家庭成员进行肉体上以及精神上的折磨、伤害和虐待的行为；狭义的家庭暴力指丈夫对妻子进行肉体上的摧残、虐待和伤害。

***** 音频

dc8732f2-f3c0-4eea-9b2f-68af8f486fbb.mp3

**** 答案

B

*** 3

**** 选择

***** A

医生给病人胡乱诊断了一通

***** B

狠心的家人不承认朋友病了

***** C

朋友心思太重，终于病倒了

***** D

医生骗病人，也是出于好意

**** 段话

朋友认为自己病了，而且病得很重。医生说没什么大碍，家人也说心情舒畅就会好的。可他不信，认为医生和家人联合起来骗他。他的疑心越来越重，面容越来越憔悴，直到有一天真的生了一场大病。

***** 音频

b6462ebe-90f1-465d-9e72-475227c05826.mp3

**** 答案

C

*** 4

**** 选择

***** A

张衡认为月亮是发光的

***** B

在张衡眼中地球像鸡虾

***** C

张衡的天文学说很精确

***** D

张衡是1800多年前的人

**** 段话

张衡断定地球是圆的，月亮是借太阳的照射才反射出光来。他还认为天好像鸡蛋壳，包在地的外面，地好像鸡蛋黄，在天的中间。这种学说虽然不完全精确，但在 1800 多年前，能有这种见解，也够令人钦佩的了。

***** 音频

8a8055e7-95a4-4ad4-acb9-e99e23a3389c.mp3

**** 答案

D

*** 5

**** 选择

***** A

“饥饿营销“有弊有利

***** B

“饥饿营销“不可急于求成

***** C

“饥饿营销“促使老产品更新换代

***** D

为新产品树立品牌应使用“饥饿营销“

**** 段话

“饥饿营销”始终贯穿着“品牌”这个因素。其运作必须依靠产品强势的品牌号召力，也正由于有“品牌”这个因素，饥饿营销是一把双刃剑。用好了，可以使原来就强势的品牌产生更大的附加值；用不好，则会对其品牌造成伤害。

***** 音频

fc58d1d8-d465-4b78-af95-b1a660be1fbe.mp3

**** 答案

A

** 第三部分

*** 11-13

**** 课文

游泳运动总是在一届又一届的赛事中超越以前的纪录，而田径运动中许多项目的纪录却长时间停滞。过去20年来，在16届游泳赛事中各项纪录共被打破275次，而在24届田径赛事中各项纪录仅被打破166次，其中38次是撑杆跳创造的新纪录。在游泳运动中，任何一项创造于2008年以前的世界纪录都没能保持到现在，而在田径运动中，还有许多纪录是20世纪90年代之前创下的。

导致这种不同的原因之一，是游泳作为运动的历史更短，在生物力学和技术等方面，还有许多需要研究和改进之处。其次，与游泳相比，跑、跳和投掷是人类遗传密码里带有的动作，这导致田径运动领先了游泳很多年。

***** 音频

87ac93af-0be9-4725-97f7-578e0eb0194c.mp3

**** 题目

***** 11

****** 选择

******* A

赛事最为频繁

******* B

成绩提高幅度有限

******* C

过去的20年举行了16次比赛

******* D

2008年以前的世界纪录都被打破了

****** 问题

游泳运动发展情况怎样？

******* 音频

4e0a5452-c62d-4457-a402-6ade740da79a.mp3

****** 答案

D

***** 12

****** 选择

******* A

和游泳比,赛事少得多

******* B

刷新纪录是件很困难的事

******* C

运动员水平基本没有提高

******* D

撑竿跳连续38年创造了新纪录

****** 问题

田径运动发展情况怎样？

******* 音频

85821d14-9822-4a9a-88be-713ec67a2818.mp3

****** 答案

B

***** 13

****** 选择

******* A

游泳比田径运动更加成熟

******* B

田径的发展是循序渐进的

******* C

田径运动中很多动作有遗传因素

******* D

游泳纪录的诞生是科学家的功劳

****** 问题

根据这段话，可以知道什么？

******* 音频

027a2f65-2f5d-4eaf-b63f-94a92a8bb4d9.mp3

****** 答案

C

*** 14-17

**** 课文

英国国民保健制度(NHS)发表在官网上的忠告称，“久坐对健康有害，不管你进行多少运动都无济于事。”“越来越多的证据”显示，肥胖、2 型糖尿病、某些种类的癌症以及早逝均与久坐有关。NHS 建议每坐 30 分钟就起来活动一下。它援引健康专家的话说：“必须打断坐着的状态。”“做些需要站起来完成的事，比如冲咖啡和聊天，甚至是写封信——海明威就是站着写小说的。”

然而，英国一项新的研究结果证实：只要定期活动，坐着并不比站着对健康的危害更大。

研究人员对 5000 多人开展了为期 16 年的跟踪调查，他们的发现发表在英国《国际流行病学杂志》季刊上。研究结果称：不管是坐着还是站着，任何静止不动、能量消耗低的姿势或许对健康都是有害的。研究发现，在办公、休闲或看电视期间采取坐姿的调查对象并未出现死亡风险增加的情况。

这一研究结果使人对坐站两用工作台的益处产生了怀疑。目前用人单位越来越多地向员工提供这种工作台，以营造更健康的办公环境。

***** 音频

5a1767d9-6925-40e5-b853-6737a050d8a8.mp3

**** 题目

***** 14

****** 选择

******* A

父坐不利于健康

******* B

癌症多少都与久坐有关

******* C

爷坐是英年早逝的重要原因

******* D

大剂量运动可降低久坐的危害

****** 问题

关于久坐与健康的关系，英国 NHS 官网上的观点是怎样的？

******* 音频

d9d4af4a-4405-4282-8982-921dbafd7186.mp3

****** 答案

A

***** 15

****** 选择

******* A

每天要坚持运动

******* B

每次活动30分钟

******* C

隔半小时活动一下

******* D

站着写小说、写信

****** 问题

英国 NHS 的建议是什么？

******* 音频

9e1bc477-8c8b-43cb-b393-0dd79d1cf696.mp3

****** 答案

C

***** 16

****** 选择

******* A

坐着工作比站着工作健康

******* B

爷坐看电视,死亡风险会增加

******* C

爷坐不伤害健康,但对姿势有要求

******* D

定期活动的话,坐着站着没什么区别

****** 问题

英国一项新的研究结果是怎样的？

******* 音频

f53fdefb-375f-4447-b5e5-ca2420971f52.mp3

****** 答案

D

***** 17

****** 选择

******* A

很多英国人选择站着办公

******* B

英国有5000多名研究人员

******* C

用人单位越来越怕员工生病

******* D

《国际流行病学杂志》是季刊

****** 问题

根据这段话，可以知道什么？

******* 音频

274332be-42ba-49b1-bc0c-f08630415038.mp3

****** 答案

D

