* Text

** title

运动的学问

** content

记者：王老师欢迎您到我们节目来做客。今天来的都是您的忠实观众，大家特别愿意和您这样的大专家进行交流。
王老师：“专家”不敢当，有这样的机会，我也很高兴。
记者：那天采访您，在公园支走廊那儿，您和您徒弟是练气功还是练太极剑呢？
王老师：哦，不是徒弟，是气功协会的气功爱好者。
记者：你们的气功不是那种力量一爆发，能瞬间把好几块砖就给劈开的啊？
王老师：那只是气功的一种。气功还是中国独特的健身方法之一，可以增强体质，促进慢性病康复，还可以辅助治疗某些疾病。
记者：看来我是误解气功了。最近有个调查，广大群众的健身意识在逐年提升。奸计于健康，您能对我们说点儿什么吗？
王老师：健康的新概念不仅是不生病，还包括心理健康和社会交往方面的能力，甚至有人提出健康五要素，包括身体、情绪、智力、精神和社交，这五个方面共同构成健康的完美状态。有句名言：生命在于运动，其实健康也在于运动。当然要达到预期效果，怎样运动很重要。
记者：那您就着重跟我们谈谈运动的学问吧。
王老师：要健康，首要问题是勤于运用大脑，人的大脑不用也会生锈。大家知道，人脑左半球主管抽象思维，右半球主管形象思维，二者有分工有联系。左右脑交替使用，思维常可以放射出新的火花。著名科学家钱学森的夫人是音乐家，钱学森的很多重要科学理论不是端端正正地坐在桌子前面想出来的，而是听过音乐之后冒出来的。科学运用左右脑，工作的高效和防止脑衰就成为了可能。大脑潜力巨大，它是人体衰退最慢的器官。一些养生著作中指出，人用脑越勤，大脑各神经细胞之间的联系越多，形成的条件反射也越多。
记者：大脑就像我们身体的指挥中心，大脑不健康，人就谈不上健康。
王老师：对。其次呢，运动贵在坚持。懒惰是人天生的弱点，所以不要迁就自己，要以坚定的意志，坚韧的精神克服惰性，下狠心咬牙坚持，绝不能半途而废。
记者：王老师，您怎么好像在说我呢？我就不想虐待自己，所以很难坚持。
王老师：怎么会是虐待呢？你以后联系我，我带你锻炼。咱们有计划，有落实。运动健身归根到底是自己的事，胡乱对付其实是在骗自己，坚持运动也是培养人的意志力、完善人格的过程。
记者：看来运动真不是小事，还间接体现着我们的品行呢。
王老师：另外，冬季健身好外汇很多，可以提高人的御寒能力；冬天阳光中的紫外线对人体有消毒作用，还能促进对钙的吸收；冬天空气中二氧化碳浓度比夏天低，所以冬天运动对身体更为有利；运动还可以使人心情舒畅。许多保健食品都宣扬能够促进健康，其实运动才是维护健康最好的方法。
记者：运动对皮肤是不是也有好处？
王老师：运动能令全身排汗，毛孔内的垃圾及多余油脂会社皮排走，皮肤自然会更好。
记者：运动是不是也要讲究科学？
王老师：当炙磁。运动健身要循序渐进，不要急于求成；不适合自己身体状况的剧烈运动或大幅度动人在尽量别勉强。
记者：运动之后，我们常常觉得又渴又锇，运动和饮食之间有什么讲究吗？
王老师：锻炼后是肌肉细胞的“进食时间”，它们渴望得到足够的蛋白质、水和维生素。运动后的两小时，是补充营养的最佳时机。
记者：王老师，您真不愧是这方面的专家，以后要是能定期和您做些交流就好了。
王老师：这是我的联系方式，以后我们可以多联络。希望大家回支以后坚持锻炼，多多保重。


*** QUESTION “智力”和“知识”有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-11 Thu 15:41]
:END:

*** QUESTION “弱点”和“缺点”有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-11 Thu 15:42]
:END:

*** QUESTION “夫人” 和”妻子“ 有什么区别？
:LOGBOOK:
- State "QUESTION"   from              [2022-08-11 Thu 15:43]
:END:



** footnotes

① 
① 
② 
③ 
④ 

** source



** new words





