:PROPERTIES:
:CREATED: [2022-04-14 11:07:55 -05]
:END:

* Listening
:PROPERTIES:
:CREATED: [2022-04-14 11:07:56 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-14 11:08:06 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-14 11:08:07 -05]
:ID: 9e31ba1b-bfba-439f-bb82-3f505d9da7bd
:END:

你今天起得真早。
pi: nǐ jīntiān qǐ de zhēn zǎo
en: you are up early today
es: hoy estas despierto temprano

answer

0

*** 2
:PROPERTIES:
:CREATED: [2022-04-14 11:11:00 -05]
:ID: 91383179-b709-4ee4-8953-8c1d8b646a2a
:END:

再来点儿米饭吧，你吃得太少了。
pi: zài lái diǎnr mǐfàn ba, nǐ chī de tài shǎo le
en: have some more rice, you've eaten too little
es: ten más arroz, has comido muy poco

answer

0

*** 3
:PROPERTIES:
:CREATED: [2022-04-14 11:12:22 -05]
:ID: 165d9c27-4358-4901-b48d-f9ee21c034a2
:END:

下雪了，今天真冷。
pi: xià xuě le, jīntiān zhēn lěng
en: it's snowing and it's really cold today
es: está nevando y hace mucho frío hoy

answer

1

*** 4
:PROPERTIES:
:CREATED: [2022-04-14 11:13:15 -05]
:ID: 8c2d5f07-459d-4ba6-a050-dd9b61bec514
:END:

我觉得很热，今天穿得太多了。
pi: wǒ juéde hěn rè, jīntiān chuān de tài duō le
en: I feel hot and overdressed today
es: me siento acalorada y demasiado vestida para el día

answer

1

*** 5
:PROPERTIES:
:CREATED: [2022-04-14 11:15:57 -05]
:ID: 11690241-64ff-49bc-8d16-a2729ace5de9
:END:

这件衣服比弟弟送给我的那件漂亮。
pi: zhè jiàn yīfu bǐ dìdi sòng gěi wǒ de nà jiàn piàoliang
en: this dress is prettier than the one my brother gave me
es: este vestido es más bonito que el que me regaló mi hermano

answer

0

** 2
:PROPERTIES:
:CREATED: [2022-04-14 11:18:34 -05]
:END:

*** 6
:PROPERTIES:
:CREATED: [2022-04-14 11:18:36 -05]
:ID: 6f9e3fc7-6144-490e-a566-a71647a69d94
:END:

男：我今天早上七点就起床了。
pi: wǒ jīntiān zǎoshang qī diǎn jiù qǐ chuǎng le
en: I got up at seven this morning
es: me he levantado a las siete de la mañana

女：你比我早起一个小时呢。
pi: nǐ bǐ wǒ zǎo qǐ yí gè xiǎo shí ne
en: you got up an hour earlier than me
es: te has levantado una hora antes que yo

answer

f

*** 7
:PROPERTIES:
:CREATED: [2022-04-14 11:25:20 -05]
:ID: 10d499a9-c8bd-4e99-bfc9-e938c744dd7d
:END:

女：你做饭做得怎么样？
pi: nǐ zuò fàn zuò de zěnmeyàng?
en: how well do you cook?
es: ¿qué tan bien cocinas?

男：不怎么样，我妻子比我做得好。
pi: bù zěnmeyàng, wǒ qīzi bǐ wǒ zuò de hǎo
en: not great, my wife cooks better than me
es: no muy bien, mi mujer cocina mejor que yo

answer

b

*** 8
:PROPERTIES:
:CREATED: [2022-04-14 11:27:55 -05]
:ID: 6236d498-89ab-476a-bbb8-dd53f0462276
:END:

男：今天天气真冷了。
pi: jīntiān tiānqì zhēn lěng le
en: it's really cold today
es: hoy hace mucho frío

女：是啊，我觉得晚上可能下雪。
pi: shì a, wǒ juéde wǎnshàng kěnéng xiàxuě
en: yeah, I think it might snow at night
es: sí, creo que podría nevar por la noche

answer

a

*** 9
:PROPERTIES:
:CREATED: [2022-04-14 11:30:49 -05]
:ID: 2989899b-648f-4285-8ec2-888f1740a3be
:END:

女：大卫很喜欢跑步。
pi: dàwèi de xǐhuan pǎobù
en: David loves to run
es: a David le encanta correr

男：是啊，他跑得非常快。
pi: shì a, tā pǎo de fēicháng kuài
en: yeah, he's a very fast runner
es: sí, es un corredor muy rápido

answer

e

*** 10
:PROPERTIES:
:CREATED: [2022-04-14 11:34:40 -05]
:ID: 955a206f-0476-4b44-8b3f-69ba4860837e
:END:

男：你今天穿得真漂亮。
pi: nǐ jīntiān chuān de zhēng piàoliang
en: you're dressed so nicely today
es: hoy estás muy bien vestida

女：谢谢，今天是我的生日。
pi: xièxie, jīntiān shì wǒ de shēngrì
en: thank you, it's my birthday
es: gracias, es mi cumpleaños

answer

c
** 3
:PROPERTIES:
:CREATED: [2022-04-14 11:37:26 -05]
:END:

*** 11
:PROPERTIES:
:CREATED: [2022-04-14 11:45:07 -05]
:ID: 20278dec-1ed3-4afa-ab8d-b9be333c17b6
:END:

男：你每天几点睡觉？
pi: nǐ měitiān jǐ diǎn shuìjiào?
en: what time do you go to beed every day?
es: ¿a qué hora duermes todos los días?

女：我每天十点就睡觉了，早睡早起身体好。
pi: wǒ měitiān shí diǎn jiù shuìjiào le, zǎo shuì zǎo qǐ shēntǐ hǎo
en: I go to bed at 10 o'clock every day, sleeping early and waking up early is healthy
es: todos los dias duermo a las 10, dormir y despertarse temprano es bueno para la salud

问： 女的为什么睡得很早？
pi: nǚ de wèi shénme shuì de hěn zǎo?
en: why does the woman sleep very early?
es: ¿por qué la mujer se duerme muy temprano?

answer

c

*** 12
:PROPERTIES:
:CREATED: [2022-04-14 11:45:16 -05]
:ID: 34f3d780-daf6-4985-8b4f-64e146ba787c
:END:

男：明天天气怎么样？
pi: míngtiān tiānqì zěnmeyàng?
en: how is the weather tomorrow?
es: ¿como estará el clima mañana?

女：零下十度， 比今天冷多了，你要多穿件儿衣服。
pi: líng xià shí dù, bǐ jīntiān lěng duō le, nǐ yào duō chuān jiànr yīfu
en: -10 degrees, much colder than today, you need to wear more clothes
es: hay 10 grados bajo cero, mucho más frío que hoy, así que tienes que ponerte más ropa

问：明天冷吗？
pi: míngtiān lěng ma?
en: is it cold tomorrow?
es: ¿hará frío mañana?

answer

a

*** 13
:PROPERTIES:
:CREATED: [2022-04-14 11:52:15 -05]
:ID: dde2b5ed-cf89-4678-b0ae-1763c5027a20
:END:

女：你们家谁做饭做得好？
pi: nǐ men jiā shéi zuò fàn zuò de hǎo?
en: who cooks well in your family?
es: ¿quién cocina bien en tu familia?

男：我做得还可以，我妻子做得比我好吃。
pi: wǒ zuò de hái kěyǐ, wǒ qīzi zuò de bǐ wǒ hǎochī
en: I cook okay, my wife cooks better than I do
es: yo cocino bien, mi mujer cocina mejor que yo

问：谁做饭做得最好？
pi: shéi zuò fàn zuò de zuì hǎo?
en: who cooks best?
es: ¿quién cocina mejor?

answer

b

*** 14
:PROPERTIES:
:CREATED: [2022-04-14 11:56:57 -05]
:ID: 09f94db9-d618-4f1c-b1ee-77eecb1d0937
:END:

男：你这几天在忙什么呢？
pi: nǐ zhè jǐ tiān zài máng shènme ne?
en: what are you working on these days?
es: ¿en qué estás trabajando estos días?

女：我弟弟让我帮他找个房子，他家离公司有点儿远。
pi: wǒ dìdi ràng wǒ bāng tā zhǎo ge fángzi, tā jiā lí gōngsī yǒu diǎnr yuǎn
en: my brother asked me to help him find a house, his house is a bit far from the company
es: mi hermano me pidió que le ayudara a encontrar una casa, su casa está un poco lejos de la oficina

问：她弟弟为什么要找个房子？
pi: tā dìdi wèi shénme yào zhǎo ge fángzi?
en: why does her brother need a house?
es: ¿por qué necesita su hermano una casa?

answer

a

*** 15
:PROPERTIES:
:CREATED: [2022-04-14 12:05:08 -05]
:ID: 1027235f-d25c-4a8b-828f-6f4538bbfb7b
:END:

男：儿子这次考试考得怎么样？
pi: èrzi zhè cì kǎo shì kǎo de zěnmeyàng?
en: how did my son do on this exam?
es: ¿cómo le fue a mi hijo en este examen?

女：还不错，比上次好一些。
pi: hái bùcuò, bǐ shàng cì hǎo yī xiē
en: not bad, better than last time
es: no está mal, mejor que la última vez

问：儿子考得怎么样？
pi: érzi kǎo de zěnmeyàng?
en: how did the son do on the test?
es: ¿como le fue al hijo en en el examen?

answer

c

* Reading
:PROPERTIES:
:CREATED: [2022-04-14 12:31:24 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-14 12:31:26 -05]
:END:

*** 16
:PROPERTIES:
:CREATED: [2022-04-14 12:31:33 -05]
:END:

别离电脑太近，对眼睛不好。
pi: bié lí diànnǎo tài jìn, duì yǎnjing bù hǎo
en: don't get too close to the computer, it's not good for your eyes
es: no te acerques demasiado al ordenador, no es tan bueno para tus ojos

answer

e

*** 17
:PROPERTIES:
:CREATED: [2022-04-14 12:32:47 -05]
:END:

妻子这几天很忙，所以我洗衣服。
pi: qīzi zhè jǐ tiān hěn máng, suǒyǐ wǒ xǐ yīfu
en: my wife is very busy these days, so I do the laundtry
es: mi mujer está muy ocupada estos días, así que yo lavo la ropa

answer

c

*** 18
:PROPERTIES:
:CREATED: [2022-04-14 12:33:02 -05]
:END:

今天零下十度，比昨天冷多了。你多穿点儿衣服吧。
pi: jīntiān língxià shí dù, bǐ zuǒtiān lěng duō le. nǐ duō chuān diǎnr yīfu ba
en: it's 10 degree below zero today, much colder than yesterday. You should wear more clothes
es: hoy hace 10 grados bajo cero, mucho más frío que ayer. Deberías llevar más ropa

answer

a

*** 19
:PROPERTIES:
:CREATED: [2022-04-14 12:33:22 -05]
:END:

你唱歌唱得太好了，再来一个吧。
pi: nǐ chànggē chàng de tài hǎo le, zài lái yí ge ba
en: you sing so well, let's have another one
es: cantas muy bien, tomemos otra

answer

b

*** 20
:PROPERTIES:
:CREATED: [2022-04-14 12:33:41 -05]
:END:

今天比昨天起得早，所以我走路去上班。
pi: jīntiān bǐ zuǒtiān qǐ de zǎo, suǒyǐ wǒ zǒu lù qù shàng bān
en: I got up eaarlier today than yesterday, so I walked to work
es: hoy me he levantado más temprano que ayer, así que he ido andando al trabajo

answer

f

** 2
:PROPERTIES:
:CREATED: [2022-04-14 12:33:57 -05]
:ID: 103d02e1-123e-4b04-9aa5-d34f18597a03
:END:

穿
进
近
让
贵
希望

*** 21
:PROPERTIES:
:CREATED: [2022-04-14 12:34:03 -05]
:END:

他的家比我的家离公司//一点儿。
近
pi: tā de jiā bǐ wǒ de jiā lí gōngsī (jìn) yìdiǎnr
en: his home is a little closer to the office than mine
es: su casa está un poco más cerca de la oficina que la mía

answer

c

*** 22
:PROPERTIES:
:CREATED: [2022-04-14 12:35:07 -05]
:END:

我//找一个比现再钱多一点儿的工作。
希望
pi: wǒ (xīwàng) zhǎo yí ge bǐ xiànzài qián duō yìdiǎnr de gōngzuò
en: I hope to find a job with a little more money than I have now
es: me gustaría encontrar un trabajo con un poco más de dinero del que tengo ahora

answer

f

*** 23
:PROPERTIES:
:CREATED: [2022-04-14 12:34:39 -05]
:END:

外面太冷了，快请//房间里来吧。
进
pi: wàimian tài lěng le, kuài qǐng jìn fángjiān li lái ba
en: it's too cold outside, please come into the room
es: hace demasiado frío fuera, pro favor, entra a la habitación

answer

b

*** 24
:PROPERTIES:
:CREATED: [2022-04-14 12:36:29 -05]
:END:

明天有一个新年晚会，我想//得漂亮一点儿。
穿
pi: míngtiān yǒu yí ge xīnnián wǎnhuì, wǒ xiǎng (chuān) de piàoliang yìdiǎnr
en: there's a New Year's party tomorrow and I want to dress up
es: mañana hay una fiesta de año nuevo y quiero vestirme bien

answer

a

*** 25
:PROPERTIES:
:CREATED: [2022-04-14 12:36:00 -05]
:END:

大卫生病了，他//我告诉王老师。
让
pi: dàwèi shēng bìng le, tā ràng wǒ gàosu wáng lǎoshī
en: David is sick, and he asked me to tell Mr. Wang
es: David está enfermo y me pidió que le dijera al Sr. Wang

answer

d

** 3
:PROPERTIES:
:CREATED: [2022-04-14 12:36:47 -05]
:END:

*** 26
:PROPERTIES:
:CREATED: [2022-04-14 12:37:49 -05]
:END:

今年没有去年冷，北京到现在还没下雪呢。去年这个时候已经下雪了。
pi: jīnnián méiyǒu qùnián lěng, běijīng dào xiànzài hái méi xiàxuě ne. qùnián zhège shíhou yǐjīng xià xuě le.
en: it's not as cold as last year, and it hasn't snowed in Beijing yet. This time last yaer it was already snowing
es: este año no hace tanto frío como el año pasado, y hasta ahora no ha nevado en Pekín. el año pasado ya nevaba por estas fechas

北京今年比去年冷。
pi: běijīng jīnnián bǐ qùnián lěng
en: In Beijing, this year is colder than last year
es: En Pekín, este año hace más frio que el año pasado

answer

0

*** 27
:PROPERTIES:
:CREATED: [2022-04-14 12:41:28 -05]
:END:

你上个月没怎么运动吧？明天和我一起去踢足球怎么样？打篮球也可以。
pi: nǐ shàng ge yuè méi zěnme yùndòng ba? míngtiān hé wǒ yìqǐ qù tī zúqiú zěnmeyàng? dǎ lánqiú yě kěyǐ
en: you haven't exercises much in the last month, have you? how about going to play soccer with me tomorrow? playing basketball is fine too
es: no has hecho mucho ejercicio en el el último mes ¿verdad? ¿qué te parece jugar al fútbol conmigo mañana? jugar al baloncesto también está bien

他们可能明天一起运动。
pi: tāmen kěnéng míngtiān yìqǐ yùndòng
en: they might play sports together tomorrow
es: puede que mañana hagan deporte juntos

answer

1

*** 28
:PROPERTIES:
:CREATED: [2022-04-14 12:42:00 -05]
:END:

妻子每天睡觉前都要喝一杯牛奶，她说这样可以睡得好一些。
pi: qīzi měi tiān shuì jiào qián dōu yào hē yì bēi niúnǎi, tā shuō zhèyàng kěyǐ shuì de hǎo yìxiē
en: my wife has to drink a glass of milk every day before she goes to bed, she says she can sleep better that way
es: mi mujer tiene que beber un vaso de leche todos los días antes de acostarse, dice que le hace dormir mejor

妻子起床后要喝牛奶。
pi: qīzi qǐ chuáng hòu yào hē niúnǎi
en: the wife has to drink milk when she wakes up
es: la mujer tiene que beber leche cuando se despierta

answer

0

*** 29
:PROPERTIES:
:CREATED: [2022-04-14 12:46:13 -05]
:END:

谢谢您，没有您的帮助，这件事情可能到今天晚上也做不完。
pi: xièxie nín, méiyǒu nín de bāngzhù, zhè jiàn shìqing kěnéng dào jīntiān wǎnshng yě zuò bu wán
en: thank you, without your help, this matter may not be done by this evening
es: gracias, sin su ayuda esto probablemnete no se habría hecho esta tarde

事情已经做完了。
pi: shìqing yǐjīng zuòwán le
en: the thing is done
es: la cosa ya se ha hecho

answer

1

*** 30
:PROPERTIES:
:CREATED: [2022-04-14 12:47:36 -05]
:END:

慢一点儿，你走得太快了，我们去那个茶馆喝杯茶好不好？
pi: màn yìdiǎnr, nǐ zǒu de tài kuài le, wǒmen qù nàge cháguǎn hē bēi chá hǎo bu hǎo?
en: slow down, you're walking too fast, let's go to that teahouse and have a cup of tea, okay?
es: más despacio, estás caminando demasiado rápido. ¿vamos a la casa de té a tomar una taza de té?

他想去喝茶。
pi: tā xiǎng qù hē chá
en: he wants to go to drink tea
es: él quiere ir a tomar té

answer

1

** 4
:PROPERTIES:
:CREATED: [2022-04-14 13:06:44 -05]
:ID: f76e29dc-ef69-4143-8593-c9facf42316a
:END:

路上车太多，坐公共汽车还没有走路快呢。
pi: lùshang chē tài duō, zuò gōnggòngqìchē hái méiyǒu zǒu lù kuài ne
en: there are too many cars on the raod, taking the bus is not as fast as walking
es: hay demasiados coches en la carretera, y coger el autobús no es tán rápido como caminar.

上个星期怎么没看到你？
pi: shàngge xīngqī zěnme méi kàndào nǐ?
en: how come I didn't see you last week?
es: ¿cómo es que no te vi la semana pasada?

天气太冷了，都零下十度了。
pi: tiānqì tài lěng le, dōu língxià shí dù le
en: it's too cold, it's ten degrees below zero
es: hace mucho frío, hay diez grados bajo cero

他比我游得快，但是没有大卫游得快。
pi: tā bǐ wǒ yóu de kuài, dànshì méiyǒu dàwèi yóu de kuài
en: He swims faster than I do, but not as fast as David
es: el nada más rápido que yo, pero no tanto como David

他在哪儿呢？你看见他了吗？

住得远真的很累。
pi: zhù de yuǎn zhēn de hěn lèi
en: It's really tiring to live far away
es: es realmente agotador vivir lejos

*** 31
:PROPERTIES:
:CREATED: [2022-04-14 13:07:07 -05]
:END:

你今天怎么穿的这么多？
pi: nǐ jīntiān zěnme chuān de zhème duō?
en: why are you wearing so much today?
es: ¿por qué vistes mucho hoy?

answer

c

*** 32
:PROPERTIES:
:CREATED: [2022-04-14 13:07:12 -05]
:END:

我每天要坐一个多小时的公共汽车去上班。
pi: wǒ měitiān yào zuò yí ge duō xiǎoshí de gōnggòngqìchē qù shàng bān
en: I take the bus for more than an hour to go to work every day
es: tomo el autobús durante más de una hora para ir al trabajo todos los días

answer

f

*** 33
:PROPERTIES:
:CREATED: [2022-04-14 13:07:30 -05]
:END:

小王每天都游泳，他游得快吗？
pi: xiǎo wáng měitiān dōu yóuyǒng, tā yóu de kuài ma?
en: Xiao Wang swims every day, does he swim fast?
es: Xiao Waang nada todos los días ¿es un nadador rápido?

answer

d

*** 34
:PROPERTIES:
:CREATED: [2022-04-14 13:07:51 -05]
:END:

你每天坐公共汽车去学校吗？
pi: nǐ měitiān zuò gōnggòngqìchē qù xuéxiào ma?
en: do you take the bus to school every day?
es: ¿coges el autobús para ir al colegio todos los días?

answer

a

*** 35
:PROPERTIES:
:CREATED: [2022-04-14 13:09:01 -05]
:END:

我和妻子一起去北京旅游了几天。
pi: wǒ hé qīzi yìqǐ qù běijīng lǚyóu le jǐ tian
en: Me and my wife traveled to Beijing for a few days
es: Yo y mi esposa viajamos a Beijing por unos días

answer

b

* Characters
:PROPERTIES:
:CREATED: [2022-04-14 13:47:29 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-04-14 13:47:31 -05]
:END:

c

公园 | gōng yuán | park | parque ;

b

公共汽车 | gōng gòng qì chē | public bus | bus de transporte público

a

公司 | gōng sī | company, office | empresa ;

d

公用电话 | gōng yòng diàn huà | public phone | teléfono público ;

