:PROPERTIES:
:CREATED: [2022-04-13 16:38:38 -05]
:END:

* Warm-up
:PROPERTIES:
:CREATED: [2022-04-13 16:44:36 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-13 16:44:47 -05]
:END:

1. b

妻子 | qīzi | wife | esposa ;

2. d

睡觉 | shuìjiào | to sleep | dormir ;

3. a

房间e | fángjiān | room | cuarto ;

4. e

下雪 | xiàxuě | to snow | nover ;

5. c

起床 | qǐ chuáng | to wake up | despertarse ;

6. f

房子 | fángzi | apartment | casa ;

** 2
:PROPERTIES:
:CREATED: [2022-04-13 16:44:37 -05]
:END:

Using 说

说

Using 开

开车
开公共汽车

Using 准备



Using 读

怎么读汉字？

Using 找

找朋友
找工作
找女朋友/男朋友
找我的手机

Using 学习

学习汉语
pi: xuéxí hànyǔ
en: study chinese

学习数学
pi: xuéxí shùxué
en: study mathematics

* Text
:PROPERTIES:
:CREATED: [2022-04-13 16:54:18 -05]
:END:

** 1. 在教室 | zài jàoshì | in the classroom | en la clase
:PROPERTIES:
:CREATED: [2022-04-13 16:54:31 -05]
:ID: 5fdb3837-1f66-42ac-bfd6-6474f5829fdc
:END:

Ａ：你每天早上几点起床？
pi: nǐ měi tiān zǎoshang jǐ diǎn qǐ chuáng
en: what time do you get up every morning?
es: ¿a qué hora te levantas cada mañana?

Ｂ：六点多。
pi: liù diǎn duō
en: after six o'clock
es: despues de las seis

Ａ：你比我早起一个小时。
pi: nǐ bǐ wǒ zǎo qǐ yí ge xiǎoshí
en: you get up an hour earlier than that
es: te levantas una hora antes que yo

Ｂ：我睡得也早，我每天晚上十点就睡觉。早睡早起身体好。
pi: wǒ shuì de yě zǎo, wǒ měi tiān wǎnshang shí diǎn jiù shuì jiào. zǎo shuì zǎo qǐ shēntǐ hǎo
en: I also go to bed early, I go to bed at ten o'clock every night. sleeping early and waking up early is good for the health
es: yo también me acuesto pronto¸ me acuesto a las diez todas todas las noches. acostarse temprano y levantarse temprano es bueno para la salud

New words

得 | de | used after a verb or an adjective to introduce a complement of result or degree ;

** 2. 在朋友家 | zài péngyou jiā | At a friend's home | en la casa de un amigo
:PROPERTIES:
:CREATED: [2022-04-13 16:54:31 -05]
:ID: e34e8d6a-96c0-40b7-945e-75834caea7df
:END:

Ａ：再来点儿米饭吧，你吃得太少了。
pi: zài lái diǎnr mǐfàn ba, nǐ chī de tài shǎo le
en: have some more rice, you've eaten too little
es: toma más arroz, has comido muy poco

Ｂ：不少了，今天吃得很好，太谢谢你了。
pi: bù shǎo le, jīntiān chī de hěn hǎo, tài xièxie nǐ le
en: it's quite a lot, I ate very well today, thank you so much
es: no está mal, he comido bien, gracias

Ａ：你做饭做得怎么样？
pi: nǐ zuò fàn zuò de zěnmeyàng?
en: how is your cooking?
es: ¿qué tal cocinas?


Ｂ：不怎么样，我妻子比我做得好。
pi: bù zěnmeyàng, wǒ qīzi bǐ wǒ zuò de hǎo
en: not good, my wife is better than me
es: no tan bien, mi mujer es mejor que yo

New words

妻子 | qīzi | wife | esposa ;

** 3. 在家门口 | zài jiā mén kǒu | at the door of the house | en la puerta de la casa
:PROPERTIES:
:CREATED: [2022-04-13 16:54:31 -05]
:ID: bbe8bb76-c6b6-435f-9720-493516a5ab78
:END:

Ａ：下雪了，今天真冷。
pi: xià xuě le, jīntiān zhēn lěng
en: it's snowing, it's really cold today
es: está nevando, hoy hace mucho frío

Ｂ：有零下10度吧？
pi: yǒu líng xià shí sù ba
en: it's ten degrees below zero, right?
es: hay diez grados bajo cero ¿no?

Ａ：是啊，你穿得太少了，我们进房间吧。
pi: shì a, nǐ chuān de tài shǎo le, wǒmen jìn fángjiān ba
en: yeah, you're undressed, let's go into the room
es: sí, estás mal vestido, vamos a la habitación

Ｂ：好吧。
pi: hǎo ba
en: okay
es: de acuerdo

New words

雪 | xuě | snow | nevar ;

零 | líng | zero | cero ;

度 | dù | degree ;

穿 | chuān | to wear | vestir ;

进 | jìn | to enter, to come/go in | entrar ;

** 4. 在家里 | zài jiā lǐ | at home | en casa
:PROPERTIES:
:CREATED: [2022-04-13 16:54:31 -05]
:ID: 6d7314b6-86ae-4437-94c1-288be895f139
:END:

Ａ：你在忙什么呢？
pi: nǐ zài máng shénme ne?
en: what are you working on?
es: ¿en qué está trabajando?

Ｂ：我弟弟让我帮他找个房子，现在他家离公司有点儿远。
pi: wǒ dìdi ràng wǒ bāng tā zhǎo ge fángzi, xiànzài tā jiā lí gōngsī yǒudiǎnr yuǎn
en: my brother asked me to help him find a house, now his house is a bit far from the company
es: mi hermano me pidió que le ayudara a encontrar un piso, ahora su casa está un poco lejos de la oficina

Ａ：住得远真的很累！
pi: zhù de yuǎn zhēn de hěn lèi
en: it's really tiring to live far away
es: ¡es ralmente agotador vivir lejos!

Ｂ：是啊，他也希望能住得近一点儿。
pi: shì a, tā yě xīwàng néng zhù de jìn yīdiànr
en: yeah, he also wants to live a little closer
es: sí, a él también le gustaría vivir más cerca

New words

弟弟 | dìdi | younger brother | hermano más joven ;

近 | jìn | near, close | cerca ;

* Notes
:PROPERTIES:
:CREATED: [2022-04-13 21:27:06 -05]
:END:

** 1. Complements of degree
:PROPERTIES:
:CREATED: [2022-04-13 21:28:05 -05]
:END:

A complement of degree describes the degree of something. The structural particle "得" is often used to introduce a complement of degree which makes remarks on the extent or degree an action or the quality or state of something has rechaed. Sometimes "得" is not used. For example:

他说得很好。
pi: tā shuō de hěn hǎo
en: he speaks very well
es: él habla muy bien

我起得很早。
pi: wǒ qǐ de hěn zǎo
en: I get up very early
es: Me levanto muy temprano

我睡得也早。
pi: wǒ shuì de yě zǎo
en: I also wake up early
es: Yo también me levanto temprano

If a verb takes an object, the object should be put before the verb, or the verb be reduplicated. For example:

他（说）汉语说得很好。
pi: tā (shuō) hànyǔ shuō de hěn hǎo
en: he speaks chinese very well
es: habla muy bien el chino

我（写）汉语写得很好。
pi: wǒ (xiě) hànyǔ xiě de hěn hǎo
en: I write chinese very well
es: escribo muy bien el chino

姐姐（唱）歌唱得不错。
pi: jiějie chàng gē chàng de bù cuò
en: my sister sings well
es: la hermana canta muy bien

In the negative form, the negaative word should be put after the structural particle "得". For example:

他说得不好。
pi: tā shuō de bù hǎo
en: he doesn't speak very well
es: el no habla bien

我起得不早。
pi: wǒ qǐ de bù zǎo
en: I don't get up early
es: no me levanto temprano

我住得不远。
pi: wǒ zhù de bù yuǎn
en: I don't live far away
es: no vivo muy lejos

他（说）汉语说得不好。
pi: tā (shuō) hànyǔ shuō de bù hǎo
en: he doesn't speak chinese well
es: el no habla bien el chino

我（写）汉字写得不好。
pi: wǒ xiě hànyǔ xiě de bù hǎo
en: I don't write chinese characters well
es: no escribo los caracteres chinos bien

姐姐（唱）歌唱得不太好。
pi: jiějie chàng gē chàng de bù tài hǎo
en: sister doesn't sing very well
es: la hermana no canta muy bien

In the interrogative form, "得" is followed by the structure "Adj + 不 + Adj", forming an affirmative-negative sentences.

他说得好不好？
pi: tā shuō de hǎo bù hǎo?
en: does he speak well?
es: ¿él habla bien?

姐姐起得早不早？
pi: jiějie qǐ de zǎo bù zǎo?
en: does sister wake up very early?
es: ¿la hermana se levanta temprano?

你住得远不远？
pi: nǐ zhù de yuán bù yuán?
en: do you live far away?
es: ¿vives lejos?

** 2. The "比" sentence
:PROPERTIES:
:CREATED: [2022-04-13 21:48:38 -05]
:END:

If a verb takes a complement of degree, "比" can be put before the verb or the complement. For example:

他比我学得好。
pi: tā bǐ wǒ xué de hǎo
en: he learns better than I do
es: el aprende mejor que yo

姐姐比我跑得快。
pi: jiějie bǐ wǒ pào de kuài
en: my sister runs faster than me
es: mi hermana corre más rápido que yo

我妻子比我做得好。
pi: wǒ qīzi bǐ wǒ zuò de hǎo
en: my wife does a better job than I do
es: mi esposa lo hace mejor que yo

他学得比我好。
pi: tā bǐ wǒ xué de hǎo
en: he learns better than I do
es: el aprende mejor que yo

姐姐跑得比我快。
pi: jiějie bǐ wǒ pào de kuài
en: my sister runs faster than me
es: mi hermana corre más rápido que yo

我妻子做得比我好。
pi: wǒ qīzi bǐ wǒ zuò de hǎo
en: my wife does a better job than I do
es: mi esposa lo hace mejor que yo

* Exercises
:PROPERTIES:
:CREATED: [2022-04-13 21:58:27 -05]
:END:

** 2
:PROPERTIES:
:CREATED: [2022-04-13 22:25:09 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-13 22:03:49 -05]
:END:

她为什么每天晚上十点就睡觉？
因为她觉得睡得早对身体好。

*** 2
:PROPERTIES:
:CREATED: [2022-04-13 22:03:53 -05]
:END:

他们家谁做饭做得好？
他妻子，他妻子比他做饭做得好。

*** 3
:PROPERTIES:
:CREATED: [2022-04-13 22:04:14 -05]
:END:

今天天气怎么样？
今天真冷。
今天下雪。
今天有零下10度。

*** 4
:PROPERTIES:
:CREATED: [2022-04-13 22:08:04 -05]
:END:

她这两天在忙什么呢？
她在帮她弟弟找个房子。

*** 5
:PROPERTIES:
:CREATED: [2022-04-13 22:11:07 -05]
:END:

她弟弟为什么要找新得房子？

因为他家离公司有点儿远。

** 3
:PROPERTIES:
:CREATED: [2022-04-13 22:25:11 -05]
:END:

她唱得很（好）。
pi: tā chàng de hěn hǎo

爸爸开车开得（太快了）。
pi: bàba kāi chē kāi de tài kuài le

哥哥比我吃得（多）。
pi: gēge bǐ wǒ chī de duō

爸爸比妈妈做饭做得（好吃）。
pi: bàba bǐ māma zuò fàn zuò de hǎo chī

* Application
:PROPERTIES:
:CREATED: [2022-04-13 22:28:42 -05]
:END:

** Pair Work
:PROPERTIES:
:CREATED: [2022-04-13 22:39:45 -05]
:END:

*** Easy sentences
:PROPERTIES:
:CREATED: [2022-04-16 17:43:50 -05]
:END:

**** Using 学
:PROPERTIES:
:CREATED: [2022-04-13 22:57:25 -05]
:END:

他学得快。
pi: tā xué de kuài
en: he learns fast
es: el aprende rápido

她学汉语学得很好。
pi: tā xué hànyǔ xué de hěn hǎo
en: she learns chinese very well
es: ella aprende chino muy bien

他学得不快。
pi: tā xué de bù kuài
en: he doesn't learn fast
es: el no aprende rápido

他学得快不快？
pi: tā xué de kuài bú kuài
en: does he larn fast?
es: ¿él aprende rápido?

大卫比安妮学得快。
pi: dàwèi bǐ ānnī xué de kuài
en: David learns faster than Annie
es: David aprende más rápido que Ana

大卫学比安妮得快。
pi: dàwèi bǐ ānnī xué de kuài
en: David learns faster than Annie
es: David aprende más rápido que Ana

**** Using 走
:PROPERTIES:
:CREATED: [2022-04-13 22:57:27 -05]
:END:

她走得慢。
pi: tā zǒu de màn
en: she walks slowly
es: ella camina lento

她走得快。
pi: tā zǒu de kuài
en: she walks fast
es: ella camino rápido

大卫比安妮走得快。
pi: dàwèi bǐ ānnī zǒu de kuài
en: David walks faster than Annie
es: David camina más rápido que Annie

小刘比小李走得慢。
pi: xiǎo liú bǐ xiǎo lǐ zǒu de màn
en: Xiao Liu walks slower than Xiao Li
es: Xiao Liu camina más lento que Xiao Li

**** Using 写
:PROPERTIES:
:CREATED: [2022-04-13 22:57:29 -05]
:END:

她写汉字写得很好。
pi: tā xiě hànzì xiě de hěn hǎo
en: she writes chinese characters very well
es: ella escribe caracteres chinos muy bien

她写汉字写得不错。
pi: tā xiě hànzì xiě de bùcuò
en: she writes chinese characters well
es: ella escribe caracters chinos bien

哥哥比姐姐写汉字写得好。
pi: gēge bǐ jiějie xiě hànzi xiě de hǎo
en: my brother can write chinese characters better than my sister
es: mi hermano puede escribir caracteres chinos mejor que mi hermana

哥哥写汉字写得不好。
pi: gēge xiě hànzi xiě de bù hǎo
en: my brother can't write chinese characters well
es: mi hermano no escribe bien los caracteres chinos

**** Using 读
:PROPERTIES:
:CREATED: [2022-04-13 22:57:35 -05]
:END:

她读很快。
pi: tā dú de kuài
en: she reads fast
es: ella lee rapido

她读得不快。
pi: tā dú de bù kuài
en: she doesn't read fast
es: ella no lee rapiido

她读汉语读得快。
pi: tā dú hànyǔ dú de kuài
en: she reads chinese fast
es: ella lee chino rápido

他比安妮读得快。
pi: tā bǐ ān nī dú de kuài
en: he reads faster than Annie
es: él lee más rápido que Ana

**** Using 下
:PROPERTIES:
:CREATED: [2022-04-13 22:57:37 -05]
:END:

**** Using 起床
:PROPERTIES:
:CREATED: [2022-04-13 22:57:39 -05]
:END:

我喜欢起床得早。
pi: wǒ xǐhuān qǐchuáng de zǎo
en: I like waking up early
es: me gusta levantarme temprano

我哥哥每天起床得晚。
pi: wǒ gēge měitiān qǐ chuáng de wǎn
en: my brother wakes up late every day
es: mi hermano se levanta tarde todos lso días

每天我爸爸比我妈妈起床得早。
pi: měitiān wǒ bàba bǐ wǒ māma qǐ chuáng de zǎo
en: every day my father wakes up early than my mother
es: todos los días mi padre se levanta más temprano que mi madre

他起床得早不早？
pi: tā qǐ chuáng de zǎo bù zǎo?
en: does he wake up early?
es: ¿el se levanta temprano?

他起床得晚不晚？
pi: tā qǐ chuáng de wǎn bù wǎn?
en: does he wake up very late?
es: ¿él se levanta tarde?

**** Using 睡觉
:PROPERTIES:
:CREATED: [2022-04-13 22:57:40 -05]
:END:

我每天睡觉得早。
pi: wǒ měitiān shuìjiào de zǎo
en: I wake up early every day
es: me acuesto temprano todos los días

**** Using 准备
:PROPERTIES:
:CREATED: [2022-04-13 22:57:42 -05]
:END:

en: He was well prepared for the exam.

他考试准备得好。

他得考试准备好。


*** Complex sentences
:PROPERTIES:
:CREATED: [2022-04-16 17:44:06 -05]
:END:

Using 学 and 好

他比他哥哥学得好，所以他考试考得好。
en: he studied better than his brother, so he did well in the exam

Using 写 and 漂亮

他（写）汉字写得漂亮。
他（写）汉字写得好看。
en: he writes chinese characters beautifully

Using 走 and 慢

昨天在商店我看见他走得慢。
en: I saw him walking slowly yesterday at the store

他想按时上课，所以他走得快。
pi: tā xiǎng àn shí shàng kè, suǒyǐ tā zǒu de kuài
en: he wanted to be on time for class, so he walked fast


Using 下 and 大

昨天雨下得比今天大。 (comparing the verb)
昨天的雨比今天的大。 (comparing the noun)
en: yesterday's rain was heavier than today's

Using 读 and 快

他是一个好学生，他能读得快。
en: he's a good student, he can read very fast

Using 准备 and 好


每次上汉语课前，他准备得好。
pi: měi cì shàng hànyǔ kè qián, tā zhǔnbèi de hǎo
en: he prepares well before each chinese lesson
es: se prepara bien antes de cada lección de chino

爸爸告诉我，明天的考试我要准备得很好。
pi: wǒ bàba gàosu wǒ, wǒ yào zhǔnbèi míngtiān de kǎoshì de hěn hǎo
en: my dad told me that I have to prepare for tomorrow's exam very well
es: mi padre me ha dicho que tengo que prepararme para mi examen de mañana muy bien


** Group Work
:PROPERTIES:
:CREATED: [2022-04-14 00:03:03 -05]
:END:


1. Using "A 比 B + V + 得 + Adj".
2. Using "A + V + 得 + 比B + Adj"

Example

我比大卫跑得快。
我跑得比大卫快。

Example

我比安妮唱得好。
我唱得比安妮好。


Example

他比他姐姐起得早。
他起得比他姐姐早。

Example

我比安妮写得好。
我写得比安妮好。


Example

他比他哥哥走得快。
他走得比他哥哥快。

