* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: f27b91b6-00fc-4077-a78f-d70597e3e494
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
21d436ee-5d87-4548-b176-c1af10f7dff7.mp3
***** 转录
表面看，它是一个普通得不能再普通的包裹，里面装的是家乡的土特产，但在我的眼里，它珍贵着呢。它经过了母亲的双手，又途经千里，来到了我的面前。它沾染着故乡的气息，满载着母亲无声的爱意。
**** 选择
***** A
猎能发现老鼠的踪迹
***** B
猎需要牛磴酸提高嗜克
***** C
猎的体内含有较多牛磺酸
***** D
猎因为自己的需要而吃鱼和老鼠
**** 答案
C
*** 2
:PROPERTIES:
:ID: 8cf620be-9254-4f03-9325-8a721bda8e44
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
28687608-3031-4c63-b40b-df670dd53872.mp3
***** 转录
清晨，梦中的我被父亲叫醒，“走，晨练去！”我和父亲并排跑着，一抬头发现父亲竟然有了一丝白发。我有些心酸。他总是那么勤奋，那么忙碌，为家庭、为单位操劳。作为女儿，我懂得父亲的付出、父亲的期望。
**** 选择
***** A
母亲常常给我寄包衣
***** B
包啧里的东西很值钱
***** C
包商是母亲亲手打理的
***** D
母亲亲自给我带了包啧
**** 答案
D
*** 3
:PROPERTIES:
:ID: bf5dfa3f-271c-48c1-be58-71ebca030122
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
6bbd24bc-e7f6-4285-ad33-548159d5ad74.mp3
***** 转录
家是什么？家是一个可以放松的地方，说话做事都不必小心；家是一个可以疗伤的地方，伤了痛了都可以在家中得以缓解。回到家，可以听几首音乐，可以饮一杯清茶，让心情重归舒畅。
**** 选择
***** A
我特别不喜欢晨练
***** B
我胃有点儿不舒服
***** C
父亲的胡须都白丁
***** D
我理解勤奋的父亲
**** 答案
D
*** 4
:PROPERTIES:
:ID: a3b6a684-6210-4309-8c59-26e2e90f64fd
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
799ee35c-4f2d-4d8e-83ff-83eaf8922c59.mp3
***** 转录
“诚”指诚实诚恳，“信”即信用信任。“诚”主要指“内诚于心”，“信”主要指“外信于人”。“诚”“信”组合在一起，就形成了一个内外兼备，具有丰富内容的词汇，即诚实无欺，讲求信用。
**** 选择
***** A
出门在外都应该惦记家
***** B
回家时心中会充满喜悦
***** C
受了伤还是回家休息好
***** D
在家中可以改变坏心情
**** 答案
D
*** 5
:PROPERTIES:
:ID: 824b23e8-4f9c-4263-b28b-a540d72b7e00
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
1e3e2fca-0ca1-4b38-b950-80a947e3f0e8.mp3
***** 转录
老张做月饼的手艺是一流的，那是他父亲的父亲传下来的。老张做月饼不喜欢别人看，可他也不特别防范，一来是人来人往地不好防；二来是老张不好意思跟人急，真翻脸。邻居们也很自觉，老张养活着一大家人，不容易。
**** 选择
***** A
“信“主要指对人要诚悟
***** B
“诚“主要指对人要守信
***** C
“诚“和“信“是同义词
***** D
“诚信“指不欺骗，守信誉
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: cc675f57-f5d6-4289-8c49-a6ee93534d06
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
fc5d5d4a-1434-46de-9145-99c1fe936ea6.mp3
***** 转录
女：赵老师，今天跟您探讨一下“面子”问题。您能不能确切点儿说说，到底什么是面子？
男：按词典的解释，就是“表面上的形象；虚荣”。
女：这个解释挺负面的哈。中国人常说“死要面子活受罪”，可大家还是觉得面子不能不要。
男：也有人说，面子是每一个社会成员想为自己挣得的一种在公众中的个人形象。
女：这个解释我觉得更好。
男：仔细想想，其实咱们都挺顾面子的，比如说，在公众场合要干净、整洁、文明，给别人留下个好印象，不能丢人。
女：没错。
男：咱们中国人还认为有面子就有尊严，没面子就被人看不起，这是积极的一面。面子会使我们约束自己，规范自己，注意维护自己的形象。但因为要面子而使自己受委屈，甚至骗别人，就不好了。
女：您举个例子？
男：有这样一个故事。从前，有一个人，每次出去，都是酒足饭饱以后回来。妻子问他和什么人一起吃的饭？他说是朋友，大官，有钱人。妻子奇怪，家里从来没来过这样的客人呀。妻子想把这件事搞清楚。第二天丈夫出门后，她就跟上了。丈夫走遍全城也没有一个人和他说话，最后丈夫来到城东边安葬死人的地方，走到祭祀的人跟前，跟人家要剩下的食物。妻子看了很生气，心想：“丈夫是自己终身依靠的人，现在竟然这样。”一会儿，丈夫又高高兴兴地回来了，仍旧对妻子摆出一脸的高傲。这个故事没有讲结局，但我们可以想象，不管在什么时代，这个丈夫一定没有好前途。
女：这个故事像一幅画，给我们画出了一类人，他们不想劳动，只想过安闲舒适的生活，这种人还有个更大的问题，就是他们还想要面子。
男：对。
女：我觉得我们说的面子有时候还指公共面子，比如，我们都希望中国队在国际比赛中得到冠军，为国家争光。
男：没错。
**** 题目
***** 6
:PROPERTIES:
:ID: 5c22b646-d69e-48c7-a82d-f5975fbed9bf
:END:
****** 问题
******* 音频
47c6c99c-ba4c-4974-8863-68efbe6dcfa5.mp3
******* 转录
女的认为哪种“面子”的解释更好？
****** 选择
******* A
一个人天生的模样
******* B
实际不存在的光荣
******* C
努力取得的个人的公众形象
******* D
即使倒霆也得保持的好形象
****** 答案
C
***** 7
:PROPERTIES:
:ID: ee661273-4912-4d90-b5ad-f9bddcb1b1ee
:END:
****** 问题
******* 音频
b5814d68-d6aa-464f-8133-f30ea1aebc37.mp3
******* 转录
面子的积极意义是什么？
****** 选择
******* A
希望别人留下好印象
******* B
看不起不爱面子的人
******* C
在公共场合不能受委屈
******* D
为面子规范自己的行为
****** 答案
D
***** 8
:PROPERTIES:
:ID: ad3b5552-3421-4b5b-9a24-ed80c3b2870c
:END:
****** 问题
******* 音频
47d1acf2-8228-4c7b-8032-ce5dc3564876.mp3
******* 转录
以下哪一项符合故事的情节？
****** 选择
******* A
夫妻二人从来不和人来往
******* B
这个故事没有讲事情的结果
******* C
丈夫每天和达官贵人一起吃饭
******* D
丈夫自己在外吃饭妻孔很生气
****** 答案
B
***** 9
:PROPERTIES:
:ID: 55bcd8e5-2bd8-4a5f-90eb-90b897a43886
:END:
****** 问题
******* 音频
779fbaf7-ef4f-4922-bf0f-13c86cce3c68.mp3
******* 转录
这个故事表现了一类人的什么特点？
****** 选择
******* A
他们的生活像一张画儿
******* B
他们过着安闲舒适的生活
******* C
他们有比较大的心理问题
******* D
他们不想付出还想要面子
****** 答案
D
***** 10
:PROPERTIES:
:ID: 72584d97-c2ab-4ac5-983c-37f58de6047c
:END:
****** 问题
******* 音频
25985c08-d8db-4c82-a7cf-aa7c3637344f.mp3
******* 转录
人们常说的面子还包括什么？
****** 选择
******* A
集体、公众的面子
******* B
每个人的言行举止
******* C
不能让别人看不起
******* D
有自尊心不做丢脸事
****** 答案
A
** 第三部分
*** 11-13
:PROPERTIES:
:ID: d3d5410a-51f1-4dcc-875f-419efa3f9263
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
b904fa17-d9c9-4047-a719-cd1221aa693f.mp3
***** 转录
41 岁的男子伊尔雅特只读过三年小学，却在 35 岁时重拾书本，苦读六年后取得了律师资格。你相信吗？
伊尔雅特 3 岁时，父母离异，他和母亲一起生活。看着常年有病的母亲异常艰难，伊尔雅特 8 岁离开学校，担起了家庭的重担。他开始卖报、卖糖果和一些小商品，和母亲过着半饥半饱的日子。伊尔雅特 35 岁成了一名公交司机，一天一位女士在车上听着伊尔雅特风趣幽默的谈吐，忍不住大笑，对他说：“你是一个有能力的人，应该继续去读书，然后做律师。”伊尔雅特流露出一脸的迟疑，小声说：“我这么大年龄了，能行吗？”女士鼓励他：“起码要尝试一下，不然你怎么知道自己不行？记住一句话——要相信自己，你是最棒的！”伊尔雅特接受了女士的建议，经过六年的艰苦努力，终于改变了自己的人生。
**** 题目
***** 11
:PROPERTIES:
:ID: e0f04de9-6073-422b-8df0-db5e9b069337
:END:
****** 问题
******* 音频
853bc142-db71-49b0-aa0e-07c6960d1cbe.mp3
******* 转录
以下哪一项符合伊尔雅特的经历？
****** 选择
******* A
他总共就读过六年书
******* B
他8岁就特别会做买卖
******* C
小时候他和妈妈每天都吃不何
******* D
长大后他坐车遇到了一位女士
****** 答案
C
***** 12
:PROPERTIES:
:ID: b9c903ac-23c8-4769-9f6e-06c57f20a64b
:END:
****** 问题
******* 音频
1bff6403-bb40-4d8d-9346-e9421d562f87.mp3
******* 转录
是什么促使伊尔雅特继续读书？
****** 选择
******* A
女士的一番话
******* B
当律师挣钱多
******* C
他想改变工作
******* D
他口才特别好
****** 答案
A
***** 13
:PROPERTIES:
:ID: 9f6c6288-8b52-4135-8fc1-d79114cb88bf
:END:
****** 问题
******* 音频
c51061d8-464e-45a5-bc88-c5c2f5bfed8f.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
伊尔雅特非常同情母亲
******* B
伊尔雅特是一名好司机
******* C
伊尔雅特幽默且肯付出
******* D
伊尔雅特相信自己最棒
****** 答案
C
*** 14-17
:PROPERTIES:
:ID: 2d4e4bef-fce0-4f14-b316-834a9873dfca
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
5c16b5ef-149c-4dd9-a6e3-8d9da0b420a0.mp3
***** 转录
在很多孩子心中，爸爸是严厉的，而我正好相反。在我的记忆中，爸爸总是斯斯文文的，从来不会给人威严的感觉。我很喜欢亲近爸爸，年龄绝对不会阻挡我们之间的友谊。我小的时候，爸爸只要一有空就会和我做游戏；晚上，数着天上的星星，说着白马王子的故事。每每和爸爸在一起，我总能感觉到温暖。
其实玩儿是次要的，爸爸的魅力主要表现在他有渊博的知识和无限的爱心。
也许是学有家传，爸爸懂的特别多，在我的眼里他绝对是本百科全书。上至天文，下至地理，早到人类的起源，迟到人类的未来，他都知道。我有时候会边打量他边问自己：“爸爸的脑袋里怎么能装那么多知识？”并暗暗下决心，我也要像爸爸那般有学问。
爸爸的职业是医生，他的超级爱心还表现在他热爱他的职业、关爱他的每一位病人上。他医术高明，为病人着想。当年爸爸在日本读书，带回来一笔钱，很多人都以为我们家要发财了，可爸爸把大部分钱捐给了他住在大山中的病人家乡的一所小学，他说这笔钱花在那里更值。
**** 题目
***** 14
:PROPERTIES:
:ID: 131e2f51-c8a1-4892-905d-556cf45c66da
:END:
****** 问题
******* 音频
dbbb16fa-4233-4897-b58d-c30d1bbe0d8c.mp3
******* 转录
在“我”的心中，爸爸是个什么样的人？
****** 选择
******* A
非常严厉
******* B
十分斯文
******* C
很有童心
******* D
年龄太大
****** 答案
B
***** 15
:PROPERTIES:
:ID: 5cc31252-53f6-4831-8916-32e7355b3d0f
:END:
****** 问题
******* 音频
17dca947-18de-40d2-bed5-25699810549f.mp3
******* 转录
“我”为什么说爸爸很有魅力？
****** 选择
******* A
他关爱每一位病人
******* B
他比一般人会讲故事
******* C
他是医院的骨干医生
******* D
他没有辜负长辈的期望
****** 答案
A
***** 16
:PROPERTIES:
:ID: 071af1b5-f004-43df-9a0a-7deda50191d1
:END:
****** 问题
******* 音频
f1955579-e633-4b83-947a-0b70a259c700.mp3
******* 转录
关于爸爸知识渊博，下列哪项正确？
****** 选择
******* A
爸爸最喜欢读百科全书
******* B
爸爸的大脑和别人不同
******* C
爹爸最喜欢天文和地理
******* D
可以说爸爸什么都知道
****** 答案
D
***** 17
:PROPERTIES:
:ID: 97a36cad-62ef-4fb3-b17d-2bb831345197
:END:
****** 问题
******* 音频
4b3cd589-5fcc-47bc-8c8b-b91b10bf51f7.mp3
******* 转录
对医生爸爸的评价，下列哪项正确？
****** 选择
******* A
爸爸爱病人超过爱家人
******* B
爸爸从不认为钱很有用
******* C
爹爸是个敬业的好医生
******* D
爹爸愚改行当小学老师
****** 答案
C
* 阅读
** 第一部分
*** 18
**** 句子
***** A
清晨的第一缕阳光照在妈妈的脸上，显得光彩照人。
***** B
秋冬季节，除丁适合喝红茶，发酵的黑茶也是不错的选择。
***** C
正常人每天保证肉蛋奶和豆制品的摄人，没必要再补充蛋白质。
***** D
与戴先生不同，作为公司主管的诗女士对自己的职业规划始终非常明确。
**** 答案
*** 19
**** 句子
***** A
一望无际的海，让我思绪如潮，瞬间有了想抒发情感的欲望。
***** B
我最喜欢去的地方是博物馆，在那里可以与历史和艺术对话。
***** C
明晚8点，我们班在会议室进行新年联欢会，望同学们准时参加。
***** D
狗是第一种人类驯养的动物，最初并不是宠物，而是人类狞猎的助手。
**** 答案
*** 20
**** 句子
***** A
小时侯，父亲在我心中的模样很模糊，只记得是很严肃的人。
***** B
钟连盛是国家级非物质文化遗产传承人，已经和景泰蓝打了37年交道。
***** C
圣贝纳迪诺市位于洛杉矶以东96公里，是一个有着20多万人口的小城。
***** D
教练喜欢他，因为他有天赋，有渺望，有拼劲，欠缺的只是训练和机会。
**** 答案
** 第二部分
*** 21
**** 段话
一个醉汉躺在街头，警察[[gap]]起他，发现他是当地的富翁。警察要送他回家，他却说：“我没有家。”警察指着不远处灯光灿烂的居所问：“那是什么？”富翁说：“那是房子。你们都[[gap]]子就是家。可是，在你的亲人搬[[gap]]以后，那儿还是家因7”
**** 选择
***** A
****** 1
抱
****** 2
觉得
****** 3
离
***** B
****** 1
扶
****** 2
认为
****** 3
走
***** C
****** 1
喜
****** 2
以为
****** 3
远
***** D
****** 1
叫
****** 2
感觉
****** 3
家
**** 答案
*** 22
**** 段话
在中西方文化中，“面子”[[gap]]不同的文化特征。探讨和对比不同文化背景下的语言和行[[gap]]为出的面子文化的差异，[[gap]]消除东西方[[gap]]在交往中的障碍，从而有效促进跨文化交流。
**** 选择
***** A
****** 1
具备
****** 2
表达
****** 3
有益于
****** 4
人民
***** B
****** 1
含有
****** 2
再现
****** 3
有利于
****** 4
人员
***** C
****** 1
具有
****** 2
体现
****** 3
有助于
****** 4
人士
***** D
****** 1
富有
****** 2
展现
****** 3
有待于
****** 4
百姓
**** 答案
*** 23
**** 段话
我醒来发现自己躺在医院的病床上，有腹商着厚厚的纱布，疹得心[[gap]]发抖，慢慢地，我[[gap]]起，清晨，上学的路上，我被车撞了。看看床边，[[gap]]我的是爹爸。他的眼普布满了血丝，[[gap]]刚刚哭过，眼角还存留着未擦干的泪水。
**** 选择
***** A
****** 1
都
****** 2
回忆
****** 3
陪着
****** 4
好像
***** B
****** 1
在
****** 2
记忆
****** 3
看着
****** 4
如同
***** C
****** 1
还
****** 2
追忆
****** 3
伴随
****** 4
倒是
***** D
****** 1
仍
****** 2
回想
****** 3
护理
****** 4
曾经
**** 答案
** 第三部分
*** 段话
从前，有个人叫伯乐，[[gap:24]]。楚王派他去买一匹日行千里的好马。伯乐说：“良马世间少有，大王要耐心等待。”伯乐走了很多地方，没发现一匹中意的马。一天，伯乐走在山间，迎面过来一辆运盐的车，[[gap:25]]，吃力地走着。马累得呼呼喘气，每迈一步都很艰难。伯乐走到马跟前。马见伯乐走近，窝然昂起头来，睹大眼睛，大声嘶叫，好像要对伯乐诉说什么。伯乐立即从声音中判断出，[[gap:26]]。伯乐对驾车人说：“如果上战场，〕」短一]卫兰z子马，芳F]二荃〕[\/-诸F可[j』苄「你把它卖给我吧。”驾车人想：普普通通一毕马，拉车没气力，吃得又多，骨瘦如柴，还上战场呢！[[gap:27]]
伯乐回到楚国，把马交给了楚王。夷查王刁与山L不高兴，说：“这马走路都困难，能上战场团？”伯乐说：“这确实是匹十里马，只是拉了一段车，[[gap:28]]，才这么瘦。只要暇得好，很快就能恢复体力。”楚王将信将疑，和马夫精心喂养。不次，马变得精壮神勇，跑起路来像风一样快。
*** 选择
**** A
这是一匹难得的好马
**** B
又没有好好喂养
**** C
因会挑马而远近闻名
**** D
二话没说就同意了
**** E
一匹瘦弱的马拉着车
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
“哗啦”1客厅里不寻常的声响把我从烈睡中惊醒，不过迷迷糊糊中我义安下心来，有爸爸昵。没等我睡着，又是“哗啦”一声，这下我彻底醒了，努力晏开眼睬，想起我现在独自一人身在澳洲。我壮着胆孔爬起来，没敢开灯，一步步蹭到门边，把门拉开一条缝，看到地上的世界地图，心踏实下来，是风把增上的地图吹到地上了。放好地图，重新躺下，却再也睡不着了，脑海中出现的全是爸爸忙碌的面面。
小时候，我很淘气，虫然是个女孩孔，可天天疯跑，比男孩二还淘。天不怕地不怕的我只怕一个人一一爸爸。只要他冲我一瞥眼，我立刻就老实了，变成丁乖乖女。
爸爸心灵手巧，木工、电工、修理工，样桦精通，什么活儿都难不倒他，因此找他帮忙的人特别多，他也总是二话不说，高高兴兴地就去给人家忙活去了。我这个女儿却不像他，除丁学习还说得过去之外，干别的都笨手笨脚，爸爸常常在一边急得摇头。
爸爸有个很大的优点就是不重男转女，这在我们农村显得可特别了。我家只有我和妊妹两个孩子，爸爸总是开心地看着我俩说，没有男孩儿又怎样，我们的女儿也可以干得和他们一样好！爸爸要强，他知道我们姐妊书读得好，一心一意要塘养我们上大学。
我考上了大学，爸爸高兴得像个孩子。他满面春风，见人就炫耀。我明白了，我就是他的骄健。
**** 题目
***** 29
****** 问题
“我”熟睡时发生了什么事？
****** 选择
******* A
梦见我已身在国外
******* B
爸爸守在我的身旁
******* C
爹爸仍然在忙他的事
******* D
墙上的地图掉了下来
****** 答案
***** 30
****** 问题
“我”小时候：
****** 选择
******* A
不怕所有的人
******* B
只怕爸爸一个人
******* C
是个听话的女孩儿
******* D
喜欢跟男孩子一起玩儿
****** 答案
***** 31
****** 问题
以下哨一项符合爸爸的特点？
****** 选择
******* A
没什么本领
******* B
不喜欢男孩儿
******* C
越难的活越爱干
******* D
一心要培养好孩子
****** 答案
***** 32
****** 问题
最适合做上文标题的是：
****** 选择
******* A
我的爸爸
******* B
我的学习经历
******* C
爹爸呵护我成长
******* D
我是爸爸的骄健
****** 答案
*** 33-36
**** 段话
冉于眼普悦有先大性残疾，三个月大的陈燕被父母遗弃，是姥姥把她护回来，将她抚养成人。
姥姥知道陈燕无法重见光明，就想方设法开发陈燕的听觉和触觉。在陈燕刚会走路的时候，娃姥就教她靠听觉走路。为了培养陈燕辩别声音变化的能力，姥姥把五分硬币丢到地上让陈燕去找，但不许她在地上摸。还把一分、二分、五分硬币分别丢到地上，计她用耳朵来辨别币值。为锻炼小陈燕的触觉，姥姥要她练习穿针引线。对于一个盲童，穿针引线怕是过于艰隼了。陈燕左手挽着针眼，矶手捏着线头，往针眼里一次次不停地穿。起初半个小时穿一根，熟练之后两秒钟就可以穿一根了。正是这种不可思议的听觉和触克训绕，使陈燕与一般育人相比，有了许多过人之处：她会游沪，会骑自行转，甚
陈灿口小对甘乐感兴趣学过很多乐器。自打学调琴开始，她每天总是十三四个小时泡在钢琴边，仔细摸，用心记。学调律还必须会修琴，一个育人手侣锤孔钉钉孔、用则子则木头，受伤总是难免的。那段时间，她手上就没有一块好肉。
四看学习，陈燕掌握了最先进的钢琴调律技术，但满怀信心的她马上遭遇了残酷的现实，当时国内的人达无法接受相人调琴师。儿经周折，一家琴行才经过重重考核后同意录用她。
如今陈燕靠技术已经在调琴这个团子里闻出了名气。她将8000多个钢琴零件热记于心，并能及时发现影响音准的零件，调出正确的音律。到目前，她已给上万个家庭的钥萧做过调音，她用自己的行动实现了她的理想一一计全国人都知道，育人完全可以从事铜琴调律工作。
**** 题目
***** 33
****** 问题
姥姥为什么要努力开发陈燕的吻觉和触觉？
****** 选择
******* A
陈燕离开了父毒
******* B
陈燕的身体不好
******* C
陈燕永远看不到光明
******* D
陈燕和姥姥生活在一起
****** 答案
***** 34
****** 问题
姥姥是怎样训练陈燕的？
****** 选择
******* A
计她专门去护地上的钱
******* B
让她天天骑自行车上学
******* C
让她从小就学习做针线活
******* D
一开始就让她靠听觉走路
****** 答案
***** 35
****** 问题
为了学钢琴调律，陈燕：
****** 选择
******* A
先学会了修琴
******* B
整整学了13年
******* C
手经常会受伤
******* D
渐渐喜欢上了音乐
****** 答案
***** 36
****** 问题
根据上文，下列睇项正确？
****** 选择
******* A
陈燕身残志不残
******* B
陈燕是个音乐天才
******* C
姥姥从不为陈燕着想
******* D
姥姥的方法有些过头
****** 答案
