:PROPERTIES:
:CREATED: [2022-07-06 14:23:08 -05]
:END:

* Text
:PROPERTIES:
:CREATED: [2022-07-06 14:32:30 -05]
:END:


** 标题
:PROPERTIES:
:CREATED: [2022-07-06 14:34:57 -05]
:END:

爱的细节

** Content
:PROPERTIES:
:CREATED: [2022-07-06 14:32:33 -05]
:END:

电台要选出一对最恩爱的夫妻。对比后，有三对夫妻入围。

评委觉第一对夫妻说说他俩是如何恩爱的。妻子说，前几年他全身瘫痪了，医生说她站起来的可能性很小。别人都觉得她的丈夫会跟她离婚，她也想过要自杀。但丈夫一直豉励她，为她不和找了多少家医院。并且几年如一日地照顾她，从不抱怨。在丈夫的爱护和努力下，她终于又站了起来。她的故事十分感人，评委们听了都很感动。

随后进来的是第二对夫妻，他俩说，十几年的婚姻生活中，他们从来没为任何事红过脸、吵过架，一直相亲相爱、想敬如宾。评委们听了暗暗点头。

轮到第三对夫妻了，却很长时间不见人。评委们等得有些不耐烦，就走出来看个究竟。只见第三对夫妻仍然坐在门口，男人的头靠在女人的肩膀上，睡着了。一个评委要上前；喊醒那个男的，女的却伸出手指做了个小声的动作，然后小心地从包里那出纸笔，永久左手歪歪妞妞写下一行字递给评委，而她的右肩一直让丈夫的脑袋靠着。

** Note
:PROPERTIES:
:CREATED: [2022-07-06 15:28:48 -05]
:END:

I gave up at 15:28. Almost one hour typing this text.

** 笔记
:PROPERTIES:
:CREATED: [2022-07-06 14:33:03 -05]
:END:

电台 / dian4 tai2 / radio station ;
夫妻 / fu1 qi1 / husband and wife, married couple ;

** 生词
:PROPERTIES:
:CREATED: [2022-07-06 14:33:40 -05]
:END:

细节 / xi4 jie2 / detail ;
电台 / dian4 tai2 / radio station ;
恩爱 / en1 ai4 / (of husband and wife) loving ;
对比 / dui4 bi3 / to compare, to contrast ;
入围 / ru4 wei2 / to be shortlisted ;
评委 / ping2 wei3 / judge, member of a judging panel ;
如何 / ru2 he2 / how ;
瘫痪 / tan1 huan4 / to be paralyzed ;
离婚 / li2 hun1 / to divorce ;
自杀 / zi4 sha1 / to commit suicide ;
抱怨 / bao4 yuan4 / to complain ;
爱护 / ai4 hu4 / to take good care of ;
婚姻 / hun1 yin1 / marriage ;
吵架 / chao3 jia4 / to quarrel ;
相敬如宾 / xiang1 jing4 ru2 bin1 / (of husband and wife) to respect each other like guests) ;
暗暗 / an4 an4 / secretly, to oneself ;
轮 / lun2 / to take turns ;
不耐烦 / bu2 nai4 fan2 / impatient ;
靠 / kao4 / to lean against ;
肩膀 / jian1 bang3 / shoulder ;
喊 / han3 / to shout, to call ;
伸 / shen1 / to stretch, to extend ;
手指 / shou3 zhi3 / finger ;
歪歪妞妞 / wai1 wai niu3 niu3 / crooked, askew ;
递 / di4 / to hand over, to pass ;
脑袋 / nao3 dai / head ;
女士 / nv3 shi4 / lady, madam ;
叙述 / xu4 shu4 / to narrate ;
居然 / ju1 ran2 / indicating unexpectedness ;
催 / cui1 / to urge, to push ;
等待 / deng3 dai4 / to wait ;
蚊子 / wen2 zi / mosquito ;
半夜 / ban4 ye4 / midnight ;
叮 / ding1 / to bite, to sting ;
老婆 / lao3 po / wife ;
吵 / chao3 / to make a noise, noisy ;
项 / xiang4 / (used for itemized things) ;
患难与共 / huan4 nan4 yu3 gong4 / to share weal and woe ;
* 练习

** 1
:PROPERTIES:
:ID: b63c635f-bc9b-4cdd-aedd-d69014268265
:END:

*** 选择

**** 1

催

**** 2

递

**** 3

喊

**** 4

项

**** 5

爱护

**** 6

抱怨

**** 7

等待

*** 题目

**** 1

***** 句子填空

她从小就🟦小动物。

***** 答案

5

**** 2

***** 句子填空

关于这段对话，下面哪🟦是正确的？

***** 答案

4

**** 3
:PROPERTIES:
:ID: eb695219-3eb8-4cec-8d10-f182d659bd40
:END:

***** 句子填空

请大家耐心地🟦一会儿，不要🟦他。

***** 答案

7/1

**** 4

***** 句子填空

请把那本杂志🟦给我。

***** 答案

2

**** 5

***** 句子填空

火车快到的时候你🟦我一声。

***** 答案

3

**** 6

***** 句子填空

不要总是🟦别人，要想想能不能改变自己。

***** 答案

6

** 2

*** 1

**** 句子

你的病都好了吗？现在感觉🟨？

**** 选择

***** a

如何

***** b

怎么

**** 答案



*** 2

**** 句子

电视里广告太多让观众感到很不🟨。

**** 选择

***** a

耐心

***** b

耐烦

**** 答案



*** 3

**** 句子

这儿太🟨了，我们换个地方吧。

**** 选择

***** a

吵

***** b

吵架

**** 答案



*** 4

**** 句子

他这么年轻，没想到🟨是一位著名的作家。

**** 选择

***** a

居然

***** b

仍然

**** 答案


** 3

*** 1

**** 词语

如何

**** 句子

如果🟨是你🟨，你会🟨选择🟨呢？

**** 答案



*** 2

**** 词语

过

**** 句子

你跟🟨你的同屋🟨吵🟨架🟨吗？

**** 答案



*** 3

**** 词语

靠

**** 句子

🟨机会是要🟨自己努力🟨去🟨获得的。

**** 答案



*** 4

**** 词语

伸

**** 句子

请不要🟨把关🟨到车窗外🟨去🟨。

**** 答案



** 4

*** 第一行

**** 内容提示

第一对夫妻

**** 重点词语

离婚
自杀
抱怨
爱护

**** 课文复述



*** 第二行

**** 内容提示

第二对夫妻

**** 重点词语

婚姻
吵架
暗暗

**** 课文复述



*** 第三行

**** 内容提示

第三对夫妻

**** 重点词语

不耐烦
靠
喊
伸
催
等待
半夜
吵

**** 课文复述



* 扩展

** 词语

*** 1

**** 话题

人体

**** 词语

脑袋
脖子
肩膀
胸
腰
后背
手指
眉毛
嗓子
牙齿

** 题

*** 1

**** 句子

你的🟨好像一边高一边低，我建议你去买个双肩包。

**** 答案

肩膀

*** 2

**** 句子

早上起来，伸个懒🟨，真舒服！

**** 答案

腰

*** 3

**** 句子

他长着两条又黑又粗的🟨，一双大大的眼睛。

**** 答案

眉毛

*** 4

**** 句子

讲了一天的课，老师的🟨都疼了。

**** 答案

嗓子

** Note
:PROPERTIES:
:CREATED: [2022-12-14 21:20:01 -05]
:END:

从上表中选择合适的词语填空

HSK（五级）话题分类词语
