* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: b6580877-5b5a-4c52-83df-6b068b0946e9
:END:
**** 对话
***** 转录
男：我觉得马跑得那么快，跳起时四蹄应该都是不着地的。[[file:b544c0b3-854b-46bc-98df-9e39f6b9effd.mp3][(audio)]]
女：瞎说，要是四蹄都不着地，那不成了青蛙啦？[[file:eecf6227-a9ca-43ea-8a92-f8bc9e2727a5.mp3][(audio)]]
***** 音频
f94dcc7c-20a3-4252-91da-836652728aae.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
2f04837c-7db6-4972-a0b3-f42e916d8e43.mp3
**** 选择
***** A
马比青蛙跳得远
***** B
不着地时跑得快
***** C
马的四蹄都不落地
***** D
不会四蹄都不着地
**** 答案
D
*** 2
:PROPERTIES:
:ID: 0adf2fb1-3f16-4d91-a08f-27539e0e4ac7
:END:
**** 对话
***** 转录
男：刘经理，行李已经给您放车里了，咱们什么时候出发？[[file:93274b0f-3e49-4885-9fd6-3a6975a28735.mp3][(audio)]]
女：李师傅，登机牌我在网上都换好了。时间还早，您先去吃个饭吧。[[file:6afe21f2-0b62-4e77-8792-ad81eb3c9fe5.mp3][(audio)]]
***** 音频
099ad79d-2bb7-405a-8c7c-36a6532c7eba.mp3
**** 问题
***** 转录
女的准备要去哪儿？
***** 音频
050d0005-8a1b-405b-89ac-5d6cb8d18f6c.mp3
**** 选择
***** A
饭馆
***** B
公司
***** C
机场
***** D
火车站
**** 答案
C
*** 3
:PROPERTIES:
:ID: 5d7e8c85-68ef-4ce9-a7b4-f5364edf6662
:END:
**** 对话
***** 转录
男：小李，你这张婚纱照在哪儿照的？真不错！[[file:e81d689e-5759-4caa-8059-4c733603488a.mp3][(audio)]]
女：是我们去欧洲旅行结婚时，请摄影师拍的。[[file:6e6c78f7-b6a9-4680-bf84-6eb760bef41a.mp3][(audio)]]
***** 音频
2237b70f-8da6-4c0e-97e0-5975e0dd8f26.mp3
**** 问题
***** 转录
关于小李，下列哪项正确？
***** 音频
4a6344f0-cfef-4288-97ff-9fe0de986202.mp3
**** 选择
***** A
曾经去过欧洲
***** B
丈夫是摄影师
***** C
喜欢摄影艺术
***** D
做过婚礼主持
**** 答案
A
*** 4
:PROPERTIES:
:ID: 6a4074ec-5981-41fa-aafa-95b800ed1483
:END:
**** 对话
***** 转录
女：儿子来了个短信，说在路上耽误了，让我们再等一会儿。[[file:b92c0186-f823-4b8e-835b-e74f7f6128b5.mp3][(audio)]]
男：这孩子真不像话！这是什么日子，他还敢这么不当回事？[[file:e51c723e-cb03-4aba-b465-71dc52d11e27.mp3][(audio)]]
***** 音频
397d160a-e965-45d3-a4a4-5cf3501aaca2.mp3
**** 问题
***** 转录
男的说话时的心情怎么样？
***** 音频
fa996dc0-38bf-407b-bb8e-417d3ea9d668.mp3
**** 选择
***** A
紧张不安
***** B
非常生气
***** C
感到自豪
***** D
感到惭愧
**** 答案
B
*** 5
:PROPERTIES:
:ID: b83a8cf3-b741-47f9-b1b3-c4d9e1308912
:END:
**** 对话
***** 转录
女：最近忙什么呢？好长时间没看到你了。[[file:3716eeb2-aae8-4d19-9303-b1b26b77a456.mp3][(audio)]]
男：学院进了一批新电脑，这段时间忙着安装调试呢。[[file:09581477-80f9-415b-adc8-140000e11cbb.mp3][(audio)]]
***** 音频
8e22eb2f-6f46-4aa2-a642-1b224e63c813.mp3
**** 问题
***** 转录
关于男的，可以知道什么？
***** 音频
55464167-fe5b-45b9-96b0-ab0787b45dcf.mp3
**** 选择
***** A
电脑坏了
***** B
工作很忙
***** C
在学习电脑
***** D
买了新电脑
**** 答案
B
*** 6
:PROPERTIES:
:ID: 1b93265c-8397-4472-b9d2-a7c81901b4c5
:END:
**** 对话
***** 转录
男：电影频道播的一些原版电影，我很喜欢看。[[file:77277d43-c882-43cb-a06a-3f83618ab032.mp3][(audio)]]
女：我也喜欢，看着字幕，还可以练习一下英语。[[file:a791af3f-049a-44e7-8607-adf10a05427c.mp3][(audio)]]
***** 音频
2e616c4a-e566-4575-b812-e529f24d7101.mp3
**** 问题
***** 转录
关于女的，可以知道什么？
***** 音频
6d623697-b622-48a4-a164-cfa268d82c44.mp3
**** 选择
***** A
学过英语
***** B
爱看电视
***** C
视力不好
***** D
拍过电影
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
女：你看过动画片《大闹天宫》吧？
男：咱们小时候，谁没看过？在国内国际多次获过奖的，太经典了！
女：昨天，我儿子看了，他居然说不喜欢。
男：可能这就是时代的差距吧。
***** 音频
19dbdab1-6e7e-4714-8e5f-14b1be718a45.mp3
**** 问题
***** 转录
关于《大闹天宫》，可以知道什么？
***** 音频
89724698-3254-4239-ae3e-910aa82895eb.mp3
**** 选择
***** A
得过很多奖
***** B
儿二很喜欢
***** C
一直不被肯定
***** D
创作时间不长
**** 答案
A
*** 8
**** 对话
***** 转录
男：听你说话声音好像感冒了。
女：起床时觉得鼻子有点儿堵，嗓子也发干。
男：用盐水漱漱口，用吹风机吹吹脖子后边，注意别太烫。
女：这办法还没用过，管用吗？
男：感冒初期有效，严重了当然还得吃药。
***** 音频
33c81dd9-0235-4e17-9b0c-4346eadca898.mp3
**** 问题
***** 转录
男的建议用吹风机吹什么地方？
***** 音频
e574018f-3cc8-4294-88fb-b5e7c8f0ee0c.mp3
**** 选择
***** A
头顶
***** B
胶子
***** C
鼻子
***** D
嗓子
**** 答案
B
*** 9
**** 对话
***** 转录
女：你这条牛仔裤的颜色越洗越浅了。
男：是啊，褪色了。不好看了。
女：听人说，新的牛仔裤放浓盐水里泡半天，以后就不会褪色了。
男：下回咱们试试。
***** 音频
5ec65556-05fe-4164-bfea-fd6b347edb0e.mp3
**** 问题
***** 转录
关于牛仔裤，可以知道什么？
***** 音频
654715af-3f41-43c5-b002-1f1bbd8dddbf.mp3
**** 选择
***** A
男的想扔掉
***** B
磨出一个洞
***** C
颜色变浅丁
***** D
吃饭时弄脏了
**** 答案
C
*** 10
**** 对话
***** 转录
男：昨天我整理东西，有个意外的收获。
女：是吗？什么收获？
男：我居然找到考上大学时，姑姑送我的那块手表了，我一直以为丢了呢。
女：看起来你应该经常收拾一下房间。
***** 音频
0e74fd7f-e50f-4fb3-a2e1-67c09b612510.mp3
**** 问题
***** 转录
男的那块手表，是谁送给他的？
***** 音频
0f8ffdbe-cc0a-425e-a176-6d9097fb130e.mp3
**** 选择
***** A
外公
***** B
姑姑
***** C
舅舅
***** D
太太
**** 答案
B
*** 11-12
**** 对话
***** 转录
女：你的相机看起来挺不错，唯一的缺点就是重。
男：你说得没错，但我喜欢摄影，这点儿难题能克服。
女：你这相机多少钱买的？
男：加上镜头，一万五左右。
女：我这个手机才四千多，也有拍照功能，效果也不错，带着多方便。
男：手机怎么能和相机比？太不专业了。
***** 音频
9055a650-9761-433c-a058-deeb196aa5aa.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于男的，从对话中可以知道什么？
******* 音频
2e4e9bd5-c2c3-427b-882d-38e2ef060384.mp3
****** 选择
******* A
爱好摄影
******* B
不喜欢手机
******* C
从事摄影工作
******* D
受过专业培训
****** 答案
A
***** 12
****** 问题
******* 转录
女的对相机最不满意的地方是什么？
******* 音频
3cd93e3d-428b-4bce-bf52-b0c682871294.mp3
****** 选择
******* A
拿着太重
******* B
使用复杂
******* C
价钱太贵
******* D
功能简单
****** 答案
A
*** 13-14
**** 段话
***** 转录
现在的孩子“动”的时间越来越少。在家里，饭来张口，衣来伸手，基本不做家务；外出，上楼有电梯，出行有汽车；在学校，课间 10 分钟多被加课挤占，体育课的活动量过小或被挪作他用；有限的业余时间又多用在电脑上网、玩儿游戏机、看电视等静态的活动上，户外活动时间越来越少。据统计，60%的儿童肥胖和每天长时间坐在屏幕前有关。其实，玩儿是孩子们的天性，孩子在玩儿中得到快乐，也在玩儿中锻炼身体。如今，过多的作业、名目繁多的特长班和辅导班夺去了孩子们玩儿的权利。而家长们由于职场压力和工作负担，也谈不上做孩子们的玩伴了。
***** 音频
bad764e8-665c-4c07-a6f8-8ff2d05f4f42.mp3
**** 题目
***** 13
****** 问题
******* 转录
文中提到的“动”的时间，是指下列哪种时间？
******* 音频
a8b80de3-3da7-427e-841a-d4d6766c24d8.mp3
****** 选择
******* A
坐电梯的
******* B
上辅导班的
******* C
室外活动的
******* D
玩儿游戏机的
****** 答案
C
***** 14
****** 问题
******* 转录
根据本文，家长为什么不能成为陪孩子玩儿的玩伴？
******* 音频
ba49e38b-e132-40fc-9722-5b697ae78907.mp3
****** 选择
******* A
工作负担重
******* B
家务做不完
******* C
反对孩子玩儿
******* D
孩二作业太多
****** 答案
A
* 阅读
** 第一部分
*** 段话
有一个制作眼镜的荷兰人，名叫汉斯。李普希。一天，他的孩子们悄悄滢进他工作的地方，去摆弄那些玻璃透镜。其中一个孩孔拿起两片透镜[[gap][15]]“窗外望去。他非常吃惊地发现远处的教堂看上去竟然那么近、那么大，于是便叫父亲来看。父亲急忙跑来，[[gap][16]]，就这样，汉斯的儿子[[gap][17]]获得了一项重大发现。他发现如果把一个透镜贴近眼晴，而把另一个稍微远离眼普，那么远处的物体看上去就会大一些近一些。时隔不久，一位名叫伽利略的意大利科学家听说了此项发现，于是立即着手用两片透镜制造出了望远镜。
自伽利略于1609年制造出第一个望远镜后，科学家们陆续制造出更大更好的望远镜。正是望远镜打开了[[gap][18]]向天文世界的大门。有了它们，天文学家在太空中看得越来越远。
*** 题目
**** 15
***** 选择
****** A
对
****** B
朝
****** C
从
****** D
由
***** 答案
B
**** 16
***** 选择
****** A
好奇地让儿子解释
****** B
见此情景也非常吃惊
****** C
把儿子严肃地批评了一顿
****** D
耐心地安慰着急的儿子
***** 答案
B
**** 17
***** 选择
****** A
仍然
****** B
突然
****** C
果然
****** D
偶然
***** 答案
D
**** 18
***** 选择
****** A
通
****** B
飞
****** C
冲
****** D
去
***** 答案
A
** 第二部分
*** 19
:PROPERTIES:
:ID: a2b3e44d-c9e1-4099-83fa-cc181681e85a
:END:
**** 段话
经过艰苦的试验，电影拍摄技术逐渐改进、成熟。1895年12月28日，法国人卢米埃尔兄弟在巴黎第一次向公众播放了短片《火车到站》这一天后来成为电影产生的纪念日，兄弟俩也成为历史上最早的电影导演。
**** 选择
***** A
《火车到站》深受观众好评
***** B
最早的电影是在巴黎公映的
***** C
卢米埃尔发明了电影拍摄技术
***** D
1895年12月28日举办了第一届电影节
**** 答案
B
*** 20
:PROPERTIES:
:ID: 3927c2fc-37e7-4be8-bb73-7d39d99c26d6
:END:
**** 段话
年画是中国一种古老的民间艺术，同时也是中国社会历史、生活、信仰和风俗的反映。每逢过农历新年人们都会买几张年画贴在家里，差不多每家都是如此，由大门到厅房，都贴满了各种花花绿绿、象征吉祥富贵的年面，新春之所以充满欢乐热闸的气氛，年画在这里起着不小的作用。
**** 选择
***** A
年画主要贴在民居的大门上
***** B
年画为新年增添了喜庆的气氛
***** C
年画都用红纸剪成，象征着吉祥
***** D
年面反映了中国农村的社会生活
**** 答案
B
*** 21
:PROPERTIES:
:ID: 94c996e4-f5f9-490c-a172-b1103f931ae5
:END:
**** 段话
20世纪60年代还没有电脑制作，动画制作全靠手中的一支画笔。一般来说，10分钟的动画影片要画7000到10000张原动画，可以想见一部《大闹天宫》工程的巨大。整个原动画绘画阶段每天都在重复同样的工作，41分钟的上集和72分钟的下集，仅绘制原动画就耗时近两年。
**** 选择
***** A
仅靠手工绘制动画非常费时间
***** B
《大闹天客》的原动画大约有10000张
***** C
创作《大闹天宫》前后花费了近两年时间
***** D
《大闹天宫》的动画制作是利用电脑完成的
**** 答案
A
*** 22
:PROPERTIES:
:ID: 13dddd70-da90-41f1-8277-b1635af7d7b5
:END:
**** 段话
茶叶的种类很多，乌龙茶就是其中特色鲜明的一种。据说它是因创造人为清代人苏乌龙而得名，又因色泽青褐而称“青茶”。它是一种部分发酶茶，既不同于不发酵的绿茶，也不同于全发酵的红茶，性质介于二者之间。因为发酵不充分，因此乌龙茶既具有绿茶清香甘鲜的特点，又具有红茶浓香芬芳的优点，可谓吸取两者长处于一身，一个“香”字，赢得了众多茶人的喜爱。
**** 选择
***** A
青茶是乌龙茶中的一种
***** B
绿茶是一种全发酶的茶
***** C
红茶具有清香甘鲜的特点
***** D
尹龙茶兼具绿茶和红茶的优点
**** 答案
D
** 第三部分
*** 23-25
**** 段话
爱因斯坦出任荷兰莱顿大学特邀教授时，给学生讲的第一堂课是：成功的秘诀。
爱因斯坦拿着一个盒子走上讲台，从盒子里拿出一块又一块骨牌，在桌子上像搭积木一样地搭起来，搭到二十几块时，骨牌唉啦倒了，他不紧不慢地捡起来接着搭。当爱因斯坦搭到四五次时，平静的礼堂开始骚动。但爱因斯坦依然慢条斯理地搭了倒、倒了再搭……
30分钟过去了，学生们开始纷纷离去。也有学生帮爱因斯坦搭，这时他们发现，盒子里大约有50块骨牌，他们搭起不到40块就倒了。学生又一个个离去，只剩一名学生仍然固执地搭。又过了四一个小时，那个学生终于将50块骨牌全部搭了起来。
爱因斯坦高兴地开口了：“祝贺你成功了，有什么感想吗？”学生思考了一下，说：每搭一次，都有新的发现。“原来，他在搭时，发现有的骨牌略带磁性，能吸在一起，他就把带磁性的骨牌都搭在下面。倒了再搭时，他又发现骨牌轻重不一，他又把重的搭在下面，就这样反复几次，便全部搭了起来。
爱因斯坦说：“成功就是不断发现问题解决问题的过程，同时还要有足够的耐心去做，所以成功的秘诀就是：简单的事情重复做。”
那位搭骨牌的学生就是后来爱因斯坦的同事，美国著名物理学家、思想家和教育家——惠勒。
**** 题目
***** 23
****** 问题
爱因斯坦讲第一堂课时：
****** 选择
******* A
用骨牌盖房子
******* B
在桌子上搭骨牌
******* C
和学生们玩儿骨牌
******* D
讲骨牌的游戏规则
****** 答案
B
***** 24
****** 问题
根据本文，30分钟后，发生了什么情况？
****** 选择
******* A
学生把他赶出教室
******* B
学生们吵着要下课
******* C
有人搭起了全部骨牌
******* D
学生陆续离开教室
****** 答案
D
***** 25
****** 问题
爱因斯坦搭骨牌是想告诉学生成功的秘诀是：
****** 选择
******* A
要仔细观察事物
******* B
简单的事情重复做
******* C
要善于发现问题
******* D
耐心听别人的建议
****** 答案
B
*** 26-28
**** 段话
茅膏菜是一种外表漂亮的矮小植物，它们看上去那么小，似乎没有什么伤害力。它的叶子的边缘布满细小的绒毛，这些绒毛上沾着液体，看上去闪闪发亮。对昆虫而言，这种植物看上去像不错的食物。可是一旦昆虫降落在它的叶片上，叶边绒毛上的液体就会使其不能动弹。于是，茅膏菜就用自己的枝叶把昆虫包裹起来，继而吃掉它们。
很多年前，英国生物学家达尔文对这种茅膏菜很感兴趣。他很想知道这种植物除了昆虫是否还猎食其他的食物。于是他放了一些细小的烧羊肉在黏黏的叶子上，这种植物居然狼吞虎咽地把它们一扫而光。接着，达尔文试着把少量牛奶、鸡虾和其他细小的食物放到叶子上，茅膏菜对它们甚是喜爱，竟然来者不拒，统统吃光。
食肉植物有很多种，茅膏菜只是其中的一种。这些食'肉植物捕捉昆虫的方法各异。有些像茅膏菜一样，用它们细小的绒毛粘住猎物。有的则像猪笼草那样，用自身鲜亮的颜色吸引昆虫。当昆虫降落到猪笼草色彩鲜丽的花瓣上时，昆虫就会自行掉下去，然后滑进光滑的植物内部。猪笼草的底部是一个盛满液体的池子，其中的液体含有特殊的化学物质，能把昆虫分解成植物所需的营养。
狸藻类植物也是一种食肉植物，它们大部分生长在水中。这种植物的侧面都有一个活动的盖，当昆虫靠近狸藻的细小绒毛时，它的活盖板门就会打开，这样昆虫就会掉进去。
还有一种植物收集雨水，当昆虫前来喝水时，它们就不能逃开了。原因是这种植物上布满粉末，一旦昆虫沾上这些粉末就动弹不得。一位名叫德兰。菲什的科学家在一个花园的栅栏边放了四株这种植物，你知道吗？在短短八天的时间内，这四株植物竟然捕捉了136只昆虫！
**** 题目
***** 26
****** 问题
本文主要介绍的是：
****** 选择
******* A
茅膏菜
******* B
猪笼草
******* C
食肉植物
******* D
狸藻类植物
****** 答案
C
***** 27
****** 问题
达尔文观察后，发现茅膏菜：
****** 选择
******* A
只对昆虫感兴趣
******* B
特别喜欢烧羊肉
******* C
任何肉食都爱吃
******* D
不吃牛奶、鸡蛋
****** 答案
C
***** 28
****** 问题
德兰。菲什研究的植物靠什么捕食昆虫？
****** 选择
******* A
粉未
******* B
活盖板门
******* C
绒毛
******* D
底部的池子
****** 答案
A
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
