* 练习

** 1
:PROPERTIES:
:ID: 5873ffff-45ff-4010-bb0c-0605ce068ee0
:END:
*** 选择
**** 1
插
**** 2
系
**** 3
拦
**** 4
拍
**** 5
说服
**** 6
围绕
*** 题目
**** 1
***** 句子填空
你今天[[gap]]这条领带吧，比较正式。
***** 答案
2
**** 2
***** 句子填空
地球为什么会[[gap]]太阳转，一直是科学家们很感兴趣的问题。
***** 答案
6
**** 3
***** 句子填空
如果不是他在中间[[gap]]了一手，事情不会变成现在这样。
***** 答案
1
**** 4
***** 句子填空
这位导演[[gap]]过二十几部电影，得过好几项国际大奖。
***** 答案
4
**** 5
***** 句子填空
我始终没有办法[[gap]]他接受这个结论。
***** 答案
5
**** 6
***** 句子填空
前面不知道发生了什么事，路被[[gap]]住了。
***** 答案
3
** 2
*** 1
:PROPERTIES:
:ID: 191830df-95dd-4d6a-a4d2-416534a6ced4
:END:
**** 句子填空
在昨天举行的[[gap]]赛上，他的表现得到了大家的好评
**** 选择
***** A
争论
***** B
辩论
**** 答案
B
*** 2
:PROPERTIES:
:ID: 9b65c8ef-b8b9-460c-bf17-4cb667b93a94
:END:
**** 句子填空
毕业二十年以来，我们[[gap]]保持着联系。
**** 选择
***** A
始终
***** B
终于
**** 答案
A
*** 3
:PROPERTIES:
:ID: a603fbdc-cca0-485f-8553-796bd1e0a1be
:END:
**** 句子填空
我们之间还有很大的[[gap]]，我要向他学习，更加努力。
**** 选择
***** A
差距
***** B
距离
**** 答案
A
*** 4
:PROPERTIES:
:ID: 47dfd9bf-3349-4e48-8e4f-e37a55c7cab5
:END:
**** 句子填空
吃中餐[[gap]]西餐都可以，只是我不能吃太辣的。
**** 选择
***** A
或许
***** B
或者
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
我[[A]]都十八岁[[B]]，能照顾好[[C]]自己，您就放心[[D]]吧。
**** 词语
啦
**** 答案
B
*** 2
**** 句子
[[A]]是秋天了，[[B]]再热[[C]]也不会[[D]]像夏天那样。
**** 词语
毕竟
**** 答案
A
*** 3
**** 句子
这是[[A]]已经[[B]]经过很多人[[C]]证明的[[D]]经验。
**** 词语
成熟
**** 答案
D
*** 4
**** 句子
真心[[A]]希望[[B]]您能同意我的[[C]]，[[D]]帮我这个忙！
**** 词语
请求
**** 答案
C
* 扩展
** 词语
*** 话题
服饰
*** 词语
**** 1
围巾
**** 2
领带
**** 3
手套
**** 4
牛仔裤
**** 5
丝绸
**** 6
布
**** 7
耳环
**** 8
戒指
** 题目
*** 1
**** 句子
天气太冷了，你系条[[gap]]再出去吧。
**** 答案
1
*** 2
**** 句子
我们去年买的那双[[gap]]你放在哪儿了？
**** 答案
3
*** 3
**** 句子
今天不上班，不用穿西服，终于可以穿[[gap]]了。
**** 答案
4
*** 4
**** 句子
您觉得这条[[gap]]怎么样？当生日礼物送给您先生很合适。
**** 答案
2
* 注释
** （三）词语辨析
*** 显示——显得
**** 做一做
***** 1
****** 句子
他最近怎么了？总是[[gap]]不太高兴。
****** 答案
******* 1
******** 显示
0
******** 显得
1
***** 2
****** 句子
调查[[gap]]，只有37％的人愿意回到没有手机的时代。
****** 答案
******* 1
******** 显示
1
******** 显得
0
***** 3
****** 句子
节日的北京[[gap]]更加美丽。
****** 答案
******* 1
******** 显示
0
******** 显得
1
***** 4
****** 句子
你得[[gap]]出自己的本领，公司才会愿意用你。
****** 答案
******* 1
******** 显示
1
******** 显得
0
* 课文
** 转录
1872 年的一天，在美国加利福尼亚州的一个酒店里，斯坦福与科恩围绕“马奔跑时蹄子是否着地”进行了辩论。斯坦福认为，马奔跑得那么快，在跳起时四蹄应该都是不落地的；而科恩认为，马要是四蹄都不着地，那不是成了青蛙啦？应该是始终有一蹄着地。两人各执一词，争论得脸红脖子粗，谁也说服不了谁。于是他们就请英国摄影师麦布里奇来判断，可麦布里奇也弄不清楚。不过摄影师毕竟是摄影师，主意还是有的。他们一起来到一个操场，在一条跑道的一边等距离放上 24 个照相机，照相机对准跑道；在跑道另一边边打 24 个洞，分别插进 24 根木棍，木棍上系着细线，细线穿过跑道，接上相机快门。
一切都准备好了，麦布里奇让一匹马从跑道的一头飞奔到另一头，马一边跑，一边按顺序撞断拦路的 24根细线，相机连续拍下了 24 张相片，相邻两张相片的差距都很小。相片显示：马奔跑时始终有一蹄着地，科恩赢了。
事后，有人无意识地快速拉动那一长串相片，“奇迹”出现了：各张相片中静止的马连成了一匹运动的马，相片“活”了。这就是电影最早的样子。
经过艰苦的试验，电影拍摄技术逐渐改进、成熟。1895 年 12 月 28 日，法国人卢米埃尔兄弟在巴黎第一次向公众播放了短片《火车到站》，这一天后来成为电影产生的纪念日，兄弟俩也成为历史上最早的电影导演。
留心生活的每一瞬间，并为之争论，适时请求帮助、认真研究，或许重大发现就在你的眼前。
