* 听力

** 1

*** 1

**** transcript

宋末政治家、文学家、爱国诗人文天祥被关在牢房里，恶劣的环境只能折磨他的身体，却不能摧毁他的意志。就是在这间牢房中，文天祥写下了千古传诵的《正气歌》。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 2

**** transcript

博客从某个方面来说，已经不是一个私人圈子，而更像是一个言论堂，一个发表观点的地方。一般来说，博客谈论的是社会热门话题。其实，是先有论坛，后来因为用户想有自己的小天地，所以才产生了博客。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 3

**** transcript

汽车司机在封闭的高速公路上驾驶汽车时，基于合理信赖相信行人不会横穿公路，如果行人违反交通规则横穿公路而被正常行驶的汽车撞死，该汽车司机不承担过失犯罪的刑事责任。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

d

*** 4

**** transcript

谈起李敖，无论是他的敌人还是朋友都不得不承认他是一位奇人，他几十年来口诛笔伐、特立独行，坐过六年牢，打过几十场官司，一共有九十六本书被禁，创下了历史记录，但同时他又是千万人心中的偶像。



**** alternatives

***** a



***** b



***** c



***** d



**** answer

c

*** 5

**** transcript

在超市打工期间，她边打工，边读书，穿梭于校园和工作单位之间。她逐渐学会了如何最大限度地利用一天24小时的有限时间，如何面对工作考核和学校考试的双重压力，如何从容完成一个接一个的作业和论文。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

b

**  第二部分
:PROPERTIES:
:ID: cf24e400-3fb5-4000-9d47-dc0766f86685
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：您的网上书店开业以来，销量和好评率一直很稳定，您还开有实体书店。我们想知道，您是怎么与书结缘的？
男：与书结缘，是从少年时代开始的。那时家境贫寒，新书买不起，就打旧书的主意。80 年代初，小镇上有租连环画的摊子，一分钱，两分钱，就可以租看一本，我整天坐在小板凳上，慢慢品味，这种美妙的享受让我对书十分有感情。上学以后，我周末去的最多的地方就是书店。
女：那您最开始开书店和这份书缘有关？
男：是啊，那也算是我人生一个小小的转折点。那时我在南方打工，一个老乡知道我喜欢看书，告诉我去废品收购站可以买到非常便宜的旧书。我由此得到启发，决心开二手书摊。
女：您后来开了实体书店，卖的也是二手书吗？
男：对，我的书店不卖新书，只卖各种门类的二手书，这样一来，在售价上就比较有优势。当然，也不仅仅是价格优势，许多早年出版的书，在图书城是很难买到的，而在旧书店却有可能淘到。
女：您对深圳的状况很熟悉，能不能给我们说说那里古旧书的情况？
男：大家都知道，深圳是一座年轻的城市，是中国改革开放建立的第一个经济特区。深圳的古旧书市场并不是很理想，这大概与这座城市的年龄有关。但深圳二手书货源却相当充足，这也给我开设实体书店提供了帮助。如果我们把古旧书仅仅定义为多少年多少年以前的老书，那深圳的“货源”的确是个大问题，但如果把二手书都当作旧书来经营，深圳的货源充足到一听到有人打电话让我去收书，我就头痛，因为收回来没地方放，店租实在涨得太快，这也是我经营中最大的难题。
女：感谢您给我们讲了这么多有趣的事情，衷心祝愿您的书店越办越好！

*** 音频

6f6c7ea6-914b-4df4-8539-0af885e1fff5.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: d631cd9e-b7a0-45da-a3b8-4ccbaeead129
:END:

***** 问题

男的是怎样与书结缘的？

***** 音频

048556f2-2bf8-4268-977d-fce862557b12.mp3

***** 选择

****** A

从小对书就有感情

****** B

家里开了连环画摊

****** C

小时候买书很便宜

****** D

上学时在书店打工

***** 答案

A

**** 7
:PROPERTIES:
:ID: ae920c93-605e-4615-9786-5579c03b237f
:END:

***** 问题

男的在南方打工时发生了什么事情？

***** 音频

c203e5d9-0f7a-450a-b010-dd5545399e69.mp3

***** 选择

****** A

遇到了开书摊的老乡

****** B

在老乡的启发下开了书摊

****** C

老乡给他介绍了书店的工作

****** D

收废品时发现旧书可以敞开收

***** 答案

B

**** 8
:PROPERTIES:
:ID: 0b7d11f0-27ea-489d-94b5-53431074dd52
:END:

***** 问题

男的开的实体书店有什么特色？

***** 音频

9f804417-9bf5-424a-a625-045134c88529.mp3

***** 选择

****** A

书的进价很贵

****** B

书店制度完备

****** C

销售人员态度好

****** D

全部经营二手书

***** 答案

D

**** 9
:PROPERTIES:
:ID: b0d9d4ab-8aac-47ae-873a-88f858fa8b33
:END:

***** 问题

深圳是个什么样的城市？

***** 音频

9fa5efc5-b180-4c23-8f89-890bbb5ab500.mp3

***** 选择

****** A

深圳是个厚重的城市

****** B

深圳的历史不够久远

****** C

深圳能激发读书的激情

****** D

深圳的二手书货源不多

***** 答案

B

**** 10
:PROPERTIES:
:ID: 55641d59-5cc1-4975-8aa9-8f2830d6b896
:END:

***** 问题

关于男的，下列哪项正确？

***** 音频

00866bc5-2b69-4ef2-997a-50702c43b5b7.mp3

***** 选择

****** A

男的很受读者的爱戴

****** B

男的打工时收过废品

****** C

男的卖的书价格便宜

****** D

男的专卖古旧连环画

***** 答案

C

