* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: f8ea9fde-bf9c-44dc-a79c-39d858f3199b
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
60e8e9f4-f85a-44d6-b042-effa6c2caf20.mp3
***** 转录
在查找资料的过程中，我发现外国人对于经典老车的区分很明确。1919 年之前生产的汽车被叫作老爷车，之后生产的汽车叫古董车。单从这一点也可以看出，他们对于这些经典老车常常是怀着一份敬慕之情去看待的。
**** 选择
***** A
古董车的历史比老爷车长
***** B
外国人对车的评价十分经典
***** C
外国人对车怀有尊敬、仰慕之情
***** D
老爷车和古董车的区别在资料中有记载
**** 答案
D
*** 2
:PROPERTIES:
:ID: 15a5c960-0f98-495d-b37c-6de72dcca973
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
a0347b39-9217-4366-b98b-65f9171f3315.mp3
***** 转录
消费者不应该只把眼睛盯在哪种商品价格升了或是降了，支出多了还是少了，而应用心研究“钱”的购买力、“钱”的潜在价值还有哪些，只有这样，才能真正做到精打细算，花多少钱办多少事。
**** 选择
***** A
消费者应该处处精打细算
***** B
东西涨价，就会增加支出
***** C
钱的潜在价值比商品价格更重要
***** D
精明的消费者能够少花钱多办事
**** 答案
C
*** 3
:PROPERTIES:
:ID: 9126df09-0bd2-4239-b97f-e38f308c3498
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
13e4aa8d-6584-4a8b-aafd-b31d04758bae.mp3
***** 转录
对包装，人们提出了“绿色”的要求，希望它在保护环境和资源利用两方面都符合可持续发展的特征。即该种包装源于自然，能与自然融为一体，对生态环境和人类健康无害，能重复使用和再生。
**** 选择
***** A
绿色包装对人体健康无害
***** B
绿色包装的颜色都很自然
***** C
绿色包装不支持重复使用
***** D
绿色包装都使用再生资源
**** 答案
A
*** 4
:PROPERTIES:
:ID: 526577e8-37e8-47b7-a1c6-7294ab215fb0
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
e082c0c1-99be-484a-b045-3dbc37b48e60.mp3
***** 转录
春节后是员工跳槽的高峰期，也是中国企业招聘的高峰期，一是会有员工离职，二是有些部门对人员有新的需求。作为部门经理，这时就应该对人员变动提前做好预期和准备，以免临时抓瞎。
**** 选择
***** A
春节后是公司生产的旺季
***** B
春节后单位人员流动很大
***** C
很多部门经理工作抓得不够紧
***** D
公司应事先掌握人员变动情况
**** 答案
B
*** 5
:PROPERTIES:
:ID: 0e8efd24-6ec2-45d3-906b-1080830058ac
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fa47ca5c-7305-43b3-b793-1c304c31c3af.mp3
***** 转录
我见过许多成就颇高的华人文化艺术家，这些人往往是一袭中式对襟衣裳，神情淡定，举止儒雅。那种气质和风度，令人倾倒。我深信，文化就是蕴含在举手投足之间的秘密，这些生命与文化的密码，是任何形式的全球化都无法改变的。
**** 选择
***** A
我访问过许多艺术家
***** B
全球化包括文化交流
***** C
艺术家的一举一动都有文化烙印
***** D
艺术家的气质、风度很令人信任
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 20b7b77a-ed15-491c-97c6-1d1ac47d4c03
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
5deea55f-92c4-4ad6-af82-233b16e46e5d.mp3
***** 转录
女：大家好，在热闹的娱乐圈里，陈老师算是位特立独行的人物，演戏之余，往往深居简出，即使不得不参加一些公开的宣传活动，也是惜字如金。于是，一些人说他是典型的“孤芳自赏”“冷漠清高”，不过陈老师本人却觉得自己很委屈，也许是为了证明自己并不那么各色，他同意接受我的访问。您是不是一直有意识地使自己和这个圈子保持一定的距离？
男：我不是有意识的，在圈子里也有不少谈得来的朋友，但是我不喜欢动不动就上酒桌，我一上这个酒桌就觉得是一种煎熬。
女：没话说？
男：没话说，因为我本人不喝酒。尤其有这么一两次，当一个人喝醉酒，一个主题、一句话跟你说五遍的时候，我就感到窝火，头脑就会冲动，心里充满难以抑制的愤怒。
女：平常的潇洒劲儿也没了，觉得是别人强加给您的？
男：对。你还得客客气气地对他，好好听着。他跟你说五遍，一个名片递你八张。这时候我就觉得特别烦。
女：那跟什么样的人说话越来越多呢？
男：可能跟我自己对话多一些，我经常反问自己一些问题。
女：问自己什么问题呢？
男：其实仔细想一想，包括现在社会一天到晚在强调竞争，往往就忽略和忘记了独处的美好。
女：美好在什么地方？
男：我觉得是自我净化，自我调教，自我教化，在独处当中我才能够真正安安静静地去思考。我喜欢自己支配自己的时间。
女：那您靠什么来排解自己的压力和情绪呢？
男：我有第二支点，就是弹钢琴。我把弹钢琴当作自己情绪的抒发口。
女：不同情绪的时候弹不同的曲子？
男：对，我弹钢琴时面对一扇窗，从那扇窗可以望见天空，我经常会坐在钢琴前面，一边弹琴，一边使目光穿越窗口，用心跟一片片白云对话。
**** 题目
***** 6
:PROPERTIES:
:ID: 5f856b35-21ee-4cd6-bd75-2c7d5c5c2f43
:END:
****** 问题
******* 音频
98aef0a0-84f4-466e-beaa-ba9df13b0ce9.mp3
******* 转录
男的为什么接受这次采访？
****** 选择
******* A
他非常欣赏这位记者
******* B
他不愚再冷漠下去了
******* C
他觉得别人误解他了
******* D
他演完戏后有时间了
****** 答案
C
***** 7
:PROPERTIES:
:ID: eb766336-c3be-4eab-8c8f-4eb0193ae15c
:END:
****** 问题
******* 音频
76237e77-a79e-458d-be51-6a0e965835f0.mp3
******* 转录
女的所说的“这个圈子”指什么？
****** 选择
******* A
娱乐圈
******* B
谈话圈
******* C
记者圈
******* D
百姓圈
****** 答案
A
***** 8
:PROPERTIES:
:ID: 93a54d20-60cc-4508-9ae0-5b7ef97b94f2
:END:
****** 问题
******* 音频
a6d228a3-1b29-402a-b299-d274ca107e95.mp3
******* 转录
为什么男的一上酒桌就觉得煎熬？
****** 选择
******* A
他对喝酒没兴趣
******* B
他本来话就不多
******* C
他痛恨别人唷唆
******* D
他怕自己喝醉了
****** 答案
A
***** 9
:PROPERTIES:
:ID: c42ee668-2434-4539-858c-a8c4eff9dca5
:END:
****** 问题
******* 音频
869aeeaa-a439-4558-9c44-aacac0191dea.mp3
******* 转录
男的为什么喜欢独处？
****** 选择
******* A
可以赢得竞争
******* B
可以静心思考
******* C
可以排解压力
******* D
可以听钢琴曲
****** 答案
B
***** 10
:PROPERTIES:
:ID: 5d4c771a-2656-4976-84d4-e861d4fe9102
:END:
****** 问题
******* 音频
6284eb64-cf1b-4fc2-b6e7-8cdecb0ad824.mp3
******* 转录
关于男的，下列哪项正确？
****** 选择
******* A
他只懂得自我欣赏
******* B
他的性格非常冲动
******* C
他很冷漠看不起人
******* D
他喜欢安静和思考
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: d8631c0f-f9a0-43b7-ad38-0cd2e67a08ae
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
317336bc-954b-468b-91a4-08bd18870bdb.mp3
***** 转录
无论是摄影还是旅行圈子，火车迷都为数不少。王嵬对于火车、对于铁路的喜爱，源于小时候家住火车站附近，铁路就从他家楼下经过，趴在阳台上观察来往的火车是小王嵬最喜欢的游戏，后来，他变成了十足的“火车迷”。他观察火车、画火车、研究火车的车型和运动原理、关注铁路的历史和建设，他设想过自己当上了火车司机，也觉得造火车的工作很不错，没想到的是，如今他举办了铁路题材的个人摄影作品展。
这张拍摄于卓资山的照片是王嵬最喜欢的作品之一。他还记得这里的地形特点是多山、多丘陵、少平川，景色富于变化，非常美丽，火车蜿蜒穿行其间，又给这份景色平添了一份硬朗的动感。
为了拍出火车经过那里所呈现的大曲线的美感，王嵬多次前往，仔细研究卓资山大曲线的拍摄角度，最终在大曲线北端的高山上将曲线的“S”形整个收入到画面中。后来，随着穿山隧道的投入使用，卓资山大曲线完成了它的历史使命，不再有列车通行。他的这张照片承载的也就不光是一份美，还有着一段沉甸甸的历史了。
**** 题目
***** 11
:PROPERTIES:
:ID: cee9c0ca-3d2a-4c04-bfac-64f9627d96ec
:END:
****** 问题
******* 音频
ba5ccd58-aa7b-4fcc-a179-68baf63c6a82.mp3
******* 转录
王嵬的职业是什么？
****** 选择
******* A
摄影家
******* B
旅行家
******* C
火车司机
******* D
火车维修员
****** 答案
A
***** 12
:PROPERTIES:
:ID: ee28f243-4fc7-4e91-aa97-74e12e687402
:END:
****** 问题
******* 音频
527d2a3e-d950-4ff6-90b4-bb8e0476481a.mp3
******* 转录
小王嵬成为“火车迷”的原因是什么？
****** 选择
******* A
他天天在铁路边玩耍
******* B
他爸爸是一个火车迷
******* C
他每天观察来往的火车
******* D
中国铁路发展史吸引了他
****** 答案
C
***** 13
:PROPERTIES:
:ID: 94439696-564f-4cf0-ac3c-7d8c8e14dda0
:END:
****** 问题
******* 音频
2d3a8fe1-73f7-4047-9c6d-cd8290a27148.mp3
******* 转录
关于王嵬拍摄于卓资山的照片，下列哪项正确？
****** 选择
******* A
王鬼始终拍不全完整的曲线
******* B
王棣的照片被选人了历史书
******* C
火车穿越隆道时要走S型线路
******* D
卓资山大曲线现在已经废弃丁
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: 65c110b7-8444-4b0d-a9ed-f588bf795418
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
128c58bb-41ad-4513-9f9e-571570c80d5a.mp3
***** 转录
从前，森林里生活着一群熊，它们食物充足，无忧无虑。突然有一天，森林着火了，它们的家园被烧光，食物没有了来源。这时，一部分熊说：“我们去北极吧，说不定那里有我们的天地。”另一部分则反对说：“不行，那里气候严寒，说不定我们会冻饿而死。还是找个近点儿的地方吧。”熊们争论到疲惫至极也没有结果。最后，一部分熊去了北极，一部分熊去了四季温暖、草木葱郁的盆地。
到了北极的熊学会了在冰冷的海水中捕鱼捉虾，甚至和比自己大的海豹搏斗，结果它们进化成高大凶猛的北极熊。到了盆地的熊发现，这里的食肉动物太多了，它们根本抢不到食物，于是它们改吃草；可是，更加意外的是，这里食草动物也多，它们连草也抢不到，于是它们改吃别的动物不吃的食物——竹子，这才勉强生存下来，成了人们天天念叨的濒危动物——熊猫。
竞争每天都在发生，如果一味地逃避，唯一的结果就是被淘汰出局。因此要勇敢地走在风暴的前面，敢于主动超越自己，只有这样，才能不被别人淘汰，让自己成为那个走在最前面的乘风破浪的勇士。
**** 题目
***** 14
:PROPERTIES:
:ID: a6f9e90f-7a68-4140-9507-35623a70c663
:END:
****** 问题
******* 音频
67699a06-9137-40df-99c7-15d725597a41.mp3
******* 转录
关于熊，可以知道什么？
****** 选择
******* A
它们只会争论,不懂团结
******* B
它们只适合在森林中生活
******* C
火灾破坏了它们平静的生活
******* D
它们本不该把家安在森林里
****** 答案
C
***** 15
:PROPERTIES:
:ID: 6ec7a3a7-c08f-4007-a0fd-e4559383c43c
:END:
****** 问题
******* 音频
fef482ca-2c2b-40c3-b438-9c04b4b59bcf.mp3
******* 转录
关于北极熊，可以知道什么？
****** 选择
******* A
它们打不过海豹
******* B
它们变得强悍了
******* C
它们爱上了鱼虾
******* D
它们改成了吃草
****** 答案
B
***** 16
:PROPERTIES:
:ID: 089b6895-3511-4f50-8783-c78bc3223206
:END:
****** 问题
******* 音频
87a7acfb-51f0-4a81-8b46-859a3476fc2b.mp3
******* 转录
到了盆地的熊生活得怎样？
****** 选择
******* A
它们不断发扬奉献精神
******* B
它们和其他动物争夺食物
******* C
它们找到了最爱吃的竹子
******* D
它们变成了被抢救的濒危物种
****** 答案
D
***** 17
:PROPERTIES:
:ID: 451738bd-8e1d-4330-a324-b822522b5614
:END:
****** 问题
******* 音频
49670ccb-42ac-4ce6-9202-f5696265e357.mp3
******* 转录
根据这段话，下列哪项正确？
****** 选择
******* A
要敢于迎接挑战
******* B
要勇敢面对失败
******* C
要愚重做出决定
******* D
要保护弱势群体
****** 答案
A
* 阅读
** 第一部分
*** 18
**** 句子
***** A
整部书的完成是我一边采访一边写作的状态下完成的。
***** B
旅行团一到，好马很快就被抢光了，我们只能将就了，否则就没马骑。
***** C
从纪录片产生到今天，纪录片的资金筹措问题从来就没有得到过解决。
***** D
科学地确定发展模式和奋斗目标，是时代向我们提出的刻不容缓的任务。
**** 答案
*** 19
**** 句子
***** A
“糠瓜”是这里过年流行的美食。
***** B
有人认为，过年觉得没意思也许跟年味逐年冷淡有很大关系。
***** C
老汉不善言辞，但讲起制作松鼠鱼繁复的过程，他立刻滔滔不绝。
***** D
这个徽州女人和她不太会讲话的儿子，把这家豆腐房经营得红红火火。
**** 答案
*** 20
**** 句子
***** A
这一改革措施必将引起城市内部一系列的连锁反应。
***** B
儿年来，他一有机会就鼓动我跳槽，让我辞了现在仍从事的这份工作。
***** C
唐朝的很多王公将相，甚至连唐太宗的皇后长孙氏，都出身于少数民族。
***** D
当这些美食放大许多倍呈现在大银幕上时，的确产生丁震撼的昧觉效果。
**** 答案
** 第二部分
*** 21
**** 段话
孩子参加劳动，既是学习过程，又是[[gap]]过程，在这个过程中自然会有成功和失败。这就要求父母鼓励孩子[[gap]]囱难，建立信心和决心，学会做自己的事情。
**** 选择
***** A
****** 1
磨炼
****** 2
打赡
****** 3
随心所欲
***** B
****** 1
磨合
****** 2
无视
****** 3
得心应手
***** C
****** 1
锻炼
****** 2
战胜
****** 3
力所能及
***** D
****** 1
练习
****** 2
克服
****** 3
无能为力
**** 答案
*** 22
**** 段话
表情是[[gap]]的外部表现，有的表情是人类生物学性质的本能表现。一般婴儿会毫不[[gap]]地表露自己的情绪，[[gap]]则根据社会的要求调整其情绪表现方式。儿童从2岁开始就能够用表情手段去[[gap]]别人，并学会在不同场合用不同方式表达同一种情感。
**** 选择
***** A
****** 1
情绪
****** 2
保留
****** 3
以后
****** 4
影响
***** B
****** 1
心境
****** 2
保守
****** 3
后来
****** 4
管理
***** C
****** 1
感情
****** 2
在意
****** 3
然后
****** 4
感化
***** D
****** 1
心情
****** 2
保密
****** 3
往后
****** 4
感染
**** 答案
*** 23
**** 段话
我们[[gap]]会碰到这样的老人：他们总怕儿女不会[[gap]]自己，要竭尽全力地为他们操劳；他们茵要丈比家里的犬韦小慌生怕缺了他们一切变得[[gap]]。他们以为这就是爱，实际上这种捆绑关系往往会造成灾难性的[[gap]]，因为孩子往往不喜欢你太多地唠叨。
**** 选择
***** A
****** 1
时常
****** 2
照顾
****** 3
一团糟
****** 4
后果
***** B
****** 1
不时
****** 2
看护
****** 3
乱哄哄
****** 4
结果
***** C
****** 1
曾经
****** 2
关照
****** 3
乱糟糟
****** 4
苦果
***** D
****** 1
迟早
****** 2
照料
****** 3
乱腾腾
****** 4
成果
**** 答案
** 第三部分
*** 段话
赤道为低气压区，由赤道两侧吹向赤道的东北信风和东南信风，驱动赤道南北两侧的海水由东向西流动。[[gap:24]]，南面的称为南赤道暖流。歹苯1」…l亘忙l7夏之捡千五至‖〕丕员更/刁仝官邗可岸日寸受陆地阻挡，其中一小股回头向东形成赤道逆流；大部分受地转偏向力的影响，沿海岸向较高的纬度流去，至中纬地区受西风吹动形成西风漂流。[[gap:25]]，一部分沿大陆西岸折向低纬，成为赤道暖流的补偿流；另一部分沿大陆西岸折向高纬，构成极地环流。
赤道是物种的制造厂。与其他未能这么幸运地享受到这一地理位置优势的物种相比，[[gap:26]]，无论从温度、湿度还是从可获取的食物来看，都是如此。生活在这片乐土上的唯一不不]丨人丨言掌[[gap:27]]！
在赤道，动植物比其他地方的动植物长得更快、更大，而且外形更怪异。[[gap:28]]。由于这里的阳光使海洋大量蒸发，这种冲击会在这样一个大范围中形成湿度柱，互亚而形成风禾丨〕乞替{冢贡宽，而风和潜流随后会最终给位于异常遥远的地方的生命提供能量。
*** 选择
**** A
赤道动物简直是生活在一个近乎完美的环境中
**** B
赤道地区的阳光是地球上最强劲的能量
**** C
北面的称为北赤道暖流
**** D
当它们到达大洋东岸时
**** E
就是要与地球上半数以上的物种分享资源
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
上小学的迪士尼是个聪明调皮的小男孩，他在文学和绘画方面有着惊人的天分。不到十岁，他便读完丁马克.吐温的《汤姆.索亚历险记》等名著，老师的绘画作业，他每次都能完成得十分出色。
一次，老师给大家留的作业是画一盆花。在迪士尼手下，不光花朵变成了人脸，花形的人脸还有各种不同的表情，花朵下面的叶子被画成了人手，最下面的花盆变成了一把小椅子。这样，整帽画看上去既像是一盆花，又像是一群坐在小椅子上手舞足蹈的孩子。
老师看到迪士尼的画儿既惊奇又生气，他不认为这是孩子的开拓性思维，反而认为他是在胡闸，于是当众把迪士尼的画按得粉碎，还把他批评了一顿。满肚子委屈的迪1士尼回到家中，把这件事告诉了父亲。父亲说：“孩子，不能学握白己命运的人终生都会是一个奴隶。”幼小的迪士尼不能完全理解父亲的话，却隐约感到父亲是支持自己的。
迪士尼长大了，一有空闲，他就创作一些画儿寄给杂志，虽然层层遭遇退稿，倔强的迪士尼却是属败层战。1923年，迪士尼与哥哥毅然合作成立了“迪士尼兄弟公司”，在好莱坞一家房地产公司废弃的仓库里度过了最初的艰难后，他们创作的米老鼠和唐老鹄横空出世，迅速享誉世界。
**** 题目
***** 29
****** 问题
和第1段画线词语“天分”意思最相近的是：
****** 选择
******* A
成绩
******* B
想法
******* C
能力
******* D
天资
****** 答案
***** 30
****** 问题
迪士尼的老师：
****** 选择
******* A
急了就拿孩子撒气
******* B
讨厌拿作业开玩笑
******* C
不能理解孩子的心灵
******* D
鼓励孩子发挥创造性
****** 答案
***** 31
****** 问题
关于迪士尼，下列睇项正确？
****** 选择
******* A
创办过一家美术杂志社
******* B
小学老师给他的打击很大
******* C
曾经开过一家房地产公司
******* D
能捕捉到父亲语言中的积极因素
****** 答案
***** 32
****** 问题
上文主要介绍的是：
****** 选择
******* A
迪士尼的成长过程
******* B
迪士尼的不幸遭遇
******* C
迪士尼有个好父亲
******* D
“迪士尼兄弟公司”的由来
****** 答案
*** 33-36
**** 段话
人们往往容易低估别人的工作难度，以为对方的工作是极易完成的。这往往会体现在一个有多种职务的公司里，员工们的评论总是偏向自己，比如搞技术的可能会埋怨摘销售的没有把自己创造的产品卖得更好，搞销售的会埋怨搞技术的没有设计出更好的产品，他们都觉得和自己比，别人相差太远。
一位足球教练曾经这样描述一些站着说话不腰疹的球迷：“他们坐在看台上，看着球场里的运动员无法把球传给几米外的队友，会气急败坏地抱怨场上的运动员，因为他们觉得这么轻而易举的事对方都做不到。”是什么导致人们总以为别人的工作比较轻松？有研究显示，这一现象是人的正常心理和生理反应，经考察，其神经学上的根据就是，大脑的运作方式让人们得出了“别人比自己轻松”的判断。
当人们观察别人做树件事情时，观察者的运动神经系统会仿真对方的行为。这一仿真行为可以帮助观察者理解对方的动作、用意与目标。但这种仿真往往会出现偏差，毕竟观察者是在想象，需要有什么结果，一想就获得了，所以觉得该项工作做起来并不难。然而，如果让观察者去做一件事，他的动作就会干扰自己的大脑产生理解上的差别，认为自己的工作有难度，而且自己既用功又勤奋。最直观的例子就是：假设你是一名工人，整天在生产线上忙碌地装配产品，那么，你肯定看身旁那些在设备旁晃来晃去的技术人员不顺眼，总觉得自己在拼命工作，他们却在混日子。
这个研究的意义是重大的，它可以促进人们的相上理解，尽量消除自己的大脑对别人工作产生的误解，减少负面情绪的产生和释放。
**** 题目
***** 33
****** 问题
在有多种职务的公司里，往往会发生什么情况？
****** 选择
******* A
员工容易工作偷懒
******* B
员工经常互相鼓励
******* C
员工工作挑肥拣瘦
******* D
员工认为别人不努力
****** 答案
***** 34
****** 问题
足球教练的描述说明什么？
****** 选择
******* A
看球容易让人生气
******* B
教练也常被人误解
******* C
腰疹的球迷看不懂球
******* D
球迷常低估球员传球的难度
****** 答案
***** 35
****** 问题
当我们观察别人做某事时会：
****** 选择
******* A
进行仿真的心理体验
******* B
充分发挥自己的想象
******* C
大脑的理解能力变差
******* D
无法摆脱负面情绪的误导
****** 答案
***** 36
****** 问题
第2段画线词语“转而易举”的意恩是：
****** 选择
******* A
只有自己能做
******* B
事情很容易做
******* C
结果来之不易
******* D
稍微用心就行
****** 答案
