* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: e530bb2a-f8a4-411c-a6a3-f8c845990d76
:END:
**** 对话
***** 转录
女：我不是催你，只是想告诉你一声，我已经到了。[[file:5f78cb3d-6e24-42ae-9af8-78dddb19f24b.mp3][(audio)]]
男：啊？你都到啦！这才几点哪？[[file:a4115465-10cb-4533-bfcc-601f5b685168.mp3][(audio)]]
***** 音频
5362ec23-e92a-4cc7-84b7-e726a8f24ad3.mp3
**** 问题
***** 转录
从对话中可以知道什么？
***** 音频
99627aec-a595-484e-b25a-f70ea45397b7.mp3
**** 选择
***** A
女的来早了
***** B
男的迟到了
***** C
女的让男的快来
***** D
男的记错时间了
**** 答案
A
*** 2
:PROPERTIES:
:ID: 5f280912-3e02-47ed-a4cc-689be925fb51
:END:
**** 对话
***** 转录
女：你不是说今天有会要早点儿去单位吗？怎么还不走？[[file:28c407d5-f47f-4d0f-8fe3-3f1f91ceba8a.mp3][(audio)]]
男：刘总昨天临时有事去上海了，会取消了。[[file:5469361c-205a-4793-896f-59c0dc7014f8.mp3][(audio)]]
***** 音频
4e56e9b6-d014-417b-bcff-1da36bbf09e3.mp3
**** 问题
***** 转录
根据对话，男的怎么了？
***** 音频
e055bb6d-ce0b-4e88-8272-ddf3cb885532.mp3
**** 选择
***** A
今天不去单位
***** B
昨天去上海了
***** C
不用去开会了
***** D
上班迟到了
**** 答案
C
*** 3
:PROPERTIES:
:ID: 8e1e124c-d140-4f52-9491-d08a5e54e43a
:END:
**** 对话
***** 转录
男：妈妈，你看天阴得多厉害，这雨肯定小不了，下午篮球[[wikidata:L1144569-S1][训练]]还能进行吗？[[file:22100e25-c29f-4af5-8ee3-34c1b42fdd29.mp3][(audio)]]
女：现在都是[[wikidata:L1144572-S1][雷阵雨]]，[[wikidata:L1144573-S1][说不定]]一会儿就停了。[[file:f6c08f81-26ab-4caa-b891-ca9018ef5242.mp3][(audio)]]
***** 音频
10761af3-254b-4ed1-9e53-76ce08ae822e.mp3
**** 问题
***** 转录
妈妈觉得下午的[[wikidata:L1144569-S1][训练]]最可能怎样？
***** 音频
b227f3e8-65e9-4681-8592-b8f4e8814035.mp3
**** 选择
***** A
改天进行
***** B
照常训练
***** C
改在室内
***** D
[[wikidata:L1144574-S1][被迫]]取消
**** 答案
D
*** 4
:PROPERTIES:
:ID: 46ea1650-fc38-4215-9e50-50d0981daf13
:END:
**** 对话
***** 转录
男：真佩服你丈夫。[[file:96c7d8e8-2606-421f-aaa0-d51315f07563.mp3][(audio)]]抽了 20 多年的烟，说戒就戒了。[[file:338b7c6d-d295-4125-9c7b-e938a5dba301.mp3][(audio)]]我也一直想，可到现在也没戒掉。[[file:5a9a5a6e-19f3-4797-b122-ca774d4b0f44.mp3][(audio)]]
女：其实很简单，关键就看你有没有决心。[[file:e5dbb36f-d221-434f-bb84-358322c978d3.mp3][(audio)]]
***** 音频
9f0be1e0-c60a-4fcb-9014-a1c38f6da54a.mp3
**** 问题
***** 转录
关于戒烟，可以知道男的什么情况？
***** 音频
fb71ed41-f623-4a63-a46d-9cc6fb06ea36.mp3
**** 选择
***** A
刚开始戒
***** B
一直想戒
***** C
有点儿犹豫
***** D
成功戒掉了
**** 答案
B
*** 5
:PROPERTIES:
:ID: e2594cb5-7c72-49ab-a9bc-e14b3513405e
:END:
**** 对话
***** 转录
男：小区的中心广场安装了很多健身器，你没事也去锻炼锻炼吧。[[file:1c4e872c-feb7-4d8c-b50f-a8dd1e62a565.mp3][(audio)]]
女：等我把这集电视剧看完了再说。[[file:baf4d6fe-26b3-4173-82f2-88012311be1b.mp3][(audio)]]
***** 音频
89408c37-9284-4e7d-a966-b34469458f45.mp3
**** 问题
***** 转录
男的让女的做什么？
***** 音频
12091108-143a-4f8f-af88-ab37553b69b7.mp3
**** 选择
***** A
安装电脑
***** B
出去散步
***** C
运动健身
***** D
看电视剧
**** 答案
C
*** 6
:PROPERTIES:
:ID: 44b47f73-a531-42cd-b23b-59aee98b8868
:END:
**** 对话
***** 转录
男：小刘，你帮我看看，这个复印机出什么问题了？印着印着就停了。[[file:aa33014c-617b-45e2-a6dc-e1dd972733e9.mp3][(audio)]]
女：这个指示灯亮了，就说明没纸了，要重新装纸。[[file:29d70c3b-cfdf-402b-bd64-6d1dad2335a2.mp3][(audio)]]
***** 音频
304ce4da-2bfe-44a5-8157-7290a26c135c.mp3
**** 问题
***** 转录
关于复印机，下列哪项正确？
***** 音频
ddc85aa2-7444-481a-9364-3c3efd31a66d.mp3
**** 选择
***** A
需要维修
***** B
没有插电
***** C
需要保养
***** D
没有问题
**** 答案
D
** 第二部分
*** 7
**** 对话
***** 转录
男：这两天又失眠了。你说，换个枕头会不会好点儿？
女：也许吧，睡前喝杯牛奶可以改善睡眠，你试试。
男：昨晚夜里三点多醒了，想起单位那些头疼的事，就再也没睡着。
女：你要学会放松，别老胡思乱想。
***** 音频
08a41c43-74ac-4279-acac-7e266f3eafb5.mp3
**** 问题
***** 转录
男的为什么失眠？
***** 音频
12f5e87b-ab5a-47cf-ac43-4e9288c8301d.mp3
**** 选择
***** A
枕头不合适
***** B
精神压力大
***** C
忘了喝牛奶
***** D
头疼得厉害
**** 答案
B
*** 8
**** 对话
***** 转录
女：你说，鸵鸟也有翅膀，可为什么不会飞呢？
男：我听说它们胸骨太平了，肌肉不够发达。
女：懂的还不少。关键是它们的羽毛太柔软，翅膀与身体相比过于短小，根本不适合飞行。
男：还是没你懂得多呀！
***** 音频
185f7d75-8446-44d5-a060-31c3c7d0031c.mp3
**** 问题
***** 转录
根据对话，鸵鸟不会飞的关键因素是什么？
***** 音频
501e0cba-e80d-40e7-ac89-3bc3af267c30.mp3
**** 选择
***** A
翅膀太小
***** B
胸骨太平
***** C
羽毛不丰满
***** D
肌肉不发达
**** 答案
A
*** 9
**** 对话
***** 转录
女：现在大家都用智能手机了，你怎么还用这种老式的功能手机啊？
男：我这个手机的电池充一次电能用好几天，你的不行吧。
女：你太落后了，功能机有很多应用用不了。
男：没关系，我只要能打电话、发短信就够了。
***** 音频
0915fa67-9c9b-4a35-9d45-db37acab8f71.mp3
**** 问题
***** 转录
男的为什么还用老式的功能手机？
***** 音频
c9d16759-7293-43c3-a1f6-6070ff3969d6.mp3
**** 选择
***** A
智能手机太贵
***** B
用不惯智能机
***** C
只需接打电话
***** D
儿天才需充电
**** 答案
D
*** 10
**** 对话
***** 转录
男：上周五校庆，你怎么没来啊？
女：我在外地出差呢。
男：好多外地同学也来了，都二十年没见了，我们照了好多照片。
女：你不是有我微信吗？赶快给我发几张看看。
***** 音频
4b5e168a-a1cb-41a7-bedf-9d004072bc8f.mp3
**** 问题
***** 转录
女的上周五做什么了？
***** 音频
66f10fac-8e70-4fa1-ab7f-daa60e1d9292.mp3
**** 选择
***** A
去外地出差
***** B
去参加校庆
***** C
去看望老师
***** D
去参观摄影展
**** 答案
A
*** 11-12
**** 对话
***** 转录
男：我老板送了我两张展览会的门票，周六你有时间吗？
女：是什么展览？
男：今年的国际车展，全球各大厂商的新款车型都有展出。
女：太好了！我正想买车呢，听说买新能源汽车，政府是有很大优惠的。
男：新能源汽车是今后的发展方向，车展上你可以去咨询一下这方面的情况。
女：你汽车方面比我懂得多，到时候帮我参谋参谋。
男：没问题。那周六你就在家等我，我开车去接你。
***** 音频
8872d355-39a3-4111-a15e-64b059e87fea.mp3
**** 题目
***** 11
****** 问题
******* 转录
说话的两个人最可能是什么关系？
******* 音频
50f0163b-98a9-4f49-84c7-9447d43f784d.mp3
****** 选择
******* A
邻居
******* B
朋友
******* C
夫妻
******* D
师生
****** 答案
B
***** 12
****** 问题
******* 转录
关于车展，从对话中可以知道什么？
******* 音频
ac1b703c-508a-464f-ab91-93f5689b60bf.mp3
****** 选择
******* A
各大厂家都有参展
******* B
主要展出新能源车
******* C
展览门票免费赠送
******* D
政府给了许多优惠
****** 答案
A
*** 13-14
**** 段话
***** 转录
近年来，我国小学生的睡眠时间持续减少，80%的学生睡眠时间达不到每天10 小时的国家标准，即使在周末，也有七成以上的学生存在缺觉状况。尽管学校采取措施推迟上学时间在一定程度上保障了孩子的睡眠时间，但是许多“望子成龙”的家长却因“不能输在起跑线上”的心态不断给孩子加压，使孩子的睡眠时间不断被挤占。在学习日，过多的课后作业是抢占孩子睡眠的主要因素；而周末，主要是过多的课外补习班与兴趣班夺去了孩子的睡眠。缺觉不仅影响学习，还会导致肥胖，影响生长发育。研究发现，与每天睡眠在 10 小时以上的孩子相比，长期睡眠不足 10 小时的孩子变成胖墩儿的可能性会增加 3.5 倍。因此，保证小学生每天 10 个小时的睡眠是非常重要的。
***** 音频
b4ad9e70-06b5-4f38-a9bb-8349b139851f.mp3
**** 题目
***** 13
****** 问题
******* 转录
从文中可以知道，缺觉对小学生有什么不良影响？
******* 音频
6cc1bb6e-41cf-4304-b497-0222a2178a80.mp3
****** 选择
******* A
导致孩子肥胖
******* B
让孩子爱发脾气
******* C
导致孩子视力下降
******* D
使孩二注意力不集中
****** 答案
A
***** 14
****** 问题
******* 转录
这段短文主要告诉我们什么？
******* 音频
9b095926-a238-4265-a551-655aa6e2ac5b.mp3
****** 选择
******* A
课外兴趣班的危害
******* B
造成肥胖的主要原因
******* C
如何提高学习积极性
******* D
保证孩二睡眠很重要
****** 答案
D
* 阅读
** 第一部分
*** 段话
北京的胡同经历数百年的风雨，是老北京人生活的[[gap][15]]，今天仍居住着市区内三分之一的人口。朐同内的居民们仍保留着许多旦有的生活方式。
有人说，北京的胡同就像卢沟桥的狮子，[[gap][16]]数也数不清。北京的胡同密如蛛网，四通八达，[[gap][17]]在城市的每个角落，不要说外国人、外地人初到北京要找条胡同很围难，就是北京人也不见得一问就能说得清楚，[[gap][18]]，对那个地方很熟悉。因此，在北京走街串巷，进行胡同游，是很有意思的一件事情，就如同进了一座巨大迷官。
*** 题目
**** 15
***** 选择
****** A
象征
****** B
标记
****** C
反映
****** D
表现
***** 答案
A
**** 16
***** 选择
****** A
必然
****** B
反而
****** C
以乎
****** D
从而
***** 答案
C
**** 17
***** 选择
****** A
分布
****** B
分配
****** C
位于
****** D
充满
***** 答案
A
**** 18
***** 选择
****** A
既然他已经来过
****** B
虽然他去过很多次
****** C
除非他就住在那里
****** D
即使你听别人介绍过
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: d2e9616f-0592-4d9e-b6e8-082e41c384f3
:END:
**** 段话
如果突然被闹钟叫醒，将在心理上使人产生心慌、情绪低落、感觉没睡醒等不适。如果是从深度睡眠中被闹然叫醒，那么，人的短期记忆能力、计算技能都会受到影响，这些能力最多为正常状态的65％，与醉酒者相当。
**** 选择
***** A
闹钟会影响人的睡眠质量
***** B
熟睡时被闹钟吵醒人会心慌
***** C
深度睡眠时人的记忆能力下降
***** D
被闹钟叫醒时感觉像喝醉一样
**** 答案
B
*** 20
:PROPERTIES:
:ID: 7e4b2188-fe28-4cd3-ae7a-d979a6a35327
:END:
**** 段话
流行不仅仅是一个概念。以前以为流行仅仅是电视中模特的展示，现在却能实实在在感觉到它充满我们的生活，影响我们的穿着。不管是流行主导我们，还是消费决定流行，对我们来说，如果不能避免它，就主动去接受它。
**** 选择
***** A
现在，流行能影响我们的现实生活
***** B
过去，我们对流行存在着很多误解
***** C
越流行的东西大家越愿意消费
***** D
电视模特的工作常常不被接受
**** 答案
A
*** 21
:PROPERTIES:
:ID: 5c1cf243-8633-4623-b63c-a6ec3ac3dc89
:END:
**** 段话
有些孩子爱静，有的孩子好动，从拿起笔和纸的一刻起就表现不同，文静的孩子会安心认真地作画，好动的则会在纸上重重地乱划，随后把纸揉作一团或把纸撕碎。
**** 选择
***** A
爱静的孩子比较适合画画儿
***** B
好动的孩子一般都讨厌画画儿
***** C
爱静的孩子比好动的孩子有想象力
***** D
画画儿时的表现反映出孩子的性格
**** 答案
D
*** 22
:PROPERTIES:
:ID: 97b87e30-e16b-4888-88f1-1192957c64ff
:END:
**** 段话
机器人技术作为20世纪人类最伟大的发明之一，从60年代初问世以来，经历五十多年的发展已取得长足的进步。在制造业中，工业机器人甚至已成为不可缺少的核心装备，世界上有近百万台工业机器人正与工人朋友并肩战斗在各条战线上。机器人的出现是社会经济发展的必然，它的高速发展提高了社会的生产水平和人类的生活质量。
**** 选择
***** A
机器人是20世纪50年代发明的
***** B
机器人现在被广泛应用于战争
***** C
机器人将来必然会代替工人
***** D
机器人的发展提高了生产、生活水平
**** 答案
D
** 第三部分
*** 23-25
**** 段话
在距离现在一十七百多年前，中国处于魏、蜀、吴三强鼎立的三国时代。
有一天，吴国的孙权送给魏国的曹操一只大象，长久居住在中原的曹操从来没有见过这种庞然大物，好奇地想知道这个大怪物到底有多重？于是，他问大臣们：“谁有办法把这只大象称一称？”在场的人七嘴八舌地讨论着。有人回家搬出特制的秤，但大象实在太大了，一站上去，就把秤踩扁了；有人提议把大象一块一块地切下分开称，再算算看加起来有多重，可是大家觉得这样太残忍了，而且曹操喜欢大象的可爱模样，不希望望为了称重失去它。就在大家束手无策正想要放弃的时候，曹操七岁的儿子曹冲，突然开口说：“我知道怎么称了！”他请大家把大象赶到一条船上，看船身沉人水中多少，在船身上做了个记号。然后又请大家把大象赶回岸上，把一筐筐的石头搬上船去，直到船下沉到刚刚画的那一条线上为止。接着，他请大家把在船上的石头逐一称过，全部加起来就是大象的重量了！
现代的科技非常发达，我们已经发明出许多称重的工具，不需要再大费周折地一筐筐地搬石头了。但在一千七百多年前的时代，曹冲的方法的确很聪明。
**** 题目
***** 23
****** 问题
关于那只大象，从文中可以知道：
****** 选择
******* A
令曹操感到非常害怕
******* B
是魏国从吴国抢来的
******* C
是魏国本地没有的动物
******* D
很难长久在中原生活
****** 答案
C
***** 24
****** 问题
关于大臣们想到的办法，下列哪项正确？
****** 选择
******* A
根本办不到
******* B
计算不准确
******* C
会杀死大象
******* D
曹操很满意
****** 答案
C
***** 25
****** 问题
曹冲想出的方法：
****** 选择
******* A
现在显得很麻烦
******* B
是唯一的办法
******* C
需要把象赶下河
******* D
需要一筐石头
****** 答案
A
*** 26-28
**** 段话
我们到底该工作多长时间——一般情况下，我问到的每一个人都会引证一些道理说服我，这个时间接近每天八小时。数据似乎也证实了这一点：美国人平均每天工作8.8小时。至少这是来自美国劳动统计局的官方数据。
我们最开始为什么要一天工作八小时呢？
让我们从现有的工作制度开始。典型的工作日一天大约都是八小时。可我们是怎么提出这样的方案的？答案隐藏在工业革命的浪潮之中。
18世纪后期，当公司开始最大化提高工厂产量时，让工厂一周七天、一天24小时运转不停成了关键。当然，为了提高效率，人们就得工作得更多。实际上，那个时候一天工作10至16小时很正常。
如此超长的工作时间并没有一直持续下去，因为很快，一个名叫罗伯特。欧文的人勇敢地发起了一场运动，呼吁人们每天的工作时间不应超过八小时。他的口号就是“八小时工作，八小时娱乐八小时睡觉”。
最早引进这种工作制度的是福特汽车公司。1914年，福特公司不仅将标准的工作时长改为八小时，并且将工人们的工资翻了一番。让许多公司吃惊的是，随着工作小时数的减少，同样的工人，他们的生产力却大幅度地提高了。而两年间福特公司利润的增长幅度也极为巨大。这就促使其他公司也采用这种更短的八小时工作制作为员工的工作标准。
所以就是这样，这就是我们每天工作八小时的原因。并不是什么科学或者其他的缘由，仅仅只是一个世纪以来为了提高工厂效率而采用的古老标准。
**** 题目
***** 26
****** 问题
根据上文，对八小时工作制，大多数人是什么态度？
****** 选择
******* A
怀疑
******* B
认可
******* C
反对
******* D
欢迎
****** 答案
B
***** 27
****** 问题
根据上文，福特公司采用八小时工作制后：
****** 选择
******* A
生产力提高了
******* B
工人工资未变
******* C
企业利润下降了
******* D
公司增加了员工
****** 答案
A
***** 28
****** 问题
关于八小时工作时长这一标准，作者认为：
****** 选择
******* A
是欧文最先采用的
******* B
是经过科学验证的
******* C
得到政府部门的推广
******* D
出于提高效率的目的
****** 答案
D
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
