* 练习

** 1
:PROPERTIES:
:ID: e95bf952-e4ad-4201-a704-e3261cf71faf
:END:
*** 选择
**** 1
所
**** 2
享受
**** 3
导致
**** 4
过渡
**** 5
必要
**** 6
规律
*** 题目
**** 1
***** 句子填空
在婚因问题上，听听父母的意见还是很有[[gap]]的。
***** 答案
5
**** 2
***** 句子填空
由于近一个月来没有降水，[[gap]]河水水位持续下降。
***** 答案
3
**** 3
***** 句子填空
正如你[[gap]]估计的那样，李岩确实改变了主意。
***** 答案
1
**** 4
***** 句子填空
擦擦办公桌，整理一下文件，这些都可以让你从放松的休息状态自然[[gap]]到工作状态。
***** 答案
4
**** 5
***** 句子填空
生命在于运动，有[[gap]]的运动对于身体健康大有好处。
***** 答案
6
**** 6
***** 句子填空
为了[[gap]]轻松的生活，夫妻俩决定把家搬到这个安静的小镇。
***** 答案
2
** 2
*** 1
:PROPERTIES:
:ID: 02a04178-691b-4b7b-8cdb-caac8ede81ed
:END:
**** 句子填空
实验失败了没关系，打起[[gap]]从头再来。
**** 选择
***** A
情绪
***** B
精神
**** 答案
B
*** 2
:PROPERTIES:
:ID: d603c4ce-9143-4787-b2f4-479f63182353
:END:
**** 句子填空
每晚抽出点儿时间来阅读、学习，坚持[[gap]]年之后，成功就会向你招手。
**** 选择
***** A
来
***** B
数
**** 答案
B
*** 3
:PROPERTIES:
:ID: 55c241b1-2827-43e1-b476-3a2d4489d395
:END:
**** 句子填空
作为孩子的父母，我们当然[[gap]]他能成为一个有用的人才。
**** 选择
***** A
愿望
***** B
希望
**** 答案
B
*** 4
:PROPERTIES:
:ID: 813b4663-cab2-49df-bfba-564bb40455be
:END:
**** 句子填空
他的行为已经严重[[gap]]到了社会安全。
**** 选择
***** A
危害
***** B
伤害
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
享受
***** 答案
音乐
**** 1
***** 词语
导致
***** 答案
灾害
**** 1
***** 词语
危害
***** 答案
社会
**** 1
***** 词语
避免
***** 答案
麻烦
*** 2
**** 1
***** 词语
满足
***** 答案
愿望
**** 1
***** 词语
稳定
***** 答案
情绪
**** 1
***** 词语
集中
***** 答案
精神
**** 1
***** 词语
重视
***** 答案
传统
* 扩展
** 词语
*** 话题
家居
*** 词语
**** 1
抽屉
**** 2
书架
**** 3
窗帘
**** 4
地毯
**** 5
被子
**** 6
玩具
**** 7
日历
**** 8
日期
**** 9
包裹
** 题目
*** 1
**** 句子
这块[[gap]]是去年夏天我和太太去新疆旅游时买回来的，她很喜欢。
**** 答案
4
*** 2
**** 句子
李阳很喜欢作家老舍，[[gap]]上摆满了他不同时期的作品。
**** 答案
2
*** 3
**** 句子
我建议您给孩子买这个[[gap]]火车，这个牌子很有名。
**** 答案
6
*** 4
**** 句子
我把光盘放在书桌左边的第二个[[gap]]里了。
**** 答案
1
* 注释
** （三）词语辨析
*** 持续——继续
**** 做一做
***** 1
****** 句子
真希望刘老师能[[gap]]给我们上课。
****** 答案
******* 1
******** 持续
0
******** 继续
1
***** 2
****** 句子
这次的宣传活动将[[gap]]到9月底。
****** 答案
******* 1
******** 持续
1
******** 继续
0
***** 3
****** 句子
不管你是快乐还是难过，生活总要[[gap]]下去。
****** 答案
******* 1
******** 持续
1
******** 继续
1
***** 4
****** 句子
朋友是在你失败时，鼓励你[[gap]]前进的人。
****** 答案
******* 1
******** 持续
0
******** 继续
1
* 课文
** 转录
医学研究证明，人类睡眠有其特定的机制，自然醒是最符合人体生物钟规律的。光线是自然醒的必要条件，是人体内的生物闹钟。
早晨，人体感受到逐渐变强的太阳光线，新陈代谢随之加快，人逐渐从熟睡过渡到浅睡，直到醒来。这就是阴雨天人们往往喜欢睡懒觉的原因。
紧张的现代生活，使很多上班的人无法享受轻松舒适的睡眠、自然地醒来，闹钟的用途就显得格外重要了。但实验研究证明，人们对自然醒与被闹钟铃声叫醒这两种方式所产生的反应是很不相同的。从睡眠状态过渡到清醒状态时，人的呼吸会从 16 次/分钟提高到 24 次/分钟，心跳每分钟加快 10 次。如果突然被闹钟叫醒，将在心理上使人产生心慌、情绪低落、感觉没睡醒等不适。如果是从深度睡眠中被突然叫醒，那么，人的短期记忆能力、计算技能都会受到影响，这些能力最多为正常状态的 65 ％，与醉酒者相当。
出于自我保护，被闹钟叫醒时我们的身体会提高体内的肾上腺素水平。这种状态如果持续数天、数周、数月，将导致高血压、失眠和一些精神问题等。研究发现，突然被闹铃惊醒的人比自然醒的人血压更高、心跳更快。对此，专家解释说，人在睡眠时，身体会发生一些变化，因此人们在早上醒来时更容易发病，而闹铃则会使发病的可能性变得更大。如果你必须定个闹钟，应采用柔和的声音或音乐。
各种醒来方式中，当然是自然醒最符合我们的愿望。可谁能替你拉开窗帘让阳光照进来呢？近年来，市场上出现了一种新的电子产品，名为“光闹钟”。它能在室内模仿早晚自然光线的变化，通过光线的作用使人在设定的时间里自然地醒来，可免免传统闹钟突然惊醒对人体健康的伤害。希望这样能向真正的“自然醒”走近一点，再走近一点。
