* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 9d2c13b6-e8ee-404f-9805-2f1f7bbf2886
:END:
**** 对话
***** 转录
男：你是要提醒我整理阳台吗？我没忘。[[file:78b876ee-1001-43d9-ad8a-372153a82a77.mp3][(audio)]]
女：那你抓紧时间弄，[[file:e740ba77-924e-4a7e-a6dc-967257fa68be.mp3][(audio)]]今天太阳好，我想洗洗衣服。[[file:10b31093-caa8-464b-af62-77122d9f7317.mp3][(audio)]]
***** 音频
6a8948dd-4855-43da-9761-b622db17fb9b.mp3
**** 问题
***** 转录
男的今天要做什么？
***** 音频
6f07f8f9-d06e-4593-b883-97183198ad8a.mp3
**** 选择
***** A
去电视台
***** B
做完作业
***** C
收拾阳台
***** D
洗洗衣服
**** 答案
C
*** 2
:PROPERTIES:
:ID: 8a912b40-0f36-4418-9d03-1acac2f02ecd
:END:
**** 对话
***** 转录
男：你感冒了，要多休息，这擦地的活儿我来干吧。[[file:ef497c5e-2292-4dd3-9fb5-1e2d6ba15847.mp3][(audio)]]
女：这点儿病算得了什么？[[file:5e28bb18-d258-4e61-9585-a70af77e164c.mp3][(audio)]]再说了，我总觉得你擦得不干净。[[file:585ea1a8-5c07-4829-a37f-5f52a1c95f3d.mp3][(audio)]]
***** 音频
6cbddfb9-5d5c-4353-87bd-f8fcf242cb30.mp3
**** 问题
***** 转录
根据对话，可以知道什么？
***** 音频
435bab6d-ac1d-409e-b120-6a380ec70e94.mp3
**** 选择
***** A
女的不想干活儿
***** B
女的感冒都好了
***** C
男的不喜欢擦地
***** D
男的擦地不干净
**** 答案
D
*** 3
:PROPERTIES:
:ID: 25d051fa-3129-4da6-9f20-02ea25f84ae1
:END:
**** 对话
***** 转录
男：暑假我打算带孩子去北京，那儿的名胜古迹多，风景也不错。 [[file:2edba66b-ee60-4e5a-a7d9-3b8fa7227f44.mp3][(audio)]]
女：我哥哥家就在那儿，[[file:dd306b4b-4419-4ffc-a6c1-de35ed5cd731.mp3][(audio)]]等我打个电话让他招待你们。[[file:2d69d9b0-0b5b-465e-a520-7f781e472c17.mp3][(audio)]]
***** 音频
e921ba4f-9bc9-4f3f-bc4b-b0242d0a4247.mp3
**** 问题
***** 转录
女的为什么给哥哥打电话？
***** 音频
c57ff757-012a-407c-92ff-5e7f4219c4ab.mp3
**** 选择
***** A
要带孩子过去
***** B
请他招待朋友
***** C
要去北京看他
***** D
问候他的情况
**** 答案
B
*** 4
:PROPERTIES:
:ID: c9eadfb7-a0a7-433c-a9e3-e4151ba28912
:END:
**** 对话
***** 转录
男：国庆节你打算去哪儿玩儿？ [[file:21e33d3e-9535-4331-bbc1-c7859f6efb09.mp3][(audio)]]
女：去杭州，我大学同学结婚，我要去参加婚礼。[[file:c6ed0f54-70c6-4cb9-83a3-26f507b11545.mp3][(audio)]]回来路过苏州再玩儿两天。[[file:3d57c9df-78dc-4182-9e43-73375c2d52f4.mp3][(audio)]]
***** 音频
b53e208a-9cda-4e84-903e-29f09baf33ec.mp3
**** 问题
***** 转录
女的去苏州做什么？
***** 音频
b84d881b-a973-4197-99ca-1104a583e1f9.mp3
**** 选择
***** A
出差
***** B
旅游
***** C
参加婚礼
***** D
看老同学
**** 答案
B
*** 5
:PROPERTIES:
:ID: 11bb4b6c-6c25-4dce-b03e-20743d7fbf81
:END:
**** 对话
***** 转录
男：这次去北京收获不小吧？[[file:5503c2b8-698f-4f18-8909-cad0178daa9c.mp3][(audio)]]
女：没错。[[file:9ff3a958-969a-45fe-8074-e63ef05fa515.mp3][(audio)]]长城、颐和园的风景真美，胡同也很特别，[[file:a913ea2a-16da-48f5-ab13-76051dd1f2bc.mp3][(audio)]]给我留下印象最深的还是北京烤鸭，味道棒极了。[[file:9e063d14-070c-4d4f-9595-fed44a8f3916.mp3][(audio)]]
***** 音频
e8b72c40-f591-4a2b-b577-70e98c705c7a.mp3
**** 问题
***** 转录
女的对北京的什么印象最深刻？
***** 音频
d987c1de-0882-453e-97d3-4a4a408a35e6.mp3
**** 选择
***** A
美食
***** B
风景
***** C
京剧
***** D
胡同
**** 答案
A
*** 6
:PROPERTIES:
:ID: a34b7494-c860-4de3-addb-fcf04da1afd5
:END:
**** 对话
***** 转录
男：苏州有个叫山塘的地方，不知你这次有没有去看看？[[file:395485ce-ae03-41a5-9165-6c1efeb8b660.mp3][(audio)]]
女：当然，我还坐了那里的游船，体会了一下“小桥流水人家”的感觉，很有味道。[[file:325d06e5-af9c-42da-b2e6-ffd545a34894.mp3][(audio)]]
***** 音频
83216593-c767-42e4-8d74-631186196075.mp3
**** 问题
***** 转录
女的觉得山塘怎么样？
***** 音频
7e2c66a3-4a26-4941-aacc-59788dd5cfad.mp3
**** 选择
***** A
菜的味道很好
***** B
风景很有特色
***** C
感觉有些失望
***** D
比想象的美丽
**** 答案
B
** 第二部分
*** 7
**** 对话
***** 转录
男：你来中国留学两年了，利用假期去过不少地方了吧？
女：中国的名胜古迹很多，风景优美的地方太多了。
男：那你最喜欢的地方是哪里？
女：我觉得四川的黄龙风景最美，到了那儿，真像是到了童话世界。
***** 音频
7ad47a1c-3be3-497d-920e-25f94236d96d.mp3
**** 问题
***** 转录
女的觉得四川的黄龙怎么样？
***** 音频
69bc3f3b-72ca-4354-ab9f-6b0f1c245769.mp3
**** 选择
***** A
没什么印象丁
***** B
没有宣传的好
***** C
风景非常优美
***** D
让她想起童年
**** 答案
C
*** 8
**** 对话
***** 转录
男：姥姥，您来了些日子了，今天正好有空儿，我陪您去故宫转转？
女：故宫人太多，我这腿脚又不方便，还是别去了。
男：那我陪您看电影去吧？
女：好哇！我最爱看电影了！
***** 音频
34318b0a-16c2-4029-ad90-6c35623cf837.mp3
**** 问题
***** 转录
关于姥姥，从对话中可以知道什么？
***** 音频
699d012e-8b00-460b-8460-6d8f5aa19628.mp3
**** 选择
***** A
不喜欢电影
***** B
想去看故客
***** C
哪儿也不想去
***** D
走路不太方便
**** 答案
D
*** 9
**** 对话
***** 转录
男：你好，我想预订周末的一个房间，标准间就行。
女：先生，不好意思，我们接待了一个会议的预订，标准间都没有了，只有豪华客房和商务套间，请问您还需要吗？
男：也行。我们带孩子来旅游，商务间就不用了，豪华间有大床房吗？
女：有的，请问您要住几天？
***** 音频
8aaaf886-094f-4e04-a91e-062997b56c0c.mp3
**** 问题
***** 转录
关于男的，下列哪项正确？
***** 音频
f04b5db1-109b-430e-9a0f-a9341875855a.mp3
**** 选择
***** A
来参加会议
***** B
打算住一周
***** C
想要大床房
***** D
订了商务间
**** 答案
C
*** 10
**** 对话
***** 转录
男：我的小学就在和南锣鼓巷交叉的一条胡同里，每天上学都经过这里。
女：那时候这里可没有现在这么热闹，就是条普普通通的胡同。
男：这都是 20 年前的事了。你看变化多大啊！
女：不过，你读的小学一直以来都是所好学校。
***** 音频
f7ed40e0-e2bb-4ceb-a73d-cae3a169f24a.mp3
**** 问题
***** 转录
关于男的，从这段对话中可以知道什么？
***** 音频
b2ec9f60-adbe-4197-96cf-ef24679ca27f.mp3
**** 选择
***** A
以前住在这里
***** B
不太腺欢热闹
***** C
读的小学很普通
***** D
以前常路过这里
**** 答案
D
*** 11-12
**** 对话
***** 转录
女：你带小明去自然博物馆了？
男：是，儿童节了，我这个当小舅舅的，还不该满足他一个要求嘛！
女：小明之前跟我说过好几次想去自然博物馆看恐龙，你们看了吗？
男：当然看了，我们还看了海洋馆。人类馆关闭装修，没看到，很遗憾。那儿的设施虽然有点儿旧，但 8000 平方米的展厅，一天都看不完。
女：小明喜欢那儿吗？
男：那还用说吗？小眼睛都不够用的了。
***** 音频
fc6bb175-204b-4ffc-87bb-f36bd6b334a9.mp3
**** 题目
***** 11
****** 问题
******* 转录
说话的两个人是什么关系？
******* 音频
dbf45584-b5e9-4ed8-8935-946ed7b1cbca.mp3
****** 选择
******* A
姐弟
******* B
夫妻
******* C
朋友
******* D
母子
****** 答案
A
***** 12
****** 问题
******* 转录
关于自然博物馆，从对话中可以知道什么？
******* 音频
22c63108-7548-4705-a0c2-a3d6ab5432ff.mp3
****** 选择
******* A
设施非常落后
******* B
展馆面积很大
******* C
刚进行过装修
******* D
观众多很拥挤
****** 答案
B
*** 13-14
**** 段话
***** 转录
有一位名叫威廉森的 9 岁英国男孩，看上去，他和同龄的孩子没什么不同，可一拿起画笔，他就立刻显示出画家范儿来。新近在他的个人画展上，展出的25 幅作品仅 15 分钟就被抢购一空，价值达 25 万英镑。一位知名艺术品专家表示，威廉森的画之所以如此受到欢迎，除了因为他的作品本身很单纯以外，还因为他在这么小的年纪就熟练掌握了多种绘画技巧，对一些画家而言，达到他的程度需要花上至少 10 年。
***** 音频
672b57e2-e93b-4140-afd6-53a1c447497b.mp3
**** 题目
***** 13
****** 问题
******* 转录
关于威廉森，下列哪项正确？
******* 音频
c9fe7984-2d61-470c-b8fc-30e67f96ed44.mp3
****** 选择
******* A
学画已经9年了
******* B
大家都抢购他的画
******* C
看上去和同龄孩子很不同
******* D
9岁就得过许多绘画大奖
****** 答案
B
***** 14
****** 问题
******* 转录
威廉森的画受欢迎的原因是什么？
******* 音频
cfa7b796-11e0-43e0-9f6a-f8aaed0ecd2d.mp3
****** 选择
******* A
绘画技巧很成熟
******* B
作品色彩很丰富
******* C
作品充满表现力
******* D
有超人的想象力
****** 答案
A
* 阅读
** 第一部分
*** 段话
一只狼出去找食物，找了半天都没有收获。偶妖经过]习人家听见房中孩子哭闹，接着[[gap][15]]“来一位老太婆的声音：”别哭啦，再不听话，就把你扔出去喂狼吃“狼一听此言，心中大喜，便守在不远的地方等着。太阳落山了，也/垦、乏见4j寥置艾〔婆茎〔巴子亥守乙茎嶂乃置骂来。晚上，狼已经等得[[gap][16]]了，转到房前想找机会进去，却又听老太婆说：”快睡吧，别怕，狼来了，咱们就把它杀死煮了吃“狼听了，吓得一溜烟跑回老窝。同伴问它收获[[gap][17]]，它说：”别提了，老太婆说话不算数，[[gap][18]]，不过幸好后来我跑得快“
*** 题目
**** 15
***** 选择
****** A
递
****** B
传
****** C
听
****** D
飘
***** 答案
B
**** 16
***** 选择
****** A
不耐烦
****** B
不舒服
****** C
不要紧
****** D
差不多
***** 答案
A
**** 17
***** 选择
****** A
任何
****** B
如何
****** C
怎么
****** D
什么
***** 答案
B
**** 18
***** 选择
****** A
就是不让我进门
****** B
请我到家里做客
****** C
害很我饿了一天
****** D
跟我聊起来没完
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: 2bf8effb-779b-4d3d-8cb5-364f72848f57
:END:
**** 段话
长江是我国最大最长的河流。它全长约6300公里，流域面积约180万平方公里，仅次于非洲的尼罗河和南美洲的亚马孙河，为世界第三长河。长江发源于中国西部，自西而东横穿中国中部，干流流经11个省、自治区、直辖市。长江干流通航里程达2800多公里，素有“黄金水道”之称。
**** 选择
***** A
长江全长2800多公里
***** B
长江是重要的航运水道
***** C
亚马孙河是世界第三长河
***** D
长江因出产黄金而著名
**** 答案
B
*** 20
:PROPERTIES:
:ID: 0cc5dd91-8cfd-4f12-8005-dae73688cce9
:END:
**** 段话
在中国，风的变化与季节的变化有很大的关系。比如，炎热的夏天，中国大部分地区刮东南风，东南风是从海上刮来的。它带来了温暖潮湿的气流，所以夏季才会温暖、潮湿、多雨。而到了冬天，中国大部分地区开始刮西北风，西北风来自北方蹄冷的蒙古、西伯利亚等内陆地区，所以冬季气候通常寒冷、干燥、少雨。
**** 选择
***** A
中国的夏季通常会刮西北风
***** B
在中国东南风来自内陆地区
***** C
在中国不同地区风向也不同
***** D
中国的风向变化有季节规律
**** 答案
D
*** 21
:PROPERTIES:
:ID: 2add3883-2c1a-4393-a49f-a87f981ebf0e
:END:
**** 段话
世界上面积最大的海洋是太平洋，大约占海洋总面积的一半，它还是水最深的大洋。太平洋中岛屿很多，大大小小共有两万多座。太平洋里生长着许多动物和植物，无论是浮游生物和海底植物，还是鱼类与其他动物，都比其他大洋丰富。太平洋底还有着丰富的石油等矿藏。
**** 选择
***** A
太平洋的鱼类有两万多种
***** B
最大最小的岛都在太平洋
***** C
太平洋里的动植物最丰富
***** D
太平洋的石油资源最丰富
**** 答案
C
*** 22
:PROPERTIES:
:ID: 3738ec0b-c562-435d-b6d6-3dab3416f409
:END:
**** 段话
济南的泉水，历史悠次，最早的文字记载可以推到3000多年前。许多文人都对它的声音、颊色、形状、味道进行过描写，留下了许多赞美泉水的诗文。而济南的老百姓住在泉边，喝着这甜美的泉水，自然对泉水充满感激之情，从而也产生出了许多关于泉水的美丽传说。
**** 选择
***** A
文人最喜欢描写松水昧道的甜美
***** B
三十年前就有许多赞美泉水的诗文
***** C
济南的百姓很感激文人对泉水的描写
***** D
在白姓中流传着许多有关泉水的传说
**** 答案
D
** 第三部分
*** 23-25
**** 段话
我的爷爷是个玉雕艺人，一辈子不知做过多少精美的玉器。晚年的时候，爷爷的名声在同行里无人不知，许多富人把拥有一件出自爷爷之手的玉器引为骄傲。
爷爷要退休了，他为他的老板干了一辈子，他没有任何过分的想法，只是想得到多年来盼望已久的一块璞玉。爷爷一生为老板赢得了无数财富，这个小小的要求，他觉得老板一定会满足他，却不想老板笑笑说：“我正准备要您帮我做最后一个物件，就用这块璞玉，您用出全部的本领，能把它做成什么就是什么！”
爷爷听后，心里暗暗生气。他抱怨老板的无情，自己老了，没有用了，连这点儿情面都不给。爷爷感慨人情冷漠，把全部的失望和恭怒都发到了那块璞玉上，他做了一件非常难看的玉船。
把玉船交给老板后爷爷默默地离开，老板紧赶慢赶追上来，态度诚恳地送给爷爷一个锦缎的盒子：。“老人家，您为我工作了一辈子，这点儿东西，留给您做个纪念吧！”爷爷打开一看，不禁惭愧地低下了头：盒子里装的正是自己最后做的那件玉船。
**** 题目
***** 23
****** 问题
根据本文，晚年时的爷爷：
****** 选择
******* A
非常有名
******* B
非常富有
******* C
爱抱怨别人
******* D
特别骄傲
****** 答案
A
***** 24
****** 问题
要退休时，爷爷有什么打算？
****** 选择
******* A
想痛骂老板一顿
******* B
准备做一件玉船
******* C
想跟老板要笔钱
******* D
希望得到那块璞玉
****** 答案
D
***** 25
****** 问题
关于爷爷的老板，从文中可知：
****** 选择
******* A
非常小气
******* B
无情无义
******* C
很感谢爷爷
******* D
不想让爷爷走
****** 答案
C
*** 26-28
**** 段话
元朝修建北京城时按照严格的规划，城内的主要街道都像棋盘一般整齐划一，井然有序，因此，北京人的方位感特别强。在北京问路，指路的人一般会告诉你路南还是路北北京的胡同都比较平直规则，大多是东西走向的，而且为了便于通行和采光，元代时规定，城区胡同宽度约为9米，由于两旁房屋低矮，哪怕在冬季，只要是晴天，胡同里便充满阳光。这一规定到明清时就不再那么严格了，这样有些地方就出最现了一些不规则的胡同，有长有短，有宽有牵，有横有窄，有直有斜。其中还有许多小胡同，貌不惊人，却留下了许多历史文化印记。
前门大栅栏（dàshílànr）原本也是一条普通胡同，宽不过七八米，长不过200多米。然而，这里却是北京最古老的商业中心之一。至今在这里仍汇集着许多著名的老字号商家，如同仁堂中药店、瑞蚨祥绸布店、张一元茶叶店、内联升鞋店……
小胡同也有自己的故事。在西城区的大街上，有一条很不起眼的小胡同，叫小羊圈胡同，入口处最窄的地方只有一米多宽，可是谁又能想得到，现代中国的大作家老舍就诞生在这条小胡同里。在老舍的《小人物自述》《四世同堂》《正红旗下》三部著名小说中，他都把小羊圈胡同作为小说主人公生活和活动的舞台，使这条本来名不见经传的小胡同被世人所熟知。小羊圈胡同后来改名为小杨家胡同。
**** 题目
***** 26
****** 问题
根据本文，北京人的方位感强是因为：
****** 选择
******* A
城市不大
******* B
街道整齐有序
******* C
地名很好记
******* D
房屋修建有规定
****** 答案
B
***** 27
****** 问题
关于北京的胡同，下列哪项不正确？
****** 选择
******* A
多为东西走向
******* B
一般宽约为9米
******* C
冬季采光不好
******* D
多比较平直规则
****** 答案
C
***** 28
****** 问题
关于小羊圈胡同，从文中可知：
****** 选择
******* A
宽度只有一米多
******* B
很不引人注意
******* C
是老北京商业中心
******* D
老舍在此写了三部小说
****** 答案
B
* 书写
** 第一部分
*** 29
**** 词语
***** 1
强烈的
***** 2
两种颜色
***** 3
对比
***** 4
形成了
***** 5
这
**** 答案
***** 1
这两种颜色形成了强烈的对比。
*** 30
**** 词语
***** 1
两十多年前的
***** 2
于
***** 3
皮影戏
***** 4
西汉时期
***** 5
产生
**** 答案
***** 1
皮影戏产生于两千年前的西汉时期。
*** 31
**** 词语
***** 1
往往
***** 2
能
***** 3
一个人的心态
***** 4
脸上的表情
***** 5
反映
**** 答案
***** 1
脸上的表情往往能反映一个人的心态。
