* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 41a7d7e6-a60c-4381-8b6d-f8ac087754d8
:END:
**** 对话
***** 转录
男：到了新公司，你一定要吸取教训，争取留用。[[file:c052560a-d845-4a35-913f-2ffc36d712ba.mp3][(audio)]]
女：上次的机会我没有珍惜，这次一定好好表现。[[file:c647185e-3704-4dda-b629-986f648f969a.mp3][(audio)]]
***** 音频
5ba227ee-8480-4fe6-81d2-59736875dc74.mp3
**** 问题
***** 转录
关于女的，可以知道什么？
***** 音频
2c04073b-ab11-43ce-9426-4ed8e4f073bd.mp3
**** 选择
***** A
失去了工作
***** B
面试表现不错
***** C
在找实习单位
***** D
得到了试用机会
**** 答案
D
*** 2
:PROPERTIES:
:ID: 562b95f8-cd19-46d8-815f-9f4b9d291127
:END:
**** 对话
***** 转录
女：参加这个项目的选手一个比一个厉害，刘云能进决赛真不容易。[[file:8ab5135e-5ed8-464c-930a-7124d136a91b.mp3][(audio)]]
男：今年他的状态很好，可以说是超水平发挥了。[[file:f431a62a-e5e0-495c-a75c-aa1653334809.mp3][(audio)]]
***** 音频
60181c0d-6e26-4121-8fa0-1efac848d6b2.mp3
**** 问题
***** 转录
男的觉得刘云怎么样？
***** 音频
fbf769d2-1bd1-4be7-a7f0-4b61965a1367.mp3
**** 选择
***** A
状态不稳定
***** B
发挥很出色
***** C
成绩不够理想
***** D
一定能拿冠军
**** 答案
B
*** 3
:PROPERTIES:
:ID: 7a159e6d-8ce3-4730-b083-518442540014
:END:
**** 对话
***** 转录
男：寒假你不打算回家了吗？ [[file:38e73371-c2c0-4bc6-ac7b-b4b1da51d59a.mp3][(audio)]]
女：我在一家旅行社实习，公司让我设计一条新线路，年前要出差做调研。[[file:681c5568-afc2-4d6e-9e34-f699643c3ad1.mp3][(audio)]]
***** 音频
3568292b-675a-405e-af24-7fdb893506ba.mp3
**** 问题
***** 转录
女的寒假为什么不回家？
***** 音频
8d53d454-e6ae-4d3d-a8b0-bdb3cd05ab34.mp3
**** 选择
***** A
出差去做调研
***** B
联系实习单位
***** C
设计新款服装
***** D
抓紧准备论文
**** 答案
A
*** 4
:PROPERTIES:
:ID: 29c0e8d5-cec2-4a80-800d-aa36d8fe25ca
:END:
**** 对话
***** 转录
女：小刘运气真不错，刚来一年就成了主力队员。[[file:73ad6bbf-0cc0-4a5f-8e5f-67176ad99029.mp3][(audio)]]
男：你也别灰心，论实力你未必比她差，下个月的比赛好好把握。[[file:933b0b96-5a7f-45f8-9e9e-0277a6db122f.mp3][(audio)]]
***** 音频
6d06fc24-8982-4bbf-94f8-864a032356be.mp3
**** 问题
***** 转录
男的对女的说这些话是想怎样？
***** 音频
54b65c85-7b66-4602-9c7e-80114241d45c.mp3
**** 选择
***** A
责备她
***** B
说服她
***** C
鼓励她
***** D
称赞她
**** 答案
C
*** 5
:PROPERTIES:
:ID: 81ce3b51-46be-47e1-a2d7-cce281fa1c0a
:END:
**** 对话
***** 转录
女：我对小林是有些看法，这一点儿我不否认。[[file:f698819c-743a-4a89-b779-df97a162cbb1.mp3][(audio)]]
男：我希望你找机会和他沟通一下，把问题谈开，别影响工作。[[file:4e9f9a27-39e3-41ac-93e7-8e44394de233.mp3][(audio)]]
***** 音频
570839d7-6648-4745-97b4-d9e6c78d671d.mp3
**** 问题
***** 转录
女的和小林最可能是什么关系？
***** 音频
5a1a37b1-6931-41fa-a7bb-36b158d86b07.mp3
**** 选择
***** A
恋人
***** B
同事
***** C
朋友
***** D
客户
**** 答案
B
*** 6
:PROPERTIES:
:ID: 02adae3e-5339-4108-a3b4-050330e69163
:END:
**** 对话
***** 转录
女：你不知道吗？比赛期间，任何队员都不能随便外出。[[file:da739260-9f87-4014-a542-e3c0004d7158.mp3][(audio)]]
男：我事先跟教练打过招呼的，他同意了。[[file:8c53f467-520b-447e-a086-c014027bcb17.mp3][(audio)]]
***** 音频
70b85161-6b58-4d2e-805d-4d31a61c03c0.mp3
**** 问题
***** 转录
关于男的，可以知道什么？
***** 音频
f1cfcc2c-c945-4dab-9636-da5b788d7f7e.mp3
**** 选择
***** A
违反了纪律
***** B
承认犯了错
***** C
退出了比赛
***** D
教练准了假
**** 答案
D
** 第二部分
*** 7
**** 对话
***** 转录
女：昨天我去隔壁莉莉家还东西，他们家的窗帘我特喜欢。
男：怎么？你又想干什么？
女：咱家客厅的窗帘用了好多年了，花样也不流行了。
男：我看就是有些脏了，洗洗还能用。
***** 音频
0eed95c7-fb92-4985-9ee9-b9ca84f0d69a.mp3
**** 问题
***** 转录
关于窗帘，男的是什么意思？
***** 音频
2ac7142c-a7ba-4f11-9d99-be427c2a470f.mp3
**** 选择
***** A
花样很时髯
***** B
干净不用洗
***** C
不想换新的
***** D
买跟莉莉家一样的
**** 答案
C
*** 8
**** 对话
***** 转录
男：上次李阳去德国讲学，本来领导也问过我。
女：那你怎么不去呀？
男：当时孩子小，我有点儿犹豫。现在觉得有点儿后悔了。
女：多好的机会失去了，我的经验就是，有机会一定要好好把握。
***** 音频
bd68ac02-f7eb-493a-9030-d3727073c393.mp3
**** 问题
***** 转录
男的为什么没去德国讲学？
***** 音频
d7465d9b-7cf1-4cf1-bc63-538dc38e9c75.mp3
**** 选择
***** A
要照顾孩子
***** B
领导不同意
***** C
不符合条件
***** D
对自己没把握
**** 答案
A
*** 9
**** 对话
***** 转录
女：刘京报的价格好像不对，你怎么没检查出来？
男：真是的！上次开会讨论得很清楚了，他怎么还弄错了。
女：你遇到问题总爱责备别人，就不想从自己身上找找原因。
男：我主要是太信任他了。
***** 音频
9c51da8f-dd95-4357-9d2b-8d5efcb0c3d7.mp3
**** 问题
***** 转录
在这件事上，女的觉得男的怎么样？
***** 音频
58e2289a-5f95-406d-ba4c-9ae4817f8311.mp3
**** 选择
***** A
用人不当
***** B
认真负责
***** C
过于自信
***** D
爱抱怨别人
**** 答案
D
*** 10
**** 对话
***** 转录
女：小刘请假看球赛是你同意的吗？
男：他最近修改设计方案，搞得很辛苦，我想让他放松放松。
女：工作辛苦可以理解，但不能因为他跟你关系好就不按规定办事。
男：我知道了，下次一定不再自作主张。
***** 音频
7b984e70-6e08-4c1a-927a-f74390e8abc5.mp3
**** 问题
***** 转录
女的批评男的什么？
***** 音频
625f7706-b6eb-4f15-9ccb-c5f0743dfff1.mp3
**** 选择
***** A
不关心同事
***** B
不坚持原则
***** C
工作不努力
***** D
上班看球赛
**** 答案
B
*** 11-12
**** 对话
***** 转录
刘明遇见了从体育馆出来的一位朋友。他问这个朋友：“玩儿得怎么样？”“玩儿得很好！”朋友回答，“我打了网球，下了象棋。既赢了象棋冠军，又赢了网球冠军。”“你对打网球、下象棋都很在行吗？”刘明问。“我和网球冠军一起下象棋，赢了他，后来，我又和象棋冠军一起打网球，我也赢了他。”比赛中要做到知己知彼，有利地选择对手，这也是取胜的好办法。
***** 音频
7509552a-1bcc-4efe-9df9-4cecccf8589e.mp3
**** 题目
***** 11
****** 问题
******* 转录
关于刘明的朋友，可以知道什么？
******* 音频
5244d7fa-a754-4727-bb15-ab44a17c2314.mp3
****** 选择
******* A
象棋下得非常好
******* B
网球打得很不错
******* C
曾经是全国冠军
******* D
下棋打球都嬴了
****** 答案
D
***** 12
****** 问题
******* 转录
这段话想告诉我们什么道理？
******* 音频
fb03404f-7f7d-4b8f-a279-3b7d92ca9f04.mp3
****** 选择
******* A
不要轻视对手
******* B
心理素质很重要
******* C
刻苦训练才能嬗
******* D
了解对手更易取胜
****** 答案
D
*** 13-14
**** 段话
***** 转录
在 14 日的足球比赛中，上海队主场迎战北京队。这天，上海整个下午都在下雨。上半时，赛场条件尚可，一开始主队就控制了场上局势，可惜浪费了大量得分机会。他们在第 24 分钟时才首先破门，可 4 分钟后客队队长就为北京队追平比分。下半时，赛场局部区域积水明显，双方队长都对主裁判表示愿意继续比赛，但在比赛进行了 20 分钟后，赛场条件变得非常糟糕，大有变成水球比赛的可能。裁判只好暂停比赛，球员回到了休息室。15 分钟后，主裁判见赛场积水更加严重，于是只好宣布比赛中止。
***** 音频
de06ad0b-1fd0-46b8-92d6-0124b90285d6.mp3
**** 题目
***** 13
****** 问题
******* 转录
从上半场的比赛可以知道什么？
******* 音频
ffdd14aa-0521-49c2-b5c3-915aaab16cb5.mp3
****** 选择
******* A
北京队首先进球
******* B
北京队有人受伤
******* C
上海队显得很吃力
******* D
上海队丢掉很多机会
****** 答案
D
***** 14
****** 问题
******* 转录
下半场比赛实际进行了多长时间？
******* 音频
c491f96c-418e-45fd-83b9-0a8a0f4295b3.mp3
****** 选择
******* A
4分钟
******* B
15分钟
******* C
20分钟
******* D
24分钟
****** 答案
C
* 阅读
** 第一部分
*** 段话
有一个韩国家庭，收到别人送的两箱苹果。其中一箱苹果已有些[[gap][15]]成熟了，如果不马上吃掉，很快就会烂掉；另一箱比较新鲜，还可以[[gap][16]]长一点儿的时间。父亲把三个儿子找来，[[gap][17]]。大儿子说，趁还没有完全坏，先吃那成熟的一箱。父亲说，不过等这一箱吃完，那一箱也就快坏了。二儿子说，先吃那好的一箱，这样能尽可能多吃-点儿好苹果。父亲说，可是这样一来，过熟的那一箱肯定全部浪费了。三儿子说，我们把两箱苹果混合起来，分一半给邻居，所有的苹果都不会浪费。这位三儿子，名叫潘基文，就是前任联合国秘书长。可以看出，潘基文的办法，于己无损，于人有益，更重要的是节约了社会资源，使每一个鞅果都能[[gap][18]]作用。这样的人，一定会朋友多，一定会在人生的道路上得到更多的支持和帮助，也会取得更多的成就。
*** 题目
**** 15
***** 选择
****** A
明显
****** B
格外
****** C
过分
****** D
极其
***** 答案
C
**** 16
***** 选择
****** A
持续
****** B
保存
****** C
延长
****** D
推迟
***** 答案
B
**** 17
***** 选择
****** A
商量苹果的吃法
****** B
让他们吃苹果
****** C
问了他们一个问题
****** D
把苹果分给他们
***** 答案
A
**** 18
***** 选择
****** A
加强
****** B
发挥
****** C
显示
****** D
失去
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 29e095c4-051d-4e0c-81a2-dbbdaab7bf57
:END:
**** 段话
语言是一种艺术，询问是一种技巧。能否最快地得到想要的答案，是判别一个人设计问题高下的方法。这也是为什么有些人能当首席记者，采访世界名人，而有些人只能替人校稿。
**** 选择
***** A
有问题尽快问
***** B
记者更善于写稿
***** C
询问需要有技巧
***** D
名人都很会回答问题
**** 答案
C
*** 20
:PROPERTIES:
:ID: 1eb2b33c-c77a-4c5f-8e1a-c870c56010dc
:END:
**** 段话
“京韵大鼓”形成于北京和天津一带。20世纪初期著名鼓书艺人刘宝全等人在河北“木板大鼓”的基础上，吸收京剧唱腔和北京地方民间小调，同时使用北京语音进行演唱，并在原有伴奏乐器三弦外，增加了四胡和琵琶，创造出“京韵大鼓”这门曲艺艺术。
**** 选择
***** A
刘宝全是著名的京剧演员
***** B
木板大鼓的伴奏乐器为三弦
***** C
京韵大鼓是木板大鼓的另一名称
***** D
京韵大鼓是在京剧的基础上发展出来的
**** 答案
B
*** 21
:PROPERTIES:
:ID: 9956a9c5-9e13-4a2e-a701-5ff908d9cac6
:END:
**** 段话
南方人尊称医生为郎中。为什么会有“郎中”这样的称呼呢？原来，郎中本来是一种官名，他的职责就是保护、陪同帝王，并随时提出建议。自战国时期就有此官，以后各朝各代都把侍郎、郎中作为各部门的重要职务。唐代以后因国家设立的官职太多太滥了，社会上就有了把医生叫作郎中的风俗。
**** 选择
***** A
郎中是对医生的一种尊称
***** B
郎中最早是一个国家机构
***** C
只有南方人才知道郎中的意思
***** D
战国时人们开始称医生为郎中
**** 答案
A
*** 22
:PROPERTIES:
:ID: e03a2fdb-fcfe-4402-8da1-21eb251711dc
:END:
**** 段话
人到中年，除了每日处理繁忙的工作外，身边总是围绕着或大或小、或急或缓的事儿。比如孩子的教育、双方父母的身体、对亲朋好友或精神或物质的照顾，等等。这些事情接二连三，频繁不断，不管你是否有所准备，它们都不期而至，时常搞得人心烦意乱、疲惫不堪。我的生活就是这个状态。
**** 选择
***** A
“我”只为孩子的事操心
***** B
“我”对现在的状态不满
***** C
“我”现在的生活很悠闲
***** D
“我”渴望得到家人的理解
**** 答案
B
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
