* 课文

** 标题

下棋

** 转录
我父亲是一位象棋教练。那一年，我大学放假回家，父亲要跟我下棋，我高兴地答应了。
父亲让我先走三步。不到三分钟，我的棋子损失大半，棋盘上空空的，只剩下几个子了。没办法，眼睁睁看着父亲“将军”，我输了。
我不服气，说：“这次运气不好，再来！”第二局又输了，“这次没发挥好，我们再来”！几局下来，基本上都是不到10分钟我就败下阵来。我有些灰心。父亲看看我说：“你初学棋，输是正常的。但是你要知道输在什么地方，要吸取教训。否则，你就再下上10年，也未必能赢。”
“我知道，我技术没你好，经验也不足。”
“这只是次要因素，不是最重要的。”
“那最重要的是什么？”我奇怪地问。
“最重要的问题在于你心态不对。你不够珍惜你的棋子。”
“怎么不珍惜呀？我每走一步，都想半天。”我否认说。
“那是后来。开始你是这样吗？我仔细观察过，你三分之二的棋子是在前三分之一的时间失去的。这期间你好像很有把握，下棋时不假思索，拿起来就走，失去了也不觉得可惜。因为你觉得棋子很多，失一两个不算什么。后三分之二的时间，你又犯了相反的错误：对棋子过于珍惜，每走一步都过于谨慎，一个棋子也不想失，反而一个一个都失去了。”
说到这，父亲停下来，把棋子重新在棋盘上摆好，抬起头，看着我，问：“这是一盘待下的棋。我问你，下棋的基本原则是什么？”
我想也没想，脱口而出：“赢啊！”
“那是目的。”父亲用责备的眼光看了我一眼，“至于原则，是要考虑得失。有得必然有失，有失才会有得。每走一步，你事先都应该想清楚：为了赢得什么，你愿意失去什么，这样才可能赢。可惜，大部分人都像你这样，开始不考虑得失，等到后来失去得多了，又开始舍不得，后果就是屡下屡败。其实不仅是下棋，人生也是如此啊！”
** 生词

（象）棋 / (xiang4)qi2 / (Chinese) class, board game ;
教练 / jiao4lian4 / coach, instructor ;
答应 / da1ying / to agree, to promise ;
损失 / sun3shi1 / to lose ;
睁 / zheng1 / to open (one's eyes) ;
眼睁睁 / yan3zheng1zheng1 / (looking on) helpesly or indifferently ;
将军 / jiang1jun1 / (military) general; (in chess) to put one's king/general in check ;
服气 / fu2qi4 / to be convinced, to be won over ;
运气 / yun4qi / luck, fortune ;
局 / ju2 / game, set ;
发挥 / fa1hui1 / to bring into play, to give rein to ;
灰心 / hui1xin1 / discouraged ;
吸取 / xi1qu3 / to absorb, to draw ;
教训 / jiao4xun4 / lesson, moral ;
未必 / wei4bi4 / may not, not necessarily ;
次要 / ci4yao4 / less important, secondary ;
因素 / yin1su4 / factor ;
在于 / zai4yu2 / to lie in, to consist in ;
心态 / xin1tai4 / psychology, mental attitude ;
珍惜 / zhen1xi1 / to cherish, to treasure ;
否认 / fou3ren4 / to deny, to disavow ;
观察 / guan1cha2 / to observe, to watch ;
失去 / shi1qu4 / to lose ;
期间 / qi1jian1 / time, period ;
把握 / ba3wo4 / assurance, confidence ;
不假思索 / bu4jia3-si1suo3 / without thinking or hesitation ;
犯 / fan4 / to commit (an error, a crime, etc.) ;
过于 / guo4yu2 / too, excessively ;
原则 / yuan2ze2 / principle, tenet ;
责备 / ze4bei2 / to blame, to reproch ;
必然 / bi4ran2 , inevitable, certain ;
事先 / shi4xian1 / beforehand, in advance ;
舍不得 / she3bude / to be unwilling to part with or give up, to grudge ;
后果 / hou4guo3 / consequence, aftermath ;
屡 / lv3 / repeatedly, time and again ;

** source
* 练习

** 1
:PROPERTIES:
:ID: 48399829-e59a-44ae-a7e9-f29da5142b2d
:END:
*** 选择
**** 1
把握
**** 2
发挥
**** 3
观察
**** 4
教训
**** 5
因素
**** 6
眼睁睁
*** 题目
**** 1
***** 句子填空
吸取[[gap]]才能避免以后再次发生同样的问题。
***** 答案
4
**** 2
***** 句子填空
工作压力太大、不能兼顾（jiāngù， to give consideration to two or more things）工作和家庭是影响幸福感的重要[[gap]]。
***** 答案
5
**** 3
***** 句子填空
希望你在比赛中[[gap]]好，赛出好成绩！
***** 答案
2
**** 4
***** 句子填空
只有做好准备的人才能[[gap]]隹机会。
***** 答案
1
**** 5
***** 句子填空
你就这样[[gap]]地看着他摔倒了？！
***** 答案
6
**** 6
***** 句子填空
仔细[[gap]]周围的大自然，你会发现很多有意思的东西。
***** 答案
3
** 2
*** 1
:PROPERTIES:
:ID: 94b43a87-94a2-43bd-99e6-fd330bde6e37
:END:
**** 句子填空
这几次考试我都考得不太好，觉得有点儿[[gap]]。
**** 选择
***** A
灰心
***** B
死心
**** 答案
A
*** 2
:PROPERTIES:
:ID: 3891d53f-69c6-4c0a-b52a-a56585a244f2
:END:
**** 句子填空
在国外工作[[gap]]，我一直很想念我家的乡和家人。
**** 选择
***** A
时期
***** B
期间
**** 答案
B
*** 3
:PROPERTIES:
:ID: fbdc16c7-4208-489a-bb80-5406e7ad0ba5
:END:
**** 句子填空
如果有变动，请[[gap]]24小时告诉我。
**** 选择
***** A
事先
***** B
提前
**** 答案
B
*** 4
:PROPERTIES:
:ID: f10c4f84-2d71-4ebc-bcbe-7a31109b4748
:END:
**** 句子填空
你要想清楚，这样做的[[gap]]很严重！
**** 选择
***** A
后果
***** B
结果
**** 答案
A
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
你[[A]]说得这么复杂，我[[B]]觉得他[[C]]能[[D]]听懂。
**** 词语
未必
**** 答案
C
*** 2
**** 句子
[[A]]我看，老板没有糟糕的，[[B]]关键[[C]]你[[D]]怎样去和他沟通。
**** 词语
在于
**** 答案
C
*** 3
**** 句子
在很多[[A]]家庭中，夫妻[[B]]同时[[C]]工作并[[D]]做家务。
**** 词语
双方
**** 答案
B
*** 4
**** 句子
开始学滑雪[[A]]的时候，我花了很长时间[[B]]学习[[C]]怎么停[[D]]。
**** 词语
下来
**** 答案
D
* 扩展
** 词语
*** 话题
家居2
*** 词语
**** 1
夹子
**** 2
梳子
**** 3
肥皂
**** 4
扇子
**** 5
剪刀
**** 6
绳子
**** 7
锁
**** 8
叉子
**** 9
锅
**** 10
壶
**** 11
盆
**** 12
火柴
** 题目
*** 1
**** 句子
这份文件有好几页，拿个[[gap]]夹一下吧，别丢了。
**** 答案
1
*** 2
**** 句子
一把钥匙开一把[[gap]]。
**** 答案
7
*** 3
**** 句子
中国人吃饭习惯用筷子，西方人吃饭习惯用刀和[[gap]]。
**** 答案
8
*** 4
**** 句子
周末的下午，坐在阳光下，喝[[gap]]茶，感觉很舒服。
**** 答案
10
* 注释
** （三）词语辨析
*** 损失——失去
**** 做一做
***** 1
****** 句子
生意失败，他[[gap]]了很多钱。
****** 答案
******* 1
******** 损失
1
******** 失去
0
***** 2
****** 句子
因为一场病，他[[gap]]了记忆。
****** 答案
******* 1
******** 损失
0
******** 失去
1
***** 3
****** 句子
要珍惜时间，因为[[gap]]的时间永远都不会再回来。
****** 答案
******* 1
******** 损失
0
******** 失去
1
***** 4
****** 句子
这次火灾造成了巨大的[[gap]]。
****** 答案
******* 1
******** 损失
1
******** 失去
0
