* 课文
** 转录
对普通人来说，睡觉只是惯例，可是对于患有顽固失眠症的人来说，睡觉却成了难得的奢侈。
近日，中国发布的睡眠指数总得分 66.5 分，超过 36.2％的居民得分低于及格线 60 分。统计数字显示，睡眠指数的得分随着城市层级的升高而下降，一线城市的平均睡眠指数为 60.3 分，三线城市为 61.4 分，而农村和小城镇得分均在 70 分以上。可见，当前失眠症正扰乱着人们的情绪，摧残着城市人群的健康。
调查发现，该睡时不睡，是影响成人健康睡眠的重要因素。手机和平板电脑的普及，使睡前上网的习惯日渐盛行，不少人临睡前再过过网瘾成了常态。而电子产品严重的光污染不仅影响了人体褪黑素的正常分泌，还会使人体生物钟后移，结果就是晚上睡不着，早上睡不醒。
褪黑素是什么？据研究，褪黑素是保证人体健康的重要物质之一，它的职能包括增强人体免疫力、抗衰老、调剂睡眠等。当人体内褪黑素分泌不正常时，人体细胞组织和器官的作用和活动能力都会受到影响，各种疾病，包括恶性肿瘤，也就是我们常说的癌症，就会随之而来。
除了睡不着，还有人睡不好。中国有睡眠障碍的人约为 38.2％，因此，在中国专治睡眠障碍的医生总是供不应求。
睡眠障碍表现为入睡困难，头在枕头上，就是睡不着，翻来覆去瞎折腾，心烦意乱得无法容忍，白天又老是犯困。此外，入睡后噩梦连连，一会儿蹬腹，一会儿挥拳头，不时大声叫喊，也是睡眠障碍的典型症状。
睡眠不足会使人气色不好，行为能力偏离正常轨道，据悉，一个17～19 个小时没睡觉的人，其行为能力与一个血液中酒精浓度为 0.05％的人不相上下。即便一周内每天少睡两个小时，疲劳也会累积在一起，并在不适宜的场合引发事故，我们曾见过这样一个不可思议的案例，一位技术熟练的老司机把车开上了逆行道，而这就是疲劳驾驶造成的。
此外，长期睡眠不足还会使人注意力下降、表情茫然、丢三落四、情绪起伏不定，动不动就发呆，继而记性越来越差，到了更严重的地步，会思维混乱，健康状况逐步恶化，进而诱发慢性疾病。总而言之，睡眠好坏对人体健康举足轻重，因此，医生呼吁，不要对失眠症状无动于衷，要弄清病因，并根据不同情况竭尽全力进行治疗。
不可否认的是，很多人原本睡眠是没有问题的，导致问题的根源多多少少与不健康的生活方式有关，因此，对付失眠症的方法就是纠正不好的生活习惯，不要糟蹋自己的身体，不要自己迫害自己，不要让坏习惯毁灭我们的健康。
