* 听力

** 第二部分
:PROPERTIES:
:ID: 4a226529-7735-4691-af9e-8979b513ac87
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：不少人认为《西游记》是儿童读物，请问您是怎样看待《西游记》的特点以及它在中国文学史上的地位的？
男：《西游记》是中国古代小说中最容易为儿童接受的作品，这本身就是极为可贵的。要知道，中国古代除了民间故事和童谣，儿童可读的作品几乎没有。不过，这并不意味着《西游记》是肤浅的。一方面，对童心童趣的向往，可能是人难以泯灭的本性。而《西游记》神奇瑰丽、自由天真的想象，或许有助于我们暂时回归这一本性。另一方面，《西游记》又不只是单纯的童话，其中蕴含了丰富的中国文化。
女：您能具体谈一谈吗？
男：具体来说，孙悟空的机智勇敢、诙谐幽默代表了英雄主义和乐观主义；唐僧的坚定虔诚、软弱无能反映出旧时代知识分子面对瞬息万变的现实时缺乏应对能力；猪八戒的贪图安逸、目光短浅体现了传统农民的保守心理；至于沙和尚的勤恳依顺，也折射着我国民众朴实善良的品性。
女：有道理。
男：能够以一部作品如此鲜活地概括民族性格的几个重要类型，在古代小说中是不多见的。
女：这么说，即使在今天，《西游记》也还是很有现实意义的。
男：对呀。我们常常可以在以上这些人物身上看到自己或者我们相识的人的影子。也许，你渴望摆脱一切束缚，那么，孙悟空一定是你心仪的榜样；也许，你有时不免为物色诱惑，做出些荒唐可笑的事，那么，不妨以猪八戒为自嘲的镜子；万一你不幸如唐僧处处逢灾，又无能为力，也不必自怨自艾，只要虔诚坚定，西天还是可以到达的；假如你普普通通，默默奉献如沙和尚，最终也会赢得人们的赞赏和尊敬。

**** 音频

7a051a43-150e-48eb-9f02-7b3e098ddf2e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1702f390-7b41-4d35-bae9-db5e50c8f43c
:END:

***** 问题

关于《西游记》的可贵之处，下列哪项正确？

****** 音频

d0866e39-4d86-4f29-9da1-c27bad68a7be.mp3

***** 选择

****** A

容易为儿童接受

****** B

书中有民间故事

****** C

书中有许多童诫

****** D

是为儿童创作的

***** 答案

A

**** 7
:PROPERTIES:
:ID: 14cdf506-26ca-4d01-8533-d544d174a8ef
:END:

***** 问题

为什么说《西游记》并不肤浅？

****** 音频

ff714da0-cbb3-4b9e-a1ea-908708cdab13.mp3

***** 选择

****** A

它是一部优秀的童话

****** B

它能启发人的想象力

****** C

它能帮助成年人回忆童年

****** D

它有丰富的中国文化内淼

***** 答案

D

**** 8
:PROPERTIES:
:ID: 40d70744-f420-4273-ab6a-7bef5b94ff43
:END:

***** 问题

关于《西游记》反映的民族性格，可以知道什么？

****** 音频

fcefb446-2415-4f54-9f43-0079e71a0785.mp3

***** 选择

****** A

孙悟空反映出中国人很重视集体观念

****** B

唐僧反映出古代知识分子对现实的不满

****** C

猪八戒反映出中国传统农民的乐观心理

****** D

沙和尚反映出中国人朴实而善良的品格

***** 答案

D

**** 9
:PROPERTIES:
:ID: 194d9181-f562-4d0a-baaf-49fc6d037598
:END:

***** 问题

关于《西游记》的现实意义，下列哪项正确？

****** 音频

1c0ce09e-68f9-4227-b540-ae1cc839d2d9.mp3

***** 选择

****** A

孙悟空仍是我们学习的榜样

****** B

性格懦羽也不是要命的缺点

****** C

从中可以看到现代人的影子

****** D

默默奉献的精神才会受尊敬

***** 答案

C

**** 10
:PROPERTIES:
:ID: 524a187d-1664-43a1-aa57-ceb482701aa9
:END:

***** 问题

这段话主要谈的是什么？

****** 音频

2087bf80-c7e8-4b80-876e-9cd644e178a9.mp3

***** 选择

****** A

《西游记》的故事情节

****** B

《西游记》与儿童文学

****** C

《西游记》中的人物性格

****** D

《西游记》的特点和历史地位

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

有钱就能整天山珍海咖

***** B

餐桌上多数是大鱼大肉

***** C

大家喜欢在校长家里聚餐

***** D

在校长家吃的是西式餐点

**** 段话

那次聚会我至今记忆犹新。一群富家子弟，山珍海味都已吃过，就是不曾见过西点西餐，在校长家里他们才算真正“大开洋荤”，吃的是西式糕点，喝的是咖啡、可乐。

***** 音频

52a0b2f7-3255-4972-a1bc-0c631dbf0c4d.mp3

**** 答案

D

*** 2

**** 选择

***** A

野生动物保护应继续加强

***** B

捕杀野生动物都会被严惩

***** C

有人竟然驱车捕杀野生动物

***** D

捕杀野生动物的现象已很少

**** 段话

捕杀野生动物、破坏生态平衡的行为之所以屡禁不止，皆因“利”之驱动。如果捕杀了野生动物卖不出去，且有严格的法律法规，犯法就兑现，捕杀就会被重判，干这个行当的人就会越来越少。

***** 音频

7770ee84-3b17-4a0c-81d1-8deab7fa650e.mp3

**** 答案

A

*** 3

**** 选择

***** A

说话人得到了别人的帮助

***** B

说话人的命运在别人手里

***** C

说话人坚持履行自己的诺言

***** D

说话人是一副失败者的姿态

**** 段话

我碰了无数次壁，也没推出自己的歌，我绝望了，想重返地铁口，从此安心做我的地铁歌手，并发誓永远不再去那个所谓的歌坛折腾。这时候，一位真正有才有德的艺人出现了，是他彻底改变了我的命运！

***** 音频

ff06a7ac-aaf3-49d2-8063-ae11b1d2cf11.mp3

**** 答案

A

*** 4

**** 选择

***** A

说话人经常得罪人

***** B

说话人出版了一本书

***** C

说话人文章写得很漂亮

***** D

说话人是个刚人门的记者

**** 段话

在访谈中，我的一些说法可能有失偏颇，请大家原谅。在一些文章中，我的观点不够成熟，请大家包涵。总之，在传媒行业，我有许多东西需要学习，真诚地希望通过本书结识更多的媒体同行，向大家请教学习。

***** 音频

fc3aada2-14a1-49a2-a672-6f404b6f7fad.mp3

**** 答案

B

*** 5

**** 选择

***** A

当代独生女都很能干

***** B

独生子女都被宠坏了

***** C

青春期女孩更具叛逆性

***** D

现在的中国学生很不听话

**** 段话

当代中学生“青春期”发育普遍提前，尤其是女中学生，由于身心发展普遍比男生快，加上独生女在家庭中的地位得到强化，她们往往敢于做一些引人注目、与众不同的事，爱说一些令人吃惊的话，比男生更敢于顶撞和冒犯父母。

***** 音频

10ee7f76-6c8d-4d59-90e6-0cf4de618dc8.mp3

**** 答案

C

** 第三部分

*** 11-13

**** 课文

塞万提斯出生在一个医生家庭，有过军旅生活的经历，并屡立战功，得到嘉奖，曾经被俘身负重伤。当他拿着元帅的保荐书，兴致勃勃归国时，途中再次被俘，做了 5 年苦工后才得以回国。没想到，回来后，他连工作都找不到，历尽艰辛，才勉强找了份工作，后又被诬陷入狱。出狱后，他干上了税收。一次他把税款交给一家银行保管，偏偏银行倒闭，他第二次入狱。

出狱后，他陷入贫困，妹妹、妻子、儿女，一大家子人都等着他抚养。他住的地方环境极其恶劣，楼下就是酒馆。一天，有人酒后斗殴，眼看就要发生命案，他不顾一切，把那人背到家里，谁知人没救活，他涉嫌谋杀再次入狱。

虽然恶运缠身，他却没有被打倒，相反思想却变得异常丰富。他凭着对生活的反思和斗牛士的精神，写出了震惊世界的巨著——《堂•吉诃德》。

**** 题目

***** 11

****** 选择

******* A

医术

******* B

军功

******* C

经历

******* D

作品

****** 问题

塞万提斯靠什么出的名？

****** 答案

D

***** 12

****** 选择

******* A

他做过军医

******* B

他做过斗牛士

******* C

他曾三次人狱

******* D

他做过三次俘虏

****** 问题

关于塞万提斯的经历，下列哪项正确？

****** 答案

C

***** 13

****** 选择

******* A

他的运气特别不好

******* B

他喜欢银行的工作

******* C

他天生是个思想家

******* D

他一直在为写作做准备

****** 问题

根据这段话，可以知道什么？

****** 答案

A

*** 14-17

**** 课文

“我的手还能活动；我的大脑还能思维；我有终生追求的理想；我有爱我和我爱着的亲人与朋友；对了，我还有一颗感恩的心……”。谁能想到这段豁达而美妙的文字，竟出自一位在轮椅上生活了三十余年的高位截瘫的残疾人——世界科学巨匠霍金。

在常人看来，命运真是亏待了霍金，可他仍感到自己很富有：一根能活动的手指，一个能思维的大脑……这些都让他感到满足，并对生活充满了感恩之心。因而，他的人生是充实而快乐的。

对生活、对世界、对身边熟悉和陌生的人、对我们的朋友和对手，怎么能不真诚感谢呢？是它们使我们的人生变得如此精彩。我们更要真诚地感恩生活中的逆境，它让我们得到锤炼；它是一个课堂，让我们学会了刻苦、忍耐、淡泊和宽容；它是一笔财富，经历了它，会让我们精神富有，终生享用不尽。

**** 题目

***** 14

****** 选择

******* A

工作的权利

******* B

灵活的大脑

******* C

祺高的理想

******* D

方便的轮椅

****** 问题

根据这段话，世界科学巨匠霍金很珍惜什么？

****** 答案

B

***** 15

****** 选择

******* A

非常容易满跃

******* B

有雄厚的经济实力

******* C

命运对他极其苛刻

******* D

对物质生活要求不多

****** 问题

关于常人眼中的霍金，下列哪项正确？

****** 答案

C

***** 16

****** 选择

******* A

它让我们的身体得到锻炼

******* B

它让我们得到更多的知识

******* C

它让我们嬴得了大量钱财

******* D

它让我们学会了如何感恩

****** 问题

关于生活中的逆境，下列哪项正确？

****** 答案

D

***** 17

****** 选择

******* A

有对手的生活才有味道

******* B

转变逆境需要好的对策

******* C

学生的生活也会有坎坷

******* D

挫折可以帮助我们成长

****** 问题

根据这段话，可以知道什么？

****** 答案

D

