* 听力

** 1

*** 1

**** trascript

那次聚会我至今记忆犹新。一群富家子弟，山珍海味都已吃过，就是不曾见过西点西餐，在校长家里他们才算真正“大开洋荤”，吃的是西式糕点，喝的是咖啡、可乐。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:44:55 -05]
:END:

That party is still fresh in my mind. A group of rich children, all the food has been eaten, but never seen the western food, in the principal's house they are really "not open foreign meat", eating Western-style pastry, drinking coffee, Coke.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

捕杀野生动物、破坏生态平衡的行为之所以屡禁不止，皆因“利”之驱动。如果捕杀了野生动物卖不出去，且有严格的法律法规，犯法就兑现，捕杀就会被重判，干这个行当的人就会越来越少。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:49:12 -05]
:END:

Hunting and killing of wildlife, ecological balance of the behavior is repeatedly prohibited, all because of the "profit" drive. If the capture and kill of wild animals can not be sold, and there are laws and regulations, the law is now the situation, the capture and kill will be heavily sentenced to do this business will be less and less people.


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

我碰了无数次壁，也没推出自己的歌，我绝望了，想重返地铁口，从此安心做我的地铁歌手，并发誓永远不再去那个所谓的歌坛折腾。这时候，一位真正有才有德的艺人出现了，是他彻底改变了我的命运！

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:51:58 -05]
:END:

I hit the wall countless times and didn't launch my own songs, I was desperate and wanted to return to the subway entrance, to be my subway singer from then on, and to pay a golden vow never to go to that so-called singing world again. That's when a truly talented and virtuous artist came along, who changed my fate completely!

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** trascript

在访谈中，我的一些说法可能有失偏颇，请大家原谅。在一些文章中，我的观点不够成熟，请大家包涵。总之，在传媒行业，我有许多东西需要学习，真诚地希望通过本书结识更多的媒体同行，向大家请教学习。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:56:19 -05]
:END:

Please forgive me for some of my statements in the interview that may be biased. In some articles, my views are not mature enough, so please bear with me. In short, I have a lot to learn in the media industry, and I sincerely hope to meet more media colleagues through this book and ask for your advice and learning.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

当代中学生“青春期”发育普遍提前，尤其是女中学生，由于身心发展普遍比男生快，加上独生女在家庭中的地位得到强化，她们往往敢于做一些引人注目、与众不同的事，爱说一些令人吃惊的话，比男生更敢于顶撞和冒犯父母。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:59:40 -05]
:END:

Contemporary secondary school students are generally developing earlier in their adolescence, especially female secondary school students, as their physical and mental development is generally faster than that of male students, coupled with the reinforced status of only girls in the family, they often dare to do something striking and different, love to say some surprising things, and dare to hit and offend their parents more than male students.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



