* 听力

** 1

*** 1

**** trascript

那次聚会我至今记忆犹新。一群富家子弟，山珍海味都已吃过，就是不曾见过西点西餐，在校长家里他们才算真正“大开洋荤”，吃的是西式糕点，喝的是咖啡、可乐。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:44:55 -05]
:END:

That party is still fresh in my mind. A group of rich children, all the food has been eaten, but never seen the western food, in the principal's house they are really "not open foreign meat", eating Western-style pastry, drinking coffee, Coke.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

捕杀野生动物、破坏生态平衡的行为之所以屡禁不止，皆因“利”之驱动。如果捕杀了野生动物卖不出去，且有严格的法律法规，犯法就兑现，捕杀就会被重判，干这个行当的人就会越来越少。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:49:12 -05]
:END:

Hunting and killing of wildlife, ecological balance of the behavior is repeatedly prohibited, all because of the "profit" drive. If the capture and kill of wild animals can not be sold, and there are laws and regulations, the law is now the situation, the capture and kill will be heavily sentenced to do this business will be less and less people.


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

我碰了无数次壁，也没推出自己的歌，我绝望了，想重返地铁口，从此安心做我的地铁歌手，并发誓永远不再去那个所谓的歌坛折腾。这时候，一位真正有才有德的艺人出现了，是他彻底改变了我的命运！

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:51:58 -05]
:END:

I hit the wall countless times and didn't launch my own songs, I was desperate and wanted to return to the subway entrance, to be my subway singer from then on, and to pay a golden vow never to go to that so-called singing world again. That's when a truly talented and virtuous artist came along, who changed my fate completely!

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** trascript

在访谈中，我的一些说法可能有失偏颇，请大家原谅。在一些文章中，我的观点不够成熟，请大家包涵。总之，在传媒行业，我有许多东西需要学习，真诚地希望通过本书结识更多的媒体同行，向大家请教学习。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:56:19 -05]
:END:

Please forgive me for some of my statements in the interview that may be biased. In some articles, my views are not mature enough, so please bear with me. In short, I have a lot to learn in the media industry, and I sincerely hope to meet more media colleagues through this book and ask for your advice and learning.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

当代中学生“青春期”发育普遍提前，尤其是女中学生，由于身心发展普遍比男生快，加上独生女在家庭中的地位得到强化，她们往往敢于做一些引人注目、与众不同的事，爱说一些令人吃惊的话，比男生更敢于顶撞和冒犯父母。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:59:40 -05]
:END:

Contemporary secondary school students are generally developing earlier in their adolescence, especially female secondary school students, as their physical and mental development is generally faster than that of male students, coupled with the reinforced status of only girls in the family, they often dare to do something striking and different, love to say some surprising things, and dare to hit and offend their parents more than male students.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：不少人认为《西游记》是儿童读物，请问您是怎样看待《西游记》的特点以及它在中国文学史上的地位的？
男：《西游记》是中国古代小说中最容易为儿童接受的作品，这本身就是极为可贵的。要知道，中国古代除了民间故事和童谣，儿童可读的作品几乎没有。不过，这并不意味着《西游记》是肤浅的。一方面，对童心童趣的向往，可能是人难以泯灭的本性。而《西游记》神奇瑰丽、自由天真的想象，或许有助于我们暂时回归这一本性。另一方面，《西游记》又不只是单纯的童话，其中蕴含了丰富的中国文化。
女：您能具体谈一谈吗？
男：具体来说，孙悟空的机智勇敢、诙谐幽默代表了英雄主义和乐观主义；唐僧的坚定虔诚、软弱无能反映出旧时代知识分子面对瞬息万变的现实时缺乏应对能力；猪八戒的贪图安逸、目光短浅体现了传统农民的保守心理；至于沙和尚的勤恳依顺，也折射着我国民众朴实善良的品性。
女：有道理。
男：能够以一部作品如此鲜活地概括民族性格的几个重要类型，在古代小说中是不多见的。
女：这么说，即使在今天，《西游记》也还是很有现实意义的。
男：对呀。我们常常可以在以上这些人物身上看到自己或者我们相识的人的影子。也许，你渴望摆脱一切束缚，那么，孙悟空一定是你心仪的榜样；也许，你有时不免为物色诱惑，做出些荒唐可笑的事，那么，不妨以猪八戒为自嘲的镜子；万一你不幸如唐僧处处逢灾，又无能为力，也不必自怨自艾，只要虔诚坚定，西天还是可以到达的；假如你普普通通，默默奉献如沙和尚，最终也会赢得人们的赞赏和尊敬。
