* 听力

** 第二部分
:PROPERTIES:
:ID: c507f1d0-23cf-4c3f-a52a-41d897d6cd44
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：听说你是个美食家？
男：美食家谈不上，只能说我是一个对美食没有抵抗力的人，我的优点就是不挑食。
女：你认为什么是美食？
男：美食是可以让你身心愉悦的妙药。
女：能说得具体点儿吗？
男：在心情好的时候、疲惫的时候或是悠闲的时候，享受一顿可口的饭菜，那一定是最幸福的时刻。
女：看来吃什么在其次，只要能让你有愉快的感受，什么都是美食？
男：可以这么说。可是也有例外，对于我来讲，新疆的饭菜都是美味佳肴，因为我是新疆人嘛。还有，南京算是我的第二故乡，我对南京美食也是爱得不得了呀。
女：对吃你有什么感悟？
男：俗话说“民以食为天”，吃对于每个人来讲都是生存本能。可是，众所周知，吃给予我们的远不止于此，我更在意的是与家人、友人在“吃”的那个时刻围坐在一起，暂时放下忙碌的工作，忘掉这样那样的烦恼，享受片刻难得的悠闲。
女：平常你下厨吗？
男：以前经常下厨，现在因为工作的关系，下厨少了。其实我很享受烹饪的过程，能亲手为家人准备一桌饭菜，是一件非常幸福的事情。虽然做不出用料复杂、精致无比的饭菜，色香味俱佳还是没有问题的。
女：讲个关于你的吃的故事吧？
男：要说就说与拍戏有关的吃，那是在拍摄《特种兵》的时候。这部戏主要讲的是女特种兵的故事，拍戏强度很高，体力消耗特别大。我们的阵容中女演员居多，女孩子嘛，本来就喜欢吃一些零食和水果之类的东西，可是在戏里我是教官，总操练她们，尤其不允许她们吃零食。每天女演员们顶着烈日做体能训练，还得忍受我的“训斥”。直到今天，我心里还对她们抱有歉意，觉得当时我丧失了一个男子汉对女士们应有的同情心。

**** 音频

164c19e3-8938-4f95-afcb-2afa9be0e641.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: c6b28bc3-77d4-45a3-b224-5509183062c0
:END:

***** 问题

在吃的问题上，男的是个什么样的人？

****** 音频

92fd1d7b-6361-41cf-b78f-939b4efbc197.mp3

***** 选择

****** A

没有不爱吃的食物

****** B

对美食的要求很高

****** C

只吃自已喜爱的食物

****** D

对美食有奇特的标准

***** 答案

A

**** 7
:PROPERTIES:
:ID: 61ceecde-7843-40c2-8031-ed57b05b5d5f
:END:

***** 问题

关于男的眼中的美食，下列哪项正确？

****** 音频

233cbbef-7c2d-49cf-b326-fd7b8289e723.mp3

***** 选择

****** A

美食是可以治病的

****** B

口昧独特的是美食

****** C

家乡的食物是美食

****** D

饿了吃什么都是美食

***** 答案

C

**** 8
:PROPERTIES:
:ID: 793c381d-c08d-4fac-8ac5-9f9d86cb91e2
:END:

***** 问题

对于吃，男有什么感悟？

****** 音频

131963ff-b7ef-46b8-b6a0-2e59a697624d.mp3

***** 选择

****** A

吃是人生头等大事

****** B

吃能解决生存问题

****** C

吃能提供营养，保证健康

****** D

可以和亲友一起享受悠闲

***** 答案

D

**** 9
:PROPERTIES:
:ID: e4943dac-ba80-495b-818c-8af7c0ef851a
:END:

***** 问题

在做饭的问题上，下列哪项正确？

****** 音频

c3243686-8ffa-4a73-a7f8-4a1af6f7dd7c.mp3

***** 选择

****** A

男的历来就不愿意做饭

****** B

男的太忙，没学过做饭

****** C

男的做饭手艺相当不错

****** D

男的做饭非常讲究用料

***** 答案

C

**** 10
:PROPERTIES:
:ID: 513d59ff-812a-44ed-8eaf-3df2f33bdefd
:END:

***** 问题

关于吃的故事，下列哪项正确？

****** 音频

5efbb6b2-9f15-4419-b827-fedbaf58970c.mp3

***** 选择

****** A

男的拍戏时经常吃零食

****** B

女演员怕胖不敢吃零食

****** C

男的看不惯女演员老吃零食

****** D

戏中男的不让女演员吃零食

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

每个孩子都有自己的特长

***** B

好老师要能发现学生的问题

***** C

老师要善于帮学生解决问题

***** D

老师要根据学生的特长加以引导

**** 段话

青少年的兴趣爱好若能及早得到培养，就能表现出某一方面的才能。老师根据学生的爱好，有意识地加以引导，就会使学生在自己爱好的活动中发展特长、增长聪明才智，进而具有发现问题、分析问题、解决问题的能力。

***** 音频

d812959f-6844-4a85-83ec-0dcb5469de60.mp3

**** 答案

D

*** 2

**** 选择

***** A

乌鲁木齐是新疆的首府

***** B

在新疆40人高温很普道

***** C

7月份新疆的天气反复无常

***** D

乌鲁木齐的气温高于吐鲁番

**** 段话

7月份新疆出现异常高温天气，大部分地区最高气温在35摄氏度以上,一些地区的最高气温为40摄氏度以上。首府乌鲁木齐14日最高气温达到40.6摄氏度,突破近30年来最高气温历史极值,吐鲁番地区最高气温达到46.2摄氏度。

***** 音频

76a692b0-8726-45fe-ae33-a1739647da74.mp3

**** 答案

A

*** 3

**** 选择

***** A

每个人都向交际提出新要求

***** B

历史会记录社会的发展变化

***** C

语言会随着社会的变化而变化

***** D

书面语和口语有许多不同之处

**** 段话

随着社会的发展，新事物、新概念不断出现，这些都会向交际提出新的要求，我们翻阅解放前的书报杂志，就会感到有些词语很陌生，有些格式很不习惯。社会的发展变迁必然会在语言的词汇里留下印记。

***** 音频

d59fbbd3-47bf-4fa4-b855-02ea3a5958e8.mp3

**** 答案

C

*** 4

**** 选择

***** A

林行止、熊秉元都是小说作家

***** B

林行止的书介绍了很多旅游景点

***** C

熊秉元的书内容常涉及餐饮美显

***** D

“经济新观察“是一套经济学书籍

**** 段话

今年读到了新近出版的“经济新观察”丛书中的林行止系列和熊秉元系列。林行止读书甚广，读他的文章犹如进入阿里巴巴的山洞，美不胜收。熊秉元善于从一些日常小事中总结出经济学精神，读来有滋有味。

***** 音频

fb8c1140-5db6-47e3-817e-a7c22b317c12.mp3

**** 答案

D

*** 5

**** 选择

***** A

人类的定居促进了人口的增长

***** B

农业的发展也促进了渔猎文明

***** C

人口迁移是为了解决耕地问题

***** D

人类定居从渔猎时期就开始了

**** 段话

从渔猎到农业，人类社会先是出现了半永久性的农牧业村舍，之后有了定居的村庄。但这种状况也未能持久，一旦地力衰竭或人口增长过快，整个村舍就要迁移，或分裂成较小的组团，寻找新的住地，以保证足够的耕地。

***** 音频

05fd0009-bc2b-4bcd-bb1d-606fa4d9ac68.mp3

**** 答案

C

** 第三部分

*** 11-13

**** 课文

传统密码的缺陷是显而易见的，简单的密码依然是大多数人保护个人隐私的最常见方式。以人体生物特征作为密码，真的可以变为现实吗？回答是肯定的，距离我们越来越近的“眼泪密码”便是如此。由于眼泪作用于角膜的结果无法被复制，因此“眼泪密码”的安全性有了质的提升。

“眼泪密码”之所以保密性强，是因为每个人的角膜都有独特的图像，扫描仪可据此甄别不同的人。如果黑客偷取并使用某人上次使用过的数据，机器会认定其无效，因为它“懂得”每次扫描结果都应该有细微的变化。这是因为，角膜表面因有泪水而湿润，因此数据是实时改变的。

还有科学家在探索声音密码，也有银行推出指纹密码。不过，生物密码技术目前并不完全成熟，假如一个人的手指肿了，那么机器则无法识别出指纹密码。

*** 14-17

**** 课文

蛤蜊，身上长着像树木年轮一样的纹路，每成长一年，它就仔细地划上一道完美的圆圈。科学家们数了又数，身上有一百二十多圈的蛤蜊并不稀少，也就是说这些蛤蜊穿越了一个世纪，又健康快乐地生活了二十多年。目前发现的最高龄蛤蜊为 507 岁。

想知道蛤蜊长寿的秘诀吗？夏天对许多动物来说都是最享受的季节，它们大口大口地吃东西，以保持正常的新陈代谢；夏季的美食足够丰盛，它们不担心会没有东西可享用。对于蛤蜊来说，夏季是最幸福的季节，它们要繁殖后代，要承担起做父母的责任和义务，它们没有过多的时间去享用美食，它们的生活简单而快乐。冬天到了，宝宝们长大了，爸爸妈妈也自由了。但这时候草木枯萎、万物藏匿，蛤蜊吃不到多少可口的食物。好在它们习惯了节省而优雅的生活，只要有一些东西吃就足够满意和幸福了。

正是这些高贵的品质保证了蛤蜊的长寿。也许聪明的人类，这时你恍然大悟了吧，我们总能够从蛤蜊身上想到些什么吧！

