* 听力

** 1

*** 1

**** transcript

青少年的兴趣爱好若能及早得到培养，就能表现出某一方面的才能。老师根据学生的爱好，有意识地加以引导，就会使学生在自己爱好的活动中发展特长、增长聪明才智，进而具有发现问题、分析问题、解决问题的能力。

***** translation

Young people can show their talents in a certain area if their interests are cultivated. If teachers consciously guide students according to their hobbies, students will develop their strengths and talents in their hobby activities, and then have the ability to identify, analyze and solve problems.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

7月份新疆出现异常高温天气，大部分地区最高气温在35摄氏度以上，一些地区的最高气温为40摄氏度以上。首府乌鲁木齐14日最高气温达到40.6摄氏度，突破近30年来最高气温历史极值，吐鲁番地区最高气温达到46.2摄氏度。

***** translation

In July, there was unusually high temperature in Xinjiang, with the maximum temperature in most areas above 35 degrees Celsius, and in some areas the maximum temperature was above 40 degrees Celsius. The maximum temperature in the capital city of Urumqi reached 40.6 degrees Celsius on the 14th, breaking the historical maximum temperature pole in the past 30 years, and the maximum temperature in Turpan area reached 46.2 degrees Celsius.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

随着社会的发展，新事物、新概念不断出现，这些都会向交际提出新的要求，我们翻阅解放前的书报杂志，就会感到有些词语很陌生，有些格式很不习惯。社会的发展变迁必然会在语言的词汇里留下印记。

***** translation

With the development of society, new things and new concepts are constantly appearing, which will put forward new requirements for communication. When we look through the pre-liberation books and magazines, we will feel that some words are unfamiliar and some formats are uncomfortable. The development of society is bound to leave a mark in the language vocabulary.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

今年读到了新近出版的“经济新观察”丛书中的林行止系列和熊秉元系列。林行止读书甚广，读他的文章犹如进入阿里巴巴的山洞，美不胜收。熊秉元善于从一些日常小事中总结出经济学精神，读来有滋有味。

***** translation

This year, I read Lin Xingzhi and Xiong Pingyuan in the newly published "New Economic Observation" series. Lin Xingzhi has read extensively and his articles are like entering Alibaba's cave, which is beautiful. Xiong Bingyuan is good at summing up the spirit of economics from some small things in daily life, which is tasty to read.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

从渔猎到农业，人类社会先是出现了半永久性的农牧业村舍，之后有了定居的村庄。但这种状况也未能持久，一旦地力衰竭或人口增长过快，整个村舍就要迁移，或分裂成较小的组团，寻找新的住地，以保证足够的耕地。

***** translation

From fishing and hunting to agriculture, human society first saw the emergence of semi-permanent agro-pastoralist village houses, followed by settled villages. However, this situation did not last, and once the land was exhausted or the population grew too fast, the whole village house had to be moved or split into smaller groups to find new settlements in order to keep enough arable land.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: c507f1d0-23cf-4c3f-a52a-41d897d6cd44
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：听说你是个美食家？
男：美食家谈不上，只能说我是一个对美食没有抵抗力的人，我的优点就是不挑食。
女：你认为什么是美食？
男：美食是可以让你身心愉悦的妙药。
女：能说得具体点儿吗？
男：在心情好的时候、疲惫的时候或是悠闲的时候，享受一顿可口的饭菜，那一定是最幸福的时刻。
女：看来吃什么在其次，只要能让你有愉快的感受，什么都是美食？
男：可以这么说。可是也有例外，对于我来讲，新疆的饭菜都是美味佳肴，因为我是新疆人嘛。还有，南京算是我的第二故乡，我对南京美食也是爱得不得了呀。
女：对吃你有什么感悟？
男：俗话说“民以食为天”，吃对于每个人来讲都是生存本能。可是，众所周知，吃给予我们的远不止于此，我更在意的是与家人、友人在“吃”的那个时刻围坐在一起，暂时放下忙碌的工作，忘掉这样那样的烦恼，享受片刻难得的悠闲。
女：平常你下厨吗？
男：以前经常下厨，现在因为工作的关系，下厨少了。其实我很享受烹饪的过程，能亲手为家人准备一桌饭菜，是一件非常幸福的事情。虽然做不出用料复杂、精致无比的饭菜，色香味俱佳还是没有问题的。
女：讲个关于你的吃的故事吧？
男：要说就说与拍戏有关的吃，那是在拍摄《特种兵》的时候。这部戏主要讲的是女特种兵的故事，拍戏强度很高，体力消耗特别大。我们的阵容中女演员居多，女孩子嘛，本来就喜欢吃一些零食和水果之类的东西，可是在戏里我是教官，总操练她们，尤其不允许她们吃零食。每天女演员们顶着烈日做体能训练，还得忍受我的“训斥”。直到今天，我心里还对她们抱有歉意，觉得当时我丧失了一个男子汉对女士们应有的同情心。

*** 音频

164c19e3-8938-4f95-afcb-2afa9be0e641.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: c6b28bc3-77d4-45a3-b224-5509183062c0
:END:

***** 问题

在吃的问题上，男的是个什么样的人？

***** 音频

92fd1d7b-6361-41cf-b78f-939b4efbc197.mp3

***** 选择

****** A

没有不爱吃的食物

****** B

对美食的要求很高

****** C

只吃自已喜爱的食物

****** D

对美食有奇特的标准

***** 答案

A

**** 7
:PROPERTIES:
:ID: 61ceecde-7843-40c2-8031-ed57b05b5d5f
:END:

***** 问题

关于男的眼中的美食，下列哪项正确？

***** 音频

233cbbef-7c2d-49cf-b326-fd7b8289e723.mp3

***** 选择

****** A

美食是可以治病的

****** B

口昧独特的是美食

****** C

家乡的食物是美食

****** D

饿了吃什么都是美食

***** 答案

C

**** 8
:PROPERTIES:
:ID: 793c381d-c08d-4fac-8ac5-9f9d86cb91e2
:END:

***** 问题

对于吃，男有什么感悟？

***** 音频

131963ff-b7ef-46b8-b6a0-2e59a697624d.mp3

***** 选择

****** A

吃是人生头等大事

****** B

吃能解决生存问题

****** C

吃能提供营养，保证健康

****** D

可以和亲友一起享受悠闲

***** 答案

D

**** 9
:PROPERTIES:
:ID: e4943dac-ba80-495b-818c-8af7c0ef851a
:END:

***** 问题

在做饭的问题上，下列哪项正确？

***** 音频

c3243686-8ffa-4a73-a7f8-4a1af6f7dd7c.mp3

***** 选择

****** A

男的历来就不愿意做饭

****** B

男的太忙，没学过做饭

****** C

男的做饭手艺相当不错

****** D

男的做饭非常讲究用料

***** 答案

C

**** 10
:PROPERTIES:
:ID: 513d59ff-812a-44ed-8eaf-3df2f33bdefd
:END:

***** 问题

关于吃的故事，下列哪项正确？

***** 音频

5efbb6b2-9f15-4419-b827-fedbaf58970c.mp3

***** 选择

****** A

男的拍戏时经常吃零食

****** B

女演员怕胖不敢吃零食

****** C

男的看不惯女演员老吃零食

****** D

戏中男的不让女演员吃零食

***** 答案

D

