* 听力

** 1

*** 1

**** transcript

青少年的兴趣爱好若能及早得到培养，就能表现出某一方面的才能。老师根据学生的爱好，有意识地加以引导，就会使学生在自己爱好的活动中发展特长、增长聪明才智，进而具有发现问题、分析问题、解决问题的能力。

***** translation

Young people can show their talents in a certain area if their interests are cultivated. If teachers consciously guide students according to their hobbies, students will develop their strengths and talents in their hobby activities, and then have the ability to identify, analyze and solve problems.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

7月份新疆出现异常高温天气，大部分地区最高气温在35摄氏度以上，一些地区的最高气温为40摄氏度以上。首府乌鲁木齐14日最高气温达到40.6摄氏度，突破近30年来最高气温历史极值，吐鲁番地区最高气温达到46.2摄氏度。

***** translation

In July, there was unusually high temperature in Xinjiang, with the maximum temperature in most areas above 35 degrees Celsius, and in some areas the maximum temperature was above 40 degrees Celsius. The maximum temperature in the capital city of Urumqi reached 40.6 degrees Celsius on the 14th, breaking the historical maximum temperature pole in the past 30 years, and the maximum temperature in Turpan area reached 46.2 degrees Celsius.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

随着社会的发展，新事物、新概念不断出现，这些都会向交际提出新的要求，我们翻阅解放前的书报杂志，就会感到有些词语很陌生，有些格式很不习惯。社会的发展变迁必然会在语言的词汇里留下印记。

***** translation

With the development of society, new things and new concepts are constantly appearing, which will put forward new requirements for communication. When we look through the pre-liberation books and magazines, we will feel that some words are unfamiliar and some formats are uncomfortable. The development of society is bound to leave a mark in the language vocabulary.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

今年读到了新近出版的“经济新观察”丛书中的林行止系列和熊秉元系列。林行止读书甚广，读他的文章犹如进入阿里巴巴的山洞，美不胜收。熊秉元善于从一些日常小事中总结出经济学精神，读来有滋有味。

***** translation

This year, I read Lin Xingzhi and Xiong Pingyuan in the newly published "New Economic Observation" series. Lin Xingzhi has read extensively and his articles are like entering Alibaba's cave, which is beautiful. Xiong Bingyuan is good at summing up the spirit of economics from some small things in daily life, which is tasty to read.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

从渔猎到农业，人类社会先是出现了半永久性的农牧业村舍，之后有了定居的村庄。但这种状况也未能持久，一旦地力衰竭或人口增长过快，整个村舍就要迁移，或分裂成较小的组团，寻找新的住地，以保证足够的耕地。

***** translation

From fishing and hunting to agriculture, human society first saw the emergence of semi-permanent agro-pastoralist village houses, followed by settled villages. However, this situation did not last, and once the land was exhausted or the population grew too fast, the whole village house had to be moved or split into smaller groups to find new settlements in order to keep enough arable land.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



