:PROPERTIES:
:CREATED: [2022-08-20 08:39:01 -05]
:END:

* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 071475de-5b70-4776-8799-43cc922b06dd
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
88e9d56a-b67a-4504-93a9-a83f46b63def.mp3
***** 转录
教师必须把教学活动组织得生动、有趣，除了教师讲授外，要多给学生参与的机会。小学生中出现的课堂纪律问题，往往不是学生故意捣乱，而是学生对教师的课不感兴趣，因而不能坚持听课。
**** 选择
***** A
小学生的注意力不能持仁
***** B
没有经验的老师上不好课
***** C
课有吸引力学生就会认真听
***** D
学生违反纪律是应该原谅的
**** 答案
C
*** 2
:PROPERTIES:
:ID: 04dee175-9824-484a-af75-d07379712c4d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
b709f83e-bc23-4fd0-a0e3-918c2462be6e.mp3
***** 转录
考古发掘中，能够直接参加考古工作的人终究是少数，且一旦发掘工作完毕，现场往往很难原样不动地保存下来，要想让更多的人了解某一地下发掘的现场、情景以及出土文物，只有依靠考古报告。
**** 选择
***** A
考古工作者的数量一直不跃
***** B
考古工作完毕，现场就破坏了
***** C
考古工作者都应该学习考古报告
***** D
考古报告能反映当时的考古发掘情况
**** 答案
D
*** 3
:PROPERTIES:
:ID: c7527d05-7614-4bc5-a417-56a1242fa44e
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
b0e2e70d-8698-4307-96be-a0ee74690fee.mp3
***** 转录
传统的化学工业给环境带来的污染已十分严重，并威胁着人类的生存。化学工业能否生产出对环境无害的化学品？甚至开发出不产生废物的工艺？有识之士提出了绿色化学的号召，并立即得到了全世界的积极响应。
**** 选择
***** A
化学工业正在进行一场革命
***** B
人们怀疑无害化学品的真实性
***** C
传统化学工业的生存受到了挑战
***** D
降低化学污染的号召得到了响应
**** 答案
D
*** 4
:PROPERTIES:
:ID: 0f84faaa-17aa-40c7-b48c-dc0fc6354a24
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
e6faa4ae-1310-44a0-8121-759590a2fd51.mp3
***** 转录
农历正月初一是古时的新年，又称“新正”，今天我们称之为“春节”。它作为古代官方法定岁首，乃汉武帝时编定的太初历所规定。千百年来，这个法定岁首逐步汇聚了许多其他节日的习俗，成为一个送旧迎新的节日。
**** 选择
***** A
春节是一年的最后一天
***** B
“春节“古时称为“新正“
***** C
汉武帝规定春节为法定节日
***** D
从一开始春节就有很多习俗
**** 答案
B
*** 5
:PROPERTIES:
:ID: 90ed6d97-3c27-4ec8-98ed-bf69e447f976
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
7764c7a3-e05f-4a0d-ba8c-117123f90c1b.mp3
***** 转录
小篆，是秦始皇统一六国之后，秦代通用的标准字体。相传是秦国丞相李斯所创。与大篆相比，小篆书写起来更加简便，字体长方，每个字大小一样，排列方正，横竖成行，给人一种整齐之美，这样也就形成了方圆兼备的小篆体。
**** 选择
***** A
小篆曾经风行六国
***** B
相传李斯创造了小篆
***** C
小篆可以写成方的或圆的
***** D
就书写简便而言，大篆更优
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: b3972204-d280-499d-a2d3-443c835d9c41
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
da25817e-346b-44be-9900-caf84a639022.mp3
***** 转录
男：离开美国后，你决定写这部非虚构题材的小说，有什么原因和契机吗？
女：这本书是我自己的一段人生历程，其中也包含了大量人们需要的信息。之前我只写形象更为复杂、主题相对悲观的虚构作品。说到非虚构题材的写作，原因和契机其实很偶然。去年，我和一位出版社编辑聊起我在美国陪孩子读书时的一些见闻，提到这样一个场景：一对华人夫妇星期天去购物，那是个冬天，下着鹅毛大雪，他们开车经过市中心，看到有个女孩儿高举标语牌，孤零零地站在教堂门口，标语牌上写着：“抗议反对人工流产”“抗议歧视同性恋”，华人夫妇议论道，这么冷的天，一个女孩子站在雪地里，也不知道她父母知道不知道，车到近前才骇然发现，这女孩儿竟是他们还在读高中的独生女儿。编辑朋友激动地打断我，提议我写下来。她认为，我这几年陪读生活中遇到的点点滴滴都值得记录下来，现在这么多中国家庭把孩子送出去留学，家长非常需要了解我经历过的这些事，中国教育是有问题，但异国生涯无论对小留学生还是对家长都未必不是挑战。
男：你是一个擅长写虚构小说和戏剧的作家，是什么让你决定从虚构的掩体中跃出，开始非虚构的写作？
女：关于非虚构写作，虽然我是第一次尝试，不过我很早就关注了。那是 2000年我在美国期间，逛书店的时候，我发现书店每周张贴出的畅销书前十名排行榜都分为两大类：虚构和非虚构，我吃惊地意识到，在美国，非虚构作品的数量和质量竟然可以和虚构作品不分伯仲。而那时，中国的文学刊物还没有“非虚构”栏目，虽然有报告文学，但报告文学只是非虚构里的一种形式。写这本书，我的初衷是希望和其他家长分享我所了解的美国高中校园，希望读者能够通过我和孩子的一些经历获得他们需要的信息，也希望通过我的视角让读者了解这个媒体上谈论最多的国家，因此比较有说服力的应该是非虚构这个写作形式。
**** 题目
***** 6
:PROPERTIES:
:ID: d0428248-c813-4416-96f4-17342f0c0214
:END:
****** 问题
******* 音频
6099cb26-7825-4003-ab85-f318b929e5f6.mp3
******* 转录
女的这本非虚构题材小说的写作契机是什么？
****** 选择
******* A
自己留学的经历
******* B
编辑朋友的建议
******* C
外国朋友的问题
******* D
女儿学校的要求
****** 答案
B
***** 7
:PROPERTIES:
:ID: 02ba94fa-e9cc-4a21-9f57-a50bd99ca1e4
:END:
****** 问题
******* 音频
df7e1cc0-0cef-4d1d-8b61-30f9b9eb50b0.mp3
******* 转录
关于编辑朋友，下列哪项正确？
****** 选择
******* A
被华人夫妇的女儿征服了
******* B
认为小留学生也面临挑战
******* C
认为中国家长有时很幼稚
******* D
庆幸自己认识一位好作者
****** 答案
B
***** 8
:PROPERTIES:
:ID: a2867def-71e3-41a9-a781-6edbd47180d6
:END:
****** 问题
******* 音频
ce385b2d-281e-497b-acf6-7b11deb00895.mp3
******* 转录
是什么原因促使女的愿意尝试非虚构写作？
****** 选择
******* A
非虚构文学在中国是空白
******* B
 2000年非虚构文学才出现
******* C
在美国非虚构作品很畅销
******* D
她接受了非虚构刊物的约稿
****** 答案
C
***** 9
:PROPERTIES:
:ID: 7ab8ae37-7610-4899-b7aa-b942537f9538
:END:
****** 问题
******* 音频
b9cbe20c-5ec1-475c-98fb-d1163a032113.mp3
******* 转录
关于女的的非虚构小说，下列哪项正确？
****** 选择
******* A
读者喜欢什么她就写什么
******* B
进人本周畅销书排行前十
******* C
写的是美国高中校园生活
******* D
媒体评价其内容很有说服力
****** 答案
C
***** 10
:PROPERTIES:
:ID: 48762a3b-4476-4ad8-92d7-10d821634920
:END:
****** 问题
******* 音频
6b2677e2-0918-4eeb-adda-baa5dd8fa796.mp3
******* 转录
关于女的，下列哪项正确？
****** 选择
******* A
她的书都写自己的亲身经历
******* B
她的非虚构小说信息量很大
******* C
她的作品内容丰富体裁齐全
******* D
她是一位正义感极强的作家
****** 答案
B
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 2fdd960c-3c58-46b5-b4e3-2931d53670a4
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
04770486-76a0-44bf-b59a-21925d49a788.mp3
***** 转录
“年”是中国人最重要、最综合的一个节日。年，对我们究竟意味着什么？华服？美食？休闲？放松？不尽然，应该说贴对联、穿新衣，只是一种仪式，是对辞旧迎新的尊重，对美好生活的憧憬；拜年、聚餐、拉家常，则是对亲情的眷恋。
很多人感慨现在的“年味”越来越淡了。其实所谓“浓”或“淡”，恐怕只是成年人的感受，年复一年，循环往复，再加上现在生活水平提高了，平时吃、穿水平就不低，过年也变不出什么新花样，新鲜感自然就少了！但是孩子过年总是欢乐的，仿佛天天都被浓浓的年味包裹着，光是过年的气氛，就足以让他们欢快了，和儿时的我们一样。
**** 题目
***** 11
:PROPERTIES:
:ID: 7f81482d-3c2c-4615-abe3-6587ce22140e
:END:
****** 问题
******* 音频
2875052d-a673-443a-9971-640dd1009647.mp3
******* 转录
根据这段话，中国人过年要做什么？
****** 选择
******* A
努力工作
******* B
全家团聚
******* C
举行仪式
******* D
外出旅行
****** 答案
B
***** 12
:PROPERTIES:
:ID: 1b624b5d-78bb-4f55-ab26-6dde49675b52
:END:
****** 问题
******* 音频
733f6cbc-4db0-49ed-806b-18e194c5fcf3.mp3
******* 转录
过年为什么要穿新衣服？
****** 选择
******* A
为丁漂亮
******* B
以示重视
******* C
因为有钱
******* D
因为高兴
****** 答案
B
***** 13
:PROPERTIES:
:ID: b4f79136-b09e-462e-b0dc-8e2bd56ae3ee
:END:
****** 问题
******* 音频
24f624a3-fc41-4644-9e98-b1f3f2fb6e7e.mp3
******* 转录
为什么很多人觉得现在年味不浓？
****** 选择
******* A
以前的喧哗不见了
******* B
新鲜的东西都没有了
******* C
现在天天都穿新衣服
******* D
平时生活水平提高了
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: a3ec4f5d-246e-4b12-80a3-9b2384e3e6b5
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
7225b3d1-3afa-4d78-b44d-dd2fde8d1508.mp3
***** 转录
我理解“慢生活”就是一种生活态度，把工作、吃饭、休息、劳动都看成一种享受。老实说，生活中的每件小事都能给我们带来快乐，比如，拿起剪刀慢慢做点儿小手工；亲手织一件色泽淡雅、款式绝无仅有的毛衣穿在身上；在花瓶中插上一束沁人心脾的鲜花；每顿都用心做一碗健康美味的汤品。而做这些事的过程并非都是痛苦的劳动，其本身就充满了乐趣。
于是，我开始改变自己。原本我不写日记，现在开始徜徉在文字之间，寻觅那一份“慢”的惬意；每天开车上班，我改变了按点出门的习惯，这样就不会为堵车而心急火燎，而是慢慢开，把驾驶当成一种乐趣；出去买菜或办事需要走路时，我的脚步慢了下来，看看身边的城市、身边的人，发现竟然会有不一样的心情！
慢下来其实很简单，只要去除那些外力强加给你的价值观，只需听从自己内心的声音，找到自己喜欢的事情，按照自己的节奏，慢慢地享受那份美好，你的心中就会少些抱怨，感觉生活其实很精彩！
**** 题目
***** 14
:PROPERTIES:
:ID: 5fa4e82e-1510-4e1c-9482-5af0e1aa2e14
:END:
****** 问题
******* 音频
e5436eb1-5918-4eaf-91a1-4d6795938ab1.mp3
******* 转录
说话人认为应该怎样理解“慢生活”？
****** 选择
******* A
“慢生活“讲究事必躬亲
******* B
“慢生活“讲究行为优雅
******* C
“慢生活“讲究品咖和质量
******* D
“慢生活“讲究体咖做事的过程
****** 答案
D
***** 15
:PROPERTIES:
:ID: 4b379427-bcb1-40a1-a1c8-40995dee0617
:END:
****** 问题
******* 音频
34ef63ba-fce4-433b-8a4e-70b86298b2ef.mp3
******* 转录
说话人有哪些改变？
****** 选择
******* A
开始读书写作
******* B
开始调整自己
******* C
学着买菜做饭
******* D
在街上东张西望
****** 答案
B
***** 16
:PROPERTIES:
:ID: 668bb49f-eedb-4daf-a533-a943ef81aa62
:END:
****** 问题
******* 音频
a451884f-191c-41f4-8c88-fd2711557235.mp3
******* 转录
说话人对“慢生活”的切身感受是什么？
****** 选择
******* A
不要去管别人想什么
******* B
不要惧怕外界的压力
******* C
按自己的想法享受美好
******* D
慢与不慢都能活得精彩
****** 答案
C
***** 17
:PROPERTIES:
:ID: 49f3655e-b9e2-42d8-8ff2-98e890ed8144
:END:
****** 问题
******* 音频
ee1f52cb-d4e1-4232-82e6-bed5c9ce6b00.mp3
******* 转录
说话人告诉我们什么？
****** 选择
******* A
慢生活是大势所趋
******* B
慢点开车才能欣赏到风景
******* C
想提高工作效率要先慢下来
******* D
慢下来可以感受到不一样的生活
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
由于这些电动机都以电池作为电源，所以未能广泛普及。
***** B
我承认，你年轻，身体比我棒极了，可你也不能这么不注意呀！
***** C
团结友爱、助人为乐、无私奉献，这些都是中华民族的传统美德。
***** D
人们散落在沙滩上，吃的吃，玩儿的玩儿，晒太阳的晒太阳，悠闲极了。
**** 答案
*** 19
**** 句子
***** A
成都平原是我国西南地区最大的平原。
***** B
每逢佳节，这里常举行游园联欢，人们载歌载舞，喜气洋洋。
***** C
随着现代文明的发展和进步，人们对于生活节奏是更加没有规律了。
***** D
民间传说及古代作者常将元宵节的起源上溯至汉代，这不是没有道理的。
**** 答案
*** 20
**** 句子
***** A
老人有一个儿子、两个女儿。每逢年节和老人的生日，几代人便欢聚一堂，尼享天伦之乐。
***** B
他规定所有员工统一着装。因为统一的服装可以使员工表现为非同一般的庄重和一丝不苟的修养，给客户留下好印象。
***** C
春天，他们种植松树；夏天，他们播种和照料野花；秋天，他们观察冬眠前各种动物的奇异骚动；冬天，他们给鸟喂食。
***** D
科学史是自然科学与人文科学之间的桥梁，它能够帮助人们获得自然科学的整体形象、人性的形象，从而全面地理解科学、理解科学与人文的关系。
**** 答案
** 第二部分
*** 21
**** 段话
贾府不计成本办秦可卿葬礼和元妃省亲，只求[[gap]]辉煌。结果事情是办得[[gap]]了，但资源浪费了，贾府[[gap]]的也就此开始了。
**** 选择
***** A
****** 1
偶尔
****** 2
顺利
****** 3
没落
***** B
****** 1
一度
****** 2
漂亮
****** 3
渊零
***** C
****** 1
暂时
****** 2
得意
****** 3
陶落
***** D
****** 1
一时
****** 2
风光
****** 3
衰落
**** 答案
*** 22
**** 段话
很多女人，特别是知性女人，常常认为女人的美是内在美和外在美的[[gap]]。其实，在她们潜意识中更[[gap]]的是内在美，往往[[gap]]外在美，甚至对外在美有些[[gap]]。
**** 选择
***** A
****** 1
结合
****** 2
在意
****** 3
忽略
****** 4
不屑一顾
***** B
****** 1
总和
****** 2
留心
****** 3
疏忽
****** 4
无拘无东
***** C
****** 1
夹杂
****** 2
挂念
****** 3
漠视
****** 4
无动于衷
***** D
****** 1
统一
****** 2
相信
****** 3
马虎
****** 4
不以为然
**** 答案
*** 23
**** 段话
第一天开上四个轮子上路，小李手忙脚乱，[[gap]]至极，他能感觉到，路上的高手们嫌他车开得慢，[[gap]]一般地超过他的车，有的还回过头来看上两眼，[[gap]]中净是烦躁和埋怨，车子也是憋足了劲儿[[gap]]而过。
**** 选择
***** A
****** 1
威风
****** 2
发狂
****** 3
表情
****** 4
擦肩
***** B
****** 1
狼狐
****** 2
示威
****** 3
眼神
****** 4
呼哨
***** C
****** 1
惊恐
****** 2
抗议
****** 3
回顾
****** 4
轲鸣
***** D
****** 1
拘束
****** 2
撒欢
****** 3
仓促
****** 4
一闪
**** 答案
** 第三部分
*** 段话
一个人的成长，没有不经历坎坷的。只有历经挫折、苦淋与喜悦，才称得上是健康的成长。我一直在努力，希望自己做得更好，不辜负父母对我的期望，[[gap:24]]，唯有父母为子女的付出是无私且不求回报的。
不记得有多少回，父母发现我走了歪路，好心来管教，[[gap:25]]，觉得父母多余，不喜欢他们管我，直到吃了苦头才后悔不已。那会儿的我，和很多孩子一样，[[gap:26]]，把父母的扶助当作天经地义，相反，对父母的教诲却是满肚子的不愿意，甚至充满敌意。
其实父母把我们带到这个世界上，[[gap:27]]，让我们健康、快乐地成长，让我们掌握了知识，他们就尽到了责任。人生道路的选择是我们自己的事情，父母没有保证我们一辈子活得无忧无虑的义务。
告诫各位朋友，懂事之后，不要随意伤害父母，多考虑一下他们的感受和意见，他们是为我们好，怕我们在成长之路上陷入误区，怕我们陷人不必要的痛苦。在我们成人之后，[[gap:28]]，做个有良心的人。
*** 选择
**** A
我却习惯性地反抗
**** B
因为普天之下
**** C
把我们拉扯大
**** D
要感念他们的养育之恩
**** E
把父母的付出当作理所当然
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
富兰克林的名言“时间就是生命，时间就是金钱”，作为大工业时代的座右铭，曾影响了整个世界，激励了无数人化身为社会机器的一个齿轮，越来越多的人沦为时间的奴隶。“慢的乐趣怎么失传了呻？”作家米兰.昆德拉在《慢》一书中发出这样的感慨。
如今，一场新的提倡“慢”的革命正在悄然兴起。这场革和是由无数厉倦了忙碌日子的人们发起的，他们席望可以用更多的时间来欣赏生活的乐趣。
对于“慢生活”，记者对10位不同行业的白领做丁一次小型调查，无一例外，大家都渴望拥有慢生活的生活状态，但八成人认为“慢生活”只是美好的向往。“国情不允许”是白领们最为集中的观点。他们觉得中国用20年经历了欧美200年发生的事情，现在西欧的生活不快，因为他们的社会发展正处在较为稳定的阶段，而我国尚没有这样的经济基础和条件，还需要我们艰苦奋斗。另一方面，生活压力大也是白领们认为慢生活仅是向往的原因之一。
媒体工作者薇薇是快工作、慢生活的有效实践者。虽然做媒体工作仿佛每天都在与时间赛跑，可她依然是贤惠的好媳妇、双胞胎的好母亲、公婆的好儿媳，她依然能超然地活得轻松而自在。上班时，她认真、高效地完成本职工作，下班后和孩子看漫画，和老人聊天，业余读读钟爱的古诗词，练练书法，周未全家人一起去爬山、会朋友、泛舟湖泊、纵情于山水之间。不管别人多忙碌，她依然可以保有内心的平静、淡定和从容。她做不了贵族，但她一定要做生活的主人。
**** 题目
***** 29
****** 问题
失去慢的乐趣，源于：
****** 选择
******* A
社会的飞速发展
******* B
富兰克林的影响
******* C
人类深感时间宝贵
******* D
《慢》这本书的影响
****** 答案
***** 30
****** 问题
如今的状况是：
****** 选择
******* A
记者的调查惊动了社会
******* B
欣赏生活是一个世界潮流
******* C
多数白领希望生活重回慢节奏
******* D
多数人认为慢生活没什么好的
****** 答案
***** 31
****** 问题
八成人认为慢生活难以实现的理由是：
****** 选择
******* A
中国国情决定的
******* B
这些人还不够富有
******* C
中国经济发展不够稳定
******* D
中国赶上欧美需要200年
****** 答案
***** 32
****** 问题
关于薇薇，下列睇项正确：
****** 选择
******* A
她业余爱好跑步
******* B
她喜欢游山玩水
******* C
她还是个书法家
******* D
她向往贵族生活
****** 答案
*** 33-36
**** 段话
三十年以后，乡村将是未来中国人的奢侈品。那时的乡村正如今天的城市让人们向往，那时的乡村将是乌语花香的好地方。
中国有旬老话：三十年河东，三十年河西。1949年新中国成立，前半部历史是城市化，后半部历史将是乡村化。
如今中国的乡村很多已经变成空心村，年轻人外出上学、务工，人人憧憬着城市生活，这就是今天的城市化。往后，再成为乡村土地主人的不再是曾经走出去的农民，而是从城市奔向农村的大学生和工人。“农民”这个名词将逐步被人们淡忘。城市化在不到20年时间内，会促成乡村更多的耕地转化，空心村将会转移，因为都市人住进了乡村，城市核心区将会成为“空心城”。那时，种田是一种最好的生活方式。三五万人的小城镇将是人们最向往的地方。那时的市长很牛，村长更牛。那时，村依然在，可能已改为庄园或农场，农业机械化程度达到90％。
以自然为本，与自然相融将会成为未来人的集体追求。“食”在田园乡村会成为人们的首选，新鲜的空气、自然的田园、刚刚从树上摘下来的水果、刚刚从菜园采回来的落菜，这一切都会成为享受。若干年后，人们开始从内心关注土壤，开始把土壤、树木视为自己的孩子，看成有生命的物质。那时的“佣”，追求的不仅是宽敞和室内的舒适度，还关注室内外的环境，环境将成为居住的重要条件。
**** 题目
***** 33
****** 问题
今天中国乡村的状况是：
****** 选择
******* A
年轰人都很忙
******* B
人口流向城市
******* C
老房子都坏了
******* D
环境污染严重
****** 答案
***** 34
****** 问题
第2段画线词语“一十年河东，一十年河西”的意思最可能是：
****** 选择
******* A
指人事变化无常
******* B
指不必被往事所阜
******* C
指人的习俗好恶变迁
******* D
指每三十年中定会发洪水
****** 答案
***** 35
****** 问题
根据上文，往后乡村会是什么样子？
****** 选择
******* A
那时的村长兼职养牛
******* B
都市人都会住进乡村社区
******* C
走出去的农民争相重回土地
******* D
村子可能已改为庄园或农场
****** 答案
***** 36
****** 问题
“以自然为本，与自然相融”指的是：
****** 选择
******* A
大自然应进人学生的书本
******* B
人们的居住环境不再闭塞
******* C
大家追求人与自然环境的融合
******* D
人们像爱护孩子一样爱护树木
****** 答案
