* 课文
** 转录
为期三天的假期，我和儿时的好友结伴去西安旅行。
去时乘高铁，车程 6 小时。列车缓缓离开了车站，很快就以征服一切的气势甩开窗外的景致，以 300 公里的时速跨过了桥梁，穿越了平原。车窗外，模糊的景象夹杂着西北“的风沙呼啸而过。坐在宽敞座椅中的人们，享受着齐全的软硬件设施，看电影的看电影，打电话的打电话，更多的则是把自己封闭在小小的手机屏幕中，不是用语言，而是用符号传递着各自的情感。寄情于虚拟世界的网迷们对喧哗的现实流露出的是不屑一顾的冷淡。伴随着”终点站到了“的广播，我和朋友像千千万万旅途中的人们一样，没等车停稳，就兴冲冲地守候在车门口，迫不及待地投入到西安滚滚的人流中。
三天的旅行很快就结束了，我们回程坐特快，将近 13 个小时的硬座。列车没有了高铁的威风，不紧不慢地开出了车站，不温不火地匀速前行，仿佛知道一路上将会演绎出许许多多的故事。不久我就发现硬座车厢信号很差无法上网；灯光昏暗无法看书；没有电源，耗尽了电量的手机无法充电；人多嘈杂混乱得睡不着觉，闭塞的车厢里，我们像是回到了 50 年前。朋友忽然说：“其实有时候吧，我还挺喜欢这种感觉的，只有这时候，人和人之间才有种久违的亲近感，也许是因为我们手头都没有事情，愿意彼此分享和倾听。”之后发生的一切，都像是在证明朋友的话是对的。
昏暗的灯光下，我和朋友开始聊天儿。她讲起小学的时候，班里颇具正义感的女生李芳芳如何见义勇为，在洪水中英勇救人；我感叹初中时，班里那个贵族气十足的男生，他叫……唉，一时竟忘了他叫什么名字。他 16 岁到了农村，从播种开始学习，后来长成了个精壮的汉子，改革开放后第一批承包了土地，就此发家致富，他简直就是一代人中的奇迹。我们想起小学的地理老师，讲课的时候总会带出些方言，班里调皮的男生千方百计跟她捣乱，弄得老师狼狈不堪，那会儿的我们真是幼稚得可笑。还有，中学我们班那个料事如神的诸葛亮……火车上，我们边回忆边开心地笑着，好像很久很久都没有这么纯粹地开心过了。
说笑累了，朋友看着窗外，我则观察着周围的人们。坐我对面的像是一对双胞胎姐弟，他们正在聊家常。姐姐轻声细语，回顾着陈年往事：改革开放后的第一年，弟弟考上了大学，瞬间，这消息成了方圆百里的爆炸性新闻。那一年过春节弟弟在学校没回家，家里节过得别提多冷清了，对联都懒得贴。虽然弟弟写信来拜年，可全家都觉得没了天伦之乐。那一年除夕、元宵节，不，是整个正月都过得没了生气，爸妈大年初一连寺庙都懒得去，天天感叹孩子翅膀硬了就要飞了，眼神中流露着失落。隔着过道坐着一对新婚的夫妇，新郎新娘一边给大家分发喜糖，一边说他们是旅行结婚的，顿时，整节车厢都热闹起来了，有人提议新郎新娘唱支歌，大家立刻鼓掌响应，那新郎一看就是个老实人，脸憋得通红，说他是社区物业干维修的，就会干活儿，不会唱歌，不过他媳妇不光贤惠，歌也唱得好，就让媳妇代表了，果然新娘张嘴就惊动了整节车厢，掌声、赞美声响成一片，现场简直就像联欢会一样，而我们对面角落里坐着的漫画家，早就用画笔记录下了眼前的一切。
……
我和朋友不由得感叹，现代交通的确高效，人们随意打发着路上的时间，仓促间投入目的地的怀抱，早就忘了其实沿途的风景也是旅途的一部分，人和人之间无拘无束的交流也是人生最宝贵的财富。若不如此，我们又怎么会读到古人在那一束月光，一叶小舟，或者在那青山绿水间所寄托的情感呢！
