* 听力

** 1

*** 1

**** trascript

女性杂志很受欢迎，实际上这类杂志并没有什么内涵和底蕴，读者不会从杂志中真正获得多少信息，得到的只是休息和放松。也就是说，“没什么实质性内容”反而成了女性杂志吸引人的地方。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:26:31 -05]
:END:

Women's magazines are very popular, but in fact these magazines do not have much substance and content, readers do not really get much information from the magazine, but only rest and relaxation. In other words, "nothing substantial" has become the attraction of women's magazines.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

远古的地球，除了海水就是绿色。森林不但是原始人类的栖息之地，也是他们生产和生活资料的来源。然而，随着经济的发展与人口的增长，人类正在以摧毁地球为代价，肆无忌惮地砍伐着森林。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:29:25 -05]
:END:

In ancient times, the earth was green except for sea water. The forest is not only the resting place of the first human beings, but also the source of their production and living materials. However. With the economic development and population growth, human beings are destroying the earth at the expense of deforestation.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

他表演的相声在嬉笑怒骂间，用他自己的语言与判断陈述了相声界的现状及他本人曲折的经历。令他意外的是，这个段子赢得的竟然是台下相声爱好者的眼泪，然后是如雷般的掌声。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:33:11 -05]
:END:

He performed a comic strip in which he stated in his own words and judgement the current state of the comedy industry and his own tortuous experiences between laughter and anger. To his surprise, the segment won tears from the comic fans on stage, followed by thunderous applause.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** trascript

樱花是日本民族的骄傲，它同雄伟的富士山一样，是勤劳、勇敢、智慧的象征。每年的3月15日，是日本的樱花节。这一天，日本的男女老少都会到公园或野外赏樱花，东京的上野公园在这天还有花宴、花会、花舞等种种活动。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:37:23 -05]
:END:

Cherry blossoms are the pride of the Japanese nation, and like the majestic Mount Fuji, they are a symbol of hard work, courage and wisdom. Every year on March 15, it is the cherry blossom festival in Japan. On this day, Japanese men, women and children go to the park or the field to enjoy the cherry blossoms, and in Ueno Park in Tokyo, there are various activities such as flower feast, flower party and flower dance on this day.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

地毯怕湿，若不保持干燥，就会发霉，被虫蛀，缩短使用寿命。地毯每年最好在陳光下晾晒二二次。晒时要用木棍敲打，把地毯里的灰尘弹出。地毯如溅上酱油、菜汤和其他油脂，应立即用干净的干抹布轻轻擦去，切忌用湿抹布擦。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:41:50 -05]
:END:

Carpets are afraid of moisture, if not kept dry, they will become moldy, insects and shorten their service life. It is best to dry the carpets under the light of the sun for two times a year. When drying, you should use a wooden stick to beat the carpet and pop out the dust in the carpet. If the carpet is spattered with soy sauce, vegetable soup and other grease, it should be wiped away gently with a clean dry rag immediately, never with a wet rag.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：感谢您应邀接受我们的采访。您对健康、农业、移动银行等领域做出了预测，我们就聊聊这些领域吧。
男：先说说埃博拉吧。希望我们可以消灭埃博拉，我们已经取得了很大进步，中国在其中付出了许多努力，投入了很多资源。事实证明应对这样的传染病爆发，需要广泛的国际合作。至于为什么健康会成为基金会的第一要务，是因为没有健康，贫困国家不仅会有很多孩子死亡，还会有很多孩子因为疾病或营养不良而丧失发展的机会，所以健康是最基本的保障。
女：在农业方面，您刚才提到，中国是稻米生产的行家，还有哪些方面中国可以贡献更多的力量呢？
男：首先中国在农业生产力方面实现了大幅度提升，而有的国家农业生产力大概是世界平均水平的五分之一，无论是政策扶持或是科技创新，中国都有很多经验。我们正在和中国合作，确保合适的技术被应用到非洲有需求的国家，并为当地带来实实在在的好处。
女：那么移动银行呢？您觉得什么技术是移动银行革新的关键？
男：如果我们在贫困地区推广传统银行，那么传统银行的收费结构对于贫困地区的居民来说成本过高，所以贫困地区的人会倾向于使用现金，同时传统银行的借贷利率也很高，所以它们不适用于这些地区。我们必须在这些地区推行新的银行，必须价格低廉而且高效，所以我们要推广电子银行。即便你只借一块或两块钱，服务成本也是非常低的。我们同时会对农民进行教育，教会他们如何借贷，如何更好地管理储蓄等。传统银行不能为穷人提供服务，但是这些新兴银行可以，我们需要做的是确保相关监管到位，推动普及教育，提高大家的信任度，并激励更多的创新者为电子银行开发新的产品和应用。

*** 音频

859fd2f5-700c-4ac9-9176-ea3a115da230.mp3

*** 题目

**** 6

***** 问题

关于健康，男的首先谈到了什么？

***** 音频

728873c5-f294-419d-8dc2-377add321c4c.mp3

**** 7

***** 问题

没有健康会怎样？

***** 音频

904e905a-6571-4375-96cc-6befcfe7672a.mp3

**** 8

***** 问题

在农业方面，中国可以做出什么贡献？

***** 音频

f0f6d372-ad09-4db3-8e14-2436619ee7bb.mp3

**** 9

***** 问题

对于贫困地区，传统银行有什么问题？

***** 音频

585356c1-e783-4f96-9b3d-e7db3f96c04c.mp3

**** 10

***** 问题

关于移动银行，下列哪项正确？

***** 音频

a302c930-8dd0-4643-9836-89460d1cea04.mp3

