* 听力

** 第二部分
:PROPERTIES:
:ID: 5507774e-33d2-42e3-a258-ec618e9a5322
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：感谢您应邀接受我们的采访。您对健康、农业、移动银行等领域做出了预测，我们就聊聊这些领域吧。
男：先说说埃博拉吧。希望我们可以消灭埃博拉，我们已经取得了很大进步，中国在其中付出了许多努力，投入了很多资源。事实证明应对这样的传染病爆发，需要广泛的国际合作。至于为什么健康会成为基金会的第一要务，是因为没有健康，贫困国家不仅会有很多孩子死亡，还会有很多孩子因为疾病或营养不良而丧失发展的机会，所以健康是最基本的保障。
女：在农业方面，您刚才提到，中国是稻米生产的行家，还有哪些方面中国可以贡献更多的力量呢？
男：首先中国在农业生产力方面实现了大幅度提升，而有的国家农业生产力大概是世界平均水平的五分之一，无论是政策扶持或是科技创新，中国都有很多经验。我们正在和中国合作，确保合适的技术被应用到非洲有需求的国家，并为当地带来实实在在的好处。
女：那么移动银行呢？您觉得什么技术是移动银行革新的关键？
男：如果我们在贫困地区推广传统银行，那么传统银行的收费结构对于贫困地区的居民来说成本过高，所以贫困地区的人会倾向于使用现金，同时传统银行的借贷利率也很高，所以它们不适用于这些地区。我们必须在这些地区推行新的银行，必须价格低廉而且高效，所以我们要推广电子银行。即便你只借一块或两块钱，服务成本也是非常低的。我们同时会对农民进行教育，教会他们如何借贷，如何更好地管理储蓄等。传统银行不能为穷人提供服务，但是这些新兴银行可以，我们需要做的是确保相关监管到位，推动普及教育，提高大家的信任度，并激励更多的创新者为电子银行开发新的产品和应用。

**** 音频

859fd2f5-700c-4ac9-9176-ea3a115da230.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 1196e4fe-0db0-406f-a188-649246c2cd98
:END:

***** 问题

关于健康，男的首先谈到了什么？

****** 音频

728873c5-f294-419d-8dc2-377add321c4c.mp3

***** 选择

****** A

如何控制埃博拉疫情

****** B

钦佩、赞叹中国的医疗水平

****** C

许多国家为防治疾病投人了资金

****** D

对付某些传染病暴发需要国际合作

***** 答案

D

**** 7
:PROPERTIES:
:ID: 2aca8bac-a5bd-46bb-9c27-5ae02ebd6bce
:END:

***** 问题

没有健康会怎样？

****** 音频

904e905a-6571-4375-96cc-6befcfe7672a.mp3

***** 选择

****** A

会重新陷人贫囱

****** B

会丧失发展机会

****** C

会导致人口危机

****** D

会减少投资收益

***** 答案

B

**** 8
:PROPERTIES:
:ID: 1f0e450a-de44-4347-9d00-66b7ae650e87
:END:

***** 问题

在农业方面，中国可以做出什么贡献？

****** 音频

f0f6d372-ad09-4db3-8e14-2436619ee7bb.mp3

***** 选择

****** A

成为稻米生产的行家

****** B

研究如何提高生产力水平

****** C

介绍中国政策扶持的好经验

****** D

根据当地的需求推广合适的技术

***** 答案

D

**** 9
:PROPERTIES:
:ID: 40711852-9b11-4582-b1d1-a4515dd111aa
:END:

***** 问题

对于贫困地区，传统银行有什么问题？

****** 音频

585356c1-e783-4f96-9b3d-e7db3f96c04c.mp3

***** 选择

****** A

现金不足

****** B

成本过高

****** C

利率不透明

****** D

服务不到仨

***** 答案

B

**** 10
:PROPERTIES:
:ID: eed5a7b4-ca20-400c-9360-20727d513c16
:END:

***** 问题

关于移动银行，下列哪项正确？

****** 音频

a302c930-8dd0-4643-9836-89460d1cea04.mp3

***** 选择

****** A

借一块钱不收费

****** B

价格低廉效率高

****** C

可替农民管理储花

****** D

监管到位信任度高

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

女性杂志的格调普道不高

***** B

女性读者对杂志内容要求很高

***** C

女性读者希望杂志提供丰富信息

***** D

女性杂志因读起来轻松而受欢迎

**** 段话

女性杂志很受欢迎，实际上这类杂志并没有什么内涵和底蕴，读者不会从杂志中真正获得多少信息，得到的只是休息和放松。也就是说，“没什么实质性内容”反而成了女性杂志吸引人的地方。

***** 音频

098ec147-f9a6-444d-bd33-c1fbf6c381d5.mp3

**** 答案

D

*** 2

**** 选择

***** A

没有森林就没有人类

***** B

远古人类靠海洋生存

***** C

远古人类生活在森林中

***** D

人类必须增强资源意识

**** 段话

远古的地球，除了海水就是绿色。森林不但是原始人类的栖息之地，也是他们生产和生活资料的来源。然而，随着经济的发展与人口的增长，人类正在以摧毁地球为代价，肆无忌惮地砍伐着森林。

***** 音频

6373d342-d0e0-4832-907b-42a7bedf7e15.mp3

**** 答案

C

*** 3

**** 选择

***** A

他表演相声时经常又哭又笑

***** B

他做相声演员本身是个意外

***** C

他的相声反映了相声的发展历程

***** D

他的相声收到了意外的表演效果

**** 段话

他表演的相声在嬉笑怒骂间，用他自己的语言与判断陈述了相声界的现状及他本人曲折的经历。令他意外的是，这个段子赢得的竟然是台下相声爱好者的眼泪，然后是如雷般的掌声。

***** 音频

ae57bec0-feca-4313-9f03-2ea90909eb85.mp3

**** 答案

D

*** 4

**** 选择

***** A

日本人很喜欢山

***** B

日本是个爱美的国家

***** C

日本把樱花视为骄傲

***** D

3月15日是日本的国庆节

**** 段话

樱花是日本民族的骄傲，它同雄伟的富士山一样，是勤劳、勇敢、智慧的象征。每年的 3 月 15 日，是日本的樱花节。这一天,日本的男女老少都会到公园或野外赏樱花，东京的上野公园在这天还有花宴、花会、花舞等种种活动。

***** 音频

ac9d5299-4daa-4360-b0de-b3b036645c0e.mp3

**** 答案

C

*** 5

**** 选择

***** A

地毯使用寿命很短

***** B

地毯不能经常暴晒

***** C

地毯不可用涨布擦

***** D

地毯上不可撒汤类等东西

**** 段话

地毯怕湿，若不保持干燥，就会发霉，被虫蛀，缩短使用寿命。地毯每年最好在阳光下晾晒二三次。晒时要用木棍敲打，把地毯里的灰尘弹出。地毯如溅上酱油、菜汤和其他油脂，应立即用干净的干抹布轻轻擦去，切忌用湿抹布擦。

***** 音频

f8079d05-e816-4939-9de6-e46c2f127a10.mp3

**** 答案

C

