* 听力

** 1

*** 1

**** trascript

女性杂志很受欢迎，实际上这类杂志并没有什么内涵和底蕴，读者不会从杂志中真正获得多少信息，得到的只是休息和放松。也就是说，“没什么实质性内容”反而成了女性杂志吸引人的地方。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:26:31 -05]
:END:

Women's magazines are very popular, but in fact these magazines do not have much substance and content, readers do not really get much information from the magazine, but only rest and relaxation. In other words, "nothing substantial" has become the attraction of women's magazines.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

远古的地球，除了海水就是绿色。森林不但是原始人类的栖息之地，也是他们生产和生活资料的来源。然而，随着经济的发展与人口的增长，人类正在以摧毁地球为代价，肆无忌惮地砍伐着森林。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:29:25 -05]
:END:

In ancient times, the earth was green except for sea water. The forest is not only the resting place of the first human beings, but also the source of their production and living materials. However. With the economic development and population growth, human beings are destroying the earth at the expense of deforestation.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

他表演的相声在嬉笑怒骂间，用他自己的语言与判断陈述了相声界的现状及他本人曲折的经历。令他意外的是，这个段子赢得的竟然是台下相声爱好者的眼泪，然后是如雷般的掌声。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:33:11 -05]
:END:

He performed a comic strip in which he stated in his own words and judgement the current state of the comedy industry and his own tortuous experiences between laughter and anger. To his surprise, the segment won tears from the comic fans on stage, followed by thunderous applause.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** trascript

樱花是日本民族的骄傲，它同雄伟的富士山一样，是勤劳、勇敢、智慧的象征。每年的3月15日，是日本的樱花节。这一天，日本的男女老少都会到公园或野外赏樱花，东京的上野公园在这天还有花宴、花会、花舞等种种活动。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:37:23 -05]
:END:

Cherry blossoms are the pride of the Japanese nation, and like the majestic Mount Fuji, they are a symbol of hard work, courage and wisdom. Every year on March 15, it is the cherry blossom festival in Japan. On this day, Japanese men, women and children go to the park or the field to enjoy the cherry blossoms, and in Ueno Park in Tokyo, there are various activities such as flower feast, flower party and flower dance on this day.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

地毯怕湿，若不保持干燥，就会发霉，被虫蛀，缩短使用寿命。地毯每年最好在陳光下晾晒二二次。晒时要用木棍敲打，把地毯里的灰尘弹出。地毯如溅上酱油、菜汤和其他油脂，应立即用干净的干抹布轻轻擦去，切忌用湿抹布擦。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 18:41:50 -05]
:END:

Carpets are afraid of moisture, if not kept dry, they will become moldy, insects and shorten their service life. It is best to dry the carpets under the light of the sun for two times a year. When drying, you should use a wooden stick to beat the carpet and pop out the dust in the carpet. If the carpet is spattered with soy sauce, vegetable soup and other grease, it should be wiped away gently with a clean dry rag immediately, never with a wet rag.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



