* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 941af78d-8587-4bce-a56b-4b4f6b6900e3
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
e210c269-8fa7-4602-949a-681c6d615f27.mp3
***** 转录
在原始社会，生产力水平低下，人们为了获取食物、防御自然界的危险和侵袭，必须集体行动、共同协作才能生存下去。对集体的依赖性强化了人们的群体意识以及与集体同生共死的观念。
**** 选择
***** A
自然界的危险时刻会危害人类
***** B
共同协作能够培养人的群体意识
***** C
原始社会，人要生存就离不开集体
***** D
生产力水平取决于人们的思想观念
**** 答案
C
*** 2
:PROPERTIES:
:ID: 82ff206b-8056-4630-acdc-d6eabb3ba442
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fd3aec14-652e-449e-af81-68370a426dbc.mp3
***** 转录
老话说得好，当一个人变为两个人，两个人守护着一个共同的家，就必须各尽其责，关心对方、体贴对方、照顾对方、理解对方。美满的婚姻应该是两颗心的相守相依，两个人情感的互相给予。
**** 选择
***** A
结婚后要改变过去的生活方式
***** B
老人的话都是宝贵的生活经验
***** C
美满婚姻有赖于两个人的经营
***** D
给予了才能得到，家庭也如此
**** 答案
C
*** 3
:PROPERTIES:
:ID: e397858a-fd60-4a7d-baf7-e6fe7073121f
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
7cfa2593-3624-4d8e-ad23-54030157c8ed.mp3
***** 转录
暴发户文化最大的特征就是附庸风雅。暴发户的文化水平没有到，可是经济水平超过了，因此他会花很多冤枉钱，做很多冤大头的事情。比如说到哪儿都摆阔，房间里弄得金玉满堂，十分俗气。
**** 选择
***** A
暴发户都没有文化
***** B
有钱不会花，就是暴发户
***** C
暴发户会花很多不该花的钱
***** D
说话人对房间俗气的摆设很恭火
**** 答案
C
*** 4
:PROPERTIES:
:ID: eeefa166-f0bb-4515-9410-a72c27f32d9d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
6fe8974b-6acd-4981-848d-c69c4a43a4cd.mp3
***** 转录
那些学贯古今的大学者，何不编写一册通俗的传统文化读本。不要长篇巨制，那是成心不让人读；不要东拼西凑，那样不值得读。只要以成熟的态度，把古人的生存方式、智慧、经验、得失告诉我们，就像一册新时代的《三字经》，岂不是好事！
**** 选择
***** A
说话人讨厌拼凑而成的书
***** B
说话人特别喜欢长篇小说
***** C
《通俗文化读本》是一本好书
***** D
真正有学问的人都能谈古论今
**** 答案
A
*** 5
:PROPERTIES:
:ID: 73671124-0777-4650-9f01-5d2333af6d5e
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
563331b9-8f75-4a71-9e77-b998b5ce8847.mp3
***** 转录
她能说善辩，适合当律师。在课堂上，她们做过模拟律师辩护项目，她的表现极其出色。可她读过许多美国名律师写的小说，她知道律师们要想赚大钱就要为有钱有势的人打官司，她不想被钱、权、势所左右，所以她不想当律师。
**** 选择
***** A
她有当律师的天分
***** B
她一直被钱所困扰
***** C
她不愿看律师写的小说
***** D
她认为为钱打官司很容易
**** 答案
A
** 第二部分
*** 6-10
:PROPERTIES:
:ID: e6245534-b395-4a47-a5cb-c7bef68a6f67
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
8800fd44-3924-4cbc-8c44-b844eeb6b278.mp3
***** 转录
女：您今天能不能就马拉松这个话题和我们聊聊。
男：马拉松运动起源于一个古老的故事。公元前 490 年，波斯军队入侵希腊，在雅典城东北的马拉松平原登陆，准备攻打雅典。当时雅典将军手下只有一万多人，面对的是 10 万装备精良的敌人。雅典士兵拼死奋战，结果他们赢了。雅典统帅大声喊道：“我们应该立刻把消息传送给雅典人民，从这儿到雅典有很长的一段路，谁能去？”刚从战场上回来的菲迪皮德思说：“我能，我跑得比谁都快！”接着他就奔赴雅典城。当到达雅典的时候，菲迪皮德思已经筋疲力尽，他高喊出“高兴吧，我们胜利了”，就永远地倒下了。
女：很感人的一个故事，那这个故事怎么就变成了一项运动呢？
男：1896 年，第一届奥运会于雅典召开前，法国人米歇尔·布雷尔向现代奥林匹克运动的奠基人顾拜旦建议，增设一项以马拉松命名的长跑赛，以纪念马拉松战役和菲迪皮德思。希腊奥组委接受了这一建议，马拉松这个名词第一次出现在国际体坛。
女：那马拉松长跑跑的是什么路线呢？
男：就是昔日菲迪皮德思跑过的从马拉松到雅典的路线。
女：那之后呢？
男：之后几届奥运会的起点和终点都是组织者根据当地情况决定，长度也各不相同。直到 1908 年英国主办奥运会时，马拉松长跑总长度定为 42.195 公里，以后马拉松比赛的正式距离就以此为准了。
女：这项比耐力、比速度、比技能、比拼搏精神的运动一定有很多有趣的故事吧？
男：是啊。我最喜欢的是首届奥运会马拉松冠军的故事。比赛那天酷热难耐，路上灰尘满天，比赛的艰苦无法形容。希腊人路易斯第一个冲入运动场，全场欢声雷动，此时冠军已无悬念，担任总裁判的希腊王储情不自禁地陪着路易斯冲击终点。一束束鲜花，一件件礼物，投向人们崇拜的英雄，甚至有人高呼：让他当部长。
女：后来呢？
男：后来，他获得了希腊民族英雄的称号，仍然回到了偏僻的家乡，继续当他的乡村邮递员，和妻儿一起过着清贫的生活。
**** 题目
***** 6
:PROPERTIES:
:ID: c120bd85-da93-440a-acb5-1fbb98a3b68f
:END:
****** 问题
******* 音频
55bf3720-3040-44f9-b23d-ed2e3d419466.mp3
******* 转录
马拉松作为一项体育运动，是哪一年开始的？
****** 选择
******* A
 490年
******* B
 1896年
******* C
 1908年
******* D
 2000多年前
****** 答案
B
***** 7
:PROPERTIES:
:ID: 44eef77f-188b-4225-a055-437c60c141e7
:END:
****** 问题
******* 音频
9cc6cb66-4d88-429c-b043-84e2222124f3.mp3
******* 转录
关于马拉松运动的起源，下列哪项正确？
****** 选择
******* A
那只是一个传闻
******* B
参加马拉松的人都很能跑
******* C
这项运动与马拉松战役有关
******* D
为丁表彰喜爱运动的希腊人
****** 答案
C
***** 8
:PROPERTIES:
:ID: e9530352-40d5-4eb4-82f9-f9ef55fc2790
:END:
****** 问题
******* 音频
2cffee10-4629-4670-8363-7f93f7badc79.mp3
******* 转录
在奥运会上设立马拉松长跑项目是谁提出的？
****** 选择
******* A
顾拜丁
******* B
菲迪皮德思
******* C
希腊奠组委
******* D
米歇尔・布雷尔
****** 答案
D
***** 9
:PROPERTIES:
:ID: 23e1129e-9d65-4d70-ab77-4861adcd0de4
:END:
****** 问题
******* 音频
ba17d356-6185-4fc4-a53f-8e367104c820.mp3
******* 转录
关于今天奥运会马拉松长跑总长度，下列哪项正确？
****** 选择
******* A
各国奥组委可自行决定
******* B
以马拉松到雅典的距离为准
******* C
奥组委根据当地情况临时决定
******* D
以1908年英国奥运会距离为准
****** 答案
D
***** 10
:PROPERTIES:
:ID: 084ed17c-28ab-4809-bcbd-ccf5f3e29939
:END:
****** 问题
******* 音频
dcfd5101-863e-48d9-9a6d-b040d3f439e8.mp3
******* 转录
根据这段采访可以知道什么？
****** 选择
******* A
路易斯原本是个乡村邮递员
******* B
全世界都视马拉松冠军为英雄
******* C
长跑是希腊全民热爱的体育运动
******* D
路易斯拿到马拉松冠军后当了部长
****** 答案
A
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 4cf9184a-4bfa-402d-9173-a802df9c92e2
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
b29d7450-3271-468b-b40c-68c76051993f.mp3
***** 转录
趣味体育是近年新兴的体育活动，其运动方式没有传统运动那么正式，它以趣味为主，注重娱乐性与大众性；没有传统运动那么严格，它以体验为主；更不需要那么严格的选拔，它属于有兴趣参加的每一个人。它可以在乡间，也可以在高楼之间，甚至在小区的小院里都能举办，比赛的内容也不需要你具备什么天分，更不必提前多少年去接受专门训练。
趣味体育同样可以强身健体，使大家形成终身体育的意识；趣味体育可以娱乐大众，使没有体育专长的人也能体验到体育带来的快乐；由于趣味体育以集体项目居多，可以锻炼参赛者的团结协作意识和竞争拼搏精神。
**** 题目
***** 11
:PROPERTIES:
:ID: 8feb2636-ebe1-4849-82bf-3909da5ba1c5
:END:
****** 问题
******* 音频
1e7da32c-e531-4648-b8c8-5587fec3ce9e.mp3
******* 转录
趣味体育比赛项目的设计有什么特点？
****** 选择
******* A
刺激
******* B
正规
******* C
传统
******* D
好玩儿
****** 答案
D
***** 12
:PROPERTIES:
:ID: 3c144dd5-883a-4399-a25f-aac3628b608a
:END:
****** 问题
******* 音频
20d52501-47a3-4e13-8b0a-e722bb4f678e.mp3
******* 转录
趣味体育的作用是什么？
****** 选择
******* A
产生更多冠军
******* B
增强团队观念
******* C
普及体育常识
******* D
给观众带来竞争
****** 答案
B
***** 13
:PROPERTIES:
:ID: a6e9d8b7-d243-4d16-92e9-73363eeb0efe
:END:
****** 问题
******* 音频
58b37ef7-a342-4379-846b-0b92fbd905c9.mp3
******* 转录
根据这段话，可以知道什么？
****** 选择
******* A
近年来趣昧体育逐渐衰落
******* B
没有人不喜欢趣显体育
******* C
趣味体育对场所要求不高
******* D
趣显体育的参与者都没有天分
****** 答案
C
*** 14-17
:PROPERTIES:
:ID: 792489a2-c0f3-4089-aaf1-ecb06415bd10
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
d8a08975-6691-41e0-8884-8e11c2bac2ba.mp3
***** 转录
世界杯刚一落幕，老球迷就在微博上怀念起旧时足球解说员。
1978 年之前，中国还是收音机时代，那时候不是“看足球”，而是“听足球”。因为足球比赛信息量大且有规定时间，加上比赛情况瞬息万变，所以当时解说的语速都很快，像足球在场上的速度那么快。
电视时代到来后，足球解说也悄然变化。第一代解说以宋世雄、韩乔生为代表，语言上已相对活泼一些了，而且开始引入解说嘉宾这一概念，并尝试在解说中提供更多背景信息。
黄健翔是第二代解说的代表。他把重心放在掌握更多资讯上，同时注重给观众一种现场感，由于是现场解说，解说员自然也会更有激情。
近年被称为文艺青年解说员的贺炜给人们留下了深刻的印象。他语言充满艺术性，被球迷称为“诗人”。解说时这位新生代解说员声情并茂，遣词用句常在观众意料之外，有人评价他的解说专业客观，又使人得到一种艺术的享受。
**** 题目
***** 14
:PROPERTIES:
:ID: 997b5002-deb5-4663-9fff-b633e9b3f175
:END:
****** 问题
******* 音频
edd947c9-eb87-4175-9559-f127562a18df.mp3
******* 转录
31978 年之前，中国足球解说有什么特点？
****** 选择
******* A
信息量大
******* B
解说速度快
******* C
解说员都是球员
******* D
没人看电视转播
****** 答案
B
***** 15
:PROPERTIES:
:ID: 2b24e323-983f-4d66-9e64-f0a2156e5a41
:END:
****** 问题
******* 音频
8d8c9900-30af-4bd6-9317-bab63f33b3b5.mp3
******* 转录
第一代电视足球解说有什么特点？
****** 选择
******* A
风格变化很突然
******* B
解说员都很活泼
******* C
有时嘉宾代替解说
******* D
解说中增加了背景信息
****** 答案
D
***** 16
:PROPERTIES:
:ID: 60ec7449-136a-4cc8-9567-6d11d7e8ed2e
:END:
****** 问题
******* 音频
98aca372-1446-4901-a41c-ca7ba1b14701.mp3
******* 转录
第二代电视足球解说有什么特点？
****** 选择
******* A
他们选出了自己的代表
******* B
现场解说的比例增加了
******* C
解说员解说时更有激情
******* D
解说员对任何资讯都不疏忽
****** 答案
C
***** 17
:PROPERTIES:
:ID: 8900ee2c-bfc7-4a19-beb7-f7b5350e75c1
:END:
****** 问题
******* 音频
743e1569-1f14-4499-9b1b-86fe824fc90e.mp3
******* 转录
贺炜为什么被称为文艺青年解说员？
****** 选择
******* A
他会写诗
******* B
他是业余诗人
******* C
他对艺术情有独钟
******* D
他的语言充满艺术性
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
事件的经过我都告诉你丁，你爱信不信。
***** B
阳春三月，沉睡了一冬天的桃树被蒙蒙细雨唤醒了。
***** C
人的手指甲缝里经常有细菌生存，因此要勤剪指甲，这是常识。
***** D
1981年至今，法国已有157个古镇被进人法国文化遗产保护范围。
**** 答案
*** 19
**** 句子
***** A
游行队伍出发了，市民们举着标语，高叫反对战争的口号。
***** B
广义上的遗膨指死者生前对死后一切事务所做的处置和安排。
***** C
火车的惯性很大，一般列车从刹车到停下，要往前冲出800米左右。
***** D
她咬着嘴唇，眼泪都要流出来了，看得出那问题让她很为难，她不愿回答。
**** 答案
*** 20
**** 句子
***** A
我们开设了抚养小鸡的课程，让每个孩子认领一枚鸡蛋，做好标记，一点点地观察小鸡破壳而出。
***** B
女儿第一次对我的教导表示出不屑，加重语气告诉我她现在的职位，似乎在提示我她现在的成功。
***** C
陈可辛高调宣布他要拍网券了，但他自称这并不是为了讨好“90后”“00后”，而是他意识到：“这是一个更自由的天地。”
***** D
无论是在中国或者在外国，古代思想家、教育家的教育思想，只是他们的哲学思想或政治思想的组成部分，没有形成一门独立的学科。
**** 答案
** 第二部分
*** 21
**** 段话
作为父母，当孩子取得成绩时，一定要给予他们表扬和[[gap]]，让孩子体验到成功的喜悦。在孩子遇到困难和[[gap]]时，要注意给孩子支持和安慰，不要雪上加需地[[gap]]茹孔，这样孩子才会有信心。
**** 选择
***** A
****** 1
促进
****** 2
悲哀
****** 3
谴责
***** B
****** 1
鼓励
****** 2
失败
****** 3
数落
***** C
****** 1
奖励
****** 2
麻烦
****** 3
抱歉
***** D
****** 1
鼓舞
****** 2
障碍
****** 3
嘲笑
**** 答案
*** 22
**** 段话
做任何事情，都要讲究方法。方法对了，一切都[[gap]]，方法不对，[[gap]]意显着南辕北辙。对教育来说，方法也至关重要，无怪乎人们总是想[[gap]]一种万能的教育方法以实现人们对教育[[gap]]的无限厚望。
**** 选择
***** A
****** 1
顺理成章
****** 2
则
****** 3
寻找
****** 4
寄了
***** B
****** 1
微不足道
****** 2
只
****** 3
发明
****** 4
给以
***** C
****** 1
头头是道
****** 2
或
****** 3
创造
****** 4
赠送
***** D
****** 1
有条不亲
****** 2
既
****** 3
探索
****** 4
了以
**** 答案
*** 23
**** 段话
结婚5年，妻子任何汤类都放香菜，那味道让我精神[[gap]]，吃饭都聚精会神。小时候我不吃香菜，听妻子说那玩意挺有益的，我就喜欢上它啦。如今我正[[gap]]去买些香菜种子[[gap]]在花盆里，长出来当花儿养，它比芹菜可有[[gap]]多了。
**** 选择
***** A
****** 1
集中
****** 2
思索
****** 3
搁
****** 4
气势
***** B
****** 1
享受
****** 2
推敲
****** 3
栽
****** 4
情趣
***** C
****** 1
充实
****** 2
思量
****** 3
放
****** 4
品味
***** D
****** 1
大振
****** 2
考虑
****** 3
种
****** 4
魅力
**** 答案
** 第三部分
*** 段话
叶问（1893年一1972年），本名叶继问，祖籍广东省南海县，出生于富足之家。他从小受的是儒家教育，[[gap:24]]。上学读书之后，他爱上了传统武术，从7岁起便拜“咏春拳王”梁赞的高足陈华顺为师学习咏春拳。
陈华顺收叶问为徒后，便不再接受任何人拜师学艺，[[gap:25]]。叶问的各位师兄，如吴仲素、陈汝棺、雷汝齐等，对师弟更是照顾有加。陈华顺逝世后，为了不中断学习，叶问随师兄吴仲素钻研拳技，[[gap:26]]
叶问十六岁那年，远离佛山，赴港求学，就读]圣上提反学院o1950年，叶问再度赴港，在港九饭店职工总会内传授咏春拳术，[[gap:27]]。其徒弟除总会及分会的会员、港九各地的中国工人外，[[gap:28]]。其弟子中最出名的是让中国武术闻名世界的武打巨星李小龙。
*** 选择
**** A
有着深厚的传统文化素养
**** B
后随梁资之子梁壁学武
**** C
还有在港的外国留学生
**** D
从而一举成名
**** E
叶问就成了陈华顺的封门弟子
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
“蹴鞠”是中国古代的一项球类运动，早在《史记》中就有记载。“蹴”的意思是用脚踏，“鞠”指外面包着皮革、里面装着米糠的球。“蹴鞠”大意即用脚踪球。
蹴鞠起源于齐国都城临淄（今天的山东省溏博一带），齐宣王在位时（公元前319年一公元前310年）已经十分盛行。汉代，蹴鞠更被视为“治国习武”之道。出身平民百姓的汉高祖刘邦不但自己爱踢球，还专门在客苑中建造“鞠域”，也就是足域场。汉武帝还把蹴鞠列为军事训练科目，以提高将帅的身体素质和反应能力，并以其作为考察兵将体质的手段。汉代还出现了研究蹴鞠运动的专著《蹴鞠二十五篇》这也是中国和世界上最早的一部体育著作。
到了唐代，“鞠”的制作艺术和“蹴”的运动技术都有了很大的改进。球变得更圆、更轻；运动规则也由原来的直接对抗转为间接对抗，中间隔着球门，双方各在一侧，以射门数多者为胜，而且还出现了女子蹴鞠。女子蹴鞠不射门，是以踢球的技法取胜。唐玄宗李隆基、唐中宗李显等都曾是当时的球星。
宋代，蹴鞠变得更加兴盛，而东在球的制作方面又有了进一步的发展，不仅针脚组密，而且不露线头，制成的球也十分地圆。
到了清代，骑马射箭盛行，“蹴鞠”渐被冷落。
**** 题目
***** 29
****** 问题
根据第2段，汉武帝把蹴鞠列为军事训练科目是因为：
****** 选择
******* A
将帅喜欢蹴鞠
******* B
能踢球就能打仗
******* C
蹴鞠能强身健体
******* D
反应快的人也能踏球
****** 答案
***** 30
****** 问题
根据上文，下列说法正确的是：
****** 选择
******* A
女子踢球技术强于男子
******* B
唐代蹴鞠转而注重观赏性
******* C
“鞠”的制作越来越精良
******* D
古代有球星，也有追星族
****** 答案
***** 31
****** 问题
关于“蹴鞠”，下列睑项正确？
****** 选择
******* A
《史记》是与之相关的专著
******* B
起源于今天山东省溏博一带
******* C
是老百姓最喜欢的一项运动
******* D
清朝，天冷的季节才有人蹴鞠
****** 答案
***** 32
****** 问题
最适合做上文标题的是：
****** 选择
******* A
蹴鞠
******* B
足球小史
******* C
足球的演变
******* D
球类运动在中国
****** 答案
*** 33-36
**** 段话
童年的邓亚萍梦想成为一名运动员，但身高仅有1.55米、手脚粗短的她，被认为没有发展前途。是啊，个子太矮，这几乎是致命的缺点，可是邓亚萍没有选择“认输”。身高不行，她就以脚步灵活来弥补；体校不要她，她就跟父亲学。为了练好基本务，她在腹上绑上沙袋。小小的她，每闪、展、腾、挪一步，都可以用举步维艰来形容。膈肿了，手掌磨破了，她从不叫苦。付出总有回报，10岁的她便在全国少年乒乓球比赛中获得囡体和单打两项冠军。
进人国家队后，教练最常噜咐邓亚萍的就是“要注意休息，别练过了”。实际上，每天正常训练完以后，邓亚淬都要加练，她的训练量要超过正常运动员很多。她每天练球都要带两双鞋，一双被汗水湿透就再换一双；一筐200多个训练用球，邓亚萍一天要打掉[儿筐，邓亚萍的一堂训练课相当于跑一次一万米，这还没算上数十次的挥拍动作，她还经常因为训练错过吃饭的时间。
邓亚萍先后14次获得世界冠军，乒坛世界排名曾经连续8年保持第一，是排名世界第一时间最长的女运动员，也是唯一蝉联奥运会女子乔乎球单打和双打双料冠军的运动员。邓亚萍的出色成就，改变了世界乒坛只在高个子中选拔运动员的传统观念。无数人为邓亚萍的球风和球艺所倾倒。
**** 题目
***** 33
****** 问题
童年的邓亚萍：
****** 选择
******* A
天天做美梦
******* B
身材不苗条
******* C
坚决不服输
******* D
常遭受打击
****** 答案
***** 34
****** 问题
为了练好基本功，邓亚著：
****** 选择
******* A
把沙袋捡绑在腹上
******* B
每天坚持练习长跑
******* C
刻苦学习武术步法
******* D
不计较生活苦不苦
****** 答案
***** 35
****** 问题
下列哪个词语用来形容邓亚萍进人国家队后的训练生活更合适？
****** 选择
******* A
日夜兼程
******* B
不畏艰辛
******* C
省吃俭用
******* D
顺其自然
****** 答案
***** 36
****** 问题
根据上文，下列说法正确的是：
****** 选择
******* A
8年中，她一直活跃在乒坛
******* B
她是运动生涯最长的女运动员
******* C
她是拿奠运会金牌最多的运动员
******* D
她用事实说明锭个孔同样能打好乒乓球
****** 答案
* 书写
** 文章
我们以前只知道“科学育儿”，却没有听说过“极限育儿”。“极限育儿”，顾名思义，就是让孩子从小冒险，体验生命的极限。
澳大利亚的詹姆斯和米娅是一对典型的“极限家长”，夫妻俩腺欢挑战各种极限运动。他们的儿子杰克4个月大时，詹姆斯就把儿子吊在胸前，背着一大包旅行用品，一家三口在山上露腊地的帐篷里过了一夜。杰克4岁就成了探险老手。他与父亲连在同一条绳上攀岩，跟随父亲从100米高的悬崖上进行快速滑降，一起从高空跳水。他从来不知道什么是害怕，简直没有他不能到达的高度和深度。
如今世界各地涌现出的“极限家长”不在少数。怀塔克莱一家的全部家当都装在汽车里，晚上就搭起帐篪，睡在折叠床上。除了必要的生活用品外，他们几乎一无所有。夫妻俩教孩子如何观察周围的环境，在野外辨认方向和读懂地图。挂子们在不断变换“驼地”的日子里，学会了用最快的速度适应新环境，学会了收集燃料，节约饮水，用可以到手的原始物品制作用具，甚至给自己做玩具，从来不会为每天不安定的生活而痛苦。
近日，一段视频被人放到了网上。视频中，父亲在与一个4岁的男孩沟通并经过30分钟的热身慢跑后，这个4岁的男孩脱掉了自己的内外衣裤，仅穿一条嫩黄色的小短裤和运动鞋，快速跑人风雪之中，而当天清晨的室外最低气温是~-13C，大街上几乎看不到一个人，只有他在厚厚的雪地里晨跑。开始小家伙可能有点儿冷，一边跑，一边带着哭腔路爸爸要“抱抱”，不想再跑了，很快孩子的头上挂满了雪花，可最后还是在父亲的鼓励下，小家伙儿坚持跑了大约5分钟。
对此，网民们议论纷纷。有人认为“极限教育”是一种爱心教育，是一种超越溺爱的大爱，尤其值得溺爱孩子的父母学习。有人认为探险活动可以培养儿童长时间集中注意力，在探险活动中，他们需要观察周围事物，收集各种信息来帮助自己做出决定，有时还要制定多种方案。探险对增强体质和意志力能起到很大的作用，这不是什么坏事。持不同意见者则认为，对于儿童探险存在的风险，不是每个人都能清想地认识到的，让那么小的孩子身处险境，可能遇上各种不测，奉劝家长放过幼小的孩子，对脆弱的他们还是不要大意。
