* Listening
:PROPERTIES:
:CREATED: [2022-03-26 23:55:03 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-04-07 17:13:17 -05]
:END:

*** 1
:PROPERTIES:
:CREATED: [2022-04-07 17:13:59 -05]
:ID: e63c921c-14e4-4bec-ad16-83ce2a1c705a
:END:

左边的大，右边的小。
pi: zuǒbian de dà,  yòubian de xiǎo
en: the left side is large, the right side is small
es: el lado derecho es grande, el lado izquierdo es pequeño

*** 2
:PROPERTIES:
:CREATED: [2022-04-07 17:16:22 -05]
:ID: d5399dc0-42e3-443f-a486-d0bd4307f4b5
:END:

您好，见到您很高兴。

note

见到 | jian4 dao4 | to see ;

*** 3
:PROPERTIES:
:CREATED: [2022-04-07 17:24:41 -05]
:ID: 80a7f95b-d34a-4e64-b652-4893ad90fe1d
:END:

你看，女孩子也喜欢踢足球。
pi: nǐ kàn, nǚ háizi yě xǐhuan tī zú qiú
en: you see, girls like to play soccer too
es: ¿ves? a las chicas también les gusta jugar fútbol

*** 4
:PROPERTIES:
:CREATED: [2022-04-07 17:32:21 -05]
:ID: 798a82c0-683e-43a5-934c-693c487688aa
:END:

咖啡来了，要不要喝一杯？
pi: kāfēi lái le, yào bú yào hē yī bēi
en: here's the coffee, want a cup?
es: acá está el café ¿quieres una taza?

*** 5
:PROPERTIES:
:CREATED: [2022-04-07 17:32:32 -05]
:ID: 34267d05-c61d-4f9b-8d11-4b9aa3010536
:END:

昨天是小李的生日，下班后我们去唱歌了。
pi: zuótiān shì xiǎo lǐ de shēngrì, xià bān hòu wǒmen qù chàng gē le
en: yesterday was Lee's birthday, we went singing after work
es: ayer fue el cumpleaños de Lee, fuimos a cantar después del trabajo

*** 6
:PROPERTIES:
:CREATED: [2022-04-07 17:36:52 -05]
:ID: ac26850d-eefa-4a93-8294-8ecb6f45b682
:END:

太好了，我找到这本书了。
pi: tài hǎo le, wǒ zhǎo dào zhè běn shū le
en: great, I've found the book
en: genial, enconrté el libro

*** 7
:PROPERTIES:
:CREATED: [2022-04-07 17:39:39 -05]
:ID: c2de61d3-7e7c-4b69-b88c-2bfa38579732
:END:

中午她给女儿买了一件衣服。
pi: zhōngwǔ tā gěi nǚ'ér mǎi le yī jiàn yīfu
en: at noon she bought a dress for her daughter
es: al mediodía compró un vestido para su hija.

*** 8
:PROPERTIES:
:CREATED: [2022-04-07 17:43:28 -05]
:ID: 8a160611-7314-41f8-adb1-ef94a6d460e9
:END:

他们四个人每天都一起吃饭。
pi: tāmen sì ge rén měitiān dōu yī qǐ chī fàn
en: the four of them eat together everyday
es: los cuatro comen juntos todos los días

*** 9
:PROPERTIES:
:CREATED: [2022-04-07 17:45:45 -05]
:ID: 87f89484-4a62-42e3-a4ce-c9c3270b8d7b
:END:

对不起，我现在很忙，十分钟后我再给你打电话。
pi: duìbuqǐ, wǒ xiànzài hěn máng, shí fēnzhōng hòu wǒ zài gěi nǐ dǎ diànhuà
en: I'm sorry, I'm very busy now, I'll call you in 10 minutes.
es: lo siento, estoy muy ocupada ahora, te llamaré en 10 minutos.

*** 10
:PROPERTIES:
:CREATED: [2022-04-07 17:51:55 -05]
:ID: 2fabb093-7a3c-4655-b043-6ae63df40b15
:END:

他们开着车出去了。
pi: tāmen kāi zhe chē chū qù le
en: they drove out in a car
es: salieron en su auto

** 2
:PROPERTIES:
:CREATED: [2022-04-07 17:57:03 -05]
:END:

*** 11
:PROPERTIES:
:CREATED: [2022-04-07 17:57:05 -05]
:ID: 584a5fbb-d7ff-46ac-9906-07af9e792baa
:END:

女：是今天早的上报纸吗？
pi: shì jīntiān zǎoshàng de bàozhǐ ma?
en: is it this morning's newspaper?
es: ¿es este el periódico de la mañana?

男：不是，是昨天的，今天的还没到。
pi: bú shì, shì zuótiān de, jīntiān de hái méi dào
en: no, it's yesterday's, today's hasn't arrived yet
es: no, es el de ayer, el de hoy no ha llegado aún

*** 12
:PROPERTIES:
:CREATED: [2022-04-07 18:02:39 -05]
:ID: 27037530-32cb-4cd2-a447-f8001fc8c71d
:END:

男：你去洗洗手。
pi: nǐ qù xǐ xǐ shǒu
en: you go wash your hands
es: ve a lavarte las manos

女：好，今天晚上给我准备什么好吃的了？
pi: hǎo, jīntiān wǎnshàng gěi wǒ zhǔnbèi shénme hǎochī de le?
en: ok, what's ready for me tonight?
es: ok ¿qué me has preparado hoy?

*** 13
:PROPERTIES:
:CREATED: [2022-04-07 18:10:46 -05]
:ID: 17e33272-bc7c-4ffb-9fb2-36cbb974cd4a
:END:

女：车怎么了？
pi: chē zěn me le
en: what happened to the car?
es: ¿qué le pasó al carro?

男：没关系，可能出了点儿小问题。
pi: méi guān xi, kěnéng chū le diǎr xiǎo wèntí
en: it's okay, there may be a small problem
es: está bien, puede haber un pequeño problema

*** 14
:PROPERTIES:
:CREATED: [2022-04-07 18:20:05 -05]
:ID: e31d5b85-4625-457d-a165-61dfa8ab21a1
:END:

男：现在雨已经不下了。
pi: xiànzài yǔ yǐjīng bú xià le
en: it's not raining anymore
es: ya no llueve

女：是吗？我看看。
pi: shí ma? wǒ kàn kàn
en: is it? let me see.
es: ¿en serio? dejame ver

*** 15
:PROPERTIES:
:CREATED: [2022-04-07 18:26:27 -05]
:ID: cfbf1dc2-3f24-42ae-9166-4a4ebc757132
:END:

女：怎么样？漂亮吗？
pi: zěnmeyàng? piàoliàng ma?
en: how about that? is it beautiful?
es: ¿qué te parece? ¿es bonito?

男：真漂亮，我觉得非常好。
pi: zhēn piàoliàng, wǒ juéde fēicháng hǎo
en: it's beautiful, I think it is very good
es: muy hermoso, creo que es muy bueno

*** 16
:PROPERTIES:
:CREATED: [2022-04-07 18:32:51 -05]
:ID: a7c53d50-f5b1-4054-8f76-99feffa3ab71
:END:

男：这个字是什么意思？
pi: zhè ge zì shì shénme yìsi?
en: what does this character mean?
es: ¿qué significa este caracter?

女：在哪儿？
pi: zài nǎr
en: where is it?
es: ¿dónde esta?

*** 17
:PROPERTIES:
:CREATED: [2022-04-07 18:48:55 -05]
:ID: 480fe7d5-305e-43cf-bb9f-c37f4fdc2bda
:END:

女：这个药一天吃几次呢？
pi: zhè ge yào yī tiān chī jǐ cì ne
en: how many times a day do I need to take this medicine?
es: ¿cuántas veces al día tomo este medicamento?

男：医生说一天吃两次。
pi: yīshēng shuō yī tiān chī liǎng cì
en: the doctor said to take it twice a day
es: el médico dijo que tomaras dos veces al día

*** 18
:PROPERTIES:
:CREATED: [2022-04-07 18:54:57 -05]
:ID: 988c5231-ea32-4c60-b3ad-75b0ddabdb78
:END:

男：上午考得怎么样？
pi: shàngwǔ kǎo de zěnmeyàng
en: how was the morning exam?
es: ¿cómo te fue en el examen de la mañana?

女：别问了，很多题我都不会做。
pi: bié wèn le, hěn duō tí wǒ dōu bù huì zuò
en: don't ask, I couldn't do many questions.
es: no preguntes, no pude hacer mucha de las preguntas

*** 19
:PROPERTIES:
:CREATED: [2022-04-07 21:36:54 -05]
:ID: a88693aa-3210-4637-a75b-7c08c09d3cb5
:END:

女：我想去北京旅游，北京哪儿最好玩儿？
pi: wǒ xiǎng qù běijīng lǚyóu, běijīng nǎr zuì hǎo wánr?
en: I want to travel to Beijing, where is the most fun in Beijing?
es: quiero visitar Pekin ¿cuál es el lugar más interesante de Pekín?

男：让我想想。
pi: ràng wǒ xiǎng xiǎng
en: let me think
es: déjame pensar

*** 20
:PROPERTIES:
:CREATED: [2022-04-07 21:42:07 -05]
:ID: 1d85202a-7c89-46ac-83d1-b40e5123b360
:END:

男：今天还是阴天，这天气真冷。
pi: jīntiān háishì yīntiān, zhè tiānqì zhēn lěng
en: it's still cloudy today, it's really cold
es: hoy sigue nublado, hace mucho frío

女：是，我穿了这么多，还觉得冷。
pi: shì, wǒ chuān le zhè me duō, hái juéde lěng
en: yes, I'm wearing so much and I still feel cold
es: sí, llevo puesto todo esto y todavía siento frío

** 3
:PROPERTIES:
:CREATED: [2022-03-26 23:55:10 -05]
:ID: 0cc40696-0a74-401d-a583-fbde7e0053fd
:END:

*** 21
:PROPERTIES:
:CREATED: [2022-03-26 23:55:21 -05]
:ID: 45708256-2cfa-4109-a48e-75ed334a60e0
:END:

女：你眼睛怎么什么红？没休息好？
pi: nǐ yǎnjīng zěnme shénme hóng? méi xiūxi hǎo?
en: why are your eyes so red? did not rest well?
es: ¿por qué tienes los ojos tan rojos? ¿no has tenido un buen descanso?

男：是，昨天晚上看电视看到十二点。
pi: shì, zuótiān wǎnshàng kǎn diànshì kàn dào shíèr diǎn
en: yes, last night I watched TV until 12 o'clock
es: sí, anoche vi televisión hasta las doce

问：男的昨天晚上做什么了？
pi: nán de zuótiān wǎnshàng zuò shénme le?
en: what did the man do last night?
es: ¿qué hizo el hombre anoche?

answer

c

*** 22
:PROPERTIES:
:CREATED: [2022-03-27 00:14:03 -05]
:ID: 5321ac50-0cf5-4fd0-a25b-dceee46a1307
:END:

男：服务员，请给我来一杯热水。谢谢。
pi: fúwùyuán, qǐng gěi wǒ lái yī bēi rè shuǐ. xièxie
en: waiter, please bring me a cup of hot water. Thank you.
es: camarero, por favor, tráigame una taza de agua caliente. Gracias.

女：好的，不客气。
pi: hǎo de, bù kè qi
en: yes, you are welcome.
es: sí, de nada.

问：他们最可能在哪儿？
pi: tāmen zuì kě néng zài nǎr?
en: where are they most likely to be?
es: ¿dónde es más probable que estén?

*** 23
:PROPERTIES:
:CREATED: [2022-03-27 00:14:20 -05]
:ID: 92e3c2d5-0a36-441e-af8d-6a4de7e4e3ff
:END:

女：你知道你们学校有多少学生吗？
pi: nǐ zhī dào nǐ men xuéxiào yǒu duō shǎo xuésheng ma
en: do you know how many students there are at your school?
es: ¿sabes cuántos alumnos hay en tu colegio?

男：知道，有两千多。
pi: zhīdào, yǒu liǎng qiān duō
en: I know, there are more than two thousands
es: sí, hay más de dos mil.

问：这个学校有多少学生？
pi: zhè ge xuéxiào yǒu duō shǎo xuésheng
en: how many students are there there in this school
es: ¿cuántos alumnos hay en esta escuela?

*** 24
:PROPERTIES:
:CREATED: [2022-03-27 00:32:47 -05]
:ID: da80e95d-53d5-4fe7-9145-8807a4c3b497
:END:

男：你是什么时候来这个公司的？
pi: nǐ shì shénme shíhou lái zhège gōngsī de
en: when did you come to this company?
es: ¿cuándo llegaste a esta empresa?

女：我是去年2008年来的。
pi: wǒ shì qù nián èr líng líng bā nián lái de
en: I came here last year in 2008
es: llegué aquí el año pasado en 2008.

问：女的是什么时候来这个公司的？
pi: nǚ de shì shénme shíhou lái zhège gōngsī de
en: when did the woman come to this company?
es: ¿cuándo llegó la mujer a esta empresa?

*** 25
:PROPERTIES:
:CREATED: [2022-03-27 00:36:18 -05]
:ID: 4301d452-8b39-4f09-9306-564d70ad5d21
:END:

女：我们下午去看电影，好吗？
pi: wǒmen xiàwǔ qù kàn diànyǐng, hǎo ma?
en: let's go see a movie this afternoon, okay?
es: vamos al cine esta tarde ¿te parece?

男：我上个星期已经看过了，我们去游泳吧。
pi: wo shàng ge xīngqī yǐjīng kàn guò le, wǒmen qù yóuyǒng ba
en: I've already seen it last week, let's go swimming
es: ya lo vi la semana pasada, vamos a nadar.

问：男的为什么不去看电影？
pi: nán de wèi shénme bù qù kàn diànyǐng?
en: why doesn't the man go to the movies?
es: ¿por qué el hombre no va al cine?

*** 26
:PROPERTIES:
:CREATED: [2022-04-07 22:54:18 -05]
:ID: 5372f7f8-ce8a-4195-bfca-c7276439a99f
:END:

男：你好，鱼怎么卖呢？
pi: nǐ hǎo, yú zěnme mài ne?
en: hello, how do you sell the fish?
es: hola ¿a cómo se vende el pescado?

女：很便宜，两块钱一斤。
pi: hěn piányi, liǎng kuài qián yī jīn
en: it's cheap, two dollars a pound
es: está barato, dos dólares la libra

问：男的要买什么？
pi: nán de yào mǎi shénme?
en: what does the man want to buy?
es: ¿qué quiere comprar el hombre?

*** 27
:PROPERTIES:
:CREATED: [2022-04-07 23:03:45 -05]
:ID: 0df5b844-edbb-4021-b9c5-e5e05b82190c
:END:

女：张小姐的飞机快到了，我们还要多长时间？
pi: zhāng xiǎojiě de fēijī kuài dào le, wǒmen hái yào duō cháng shíjiān?
en: miss Zhang's plane is almost here, how long will it take to get there?
es: el avión de la seǹorita Zhang llega pronto ¿en cuánto tiempo llegaremos?

男：没问题，我们再有五分钟就到机场了。
pi: méi wèntí, wǒmen zài yǒu wǔ fēnzhōng jiù dào jīcháng le
en: no problem, we'll be at the airport in five minutes
es: no hay problema, estaremos en el aeropuesto en cinco minutos

问：他们要去哪儿？
pi: tāmen yào qù nǎr
en: where are they going?
es: ¿a dónde están yendo?

*** 28
:PROPERTIES:
:CREATED: [2022-04-07 23:15:56 -05]
:ID: 751a9fcd-b107-4e48-bdb1-2d8670032cd5
:END:

男：这个椅子有点儿贵，但是颜色很不错。
pi: zhège yǐzi yǒu diǎr guì, dànshì yánsè hěn búcuò
en: this chair is a bit expensive, but the color is very nice
es: esta silla es un poco cara, pero tiene un bonito color

女：你喜欢？那就买它吧。
pi: nǐ xǐhuan? nǎ jiù mǎi tā ba
en: do you like it? then buy it
es: ¿te gusta? pues cómpralo

问：男的觉得这个椅子怎么样？
pi: nán de juéde zhège yǐzi zěnmeyàng?
en: what does the man think of this chair?
es: ¿qué piensa el hombre de esta silla?

*** 29
:PROPERTIES:
:CREATED: [2022-04-07 23:50:58 -05]
:ID: f9a48b22-ad27-4a92-b337-0325dceeac4b
:END:

女：你准备哪天去中国？
pi: nǐ zhǔnbèi nǎ tiān qù zhōngguó?
en: which day do you plan to go China?
es: ¿qué día piensas ir a china?

男：我买的机票是八月七号的。
pi: wǒ mǎi de jī piào shì bā yuè qī hào de
en: the ticket I bought is for August 7th
es: el boleto que compré es para el 7 de agosto.

问：男的哪天去中国？
pi: nán de nǎ tiān qù zhōngguó?
en: What day is the man going to China?
es: ¿qué día va a ir el hombre a China?

*** 30
:PROPERTIES:
:CREATED: [2022-04-07 23:59:10 -05]
:ID: 83118196-2ca4-4019-9e57-66e6554b88c4
:END:

男：谁在门外？是你妈妈回来了？
pi: shéi zài mén wài? shì nǐ māma huí lái le
en: who's at the door? is it your mother coming back?
es: ¿quién está en la puerta? ¿es tu madre que ha vuelto?

女：不是，是送牛奶的。
pi: bú shì, shì sòng niú nǎi de
en: no, it's the milk delivery guy.
es: no, es el repartidor de leche.

问：谁在门外？
pi: shéi zài mén wài?
en: who's at the door?
es: ¿quién está en la puerta?

** 4
:PROPERTIES:
:CREATED: [2022-04-08 00:06:47 -05]
:END:

*** 31
:PROPERTIES:
:CREATED: [2022-04-08 00:06:49 -05]
:ID: cd1db5b2-a1f8-4112-86c1-e032112f582c
:END:

男：今天的羊肉做得很好吃，你怎么不吃了？
pi: jīntiān de yángròu zuò de hěn hǎochī, nǐ zěnme bù chī le
en: today's lamb is very good, why do not you eat?
es: la carne de hoy está muy bien ¿por qué no comes?

女：少吃肉，多吃菜，对身体好。
pi: shǎo chī ròu, duō chī cài, duì shēntǐ hǎo
en: eat less meat, eat more vegetables, it's good for your body.
es: come menos carne, come más verduras, es bueno para tu cuerpo.

男：身体好还要多运动。
pi: shēntǐ hǎo hái yào duō yùndòng
en: good health also requires more exercise
es: la buena salud también requiere más ejercicio

女：那我们明天去跑步吧。
pi: nǎ wǒmen míngtiān qù pǎobù ba
en: then let's go running tomorrow.
es: entonces salgamos a correr mañana

问：他们在做什么？
pi: tāmen zài zuò shénme?
en: what are they doing?
es: ¿qué están haciendo?

*** 32
:PROPERTIES:
:CREATED: [2022-04-08 03:58:01 -05]
:ID: cff1a35d-5be4-448e-8e21-a38bdd3068f0
:END:

女：你家离学校远吗？
pi: nǐ jiā lí xuéxiào yuǎn ma?
en: is your home far from school?
es: ¿está tu casa lejos de la escuela?

男：不太远。
pi: bú tài yuǎn
en: not too far
es: no muy lejos

女：你每天怎么去上学？
pi: nǐ měitiān zěnme qù shàngxué
en: how do you go to school every day?
es: ¿cómo vas a la escuela todos los días?

男：有时候坐公共汽车，有时候走路去。
pi: yǒu shíhou zuò gōnggòngqìchē, yǒu shíhou zǒu pǎo qù
en: sometimes by bus, sometimes by foot.
es: a veces en bus, a veces a pie.

问：男的家离学孝远吗？
pi: nán de jiā lí xuéxiào yuǎn ma?
en: is the man's home far from school?
es: ¿está la casa del hombre lejos de la escuela?

*** 33
:PROPERTIES:
:CREATED: [2022-04-08 04:10:06 -05]
:ID: 5379ceae-c059-441a-a18e-025525eab3c0
:END:

男：您从几岁开始学习跳舞？
pi: nín cóng jǐ suì kāishǐ xuéxí tiàowǔ
en: at what age did you start learning to dance?
es: ¿a qué edad empezó a aprender a bailar?

女：七岁。
pi: qī suì
en: seven years old
es: siete años

男：是吗？我女儿今年也七岁了，我希望她能和您学跳舞，可以吗？
pi: shì ma? wǒ nǚ'ér jīnnián yě qī suì le, wǒ xīwàng tā néng hé nín xué tiàowǔ, kěyǐ ma?
en: is that so? my daughter is also seven years old this year, I hope she can learn to dance with you, is that ok?
es: ¿de verdad? mi hija también tiene siete años este año y me gustaría que aprendiera a bailar con ustedes ¿te parece bien?

女：没问题，非常欢迎。
pi: méi wèntí, fēicháng huānyíng
en: no problem, you are very welcome
es: no hay problema, de nada.

问：男的想让谁学跳舞？
pi: nán de xiǎng ràng shéi xué tiàowǔ?
en: who does the man want to learn to dance?
es: ¿quién quiere el hombre que aprenda a bailar?

*** 34
:PROPERTIES:
:CREATED: [2022-04-08 04:23:55 -05]
:ID: 6e271626-1ffa-46b9-9576-4963aa56e8f3
:END:

女：天快黑了，我要回去了。
pi: tiān kuài hēi le, wǒ yào huí qù le
en: it's getting dark, I'm going back
es: está ocureciendo, tengo que volver.

男：好的，外面正在下雪，您路上慢点儿。
pi: hǎo de, wàimian zhèngzài xià xuě, nín lùshàng màn diǎr
en: okay, it's snowing outside, take care on your way.
es: vale, está nevando afuera, tened cuidado en vuestro camino.

女：没关系，明天见。
pi: méiguānxi, míngtiān jiàn
en: it's okay, see you tomorrow
es: está bien, nos vemos mañana

男：好的，再见。
pi: hǎo de, zàijiàn
en: okay, bye
es: vale, adiós

问：现在天气怎么样？
pi: xiànzài tiānqì zěnmeyàng
en: how is the weather now?
es: ¿cómo está el clima ahora?

*** 35
:PROPERTIES:
:CREATED: [2022-04-08 04:34:23 -05]
:ID: 6a28a90a-19cb-41b0-b579-b3b0c9b6fb8f
:END:

男：你怎么九点就睡觉了？
pi: nǐ zěnme jiǔ diǎn jiù shuìjiào le?
en: why did you go to bed at nine o'clock?
es: ¿por qué te acostaste a las nueve?

女：因为明天要早起。
pi: yīnwèi míngtiān yào zǎo qǐ
en: because I have to get up early tomorrow
es: por que mañana tengo que levantarme temprano

男：明天星期日，你起那么早做什么？
pi: míngtiān xīngqī rì, nǐ qǐ nǎ me zǎo zuò shénme?
en: tomorrow is sunday, you get up so early for what?
es: mañana es domingo, ¿qué haces mañana tan temprano?

女：我一个朋有明天要来，船七点就到。
pi: wǒ yí gè péngyǒu míngtiān yào lái, chuán qī diǎn jiù dào
en: a friend of mine is coming tomorrow, the ship will arrive at seven o'clock
es: un amigo mío viene mañana y el barco estará ahí a las siete

问：女的为什么要早起？
pi: nǚ de wèi shénme yào zǎo qǐ?
en: why does the woman have to get up early?
es: ¿por qué la mujer tiene que madrugar?

