* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 73674608-9cdd-4869-b310-9496303c076d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
5fd98121-46c8-4a7c-baa7-1ff9d66b7d49.mp3
***** 转录
在惩罚实施后对受罚者保持关爱，通常会收到良好的效果。这是因为惩罚会给人带来羞愧、痛苦、不安和悔恨等消极情绪,这时人的心理承受能力较低，比平时更期望得到别人的关爱,儿童、青少年尤其如此。
**** 选择
***** A
青少年触犯刑法也要惩罚
***** B
对受到惩罚的人更要关心
***** C
惩罚会给人带来极大的伤害
***** D
惩罚就是为丁造成心理压力
**** 答案
B
*** 2
:PROPERTIES:
:ID: 45a50c3f-f153-41d0-bcde-960c89e9dd3d
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
99958f8d-2086-45a9-b4a9-2bf692249140.mp3
***** 转录
机器人指能够自动执行工作的机器装置，它可以接受人类指挥，也可以根据已编好的程序运行。它的任务是帮助或代替人类工作，可应用于生产业、建筑业，或是危险工作。
**** 选择
***** A
机器人是外形像人的一种机器
***** B
想指挥机器人必须先编好程序
***** C
机器人可代替人进行危险作业
***** D
机器人迟早要取代人类
**** 答案
C
*** 3
:PROPERTIES:
:ID: 085974d3-d820-4b4d-8e5c-32cf65bc6ecd
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
acf6e1ad-c07d-4e18-8919-716db2a43ed0.mp3
***** 转录
那一年，中国开始推动介入治疗，张医生发现当时手术用的封堵器全部是进口的，价格贵不说，由于材质偏硬，极易造成其他组织的损伤。他天天想，可否找到一种能降低成本，同时能提升治疗效果的新材料？
**** 选择
***** A
进口的手术材料比较便宜
***** B
进口的手术材料材质不好
***** C
张医生发明了一种新材料
***** D
张医生手术技术全国闻名
**** 答案
B
*** 4
:PROPERTIES:
:ID: 55f66a96-e18c-4657-a3cb-ffe4b322f3f4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
956a8ebd-1207-4c77-b098-aee20c63cc51.mp3
***** 转录
人脑的重量虽然只占人体重量的 2%左右，但大脑消耗的能量却占全身消耗能量的 20%。人脑每天需要 116～145 克的糖，当血糖浓度降低时，大脑的耗氧量也随之下降，轻者会感到头昏、疲倦，重者则会陷入昏迷。
**** 选择
***** A
人脑消耗的能量非常少
***** B
人的血糖浓度低很危险
***** C
为了大脑健康要多吃精
***** D
血糖浓度过高人会昏迷
**** 答案
B
*** 5
:PROPERTIES:
:ID: 3184cd97-3a31-44ac-9dc0-d09e220e94e3
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
d51bb370-7c51-4e05-8ca0-60c9d590e397.mp3
***** 转录
李小龙用 33 岁短暂的人生制造了一段传奇。从他离开这个世界的第一天起，他的追随者就对这位“功夫之王”进行了各种形式的追忆和纪念，这种狂热的纪念逐渐演变成一个神话，一个龙的神话，一个空前绝后的神话。
**** 选择
***** A
李小龙33岁就辞世了
***** B
李小龙神拜“功夫之王“
***** C
李小龙的电影是个神话
***** D
李小龙对功夫十分狂热
**** 答案
A
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 9e84b20c-b386-427c-8e3f-63c5b7c427ed
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
b94762c5-aa49-469e-8e9e-e341c9719dca.mp3
***** 转录
女：你七年前生病后逃离上海，如今带着自己的新书《逃离》回到上海做宣传，是否多少有些感慨？
男：我当年就特别有感触。七年前生病，我首先要逃出医院，要知道，当时我住的是中国肺科最好的医院。然后我要逃离上海。
女：那时候你好像刚结婚？
男：我结婚一个月后就查出得了大家都认为是不治之症的病，当时我的想法是和老婆离婚，不想耽误她。
女：她怎么想？
男：她说她没觉得这是多大的事，病了就病了，死了就死了，这都是命，你想那么多干吗。
女：在上海你的一切都很稳定，做出逃离上海的决定也不容易吧？
男：在上海，我有大房子，有车，有社会地位。但对我来说，逃出医院才是最艰难的，因为我选择了自我治疗。
女：上海这座城市曾经给你什么美好的记忆吗？
男：上海带给我的记忆一直很美好。我的不适应还是在生活上、语言上，包括生病这件事。我之所以选择离开，主要是对于我生病地的水，我再也不想喝了。因为我只信水，所以想找到好的水、干净的水。我在《逃离》一书中反复地说，生命是以水为基础的。生病是生命的一部分，我决定用换水的方式来解决病的问题。那时医院的肺科主任对我说：“马老师，什么事情都没有耽误治疗的事情大。”这位医生说得入情入理，但我跟他们说，我自己的命，我做一回主。
女：你在山里过上了世外桃源的生活。你觉得，逃离最大的好处是什么？
男：不久前我才有了网络。这种与世隔绝的生活最大的好处是可以免遭外界干扰。对于都市生活的负面影响，各种各样的说法都有，譬如“都市病”，大家越来越觉得都市生活对人性本身是一种禁锢。在大山里则不同，可以让我在寂静中沉下心来思索。一个人独居，就会有特别多的想法。我每天的生活是简单的，在这个简单里，你很容易进入一种抽象思维的状态，很容易变得哲学化。
**** 题目
***** 6
:PROPERTIES:
:ID: a28396f4-9302-47f2-a1b6-74b980c5694f
:END:
****** 问题
******* 音频
2c6baeaf-88a6-4d59-8f5a-f8aff2399e04.mp3
******* 转录
七年前发生了什么事？
****** 选择
******* A
男的生了重病
******* B
男的准备结婚
******* C
妻子不高兴了
******* D
男的出了新书
****** 答案
A
***** 7
:PROPERTIES:
:ID: c3c4c918-bfee-4391-b881-211d991501b9
:END:
****** 问题
******* 音频
0d30f825-2360-4f13-8eae-9e39611410c0.mp3
******* 转录
对男的来说，最艰难的是什么？
****** 选择
******* A
卖掉房孔、车子
******* B
放弃优越的生活
******* C
拒绝在医院治疗
******* D
远离社会的尊重
****** 答案
C
***** 8
:PROPERTIES:
:ID: 89490de8-9879-4ccb-9b1f-33927d2b86d9
:END:
****** 问题
******* 音频
26472892-1bb0-4d11-aa46-01d65d428186.mp3
******* 转录
男的为什么选择离开上海？
****** 选择
******* A
医生都特别不会说话
******* B
再也不想喝上海的水
******* C
很多人听不懂上海话
******* D
妻二决定要离开上海
****** 答案
B
***** 9
:PROPERTIES:
:ID: a9f6fa4f-5ccc-4e89-a9be-b97d92559313
:END:
****** 问题
******* 音频
e90059ad-cb90-420f-b32a-85884d8318f7.mp3
******* 转录
男的认为远离都市的生活有什么好处？
****** 选择
******* A
可以思考哲学问题
******* B
可以不受外界干扰
******* C
可以比城里人少生病
******* D
可以吃到鲜美的桃子
****** 答案
B
***** 10
:PROPERTIES:
:ID: f91a2cf8-0a19-4532-9d62-c30db1e01e19
:END:
****** 问题
******* 音频
77dabfc1-67ae-4ca8-9498-de27cd61560a.mp3
******* 转录
关于男的，下列哪项正确？
****** 选择
******* A
他很爱他的妻子
******* B
他不愿和人打交道
******* C
他是有影响的哲学家
******* D
他把妻子的事写成了书
****** 答案
A
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 5c1fc404-159d-49e1-afb4-addddc4675a4
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
7ec3191e-550a-46c0-9e31-1ff0eadaf0e5.mp3
***** 转录
自 1957 年人类发射第一颗人造卫星至今，太空中的废弃航天器已有 5000颗左右，而失效的卫星、探测器以及火箭发射后残留下来的碎片就更多了，它们漂浮在太空中，形成太空垃圾，即“空间碎片”。
目前太空碎片总数已超过 4000 万个，而且空间碎片每年还在以 2%～5%的速度增加。数量多、速度快是空间碎片的危害所在，这些碎片以每秒 6000～7000米的速度运行，一个仅 10 克重的太空垃圾的撞击强度，与以 100 公里时速行驶的两辆轿车迎面相撞的强度相当。对人类而言，空间碎片落到地面，后果将会是灾难性的。
面对太空垃圾，人类必须清醒，我们只有一个地球，也只有一个外层空间，维护外层空间的清洁迫在眉睫，而且空间碎片问题需要全球共同努力，共同面对。
**** 题目
***** 11
:PROPERTIES:
:ID: a2e02967-f264-443a-893e-5933d18844c3
:END:
****** 问题
******* 音频
ba137eca-3059-43a5-9be0-816f4a9f8917.mp3
******* 转录
太空垃圾还叫什么？
****** 选择
******* A
空间硼片
******* B
失效卫星
******* C
火箭残片
******* D
废弃航天器
****** 答案
A
***** 12
:PROPERTIES:
:ID: bcbd8ec7-9006-40e9-9010-7b046cf06156
:END:
****** 问题
******* 音频
492721e7-7713-4f62-ba75-eaea4b49886d.mp3
******* 转录
太空垃圾的危害是什么？
****** 选择
******* A
碎片重量过大
******* B
每年大量增加
******* C
数量多,速度快
******* D
会经常撞击地球
****** 答案
C
***** 13
:PROPERTIES:
:ID: 7a35d88d-2935-4629-919e-38fd53a820a6
:END:
****** 问题
******* 音频
fe1b704c-4064-49e7-afbb-2103b2100543.mp3
******* 转录
人类最紧急的任务是什么？
****** 选择
******* A
减少发射人造卫星
******* B
了解太空垃圾的危害
******* C
提高思考问题的能力
******* D
维护外层空间的清洁
****** 答案
D
*** 14-17
:PROPERTIES:
:ID: 5cc2d1ee-4487-4362-8d54-382e4df383dd
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
8372b17b-baa1-4d6c-9428-a1d3b3085ddb.mp3
***** 转录
人的大脑只有在体力、脑力和心力处于最佳状态时，才能得到最好的发挥，这是不可不信的科学。
先说体力，它是大脑开发的基础条件，在实现目标的过程中是否会白白失去成功的机会，有时确实与是否具备充足的体力有关。因此我们要长久地保养和锻炼身体，保持体力，增进健康。至于父母为了提高孩子的学习成绩，让孩子不停地奔忙于学校和各种补习班之间，绝非聪明之举，这样做只会导致孩子体力欠缺，进而造成注意力、免疫力不同程度地下降。
脑力，也就是我们常说的“聪明才智”，并非只有学习才能促进其增长。玩耍、运动、休息、调整，同样会不断地刺激大脑，使头脑更加灵活，进而提高人的判断力、识别力、记忆力，甚至做事的效率。试想，具备了这些能力的人，还存在脑力、心智不足的问题吗？
人的心力是一种正义的力量。当一个人的品质最接近人生的本质时，心力指数会明显提高，他的人格魅力也会增强，更会被人尊重和喜爱。心力是人的灵魂觉醒时产生的力量，也是能唤醒人的灵魂的力量。
**** 题目
***** 14
:PROPERTIES:
:ID: 50d71f5d-01ef-4365-8c33-bcd23fa22197
:END:
****** 问题
******* 音频
8f8315cd-ba1c-49fe-93b2-64b8ec2c91a8.mp3
******* 转录
父母最聪明的做法是什么？
****** 选择
******* A
让孩子多玩儿
******* B
让孩子锻炼身体
******* C
让孩子劳逸结合
******* D
让孩子集中注意力
****** 答案
C
***** 15
:PROPERTIES:
:ID: 4e782f1a-5994-4855-ba65-5f94abd0a91c
:END:
****** 问题
******* 音频
4a56a218-ec42-4b68-9bba-633bb7741b8e.mp3
******* 转录
怎样才能使我们更聪明？
****** 选择
******* A
不断提高做事的效率
******* B
刺激大脑,促其灵活
******* C
多向能力强的人学习
******* D
克服脑力不足的缺陷
****** 答案
B
***** 16
:PROPERTIES:
:ID: c2733faf-933e-4b2f-a0ad-aa8601b0d286
:END:
****** 问题
******* 音频
e712c348-eda4-41c5-91e0-1d3a8ce7d124.mp3
******* 转录
人的“心力”是什么？
****** 选择
******* A
灵魂的觉醒
******* B
人格的魅力
******* C
正义的力量
******* D
人生的本质
****** 答案
C
***** 17
:PROPERTIES:
:ID: 71532c6b-5331-4f52-9777-515c6f434d67
:END:
****** 问题
******* 音频
5466af7c-f04b-4cc9-bc1c-3b1c599e2d4e.mp3
******* 转录
这段话主要想告诉我们什么？
****** 选择
******* A
身体健康是最重要的
******* B
谁都不能不相信科学
******* C
离开科学我们寸步难行
******* D
大脑如何得到最好地发挥
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
猎咪拙头看看我，一双绿色的眼睛流露出淡淡的哀怨。
***** B
车坏了，我俩心里都明白，这辆车被人修不好我们就走不了。
***** C
每到烈日炎炎的盛夏，沙漠吹来的热风都会把这里变成一个大蒸笼。
***** D
我觉得无论什么猎都是胖一点儿好，圆滚滚的，看着舒服，摸着也舒服。
**** 答案
*** 19
**** 句子
***** A
大家不用担心，估计明天的天气肯定很好。
***** B
马继兴一生埋头读书，勤奋笔耕，60多年出版专著20余部。
***** C
就是在这个论坛上，他第一次尝到了与人交流分享爱好的乐趣。
***** D
大兴安岭的秋色，南疆的戈壁、草原、雪山，都是中国最美的景色。
**** 答案
*** 20
**** 句子
***** A
有人为追求浪漫，在屋子里安装上许多彩灯。
***** B
从广义上讲，濑危动物泛指珍贵、稀有的野生动物。
***** C
她着装简洁，言谈高雅，第一次见面，我被她的美所深深吸引了。
***** D
我是个随性的人，我不喜欢的事就不干，只要喜欢，玩儿了命也要往里钻。
**** 答案
** 第二部分
*** 21
**** 段话
人类有[[gap]]的感觉器官，能眼观六路，耳听八方，通过听觉、视觉、触觉等反映[[gap]]现象，认识客观事物，这就为大脑这个加工车间提供了形成语言的[[gap]]。
**** 选择
***** A
****** 1
敏感
****** 2
当时
****** 3
见解
***** B
****** 1
敏锐
****** 2
现实
****** 3
原料
***** C
****** 1
灵活
****** 2
实际
****** 3
材料
***** D
****** 1
聪明
****** 2
更新
****** 3
资料
**** 答案
*** 22
**** 段话
我今年16岁，[[gap]]是无忧无虑的年龄，可我却整天愁眉不展。我很小的时候，爸爸就教育我要好好学习，将来考大学，可我只对音乐[[gap]]。我一心一意只想报考艺术学校，全家只有爸爸坚决不[[gap]]，其他人都不[[gap]]。
**** 选择
***** A
****** 1
确信
****** 2
出神
****** 3
答应
****** 4
否认
***** B
****** 1
原来
****** 2
人迷
****** 3
批准
****** 4
际止
***** C
****** 1
本来
****** 2
走神
****** 3
认同
****** 4
抗议
***** D
****** 1
本该
****** 2
着迷
****** 3
同意
****** 4
反对
**** 答案
*** 23
**** 段话
坎儿井是沙漠地区一种[[gap]]的灌溉系统，普遍应用于中国新疆召鲁番地区。坎儿井与万里长城、京杭大运河[[gap]]为中国古代三大工程。吐鲁番的坎儿井[[gap]]达1100多条，全长[[gap]]5000公里。
**** 选择
***** A
****** 1
特定
****** 2
起名
****** 3
数量
****** 4
达
***** B
****** 1
特殊
****** 2
并称
****** 3
总数
****** 4
约
***** C
****** 1
特别
****** 2
简称
****** 3
总量
****** 4
计
***** D
****** 1
奇特
****** 2
合称
****** 3
条数
****** 4
共
**** 答案
** 第三部分
*** 段话
Geminoid F 被视为当前高度仿真机器人中最优秀的作品，[[gap:24]]，甚至有人称赞“她”是世界上最性感的美女机器人。她可以识别对方的眼神和身体语言，甚至模仿对方的面部动作。
[[gap:25]]，她身高 1.68 米，皮肤由柔软的硅胶制成，肤色逼真度极高。她能通过视觉系统读懂人类的面部表情并成功复制，具有微笑、皱眉等65种不同的面部表情，还可以像真人一样发声、对话和唱歌。[[gap:26]]，远看就是一位活生生的美丽女子。
机器人的研发者说，现在，大部分语音识别系统还不能很好地工作，[[gap:27]]，未来，他们希望借助这款机器人研制…吏兀美的人智能系统。他们希望这款机器人能让科技离主流人群更近，[[gap:28]]。
*** 选择
**** A
最终“飞人寻常百姓家“
**** B
也是目前方兴未艾的情感机器人领域的优秀代表作
**** C
这个美女机器人的原型是一名20多岁的日俄混血女模特
**** D
尤其是在杂乱的环境下
**** E
她的呼吸似乎都与真人无异
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
我家附近有几家卖婴幼儿物品的商店，商品的种类、价格相差无儿。只是大家差不多都喜欢中间的那家，进去后质量、价格一概不问，直接拿东西付钱。那家小店跟别的店没什么区别，唯一不同的是店门口台阶上摆着好些花。花盆不是破了沿儿的塑料盆，就是没了盖儿的茶壶，再不就是装过东西的塑料桶剪去了上半部分，反正没儿个正经花盆，基本都是废品利用。花儿也不怎么名贵，都是一些插在土里就能活的品种，可是店主每天都亲自把花草打理得干浑、清爽、水灵。
我和朋友们曾经讨论过这家店聚集人气的原因，朋友们看法不一。有的说，爱花的人一定心地善良，这样的人断然不会也不忍用假货欺骗顾客。有的说，看着满台阶的花就知道店主一定热爱生活，以诚待客，他卖的东西我信。虽然这两种说法都是推测，但也不无道理，不瞒你说，我每次走到这条小街，都会被这家店洋滥着的生活气息所吸引，经常会不由自主地走进这家店，也许就是因为生活中任何人都喜爱美好的事物吧。
**** 题目
***** 29
****** 问题
关于“我”家附近的儿家商店，下列晨项正确？
****** 选择
******* A
价格差别很大
******* B
质量不用担心
******* C
有一家最受欢迎
******* D
商品的来源不同
****** 答案
***** 30
****** 问题
关于中间的那家店，下列睇项正确？
****** 选择
******* A
店里同时还卖花
******* B
店中没有服务员
******* C
店主勤劳爱干净
******* D
东西价格最便宜
****** 答案
***** 31
****** 问题
文中提到的花盆和花，下列睇项正确？
****** 选择
******* A
花盆的形状很有趣
******* B
花盆都是废旧物品
******* C
花的价格出奇的贵
******* D
花都是请人打理的
****** 答案
***** 32
****** 问题
大家对这家店的看法，下列哪项正确？
****** 选择
******* A
店主一定不骗人
******* B
店主很会做生意
******* C
店主的做法没道理
******* D
店主很有人格魅力
****** 答案
*** 33-36
**** 段话
世间万物都在变，一点一点细微地变，等到哪一天你突然发现它已经有了翻天覆地的变化的时候，你可能会在大脑中反复搜寻，希望抓住它的演变过程，可是你找不到，呈现在你脑海中的就是那个以前的它和如今让你感到陌生的崭新的它。无论是人、物或环境都在改变。人的性格会变、观念会变、长相会变；物的形会变，环境更是每时每刻都在变。我有时常想：到底是人改变了环境，还是环境改变了我们……
暨春时节，夕阳懒洋洋地照在村口的核桃树上，我兴沥沥地回到阑别了十年的村子。温暖的夕阳、老气横秋的核桃树、树下的青石板，和十年前一模一样，我恨不得和小时候一样，三蹦两跳跑到叔叔家，可是我没有，如今的我已不是那个毛头小伙子了，我成熟了。我极力掩盖着内心的兴奋，快步向村中走去。
快到叔叔家的时候，不远处一位跟我年龄相仿、穿着白色连衣裙的漂亮女孩儿向我走来，我立刻开始在脑子中搜寻：我这么大的玩伴，谁能婢来这么漂亮的女孩儿？正想得出神，她韶叫了声我的小名，我下意识地应了一声，疑惑地问了句：“我认识你因？”走近丁，她笑着说：“真的是你啊，好久没见了！我是建萍呀，我们小时候天天在一块儿玩儿！”我顿时傻了眼，我脑海中的她个子矮矮的，皮肤有点儿黑，性格有点儿内向……再看看现在的她，个子好高，皮肤也变白了，性格好活泼，只是那对酒窝，还依稀保留着一丝她小时候的影子。我说她变了，她很淑女地笑着说：“你也变了。”
一直以来我都觉得自己没有变，她说我也变了的时候，我才发现原来我也在变。
**** 题目
***** 33
****** 问题
根据第！段，“变化”的特点是：
****** 选择
******* A
在不知不觉中发生
******* B
某一天会突然发生
******* C
人的性格很难改变
******* D
环境总是被人改变
****** 答案
***** 34
****** 问题
“我”进村时的情景，下列哨项正确？
****** 选择
******* A
“我”特别想用小时候的方式跑到叔叔家
******* B
“我”在十年前春天的一个傍晚离开了这里
******* C
“我”和小时候不一样，已经跑不动了
******* D
十年前村子里的核桃树早已找不到了
****** 答案
***** 35
****** 问题
关于建淑，下列哨项正确？
****** 选择
******* A
已经和我的小伙伴结婚了
******* B
面貌、性格都有了巨大变化
******* C
小时候的影子一点儿都没了
******* D
她说我变得她都认不出来了
****** 答案
***** 36
****** 问题
最适合做上文标题的是：
****** 选择
******* A
我回到了故乡
******* B
小时候的朋友
******* C
记忆有时不可靠
******* D
原来我们都在变
****** 答案
