* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 04111992-0bbf-4686-8f0f-029eee4cd2be
:END:
**** 对话
***** 转录
女：您写作的过程中会休息吗？[[file:c2761c8f-1c03-4669-b666-250e8063f80e.mp3][(audio)]]
男：会。我经常写一会儿就到院子里转转，给花草剪剪枝，捡几块漂亮的小石头。这样脑力和体力可以很好地结合，身心得到放松。[[file:c585b660-7022-4c19-8098-b4ac80619367.mp3][(audio)]]
***** 音频
173e3a53-1de4-444d-b030-0203de6ca022.mp3
**** 问题
***** 转录
男的为什么要给花草剪枝？
***** 音频
78b1d6d4-be97-4948-a172-79c08093177d.mp3
**** 选择
***** A
他在写关于养花的文章
***** B
他是个勤劳的人
***** C
小石头很漂亮
***** D
为了放松身心
**** 答案
D
*** 2
:PROPERTIES:
:ID: b5d157d6-4147-4809-a469-ee233bbfd3db
:END:
**** 对话
***** 转录
男：你的花养得这么好，总结过经验吗？[[file:c596d56e-87df-457c-b036-8135ff5afcd1.mp3][(audio)]]
女：有的花喜干，就别多浇水；有的花喜欢潮湿的环境，就别放在太阳地里。[[file:74e6bebd-269c-4245-a2ab-a50e93355663.mp3][(audio)]]
***** 音频
86928f66-68d7-4414-bfc8-bc7c770a38f5.mp3
**** 问题
***** 转录
女的认为养花最重要的是什么？
***** 音频
a9804bce-67de-4ec7-8bd3-ab73b8e31497.mp3
**** 选择
***** A
多浇水
***** B
多晒太阳
***** C
了解花的习性
***** D
找有经验的人
**** 答案
C
*** 3
:PROPERTIES:
:ID: 9f1dd3ef-2867-4fa6-8492-443c9210329e
:END:
**** 对话
***** 转录
女：你怎么看起来这么累啊？[[file:74236ba8-2b97-45f6-bd88-43178c56444e.mp3][(audio)]]
男：马上快下班的时候来了个病人，情况紧急，又做了个两小时的手术，累得我腰都直不起来了。[[file:8a79d06d-12b6-4678-a60f-b2fb98327fad.mp3][(audio)]]
***** 音频
90e9d489-a8be-469f-8766-3fb702cd4c4c.mp3
**** 问题
***** 转录
男的怎么了？
***** 音频
90b01515-3806-4f2f-b1f3-93b35ac30a65.mp3
**** 选择
***** A
生病了
***** B
加班了
***** C
腰受伤了
***** D
站不起来了
**** 答案
B
*** 4
:PROPERTIES:
:ID: 4de3a931-6963-4f7a-8a49-142c4ffc45cd
:END:
**** 对话
***** 转录
男：这次真是搞砸了！[[file:b2491e89-f9bb-474c-90e5-ebbdc7de2442.mp3][(audio)]]
女：生活总是有成功也有失败，有悲伤也有幸福，别这么灰心。[[file:d84ae49f-647c-4059-874a-9cc911a6bda7.mp3][(audio)]]
***** 音频
48c42ba9-3930-47f6-a02f-2be1fa294469.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
e1e4591b-c636-4741-9d73-11f491ace9e3.mp3
**** 选择
***** A
抱怨
***** B
安慰
***** C
佩服
***** D
感激
**** 答案
B
*** 5
:PROPERTIES:
:ID: dabd3bf8-cf09-4f8d-aab5-6ce4ecb5f78b
:END:
**** 对话
***** 转录
女：明天的比赛你准备好了吗？[[file:fbeadf30-6af5-4337-96b3-caf76b7fa05d.mp3][(audio)]]
男：熟练工种，天天干，我闭着眼睛都能应付，放心吧！[[file:fa7e11ce-cd83-436f-8736-9c7fa82f6da7.mp3][(audio)]]
***** 音频
b2f77d58-95c7-4fc3-93dd-fdbc0d3864d7.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
45df7986-853d-43a1-a526-552bd4a6fc42.mp3
**** 选择
***** A
很有把握
***** B
想睡觉了
***** C
眼睛不舒服
***** D
每天都有比赛
**** 答案
A
*** 6
:PROPERTIES:
:ID: 372eeaf8-bbf5-436e-ae43-1c14ece8ca77
:END:
**** 对话
***** 转录
男：你靠扫大街挣钱，不觉得丢脸吗？[[file:622dd9ec-a490-41bd-b3e6-f7b715e047c2.mp3][(audio)]]
女：我不偷不抢，靠自己劳动养活自己，有什么丢脸的？[[file:05f5db99-f826-4ecf-9337-98847c894ec5.mp3][(audio)]]
***** 音频
1fe3b019-8dbb-48a9-8216-bec5d0910c19.mp3
**** 问题
***** 转录
女的的钱是怎么来的？
***** 音频
3c929e83-34e1-46c4-95c0-30d6b2453df4.mp3
**** 选择
***** A
偷来的
***** B
抢来的
***** C
自己挣的
***** D
别人捐的
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：听说老舍先生特别爱花？
男：对，他养的花很多，满满摆了一院子。
女：他都喜欢什么花？
男：好种易活、自己会奋斗的。因为他说北京的气候不适合养花，想把南方的名花养活并非易事。
***** 音频
9d4e0560-1c9e-4ccc-a36a-92544862dec3.mp3
**** 问题
***** 转录
老舍先生喜欢什么花？
***** 音频
6e942d0a-702b-42fb-a083-655e89016a16.mp3
**** 选择
***** A
南方的名花
***** B
容易养的花
***** C
北京本地的花
***** D
什么花都喜欢
**** 答案
B
*** 8
**** 对话
***** 转录
男：北京有个老舍茶馆，是不是老舍先生开的店？
女：不是，是以他的名字命名的。
男：你去过吗？怎么样？
女：很好，有便宜的大碗茶、各种北京传统风味小吃，还有京剧、相声表演什么的。
***** 音频
b37c4170-7a59-451a-9353-6d531dda42ad.mp3
**** 问题
***** 转录
关于老舍茶馆，下列哪项正确？
***** 音频
7e41e665-4048-432b-b317-85f35f10ade7.mp3
**** 选择
***** A
老板是老舍先生
***** B
用老舍的名字命名
***** C
可以吃北京风昧菜
***** D
可以看话剧表演
**** 答案
B
*** 9
**** 对话
***** 转录
女：怎么，又跟你们家亲爱的吵架了？
男：没吵架，她乱发脾气，我懒得理她，就自己出来了。
女：这可不行，除非你以后都不打算回去了，不然还是早点儿回家的好。
男：先各自冷静一下吧。
***** 音频
0e27ffbe-f52b-4c3b-80ee-b400218bef32.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
d44a8f05-e831-43d2-a13d-7bcb538396f6.mp3
**** 选择
***** A
暂时不回去
***** B
马上就回去
***** C
已经回去过了
***** D
以后都不回去了
**** 答案
A
*** 10
**** 对话
***** 转录
男：这是我前天买的衣服，有点儿问题，麻烦您帮我退了。
女：您这已经拆了，我们退不了。
男：这衣服是质量问题，必须得退。
女：那您也别把价签儿剪了啊！
***** 音频
3b3287d2-3a11-43e2-a482-aafa7a3e5120.mp3
**** 问题
***** 转录
女的为什么不给他退货？
***** 音频
8e44c60b-46c9-4f03-a4a4-0f34cdfe319f.mp3
**** 选择
***** A
超过时间了
***** B
价签被剪了
***** C
没有质量问题
***** D
不是这里买的
**** 答案
B
*** 11-12
**** 对话
***** 转录
人们都爱吃营养丰富、味道鲜美的新鲜蔬菜和瓜果。然而，生活在城市中的人们，只能购买超市或菜场里出售的蔬果商品。这些商品，不但在新鲜度和品种上不能完全满足人们的需求，而且价格也比较贵，尤其在冬天更是如此。为了节省开支，吃到自己喜欢的蔬菜，在英国，许多居民开始自己用营养土在窗台上种植蔬菜。安排设计好的话，不仅可以吃到自己喜欢的蔬果，家里还多了一些可供观赏的植物。
***** 音频
a1bf9897-9240-4493-88c5-7947b5d09cef.mp3
**** 题目
***** 11
****** 问题
******* 转录
根据这段话，许多英国人在哪里种植蔬果？
******* 音频
c2718ac8-bab0-42ce-8fe4-849c77b30de5.mp3
****** 选择
******* A
超市
******* B
菜场
******* C
家中
******* D
农场
****** 答案
C
***** 12
****** 问题
******* 转录
为什么有些人不愿意买超市的蔬果商品？
******* 音频
8e9214d5-743e-4cac-8e2e-126b049a3488.mp3
****** 选择
******** A
比菜场贵
******** B
不够新鲜
******** C
不能欣赏
******** D
并不安全
****** 答案
B
*** 13-14
**** 段话
***** 转录
据新闻报道，一个 19 岁的北京女孩儿在 10 年间有过将近 40 个拓麻歌子，她一共在这种迷你游戏机上花去了一万多元。你可能不知道“拓麻歌子”这个名字，但是你一定记得一种叫作“电子宠物”的东西。电子宠物现在听起来可能是个有点儿年代感的说法了，不过它可是许多人，尤其是 90 后的童年记忆。甚至到现在，这种迷你的电子宠物游戏机依旧吸引着一众忠实的爱好者。
***** 音频
bf1cf3e7-f42e-447f-aaae-968a4ba438dd.mp3
**** 题目
***** 13
****** 问题
******* 转录
这段话主要谈论什么？
******* 音频
4a8c2fc8-3e90-46b6-b2c9-b8ea00ce5f07.mp3
****** 选择
******* A
一则新闻
******* B
怎么养宠物
******* C
一种童年游戏
******* D
一种电子游戏机
****** 答案
D
***** 14
****** 问题
******* 转录
关于电子宠物，下列哪项正确？
******* 音频
eb17fc12-56ee-49b1-804c-af2fb1b57962.mp3
****** 选择
******* A
非常贵
******* B
受90后欢迎
******* C
很多人没听说过
******* D
已经彻底过时了
****** 答案
B
* 阅读
** 第一部分
*** 课文
*** 题目
**** 15
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 16
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 17
***** 选择
****** A
****** B
****** C
****** D
***** 答案
**** 18
***** 选择
****** A
****** B
****** C
****** D
***** 答案
** 第二部分
*** 19
:PROPERTIES:
:ID: 4e3cfc10-e6ea-4a39-84c9-5fa6090a8b9e
:END:
**** 段话
老舍很有爱心，更懂得快乐要分享。每到昙花开放的时候，他就约上几位朋友来家里赏花庆祝。花分根了，一棵分为几棵，他会毫无保留地送给朋友们。看着友人高兴地拿走自己的劳动果实，老舍心里十分欢喜。
**** 选择
***** A
老舍会邀请朋友来家赏花
***** B
老舍毫无保留地帮助朋友
***** C
老舍把自己种的水果送人
***** D
老舍喜欢独享快乐的心情
**** 答案
A
*** 20
:PROPERTIES:
:ID: f648b663-8858-40df-9bbe-a25c82b1eeee
:END:
**** 段话
梅花香自苦寒来。老舍小时候家庭条件不好，在艰苦的生活环境中培养了勤俭节约的精神。当他功成名就之后，仍然保持着勤俭的好习惯。一次，朋友邀请他参加一个舞会。可是老舍只有两套灰布中山装，洗过几次后，都显得旧了，穿在身上像个清洁工。老舍就穿着这样的衣服进了舞会，他对投来不解目光的朋友说：“对不起了，这已经是我最好的衣服一。”
**** 选择
***** A
老舍喜爱梅花
***** B
老舍家里一直很穷
***** C
去舞会必须穿中山装
***** D
老舍没有为舞会买新衣服
**** 答案
D
*** 21
:PROPERTIES:
:ID: b6d2d427-07df-43b6-a1df-16b4d04ff6af
:END:
**** 段话
弗洛伊德认为，真正的心理咨询是咨询师把自己当作“会听故事的小男孩儿”，换句话说，咨询师就是倾听，而不做任何评价。而宠物就是良好的聆听者。从这个角度说，它们是天生的心理咨询师，可以给予主人一种特有的精神支持，安慰他们的心灵。
**** 选择
***** A
做心理咨询就是听别人讲故事
***** B
宠物可以给主人一种精神安慰
***** C
弗洛伊德认为小男孩儿适合当咨询师
***** D
主人和宠物的关系相当于病人和医生的关系
**** 答案
B
*** 22
:PROPERTIES:
:ID: 502c223e-54e7-495d-9f14-e76a9b880ec4
:END:
**** 段话
鲜艳的颜色往往是人们的视觉中心，它是一个环境中最突出的部分。利用好鲜艳的颜色，就给人的视觉带来了主题，就像一首优美的歌曲，不仅仅在曲调上有丰富的变化，而东能在听众的心中产生共鸣，达到高潮。所以，在室内装饰中，利用好鲜艳的颜色，就会使居室既雅致漂亮，又具有鲜明的个性，给人带来丰富的情感享受，对人的心理活动产生积极的影响。
**** 选择
***** A
室内装饰最好不用鲜艳的颜色
***** B
鲜艳的颜色容易吸引人的注意
***** C
看鲜艳的颜色就像在听一首歌
***** D
使用鲜艳的颜色才代表有个性
**** 答案
B
** 第三部分
*** 23-25
**** 课文
**** 题目
***** 23
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 24
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 25
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
*** 26-28
**** 课文
**** 题目
***** 26
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 27
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
***** 28
****** 问题
****** 选择
******* A
******* B
******* C
******* D
****** 答案
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
