* 练习

** 1
:PROPERTIES:
:ID: ba866def-6295-426e-b0f5-a19323d02882
:END:
*** 选择
**** 1
熟练
**** 2
结合
**** 3
不然
**** 4
自豪
**** 5
庆祝
**** 6
在乎
*** 题目
**** 1
***** 句子填空
我们的产品改善了许多人的生活，这是我们非常[[gap]]的事情。
***** 答案
4
**** 2
***** 句子填空
这项规定是[[gap]]了我校的实际情况而制定的。
***** 答案
2
**** 3
***** 句子填空
老李对儿子面试没被录取的事显得满不[[gap]]。
***** 答案
6
**** 4
***** 句子填空
国庆节期间，本市会举行大规模的[[gap]]活动。
***** 答案
5
**** 5
***** 句子填空
多亏了这条铁路，[[gap]]这么多煤炭怎么运出去？
***** 答案
3
**** 6
***** 句子填空
我觉得你们的动作好像还不太[[gap]]，还得多练习练习。
***** 答案
1
** 2
*** 1
:PROPERTIES:
:ID: 3d35d75b-5d5a-40f8-bf75-b6de5607e058
:END:
**** 句子填空
一连取得两扬胜利，李岩[[gap]]得不得了，以为冠军非他莫属了。
**** 选择
***** A
自豪
***** B
骄傲
**** 答案
B
*** 2
:PROPERTIES:
:ID: 7413f3b4-f479-4225-9612-a6d22fe464fb
:END:
**** 句子填空
对于他们这种敌法，我[[gap]]自己的意见。
**** 选择
***** A
保留
***** B
保存
**** 答案
A
*** 3
:PROPERTIES:
:ID: 078b2c4a-c4f4-4977-8ad1-e105f268a83a
:END:
**** 句子填空
看到五星红旗在赛扬上升起，我的眼圈[[gap]]了。
**** 选择
***** A
潮湿
***** B
湿润
**** 答案
B
*** 4
:PROPERTIES:
:ID: 51475cd5-f8af-4bbb-84e8-30a891c9c322
:END:
**** 句子填空
他是个工作狂，生活中[[gap]]工作还是工作。
**** 选择
***** A
除非
***** B
除了
**** 答案
B
** 3
:PROPERTIES:
:NOTETYPE: ed35c1fb-b432-43d3-a739-afb09745f93f
:END:
*** 1
**** 1
***** 词语
佶合
***** 答案
实际
**** 2
***** 词语
应付
***** 答案
挑战
**** 3
***** 词语
装饰
***** 答案
街道
**** 4
***** 词语
保留
***** 答案
观点
*** 2
**** 1
***** 词语
气候
***** 答案
潮湿
**** 2
***** 词语
服装
***** 答案
鲜艳
**** 3
***** 词语
情况
***** 答案
紧急
**** 4
***** 词语
动作
***** 答案
熟练
* 扩展
** 词语
*** 话题
行为2
*** 词语
**** 1
拆
**** 2
撕
**** 3
摸
**** 4
拍
**** 5
抓
**** 6
捡
**** 7
摘
**** 8
披
**** 9
偷
**** 10
抢
**** 11
捐
**** 12
扶
**** 13
挡
**** 14
拦
**** 15
退
** 题目
*** 1
**** 句子
知道李阳的困难后，同事们都为他[[gap]]款。
**** 答案
11
*** 2
**** 句子
产品自售出之日起七日内，发生问题，消费者可以选择[[gap]]贷。
**** 答案
15
*** 3
**** 句子
这个袋子很结实，用手[[gap]]不开，去拿把剪刀。
**** 答案
2
*** 4
**** 句子
经过四年的植树造林，种草固沙，退化的草原又[[gap]]上了绿装。
**** 答案
8
* 注释
** （三）词语辨析
*** 应付——处理
**** 做一做
***** 1
****** 句子
一个星期的迎来送往，她已经有点儿[[gap]]不了了。
****** 答案
******* 1
******** 应付
1
******** 处理
0
***** 2
****** 句子
他实在说不出什么，只好随口说：“不怎么习惯。”总算[[gap]]过去了。
****** 答案
******* 1
******** 应付
1
******** 处理
0
***** 3
****** 句子
放心吧，海关手续的事我一个人能[[gap]]。
****** 答案
******* 1
******** 应付
1
******** 处理
1
***** 4
****** 句子
我非常尊敬他，但同时也觉得他是个不好[[gap]]的人。
****** 答案
******* 1
******** 应付
1
******** 处理
0
* 课文
** 转录
作家老舍先生爱花，他养的花很多，满满摆了一院子。可除非是那些好种易活、自己会奋斗的花草，否则他是不养的。因为他知道北京的气候对养花来说，不算很好，想把南方的名花养活并非易事。
老舍把养花当作一种生活乐趣。他不在乎花开得大小好坏，只要开花，他就高兴。每天老舍像好朋友似的照管着花草。工作的时候，经常写几十个字，就到院中去转转，瞧瞧这棵，看看那朵，有时拿起剪刀给它们剪剪枝，有时蹲下捡几块小石头放在花盆里做点儿装饰，然后回到屋中再写一会儿，然后再出去，就这样脑力和体力很好地结合，身心也得到放松。
写作是件艰苦的工作，养花也是如此。有时赶上狂风暴雨，情况紧急，他就得劳驾全家人抢救花草。几百盆花，要很快地抢到屋里去，累得腰酸腿疼，热汗直流。第二天，天气好了，又得一盆盆地搬出去。可是，他并不抱怨，在他看来，任何事都要有付出，不然怎么会有回报？这是生活的真理。
一来二去，他慢慢地总结出一些养花的经验：有的花喜干，就别多浇水；有的花喜欢潮湿的环境，就别放在太阳地里。给花换盆剪枝施肥的活儿他越做越熟练，花生病长虫他也知道如何应付了。看着院子里那鲜艳的花朵，老舍自豪地说，“不是乱吹，这就是知识啊！多得些知识，一定不是坏事。”
老舍很有爱心，更懂得快乐要分享。每到昙花开放的时候，他就约上几位朋友来家里赏花庆祝。花分根了，一棵分为几棵，他会毫无保留地送给朋友们。看着友人高兴地拿走自己的劳动果实，老舍心里十分欢喜。有一次，送牛奶的小伙子进门就夸“好香”，这让老舍先生感到格外高兴。
当然，也有伤心的时候。一年夏天，下了暴雨，邻居家的墙倒了，菊花被砸死了一百多棵，这下可把老舍难受坏了，一连几天人们都看不到他脸上的笑容。
“有喜有悲，有笑有泪”，这是老舍对养花、对生活的体验。“我不知道花草们受我的照顾，感谢我不感谢，反正我要感谢它们。”老舍在自己的文章中这样写道。从中我们不难看出老舍先生对大自然的热爱，对生活的热爱。
