* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 9da120f6-76d9-4b85-b0e9-223d43dc5bb4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
65062dd7-f67d-41f2-a22c-4b8b1497852d.mp3
***** 转录
世界上有些珍奇动物，尽管人们千方百计去保护，仍然处于即将灭绝的境地。可是有些动物，比如老鼠，虽然人们在用各种方法消灭它们，但却总是消灭不了，成群的老鼠依然到处作祟。
**** 选择
***** A
珍奇动物灭绝得更快
***** B
老鼠不喜欢单独行动
***** C
人类想尽办法消灭老鼠
***** D
人类保护动物效果很好
**** 答案
C
*** 2
:PROPERTIES:
:ID: 3725e4da-e44b-4160-9106-350a2cce2ecd
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
31b548ef-d9c6-4882-bd0e-8b7fd67a67a2.mp3
***** 转录
手脚并用原地跑减肥方案的最大特点是在原地跑的基础上将上肢运动很好地融进来，通过每2～3分钟变速和花样变化跑，加之现场的互动气氛，增加了原地跑的趣味性，减少了原地跑的枯燥、乏味，使原地跑更易坚持。
**** 选择
***** A
原地跑步减肥成功概率高
***** B
手脚并用原地跑趣味性强
***** C
原地跑枯燥，但容易坚持
***** D
跑步需要互动，需要鼓励
**** 答案
B
*** 3
:PROPERTIES:
:ID: 73ab6ec0-7642-4c44-96f8-a579c93974cf
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
a54e8f48-b4b0-47d2-a745-aa6411e1dc7c.mp3
***** 转录
腌制食品口味独特，包装简单，便于携带，成为上班族的家常便饭。可是你知道吗，这些食品在腌制过程中需要大量放盐，这会导致此类食物盐含量超标，经常食用会加重肾脏的负担，增加发生高血压的风险。
**** 选择
***** A
腌制食品的包装非常独特
***** B
高血压病人不能吃腋制食品
***** C
上班族经常在家制作腋制食品
***** D
腌制食品含盐多，常吃不利于健康
**** 答案
D
*** 4
:PROPERTIES:
:ID: c98907ab-13e9-4077-80cf-c98ca0e075c9
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
07aa6dfb-3c74-4615-abde-a2c24b4df7e0.mp3
***** 转录
与人会谈时，若言不及义、唠唠叨叨，再多的时间也浪费了，如能把握谈话要领，言谈简要切题，就可以节省很多时间。节省下时间，就可以解决更多的问题，并且为自己赢得更多的自由时间。
**** 选择
***** A
谈话要简单、抓住重点
***** B
会谈前应做好时间计划
***** C
每个人都应有自由时间
***** D
节省下时间能发现问题
**** 答案
A
*** 5
:PROPERTIES:
:ID: c4a13603-bf6e-458c-9af0-793ca5eb4957
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
b1f4e64b-9afa-45b0-9da6-16709dccf499.mp3
***** 转录
余老师是个热心人，她多次从自己微薄的收入中拿出钱来给家庭困难的学生交学费。前不久，又从自己多年的积蓄中拿出钱资助村里修路。邻居们谁家有事也总爱找她参谋，她是周围十里八乡大伙儿的贴心人。
**** 选择
***** A
余老师热爱每一个学生
***** B
余老师的孩子没钱交学费
***** C
邻居家的闲事余老师都管
***** D
大伙把余老师看成最亲近的人
**** 答案
D
** 第二部分
*** 6-10
:PROPERTIES:
:ID: d3baa158-abdb-428a-ad14-8f91b80b0c93
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
ffaa7209-85b2-457e-be3b-5d75ed487207.mp3
***** 转录
男：您好！我们都知道您 25 岁考古系毕业就一头扎进了敦煌，在敦煌一待就是几十年，被誉为“敦煌女儿”。今天您就跟我们谈谈敦煌吧。
女：刚去的时候，虽说对大西北恶劣的自然环境早有心理准备，可是没想到反差那么大。那时候整个研究所只有一部电话，晚上只能用手电照明，上厕所要跑好远的路。和北京相比，简直就不是一个世界。可是每当我走过石窟的时候，都会赞叹：敦煌太好了，太美了！
男：敦煌莫高窟从发现到现在 100 多年了，把毕生精力都献给敦煌的人不少吧？
女：是的，它 1900 年一被发现便轰动了世界。1944 年中国第一批有志之士奔赴敦煌，在那儿设立了敦煌艺术研究所，至今已有三代学人在遍布黄沙的偏僻荒漠撰写了敦煌传奇。
男：我注意到您在那儿的研究不纯粹局限于考古，您的研究成果包括敦煌石窟考古美术方面的书籍、有关石窟考古与艺术的论文，还有大量探索古遗址科学保护及管理的论文。另外，“数字敦煌”也是在您的提倡下实现的，当时这在国内文物保护领域还是创举吧？
女：对。敦煌壁画是画在岩洞里的，自然侵蚀会使壁画慢慢消亡。莫高窟犹如人体，也会一天天变老，100 年前人们看到的莫高窟和现在看到的是不一样的。可是什么东西一旦数字化了就不变了，我们想利用计算机技术实现敦煌壁画、彩塑艺术永久保存的构想。
男：具体来讲，什么是“数字敦煌”？
女：这还要从游客说起。我们发现很多游客来之前没有做功课，不了解莫高窟。来了直接进入洞窟，看半天也看不出所以然。“数字敦煌”就是数字电影，把敦煌的历史、洞窟的相关内容以及分散在世界各地的相关资料、研究成果汇集到了一起。这样便于游客通过“数字敦煌”先了解敦煌，再进洞窟参观，效果会更好。实践证明“数字敦煌”很成功，它一问世就受到游客的欢迎。
**** 题目
***** 6
:PROPERTIES:
:ID: 8e47f99f-df92-4f0a-a491-4518729949f5
:END:
****** 问题
******* 音频
f2ec9372-dac5-4911-9570-377838750128.mp3
******* 转录
女的为什么被誉为“敦煌女儿”？
****** 选择
******* A
她对考古研究情有独钟
******* B
她多次去敦煌参观游览
******* C
她把毕生精力献给了敦煌
******* D
她自愿放弃了北京的生活
****** 答案
C
***** 7
:PROPERTIES:
:ID: a9e1c48a-6145-48af-955d-91e5862cc1cc
:END:
****** 问题
******* 音频
d3700c56-318a-42f1-b392-5a2bf8efd4f4.mp3
******* 转录
关于敦煌莫高窟，下列哪项正确？
****** 选择
******* A
莫高窟的历史长达百年
******* B
只有一批爱国人士去过敦煌
******* C
全世界都知道敦煌艺术研究所
******* D
三代学者为敦煌研究艰苦奉献
****** 答案
D
***** 8
:PROPERTIES:
:ID: a90a9c92-a371-410c-8112-d9cfa21b3ce0
:END:
****** 问题
******* 音频
0ee48f1f-cccc-4d22-9554-00172d69067a.mp3
******* 转录
女的做的哪件事在当时属于创新之举？
****** 选择
******* A
她写了敦煌石窟考古美术方面的书
******* B
她写了石窟考古与艺术方面的论文
******* C
关于古遗址科学保护及管理方面探索
******* D
利用计算机技术实现对文物的永久保存
****** 答案
D
***** 9
:PROPERTIES:
:ID: 5044b917-db1d-43a0-941f-6f92c90712bc
:END:
****** 问题
******* 音频
1980632c-aa5d-43d8-871c-4743805a0cc1.mp3
******* 转录
实现“数字敦煌”的好处是什么？
****** 选择
******* A
可实现敦煜艺术的永久保存
******* B
可代替人们去实地参观敦煌
******* C
可回看百年之前的敦煌莫高窟
******* D
可缓解自然对敦煌壁画的侵代
****** 答案
A
***** 10
:PROPERTIES:
:ID: 1c72bd0d-bd51-4f41-918b-154f66a0f114
:END:
****** 问题
******* 音频
42f16bd8-4cf2-44d3-8803-e449e033af64.mp3
******* 转录
游客为什么欢迎“数字敦煌”？
****** 选择
******* A
“数字敦煌”价格便宜
******* B
“数字敦煌”更为环保
******* C
游客直接看洞窟看不懂
******* D
游客喜欢电影这种形式
****** 答案
C
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 1beed128-7b34-4fe6-a7f6-364cac28b38e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
25fdcc56-8d0c-4471-93c6-893a83238ce7.mp3
***** 转录
这是一个奇怪的组合，一对退休的老夫妻，一辆年逾百岁的老爷车。不知是冲动还是执念，他们相伴踏上了环游世界的奇妙旅途。
老夫妻来自荷兰，丈夫叫德克，妻子唤作特鲁迪，他们在 1997 年购入了一款生产于 1915 年的老式福特 T 型车。这辆本应在博物馆里沉睡的老爷车，却在德克的手中焕发了青春。
2012 年夏，漫漫旅程拉开了序幕。他们先是去了非洲，行程大约 24000 公里，这是他们的第一次尝试，幸运的是，比他们年纪都大的福特 T 型车并没有吃不消。2013 年，他们来到了美国和加拿大，走过了 27000 公里，在这段旅途中，福特 T 型车仅仅出了一点儿小毛病。2014 年，他们开赴南美地区，总行程 26000公里。随着名声渐起，这一次，他们还顺便做了一场公益活动，全程共募集爱心捐款 3 万英镑，悉数用来资助贫困儿童。
旅行还没有完成，但德克夫妇由衷地感谢这辆年迈的爱车，是它伴随着他们进行了这场他们盼望已久的挑战。
**** 题目
***** 11
:PROPERTIES:
:ID: 5faa8525-3b23-40a7-a078-63e12090ea0b
:END:
****** 问题
******* 音频
02fc67ee-892b-4c9c-8455-f7f4ca42a6ad.mp3
******* 转录
关于德克夫妇的环游世界之旅，下列哪项正确？
****** 选择
******* A
德克夫妇为了旅行辞掉了工作
******* B
德克夫妇一共去了4个国家
******* C
环球旅行的费用全部来自公益活动
******* D
环球旅行对德克夫妇来说是一场挑战
****** 答案
D
***** 12
:PROPERTIES:
:ID: ee8a28dd-3cc0-48eb-b36d-d1640cef90c6
:END:
****** 问题
******* 音频
bf556f1e-0d98-437d-86c1-de4eeb7e09c3.mp3
******* 转录
关于福特 T 型车，下列哪项正确？
****** 选择
******* A
博物馆喜欢收藏这款车
******* B
车是1915年生产的
******* C
1997年这款车坏了
******* D
2012年老夫妻租赁了这款车
****** 答案
B
***** 13
:PROPERTIES:
:ID: 793bb598-a27b-4961-90ad-b9e4bdcfc614
:END:
****** 问题
******* 音频
65f519a8-e9f5-48cc-ad96-d2e71e0e4263.mp3
******* 转录
在旅途中，可以知道什么？
****** 选择
******* A
车经常会出一些小问题
******* B
这辆百岁老车一直很森
******* C
出发前德克夫妇已闻名世界
******* D
德克夫妇长年帮助贫困儿童
****** 答案
B
*** 14-17
:PROPERTIES:
:ID: 5b750963-96a6-4012-ba03-0ae187574a8e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
2da9e8c9-d994-43c8-9c33-78c758d6cab9.mp3
***** 转录
东明是我的一位朋友，她习惯先做喜欢做的事，心情好了，再做不喜欢做的事。她喜欢旅行，有朋友对她说，钱花在玩儿上，多浪费啊，用这些钱干点儿什么不好。她说，再穷也要去旅行。不去旅行，你会更穷。这是什么逻辑？可她真是这样做的，云南、西藏、沿海渔村，我想去却因为种种原因没去成的地方，她都去了。每次回来，她虽然疲惫，精神却很饱满。那次从西藏回来，她写了一个很久都写不下去的提案，灵感如泉涌，下笔如神助，讨厌的事就这么又快又好地做完了。后来那个提案得了奖，她的旅费都赚回来了。
东明在做一件很重要的事之前，总是先给自己一个奖励。比如坐周末航班去另一个城市见一位想见的朋友，先在那里和好友喝咖啡逛店，聊天聊到深夜，周一回来再开始工作，因为心情放松了，事情也就完成得特别顺利。
**** 题目
***** 14
:PROPERTIES:
:ID: 1d20db64-1ad7-4dfc-a2b1-67036f5693f3
:END:
****** 问题
******* 音频
3a07ac16-368e-4f97-97b8-a8b4d852614b.mp3
******* 转录
东明的逻辑是什么？
****** 选择
******* A
没钱也要去旅行
******* B
穷人不用去旅行
******* C
心情好才适合旅行
******* D
少花钱也可以旅行
****** 答案
A
***** 15
:PROPERTIES:
:ID: d39f64cf-2340-422c-9da6-91c328b09d53
:END:
****** 问题
******* 音频
a539069c-0b54-4ee9-84c7-b8ea2aef6b30.mp3
******* 转录
东明从西藏回来有什么收获？
****** 选择
******* A
高质量地写完一提案
******* B
改善了一度疲惨的状态
******* C
顺便在那里赚了一笔钱
******* D
找到了一份更好的工作
****** 答案
A
***** 16
:PROPERTIES:
:ID: e8a9f858-f225-4759-bc8e-c0292ffca4e9
:END:
****** 问题
******* 音频
0e13a3cf-4824-412b-9e32-8286866e901b.mp3
******* 转录
东明做重要事情之前，先做什么？
****** 选择
******* A
拜访老友
******* B
喝杯咖啡
******* C
逛店聊天
******* D
奖励自己
****** 答案
D
***** 17
:PROPERTIES:
:ID: 167eae99-0eab-46bd-88bd-af0f03247aac
:END:
****** 问题
******* 音频
a539db68-3620-4575-bcad-53bb065cd284.mp3
******* 转录
根据这段话可以知道什么？
****** 选择
******* A
有钱要花在刀刃上
******* B
旅游有助于调整情绪
******* C
游山玩水花钱是浪费
******* D
人都有心情不好的时候
****** 答案
B
* 阅读
** 第一部分
*** 18
**** 句子
***** A
这件作品我整整做了10年，是我辛苦最多的。
***** B
李老汉做的松皮扣肉远近闻名，饭店常请他帮忙，以便招徕食客。
***** C
假如我不去留学，一直留在家里，我的人生完全会变成另外一副样二。
***** D
他是专程赶到阿姆斯特丹，去看那些很慢、很长，又很有情怀的纪录片的。
**** 答案
*** 19
**** 句子
***** A
他是很重友情的，永远会全心全意对待每一个朋友。
***** B
全世界章鱼种类大约有650多种，它们的个头相差极大。
***** C
初来乍到，我们既不熟悉当地风土人情，也听不懂他们的方言。
***** D
在一个人的成长道路上，要是能够找到自己的指南针，就会少走许多弯路。
**** 答案
*** 20
**** 句子
***** A
调查表明，城市各主要街道繁体字使用率高达39％。
***** B
为了防止不再发生乱收费的问题，有关部门加强了管理。
***** C
社会的发展变迁必然会在语言的词汇系统里留下时代印迹。
***** D
他生活在繁华的都市，忙得日理万机，但他始终不能淡忘儿时的往事。
**** 答案
** 第二部分
*** 21
**** 段话
鸟类在不同季节[[gap]]栖息地，或是从居住地移至越冬地，或是从越冬地[[gap]]居住地，这种现象称为迁徙。乌类因迁从[[gap]]的不同可分为留乌、夏候鸟、冬候鸟、旅鸟、迷鸟等几个类型。
**** 选择
***** A
****** 1
交换
****** 2
搬回
****** 3
方法
***** B
****** 1
更改
****** 2
移居
****** 3
风格
***** C
****** 1
转换
****** 2
迁移
****** 3
习俗
***** D
****** 1
更换
****** 2
返回
****** 3
习性
**** 答案
*** 22
**** 段话
卫星导航技术的发展[[gap]]有三：一是卫星导航的多系统并存，使系统可用性[[gap]][[gap]]提高，应用范围更大；二是多元组合导航技术得到[[gap]]应用；三是卫星导航与无线通信等其他高科技相结合，从[[gap]]上促进IT技术的整体发展。
**** 选择
***** A
****** 1
趋势
****** 2
得以
****** 3
推广
****** 4
根本
***** B
****** 1
事业
****** 2
可以
****** 3
延伸
****** 4
基础
***** C
****** 1
主流
****** 2
能够
****** 3
若干
****** 4
基本
***** D
****** 1
产业
****** 2
获得
****** 3
深入
****** 4
本来
**** 答案
*** 23
**** 段话
[[gap]]凶猛的鲢鱼一般在海洋中上层活动，它能一口吞下成群的小鱼，还能咬死和吃掉比它大的鱼或其他动物，奇怪的是，它从不吞食和它[[gap]]的小伙伴一一向导鱼。向导鱼在鲨鱼周围游来游去，反应[[gap]]，一点儿也不[[gap]]粼鱼。
**** 选择
***** A
****** 1
脾气
****** 2
不离不弃
****** 3
灵活
****** 4
畏惧
***** B
****** 1
个性
****** 2
难舍难分
****** 3
灵敏
****** 4
恐怕
***** C
****** 1
性情
****** 2
形影不离
****** 3
敏捷
****** 4
害怕
***** D
****** 1
性格
****** 2
亲密无间
****** 3
矫健
****** 4
惊恐
**** 答案
** 第三部分
*** 段话
曾经有人说过，要么读书，要么旅行，身体和心灵，[[gap:24]]。
生活在这个世界上，我们会遇见很多的人，经历很多的事，我f丨〕含厄`之寥J茎‖灾F惑、疲怀。这个时候，[[gap:25]]？在行走中领悟人生，在与大自然的接触中找到自我。
旅行，让人见多识广。在旅行中，我们可以看美丽的风景，了解新的文化习俗，[[gap:26]]，所以不要再被束缚在书本里了，旅行吧，更好地去了解生存的意义。
旅行，能让我们的心灵得到一次真正的解脱，远离现实的复杂，远离城市的喧闸，[[gap:27]]。行走在阳光下，循征在微风中。在那样的美景里，每一秒钟的自己都是全新的。
所谓旅行，并不光是去过多少地方，吃过多少美食，看过多少美景，而是在一个又一个的旅途中，对自己有不同的认识，对人生有不同的感受。其实，人生就是一次旅行，重要的不是目的地，[[gap:28]]。
*** 选择
**** A
何不去旅行呢
**** B
远离所有的烦恨
**** C
我们还能发现那些在书本上找不到的东西
**** D
而是欣赏风景的心情
**** E
必须有一个在路上
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
旅游，顾名思义是外出旅行游览。跋山涉水，观赏自然界的美丽风光，忘情于山水之间。
古人也喜爱这项情趣高雅的活动。大约1500年前，中国就有了“旅游”一词。当时的诗人沈约就有“旅游媚年春，年春媚游人”的诗句，意思是说“游客留恋春天的美景，春景也在取悦着游人”。
古人旅游交通不倬，基本靠脚，其他交通工具多是驴车、马车或木船，大部分时间都要花在行程中，真所谓历尽艰辛，因此多数百姓是就近游玩。史载，唐朝，西安郊外曲江风光秀美，景色宜人。每年三月三、重阳节，曲水悠悠，亭台楼阁，游人如织。大家兴致高了，便登高作诗，借以助兴。
明未旅行家徐霞客一生志在四方，足迹遍及如今各省、自治区、直辖市。所到之处，探幽寻秘。徐霞客的传世之作《徐霞客游记》便是他旅行34年，撰写的-本以日记体形式完成的地理著作，主要记录了他观察到的人文、地理、动植物等状况。如今中国将5月19日定为“中国旅游日”，便是选择的《徐霞客游记》的开篇之日。
古人旅行是把心放在山水里，认为风景是属于懂它的人。在自然面前，山水之美，让人世间的是非恩怨都淡了。古人旅游的兴致与情趣令今人自叹弗如，让我们试着感受古人的旅游，心随山水走，诗意地行走于生活，尽情释放自己的真性情。
**** 题目
***** 29
****** 问题
古人旅行：
****** 选择
******* A
寄情于山水之间
******* B
一心为喝酒写诗
******* C
没有今人的兴致高
******* D
在旅行中寻找人性
****** 答案
***** 30
****** 问题
第3段画线词语“就近”的意思是：
****** 选择
******* A
靠近
******* B
趁着近
******* C
如果近
******* D
在附近
****** 答案
***** 31
****** 问题
古人旅游最大的囱难是：
****** 选择
******* A
行程不好定
******* B
交通不方便
******* C
景点太集中
******* D
没有人组织
****** 答案
***** 32
****** 问题
为什么称徐霞客为旅行家？
****** 选择
******* A
他旅行的时候坚持天天写日记
******* B
他用34年的时间写了一本游记
******* C
他道览中国名山大川并有著作传世
******* D
他号召设立了“中国旅游日”
****** 答案
*** 33-36
**** 段话
瑞士拉沃梯田式葡菊园，位于瑞士沃州荷蒙湖北岸一片18公里长的山坡上。800多年来，这片“世外桃源”始终坚持人与自然的完美对话，在改造自然、战胜自然的同时，面对势如破竹的城市化进程依然独善其身，被称为“人间仙境”。
拉沃梯田式葡萄园总面积898公顷，包括574公顷葛萄园和散落其问的14个小村落。路特里一一拉沃地区西端的第一个村落，就是梯田式葡萄园的起点。湖边一直平缓的山坡从这里开始变得险要，坡度从25“到团渡70”不等，然而，这儿乎直立的山坡上，却满是碧绿的葡萄园，18公里长的坡地就像一条时宽时窄的翠带，丝毫看不出这里曾是一片多石少土的荒蛮之地。
拉沃梯田式葡萄再始建于12世纪中叶。起初教士们从山坡最为险要的地段开始开垒这片贫疳的土地，他们用双手将山坡上的石头垒成一道道石墙，在石墙里堆上土，建成一道道梯田，种上一株株葡萄苗。随后，附近的村民也加人到改造山坡、种植葡萄的大军中。经过数个世纪的辛勤劳作，葡萄种植和酿酒已成为拉沃地区的支柱产业之一。这里生产的葡萄酒品牌远近闻名，德萨雷牌葡萄酒更是供不应求。
20世纪70年代初，拉沃也面临着城市化的问题，甚至有人相中了这里的湖光山色、林木葱茫，一心一意要在这里建造高档别墅区，届时超级市场、娱乐场所、大型停车场等一样都少不了，果真如此，保持了几个世纪的拉沃地区梯田式葡菊园将会被彻底破坏掉。最后经过当地居民的不断努力，拉沃成功避免了城市化的侵犯。从1998年起，拉沃地区梯田式葡萄园开辟出32公里长的旅游步行线，人们可以步行在田垒小道上欣赏葡萄园。2007年，拉沃梯田式葡萄吴成功进入《世界文化遗产名录》人们称它是“种出来的世界文化遗产”。
**** 题目
***** 33
****** 问题
800多年来，拉沃梯田式葡萄园有过怎样的经历？
****** 选择
******* A
村里盖起了别坐
******* B
与城市化擦肩而过
******* C
葡萄园里有了娱乐场所
******* D
这里酿出来的酶总是不够喝
****** 答案
***** 34
****** 问题
拉沃梯田式葡萄园的特点是：
****** 选择
******* A
葡萄再散落在村子里
******* B
葡菊都种在平缓地带
******* C
葡萄种在多石少土的山坡上
******* D
儿乎直立的山坡上种满了葛萄
****** 答案
***** 35
****** 问题
12世纪中叶，拉沃地区发生了什么事？
****** 选择
******* A
教士们带头修建梯田
******* B
村民们学习种植葡萄
******* C
葡萄酒成了当地特产
******* D
这里的葡萄酒出名了
****** 答案
***** 36
****** 问题
最适合做上文标题的是：
****** 选择
******* A
美丽的葡萄园
******* B
人与自然的完美对话
******* C
拉沃创造了人间奇迹
******* D
种出来的世界文化遗产
****** 答案
