* 热身

** 1
:PROPERTIES:
:ID: f6404525-2a0a-471c-bcd1-2590a22fbb2d
:END:

*** 1

**** 词语

兴奋

**** 答案

f

*** 2

**** 词语

硕士

**** 答案

a

*** 3

**** 词语

困

**** 答案

e

*** 4

**** 词语

翻译

**** 答案

b

*** 5

**** 词语

拉

**** 答案

d

*** 6

**** 词语

躺

**** 答案

c

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: 1d5b865d-885d-42de-a74a-ac03804e33f9
:END:

**** 选择

***** 1

低

***** 2

困

***** 3

拉

***** 4

泳远

***** 5

建议

**** 题

***** 1

****** 段话填空

一个不知道自己缺点的人，🟦都不会想要去改变。

****** 答案

永远

***** 2

****** 段话填空

他们两个人打球的水平差不多，很难仇出高🟦。

****** 答案

低

***** 3

****** 段话填空

我刚学会开车，水平一般，还经常走错路。朋友🟦我平时多开车出去走走，熟悉一下道路情况，这样慢慢就好了。

****** 答案

建议

***** 4

****** 段话填空

解决问题时，一个人的知识常常是不够的，所以人与人之间需要交流。在交流过程中，一方面，丰富了知识，提高了能力，另一方面，又🟦近了人们之间的距离。

****** 答案

拉

***** 5

****** 段话填空

人比动物聪明，但动物仍然有很多值得人学习的地方。拿狮子来说，仑们🟦的时候才星觉，锇的时候才吃东西，永远不为昨天的事烦恼，也不为明天的事担心。

****** 答案

困

*** 6-10
:PROPERTIES:
:ID: 20e7db65-d9c1-4ed5-96ef-5d2cf676f54e
:END:

**** 选择

***** 1

空儿

***** 2

答案

***** 3

礼拜天

***** 4

关键

***** 5

躺

**** 题

***** 6

****** 对话填空

Ａ：你最近忙吗？哪天有🟦？
Ｂ：干什么？又想让我陪你去逛街呀？

****** 答案

空儿

***** 7

****** 对话填空

Ａ：🟦我们去学校的体育馆打网球吧？
Ｂ：好啊，不过周末人会不会很人多？

****** 答案

礼拜天

***** 8

****** 对话填空

Ａ：房间里这么暗，怎么不开灯呀？你身体不舒服？
Ｂ：没有，我本来🟦在沙发上看书，结果睡着了。

****** 答案

躺

***** 9

****** 对话填空

Ａ：很多女孩子都希望找一个个子高的男朋友，你呢？
Ｂ：高矮没太大关系，🟦是我得喜欢他，爱他。

****** 答案

关键

***** 10

****** 对话填空

Ａ：怎么了？什么事这么不高兴？
Ｂ：别提了，今天考试写🟦写到最后，发现少了一个，又来不及改了。

****** 答案

答案
* 注释

** 1

*** 比一比

**** 做一做

***** 词语

****** 1

不过

****** 2
:PROPERTIES:
:ID: 6fd2e284-9b49-49fc-9e08-9abe329f362a
:END:

但是

***** 题

****** 1
:PROPERTIES:
:ID: 5adf7159-3653-4b31-8bb2-03757250c3f0
:END:

******* 课文

每天喝上点儿葡萄酒，对身体是有好处的不能喝太多。🟦不能喝太多。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: a5b457df-d8a4-425a-b36f-4d6552e06dbc
:END:

******* 课文

他结婚的时候🟦20岁。

******* 答案

******** 1

1

******** 2

0

****** 3
:PROPERTIES:
:ID: fffe64cc-c43f-47b0-85a4-b8857ea58f6d
:END:

******* 课文

大部分人每天晚上至少应该睡7个小时，🟦这个标准并不适合每一个人。

******* 答案

******** 1

1

******** 2

1

****** 4
:PROPERTIES:
:ID: 1510a436-0522-48c9-be45-02b5f680480c
:END:

******* 课文

对不起，先生，我们店的吊卡机环了，只能用现金。🟦商场附近有衫银行，您出了门右转，走到头儿就能看到。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: 39673ba3-112c-4d05-ad07-63f08ca3ef75
:END:

******* 课文

这次亲戚来北京🟦住两三天，就让他来家里住吧，不用信宾馆了。

******* 答案

******** 1

1

******** 2

0

* 扩展

** 做一做
:PROPERTIES:
:ID: f46acb01-11ac-4564-b0a4-9793387d5c76
:END:

*** 选择

**** 1

经济

**** 2

经验

**** 3

经历

*** 题

**** 1

***** 内容填空

取得成功的人都🟦过许多失败，他们和普通人的区别是，他们坚持了下来，正是这种坚持，使他们从失败走向了成功。

***** 答案

****** 1

经历

**** 2

***** 内容填空

我哥哥今年26岁，现在正在读硕士研究生，学的是🟦法专业。我觉得他不但能力强，而且脾气好，将来一定能找到一份很好的工作。

***** 答案

****** 1

经济

**** 3

***** 内容填空

我们长大的过程，就是解决一个又一个问题，在失败中慢慢积累🟦，在成功中慢慢获得信心的过程。

***** 答案

****** 1

经验

* 课文
** 1
*** 转录
孙月：礼拜天有空儿吗？陪我去逛街怎么样？我想去给丈夫买个生日礼物。
王静：我可能去不了，最近事情多。
孙月：你最近是不是工作特别忙？
王静：我现在上有老，下有小。除了工作以外，家里还有母亲和儿子需要照顾。
孙月：真是辛苦啊！你最近脸色不太好，是不是哪儿不舒服？要注意身体啊。
王静：没事儿，谢谢！不过现在我很幸福，因为在母亲面前我可以做一个永远长不大的孩子；在孩子面前我又是个能照顾他的母亲，这让我有了努力的方向。
** 2
*** 转录
高老师：你看人家王老师，刚来这儿工作三年就当了教授，还有个好妻子，真让人美蓉！
李老师：其实，你在别人眼中也是很幸福的，只是你自已没有发现。
高老师：是吗？我哪能跟王老师比啊？
李老师：你有一个漂亮的女儿，还那么优秀，硕士毕业后就当了翻译。
高老师：我女儿确实不错，记得她刚拿到第一个月工资时，就兴奋地拉着我和她爸俩去商场，给我们买礼物，那时我和她爸心里别提多美了！
李老师：所以说每个人有每个人的生活，不用羡慕别人。你美慕别人的时候，他们可能也正在羡慕你呢。
** 3
*** 转录
小雨：时间过得真快，马上就要毕业了。毕业后你打算做什么？
小夏：我还没想好呢，正想听听你的建议。你觉得在选择职业时，收入重要吗？
小雨：在我看来，赚钱多少不是最重要的，兴趣才是关键。只有做自已喜欢的事，才会觉得幸福，将来也会有更好的发展。
小夏：我也这么想。如果我带着热情去做自己喜欢的工作，就不会感到累。不过，现在什么东西都那么贵，生活压力太大了，没有钱也不会过得幸福啊！
小雨：幸福其实很筒单，它不是只要有钱就能买到的。我觉得工作结束回家后，洗个热水澡，然后躺在床上看看书、听听音乐，困了睡睡觉，就很幸福。
小夏：你说的也对。如果能找到一份自己既感兴趣，收入又不错的工作，那就最好了。
** 4
*** 转录
有的人希望穿得再好一些，房子再大一些，认为经济条件越好人就越幸福。其实有很多富人过得并不愉快，而有些穷人却过得很快乐。有钱不一定幸福，因为很多东西都是不能用钱买到的，例如时间、感情、生活经历等。但是，从另外一个方面看，如果没钱，也，很难过得幸福。当你生病了，如果由于缺钱而不能及时去看医生，你的健康都很难得到保证，就更别说幸福了。
** 5
*** 转录
什么是幸福？有的人认为，工资高、能赚钱就是幸福；有的人认为，情放松、身体健康才是幸福；也有人认为，能帮助别人就是一种幸福。还有人说，小时候幸福是一件东西，比如一块橡皮、一块糖，得到了就很幸福；长大后幸福是一种态度，生活的态度决定了我们幸福感的高低。那怎样才算是真正的幸福？其实，幸福并没有一个标准答案，每个人对幸福都有不同的理解。不管你认为幸福是什么，只要你用心去找，就一定能发现它。
