* 听力

** 1

*** 1

**** transcript

古人云“书到用时方恨少”，今天确实有了体会。妻子出差，我陪儿子睡觉。儿子要求讲故事，我搜肠刮肚也找不出故事。找书求救吧，这才发现，家里书是不少，但除了计算机还是计算机，竟找不出一本能救急。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

我小的时候，一直看着父亲和周围的人忙碌，于是觉得一切都理所当然。长大了自然和父亲一样，每天过着除了工作没有其他内容的生活。但日复一日，现在这种紧张的生活已经让我有些身心俱疲。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

天才常给人留下不爱和人打交道甚至独来独往的印象，或经常有着悲惨的经历。和其他天才不同的是，他被很多爱热闹的朋友们环绕，有着温暖的家庭和优秀的员工。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

这本纪念普及版的《城南旧事》2003年由中国青年出版社出版，作者是台湾女作家林海音。全书讲述的是英子童年的故事，反映了作者对童年的怀念和对故乡的思念。同名电影在中外电影节荣获过多个奖项。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

有人说，最幸运的人是在年轻时犯过所有的错误，然后及早明白了人生道理，从此踏上坦途。小李就是这样的幸运儿，如今的他，感谢自己曾经遭受过的一切挫折，因为那些正是他成长的动力。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

男：好久不见，您好！
女：您好！
男：作为记者，虽然我自认为已经很资深了，但还是很期待今天的采访。大家都知道，您是前女排国手，一位尽人皆知的明星运动员。而退役之后，您的生活更引人关注，因为您选择了一条与众不同的路。如今您的小说已确定入围华语科幻星云奖了，您有什么样的感受？
女：这是另一个领域给自己的肯定。我很开心，非常开心。当然这只能算是一个起点。
男：您觉得写科幻小说和打排球是不一样的？
女：打排球压力很大，背负了太多国家、球迷和家人给的压力。
男：运动员退役写自传的比较多，您却选择了写科幻小说，您是觉得自己擅长写科幻？还是科幻对您有特别的意义？
女：我从小好奇心就比较重。也喜欢看探索、揭秘这种节目，包括外星人这些话题。
男：您觉得作为一个作家，您的优势在哪里？
女：勤奋。打排球教会我很多东西。我学到了坚持，拼搏，不怕挫折。当别人认为可能没有机会的时候，我还想努力去拼一下。可能只有 1％的概率，我也想去挑战，这可能就是运动员的性格。
男：运动员退役转型很受关注，您觉得自己的决策算是成功的吗？
女：有些人会觉得我出书了，还入围了奖项，我成功了。我自己倒是觉得，勇于义无反顾地丢掉铁饭碗，勇于为自己的人生做主，这是我的成功之处。
男：很多人愿意留在相对稳定的环境中，您这样做意味着要终身为自己的生计操劳，您对自己的选择不后悔吗？
女：不会呀。当然，刚开始会觉得不安，突然有一天没人给你发工资了，你的医疗卡也被取消了。会觉得我脱离这些以后，我能做什么呢？我父母也有顾虑，觉得起码要有一个保障。但我觉得，我要自由，我想做自己想做的事情。我会对自己的将来负责任。不管是好是坏，我都认。我不后悔自己所做的任何选择，就算是错误的，那也是我的成长经历。

*** 音频

e104e3fb-1df5-4873-86a2-33b9ad445653.mp3

*** 题目

**** 6

***** 问题

记者为什么期待这次采访？

***** 音频

0a3caf48-6651-410c-8ac9-16dcc16a965c.mp3

**** 7

***** 问题

女的怎么看排球或者是科幻小说？

***** 音频

309ddc28-696e-46bd-8347-6bb29a9a51b3.mp3

**** 8

***** 问题

女的作为作家，她的优势是什么？

***** 音频

d1416b60-0e62-4733-853d-a2e47d23f0d4.mp3

**** 9

***** 问题

女的认为自己什么地方是成功的？

***** 音频

1bcfbb30-31b1-4f45-a72f-b69ffb577bca.mp3

**** 10

***** 问题

对于自己的选择，女的怎么想？

***** 音频

e5b94f1b-89c9-4801-bc42-c6ff999132bd.mp3

