* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: a5dfeb54-51e4-4b8b-a353-fb7926d53709
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
291bff1d-81b1-42e2-9cc0-85da1a1565c6.mp3
***** 转录
教师上课精神焕发、情绪饱满，学生也会注意力集中。在这种状态下进行体育教学，学生就会思想敏捷、动作反应快；反之，则动作迟缓、接受能力差。
**** 选择
***** A
身体不好就不适合教书
***** B
老师的情绪会影响学生
***** C
好老师未必能教出好学生
***** D
老师上课都会集中注意力
**** 答案
B
*** 2
:PROPERTIES:
:ID: 3c309ecc-271e-450d-b797-afd59ae017b3
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
05eafdd8-c1df-4102-a62e-8a26c633e472.mp3
***** 转录
书有精装，有平装。我喜欢平装的那种，一是经济实惠，二是便于阅读。硬皮的精装版不适于携带，阅读时需要正襟危坐，本来看书是一种赏心悦目的享受，这样严阵以待弄得就有些累了。
**** 选择
***** A
精装书便于阅读
***** B
平装书价格便宜
***** C
收藏精装书是享受
***** D
说话人喜欢欣赏书
**** 答案
B
*** 3
:PROPERTIES:
:ID: 158e0194-4c8c-4a1e-98a1-d93e98a89052
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
d5875aac-fff8-49fb-8e7f-153e461c3d19.mp3
***** 转录
仿生学是生物学的一个分支，研究生物体系统的结构、功能等，用来改进工程技术系统。如模拟人脑的结构和功能原理，改善计算机的性能。
**** 选择
***** A
仿生学等同于生物学
***** B
仿生学可仿制人脑的结构
***** C
计算机中就有仿生学的研究成果
***** D
生物体系统的结构、功能有待改进
**** 答案
C
*** 4
:PROPERTIES:
:ID: 7affea00-ed37-441e-9735-9c509af139c5
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
06f8dc8b-9932-493f-91bf-00673e98b529.mp3
***** 转录
别看小青长得不起眼，她的工作可是一级棒。想当初她应聘，没有一个部门要她。看她笔试成绩第一，我决定姑且一试。结果不到一星期，她就把部门所有的烂账搞得一清二楚，现在大家都想来抢她。嘿嘿，这可是门儿都没有的事。
**** 选择
***** A
小青样孔很漂亮
***** B
小青面试不合格
***** C
小青数学成绩好
***** D
谁都要不走小青
**** 答案
D
*** 5
:PROPERTIES:
:ID: ce236090-6534-4484-820f-fda1d257d574
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
ad6512b7-78e4-48ee-8e26-cd3081f0a234.mp3
***** 转录
对于我这个小球迷，姥姥可是操心不少，她总是担心我看足球比赛影响学习。我向她保证，只会学习球员勇争第一的精神，一定不会影响学习。可是，独自看球多没劲呀，一个人喝彩、一个人焦急！我真想看球的时候有个伴儿。
**** 选择
***** A
姥姥不爱看足球比赛。
***** B
姥姥喜欢球员的勇敢
***** C
一个人看球很没意思
***** D
“我“有个朋友也爱看球
**** 答案
C
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 25a0dbac-64eb-4a3f-b8e7-33c658a83969
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
82f478a9-0f33-411f-9ab9-43422540749e.mp3
***** 转录
女：您新书上市以后，引起了不少读者的共鸣，您是怎么决定写这本书的？
男：我爱人给我讲了一个真实的故事。一个弱女子为了爱远嫁他乡，但换来的既有短暂的幸福又有暴力相加的婚姻生活。她想过逃，可一想到还有甜蜜的爱，又不想逃了，就这样，她已年近 40。我想知道现在人的爱情观，他们的爱与被爱，他们的幸福与不幸福。我开始有了写书的念头，我希望写一本书，能给爱或即将爱的人一些思考抑或参考。
女：素材来自哪里呢？
男：既然要真实，那就采访吧。我采访了各行各业的数十个男男女女，听他们讲述各自的情感故事。
女：难怪这本书是由一系列并无关联的小故事构成的。
男：是。我打心眼里相信，有的人的人生是故事，也有可能是事故，而在人生的爱情部分，有太多的存在方式。譬如自爱、他爱、离爱、被爱、弃爱。我的愿望是写出真实、可感、可悟的作品，客观地呈现当代人的情感状态。
女：为了搜集这些情感故事，您一定付出了很多。
男：是啊，一边采访一边写。我每天观察身边的人，不想漏掉任何一个好故事，再筛选其中最有价值的。我每天带着纸和笔，我拒绝用录音、录像那些高科技手段做记录，因为原始的方法给我一种“融入”或“参与”其中的感觉，我怕其中掺杂了太多想像的成分。
女：能给我们讲一个您印象最深的故事吗？
男：书里面有一个电脑先生的故事。电脑先生一直单身。一次他去一个客户家维修电脑，他娴熟的技术和温文尔雅的态度给客户小姐留下了深刻的印象。从此，客户小姐电脑一出问题立刻就找他，再后来，家里所有的东西出了问题都会请他来。结局你当然猜得到，文雅、漂亮、收入好的客户小姐相中了电脑先生。这个故事呈现出爱情的千万种可能，所以我把它写进了书里。
**** 题目
***** 6
:PROPERTIES:
:ID: dc0a7f9b-f119-4dec-93dc-6a73bfd7b23f
:END:
****** 问题
******* 音频
54b2d396-d930-4a64-81af-bb122370a1c2.mp3
******* 转录
关于男的的爱人讲的故事，下列哪项正确？
****** 选择
******* A
女的身体一直不好
******* B
女的婚后有时挨打
******* C
女的婚后非常幸福
******* D
女的四十岁去世了
****** 答案
B
***** 7
:PROPERTIES:
:ID: a6cb4f08-98c1-4e01-952f-b15b5fb1705a
:END:
****** 问题
******* 音频
3b8b987c-7d49-48f3-8771-a78ae4de6889.mp3
******* 转录
男的写这本书的目的是什么？
****** 选择
******* A
给人们提供一些思考
******* B
避免人生事故的出现
******* C
告诉人们要相信爱情
******* D
写出一本最畅销的书
****** 答案
A
***** 8
:PROPERTIES:
:ID: 04bc85f2-39fa-4652-b89c-730b1d921630
:END:
****** 问题
******* 音频
92cce102-352e-4ee2-b652-62fe67112e72.mp3
******* 转录
关于素材，下列哪项正确？
****** 选择
******* A
故事必须是自己的
******* B
当事人要写下故事
******* C
故事必须有录音录像
******* D
作者追求融人的感觉
****** 答案
D
***** 9
:PROPERTIES:
:ID: 3c37e899-41a3-4f88-a54c-25ca52c571a1
:END:
****** 问题
******* 音频
4a13f8d8-372a-40e9-8361-eb1b5c222790.mp3
******* 转录
关于电脑先生的故事，下列哪项正确？
****** 选择
******* A
电脑先生非常会讨好女士
******* B
电脑先生修电脑的技术差
******* C
客户小姐看上了电脑先生
******* D
客户小姐独立生活能力差
****** 答案
C
***** 10
:PROPERTIES:
:ID: 05f2ba23-6031-440d-83d6-c17e68bc57f0
:END:
****** 问题
******* 音频
e4214290-db9e-4785-bd00-a5ccc91dd91d.mp3
******* 转录
关于小说创作，男的看重什么？
****** 选择
******* A
书的真实性
******* B
书的发行量
******* C
书的知名度
******* D
书的影响力
****** 答案
A
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 52a35f4a-ace3-4806-8a47-90780baa1ef6
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
2344edc2-e493-40bb-b897-4f6e7a31ffe6.mp3
***** 转录
到了美国的一个港口，我们准备下船透透风，突然大厨发现码头一根横梁上有几只鸽子蛋，说：“这蛋的母亲也太不负责任了，一阵风不就刮到海里去了？”说着，他小心地把蛋捧在手里，船也不下了，找了些棉花包起来，放在房间里孵着，一天不知要看多少次。终于有一天小鸽子破壳出世了，他高兴得喜形于色，手舞足蹈，见人就拖着去看，为此还特地请了几个人一块儿喝了几杯。
这几个肉乎乎、娇滴滴的小东西也真难为他了。它们不能吃食，大厨就用笨拙的大手扒着嫩嫩的小嘴喂奶粉，那场面真是动人。有时喂不进去，大厨也火，可火过之后还是喂。他常自嘲地说，自己的儿子出世那会儿也没这么伺候过。
**** 题目
***** 11
:PROPERTIES:
:ID: 21583c29-ff2d-49dd-bb44-1fe526f83a8e
:END:
****** 问题
******* 音频
11a536fe-56b4-404f-9b4f-d05575cf499e.mp3
******* 转录
关于鸽子可以知道什么？
****** 选择
******* A
小鸽子被妈妈扔掉了
******* B
大风把鸽子蚯刮跑了
******* C
小鸽子个个都很调皮
******* D
小鸽子是大厨喂大的
****** 答案
D
***** 12
:PROPERTIES:
:ID: 7d401be7-474d-4f0c-b940-372bd8feb8bb
:END:
****** 问题
******* 音频
705ce528-7dab-4970-9c0e-09d336d0201d.mp3
******* 转录
大厨为什么和别人喝酒？
****** 选择
******* A
他捡到几只鸽子
******* B
他朋友特别高兴
******* C
他的鸽子出世了
******* D
那天有舞蹈表演
****** 答案
C
***** 13
:PROPERTIES:
:ID: 0615842d-6746-48fb-8d2b-90b1ef5d46a9
:END:
****** 问题
******* 音频
c6b15bb0-6514-4df3-ae0d-11660007595f.mp3
******* 转录
大厨为什么自嘲？
****** 选择
******* A
他对鸽子太好了
******* B
鸽子不听他的话
******* C
他有些无能为力
******* D
鸽子给他出难题
****** 答案
A
*** 14-17
:PROPERTIES:
:ID: 4531ff68-28fb-4f42-8d1f-4e61d62920a1
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
e29687d1-b5ff-4223-ae4f-0808f63cf3e5.mp3
***** 转录
在日常生活中,存在着大量从自然界得到启发的发明,但大多数人对此却知之甚少。比方说，我们对铁丝网再熟悉不过了,但是你知道它是怎么来的吗?早在1868 年,迈克尔·凯利发现人们放牧的时候,通常使用一种叫作荆棘的扎手的灌木做围栏圈养动物，于是仿照荆棘制造的铁丝网就问世了。
你知道水母吧？早在 5 亿多年前它就已经在海里生活了。人们发现当水母成群结队地游向大海，风暴就要来了。原来，海上风暴来临之前，海浪与空气摩擦会产生 8～13HZ 的次声波，人耳无法听到这种次声波，而水母特殊的听觉系统却可以听到。科学家通过研究，仿照水母的听觉系统，发明了水母耳风暴预测仪。把这种仪器安装在舰船的前甲板上，当接受到风暴的次声波时，可令旋转 360°的喇叭自行停止旋转,它所指的方向，就是风暴前进的方向，指示器上的读数即可告知风暴的强度。这种预测仪能提前 15 小时对风暴做出预报，对航海和渔业的安全具有重要意义。
**** 题目
***** 14
:PROPERTIES:
:ID: e3a4b754-5c43-437e-95d4-1910370e5a96
:END:
****** 问题
******* 音频
82597a42-b211-4cbc-8506-f112837c3888.mp3
******* 转录
关于日常生活中存在的发明，可以知道什么？
****** 选择
******* A
思路来自自然界
******* B
大多数人不清想
******* C
我们都非常熟悉
******* D
出自人类的智慧
****** 答案
A
***** 15
:PROPERTIES:
:ID: 730b7103-a254-4a86-b83c-5c5a74dc3b76
:END:
****** 问题
******* 音频
1039f586-6ef6-4896-a925-b6c6c5b7ec0d.mp3
******* 转录
谁发明了铁丝网？
****** 选择
******* A
工人
******* B
科学家
******* C
放牧人
******* D
迈克尔.凯利
****** 答案
D
***** 16
:PROPERTIES:
:ID: 11fd08c3-e810-4fde-8cd1-db53faee4c85
:END:
****** 问题
******* 音频
a1eb7140-3c04-4a6a-8999-58e3fe2ed0b6.mp3
******* 转录
水母为什么能够预测风暴？
****** 选择
******* A
它生活在海里
******* B
它进化5亿年了
******* C
它能发出次声波
******* D
它有特殊的听觉系统
****** 答案
D
***** 17
:PROPERTIES:
:ID: cc219aec-ee23-435a-b629-2addd91fc75f
:END:
****** 问题
******* 音频
c5897d79-d96f-4b1c-8510-bb00197f75cc.mp3
******* 转录
水母耳风暴预测仪的用途是什么？
****** 选择
******* A
方便人类随时跟踪水母
******* B
可以有效防止风暴发生
******* C
有利于航海和渔业的安全
******* D
为科学家的研究提供根据
****** 答案
C
* 阅读
** 第一部分
*** 18
**** 句子
***** A
任何一个团队的力量都大于任何一个强大的个体。
***** B
我一生中最想做的第一件事是小说家，第二件事是画家。
***** C
神舟九号发射几秒钟以后就在我们的视线中消失得无影无踪了。
***** D
为了生存，狼会主动攻击比自己强大数倍的敌人，为同类创造生机。
**** 答案
*** 19
**** 句子
***** A
我喜欢所有的动物，从爬行的蚂蚁到跳跃的羚羊。
***** B
他今天居然动手干家务活丁，真是太阳从西边出来啦！
***** C
全场观众站了起来，用最激烈的掌声感谢演员们的精彩演出。
***** D
我虽然住的地方比较偏僻，但周边餐馆、公园、购物场所一应俱全。
**** 答案
*** 20
**** 句子
***** A
这个大玩具有3800多个零件，耗时3个月，售价1。75万。
***** B
我们的目标是第三名，要是能获得更好的名次，就是意外的惊腺了。
***** C
在电脑前工作一个小时，要休息10分钟，这样可以有效地保护视力。
***** D
冷空气袭来，山冷得在颤抖，江河也僵硬了，空气也似乎要凝固起来。
**** 答案
** 第二部分
*** 21
**** 段话
运动时[[gap]]机体的新陈代谢较快，[[gap]]流汗过多，汗液中的酸性物质会伤害表层皮肤，使皮肤[[gap]]老化，所以运动过后更应呵护肌肤。
**** 选择
***** A
****** 1
尽管
****** 2
以致
****** 3
过于
***** B
****** 1
由于
****** 2
导致
****** 3
过早
***** C
****** 1
经常
****** 2
势必
****** 3
过度
***** D
****** 1
既然
****** 2
必然
****** 3
本身
**** 答案
*** 22
**** 段话
每到群星灿烂之时，小院的主人或独自[[gap]]星空，或在院中散步，或[[gap]]地望着院中的两棵百年老树，[[gap]]在思忏些什么，或许他在回忆过去，或许他在感悟一种博大精深的人生[[gap]]吧。
**** 选择
***** A
****** 1
关注
****** 2
小心
****** 3
似乎
****** 4
追求
***** B
****** 1
注视
****** 2
专一
****** 3
类似
****** 4
理想
***** C
****** 1
眸仰
****** 2
深奠
****** 3
好像
****** 4
感慨
***** D
****** 1
仰望
****** 2
松果
****** 3
仿佛
****** 4
意义
**** 答案
*** 23
**** 段话
猎豹[[gap]]早睡早起，一般清晨5点半左右起来，然后外出寻食。行走时[[gap]]性很高，常常停下来东张西望。即使午睡时，也[[gap]]约6分钟就坐起来，察看四周的[[gap]]。
**** 选择
***** A
****** 1
通通
****** 2
规律
****** 3
每停
****** 4
信息
***** B
****** 1
惯于
****** 2
自觉
****** 3
每次
****** 4
消息
***** C
****** 1
通常
****** 2
警惕
****** 3
每隔
****** 4
动静
***** D
****** 1
大凡
****** 2
积极
****** 3
每睡
****** 4
风声
**** 答案
** 第三部分
*** 段话
章鱼又称八爪鱼，蚀然叫鱼，它却不属于鱼类，[[gap:24]]。
章鱼种类繁多，身体的大小差别极大，[[gap:25]]，有8条爪。章鱼的爪很有用，可以爬行，可以游泳，可以握持东西。
章鱼约有3500组世上独一无二的基因，其中很多组基因都是负责大脑、爪及隐身能力的。章鱼不仅聪明无比，分散的大脑亦使它们的8条手爪能独立移动。情急时，章鱼可连续六次喷射黑色液体，[[gap:26]]。它有时会变得像一块覆盖着藻类的石头，在猎物完全没有察觉之时窝然扑过去，结果自然是大获全胜。除了伪装术以外，章鱼还会用两足“走路”逃生。
海洋学家还曾观察到章鱼一种不同寻常的捕食方式：太平洋条纹大章鱼在捕食时，[[gap:27]]，伸出一只爪，轻轻地拍了下虾较远一边的肩部，被惊吓到的虾想快速跑到安全地带，没想到正好跑进了章鱼的怀中。[[gap:28]]！
*** 选择
**** A
它的头与躯体分界不明显
**** B
偷偷地跟踪在一只虾的身后
**** C
还能够像变色龙一样改变自身的颜色和构造
**** D
这是怎样充满智慧的诱捕啊
**** E
而是海洋软体动物
*** 答案
**** 24
**** 25
**** 26
**** 27
**** 28
** 第四部分
*** 29-32
**** 段话
达・芬奇在乌类K行的启发下造出第一个飞行器400年之后，人们经过长期反复的实践，终于在1903年发明了飞机，圆了人类飞上天空的梦。之后又经过30年的不断努力，飞机在速度、高度和飞行距离上都超过了乌类，但是在继续研制飞行更快更高的飞机时，设计师碰到了一个更大的难题，就是颤振现象。
当飞机飞行时，飞机的翅膀会发生有害振动，飞行越快，颤振越强烈，甚至会折断翅膀，不少试飞的飞行员因此而丧生。飞机设计师们为此绞尽脑汁，费尽周折，最后终于找到解决这一难题的方法，就是在飞机翅膀前缘的远端上安放一个加重装置，这样就消除了有害振动。
此后人们发现，昆虫早在三亿年以前就飞翔在空中了，它们也同样躲避不掉颤振的危害，只是经过长期的进化，早已成功地获得了防止颤振的方法。生物学家发现蜻蜓每个翅膀前缘的上方都有一块深色的角质加厚区，人们将它称为翅痢或翼眼。如果把翅痢去掉，蜻蜓就会在空中浏来荡去。实验证明正是翅瘙的角质组织消除了蜻蜓飞行时翅膀的颤振危害，这与人类的发明简直有异曲同工之妙。
假如设计师们能够早些发现昆虫翅疤的功用，受益于颤振的解决思路，就可以避免长期的探索和人员的牺牲了。面对蜻蜓翅膀的翅痞，机设计师们抱懋良久。
**** 题目
***** 29
****** 问题
1903年发生了什么事情？
****** 选择
******* A
乌给丁达·芬奇很大启发
******* B
人类造出了第一个飞行器
******* C
人类实现了飞上天空的梦想
******* D
人类瞄准飞机市场做出努力
****** 答案
***** 30
****** 问题
人类在研制飞行更快更高的飞机时，碰到的难题是：
****** 选择
******* A
机冀的有害振动卫
******* B
行速度上不去
******* C
飞行员安全问题
******* D
做不出加重装置
****** 答案
***** 31
****** 问题
和第3段画线词语“异曲同工”意思最相近的是：
****** 选择
******* A
异途同归
******* B
异口同声
******* C
不约而同
******* D
不谋而合
****** 答案
***** 32
****** 问题
通过上文，我们知道什么？
****** 选择
******* A
乌类和明虫比人类更有智慧
******* B
人类在大自然面前非常渺小
******* C
乌帮助人类克服了有害振动
******* D
鸟的飞行给人类提供了启示
****** 答案
*** 33-36
**** 段话
进入6月，又到了登革热高发期。全球每年约有50万人因患重症登革热住院，约2.5％的感染者死亡。没有针对性药物，没有疫苗。伊蚊是登革热的主要传播媒介，包括埃及伊蚊和白纹伊蚊。科研人员正在“创造”一种特种部队，以蚊治蚊。
随着纱布被移开，数百只雄性白纹伊蚊飞出笼子，四散开去。如果顺利的话，它们将在接下来一周里，找到一只只野生雌蚊，在飞舞中、在叶片上，一次次地交配。不过，那些野生雌蚊诞下的虫卵，将等不到发育成蚊的那一刻。原来，这群雄性白纹伊蚊身上带着科研人员专门挑选出的沃尔巴克氏体，与它们交配后，野生雌蚊的卵在胚胎发育早期便直接发生卵死亡。以蚊治蚊，科研人员计划用这种方式，使白纹伊蚊数量锐减。
所谓沃尔巴克氏体，早在1924年便被发现，是一类广泛存在于节肢动物体内、可以经卵垂直传播的胞内共生菌，但将它变成子弹装入枪支，人类却经过了约80年的努力。
除了发现和提取合适的沃尔巴克氏体菌种，掌握显微胜胎注射技术也是这项实验成务的关键。科研人员用小毛笔挑起一颗刚产下不久的白纹伊蚊虫卵，放在载玻片上，置于显微镜下，视觉上将虫卵放大到鸡蛋大小，再用毛细吸管将沃尔巴克氏体注射到卵组胞的包浆中。至此还不能算大功告成，因为胚胎的成活率很低，稍微控制不好，绝大多数卵就会死亡。
确切地讲，人类煞费苦心策划了这场战争，期待自己是真正的赡家一一抵抗登革热。
**** 题目
***** 33
****** 问题
面对登革热，人类正在做什么？
****** 选择
******* A
湘少感染者死亡
******* B
用蚊子消灭蚊子
******* C
干方百计发明药物
******* D
想方设法制作疫苗
****** 答案
***** 34
****** 问题
第2段画线词语“锐减”的意思是：
****** 选择
******* A
急刹减少
******* B
少量减少
******* C
逐渐减少
******* D
稍微减少
****** 答案
***** 35
****** 问题
科研人员放出的鲁子是：
****** 选择
******* A
普通白纹伊蚊
******* B
野生雌性蚊子
******* C
发育成熟的蚊子
******* D
特殊的雄性蚊子
****** 答案
***** 36
****** 问题
“以蚊治鲁”的战争中，技术关键包括：
****** 选择
******* A
发明显微胜胎提取技术
******* B
研制出专用的毛笔和鸡蛋
******* C
制作出沃尔巴克氏体菌种
******* D
保证注射过菌种胚胎的成活率
****** 答案
