* 听力

** 1

*** 1

**** transcript

近日，假冒劣质酱油横行市场，究其原因，酱油的好坏优劣，广大消费者很难辨别，不法分子就利用这一点，不择手段进行非法生产，鱼目混珠，以假充真，坑害消费者。

***** translation

Recently, counterfeit poor-quality soy sauce has been running through the market. The reason. It is very difficult for the majority of consumers to distinguish the good from the bad of soy sauce, and the unscrupulous elements take advantage of this and do whatever they can to produce illegally, mixing fish eyes with pearls, passing off fake as real, and victimizing consumers.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

那年，父亲因病医治无效，与世长辞，他在悲痛之余，除发奋读书外，为奉养母亲，还须觅一份工作。适逢邮局登报招考邮递员，他便报名应试，侥幸被录取。于是他一边工作，一边读书，虽然紧张，却也不觉得苦。

***** translation

In that year, his father passed away after failing to receive medical treatment, and in his grief, he had to find a job to support his mother in addition to studying hard. When the post office advertised for a postal worker, he applied for the job and was lucky enough to be accepted. So he worked and studied at the same time, and although he was nervous, he did not feel any hardship.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

红灶鸟以搭建奇异的“面包烤炉”而著称。所谓“面包烤炉”并不是真正烤面包的，而是红灶鸟所建的椭圆形鸟巢。鸟巢呈红色，坚硬结实，形状像炉子，当地人称它为“面包烤炉”，红灶鸟也因此得名“面包师”。

***** translation

The Red Zodiacs are known for building strange "bread ovens". The so-called "bread oven" is not a real baking oven, but an oval nest built by the Red Zodiac. The nest is red, hard and strong, and shaped like a stove, so the locals call it a "bread baking oven", which gives the bird its name "baker".

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

面试官说他们那儿需要的是高级管理人才，问李辉除了自己的本行外，对其他行业还有什么了解？李辉心中暗想，今天面试八成要砸锅。好在平时常看报纸杂志，对当今经济形势、变化趋势略知一二，于是便想到哪儿说到哪儿。

***** translation

The interviewer said that they need senior management personnel there and asked Li Hui what he knew about other industries in addition to his own line of work. Li Hui thought to himself, "Today's interview is going to be a disaster. The good thing is that usually often read newspapers and magazines, today's economic situation, the trend of change know a little bit, so it will think of where to say to where.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

他是收藏家。然而，他的收藏品并不是在豪宅密室里，而是在名胜古迹之间、青山绿水之畔。瑞士最好的宾馆是他的，纽约曼哈顿也有摩天写字楼归他所有。他的大名是卡尔・海因茨・基普。

***** translation

He is a collector. However, his collection is not in the secret rooms of his mansion, but among the famous places and on the shores of the green mountains. He owns the best hotels in Switzerland and the skyscrapers in Manhattan, New York, and his name is Karl Heinz Kip.

***** QUESTION What are the characters for this black dots in the middle of the line?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-21 Sun 14:03]
:END:

They are described in [[https://lists.w3.org/Archives/Public/public-clreq-admin/2015JulSep/att-0000/index-dual.html][this website]] ([[https://web.archive.org/web/20220821190736/https://lists.w3.org/Archives/Public/public-clreq-admin/2015JulSep/att-0000/index-dual.html][archive]]).

#+begin_quote
Emphasis dots are symbols placed above or beneath characters to emphasize the text, strengthen the tone, or avoid ambiguity. For horizontal writing mode, the emphasis dots are placed under the characters, whereas in vertical writing mode, they are usually placed to the right side of the characters. Both U+25CF BLACK CIRCLE [●] or U+2022 BULLET [•] can work as emphasis dots.
#+end_quote

Note that for the •, the following character also exists ・. This character is different to the one recommended in w3c (as shown above)

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：严老师，“家风”是中国人长久关注的一个话题，今天您能不能在这儿跟我们一起分享一下您的研究成果？
男：好啊。
女：还是请您先给我们说说什么是“家风”。
男：“家风”指一个家庭或家族在长期的生活中，逐步形成的被家庭、家族成员认可，而且共同遵守的生活方式、生活习惯、审美观点、价值取向、精神追求等等方面的总和。
女：那看来，家风对每个家庭成员的影响都是巨大的。
男：对，长期生活在一个特定的家庭，耳濡目染，每个家庭成员必然会不知不觉地受到家风的影响，言行举止，性格气质，必定会带有这个家庭家风的特征，也会自觉不自觉地朝着家庭所希望的方向发展。良好的家风可以使家人朝积极的方向发展，不良的家风会引导家人走上邪路。家风对我们每个人都是一种无言的教育，影响每个家庭成员的心灵，特别是孩子。
女：我们发现，有时候孩子有了问题，家长会责怪孩子、责怪老师，也许家长最应该的是反省一下自己。
男：您说得没错。
女：我想，家风对社会的影响也是不可忽视的。
男：对，因为家庭不是孤立于社会之外的，家庭和社会生活息息相通。家风好，会对良好社会风气的形成发挥积极的作用，家风不好，会给社会风气造成污染。
女：确实如此。
男：古人历来重视家风的培养、建设，把家风的延续看作是很严肃的事情。
女：那古时候家风的传承有什么方式啊？
男：有的家庭靠言传身教，还有的家庭以“家训”的方式形成文字。比如，宋朝史学家司马光就给儿子写过一篇短文，告诉儿子即使生活富裕了，也要节省，还要把节俭的家风传给子孙后代。宋朝政治家包拯把家风视为家族的头等大事。他的家训只有三十七个字，大意是说“后代子孙为官者中，如有因贪污而撤职的人，死后不许埋入祖坟，如违背了我的志向，就不是我的子孙后代。”
女：真是旗帜鲜明啊！

*** 题目

**** 6

***** 问题

以下哪一项是“家风”具有的特点？

**** 7

***** 问题

家风对每个家庭成员的影响是怎样的？

**** 8

***** 问题

家风不好会对家庭成员产生怎样的影响？

**** 9

***** 问题

家风与社会风气之间是什么关系？

**** 10

***** 问题

关于古代家风，下列哪项正确？

