* 听力

** 1

*** 1

**** transcript

近日，假冒劣质酱油横行市场，究其原因，酱油的好坏优劣，广大消费者很难辨别，不法分子就利用这一点，不择手段进行非法生产，鱼目混珠，以假充真，坑害消费者。

***** translation

Recently, counterfeit poor-quality soy sauce has been running through the market. The reason. It is very difficult for the majority of consumers to distinguish the good from the bad of soy sauce, and the unscrupulous elements take advantage of this and do whatever they can to produce illegally, mixing fish eyes with pearls, passing off fake as real, and victimizing consumers.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

那年，父亲因病医治无效，与世长辞，他在悲痛之余，除发奋读书外，为奉养母亲，还须觅一份工作。适逢邮局登报招考邮递员，他便报名应试，侥幸被录取。于是他一边工作，一边读书，虽然紧张，却也不觉得苦。

***** translation

In that year, his father passed away after failing to receive medical treatment, and in his grief, he had to find a job to support his mother in addition to studying hard. When the post office advertised for a postal worker, he applied for the job and was lucky enough to be accepted. So he worked and studied at the same time, and although he was nervous, he did not feel any hardship.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

红灶鸟以搭建奇异的“面包烤炉”而著称。所谓“面包烤炉”并不是真正烤面包的，而是红灶鸟所建的椭圆形鸟巢。鸟巢呈红色，坚硬结实，形状像炉子，当地人称它为“面包烤炉”，红灶鸟也因此得名“面包师”。

***** translation

The Red Zodiacs are known for building strange "bread ovens". The so-called "bread oven" is not a real baking oven, but an oval nest built by the Red Zodiac. The nest is red, hard and strong, and shaped like a stove, so the locals call it a "bread baking oven", which gives the bird its name "baker".

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

面试官说他们那儿需要的是高级管理人才，问李辉除了自己的本行外，对其他行业还有什么了解？李辉心中暗想，今天面试八成要砸锅。好在平时常看报纸杂志，对当今经济形势、变化趋势略知一二，于是便想到哪儿说到哪儿。

***** translation

The interviewer said that they need senior management personnel there and asked Li Hui what he knew about other industries in addition to his own line of work. Li Hui thought to himself, "Today's interview is going to be a disaster. The good thing is that usually often read newspapers and magazines, today's economic situation, the trend of change know a little bit, so it will think of where to say to where.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

他是收藏家。然而，他的收藏品并不是在豪宅密室里，而是在名胜古迹之间、青山绿水之畔。瑞士最好的宾馆是他的，纽约曼哈顿也有摩天写字楼归他所有。他的大名是卡尔・海因茨・基普。

***** translation

He is a collector. However, his collection is not in the secret rooms of his mansion, but among the famous places and on the shores of the green mountains. He owns the best hotels in Switzerland and the skyscrapers in Manhattan, New York, and his name is Karl Heinz Kip.

***** QUESTION What are the characters for this black dots in the middle of the line?
:LOGBOOK:
- State "QUESTION"   from              [2022-08-21 Sun 14:03]
:END:

They are described in [[https://lists.w3.org/Archives/Public/public-clreq-admin/2015JulSep/att-0000/index-dual.html][this website]] ([[https://web.archive.org/web/20220821190736/https://lists.w3.org/Archives/Public/public-clreq-admin/2015JulSep/att-0000/index-dual.html][archive]]).

#+begin_quote
Emphasis dots are symbols placed above or beneath characters to emphasize the text, strengthen the tone, or avoid ambiguity. For horizontal writing mode, the emphasis dots are placed under the characters, whereas in vertical writing mode, they are usually placed to the right side of the characters. Both U+25CF BLACK CIRCLE [●] or U+2022 BULLET [•] can work as emphasis dots.
#+end_quote

Note that for the •, the following character also exists ・. This character is different to the one recommended in w3c (as shown above)

**** alternatives

***** a



***** b



***** c



***** d



**** answer



