* 听力

** 第二部分
:PROPERTIES:
:ID: b3625d04-7dc0-4a00-a44a-08349c22327d
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：严老师，“家风”是中国人长久关注的一个话题，今天您能不能在这儿跟我们一起分享一下您的研究成果？
男：好啊。
女：还是请您先给我们说说什么是“家风”。
男：“家风”指一个家庭或家族在长期的生活中，逐步形成的被家庭、家族成员认可，而且共同遵守的生活方式、生活习惯、审美观点、价值取向、精神追求等等方面的总和。
女：那看来，家风对每个家庭成员的影响都是巨大的。
男：对，长期生活在一个特定的家庭，耳濡目染，每个家庭成员必然会不知不觉地受到家风的影响，言行举止，性格气质，必定会带有这个家庭家风的特征，也会自觉不自觉地朝着家庭所希望的方向发展。良好的家风可以使家人朝积极的方向发展，不良的家风会引导家人走上邪路。家风对我们每个人都是一种无言的教育，影响每个家庭成员的心灵，特别是孩子。
女：我们发现，有时候孩子有了问题，家长会责怪孩子、责怪老师，也许家长最应该的是反省一下自己。
男：您说得没错。
女：我想，家风对社会的影响也是不可忽视的。
男：对，因为家庭不是孤立于社会之外的，家庭和社会生活息息相通。家风好，会对良好社会风气的形成发挥积极的作用，家风不好，会给社会风气造成污染。
女：确实如此。
男：古人历来重视家风的培养、建设，把家风的延续看作是很严肃的事情。
女：那古时候家风的传承有什么方式啊？
男：有的家庭靠言传身教，还有的家庭以“家训”的方式形成文字。比如，宋朝史学家司马光就给儿子写过一篇短文，告诉儿子即使生活富裕了，也要节省，还要把节俭的家风传给子孙后代。宋朝政治家包拯把家风视为家族的头等大事。他的家训只有三十七个字，大意是说“后代子孙为官者中，如有因贪污而撤职的人，死后不许埋入祖坟，如违背了我的志向，就不是我的子孙后代。”
女：真是旗帜鲜明啊！

**** 音频

ee0c14d4-754b-4429-9d56-9bd61dbd23a4.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 32ed6d9c-7a5c-41d1-88d5-1c44a5b1f2f4
:END:

***** 问题

以下哪一项是“家风”具有的特点？

****** 音频

59f3e9b6-da43-4e40-9491-a15a2f06bbeb.mp3

***** 选择

****** A

在一个家族中世代相传

****** B

家庭成员都欣赏的风格

****** C

当时社会峄尚的价值观

****** D

引导社会发展的审美观

***** 答案

A

**** 7
:PROPERTIES:
:ID: 8a68885e-bfe9-402e-bee4-2a18095fc674
:END:

***** 问题

家风对每个家庭成员的影响是怎样的？

****** 音频

67fef549-fc22-4f99-9393-822c94546786.mp3

***** 选择

****** A

有家庭成员感觉不到家风

****** B

有人不想接受家风的影响

****** C

无形中就会受到家风影响

****** D

家风不能影响年轻人的发展

***** 答案

C

**** 8
:PROPERTIES:
:ID: be17f4f5-0d73-42b5-a07a-ec100bed24a9
:END:

***** 问题

家风不好会对家庭成员产生怎样的影响？

****** 音频

a91acf5a-1d2e-43f8-9242-d10503cf6610.mp3

***** 选择

****** A

没有生活目标

****** B

走上错误道路

****** C

没有反思精神

****** D

有问题怪别人

***** 答案

B

**** 9
:PROPERTIES:
:ID: 1a5ab9e9-85a0-4711-941e-6aa8effd39b0
:END:

***** 问题

家风与社会风气之间是什么关系？

****** 音频

0bf3741d-c55d-4d76-92ba-f044b8838929.mp3

***** 选择

****** A

社会风气好会影响家风传承

****** B

家风与社会风气关系不太大

****** C

家风好坏是每个家庭的私事

****** D

家风会影响社会风气的建设

***** 答案

D

**** 10
:PROPERTIES:
:ID: 1b109392-d523-4c0f-a051-3a753329713e
:END:

***** 问题

关于古代家风，下列哪项正确？

****** 音频

29b00dfa-2c3d-4df6-bb79-b45bd41b07bb.mp3

***** 选择

****** A

家家都以文字形式的家训传承

****** B

司马光很有钱却告语后代节俭

****** C

家训中常提到不可助贿赂之风

****** D

宋代包拯把为官不贪作为家训

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

谁也没本事分辨出酱油的好坏

***** B

伪劣酱油进人市场系偶然现象

***** C

造假者以劣质酱油冒充好酱油

***** D

造假者修改了酱油的技术标准

**** 段话

近日，假冒劣质酱油横行市场，究其原因，酱油的好坏优劣，广大消费者很难辨别，不法分子就利用这一点，不择手段进行非法生产，鱼目混珠，以假充真，坑害消费者。

***** 音频

bcf0279b-3132-4b6b-acde-46185ec08dcf.mp3

**** 答案

C

*** 2

**** 选择

***** A

父亲得的是不治之疳

***** B

他一边读书一边工作

***** C

他喜欢邮递员的工作

***** D

他参加了报社的考试

**** 段话

那年，父亲因病医治无效，与世长辞。他在悲痛之余，除发奋读书外，为奉养母亲，还须觅一份工作。适逢邮局登报招考邮递员，他便报名应试，侥幸被录取。于是他一边工作，一边读书，虽然紧张，却也不觉得苦。

***** 音频

9b8cf3f5-50a6-48f3-aacc-234409bec3e1.mp3

**** 答案

B

*** 3

**** 选择

***** A

红灶鸟也被叫作“面包师“

***** B

红灶乌做的面包烤炉很耐用

***** C

红灶鸟住在废弃的面包炉里

***** D

红灶鸟喜欢住在面包房附近

**** 段话

红灶鸟以搭建奇异的“面包烤炉”而著称。所谓“面包烤炉”并不是真正烤面包的，而是红灶鸟所建的椭圆形鸟巢。鸟巢呈红色，坚硬结实，形状像炉子，当地人称它为“面包烤炉”，红灶鸟也因此得名“面包师”。

***** 音频

24c19830-7a12-47a5-9294-ded4961547e7.mp3

**** 答案

A

*** 4

**** 选择

***** A

面试官故意给李辉出难题

***** B

对经济李辉多少算个内行

***** C

李辉估计今天的面试要失败

***** D

面试时李辉想说什么就说什么

**** 段话

面试官说他们那儿需要的是高级管理人才，问李辉除了自己的本行外，对其他行业还有什么了解？李辉心中暗想，今天面试八成要砸锅。好在平时常看报纸杂志，对当今经济形势、变化趋势略知一二，于是便想到哪儿说到哪儿。

***** 音频

243d7051-930d-4ff3-93d8-d91a1eef0bd1.mp3

**** 答案

C

*** 5

**** 选择

***** A

基普非常喜欢旅游

***** B

基普的住所很豪华

***** C

基晏“收藏“建筑

***** D

基普的办公室在纽约

**** 段话

他是收藏家。然而，他的收藏品并不是在豪宅密室里，而是在名胜古迹之间、青山绿水之畔。瑞士最好的宾馆是他的，纽约曼哈顿也有摩天写字楼归他所有。他的大名是卡尔·海因茨·基普。

***** 音频

3cd2a0a9-9945-4026-aafa-27ad864a1a28.mp3

**** 答案

C

