* 听力

** 第二部分
:PROPERTIES:
:ID: 01168e4c-52d2-46ed-bcdf-b9d80d8881b0
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

*** 对话

女：各位网友大家好。今天来到现场的是我们的同龄人丁然，他将跟我们聊聊他的职场经历。他在一家公司工作，到这家公司之前，他跳槽 5 次，换过 6家公司。他从来没见过一家公司像现在这家这么穷，也没见过一家公司有这么多笑声。当初他毅然落脚在这家公司，就是对那么多同事为什么能悠然自得地待在这家有欠薪记录的公司里十分纳闷，没想到的是，现在他也成了他们中的一员。丁然，能不能给我们介绍一下你们公司？
男：这家公司算上老总和他的助理共 24 个人。没有司机，没有清洁工，没有自己的保安。偶尔会开不出支，但最迟三两个月就能补上，绝不少发。就是这么一家亏损的小企业，员工却十分稳定，三年来只有两个人离职。
女：哦，企业日子过得也很节省吧？
男：是啊。为了省钱，办公用纸要双面使用，之后会收集起来卖废品；圆珠笔没水了，就去办公室更换笔芯。
女：好多公司都有集体活动，什么卡拉 OK、自助餐，甚至出国旅行，你们有吗？
男：只有一次，老总决定带大家去植物园踏青，说是健康又环保，关键是省钱，植物园门票便宜。就这，老总还千叮咛万嘱咐，别买他的票，他自己有公园年票。
女：你们公司除了穷，还有什么特殊之处啊？
男：公司虽然穷，但业务应酬不少，时不时就能收到客户送来的各式礼物：水果、月饼、洗发水、饮料之类的。无论收到什么，通常的做法就是充公。于是我们每人的桌子上就会有几个水果、两瓶饮料，要是有了月饼，嘿嘿，那就得看谁眼疾手快了。
女：嗯，单位气氛好，老总还真没架子哈。
男：记得有一次我生病，副总和同事一个月来了三次，买的补品和水果价钱不高，却全都对症适用。他们都是细心温暖的人。
女：这样的工作环境，确实会让人心情愉快。
男：其实心情是小事，关键是我认准了，一个内心积极温暖的人，一定会有光明美好的前途，所以我看好我们的公司。

**** 音频

aefd05c2-0258-4590-82bd-3fd1f2af254e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: a99aaad5-d0c7-4ebe-99d0-23ae587e4b0f
:END:

***** 问题

关于男的的职场经历，下列哪项正确？

****** 音频

cde330ac-3943-4bd1-9a4d-79f0e231cd40.mp3

***** 选择

****** A

他讨厌工作不严肃

****** B

他炒过公司的鱿鱼

****** C

公司效益不好他就走

****** D

收人没有保障他不干

***** 答案

B

**** 7
:PROPERTIES:
:ID: 109423bc-f6dc-4295-9ba4-ad91bd1dce39
:END:

***** 问题

最初男的为什么选择了现在这家公司？

****** 音频

9c29648f-2036-4231-93cf-a8fc8c7ced53.mp3

***** 选择

****** A

他很受重用

****** B

领导很明智

****** C

好奇心驱使

****** D

职位非常好

***** 答案

C

**** 8
:PROPERTIES:
:ID: a36d825c-0259-48e8-9fa3-33349c4c3b86
:END:

***** 问题

关于这家公司，下列哪项正确？

****** 音频

78208904-6562-46a8-b0b5-e5a5bdf23a41.mp3

***** 选择

****** A

偶尔会迟发工资

****** B

做废品回收业务

****** C

社会责任感很强

****** D

常组织集体活动

***** 答案

A

**** 9
:PROPERTIES:
:ID: 70226265-7484-4384-aeac-f5f4d3699e96
:END:

***** 问题

生病的经历让他有了怎样的感触？

****** 音频

33c5bba0-5455-450d-ad34-383aaeedc5bb.mp3

***** 选择

****** A

同事很会买水果

****** B

领导同事很体贴

****** C

公司确实手头紧

****** D

谁都渺望被关心

***** 答案

B

**** 10
:PROPERTIES:
:ID: b6359e3c-4f3c-4b87-b863-f98fa9f17ca3
:END:

***** 问题

男的看好这家公司的理由是什么？

****** 音频

baee7399-4caa-4aee-843a-9f29e5a749cf.mp3

***** 选择

****** A

同事之间的友情

****** B

讨人喜欢的领导

****** C

轻松友好的氛围

****** D

光明美好的前途

***** 答案

D

** 第一部分

*** 1
:PROPERTIES:
:ID: 216dccb2-fe8d-41a0-b825-d507bec932f0
:END:

**** 选择

***** A

贫穷地区需要更多扶助

***** B

要系统地帮助农村脱贫

***** C

必须关心农村工程建设

***** D

农村要建设得更有特色

**** 段话

改变农村落后面貌，建设小康村是一项系统工程，各级干部必须全身心地投入，全方位地服务，不仅要为条件好的村“锦上添花”，更要为基础差的村“雪中送炭”。

***** 音频

ed7e08c4-e5df-404a-8934-10e7cf6e7aa7.mp3

**** 答案

A

*** 2
:PROPERTIES:
:ID: 376e93e2-fd98-45dd-9199-05ae1af2c757
:END:

**** 选择

***** A

四书五经是一本书

***** B

2010年没人再看四书五经了

***** C

不少人不能把四书五经名字说全

***** D

北京很多出版社都想出版四书五经

**** 段话

2010 年，北京某出版社为了策划“四书五经精选”系列图书，设计了一个采访题目：“中国人你知道四书五经具体是哪些书吗？”采访一天以后，他们发现被采访的人中十之六七不能全部说出来。

***** 音频

2e5e6616-ff54-4e69-bb44-41bbf8be54f8.mp3

**** 答案

C

*** 3
:PROPERTIES:
:ID: bd26ceb0-cf7a-4932-a774-3003c2a41fb5
:END:

**** 选择

***** A

人的“特长“不是培养出来的

***** B

每个人都盼望做自己喜欢的工作

***** C

每个学生至少能在一方面施展才华

***** D

老师要因材施教，对学生加以引导

**** 段话

青少年都有自己的兴趣爱好，这些兴趣和爱好若能及早得到培养，就能形成特长。老师根据学生的爱好，有意识地加以引导，学生就可能在自己爱好的领域施展才华、发展特长。

***** 音频

685f9f9f-0b1c-4d2b-9851-32de09161632.mp3

**** 答案

D

*** 4
:PROPERTIES:
:ID: 673b1f13-e7c7-4b1b-9120-b59a54d2281c
:END:

**** 选择

***** A

人类离开动物不能生活

***** B

动物是人类的精神支柱

***** C

动物和人具有平等的权利

***** D

人类没有平等地对待动物

**** 段话

从人类诞生的那一刻起，动物就成为人类密不可分的伴侣。在人类寂寞而漫长的进化行程中，动物像忠实的朋友一样始终陪伴左右，然而，作为和人一样有生命有感觉的存在，它们却一直被排除在人类的伦理视野之外。

***** 音频

007cab08-3f1e-48e1-aca2-49ccb3e9d11c.mp3

**** 答案

D

*** 5
:PROPERTIES:
:ID: 58842e39-c862-4bef-9560-da0dd75baada
:END:

**** 选择

***** A

气候异常必然导致温室效应

***** B

二氧化碳疑聚后变成玻璃暑

***** C

温室效应的产生与燃煤有关

***** D

气候变化的趋势是温室效应

**** 段话

燃煤会产生二氧化碳和二氧化硫，二氧化碳积聚在地面，会像玻璃罩一样，阻断地面热量向空中散发，使地球表面温度升高，形成“温室效应”。“温室效应”会使全球气候异常，引发干旱或洪涝，还会使冰山融化，海平面升高，海拔较低的国家或岛屿就会被淹没。

***** 音频

3a18532a-6cc3-4484-bf59-f04c240f29de.mp3

**** 答案

C

** 第三部分

*** 11-13
:PROPERTIES:
:ID: 512a3cb6-081b-4d94-814d-e9b49d92c8da
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

**** 课文

自世界上第一辆自行车问世至今已有 200 多年的历史了。

18 世纪末，法国人发明了最早的自行车。它是木制的，结构比较简单，不能转向，骑车人用双脚用力蹬地前行，改变方向时也只能下车搬动车子。即使这样，当发明人骑着这辆自行车出现在公众面前时，在场的人仍十分惊异。

世界上第一批真正实用的自行车出现于 19 世纪初。1817 年，德国人在法国巴黎发明了带车把的木制两轮自行车，它最大的进步是可以改变方向了，它一问世便引起了人们极大的兴趣，之后不仅有成百上千辆自行车涌上了街头，法国政府还为邮差配备了自行车作为交通工具。

随后，自行车的技术、性能不断得到改进。1839 年，英国人发明了蹬踏式脚蹬驱动自行车，骑车时两脚不用蹬地，并提高了行驶速度。1869 年诞生的雷诺型自行车，车架改由钢管制作，车轮也改为钢圈和辐条，采用实心轮胎，自行车更加轻便了。1887 年，英国人劳森完成了链条驱动自行车的设计。同年，英国人研制出了充气轮胎。从此，自行车技术开始走向商业化，实现批量生产并投入市场。

***** 音频

bb36243a-8df4-4aa7-a904-3dd5fbb88195.mp3

**** 题目

***** 11
:PROPERTIES:
:ID: 45246170-29e7-40ca-ad6b-b57ca154ce60
:END:

****** 选择

******* A

赞叹

******* B

吃惊

******* C

无所谓

******* D

感兴趣

****** 问题

世界上最早的自行车出现在街头时，人们是什么态度？

******* 音频

0d81af6a-78ce-418b-a6ec-5c6b49db11fa.mp3

****** 答案

B

***** 12
:PROPERTIES:
:ID: ed03146d-6f2c-4e06-ab6e-ef4c0fae38b5
:END:

****** 选择

******* A

法国人

******* B

德国人

******* C

英国人

******* D

中国人

****** 问题

哪国人发明了自行车？

******* 音频

f9303640-526d-4ce2-8290-c6d7e01123c9.mp3

****** 答案

A

***** 13
:PROPERTIES:
:ID: b8682fd9-6be4-4549-932a-479f9a005c26
:END:

****** 选择

******* A

材料

******* B

用途

******* C

营销方式

******* D

市场开发

****** 问题

英国人在哪方面对自行车的发展做出了贡献？

******* 音频

5615f81c-c367-4ddf-ac9d-fbf8f3d98369.mp3

****** 答案

A

*** 14-17
:PROPERTIES:
:ID: c3b8eed0-2ffd-4d3a-a986-e79ae455570d
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:

**** 课文

你想知道我设计的未来汽车什么样吗？让我来告诉你吧！

这款汽车是水、陆、空三用车。它不用汽油，而是以太阳能做燃料，当然它也不排放有害气体。形容它的速度，“奔驰”“驰骋”这样的词汇都用不上了，它的速度和光的速度差不多。这种汽车没有方向盘，只有一块超薄屏幕，显示着你所在的方位、本地区的交通要道和世界各地的地图。当然 GPS 导航系统是必不可少的，只要你说出自己想去的地方，汽车就会把你送到目的地。

这款车在行驶过程中能自动调节车速以及车内温度和光线，前方出现阻碍，它会自动避开，因此在陆地上行驶它安全可靠。下雪天，汽车会伸出两根滑板，这样在雪地里它也是来去自如。

在空中飞行时，它平稳无噪声，就像坐在自家的沙发上一样，对了，它还能够像直升飞机一样升降。

在水面上行驶时，车的轮胎会自动变大，浮力也随之变大，速度可达每小时5000 海里。想拥有一辆这样的车吗？这并不难，我发明的这款车物美价廉，人人都买得起。

***** 音频

f7d15ed4-e9fb-4cd2-8955-8d62dbe18f4d.mp3

**** 题目

***** 14
:PROPERTIES:
:ID: 1fa3313e-ed2f-4a51-bd93-ed5b56a2420f
:END:

****** 选择

******* A

汽油

******* B

空气

******* C

太阳能

******* D

有害气体

****** 问题

这款未来汽车的燃料是什么？

******* 音频

c6e3cc79-5635-46fa-974e-f6d581ab0615.mp3

****** 答案

C

***** 15
:PROPERTIES:
:ID: 109397df-0003-4946-a61a-e693cee952a0
:END:

****** 选择

******* A

跟鸟飞得一样快

******* B

和光的速度不相上下

******* C

跟“奔驰“汽车的速度一样

******* D

和声音在空中传播的速度相当

****** 问题

这款未来汽车的速度怎样？

******* 音频

ba7a87b4-4f4f-46bd-840b-effc87b7bbe4.mp3

****** 答案

B

***** 16
:PROPERTIES:
:ID: 32a314a8-2461-4a80-94f9-164ace01d2d8
:END:

****** 选择

******* A

不再需要GPS导航系统

******* B

汽车座椅是宽大的沙发

******* C

能够在平坦的冰面上滑行

******* D

在水面上行驶速度也很快

****** 问题

这款未来汽车还有什么优点？

******* 音频

d09b01e6-b7f9-4219-ac05-19b09c7eda75.mp3

****** 答案

D

***** 17
:PROPERTIES:
:ID: b359480e-5711-46a7-829f-637a470e7693
:END:

****** 选择

******* A

这款车价格昂贵

******* B

这款车已经大量生产

******* C

这款车是说话人心中的理想

******* D

这款车可以在陆地、空中、水下使用

****** 问题

根据这段话，可以知道什么？

******* 音频

e4d773c7-951c-4e16-a1a5-903e24dc7d05.mp3

****** 答案

C

