* 听力

** 1

*** 1

**** transcript

改变农村落后面貌，建设小康村是一项系统工程，各级干部必须全身心地投入，全方位地服务，不仅要为条件好的村“锦上添花”，更要为基础差的村“雪中送炭”。

***** translation

Changing the backward appearance of rural areas and building well-off villages is a systematic project, and cadres at all levels must devote themselves to all-round services, not only to "add flowers" for villages with good conditions, but also to "send charcoal in snow" for villages with poor foundation.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

2010年，北京某出版社为了策划“四书五经精选”系列图书，设计了一个采访题目：“中国人你知道四书五经具体是哪些书吗？”采访一天以后，他们发现被采访的人中十之六七不能全部说出来。

***** translation

In 2010, a publisher in Beijing designed an interview for the "Four Books and Five Classics" book series: "Do Chinese people know which books are the Four Books and Five Classics?" After a day of interviewing, they found that sixty-seven out of ten people interviewed could not tell us all of them.

***** TODO Read these books
:LOGBOOK:
- State "TODO"       from              [2022-08-21 Sun 09:15]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

青少年都有自己的兴趣爱好，这些兴趣和爱好若能及早得到培养，就能形成特长。老师根据学生的爱好，有意识地加以引导，学生就可能在自己爱好的领域施展才华、发展特长。

***** translation

All young people have their own interests and hobbies, and if these interests and hobbies can be cultivated, they can become specialties. If teachers consciously guide students according to their hobbies, students may develop their talents and strengths in their own hobbies.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

从人类诞生的那一刻起，动物就成为人类密不可分的伴侣。在人类寂寞而漫长的进化行程中，动物像忠实的朋友一样始终陪伴左右，然而，作为和人一样有生命有感觉的存在，它们却一直被排除在人类的伦理视野之外。

***** translation

From the moment of human birth, animals have been inseparable companions of human beings. During the long and lonely journey of human beings, animals have always been with us like loyal friends, but as living and feeling beings like humans, they have always been excluded from the ethical vision of human beings.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

燃煤会产生二氧化碳和二氧化硫，二氧化碳积聚在地面，会像玻璃罩一样，阻断地面热量向空中散发，使地球表面温度升高，形成“温室效应”。“温室效应”会使全球气候异常，引发干旱或洪涝，还会使冰山融化，海平面升高，海拔较低的国家或岛屿就会被淹没。

***** translation

Burning coal produces carbon dioxide and sulfur dioxide, which accumulate on the ground and act as a glass cover to block heat from the ground to the air, raising the earth's surface temperature and creating the "greenhouse effect. The "greenhouse effect" will cause global climate anomalies, leading to droughts or floods, as well as the melting of icebergs, rising sea levels, and the inundation of countries or islands at lower elevations.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 01168e4c-52d2-46ed-bcdf-b9d80d8881b0
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：各位网友大家好。今天来到现场的是我们的同龄人丁然，他将跟我们聊聊他的职场经历。他在一家公司工作，到这家公司之前，他跳槽 5 次，换过 6家公司。他从来没见过一家公司像现在这家这么穷，也没见过一家公司有这么多笑声。当初他毅然落脚在这家公司，就是对那么多同事为什么能悠然自得地待在这家有欠薪记录的公司里十分纳闷，没想到的是，现在他也成了他们中的一员。丁然，能不能给我们介绍一下你们公司？
男：这家公司算上老总和他的助理共 24 个人。没有司机，没有清洁工，没有自己的保安。偶尔会开不出支，但最迟三两个月就能补上，绝不少发。就是这么一家亏损的小企业，员工却十分稳定，三年来只有两个人离职。
女：哦，企业日子过得也很节省吧？
男：是啊。为了省钱，办公用纸要双面使用，之后会收集起来卖废品；圆珠笔没水了，就去办公室更换笔芯。
女：好多公司都有集体活动，什么卡拉 OK、自助餐，甚至出国旅行，你们有吗？
男：只有一次，老总决定带大家去植物园踏青，说是健康又环保，关键是省钱，植物园门票便宜。就这，老总还千叮咛万嘱咐，别买他的票，他自己有公园年票。
女：你们公司除了穷，还有什么特殊之处啊？
男：公司虽然穷，但业务应酬不少，时不时就能收到客户送来的各式礼物：水果、月饼、洗发水、饮料之类的。无论收到什么，通常的做法就是充公。于是我们每人的桌子上就会有几个水果、两瓶饮料，要是有了月饼，嘿嘿，那就得看谁眼疾手快了。
女：嗯，单位气氛好，老总还真没架子哈。
男：记得有一次我生病，副总和同事一个月来了三次，买的补品和水果价钱不高，却全都对症适用。他们都是细心温暖的人。
女：这样的工作环境，确实会让人心情愉快。
男：其实心情是小事，关键是我认准了，一个内心积极温暖的人，一定会有光明美好的前途，所以我看好我们的公司。

**** 音频

aefd05c2-0258-4590-82bd-3fd1f2af254e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: a99aaad5-d0c7-4ebe-99d0-23ae587e4b0f
:END:

***** 问题

关于男的的职场经历，下列哪项正确？

****** 音频

cde330ac-3943-4bd1-9a4d-79f0e231cd40.mp3

***** 选择

****** A

他讨厌工作不严肃

****** B

他炒过公司的鱿鱼

****** C

公司效益不好他就走

****** D

收人没有保障他不干

***** 答案

B

**** 7
:PROPERTIES:
:ID: 109423bc-f6dc-4295-9ba4-ad91bd1dce39
:END:

***** 问题

最初男的为什么选择了现在这家公司？

****** 音频

9c29648f-2036-4231-93cf-a8fc8c7ced53.mp3

***** 选择

****** A

他很受重用

****** B

领导很明智

****** C

好奇心驱使

****** D

职位非常好

***** 答案

C

**** 8
:PROPERTIES:
:ID: a36d825c-0259-48e8-9fa3-33349c4c3b86
:END:

***** 问题

关于这家公司，下列哪项正确？

****** 音频

78208904-6562-46a8-b0b5-e5a5bdf23a41.mp3

***** 选择

****** A

偶尔会迟发工资

****** B

做废品回收业务

****** C

社会责任感很强

****** D

常组织集体活动

***** 答案

A

**** 9
:PROPERTIES:
:ID: 70226265-7484-4384-aeac-f5f4d3699e96
:END:

***** 问题

生病的经历让他有了怎样的感触？

****** 音频

33c5bba0-5455-450d-ad34-383aaeedc5bb.mp3

***** 选择

****** A

同事很会买水果

****** B

领导同事很体贴

****** C

公司确实手头紧

****** D

谁都渺望被关心

***** 答案

B

**** 10
:PROPERTIES:
:ID: b6359e3c-4f3c-4b87-b863-f98fa9f17ca3
:END:

***** 问题

男的看好这家公司的理由是什么？

****** 音频

baee7399-4caa-4aee-843a-9f29e5a749cf.mp3

***** 选择

****** A

同事之间的友情

****** B

讨人喜欢的领导

****** C

轻松友好的氛围

****** D

光明美好的前途

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

贫穷地区需要更多扶助

***** B

要系统地帮助农村脱贫

***** C

必须关心农村工程建设

***** D

农村要建设得更有特色

**** 段话

改变农村落后面貌，建设小康村是一项系统工程，各级干部必须全身心地投入，全方位地服务，不仅要为条件好的村“锦上添花”，更要为基础差的村“雪中送炭”。

**** 答案

A

*** 2

**** 选择

***** A

四书五经是一本书

***** B

2010年没人再看四书五经了

***** C

不少人不能把四书五经名字说全

***** D

北京很多出版社都想出版四书五经

**** 段话

2010 年，北京某出版社为了策划“四书五经精选”系列图书，设计了一个采访题目：“中国人你知道四书五经具体是哪些书吗？”采访一天以后，他们发现被采访的人中十之六七不能全部说出来。

**** 答案

C

*** 3

**** 选择

***** A

人的“特长“不是培养出来的

***** B

每个人都盼望做自己喜欢的工作

***** C

每个学生至少能在一方面施展才华

***** D

老师要因材施教，对学生加以引导

**** 段话

青少年都有自己的兴趣爱好，这些兴趣和爱好若能及早得到培养，就能形成特长。老师根据学生的爱好，有意识地加以引导，学生就可能在自己爱好的领域施展才华、发展特长。

**** 答案

D

*** 4

**** 选择

***** A

人类离开动物不能生活

***** B

动物是人类的精神支柱

***** C

动物和人具有平等的权利

***** D

人类没有平等地对待动物

**** 段话

从人类诞生的那一刻起，动物就成为人类密不可分的伴侣。在人类寂寞而漫长的进化行程中，动物像忠实的朋友一样始终陪伴左右，然而，作为和人一样有生命有感觉的存在，它们却一直被排除在人类的伦理视野之外。

**** 答案

D

*** 5

**** 选择

***** A

气候异常必然导致温室效应

***** B

二氧化碳疑聚后变成玻璃暑

***** C

温室效应的产生与燃煤有关

***** D

气候变化的趋势是温室效应

**** 段话

燃煤会产生二氧化碳和二氧化硫，二氧化碳积聚在地面，会像玻璃罩一样，阻断地面热量向空中散发，使地球表面温度升高，形成“温室效应”。“温室效应”会使全球气候异常，引发干旱或洪涝，还会使冰山融化，海平面升高，海拔较低的国家或岛屿就会被淹没。

**** 答案

C

