* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: a912514b-7e0b-49a5-a0a0-be9f0b24f902
:END:
**** 对话
***** 转录
女：老师，我们孩子平时很爱看书，为什么作文还是写不好？[[file:d5992c9b-0ad8-4e0f-9e95-bdba606af8e2.mp3][(audio)]]
男：认为只要多读书就能把作文写好，这个观点是不全面的。[[file:13ade76f-50a2-4071-bbdd-3e6377f56b83.mp3][(audio)]]
***** 音频
75b7fbdf-8e80-43f8-a07b-f479e7ca0c78.mp3
**** 问题
***** 转录
老师的看法是什么？
***** 音频
7e15bd18-9f49-486f-83f4-cd8eb808cf68.mp3
**** 选择
***** A
要多读书
***** B
要多练习写作
***** C
多读书就能写好作文
***** D
多读书不一定能写好作文
**** 答案
D
*** 2
:PROPERTIES:
:ID: 0631c905-50a8-4bc2-84fc-1b276fea5ee0
:END:
**** 对话
***** 转录
男：网上报名的资料，你得仔细看看。要知道，一旦提交，就不能更改了。[[file:1ca6965a-2e15-4253-8435-fac781ac7994.mp3][(audio)]]
女：放心吧，我看了好几遍了。[[file:c9cd8308-3bff-4c96-a6f3-3deddc882abd.mp3][(audio)]]
***** 音频
d1919978-5175-4d5b-80da-5dbb97f248f7.mp3
**** 问题
***** 转录
男的为什么让女的多看看资料？
***** 音频
d39e5fd1-87bc-4dcc-bc91-532a3d641da4.mp3
**** 选择
***** A
这些资料很重要
***** B
报名后就不能改
***** C
女的不太仔细
***** D
男的还没看过
**** 答案
B
*** 3
:PROPERTIES:
:ID: 28e33e56-c6bb-42c4-8071-ff96b53f82fa
:END:
**** 对话
***** 转录
女：儿子，你的毕业论文写得怎么样了？[[file:145249f9-70ae-40cb-aa97-f4f0d102014f.mp3][(audio)]]
男：论文好说，我已经找了资料，写了一大部分，再修改修改就差不多完了。[[file:6c0f98ea-5894-4e99-9dbc-f6f57d8eafab.mp3][(audio)]]
***** 音频
ca16d526-c2d4-4ff0-8ffe-d045e9e3679f.mp3
**** 问题
***** 转录
男的的论文现在是什么情况？
***** 音频
a3fb7f8e-cc41-49c9-be9e-59916565720d.mp3
**** 选择
***** A
正在想题目
***** B
还没找资料
***** C
写了一部分
***** D
已经写完了
**** 答案
C
*** 4
:PROPERTIES:
:ID: 4e8e68b8-9b35-4280-87b2-3409b400b72e
:END:
**** 对话
***** 转录
男：你不是不喜欢儿子找的那个女孩儿吗？[[file:53c25e3e-6918-4af9-9a68-13d92c03fd02.mp3][(audio)]]
女：孩子大了，有自己的主张了，我有什么办法？[[file:41333752-5aaa-4129-8a27-96dd5d967af6.mp3][(audio)]]
***** 音频
6d5927d0-98d9-4cf3-9b26-1b506754233c.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
d0839483-de1c-4a71-a746-62f3bf2d78c9.mp3
**** 选择
***** A
无奈
***** B
疼爱
***** C
高兴
***** D
后悔
**** 答案
A
*** 5
:PROPERTIES:
:ID: 90c090c8-903e-4c4d-8700-bd35511b0529
:END:
**** 对话
***** 转录
女：这计划我都做了四次了，还是觉得不满意。[[file:d0839483-de1c-4a71-a746-62f3bf2d78c9.mp3][(audio)]]
男：没有真正完美的计划，先干着吧。[[file:8d6df30d-fffc-4edf-8927-ff7b9ac838ff.mp3][(audio)]]
***** 音频
0e2bc27c-3bbd-445f-be4a-1faf80c89b4a.mp3
**** 问题
***** 转录
男的对这个计划有什么看法？
***** 音频
5f413ea2-8854-4126-88b3-481a8b73bd0b.mp3
**** 选择
***** A
也不满意
***** B
应该放弃
***** C
可以先试试
***** D
继续做新的
**** 答案
C
*** 6
:PROPERTIES:
:ID: df99d9e9-f39b-40e6-b24b-53982859212f
:END:
**** 对话
***** 转录
男：这本书的主题是你感兴趣的吧？[[file:836b3610-3c2c-4af0-9fd2-d4243a5c5cdc.mp3][(audio)]]
女：对，但是我翻了翻目录，觉得没什么意思，还不如去看几篇论文。[[file:8533a6f7-5049-4274-b5e9-e511333bd39b.mp3][(audio)]]
***** 音频
a5c141fc-2c60-4590-aca7-2be25c9733dd.mp3
**** 问题
***** 转录
他们在谈论什么？
***** 音频
30d36ad3-9360-4f92-b944-8a9e67217096.mp3
**** 选择
***** A
书
***** B
主题
***** C
目录
***** D
论文
**** 答案
A
** 第二部分
*** 7
**** 对话
***** 转录
女：对不起，小说不在这儿，你可以去二层借。
男：二层借书处的老师告诉我，新书都在一层的阅览室。
女：哦，一层有两个阅览室，我们这边只有理科方面的书，文科的在那一头。
男：好的，谢谢。
***** 音频
cb36ff8c-f7db-4607-8673-0997d9036bda.mp3
**** 问题
***** 转录
说话人现在在哪儿？
***** 音频
95a55bc6-8edb-4e37-9c00-edb29a21d3d6.mp3
**** 选择
***** A
书店
***** B
借书处
***** C
理科阅览室
***** D
文科阅览室
**** 答案
C
*** 8
**** 对话
***** 转录
男：你这次考试怎么考得这么差？是不是考前没复习，还是身体不好？
女：都不是，我就是考试时太紧张了。
男：是吗？考试时紧张是难免的，但没想到影响会这么大。
女：我下次想办法调整。
***** 音频
f7d3d784-a642-4c44-9f56-fc4954b8a0d1.mp3
**** 问题
***** 转录
女的为什么没考好？
***** 音频
93568e05-acf2-49c0-8427-1cd85978eb10.mp3
**** 选择
***** A
没复习
***** B
太紧张
***** C
身体不好
***** D
考试时间调整了
**** 答案
B
*** 9
**** 对话
***** 转录
女：这次的事情你做得太过分了！
男：你先听我解释，我这么做是有原因的。
女：你最好给我一个好的理由。
男：当然，你别急，听我慢慢说……
***** 音频
7bffe38d-c6a4-4193-88cc-f57881b10a01.mp3
**** 问题
***** 转录
女的是什么语气？
***** 音频
6af9f054-55db-4c7f-911b-06763a3e81de.mp3
**** 选择
***** A
生气
***** B
伟念
***** C
痛苦
***** D
疹爱
**** 答案
A
*** 10
**** 对话
***** 转录
男：你觉得灰姑娘进入王宫以后，应该怎么对待她的继母？
女：一个已经拥有巨大幸福的人，应该原谅和理解别人。
男：但是继母毕竟伤害过她啊？
女：虽然继母很自私，但作为一个母亲，在自己的亲生女儿和继女之间，很难做到完全的平等，这也是人的天性。
***** 音频
039c20e8-ba60-4fcb-80c1-786c64cb5694.mp3
**** 问题
***** 转录
对于灰姑娘的继母，女的有什么看法？
***** 音频
0fb1e054-f6c7-45c6-be4a-75caed83af1f.mp3
**** 选择
***** A
不可原谅
***** B
难以相处
***** C
可以理解
***** D
过于自私
**** 答案
C
*** 11-12
**** 对话
***** 转录
法国作家杜马在俄国旅行时,来到一个城市,决定参观城里最大的书店。书店老板听说作家要来,便把所有书架都摆上了杜马的书,想让他高兴。杜马走进书店，发现书架上全是自己的著作，非常吃惊。他问道：“别人的书呢？”老板对这个问题完全没有思想准备，于是紧张地回答：“别人的书，都……都卖完了。”
***** 音频
eaade725-9275-409a-977e-4d72c88bb186.mp3
**** 题目
***** 11
****** 问题
******* 转录
书店里为什么没有别人的书？
******* 音频
2321d3d5-f55f-4eb9-816d-fff8bae6e4ec.mp3
****** 选择
******* A
老板特意安排的
******* B
别人的书都卖完了
******* C
书店是作家自己开的
******* D
老板特别喜欢这位作家
****** 答案
A
***** 12
****** 问题
******* 转录
这个故事想告诉我们什么？
******* 音频
6b5fca56-1513-4cca-ac82-9c7945f6c1a6.mp3
****** 选择
******* A
老板好心办了坏事
******* B
这位作家的水平很差
******* C
老板想讽刺这位作家
******* D
法国作家在俄国不受欢迎
****** 答案
A
*** 13-14
**** 段话
***** 转录
据说有位大作家，写作时有个古怪的习惯——他写文章从来不坐着。有人问他原因，他说：“坐着太舒服，这样，文章一写起来就没完没了。站久了容易腿疼，这样，你就想快点儿写完，快点儿坐下。”这个故事可能只是个玩笑，文章的长短与坐着写还是站着写当然没有太大关系，但是，它却让我们思考一个问题：如果我们都像他一样站着写作，是不是文章都会更简短、更有可读性呢？
***** 音频
6abefd0e-e33f-4c9a-b3e6-2e2d3ecde788.mp3
**** 题目
***** 13
****** 问题
******* 转录
这位作家为什么要站着写文章？
******* 音频
91e0b25d-a921-4971-8513-292d1d84623a.mp3
****** 选择
******* A
他家没有椅子
******* B
他想写得简短
******* C
他坐久了腹疣
******* D
他想锻炼身体
****** 答案
B
***** 14
****** 问题
******* 转录
对于文章的长短，说话人是什么态度？
******* 音频
8249f9d5-6b5f-4fed-b27c-e73c0f0c615d.mp3
****** 选择
******* A
长短不重要
******* B
应该长一点儿
******* C
应该短一点儿
******* D
没有明确说
****** 答案
C
* 阅读
** 第一部分
*** 段话
各持己见往往是人与人之间矛盾冲突的重要原因。人们在生活中[[gap][15]]会与家人、朋友、同事、同学或者领导产生这样那样的矛盾。这些矛盾会使人伤心气愤。如果矛盾双方都各持己见，互不相让，可能还会导致过激的言行，使人际关系恶化，而这是非常有害于心理健康和办事结果的。要避免这种情况出现，需要心理换位一一[[gap][16]]位置，试着站到对方立场上去思考，你就会发现其实对方的[[gap][17]]“也不无道理。比如，我的父母总是对我提出各种口样的过高要求：学习上要努力，工作上要出色，生活上要俭朴勤快，最好所有家务都能干…。。。我烦死了，有时候[[gap][18]]。但是从父母的角度想一想，他们也是为我好，假如有一天我自己做了父母，我肯定也会对自己的孩子提出这样那样的要求。这样，我心中的怒气便消了很多。
*** 题目
**** 15
***** 选择
****** A
难道
****** B
难免
****** C
难过
****** D
难受
***** 答案
B
**** 16
***** 选择
****** A
转变
****** B
变化
****** C
变
****** D
交换
***** 答案
D
**** 17
***** 选择
****** A
建议
****** B
借口
****** C
观点
****** D
理由
***** 答案
C
**** 18
***** 选择
****** A
觉得他们有道理
****** B
真想跟他们大吵一架
****** C
不跟他们生气
****** D
坚持自己的意见
***** 答案
B
** 第二部分
*** 19
:PROPERTIES:
:ID: 355d8846-aebd-47c1-97a8-7f2173ceff24
:END:
**** 段话
这是一套非常有趣的儿童读物，一套8本，包含8个世界著名的童话故事。故事情节易懂，语言简单，适合6～8岁的孩子。它很适合在睡前读给孩子听；还配有图画和拼音，所以也适合孩子在家长的带领下自己阅读，有利于识字。
**** 选择
***** A
这套书的读者是成人
***** B
这套书可以用来识字
***** C
这套书配有录音光盘
***** D
这套书有6～8个故事
**** 答案
B
*** 20
:PROPERTIES:
:ID: a0d14268-6a4a-42fb-b388-6354c7c3e899
:END:
**** 段话
教育学家认为，儿童需要阅读与他们的年龄、兴趣和能力相符的书，同时，他们也希望阅读题材丰富多样。所以专家建议，可以让儿童多接触不同方面的阅读材料，包括报纸、杂志，甚至商品包装、广告标语等。通过这些，儿童会越来越认识到语言文字的重要性。
**** 选择
***** A
孩子只应该读儿童读物
***** B
孩子必须多看报纸杂志
***** C
语言文字有很重要的作用
***** D
儿童不需要了解语言文字
**** 答案
C
*** 21
:PROPERTIES:
:ID: 8cb64300-a77a-40ff-8552-ce5e5ecd8dd8
:END:
**** 段话
现在有一种观点认为，坚持全面发展，就不该突出发展个性；主张发展个性，就是否定全面发展，把发展个性与全面发展放在对立的位置上。我不同意这种观点。我们应该大胆地、理直气壮地承认学生的个体存在价值，我认为对个性教育的种种顾虑是不必要的。
**** 选择
***** A
发展个性与全面发展是对立的
***** B
坚持全面发展就不应发展个性
***** C
应该对每个学生开展个性教育
***** D
发展个性与全面发展并不矛盾
**** 答案
D
*** 22
:PROPERTIES:
:ID: 74e2341f-3f6a-4522-87a4-85c38bcbec46
:END:
**** 段话
人们通常认为诚实是一种道德。如果每个人都遵守诚实的道德标准，对任何事情都能实事求是地处理，社会中每个人都能受益。反过来如果社会中有人是不诚实的，某个人为了自己的利益而不诚实，损害了其他人的利益，那么事情就不能被正确解决和处理，社会也就不会向前发展，这样对社会中每个人都不利。人们认识到不诚实对社会中的每一个人都没有好处，而诚实能给每个人带来好处，诚实就成了一种道德。
**** 选择
***** A
诚实能够解决问题
***** B
诚实可以使大家受益
***** C
不诚实是因为利益受损
***** D
诚实是唯一的道德标准
**** 答案
B
** 第三部分
*** 23-25
**** 段话
《卖火柴的小女孩》是19世纪中叶丹麦作家安徒生的著名童话作品，发表于1846年。主要讲了一个卖火柴的小女孩在合家欢乐的大年夜冻死在街头的悲剧故事。小女孩死了，嘴角却带着微笑，擦燃火柴的美好幻想与她饥寒交迫的现实生活形成了鲜明的对比。
因为没能卖出一根火柴，小女孩整天都没有东西吃。她又冷又饿，于是点燃了自已没有卖掉的火柴。擦亮第一根火柴，她看见了大火炉；擦亮第二根火柴，她看见了香喷喷的烤鹅；擦亮第三根火柴，她看见了美丽的圣诞树；而第四根火柴擦亮时，她看见了久违的奶奶，她想让奶奶留在自己身边，于是点燃了剩下的一整把火柴。然而，当火柴熄灭的时候，这所有的一切都不见了，小女孩就这样在圣诞之夜悲惨地死去，没有人知道她在生前最后一刻看到的美好情景。
安徒生童话的题材很广，在他众多的童话中，悲剧性故事占有相当大的比例。带着微笑和温柔的情感进行悲剧叙事是安徒生童话的一个显著特点。从他创作中期的《海的女儿》到其晚期创作的《老约翰尼讲的故事》，悲剧无所不在。安徒生在其中寄托了自己对人物的同情、理解、挚爱和尊重。当然，他也有《拇指姑娘》这样轻松愉快的作品。
**** 题目
***** 23
****** 问题
《卖火柴的小女孩》是一篇：
****** 选择
******* A
历史故事
******* B
民间传说
******* C
童话故事
******* D
现代小说
****** 答案
C
***** 24
****** 问题
小女孩擦亮所有的火柴是为了留住：
****** 选择
******* A
火炉
******* B
烤鹅
******* C
圣诞树
******* D
奶奶
****** 答案
D
***** 25
****** 问题
下列哪篇作品不是悲剧性故事？
****** 选择
******* A
《海的女儿》
******* B
《拇指姑娘》
******* C
《卖火柴的小女孩》
******* D
《老约翰尼讲的故事》
****** 答案
B
*** 26-28
**** 段话
无论学习什么学科，都该预先认清楚为什么要学习它。认清楚了，一切努力才有目标、有方向，不至于盲目地胡搅一阵。
学生为什么要学习语文呢？这个问题，读者如果没有思考过，请仔细地思考一下。如果已经思考过了，请把思考的结果和后面所说的对照一下，看从中能不能得到些补充或修正。
学习语文就是学习本国的语言文字。语言文字的学习，就理解方面说，是得到一种知识；就运用方面说，是养成一种习惯。这两方面必须联成一体。就是说，理解是必要的，但是理解之后必须能够运用；知识是必要的，但是这种知识必须成为习惯。语言文字的学习，出发点在“知”，而终极点在“行”，到能够“行”的地步才算具有这种生活的能力。这是每一个学习语文的人应该记住的。
学习语文，我们将得到什么知识，养成什么习惯呢？简括地说，只有两项，一项是阅读，另一项是写作。要从语文得到阅读和写作的知识，养成阅读和写作的习惯。阅读是“吸收”的事情，通过阅读可以领受人家的经验，接触人家的心情；写作是“发表”的事情，写作可以显示自己的经验，吐露自己的心情。在人群中间，经验的授受和心情的沟通是最切要的，所以阅读和写作两项也最重要。这两项的知识和习惯，其他学科是不负授予和训练的责任的，这是语文的专责。每一个学习语文的人应该认清楚：得到阅读和写作的知识，从而养成阅读和写作的习惯，就是学习语文的目标。
**** 题目
***** 26
****** 问题
关于“知”和“行”，下列哪项不正确？
****** 选择
******* A
“知”是“行”的目标
******* B
“知”是指获得知识
******* C
学习语言知识后应该运用
******* D
“知”和“行”应该联系起来
****** 答案
A
***** 27
****** 问题
作者认为语文的责任是：
****** 选择
******* A
得到阅读和写作的知识
******* B
养成阅读和写作的习惯
******* C
吐露自己的心情
******* D
在阅读和写作方面教授知识、训练习惯
****** 答案
D
***** 28
****** 问题
最适合这篇文章的标题是：
****** 选择
******* A
学科的特点
******* B
什么是语文
******* C
为什么要学习语文
******* D
“知”与“行”
****** 答案
C
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
