* Text

** 标题

最受欢迎的毕业生

** content

他叫刘辰，是一个年仅23岁的应届本科毕业生，再过一个月就要毕业了。面对并不乐观的就业形势，他压力很大：“说实话，我觉得自己实在没什么优势。”

就在他为工作发愁时，机会来了。天津卫视的《非你莫属》节目组看了他的简历，接受了他的申请，他可以到节目现场去求职。来到现场，他发现，果然有一家公司有适合他乙的职位——旅游体验师。因为小学六年级的时候，他迷上了公交年，从此，就一直关注公交线路，北京市范围内所有的公交线路他都了如指忉听。从上初中起，他就是同学们的出行顾问，无论谁想去哪里，他都能很快地回荅出最方便的路线，提供给同学们参考。在他的成长过程中，公交就是他最好的伙伴。

节目制作时，电视台问他有什么才艺，他便说：“我是个公交迷，对北京市的公交、地铁线路都有一些研究。”主持人现考他：“假设我要从国贸到鼓楼不街，该怎么乘车？”他反应得非常快，马上回答说：“在国贸坐1路车，到天安门东，换乘82路，就可以到达。”他的回答让台上的12位老板都兴奋了起来，他们开始陆续向他提问。他有问必答，不但准确无误地按顺序报了一大堆公交车、地铁站稽延名字，而且还给一对情侣制订了此就休闲一日游的具体方案。

他对公交的这种专注显然为他的求职打开了大门。老总们向他发出了热情的邀请，给他非常好的职位和待遇，甚至要专门为他成立有关的部门，只为留住这个人才。最终，他选择了一家他感兴趣的单位。

主持人问这家公司的老总：“你给的工资是不是太高了？“这个老总回答：”专业的、执着的、优秀的人才是无价的，这样的人一定会有光明的前途。“是个，无论在哪个行业，最缺乏的永远都是专注的人。专注的人永远不缺机会！

** 生词

届 / jie4 / session, year, class ;
本科 / ben3ke4 / undergraduate education ;
面对 / mian4dui4 / to face, to confront ;
乐观 / le4guan1 / optimistic ;
就业 / jiu4ye4 / to find employment ;
实话 / shi2hua4 / truth, true words ;
优势 / you1shi4 / superiority, advantage ;
简历 / jian3li4 / resume, CV ;
现场 / xian4chang3 / site, spot ;
职位 / zhi2wei4 / position, post ;
体验 / ti3yan4 / to feel and experience ;
从此 / cong2ci3 / from then on, since then ;
范围 / fan4wei2 / scope, range ;
初（级）中（学） / chu1 (ji2) zhong1 (xue2) / junior high school ;
顾问 / gu4wen4 / consultatnt, adviser ;
参考 / can1kao3 / to consult, to refer to ;
成长 / cheng2zhang3 / to grow up ;
制作 / zhi4zuo4 / to make, to produce ;
才艺 / cai2yi4 / talent and skill ;
假设 / jia3she4 / to suppose, to assume ;
乘 / cheng2 / to ride, to travel by ;
反应 / fan3yiing4 / to respond, to react ;
到达 / dao4da2 / to reach, to arrive ;
老板 / lao3ban3 / boss, employer ;
陆续 / lu4xu4 / one after another, in succession ;
提问 / ti2wen4 / to ask a question ;
堆 / dui1 / heap, pack, pile ;
情侣 / qing2lv3 / couple, lovers ;
制订 / zhi4ding4 / to make, to draw up, to work out ;
休闲 / xiu1xian2 / to have leisure, to relax ;
具体 / ju4ti3 / specific, detailed ;
专注 / zhuan1zhu4 / concentrated, engrossed ;
显然 / ian3ran2 / obvious, evident ;
成立 / cheng2li4 / to establish, to set up ;
部门 / bu4men2 / department, section ;
执着 / zhi2zhuo2 / persistent, persevering ;
光明 / guang1ming2 / bright, promising ;
前途 / qian2tu2 / future, prospect ;
行业 / hang2ye4 / trade, profession, industry ;
缺乏 / que1fa2 / to lack, to be short of ;

** QUESTION “问问题”和“提问”有什么区别？
:PROPERTIES:
:CREATED: [2022-08-27 17:03:09 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-08-27 Sat 17:03]
:END:


** 专有名词

刘辰 / liu2 chen / Liu Chen, name of a person;
天津卫视 / tian1jin1 wei4shi4 / Tianjin TV, a television channel ;
《非你莫属》 / fei1ni3mo4shu3 / Only You, a job-hunting reality show ;
国贸 / guo2mao4 / Guomao, the central business district of Beijing ;
鼓楼大街 / gu3lou2 da4jie1 / Gulou Street, literally "Old Drum Tower Street" ;
天安门东 / Tian1'an1men2 dong1 / Tian'anmen East Station ;
* 练习

** 1
:PROPERTIES:
:ID: 3961ec68-df42-4189-9d92-3d4f313f0759
:END:

*** 选择

**** 1

参考

**** 2

范围

**** 3

具体

**** 4

乐观

**** 5

陆续

**** 6

显然

*** 题目

**** 1

***** 句子填空

因为天气影响，我们的活动推迟了，🟦时间再等通知。

***** 答案

3

**** 2

***** 句子填空

会议快要开始了，代表们🟦走进了会场。

***** 答案

5

**** 3

***** 句子填空

这次比赛是在全国🟦内举行的。

***** 答案

2

**** 4

***** 句子填空

前两局棋输给爸爸，他🟦并不担心。

***** 答案

6

**** 5

***** 句子填空

不管遇到什么因难，都要🟦地面对生活。

***** 答案

4

**** 6

***** 句子填空

这只是我个人意见，仅供你🟦。

***** 答案

1

** 2

*** 1

**** 句子

这个玩具是我爸爸亲手为我🟨的。

**** 选择

***** a

制作

***** b

制造

**** 答案



*** 2

**** 句子

我们🟨他明天9点能出发，那么10点可以到这儿。

**** 选择

***** a

假设

***** b

假如

**** 答案



*** 3

**** 句子

我们已经安全地🟨目的地了。

**** 选择

***** a

达到

***** b

到达

**** 答案



*** 4

**** 句子

来我们么司工作，你的前途一片🟨！

**** 选择

***** a

光明

***** b

明亮

**** 答案



** 3

*** 1

**** 1

***** 词语

一届

***** 答案



**** 2

***** 词语

一堆

***** 答案



**** 3

***** 词语

一份

***** 答案



**** 4

***** 词语

一种

***** 答案



*** 2

**** 1

***** 词语

失去

***** 答案



**** 2

***** 词语

制定

***** 答案



**** 3

***** 词语

缺乏

***** 答案



**** 4

***** 词语

成立

***** 答案





* 扩展

** 词语

*** 1

**** 话题

职业

**** 词语

模特
会计
秘书
农民
工程师
工人
员工

*** 2

**** 话题

求职

**** 词语

人事
报到
失业
手续
待遇
兼职
简历

** 题

*** 1

**** 句子

你女儿的身材这么好，可以去当个🟨。

**** 答案



*** 2

**** 句子

我要考注册🟨师，报了个辅导班，每周末都要上课。

**** 答案



*** 3

**** 句子

平时的上课，周末我会到一个么司去做🟨。

**** 答案



*** 4

**** 句子

我们决定录用你，请你下周一到🟨部办理🟨手续。

**** 答案


