* 听力
** 第一部分
:PROPERTIES:
:NOTETYPE: 21f26a95-0bf2-4e3f-aab8-a2e025d62c72
:END:
*** 1
:PROPERTIES:
:ID: 8fb1c264-fbcd-4878-bef4-8220075633b7
:END:
**** 对话
***** 转录
女：这位先生，请你说说你摸到的大象是什么样的？[[file:f904d90b-3074-47f8-b44d-38995908a735.mp3][(audio)]]
男：我觉得它像一根绳子。[[file:5a18345b-0e2a-4ca3-bbf0-2b0d929bc8ab.mp3][(audio)]]
***** 音频
992ddce9-e9aa-4805-8ed4-a985ae42998a.mp3
**** 问题
***** 转录
这个盲人最可能摸到了大象身体的哪个部位？
***** 音频
de2189db-01e8-41c7-8aad-1d29b66e2348.mp3
**** 选择
***** A
尾巴
***** B
耳朵
***** C
身子
***** D
牙齿
**** 答案
A
*** 2
:PROPERTIES:
:ID: 400f1143-49d1-477f-9e69-b82ccd02d4ae
:END:
**** 对话
***** 转录
男：是谁把玻璃打碎了？[[file:67c14399-a594-4354-93ad-94b8539024f7.mp3][(audio)]]
女：不是我们，窗户外面忽然飞进来一只足球。[[file:f8469b5a-69a8-403b-b7cc-53205d580f83.mp3][(audio)]]
***** 音频
9c96de3d-239f-447d-a9d7-685a36f90808.mp3
**** 问题
***** 转录
他们现在在哪儿？
***** 音频
0afa2778-7b79-4db4-a4a8-09e51f8ebe76.mp3
**** 选择
***** A
屋子外面
***** B
屋子里面
***** C
窗户外面
***** D
足球场上
**** 答案
B
*** 3
:PROPERTIES:
:ID: e9d6672a-7713-4091-971f-4580d8a6f576
:END:
**** 对话
***** 转录
女：我认为自己很适合贵公司的这个职位。[[file:1ed6c6f9-94fa-4456-9f9a-b47bea930d31.mp3][(audio)]]
男：那请你说说，如果来我们公司，你最善于处理哪方面的业务？[[file:c001057c-65d6-4d7d-8ef1-e72ca373480f.mp3][(audio)]]
***** 音频
28b6f8c7-d261-4223-b62a-61bfb01fdfb6.mp3
**** 问题
***** 转录
对话最可能发生在什么时候？
***** 音频
4eb6de13-9b10-4bba-9568-2610ce1f13fb.mp3
**** 选择
***** A
夫妻交流
***** B
招聘面试
***** C
记者采访
***** D
同事聊天儿
**** 答案
B
*** 4
:PROPERTIES:
:ID: 992788ae-c67c-49b1-91e2-446597df239d
:END:
**** 对话
***** 转录
男：就买这个花盆怎么样？[[file:702a486c-2045-4f92-92e6-9d183f9b1125.mp3][(audio)]]
女：我不太想要塑料的，还是找找有没有木头的吧。[[file:9ae382c9-70c0-49fc-af3d-f7ace4ecabf9.mp3][(audio)]]
***** 音频
90a19c36-a491-47c7-849d-27aaca6b2b0a.mp3
**** 问题
***** 转录
女的想买什么材料的花盆？
***** 音频
2e322654-6c0d-45b1-8443-07b6cfd312f6.mp3
**** 选择
***** A
金属
***** B
石头
***** C
木头
***** D
塑料
**** 答案
C
*** 5
:PROPERTIES:
:ID: 7b4f0127-b14e-477c-93a4-e0a4b5931940
:END:
**** 对话
***** 转录
女：你蹲下来点儿，别让他发现你了。[[file:a1c14e35-510a-4759-b762-77709382c303.mp3][(audio)]]
男：不要紧，我这边正好有棵树挡着呢。[[file:2af2f781-d9c5-4a19-9996-2d65cbc8d429.mp3][(audio)]]
***** 音频
66412552-98ba-44a3-807a-7a6d3bbd93a1.mp3
**** 问题
***** 转录
男的是什么意思？
***** 音频
0cc004fe-7e73-4a71-aab9-f75397ff1751.mp3
**** 选择
***** A
他不愿意蹲下
***** B
他想被人发现
***** C
他准备去那边
***** D
他不会被看见
**** 答案
D
*** 6
:PROPERTIES:
:ID: 0eecbe02-a858-41fe-b966-a60b5cda6a34
:END:
**** 对话
***** 转录
男：我还没说完你就急着插嘴，能听我说完吗？[[file:e91add79-0e99-48bf-8a4e-0e6b9d8143f8.mp3][(audio)]]
女：你能有什么好主意？[[file:4a641fc0-84af-4082-b444-56189fe8b401.mp3][(audio)]]
***** 音频
9a1af78f-c69d-49aa-8a05-3d1d83b5e2e9.mp3
**** 问题
***** 转录
女的是什么态度？
***** 音频
2f913289-eba0-4719-b58d-952d5a5693cf.mp3
**** 选择
***** A
去持
***** B
肯定
***** C
否定
***** D
兴奋
**** 答案
C
** 第二部分
*** 7
**** 对话
***** 转录
女：你以前考试都是前三名，这次成绩怎么下滑得这么厉害？
男：唉，我最近确实不够用心。
女：考前没好好复习吗？
男：昨天熬夜看书了，但已经来不及了。
***** 音频
197085b9-efbf-45a0-a10b-569d83ee9c6a.mp3
**** 问题
***** 转录
男的为什么成绩下滑？
***** 音频
3daee704-69b2-41b3-bee4-ce3b7115d276.mp3
**** 选择
***** A
这次考试太难
***** B
最近不太认真
***** C
考前没有复习
***** D
熬夜精神不好
**** 答案
B
*** 8
**** 对话
***** 转录
男：咱们把空调打开吧。
女：空调太费电了，开个电风扇就行。
男：天这么热，电扇不管用。
女：有这么热吗？心静自然凉。
***** 音频
cf79acab-2d2b-4078-be8e-8a02aa31dc8b.mp3
**** 问题
***** 转录
女的是什么意思？
***** 音频
34bc0152-ef70-496d-ad2f-0d0b71a0476e.mp3
**** 选择
***** A
应该开空调
***** B
开电扇就够
***** C
天气很凉快
***** D
电扇很费电
**** 答案
B
*** 9
**** 对话
***** 转录
女：有人说，传统文化是一个民族的根，您同意吗？
男：我完全同意，丢掉传统的民族是没有生命力的。
女：那您也同意我们应该尽力保护传统文化了？
男：不是尽力，是一定要做到。
***** 音频
d4978dce-e7ca-4f09-930a-888828599e68.mp3
**** 问题
***** 转录
关于传统文化，男的有什么看法？
***** 音频
ac40f4af-2857-4b98-972b-0f3035347807.mp3
**** 选择
***** A
非常重要
***** B
不需要保护
***** C
失去了生命力
***** D
没有办法保护
**** 答案
A
*** 10
**** 对话
***** 转录
男：你这次比赛中的表现真是太精彩了！
女：是吗？我觉得有两道题我反应有点儿慢。
男：已经非常好了，最多的一次你连续抢答了六道题呢！
女：哈哈，你看得可真仔细啊！
***** 音频
e1510557-5040-4a5e-8c53-59de73137e02.mp3
**** 问题
***** 转录
女的可能参加了什么比赛？
***** 音频
ab5b02fd-498b-4698-89b2-ac27849e5247.mp3
**** 选择
***** A
唱歌比赛
***** B
射箭比赛
***** C
智力问答
***** D
机器维修
**** 答案
C
*** 11-12
**** 对话
***** 转录
女：杰克，你学中文的时候，听过“夸父追日”这个故事吗？
男：听过啊！这是古书《山海经》里的一个神话传说。
女：那你能不能给我们讲讲这个故事？
男：好啊，夸父跟太阳赛跑。在追赶太阳的过程中，他太渴了，喝光了黄河、渭河的水都不够，就想去喝北方大湖的水，结果还没到大湖的时候，他就渴死了。在他死后，他扔掉的手杖变成了桃林。
女：你讲得真清楚。
***** 音频
294bf5c7-5ee8-403c-8ce1-35be4df34048.mp3
**** 题目
***** 11
****** 问题
******* 转录
“夸父追日”是一个什么故事？
******* 音频
4d9d093e-467d-4c18-950e-4d92c9a1aece.mp3
****** 选择
******* A
中国当代故事
******* B
中国传统故事
******* C
外国当代故事
******* D
外国传统故事
****** 答案
B
***** 12
****** 问题
******* 转录
夸父是怎么死的？
******* 音频
d5c17456-39b9-4f5e-b8ee-3bb346db0b16.mp3
****** 选择
******* A
饿死的
******* B
冻死的
******* C
渴死的
******* D
累死的
****** 答案
C
*** 13-14
**** 段话
***** 转录
一个寒冷的冬夜，有位农夫在路边看到一条快要冻死的蛇。善良的农夫觉得很可怜，就把蛇捡起来，放到自己的怀里为它取暖。在农夫温暖的怀中，蛇渐渐醒了过来。农夫很高兴，问蛇好点儿了没有。没想到，蛇的回答是狠狠地咬了他一口。临死之前，农夫非常后悔。他终于明白，像毒蛇一样的恶人是不应该去帮的。但是他明白得太晚了。
***** 音频
1c901a6f-9b27-428e-a054-7938006721b1.mp3
**** 题目
***** 13
****** 问题
******* 转录
这个故事发生在什么季节？
******* 音频
28a1d8b8-7660-43ee-ac8e-ef93151a5cff.mp3
****** 选择
******* A
春天
******* B
夏天
******* C
秋天
******* D
冬天
****** 答案
D
***** 14
****** 问题
******* 转录
下列哪个词最适合形容农夫的行为？
******* 音频
96c5d8ac-f45b-4275-956d-7b849fc090e3.mp3
****** 选择
******* A
天真的
******* B
小气的
******* C
周到的
******* D
坦率的
****** 答案
A
* 阅读
** 第一部分
*** 段话
昨天的数学考试里有一道很有意思的题：有三张大小一样的卡片，上面画着不同的画。把它们[[gap][15]]从中间剪开，每一张都分成上下两部分。然后把三张卡片的上半部分都[[gap][16]]，把下半部分都放进第二个盒子中。拿起两个盒子摇一摇，打乱[[gap][17]]的卡片，从每个盒子中各[[gap][18]]一张。请问，有多大的可能，两个部分正好可以拼成原来的画7
*** 题目
**** 15
***** 选择
****** A
特别
****** B
分别
****** C
区别
****** D
个别
***** 答案
B
**** 16
***** 选择
****** A
藏起来
****** B
放进第一个盒子里
****** C
放在桌子上
****** D
放在一个塑料袋里
***** 答案
B
**** 17
***** 选择
****** A
表面
****** B
片面
****** C
对面
****** D
里面
***** 答案
D
**** 18
***** 选择
****** A
伸出里面
****** B
挣出
****** C
摸出
****** D
扶出
***** 答案
C
** 第二部分
*** 19
:PROPERTIES:
:ID: e4bbac7a-c477-4356-99e4-691cdec89d5d
:END:
**** 段话
西汉时期有一位著名的将军叫李广，他善于骑马射箭，作战勇敢，被称为“飞将军”。他曾经有一次把一块大石头当成了老虎，结果把一整支箭都射进了石头中。士兵们都惊呆。
**** 选择
***** A
李广是唐朝的将军
***** B
李广功夫很好，会飞
***** C
李广射死了一只老虎
***** D
李广把石头当成了老虎
**** 答案
D
*** 20
:PROPERTIES:
:ID: d92cdbc6-fd6d-4a55-98ce-809305ee83fc
:END:
**** 段话
一个勤劳善良的农民，收获了一个好大好大的西瓜。他把这个西瓜献给国王，国王很高兴，赏给农民一匹高大结实的马。很快，这件事大家都知道了。有个富人心想：献个西瓜，就能得到一匹马；如果献一匹马，国王会赏给我多少金银或者美女呢？于是富人向国王进献了一匹好马。国王同样很高兴，告诉身边的人：“把那个农民献的大西瓜赏给这个献马的人吧。”
**** 选择
***** A
农民向国王进献了一匹好马
***** B
富人希望能得到更多的赏赐
***** C
国王赏给了富人金银和美女
***** D
国王对富人的进献很不满意
**** 答案
B
*** 21
:PROPERTIES:
:ID: da9c393a-e267-45a4-bb2b-1a22ccb83401
:END:
**** 段话
甲骨文是刻在龟甲、兽骨上的文字。从1899年开始，大约出土了10万多片甲骨，所见单字总数近5000个，其中只有1000多字能够被准确辨认。现已发现的甲骨文大部分属于商朝时期。最早发现于河南安阳小屯的殷墟，所以又称“殷墟文字”。
**** 选择
***** A
甲骨文的“甲”是指龟甲
***** B
甲骨文都已被辨认出来了
***** C
甲骨文都是商朝时的文字
***** D
甲骨文都是在河南发现的
**** 答案
A
*** 22
:PROPERTIES:
:ID: ae9be46d-432b-4eb4-8e62-ca186449d560
:END:
**** 段话
汉语中的第三人称代词“她”，是现代诗人刘半农首创的。古代汉语中没有“她”字，第三人称不分男女，一律写成“他”。到五四时期，曾在法国留学的刘半农觉得，白话文的兴起，加上翻译介绍外国文学作品的增加，第三人称代词使用频繁，仅仅一个看不出性别的“他”是不够的。于是，1917年，刘半农在翻译一个英国戏剧时，用了自己创造的“她”字。
**** 选择
***** A
汉语中的第三人称代词只有一个
***** B
刘半农五四时期曾经在英国留学
***** C
古汉语中指称女性也用“他”字
***** D
“她”字与白话文是同年出现的
**** 答案
C
** 第三部分
*** 23-25
**** 段话
古时候有个人，我们暂且叫他张三吧。张三辛苦了大半辈子，存了三百两银子。他心里很高兴，但是也很苦恼，怕有人把他的银子偷走，不知道放在哪里才安全。带在身上吧，不方便；放在抽屉里，觉得不妥当；放在床底下，好像还是容易被偷……他捧着银子，冥思苦想了半天，终于想到了一个自以为巧妙的办法。
当天晚上，他趁着夜深人静，找了一个箱子，把银子放在箱子里，然后在自家院子里的墙角边挖了个坑，把箱子埋在里面。埋完了他还是不放心，害怕别人怀疑这里藏了银子，于是就在白纸上写了“此地无银三百两”七个大字，贴在坑边的墙上，这才放心地睡觉去了。
这一整天，他心神不宁的样子早就被邻居王二看到了。第二天半夜，王二悄悄溜进他家的院子，把三百两银子都偷走了。王二看着白花花的银子又激动又担心。为了不让张三知道是他偷了银孔，便在“此地无银三百两”的下面加上了一句“隔壁王二不曾偷”。
后来，人们就用这两句话来形容人自作聪明，本来想要隐藏起来、不让别人知道的事情，反而暴露了。使用时，这两句话也可以简化成“此地无银”。还有“不打自招”欲盖弥彰“等成语，都有类似的意思。
**** 题目
***** 23
****** 问题
张三把银子藏在了：
****** 选择
******* A
抽屉里
******* B
床底下
******* C
墙里面
******* D
地底下
****** 答案
D
***** 24
****** 问题
王二为什么要留下一句话？
****** 选择
******* A
他的书法很好
******* B
他怕张三怀疑他
******* C
他想让张三来找他
******* D
他怕张三不知道他是谁
****** 答案
B
***** 25
****** 问题
下列词语，哪个与“此地无银”的意思无关？
****** 选择
******* A
自作聪明
******* B
不打自招
******* C
欲盖弥彰
******* D
远亲不如近邻
****** 答案
D
*** 26-28
**** 段话
普通话中有四个声调，通常叫四声，我们依次把它们称为“阴平、阳平、上声（‘上’读第三声）、去声”。
标声调首先要读准字音，这样就不会标错第几声。但在读准音的情况下还请记住，标声调有一个规律：所有声调都是标在韵母上的。不过，标在哪个韵母上也有一定要求。
根据《汉语拼音方案》的规定，“声调符号标在音节的主要母音上「。主要母音就是主要元音，也就是韵母的韵腹。有a、o、e的韵母，a、o、e就是主要元音；以单元音i、u、ü一作为韵母的，i、u、ü就是主要元音。简单地说就是一般按元音的开口大小标调，即a-o-e-i-u-ü的顺序，都是标在开口大的上面。不过韵母iou、uei、uen省略成iu、ui、un后，韵腹o、e不见了，调号标在哪里呢？现在的习惯办法是标在后一个元音字母上，即标在iu的u、ui的i上，un当然标在u上。有句顺口溜可以帮助我们记忆。”有a在，把帽戴；a要不在，o、e戴；要是i、u一起来，谁在后面给谁戴。“
汉语中还存在着一种特殊声调，叫作轻声，有时也叫第五声，它也能够起到分辨语义的作用，写汉语拼音时不标调号。也有学者认为“第五声”的说法并不确切。
**** 题目
***** 26
****** 问题
汉语拼音中的“阴平”指的是：
****** 选择
******* A
第一声
******* B
第二声
******* C
第三声
******* D
第四声
****** 答案
A
***** 27
****** 问题
根据《汉语拼音方案》下列拼音中正确的是：
****** 选择
******* A
瞎 xià
******* B
说 shuō
******* C
摇 yáo
******* D
慧 huì
****** 答案
D
***** 28
****** 问题
关于轻声，下列说法正确的是：
****** 选择
******* A
轻声是四声中的一种
******* B
轻声不能区别词义
******* C
轻声书写时没有相应的调号
******* D
学者们对轻声的看法一致
****** 答案
C
* 书写
** 第一部分
*** 29
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 30
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
*** 31
**** 词语
***** 1
***** 2
***** 3
***** 4
***** 5
**** 答案
***** 1
