:PROPERTIES:
:CREATED: [2022-03-10 14:49:41 -05]
:END:

* Listening
:PROPERTIES:
:CREATED: [2022-03-10 09:44:20 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-03-09 05:51:39 -05]
:END:


Don't confuse 去 (qù) with 柱 (zhù).

*** 1
:PROPERTIES:
:CREATED: [2022-06-24 14:18:37 -05]
:ID: b3f9f599-d06d-4aee-a168-662c073a2148
:END:

医生说要住一个月，现在不能出院。
pi: yīshēng shuō yào zhù yī gè yuè, xiànzài bù néng chū yuàn
en: The doctor said I need to stay for one month, I can't be discharged now
es: El doctor dijo que debo quedarme por un mes, ahora no puedo ser dado de alta

Answer: ✅

*** 2
:PROPERTIES:
:CREATED: [2022-06-24 14:18:40 -05]
:ID: 72f4441d-8c59-417d-95fe-442bc29a7690
:END:

我爸爸每天早上都要运动。
pi: wǒ bāba měitiān zǎoshang dōu yào yùndòng
en: My father runs every morning
es: My padre corre todas las mañanas

Answer: ❌

*** 3
:PROPERTIES:
:CREATED: [2022-06-24 14:18:42 -05]
:ID: f845a94a-b572-4660-8244-c17b1d1f36b2
:END:

张先生已经给大卫打电话了。
pi: zhāng xiānsheng yǐjīng gěi dàwèi dǎ diànhuà le
en: Mr. Zhang already called David
es: Sr. Zhang ya llamó a David

Answer: ✅

*** 4
:PROPERTIES:
:CREATED: [2022-06-24 14:18:45 -05]
:ID: 78c6283c-a985-404b-9eb8-02ffce77f3ef
:END:

他最近太累了，已经生病了。
pi: tā zuì jìn tài lèi le,  yǐjīng shēngbìng le
en: He's been too tired lately and has been sick.
es: Últimamente ha estado tan cansado que se ha puesto enfermo.

Answer: ✅

*** 5
:PROPERTIES:
:CREATED: [2022-06-24 14:18:47 -05]
:ID: 76aff05b-6e34-411a-a235-7eb1e626dbf5
:END:

他每天十二点睡觉，早上九点起床。
pi: tā měitiān shíèr diǎn shuìjiào, zǎoshang jiǔ diǎn qǐchuáng
en: everyday he sleeps at 12:00, wakes up at 9:00
es: Todos los días él duerme a las 12:00 y se levanta a las 9:00 de la mañana

Answer: ✅

** 2
:PROPERTIES:
:CREATED: [2022-03-09 06:09:08 -05]
:END:

Answers

6. F
7. E
8. C
9. A
10. B

*** 6
:PROPERTIES:
:CREATED: [2022-03-09 06:20:07 -05]
:ID: be8452bd-7f09-4b97-be5c-a3cf6cc7ce36
:END:

男：你爸爸每天运动吗？
pi: nǐ bàba měitiān yùndòng ma
en: Does your father do exercise every day?
es: ¿Tu papa hace ejercicio todos los días?

女：对，他每天早上出去跑不。
pi: duì, tā měitiān zǎoshang chū qù pǎobù
en: yes, every morning he goes for a run
es: sí, todas las mañanas sale a correr


Answer: F

*** 7
:PROPERTIES:
:CREATED: [2022-03-09 06:20:01 -05]
:ID: 07bbec50-1352-4870-90a0-1b1bbde1e8b8
:END:

男：你怎么了？
pi: nǐ zěnmele
en: how are you?
es: ¿cómo estás?

女：身体不好，已经两天了。
pi: shēntǐ bù hǎo, yǐjīng liǎng tiān le
en: I'm not good, it's been 2 days now
es: no ha estado bien, ya van dos días

Answer: E

*** 8
:PROPERTIES:
:CREATED: [2022-03-09 06:20:14 -05]
:ID: 4ffc8e4d-d31a-47fd-a3b6-9f7034e76ed4
:END:

男：明天下午你有时间吗？我们去看电影吧。
pi: míngtiān xiàwǔ nǐ yǒu shíjiān ma? wǒmen qù kàn diànyǐng bā
en: Do you have time tomorrow afternoon? Let's go to the movies.
es: ¿Estás libre mañana por la tarde? Vamos al cine.

女：对不起，我要看书，没有时间。
pi: duìbuqǐ, wǒ yào kàn shū, méiyǒu shíjiān
en: Sorry, I have to read a book, I don't have time.
es: Lo siento, tengo que leer un libro y no tengo tiempo.

Answer: C

*** 9
:PROPERTIES:
:CREATED: [2022-03-09 06:20:17 -05]
:ID: 944ef328-f5a6-4480-8ff7-cc1945728893
:END:

女：你的小女儿多高？
pi: nǐ de xiǎo nǚ'ér duō gāo
en: How tall is your little girl?
es: ¿Cuánto mide tu pequeña?

男：一米多一点儿吧。
pi: yī mǐ duō yīdiǎr bā
en: A little over one meter.
es: Un poco más de 1 metro

Answer: A

*** 10
:PROPERTIES:
:CREATED: [2022-03-09 06:20:18 -05]
:ID: 59da166c-807b-451f-99ce-086e6998572e
:END:

女：医生我明天能出院吗？
pi: yīsheng wǒ míngtiān néng chū yuàn ma
en: Dr., will I be able to leave tomorrow?
es: Doctor ¿podré irme mañana?

男：能，回家每天吃这个药。
pi: néng, huíjiā měitiān chī zhège yào
en: yes, go home and take these medicines every day
es: sí, ve a casa y toma estas medicinas todos los días

Answer: B

** 3
:PROPERTIES:
:CREATED: [2022-03-10 00:14:10 -05]
:END:


*** 11
:PROPERTIES:
:CREATED: [2022-03-10 00:14:14 -05]
:ID: ba450f88-7d88-4063-8167-21385ebcdfe4
:END:

Alternatives

不能
pi: bù néng
en: can't
es: no puede

Dialogue

女：你什么时候能出院？
pi: nǐ shénme shíhou néng chū yuàn
en: When will you be discharged from the hospital?
es: ¿Cuándo le darán el alta del hospital?

男：医生说有要再住三天看一看。
pi: yīsheng shǔo, yào zài zhù sān tiān kàn yī kàn
en: The doctor said there is to stay for another three days to see.
es: El médico dijo que habría una estancia de tres días más para ver qué pasa.

问：男的明天能出院吗？
pi: nán de míngtiān néng chū yuàn ma
en: Can the male be discharged tomorrow?
es: ¿El varón puede ser dado de alta mañana?

Answer

B

*** 12
:PROPERTIES:
:CREATED: [2022-03-10 08:14:31 -05]
:ID: c2f89236-2e80-440f-bc69-98906dd38d42
:END:

Alternatives

Dialogue

女：你每天早上几点起床？
pi: nǐ měitiān zǎoshang jǐ diǎn qǐchuáng
en: What time do you get up every morning?
es: ¿A qué hora se levanta cada mañana?

男：七点多，星期六和星期天十点多起床。
pi: qī diǎn duō, xīngqī liù hé xīngqī tiān shí diǎn duō qǐchuáng
en: After 7:00, and after 10:00 on Saturday and Sunday.
es: Después de las siete, y después de las diez los sábados y domingos.

问：女的星期六几点起床？
pi: nǚ de xīngqī liù jǐ diǎn qǐchuáng
en: What time does the woman get up on Saturday?
es: nǚ de xīngqī liù jǐ diǎn qǐchuáng

Answer

C

*** 13
:PROPERTIES:
:CREATED: [2022-03-10 08:20:30 -05]
:ID: 0be50bc9-8fec-4889-8c9e-4459a9749891
:END:

女：你一个人做饭累不累？
pi: nǐ yī gè rén zuò fàn lèi bù lèi
en: Are you tired of cooking alone?
es: ¿Está cansado de cocinar solo?

女：不累，我很喜欢做饭。
pi: bú lèi, wǒ hěn xǐhuan zuò fàn
en: No, I like cooking very much.
es: No, me gusta cocinar.

问：女的觉得做饭累不累？
pi: nǚ de júede zuò fàn lèi bú lèi
en: Does the woman find it tiring to cook?
es: ¿A la mujer le resulta agotador cocinar?

Answer: A

不累
pi: bú lèi
en: not tiring
es: no agotador

*** 14
:PROPERTIES:
:CREATED: [2022-03-10 08:51:36 -05]
:ID: f40a92af-edf1-4778-be35-1d2a6e1cc990
:END:

女：你女儿今年多大了？
pi: nǐ nǚ'ér jīnnián duō dà le
en: How old is your daughter?
es: ¿Qué edad tiene tu hija?

男：今年二十三岁，已经工作了。
pi: jīnnián èrshìsān suì, yǐjīng gōngzuò le
en: Twenty-three years old and already working.
es: Veintitrés años y ya está trabajando.

问：男的的女儿现在工作了吗？
pi: nán de de nǚ'ér xiànzài gōngzuò le ma
en: Is the man's daughter working now?
es: ¿La hija del hombre está trabajando ahora?

Answer: A

工作了
pi: gōngzuò le
en: she's already working
es: ya está trabajando

*** 15
:PROPERTIES:
:CREATED: [2022-03-10 10:11:08 -05]
:ID: 9ec8fd19-7c51-48f5-a4ae-dd8ea5b6723e
:END:

Alternatives

A. 去医院了
pi: qù yīyuàn le
en: went to the hospital
es: fue al hospital

B. 病了
pi: bìng le
en: sick
es: enfermo

C. 身体好多了
pi: shēntǐ hǎo duō le
en: her health is much better
es: su salud está mucho mejor

Dialogue

女：我这几天身体不好。吃了很多药。
pi: wǒ zhè jǐ tiān shēntǐ bù hǎo. chī le hěn duō yào.
en: I am not well these days. Took a lot of medicine.
es: No estoy bien estos días. Tomó mucha medicación.

男：我和你一起去医院看看吧。
pi: wǒ hé nǐ yīqǐ qù yīyuàn kàn kàn bā
en: I'll go to the hospital with you.
es: Iré al hospital contigo.

问：女的怎么了？
pi: nǚ de zěnmele
en: What's wrong with the women?
es: ¿Qué le pasa a la mujer?

Answer

B

* Reading
:PROPERTIES:
:CREATED: [2022-06-24 09:29:16 -05]
:END:

** 1
:PROPERTIES:
:CREATED: [2022-06-24 09:30:52 -05]
:END:

*** 16
:PROPERTIES:
:CREATED: [2022-06-24 09:29:19 -05]
:END:

麦克先生最不喜欢住院。

*** 17
:PROPERTIES:
:CREATED: [2022-06-24 09:29:41 -05]
:END:

爸爸每天工作很忙，星期六也不休息。

*** 18
:PROPERTIES:
:CREATED: [2022-06-24 09:30:02 -05]
:END:

我每天下午喝同学一起去跑步。

*** 19
:PROPERTIES:
:CREATED: [2022-06-24 09:30:16 -05]
:END:

这是一个星期的药，每天早上吃。

*** 20
:PROPERTIES:
:CREATED: [2022-06-24 09:30:31 -05]
:END:

妈妈每天早上七点前起床。

** 2
:PROPERTIES:
:ID: 89f52271-4750-4427-865c-b78fb9e2fd27
:END:

*** 21

我们//个星期六都工作。

*** 22

对不起，我很//，没时间去看电影。

*** 23

他不在家，下午四点//买东西了。

*** 24

我的小猫不想吃东西，我觉得它//了。

*** 25

我也不//北京的天气，你问问小李，他是北京人。

** 3

*** 26

医生说我要住两天院，明天能出院。

我今天不能出院。

*** 27

我的小猫生病了，你知道去哪个医院好吗？

我的小猫现在好多了。

*** 28

你星期天也去学校吗？太忙了！

他星期天不休息。

*** 29

这个药每天中午吃，晚饭后不要吃。

每天晚饭后吃药。

*** 30

我儿子不太高，他今年十四岁，一米五几。

他儿子今年十多岁。

** 4
:PROPERTIES:
:ID: 4b57febd-9c01-423f-ac9e-d0a279cf53d7
:END:

他儿子今年八岁了。
星期六也不休息，你工作累不累？
我不喜欢早上运动，我喜欢下午和朋友一起踢足球。
医生说他不能出院。
他在哪儿呢？你看见他了吗？
你每天什么时候回教？

*** 31

什么？已经三天了，为什么？

*** 32

我也不喜欢，我早上没时间。

*** 33

是啊，已经一米四了。

*** 34

没关系，星期天我有不少时间休息。

*** 35

九点多吧，很早。我早上起床也很早。

