* 课文
** 转录
每次遇到交通堵塞，那些滞留在路上，被堵车折磨得心烦意乱的人们就会想：汽车要是也有双翼，能飞起来就好了。人们的期盼，有可能变为现实吗？2050 年，汽车会是什么样？别的不敢担保，以下四点大体为我们勾画出了 2050 年汽车的轮廓。
甲更加清洁、安全
我们首先要问的是，2050 年汽车还会存在吗？我们常常听到这样的指责：北极冰川在融化；空气质量在下降；石油资源日益紧缺；全年全球一百多万人死于交通事故，都是汽车惹的祸。鉴于以上劣迹，人类会不会忍痛割爱？根据优胜劣汰的原则，汽车会不会被取代？一切皆有可能，但作为一种将人解放出来的灵活的交通工具，动不动就要将其淘汰，似乎不是明智之举，根本出路还是要在清洁环保、规范驾车出行上下功夫。谋求这一交通工具的清洁、安全，是 2050 年对汽车最起码的要求。
乙能自动行驶
2050 年，无人干预，能够自动在平坦的高速路上奔驰的车辆将会走进家庭。欧洲正试图实现由一名职业司机驾车引导一长串汽车前行，它们像是一条线上的珍珠，在路上移动。被引导车辆上的驾驶者可以工作，也可以休息，职业司机的工作效益也将大大提高。汽车抵达终点后，车上配备的高科技系统能使车辆自动停泊入位。这就是人类力求实现的汽车自动行驶。
丙融合数字生活方式
某家著名的搜索引擎公司意识到，为个人驾驶提供服务蕴藏着巨大的商机，于是，他们迫不及待地加入到汽车研发的行列，车企与电脑公司合作几乎成了无法阻挡的潮流。创造虚拟个人助理，为汽车用户提供路线、交通信息和日程安排等方面的帮助，在 2050 年将会是必然的服务，而非锦上添花。数字生活方式将完全与汽车融为一体，为汽车的方便、安全使用提供保障。
丁长途行车仍靠汽油
2050 年的汽车动力是什么？电力？风力？还是依然用汽油和柴油？有人会说，清洁能源的开发就是要遏制汽油、柴油的使用。没错，作为日常交通工具，电动汽车的比重一定会提高，可是跑长途呢？电动汽车也许能承受超远距离行驶，但电池可能很重，造价可能很昂贵，充电的时间可能很长，这些都可能成为阻碍人们选择电动汽车的理由，所以，不排除长距离行车还用汽油或柴油，因此为了确保减少污染，燃料的使用效率必须提高，废气的排放必须减少。
长久以来，汽车作为人类重要的交通工具与我们相伴相随，人类也为此付出了巨大的代价。2050年，如果汽车还是我们生活中不可缺少的伴侣，它在我们的经济生活中还扮演支柱产业的角色，它必须是清洁的、安全的，它必须符合可持续发展的原则。
