* 热身

** 1
:PROPERTIES:
:ID: f6c55726-ab41-45df-9eee-3e241819f572
:END:

*** 1

**** 词语

客厅

**** 答案

d

*** 2

**** 词语

猜

**** 答案

c

*** 3

**** 词语

复杂

**** 答案

e

*** 4

**** 词语

阅读

**** 答案

b

*** 5

**** 词语

杂志

**** 答案

a

*** 6

**** 词语

笔记

**** 答案

f

* 课文1
:PROPERTIES:
:CREATED: [2022-07-06 19:53:26 -05]
:END:

** 1

*** 标题

马克介绍自己学习汉语的方法

*** 对话

大卫：你来中国才一年，汉语就说得这么琉璃，真厉害！
马克：谢谢！其实我的语法不太好，很多句子说得都不太准确。
大卫：但是我看你跟中国人交流没什么问题，你是怎么做到的？
马克：平时多交一些中国朋友，经常和他们聊天儿，听说能力自然就能得到很大的提高。另外，我建议你坚持看中文报纸，这样能学到很多新词语。
大卫：你太厉害了！连中文报纸都看得懂。
马克：刚开始肯定有困难，不过遇到不认识的词语，你可以查词典，然后写在本子上，有空儿就拿出来复习一下，慢慢地就会发现中文报纸也没那么难了。

**** 对我生词

方法 🟦 fang1 fa3 🟦 method ;
交流 🟦 jiao1 liu2 🟦 to communicate ;
平时 🟦 ping2 shi2 🟦 normal times ;
自然 🟦 zi4 ran2 🟦 naturally ;
另外 🟦 ling4 wai4 🟦 in addition to ;
建议 🟦 jian4 yi4 🟦 to advice ;
坚持 🟦 jian1 chi2 🟦 to persist ;
肯定 🟦 ken3 ding4 🟦 definitely ;
困难 🟦 kun4 nan 🟦 difficult ;
查 🟦 cha2 🟦 to look up ;
词典 🟦 ci2 dian3 🟦 dictionary ;
本子 🟦 ben3 zi 🟦 notebook ;
空儿 🟦 kong4 r 🟦 spare time ;
*** 生词

1. 琉璃 🟦 liu2li4 🟦 adj. fluent ;
2. 厉害 🟦 li4hai 🟦 adj. awesome, serious ;
3. 语法 🟦 yu3fa3 🟦 n. grammar ;
4. 准确 🟦 zhun3que4 🟦 adj. accurate, precise ;
5. 词语 🟦 ci2yu3 🟦 n. word, expression ;
6. 连 🟦 lian2 🟦 prep. even ;

*** 专有名词

大卫 🟦 Da4wei4 🟦 name of a person ;

** 2

*** 标题

小夏和小雨聊考试的情况

*** 对话

小夏：考试结束了，你对自己的成绩满意吗？
小雨：说真的，我不太满意。这次阅读考试的题太多了，我没做完。
小夏：两个小时的时间应该来得及吧？
小雨：这次主要是因为为我先做了比较难、比较复杂的题，结束花了太多时间，后面简单的题我虽然会，可是时间来得及，最后只好放弃了。
小夏：其实我考得也不怎么样。有几个天空题不会做，有几个选择题，实在想不出来该选哪个，就随便猜猜了一个答案，结果一个都没猜对。
小雨：看来要想考好，不但要认真复习，还得注意考试的方法，否则，会做的题也没时间做了。

**** 对我生词

情况 🟦 qing2 kuang4 🟦 situation ;
成绩 🟦 cheng2 ji4 🟦 grade ;
满意 🟦 man3 yi4 🟦 to be satisfied ;
主要 🟦 zhu3 yao4 🟦 main ;
放弃 🟦 fang4 qi4 🟦 to give up ;
随便 🟦 sui2 bian4 🟦 random ;
结果 🟦 jie2 guo3 🟦 result ;
注意 🟦 zhu4 yi4 🟦 to pay attention to ;
方法 🟦 fang1 fa3 🟦 method ;

*** 生词

7. 阅读 🟦 yue4du2 🟦 v. to read ;
8. 来得及 🟦 lai2deji2 🟦 v. there's still time (to do sth.) ;
9. 复杂 🟦 fu4za2 🟦 adj. complicated ;
10. 只好 🟦 zhi3hao3 🟦 adv. cannot but, to be forced to ;
11. 天空 🟦 tian2 kong4 🟦 v. to fill in a blank ;
12. 猜 🟦 cai1 🟦 v. to guess ;
13. 否则 🟦 fou3ze2  🟦 conj. or, otherwise ;

** 3

*** 标题

小李告诉小林阅读的好处

*** 对话

小林：你的客厅里怎么到处是书啊？这些书你都喜欢看吗？
小李：当然，我每天都要看书。无论是普通杂志，还是著名小说，只要打开它们，就会发现，世界上有那么多有意思的事情，有那么多不一样的生活。
小林：想不到你工作那么忙，还能每天坚持阅读。
小李：如果3分钟一页书，半个小时就可以读10页。每天花半个小时来读书，一个月就可以读300页，差不多就是一本书了。
小林：是啊，一个真正爱看书的人总能接找出时间来阅读。
小李：坚持阅读，除了能增加知识外，还能帮助我减轻压力，人也会变得轻松起来。

**** 对我生词

阅读 🟦 yue4 du2 🟦 to read ;
好处 🟦  hao3 chu4 🟦 advantage ;
普通 🟦 pu3 tong1 🟦 common ;
坚持 🟦 jian1 chi2 🟦 persist ;
差不多 🟦 cha4 bu duo1 🟦 almost ;
轻松 🟦 qing1 song1 🟦 to relax ;

*** 生词

14. 客厅 🟦 ke4ting1 🟦 n. living room ;
15. 无论 🟦 wu2lun4 🟦 conj. regardless of, no matter (what, how, when, etc.) ;
16. 杂志 🟦 za2zhi4 🟦 n. magazine ;
17. 著名 🟦 zhu4ming2 🟦 adj. famous, well-known ;
18. 页 🟦 ye4 🟦 m. page ;
19. 增加 🟦 zeng1jia1 🟦 v. to increase, to add ;
* 课文2

** 4

*** 段话

根据调查，阅读能力好的人，但是容易找到工作，而且工资也比较高。怎么才能有效提高自己的阅读能力呢？做读书笔记就是其中一种好方法。读书笔记有很多种，最简单的就是把自己喜欢或者觉得有用的词语和句子记下来。另外，在看完一篇文章或一本书之后，还可以把它的主要内容和自己的想法写下来。然而，你不能完全相信书本上的内容，要有自己的看法和判断。坚持做读书笔记，对提高阅读能力有很大帮助。

**** QUESTION “看法”和“想法”有什么区别？
:PROPERTIES:
:CREATED: [2022-07-06 22:18:59 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-06 Wed 22:19]
:END:

**** 对我生词

根据 🟦 gen1 ju4 🟦 according to ;
调查 🟦 dao4 cha2 🟦 survey ;
阅读 🟦 yue4 du2 🟦 to read ;
有效 🟦 you3 xiao4 🟦 effective ;
能力 🟦 neng2 li4 🟦 capability ;
工资 🟦 gong1 zi1 🟦 wages ;
其中 🟦 qi2 zhong1 🟦 among ;
有用 🟦 you3 yong4 🟦 useful ;
内 🟦 nei4 🟦 within ;
想法 🟦 xiang3 fa3 🟦 notion ;
判断 🟦 pan4 duan4 🟦 to judge ;
坚持 🟦 jian1 chi2 🟦 to persist ;
笔记 🟦 bi3 ji4 🟦 notes ;

*** 生词

20. 文章 🟦 wen2 zhang1 🟦 n. essay, article ;
21. 之 🟦 zhi1 🟦 part. /connecting the modifier and the word modified/ ;
22. 内容 🟦 nei4 rong2 🟦 n. content ;
23. 然而 🟦 ran2 ' er2 🟦 conj. but, however ;
24. 看法 🟦 kan4 fa3 🟦 n. viewpoint, opinion ;

** 5

*** 段话

“读书好(hǎo)，读好(hǎo)书，好读书(hào)”。虽然这句话只用了三个相同的汉字，但是不同的顺序却表示了同的意思。首先，“读书好”说的是读书有很多好处；其次，每个人的时间都是有限的，不可能把世界上没一本书都读完，所以要读好的书；最后，”好读书“就是要养成阅读的习惯，便读书真正成为自己的兴趣爱好。阅读有许多好处，它能丰富你的知识，让你找到解决问题的办法；同时，它还会丰富你的情感，使你的生活更精彩。所以，让阅读成为你的习惯吧！

**** 对我生词

首先 🟦 shou3 xian1 🟦 in the first place ;
好处 🟦  hao3 chu4 🟦 advantage ;
限 🟦 xian4 🟦 limit ;
成为 🟦 cheng2 wei2 🟦 to become ;
知识 🟦 zhi3 shi 🟦 knowledge, intellectual ;
丰富 🟦 feng1 fu4 🟦 to enrich ;
情感 🟦 qing2 gan3 🟦 emotion, feeling ;

*** 生词

25. 相同 🟦 xiang1tong2 🟦 adj. same ;
26. 顺序 🟦 shun4xu4 🟦 n. order, sequence ;
27. 表示 🟦 biao3shi4 🟦 v. to express, to indicate ;
28. 养成 🟦 yang3cheng2 🟦 v. to develop, to form ;
29. 同时 🟦 tong2shi2 🟦 conj. at the same time, meanwhile ;
30. 精彩 🟦 jing1cai3 🟦 adj. wonderful, splendid ;

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: 4e73d86d-f955-4ff1-91d7-d4647226775b
:END:

**** 选择

***** 1

著名

***** 2

有限

***** 3

复杂

***** 4

顺序

***** 5

增加

**** 题

***** 1

****** 段话填空

为了保证您和他人的安全，请您按照”先下后上“的🟦上下车。

****** 答案

顺序

***** 2

****** 段话填空

科学的发展确实给生活带来了许多方便，但也给我们🟦了不少烦恼。

****** 答案

增加

***** 3

****** 段话填空

虽然身高只有一米六零，但他却是世界上🟦的篮球运动员。

****** 答案

著名

***** 4

****** 段话填空

这个问题有点儿🟦，你耐心听我给你解释一下，好吗？

****** 答案

复杂

***** 5

****** 段话填空

一个人的知识是🟦，所以人与人之间需要交流，交流能能使我们丰富知识、提高能力。

****** 答案

有限


*** 6-10
:PROPERTIES:
:ID: 7d06d4b1-9704-4930-9a92-28c1d17debfe
:END:

**** 选择

***** 1

准确

***** 2

只好

***** 3

厉害

***** 4

词语

***** 5

内容

**** 题

***** 6

****** 对话填空

Ａ：大夫，我的牙最近疼得🟦，不知道是怎么回事。
Ｂ：你先躺这儿，张开嘴我看看。

****** 答案

厉害

***** 7

****** 对话填空

Ａ：你家的孩子真可爱，会说话了吗？
Ｂ：会叫“爸爸”“妈妈”了，也能说一些简单的🟦。

****** 答案

词语

***** 8

****** 对话填空

Ａ：这是复习材料，复习要注意方法，要复习重要内容。
Ｂ：时间可能来不及，不过🟦这样了，这些语法知识太难了。

****** 答案

只好

***** 9

****** 对话填空

Ａ：听说公司明年要搬，到时候我又得重新找房子了。
Ｂ：这个消息🟦吗？我怎么不知道？

****** 答案

谁确

***** 10

****** 对话填空

Ａ：你看过那位怎家的小说吗？他的小说语言幽默，🟦丰富。
Ｂ：那当然了，他在国内很受欢迎，他的小说已经被翻译成了好几种语言。

****** 答案

内容


* 注释

** 3

*** 比一比

**** 做一做

***** 词语

****** 1

无论

****** 2
:PROPERTIES:
:ID: 5a4400ba-9519-40c9-83f2-2d1346f6e8a3
:END:

不管

***** 题

****** 1
:PROPERTIES:
:ID: 0bf53b65-93ce-4e26-be0f-a1c0d118dd1d
:END:

******* 课文

🟦别人说什么，我只相信自己眼睛看见的东西。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: 83e348de-c1d4-43be-af8a-0f848510a70a
:END:

******* 课文

🟦去不去，最后都别忘了告诉我一声。

******* 答案

******** 1

0

******** 2

1

****** 3
:PROPERTIES:
:ID: 8aa72fdf-7f27-448e-ba43-8710060d2f4f
:END:

******* 课文

🟦是工作还是学习，“光说不练”都是不行的。

******* 答案

******** 1

1

******** 2

1

****** 4
:PROPERTIES:
:ID: b42a021a-033c-443e-9394-61606c34262e
:END:

******* 课文

虽然压力很大，但是为了我们共同的理想，🟦如何一定不能放弃。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: 5a49a15c-69b5-47d1-ab2a-909a28684e45
:END:

******* 课文

妲光、空气和水，🟦是对动植物，还是对人来说，这三样东古都是不可缺少的。

******* 答案

******** 1

1

******** 2

1

* 扩展

** 做一做
:PROPERTIES:
:ID: cb95aa6c-2b6c-4028-a7b7-419cb9e644fc
:END:

*** 选择

**** 1

同意

**** 2

共同

**** 3

相同

**** 4

同时

*** 题

**** 1

***** 内容填空

幽默是成功者的🟦特点之一，也是值得我们好好学习的一种生活态度。

***** 答案

****** 1

共同

**** 2

***** 内容填空

Ａ：网上买衣服没法试穿，大小不合适怎么办？
Ｂ：没关系，号码不合适的话，店家一般都会🟦换的。

***** 答案

****** 1

同意

**** 3

***** 内容填空

医生建议大家冬季在选择合适的锻炼方法的🟦，应该注意运动量不要太大。

***** 答案

****** 1

同时

**** 4

***** 内容填空

中国小孩子的小名一般都比较好听好记，而且很多都是两个🟦的字，比如“乐乐”笑笑“聪聪”等。

***** 答案

****** 1

相同

