* 热身

** 1
:PROPERTIES:
:ID: 6691b9d9-32ad-4d85-8974-30db2a886253
:END:

*** 1

**** 词语

温度

**** 答案

f

*** 2

**** 词语

地球

**** 答案

e

*** 3

**** 词语

垃圾桶

**** 答案

a

*** 4

**** 词语

速度

**** 答案

d

*** 5

**** 词语

污染

**** 答案

b

*** 6

**** 词语

塑料袋

**** 答案

c

* 课文1
:PROPERTIES:
:CREATED: [2022-07-08 19:25:04 -05]
:END:

** 1

*** 标题

李进要出差，王静和李进在聊天儿

*** 对话

王静：这是明天你出差要带的毛巾，牙膏和牙刷，把它们放到
李进：不用拿这些，宾馆都会免费提供的。再说，箱子已经够重的了！
王静：我当然知道宾馆里有。你不是一直说要保护环境吗？现在就从身边的小事做起吧。
李进：行，没问题。我明天上午10点的飞机，你能开车把我送到机场吗？
王静：那个时间路上堵车多严重啊！你还时坐地铁去机吧。这样不仅省油钱，而且还不会不会污染空气。
李进：好，拿就听你的。

**** QUESTION Does 箱子 means box or suitcase?
:PROPERTIES:
:CREATED: [2022-07-08 19:30:08 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-08 Fri 19:30]
:END:

**** 对我生词

牙刷 🟦 ya2 shua1 🟦 toothbrush ;
箱子 🟦 xiang1 zi 🟦 box, suitcase ;
免费 🟦 mian3 fei4 🟦 free ;
保护 🟦 bao3 hu4 🟦 to protect ;
环境 🟦 huan2 jing4 🟦 environment ;
空气 🟦 kong1 qi4 🟦 air ;

*** 生词

1. 出差 🟦 chu1chai1 🟦 v. to go on a business trip ;
2. 毛巾 🟦 mao2jin1 🟦 n. towel ;
3. 牙膏 🟦 ya2gao1 🟦 n. toothpaste ;
4. 重 🟦 zhong4 🟦 adj. heavy, weighty ;
5. 行 🟦 xing2 🟦 v. to be ok, to be all right ;
6. 省 🟦 sheng3 🟦 v. to save, to economize ;
7. 污染 🟦 wu1ran2 🟦 v. to pollute ;

** 2

*** 标题

经理和服务员在谈工作

*** 对话

经理：小王，卫生间怎么那么脏啊？这会给客人留下不好的印象，快去打扫一下。
服务员：经理，买在抱歉。今天店里太忙了，我还没来得及打扫。
经理：那张桌子下面还有一些空饮料瓶子和纸盒子。
服务员：好的，我马上就去把他们扔掉。
经理：以后你一定就注意这个问题，不管客人多多，生意多忙，我们都要保证餐厅干净卫生。
服务员：经理您放心，我一定以最快的速度完成。不过咱们真的应该再多招聘几个服务员了。


**** QUESTION “客人”和“顾客”有什么区别？
:PROPERTIES:
:CREATED: [2022-07-08 19:42:44 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-08 Fri 19:42]
:END:

**** 对我生词

谈 🟦 tan2 🟦 to discuss ;
印象 🟦 yin4 xiang4 🟦 impression ;
瓶子 🟦 ping2 zi 🟦 bottle ;
纸 🟦 zhi3 🟦 (classifier for documents, letter, etc.)
生意 🟦 sheng1 yi 🟦 business ;
保证 🟦 bao3 zheng4 🟦 to guarantee ;
餐厅 🟦 can1 ting1 🟦 restaurant ;
卫生 🟦 wei4 sheng1 🟦 hygiene ;
招聘 🟦 zhao1 pin4 🟦 to recruit ;
咱们 🟦 zan2 men 🟦 (dialect) (in a coaxing or familiar way) you (

*** 生词

8. 卫生间 🟦 wei4sheng1jian1 🟦 n. restroom, bathroom ;
9. 脏 🟦 zang1 🟦 adj. dirty ;
10. 抱歉 🟦 bao4qian4 🟦 v. to be sorry ;
11. 空 🟦 kong1 🟦 adj. empty ;
12. 盒子 🟦 he2zi 🟦 n. box, case ;
13. 扔 🟦 reng1 🟦 v. to throw away ;
14. 以 🟦 yi3 🟦 prep. via, by means of ;
15. 速度 🟦 su4du4 🟦 n. speed ;
** 3

*** 标题

孙月和王静在聊关于环保的事情

*** 对话

孙月：早上听新闻说明天有一个叫“地球一小时”的活动，你对这个活动了解吗？
王静：这个活动年年都有，最早是从2007年开始的。明天晚上很多人都会关灯一小时，支持这个活动。你没看到门口的通知吗？我们公司也参加。
孙月：真的吗？太好了！既然明天晚上公司会关灯停电，那么我们肯定不用加班了。
王静：看你得意的样子！还以为你高兴是为了支持环保，原来是因为不用加班啊！
孙月：环境保护我当然也支持了！对了，为什么会有这么一个活动啊？
王静：其实目的挺简单的，就是提醒人们节约用电，希望引起人们对气候变暖问题的关注。

**** 对我生词

环保 🟦 huan2 bao3 🟦 environmental protection ;
了解 🟦 liao3 jie3 🟦 to know ;
支持 🟦 zhi1 chi2 🟦 support ;
通知 🟦 tong1 zhi1 🟦 to inform ;
肯定 🟦 ken3 ding4 🟦 definitely ;
加班 🟦 jia1 ban1 🟦 to work overtime ;
保护 🟦 bao3 hu4 🟦 to protect ;
提醒 🟦 ti2 xing3 🟦 to remind ;
节约 🟦 jie2 yue1 🟦 to conserve (resources) ;
引起 🟦 yin3 qi3 🟦 to cause ;
气候 🟦 qi4 hou4 🟦 climate ;
关注 🟦 guan1 zhu4 🟦 concern ;

*** 生词

16. 地球 🟦 di4qiu2 🟦 n. earth, globe ;
17. 既然 🟦 ji4ran2 🟦 conj. since, as, now that ;
18. 停 🟦 ting2 🟦 v. to stop, to cease ;
19. 得意 🟦 de2yi4 🟦 adj. complacent, gloating ;
20. 目的 🟦 mu4di4 🟦 n. aim, purpose ;
21. 暖 🟦 nuan3 🟦 adj. warm ;

* 课文2

** 4

*** 段话

塑料袋给人们的生活带来方便，受到人们的普遍欢迎，可是，它的大量使用也带来了严重的环境污染问题。于是，一些国家规定，超市，商场拒绝不能为顾客提供免费塑料袋，并且鼓励大家购买可以多次使用的购物袋。我们每个人都有责任保护环境，因此，请大家节约使用塑料袋，或者购物时自备购物袋，甚至拒绝使用塑料袋。虽然这是一样很小的事，但这样做可以减少塑料袋的使用数量，对环境保护有很大的作用。

**** 对我生词

受到 🟦 shou4 dao4 🟦 to receive ;
于是 🟦 yu2 shi4 🟦 as a result ;
规定 🟦 gui1 ding4 🟦 to regulate ;
并且 🟦 bing4 qie3 🟦 furthermore, in addition ;
购物袋 🟦 gou4 wu4 dai4 🟦 shopping bag ;
责任 🟦 ze2 ren4 🟦 responsibility ;
保护 🟦 bao3 hu4 🟦 to protect ;
因此 🟦 yin1 ci3 🟦 therefore, so ;
节约 🟦 jie2 yue1 🟦 to conserve (resources) ;
自备 🟦 zi4 bei4 🟦 self-contained ;
甚至 🟦 shen4 zhi4 🟦 even ;
数量 🟦 shu4 liang4 🟦 amount ;
作用 🟦 zuo4 yong4  🟦 effect ;

*** 生词

22. 塑料袋 🟦 su4liao4dai4 🟦 n. plastic bag ;
23. 于是 🟦 yu2shi4 🟦 conj. hence, therefore ;
24. 鼓励 🟦 gu3li4 🟦 v. to encourage ;
25. 拒绝 🟦 ju4jue2 🟦 v. to refuse, to reject ;
26. 减少 🟦 jian3shao3 🟦 v. to reduce, to decrease ;
27. 数量 🟦 shu4liang4 🟦 n. quantity, amount ;
** 5

*** 段话

保护地球环境，并不是一样离我们很远，很难做到的事情。实际上，我们只需注意一下身边的小事就可以。例如，夏天把空调的温度开得高一些，出门时记得关空调和电脑，这样可以节约用电；少开车，多骑车或者乘坐地铁和公共汽车，这样能降低空气污染；还有养成把垃圾丢进垃圾桶的习惯什么的。这些是我们每个人都能够做到的小事，但却有实实在在的效果。地球是我们共同的家，只有大家共同努力，减少污染，保护环境，才能使我们的家变得更美丽。

**** 对我生词

地球 🟦 di4 qiu2 🟦 earth, globe ;
实际 🟦 shi2 ji4 🟦 reality ;
例如 🟦 li4 ru2 🟦 for example ;
空调 🟦 kong1 tiao2 🟦 air conditioner ;
节约 🟦 jie2 yue1 🟦 to conserve (resources) ;
降低 🟦 jiang4 di1 🟦 to reduce ;
空气 🟦 kong1 qi4 🟦 air ;
污染 🟦 wu1 ran2 🟦 to pollute ;
养成 🟦 yang3 cheng2 🟦 to form (a habit) ;
垃圾 🟦 la1 ji1 🟦 garbage ;
小事 🟦 xiao3 shi4 🟦 trivial matter ;
效果 🟦 xiao4 guo3 🟦 effect ;
共同 🟦 gong4 tong2 🟦 collaborative ;
减少 🟦 jian3 shao3 🟦 to reduce ;

*** 生词

28. 温度 🟦 wen1du4 🟦 n. temperature ;
29. 乘坐 🟦 cheng2zuo4 🟦 v. to take (a vehicle), to ride (in a vehicle) ;
30. 丢 🟦 diu1 🟦 v. to throw, to cast ;
31. 垃圾桶 🟦 la1ji1tong3 🟦 n. dustbin, trash can ;
32. 美丽 🟦 mei3li4 🟦 adj. beautiful ;
* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: 394e8c18-a730-4f84-a8cf-827c36a26a59
:END:

**** 选择

***** 1

拒绝

***** 2

鼓励

***** 3

得意

***** 4

省

***** 5

重（zhòng）

**** 题

***** 1

****** 段话填空

为了🟦大家少抽烟，人们将每年的4月7日定为“世界无烟日”。

****** 答案

鼓励

***** 2

****** 段话填空

有的人总是不好意思🟦朋友的要求，害怕这样会影响两个人的感情。

****** 答案

拒绝

***** 3

****** 段话填空

按照规定，您只能免费带20公斤的行李，超🟦的部分每公斤加收全部票价的1.5％。

****** 答案

重

***** 4

****** 段话填空

不要因一时的成功而🟦，也不要因一时的失败而伤心，因为那些都已经过去，重要的是怎样过好将来的生活。

****** 答案

得意

***** 5

****** 段话填空

山东🟦烟台市是中国著名的“苹果之都”。由于气候等自然条件较好，那儿的苹果个儿大味道香甜，颜色也漂亮。

****** 答案

省

*** 6-10
:PROPERTIES:
:ID: 4f20c9bb-8fc4-48f4-bca8-d4650970c3ca
:END:

**** 选择

***** 1

扔

***** 2

丢

***** 3

行

***** 4

出差

***** 5

抱歉

**** 题

***** 6

****** 对话填空

Ａ：打扰一下，请问李老师在吗？
Ｂ：他🟦了。你找他有事吗？

****** 答案

出差

***** 7

****** 对话填空

Ａ：喂，你还在逛街吗？我的钥匙🟦了，进不了门，你快回来吧。
Ｂ：好，我马上就回去。

****** 答案

丢

***** 8

****** 对话填空

Ａ：实在🟦，我来晚，晚了。今天路上有点儿堵。
Ｂ：没关系，请坐。你喝果计还是咖啡？

****** 答案

抱歉

***** 9

****** 对话填空

Ａ：垃圾桶又满了，你去🟦一下垃圾吧。
Ｂ：好的，看完这个节目我就去。

****** 答案

扔

***** 10

****** 对话填空

Ａ：马上就要毕业了，你准备在学校附近租房子吗？
Ｂ：学校附近房子太贵。离学校远点儿没关系，只要离地铁或者公交车站近就🟦。

****** 答案

行

* 注释

** 4

*** 比一比

**** 做一做

***** 词语

****** 1

于是

****** 2
:PROPERTIES:
:ID: 4c9d43cf-d582-4357-a808-369096661dd9
:END:

因此

***** 题

****** 1
:PROPERTIES:
:ID: b43aa296-1a36-4d7f-b140-84d53d0d8d52
:END:

******* 课文

有些年轻人申请了信用卡，但在购物时却没有考虑自己的经济能力，最后不能按时还银行的钱，🟦出现严重的信用问题。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: 36d76701-410e-4e33-9425-72c1012e16f4
:END:

******* 课文

习惯是不容昒改变的，🟦，在孩子小的时候，父母要帮他们养成好的生活、学习习惯。

******* 答案

******** 1

0

******** 2

1

****** 3
:PROPERTIES:
:ID: 986f73d2-4543-425b-a2de-22c671a5878e
:END:

******* 课文

不少人刚开始运动时，会感觉十分无聊，🟦很快就放弃了。

******* 答案

******** 1

1

******** 2

1

****** 4
:PROPERTIES:
:ID: 5425b1bb-59cd-4d4b-b036-e36fb37f0f57
:END:

******* 课文

那是1994年的冬天，那场雪下得特别大。大家都很激动，🟦都跑到外面去玩儿雪。

******* 答案

******** 1

1

******** 2

0

****** 5
:PROPERTIES:
:ID: a2bbc231-017d-4cc1-a3af-d564349b2348
:END:

******* 课文

生活往往不会按照我们的计划来进行。🟦，光有计划还不行，还需要我们能及时地对原来的计划做出改变。

******* 答案

******** 1

0

******** 2

1

* 扩展

** 做一做
:PROPERTIES:
:ID: e0b991ca-e680-4345-9e24-62f9a11954c2
:END:

*** 选择

**** 1

速度

**** 2

温度

**** 3

态度

*** 题

**** 1

***** 内容填空

这个月底，我和丈夫准备开车去长白山，那边🟦比较低，所以要提前准备几件厚一些的衣服。

***** 答案

****** 1

温度

**** 2

***** 内容填空

Ａ：小张，你有什么意见？
Ｂ：按照现在的🟦，想要在规定时间内完成计划，好像有点儿困难。

***** 答案

****** 1

速度

**** 3

***** 内容填空

幽默是一仲积极的生活🟦，不但可以减轻你工作上的压力，还可以拉近人与人之间的距离。

***** 答案

****** 1

态度

