* 热身

** 1
:PROPERTIES:
:ID: 5f55db35-0faf-4a55-8a26-6a5a595b64bc
:END:

*** 1

**** 词语

赶时间

**** 答案

c

*** 2

**** 词语

害羞

**** 答案

b

*** 3

**** 词语

打针

**** 答案

e

*** 4

**** 词语

闹钟

**** 答案

a

*** 5

**** 词语

敲门

**** 答案

f

*** 6

**** 词语

弹钢琴

**** 答案

d

* 课文1
:PROPERTIES:
:CREATED: [2022-07-09 06:03:40 -05]
:END:

** 1

*** 标题

李老师建议王静让孩子养成好习惯

*** 对话

王静：那个一边弹钢琴一边唱歌的男孩子是谁？表演真的棒！
李老师：是我孙子。去年寒假前的新年晚会他也
王静：我想起来了，这孩子又聪明又可爱，你们教育得真好。
李老师：是他父母教育得好。父母是孩子最重要的老师。他父母不仅教他知识，而且还花了很长时间帮助他养成了非常好的习惯，现在他每天都自己练习弹钢琴。
王静：让孩子养成一个好习惯实在太重要了。看来我的向他父母好好儿学习。
李老师：对。如果希望有一个优秀的孩子，你就要先成为一位优秀的父亲或者母亲。

**** 对我生词

建议 🟦 jian4 yi4 🟦 to recommend ;
养成 🟦 yang3 cheng2 🟦 to form (a habit) ;
习惯 🟦 xi2 guan4 🟦 habit ;
表演 🟦 biao3 yan3 🟦 to perform ;
教育 🟦 jiao4 yu4 🟦 to educate ;
优秀 🟦 you1 xiu4 🟦 excellent ;

*** 生词

1. 弹钢琴 🟦 tan2 gang1qin2 🟦 to play the piano ;
2. 棒 🟦 bang4 🟦 adj. excellent, amazing ;
3. 孙子 🟦 sun1zi 🟦 n. grandson ;
4. 寒假 🟦 han2jia4 🟦 n. winter vacation ;
5. 父亲 🟦 fu4qin1 🟦 n. father ;


** 2

*** 标题

王静建议孙月教育孩子学会安排时间

*** 对话

王静：看你脸色不太好，是不是昨晚没休息好？
孙月：别提了。我女儿昨晚做作业又做到11点。
王静：睡觉太晚对孩子的身体没有好处。最近孩子作业是不是太多了？
孙月：主要是她做事情比较慢，比如早上闹钟响了她不醒，我赶时间送她上学，她又着急上厕所。每天因为这些小事批评她，弄得我俩心情都不好。
王静：孩子做事慢，往往是因为他们不会安排自己的时间。你应该让孩子学会管理时间。
孙月：看来这是我的教育方法有问题。平时看她做事情慢，总想替她做，以后得让她学会安排时间，自己的事情自己做。

**** QUESTION 说”别提了”是不礼貌吗？
:PROPERTIES:
:CREATED: [2022-07-09 06:21:28 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-09 Sat 06:22]
:END:

**** 对我生词

建议 🟦 jian4 yi4 🟦 to advice ;
教育 🟦 jiao4 yu4 🟦 to educate ;
学会 🟦 xue2 hui4 🟦 to learn ;
安排 🟦 an1 pai2 🟦 to arrange ;
脸色 🟦 lian3 se4 🟦 look ;
好处 🟦  hao3 chu4 🟦 benefit ;
主要 🟦 zhu3 yao4 🟦 main ;
心情 🟦 xin1 qing2 🟦 mood ;
往往 🟦 wang3 wang3 🟦 often ;
管理 🟦 guan3 li3 🟦 to administer ;

*** 生词

6. [X] 闹钟 🟦 nao4zhong1 🟦 n. alarm clock ;
7. 响 🟦 xiang3 🟦 v. to sound, to ring ;
8. 醒 🟦 xing3 🟦 v. to wake up, to be awake ;
9. 赶 🟦 gan3 🟦 v. to rush for, to hurry ;
10. 厕所 🟦 ce4suo3 🟦 n. lavatory, toilet ;
11. 批评 🟦 pi1ping2 🟦 v. to criticize ;
12. 弄 🟦 nong4 🟦 v. to do, to make ;
13. 管理 🟦 guan3li3 🟦 v. to manage, to administer ;
** 3

*** 标题

王静和孙月讨论表扬孩子的方法

**** QUESTION “谈”和“讨论”有什么区别？
:PROPERTIES:
:CREATED: [2022-07-09 06:28:45 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-09 Sat 06:28]
:END:

*** 对话

王静：明天又要带我儿子去医院打针，刚开始，她害怕得要哭。我就声地和护士说我女儿很勇敢，一点儿也不怕打针，女儿听了以后马上就不哭了。
孙月：原来鼓励和表扬对 小孩儿挺有用的，下次我也试试。
王静：不过表扬也是一门艺术，表扬千万不要太多，过多的表扬可能会给孩子带来压力。不仅起不到鼓励的作用，还可能让孩子怀疑自己的能力，变得没有信心。
孙月：那怎么表扬孩子才会更有效果呢？
王静：我认为表扬要及时，而且表扬不仅仅要看结果，更要看过程，这样才能鼓励他的积极性，让他变得勇敢，不怕困难。

**** QUESTION 为什么“效果”和“结果”有一样的意思？
:PROPERTIES:
:CREATED: [2022-07-09 06:42:10 -05]
:END:
:LOGBOOK:
- State "QUESTION"   from              [2022-07-09 Sat 06:42]
:END:

根据hanzii.net，这两单词的意思是“result".

**** 对我生词

讨论 🟦 tao3 lun4 🟦 to discuss ;
表扬 🟦 biao3 yang2 🟦 to commend ;
勇敢 🟦 yong3 gan3 🟦 courageous ;
鼓励 🟦 gu3 li4 🟦 to encourage ;
有用  🟦 you3 yong4 🟦 useful ;
艺术 🟦 yi4 shu4 🟦 art ;
压力 🟦 ya1 li4 🟦 pressure ;
作用 🟦 zuo4 yong4 🟦 effect, impact, function ;
信心 🟦 xin4 xin1 🟦 confidence ;
效果 🟦 xiao4 guo3 🟦 result ;
结果 🟦 jie2 guo3 🟦 result ;
积极性 🟦 ji1 ji2 xing4 🟦 enthusiasm ;

*** 生词

14. 打针 🟦 da3zhen1 🟦 v. to give or have an injection ;
15. 护士 🟦 hu4shi 🟦 n. nurse ;
16. 表扬 🟦 biao3yang2 🟦 v. to praise, to commend ;
17. 千万 🟦 qian1wan4 🟦 adv. must, to be sure to ;
18. 怀疑 🟦 huai2yi2 🟦 v. to suepct, to doubt ;
* 课文2

** 4

*** 段话

有的孩子在得不到自己想要的东西的时候，会通过哭、扔东西或者故意敲打来引起父母的注意。在这种情况下，建议父母先不要生气，应该停下手中的事情，陪孩子整理整理东西，和他们聊聊天儿，弄清楚他们的问题。父母的关心，可以让孩子心情愉快起来。教育孩子应该选择合适的教育方法，最好不要为了解决问题而骗孩子，这是因为儿童少判断能力，看到父母骗人，他们也会学着说假话。

**** 对我生词

通过 🟦 tong2 guo4 🟦 through, by means of ;
情况 🟦 qing2 kuang4 🟦 situation ;
建议 🟦 jian4 yi4 🟦 to advice ;
弄 🟦 nong4 🟦 to manage ;
关心 🟦 guan1 xin1 🟦 to be concerned about, to care about ;
心情 🟦 xin1 qing2 🟦 mood ;
判断 🟦 pan4 duan4 🟦 to judge ;
假话 🟦 jia1 hua4 🟦 a lie ;

*** 生词

19. 故意 🟦 gu4yi4 🟦 adv. intentionally, on purpose ;
20. 敲 🟦 qiao1 🟦 v. to knock, to beat, to strike ;
21. 整理 🟦 zheng3li3 🟦 v. to tidy up, to arrange ;
22. 合适 🟦 he2shi4 🟦 adj. fit, suitable ;
23. 骗 🟦 pian4 🟦 v. to cheat, to deceive ;
24. 儿童 🟦 er2tong2 🟦 n. children ;
25. 假 🟦 jia3 🟦 adj. false, fake ;

** 5

*** 段话

七岁左右的儿童普好动，坐不住，所以老师在教这个年龄的孩子时，一定要想办法引起他们的兴趣。只有让他们觉得你教的内容有趣，他们才会愿意努力学习。当孩子不明白时，应该多鼓励她，不要用“懒”“笨”“粗心”这种词批评他，这样对对他们的正常发展不好。而且，对不同性格的孩子要使用不同的教育方法。如果孩子比较骄傲，应该让他明白还有很多知识需要学习；要是孩子性格有些害羞，就要经常鼓励他说出自己的看法，这样才能让每一个孩子都健康地发展。

**** 对我生词

儿童 🟦 er2 tong2 🟦 children ;
普遍 🟦 pu3 bian4 🟦 common ;
好动 🟦 hao4 dong4 🟦 energetic ;
年龄 🟦 nian2 ling2 🟦 (a person's age) ;
段 🟦 duan4 🟦 (used for certain sections or periods) ;
引起 🟦 yin3 qi3 🟦 to arouse ;
内容
鼓励 🟦 gu3 li4 🟦 to encourage ;
批评 🟦 pi1 ping2 🟦 to criticize ;
正常 🟦 zheng4 chang2 🟦 normal, regular ;
发展 🟦 fa1 zhan3 🟦 to grow ;
性格 🟦 xing4 ge2 🟦 personality ;

*** 生词

26. 左右 🟦 zuo3you4 🟦 n. around, or so ;
27. 懒 🟦 lan3 🟦 adj. lazy ;
28. 笨 🟦 ben4 🟦 adj. stupid, foolish ;
29. 粗心 🟦 cu1xin1 🟦 adj. careless, toughtless ;
30. 骄傲 🟦 jiao1ao4 🟦 adj. arrogant, conceited ;
31. 害羞 🟦 hai4xiu1 🟦 v. to be shy, to be timid ;

* 练习

** 2

*** 1-5
:PROPERTIES:
:ID: af3c6c94-b65d-4732-b7f1-c94ebf7172e0
:END:

**** 选择

***** 1

粗心

***** 2

表扬

***** 3

整理

***** 4

寒假

***** 5

批评

**** 题

***** 1

****** 段话填空

已经放🟦了，去打球的人肯定不多，星期天我们去字校的椎育馆打网球吧。

****** 答案

寒假

***** 2

****** 段话填空

这些只有三分之一吧，还有很多东西没来得及🟦呢，下周再搬。

****** 答案

整理

***** 3

****** 段话填空

如果遇到不得不🟦别人的时候，态度要友好上点儿，不要让别人听子心里不舒服。

****** 答案

批评

***** 4

****** 段话填空

他的优点是有礼貌、诚实，能吃苦，就是太🟦了，不适合我们这儿的工作。

****** 答案

粗心

***** 5

****** 段话填空

孩子在受到🟦时，往往会对自己更有信心，对学习的兴趣也会更大，成绩当然会提高。

****** 答案

表扬

*** 6-10
:PROPERTIES:
:ID: 5eaebb30-5399-4190-ba60-8cb6920f04a4
:END:

**** 选择

***** 1

响

***** 2

管理

***** 3

故意

***** 4

赶

***** 5

害羞

**** 题

***** 6

****** 对话填空

Ａ：因为那件事，他特别生我的气。
Ｂ：放心吧，你也不是🟦的，去跟她解释一下，她会理解的。

****** 答案

故意

***** 7

****** 对话填空

Ａ：你妹妹很可爱，但是好像不太爱说话。
Ｂ：他只是有点儿🟦，等跟大家熟悉子就好了。

****** 答案

害羞

***** 8

****** 对话填空

Ａ：这次大学同学聚会你联系得怎么样子？能来多少人？
Ｂ：大约有一半吧，李进还专门从国外🟦回来呢。

****** 答案

赶

***** 9

****** 对话填空

Ａ：桌子上那个一直在🟦的手机是谁的？可能找他有什么急事。
Ｂ：那是张经理的，他在会议室开会呢，你快把手机给他拿过去吧。

****** 答案

响

***** 10

****** 对话填空

Ａ：听说昨天那个招聘会提供了很多工作机会，你找到合适的公司了吗？
Ｂ：这个招聘会主要是为经济和🟦专业的学生举办的，所以没几个鸽适的。

****** 答案

管理

* 注释

** 3

*** 比一比

**** 做一做

***** 词语

****** 1

千万

****** 2
:PROPERTIES:
:ID: 6a78b9dd-a328-42f6-aa8c-b2be95848368
:END:

一定

***** 题

****** 1
:PROPERTIES:
:ID: 35401ddb-effb-4de9-b86b-5aeffcf6c43f
:END:

******* 课文

不管压力有多么大，🟦不能放弃，而是要继续坚持下去。

******* 答案

******** 1

1

******** 2

1

****** 2
:PROPERTIES:
:ID: f72a1669-2503-45fd-9938-01b5d81c9f21
:END:

******* 课文

哭并不🟦是件坏事，哭可以让人从坏心情中走出来，是一种减轻压力的好办法。

******* 答案

******** 1

0

******** 2

1

****** 3
:PROPERTIES:
:ID: db6f3a4b-e36f-4214-a286-f4e34e39aed0
:END:

******* 课文

这次你一定要按照要求认真填写，小心一点儿，🟦别写错了。

******* 答案

******** 1

1

******** 2

0

****** 4
:PROPERTIES:
:ID: 8a3b787c-d1ca-4a8e-87a3-a854aa1dd64c
:END:

******* 课文

兴趣是最好的老师，如果孩子对一件事情感兴趣，那他🟦会努力地去学习，效果也会更好。

******* 答案

******** 1

0

******** 2

1

****** 5
:PROPERTIES:
:ID: 3e1fc5ae-9e7f-4f99-b80a-468020728d77
:END:

******* 课文

事情的原因和结果往往是互相联系的。🟦的原因会引起一定的结果，有时候一件事情的结果可能又是另一件事情的原因。

******* 答案

******** 1

0

******** 2

1

* 扩展

** 做一做
:PROPERTIES:
:ID: 40382d9c-1450-42c2-8f76-38488cb07c16
:END:

*** 选择

**** 1

护照

**** 2

保护

**** 3

护士

*** 题

**** 1

***** 内容填空

冬季皮肤往往容易变得干燥，女性朋友尤其应该注意🟦皮肤要多吃水果，比如香蕉、苹果等等。

***** 答案

****** 1

保护

**** 2

***** 内容填空

爸爸说我小时候特别害怕打针，一看见医生就就哭，他怎么都没想到，我长磊后竟然会成为一名🟦。

***** 答案

****** 1

护士

**** 3

***** 内容填空

因为要申请去国外留学，她最近特别忙。一方面她要准备成绩证明办🟦，一方面还要跟国外的大学联系。

***** 答案

****** 1

护照

