* 听力

** 第二部分
:PROPERTIES:
:ID: 150a0e98-8121-4679-a4a4-dc5611738446
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：深圳显然是腾讯诞生的福地。如果当年的创业地址不是在深圳，挪个地方，您觉得今天又会是什么情形？
男：腾讯离不开深圳。对比中国的其他城市，我觉得深圳总体的创业环境还是更适合自主科技创新型的中小民营企业发展并取得成功，这一点毋庸置疑。那时候深圳的口号是“时间就是金钱，效率就是生命”。第一次听到这话，我真的很震惊：金钱居然可以拿来当口号提！但它的确会让人们对时间、效率的迫切感前所未有地提升。
女：您如何看待今天长大成人的腾讯？
男：我觉得机遇很重要，至少占了五成吧。我们也不觉得自己特别聪明，我们做的东西都很简单，大家都能做。但是好的团队、公司的股份结构和投资者的合理搭配，这是很重要的，否则也不会成功。当然，时代的因素也是非常重要的，很多机遇是外界给予的，我们觉得很幸运。
女：深圳汇聚了很多和您一样的知名企业家。在这个城市，您有什么感触？
男：深圳跟其他城市还不一样，那些地方要么有政策，要么有别的条件，在客观环境下能做起来，在深圳企业完全是靠自己做起来的。这里是创业的热土，相信创业者的这种感觉会强烈得多。这里需要有创业的心态，需要有闯劲儿，需要珍惜时间。
女：在闲暇时，您也会在这座城市的某个角落欣赏它的景致，或者享受某个美食城的招牌菜，或者看一场电影，过一下普通市民的生活吗？
男：我本来就是普通市民。平时我就是上网、看看杂志、看看书。QQ 和互联网对我来说已经不是工作了，更多的是一种爱好，是我生活的一部分。

**** 音频

289498a1-819a-4054-a01e-6733ac76e32d.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 5cce9e89-2d7d-47d2-881e-ac1bcca23990
:END:

***** 问题

关于深圳这座城市，下列哪项正确？

****** 音频

96d4c528-332e-41b0-8190-27ff43f1b642.mp3

***** 选择

****** A

这里政策好条件好

****** B

这里是创业的热土

****** C

没有人怀疑它的成功

****** D

城市对发展有迫切感

***** 答案

B

**** 7
:PROPERTIES:
:ID: 7f76a8e1-c861-40a8-9dd0-bf5ba1fe80b7
:END:

***** 问题

对于“时间就是金钱，效率就是生命”，男的持什么态度？

****** 音频

9b36eff3-c92e-443b-aece-bbacf8d4a2aa.mp3

***** 选择

****** A

怀疑

****** B

蔑视

****** C

反对

****** D

赞成

***** 答案

D

**** 8
:PROPERTIES:
:ID: 9466ec06-8c9c-4538-8e13-041205055c47
:END:

***** 问题

关于腾讯成长的有利因素，下列哪项正确？

****** 音频

d423085d-9cd0-4a55-9c3f-9f23df0ebf02.mp3

***** 选择

****** A

公司资金充裕

****** B

公司聪明人多

****** C

赶上了好时代

****** D

产品具有唯一性

***** 答案

C

**** 9
:PROPERTIES:
:ID: 71759b14-fabd-4e25-a913-a08dd42efb3e
:END:

***** 问题

男的在闲暇时会干些什么？

****** 音频

53174c15-67ed-4b85-a3c1-a6dccc7364aa.mp3

***** 选择

****** A

外出旅行

****** B

学做美食

****** C

拍摄电影

****** D

上网、看书

***** 答案

D

**** 10
:PROPERTIES:
:ID: de8f35de-ce70-475d-9759-d6f90102f65e
:END:

***** 问题

关于男的，下列哪项正确？

****** 音频

63310735-7fe5-4360-8ed4-154088157d91.mp3

***** 选择

****** A

他是知名的企业家

****** B

他闯过了无数难关

****** C

深圳是他的出生地

****** D

上下班都着迷于工作

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

说话人是个作家

***** B

说话人是打鱼的

***** C

说话人喜欢看小说

***** D

说话人是语言研究者

**** 段话

也许有人问，全国方言这么复杂，几万字的一本小书，够用吗？我们认为，在茫茫大海中，鱼网再大，也会有漏网之鱼。我们的网打算只捞与普通话不同的鱼。

***** 音频

ed354b35-5f2f-4325-969b-f7cd7095d4ff.mp3

**** 答案

D

*** 2

**** 选择

***** A

许大夫医术十分高明

***** B

请许大夫看病要多花钱

***** C

许大夫一家一家去找病人

***** D

许大夫是个走街丨巷的大夫

**** 段话

许大夫治病往往是一服药见效，三服药病就好，这种高手给人看病，我们觉得花多少钱都值。当碰上瘟疫来临的时候，许大夫就会拿上药挨家挨户去敲门，有患者马上免费治疗。

***** 音频

d5f7fbb4-731d-454c-9154-be9bfb604b1e.mp3

**** 答案

A

*** 3

**** 选择

***** A

家庭的影响是无形的

***** B

母亲是孩子快乐的源柳

***** C

应避免孩子负面情绪的蔓延

***** D

贫困与否不会对孩子造成影响

**** 段话

儿童情感起源于父母的抚爱和家庭温馨气氛的熏陶。如果在家庭中父母能互敬互爱，和睦相处，善于处理好自己的情绪，孩子就能够获得爱和尊重，快乐健康地成长。

***** 音频

3d631ed0-5f6e-41ac-ae39-029262b70ea1.mp3

**** 答案

A

*** 4

**** 选择

***** A

《城市旧事》表现了乡愁

***** B

中国电影很讲究“言志“

***** C

《城南旧事》充满了诗意

***** D

诗意的世界都是不现实的

**** 段话

《城南旧事》是中国新时期电影中少有的“言志”作品。这部弥漫着“淡淡的哀愁、沉沉的相思”的电影，用非常物质的东西编织出诗意的世界，又不失现实的真。

***** 音频

1cbcd46d-2b11-4c0f-8afe-ea72129b10b1.mp3

**** 答案

C

*** 5

**** 选择

***** A

中国的企业很有责任感

***** B

效率高的企业才能生存

***** C

中国资源人均占有率较低

***** D

资源贫乏是当今普道现象

**** 段话

中国是一个人均占有自然资源比较贫乏的国家，水资源、能源的危机随时都在冲击和影响一些企业的经济生产，同时森林资源人均占有率也不高。保护环境，充分利用有限的资源条件创造更多的社会经济效益，是每个企业应负的社会责任。

***** 音频

db42d0d0-ae6b-4c5c-b10d-32af75ad8574.mp3

**** 答案

C

** 第三部分

*** 11-13

**** 课文

落花在田野中孤独地飘零，寻找着能陪伴她一生的伴侣。流水静静地流淌，等待着能伴随他一世的朋友。

他们就这样寻找着。终于有一天，落花与流水相遇了。落花仰慕流水的英俊潇洒，胸怀博大。流水欣赏落花的美丽多姿，温柔体贴。他们彼此吸引，相互依恋，成为世间的一段佳话。

无奈，流水整日漂流不定。落花厌倦这种漂泊的生活，只盼能与爱人幸福相守。于是，他们开始争吵。

落花说：“你就不能为我停留一刻吗？”流水说：“这是我的天性，你就不能随我一起游遍大江南北吗？”落花说：“我想要的是安定的生活啊。”

流水低头不语，沉思良久，说：“以前的你是多么善解人意，温柔懂事，从不强迫我做任何事。你不是说过，我到哪儿，你就会随我到哪儿吗？”

落花愕然，抬头看着流水，流下了怨恨的泪水：“以前的你是多么无微不至，关爱有加，就算我想要天上的星星，你也会摘给我。”

吵了半天也没吵出个所以然，最终他们选择了分手。

**** 题目

***** 11

****** 选择

******* A

文雅多情

******* B

自私任性

******* C

不愿漂泊

******* D

风雅幽默

****** 问题

关于落花，可以知道什么？

***** 12

****** 选择

******* A

身体强壮

******* B

居无定所

******* C

会摘星星

******* D

天性好静

****** 问题

关于流水，可以知道什么？

***** 13

****** 选择

******* A

他们相依相恋,相守终生

******* B

他们都希望有安定的生活

******* C

他们不堪忍受生活的平淡

******* D

他们吵不出结果,分手了

****** 问题

关于落花、流水，下列哪项正确？

*** 14-17

**** 课文

如今，说一个人干净，是个极高的评价。

说一个男人干净，是说他对家人、对朋友、对同事胸怀坦荡，该负什么责任绝不躲躲闪闪，没有算计，没有欺瞒，不两面三刀，不见人说人话、见鬼说鬼话。在家里，他是好丈夫、好父亲；在单位，他是好部下、好同事、好上司；对朋友，他是可以交心的挚友。他不一定是社会名流，也不一定有巨额财富，他可能只是公交车上的一位普通男士，是风里来雨里去的为人父者，走入人群，他会立刻消失。但无数个这样的男人组合起来的家及社会，真实而平静。

说一个女人干净，并非指外在衣着，而是指内在品德，安守本分，不招惹是非。干净的女人心中也有向往，就是不委屈自己行违心之事。走到哪儿，她们都可以直视任何人的眼光，笑起来，也是透着从心底升起的自信。她们的日子平静如水，她们把家庭打理得美满幸福。

干干净净做人，规规矩矩做事，理应是条底线。有了这条底线，才能托起为人的更多的本真，才能远离更多的虚浮。

守住这样的底线，说难也难，说不难也不难。

**** 题目

***** 14

****** 选择

******* A

为人真诚

******* B

胸怀天下

******* C

会做家务

******* D

很会哄人

****** 问题

关于干净男人，下列哪项正确？

***** 15

****** 选择

******* A

衣着干净

******* B

光明确落

******* C

会过日子

******* D

屈己待人

****** 问题

关于干净女人，下列哪项正确？

***** 16

****** 选择

******* A

美丽、善良

******* B

做事有底线

******* C

能克制私欲

******* D

讲究生活质量

****** 问题

“干净”的含义是什么？

***** 17

****** 选择

******* A

男人衣着一定要“干净“

******* B

“干净“人越来越少丁

******* C

“干净“是个很高的标准

******* D

“干净“指从外到内讲卫生

****** 问题

根据这段话，可以知道什么？

