* 听力

** 1

*** 1

**** trascript

也许有人问，全国方言这么复杂，几万字的一本小书，够用吗？我们认为，在茫茫大海中，鱼网再大，也会有漏网之鱼。我们的网打算只捞与普通话不同的鱼。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:27:46 -05]
:END:

Some people may ask, the national dialect is so complex, a small book of tens of thousands of words, is it enough? We believe that in a vast sea of disparities, even if the fish net is large, there will be fish that slip through it. Our net intends to fish only for fish that are different from Mandarin.


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

许大夫治病往往是一服药见效，三服药病就好，这种高手给人看病，我们觉得花多少钱都值。当碰上瘟疫来临的时候，许大夫就会拿上药挨家挨户去敲门，有患者马上免费治疗。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:32:42 -05]
:END:

The first thing you need to do is to take a dose of medicine and you'll be fine. When it happens that the plague is coming, Dr. Xu will take the medicine to go door-to-door knocking, there are patients immediately free treatment.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

儿童情感起源于父母的抚爱和家庭温馨气氛的熏陶。如果在家庭中父母能互敬互爱，和睦相处，善于处理好自己的情绪，孩子就能够获得爱和尊重，快乐健康地成长。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:37:00 -05]
:END:

Children's emotions originate from their parents' affection and the warm atmosphere of the family. If parents can respect and love each other in the family, get along with each other and handle their emotions well, children will be able to gain love and respect and grow up happily and healthily.

**** alternatives

***** a



***** b



***** c



***** d

r

**** answer



*** 4

**** trascript

《城南旧事》是中国新时期电影中少有的“言志”作品。这部弥漫着“淡淡的哀愁、沉沉的相思”的电影，用非常物质的东西编织出诗意的世界，又不失现实的真。

***** translation

South of the City" is one of the rare works of "words and aspirations" in Chinese new-era cinema. This film is filled with "light sorrow and heavy longing", using very material things to weave a poetic world without losing the realistic truth.

***** TODO Watch this movie
:LOGBOOK:
- State "TODO"       from              [2022-08-21 Sun 01:06]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

中国是一个人均占有自然资源比较贫乏的国家，水资源、能源的危机随时都在冲击和影响一些企业的经济生产，同时森林资源人均占有率也不高。保护环境，充分利用有限的资源条件创造更多的社会经济效益，是每个企业应负的社会责任。

***** translation

China is a country with relatively poor natural resources per capita, and the crisis of water and energy resources is affecting the economic production of some enterprises at any time, while the per capita occupancy rate of forest resources is not high. It is the social responsibility of every enterprise to protect the environment and make full use of the limited resources to create more social and economic benefits.

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分
:PROPERTIES:
:ID: 150a0e98-8121-4679-a4a4-dc5611738446
:NOTETYPE: dialogue-with-multiple-questions
:END:

*** 对话

女：深圳显然是腾讯诞生的福地。如果当年的创业地址不是在深圳，挪个地方，您觉得今天又会是什么情形？
男：腾讯离不开深圳。对比中国的其他城市，我觉得深圳总体的创业环境还是更适合自主科技创新型的中小民营企业发展并取得成功，这一点毋庸置疑。那时候深圳的口号是“时间就是金钱，效率就是生命”。第一次听到这话，我真的很震惊：金钱居然可以拿来当口号提！但它的确会让人们对时间、效率的迫切感前所未有地提升。
女：您如何看待今天长大成人的腾讯？
男：我觉得机遇很重要，至少占了五成吧。我们也不觉得自己特别聪明，我们做的东西都很简单，大家都能做。但是好的团队、公司的股份结构和投资者的合理搭配，这是很重要的，否则也不会成功。当然，时代的因素也是非常重要的，很多机遇是外界给予的，我们觉得很幸运。
女：深圳汇聚了很多和您一样的知名企业家。在这个城市，您有什么感触？
男：深圳跟其他城市还不一样，那些地方要么有政策，要么有别的条件，在客观环境下能做起来，在深圳企业完全是靠自己做起来的。这里是创业的热土，相信创业者的这种感觉会强烈得多。这里需要有创业的心态，需要有闯劲儿，需要珍惜时间。
女：在闲暇时，您也会在这座城市的某个角落欣赏它的景致，或者享受某个美食城的招牌菜，或者看一场电影，过一下普通市民的生活吗？
男：我本来就是普通市民。平时我就是上网、看看杂志、看看书。QQ 和互联网对我来说已经不是工作了，更多的是一种爱好，是我生活的一部分。

*** 音频

289498a1-819a-4054-a01e-6733ac76e32d.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 5cce9e89-2d7d-47d2-881e-ac1bcca23990
:END:

***** 问题

关于深圳这座城市，下列哪项正确？

***** 音频

96d4c528-332e-41b0-8190-27ff43f1b642.mp3

***** 选择

****** A

这里政策好条件好

****** B

这里是创业的热土

****** C

没有人怀疑它的成功

****** D

城市对发展有迫切感

***** 答案

B

**** 7
:PROPERTIES:
:ID: 7f76a8e1-c861-40a8-9dd0-bf5ba1fe80b7
:END:

***** 问题

对于“时间就是金钱，效率就是生命”，男的持什么态度？

***** 音频

9b36eff3-c92e-443b-aece-bbacf8d4a2aa.mp3

***** 选择

****** A

怀疑

****** B

蔑视

****** C

反对

****** D

赞成

***** 答案

D

**** 8
:PROPERTIES:
:ID: 9466ec06-8c9c-4538-8e13-041205055c47
:END:

***** 问题

关于腾讯成长的有利因素，下列哪项正确？

***** 音频

d423085d-9cd0-4a55-9c3f-9f23df0ebf02.mp3

***** 选择

****** A

公司资金充裕

****** B

公司聪明人多

****** C

赶上了好时代

****** D

产品具有唯一性

***** 答案

C

**** 9
:PROPERTIES:
:ID: 71759b14-fabd-4e25-a913-a08dd42efb3e
:END:

***** 问题

男的在闲暇时会干些什么？

***** 音频

53174c15-67ed-4b85-a3c1-a6dccc7364aa.mp3

***** 选择

****** A

外出旅行

****** B

学做美食

****** C

拍摄电影

****** D

上网、看书

***** 答案

D

**** 10
:PROPERTIES:
:ID: de8f35de-ce70-475d-9759-d6f90102f65e
:END:

***** 问题

关于男的，下列哪项正确？

***** 音频

63310735-7fe5-4360-8ed4-154088157d91.mp3

***** 选择

****** A

他是知名的企业家

****** B

他闯过了无数难关

****** C

深圳是他的出生地

****** D

上下班都着迷于工作

***** 答案

A

