* 听力

** 1

*** 1

**** trascript

也许有人问，全国方言这么复杂，几万字的一本小书，够用吗？我们认为，在茫茫大海中，鱼网再大，也会有漏网之鱼。我们的网打算只捞与普通话不同的鱼。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:27:46 -05]
:END:

Some people may ask, the national dialect is so complex, a small book of tens of thousands of words, is it enough? We believe that in a vast sea of disparities, even if the fish net is large, there will be fish that slip through it. Our net intends to fish only for fish that are different from Mandarin.


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** trascript

许大夫治病往往是一服药见效，三服药病就好，这种高手给人看病，我们觉得花多少钱都值。当碰上瘟疫来临的时候，许大夫就会拿上药挨家挨户去敲门，有患者马上免费治疗。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:32:42 -05]
:END:

The first thing you need to do is to take a dose of medicine and you'll be fine. When it happens that the plague is coming, Dr. Xu will take the medicine to go door-to-door knocking, there are patients immediately free treatment.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** trascript

儿童情感起源于父母的抚爱和家庭温馨气氛的熏陶。如果在家庭中父母能互敬互爱，和睦相处，善于处理好自己的情绪，孩子就能够获得爱和尊重，快乐健康地成长。

***** translation
:PROPERTIES:
:CREATED: [2022-08-20 19:37:00 -05]
:END:

Children's emotions originate from their parents' affection and the warm atmosphere of the family. If parents can respect and love each other in the family, get along with each other and handle their emotions well, children will be able to gain love and respect and grow up happily and healthily.

**** alternatives

***** a



***** b



***** c



***** d

r

**** answer



*** 4

**** trascript

《城南旧事》是中国新时期电影中少有的“言志”作品。这部弥漫着“淡淡的哀愁、沉沉的相思”的电影，用非常物质的东西编织出诗意的世界，又不失现实的真。

***** translation

South of the City" is one of the rare works of "words and aspirations" in Chinese new-era cinema. This film is filled with "light sorrow and heavy longing", using very material things to weave a poetic world without losing the realistic truth.

***** TODO Watch this movie
:LOGBOOK:
- State "TODO"       from              [2022-08-21 Sun 01:06]
:END:

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** trascript

中国是一个人均占有自然资源比较贫乏的国家，水资源、能源的危机随时都在冲击和影响一些企业的经济生产，同时森林资源人均占有率也不高。保护环境，充分利用有限的资源条件创造更多的社会经济效益，是每个企业应负的社会责任。

***** translation

China is a country with relatively poor natural resources per capita, and the crisis of water and energy resources is affecting the economic production of some enterprises at any time, while the per capita occupancy rate of forest resources is not high. It is the social responsibility of every enterprise to protect the environment and make full use of the limited resources to create more social and economic benefits.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



