* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 6c55a5b3-438a-4f94-baea-06a440c4e994
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
4d9de802-ce66-4dad-a4c6-791a7d3d25de.mp3
***** 转录
活儿总算忙完了，他累得都要崩溃了，满脑子都是客户和协议。虽然困得要死，可躺在床上颠来倒去睡不着，心烦意乱之中，突然听到儿子的房间传来了朗读英语的声音，轻柔、平静，不知不觉中，他竟入睡了。
**** 选择
***** A
他每天都学习英语
***** B
他白天工作特别多
***** C
他每天很晚才睡觉
***** D
他晚上一直没睡着
**** 答案
B
*** 2
:PROPERTIES:
:ID: 3f819960-6cee-4f5b-8bfa-eb439d940be4
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
18799a1f-b801-4732-952c-00006536ebad.mp3
***** 转录
人的头发中有一种叫作黑色素的物质，黑色素越多头发的颜色越黑，黑色素少了，头发便会发黄或变白。人进入老年，身体的各种机能会逐渐衰退，色素也会越来越少，所以头发就会渐渐变白。
**** 选择
***** A
头发是否变白和人的肤色有关
***** B
头发变白说明人各种机能变好
***** C
头发的颜色取决于黑色素的多少
***** D
黑色素的多少决定着头发的多少
**** 答案
C
*** 3
:PROPERTIES:
:ID: 232f2dcc-4945-4142-baca-201004b62608
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
a8473ed7-d75d-4b7c-8f2b-387b8944f7fb.mp3
***** 转录
1915 年中国将清明节定为植树节，1928 年将植树节改为 3 月 12 日，这一设定一直沿用至今。此外，一些省市还根据当地的气候规律，规定了其他的植树日、植树周、植树月。
**** 选择
***** A
1915年中国有了清明节
***** B
1928年中国首创植树节
***** C
很多省市有自己的植树节
***** D
植树节在每年的3月12号
**** 答案
D
*** 4
:PROPERTIES:
:ID: e581e4ca-c6d0-4aeb-80d2-59b75e52f294
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
2c62cb1e-9f13-4b8c-b992-7bc7ccea521c.mp3
***** 转录
盛文强长期从事海洋民间故事的采集整理，并出版了多部海洋题材小说。作为传统的农业国家，中国文学中的农业元素太多了，所以盛文强的“海洋文学”出现在读者面前时，不免让人眼前一亮。
**** 选择
***** A
盘文强从小生活在农村
***** B
意文强的作品取材海洋
***** C
盛文强很会讲民间故事
***** D
盛文强特别喜欢看小说
**** 答案
B
*** 5
:PROPERTIES:
:ID: 26822637-4fe3-4d4d-b442-782b972a52a3
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
d23170e5-df13-4e5b-ba35-4562cdea0466.mp3
***** 转录
5. 我带着狗去郊游，狗发现了野兔就兴奋地前去追赶。野兔明明知道狗来了，却像没这事一样，照样坐在那儿吃草，直到狗跑近了，野兔才一跃而起，迅速跑开，当它跑到自认为安全的地方，便又马上安定下来。
**** 选择
***** A
狗追近丁，兖子才会躲开
***** B
免子看到狗就会拼命地跑
***** C
兖二看到狗就会心神不定
***** D
我专程去郊外看狗追免子
**** 答案
A
** 第二部分
*** 6-10
:PROPERTIES:
:ID: 57a42d26-8960-4ff3-800c-54ee031f954e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
74a36d54-4368-47ab-b1b7-4e8b3337ba86.mp3
***** 转录
女：今天来参加我们访谈节目的是年轻朋友非常崇拜的著名节目主持人刘可心。欢迎您！您知道年轻朋友私底下怎么称呼您吗？
男：“可心同学”？
女：对。
男：可以这么叫我。我喜欢这个称呼。
女：那好，咱们就这么叫了。可心同学，很多听众喜欢听您说话，认为您思维角度与众不同，听您说话不只是听听而已，关键是总能受到启发。
男：过奖了。我之所以能成为今天的我，无非是和读书，特别是和读名著有关。阅读经典，肯定会对我们的人生产生影响。比如，我小时候对“美”和“丑”的理解，就跟读法国作家雨果的《巴黎圣母院》有关，这本书让我意识到，不能光凭外表长得不好看就觉得这个人也不好。
女：名著这么好，有些孩子怎么就是不愿意读呢？
男：主要是因为老师家长把这事当任务布置给孩子，孩子就会觉得很累，甚至反感。读书不能勉强，其实读名著是件很好玩儿的事情，名著都是经受住了历史考验的。所以，家长要让孩子带着好奇心去读，他就有了动力。
女：您的孩子喜欢读书吗？这不是隐私吧？
男：当然不是。我的孩子非常喜欢读书。
女：他读的第一本书是什么，您还记得吗？
男：他认真读的第一本书是武侠小说。
女：哦？
男：在读书方面，我给他非常大的自由。我觉得最重要的是让他在年少时喜欢读书，而不是读哪本书。
女：听说您的孩子马上就要高考了，而且选择的是历史？
男：对，应该说他的选择跟他的阅读经历有关，他读金庸的武侠小说着迷，读完一遍还想读第二遍，书里涉及一些他不懂的内容，就到处查书查资料，这样他的阅读面就会不断向外延伸。
女：这么说，名著也不需要读全？您怎么看古人说过的“读万卷书行万里路”？
男：在我看来，不管行万里路还是读万卷书，关键得看走不走心，到哪儿赶紧拍照，奔下一个景点，万里路固然是走了，可一点儿用都没有。即使你没读万卷书，但把 10 本书给读明白了，要比囫囵吞枣读 100 本书好得多。
**** 题目
***** 6
:PROPERTIES:
:ID: 1aead7c4-4e7e-4c12-bf50-1f08391698fc
:END:
****** 问题
******* 音频
a2847335-119d-4770-9b75-c11b917e85ec.mp3
******* 转录
关于刘可心，可以知道什么？
****** 选择
******* A
他很受年轻人欢迎
******* B
他还没工作，是个学生
******* C
他的话没有太大的价值
******* D
他总能从生活中受到启发
****** 答案
A
***** 7
:PROPERTIES:
:ID: 7c5c9da6-682b-4d75-bca5-0611a78f1eab
:END:
****** 问题
******* 音频
fb29d2bd-5e35-4644-8a27-333ff87048c4.mp3
******* 转录
刘可心怎么评价自己？
****** 选择
******* A
他在睇儿都会受表扬
******* B
他的成功和读书有关
******* C
他一直喜欢法国小说
******* D
人长相难看心眼儿才好
****** 答案
B
***** 8
:PROPERTIES:
:ID: e458609a-6cdf-4317-816c-deb14ff344b0
:END:
****** 问题
******* 音频
215fab1f-8b0b-428f-8ef2-c8d279d1e1e6.mp3
******* 转录
刘可心认为有的孩子不愿意读名著的原因是什么？
****** 选择
******* A
孩二们学习太紧张
******* B
家长自己就不读书
******* C
孩二们没找到好书
******* D
大人的方法有问题
****** 答案
D
***** 9
:PROPERTIES:
:ID: beb8f4f4-572a-497d-a00b-2a57f33b8896
:END:
****** 问题
******* 音频
64efc845-e40b-4304-ba90-40943096a700.mp3
******* 转录
关于刘可心的孩子，下列哪项正确？
****** 选择
******* A
读书使他喜欢上了历史
******* B
每本书他都会认真读完
******* C
每部小说他都会反复看
******* D
父亲喜欢武侠他也喜欢
****** 答案
A
***** 10
:PROPERTIES:
:ID: 7af910a9-fe70-4069-8cdb-481c00aca1ca
:END:
****** 问题
******* 音频
f82caf6d-cf23-41f9-9b42-9e0221f35877.mp3
******* 转录
对“读万卷书行万里路”，刘可心怎么看？
****** 选择
******* A
书当然是读得越多越好
******* B
行万里路一点儿用都没有
******* C
读书不在多少，关键是用心
******* D
天天忙着旅游就没法读书了
****** 答案
C
** 第三部分
*** 11-13
:PROPERTIES:
:ID: 4189da81-0465-44a3-b066-579cf3523eb8
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
a424f854-467a-469e-94ae-f83c63ebc26b.mp3
***** 转录
我们常常会听到家长感叹，现在的孩子，能安安静静坐下来看书的实在太少。想想我们小的时候，一本书在同学之间传来传去，大家迫不及待地轮流传阅，兴致勃勃地捧着一本书，如痴如醉……那样的乐趣，我们的孩子为什么就完全没有感觉呢？
王先生常抱怨，儿子小的时候，自己每天晚上给他读故事，本以为他长大了，在读书方面，会成为自己的知音。现实却并非如此，儿子对老师推荐的书、家长给他买的书好像都没兴致，偶尔翻看一下，不过是应付老师和家长。
在浮躁的现代生活氛围中，借助互联网和各色电子产品，人们可以接触到最新娱乐资讯，可以在卡通动漫和电脑游戏中得到放松。人们将大量时间耗费在手机、电脑与电视机前。因此，如何让心灵回归沉静，已经成为摆在人们面前的难题。
**** 题目
***** 11
:PROPERTIES:
:ID: dee4713a-ef62-4596-964b-a37abd0804ab
:END:
****** 问题
******* 音频
da08cb68-2a41-4002-9730-25c271c75050.mp3
******* 转录
家长常为什么事感叹？
****** 选择
******* A
孩子们安静不下来
******* B
孩子们不喜欢看书
******* C
自己小时候没有书看
******* D
自己小时候没钱买书
****** 答案
B
***** 12
:PROPERTIES:
:ID: 7654689a-1d58-4ccd-b796-632244a56dfb
:END:
****** 问题
******* 音频
33016820-1e37-46d4-bcfb-7826da3ab63c.mp3
******* 转录
王先生常抱怨什么？
****** 选择
******* A
儿子对自己很反感
******* B
儿子长大了,不听话了
******* C
儿子长大后并不爱读书
******* D
现在的老师不为学生着想
****** 答案
C
***** 13
:PROPERTIES:
:ID: 6425b3ee-6e71-4284-978b-b14ebdd23cb6
:END:
****** 问题
******* 音频
f6c0c76a-922a-4ce7-a6a3-9785d6a2f67a.mp3
******* 转录
如今摆在人们面前的难题是什么？
****** 选择
******* A
怎样远离电脑游戏
******* B
怎样让心灵安静下来
******* C
怎样克服互联网的弊端
******* D
如何让娱乐资讯有深度
****** 答案
B
*** 14-17
:PROPERTIES:
:ID: 36292cda-bfce-48e2-abfa-9a482234175e
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
3943dd30-1e80-4df1-af1e-1a34e272b2d3.mp3
***** 转录
有人说学好外语就得努力学、拼命学，得有大把的时间，我却说学外语就得“见缝插针”。所谓“见缝插针”，就是要把一般人看着不起眼的零碎时间都利用起来。可千万别看不起这几分钟十几分钟的时间，根据记忆心理学的原理，对于外语等以机械记忆为主的学习内容，及时地利用零碎时间进行复习，效果是很好的，学了就搁在一边，等于没学。
“见缝插针”的另一种方式就是把外语学习和日常生活联系起来，处处学，时时学，事事学。只要有了学习外语的强烈愿望和兴趣，日常生活的各个方面都可以成为外语学习的第二课堂，而且在日常生活中学到的外语记得快、记得牢，学习效果特别好。
“见缝插针”时间长了，就会感到外语学习已成为自己生活中不可缺少的内容，就会感到学习外语是一种乐趣和享受，一天不学就好像缺了点儿什么。
**** 题目
***** 14
:PROPERTIES:
:ID: bc3cfffc-13ed-4c96-8d44-4431bc27921b
:END:
****** 问题
******* 音频
51095610-bc4e-4229-9206-b203eba5a3a8.mp3
******* 转录
怎样“见缝插针”学外语？
****** 选择
******* A
工作给别人,自己学外语
******* B
有了充足的时间再学外语
******* C
别人看电视时自己学外语
******* D
多么短的时间都利用起来
****** 答案
D
***** 15
:PROPERTIES:
:ID: 33c3a74b-4913-45fe-9c30-0804b7600683
:END:
****** 问题
******* 音频
b3caf053-292e-414e-84da-c8d7ac997898.mp3
******* 转录
“见缝插针”学外语的好处是什么？
****** 选择
******* A
有新鲜感
******* B
有成就感
******* C
有利于记忆
******* D
不浪费时间
****** 答案
C
***** 16
:PROPERTIES:
:ID: 69bb9521-1e08-4c37-898b-34d590339b93
:END:
****** 问题
******* 音频
7c9e2127-edd8-446c-85ff-1dcec4a4f390.mp3
******* 转录
“见缝插针”的另一种学习方式是什么？
****** 选择
******* A
在日常生活中学习
******* B
培养学外语的兴趣
******* C
锻炼自己的记忆力
******* D
和外国人多多接触
****** 答案
A
***** 17
:PROPERTIES:
:ID: 35c9441f-e6da-437c-a352-4efca153a616
:END:
****** 问题
******* 音频
ccc0668f-a5a1-4ef2-8f06-49c9825917dc.mp3
******* 转录
这段话告诉我们什么？
****** 选择
******* A
工作忙不是学不好外语的借口
******* B
学习外语的过程也是一种享受
******* C
只要有时间就不会学不好外语
******* D
会“见缝插针“的人都能成功
****** 答案
A
* 阅读
** 第一部分
*** 18
**** 句子
***** A
一切成功的教育必须基于爱，借助于爱，归结于爱。
***** B
一个用心温暖别人的人，她自己的心也必然是温暖的。
***** C
他的父亲、爷爷都是书法家，书法作品对他一点儿也不陌生。
***** D
夕阳西下，我看到她正坐在门口专注地倾听着什么，脸上有种奇异的微笑。
**** 答案
C
*** 19
**** 句子
***** A
听家里人说他是春节以后找到工作了。
***** B
这是一本值得一辈孔去学习、去研究、去实践的好书。
***** C
妈妈年轻的时候有一个最奋侈的梦想，就是拥有一辆新自行车。
***** D
春天，万物复苏，小草从土里悄悄地探出头来，好奇地四处张望。
**** 答案
A
*** 20
**** 句子
***** A
世界各国民航部门都对商业无人机的滥用挠头不已。
***** B
我的家乡物产丰富、风景秀丽，被人们称为“草原明珠”。
***** C
他比过去成熟了，知道身体健康的重要性，更懂得约束自己。
***** D
念大学的时候，我常跟朋友去游沟，其实我并不喜欢游沟，只是凑个热闸。
**** 答案
A
** 第二部分
*** 21
**** 段话
她的教育人生，如果用一个字来[[gap]]，那就是“爱”。有了“爱”，她就有了无限的精力、无限的[[gap]]、无限的事业[[gap]]。
**** 选择
***** A
****** 1
总结
****** 2
本领
****** 3
动能
***** B
****** 1
概述
****** 2
技能
****** 3
能量
***** C
****** 1
概括
****** 2
才能
****** 3
动力
***** D
****** 1
包括
****** 2
才华
****** 3
能力
**** 答案
C
*** 22
**** 段话
幸福是什么？[[gap]]很重要，但仅仅“够用”就可以了。北欧人的幸福感，更多来源于简约、自然、平和的[[gap]]以及家庭的温暖、个人的[[gap]]，而这些是我们可以学会，可以身体力行的，也是我们自古以来[[gap]]倡导的。
**** 选择
***** A
****** 1
物质
****** 2
心态
****** 3
努力
****** 4
一直
***** B
****** 1
物资
****** 2
心理
****** 3
勤劳
****** 4
从来
***** C
****** 1
东西
****** 2
想法
****** 3
奋斗
****** 4
不停
***** D
****** 1
财物
****** 2
态度
****** 3
尽力
****** 4
不断
**** 答案
A
*** 23
**** 段话
中华鲟是古老的[[gap]]鱼类，现今仅在中国长江流域[[gap]]有分布。曾有外国人希望将它[[gap]]到自己的国度安家落户，但中华鲟总要泗游到故乡的江河生儿育女，所以人们给它[[gap]]“中华”二字。
**** 选择
***** A
****** 1
珍视
****** 2
且
****** 3
转移
****** 4
加上
***** B
****** 1
珍稀
****** 2
尚
****** 3
引进
****** 4
冠以
***** C
****** 1
珍重
****** 2
仍
****** 3
搬家
****** 4
命名
***** D
****** 1
爱惜
****** 2
犹
****** 3
移民
****** 4
起名
**** 答案
B
** 第三部分
*** 段话
2400多年前，有个叫曾子的人，他16岁拜孔子为师，勤奋好学，[[gap:24]]。
曾子不仅有学问，[[gap:25]]，即使对孩子，也是一样。一次，曾子的妻子要到街上去买东西，儿子哭闸着要跟着去。妻子对儿子说，[[gap:26]]，好好待在家里，回来就杀猪给他炖肉吃。孩子以为母亥说的是真的，就不闸了，在家里安安静静地等着。
妻子买东西回来，一进门就看到曾子已经拿出了刀，做着杀猪的准备。妻子吓了一跳，赶忙说：“你真的要杀猪吗？我没跟他说实话，[[gap:27]]，我没真想把家里的猪杀了呀。”曾子认真地说：“我们的行为会影响孩子，如果我们说话不算数，[[gap:28]]，我们就会把孩子教育成不诚实的人。”妻子听了曾子的话，觉得有道理，于是，帮着丈夫把猪杀了，做了一顿丰盛的晚餐。
*** 选择
**** A
做人诚实也是出了名的
**** B
无非是为了哄孩子不要哭闹
**** C
是春秋时期的著名学者
**** D
孩子会跟我们学
**** E
只要他不闸
*** 答案
**** 24
C
**** 25
A
**** 26
E
**** 27
B
**** 28
D
** 第四部分
*** 29-32
**** 段话
精通古汉语，对外文完全是门外汉的林纾是中国著名翻译家，近代文学翻译的开创者，正式译介西方文学的第一人。他以“耳受笔追”的方式，与留洋学子合作，翻译了11个国家107位作家的作品，对引进西方文学和促进中国社会文化的进步做出了巨大贡献。
林约有个朋友叫王昌寿，曾赴法留学6年，精通法语。他常给林纤讲外国名著，每次林纤都听得津津有昧。一来二去林纶喜欢上了西方文学，并产生了将其翻译给国人的念头。林纾想虽然自己看不懂外文，可是搭上王昌寿，俩人就没嗅做不成的。于是二人达成协议，合作翻译法国名著《茶花女》办法是王昌寿口译，林纾记录并成文。那时，人们常看到这样一幅景致：王昌寿面前搁着本原著，边浏览，边口述；林纤耳聪手疾，文思如泉涨，经常是王昌寿说完一句的同时，林纾就已经挥笔成文了。半天下来，两人能译出6000多字。1899年夏天，中国首部翻译小说《巴黎茶花女遗事》公开发售。一时间，阅读翻译小说成了社会风尚，众人争相抢阅。此后的27年里，林约与魏易、陈家麟等留学归来的才子合作翻译了160余部外国名著，这些小说向中国民众展示了丰富的西方文化，开阔了人们的视野。
除翻译外，林纾还是一位深受读者欢迎的作家，他接连发表的长篇小说和一系列短篇小说生动地反映了当时的社会现实，深受读者喜爱。此外，林纤还是一位不错的画家，他23岁招师学画，绘画成就不亚于文学创作和翻译。
**** 题目
***** 29
****** 问题
根据第1段可以知道，林纤：
****** 选择
******* A
一点儿外语也不会
******* B
把古汉语翻详成了外文
******* C
曾经去过十多个国家
******* D
促迹了西方文学的发展
****** 答案
A
***** 30
****** 问题
根据第2段可以知道：
****** 选择
******* A
《茶花女》是林纤、王旷寿合写的
******* B
1899年中国出版了第一本翻译小说
******* C
《巴黎茶花女遗事》一出版就被抢光
******* D
1899年之后，中国出了很多翻译家
****** 答案
B
***** 31
****** 问题
第2段画线词语“耳聪手疾”的意思是：
****** 选择
******* A
手有问题了
******* B
耳朵听不见了
******* C
耳朵很好手不行
******* D
耳朵也好手也快
****** 答案
D
***** 32
****** 问题
通过最后一段我们还知道，林纤：
****** 选择
******* A
尊重仪一位读者
******* B
喜欢看各类小说
******* C
23岁时教过画画儿
******* D
画画儿不比写作差
****** 答案
D
*** 33-36
**** 段话
不少工作繁忙、不希望把学习过程拖得太长的中国人，都希望能在短时间内学会英语。有人提出过这样的问题，“英语速成”可能囚？
如果我斩钉截铁地告诉你，到现在为止没有例子能够证明在一年之内可以做到听说读写没问题，请你不要失望。因为对于中国人来说，英语是一门外语，从什么都不会到能够听、说、读、写，是一个必须按照学习规律一步一个脚印走过的过程，期间没有近路可走。
如果让我为你策划学习方式，我想告诉你，学英语首先要以最严格的要求，从基础知识抓起，要学好每一个间、每一句话，之后再谈提高和强化。学习中要先把课本知识学好，把课本内容掌握得滚瓜烂熟之后，再去光顾课外材料，这种看起来在基础知识上耿误了时间的笨方法，倒有可能使你收到事半功倍的效果。
其次，不要把心思放在应试技巧上，梦想依靠所谓技巧在短期内通过某种考试。虫然一些技巧对某些人的命运能够起到决定性作用，但离开考场以后，所谓的技巧却没有任何实际应用价值。学习英语的根本目的在于应用，因此学习英语的每一个环节都应着眼于实际能力的培养与提高。
另外，一种很好的学习方法就是“听写录音”，把你听到的英语记录下来，可以让你清楚，你什么地方听不懂、写不出，让你直观地感受到你的不足在睇里，你也就找到了真正的出发点。经过努力，就能听懂了、写对了，你取得的进步也是实实在在的。如此这般，英语水平自然会日渐提高，最后顺利到达终点。
**** 题目
***** 33
****** 问题
什么样的人席望学习“速成英语”？
****** 选择
******* A
自认为聪明过人的人
******* B
做事随意不善计划的人
******* C
了解外语学习规律的人
******* D
想在短时间学会英语的人
****** 答案
D
***** 34
****** 问题
学英语最重要的方法是什么？
****** 选择
******* A
记住单词
******* B
胖诵句子
******* C
打好基础
******* D
看课外书
****** 答案
C
***** 35
****** 问题
关于应试技巧，作者认为：
****** 选择
******* A
掌握应试技巧很重要
******* B
学应试技巧很费时间
******* C
靠应试技巧学不好英语
******* D
应试技巧在生活中有用
****** 答案
C
***** 36
****** 问题
作者认为一种很好的学习方法是什么？
****** 选择
******* A
边昕录音边写下吻到的英语
******* B
反复听录音中听不懂的地方
******* C
善于发现自己学习中的弱点
******* D
每天都能感受到自己的进步
****** 答案
A
