* 听力

** 第二部分
:PROPERTIES:
:ID: 9e84b20c-b386-427c-8e3f-63c5b7c427ed
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：你七年前生病后逃离上海，如今带着自己的新书《逃离》回到上海做宣传，是否多少有些感慨？
男：我当年就特别有感触。七年前生病，我首先要逃出医院，要知道，当时我住的是中国肺科最好的医院。然后我要逃离上海。
女：那时候你好像刚结婚？
男：我结婚一个月后就查出得了大家都认为是不治之症的病，当时我的想法是和老婆离婚，不想耽误她。
女：她怎么想？
男：她说她没觉得这是多大的事，病了就病了，死了就死了，这都是命，你想那么多干吗。
女：在上海你的一切都很稳定，做出逃离上海的决定也不容易吧？
男：在上海，我有大房子，有车，有社会地位。但对我来说，逃出医院才是最艰难的，因为我选择了自我治疗。
女：上海这座城市曾经给你什么美好的记忆吗？
男：上海带给我的记忆一直很美好。我的不适应还是在生活上、语言上，包括生病这件事。我之所以选择离开，主要是对于我生病地的水，我再也不想喝了。因为我只信水，所以想找到好的水、干净的水。我在《逃离》一书中反复地说，生命是以水为基础的。生病是生命的一部分，我决定用换水的方式来解决病的问题。那时医院的肺科主任对我说：“马老师，什么事情都没有耽误治疗的事情大。”这位医生说得入情入理，但我跟他们说，我自己的命，我做一回主。
女：你在山里过上了世外桃源的生活。你觉得，逃离最大的好处是什么？
男：不久前我才有了网络。这种与世隔绝的生活最大的好处是可以免遭外界干扰。对于都市生活的负面影响，各种各样的说法都有，譬如“都市病”，大家越来越觉得都市生活对人性本身是一种禁锢。在大山里则不同，可以让我在寂静中沉下心来思索。一个人独居，就会有特别多的想法。我每天的生活是简单的，在这个简单里，你很容易进入一种抽象思维的状态，很容易变得哲学化。

**** 音频

b94762c5-aa49-469e-8e9e-e341c9719dca.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: a28396f4-9302-47f2-a1b6-74b980c5694f
:END:

***** 问题

七年前发生了什么事？

****** 音频

2c6baeaf-88a6-4d59-8f5a-f8aff2399e04.mp3

***** 选择

****** A

男的生了重病

****** B

男的准备结婚

****** C

妻子不高兴了

****** D

男的出了新书

***** 答案

A

**** 7
:PROPERTIES:
:ID: c3c4c918-bfee-4391-b881-211d991501b9
:END:

***** 问题

对男的来说，最艰难的是什么？

****** 音频

0d30f825-2360-4f13-8eae-9e39611410c0.mp3

***** 选择

****** A

卖掉房孔、车子

****** B

放弃优越的生活

****** C

拒绝在医院治疗

****** D

远离社会的尊重

***** 答案

C

**** 8
:PROPERTIES:
:ID: 89490de8-9879-4ccb-9b1f-33927d2b86d9
:END:

***** 问题

男的为什么选择离开上海？

****** 音频

26472892-1bb0-4d11-aa46-01d65d428186.mp3

***** 选择

****** A

医生都特别不会说话

****** B

再也不想喝上海的水

****** C

很多人听不懂上海话

****** D

妻二决定要离开上海

***** 答案

B

**** 9
:PROPERTIES:
:ID: a9f6fa4f-5ccc-4e89-a9be-b97d92559313
:END:

***** 问题

男的认为远离都市的生活有什么好处？

****** 音频

e90059ad-cb90-420f-b32a-85884d8318f7.mp3

***** 选择

****** A

可以思考哲学问题

****** B

可以不受外界干扰

****** C

可以比城里人少生病

****** D

可以吃到鲜美的桃子

***** 答案

B

**** 10
:PROPERTIES:
:ID: f91a2cf8-0a19-4532-9d62-c30db1e01e19
:END:

***** 问题

关于男的，下列哪项正确？

****** 音频

77dabfc1-67ae-4ca8-9498-de27cd61560a.mp3

***** 选择

****** A

他很爱他的妻子

****** B

他不愿和人打交道

****** C

他是有影响的哲学家

****** D

他把妻子的事写成了书

***** 答案

A

** 第一部分

*** 1

**** 选择

***** A

青少年触犯刑法也要惩罚

***** B

对受到惩罚的人更要关心

***** C

惩罚会给人带来极大的伤害

***** D

惩罚就是为丁造成心理压力

**** 段话

在惩罚实施后对受罚者保持关爱，通常会收到良好的效果。这是因为惩罚会给人带来羞愧、痛苦、不安和悔恨等消极情绪,这时人的心理承受能力较低，比平时更期望得到别人的关爱,儿童、青少年尤其如此。

***** 音频

5fd98121-46c8-4a7c-baa7-1ff9d66b7d49.mp3

**** 答案

B

*** 2

**** 选择

***** A

机器人是外形像人的一种机器

***** B

想指挥机器人必须先编好程序

***** C

机器人可代替人进行危险作业

***** D

机器人迟早要取代人类

**** 段话

机器人指能够自动执行工作的机器装置，它可以接受人类指挥，也可以根据已编好的程序运行。它的任务是帮助或代替人类工作，可应用于生产业、建筑业，或是危险工作。

***** 音频

99958f8d-2086-45a9-b4a9-2bf692249140.mp3

**** 答案

C

*** 3

**** 选择

***** A

进口的手术材料比较便宜

***** B

进口的手术材料材质不好

***** C

张医生发明了一种新材料

***** D

张医生手术技术全国闻名

**** 段话

那一年，中国开始推动介入治疗，张医生发现当时手术用的封堵器全部是进口的，价格贵不说，由于材质偏硬，极易造成其他组织的损伤。他天天想，可否找到一种能降低成本，同时能提升治疗效果的新材料？

***** 音频

acf6e1ad-c07d-4e18-8919-716db2a43ed0.mp3

**** 答案

B

*** 4

**** 选择

***** A

人脑消耗的能量非常少

***** B

人的血糖浓度低很危险

***** C

为了大脑健康要多吃精

***** D

血糖浓度过高人会昏迷

**** 段话

人脑的重量虽然只占人体重量的 2%左右，但大脑消耗的能量却占全身消耗能量的 20%。人脑每天需要 116～145 克的糖，当血糖浓度降低时，大脑的耗氧量也随之下降，轻者会感到头昏、疲倦，重者则会陷入昏迷。

***** 音频

956a8ebd-1207-4c77-b098-aee20c63cc51.mp3

**** 答案

B

*** 5

**** 选择

***** A

李小龙33岁就辞世了

***** B

李小龙神拜“功夫之王“

***** C

李小龙的电影是个神话

***** D

李小龙对功夫十分狂热

**** 段话

李小龙用 33 岁短暂的人生制造了一段传奇。从他离开这个世界的第一天起，他的追随者就对这位“功夫之王”进行了各种形式的追忆和纪念，这种狂热的纪念逐渐演变成一个神话，一个龙的神话，一个空前绝后的神话。

***** 音频

d51bb370-7c51-4e05-8ca0-60c9d590e397.mp3

**** 答案

A

** 第三部分

*** 11-13
:PROPERTIES:
:ID: 5c1fc404-159d-49e1-afb4-addddc4675a4
:NOTETYPE: content-with-audio-3-multiple-choice-exercises
:END:

**** 课文

自 1957 年人类发射第一颗人造卫星至今，太空中的废弃航天器已有 5000颗左右，而失效的卫星、探测器以及火箭发射后残留下来的碎片就更多了，它们漂浮在太空中，形成太空垃圾，即“空间碎片”。

目前太空碎片总数已超过 4000 万个，而且空间碎片每年还在以 2%～5%的速度增加。数量多、速度快是空间碎片的危害所在，这些碎片以每秒 6000～7000米的速度运行，一个仅 10 克重的太空垃圾的撞击强度，与以 100 公里时速行驶的两辆轿车迎面相撞的强度相当。对人类而言，空间碎片落到地面，后果将会是灾难性的。

面对太空垃圾，人类必须清醒，我们只有一个地球，也只有一个外层空间，维护外层空间的清洁迫在眉睫，而且空间碎片问题需要全球共同努力，共同面对。

***** 音频

7ec3191e-550a-46c0-9e31-1ff0eadaf0e5.mp3

**** 题目

***** 11
:PROPERTIES:
:ID: a2e02967-f264-443a-893e-5933d18844c3
:END:

****** 选择

******* A

空间硼片

******* B

失效卫星

******* C

火箭残片

******* D

废弃航天器

****** 问题

太空垃圾还叫什么？

******* 音频

ba137eca-3059-43a5-9be0-816f4a9f8917.mp3

****** 答案

A

***** 12
:PROPERTIES:
:ID: bcbd8ec7-9006-40e9-9010-7b046cf06156
:END:

****** 选择

******* A

碎片重量过大

******* B

每年大量增加

******* C

数量多,速度快

******* D

会经常撞击地球

****** 问题

太空垃圾的危害是什么？

******* 音频

492721e7-7713-4f62-ba75-eaea4b49886d.mp3

****** 答案

C

***** 13
:PROPERTIES:
:ID: 7a35d88d-2935-4629-919e-38fd53a820a6
:END:

****** 选择

******* A

减少发射人造卫星

******* B

了解太空垃圾的危害

******* C

提高思考问题的能力

******* D

维护外层空间的清洁

****** 问题

人类最紧急的任务是什么？

******* 音频

fe1b704c-4064-49e7-afbb-2103b2100543.mp3

****** 答案

D

*** 14-17
:PROPERTIES:
:ID: 5cc2d1ee-4487-4362-8d54-382e4df383dd
:NOTETYPE: content-with-audio-4-multiple-choice-exercises
:END:

**** 课文

人的大脑只有在体力、脑力和心力处于最佳状态时，才能得到最好的发挥，这是不可不信的科学。

先说体力，它是大脑开发的基础条件，在实现目标的过程中是否会白白失去成功的机会，有时确实与是否具备充足的体力有关。因此我们要长久地保养和锻炼身体，保持体力，增进健康。至于父母为了提高孩子的学习成绩，让孩子不停地奔忙于学校和各种补习班之间，绝非聪明之举，这样做只会导致孩子体力欠缺，进而造成注意力、免疫力不同程度地下降。

脑力，也就是我们常说的“聪明才智”，并非只有学习才能促进其增长。玩耍、运动、休息、调整，同样会不断地刺激大脑，使头脑更加灵活，进而提高人的判断力、识别力、记忆力，甚至做事的效率。试想，具备了这些能力的人，还存在脑力、心智不足的问题吗？

人的心力是一种正义的力量。当一个人的品质最接近人生的本质时，心力指数会明显提高，他的人格魅力也会增强，更会被人尊重和喜爱。心力是人的灵魂觉醒时产生的力量，也是能唤醒人的灵魂的力量。

***** 音频

8372b17b-baa1-4d6c-9428-a1d3b3085ddb.mp3

**** 题目

***** 14
:PROPERTIES:
:ID: 50d71f5d-01ef-4365-8c33-bcd23fa22197
:END:

****** 选择

******* A

让孩子多玩儿

******* B

让孩子锻炼身体

******* C

让孩子劳逸结合

******* D

让孩子集中注意力

****** 问题

父母最聪明的做法是什么？

******* 音频

8f8315cd-ba1c-49fe-93b2-64b8ec2c91a8.mp3

****** 答案

C

***** 15
:PROPERTIES:
:ID: 4e782f1a-5994-4855-ba65-5f94abd0a91c
:END:

****** 选择

******* A

不断提高做事的效率

******* B

刺激大脑,促其灵活

******* C

多向能力强的人学习

******* D

克服脑力不足的缺陷

****** 问题

怎样才能使我们更聪明？

******* 音频

4a56a218-ec42-4b68-9bba-633bb7741b8e.mp3

****** 答案

B

***** 16
:PROPERTIES:
:ID: c2733faf-933e-4b2f-a0ad-aa8601b0d286
:END:

****** 选择

******* A

灵魂的觉醒

******* B

人格的魅力

******* C

正义的力量

******* D

人生的本质

****** 问题

人的“心力”是什么？

******* 音频

e712c348-eda4-41c5-91e0-1d3a8ce7d124.mp3

****** 答案

C

***** 17
:PROPERTIES:
:ID: 71532c6b-5331-4f52-9777-515c6f434d67
:END:

****** 选择

******* A

身体健康是最重要的

******* B

谁都不能不相信科学

******* C

离开科学我们寸步难行

******* D

大脑如何得到最好地发挥

****** 问题

这段话主要想告诉我们什么？

******* 音频

5466af7c-f04b-4cc9-bc1c-3b1c599e2d4e.mp3

****** 答案

D

