* 听力

** 1

*** 1

**** transcript

在惩罚实施后对受罚者保持关爱，通常会收到良好的效果。这是因为惩罚会给人带来羞愧、痛苦、不安和悔恨等消极情绪，这时人的心理承受能力较低，比平时更期望得到别人的关爱，儿童、青少年尤其如此。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

机器人指能够自动执行工作的机器装置，它可以接受人类指挥，也可以根据已编好的程序运行。它的任务是帮助或代替人类工作，可应用于生产业、建筑业，或是危险工作。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

那一年，中国开始推动介入治疗，张医生发现当时手术用的封堵器全部是进口的，价格贵不说，由于材质偏硬，极易造成其他组织的损伤。他天天想，可否找到一种能降低成本，同时能提升治疗效果的新材料？

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

人脑的重量虽然只占人体重量的2％左右，但大脑消耗的能量却占全身消耗能量的20％。人脑每天需要116～145克的糖，当血糖浓度降低时，大脑的耗氧量也随之下降，轻者会感到头昏、疲倦，重者则会陷入昏迷。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

李小龙用33岁短暂的人生制造了一段传奇。从他离开这个世界的第一天起，他的追随者就对这位“功夫之王”进行了各种形式的追忆和纪念，这种狂热的纪念逐渐演变成一个神话，一个龙的神话， 一个空前绝后的神话。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：你七年前生病后逃离上海，如今带着自己的新书《逃离》回到上海做宣传，是否多少有些感慨？
男：我当年就特别有感触。七年前生病，我首先要逃出医院，要知道，当时我住的是中国肺科最好的医院。然后我要逃离上海。
女：那时候你好像刚结婚？
男：我结婚一个月后就查出得了大家都认为是不治之症的病，当时我的想法是和老婆离婚，不想耽误她。
女：她怎么想？
男：她说她没觉得这是多大的事，病了就病了，死了就死了，这都是命，你想那么多干吗。
女：在上海你的一切都很稳定，做出逃离上海的决定也不容易吧？
男：在上海，我有大房子，有车，有社会地位。但对我来说，逃出医院才是最艰难的，因为我选择了自我治疗。
女：上海这座城市曾经给你什么美好的记忆吗？
男：上海带给我的记忆一直很美好。我的不适应还是在生活上、语言上，包括生病这件事。我之所以选择离开，主要是对于我生病地的水，我再也不想喝了。因为我只信水，所以想找到好的水、干净的水。我在《逃离》一书中反复地说，生命是以水为基础的。生病是生命的一部分，我决定用换水的方式来解决病的问题。那时医院的肺科主任对我说：“马老师，什么事情都没有耽误治疗的事情大。”这位医生说得入情入理，但我跟他们说，我自己的命，我做一回主。
女：你在山里过上了世外桃源的生活。你觉得，逃离最大的好处是什么？
男：不久前我才有了网络。这种与世隔绝的生活最大的好处是可以免遭外界干扰。对于都市生活的负面影响，各种各样的说法都有，譬如“都市病”，大家越来越觉得都市生活对人性本身是一种禁锢。在大山里则不同，可以让我在寂静中沉下心来思索。一个人独居，就会有特别多的想法。我每天的生活是简单的，在这个简单里，你很容易进入一种抽象思维的状态，很容易变得哲学化。
