* 听力

** 第二部分
:PROPERTIES:
:ID: 0c8f7649-95c7-46fe-9a94-99e4b012d1c0
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：张老师，我最近拜读了一些您在杂志上发表的关于青少年教育的文章，很受启发，很多家长也想借今天的机会向您请教一些生活中碰到的实际问题。我就开门见山了，第一个问题就是怎样才能帮助孩子养成良好的学习习惯和生活习惯。
女：家长要从小培养孩子自己做主的能力，要让孩子自己设定做事规则，然后自己遵守，大了，要懂得自己承担结果。要相信孩子有能力做到这一点，让他们自己建立好的生活习惯。家长的作用只是引导他们，在旁边鼓励他们，告诉他们错在哪儿。好的生活习惯是一点一点建立的，要给他们时间去坚持。
男：有些家长很苦恼，觉得孩子很大了，独立自主的生活能力却很差。
女：我认为，最重要的一点就是要学会给孩子独立成长的空间。现在很多家长什么事都替孩子做了，让他们丧失了锻炼的机会。家长以为这就是爱，实际是害！家长要克制自己保护的欲望，不要事事都不放心，要让孩子拥有成长的空间。
男：您说得有道理，家长也巴不得孩子能自己的事自己做主呢，可是如今生活节奏很快，一步走错就可能耽误一生，孩子的事输不起呀。
女：可是谁都不能代替孩子一辈子啊！
男：还有一些家庭，在孩子教育问题上，爷爷奶奶、姥姥姥爷和孩子的父母会出现不同意见，这时候应该怎么办呢？
女：无论意见多么不同，家庭成员之间最重要的是沟通。家庭和睦、彼此融洽是首要的，最怕的是吵架，或者是大伙儿同时过于严厉或过于慈爱。家庭成员要有角色定位，老公扮演慈父，妻子就是严母；老公扮演严父，妻子就是慈母。过于严厉，孩子可能会出现离家出走或者自杀的极端行为；过于慈爱，对孩子的成长也是不利的。

**** 音频

a49afe35-8d0b-4d74-8fac-17aa5c9e59ad.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 68739a6a-3ede-43df-af72-948d53238d0c
:END:

***** 问题

关于张老师，可以知道什么？

****** 音频

fd9e8c94-1146-44eb-9b38-bd23a5220970.mp3

***** 选择

****** A

她是一名作家

****** B

她在杂志社工作

****** C

她研究青少年教育

****** D

她是一位严厉的母亲

***** 答案

C

**** 7
:PROPERTIES:
:ID: 529bfe01-e895-4982-bb7f-71b822ef893d
:END:

***** 问题

张老师觉得应该怎样培养孩子良好的学习习惯和生活习惯？

****** 音频

c958e17a-0585-4b8d-8a8d-84524ccd0f36.mp3

***** 选择

****** A

教育孪子不能害怕失败

****** B

要教会孩子做事有计划

****** C

不能让孩子事事自己拿主意

****** D

应该学会多引导和鼓励孩子

***** 答案

D

**** 8
:PROPERTIES:
:ID: 65cce5ae-83de-4621-b06d-64231489566d
:END:

***** 问题

怎样解决孩子独立自主能力缺乏的问题？

****** 音频

b6ddf010-bb31-4c85-94bc-39139f3ba936.mp3

***** 选择

****** A

家长不要太能干了

****** B

家长不要包办代替

****** C

要让孩子懂得负责

****** D

要多给孩子一些爱

***** 答案

B

**** 9
:PROPERTIES:
:ID: 96765400-0013-4fda-a893-0c5afddfaf6a
:END:

***** 问题

家长为什么总喜欢事事代替孩子做？

****** 音频

aabd2e7a-c79e-4899-8154-204a65c0ab59.mp3

***** 选择

****** A

他们怕孩子做错了主

****** B

他们想一生替孩子做主

****** C

他们觉得孩子做不了主

****** D

他们觉得孩子做事没道理

***** 答案

A

**** 10
:PROPERTIES:
:ID: 71b72a73-bd36-4d3c-928f-7b30a4a85c4d
:END:

***** 问题

家庭成员之间，在教育孩子的问题上意见不一致时要注意什么？

****** 音频

f69c74cc-c2c3-483f-b6e7-218502891ef2.mp3

***** 选择

****** A

要多和老师沟通

****** B

要多替对方着想

****** C

要多给孩子一些爱

****** D

家庭成员之间不要吵架

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

阿姨特别喜欢孩子

***** B

阿姨去明明家做客

***** C

明明很喜欢喝凉茶

***** D

明明自己喝茶自己倒

**** 段话

妈妈不在家，明明像个小绅士，把阿姨迎进门，跑到桌子前，费力地踮起脚尖，倒了一大杯凉茶，郑重地捧到阿姨面前。阿姨别提多感动了，接过凉茶，瞬间，暑气已经消散了一半。

***** 音频

3a045cc9-8c7d-4aef-b75b-fcd3de033b0a.mp3

**** 答案

B

*** 2

**** 选择

***** A

露西跟“我“很亲密

***** B

露西特别不会说话

***** C

“我“嫉妒露西会说话

***** D

“我“被露西称赞很高兴

**** 段话

露西来到我家。早餐我准备了包子和小馄饨，孩子们边吃边聊，滔滔不绝。吃完早饭，露西对我说：“这是我吃过的最好吃的美味佳肴，非常感谢您！”我瞬间被露西的赞美感动了。

***** 音频

51c38f21-52f4-4a7d-8899-f87118c11adf.mp3

**** 答案

D

*** 3

**** 选择

***** A

孩子应有人督促

***** B

孩子都喜欢自由

***** C

父母知道应该怎样培养孩子

***** D

溺爱孩子会扼杀成长的动力

**** 段话

到底应该怎样培养孩子？显然，过分地溺爱、过度地保护、天天督促他们埋头在书本堆里死读书都是错误的。大家知道，自然是孩子的天性，自由是孩子的本性，约束天性和本性，就是扼杀成长的活力和动力，这样的教育一定不会成功。

***** 音频

593f35d6-e997-4a80-86bc-2a6949c32322.mp3

**** 答案

B

*** 4

**** 选择

***** A

孙悟空是警察

***** B

孙悟空很有风度

***** C

我们都离不开孙悟空

***** D

《西游记》是一本小说

**** 段话

我很喜欢古典小说《西游记》里的孙悟空，他勇敢、聪明，能分清好人与坏人，他用超人的本领守护他的师傅和弟兄们，就像我们生活里的警察，抓坏人，帮好人，时刻保卫着我们，这就是《西游记》给我的启示。

***** 音频

b53565a2-54ff-4f80-aac4-0a233e9fa80a.mp3

**** 答案

D

*** 5

**** 选择

***** A

孩子应关注父母的健康

***** B

父母也应学会讨好孩子

***** C

有些父母让孩二感到失望

***** D

父母应重视孩子的心理成长

**** 段话

当孩子告诉父母“我感到难受”“我很失望”时，粗心的父母往往会一笑了之，甚至会说：“小孩子，有什么可失望的。”这就是现今多数父母存在的问题，他们忽略了孩子的心理成长。

***** 音频

94539906-124c-4ef6-b845-09f4d6ec54d2.mp3

**** 答案

D

** 第三部分

*** 11-13

**** 课文

新美南吉，1913 年出生于日本爱知县半田市。童话和儿童小说作家。日本儿童文学研究者石井桃子曾说过：“北有宫泽贤治，南有新美南吉。”新美南吉代表作《小狐狸阿权》《小狐狸买手套》《去年的树》等多篇经典童话被日本、韩国、中国选入语文教材。他终生独身，英年早逝，去世时仅仅 30 岁。他的童话和儿童小说极具人情味，重视故事性。家乡的自然风土人情造就了他非凡的感受力，复杂的家庭环境和贫困体弱等生活背景又使得他在作品中对处于不同生存状态的人和动物寄予了无限的同情。为了纪念新美南吉，在他的家乡爱知县半田市建有“新美南吉纪念馆”；以他的名字命名的“新美南吉儿童文学奖”是日本最重要的儿童文学奖项之一。

**** 题目

***** 11

****** 选择

******* A

新美南吉懂韩语和汉语

******* B

新美南吉一生没有结婚

******* C

新美南吉30岁成名

******* D

新美南吉最喜欢狐狸

***** 12

****** 选择

******* A

在日本南方知道的人不多

******* B

只有三篇作品称得上经典

******* C

作品主要描写家乡的自然风景

******* D

中国的语文课本选了他的作品

***** 13

****** 选择

******* A

在他的家乡建了纪念馆

******* B

大力参与保护动物的活动

******* C

出版了新美南吉的所有童话

******* D

以他的童话命名儿童文学奖

*** 14-17

**** 课文

“子不教，父之过”，意思是说生养了孩子却不教育，是父亲的过错，这句话一点儿也不假。父亲参与家教有利于子女的智力开发和体质的增强。父亲与孩子游戏时，善于变换花样，更能满足孩子不同爱好和情趣的需要。父亲参与家教有利于培养子女的社交能力。父亲常和孩子在一起，孩子在人际关系中就有安全感和自尊心，容易与他人友好相处。此外，父亲参与教育孩子还能促使孩子产生对事业成就的追求。社会学家认为，一个人的事业成就感同父亲与他们的关系有密切的联系。换言之，与父亲关系密切的子女，一般都有较强的上进心和工作毅力。如果父亲和母亲一起关心培养孩子，那么无论男孩还是女孩，在语言、理解各种概念和数学计算等方面都会发展得比较全面。大量研究资料表明：孩子总是接受母亲的教育而缺乏父亲的参与，就容易产生依赖性，一旦离开家庭，独立自主能力差的问题就会体现出来。因此，“子不教，父之过”这话一点儿都不假。

**** 题目

***** 14

****** 选择

******* A

过去父亲不管教育子女

******* B

培养孩子比给他生命重要

******* C

孩子不愿意接受父亲的管教

******* D

孩子没教育好是父亲的责任

***** 15

****** 选择

******* A

孩子会有更多爱好

******* B

孩子会变得更有情趣

******* C

孩子会更懂得尊重别人

******* D

孩子的事业心会更强

***** 16

****** 选择

******* A

容易与他人相处

******* B

独立自主能力差

******* C

不愿意参加体育活动

******* D

不知道怎样能够成功

***** 17

****** 选择

******* A

孩子更喜欢依赖母亲

******* B

缺少父爱的孩子问题多

******* C

父亲在家教中不可缺少

******* D

孩子在父爱下学会坚强

