* 听力

** 1

*** 1

**** transcript



**** alternatives

***** a

妈妈不在家，明明像个小绅士，把阿姨迎进门，跑到桌子前，费力地踮起脚尖，倒了一大杯凉茶，郑重地捧到阿姨面前。阿姨别提多感动了，接过凉茶，瞬间，暑气已经消散了一半。

****** translation in english
:PROPERTIES:
:CREATED: [2022-08-22 21:44:48 -05]
:END:

Mom is not at home, Ming Ming like a little gentleman, the aunt into the door, ran to the table, struggling on tiptoe, poured a large cup of herbal tea, solemnly held in front of the aunt. Aunt can not mention how touched, took the herbal tea, instantly, the summer heat has been dissipated half.

***** b



***** c



***** d



**** answer



*** 2

**** transcript

露西来到我家。早餐我准备了包子和小馄饨，孩子们边吃边聊，滔滔不绝。吃完早饭，露西对我说：“这是我吃过的最好吃的美味佳肴，非常感谢您！”我瞬间被露西的赞美感动了。

***** translation in english
:PROPERTIES:
:CREATED: [2022-08-22 21:44:22 -05]
:END:

Lucy came to my house. For breakfast I prepared buns and small ravioli, and the kids ate and talked about them. After breakfast, Lucy said to me, "This is the best delicious food I have ever eaten, thank you very much!" I was instantly touched by Lucy's compliment.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

到底应该怎样培养孩子？显然，过分地溺爱、过度地保护、天天督促他们埋头在书本堆里死读书都是错误的。大家知道，自然是孩子的天性，自由是孩子的本性，约束天性和本性，就是扼杀成长的活力和动力，这样的教育一定不会成功。

***** translation in english
:PROPERTIES:
:CREATED: [2022-08-22 21:43:54 -05]
:END:

How should I raise my children? Obviously, i7t is wrong to over-indulge, over-protect, and urge them to bury their heads in books and study hard every day. As we all know, nature is the child's nature and freedom is the child's nature. To restrain nature and nature is to kill the vitality and motivation of growth, and such education will definitely not be successful.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

我很喜欢古典小说《西游记》里的孙悟空，他勇敢、聪明，能分清好人与坏人，他用超人的本领守护他的师傅和弟兄们，就像我们生活里的警察，抓坏人，帮好人，时刻保卫着我们，这就是《西游记》给我的启示。

***** translation in english
:PROPERTIES:
:CREATED: [2022-08-22 21:43:33 -05]
:END:

I like the Monkey King in the classical novel "Journey to the West" very much. He is brave, smart and can distinguish the good guys from the bad guys, and he guards his master and brothers with superhuman skills, just like the police in our life, catching the bad guys and helping the good guys, defending us all the time.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

当孩子告诉父母“我感到难受”“我很失望”时，粗心的父母往往会一笑了之，甚至会说：“小孩子，有什么可失望的。”这就是现今多数父母存在的问题，他们忽略了孩子的心理成长。

***** translation in english
:PROPERTIES:
:CREATED: [2022-08-22 21:43:04 -05]
:END:

When children tell their parents "I feel bad" or "I'm disappointed," careless parents tend to laugh it off and even say, "Kids, there's nothing to be disappointed about." This is the problem with most parents today, they ignore the psychological growth of their children.

**** alternatives

***** a



***** b



***** c



***** d



**** answer



1

**  第二部分
:PROPERTIES:
:ID: 0c8f7649-95c7-46fe-9a94-99e4b012d1c0
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

男：张老师，我最近拜读了一些您在杂志上发表的关于青少年教育的文章，很受启发，很多家长也想借今天的机会向您请教一些生活中碰到的实际问题。我就开门见山了，第一个问题就是怎样才能帮助孩子养成良好的学习习惯和生活习惯。
女：家长要从小培养孩子自己做主的能力，要让孩子自己设定做事规则，然后自己遵守，大了，要懂得自己承担结果。要相信孩子有能力做到这一点，让他们自己建立好的生活习惯。家长的作用只是引导他们，在旁边鼓励他们，告诉他们错在哪儿。好的生活习惯是一点一点建立的，要给他们时间去坚持。
男：有些家长很苦恼，觉得孩子很大了，独立自主的生活能力却很差。
女：我认为，最重要的一点就是要学会给孩子独立成长的空间。现在很多家长什么事都替孩子做了，让他们丧失了锻炼的机会。家长以为这就是爱，实际是害！家长要克制自己保护的欲望，不要事事都不放心，要让孩子拥有成长的空间。
男：您说得有道理，家长也巴不得孩子能自己的事自己做主呢，可是如今生活节奏很快，一步走错就可能耽误一生，孩子的事输不起呀。
女：可是谁都不能代替孩子一辈子啊！
男：还有一些家庭，在孩子教育问题上，爷爷奶奶、姥姥姥爷和孩子的父母会出现不同意见，这时候应该怎么办呢？
女：无论意见多么不同，家庭成员之间最重要的是沟通。家庭和睦、彼此融洽是首要的，最怕的是吵架，或者是大伙儿同时过于严厉或过于慈爱。家庭成员要有角色定位，老公扮演慈父，妻子就是严母；老公扮演严父，妻子就是慈母。过于严厉，孩子可能会出现离家出走或者自杀的极端行为；过于慈爱，对孩子的成长也是不利的。

**** 音频

a49afe35-8d0b-4d74-8fac-17aa5c9e59ad.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: 68739a6a-3ede-43df-af72-948d53238d0c
:END:

***** 问题

关于张老师，可以知道什么？

****** 音频

fd9e8c94-1146-44eb-9b38-bd23a5220970.mp3

***** 选择

****** A

她是一名作家

****** B

她在杂志社工作

****** C

她研究青少年教育

****** D

她是一位严厉的母亲

***** 答案

C

**** 7
:PROPERTIES:
:ID: 529bfe01-e895-4982-bb7f-71b822ef893d
:END:

***** 问题

张老师觉得应该怎样培养孩子良好的学习习惯和生活习惯？

****** 音频

c958e17a-0585-4b8d-8a8d-84524ccd0f36.mp3

***** 选择

****** A

教育孪子不能害怕失败

****** B

要教会孩子做事有计划

****** C

不能让孩子事事自己拿主意

****** D

应该学会多引导和鼓励孩子

***** 答案

D

**** 8
:PROPERTIES:
:ID: 65cce5ae-83de-4621-b06d-64231489566d
:END:

***** 问题

怎样解决孩子独立自主能力缺乏的问题？

****** 音频

b6ddf010-bb31-4c85-94bc-39139f3ba936.mp3

***** 选择

****** A

家长不要太能干了

****** B

家长不要包办代替

****** C

要让孩子懂得负责

****** D

要多给孩子一些爱

***** 答案

B

**** 9
:PROPERTIES:
:ID: 96765400-0013-4fda-a893-0c5afddfaf6a
:END:

***** 问题

家长为什么总喜欢事事代替孩子做？

****** 音频

aabd2e7a-c79e-4899-8154-204a65c0ab59.mp3

***** 选择

****** A

他们怕孩子做错了主

****** B

他们想一生替孩子做主

****** C

他们觉得孩子做不了主

****** D

他们觉得孩子做事没道理

***** 答案

A

**** 10
:PROPERTIES:
:ID: 71b72a73-bd36-4d3c-928f-7b30a4a85c4d
:END:

***** 问题

家庭成员之间，在教育孩子的问题上意见不一致时要注意什么？

****** 音频

f69c74cc-c2c3-483f-b6e7-218502891ef2.mp3

***** 选择

****** A

要多和老师沟通

****** B

要多替对方着想

****** C

要多给孩子一些爱

****** D

家庭成员之间不要吵架

***** 答案

D

** 第一部分

*** 1

**** 选择

***** A

阿姨特别喜欢孩子

***** B

阿姨去明明家做客

***** C

明明很喜欢喝凉茶

***** D

明明自己喝茶自己倒

**** 段话

妈妈不在家，明明像个小绅士，把阿姨迎进门，跑到桌子前，费力地踮起脚尖，倒了一大杯凉茶，郑重地捧到阿姨面前。阿姨别提多感动了，接过凉茶，瞬间，暑气已经消散了一半。

***** 音频

3a045cc9-8c7d-4aef-b75b-fcd3de033b0a.mp3

**** 答案

B

*** 2

**** 选择

***** A

露西跟“我“很亲密

***** B

露西特别不会说话

***** C

“我“嫉妒露西会说话

***** D

“我“被露西称赞很高兴

**** 段话

露西来到我家。早餐我准备了包子和小馄饨，孩子们边吃边聊，滔滔不绝。吃完早饭，露西对我说：“这是我吃过的最好吃的美味佳肴，非常感谢您！”我瞬间被露西的赞美感动了。

***** 音频

51c38f21-52f4-4a7d-8899-f87118c11adf.mp3

**** 答案

D

*** 3

**** 选择

***** A

孩子应有人督促

***** B

孩子都喜欢自由

***** C

父母知道应该怎样培养孩子

***** D

溺爱孩子会扼杀成长的动力

**** 段话

到底应该怎样培养孩子？显然，过分地溺爱、过度地保护、天天督促他们埋头在书本堆里死读书都是错误的。大家知道，自然是孩子的天性，自由是孩子的本性，约束天性和本性，就是扼杀成长的活力和动力，这样的教育一定不会成功。

***** 音频

593f35d6-e997-4a80-86bc-2a6949c32322.mp3

**** 答案

B

*** 4

**** 选择

***** A

孙悟空是警察

***** B

孙悟空很有风度

***** C

我们都离不开孙悟空

***** D

《西游记》是一本小说

**** 段话

我很喜欢古典小说《西游记》里的孙悟空，他勇敢、聪明，能分清好人与坏人，他用超人的本领守护他的师傅和弟兄们，就像我们生活里的警察，抓坏人，帮好人，时刻保卫着我们，这就是《西游记》给我的启示。

***** 音频

b53565a2-54ff-4f80-aac4-0a233e9fa80a.mp3

**** 答案

D

*** 5

**** 选择

***** A

孩子应关注父母的健康

***** B

父母也应学会讨好孩子

***** C

有些父母让孩二感到失望

***** D

父母应重视孩子的心理成长

**** 段话

当孩子告诉父母“我感到难受”“我很失望”时，粗心的父母往往会一笑了之，甚至会说：“小孩子，有什么可失望的。”这就是现今多数父母存在的问题，他们忽略了孩子的心理成长。

***** 音频

94539906-124c-4ef6-b845-09f4d6ec54d2.mp3

**** 答案

D

