* 听力

** 第二部分
:PROPERTIES:
:ID: 64b30c45-d8ad-465f-82bb-f39cdb559b33
:NOTETYPE: content-with-audio-5-multiple-choice-exercises
:END:

*** 对话

女：有报告显示，当前中国移动阅读用户规模已经达到 2.42 亿，移动阅读、电子阅读正成为当下国人阅读的新常态。张老师，您对此怎么看？
男：我想，我们应该想清楚一个问题：读书对人生究竟意味着什么？
女：您是怎样阅读的？
男：我阅读也有一个变化过程的。我 40 岁之前，看的都是书本，是一个标准的书本族；2000 年以后，我开始渐渐习惯在电脑上阅读，尤其是开通了微博以后，我花在电脑上的时间越来越多；接着又有了微信，一开始也是觉得好玩儿，渐渐发现自己离不开手机了，不知不觉中变成了一个手机族。
女：您还是挺顺应时代潮流的呀！
男：这样的生活让我产生了一种恐惧，我发现自己没有了读书的时间。而且，这些微博、微信上的内容大多都是“信息快餐”，90％的内容看完就忘记了，为了记住 10％的东西，而浪费了 90％的时间，于是我逼迫自己回归书本。
女：您的做法是？
男：我给自己立了个规矩，每天只在“垃圾时间”里看手机，剩下的时间还是读书，而且要说话算数。
女：为什么这样呢？怎么阅读不是阅读啊？
男：不一样。人们通过微信、微博阅读到的大多是资讯，而不是知识。手机阅读很轻松，但仅仅是表层阅读。表层阅读愉快，不怎么需要你思考，激起某种情感就过去了。
女：那么，书本阅读应该称为深层阅读了？
男：可以这么说。我们读书大多读的是知识，知识是完整的，它有一个体系，以一套系统来解释世界，它不是以碎片的方式存在的，我们阅读的时候是要静下心来细细思考、理解、消化、沉思的。

**** 音频

ad9fd52a-585d-4b83-b5f2-1407598d016e.mp3

*** 题目

**** 6
:PROPERTIES:
:ID: c2da285f-ea51-41fd-882c-5087a2b11237
:END:

***** 问题

对于当下国人阅读的新常态，张老师怎么看？

****** 音频

5ebc817d-b7f4-415a-b610-52b282b40b69.mp3

***** 选择

****** A

应先弄明白读书的意义

****** B

应先搞清楚人生的意义

****** C

人都不可能逆潮流而动

****** D

应认真考虑阅读的新趋势

***** 答案

A

**** 7
:PROPERTIES:
:ID: ab67b790-cca2-48ae-a7e9-fac3ccb068b3
:END:

***** 问题

关于张老师，下列哪项正确？

****** 音频

acf57438-4ce2-4ada-8c2e-e68f542037af.mp3

***** 选择

****** A

勇于尝试新事物

****** B

只喜欢做书本族

****** C

从年轻时就是手机族

****** D

感觉电脑阅读优于读书

***** 答案

A

**** 8
:PROPERTIES:
:ID: 08d03d3c-de65-4283-bd4f-79be7c27fdea
:END:

***** 问题

张老师因为什么恐惧过？

****** 音频

ddedd137-a895-4685-ac9c-dcece94f0004.mp3

***** 选择

****** A

记忆力越来越差

****** B

浪费了90％的人生

****** C

垃圾信息数量惊人

****** D

自己没有时间读书了

***** 答案

D

**** 9
:PROPERTIES:
:ID: 7c155aa6-6879-49f3-9825-b18a76e10720
:END:

***** 问题

关于表层阅读和深层阅读，下列哪项正确？

****** 音频

70f78dd3-730f-47b1-9d44-9a04d54cdcd3.mp3

***** 选择

****** A

表层阅读需调整情绪

****** B

表层阅读是休闲阅读

****** C

深层阅读讲究连续性

****** D

胃口不好的人无法深层阅读

***** 答案

B

**** 10
:PROPERTIES:
:ID: 7ebe2c44-362a-4a24-896f-72ece28e33f6
:END:

***** 问题

根据上文，阅读对人生究竟意味着什么？

****** 音频

3210ffa3-7aa4-4d2b-8f3b-761ce742edfb.mp3

***** 选择

****** A

通过阅读了解知识的完整性

****** B

通过阅读、思考，了解世界

****** C

占有更多资讯，提高自身修养

****** D

轻松阅读，调动生活的积极性

***** 答案

B

** 第一部分

*** 1

**** 选择

***** A

秘方往往不能外传

***** B

中医家里都有秘方

***** C

老百姓有自己的秘方

***** D

保险柜不如枕头底下可靠

**** 段话

中医的秘方特别有趣，老百姓都有这样的概念，说秘方往往是中医家族里边最核心的机密，要保密，坚决不能告诉别人，都是在自家枕头底下藏着或者在保险柜里锁着的。

***** 音频

3c433303-a399-41db-84cb-14bfdc66094f.mp3

**** 答案

A

*** 2

**** 选择

***** A

她非常难过

***** B

她刚刚睡醒

***** C

她在船上工作

***** D

她喜欢孙悟空

**** 段话

她准备敲舱门的手久久举着，如同蟠桃园里被孙悟空施了定身法的瑶池仙女。直到有人从船舱另一侧走来，她才醒过神来，急匆匆地返回自己的舱里，趴在铺上牙咬枕巾哭泣起来。

***** 音频

f0d51e1f-f36c-4efd-bb10-0cb4d44409db.mp3

**** 答案

A

*** 3

**** 选择

***** A

母亲怀有深深的自责

***** B

父亲对儿子爱恨交加

***** C

儿子早就不想理父母丁

***** D

父母已经不想认儿子了

**** 段话

母亲双手合十，深深地低下了头。父亲缓慢地站起身，虽然热泪盈眶，却微笑着回过身来，抬起手给了儿子一记响亮的耳光，说道：“去了这么长时间！你这个调皮鬼，还记得有家！”

***** 音频

e1e3a12b-91e8-4dc9-bb09-8c7ab67ca228.mp3

**** 答案

B

*** 4

**** 选择

***** A

陶侃对部下管理很严

***** B

陶侃气急了就会打人

***** C

陶侃善于动脑筋思考

***** D

陶侃的手下都很自觉

**** 段话

陶侃手下的一些官吏喜欢喝酒，往往因此误了公务。陶侃知道了非常生气。他吩咐人把酒器一古脑儿扔到江里去，还把那些官吏鞭打了一顿。从此以后，大家都吓得不敢再喝酒了。

***** 音频

a8ff0f1b-e051-418c-8c2d-5de6cee0c19a.mp3

**** 答案

A

*** 5

**** 选择

***** A

追随沃尔特的画家很多

***** B

画家都喜欢在车库工作

***** C

尧布是个很能干的助手

***** D

天气不好沃尔特也工作

**** 段话

沃尔特的得力助手尤布很欣赏这只叫米奇的老鼠，他认为它的表情有点儿像沃尔特本人。沃尔特和尤布抓紧时间进行米老鼠的设计。他们避开其他画家们，躲到沃尔特家后面的一个车库里工作，为的是不走漏一点儿风声。

***** 音频

0f428929-0c3f-427e-b329-e4bd07b3fa48.mp3

**** 答案

C

