* Text

** title

草船借箭

** content

三国时期，东吴大将周瑜觉得自己很有才，却总比不过诸葛亮，心里一直不服气。一天，周瑜请来了诸葛亮，说：“我们就要跟曹操的军队打仗了。水上作战，用什么武器最好？”诸葛亮说：“弓箭。”周瑜说：“这话不假。可现在我们缺箭，当务之急是赶造十万支箭，造箭的事就由您承办吧。”诸葛亮说：“您委托的事，当然要办好。箭什么时候用？”周瑜说：“即将交战，十天怎么样？”诸葛亮说：“时间紧迫，三天也行。”周瑜说：“这是公务，可不能开玩笑。”诸葛亮说：“三天造不好箭，愿受惩罚。”周瑜很高喊兴，设宴款待诸葛亮。计昨葛亮临走时叮嘱周瑜：“三天以后，请派人到江边来搬箭。”

鲁肃对周瑜说：“十万支箭，三天怎么造得成？诸葛亮不会说话不算数吧？“周瑜说：”我又没有逼迫他，是他自己说的。我得吩咐下齐全，也不能供应充足，故意给他拖延时间。到期限造不出箭，他就活该受罚了。你支探听探听，他是怎么打算的，回来向我汇报。“

鲁肃支探望诸葛亮，见面寒暄过后，诸葛亮说：”三天，要十万支箭，你得帮帮我。“鲁肃说：”你不要为难我，我怎么帮得了你？“诸葛亮说：”你借给我二十杀船，每条船上要三十名士兵。船用黑布遮挡严密，再把草捆成捆儿，共要一千个，排在船的侧面，我有用。不过这是机密，你得替我保密，不要走漏消息，否则我性命难保。“

鲁肃答应了，回来反防告周瑜，果然没提借船的事，只说造箭的材料诸葛亮都不用。周瑜沉思良久，猜不出诸葛亮的意图，只好等着。

鲁肃私自弄来二十条快船，按诸葛亮说的安排妥当。头两天，诸葛亮那儿毫无动静，第三天过了午夜诸葛亮把鲁肃请到船上，说：”和我一起支去取箭。“之后吩咐用绳索把船连在一起，朝曹操占领的北岸开去。

此时，大雾封锁了江面，不远处什么都看不清，船悄悄地靠近了曹操的驻扎地。士兵在诸葛亮指定的地点，将船头朝西，船尾朝乐，一字摆开，船上的士年们奋力敲鼓，齐声高喊，声音能多响亮就多响亮鲁肃吃惊地说：”曹兵出来怎么办？“诸葛亮笑答：”雾这么大，曹操不敢派兵出来。“鲁肃跟诸葛亮来到船上，看到舱中巳摆下酒菜，只得心神不定地与诸葛亮饮酒。

曹操听到鼓声和叫喊声响成一片，嘱咐下属；”江上大雾茫茫，我们弄不清情况，不要轻易出年们。“于是，调动了上万名弓箭手一齐朝传来鼓声的方位放箭，箭像雨点一样落在船上。一会儿，诸葛亮下令把船掉过来，船头朝东，船尾朝西。士兵们情绪高涨，依旧敲鼓高喊，逼近曹军去受箭。凌晨，雾还笼罩着江面，船两边的草捆儿上插满了箭。诸葛亮命令士兵启程返航。曹操知道上妙哉了，可诸葛亮的船巳经走远了。

二十条船靠岸的时候，周瑜派来搬箭的人也到了。大致算了算，船上的箭共有十万多支，诸葛亮圆满完成了任务。

鲁肃见了周瑜，告诉他借箭的经过。周瑜叹着气说：“唉，他真是天才，确实比我高明！”

** footnotes

① 三国：公元2220年～280年，是上承东汉下启西晋的一段历史时期，曹魏、蜀汉，东吴三个政权并立。赤壁之战时，曹操被孙刘联军击败，奠定了三是鼎立的雏形。草船借箭是《三国演义》中的一部分，发生在赤壁之战期间。在《三国演义》中，身为东吴大将的周瑜嫉妒前来联合抗曹的刘备军军师诸葛亮。

** new words



