* 听力

** 1

*** 1

**** transcript

台湾一家食品公司根据消费者的不同需求和中秋节期间暑气未消的特点，创新推出了中秋雪月饼。何为雪月饼？雪月饼就是冰淇淋月饼，清凉降温，口感滑爽。此款月饼还精心采用具有保温作用的包装盒，保证雪月饼在一定时间内不融化。这就是这款产品广受欢迎之所在吧。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

中国古老的养生之道最注重季节气候变化，季节不同，饮食起居随之变化。立秋以后气温由热转凉，人体的消耗也逐渐减少，食欲开始增加。这时候就要科学地摄取营养和调整饮食，以补充夏季的消耗，并为越冬做准备。


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

2000多年前的农历五月初五，著名诗人屈原跳入汨罗江而死。老百姓立刻划龙船去寻找屈原，并将粮食、肉粒用竹叶包裹后给鱼虾投入江水中，以防止其吞食屈原。这个传统延续至今，也就有了今天的端午节赛龙舟和吃粽子的风俗习惯。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

这家胡同深处小饭馆的主人，是一位英文流利的有国际视野的老北京人。每逢周末，她就会办起烹饪课堂，教客人包饺子，做正宗的中国菜。她还兼营茶叶生意，所以这里的品茶课堂自然也不能少，让喝惯了红茶加柠檬的外国人，也尝尝中国辽阔的土地上栽培出的白茶的醇厚与绿茶的清香。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

看似简单的就餐中蕴含着很多学问，进食时要专心致志，不要边吃边讲话，也不要边吃边看书报或电视，以免妨碍消化。同时要细嚼慢咽，千万不要狼吞虎咽。进食之后不能做剧烈活动，也不可立即躺下休息。可以缓步行走，也可以擦热双手后按摩肚子数百遍以助消化。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



