* 听力

** 1

*** 1

**** transcript

台湾一家食品公司根据消费者的不同需求和中秋节期间暑气未消的特点，创新推出了中秋雪月饼。何为雪月饼？雪月饼就是冰淇淋月饼，清凉降温，口感滑爽。此款月饼还精心采用具有保温作用的包装盒，保证雪月饼在一定时间内不融化。这就是这款产品广受欢迎之所在吧。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 2

**** transcript

中国古老的养生之道最注重季节气候变化，季节不同，饮食起居随之变化。立秋以后气温由热转凉，人体的消耗也逐渐减少，食欲开始增加。这时候就要科学地摄取营养和调整饮食，以补充夏季的消耗，并为越冬做准备。


**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 3

**** transcript

2000多年前的农历五月初五，著名诗人屈原跳入汨罗江而死。老百姓立刻划龙船去寻找屈原，并将粮食、肉粒用竹叶包裹后给鱼虾投入江水中，以防止其吞食屈原。这个传统延续至今，也就有了今天的端午节赛龙舟和吃粽子的风俗习惯。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 4

**** transcript

这家胡同深处小饭馆的主人，是一位英文流利的有国际视野的老北京人。每逢周末，她就会办起烹饪课堂，教客人包饺子，做正宗的中国菜。她还兼营茶叶生意，所以这里的品茶课堂自然也不能少，让喝惯了红茶加柠檬的外国人，也尝尝中国辽阔的土地上栽培出的白茶的醇厚与绿茶的清香。

**** alternatives

***** a



***** b



***** c



***** d



**** answer



*** 5

**** transcript

看似简单的就餐中蕴含着很多学问，进食时要专心致志，不要边吃边讲话，也不要边吃边看书报或电视，以免妨碍消化。同时要细嚼慢咽，千万不要狼吞虎咽。进食之后不能做剧烈活动，也不可立即躺下休息。可以缓步行走，也可以擦热双手后按摩肚子数百遍以助消化。

**** alternatives

***** a



***** b



***** c



***** d



**** answer

**  第二部分

*** 对话

女：要想身体保持活力，水是必不可少的，可是你会喝水吗？怎样饮水才健康？今天我们请来养生专家吴先生跟大家聊一聊喝水的奥秘。
男：为了身体更健康，人们常常坚持一些所谓的好习惯，但这些习惯和作法反而给自己的健康埋下了隐患。看看这些习惯，你是不是也在坚持做呢？首先，请大家想一想，你认为每天应该喝几杯水呢？
女：不是常常说每天要喝八杯水吗？
男：事实是喝太多的水也会给身体带来麻烦。一个人喝水太多，容易使身体中的电解质失去平衡，一些水溶性维生素也更容易流失。
女：那么正常成年人每天喝多少水才算适当呢？
男：一般来说，我们每天需要补充 2000ml 左右的水分，但这不一定都通过喝水获得，应该把每天吃的食物中的水分算进去。因此，除掉每天食物中获得的1000～1200ml 水分，我们每天再喝 800～1000ml 的水，平均上、下午各两杯就足够了。
女：那感冒以后是不是应该多喝水啊？
男：也不是，感冒后如果喝过多的水导致电解质失去平衡，反而会减慢感冒的康复速度。同时，感冒和发烧时也不宜大量进食。要想感冒好得快，最好少食多餐，或者用一杯温水冲泡维生素 C，增强抵抗力。
女：水不能喝太多，那牛奶是不是多多益善呢？
男：牛奶照样不能多喝，我们常听说多喝牛奶可以补钙，真相却是多喝反而缺钙。正确的作法是一天 1～2 杯牛奶就可以满足全天所需的钙了。
