* Text

** title

大数据时代

** content

什么是大数据？枯燥的名词解释会让“科盲”们更加摸不着头脑，有学者以通俗的例子这样告诉我们，“每个人乘飞机时，都是自己选择航线，这是人的智慧，当人们的选择结果反映到具体的航程中来，就会有大量的数据被记录下来。我们根据这些原始的、堆积如山的记录梳理出的航程设计方案，将是最卓越的。这就是大数据的方法。”

大数据有什么用？举例来说，百度在2014年世界杯期间准确预测德国夺冠，就是大数据的功劳。百度的做法是：派遣数据专家全面溲索5年来全世界987支球队3.7万场比赛的数据，并与彩票中心等占有大量数据的相关机构建立战略合作伙伴关系，将各类数据融入预测模型中。这一海量数据库共计涉及19972名球员和1.12亿条相关数据。之后，百度对2006年和2010年世界杯的淘汰赛进行了结果验证，准确率接近75％，这一结果令大数据研究者万分振奋。

那么，大数据如何连接未来我们不妨以大数据与健康为例加以说明。人们公认“医疗”和“健康”分属两个完全不同的领域，有了大数据，它们不仅相通相融，还有可能彻底扭转先前陈旧而被动的有病治病方式，改为积极防治，甚至把疾病消灭在萌芽状成瘾中的想法也不显得荒廖了。

做进一步计论之前，有一个前提必须交代清楚：每一次疾病的发生都不是偶然的，追究原因，无非是基因、遣传、环境、生活习惯等。虽非偶然，却无法预料，因此，传统医疗只能帮你治病。如果能找出病因呢？消除隐患就成为了可能，“健康大数据”就是要做这件事。比如心脏病，病人发病常常是有预兆的，如果对患者的心跳数据有足够长时间的持续积累，就可能预测病人发病的时机；对于心脏病突发致死的案例，如果能提前24小时监测到零星先兆，甚至可以挽救患者的生命。

利用大数据对一个病种进行细致的监测，意义是不言而喻的。中国血压患者有1亿人，潜在患者还有我亿人，如果这2亿人都能通过“高血压手表”或者什么先进器材材进行监测，对他们的健康进行人为管理，将会是非常有前景的尝试。

在未来医疗模式中，临床会尽量减少对人的依赖，因为医生是切切实实的稀缺资源，大数据的优越之处效率，将医生的能量发挥到最大。因为大数据的健康维护不是得了病之后再采集数据，而是平时就在一些特殊设备的协助下，把人所有的生理数据攒起来，对其进行分析处理后，发给医生，远程医疗服务将会变得可行而且优质。实事求是地讲，即便仅仅做到这一点，大数据为人类做出的贡献也远远超出了我们的期盼。

展望未来，大数据将会走进我们生活的各个领域，有人这样定位大数据时代的意义：“拥有知识曾意味着掌握过去，现在它更意味着预测未来。”

** new words



