* Text

** title

体育明星们的离奇遭遇

** content

每次看到我们崇拜的体育明星在赛场上冲击奖牌，大家都深信，他们身上的每一处伤疤都是奋力拼搏的标记。可是你知道吗，明星们受伤，有时竟也荒廖得不可思议。

曾经有一名足球门将正在比赛趾聚精会神地防守，突然，一只狗以火箭般的速度冲了进来，横着冲向他的膝盖，然后向他发起进攻。人们惊呆了，这是阴谋，还是离奇的巧合？门将当场倒进地，身受重伤，经久不愈，最后竟因此告别了他心爱的职业。

南美足球赛场上的猫头鹰事件，赛后成了头条新闻。事情是这样的，球赛进行得正激烈时，一只很可能是因受伤而“迫降”球扬的猫头鹰遮挡住了球员的视线，主裁判出于保护动物的目的，决定中断比赛，可是一名的求员巳经刹不住车，一只大脚踢向了毫无防御的猫头鹰。可怜的猫头鹰，抢救两天后不治身亡。没想到一场道德讨论就此开始：有人认为想赢球也不能置猫头鹰的生命于不顾，这种只想赢球的心态和比赛精神南辕北辙。一时间，只注重胜负，却将猫头鹰残酷“射杀”致列死的行为是否应该被原谅，引起了广泛的争议。人们结结实实地打了一场嘴仗，动物保护组织甚至要和球员打官司；一些球迷认为猫头鹰是球场的守护神，甚至谴责球员就是凶手；被称为“凶手”的球员一定在心中大呼冤枉，但他还是为自己的行为诚恳道歉，道歉之余却也没忘了为自己辩解——他不是成心的。

明星们遭受的伤害有时出人意料。因赛事频繁，航空旅行成了运动员的家常便饭。你相信吗？登机牌也可能成为凶器。曾有运动员在机场被登机牌缶中眼睛，并因此错过部分比赛。

我们每个人都有过粗心大意的时候，令人悲哀的是，这也可能成为被伤害的原因。一次赛前热身，主办方特意做了警示牌，警告运动员不要在球门里训练，有位运动员一时疏忽正好踩在了警示牌上，由于重心不构刀，以致扭伤了脚；还有位同样疏忽的运动员，在折叠熨衣板时肩膀受伤；某国国脚有一次不仅磕破了嘴唇还磕掉了门牙，当时他仅仅是想从汽车里拽出高尔夫球具。

汉语有个词叫乐极生悲，说的就应该是下面这位球员：在打进一球后，他冲入观众席和球迷一起庆祝，结果结婚戒指连同他的手指一起挂在了围栏上，手指受冰重伤。更让他恼火的是，不了解情况的主裁判还给了他一张黄牌，真可谓雪上加霜！最荒唐的受伤当属某国国脚。他的脚指甲旁边长了个血泡，他决定自己处置。各种工具他都看不上，最后选中的竟然是电钻，由于用力过猛，把脚弄破了，以致感染，遭受了难以想象的痛苦。看来医生也不是谁想当就能当的，虽然在真正的医生眼里这只是个微不足道的小手术。

其实离奇伤害不仅存在于运动员当中，它也紧紧跟随着我们每一个人，只要你疏忽、大意。

** footnotes

① 南美：即南美洲，南亚美利加洲的简称，位于西半球南部，东面是大西洋，西面是太平洋。陆地以巴拿马运河为界与北美洲相分，南面隔海与南极洲相望。陆地面积约1800万平方千米，约占世界陆地总面积的12％。

** source

改编自《北京晚报》文章《体育明星们的“离奇伤害”》

** new words



