* 听力
** 第一部分
*** 1
:PROPERTIES:
:ID: 07f52e85-52b5-4811-a8f4-10b682374a0c
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
4a359d1a-2051-4a23-9cab-e13ecc2f93a9.mp3
***** 转录
不知不觉中，互联网已经进入了我们的生活。我们可以通过互联网得到海量信息，从天文到地理，从深水到太空，从远古到现代，从国内到国外；我们可以通过互联网学习，浏览新闻杂志，获知发生在世界各地的时事要闻。互联网给我们的生活带来了乐趣，使我们的生活变得更加充实。
**** 选择
***** A
网络的信息资源很有限
***** B
互联网充实了我们的生活
***** C
我们可以通过互联网环游世界
***** D
互联网让我们进入别人的生活
**** 答案
B
*** 2
:PROPERTIES:
:ID: b26d70fc-8f9e-4b61-8c11-3050480dacfa
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
fb1902e2-caf7-43d7-b006-c19941c19443.mp3
***** 转录
我们班一大半同学都有手机，虽然每次上课老师都要求我们关掉手机，但关不关就看自己了，很多人都把手机调到振动状态，在桌子下面偷偷玩。很多同学都对发短信上瘾，有同学喜欢自己编写各种短信，下课的时候还比较谁的短信新鲜好玩。
**** 选择
***** A
很多同学玩儿游戏上瘾
***** B
下课后大家会比较谁的手机好
***** C
老师对手机的管理不那么严格
***** D
老师脾气好，学生不听话就算了
**** 答案
C
*** 3
:PROPERTIES:
:ID: 362fa684-a09b-414d-bd45-8895f15dc5c0
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
b3220956-715f-473c-a39d-943ca8278768.mp3
***** 转录
作为年轻人，我们上网更多的是消遣和娱乐，有许多同龄人认为，网络这个完全虚拟的世界是我们放松自己的最佳场所。也许正因为这一点，我们的家长和老师才会对学生上网表现出不同程度的抵制，因为他们认为网上的娱乐分散了我们过多的精力，会对学业造成影响；更为重要的是，他们害怕网络上的不良信息对我们的身心不利。
**** 选择
***** A
家长和老师担心互联网诈骗
***** B
家长和老师担心互联网让人变怪
***** C
家长和老师担心互联网让人急功近利
***** D
家长和老师担心互联网会分散学生的精力
**** 答案
D
*** 4
:PROPERTIES:
:ID: 89137359-37ab-4143-994c-f7eeb7285dd6
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
df34fbdd-10bf-410c-8f3a-78e4165956ba.mp3
***** 转录
钱包不带没关系，手机千万不能忘，人们越来越深刻地感受到：在手机支付已成为重要的支付方式的今天，出门已不必非要手机、钱包、钥匙一样都不能少。互联网之所以能够进入金融业，不是因为互联网天生能做金融，而是因为传统的金融业忽略了网络支付功能。
**** 选择
***** A
互联网天生适合做金融
***** B
出门丢什么都不能丢手机
***** C
如今手机支付已十分普遍
***** D
手机、钱包、钥匙必须随身带
**** 答案
C
*** 5
:PROPERTIES:
:ID: b77f7efc-a8bd-4fe3-ba6b-d034bdcbd549
:EXPORT-ID: 6e4af68c-3365-49d9-bfcc-70d2ee989ab7
:END:
**** 段话
***** 音频
8cf63feb-9995-41aa-b892-be3215b01a9f.mp3
***** 转录
与传统的房地产开发模式相比，众筹建房的确大大缓解了房地产企业的销售压力。以往，在开发商的总成本中，融资成本和销售成本分别占比 7%和 3%左右，如今通过互联网设立的融资平台，房企绕过银行获得了新的融资渠道，从而将融资成本大大降低。另一方面，合伙众筹的成员也有机会从中受益，不但房价更合算，并且可以按照自己的需求定制房产，满足个性化需求。
**** 选择
***** A
众筹建房会增加融资成本
***** B
众筹建房的成员可以定制房产
***** C
房地产企业在众筹建房中很尴尬
***** D
传统房地产开发模式销售压力更小
**** 答案
B
** 第二部分
*** 6-10
:PROPERTIES:
:ID: e127423e-09c6-4643-b76c-3ea089fb9016
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 对话
***** 音频
963c8350-cd24-43ab-ae10-18b10051053f.mp3
***** 转录
女：您好！您能不能重点跟我们谈谈，社交网站给传统交往方式带来了哪些影响？
男：最近几年，社交网络非常流行。用户可以在网站创建一个公开或半公开的个人账号，展示和自己有联系的其他用户，查看和搜索与自己有联系的用户以及与朋友有联系的用户，还能交到新朋友，和更多的人建立起联系。
女：这是人们使用网站的主要目的吗？
男：还不是。
女：那人们使用社交网站的主要目的是什么呢？
男：应该说，社交网站主要体现的还是现实世界中的人际关系。社交网站使我们能够和平时不常见的人保持联系，但是要注意，介绍陌生人给你并不是社交网站的意图。
女：那现实中的友谊和互联网中的友谊有什么区别呢？
男：现实中的友谊和互联网上的友谊并不相同。在线联系并不意味着你们交换过电话号码，对于一些联系人，也许你觉得线上交流比线下交流舒服。网上的友谊一般是慢慢积累起来的，人们一般会在网上增加联系，而不会切断联系。而且，我们和朋友在网上的交流方式也不一样，比如在网上我们的交流更加简洁，而不是专注的、较长时间的对话。
女：在线上社交网络中，我们不仅维护着和所有朋友的珍贵友情，还能看到他们和其他人的交往和互动。这一点比在现实生活中要容易得多。
男：确实，有时候，你的线上好友传上一组照片，你会发现他们刚和你去了同一个国家……突然之间，你和好友的距离一下子就拉近了，对好友的日常生活一下就有了了解。也许你还会发现和你线上好友互动的人中，也有你的朋友，而你之前并不知道他们认识，这对于你，也许是一份惊喜。
**** 题目
***** 6
:PROPERTIES:
:ID: 075b50bd-f6c1-491e-a362-a1b42dee258b
:END:
****** 问题
******* 音频
ee062aa4-d4d6-4187-9872-46f3a79262ba.mp3
******* 转录
人们在社交网站上可以做什么？
****** 选择
******* A
炫耀和自己有联系的朋友
******* B
查看其他网络用户的账号
******* C
通过朋友交到更多的朋友
******* D
建立自己公开或半公开的账号
****** 答案
D
***** 7
:PROPERTIES:
:ID: c7bad2b7-000a-44e6-b102-52aa3b7ec53e
:END:
****** 问题
******* 音频
cc78f6e3-cfc9-42a8-bcbc-66f510d2db5a.mp3
******* 转录
人们使用线上社交网站的主要目的是什么？
****** 选择
******* A
迅速扩大朋友的范围
******* B
和更多的陌生人成为朋友
******* C
和不易见面的朋友保持联系
******* D
与已失联的朋友重新建立联系
****** 答案
C
***** 8
:PROPERTIES:
:ID: df251837-0b4d-446f-838a-4b2145d53cb7
:END:
****** 问题
******* 音频
0024cf16-c1da-4916-b495-36a83ffa0146.mp3
******* 转录
与网上交流方式相比，线下交流的特点是什么？
****** 选择
******* A
交流更加简洁
******* B
联系更加频繁
******* C
对话更加专注
******* D
对话时间更短
****** 答案
C
***** 9
:PROPERTIES:
:ID: 1049cab8-ea88-4267-a60c-4c763943dec0
:END:
****** 问题
******* 音频
0fc51a17-5e6e-4fe6-98bf-28ef58a3b9e6.mp3
******* 转录
互联网中的友谊有什么特点？
****** 选择
******* A
交流起来更加任性
******* B
不想联系了就自然断交
******* C
都不要对方的电话号码
******* D
建立友谊尤其靠日积月累
****** 答案
D
***** 10
:PROPERTIES:
:ID: 73ced705-a59d-42fb-8a89-3f6c2721791e
:END:
****** 问题
******* 音频
accc8168-a760-4e01-8c68-687f7925e964.mp3
******* 转录
根据对话，什么情况下，我们会有惊喜？
****** 选择
******* A
看到朋友传上的照片
******* B
和朋友一块儿去旅游
******* C
发现和朋友住得很近
******* D
发现和朋友有共同的朋友
****** 答案
D
** 第三部分
*** 11-13
:PROPERTIES:
:ID: b74bc2ef-6948-4090-9b1b-4c7c2011c851
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
e590d77d-3e77-47ad-b544-3978c564a6e7.mp3
***** 转录
电脑和人脑尽管在传送信息方式上表现不同，但两者在诸多功能上非常类似。比如，电脑和人脑都可以存储记忆；电脑和人脑都可以通过修正，执行新的任务；电脑和人脑都有探知所处周围环境的能力，并据此做出反应，进行调整并适应所在的环境。
电脑与人脑的最大区别在于意识。尽管我们很难描述意识，但却知道它的存在。电脑没有意识，尽管它具有惊人的运算速度，但却无法体验情绪、梦想和思维，而情绪、梦想和思维却是我们之所以成为人类的必备元素。
是否会有“像人一样思考和行动”的机器出现呢？目前没有肯定的答案。不过，科学家对人脑和电脑的研究正在缩小它们之间的差距。
**** 题目
***** 11
:PROPERTIES:
:ID: ec2553e1-2e27-47a1-9e37-d5bd0c9651a5
:END:
****** 问题
******* 音频
9615a9a0-5574-467f-9336-94f95365e082.mp3
******* 转录
电脑与人脑的相似之处是什么？
****** 选择
******* A
适应所处的环境
******* B
追忆往事的能力
******* C
探知未知的潜能
******* D
改变环境的愿望
****** 答案
A
***** 12
:PROPERTIES:
:ID: bbf5b9a0-5037-4eb2-b417-4b6eef75473d
:END:
****** 问题
******* 音频
634ab482-7c07-4090-8204-8151bac981f1.mp3
******* 转录
电脑与人脑的最大区别是什么？
****** 选择
******* A
意识的有无
******* B
记忆存储的多少
******* C
计算速度的快慢
******* D
适应环境的快慢
****** 答案
A
***** 13
:PROPERTIES:
:ID: 7426ba0f-b71e-458a-9747-b10757c71cda
:END:
****** 问题
******* 音频
8f67bd81-caa2-4f71-a1ef-7d887eec561e.mp3
******* 转录
是否会有“像人一样思考和行动”的机器出现呢？
****** 选择
******* A
肯定会有
******* B
肯定不会有
******* C
目前没有肯定的答案
******* D
现在已经发明出来了
****** 答案
C
*** 14-17
:PROPERTIES:
:ID: 3ff14384-02b8-447d-a8a8-67fafcc3d3bb
:EXPORT-ID: 7304a4a2-efe6-4d8e-96dc-e419347c7a56
:END:
**** 课文
***** 音频
c2dadb2a-2b86-4615-9591-45691d0364bb.mp3
***** 转录
有人出门旅行或者到一个新城市工作抑或生活，都会选择通过网络寻找住房。通过网络寻找住房，不仅快捷方便，还有很多意想不到的惊喜。某租房平台最近就投入 500 万，启动了一项用户补贴行动。租房平台将以发放优惠券的形式，给租客报销未来 12 个月的房租，租客最高享受补贴可达 2400 元。同时还对房东承诺 24 小时闪电出租，并有大额房屋财产保险赠送。
租房平台创始人小王说：互联网租房行业并不需要纯信息服务的中介，事实上有超过一半的租房交易都是房东和房客直接接触完成的。对于租客，租房平台承诺提供全程随时联络，百分百个人房源。对于房东，租房平台提供的租客身份审查，按时缴纳房租都是最受欢迎的服务。
最快的租赁速度，最低的交易成本，最高的交易效率，更好的租房体验，更具品质的租住生活，快速与安全，这才是核心目标。而这一切的实现，都将得益于网络的发展。
**** 题目
***** 14
:PROPERTIES:
:ID: f3d6272b-e272-46b0-8999-e6bc2212c01b
:END:
****** 问题
******* 音频
69581087-13b6-4774-9743-e45457512886.mp3
******* 转录
根据本文，网络租房最大的好处是什么？
****** 选择
******* A
价格适中
******* B
快捷方便
******* C
有优惠券
******* D
有意外惊喜
****** 答案
B
***** 15
:PROPERTIES:
:ID: 3b0f29a5-247e-4734-8f7f-49becd1aad17
:END:
****** 问题
******* 音频
c04a2062-c6d6-4bda-8ddd-8dec20014465.mp3
******* 转录
根据本文，房东在某租房平台能得到什么惊喜？
****** 选择
******* A
房屋平台有保险相送
******* B
有机会中500万大奖
******* C
平台多给一年的房租
******* D
可享受国家给的补贴
****** 答案
A
***** 16
:PROPERTIES:
:ID: 164db657-2097-4440-bf08-1381ef4f9f0e
:END:
****** 问题
******* 音频
bbf20c71-55d0-47d6-b883-104fd847838e.mp3
******* 转录
对于房东，租房平台最受欢迎的服务是什么？
****** 选择
******* A
提供海量租房信息
******* B
保证百分百个人房源
******* C
为租住双方节省时间
******* D
确保租客身份的真实性
****** 答案
D
***** 17
:PROPERTIES:
:ID: ffb0cdbe-1897-4165-a983-901e436e9765
:END:
****** 问题
******* 音频
327adcfe-36e8-4852-9a22-5dd317008f66.mp3
******* 转录
关于网络租房的核心目标，下列哪项正确？
****** 选择
******* A
网上支付房租
******* B
等选出优质房源
******* C
为租赁双方保密
******* D
做到既快速又安全
****** 答案
D
* 阅读
** 第一部分
*** 18
**** 句子
***** A
每个人都把这些樱花树看是中日友好的象征。
***** B
与会代表还听取了第四届乒乓球赛筹备情况的报告。
***** C
我们要以最大的努力去落实政策，一直到问题解决为止。
***** D
他有时无意中买到一本喜欢的书，回家后简直爱不释手。
**** 答案
A
*** 19
**** 句子
***** A
他很不懂浪漫，对妻子连一句也没说体贴的话。
***** B
借口情况变化而全盘否定历史、抛弃传统，是错误的。
***** C
深夜，两名不法分子冒充公安人员将刘兵寄存的包骗走了。
***** D
一个年轻人饮酒后，仗着酒劲，竟公然在马路上持刀追逐行人。
**** 答案
A
*** 20
**** 句子
***** A
布尔顿当时在新奥尔良的乐师中有“国王”之称，由他组建的乐队很快就家喻户晓了。
***** B
那个人对记者说：“公主病了，因此今天不能开招待会了，等公主治好病才安排吧。”
***** C
这次的谈话，先生兴奋极了，虽然大部分是牢骚话，但他说得都极其风趣，使我们笑得合不拢嘴。
***** D
公司实行股份制后，原来的企业职工多数将成为股东，这对形成职工与企业命运共同体极为有利，同时便于企业吸收社会资金用于生产。
**** 答案
B
** 第二部分
*** 21
**** 段话
在网页游戏发展史中，不得不提“偷菜游戏”。偷菜游戏具有明显的游戏特点，[[gap]]互动互助，好友越多越有趣。每天用户只需要上线给自己或者帮好友的作物浇浇水、杀杀虫、除除草、收收果实[[gap]]，如果有损友来玩家农场里使坏或者盗取果实，农场的狗也可以抓住他。该游戏不仅可以[[gap]]用户上线的积极性，还可以促使用户发起与站内好友的互动。
**** 选择
***** A
****** 1
追求
****** 2
即时
****** 3
发动
***** B
****** 1
希望
****** 2
即便
****** 3
变动
***** C
****** 1
注意
****** 2
就可
****** 3
调节
***** D
****** 1
讲究
****** 2
即可
****** 3
调动
**** 答案
D
*** 22
**** 段话
人们在大规模数据的基础上可以做到的事情，在小规模数据的基础上是无法完成的。全球新产生数据年增40％，即信息总量每两年就可以翻番，而且这一趋势还在[[gap]]。[[gap]]能够更有效地组织和使用大数据，人类将得到更多的机会[[gap]]数据对社奂发展的巨大推动作用。研究证明，通过大数据和幂律分布分析，人类行为93％是可以[[gap]]的，成为“已经发生的未来”。
**** 选择
***** A
****** 1
加速
****** 2
倘若
****** 3
发挥
****** 4
预测
***** B
****** 1
加大
****** 2
若干
****** 3
产生
****** 4
预报
***** C
****** 1
加深
****** 2
假若
****** 3
发展
****** 4
测算
***** D
****** 1
加多
****** 2
若非
****** 3
发生
****** 4
估计
**** 答案
A
*** 23
**** 段话
近些年，全球兴起金融[[gap]]，在中国，移动金融、投资和贷款似乎成了主流。在手机客户端的帮助下，邛宇〕裹广个4尘j着B亿人口和78万亿夫元的巾场里，[[gap]]科技公司正在向银行等传统机构发起[[gap]]。迄今为止，在中国注册手机银行业务的有3.9亿人，这超过了美国总人口，[[gap]]全球手机银行客户的40％。
**** 选择
***** A
****** 1
创先
****** 2
广大
****** 3
攻击
****** 4
位
***** B
****** 1
创新
****** 2
众多
****** 3
挑战
****** 4
占
***** C
****** 1
创造
****** 2
多数
****** 3
战斗
****** 4
居
***** D
****** 1
开创
****** 2
当众
****** 3
斗争
****** 4
有
**** 答案
B
** 第三部分
*** 段话
“忽如一夜春风来，干树万树梨花开”，似乎在一夜之间，[[gap:24]]。在《环球科学》杂志2013年评选出的2012年最值得铭记、对人类社会产生影响最为深远的十大新闻中，“3D打印”位列第九，[[gap:25]]。
与此同时，3D打印技术在全球的推广也正在以惊人的速度增长。房子、′罡王d义革圭手枪、骨骸…。。。[[gap:26]]，将原本难以实现的设想一一转化成现实。全球3D打印机制造门去之-的美国3DSystems公司负责全球市场3性肖的副茵裁凯西刘易斯曾自信满满地说：“有了3D打印，一切不再复杂，3D打印机儿乎可以创造任何东西。”
在企业、科研机构和媒体的互动下，3D打印的未来似乎一片光明，甚至频频被提到或将带来“第三次工业革命”的高度。[[gap:27]]？
其实，3D打印胡后的技术并不新鲜，早在一二十年前，[[gap:28]]。为何在出现多年后才突然燃起3D打印的关注热潮？3D打印正在改变什么，未来还能改变什么？仅仅是一次概念热潮，还是真的将带来一场生产方式变革？我们拭目以待
*** 选择
**** A
3D打印成了每个科技媒体乃至大众、时尚媒体争相报道的热门话题
**** B
它就开始以“快速成型技术“这一名称应用于汽车、航空航天模型设计中
**** C
3D打印已经被运用到各个行业中
**** D
理由是“3D打印将在制造业和科研领域引发一场革命“
**** E
3D打印真的会给制造业带来革命性的变化吗
*** 答案
**** 24
A
**** 25
D
**** 26
C
**** 27
E
**** 28
B
** 第四部分
*** 29-32
**** 段话
你是不是一直梦想着有另一个自己一一双胞胎机器人，在赖床的时候，可以派它去上学？日本的机器人技术专家石黑浩-直在做这方面的研究。他制造了很多机器人，其中就有一个“他自己”。
这位与石黑浩有着相同面孔的中年“男士”，坦白地说是由樵胶、气压装置、电子元件构成的，不过这位“男士”有一个身体组成成分和石黑浩相同，就是头发，这是从他本人头皮上取得的。机器人因为是固定的，所以还不能走出实验室去买东西，不过，它已经能够初步完成一些任务，就是模仿一个人。
石黑浩坐在计算机前，远程控制他的机器人，一个麦克风用来捕捉他的声音，一台摄像机跟踪他的脸部和头部运动。当石黑浩说话时，机器人也跟着他做一样的动作。它也会胥眼、抽动，表现得像是在呼吸。不过，人类的一些行为也被刻意地抑制了。当石黑浩点起一根香烟时，机器人就不会继续模仿。石黑浩认为机器双胞胎是他的好助手。“我研究的问题是了解什么是人，我使用非常像人类的机器人来测试我的假设，比如人性、智能和行为。”他的研究领域是人机互动。
**** 题目
***** 29
****** 问题
石黑浩是什么方面的专家？
****** 选择
******* A
双胞胎医学专家
******* B
机器人技术专家
******* C
远程控制技术专家
******* D
机器人模仿行为专家
****** 答案
B
***** 30
****** 问题
“机器人石黑浩”郧一部分跟石黑浩本人相同？
****** 选择
******* A
皮肤
******* B
头发
******* C
衣着
******* D
思想
****** 答案
B
***** 31
****** 问题
机器人会模仿石黑浩的什么动作？
****** 选择
******* A
出去买东西
******* B
走路、说话
******* C
胜眼、抽动
******* D
点起一根烟
****** 答案
C
***** 32
****** 问题
石黑浩希望利用机器人：
****** 选择
******* A
捕提外界的声音
******* B
分析人体的运动
******* C
测试自己的假设
******* D
代替自己做研究
****** 答案
C
*** 33-36
**** 段话
近年来，在广阑的网络文化里，一批新兴网媒迅速崛起，成为新媒体的亮点。不仅如此，在网络社交发展的基础上，新型专业社交网站不断涌现，去年社交网站用户和访问量激增，吸引了诸多商业巨头纷纷进军社交网站。
有专家指出：“随着互联网的社交功能日益发展，诸多网络应用已经成为人们进行交往的主要渠道，网络社交用户经过多年积累已成相当规模，这是社交网络热的必然条件。
社会学家则认为：“通过社交网站，商业公司不但可以收集手机号、用户账号等普通信息，还可以通过分析网民发布的博客、帖子、同学群体等，推测出用户的消费倾向（节俭还是奋侈）、个人婚娩情况（单身还是离婚）、工作情况（是否有跳槽的意向）等十分隐私的信息。社交网站的诸多争议吸引了大众的眼球，其新奇的社交功能吸引着用户，其病毒式的营销手段以及恶意韶争令人惊诧，甚至让人心生恐惧。”
新媒体是把“双刃剑”，它在促进国家经济社会等方面发展的同时，习给经济、政治、文化、社会发展和国家安全、军事安全等诸方面带来严重甚至严峻的挑战。从一定意义上讲，谁掌握新媒体，谁就将掌控世界。面对这些严峻挑战，我们不能等闲视之。
**** 题目
***** 33
****** 问题
关于近年的网络发展，下列睇项正确？
****** 选择
******* A
网络自媒体如一后春笋
******* B
社交网站用户大量增加
******* C
网上购物已经蔚然成风
******* D
独特的网络文化已然形成
****** 答案
B
***** 34
****** 问题
对于网络发展，专家的观点是：
****** 选择
******* A
“社交网络热”不会持仁
******* B
互联网的社交功能仍有待发展
******* C
网络是现今人们进行交往的主要途径
******* D
网络已无法承载日益增加的网络社交用户
****** 答案
C
***** 35
****** 问题
对于网络发展现状，社会学家认为：
****** 选择
******* A
手机号成了收藏品
******* B
个人隐私易被泄露
******* C
网络病毒为害不浅
******* D
人们对网络爱恨交加
****** 答案
B
***** 36
****** 问题
最后一段中“新媒体是把”双刃剑「“是指新媒体：
****** 选择
******* A
有利有弊
******* B
祸不单行
******* C
在快速发展
******* D
在挑战传统
****** 答案
A
