* 课文
** 转录
互联网走进我们的生活没有多久，却让我们实实在在地感受到生活正发生着日新月异的变化：它能让我们自如地通话、视频、传递消息，哪怕你在天涯海角；它使我们的生活不再单调沉闷，每一天都变得浪漫、丰富和充实；它将异地购物、交易变为了可能——我们足不出户就能任意挑选欧洲、美洲的商品；我们可以在网上学习，自由而不失乐趣；我们可以在网上找工作，简单叉高效；我们能设立个人网站，既能扩大你的朋友圈，又能让你小小的虚荣心得到满足，如果愿意，还可以设立你亲友的网站，作为赠送给他们的珍贵礼物。最近又有人通过网络，和朋友、朋友的朋友合伙筹备资金买房，人们视这一创举为互联网金融下的新成员。
据集资买房项目发起人介绍，此次众筹买房，初步打算召集 200 人，筹备建立众筹家园小区。众筹购房的好处在于价格上拥有明显优势，比市场价至少便宜30％，无论是投资还是自住，都很合算。项目沟通中，微信是主要渠道，申请人递交申请表、通过审查后，缴纳 100 元订金就可以进入购房微信群，项目的设计、户型、价格等，全部由大家商议决定。
大家深知买房对每个家庭都不是小事，众筹买房也还处于摸索阶段，因此必须慎重。众筹的参与者，都是发起人的朋友，或者朋友的朋友。他们层次较高，都有一定的经济基础，对新生事物有强烈好奇心，基本属于同一阶层。用发起人的话说，众筹不是在筹房子，而是在凝聚人心。房子怎么设计、对国家的政策怎么理解、失败了怎么办？大家每天在微信群你来我往，忙碌而欢乐，除了严肃的房价，这种共商大事的感觉也很让人上瘾。
什么是“众筹”？说白了，就是大家筹钱干一件事，上文所说的“众筹”更像是“集资建房”，广义的“众筹”则是互联网金融的产物，指创业者通过网络，向众多素不相识的人争取资金支持。
世界上第一个让初创公司梦想成真的众筹网站是美国的 Kickstarter。2011 年5 月，中国国内首家众筹网站——点名时间，将 Kickstarter 的模式搬进了中国，之后众筹平台越来越多。如今，从慈善到图书出版，从电影制作到创业项目，众筹几乎跨越了所有的领域。
美微传媒 CEOU 朱江做梦也没想到，他成了传说中的“中国众筹第一人”。那年，朱江开始在淘宝网出售美微会员卡，购买会员卡就是购买公司的原始股票，每股 1.2 元，最低认购 100 股，也就是说，花 120 元就可以成为持有美微股份的股东。朱江回忆起当时钞票源源不断流进来的感觉，真的有种苦尽甘来的味道。时至今日，众筹项目有成功的，也有处境尴尬的，而国内第一家众筹网站“点名时间”三年以后却抛弃了“众筹”，改营其他 o 坦白地讲，国内用户与国外有很大区别，比如，Kickstarter 上聚集着一群理想主义者，他们心中充满向往，购买时感性因素超越了理性。国内用户则希望尽快得到回报，甚至有些急功近利，而用户的心态很大程度上决定了项目成功的可能性。再比如，国内用户对收获时间和产品质量要求较高，如果认为产品不符合预期，或是项目进展比计划的慢，就会发牢骚，有怨气。另外，大部分投资者对众筹还是持观望态度。因此，这今为止众筹在国内还是一个看起来很美、做起来吃力的事情。
是啊，在互联网变得家喻户晓，给我们的生活带来许许多多的方便和乐趣的同时，也给我们增添了无穷无尽的烦恼，众筹平台上有，其他领域也有。据官方报道，尚未查明身份的罪犯盗窃了 1800 万个电子邮件账户及其密码；仅有两三个人的皮包公司公然冒充国家部门开设了一家假网站，大肆进行诈骗，如今已被警方依法刑事拘留；还有时时活跃着的网络黑客。每次类似这些败坏互联网名誉的事件一经曝光，就会使我们有触目惊心之感。
这就是互联网时代，在我们对它爱不释手的同时，也不免对它心存担忧。
