* 扩展
** 词语
*** 1
**** 话题
旅游
**** 词语
***** 1
名胜古迹
***** 2
风景
***** 3
展览
***** 4
合影
***** 5
预订
***** 6
结账
***** 7
团
***** 8
时差
*** 2
**** 话题
节日
**** 词语
***** 1
国庆节
***** 2
元旦
***** 3
除夕
** 题目
*** 1
**** 句子
我们还是先[[gap]]好宾馆吧，到了那儿再找比较麻烦。
**** 答案
***** 组
1
***** 词语
5
*** 2
**** 句子
你好，我要退房，现在可以[[gap]]吗？
**** 答案
***** 组
1
***** 词语
6
*** 3
**** 句子
我昨天刚从英国回来，[[gap]]还没倒过来。
**** 答案
***** 组
1
***** 词语
8
*** 4
**** 句子
在北京留学的这一年，这里的各大[[gap]]我都看遍了。
**** 答案
***** 组
1
***** 词语
1
* 练习

** 1
:PROPERTIES:
:ID: 733bec0d-178f-4ec7-9616-ac3f577c0353
:END:
*** 选择
**** 1
赶紧
**** 2
无奈
**** 3
制造
**** 4
果然
**** 5
伤害
**** 6
此外
*** 题目
**** 1
***** 句子填空
还真让你说对了，他[[gap]]还不知道这件事。
***** 答案
4
**** 2
***** 句子填空
两岁的果果是我们家最能[[gap]]麻烦的人。
***** 答案
3
**** 3
***** 句子填空
姑娘脸上表现出很[[gap]]的样子。
***** 答案
2
**** 4
***** 句子填空
他喜欢音乐、电影、运动，[[gap]]还喜欢旅行。
***** 答案
6
**** 5
***** 句子填空
不用送了，[[gap]]回去吧，家里还有别的客人呢。
***** 答案
1
**** 6
***** 句子填空
经常熬夜对身体的[[gap]]极大。
***** 答案
5
** 3
:PROPERTIES:
:NOTETYPE: 4f66e183-906c-4e83-a877-1d9a4ba39b65
:END:
*** 1
**** 句子
你的担心不是[[A]]没有[[B]]道理的，今天李阳[[C]]没有[[D]]通过面试。
**** 词语
果然
**** 答案
C
*** 2
**** 句子
[[A]]学院[[B]]所有的[[C]]老师同学都在议论[[D]]这件事。
**** 词语
整个
**** 答案
A
*** 3
**** 句子
[[A]]路上的人[[B]]他着急，拉住[[C]]他的马，阻止[[D]]他说：“方向错了。”
**** 词语
替
**** 答案
B
*** 4
**** 句子
忽然，他[[A]]看见小木屋的方向[[B]]升起了黑烟，[[C]]他[[D]]跑过去看。
**** 词语
急忙
**** 答案
D

** 2
*** 1
:PROPERTIES:
:ID: 7b0ed97e-75c6-4799-9828-b963d4312709
:END:
**** 句子填空
人的思想感情是非常丰富的，有些是无法用语言准确[[gap]]的。
**** 选择
***** A
表示
***** B
表达
**** 答案
B
*** 2
:PROPERTIES:
:ID: 6147a02d-5249-41c8-80b5-0049fe6d914a
:END:
**** 句子填空
你[[gap]]给他回个电话，他好像有什么急事找你。
**** 选择
***** A
急忙
***** B
赶紧
**** 答案
B
*** 3
:PROPERTIES:
:ID: 1bb215f9-d18b-4774-8019-c16e1e2fb49e
:END:
**** 句子填空
今天是不可能了，你[[gap]]安排一个时间见面吧。
**** 选择
***** A
此外
***** B
另外
**** 答案
B
*** 4
:PROPERTIES:
:ID: 1cd5a0a1-fe83-4f93-bec7-2dd9d2dff87c
:END:
**** 句子填空
胆星（míngxīng，star）的影响力[[gap]]不一般。
**** 选择
***** A
果然
***** B
居然
**** 答案
A
* 注释
** （三）词语辨析
*** 打听——询问
**** 做一做
***** 1
****** 句子
A：打扰一下，向您[[gap]]件事。你知道王老板有什么兴趣爱好吗？
B：他最大的爱好就是去各地旅游了，平时也喜欢看看书、看看电影什么的。
****** 答案
******* 1
******** 打听
1
******** 询问
0
***** 2
****** 句子
她[[gap]]到北京有位医生能治这个病，就带着孩子来了。
****** 答案
******* 1
******** 打听
1
******** 询问
0
***** 3
****** 句子
我[[gap]]了一下，附近像这样的房子，差不多都得一百万。
****** 答案
******* 1
******** 打听
1
******** 询问
0
***** 4
****** 句子
我[[gap]]了几个修过机器的顾客，他们对小刘的服务都很满意。
****** 答案
******* 1
******** 打听
0
******** 询问
1
* 课文
** 转录
在中国，人们把农历十二月三十日这一年中的最后一天叫作除夕，这一天，全家人会一起吃年夜饭，守岁。但是，人们为什么要把年三十叫作除夕呢？
传说在很久以前，有个叫作“夕”的怪物，经常出来伤害百姓，百姓对其恨之入骨，但是又十分无奈。当时有个英雄叫作七郎，他英俊高大、力大无比。七郎还有一条狗，这条狗非常勇敢，无论咬住什么都不会松口。
一天，七郎从外边回来，看到邻居家女孩的外公坐在路边哭，于是上前询问，一问才知道，原来天真可爱的女孩被“夕”吃掉了。七郎暗暗下定决心一定要杀死“夕”，替百姓除掉这个制造灾害的东西。于是七郎带着他的狗出发了，他到处打听“夕”的消息，但是一直找不到它。
这样过了差不多一年，这天正好是大年三十，七郎来到了一个热闹的城镇。这一年来，七郎虽然没有找到“夕”，但是了解到了很多关于“夕”的情况：它一般在太阳落山后出来害人，到天亮前又会逃得连影子都找不着了；此外，它还特别害怕声响。于是七郎告诉这里的百姓，“夕”说不定晚上要出来伤害大家，让大家今晚熬夜等着，一见到“夕”就赶紧敲打东西，大家一起把“夕”杀掉。
太阳很快落山了，到了晚上，夕“果然出来了。它想吃一户人家的姑娘，被这家人发现了，于是他们立刻敲响了家中的锅和盆子，跟着整个镇子都响了起来。”夕“吓得什么似的，急忙往外逃。七郎的狗追上了”夕“，并死死地咬住了它。七郎跑上前去，一箭射死了”夕“。
除掉“夕”以后，百姓纷纷对七郎表达谢意。由于这一天很有意义，于是人们就在每年的年三十这天晚上，仍然像那天一样整晚不睡觉，敲打出响声。就这样一代代传下来，形成了除夕夜守岁、放鞭炮的风俗。
